### ISSUE TITLE
最近发现配置更新推送机制失效了，没有异常日志，只有5分钟一次的拉取机制

### ISSUE THREAD

**Issue by LittleShrimp1987** [ctripcorp/apollo#1000]
最近发现配置更新推送机制失效了，没有异常日志，只有5分钟一次的拉取机制，有碰到类似问题的吗？

**Comment by lepdou** [comment]
你找一下客户端的日志，应该是有日志的。Warning级别的也看一下，估计是长连接有问题。

**Comment by nobodyiam** [comment]
@LittleShrimp1987 之前在群里提这个问题的也是你吧，看群里的聊天记录应该解决了？

> 我的问题解决了，是我自己加一个spring mvc filter的时候，把http long polling那种异步请求结果DeferredResult 的response body给覆盖为空了，去掉这个filter就好了

**Comment by LittleShrimp1987** [comment]
我自己的问题，解决了。
