### ISSUE TITLE
新建环境

### ISSUE THREAD

**Issue by sunguangran** [ctripcorp/apollo#1006]
请问在管理后台可以新建环境吗，没找到入口

**Comment by nobodyiam** [comment]
请参考[部署&开发遇到的常见问题#4-portal如何增加环境](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#4-portal%E5%A6%82%E4%BD%95%E5%A2%9E%E5%8A%A0%E7%8E%AF%E5%A2%83)

**Comment by sunguangran** [comment]
好的，谢谢
