### ISSUE TITLE
pollNotification 执行时间过长问题	 	

### ISSUE THREAD

**Issue by shaojie19801002** [ctripcorp/apollo#1008]
请问 pollNotification是做什么用的，我们用cat监控盈盈发现，会调用http://172.19.1.152:8080/notifications/v2? 接口，每次调用时间会长到30s-40s，这是正常情况么？
有优化的可能吗

**Comment by lepdou** [comment]
这个接口是Http Long Polling，客户端向服务端发起的连接，用来监听配置发布的。30S会断开重连一次，详细内容可参考[Apollo实时通知实现原理](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1#211-%E5%8F%91%E9%80%81releasemessage%E7%9A%84%E5%AE%9E%E7%8E%B0%E6%96%B9%E5%BC%8F)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
