### ISSUE TITLE
apollo配置中心的k-v能否传入变量呢

### ISSUE THREAD

**Issue by lic987** [ctripcorp/apollo#1009]
您好，
请问如果我很多主机使用一个namespace，但这中需要一个变量，比如主机名key为hostname或者其他因为服务器或集群不同而不同的value，这样的话如何实现呢，还是说namespace里面只能是固定的值

**Comment by lepdou** [comment]
namespace里面的值是固定的。
但是你这个场景，可以有几种实现方式，假设有一个配置项叫：timeout。然后你的应用有三台机器名称分别为MA、MB、MC。
实现方式：在一个namespace里面配置三个配置项例如：
MA-timeout = 1000
MB-timeout = 1500
MC-timeout = 2000
在客户端获取timeout这个值的时候，key是应用根据当前的机器拼接出来的。比如在MA应用里就获取MA-timeout这个配置项。
这样就能实现你的需求了。

**Comment by nobodyiam** [comment]
通过@EnableApolloConfig引入的话，namespace是常量，通过ConfigService.getConfig引入的话，namespace可以是变量

另外，@lepdou提到的是思路也可以参考一下

**Comment by lic987** [comment]
谢谢，请问namespace是变量的话，在我们的portal端的web页面应该怎么配置呢 有没有什么例子。。。谢谢 @nobodyiam

**Comment by lic987** [comment]
有没有什么通过ConfigService.getConfig(someNamespace)引入的代码例子可以参考下嘛

**Comment by nobodyiam** [comment]
@lic987 我理解错你的意思了，你要的是key是动态的，而不是namespace名字是动态，那么就按照 @lepdou 的思路做就是了。

**Comment by lic987** [comment]
好的，谢谢
