### ISSUE TITLE
如何捕获配置修改（非发布）的信息

### ISSUE THREAD

**Issue by reignsr** [ctripcorp/apollo#1010]
看到ConfigPublishListener.java类监听了配置发布事件，类似的，想监听到修改配置的相关信息，比如什么时间，谁修改的配置，请问如何能捕获到？

**Comment by lepdou** [comment]
可以通过OpenAPI获取，但是没有通知的功能，只有Get的接口。
可参考[Apollo开放平台](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0)

**Comment by reignsr** [comment]
官方代码中后续是否会考虑提供配置修改的listener？以便于配置修改时即时捕获相关信息。
