### ISSUE TITLE
uat 和prod部署在同一台主机的不同jvm进程中，portal打开后看不见uat环境

### ISSUE THREAD

**Issue by zysong92** [ctripcorp/apollo#1017]
我们uat 和prod 的adminservice 和configservice都部署在同一台主机上，用了不同的端口，进入portal能看见prod的环境，没看见uat的环境。求帮忙分析下。

**Comment by nobodyiam** [comment]
portal有环境检测的功能，如果发现某个环境不可用，就会在界面上隐藏该环境的入口。看下portal日志吧

**Comment by zysong92** [comment]
解决了。谢谢
