### ISSUE TITLE
Apollo配置中心的UI界面是否可以支持中英文切换？

### ISSUE THREAD

**Issue by ljywit** [ctripcorp/apollo#1018]
最近想用Apollo配置参数，发现配置界面只有中文，导致不能把它作为产品的一部分融合进来。

请问Apollo有这方面的计划吗？界面显示支持国际化的多语言，可以先只用实现中文+英文？谢谢

**Comment by nobodyiam** [comment]
恩，之前由于主要是公司内使用，考虑到维护成本，所以是直接用了中文。

国际化的话，可能得调研一下，不知道你对angular这块的多语言是否有研究？

**Comment by ljywit** [comment]
很高兴该问题得到您的关注，目前我对angular这块不太熟悉，我个人认为界面的中英文主要包括：界面文字、图片、后台抛出的异常信息等。

**Comment by nobodyiam** [comment]
#2370

**Comment by czd890** [comment]
现在也有这个需求，公司有老外... 中文页面看不懂。但是配置中心里面apollo是比较好用的。很纠结

**Comment by nobodyiam** [comment]
你们公司是否有前端资源能支持一下？对前端同学来说支持一下国际化应该是挺简单的

**Comment by czd890** [comment]
有单独的一个angular工程吗?

**Comment by JaredTan95** [comment]
> 有单独的一个angular工程吗? @nobodyiam

在工程apollo-portal/resources下面呢。

**Comment by czd890** [comment]
我的意思是，单独的angular应用（工程文件等），不是和java web混在一起的，这样前端童鞋好开发一些

**Comment by JaredTan95** [comment]
> 我的意思是，单独的angular应用（工程文件等），不是和java web混在一起的，这样前端童鞋好开发一些

没有哦

**Comment by czd890** [comment]
@nobodyiam @JaredTan95 麻烦看一看：https://github.com/ctripcorp/apollo/pull/2452 的实现方案可不可行。

**Comment by nobodyiam** [comment]
#2452 已经随着apollo 1.5.1版本release，增加了英文界面

**Comment by LOUISXUSEN** [comment]
1.6.1版本中没有中英文切换，请问是需要配置还是bug
![image](https://user-images.githubusercontent.com/23613668/81290024-ea171a00-9099-11ea-8e6f-5917220737a3.png)

**Comment by nobodyiam** [comment]
@LOUISXUSEN 清一下缓存试试
