### ISSUE TITLE
能不能提供一个可以直接虚拟机运行的镜像，配了两天都跑不起来！

### ISSUE THREAD

**Issue by ch19751116** [ctripcorp/apollo#1021]
docker还是有一定门槛，很多问题不好解决！

**Comment by sunguangran** [comment]
你是要quickstart的还是分布式docker部署方案？

**Comment by ch19751116** [comment]
提供个quickstart的linux镜像吧，花了好多事件，就是配不起来！

**Comment by ch19751116** [comment]
或者提供一个quickstart带数据库的的docker版本。先跑起来再慢慢研究，降低点入门门槛

**Comment by nobodyiam** [comment]
直接参考 [Docker方式部署Quick Start](https://github.com/ctripcorp/apollo/wiki/Apollo-Quick-Start-Docker%E9%83%A8%E7%BD%B2) 这个就可以快速的跑起来的。

如果是为了先跑起来再研究的话，建议直接通过IDE在开发机启动，这个应该更简单一些，可以参考 [Apollo开发指南](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
