### ISSUE TITLE
配置文件apollo-env.properties应该放在哪个目录才能正常运行apollo-demo下的SimpleApolloConfigDemo呢？

### ISSUE THREAD

**Issue by lijasonvip** [ctripcorp/apollo#1022]
1. Apollo 服务端已经用docker-compose运行正常，端口8080
2. Demo的env已经使用`System.setProperties`设置为`DEV`
3. dev_meta 写到了`apollo-env.properties`文件，这个文件该放到哪个目录呢（resources下所有目录都已经试过了）
（其他配置如appid, namespace均配置ok）

Debug到MetaDomainConsts下`ResourceUtils.readConfigFile("apollo-env.properties", prop);`抛出异常NPE

**Comment by nieguhua** [comment]
就放在resources目录下就可以了啊

**Comment by lijasonvip** [comment]
@nieguhua 感谢回复。您帮忙看看我的配置是否正确
1. `META-INF/app.properties` 下配置`app.id`
2. `resources`下`application.yml`配置`namespace`
3. `resources`下`apollo-env.properties`配置`dev_meta=http://192.168.100.7:8080`
4. `main`函数启动时注入参数`env=DEV`

这样配全了吗？可否推一份全部使用配置文件配置的demo到仓库我拉下来参考一下，非常感谢。

另外配置中心就是解决配置项带来的各种麻烦，apollo启动依赖多个文件的方式比较繁琐。
不知道放到一个文件里是不是更好（包括c:/ 和 /opt/目录下的配置方法）

**Comment by nobodyiam** [comment]
app.id信息是应用的信息，对一个应用而言是不会变的，所以放在META-INF/app.properties下面

env信息是机器的属性，不是应用的属性，所以是放在机器上的server.properties或者是通过-D传入

meta server信息是apollo-core.jar的配置属性，我们建议是直接打进包里，这样使用方使用的时候就不需要做额外配置了。apollo-env.properties也支持外置化，不过配置内容是`dev.meta=xxx`

namespace是代码的一部分，这个就看你怎么弄了，写死在代码中也可以，放在application.yml中也可以

**Comment by lijasonvip** [comment]
感谢 @nobodyiam ，在设计的时候用心良苦啊！
