### ISSUE TITLE
Apollo配置修改实时生效（热发布）机制实现方式

### ISSUE THREAD

**Issue by lijasonvip** [ctripcorp/apollo#1023]
apollo-client 代码中使用`Executors.newScheduledThreadPool` 周期性的执行`tryUpdateConfigServices`操作，apollo配置修改实时生效机制是依赖这种客户端主动查询方式实现的吗？有服务端主动推送到客户端的实现吗？有的话怎么使用？

**Comment by nieguhua** [comment]
看他文档好像是没有

**Comment by nobodyiam** [comment]
请参考 [2.1.2 Config Service通知客户端的实现方式](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1#212-config-service%E9%80%9A%E7%9F%A5%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%9A%84%E5%AE%9E%E7%8E%B0%E6%96%B9%E5%BC%8F)

**Comment by lijasonvip** [comment]
感谢 @nobodyiam ，解决了我的问题！
