### ISSUE TITLE
开源项目ServiceComb支持了apollo作为配置中心，并在oschina发了一篇宣传博客

### ISSUE THREAD

**Issue by lijasonvip** [ctripcorp/apollo#1025]
@nobodyiam 

原文地址 https://my.oschina.net/u/3823482/blog/1786716
项目文档 http://servicecomb.incubator.apache.org/cn/users/dynamic-config/

文中以引用的方式引用了apollo项目中部分内容。

目前对接方式还是通过REST接口实现定时拉取配置，使用apollo提供的Java客户端实现实时下发功能正在做。

**Comment by lepdou** [comment]
赞~博客写的很专业

**Comment by yiming187** [comment]
+1
