### ISSUE TITLE
同一个web容器下 多个工程  client配置读取错乱

### ISSUE THREAD

**Issue by cjd276** [ctripcorp/apollo#1026]
同一个web容器下 多个工程  client配置读取错乱，举个列子，一个tomcat下面两个web工程，各自读取各自appid 下的配置的时候，配置读取会乱，如何解决啊

**Comment by nobodyiam** [comment]
没明白，tomcat下面部署多个web app的话，各自都是独立的，为啥会乱呢？

**Comment by cjd276** [comment]
目前我这边两个工程分开两个tomcat，配置读取都正常，在一个tomcat部署，如果namespace里面的key有重复的就会覆盖




发自网易邮箱大师
在2018年03月29日 21:23，Jason Song 写道：

没明白，tomcat下面部署多个web app的话，各自都是独立的，为啥会乱呢？

**Comment by nobodyiam** [comment]
能否提供一个重现的demo？

**Comment by cjd276** [comment]
问题出现的前提条件：
1. env 设置为local （让applo 读取本地缓存配置）
2. 两个工程部署再同一个tomcat（配置是分开的，appid是不一样的）
3. 两个工程里面本地的缓存配置文件里面的配置项key 有一样的
现象：
分开两个tomcat 两个工程  一切正常，再同一个tomcat 下面 key 一样的配置出现覆盖的情况

**Comment by nobodyiam** [comment]
配置是按照appId+cluster+namespace区分的，不会出现串的可能。

另外，我也写了个demo，照着你的描述跑了一遍，也是OK的。
[test-apollo.zip](https://github.com/ctripcorp/apollo/files/1866367/test-apollo.zip)

如果你那里确实有这个问题的话，建议debug一下，看看是哪里的配置导致取到的配置是同一份了。

**Comment by cjd276** [comment]
谢谢 我自己这边也是百思不解，理论是不会出现这情况的 谢谢老铁




发自网易邮箱大师
在2018年04月01日 21:09，Jason Song 写道：

配置是按照appId+cluster+namespace区分的，不会出现串的可能。

另外，我也写了个demo，照着你的描述跑了一遍，也是OK的。
test-apollo.zip

如果你那里确实有这个问题的话，建议debug一下，看看是哪里的配置导致取到的配置是同一份了。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
