### ISSUE TITLE
初始化脚本在mysql5.7.21版本上运行错误

### ISSUE THREAD

**Issue by RickJou** [ctripcorp/apollo#1027]
[apolloconfigdb脚本地址](https://github.com/ctripcorp/apollo/blob/master/scripts/sql/apolloconfigdb.sql)

### 出问题的sql语句
>INSERT INTO `ServerConfig` (`Key`, `Cluster`, `Value`, `Comment`)
VALUES
    ('eureka.service.url', 'default', 'http://localhost:8080/eureka/', 'Eureka服务Url，多个service以英文逗号分隔'),
    ('namespace.lock.switch', 'default', 'false', '一次发布只能有一个人修改开关'),
    **('item.key.length.limit', 'default', '128', 'item key 最大长度限制');**
    ('item.value.length.limit', 'default', '20000', 'item value最大长度限制'),
    ('config-service.cache.enabled', 'default', 'false', 'ConfigService是否开启缓存，开启后能提高性能，但是会增大内存消耗！'),

### 修改后正常运行的语句
>INSERT INTO `ServerConfig` (`Key`, `Cluster`, `Value`, `Comment`)
VALUES
    ('eureka.service.url', 'default', 'http://localhost:8080/eureka/', 'Eureka服务Url，多个service以英文逗号分隔'),
    ('namespace.lock.switch', 'default', 'false', '一次发布只能有一个人修改开关'),
    **('item.key.length.limit', 'default', '128', 'item key 最大长度限制'),**
    ('item.value.length.limit', 'default', '20000', 'item value最大长度限制'),
    **('config-service.cache.enabled', 'default', 'false', 'ConfigService是否开启缓存，开启后能提高性能，但是会增大内存消耗！');**

### 错误原因  
('item.key.length.limit', 'default', '128', 'item key 最大长度限制');   
最后使用的是分号,其后面的语句部分无法正确识别,将分号改为逗号,在最后一行以分号结尾.

**Comment by nobodyiam** [comment]
非常感谢，发布前临时调了一下顺序，疏忽了。

**Comment by nobodyiam** [comment]
已经在[0.10.2](https://github.com/ctripcorp/apollo/releases/tag/v0.10.2)修复，非常感谢！

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
