### ISSUE TITLE
long polling url变成了内网ip

### ISSUE THREAD

**Issue by chuckie-xch** [ctripcorp/apollo#1030]
设置meta server url,dev_meta中的url是服务器的外网ip，但是客户端日志输出polling url变成了内网ip，导致polling failed，这是为什么呢

**Comment by nobodyiam** [comment]
1. config service/admin service注册到eureka的IP地址是内网
2. 客户端通过meta server（外网）拿到了config service的地址列表

具体可以参考下面的设计图：
![overall-architecture](https://github.com/ctripcorp/apollo/raw/master/doc/images/overall-architecture.png)

不建议把config service暴露到外网，如果实在要这么做的话，可以参考[1.4、网络策略](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97)调整注册到eureka的IP地址

**Comment by chuckie-xch** [comment]
ok了，thanks

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
