### ISSUE TITLE
long polling url地址问题

### ISSUE THREAD

**Issue by sunguangran** [ctripcorp/apollo#1031]
请问如果使用long polling url  API方式获取配置变更信息，API中传入的config service url 是eureka的地址还是configservice的真实地址？

如果未eureka地址，name当eureka有多个节点时怎么配置呢

**Comment by nobodyiam** [comment]
客户端首先调用meta server的接口获取到config service的列表，后续就直接通过IP+PORT访问了。

具体可以参考下[Apollo配置中心设计](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1)
