### ISSUE TITLE
spring `ConfigurationProperties`方式 apollo 中的配置可以覆盖本地application.yml的配置吗

### ISSUE THREAD

**Issue by mhcxp** [ctripcorp/apollo#1034]
测试发现application.yml中如果有`test.key1`, `ConfigurationProperties`读取不到apollo namespace中`test.key1`的配置; 删除application.yml中`test.key1`则可以

**Comment by mhcxp** [comment]
已看`ApolloApplicationContextInitializer`源码
```
environment.getPropertySources().addFirst(composite);
```
为什么没生效呢?

**Comment by mhcxp** [comment]
发现问题了

`YamlPropertySourceLoader`也会执行 propertySources.addFirst, 而且在ApolloApplicationContextInitializer之后

**Comment by nobodyiam** [comment]
我本地试了一下，在`application.yml`中加入了配置，貌似没有遇到你的问题，因为在我这里`YamlPropertySourceLoader`早于`ApolloApplicationContextInitializer`执行。

你能精简一个可重现问题的demo吗？

**Comment by mhcxp** [comment]
@nobodyiam 

[apollo-issue-demo.zip](https://github.com/ctripcorp/apollo/files/1874127/apollo-issue-demo.zip)

结果验证在`Application`中
```
 /*
application.yml中
	spring:
	  datasource:
		druid:
		  max-active: 100001
 apollo中配置
	spring.datasource.druid.max-active=100
	spring.datasource.initial-size=1
 */
System.err.println(druidProperties);
/*
输出结果: DruidProperties(initialSize=1, maxActive=10000)
 */
```

**Comment by mhcxp** [comment]
@nobodyiam 已将
`ApolloApplicationContextInitializer implements ApplicationContextInitializer<ConfigurableApplicationContext>`
修改为
`implements ApplicationListener<ApplicationEnvironmentPreparedEvent>`
可以覆盖本地属性

**Comment by nobodyiam** [comment]
@mhcxp 非常感谢，我试了一下demo，确实是会有顺序的问题导致yaml的配置覆盖了apollo的配置。

一个简单的解决办法是把`apollo.bootstrap.enabled`配置写在`application.yml`里面，不要写在`bootstrap.yml`里面，这样就能让apollo的配置晚于`YamlPropertySourceLoader`。

我们后面再研究一下如何不让`YamlPropertySourceLoader`覆盖Apollo的配置。

**Comment by taccisum** [comment]
@nobodyiam 你好，我也碰到了这个问题，按照你的办法将`apollo.bootstrap.enabled`写在`application.yml`里面后确实本地配置不再覆盖apollo的配置了，但是apollo的配置却把命令行参数的配置给覆盖掉了，想请教一下这个问题如何解决呢？

启动命令
```shell
java -server -Denv=DEV -jar foo.jar --eureka.client.serviceUrl.defaultZone=http://49.4.14.145:20000/eureka/
```

通过actuator拿到的环境变量
[http://127.0.0.1:10001/env]
```json
{
    "ApolloBootstrapPropertySources:AM.common":{
        "eureka.client.serviceUrl.defaultZone":"http://117.78.36.155:20000/eureka/"
    },
    "commandLineArgs":{
        "eureka.client.serviceUrl.defaultZone":"http://49.4.14.145:20000/eureka/"
    },
}
```
[http://127.0.0.1:10001/env/eureka.client.serviceUrl.defaultZone]
```json
{
   "eureka.client.serviceUrl.defaultZone":"http://117.78.35.154:20000/eureka/"
}
```
可见最终生效的是apollo里面的配置。

除了这个`eureka.client.serviceUrl.defaultZone`外，也试过其它配置，同样是存在这个问题。

例如自定义了一个`placeholder`属性，在apollo的值是"abcde"，通过命令行启动加入配置"--placeholder=12345"，最终生效的值是"abcde"。如果把`apollo.bootstrap.enabled`从`application.yml`迁回到`bootstrap.yml`中，最终生效的值则是"12345"。

**Comment by nobodyiam** [comment]
command line args会被覆盖的，你可以通过system property传入，比如`-Deureka.client.serviceUrl.defaultZone=http://49.4.14.145:20000/eureka/`

**Comment by nobodyiam** [comment]
Fixed in #1432

**Comment by nobodyiam** [comment]
1.1.0版本已经发布，包含了该fix，更多信息可以参考： https://github.com/ctripcorp/apollo/releases/tag/v1.1.0
