### ISSUE TITLE
关于apollo服务端几个问题

### ISSUE THREAD

**Issue by seguzhizi** [ctripcorp/apollo#1036]
1：服务端部署环境能否使用jdk7？
2：我看了apollo的maven依赖，发现依赖数量很多，而且有不同的类型。当我引入项目后，只能使用本地maven私服，请问我需要把哪些依赖上传到私服上呢？
谢谢~！

**Comment by nobodyiam** [comment]
1. 服务端部署需要jdk8
2. 只有客户端相关jar和pom文件需要上传到私服，具体参考下[分布式部署指南#28-部署apollo-client](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#28-%E9%83%A8%E7%BD%B2apollo-client)

**Comment by seguzhizi** [comment]
可是服务端运行的时候也需要jar啊，这些jar不也是maven打包的时候引入的吗？我这边的私服不能连接外网，那这些依赖也需要我手动上传的吧。
我这边的测试和生产都是自动化打包部署，所以在打包的时候无法获取jar的话，打包也会失败的吧。。

**Comment by nobodyiam** [comment]
自动化部署和私服不矛盾吧，为啥你的私服不能连接外网呢，这个有点怪啊，一般都是和中央仓库保持同步的。这个依赖的jar包很多的，就算给你一一列出来，你再一个一个上传到私服估计也很累吧。。

如果你真要这么干的话，直接到服务端项目下跑`mvn dependency:list`就知道要哪些依赖了。

**Comment by huxiaofei** [comment]
私服不能连接外网很多，比如在企业内部网：比如政府，公安，银行等

**Comment by nobodyiam** [comment]
理解，那可以按照`mvn dependency:list`获取依赖列表。

另一个方式是在能连接外网的环境打好zip包，再去内部网发布。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by zone1511** [comment]
先在可連外網的機器上跑mvn dependency:go-offline 再把本地的maven repo copy 到不能連外網的機器就可以了
