### ISSUE TITLE
配置变更发布之后，无法获取最新的变更值，使用的是placeholder的形式，client版本是v0.10.1

### ISSUE THREAD

**Issue by luoxianchao** [ctripcorp/apollo#1041]

**Comment by nobodyiam** [comment]
建议看一下客户端日志吧，如果无法定位问题，可以提供一个最简的demo程序，我们看一下。

**Comment by luoxianchao** [comment]
配置变化时，监听到变化，并且会重新设置配置的值，但是设置成功之后springboot项目会自动重启，就没有读取到变化后的值了，指定成默认的值了

**Comment by bigbenfather** [comment]
为啥关闭了，什么原因啊

**Comment by luoxianchao** [comment]
是我springboot配置错了，配置了热启动的情况下才出现了这个问题


| |
罗宪超
邮箱：luoxianchao1989@126.com
|

签名由 网易邮箱大师 定制

在2018年06月05日 20:35，bigbenfather 写道：

为啥关闭了，什么原因啊
