### ISSUE TITLE
关于spring环境依赖和apollo-client问题

### ISSUE THREAD

**Issue by seguzhizi** [ctripcorp/apollo#1042]
在本地使用时，客户端依赖了apollo-client-0.9.0版本，可以在无spring环境中正常使用，但是当我替换为0.10.0后（我仅仅替换了apollo-core和apollo-client两个jar），运行报错：
Caused by: java.lang.ClassNotFoundException: org.springframework.beans.factory.config.ConfugurableBeanFactory
我是在非spring环境使用的，按理不应该报此错误的，是因为0.10.0版本有改动吗？

**Comment by nobodyiam** [comment]
这个是0.10.0的一个已知问题，请升级到0.10.2吧。

https://github.com/ctripcorp/apollo/releases

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
