### ISSUE TITLE
portal中cookie解析报错

### ISSUE THREAD

**Issue by LittleShrimp1987** [ctripcorp/apollo#1044]
当往cookie里写入中文的时候，服务器解析cookie报错。错误堆栈如下。

`java.lang.IllegalArgumentException: Control character in cookie value or attribute. at org.apache.tomcat.util.http.LegacyCookieProcessor.isV0Separator(LegacyCookieProcessor.java:749) at org.apache.tomcat.util.http.LegacyCookieProcessor.processCookieHeader(LegacyCookieProcessor.java:546) at org.apache.tomcat.util.http.LegacyCookieProcessor.parseCookieHeader(LegacyCookieProcessor.java:276) at org.apache.catalina.connector.Request.parseCookies(Request.java:3048) at org.apache.catalina.connector.Request.getServerCookies(Request.java:2064) at org.apache.catalina.connector.CoyoteAdapter.parseSessionCookiesId(CoyoteAdapter.java:1226) at org.apache.catalina.connector.CoyoteAdapter.postParseRequest(CoyoteAdapter.java:935) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:523) at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1100) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:687) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:745)`

**Comment by nobodyiam** [comment]
根据[RFC6265](https://tools.ietf.org/html/rfc6265#section-4.1.1)，cookie是不允许有中文的。

**Comment by LittleShrimp1987** [comment]
我明白你的意思，不允许有中文，但是中文可以做urlencode再存入cookie
我们只有部门名称是中文的，portal会把部门名称写入cookie吗？

**Comment by nobodyiam** [comment]
不会的，建议找一下出问题的用户，看下cookie的具体内容

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
