### ISSUE TITLE
客户端 notifications/v2 504 怎么解

### ISSUE THREAD

**Issue by mhcxp** [ctripcorp/apollo#1045]
版本: 0.10.2 
```
2018-04-10 22:20:05.245  WARN [apollo-demo,,,] 5544 [Apollo-RemoteConfigLongPollService-1] [c.c.f.a.i.RemoteConfigLongPollService   :194] Long polling failed,
will retry in 120 seconds. appId: apollo-demo, cluster: default, namespaces: application+extraDev, long polling url:
http://localhost:18080/notifications/v2?cluster=default&appId=apollo-demo&ip=192.168.200.1&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A8%7D%2C%7B%22namespaceName%22%3A%22extraDev%22%2C%22notificationId%22%3A6%7D%5D, reason: Could not complete get operation [Cause: Server returned HTTP response code: 504 for URL: 
http://localhost:18080/notifications/v2?cluster=default&appId=apollo-demo&ip=192.168.200.1&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A8%7D%2C%7B%22namespaceName%22%3A%22extraDev%22%2C%22notificationId%22%3A6%7D%5D [Cause: Server returned HTTP response code: 504 for URL: http://localhost:18080/notifications/v2?cluster=default&appId=apollo-demo&ip=192.168.200.1&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A8%7D%2C%7B%22namespaceName%22%3A%22extraDev%22%2C%22notificationId%22%3A6%7D%5D]]

```

**Comment by nobodyiam** [comment]
你先浏览器访问以下这个URL看看？tomcat应该不会返回504吧？

**Comment by mhcxp** [comment]
浏览器一样504。修改配置并发布后，重新访问（notificationId已请求过）正常，但使用新的notificationId 依然504

**Comment by weifan01** [comment]
@mhcxp  您好，这个最终怎么解决了呢？我的也是这个问题，分布式部署方式

**Comment by nobodyiam** [comment]
504应该是Long Polling不是通过IP直连config service，而是走了网关或nginx之类的，需要调大网关或nginx上的超时设置到1分钟以上。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by working-alone** [comment]
[Apollo-RemoteConfigLongPollService-1] WARN  c.c.f.a.i.RemoteConfigLongPollService -【】- Long polling failed, will retry in 1 seconds. appId: hnf-orders-consumer-server, cluster: default, namespaces: application, long polling url: http://172.17.0.3:8180/notifications/v2?cluster=default&appId=hnf-orders-consumer-server&ip=10.244.1.3&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A88%7D%5D, reason: Could not complete get operation [Cause: No route to host (Host unreachable)]

**Comment by zhangbao1s** [comment]
nginx  keepalive_timeout 120; 还是同样报超时 HTTP response code: 504

**Comment by oldthreefeng** [comment]
> nginx keepalive_timeout 120; 还是同样报超时 HTTP response code: 504

+1
