### ISSUE TITLE
demo提示的url地址错误，

### ISSUE THREAD

**Issue by shaojava** [ctripcorp/apollo#1049]
Get config services failed from http://config.local/services/config?appId=100004458&ip=172.16.248.194 [Cause: Could not complete get operation [Cause: connect timed out]]

**Comment by shaojava** [comment]
配置写错了 解决了 
pro_meta 环境配置 
环境配置位置太多 容易出错

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
