### ISSUE TITLE
[阿里云ecs]生产和测试环境在不同的区域，导致portal无法connect测试环境

### ISSUE THREAD

**Issue by hdpter** [ctripcorp/apollo#1050]
公司使用阿里云的ecs
1、生产环境(pro)在华北2
2、测试环境(test)在华北3(为什么不在同一个区域 历史原因)。   
apollo-adminservice  8090
apollo-configservice  8091
apollo-portal  8092
已经在env下自定义了test枚举。
按照官方建议，portal 部署在了pro环境下。portal管理pro和test。
test_meta 绑定了test域名(http://apollo.test.xxxx.com --- 内网IP:172.26.0.88)

pro下的portal启动时出现了如下错误：

2018-04-11 10:30:08.441 ERROR 29947 --- [Apollo-EnvHealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env health check failed, maybe because of meta server down or configure wrong meta server address. env: TEST, meta server address: http://apollo.test.xxxx.com

com.ctrip.framework.apollo.common.exception.ServiceException: Admin servers are unresponsive. meta server address: http://apollo.test.xxxx.com, admin servers: [ServiceDTO{appName='APOLLO-ADMINSERVICE', instanceId='iZ8vbfejqs8geas2eq0pp1Z:apollo-adminservice:8090', homepageUrl='http://172.26.0.88:8090/'}]

http://apollo.test.xxxx.com 是test环境域名，nginx指向apollo-configserver的8091端口。
而错误提示需要检查 http://172.26.0.88:8090

我们的生产portal绝对连接不上 172.26.0.88 的  因为不在ecs区

这种情况下 使用 apollo 应该怎么处理呢？

**Comment by nobodyiam** [comment]
portal首先从meta server获取到admin service的信息: http://apollo.test.xxxx.com/services/admin

然后会根据获取到的信息直接连接admin service，也就是你说的 http://172.26.0.88:8090

你这个情况比较特殊，可以考虑让admin service注册上来的信息手工指定为portal能够访问到的地址，可以参考下[分布式部署指南#14网络策略](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#14%E7%BD%91%E7%BB%9C%E7%AD%96%E7%95%A5)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by filamoon** [comment]
这个 issue 建议放到 wiki 里去啊，还挺常见的

**Comment by nobodyiam** [comment]
@filamoon 

在[分布式部署指南#14网络策略](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#14%E7%BD%91%E7%BB%9C%E7%AD%96%E7%95%A5)中说明的

**Comment by Lucas4585** [comment]
我用的是apollo-build-scripts，将 -Deureka.instance.homePageUrl=http://${指定的IP}:${指定的Port} 这句话加在 demo.sh 文件的哪里啊？
