### ISSUE TITLE
Eureka提示信息如何处理，与配置有关 还是网络原因

### ISSUE THREAD

**Issue by shaojava** [ctripcorp/apollo#1051]
THE SELF PRESERVATION MODE IS TURNED OFF.THIS MAY NOT PROTECT INSTANCE EXPIRY IN CASE OF NETWORK/OTHER PROBLEMS.

**Comment by nobodyiam** [comment]
这个是因为我们把enableSelfPreservation关掉了，所以eureka会有这个提示，没有关系的。

https://github.com/ctripcorp/apollo/blob/master/apollo-configservice/src/main/resources/bootstrap.yml#L7

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
