### ISSUE TITLE
请问配置加解密目前有现有的切入点吗

### ISSUE THREAD

**Issue by cy1ng** [ctripcorp/apollo#1055]
有现有的切入点吗？还是说要自己改源码

**Comment by nobodyiam** [comment]
可以参考下这个项目：https://github.com/ulisesbocchio/jasypt-spring-boot

**Comment by cy1ng** [comment]
好的  多谢

**Comment by seven7ma** [comment]
@nobodyiam  请问非boot项目有什么好点的方案吗?

**Comment by whai888** [comment]
@nobodyiam 非boot项目，集成了apollo，不知道怎么处理加解密。可以提供一个case做参考

**Comment by nobodyiam** [comment]
[jasypt](http://www.jasypt.org/)本身是不依赖于spring boot的，可以看下它的例子

**Comment by xlixlixli** [comment]
@whai888 非boot项目，集成Apollo后加解密有解决方案了吗？还请告知一下，感谢！
