### ISSUE TITLE
刷新自定义注入的bean刷新不了，进不来，求大神指点。

### ISSUE THREAD

**Issue by gongjing2012** [ctripcorp/apollo#1056]
通过
 @Autowired
  ContextRefresher contextRefresher;
  contextRefresher.refresh();    
来刷新下面注入的bean，进不来。

@Bean
    @Scope(proxyMode = ScopedProxyMode.INTERFACES)
    @RefreshScope
    public JedisConnectionFactory redisConnectionFactory(@Qualifier("jedisPoolConfig") JedisPoolConfig jedisPoolConfig) {
        if(cluster) {
            RedisClusterConfiguration redisClusterConfiguration = new RedisClusterConfiguration(Arrays.asList(redisClusterProperties.getNodes().split(",")));
            redisClusterConfiguration.setMaxRedirects(redisClusterProperties.getMaxRedirects());
            logger.debug("load redis cluster success {} ", redisClusterProperties.getNodes().toString());
            return new JedisConnectionFactory(redisClusterConfiguration,jedisPoolConfig);
        }else{
            JedisConnectionFactory redisConnectionFactory = new JedisConnectionFactory();
            redisConnectionFactory.setHostName(redisSingleProperties.getHost());
            redisConnectionFactory.setPort(redisSingleProperties.getPort());
            redisConnectionFactory.setTimeout(redisSingleProperties.getTimeout());
            redisConnectionFactory.setPassword(redisSingleProperties.getPassword());
            redisConnectionFactory.setDatabase(redisSingleProperties.getDatabase());
            redisConnectionFactory.setPoolConfig(jedisPoolConfig);
            logger.debug("load redis single success {} ", redisSingleProperties.getHost().toString());
            return redisConnectionFactory;
        }
    }

**Comment by nobodyiam** [comment]
能否提供一个简单的demo程序？

**Comment by sunyang1989** [comment]
redisConnectionFactory.afterPropertiesSet();

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
