### ISSUE TITLE
数据库密码明文配置

### ISSUE THREAD

**Issue by chenliuyang1989** [ctripcorp/apollo#1057]
数据库密码这块的配置最好不要用明文配置吧

**Comment by nobodyiam** [comment]
恩，建议用密文存储，在客户端拿到后再解密

**Comment by chenliuyang1989** [comment]
恩，线上密码配置这块还是做到仅对DBA开发最好

**Comment by seguzhizi** [comment]
接着问下，一般使用build.sh/build.bat进行zip打包的时候，都是将数据库的信息直接写在build.sh文件里面的，但是公司的要求是开发人员不能获取生产DB密码，所以公司的其他系统都是在部署完毕，启动的时候，去服务器上指定的位置获取DB配置文件的，并不是开发人员写在系统代码（或配置文件）中的~！所以请问下， 这种启动的时候去指定位置获取DB信息的方式，Apollo支持吗？如果不支持，如何修改适应呢？

**Comment by nobodyiam** [comment]
@seguzhizi 我们公司也是这么要求的，所以我们是在运行时自己创建datasource的，你也可以这么做，参考[TitanEntityManager](https://github.com/ctripcorp/apollo/blob/master/apollo-common/src/main/java/com/ctrip/framework/apollo/common/datasource/TitanEntityManager.java)，另外，你自己写的话就不需要通过反射了。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by nobodyiam** [comment]
see #3187
