### ISSUE TITLE
加入一個專門用來創建數據庫的工具

### ISSUE THREAD

**Issue by zone1511** [ctripcorp/apollo#1059]
為了簡化數據庫的配置 可不可以增加一個用來創建數據庫schema 和初始数据的工具?

**Comment by nobodyiam** [comment]
恩，不少软件都有一个wizard的界面用来做这种初始化的事情。

**Comment by zone1511** [comment]
基於spring jpa 要創建數據庫schema 應該很容易

**Comment by kezhenxu94** [comment]
@nobodyiam 使用 flyway 初始化及管理数据库 schema 版本升级是不是好点，以后数据库 schema 有变化的时候也方便开发者升级

**Comment by kezhenxu94** [comment]
Hi @zone1511 @nobodyiam , 我在[这个分支](https://github.com/kezhenxu94/apollo/tree/feature/flyway)中引入了 flyway 进行数据库初始化和升级管理, 代码还需要做一些清理优化, 使用方式如下, 你可以看看这种是否可以接受.

```shell
$ mvn -N -Pportaldb flyway:migrate # 初始化或升级(如果有) PortalDB 数据库 Schema
$  mvn -N -Pconfigdb flyway:migrate # 初始化或升级(如果有) ConfigDB 数据库 Schema
```

@nobodyiam 如果 ok 的话, 我可以提一个 PR

**Comment by nobodyiam** [comment]
@kezhenxu94 

看了一下，挺好的，有几个小点看看是否可以改善一下：

1. url, user, password是否可以通过-D参数传入？
2. location能直接指向`scripts/sql`吗？从而避免维护多份sql

**Comment by kezhenxu94** [comment]
> @kezhenxu94
> 
> 看了一下，挺好的，有几个小点看看是否可以改善一下：
> 
> 1. url, user, password是否可以通过-D参数传入？
> 2. location能直接指向`scripts/sql`吗？从而避免维护多份sql

1. 可以的，提 PR 前我会优化着点
2. 可以直接指向 `scripts/sql`, 但 `sql` 下目录结构需要做些小改动，把两个库的脚本分别放到两个文件夹中，原因是 `flyway` 每次只会 migrate 一个 Schema, 放到一起的脚本会被执行到同一个库中，这不符合该项目

**Comment by nobodyiam** [comment]
[1.3.0](https://github.com/ctripcorp/apollo/releases/tag/v1.3.0)版本已经发布，支持了数据库版本管理工具Flyway。
