### ISSUE TITLE
apollo-core的配置外置

### ISSUE THREAD

**Issue by MrLiuhhh** [ctripcorp/apollo#1062]

**Comment by MrLiuhhh** [comment]
请问下可以实现将apollo-core中关于meta-server的属性外至吗，这样只需打一次包即可，不用根据meta-server的地址变化 重新打包。用户只需在接入的项目中更新自己的配置即可，想问下关于这个的实现有什么好的方案吗

**Comment by nobodyiam** [comment]
这个目前就是支持的，一种方式是在应用通过-D{env}_meta传入（这里的env就是实际的环境信息，如dev），另一种是把apollo-env.properties外置放在应用的classpath下。

**Comment by MrLiuhhh** [comment]
谢谢 十分感谢~
