### ISSUE TITLE
整个流程的事务控制的疑惑

### ISSUE THREAD

**Issue by ahaaaaa** [ctripcorp/apollo#1064]
1、通过mysql做队列，如果 config server挂掉了，那这个时间段发布的消息，还能继续通知客户端吗？
2、整个流程的更新的状态如何跟踪呢，如果客户端更新失败了，怎么整个流程好像不是事务控制的。

**Comment by lepdou** [comment]
1. config server挂了即使通知到了客户端，客户端也无法从config server获取最新的配置
2. 客户端如果通知更新失败了，客户端会有5分钟的定时从config server获取最新的配置，整个流程不需要事务。

**Comment by nobodyiam** [comment]
这个在[Apollo配置中心设计#四可用性考虑](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1#%E5%9B%9B%E5%8F%AF%E7%94%A8%E6%80%A7%E8%80%83%E8%99%91)中有说明的。

如果全部的config service全挂了，那么在挂的期间客户端是获取不到最新的配置的。

不过一旦config service恢复之后，客户端就能获得推送通知了，因为状态是在客户端保存的，每次客户端long polling时都会告诉服务端自己的notification id的。

另外，如 @lepdou 所说，客户端还有定期每5分钟从config service拉取配置的机制。

所以，通过推拉结合的机制，可以确保客户端的配置的最终一致性。

**Comment by ahaaaaa** [comment]
3ks，最近打算在项目中使用，然后稍微看了下源码，有问题再请教。
