### ISSUE TITLE
找不到环境列表问题

### ISSUE THREAD

**Issue by sundylgz** [ctripcorp/apollo#1066]
在configservice和adminservice中添加-Deureka.instance.homePageUrl=http://${指定的IP}:${指定的Port}，portal就找不到改环境，服务器启动都是ok的，端口是通的。

**Comment by sundylgz** [comment]
在portal 页面中报错， load env:DEV cluster error .404 NOT FUND

**Comment by nobodyiam** [comment]
可以打开meta server地址，看看admin service是不是注册上去了。

另外，可以看下portal和admin service的日志，看看404的原因。

**Comment by seven7ma** [comment]
![image](https://user-images.githubusercontent.com/24469163/39344606-ffe6e2f6-4a15-11e8-8a62-06e1d993fabc.png)
同样的问题

**Comment by seven7ma** [comment]
如果改成第二种 ip配置的话是没问题的:
eureka:
  instance:
    ip-address: ${指定的IP}

**Comment by zkk765696946** [comment]
我也是修改成 -Deureka.instance.ip-address= 指定IP没问题了

**Comment by sundylgz** [comment]
在启动shell中 -Deureka.instance.ip-address= 指定IP确实解决问题，大家遇到这个问题还是这个方法做

**Comment by jimforcode** [comment]
请问下 是在哪个环境  添加  -Deureka.instance.ip-address= 指定IP 呢， 遇到同样的问题

**Comment by jimforcode** [comment]
请问下 是在哪个环境 添加 -Deureka.instance.ip-address= 指定IP 呢？portal?， 遇到同样的问题

**Comment by nobodyiam** [comment]
@jimforcode 

config service和admin service的启动参数

**Comment by jiangxiaoqiang** [comment]
同样的问题，版本1.6.0，IP没有问题，改为域名就会出现这个问题（开发环境暴露IP会暴露端口，所以使用域名），请问下如何解决的？
