### ISSUE TITLE
缓存目录可以自定义吗？

### ISSUE THREAD

**Issue by luoxianchao** [ctripcorp/apollo#1067]
现在缓存目录需要环境根目录下创建opt/data/文件夹，想自己指定到特定的目录，可以实现吗？

**Comment by nobodyiam** [comment]
缓存目录是在[ConfigUtil](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/util/ConfigUtil.java#L208)中定义的，目前不支持自己指定

**Comment by nobodyiam** [comment]
PR #1274 已经合并，现在支持自定义了。

可以通过`-Dapollo.cacheDir=xxx`或在server.properties中配置`apollo.cacheDir=xxx`自定义。
