### ISSUE TITLE
apollo的appid是否可以优化支持在spring boot的application. properties文件里配置

### ISSUE THREAD

**Issue by onethin** [ctripcorp/apollo#1068]
如题，这样就可以少一些孤零零的配置文件

**Comment by nobodyiam** [comment]
apollo目前对运行时不做要求，所以是统一通过META-INF/app.properties或者-Dapp.id获取的，支持application.properties的话，可能就需要依赖spring boot的一些类了，这个得研究一下是否有比较好的方案

**Comment by onethin** [comment]
是否可以通过添加一个包，比如spring-boot-starter-apollo，boot环境下可以引用这个包，在这里处理读取application.properties，这样现有的代码可以不依赖boot的类

**Comment by nobodyiam** [comment]
可以是可以，不过为了这个配置增加一套东西貌似不太值。

另外，这个starter还需要替换default的application provider的实现才行，貌似有点重了
