### ISSUE TITLE
apollo启动会在服务器根生成很多tmp+uuid文件夹.

### ISSUE THREAD

**Issue by ayanjoyful** [ctripcorp/apollo#1071]
apollo启动后,根目录生成很多tmp+uuid文件夹.里边有临时文件这个怎么处理呢? 类似于这种tmp030925328f2c4c579f995817ded4941f

**Comment by nobodyiam** [comment]
这个是Apollo的服务端吗？好像之前没有印象会生成这个啊，你能看下文件里面的内容吗？

另外，根目录一般也都是没有权限写的吧，你是用root启动的apollo？

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
