### ISSUE TITLE
登陆逻辑是如何处理的？点击登陆按钮，并未发现发送到后台的请求

### ISSUE THREAD

**Issue by seguzhizi** [ctripcorp/apollo#1074]
在进行浏览器调试的时候，我点击登陆，看到的是/signin请求，并未发现其他的请求！
由于对AnjularJS不是很熟，我看到LoginCnotroller.js里面也未发现发起到后台的登陆请求。。。

**Comment by nobodyiam** [comment]
默认的认证是通过Spring Security实现的，具体可以参考 https://docs.spring.io/spring-security/site/docs/current/guides/html5/form-javaconfig.html

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by 2775468731** [comment]
这个集成springsecurity是真不好用
