### ISSUE TITLE
请问哪里可以找到changelog？

### ISSUE THREAD

**Issue by zhfish** [ctripcorp/apollo#1075]
部署了0.10.0-SNAPSHOT
看到了现在有0.11.0-SNAPSHOT
不知道该不该升级？
恕我眼拙，没找到changelog..

**Comment by nobodyiam** [comment]
Release notes - https://github.com/ctripcorp/apollo/releases

另外，不建议生产部署SNAPSHOT版本，建议使用最新的release版本 - 0.10.2，0.11.0还没有正式release。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
