### ISSUE TITLE
加载数据库连接等信息问题

### ISSUE THREAD

**Issue by seguzhizi** [ctripcorp/apollo#1076]
想问下，一般使用build.sh/build.bat进行zip打包的时候，都是将数据库的信息直接写在build.sh文件里面的，但是公司的要求是开发人员不能获取生产DB密码，所以公司的其他系统都是在部署完毕，启动的时候，去服务器上指定的位置获取DB配置文件的，并不是开发人员写在系统代码（或配置文件）中的~！所以请问下， 这种启动的时候去指定位置获取DB信息的方式，Apollo支持吗？如果不支持，如何修改适应呢？

我看了下Build.sh打出的zip包，是把DB的url，username和password打到了apollo-common.jar中的application-github.properties里面，但是暂时未发现apollo是如何加载此配置文件的？百度了下springboot加载文件的方式，好像没有在apollo里面搜索到对应的方式！
望告知~谢谢

**Comment by nobodyiam** [comment]
@seguzhizi 我们公司也是这么要求的，所以我们是在运行时自己创建datasource的，你也可以这么做，参考[TitanEntityManager](https://github.com/ctripcorp/apollo/blob/master/apollo-common/src/main/java/com/ctrip/framework/apollo/common/datasource/TitanEntityManager.java)，另外，你自己写的话就不需要通过反射了。

**Comment by seguzhizi** [comment]
谢谢解答
我这边有两个问题：
1：根据我1楼的描述，portal启动的时候应该是加载了application-github.properties中的三个属性值，然后生成了当前的DataSource对象。我想问下，能否让portal不去加载classpath:application-github.propertis文件，而去加载我自定义的properties？这样的话，我就不用自行生成DataSource了

2：如1所说，目前我未找到portal的加载代码。所以提第2个问题：
我看了下TitanEntityManager代码，应该是你们使用反射，调用DalDataSourceFactory类的createDataSource方法，然后该方法返回了DataSource对象（Spring bean），最后用这个DataSource对象来替换掉默认的DataSource。。。但是我搜索了代码，没有看到注入此bean的地方，是否是因为这是携程的实现，未放在源码中？

望解答，谢谢owner

**Comment by nobodyiam** [comment]
1. portal启动时加载application-github.properties，这个是因为配置了spring的profile为github，你可以让它加载自定义的properties，这个看下spring boot的文档就可以了，可以指定自己的profile，或者是显式加载，如`@PropertySource`

2. TitanEntityManager其实只是创建了一个`Datasource`，这个是给spring data jpa用的，所以不是我们的代码注入此bean，你如果自己实现的话，也只需要提供一个`Datasource` bean即可

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
