### ISSUE TITLE
【一致性问题】configservice集群数据一致性问题

### ISSUE THREAD

**Issue by useraddZYB** [ctripcorp/apollo#1077]
看了服务端configservice（以下简称cs）的架构图，有两个疑问：
1，cs每秒从表里取新增配置存本地，这个会导致多个cs节点有1秒的不一致？请问设计上怎么考虑取舍的。
2，cs集群去中心化的设计，虽然简单，但是理论上，如果某个cs的内部逻辑挂了（比如1秒取表数据的），这个节点的数据就不能正常更新，且整个集群不知道？（客户端取数据会上传版本，虽然某种程序上不会取到这个挂的节点的错误数据，但是cs集群确实有部份节点可能不健康了）不知道有没有对应的策略解决这个问题，比如告警之类的。

只看了配置中心说明文档，还没有看源码的，提前问下，多谢

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
