### ISSUE TITLE
.net core api 使用apollo

### ISSUE THREAD

**Issue by YINZHU2016** [ctripcorp/apollo#1078]
你好，请问可以提供一个.net core api 使用apollo的demo例子吗。我看了你们写的.net core 控制台的程序，但是不知道该如何改进到.net core api的项目里面去。谢谢

**Comment by YINZHU2016** [comment]
你好，其实您说的这些项目我在提问题之前都全部看了的，也知道有一个.net core的控制台程序的demo演示了相关的功能，但是可能因为我的.net core的基础知识不太扎实，我现在是想在一个.net core 的api项目中使用了，所以我不知道该如何转换看到的对应的demo代码，如果你们可以体统一个.net core的api项目代码的demo例子就最好了。谢谢

**Comment by nobodyiam** [comment]
可以看下这个demo

https://github.com/ctripcorp/apollo.net/blob/dotnet-core/Apollo.ConfigurationManager.Demo/ConfigurationManagerDemo.cs

https://github.com/ctripcorp/apollo.net/tree/dotnet-core 里面还有好几种不同类型的demo，也可以参考一下

**Comment by YINZHU2016** [comment]
谢谢，我仔细了看了你们的demo，并且学习了.net core关于配置的底层知识，已经可以很好将apollo的运用到我的项目中去了。
真羡慕你们Java的世界，基本上各种解决方案都会有好的开源作品。希望以后我有机会也转成java。哈哈

**Comment by nobodyiam** [comment]
@YINZHU2016 注入json对象的功能在Java中目前是支持的，不过.net core的实现可能还没有支持，@pengweiqhca 帮忙看看.net core的版本是否有此功能？

**Comment by YINZHU2016** [comment]
好吧，我可能是这个开源项目极少数的.net程序员了。应该给我一点爱呀。
嗯，我使用了曲线救国的方式解决了这个问题
我设计了一个类，然后通过在apollo直接配置Aws3UploadConfigurationItemListJsonString 这个字段，并且在这个字段里面赋值json字符串，然后客户端代码这边的配置对象，通过json转换器直接转换出来。
希望后面有.net的小伙伴能够提供一个更加友好的解决方案。

`public class Aws3UploadConfiguration
    {
        public string AwsName { get; set; }
        public List<Aws3UploadConfigurationItem> Aws3UploadConfigurationItemList { get; set; }
        
        public BaseItem Item { get; set; }
    }

    public class Aws3UploadConfigurationWrap
    {
        public Aws3UploadConfiguration Aws3UploadConfiguration
        {
            get
            {
                if (!string.IsNullOrEmpty(Aws3UploadConfigurationJsonString))
                {
                    return JsonConvert.DeserializeObject<Aws3UploadConfiguration>(
                        Aws3UploadConfigurationJsonString);
                }

                return null;
            }
        }

        public string Aws3UploadConfigurationJsonString { get; set; }
    }

    public class Aws3UploadConfigurationItem
    {
        public string AccessKey { get; set; }
        public string SecretKey { get; set; }
        public string Region { get; set; }
    }

    public class BaseItem
    {
        public string BaseName { get; set; }
        public int BaseAge { get; set; }
    }`

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
