### ISSUE TITLE
apollo没有提供推送配置的api，只能通过portal人为发布配置？

### ISSUE THREAD

**Issue by Kingson4Wu** [ctripcorp/apollo#1079]

**Comment by nobodyiam** [comment]
配置的设计场景是低频修改，需要人工配置和审批校验的，所以主要方式是通过portal发布配置。

不过Apollo也提供了open api，具体可以参考[Apollo开放平台](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0)

**Comment by Kingson4Wu** [comment]
谢谢
