### ISSUE TITLE
建议apollo-configservice模块下的单元测试关闭spring.jpa.properties.hibernate.show_sql

### ISSUE THREAD

**Issue by wuwen5** [ctripcorp/apollo#1081]
建议apollo-configservice模块单元测试的spring.jpa.properties.hibernate.show_sql配置为false，关闭打印sql。

原因是在```AbstractBaseIntegrationTest```子类的集成测试用例中，```TestBizConfig```将定时任务执行周期设置为1毫秒，所以在travis中会产生大量的查询sql日志刷屏，导致有时候会因为日志过多travis测试失败。 就像这样 https://travis-ci.org/ctripcorp/apollo/jobs/374444158#L10000

>The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).
>The job has been terminated

**Comment by nobodyiam** [comment]
非常感谢，我们后面调整一下。

**Comment by nobodyiam** [comment]
spring.jpa.properties.hibernate.show_sql is set to false in PR #1083
