### ISSUE TITLE
支持springboot2.0吗

### ISSUE THREAD

**Issue by luoyimo** [ctripcorp/apollo#1082]

**Comment by nobodyiam** [comment]
支持

**Comment by luoyimo** [comment]
我尝试升级到2.0.1,pom中存在大量重复依赖  很难升级，有什么好的解决方案吗

**Comment by nobodyiam** [comment]
你是要把config service，admin service等升级到spring boot 2.0？这个工作量还是有点大的。

客户端跑在spring boot 2.0应该没问题。

**Comment by luoyimo** [comment]
好吧  我想升级整个工程

**Comment by nobodyiam** [comment]
可以照着spring boot的教程升级看看。。。

**Comment by nobodyiam** [comment]
apollo服务端已经升级spring boot到2.0.5，spring cloud到Finchley.SR1，详情参见 #1527

**Comment by nobodyiam** [comment]
1.1.0版本已经发布，apollo服务端已经更新到spring boot 2.0，可以考虑升级~

https://github.com/ctripcorp/apollo/releases/tag/v1.1.0
