### ISSUE TITLE
同一台机器可以部署2-3套以上的Config Service和Admin Service吗

### ISSUE THREAD

**Issue by YINZHU2016** [ctripcorp/apollo#1084]
你好，我们公司其实相关服务器不多，所以我想将dev,stg环境的apollo的Config Service和Admin Service都部署在一台服务器上面是可行的吗，apollo portal当然也在一起，不过只部署一个实例。然后数据库我设计2份库，还有就是configserver,adminserver的端口也设计2套，可以吗？

**Comment by nobodyiam** [comment]
物理部署可以按照实际情况来做，只要保证逻辑上每个环境是分开的即可。

config service, admin service, ApolloConfigDB每个环境一套，portal, ApolloPortalDB只需要一套即可。

**Comment by l-ning** [comment]
你好,想问一下,如果在同一个环境下,多台机器怎么配置呢?

**Comment by nobodyiam** [comment]
config service多台的话，就填写在eureka.service.url中以逗号分隔，meta server需要自己用nginx或域名指向config service集群，admin service不需要做额外配置

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
