### ISSUE TITLE
求助：当前公共namespace的所有者 **** 没有关联此namespace,请联系****的所有者在****项目里关联此namespace

### ISSUE THREAD

**Issue by xiabobin** [ctripcorp/apollo#1086]
**apollo版本 ：** 0.10.0-SNAPSHOT

**现象描述：**
在关联public namespace时，namespace的“公共的配置”表格提示“当前公共namespace的所有者 **** 没有关联此namespace,请联系****的所有者在****项目里关联此namespace”。

**我的需求：**
1.创建一个父工程，分配dev、fat两套环境，创建若干public namespace用于保存公共配置（dev、fat环境配置不一样）。
2.然后在其他工程中关联上述public namespace。根据env选择使用不同env的public namespace配置。

**我的配置流程：**
**当Apollo只有DEV环境时：**
1.我新建了一个APPID，命名为“parent”，在这个APPID的DEV环境创建若干public namespace，例如：db_config、redis_config等，然后为这些namespace发布若干配置。
2.再创建一个APPID，命名为“child1”，在DEV环境里关联“parent”的db_config public namespace、redis_config namespace，DEV环境里能够看到“parent”的public namesapce配置。
3.截至到这步都是正常的。
**然后我又创建了FAT环境并且补全丢失环境**
4.我在“parent”的fat环境中关联了public namespace“db_config”，关联后"db_config"属性是空的，然后我在fat环境的db_config配置了各项参数并发布。
5.我在“child1”的fat环境里关联public namespace“db_config”后，在namespace表格里“当前公共namespace的所有者 parent 没有关联此namespace,请联系parent的所有者在parent项目里关联此namespace”

**Comment by xiabobin** [comment]
疑似BUG
我将通过数据库将创建的所有app、namespace全部删除，恢复到初始情况，然后在创建namespace就OK了，我怀疑这个问题是补全环境时补全数据不完整造成的。
出现问题：只有DEV环境时执行上述步骤后就出现问题。
解决问题：同时拥有DEV、FAT环境时，执行上述步骤无此问题

**Comment by nobodyiam** [comment]
补缺环境功能更多的是针对在已有环境下创建失败的场景，对于新增环境的场景，虽然在一定程度上可以实现功能，不过对于公共namespace可能没有默认创建namespace。

因为新增环境时有很多信息需要补，具体而言就是整个的app和appnamespace信息，以及所有的private namespace实例以及公共namespace在所挂项目中的实例。

所以，在新增环境的情况下，目前还是需要做一些手工的数据操作的。

**Comment by familylove** [comment]
现象描述：
在关联public namespace时，namespace的“公共的配置”表格提示“当前公共namespace的所有者 *** 没有关联此namespace,请联系的所有者在项目里关联此namespace”。
配置流程：
项目共分为4个环境，DEV，FAT，UAT，PRO，私有properties都已经发布PRO。
DEV环境创建一个新项目common-config，用于配置public common.properties，用于公共配置关联。
在DEV环境，其余项目都可以关联.
从DEV同步配置到TEST，UAT，PRO，重复关联操作，在UAT环境出现上述现象，DEV和PRO环境都是可以正常关联的。出现上述现象除了操作数据库，有其他的解决方案吗？

**Comment by nobodyiam** [comment]
到UAT环境的公共项目中关联common.properties即可

**Comment by familylove** [comment]
最后还是操作数据库，在数据库表appNameSpace补全一条记录来解决的。
界面上没法操作，返回BadRequest：400，namespace not exist。
findByNameAndIsPublicTrue这个查询结果是空。

**Comment by nobodyiam** [comment]
如果是appNamespace记录缺失的话，说明之前创建该项目时，UAT环境创建失败了，一般界面上会出现补缺环境按钮的。不过手工补一条记录也OK的。

**Comment by nobodyiam** [comment]
新增了相关的文档说明，可以参考一下：[2.1.2.1 从别的环境导入ApolloConfigDB的项目数据](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#2121-%E4%BB%8E%E5%88%AB%E7%9A%84%E7%8E%AF%E5%A2%83%E5%AF%BC%E5%85%A5apolloconfigdb%E7%9A%84%E9%A1%B9%E7%9B%AE%E6%95%B0%E6%8D%AE)。

**Comment by warlock-deng** [comment]
找到appnamespace表中该namespace，将ispublic改为1即可

**Comment by nobodyiam** [comment]
[1.2.0](https://github.com/ctripcorp/apollo/releases/tag/v1.2.0)版本已经发布，增加了『补缺Namespace』功能，支持补全缺失的公共namespace和私有namespace信息
