### ISSUE TITLE
阿波罗动态刷新properties 不重新启动项目，是否可把属性立即应用到项目上

### ISSUE THREAD

**Issue by guangmingchen** [ctripcorp/apollo#1087]
您好，spring boot 项目启动后，我想动态修改配置文件并生效，比如：在阿波罗中修改 server.port=8081
不重新启动项目 然后访问项目，端口变成8081，这个能做到吗

**Comment by lepdou** [comment]
这个取决于具体的配置项。不同的配置项，系统里使用的方式不一样。如果使用配置项的逻辑支持动态配置，那么就是支持，否则就不支持。Apollo提供了动态配置的能力，用不用这个动态能力，关键在于使用配置项的逻辑。
以server.port为例，server.port 应该是Spring boot启动的时候读取的，然后监听这个端口。如果Spring boot支持动态变更端口号，那么Spring Boot得获取到server.port变更事件，然后重新监听新的端口。这样就能现实动态改变端口了。
Spring Boot应该没有做这个逻辑的。或者说，Spring Boot提供了动态变更端口的口子，这样的话应用自己也可以监听Apollo配置变更的事件，然后通过这个口子去实现，也是可以的。
总的来说取决于Spring Boot有没有提供这种能力。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by apacheBright** [comment]
您好，群号多少
