### ISSUE TITLE
windows server2012 执行shutdown.sh没有反应

### ISSUE THREAD

**Issue by YINZHU2016** [ctripcorp/apollo#1088]
我在windows server2012上面挂在apollo项目，出现了下面的问题

执行startup.sh没有问题，但是我执行shutdown.sh的时候，在任务管理器里面发现java进程没有被杀掉。也没有看到界面上面弹出报错信息，我使用的是windows的powershell来执行的脚本

有兄弟知道该如何解决吗？谢谢

**Comment by nobodyiam** [comment]
powershell可以执行bash脚本？这个倒没测试过。。。不过shutdown.sh逻辑很简单的，可以尝试手动执行看看是哪里有问题。

**Comment by oooooooz** [comment]
@nobodyiam 我今天也碰到了这个问题，不过是 Redhat 上，比如 shutdown  portal ，脚本执行后实际又拉起了 portal。看了下，脚本是给 PortalApplication 送了个 stop 参数，但实际上 SpringApplication.run(PortalApplication.class, args) 的 args 参数识别不了 这个 stop 吧。是不是我使用的姿势哪里不对？麻烦解答

看打印日志，./$SERVICE_NAME".jar" stop 和 ./$SERVICE_NAME".jar" start 一样， 实际都是拉起应用，不过是重新绑定端口报错拉起失败

**Comment by nobodyiam** [comment]
这个参数不是给main函数的，是给jar头上的脚本的，你vi $SERVICE_NAME.jar就知道了。

**Comment by oooooooz** [comment]
明白了，多谢。如何在打包之前修改下这个脚本的？ @nobodyiam

**Comment by nobodyiam** [comment]
这个是spring boot打包的脚本，貌似没法修改，话说你也不需要修改啊

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
