### ISSUE TITLE
有关configservice的问题

### ISSUE THREAD

**Issue by oooooooz** [ctripcorp/apollo#1090]
您好，请问下为什么configservice 每个环境都要单独配置？多个环境共用一个 configservice 或者数量不与环境数据数量一致的话是有其他方面的影响吗 ?感谢

[https://github.com/ctripcorp/apollo/wiki/分布式部署指南](url)
`2.1.3.2 调整ApolloConfigDB配置
配置项统一存储在ApolloConfigDB.ServerConfig表中，需要注意每个环境的ApolloConfigDB.ServerConfig都需要单独配置 `

@nobodyiam

**Comment by lepdou** [comment]
可以看一下部署结构图，从图中可以看出，每个环境都需要部署一套config server + admin server。原因是，Apollo是通过config server 集群来区分环境的。config server部署在某个环境里，那么从这套config server获取的配置就是这个环境的。
![image](https://user-images.githubusercontent.com/4991116/39701953-abb66238-5235-11e8-93d4-60cdd3f4c93a.png)

如果部署多套config server比较麻烦的话，可以通过部署一套config server，然后通过cluster来区分环境。

**Comment by oooooooz** [comment]
我的理解是因为 config server 可以通过 apollo-env.properties 配置各个环境的 meta_server，然后 client 通过 meta server 去获取各自环境的配置，这样去理解的话，部署一个节点是不是没问题呢？@lepdou

**Comment by nobodyiam** [comment]
@oooooooz 部署一个节点本质上当然是可以的，不过在架构设计层面并不是一个很好的实践，本质上而言，我们还是希望每个环境之间是隔离的，互不影响。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
