### ISSUE TITLE
apollo分布式部署无法成功

### ISSUE THREAD

**Issue by YINZHU2016** [ctripcorp/apollo#1094]
我看了分布式部署的文档，并且按照文档进行配置，但是并没有得到对应的效果。我先讲一下我的配置方式哈
1、首先我打包了configservice和adminservice，使用的数据库连接字符串是localhost:3306.，并且将apollo的configserverdb.sql导入到了数据库，然后我在本地开启了configservice和adminservice的服务。

2、我把上面第一步打包好的configservice和adminservice，部署到了我的远程服务器server01,并且在他们的config目录里面加入了application-github.properties文件，填入了server01的mysql的数据库连接字符串。并且将apollo的configserverdb.sql导入到了数据库

3、我修改我本机的apollo的build.sh文件，将里面的meta的地址进行了修改
dev_meta=http://localhost:8080
fat_meta=http://server01的域名.com:8080
然后重新build。然后将build的portal启动起来。并且我修改了apolloportaldb的serverconfig数据库，给apollo.portal.envs赋值了value: dev,fat

但是现在的情况是，我创建一个application之后，在左侧的环境列表里面还是只能看见DEV选项。是我哪里配置有问题吗。我对比了文档，没有找到我哪一步是做错了。

补充，针对本地和server01环境的apolloconfigdb的数据库的serverconfig，我都配置了对应eureka.service.url的地址，**当然这2个地址我直接在浏览器上面是无法打开的**。我使用了apollo的0.10.2这个tag得分支进行的部署
http://localhost:8080/eureka/
http://server01的域名.com:8080/eureka/
能帮我看看不，谢谢

有一个疑问的地方是,我打开server01的eureka，截图部分的ip地址，和我实际的server01的ip地址完全不一样。点击红圈部分的地址，根本没有返回，是不是这个问题呢？

在补充一个发现的问题，就是我使用的server01的服务器是亚马逊的云服务器，并且安装的是windows server2012的操作系统，我在服务器上面使用ipconfig，发现server01的ip地址居然就是10.0.0.15
也就是说Eureka上面注册到的ip地址是错误的，不知道这个地方我该如何配置呢？

![34a4f2470dce1c4c8d142170524a24b7](https://user-images.githubusercontent.com/18044751/39739818-7ac92fb2-52c5-11e8-8f9c-1bc7384f7a77.png)

**Comment by YINZHU2016** [comment]
我发现eureka抓取的时候ec2的private ip address而不是ec2的域名或者它的public ip address

**Comment by nobodyiam** [comment]
这个应该是多网卡导致的IP注册问题，可以参考[分布式部署指南#14网络策略](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#14%E7%BD%91%E7%BB%9C%E7%AD%96%E7%95%A5)配置一下。

**Comment by YINZHU2016** [comment]
我按照文档配置并打包了程序，但是Eureka截图还是如下

**Comment by YINZHU2016** [comment]
我实验成功了
![9d26561523df9949b7ded98da9db3dd5](https://user-images.githubusercontent.com/18044751/39804520-cd256e2e-53a6-11e8-88dd-fdc841a13cba.png)

**Comment by nobodyiam** [comment]
恩，改yml是一种方式，另一种比较好的方式是通过-D传入，这样代码部署在不同的机器上都可以支持传入不同的IP了

**Comment by YINZHU2016** [comment]
@nobodyiam  确实是这样的，我看了你的文档，最后是有提出可以这样解决的问题。

在这里我提醒一下同样出现我这样问题的小伙伴几个注意点
1、认真看作者的文档，基本上所有的问题都有解决方案在里面
2、注意我这个问题，说道的修改yml文件，是**修改源代码里面的yml文件**，然后打包。
**不是修改打包以后的压缩包里面的yml文件**。这样是没有效果的。

**Comment by bigbenfather** [comment]
我的也是这种情况，注册的是主机名+端口号，用-D方式也不行

**Comment by YINZHU2016** [comment]
你要看看你的主机名和端口是否可以被你的客户端应用程序访问到呀。而且你的描述太简单了吧。建议仔细看作者的文档，是可以解决所有问题的。还有就是建议使用方案3来解决问题，
方案三：强制指定admin server和config server向eureka注册的IP和Port
修改apollo-adminservice或apollo-configservice 的bootstrap.yml文件，加入以下配置

eureka:
  instance:
    homePageUrl: http://${指定的IP}:${指定的Port}
    preferIpAddress: false
值得注意的一点是，上述的配置都可以通过JVM System Property在运行时传入，如-Deureka.instance.homePageUrl=http://${指定的IP}:${指定的Port}

**Comment by D-T-Y** [comment]
好郁闷，我也是出现使用方案3没作用，依然注册的是**主机名**，并不会注册我自定义的ip和端口

我是用的方式是：
eureka:
  instance:
    homePageUrl: http://${指定的IP}:${指定的Port}
    preferIpAddress: false

**Comment by WonderMing13** [comment]
homepageUrl 指向的是哪里？

**Comment by nobodyiam** [comment]
homepageUrl指向meta server的外网Ip和端口
