### ISSUE TITLE
不支持Mysql8.0

### ISSUE THREAD

**Issue by SmileTower** [ctripcorp/apollo#1096]
老驱动会报 Could not create connection to database server，
需要升级
`<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>5.1.46</version>
</dependency>`

**Comment by nobodyiam** [comment]
master代码已经支持mysql 8.0了，后续会在0.11.0发布支持，详见 #1147
