### ISSUE TITLE
namespace创建

### ISSUE THREAD

**Issue by sunguangran** [ctripcorp/apollo#1097]
新建namespace的时候，如果当前应用有多个集群，每个集群下都能看到一个同名namespace，并且里面的配置项都是单独发布的，这样是符合预期的吗？

**Comment by sunguangran** [comment]
我试了下public也是这样的，最新版本

**Comment by nobodyiam** [comment]
恩，是这样的。

如果是新创建的公共namespace，在所有集群下都会出现，如果他们配置没有分集群管理的需求，那么就只需要在default集群下配置即可，其它集群下的不用配置，也可以选择把不需要的namespace删除。

如果是应用关联namespace的话，只会出现在关联的集群中。

**Comment by sunguangran** [comment]
多谢
