### ISSUE TITLE
apollo-portal 加入context-path部署

### ISSUE THREAD

**Issue by jiji87432** [ctripcorp/apollo#1099]
您好：
问题描述：apollo-portal tomcat部署加入context-path，或者配置文件application.yml加上server.context-path后，eg：原来为http://localhost:8070，tomcat部署后，访问路径变为：http://127.0.0.1:8070/apollo-portal，然后启动访问很多访问静态资源找不到，访问路径也不找不到，这个是否需要对前台页面里面配置的路径做逐个修改？还是有个一统一的配置的地方？本人对angularjs不熟悉，是否是简单配置下就可以了，麻烦帮忙解答下，谢谢！

**Comment by jiji87432** [comment]
了解了，谢谢！由于公司现状是统一jekins部署，必须要求加上项目名称，如果这样的话，生产环境得需要申请单独部署。

**Comment by StoneYunZhao** [comment]
同样有增加 context-path 的需求。

**Comment by WANG352775707** [comment]
同样有增加 context-path 的需求

**Comment by RamboHsu** [comment]
同求π_π
或者直接把前端要改的东西整出来，自己去改就行

**Comment by ChuckyThh** [comment]
同样有增加 context-path 的需求

**Comment by nobodyiam** [comment]
#2754 已经支持context path了
