### ISSUE TITLE
客户端接入apollo-client的问题

### ISSUE THREAD

**Issue by rhaonan** [ctripcorp/apollo#1101]
看了目前客户端接入的方法，需要打包上传自己的仓库，总感觉这种方式有点奇怪，说下我的问题

目前我只搭建了DEV环境，我的想法是先在DEV环境试用一下，如果满足需求且稳定在申请线上库搭建PROD环境，但是我如果现在要试用就必须打包上传到公司的私有仓库了，可我之后还会修改添加PROD的META_SERVER在重新打包上传。那么我现在是不是必须把整个项目都改成SNAPSHOT版本再打包？请问你们的建议是什么？

**Comment by rhaonan** [comment]
或者说我要新增FAT或者其他环境，或者某个环境机器迁移需要更换域名或者IP，不是都需要打包上传capollo-client到私有仓库么，也就是说上传到公司私有仓库的apollo-client包是很有可能需要不断变化的，那么最好的方式是只打包SNAPSHOT版本的包到私有仓库么？

**Comment by lepdou** [comment]
如果只是在dev试用，你可以只install到你本地，不要deploy到公司私服，这个改一下脚本就好了。等全部部署完之后，在deploy一把到仓库就好了。

**Comment by rhaonan** [comment]
我install到本地只是我本地能用，并不是测试环境的机器上都能用啊。。。
我其实是在举例子说明，这个meta_server不会变的那么频繁，但肯定是有很多情况需要变的，我感觉现在这种使用方式不是很合理

**Comment by nobodyiam** [comment]
apollo-client已经推送到Maven中央仓库, [点击此链接查看](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.ctrip.framework.apollo%22%20AND%20a%3A%22apollo-client%22)
