### ISSUE TITLE
server端jdk版本的问题

### ISSUE THREAD

**Issue by zyllt** [ctripcorp/apollo#1103]
server端的环境要求必须是1.8+么，看了下代码主要是一些Lamdba表达式和新的api的使用，如果把这些替换掉可以降级为1.7么？

**Comment by lepdou** [comment]
因为Spring Boot 要求1.8版本，所以必须是1.8的

**Comment by zyllt** [comment]
spring-boot2.0之后才要求jdk1.8的呀，apollo使用的是1.3.8.RELEASE是支持1.7的。

**Comment by nobodyiam** [comment]
spring boot应该是可以支持1.7的，选择1.8作为server端的Java环境主要是我们想使用1.8的一些功能特性，不过使用的地方比较有限，所以应该可以降级到1.7。

你们公司是只能使用1.7？

**Comment by zyllt** [comment]
因为我们公司都是通过发布系统，jdk现在只有1.6和1.7可选。已经和运维提了适配1.8，不过还没给出具体时间表。而且还有个问题是域名也是在发布时候配置的，目前只有发布web项目才可以进行域名的配置，jar启动的话无法配置域名，所以现在还是要打包成war

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
