### ISSUE TITLE
新增环境后点补缺环境,新的环境中只自动添加了默认的application namespace,其他namespace没有添加

### ISSUE THREAD

**Issue by fifadxj** [ctripcorp/apollo#1108]
原来只有dev的时候已经有项目A,项目A配置了application.properties和jdbc.yaml两个namespace.
新增fat后,进入项目A,点补缺环境, FAT下只出现了application.properties,没有出现jdbc.yaml.
此时如果在FAT下新建jdbc.yaml,会报400namespace已存在错误.

**Comment by nobodyiam** [comment]
补缺环境功能更多的是针对在已有环境下创建失败的场景，对于新增环境的场景，虽然在一定程度上可以实现功能，不过对于非application可能没有默认创建namespace。

因为新增环境时有很多信息需要补，具体而言就是整个的app和appnamespace信息，以及所有的private namespace实例以及公共namespace在所挂项目中的实例。

所以，在新增环境的情况下，目前还是需要做一些手工的数据操作的。

**Comment by nobodyiam** [comment]
@fifadxj 新增了相关的文档说明，可以参考一下：[2.1.2.1 从别的环境导入ApolloConfigDB的项目数据](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#2121-%E4%BB%8E%E5%88%AB%E7%9A%84%E7%8E%AF%E5%A2%83%E5%AF%BC%E5%85%A5apolloconfigdb%E7%9A%84%E9%A1%B9%E7%9B%AE%E6%95%B0%E6%8D%AE)。

**Comment by fifadxj** [comment]
多谢！

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
