### ISSUE TITLE
请教一个部署apollo-client的问题

### ISSUE THREAD

**Issue by oooooooz** [ctripcorp/apollo#1110]
我想根据《分布式部署指南》2.8章节这个指引把客户端发布到 maven 私服，但发布的时候 maven 总是报这个错：Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project gnete: Failed to deploy artifacts/metadata: Cannot access ${releases.repo} with type default using the available connector factories: BasicRepositoryConnectorFactory: **Cannot access ${releases.repo}** using the registered transporter factories: WagonTransporterFactory: **Unsupported transport protocol**

看错误是访问不了 maven 在settings.xml 中配置的属性，不支持协议，引入了 <artifactId>wagon-file</artifactId> 这个依赖也是不行，请教下你们是怎么解决这个问题的？Google 了一圈，没找到解决方案。非常感谢！望解答 @nobodyiam 

以下是 《分布式部署指南》2.8章节 的指导内容：

> 注：deploy操作需要在.m2/settings.xml中设置releases.repo和snapshots.repo属性以及对应仓库的用户名和密码（注意server的id必须是releases和snapshots）
> 
> <profiles>
>     <profile>
>         <id>dev</id>
>         <activation>
>             <activeByDefault>true</activeByDefault>
>         </activation>
>         <properties>
>              <releases.repo>http://${your_nexus_url}/nexus/content/repositories/${release-repository}</releases.repo>
>              <snapshots.repo>http://${your_nexus_url}/nexus/content/repositories/${snapshotrepository}</snapshots.repo>
>         </properties>
>      </profile>
> </profiles>

**Comment by nobodyiam** [comment]
照着分布式部署指南中的内容做就可以了，你看一下settings.xml里面是不是没有配置releases.repo属性。

**Comment by oooooooz** [comment]
有配的，但就是读不到，可能是环境的问题，我再研究下，感谢 @nobodyiam

**Comment by nobodyiam** [comment]
apollo-client已经推送到Maven中央仓库, [点击此链接查看](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.ctrip.framework.apollo%22%20AND%20a%3A%22apollo-client%22)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
