### ISSUE TITLE
jvm 参数设置

### ISSUE THREAD

**Issue by YINZHU2016** [ctripcorp/apollo#1111]
你好，我在使用你们的服务做公司的配置中心，但是实际上我们公司的对接配置中心的客户端当前情况最多也不会超过20个。但是我部署configservice,adminservice,portalservice的服务器的时候，发现他们的java进行耗费都在300-400M之间，感觉有点大了呢，我看了您的文章说可以修改startup.sh里面的jvm参数，但是我不知道我这种情况，这些参数我怎样设置会比较合理。担心设置错误了又导致程序会出现不稳定的情况。

**Comment by nobodyiam** [comment]
目前默认的startup.sh脚本并没有指定JVM的堆大小，所以也没啥可调的，除非你希望他们再小一些。

300-400M其实已经很小了，不过实在要调小的话，虽然不建议，也还是可以试一试的（参照startup.sh中被注释掉的-Xms，-Xmx等参数），不过要观察一下调小后的GC情况。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by CHANGEX929** [comment]
> 你好，我在使用你们的服务做公司的配置中心，但是实际上我们公司的对接配置中心的客户端当前情况最多也不会超过20个。但是我部署的ConfigService，adminservice，portalservice的服务器的时候，发现他们的java的进行耗费都在300-400M之间，感觉有点大了呢，我看了您的文章说可以修改startup.sh里面的JVM参数，但是我不知道我这种情况，这些参数我怎样设置会比较合理。担心设置错误了又导致程序会出现不稳定的情况。

你好，我现在也想知道这个参数设置成多少会比较合适，目前我们公司把dev、fat、uat三个环境部署在同一台主机上，目前有点不太够用了。我想知道JVM参数设置成多少才会比较好。

**Comment by nobodyiam** [comment]
JVM参数设置要根据实际情况调整的，可以看下gc log，jstat等信息
