### ISSUE TITLE
apollo 启动异常

### ISSUE THREAD

**Issue by qushiba** [ctripcorp/apollo#1112]
启动异常, 未获取到配置
![c1](https://user-images.githubusercontent.com/6980743/40052166-c62266a4-586f-11e8-9f1b-b52a13bbd997.png)
![fc](https://user-images.githubusercontent.com/6980743/40052169-c83a0f46-586f-11e8-9637-2a79f616a302.png)

**Comment by nobodyiam** [comment]
从你的堆栈看，guava的版本是14，太低了，apollo最低要求是15

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
