### ISSUE TITLE
参数配置过于简单化了，能不能支持复杂一点的？

### ISSUE THREAD

**Issue by xiewsh** [ctripcorp/apollo#1114]
如：像数据库表格一样，或者excell格式一样

**Comment by nobodyiam** [comment]
多谢建议，确实是想支持复杂格式的，不过限于资源和精力，目前还没实现。

https://github.com/ctripcorp/apollo/projects/1

![image](https://user-images.githubusercontent.com/837658/40150616-31eb110e-59ad-11e8-8e24-516389ccb71c.png)
