### ISSUE TITLE
项目管理和回滚的问题

### ISSUE THREAD

**Issue by coolieo** [ctripcorp/apollo#1117]
分布式部署的release0.10.2版本，发现问题如下
一，项目的权限问题
 1. 只有项目的创建者能对私有的application namespace进行key的添加，而项目的所有者竟然不可以？
 2. 项目管理员是可以对该项目进行新的namespace进行创建，但是这个管理员登录portal后为什么在我的项目里面没有？这里我特意看了下代码，我的项目只是owner的list。而项目管理者不在其中，那么作为项目的管理员尴尬了需要从哪个入口去找项目呢？
二，回滚问题
亲测release0.10.2这个版本的回滚是不成功的。想咨询下官方这个是bug么,还是我使用的姿势不对啊？

@nobodyiam 
以上盼复，谢谢。

**Comment by nobodyiam** [comment]
项目的所有者拥有的是项目的权限管理能力，不代表他一定需要去修改或发布配置，当然，他自己是可以给自己授权的。

apollo的页面最上方可以搜索项目的

回滚针对的是客户端获取到的配置，不是你在页面上看到的配置，类似于在发布系统做回滚动作，回滚的是部署到机器上的包，而不是你的代码。

**Comment by coolieo** [comment]
谢谢@nobodyiam的解答
确认回滚之后，客户端是读取到相应的回滚配置了。
那配置中心里面的配置项 是 需要回滚之后再 手动去编辑再发布么？

**Comment by oooooooz** [comment]
应用的配置以最新的发布为准 @coolieo

**Comment by nobodyiam** [comment]
@coolieo 是的，就像代码出bug了，回滚完发布的包之后，自己再修改完代码重新发布一样的。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
