### ISSUE TITLE
关于apollo客户端启动连接时间过长问题？

### ISSUE THREAD

**Issue by xiewsh** [ctripcorp/apollo#1118]
目前我们这边应用集成了apollo，在调用ConfigService.getAppConfig()的时候，要花十几秒的时间，请问是什么原因？

**Comment by nobodyiam** [comment]
启动时间长一般是由于获取配置失败，然后客户端多次重试所致，建议配置logback, log4j2等，并且打开WARN级别以上日志。

**Comment by xiewsh** [comment]
日志我们是配置的，应该不是获取配置失败导致的，因为同样的配置在不同人的电脑上启动时间相差很大，有的人将近20秒，有的人只需1秒左右，大家的pc都在同一个网段，只是操作系统不一样。

**Comment by nobodyiam** [comment]
可以看看是不是[findValidateIp](https://github.com/ctripcorp/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/foundation/internals/NetworkInterfaceManager.java#L25)消耗了比较多的时间，之前有遇到过有些机器反解host name非常慢的情况。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
