### ISSUE TITLE
对于客户端jar包个环境地址配置的一点建议

### ISSUE THREAD

**Issue by spenxu** [ctripcorp/apollo#1119]
目前apollo 是把各个环境地址打进jar包，同时可以通过指定系统属性来覆盖jar包中的地址。很多同事在使用过程中感觉很怪异。针对这一点我觉得可以吧配置开放给使用者。让应用去配置，三种方式可以并存,优先级如下：
系统属性 > 应用自己的配置 > jar包中的配置

**Comment by nobodyiam** [comment]
感谢建议，环境这块我们还是认为和应用本身无关，不过目前这块确实比较麻烦，后续我们会考虑在客户端弱化环境的概念，由系统直接配置meta server地址即可，比如：

server.properties:
```properties
apollo.meta=http://xxx
```

**Comment by nobodyiam** [comment]
新版本的apollo-client已经支持可以通过各个层级配置meta server地址了，具体可以参考 [1.2.2 Apollo Meta Server](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#122-apollo-meta-server)，另外，1.0.0版本可以直接使用Maven中央仓库中的版本。

case先关闭了，如还有问题，可以提供更多信息，或进群交流。
