### ISSUE TITLE
部署后登陆报错

### ISSUE THREAD

**Issue by seguzhizi** [ctripcorp/apollo#1120]
在portal登陆界面，输入用户名和密码之后，提示如下错误：
{"exception":"ogr.springframework.web.HttpRequetMethodNotSupportedException","message":"Request method \u002POST\u002 not supported","status":"400","timestamp":"2018-05-21"}

查了一下，说的是不支持'POST'请求，我看代码中的/singin请求仅仅接收GET类型的请求，不知道能否将此限制打开？

另外，部署完毕，重启之后，此问题可能会消失。。。

不知道其他人是否遇到过此问题。。。

**Comment by nobodyiam** [comment]
你用的是默认spring security的登录实现吧，/signin其实只是重定向到登录界面，所以是GET请求。

真正的处理请求是由spring security处理的，如果还能重现的话，可以把步骤列一下，我们看看是不是spring security的配置问题。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
