### ISSUE TITLE
是否有接口可以通过后台将配置数据插入数据库？

### ISSUE THREAD

**Issue by xiewsh** [ctripcorp/apollo#1121]

**Comment by nobodyiam** [comment]
通过[开放平台](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0)可以实现

**Comment by xiewsh** [comment]
http://{portal_address}/open/manage.html    portal_address ->是配置中心的地址是吗？我访问的时候一直跳转到http://{portal_address}/sign 界面

**Comment by jieqian** [comment]
@xiewsh 建议你读一下portal项目下的open package的源码，红框标示了入口，当然还要注意他的auth机制，具体可以看一下ConsumerPermissionValidator这个类。
![image](https://user-images.githubusercontent.com/4167422/40523714-93c07b1e-6009-11e8-9f7f-949c2b6d3d90.png)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
