### ISSUE TITLE
apollo分布式部署出现问题，求教

### ISSUE THREAD

**Issue by sunnyvinson** [ctripcorp/apollo#1122]
项目源码下apollo-master/scripts/build.sh 修改了数据路连接信息，
apollo_portal_db_url=jdbc:mysql://localhost:3306/ApolloPortalDB?characterEncoding=utf8
apollo_portal_db_username=root
apollo_portal_db_password=root
dev_meta=http://localhost:8100

然后打包，然后解压了apollo-configservice-0.11.0-SNAPSHOT-github.zip，修改了的server port =8100，最后运行/scripts/startup.sh，结果是报错的，日志显示无法连接数据库，请问  我的做法是存在错误吗？什么原因呢？谢谢

**Comment by nobodyiam** [comment]
无法连接数据库，那一般就是数据库的连接串有问题，可以仔细看下报错的日志。

**Comment by sunnyvinson** [comment]
我的目的是想做分布式部署，上面的总体流程，请问是正确的吗？

**Comment by nobodyiam** [comment]
具体流程按照[分布式部署指南](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97)一步一步做就没问题的

**Comment by CHF00123** [comment]
./build.sh后一切正常，然后解压apollo-configservice-0.11.0-SNAPSHOT-github.zip后到scripts下执行./start.sh后返回到上一级生成apollo-configservice.jar，下次运行的时候直接java -jar  apollo-configservice.jar，报错Could not autowire field: private javax.sql.DataSource org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration.dataSource; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceAutoConfiguration$NonEmbeddedConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Cannot determine embedded database driver class for database type NONE. If you want an embedded database please put a supported one on the classpath. If you have database settings to be loaded from a particular profile you may need to active it (the profiles "github" are currently active).
前几天运行还好好的，今天突然就挂了，我没改什么其他地方

**Comment by jieqian** [comment]
@CHF00123 直接sh script/start.sh就好了啊，然后到start.sh里定义的$LOG_DIR中去tail log看看哪里报错。不需要自己去java -jar apollo-configservice.jar，因为你这个启动命令其实漏了很多jvm配置参数和环境变量参数，具体你也可以自己去看一下start.sh

**Comment by CHF00123** [comment]
bash-3.2# sh scripts/startup.sh
Wed May 30 11:15:12 CST 2018 ==== Starting ====
su: illegal option -- 
usage: su [-] [-flm] [login [args]
Failed to star
Wed May 30 11:15:12 CST 2018 Failed to start apollo-configservice.jar, return code: 
 tail -f apollo-configservice_usrlocalapolloconfigservice.log 查看日志什么也没打
-----------------------------------------------------------------
发件人：jieqian <notifications@github.com
发送时间：2018年5月30日(星期三) 11:0
收件人：ctripcorp/apollo <apollo@noreply.github.com
抄　送：CHF00123 <chenhoufei123@dingtalk.com>; Mention <mention@noreply.github.com
主　题：Re: [ctripcorp/apollo] apollo分布式部署出现问题，求教 (#1122
@CHF00123 直接sh script/start.sh就好了啊，然后到start.sh里定义的$LOG_DIR中去tail log看看哪里报错。不需要自己去java -jar apollo-configservice.jar，因为你这个启动命令其实漏了很多jvm配置参数和环境变量参数，具体你也可以自己去看一下start.s

**Comment by jieqian** [comment]
可能是你的权限不够吧，你用su sh script/start.sh看看？

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
