### ISSUE TITLE
多个项目互相依赖APPID会取错

### ISSUE THREAD

**Issue by zuoyixiao** [ctripcorp/apollo#1123]
场景：
A项目的appid=project-a，B项目的appid=project-b，在apollo里分别配置为两个项目。
A项目依赖B项目，在启动A项目的时候，通过日志发现appid被设置为project-b，这就导致取不到A项目的配置。
apollo版本是0.10.2

分析：
发现将DefaultApplicationProvider类initialize()方法中取配置文件的逻辑调转一下就可以解决。
求助，是这里的问题吗？
![image](https://user-images.githubusercontent.com/20982820/40338721-5a486c1e-5da9-11e8-9347-eef769a06033.png)

**Comment by zuoyixiao** [comment]
apollo版本是0.10.2

**Comment by nobodyiam** [comment]
appid是应用的身份标识，如果A依赖了B.jar，那B.jar里面就不应该有app.properties，因为B并不是一个独立的应用，不应该有app.properties。

**Comment by zuoyixiao** [comment]
谢谢答复。由于代码历史原因，现在的应用场景就是B.jar既是独立的应用，A还依赖它...

**Comment by nobodyiam** [comment]
如果是这样的话，那可以通过-Dapp.id=A传入，这个优先级最高

**Comment by zuoyixiao** [comment]
好的，谢谢！

**Comment by zuoyixiao** [comment]
但是我们现在都是spring boot项目，每个微服务都是独立的项目，这种情况咋办？

**Comment by jieqian** [comment]
@zuoyixiao 我们是自己写bootstrap autoconfiguration，然后System.setProperty("app.id","your_app_id"), 然后抽成一个公共的starter，让各个微服务项目的pom去继承

**Comment by nobodyiam** [comment]
微服务是以服务的形式对外提供服务的，而不是jar包。

如果你提供的是个jar包，那它就不应该有app.id，因为它不是一个独立的应用，它是另一个应用的一个组件而已。

对这个jar包，它应该只能获取公共的配置或者是共享应用的配置。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by yws-tracy** [comment]
> 微服务是以服务的形式对外提供服务的，而不是jar包。
> 
> 如果你提供的是个jar包，那它就不应该有app.id，因为它不是一个独立的应用，它是另一个应用的一个组件而已。
> 
> 对这个jar包，它应该只能获取公共的配置或者是共享应用的配置。

jar 包他也有自己的配置，属于某个团队维护，可能是一些基础组件，和业务使用apollo 想完全隔离， 为啥不能使用appID， 这块感觉 apollo 的设计不太合理，
