### ISSUE TITLE
【Portal部署在生产环境的机房，通过它来直接管理FAT、UAT、PRO等环境的配置】分布式部署的这句话

### ISSUE THREAD

**Issue by sunnyvinson** [ctripcorp/apollo#1125]
这句话没理解过来，换白话说就是：
prod环境部署了protal、config、admin；
dev环境部署了config、admin，有一个java项目，配置了dev_meta、appid；
fat环境部署了config、admin，有一个java项目，配置了dev_meta、appid；

请问，prod环境下的配置信息是怎么样传送到了dev和fat环境下的？或者说，图上的红色框框里的那句话如何理解？

我现在的一个理解，还请指正指正：prod环境是有配置portal图形化界面进行人工配置的，假设里面有一个项目test，appid是test001。另一个环境dev，要使用到这个test项目的配置信息，需要配置appid=test001，dev_meta=xxxxxxx，这个dev_meta是什么作用呢？ 

谢谢！

**Comment by jieqian** [comment]
首先讲一下数据库:
apollo portal db就一个，不分环境，只部署在生产环境；
apollo config db分环境部署，每个环境都一个apollo config db；
portal db中存的是和展示有关的数据，各个环境中的config db才存的是真正的配置；

调用方式：
通过操作portal展示的页面，把操作的参数传给admin server(操作包括查询，修改和发布配置等), admin server会把相应的写操作存储到config db中(按环境来，如果是添加dev环境的配置，那就把新增配置告诉dev环境部署的admin server，然后存到dev环境的config db)
admin server和config server交互方式是，config server通过监听数据库配置版本信息的变化，来更新config server这个java应用中内存的值；
apollo client通过推拉结合的方式来向config server获取最新的配置，具体问哪个config server就取决于你的xxx_meta了

**Comment by sunnyvinson** [comment]
嗯嗯，看你的讲解之后清晰多了，以后再看你们源码，谢谢你，刚刚集成多环境成功了

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
