### ISSUE TITLE
源码pom文件报错

### ISSUE THREAD

**Issue by shiqianzhen** [ctripcorp/apollo#1126]
报错找不到jar  或者事插件。所缺失的jar我该去哪儿下载？在百度上没有找到.

**Comment by jieqian** [comment]
能把报错信息贴出来看看吗？

**Comment by shiqianzhen** [comment]
Plugin  ‘com.github.github:site-maven-plugin0.12 not found  less
Inspects  a  Maven  model  for   resolution   problems


Cannot  resolve  symbol   giyhub.path less  
Inspects  a  Maven  model  for   resolution   problems

**Comment by shiqianzhen** [comment]
基本上就是这两种报错，我该在呢吗处理，注销掉，有些java文件会报错，百度上下载这些插件。没有找到

**Comment by nobodyiam** [comment]
看上去是你的maven有点问题，你要不设置下[阿里云maven](http://www.cnblogs.com/geektown/p/5705405.html)试试吧

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
