### ISSUE TITLE
notifications/v2.  404該如何解決

### ISSUE THREAD

**Issue by JimChung0403** [ctripcorp/apollo#1127]
請求：
http://127.0.0.1:8070/notifications/v2?appId=JimApp&cluster=default&notifications=%5B%7B%22namespaceName%22%3A%20%22application%22%2C%20%22notificationId%22%3A%20100%7D%5D

返回：
{"timestamp":"2018-05-23T14:46:42.845+0800","status":404,"error":"Not Found","message":"No message available","path":"/notifications/v2"}

**Comment by nobodyiam** [comment]
8070是portal的端口还是config service的端口？

感觉是你哪里配错了的样子。

**Comment by jieqian** [comment]
@nobodyiam 我已经帮他解决了，他调用了portal的端口才会这样的。他用的是agollo客户端，还有些坑，等有时间了，我fork一下
