### ISSUE TITLE
client使用jdk版本问题

### ISSUE THREAD

**Issue by LucienMoMo** [ctripcorp/apollo#1128]
我将打好的apollo-core,apollo-client（jdk1.8）上传到公司的私服了。
maven依赖得到的jar，jdk1.8可以正常运行，jdk1.7报错。
报错为：java.lang.UnsupportedClassVersionError: com/google/common/base/Strings : Unsupported major.minor version 52.0。
求指教

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
