### ISSUE TITLE
分布式部署指南文档问题

### ISSUE THREAD

**Issue by youngvery** [ctripcorp/apollo#1129]
> 2.1.3.2 调整ApolloConfigDB配置
> 2.namespace.lock.switch - 一次发布只能有一个人修改开关
> 这是一个功能开关，如果配置为true的话，那么一次配置发布只能是一个人修改，另一个发布。
以上是原文内容，关于namespace.lock.switch的解释，**只能是一个人修改，另一个发布**意思是1.一个人修改完成后必须换另一个账号登陆来发布？2.只允许当前修改完成后，另外的人不能修改了，必须等此次发布完成后才能继续的修改发布？

**Comment by nobodyiam** [comment]
是的，这个看你们实际需求决定是否打开。

我们做这个开关的目的是：

1. 确保修改的配置由另一个人审核后再发布
2. 确保生产配置一次只能一个人修改，以避免配置冲突

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
