### ISSUE TITLE
Apollo Quick Start Docker部署，eureka使用的还是docker ip

### ISSUE THREAD

**Issue by chiwenheng** [ctripcorp/apollo#1130]
你好，我根据apollo 上面docker部署步骤，部署成功，但是配置client 发现，ip为docker 内部ip，如何解决？这个docker镜像目前里面 eureka 的APOLLO-CONFIGSERVICE 和 APOLLO-ADMINSERVICE 注册都是docker内部ip。而在 分布式部署指南 中 写到 要进行spring:
      application:
          name: apollo-configservice
      profiles:
        active: ${apollo_profile}
      cloud:
        inetutils:
          ignoredInterfaces:
            - docker0
            - veth.*
那就是，官网的docker ，只能本地访问 ？ 我怎么替换里面的 apollo-all-in-one.jar 里面的配置信息呢？

**Comment by nobodyiam** [comment]
quick start是做demo使用的，如果是分布式部署，还请参考分布式部署文档。

另外，在项目中也有Dockfile的，可以自己做docker部署。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
