### ISSUE TITLE
apollo-env.properties 环境多meta配置

### ISSUE THREAD

**Issue by LucienMoMo** [ctripcorp/apollo#1133]
例如我的fat环境中在数据库中ApolloConfigDB.ServerConfig.eureka.service.url=http://192.168.8.100:8080/eureka/,http://192.168.8.101:8080/eureka/.
那么我在apollo-env.properties中的fat.meta的值怎么填写。因为配置两个eureka肯定想做自动切换在我的client读取的时候。
目前已知fat.meta=http://192.168.8.100:8080/eureka/或fat.meta=http://192.168.8.101:8080/eureka/这样子单独读一台没有问题。fat.meta=http://192.168.8.100:8080/eureka/,http://192.168.8.101:8080/eureka/，这样子填写有问题。

**Comment by jieqian** [comment]
@LucienMoMo 用域名，不要用ip地址；域名的话就是DNS服务器指向一个或一组nginx，让nginx来做lb

**Comment by LucienMoMo** [comment]
@jieqian 那这个apollo内置有NGINX没有，有的话怎么弄

**Comment by jieqian** [comment]
@LucienMoMo apollo和nginx没有任何关系，这个是需要运维来配置的

**Comment by nobodyiam** [comment]
PR #1214 支持填入以逗号分隔的多个meta service地址了，会在0.11.0版本发布。
