### ISSUE TITLE
源码pom文件报错

### ISSUE THREAD

**Issue by shiqianzhen** [ctripcorp/apollo#1134]
里面有很多插件和jar无法下载。
报错信息为Cannot  resolve  symbol   giyhub.path less  
Inspects  a  Maven  model  for   resolution   problems

Cannot  resolve  symbol  'adminServiceApplication'。
我重新下载了maven3.5.3,配置了阿里云
<mirrors>
    <mirror>
      <id>alimaven</id>
      <name>aliyun maven</name>
      <url>http://maven.aliyun.com/nexus/content/groups/public/</url>
      <mirrorOf>central</mirrorOf>        
    </mirror>
  </mirrors>
更新maven项目，还是一样报错。
请问我该如何解决，pom报错？

**Comment by shiqianzhen** [comment]
你好！  
我在maven  下面建立 bliud   在 
 working  directory   是存放源码的路径
Command  line       执行  mvn  clean  compile
profiles  是  dev
 执行 命令之后还是有不少插件无法下载
  非常期待您的回复！！！

**Comment by jieqian** [comment]
正常情况下默认的profile是github, 你看看项目根目录的pom是否被改过了，还有就是清理一下本机.m2目录下的repository中的那些失败的插件的文件夹

```
                <profile>
			<!-- for open source usage -->
			<id>github</id>
			<properties>
				<package.environment>github</package.environment>
			</properties>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
		</profile>
```

**Comment by nobodyiam** [comment]
有些插件没下载下来你是指在ide里面看到是标红的？有些插件是在travis profile下才会用到的。

只要compile ok就没有问题了。

**Comment by shiqianzhen** [comment]
哪些没有下载下来的插件不会影响程序的正常启动对吗？
打包是把所有的程序打成一个jar吗？
就可以启动运行。

**Comment by nobodyiam** [comment]
不影响，那些是给travis ci用的

**Comment by jieqian** [comment]
@shiqianzhen 建议使用命令行来执行maven的各种操作，因为各种IDE里的maven plugin的执行动作，你不一定知道到底执行了哪些命令

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
