### ISSUE TITLE
git bash启动./demo.sh  start  日志文件报错（window环境）

### ISSUE THREAD

**Issue by shiqianzhen** [ctripcorp/apollo#1135]
com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server

com.sun.jersey.api.client.ClientHandlerException: org.apache.http.conn.ConnectTimeoutException: Connect to 10.168.16.125:8080 timed out

**Comment by nobodyiam** [comment]
Connect to 10.168.16.125:8080 timed out，这个错误看上去是这个ip连不上？

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
