### ISSUE TITLE
部署时出现env is down

### ISSUE THREAD

**Issue by LucienMoMo** [ctripcorp/apollo#1136]
我在生产上打算部署为uat的环境。
打包时未传入数据库连接和meta信息
![image](https://user-images.githubusercontent.com/30652095/40486699-91e3a37c-5f94-11e8-951c-d0b63bf7cc8c.png)
在adminservice和configservice的config目录下指定了apolloconfigdb的连接信息，在portalservice的config目录下制定了apolloportaldb的连接信息。
portaldb
![image](https://user-images.githubusercontent.com/30652095/40486789-e0160eea-5f94-11e8-8975-ca91f3a740f1.png)
configdb
![image](https://user-images.githubusercontent.com/30652095/40486800-ea3e2506-5f94-11e8-9fee-7c6ab4a51a31.png)
在启动时，一直在protal的日志出现以下错误
![image](https://user-images.githubusercontent.com/30652095/40486848-081aff2c-5f95-11e8-9e82-593bd746ba00.png)
显示portal找不到meta地址，我在/opt/settings/server.properties配置了env=uat

**Comment by nobodyiam** [comment]
portal是从apollo-core.jar中的apollo-env.properties中获取uat.meta信息，可以看下这个配置是否正确。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
