### ISSUE TITLE
portal登陆问题

### ISSUE THREAD

**Issue by seguzhizi** [ctripcorp/apollo#1139]
由于要将portal接入公司登陆，故参看了portal登陆的wiki
我的实现如下：
1：实现了required 接口：UserService和UserInfoHolder
2：注释掉了profile("auth")，仿造profile=default的实现，写了profile=("um")
3：运行时，传入github,um
portal启动后，点击登陆，报错如下：
{"exception":"org.springframework.web.HttpRequestMethodNotSupportedException","message":"Request method \u0027POST\u0027 not supported","status":400,"timestamp":"2018-05-29T01:00:34.465"}

后来我恢复后，尝试使用default模式，仍然不能登陆，和上述报错一致
是否因为登陆界面只能用于security模式登陆？
请问下，接入公司的SSO的话，是使用公司的登陆界面还是当前的portal的登陆界面？

为此，我也尝试自己写一个登陆界面，后台对应一个/login方法，处理完毕，返回index.html，但事实并未返回到此界面，也是报了上述错误。。。有点费解，望协助下，谢谢~！

**Comment by nobodyiam** [comment]
如果是接入公司SSO的话，应该是要走公司的登录界面的。

你可以参考下ctrip的实现，我们就是走的公司的CAS SSO实现。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
