### ISSUE TITLE
客户端访问是否有身份认证机制？

### ISSUE THREAD

**Issue by goace** [ctripcorp/apollo#1140]
请问客户端访问configserver的时候是否支持https以及身份认证？
主要还是怕关键配置泄露，看了之前的讨论，数据两端加密/解密还是有点蛋疼，如果能有身份认证以及加密传输，这个问题基本就解决了。

**Comment by nobodyiam** [comment]
https理论上是可以支持的，不过由于是ip直连的，所以你需要在每台config service上部署证书。

身份认证理论上也可以的，在config service那里加一个filter拦截一下就可以了，不过需要解决身份认证信息下发的问题。
