### ISSUE TITLE
wiki 错误

### ISSUE THREAD

**Issue by chendifan** [ctripcorp/apollo#1142]
https://github.com/ctripcorp/apollo/wiki/Apollo%E6%A0%B8%E5%BF%83%E6%A6%82%E5%BF%B5%E4%B9%8B%E2%80%9CNamespace%E2%80%9D#542-%E5%BA%94%E7%94%A8b%E8%8E%B7%E5%8F%96apollo%E9%85%8D%E7%BD%AE

k3=v32

**Comment by nobodyiam** [comment]
Thanks!
