### ISSUE TITLE
apollo登入后，怎么获取到session

### ISSUE THREAD

**Issue by sunnyvinson** [ctripcorp/apollo#1143]
在自己的管理系统中发起一个apollo登入请求后。发现一次登入流程返回的session不出现在response header中，我该怎么抓取到这个session，我期望拿着这个session一直在我的后台管理系统中长期保持正常登入的状态

**Comment by jieqian** [comment]
session持久化到redis中去

**Comment by nobodyiam** [comment]
管理系统建议通过open api访问apollo。

如果实在想通过portal的接口访问的话。。。也不是不可以，把cookie中的JSESSIONID传过去就好了。

**Comment by sunnyvinson** [comment]
已经取到session了，谢谢二位

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
