### ISSUE TITLE
client的问题

### ISSUE THREAD

**Issue by he-yuan** [ctripcorp/apollo#1145]
请问一下，我用docker部署了个apollo，然后我用springboot项目去连接的时候报错，我看了一下日志，客户端请求的ip是我apollo所在服务器的内网ip，请问为什么会发生这种情况呢

**Comment by nobodyiam** [comment]
参考一下 [网络策略](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#14%E7%BD%91%E7%BB%9C%E7%AD%96%E7%95%A5)吧

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
