### ISSUE TITLE
client api 支持修改配置项

### ISSUE THREAD

**Issue by linzhouzhi** [ctripcorp/apollo#1146]
希望可以通过client来修改配置项，有这样的情况 我们需要根据服务的状态来判断服务的上下线，这种情况下判断服务的状态的是一个 java client 我希望通过 config.setProperty("status", "false") 这样来下线服务

**Comment by JavaXiaoJun** [comment]
这种写配置的操作还是很常见的，client api有必要支持一下

**Comment by qmwu2000** [comment]
不能在client api中修改配置是apollo在设计时特意安排的，我们希望apollo client只能取得配置信息，不能修改配置。

因为配置变更本质上是一次运维变更，它是高风险活动，需要事先经过测试验证，需要更加严谨的变更流程去约束，需要周知到相关方，甚至不能由同一个人去完成（很多行业/公司有这样的要求）。

另外在client上直接修改配置值，会给apollo在服务端和客户端的双重缓存机制带来挑战，理解和管理复杂度都会变高，本来的确定性问题会转变成不确定性问题。

当然如果你非要这么做，你可以使用apollo admin open api搞定一切。


发自我的 iPhone

**Comment by jieqian** [comment]
@linzhouzhi 如果有这种api的话，开发人员会把Apollo当成数据库用了。当然Apollo也是开发了open api，即通过restful接口的形式来对配置进行crud，具体可参考[Apollo开放平台](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0)

**Comment by jieqian** [comment]
你这个路径得看源码中portal这个module的open api包下那些controller类了，比如获取指定的cluster信息
http://localhost:8080/openapi/v1/envs/dev/apps/online_sdk_log/clusters/20170823111603-fea14b9b29292591/namespaces

**Comment by nobodyiam** [comment]
看图中被管理的appid是`hierarchy`，所以url路径中其实应该也是`hierarchy`，而不是`1220`？

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
