### ISSUE TITLE
Apollo如何支持一个应用的多版本

### ISSUE THREAD

**Issue by otyyyywangwenbin** [ctripcorp/apollo#1148]
如果一个应用在运行期同时存在v1.1和v1.2这二个版本，可以在apollo里通过一个AppId实现管理这2个版本的配置吗？该如何实现？谢谢

- 现在可以通过apollo的[灰度发布]配合自己的实现从eureka中选择不同版本实例，进行配置管理

- apollo会考虑直接支持eureka的instance.metadata里增加一个version的属性吗？

**Comment by otyyyywangwenbin** [comment]
现在可以通过apollo的 灰度发布 配合自己的实现从eureka中选择不同版本实例，进行配置管理

**Comment by jieqian** [comment]
或者你可以考虑用多个namespace

**Comment by otyyyywangwenbin** [comment]
@jieqian 👌，谢谢

**Comment by nobodyiam** [comment]
如果配置完全不一样的话，可以考虑使用不同的namespace，也可以考虑使用cluster

**Comment by jieqian** [comment]
@nobodyiam 还有种情况是测试环境同一个项目有大于2个的分支(如果是2个，可以用Apollo的主版本和grey branch来区分配置)需要上线，如果用多个namespace或cluster来区分不同配置的话，还得改代码。希望能在下一个roadmap里满足这个需求^_^

**Comment by jieqian** [comment]
恩，我也想过，但对于强迫症的我来说，测完是一定要删cluster的😝

**Comment by nobodyiam** [comment]
删除cluster功能已经可以通过 管理员工具 实现了。

case先关闭了，如还有问题，可以提供更多信息，或进群交流。
