### ISSUE TITLE
请教一下分布式部署下多个config server连接问题

### ISSUE THREAD

**Issue by RickJou** [ctripcorp/apollo#1151]
那么portal 是如何连接admin server呢?
是通过

```
set dev_meta=http://apollo-dev-config:8080  

set fat_meta=http://apollo-fat-config:8080  

set uat_meta=http://apollo-uat-config:8080  

set pro_meta=http://apollo-pro-config:8080 
```

打包时设置的meta server的地址,然后通过HTTP连接到meta server中,获取所有的eureka上的admin server服务地址吗?
如果是这个,那么比如pro环境下部署了4个节点,每个节点都有 admin/config/portal进程.那么是不是要在4个config server节点的前方设置一个Nginx 做分发? (由于 pro_meta=xxx 只能设置一个地址)
如将 http://apollo-pro-config  分发到实际的四个部署节点
另外portal本身部署了多份,那么也应该将其放置在Nginx之后.
我这样理解对吗?

**Comment by jieqian** [comment]
portal和config和admin可以分开部署，不一定要部署在一个虚机或物理机上。portal是通过build.sh里的xxx_meta信息(即domain name)加上admin service暴露出来的path进行restful的请求的(具体可参考源代码中RetryableRestTemplate这个类)。这个xxx_meta信息也会放在Apollo客户端(apollo-core.jar中的apollo-env.properties),供获取配置而使用的。客户端向config获取配置，portal是和admin做交互，比如配置的crud、配置的发布等等。。。

所以，portal的cluster可以弄一个域名，前面放一个nginx做lb，xxx_meta这个配置也可以搞一个域名，前面放nginx做lb

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
