### ISSUE TITLE
客户端配置支持多个 confservice 来达到ha效果

### ISSUE THREAD

**Issue by linzhouzhi** [ctripcorp/apollo#1152]
java 客户端使用时需要配置下面meta信息 dev.meta、pro.meta 但是该配置项好像只支持单个 ip:port 配置，倘若对应的 configservice down 掉后，就没法读取后期发布的数据了

**Comment by jieqian** [comment]
你可以配域名啊，dns server + nginx来做lb

**Comment by linzhouzhi** [comment]
就是为了这样的效果，然后去搭建一套域名服务挺麻烦的，现在很多框架的客户端都采用逗号分割 像 zk， eureka  如果 apollo 可以用逗号分隔 那么客户端使用起来会更方便

**Comment by jieqian** [comment]
我猜想可能作者不想引入太多的依赖，不然你服务端还得有个注册的server list让客户端知晓(类似于服务注册与发现的中间件)，增加部署或搭建的复杂度，推广起来就不那么容易了。

**Comment by linzhouzhi** [comment]
好吧没事， 那我自己改改，（其实 service list 我们客户端配置两个就可以达到ha效果了，根本不需要获取整个server list 那样的方式，比如连接 zk的时候并不需要配置所有的地址一个道理）
只不过建议 apollo 和 域名服务之间应该是一个选择性依赖，而不是必要性依赖，，，

**Comment by jieqian** [comment]
@nobodyiam   consul client了解一下O(∩_∩)O

**Comment by nobodyiam** [comment]
PR #1214 支持meta server配置多个ip地址了，不过生产环境还是建议使用域名（走slb）。
