### ISSUE TITLE
@ApolloConfig注解的config对象是否晚于其他成员变量初始化？

### ISSUE THREAD

**Issue by reignsr** [ctripcorp/apollo#1153]
以下代码报异常，config对象为null，
@Service
public class SmsServiceImpl implements SmsService {

	private static final Logger LOGGER = LoggerFactory.getLogger(ReceiveServiceImpl.class);
	@ApolloConfig
	private Config config;
	private String VALIDCODE_KEY=config.getProperty("rabbitmq.validcode.key", null);

改成以下代码才能正常运行，
@Service
public class SmsServiceImpl implements SmsService {

	private static final Logger LOGGER = LoggerFactory.getLogger(ReceiveServiceImpl.class);

	private Config config=ConfigService.getAppConfig();
	private String VALIDCODE_KEY=config.getProperty("rabbitmq.validcode.key", null);

是否因为@ApolloConfig注解的config对象晚于其他成员变量初始化？

**Comment by jieqian** [comment]
你的main函数类上声明了@EnableApolloConfig了吗？

**Comment by nobodyiam** [comment]
@reignsr 

这个。。。是spring的bean生命周期决定的。。。

看一下[afterPropertiesSet](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/beans/factory/InitializingBean.html#afterPropertiesSet--)和[@PostConstruct](https://www.mkyong.com/spring/spring-postconstruct-and-predestroy-example/)吧

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
