### ISSUE TITLE
域名配置问题

### ISSUE THREAD

**Issue by bigbenfather** [ctripcorp/apollo#1154]
我就一台机器做配置中心的服务器，portal、admin和conf都部署在上面，只支持一个环境，用NG做反向代理，用同一个域名，
问下能否这样配置，比如
portal ：        http://apollo.xxx.com/portal 
meta service: http://apollo.xxx.com/meta

**Comment by nobodyiam** [comment]
如果加上path的话，对portal应该会有影响，因为目前前端访问时应该是直接基于根路径的，建议搞两个域名吧

**Comment by bigbenfather** [comment]
好的，谢谢

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by canmanciu** [comment]
如果域名有带path的，类似这种 http://apollo.xxx.com/portal 目前是还不支持对么，试了下很多资源都访问不到的呢
