### ISSUE TITLE
apollo-client  打包   package  报错  

### ISSUE THREAD

**Issue by shiqianzhen** [ctripcorp/apollo#1155]
1、testAutoUpdateWithAllKindsOfDataTypes(com.ctrip.framework.apollo.spring.XmlConfigPlaceholderAutoUpdateTest)  Time elapsed: 0.068 sec  <<< ERROR!
2、org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.ctrip.framework.apollo.spring.XmlConfigPlaceholderTest.TestXmlBean#0' defined in class path resource [spring/XmlConfigPlaceholderTest3.xml]: Initialization of bean failed; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert property value of type [java.lang.String] to required type [int] for property 'timeout'; nested exception is java.lang.NumberFormatException: For input string: "${timeout:100}"
这是 java/text/resources  里面的 配置文件 spring 的配置文件XmlConfigAnnotationTest*
请问我该怎么解决
我是使用的Eclipse 开发工具。

**Comment by bigbenfather** [comment]
用脚本执行

**Comment by nobodyiam** [comment]
ut里面的自动更新测试由于涉及异步update，所以有100ms的等待机制，如果机器比较卡的话，有可能造成ut失败的。

打包的话，我们一般都是忽略测试的，所以建议使用build.sh打包。

如果实在要自己输入mvn打包的话，记得加上`-DskipTests=true`

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
