### ISSUE TITLE
ApolloAutoConfiguration两次加载

### ISSUE THREAD

**Issue by addozhang** [ctripcorp/apollo#1156]
`ApolloAutoConfiguration`使用了`@Configuration`注解, 同时还配置在`spring.factories`的`EnableAutoConfiguration`.

> 06-04 20:32:48.725 WARN  [o.s.c.annotation.ConfigurationClassPostProcessor] - Cannot enhance @Configuration bean definition 'com.ctrip.framework.apollo.spring.boot.ApolloAutoConfiguration' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.

应该去掉`@Configuration`注解

**Comment by EdwardLee03** [comment]
在使用 `DubboAutoConfiguration` 时遇到了相同的问题，参考了 @addozhang 的解法，绕过了触发该 WARN 异常的条件 “@Configuration bean 定义 + 自动配置类里包含通过 @Bean 方法注入的 BeanDefinitionRegistryPostProcessor 组件”。

### 1. 剖析异常信息线索
```java
Cannot enhance @Configuration bean definition 'com.ctrip.framework.apollo.spring.boot.ApolloAutoConfiguration' 
since its singleton instance has been created too early. 
The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.
```
不能增强 `@Configuration` 注解的 `ApolloAutoConfiguration` bean 定义，因为其单例实例创建得太早。典型的原因是返回 `BeanDefinitionRegistryPostProcessor` 类型的非静态 ` @Bean 方法`，考虑将这些方法声明为 'static'。（试过将 ` @Bean 方法` 声明为 'static'，无效）

### 2. 问题原因
通过源代码验证上述异常的提示信息：
```java
public class ConfigurationClassPostProcessor implements BeanDefinitionRegistryPostProcessor,
		PriorityOrdered, ResourceLoaderAware, BeanClassLoaderAware, EnvironmentAware {

	/**
	 * Post-processes a BeanFactory in search of Configuration class BeanDefinitions;
	 * any candidates are then enhanced by a {@link ConfigurationClassEnhancer}.
	 * Candidate status is determined by BeanDefinition attribute metadata.
	 * @see ConfigurationClassEnhancer
	 */
	public void enhanceConfigurationClasses(ConfigurableListableBeanFactory beanFactory) {
		Map<String, AbstractBeanDefinition> configBeanDefs = new LinkedHashMap<String, AbstractBeanDefinition>();
		for (String beanName : beanFactory.getBeanDefinitionNames()) {
			BeanDefinition beanDef = beanFactory.getBeanDefinition(beanName);
			if (ConfigurationClassUtils.isFullConfigurationClass(beanDef)) {
				if (!(beanDef instanceof AbstractBeanDefinition)) {
					...
				}
				else if (logger.isWarnEnabled() && beanFactory.containsSingleton(beanName)) {
					logger.warn("Cannot enhance @Configuration bean definition '" + beanName +
							"' since its singleton instance has been created too early. The typical cause " +
							"is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor " +
							"return type: Consider declaring such methods as 'static'.");
				}
				configBeanDefs.put(beanName, (AbstractBeanDefinition) beanDef);
			}
		}
		......
	}

}
```

```java
@Configuration
public class ApolloAutoConfiguration {
  @Bean
  public ConfigPropertySourcesProcessor configPropertySourcesProcessor() {
    return new ConfigPropertySourcesProcessor();
  }
}
```

```java
public class ConfigPropertySourcesProcessor extends PropertySourcesProcessor
    implements BeanDefinitionRegistryPostProcessor {
    ......
}
```

带有 `@Configuration` 注解的 `ApolloAutoConfiguration` 自动配置类通过 `@Bean 方法` 返回 `ConfigPropertySourcesProcessor` 组件，而该组件其实是 `BeanDefinitionRegistryPostProcessor` 类型的子类。

这样问题就很清晰了吧。

### 3. 可行的解法
这个解法本质上是绕过了触发该 WARN 日志的条件，Spring 官方在 `spring-core-4.3.11` 版本会修复这个（[[SPR-14603] Invalid WARN when returning a BeanDefinitionRegistryPostProcessor from within a @Configuration class](https://jira.spring.io/browse/SPR-14603)）。

```java
@Configuration
public class ApolloAutoConfiguration {

  public static class PropertySourcesConfiguration {
    @Bean
    @ConditionalOnMissingBean
    public ConfigPropertySourcesProcessor configPropertySourcesProcessor() {
      return new ConfigPropertySourcesProcessor();
    }
  }

}
```

**Comment by nobodyiam** [comment]
@EdwardLee03 

非常感谢详细的解释！所以我理解其实目前也是没问题的，只是会多一个warning日志？

**Comment by wkcaeser** [comment]
我刚刚接触Apollo，准备进行调研然后应用生产环境，但是运行demo的时候也发现了这个warn，这个后续会有处理么？目前有没有什么隐患

**Comment by edwardlee03** [comment]
@wkcaeser 后来我们是让应用在`main()`启动类增加`@DubboComponentScan(basePackages="xxx")`实现，就没这个warn日志。目前在生产环境有很多应用运行着，没反馈这个相关的问题

**Comment by lehug** [comment]
spring boot 2.2
apollo.bootstrap.enabled=true
apollo.bootstrap.eagerLoad.enabled=true

假如开启eagerLoad就会报如上的warn,并且日志中没有看到 apollo加载env环境的日志.但是不加eagerLoad的时候,就可以加载apollo了.

另外@EnableApolloConfig添加后, eagerLoad开启也不影响,可以正常输出apollo加载env的日志

**Comment by lehug** [comment]
spring boot 2.2
apollo.bootstrap.enabled=true
apollo.bootstrap.eagerLoad.enabled=true

假如开启eagerLoad就会报如上的warn,并且日志中没有看到 apollo加载env环境的日志.但是不加eagerLoad的时候,就可以加载apollo了.

另外@EnableApolloConfig添加后, eagerLoad开启也不影响,可以正常输出apollo加载env的日志

**Comment by nobodyiam** [comment]
@lehug eagerLoad 日志展示在 #3677 中解决了

**Comment by zyh0github** [comment]
> 

请问现在这个Apollo的warn日志如何规避呢？非常感谢。
最近在做springboot启动时间的优化，发现在这句日志之前是主程序激活对应环境配置文件的日志：The following profiles are active:xxx，过了8秒是这句日志：Cannot enhance @Configuration bean definition 'com.ctrip.framework.apollo.spring.boot.ApolloAutoConfiguration'。在考虑是否规避了warn日志会降低一点点启动耗时。

**Comment by nobodyiam** [comment]
@zyh0github 可以打开 spring boot 的 debug 日志看下过程中的耗时在哪里
