### ISSUE TITLE
开放平台问题

### ISSUE THREAD

**Issue by sjhuhuan** [ctripcorp/apollo#1157]
现在为什么只对开放平台做管理权限控制，而没做查询内容控制呢？
只让其查询、管理授权给他的应用配置信息
还有就是授权后没有收回或者删除的功能

**Comment by nobodyiam** [comment]
1. 因为目前对查询都还没有权限控制
2. 授权后没有收回和删除，这个确实没有，不过主要是系统管理员在使用，而且收回的场景很少，所以之前的设想是，如果要收回，直接改一下ConsumerToken表就好了。。
