### ISSUE TITLE
Tomcat启动应用时，使用配置信息的bean总是在加载配置之前先加载

### ISSUE THREAD

**Issue by MrLiuhhh** [ctripcorp/apollo#1158]
您好，有个问题想要请教下，我在用tomcat启动应用时，涉及到明文密码的加解密配置，但是涉及加解密的bean总是在加载配置之前就加载了，请问下tomcat这种方式的应用应该如何接入呢？

**Comment by nobodyiam** [comment]
这个和tomcat没啥关系吧

如果是spring的话，`@EnableApolloConfig`应该是早于普通bean的创建的

如果是spring boot的话，还可以开启`apollo.bootstrap.enabled`，就会在bootstrap阶段加载了

如果还有特殊场景的话，可以通过api方式拿到配置，再做解密操作

**Comment by MrLiuhhh** [comment]
恩恩 谢谢 已经解决了 针对我们的特殊场景，通过的是api的方式拿到配置，再做解密操作的
