### ISSUE TITLE
apollo-assembly 方式启动apollo各服务报错

### ISSUE THREAD

**Issue by duvalCC** [ctripcorp/apollo#1159]
> Caused by: org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.

启动configserver的时候报错，报错日志如下：

[configserver.log](https://github.com/ctripcorp/apollo/files/2075765/configserver.log)

**Comment by duvalCC** [comment]
试了下，单独启动configserver也是报错。启动VM参数如下：

`-Dapollo_profile=github -Dspring.datasource.url=jdbc:mysql://localhost:3306/ApolloConfigDB?characterEncoding=utf8 -Dspring.datasource.username=root -Dspring.datasource.password=root -Dlogging.file=/Users/duval/projects/apollo/logs/apollo-assembly.log`

**Comment by nobodyiam** [comment]
你是不是改过什么东西？貌似社区中这么多人用都没遇到你这个问题

**Comment by duvalCC** [comment]
@nobodyiam 我重新导入项目，看到有很多依赖下不下来，不知道是不是这个导致的。

![apollerror](https://user-images.githubusercontent.com/21072525/41076433-2b37a82a-6a44-11e8-8df9-07ef08b35ff8.png)

**Comment by duvalCC** [comment]
另外发现 pom 里边缺少了以下jar包的引入：

`import org.apache.catalina.connector.Connector;
import org.apache.coyote.ProtocolHandler;
import org.apache.coyote.http11.Http11NioProtocol;`

**Comment by nobodyiam** [comment]
maven的profile选错了，默认应该只会选中github的，为啥你把github的去掉了，然后选了其它不应该用到的profile。。。

**Comment by duvalCC** [comment]
可以了，多谢

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
