### ISSUE TITLE
为什么注册到Eureka是主机名而不是IP地址？

### ISSUE THREAD

**Issue by bigbenfather** [ctripcorp/apollo#1160]
0.10.2版本

**Comment by bigbenfather** [comment]
![111111111111](https://user-images.githubusercontent.com/3414309/41033713-11d6d5f2-69ba-11e8-98ab-14f44c588341.png)

**Comment by nobodyiam** [comment]
注册上去的是hostname和ip信息，只是界面展示的是hostname，你点击这个链接应该是跳到IP的。

**Comment by bigbenfather** [comment]
原来只是显示啊，多谢啦！

我昨天已经修改了eureka.instance.instance-id=${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}才显示IP
