### ISSUE TITLE
UAT和PRO环境的config和admin能否部署到同一台服务器？

### ISSUE THREAD

**Issue by bigbenfather** [ctripcorp/apollo#1161]
只有一台服务器
portal端口：8080
uat 的config和admin的端口分别是：8081和8082
pro的config和admin的端口分别是：8181和8182

这样可以部署成功吗？

**Comment by nobodyiam** [comment]
可以，不过要注意修改meta server和eureka.service.url的端口，参考一下分布式部署文档吧

**Comment by bigbenfather** [comment]
谢谢您的回复，已经搭建成功了！

**Comment by bigbenfather** [comment]
看到一个不错的文章，后来的朋友可以参考下，https://blog.csdn.net/buyaore_wo/article/details/79847404
