### ISSUE TITLE
关于客户端Jar编译

### ISSUE THREAD

**Issue by TheCrazyRock** [ctripcorp/apollo#1162]
> "由于客户端jar包中会包含meta server信息，无法上传一个统一的jar包到中央仓库，所以请按照分布式部署指南的文档说明打包并上传到自己公司的Maven私服。应用在实际使用时只需要按照如下方式引入即可。"

问题：由于中央仓库中没有客户端Jar，我自己编译了TAG v0.9.0的客户端jar，但有个疑问就是并没有发现客户端jar中有什么meta server信息，所以meta server信息到底是啥？

问这个问题的原因是我觉得中央仓库中没有客户端jar不太方便。我司自己编译上传私服库还要走流程，托管源码。。。比较繁琐。
如果后续的版本可以提供客户端jar了，建议最能提供一下编译产物到中央仓库，推广使用起来也更简单了。谢谢。

**Comment by bigbenfather** [comment]
apollo-core.jar看看

**Comment by nobodyiam** [comment]
@TheCrazyRock 目前主要是因为apollo-core.jar中的apollo-env.properties需要写入meta server地址，具体关于meta server信息请参考[Apollo配置中心设计](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1)

**Comment by nobodyiam** [comment]
apollo-client已经推送到Maven中央仓库, [点击此链接查看](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.ctrip.framework.apollo%22%20AND%20a%3A%22apollo-client%22)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
