### ISSUE TITLE
重新写了个go的客户端，支持多个namespace

### ISSUE THREAD

**Issue by philchia** [ctripcorp/apollo#1163]
https://github.com/philchia/agollo

@nobodyiam

**Comment by jieqian** [comment]
👍

**Comment by nobodyiam** [comment]
非常感谢！已经更新到 [Go、Python、NodeJS等客户端使用指南](https://github.com/ctripcorp/apollo/wiki/Go%E3%80%81Python%E3%80%81NodeJS%E7%AD%89%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)
