### ISSUE TITLE
想增加些功能

### ISSUE THREAD

**Issue by zhfish** [ctripcorp/apollo#1166]
看有没有在你们计划内的？
如果没有可以大家一起做一下，相信是共性需求
1. LDAP登录
2. 自动生成APPID
3. 项目分组
4. 获取配置时的IP白名单

**Comment by bigbenfather** [comment]
自动生成APPID这个功能没必要吧，如果所有的环境用一个portal还有必要，如果是分开的就没必要了，反而是个多余的。

**Comment by lepdou** [comment]
@zhfish 
你们投入Apollo共建的资源能保障不（主要是时间）？
如果能保障的话，可以拉一个小群，群里讨论需求、设计之类的。能共建，当然是最好的呀。
😁

**Comment by lepdou** [comment]
>appId自动生成 
一般appId都是可读，比如user-service等，而且appId跟公司很多平台比如paas，都是打通的。所以，Apollo 自动生成的appId的场景很少吧？

@bigbenfather 
即使是多个portai，只要是同一个应用，那也应该是各个环境一致的吧。

**Comment by bigbenfather** [comment]
如果是自生成appId，怎么保证两个portal对一个应用生成的是同一个id呢？

**Comment by zhangyg3** [comment]
如果不在同一个数据库，直接用mysqldump命令把数据导过去啊，不用重新建的；若是同一个数据库，就不存在你说的问题了。

**Comment by zhfish** [comment]
@lepdou 目前保障不了，还在协调资源，但个人比较想做这个事情
我觉得可以拉出task让大家认领
@bigbenfather 想多了，就是有个生成按钮，省的每次都要去uuid再加工..当然可以手输啊
现在的页面，uuid太长了显示不下，我一般取uuid第一段和最后一段

**Comment by sunguangran** [comment]
“LDAP登录” 这个有实现了的么~

**Comment by nobodyiam** [comment]
LDAP目前我们没有实际的使用场景，所以建议如果有公司已经实际实现并使用了，可以提供样例代码或者提交pull request

**Comment by nobodyiam** [comment]
[1.2.0](https://github.com/ctripcorp/apollo/releases/tag/v1.2.0)版本已经发布，增加了Active Directory接入方式，同时重构ldap支持，无需改动代码即可接入ldap登录。
