### ISSUE TITLE
同一台服务器，不同的config服务和数据库，不同环境的配置会混淆

### ISSUE THREAD

**Issue by huwsun** [ctripcorp/apollo#1168]
版本是pull的最新的master，自己构建的0.11.0-SNAPSHOT
按照分布式部署的方式，在同一台服务器上布了2个环境：dev,uat，数据库也是建了一个configdb,一个configdb_uat,并且配置了2个configservice和adminservice,eureka 使用的单独的服务，
下图是configservice的启动参数，标红的部分是对应的meta_server和数据库url
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/4082111/41192500-2fe4a3d4-6c31-11e8-89c3-ee63918648b6.png">

这个是adminservice的启动参数
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/4082111/41192519-7813dc88-6c31-11e8-8a20-abed112ed0d5.png">
这个是portal的启动参数
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/4082111/41192674-072e8eb6-6c34-11e8-84f6-1ec035f0081d.png">

结果在portal里，如果在dev环境里面增加配置，如下图：
<img width="952" alt="image" src="https://user-images.githubusercontent.com/4082111/41192345-c7c0765e-6c2e-11e8-8473-2dafb45c1c78.png">
在点击uat的环境的时候也会显示，
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/4082111/41192371-42856502-6c2f-11e8-9782-6c2c40a4977c.png">
item的记录却在uat库里：
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/4082111/41192391-8638a764-6c2f-11e8-813b-02ee755ada52.png">

commit的记录在uat的库中查到了
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/4082111/41192357-fc8d5dd4-6c2e-11e8-8935-3f2d502eb106.png">

反过来在uat环境新增配置，
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/4082111/41192574-7d0d95f2-6c32-11e8-8f99-5273dda6a34b.png">

在dev也能看到，如下图：
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/4082111/41192414-d110e99a-6c2f-11e8-8614-06e25c03a20c.png">
item跑到了dev的库里：
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/4082111/41192427-fa640a5c-6c2f-11e8-9fac-a71a322b29b5.png">

请问下这个是哪里配置的有问题吗？

**Comment by nobodyiam** [comment]
看上去是dev和uat的服务互相注册了，你看下config db中server config表中的eureka.service.url是不是连了两个环境的eureka地址。

应该每个环境只填自己环境的eureka地址。

**Comment by huwsun** [comment]
非常感谢 @nobodyiam ,的确是eureka server的问题。 eureka.service.url 我是配置的单独搭建的server：http://localhost:8030/eureka,用的是同一个，应该每套环境要用不同的eureka server。
