### ISSUE TITLE
spring注解模式的疑问

### ISSUE THREAD

**Issue by sjhuhuan** [ctripcorp/apollo#1170]
我现在使用Spring注解模式来加载Config，没添加一个namespace就需要@EnableApolloConfig；
我想请教为什么没设计为EnableApolloConfig 用来开启ApolloConfig支持，然后通过具体的Bean来装载对应的appid、namespace这些信息。
还有就是这样的话我就可以把一些公共的配置抽象到一个namespace中，然后在服务端就不需要每次都需要在去创建一个新的namespace去关联公共的，只需要在client端配置appid+namespace的方式就可以了，
而不像现在这样一个固定的appid，多个namespace的方式

**Comment by nobodyiam** [comment]
1. 使用EnableApolloConfig的方式是为了在spring启动过程中注入配置，而且一般情况下应用使用到的namespace是相对静态的

2. 公共配置所有应用都可以使用，不需要关联的
