### ISSUE TITLE
客户端接入内存占用严重

### ISSUE THREAD

**Issue by newbie-wang** [ctripcorp/apollo#1171]
客户端依赖apollo-client接入后，启动时CPU占满，应用占用内存从原来的200M左右到现在1G多，启动时间由原来20s到现在70s，不知道是否遇到过？

**Comment by jieqian** [comment]
你要内存和线程dump出来分析的，看看到底是哪个ThreadID特别耗CPU，还有就是看看内存dump中哪些对象占内存，得具体分析，一般apollo-client接入后不会特别耗费资源的

**Comment by nobodyiam** [comment]
这个看上去和apollo-client没啥关系，建议profile一下，可以使用jmc看看。

**Comment by newbie-wang** [comment]
嗯嗯，我再详细分析下，谢谢了
