### ISSUE TITLE
高可用和日志问题 v0.10.2

### ISSUE THREAD

**Issue by antonchen** [ctripcorp/apollo#1174]
1. apollo-portal、apollo-adminservice、apollo-configservice 是否支持运行多个实例，使用 Nginx 或 LVS 负载均衡实现高可用？（还是说由于可用性设计没有考虑这方面？）
2. /tmp 目录还会生成一份日志，如何禁用？（尝试过 `export LOG_FOLDER` 传参）

还有一个疑惑 Eureka server 是包含在 apollo-configservice 中的么？我从端口上看是包含在了 apollo-configservice，那么为何 apollo-configservice 不直接连接自己而是使用 `eureka.service.url` 配置？是为了统一 apollo-adminservice 吗？

**Comment by nobodyiam** [comment]
1. apollo-portal、apollo-adminservice、apollo-configservice都是支持运行多个实例的，我们在生产环境也都是集群部署的。简单而言，apollo-portal支持集群部署，前面会放一个nginx做负载均衡，用户通过域名访问。apollo-configservice支持集群部署，前面也会放一个nginx做负载均衡，apollo-portal和apollo-client通过域名访问meta server接口，拿到服务列表，后面就通过ip直连的方式访问了，不需要通过负载均衡。apollo-adminservice支持集群部署，它不需要在前面放一个nginx。如果还有疑问的话，可以参考一下[携程Apollo配置中心架构剖析](https://mp.weixin.qq.com/s/-hUaQPzfsl9Lm3IqQW3VDQ)

2. 你是通过[startup.sh](https://github.com/ctripcorp/apollo/blob/master/apollo-portal/src/main/scripts/startup.sh)启动的吗？这种方式会设置日志输出路径的。我看了一下我们生产运行的机器，在/tmp下并没有看到apollo相关的日志信息。你确认下这是的日志路径是否可写？

3. eureka server是包含在apollo-configservice中，集群需要组网，所以需要通过`eureka.service.url`来让所有的eureka server知道集群的机器是哪些。

**Comment by antonchen** [comment]
@nobodyiam 

是通过 `startup.sh` 启动的，并且设置了 `LOG_DIR `，`LOG_DIR ` 指定的目录下也有日志。

我观察到 spring-boot 的启动脚本（`head -242 apollo-portal.jar` 可以看见完整的脚本）中有 `/tmp` 目录相关的设置，它判断是否有 `LOG_FOLDER` 变量，如果没设置就赋值 `/tmp`。

我尝试在 `startup.sh` 中添加 `export LOG_FOLDER=$LOG_DIR` 后 `/tmp` 目录还是会打印日志。

**Comment by nobodyiam** [comment]
@antonchen 

我们在配置文件中其实已经配置好了：https://github.com/ctripcorp/apollo/blob/master/apollo-portal/src/main/config/apollo-portal.conf

相关的spring boot文档说明：
https://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html#deployment-script-customization-conf-file

所以照理说应该是OK的

**Comment by antonchen** [comment]
@nobodyiam 

`apollo-portal.conf` 中的 `LOG_FOLDER` 我没有改动也没有这个默认目录，因为我认为 `startup.sh` 中的 `LOG_DIR ` 会覆盖 `LOG_FOLDER` 设置，不知道是不是这个原因？

**Comment by nobodyiam** [comment]
@antonchen 

两者没有关系的，一个是启动脚本的日志输出目录，一个是应用的日志输出目录。

**Comment by antonchen** [comment]
@nobodyiam 

我今天试了下，`apollo-portal.conf` 和  `startup.sh` 日志配置都改了，`apollo-portal_dataappapollo-portal.log`  和  `apollo-portal.log` 打印到了设置的目录中，但是 `/tmp` 目录下还会创建一个 `apollo-portal.log` 空文件不知道怎么回事。

**Comment by fengyuzhe** [comment]
应该是logback.xml中`LOG_FILE`的设置，
```
<property name="LOG_FILE"
		value="${LOG_FILE:-${LOG_PATH:-${LOG_TEMP:-${java.io.tmpdir:-/tmp}}/}apollo-portal.log}" />
```
java.io.tmpdir的路径是tmp，会在/tmp路径下生成日志。
But：启动后，在tmp路径下生成了`tomcat........+端口号`的文件
```
drwxrwxr-x  3 tomcat tomcat   4096 Jun 28 16:00 tomcat.2739786854512427027.8025
drwxrwxr-x  3 tomcat tomcat   4096 Jun 28 16:14 tomcat.3270141047108793257.8020
drwxrwxr-x  3 tomcat tomcat   4096 Jun 28 16:15 tomcat.3533792601054988307.8025
```
这又是什么，能禁用或者修改路径吗？

**Comment by nobodyiam** [comment]
下面这个配置是最终fallback到tmpdir，前提是LOG_FILE, LOG_PATH, LOG_TEMP都没有。
另外，你的日志名是tomcat.xxx.xxx，和下面配置的也不一样，你看看里面的内容是啥？我没见过这样的日志。。

```
<property name="LOG_FILE"
		value="${LOG_FILE:-${LOG_PATH:-${LOG_TEMP:-${java.io.tmpdir:-/tmp}}/}apollo-portal.log}" />
```

**Comment by tqy-github** [comment]
> 1. apollo-portal、apollo-adminservice、apollo-configservice都是支持运行多个实例的，我们在生产环境也都是集群部署的。简单而言，apollo-portal支持集群部署，前面会放一个nginx做负载均衡，用户通过域名访问。apollo-configservice支持集群部署，前面也会放一个nginx做负载均衡，apollo-portal和apollo-client通过域名访问meta server接口，拿到服务列表，后面就通过ip直连的方式访问了，不需要通过负载均衡。apollo-adminservice支持集群部署，它不需要在前面放一个nginx。如果还有疑问的话，可以参考一下[携程Apollo配置中心架构剖析](https://mp.weixin.qq.com/s/-hUaQPzfsl9Lm3IqQW3VDQ)
> 2. 你是通过[startup.sh](https://github.com/ctripcorp/apollo/blob/master/apollo-portal/src/main/scripts/startup.sh)启动的吗？这种方式会设置日志输出路径的。我看了一下我们生产运行的机器，在/tmp下并没有看到apollo相关的日志信息。你确认下这是的日志路径是否可写？
> 3. eureka server是包含在apollo-configservice中，集群需要组网，所以需要通过`eureka.service.url`来让所有的eureka server知道集群的机器是哪些。
**===================================**
追问下:
apollo-portal支持集群部署，前面会放一个nginx做负载均衡,但是我们发现apollo是有状态的,如果负载均衡是随机轮询,会导致登录跳转后cookie登录失败?

**Comment by tqy-github** [comment]
@nobodyiam 

apollo-portal支持集群部署，前面会放一个nginx做负载均衡,但是我们发现apollo-portal是有状态的,如果负载均衡是随机轮询,会导致登录时访问serverA,成功后重定向serverB,导致登录失败?

**Comment by tqy-github** [comment]
@nobodyiam 

Apollo架构V5
V4版本已经是比较完整的Apollo架构全貌，现在还剩下最后一个环节：Portal也是无状态以集群方式部署的，用户如何发现和访问Portal？答案也是简单的传统做法，用户通过域名+NginxLB间接访问Portal集群。
以上是《携程Apollo配置中心架构剖析》by波波的架构方案,但现实是我们在生产环境使用Apollo v1.3.0 Release版本部署多个portal后使用负载均衡VIP(绑定3个portal实例,负载均衡算法是随机轮询)访问后,确实发现登录后重新跳转后提示登录失败,所以我们怀疑portal应该是有状态的,具体原因我们也没去看源码实现,盼复,谢谢
