### ISSUE TITLE
多个app的polling支持

### ISSUE THREAD

**Issue by Colstuwjx** [ctripcorp/apollo#1175]
如题，当前notification的API仅支持单个appId，单个cluster下的多个namespace，能否加入多个appId的支持。

背景是我这边想实现对PHP的支持，而PHP要做到动态更新配置，只有通过脚本或agent等方式实现，因此想在节点上部署agent，然后做polling，再通过共享内存提供给节点上运行的各个服务，类似QConf的设计。

**Comment by nobodyiam** [comment]
这个需求目前看上去可能适用的场景不多，建议在NotificationControllerV2接口中新增一个接口实现。实现关键点就在于根据传入的参数计算对应的watchedKeys。

另外，PHP应该也可以直接在客户端long polling到服务端？如果是这样的话，是不是也可以不用中间放一个agent了。
