### ISSUE TITLE
apollo发布报错

### ISSUE THREAD

**Issue by shiqianzhen** [ctripcorp/apollo#1176]
spring.application.name = ec-voicesystem
server.port = 8830
logging.level = ERROR
eureka.client.serviceUrl.defaultZone = http://127.0.0.1:8080/eureka/
eureka.client.healthcheck.enabled = true
eureka.client.registerWithEureka = true
eureka.client.fetchRegistry = true
eureka.client.eurekaServiceUrlPollIntervalSeconds = 60
eureka.instance.preferIpAddress = true
spring boot  项目在apollo发布在http://localhost:8080/看不到发布的信息。
spring boot 项目启动报错。
如何解决

**Comment by nobodyiam** [comment]
请仔细参照部署文档和Java客户端使用文档，另外也可以打开应用日志看看是否有啥异常。

**Comment by shiqianzhen** [comment]
详细参照了，日志文件也没有报错，我的apollo是基于windows10环境的，启动是用的git。
这是我的apollo配置
config_server_url=http://localhost:8080
admin_server_url=http://localhost:8090
eureka_service_url=$config_server_url/eureka/
portal_url=http://localhost:8070

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
