### ISSUE TITLE
东西不错。但部署太复杂。不能分开打包然后把配置文件导出来吗？这样也不需要每次都编译了。

### ISSUE THREAD

**Issue by jiayizhang** [ctripcorp/apollo#1178]
东西不错。但部署太复杂。不能分开打包然后把配置文件导出来吗？这样也不需要每次都编译了。太烦。
比如说：
每个服务的配置文件。build时不要写具体服务器配置。build后，直接在某一个配置文件里面修改。这样又节省时间。效率也高。对于作者来说。做成这种模式应该是很简单的事吧。

**Comment by nobodyiam** [comment]
@jiayizhang 如 @antonchen 所说，是可以打一个包把配置文件独立出来的，具体参考一下 #869 吧。

**Comment by zabzd999** [comment]
设计的太烂了！Apollo-demo能设计的好用点吗？client用的时候，直接改下配置就能运行最好。用了springboot却离springboot的 starter思想越来越远。springboot的很多starter都像你这样设计，还有人用吗？

**Comment by nobodyiam** [comment]
@zabzd999 开源需要大家一起贡献力量才能做的更好，单纯的吐槽并不能使这个世界变得更美好。

**Comment by nobodyiam** [comment]
@jiayizhang 

[0.10.2 release](https://github.com/ctripcorp/apollo/releases/tag/v0.10.2)已经更新了，支持直接修改配置文件，不需要每次都重新编译了。

相应的文档也已经更新，详见[2.2 获取安装包](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#22-%E8%8E%B7%E5%8F%96%E5%AE%89%E8%A3%85%E5%8C%85)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
