### ISSUE TITLE
一个portal怎样管理多个环境

### ISSUE THREAD

**Issue by hx78** [ctripcorp/apollo#1180]
我在https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97

看到这段话
“注3：默认ApolloPortalDB中导入的配置只会展示DEV环境的配置，所以这里配置了dev_meta属性，如果你希望在本地展示其它环境的配置，需要在这里增加其它环境的meta服务器地址，如fat_meta。”

我在两台主机都启动了config service和admin service，各自有自己的数据库，在其中一台主机启动了portal，启动命令如下：
-Dapollo_profile=github,auth
-Ddev_meta=http://localhost:8080/
-Duat_meta=http://xxx.xxx.xxx.xxx:8080/
-Dserver.port=8070
-Dspring.datasource.url=jdbc:mysql://localhost:3306/ApolloPortalDB?characterEncoding=utf8
-Dspring.datasource.username=root
-Dspring.datasource.password=root

但我并没有看到UAT 环境，只能看到DEV环境，这是怎么回事

**Comment by nobodyiam** [comment]
参考一下 https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#4-portal%E5%A6%82%E4%BD%95%E5%A2%9E%E5%8A%A0%E7%8E%AF%E5%A2%83

另外，如果只能看到DEV环境，看不到UAT环境，可以看一下portal的日志信息。

**Comment by hx78** [comment]
tks.我是这样做的
1、在portal 的 serverconfig中可支持环境列表的行的value加入uat(dev,uat)
2、重启，点击一个项目，可以看到左侧有一个“补缺环境”按钮，点击即可
3、添加一个项目，名字和appId和uat指定的主机上的项目一致，比如在uat上有个appId为testUAT的项目，在当前portal添加一个一样的项目后，portal就会根据env(uat)和appId(testUAT)获取到这个项目uat环境的配置
