### ISSUE TITLE
管理平台权限不支持精确到环境

### ISSUE THREAD

**Issue by wenchongyang** [ctripcorp/apollo#1181]
如题

**Comment by nobodyiam** [comment]
是的，设计上我们是希望开发一路从开发、测试环境管到生产环境的，不过确实有部分公司反映他们的生产环境是不允许开发管理的，之前有人在apollo的权限模型上加了环境维度来实现分环境权限。

**Comment by wenchongyang** [comment]
毕竟生产环境的权限控制还是比较严格的。另外整个role+permission 的设计原理是怎么，从数据结构看role的定义于permission 过于相识。比如 role name ModifyNamespace+901003+application = 
permission  PermissionType+TargetId     ModifyNamespace | 100001+application。

**Comment by nobodyiam** [comment]
role是一类权限的集合，权限是对特定资源的操作

**Comment by wenchongyang** [comment]
@anthonywanted 这个方法一开始也想过，其中配置同步如果是人工操作则会有一定的人为因素导致的错误。如果有自动化同步工具则需做数据上的验证。前者人为风险，后者需要研发成本。

**Comment by anthonywanted** [comment]
@wenchongyang 其实我也是一个提问者，跟你遇到一样的问题

你说的人工操作是不是说人为手动逐个配置复制粘贴？

我提出的方案里A的Portal-DEV里的TEST和B的Portal-PRD的TEST是同一个环境，所以用Portal里的同步配置功能就可以免去人工逐个配置复制粘贴

**Comment by wenchongyang** [comment]
@anthonywanted 这个好像可以。你们有试过么 Portal-DEV里的TEST和B的Portal-PRD的TEST是同一个环境。

**Comment by anthonywanted** [comment]
@wenchongyang 我这边还没试
@nobodyiam 所以想先问问此方案是否可行？

**Comment by ray1985113** [comment]
@anthonywanted 准备试试看吧

**Comment by wenchongyang** [comment]
最好还是权限支持下。总体来说权限分配还是有点麻烦的。没有一个权限管理的直接界面。

**Comment by nobodyiam** [comment]
portal db中有一些元数据的，所以如果两套portal，然后有一个环境共用的话，会有元信息同步的问题。

比如在portal-dev中创建的项目在TEST中有，但是切换到portal-prd之后就会有问题，因为portal-prd的portaldb中并没有这个公共项目。

权限这块确实如果能支持分环境会比较好，不过对目前模型会有较大变化

**Comment by anthonywanted** [comment]
@nobodyiam 弄了个PR，看看OK不
https://github.com/ctripcorp/apollo/pull/1236

**Comment by nobodyiam** [comment]
感谢 @anthonywanted，Apollo现在支持分环境权限了！详见 #1282，后续会随0.11.0版本发布，请知晓。

权限管理页面截图：

![image](https://user-images.githubusercontent.com/837658/43093361-6ef6d820-8ee2-11e8-8918-26cb1e094115.png)

**Comment by wenchongyang** [comment]
感谢 @anthonywanted 感谢@nobodyiam  数据库是否提供下升级脚本。

**Comment by nobodyiam** [comment]
如果之前是0.9.0及以上版本，直接使用最新代码即可，或者等0.11.0 release吧，预计也就是这两周了

**Comment by nobodyiam** [comment]
0.11.0版本已经发布，支持分环境权限了，具体可以参考 [Release Notes](https://github.com/ctripcorp/apollo/releases)。

case先关闭了，如还有问题，可以提供更多信息，或进群交流。
