### ISSUE TITLE
Namespace默认收缩

### ISSUE THREAD

**Issue by YanXiaoChen** [ctripcorp/apollo#1182]
![image](https://user-images.githubusercontent.com/23149320/41636638-31417a3e-743f-11e8-8523-45630b599d11.png)
怎么将Namespace设置成默认收缩的样子，因公司的配置文件比较多，因此有这个需求，找到半天，配置没有找到，求助。

**Comment by nobodyiam** [comment]
目前确实默认是展开的，可以前端简单定制一下吧，比如把namespace的收缩状态记在localstorage里面

**Comment by nobodyiam** [comment]
#1723 做了改进

**Comment by wuhaoyupku** [comment]
默认收缩太不方便了，得一个一个打开好麻烦，能否改成配置得
