### ISSUE TITLE
使用apollo.bootstrap.namespaces获取多个配置，除了application的配置其余的都获取不到

### ISSUE THREAD

**Issue by sunzhuang1212** [ctripcorp/apollo#1183]

**Comment by nobodyiam** [comment]
这个use case应该是没问题的，你看下是否配置有问题，或者看看是否有错误日志之类的。

**Comment by sunzhuang1212** [comment]
配置没有问题，只有在启动类上@EnableApolloConfig(value = {"application","apollo"})加这个才会好用

**Comment by nobodyiam** [comment]
如果要注入多个namespace，需要加上这个配置：

apollo.bootstrap.namespaces = application,apollo

**Comment by sunzhuang1212** [comment]
但是只有apollo.bootstrap.namespaces = application,apollo这个是读不出来apollo这个配置文件的

**Comment by nobodyiam** [comment]
这两个一起配上肯定是可以的，除非apollo这个namespace不存在。
```properties
apollo.bootstrap.enabled = true
apollo.bootstrap.namespaces = application,apollo
```

不过不行的话，建议看看日志，或者到 https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/boot/ApolloApplicationContextInitializer.java#L63 调试一下

**Comment by liuqingliu** [comment]
apollo.bootstrap.namespaces = application,apollo，添加上这两个namespace，这两个namespace中有相同的key会怎么选择读取顺序，或者能否做到application中获取的key 报错，再去获取apollp中对应的key？

**Comment by nobodyiam** [comment]
这部分是spring实现的，apollo会按照用户配置的顺序把配置作为property source加到spring中去，优先从application中获取配置，如果没有，再从apollo中获取

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by aimoyu** [comment]
> (value = {"application","apollo"})

我按照你的可以生效，按照官方教程配置也是不生效（我是在namespaces为application加的配置），无论这个druid加不加properties。请问你是怎么解决的哈。
apollo.bootstrap.enabled = true
# will inject 'application', 'FX.apollo' and 'application.yml' namespaces in bootstrap phase
apollo.bootstrap.namespaces = application,druid.properties

**Comment by nobodyiam** [comment]
@aimoyu 

可以看下客户端的日志，如果加载配置失败的话会有日志的，或者也可以直接到代码中debug一下

https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/boot/ApolloApplicationContextInitializer.java#L93

**Comment by aimoyu** [comment]
> ApolloApplicationContextInitializer

我看了本地缓存是没有其它的配置文件，而且debug中
String namespaces = environment.getProperty("apollo.bootstrap.namespaces", "application");
在走到这里面，value是null。所以返回默认值application。
public String getProperty(String key, String defaultValue) {
        String value = this.getProperty(key);
        return value != null ? value : defaultValue;
    }

但是我已经加了这些呀
使用方式很简单，只需要在application.properties/bootstrap.properties中按照如下样例配置即可。
我的application.properties这个配置是放在了阿波罗配置中心里面的
apollo.bootstrap.enabled = true
apollo.bootstrap.namespaces = application,druid.properties（也已经试过不加.properties关键字）

**Comment by nobodyiam** [comment]
这个方法会进来两次，第一次是bootstrap阶段，也就是bootstrap.properties的内容，第二次是application.properties的内容

**Comment by aimoyu** [comment]
> 这个方法会进来两次，第一次是bootstrap阶段，也就是bootstrap.properties的内容，第二次是application.properties的内容
谢谢，我debug了一下，但是没有进入第二次，应该是我端点打的有问题吧。总之
apollo.bootstrap.enabled = true
apollo.bootstrap.namespaces = application,druid.properties
这个配置是放到第几阶段的application.properties里面呢？还是说无论是在本地application.properties还是远程控制台配置这个apollo.bootstrap.namespaces都可以？

**Comment by nobodyiam** [comment]
这个是在本地的application.properties或bootstrap.properties里面配置的
