### ISSUE TITLE
apollo无法兼容dubbo-spring-boot-starter

### ISSUE THREAD

**Issue by BossYi** [ctripcorp/apollo#1184]
版本是0.10.2，已经在application.properties中加入 apollo.bootstrap.enabled=true，也试过提高ApolloApplicationContextInitializer的加载顺序，都无法适配dubbo-spring-boot-starter，其他的配置都可以。 dubbo-spring-boot-starter的版本是0.1.0，希望能够回复一下！

**Comment by nobodyiam** [comment]
能否上传一个简化的sample项目重现该问题？

**Comment by BossYi** [comment]
@nobodyiam 我这有对apollo如何指定meta_server的地址做了定制化，无法上传源码，不好意思。只能把这个jar发给您，然后我上传一个配置的demo吧，你看怎么样？

**Comment by BossYi** [comment]
@nobodyiam 已经确认问题，在引入apollo之后，会将dubbo service和reference的加载延后，如果在dubbo加载完成之前，在其他被@Configuration注解的类中注入某个dubbo服务，将会是null，导致启动报错。

**Comment by BossYi** [comment]
在没有引入apollo之前是没有这个问题的。

**Comment by nobodyiam** [comment]
apollo做的只是注入配置，不会将dubbo service和reference的加载延后吧，要不还是给一个简单的demo吧，只要把代码部分传上来就可以，jar包不需要的。

**Comment by BossYi** [comment]
公司这里无法上传github，做了拦截，我晚点上传一个demo给您。

**Comment by nobodyiam** [comment]
@BossYi 

我写了一个demo项目，dubbo-spring-boot-starter是可以和apollo一起工作的，示例代码请参考：https://github.com/ctripcorp/apollo-use-cases

我用的是dubbo-spring-boot-starter的0.2.0版本，不过应该和0.1.0版本一样的。

**Comment by BossYi** [comment]
@nobodyiam   实际上就是 @Configuration注解的类中，
`
@Configuration
public class A {
    @Bean
    public B getB(){
        B b = new B();
    }
}`

在B中@feference 某个服务的时候，就会是null，在没有引入apollo之前都是正常的。

**Comment by nobodyiam** [comment]
@BossYi B中reference的某个服务需要确保在bean初始化后再使用，比如放在`@PostConstruct`的方法里面

**Comment by liliang8858** [comment]
没有使用   dubbo-spring-boot-starter   
直接引用 dubbo 2.6.0 版本
这个问题

**Comment by 1528992118** [comment]
其实这种自己写个dubbo的starter启动包好了，不复杂的

**Comment by slankka** [comment]
我也遇到类似的问题：```@Reference```注解不支持Placeholder，我已经解决了。
如果使用https://github.com/alibaba/dubbo-spring-boot-starter这个的POM依赖，版本是2.0:
```
<dependency>
        <groupId>com.alibaba.spring.boot</groupId>
        <artifactId>dubbo-spring-boot-starter</artifactId>
        <version>2.0.0</version>
    </dependency>
```
这个Dubbo-starter 是个假Dubbo-starter(玩笑)。

改用
https://github.com/apache/incubator-dubbo-spring-boot-project
这个Dubbo-starter的版本是：
```
<dependency>
    <groupId>com.alibaba.boot</groupId>
    <artifactId>dubbo-spring-boot-starter</artifactId>
    <version>0.2.0</version>
</dependency>
```
区别在于，2.0.0引用的Dubbo版本是2.6.0。后者0.2.0 引用的版本是2.6.2。
查看Dubbo源码可以发现，2.6.2才支持 注解的 Placeholder的解析。

然而我并不知道这两个dubbo-spring-boot-starter是真官方。（笑）
可能是两拨人维护。
"假"Dubbo-starter 的全版本引用的都是2.6.0。

**Comment by nobodyiam** [comment]
关于dubbo spring boot starter，可以参考 #1102 中的讨论，建议使用 [incubator-dubbo-spring-boot-project](https://github.com/apache/incubator-dubbo-spring-boot-project)，这个目前测试下来都是OK的，也是官方维护的版本。

case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by nanprivate** [comment]
> @BossYi
> 
> 我写了一个demo项目，dubbo-spring-boot-starter是可以和apollo一起工作的，示例代码请参考：https://github.com/ctripcorp/apollo-use-cases
> 
> 我用的是dubbo-spring-boot-starter的0.2.0版本，不过应该和0.1.0版本一样的。

我用0.1.0试了不行
