### ISSUE TITLE
去掉 Spring boot 相关依赖以及去除 Client 模块 com.ctrip.framework.apollo.spring.boot 包有哪些影响？

### ISSUE THREAD

**Issue by stateIs0** [ctripcorp/apollo#1187]
场景：目前老项目不想依赖 SpringBoot。想去除 apollo 相关依赖，不知对现有的 SpringBoot 是否有影响？

目前的做法是: 去除 client 模块的 Springboot autoconfig 依赖，删除 spring.factories 文件，排除com.ctrip.framework.apollo.spring.boot 包。

简单的测试下来，似乎没有什么影响。

1. 不是很确定对之前的 SpringBoot 项目，这么修改 client 会有哪些影响？
2. apollo 加入 springBoot starter 的目的是什么呢？

**Comment by nobodyiam** [comment]
apollo客户端不强依赖spring boot，注意看pom中的`<optional>true</optional>`，所以删相关的代码是多此一举。

https://github.com/ctripcorp/apollo/blob/master/apollo-client/pom.xml#L42

如果是spring boot环境，就可以启用相关功能，如果不是spring boot环境，是不会跑到spring boot相关逻辑的。

**Comment by stateIs0** [comment]
@nobodyiam 谢谢您的解答。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
