### ISSUE TITLE
为什么 admin 模块 config 模块 mvn编译后的dev的zip文件中 相关的jar解压失败

### ISSUE THREAD

**Issue by samson886** [ctripcorp/apollo#1189]
![image](https://user-images.githubusercontent.com/8944097/41832791-2d414992-7880-11e8-8928-bf59176eee4a.png)
![image](https://user-images.githubusercontent.com/8944097/41832822-503355da-7880-11e8-80f4-0af81259dece.png)

**Comment by nobodyiam** [comment]
这个是可以启动的jar，所以在zip文件头部嵌入了脚本，你试试别的压缩软件吧，我们一般在Linux上直接用unzip命令是OK的。
