### ISSUE TITLE
win10下基于system enviroment设置ENV无效

### ISSUE THREAD

**Issue by Gavin-cn** [ctripcorp/apollo#1190]
在windows10下通过system enviroment设置ENV无效，改为基于C:\opt\settings\server.properties下配置后OK。

**Comment by stateIs0** [comment]
在 vm options 里设置试一下看看行不行？

**Comment by nobodyiam** [comment]
windows上改完ENV，貌似不是立即生效的？

不过一般还是建议放在server.properties中的。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
