### ISSUE TITLE
@Value 自动更新功能疑惑？

### ISSUE THREAD

**Issue by stateIs0** [ctripcorp/apollo#1193]
@Value 注解不区分 namespace。但如果有2个 namespace 有相同的属性名称，那么客户端应用的将是优先级小的那个 namespace。

问题 1：判断 @value 具体应用哪个 namespace 的代码在哪里呢？client 还是 config，还是 admin？
为题 2：这个功能是否容易引起误解？可否有详细的文档解释这些边界情况？

**Comment by stateIs0** [comment]
因为 portal 可能无意中更新了值，但却影响了客户端的配置，客户端无法控制具体到底是哪个 namespace 影响了这个功能。

也可能 2 个客户端配置的 order 是相反的。那么也会引起疑惑？

**Comment by nobodyiam** [comment]
这个是spring的配置层级覆盖逻辑，至于order的话，是越小优先级越高的，具体可以参考 org.springframework.core.Ordered

**Comment by stateIs0** [comment]
@nobodyiam 您好，我的疑惑主要是：@value 是根据优先级来决定如何更新 field 的，但如果有一种场景：2 个 client，他们设置的 config 优先级是相反的，那么，cofigService 修改一个配置，对这两个 client 将造成不同的结果？不知这个该如何解决呢？或者说，靠人工来解决？

**Comment by nobodyiam** [comment]
如果是两个客户端程序，那么它们相互是独立的，不会受影响，因为Order是在客户端起作用的。

**Comment by stateIs0** [comment]
@nobodyiam  谢谢，对的，appid 保证了这种情况不会出现。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
