### ISSUE TITLE
Windows单机模拟DEV环境下的机器集群问题

### ISSUE THREAD

**Issue by l-ning** [ctripcorp/apollo#1194]
您好,Apollo部署时出现一些问题:
1) 在windows下单机服务启动没有问题,可以达到热修改的目的
2) 在windows下进行多端口启动,没有出错,但是没有改变,并没有达到预期效果
3) 启动方式是通过java -jar 命令启动
4) 每次通过修改build.bat文件构建jar包,然后java命令执行

还有一个疑问,portal启动一个即可,那么多个服务,在build.bat里面的dev_meda怎么配置,现在我是每个build的时候,就写了一个不同的端口,这样做对不对,

诚挚的感谢!谢谢

**Comment by nobodyiam** [comment]
能详细说明下部署的情况和实际的问题吗？

**Comment by l-ning** [comment]
@nobodyiam 非常感谢您百忙中的回复,目前问题换成idea已经解决,出现问题的原因是启动jar包的方式我配置有错误,是否要强制加-Denv=envs参数,十分感谢,问题已经解决
