### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by shiqianzhen** [ctripcorp/apollo#1195]
java.lang.NoClassDefFoundError: org/springframework/web/servlet/config/annotation/WebMvcConfigurerAdapter
我在pom文件中引入了spring-boot-starter-web。
但是还是报错，我换了版本号还是一样。是不是jar冲突，我该什么方法解决。
我百度了很多方法，总是报错找不到类。
请问创建spring boot项目引入的jar  是那些？

**Comment by nobodyiam** [comment]
NoClassDefFoundError一般是指类加载失败，建议看下具体的Caused by。

另外，如果直接用apollo原生的代码启动是不会报错的，可以看看改动了什么地方

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
