### ISSUE TITLE
请问我按照官网操作，为什么没有项目权限这个入口呢

### ISSUE THREAD

**Issue by guoganbiao** [ctripcorp/apollo#1196]
我部署apollo可以用了，但是发现并没有“项目权限”这个入口 ，目前左下角的入口有“管理项目”，“添加集群”，“添加nameSpace”，请问完整的应该有哪些呢

**Comment by guoganbiao** [comment]
你好，进入管理项目后，似乎只有很简单的功能，并没有我们平时看到的用户，角色，权限等管理操作？

**Comment by nobodyiam** [comment]
权限在namespace的授权按钮中

用户管理目前apollo只提供了一个简易版本，建议和自己公司的用户系统对接。

https://github.com/ctripcorp/apollo/wiki/Portal-%E5%AE%9E%E7%8E%B0%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95%E5%8A%9F%E8%83%BD

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
