### ISSUE TITLE
springboot启动项目报错

### ISSUE THREAD

**Issue by fantingtingfei** [ctripcorp/apollo#1197]
（1）新建一个应用，但是./demo.client监听不到appolication各个配置。启动springBOOT，报com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused: connect
018-06-27 14:20:23.114 ERROR 3468 --- [           main] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_UNKNOWN/ftt - was unable to refresh its cache! status = Cannot execute request on any known server
com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
。
（2）控制台打印使用Tomcat initialized with port(s): 8080 (http)；但是在配置中心是server.port=8830
（3）若直接在Sample App的基础上修改，则可以监听到applocation各个配置。
麻烦大神帮我解答一下，谢谢啦

**Comment by nobodyiam** [comment]
第一个不是问题。

第二个是说你自己配置了server.port=8830，但是启动还是8080，你是怎么配置的？

另外，具体是什么问题详细说一下？如果有代码示例或详细日志可能会更清楚一些

**Comment by wulinjie122** [comment]
我也遇到这种问题了，我在配置中心server.port=9090，但是启动的时候还是8080，不知道哪里有问题。

**Comment by wulinjie122** [comment]
我修改好了，在resources文件夹下，添加application.properties文件：
apollo.bootstrap.enabled=true
apollo.bootstrap.namespaces=xxx

**Comment by nobodyiam** [comment]
@wulinjie122 检查一下本地配置文件中是否有server.port配置，这个配置比较特殊，需要本地没有才读apollo的。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
