### ISSUE TITLE
配置展示未分页导致页面卡顿问题

### ISSUE THREAD

**Issue by diwayou** [ctripcorp/apollo#1198]
目前我们现有项目有很多共享的配置，需要配置到某个共有的应用下供所有其它应用使用，需要是public的，但是我们发现现有的配置展示未分页展现，当我们配置迁移过来的时候，配置展现页非常的卡，有把namespace和kv配置进行分页展示的计划吗？

**Comment by j782282271** [comment]
同问

**Comment by nobodyiam** [comment]
这块确实值得优化一下，不知是否有啥建议的思路？如果能提pull request那就更好了！

**Comment by diwayou** [comment]
把namespace和kv的配置分成两个页面，第一个页面展示分页版本的namespace，当点击某个namespace的时候展现该namespace的kv的分页列表
我这边尝试优化下看看，如果感觉还不错可以提个pull request。

**Comment by nobodyiam** [comment]
好的，感谢！

**Comment by nobodyiam** [comment]
[1.2.0](https://github.com/ctripcorp/apollo/releases/tag/v1.2.0)版本已经发布，增加了以下功能：

1. 当项目中的namespace数量大于2时，默认收起配置详情
2. 当项目中的namespace数量大于10时，启用配置懒加载模式，提升页面加载性能

应该解决了Issue中提到的问题
