### ISSUE TITLE
portal启动报错

### ISSUE THREAD

**Issue by shiqianzhen** [ctripcorp/apollo#1199]
Failed to parse configuration class [com.ctrip.framework.apollo.portal.PortalApplication]; nested exception is java.io.FileNotFoundException: class path resource [portal.properties] cannot be opened because it does not exist

**Comment by nobodyiam** [comment]
https://github.com/ctripcorp/apollo/blob/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/PortalApplication.java

PortalApplication并没有引入portal.properties，建议更新下代码吧

**Comment by shiqianzhen** [comment]
请问是PortalApplication这个类更新代码，还是apollo-portal整个项目都要更新，而且我看了PortalApplication类，里面也没有添加注解@PropertySource(value= {"classpath:portal.properties"})
引入portal.properties?
