### ISSUE TITLE
portal启动后报错

### ISSUE THREAD

**Issue by shiqianzhen** [ctripcorp/apollo#1200]
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://config.local/services/admin": config.local; nested exception is java.net.UnknownHostException: config.local

**Comment by nobodyiam** [comment]
这个错是说没有可用的admin server，你可以访问 http://127.0.0.1:8088/services/admin 看一下admin server是否正确

**Comment by shiqianzhen** [comment]
apollo客户端上显示发布成功，发布信息可以在localhost8080上看到，启动adminseriver也没有么错误，adminservice使用的端口号为8099，Eureka使用的端口号是8099

--------------原始邮件--------------
发件人："Jason Song "<notifications@github.com>;
发送时间：2018年6月28日(星期四) 晚上9:49
收件人："ctripcorp/apollo" <apollo@noreply.github.com>;
抄送："shiqianzhen "<shiqz@primeton.com>;"Author "<author@noreply.github.com>;
主题：Re: [ctripcorp/apollo] portal启动后报错 (#1200)
-----------------------------------

这个错是说没有可用的admin server，你可以访问 http://127.0.0.1:8088/services/admin 看一下admin server是否正确

**Comment by shiqianzhen** [comment]
configseriver和adminservice启动正确，我不能访问127.0.0.1：8088/service/admin  我是按照文档操作的，请我们要访问这个网址需要配置什么嘛？我是在Windows10的环境

--------------原始邮件--------------
发件人："Jason Song "<notifications@github.com>;
发送时间：2018年6月28日(星期四) 晚上9:49
收件人："ctripcorp/apollo" <apollo@noreply.github.com>;
抄送："shiqianzhen "<shiqz@primeton.com>;"Author "<author@noreply.github.com>;
主题：Re: [ctripcorp/apollo] portal启动后报错 (#1200)
-----------------------------------

这个错是说没有可用的admin server，你可以访问 http://127.0.0.1:8088/services/admin 看一下admin server是否正确

**Comment by shiqianzhen** [comment]
请问这个127.0.0.1：8088/service/admin无法访问是哪里的错误，可以给说明下吗？
配置中心 4 没有之配置这个网址.

**Comment by nobodyiam** [comment]
如果无法访问，那应该就是地址配置错误了。

127.0.0.1:8088你确定下是否是指向config service的

https://github.com/ctripcorp/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/metaservice/controller/ServiceController.java#L63

**Comment by shiqianzhen** [comment]
你好，我看了很多代码，127.0.0.1:8080显示config service  在 instances  currently  registered  with  euerka中的应用中有这个服务。我是一个新手，项目经理交给我来做，期待您的回复！！！

--------------原始邮件--------------
发件人："Jason Song "<notifications@github.com>;
发送时间：2018年6月30日(星期六) 上午10:07
收件人："ctripcorp/apollo" <apollo@noreply.github.com>;
抄送："shiqianzhen "<shiqz@primeton.com>;"Author "<author@noreply.github.com>;
主题：Re: [ctripcorp/apollo] portal启动后报错 (#1200)
-----------------------------------

如果无法访问，那应该就是地址配置错误了。
 
127.0.0.1:8088你确定下是否是指向config service的
 
https://github.com/ctripcorp/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/metaservice/controller/ServiceController.java#L63

**Comment by nobodyiam** [comment]
所以你的meta server地址应该是 http://127.0.0.1:8080 而不是 127.0.0.1:8088 ？

**Comment by shiqianzhen** [comment]
能收到您的回复真的很开心，我在127.0.0.1上面也有这个两个服务，可以清楚的看的config和admin两个服务的存在，这个服务好像是apollo自带的。端口号一个为80一个为90

--------------原始邮件--------------
发件人："Jason Song "<notifications@github.com>;
发送时间：2018年7月2日(星期一) 晚上7:39
收件人："ctripcorp/apollo" <apollo@noreply.github.com>;
抄送："shiqianzhen "<shiqz@primeton.com>;"Author "<author@noreply.github.com>;
主题：Re: [ctripcorp/apollo] portal启动后报错 (#1200)
-----------------------------------

所以你的meta server地址应该是 http://127.0.0.1:8080 而不是 127.0.0.1:8088 ？

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by shiqianzhen** [comment]
那个群？

--------------原始邮件--------------
发件人："Jason Song "<notifications@github.com>;
发送时间：2018年10月6日(星期六) 晚上10:18
收件人："ctripcorp/apollo" <apollo@noreply.github.com>;
抄送："shiqianzhen "<shiqz@primeton.com>;"Author "<author@noreply.github.com>;
主题：Re: [ctripcorp/apollo] portal启动后报错 (#1200)
-----------------------------------

 
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by nobodyiam** [comment]
https://github.com/ctripcorp/apollo/wiki#support
