### ISSUE TITLE
spring boot 2.0 整合Apollo 0.10.2启动报错

### ISSUE THREAD

**Issue by linrol** [ctripcorp/apollo#1201]
启动报如下错误信息

![20180628115258](https://user-images.githubusercontent.com/18043615/42012292-fcdc2064-7ac9-11e8-9510-b9c0c9dba98d.png)

**Comment by nobodyiam** [comment]
请用maven的方式引用apollo-client，看这个错是一些间接依赖没有引入

**Comment by linrol** [comment]
好的，谢谢

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
