### ISSUE TITLE
Placeholder不能获取公共Namespace的配置么？

### ISSUE THREAD

**Issue by randomSpirit** [ctripcorp/apollo#1202]
经测试Placeholder只能获取默认Namespace的配置，其余私有公有Namespace都不能获取。
使用的是“在Spring Boot初始bootstrap阶段注入配置”
看了#1193好像跟order相关？bootstrap注入的可以配置order么？或者Placeholder能指定Namespace么？

**Comment by nobodyiam** [comment]
默认只会引入`application` namespace，如果要引入其它的需要按照如下格式指定一下。
```properties
apollo.bootstrap.enabled = true
# will inject 'application' and 'FX.apollo' namespaces in bootstrap phase
apollo.bootstrap.namespaces = application,FX.apollo
```

**Comment by randomSpirit** [comment]
其他namespace有引用的，但还是没值。不同namespace同一key按namespace的顺序取是么？bootstrap能指定namespace的顺序么？ @nobodyiam

**Comment by nobodyiam** [comment]
不同namespace同一key是按namespace的顺序取的，下面的例子就是application优先。

apollo.bootstrap.namespaces = application,FX.apollo

**Comment by randomSpirit** [comment]
之前namespaces放在yml公共部分的，现在放在对应profiles就能读取到了
