### ISSUE TITLE
请问：为什么 admin 和 config 不合在一起呢

### ISSUE THREAD

**Issue by stateIs0** [ctripcorp/apollo#1204]
是考虑高可用吗？
或者，明确职责划分？
或者，admin 不需要多个实例，而 config 需要大量实例，比例不匹配，所以需要分开？

**Comment by nobodyiam** [comment]
两者职责不太一样，设计上的一些要求也不一样，在开发阶段的更新频率也不太一样，所以是分开部署的。

**Comment by stateIs0** [comment]
@nobodyiam 感谢回复 😜

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
