### ISSUE TITLE
请教大神 apollo跨中美机房部署，有什么需要注意，可优化的点吗？

### ISSUE THREAD

**Issue by timZhangww** [ctripcorp/apollo#1208]
国内机房 部署：数据库  adminservice  configservice
美国机房 部署：configservice 
configservice开启缓存功能。
国内登录使用portal

美国的configservice 跨机房  访问国内数据库，会不会  有问题呢？

**Comment by lepdou** [comment]
只要网络是通的，本质上没有任何区别，就是延迟高一点。对于Apollo来说，因为有了缓存，所以对于数据库的依赖很轻，所以没关系的。
