### ISSUE TITLE
如何在不同环境间迁移数据, 比如迁移数据从UAT到PRO

### ISSUE THREAD

**Issue by nianjiang** [ctripcorp/apollo#1210]
**问题**
如何在不同环境间迁移数据, 比如迁移数据从UAT到PRO

背景:
Apollo是由运维工程师来负责的, 手动迁移给他们带来很大负担, 期望简化操作

**理想状态**
一键迁移, 有一个脚本或工具可以一键迁移数据, 这样可以简化管理员的操作

**方案**
有现成的工具, 或者API, wiki么?
如果没有, 我们需要开发一个, 请问有什么API/文档可以使用

.

**Comment by nianjiang** [comment]
qq群comment:
(清风伴酒(544611407)  16:18:24)
```
@killer 个人觉得，它内部实现最终所有的文件都是以key value形式入库，并关联不同的环境和命名空间以及APP，那么是不是可以尝试写一个接口直接操作数据库更改环境关联关系。（只是一个想法，没有实验过）
```

**Comment by wenchongyang** [comment]
@nianjiang 如果能做到 [#1181 管理平台权限不支持精确到环境](https://github.com/ctripcorp/apollo/issues/1181)就不存在不同环境间迁移数据问题了。

**Comment by nobodyiam** [comment]
@nianjiang 话说0.11.0版本开始支持分环境权限了，是否就不存在不同环境间迁移数据问题这个问题了？
具体可以参考 [Release Notes](https://github.com/ctripcorp/apollo/releases)。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
