### ISSUE TITLE
apollo集成springboot加载配置时启动顺序太低，导致某些配置不生效

### ISSUE THREAD

**Issue by cyejing** [ctripcorp/apollo#1211]
apollo集成springboot加载配置时启动顺序太低，导致某些配置不生效
不生效的配置有：
`
logging.level
logging.file
`
原因是apollo加载配置的顺序太慢导致的，应该在LoggingApplicationListener加载之前才可以正常
推荐：应该继承EnvironmentPostProcessor方法，在准备环境阶段就去加载apollo的配置

**Comment by stateIs0** [comment]
开启 apollo.bootstrap.enabled = true 了吗

**Comment by cyejing** [comment]
开启了，但是还是不起作用。因为没有LoggingApplicationListener这个类的顺序高

**Comment by cyejing** [comment]
启动完之后再刷新这种操作自然是繁琐的做法，建议你可以参照一下 `SpringCloudConfig的做法改一下你们的配置加载类，比如用这个`org.springframework.cloud.bootstrap.BootstrapConfiguration`，`org.springframework.cloud.config.client.ConfigServiceBootstrapConfiguration`使得apollo的配置文件有更高的加载顺序

**Comment by nobodyiam** [comment]
如我前面所说的，日志的优先级肯定是最高的。

spring cloud config的做法也是在配置加载后刷新了一下Logging system，不过我们也可以考虑一下是否把这个能力内置到apollo客户端中去。

https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceBootstrapConfiguration.java#L110

**Comment by cyejing** [comment]
我觉得在外部再添加方法去刷新日志的设置这种做法非常繁琐，不是一个优良的设计。内置到apollo客户端还差不多，因为这些日志的配置本来就是apollo配置里面的内容，结果因为不生效，需要用户再去刷新。这不是很不好用吗？

**Comment by nobodyiam** [comment]
LoggingApplicationListener这个类貌似是spring boot 2.0.0以后才有的，感觉上应该是把spring cloud的一些能力一直到spring boot 2.0了。

另外，之前apollo一度是适配spring boot启动阶段的各种event的（SpringApplicationRunListener），可是无奈spring boot每次升级都会有不兼容的情况，所以后来就还是改成和spring集成了，详见此[commit](https://github.com/ctripcorp/apollo/commit/05acc044219804fd4708b8ceb7910ba8138f57cb#diff-a23a4f04afeb1772308202c8d7306c6a)。

EnvironmentPostProcessor或许是一个可以切入的点，不过粗略看了一下，它也是在ApplicationEnvironmentPreparedEvent中触发的，和LoggingApplicationListener初始化LoggingSystem属于同一个阶段，尚不确定是否一定可以，后续我们再看一下，不过确实是一个不错的思路，非常感谢！

**Comment by kinggggg** [comment]
> 开启 apollo.bootstrap.enabled = true 了吗

it works for me.
