### ISSUE TITLE
ERROR Error: Network error: Cannot convert number to Ljava/text/NumberFormat; at index 0

### ISSUE THREAD

**Issue by cnqiuxue** [ctripcorp/apollo#1213]
When I requested the data, it showed an error.
ERROR Error: Network error: Cannot convert number to Ljava/text/NumberFormat; at index 0
i dont't konw how to resolve it,
this is my code:
```
constructor(
        private apollo: Apollo,
        private getDataService: GetDataService
    ) {
        this.getDataService.subject.subscribe((val) => {
            if (val === true) {
                this.getData();
            }
        });
    }
it will be execute  this.getData()  function
this is my getData()

 this.querySubscription = this.apollo.watchQuery<any>({
            query: getInspireProfile
        }).valueChanges.subscribe(({ data }) => {
            if (data && data.getInspire) {
                const datas = data.getInspire;
                const code = datas.code;
                if (code === 404) {
                } else if (code === 200) {
                    this.getInspire = datas;
                }
            }
        });
```
when i use BehaviorSubject()
iMake sure getData()  has been executed
but i get error

**Comment by cnqiuxue** [comment]
It's not answer  https://github.com/NativeScript/android-runtime/issues/540

**Comment by nobodyiam** [comment]
Are you sure this is the right Apollo component you are using?

This Apollo is a distributed configuration center mainly targeting backend services...

**Comment by nobodyiam** [comment]
This case is closed for now. If there is any other problem, you could provide more information to this issue, thanks!
