### ISSUE TITLE
添加集群的时候只勾选了一个环境，该新建集群却出现在了所有环境下。

### ISSUE THREAD

**Issue by Anthony-Lu** [ctripcorp/apollo#1217]
作者你好，我在创建集群的时候，只选择了一个环境（比如DEV），回到项目首页时发现所有环境下都有这个集群名称。如图:
![image](https://user-images.githubusercontent.com/22461221/42142953-081fad60-7de5-11e8-9f7f-7adf75f1f894.png)
![image](https://user-images.githubusercontent.com/22461221/42143299-00b91992-7de7-11e8-9df4-b556e31935ab.png)
![image](https://user-images.githubusercontent.com/22461221/42143027-8a3aef58-7de5-11e8-938d-ad48e8dae3e2.png)

**Comment by nobodyiam** [comment]
每个环境需要独立部署config service, admin service和config db的。

**Comment by Anthony-Lu** [comment]
那也就是说，如果只有一个环境的话，就会出现这种情况了是吗。好吧。
多谢了。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
