### ISSUE TITLE
灰度的时候能不能删除某个配置呢？

### ISSUE THREAD

**Issue by stateIs0** [ctripcorp/apollo#1218]
目前有个需求，希望灰度的时候，能删除掉某个配置，但目前 apollo 好像不支持，如果自己修改的话，怎么改更为合适呢？目前看源码，似乎不是很好改。

**Comment by nobodyiam** [comment]
灰度一般都是测试一些新的配置啥的，在什么场景下需要删除一个配置？因为删除的话，程序中等于会拿到一个默认值。

**Comment by stateIs0** [comment]
@nobodyiam 不仅仅是测试新的配置，也会删除旧的配置，我觉得都属于编辑的范畴里？但目前 apollo 好像不太好支持？

**Comment by stateIs0** [comment]
@nobodyiam 目前是场景是：应用在进行灰度时，主版本的某个配置会影响灰度版本，所以，希望在灰度版本里不要有这个配置。

**Comment by nobodyiam** [comment]
代码中一般都会设置默认值的，所以考虑在灰度中把值改为默认值就达到删除配置的效果了吧

**Comment by stateIs0** [comment]
现在的情况是：灰度的时候，不知道默认值。
