### ISSUE TITLE
apollo兼容dubbo-spring-boot-starter问题反馈

### ISSUE THREAD

**Issue by linrol** [ctripcorp/apollo#1219]
经测试，Apollo版本0.10.2在bootstrap阶段注入默认application namespace配置apollo.bootstrap.enabled = true无效，需要在Apollo-client源码类下的ApolloApplicationContextInitializer添加@Order注解调整类配置加载顺序，希望官方改进一下
![image](https://user-images.githubusercontent.com/18043615/42194475-b8b02ada-7ea6-11e8-9676-5880831f40f0.png)

**Comment by nobodyiam** [comment]
https://github.com/ctripcorp/apollo-use-cases/tree/master/spring-boot-dubbo

上面这个是我们的一个sample，没有遇到你说的问题，看一下？

**Comment by nobodyiam** [comment]
关于dubbo spring boot starter，可以参考 #1102 中的讨论，建议使用 [incubator-dubbo-spring-boot-project](https://github.com/apache/incubator-dubbo-spring-boot-project)，这个目前测试下来都是OK的，也是官方维护的版本。

case先关闭了，如还有问题，可以提供更多信息，或进群交流。
