### ISSUE TITLE
mvn test报错

### ISSUE THREAD

**Issue by JaredTan95** [ctripcorp/apollo#1220]
- cd apollo
- mvn test
报错如下：
-------------------------------------------------------------------------------
Test set: com.ctrip.framework.apollo.adminservice.controller.AppControllerTest
-------------------------------------------------------------------------------
Tests run: 6, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.313 sec <<< FAILURE! - in com.ctrip.framework.apollo.adminservice.controller.AppControllerTest
testCreateTwice(com.ctrip.framework.apollo.adminservice.controller.AppControllerTest)  Time elapsed: 0.045 sec  <<< ERROR!
org.springframework.web.client.HttpServerErrorException: 500 Internal Server Error
	at com.ctrip.framework.apollo.adminservice.controller.AppControllerTest.testCreateTwice(AppControllerTest.java:65)

testCheckIfAppIdUnique(com.ctrip.framework.apollo.adminservice.controller.AppControllerTest)  Time elapsed: 0.041 sec  <<< ERROR!
org.springframework.web.client.HttpServerErrorException: 500 Internal Server Error
	at com.ctrip.framework.apollo.adminservice.controller.AppControllerTest.testCheckIfAppIdUnique(AppControllerTest.java:30)

testCreate(com.ctrip.framework.apollo.adminservice.controller.AppControllerTest)  Time elapsed: 0.041 sec  <<< ERROR!
org.springframework.web.client.HttpServerErrorException: 500 Internal Server Error
	at com.ctrip.framework.apollo.adminservice.controller.AppControllerTest.testCreate(AppControllerTest.java:49)

但是单独跑测试是ok的。

**Comment by nobodyiam** [comment]
这个在travis ci和我本地跑都是过的，另外这个测试看了一下，调用的是测试中启动的服务，不会是500的，你本地能稳定重现？

**Comment by JaredTan95** [comment]
能重现。
- cd apollo
- mvn test
按照提示,进入apollo-adminservice/target/surefire-reports/com.ctrip.framework.apollo.adminservice.controller.AppControllerTest.txt 发现如下错误：
-------------------------------------------------------------------------------
Test set: com.ctrip.framework.apollo.adminservice.controller.AppControllerTest
-------------------------------------------------------------------------------
Tests run: 6, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.321 sec <<< FAILURE! - in com.ctrip.framework.apollo.adminservice.controller.AppControllerTest
testCreateTwice(com.ctrip.framework.apollo.adminservice.controller.AppControllerTest)  Time elapsed: 0.058 sec  <<< ERROR!
org.springframework.web.client.HttpServerErrorException: 500 Internal Server Error
	at com.ctrip.framework.apollo.adminservice.controller.AppControllerTest.testCreateTwice(AppControllerTest.java:66)

testCheckIfAppIdUnique(com.ctrip.framework.apollo.adminservice.controller.AppControllerTest)  Time elapsed: 0.049 sec  <<< ERROR!
org.springframework.web.client.HttpServerErrorException: 500 Internal Server Error
	at com.ctrip.framework.apollo.adminservice.controller.AppControllerTest.testCheckIfAppIdUnique(AppControllerTest.java:31)

testCreate(com.ctrip.framework.apollo.adminservice.controller.AppControllerTest)  Time elapsed: 0.031 sec  <<< ERROR!
org.springframework.web.client.HttpServerErrorException: 500 Internal Server Error
	at com.ctrip.framework.apollo.adminservice.controller.AppControllerTest.testCreate(AppControllerTest.java:50)

每次都会出错，但是没有更多详细的信息。

**Comment by nobodyiam** [comment]
travis ci上一直是好的，你这边还能复现这个问题吗？

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
