### ISSUE TITLE
迁移老项目问题所有@Configuration的地方都要配合@EnableApolloConfig使用么？

### ISSUE THREAD

**Issue by yyf365** [ctripcorp/apollo#1221]
如题：迁移老项目时候，之前用的springcloud的config-server，换用Apollo的话需要在原来所有@Configuration的地方都要加@EnableApolloConfig注解才能使用么？

当前的问题是有很多组件是过程中不同团队以jar的形式提供的，大部分组件中需要读取配置。那么就需要所有组件团队都修改源码增加@EnableApolloConfig来使用Apollo的参数，这样代价有点大，有没有平滑的切换办法呢？

**Comment by nobodyiam** [comment]
@EnableApolloConfig 在一个应用内只要加一次即可

如果用到了多个namespace，那么在@EnableApolloConfig中可以一次性指定多个

**Comment by liuqingliu** [comment]
多个namespace中有相同的key，会怎样选择读取顺序呢？

**Comment by nobodyiam** [comment]
在 #1183 中回复了，如果还有疑问，建议参考一下 [Spring中的Environment和PropertySource](http://nobodyiam.com/2016/04/02/dive-into-spring-cloud-config/#341-%E8%83%8C%E6%99%AF%E7%9F%A5%E8%AF%86)

**Comment by EonianGlutton** [comment]
不需要，只需要在application.properties或者application.yml中指定一次即可

**Comment by yyf365** [comment]
多谢支持

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
