### ISSUE TITLE
Unable to start embedded Tomcat，apollo-configservice启动失败

### ISSUE THREAD

**Issue by randomSpirit** [ctripcorp/apollo#1222]
Unable to start embedded Tomcat
apollo-configservice启动失败
日志如下，麻烦帮忙看看，谢谢啊
[apollo-configservice.log](https://github.com/ctripcorp/apollo/files/2158937/apollo-configservice.log)
[apollo-configservice_rootapollo-configservice.log](https://github.com/ctripcorp/apollo/files/2158944/apollo-configservice_rootapollo-configservice.log)

**Comment by nobodyiam** [comment]
Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalArgumentException: URL must start with 'jdbc'

看上去是数据库信息配置有问题

**Comment by randomSpirit** [comment]
相同配置本地能连，到测试就出问题了……

**Comment by randomSpirit** [comment]
build.sh中apollo_portal_db_password用了特殊密码，由单引号引住，应该是这个影响了apollo_portal_db_url，改掉不再报这个错
