### ISSUE TITLE
java客户端使用配置文件application.properties中使用，如：spring.datasource.url: ${someKeyFromApollo:someDefaultValue}  不能热更新

### ISSUE THREAD

**Issue by abc903349085** [ctripcorp/apollo#1224]
我在配置文件config.properties中获取apollo中的配置信息，程序中再获取配置config.properties的值。问题是apollo配置的信息更新后，获取的值却不能更新，只能重新启动才能更新。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
