### ISSUE TITLE
删除namespace再创建

### ISSUE THREAD

**Issue by j782282271** [ctripcorp/apollo#1227]
你好，我有3个问题：
1）创建一个namespace名为“abc”，然后删除，然后再创建名为“abc”的namespace，提示已存在，数据库中应该是软删除吧？这个问题有考虑过解决一下吗？这个问题会出现在以下场景中，在A项目中创建public的namespace=“abc”，发现创建错了，应该创建在B项目下，这样删除后无法用原名字，只能换名字。
2）项目无法删除，有考虑增加删除项目功能吗？
3）删除namespace提示，该namesapce有两个实例在使用，无法删除，请让apollo相关负责人删除，我用的是apollo帐号也不能删除吗？那应该怎样删除？
谢谢回答

**Comment by nobodyiam** [comment]
公共namespace目前删除的是关联的namespace，而不是元信息，所以再次创建会提示已存在

项目因为一般上生产之后很少有删除的需求，而且删除可能会造成一些不可预料的问题，所以如果一定要删，现在是提供sql删除的，详见 https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#5-%E5%A6%82%E4%BD%95%E5%88%A0%E9%99%A4%E5%BA%94%E7%94%A8%E9%9B%86%E7%BE%A4namespace

提示实例在使用，说明不应该删除，如果确认要删，可以先去instance config表把相关的实例信息先删除，然后界面上就可以操作了

**Comment by nobodyiam** [comment]
最新的master版本已经增加了管理员工具页面，可以删除应用、集群和AppNamespace，会在0.11.0版本中发布，相关文档已经更新，可以参考一下。

https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#5-%E5%A6%82%E4%BD%95%E5%88%A0%E9%99%A4%E5%BA%94%E7%94%A8%E9%9B%86%E7%BE%A4namespace

**Comment by j782282271** [comment]
感谢还记得我得提问。赞

**Comment by nobodyiam** [comment]
如果之前版本是0.9.0及以后的话就不需要升级数据库，直接用最新的代码即可

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
