### ISSUE TITLE
xsd文件404导致xml标签报错问题反馈

### ISSUE THREAD

**Issue by wysun003** [ctripcorp/apollo#1230]
![image](https://user-images.githubusercontent.com/40553921/42323048-5bb2c2d8-8091-11e8-9910-c7ffc727274e.png)

**Comment by nobodyiam** [comment]
xsd是在jar包中的，不是真的放在网上的

你是用的eclipse？我们用的idea都没这个问题来着

https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/resources/META-INF/spring.schemas

**Comment by wysun003** [comment]
基于xml方式引入多个namespace后，在代码中如何获取key值呢

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
