### ISSUE TITLE
批量导入配置

### ISSUE THREAD

**Issue by j782282271** [ctripcorp/apollo#1233]
作者你好，apollo有无提供批量导入数据库的sql？或者单条导入数据库的sql？指定了项目名、集群名、配置key-val集合，可否直接调用sql导入？

**Comment by nobodyiam** [comment]
可以在页面上通过文本模式，ctrl + c, ctrl + v把配置批量复制到namespace中

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
