### ISSUE TITLE
namespace panel 如何设置默认折叠

### ISSUE THREAD

**Issue by EonianGlutton** [ctripcorp/apollo#1234]

**Comment by EonianGlutton** [comment]
目前打开一个应用后，所属的namespace panel都是默认展开的，当一个应用有很多namespace时候，就很不好找，怎么把namespace panel默认折叠呢？我对angular实在不了解，特来求救，谢谢

**Comment by nobodyiam** [comment]
https://github.com/ctripcorp/apollo/blob/master/apollo-portal/src/main/resources/static/views/component/namespace-panel-master-tab.html#L95

把这一样的`class="collapse in"`改为`class="collapse"`即可。

修改了之后，浏览器缓存默认1小时过期，或者自己可以强刷一下。

**Comment by EonianGlutton** [comment]
搞定，赞一下响应速度，多谢多谢
