### ISSUE TITLE
windows下快速安装启动失败

### ISSUE THREAD

**Issue by pjx827480541** [ctripcorp/apollo#1238]
windows64位，JDK路径D:\Program Files\Java\jdk1.8.0_05，按快速安装教程操作，但启动总是失败，错误信息如下：
$ sh ./demo.sh start
==== starting service ====
Service logging file is ./service/apollo-service.log
Started [10596]
Waiting for config service startup........................
Config service failed to start in 120 seconds! Please check ./service/apollo-service.log for more information.

service.log错误信息： ./service/apollo-service.jar:行168: D:\Program: 未找到命令

**Comment by pjx827480541** [comment]
由同样情况的小伙伴吗？怎么解决的？

**Comment by nobodyiam** [comment]
安装一下最新版本的git for windows

**Comment by pjx827480541** [comment]
您好，不是很明白，这个错误和git有什么关系啊？

**Comment by nobodyiam** [comment]
因为windows下是使用git bash运行的，而git bash可以通过git for windows安装

**Comment by pjx827480541** [comment]
我是通过Cygwin来运行的，应该和git没关系吧。我还是升级一下我的git版本，再试一下

**Comment by pjx827480541** [comment]
使用git bash来运行成功了，cygwin里运行就是不行。为什么？？？

**Comment by nobodyiam** [comment]
因为windows下的bash环境千奇百怪，目前只适配了git bash

**Comment by pjx827480541** [comment]
好的，谢谢啦

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by richard2018** [comment]
这个应该写在quickstart文档里，用cygwin64，折腾了几个小时才找到这里

**Comment by pittzhou** [comment]
> 安装一下最新版本的git for windows

我也遇到启动config service失败的问题，报错信息误导我说找不到url，各种折腾耽误了几个小时。升级git for windows到最新版本v2.29.2(2)后，执行./demo.sh start成功。

**Comment by nobodyiam** [comment]
@pittzhou 感谢反馈，已经增加提示到文档中

![image](https://user-images.githubusercontent.com/837658/99894395-3a646b00-2cbe-11eb-87c6-9f982759f5d1.png)
