### ISSUE TITLE
公共命名空间数据未能同步到项目

### ISSUE THREAD

**Issue by wenchongyang** [ctripcorp/apollo#1242]
问题描述：
我有一个公共的项目，包含多个公共的namespace ,其中一个就901.domain。另外一个是业务项目xx，在xx项目添加namespace 时Item表未能插入数据，导致发布的时候配置项为空。界面上都是正常的，我删掉命名空间重新配置还是依旧。 

从数据库Item 查询原始公共的domain里面item是全的。  Release 表Configurations 为{}

**Comment by nobodyiam** [comment]
能否更加具体一点？

**Comment by wenchongyang** [comment]
业务项目 关联公共namespace   Release 表Configurations 为{} 也就是我新关联命空间并发布的时候没有同步 公共namespace   里面的项。  

Release 表 数据内容为 '93', '20180711170229-cdd07ec6585b470b', '20180711170225-release', '', '106001', 'default', '901.domain', '{}', '0', '1', 'yangwenchong', '2018-07-11 17:02:30', 'yangwenchong', '2018-07-11 17:05:59'

Namespace 表 901.domain命名空间的项为数据为:
19 | domain.spm | *** |   | 1 | 1
19 | domain.user-center | *** | 用户中心 | 2 | 0
19 | domain.pay-center | *** |   | 3 | 0
19 | domain.search-center | *** |   | 4 | 0

其他的Namespace  release  的时候 Release 表内容都是正常的 item里面的值都填充到了Configurations json里面去了。

**Comment by wenchongyang** [comment]
经调试发现ReleaseService   152L operateNamespaceItems = getNamespaceItems(namespace); 为空（本来就为空） parentNamespace = namespaceService.findParentNamespace(namespace); parentNamespace  也无法获取到（这里就存在问题？）

**Comment by wenchongyang** [comment]
更奇怪的问题出现了。重启configserver之后就好了。

**Comment by nobodyiam** [comment]
config server中有`AppNamespace`的缓存，可以看下是否中间有手工改过相关的数据。

**Comment by hepyu** [comment]
> 更奇怪的问题出现了。重启configserver之后就好了。
> 不重启前，添加命名空间，提示404，发布之后config server获取configurations为空。
> 同一份数据库同一份代码，本地启动也是正常的（此时服务器还未重启）。 重启之后，不发布也能取到configurations内容，发布后也正常。有什么是缓存在configserver里面的么？

我也遇到类似问题，有确认是什么原因么。https://github.com/ctripcorp/apollo/issues/1550

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
