### ISSUE TITLE
有关代码量的问题。

### ISSUE THREAD

**Issue by yangyz** [ctripcorp/apollo#1244]
宋  你好  通过调试代码发现，想让代码中配置立即生效 ，必须代码中添加 监听器也就是（@ApolloConfigChangeListener）   拿到改变事件 在对对应配置refreshScope   是不是意味着 每次新加个新实体配置 必须加个 这样的处理操作。 还有老系统接入apollo 是不是要把之前的 所有的 实体配置 全部要处理一次。请问 有没有好的办法。

![qq 20180712110152](https://user-images.githubusercontent.com/6257884/42610219-0a4c961c-85c3-11e8-8ab4-7c0a10f7c2c2.png)

**Comment by yangyz** [comment]
还有些 实体配置 可能是其他开源jar包 并没有指定 @RefreshScope 

![qq 20180712111743](https://user-images.githubusercontent.com/6257884/42610679-41700690-85c5-11e8-902f-63ce161a1119.png)

**Comment by nobodyiam** [comment]
对于API方式获取的配置，实时是最新的

对于@Value方式注入的配置，最新版本已经支持实时更新了

对于@ConfigurationProperties方式注入的配置，可以通过publish event的方式刷新，比如zuul properties的刷新可以参考 https://github.com/ctripcorp/apollo-use-cases/blob/master/spring-cloud-zuul/src/main/java/com/ctrip/framework/apollo/use/cases/spring/cloud/zuul/ZuulPropertiesRefresher.java

**Comment by yangyz** [comment]
你说的api方式获取配置 是。。
我找了处理 第三方的属性实体一种新方式 似乎可以  

![qq 20180716104442](https://user-images.githubusercontent.com/6257884/42741484-479f1f92-88e5-11e8-9ec4-d915ce9e61e8.png)

**Comment by nobodyiam** [comment]
这种方式也可以的，或者基于spring cloud的方式也可以的：https://github.com/ctripcorp/apollo-use-cases/blob/master/spring-cloud-zuul/src/main/java/com/ctrip/framework/apollo/use/cases/spring/cloud/zuul/ZuulPropertiesRefresher.java

**Comment by yangyz** [comment]
谢谢 宋
