### ISSUE TITLE
不能针对环境 来分类建 namespace么

### ISSUE THREAD

**Issue by yangyz** [ctripcorp/apollo#1245]
![qq 20180712114416](https://user-images.githubusercontent.com/6257884/42611520-25a3d4ce-85c9-11e8-8fb1-65b4fbbfd6f9.png)
![qq 20180712114536](https://user-images.githubusercontent.com/6257884/42611522-264fd24c-85c9-11e8-9722-317bff977a9d.png)

**Comment by pandalin** [comment]
我也有这样的需求，不同环境需要私有的独立的namespace，发现不能建相同的名字只能用公共的，可是又不能弄成公共的

**Comment by yangyz** [comment]
恩咯  不知道有好的方案么

**Comment by nobodyiam** [comment]
私有的namespace目前是在所有环境中都会默认创建的，所以你指的独立namespace具体是啥意思？

**Comment by pandalin** [comment]
就是每个环境中除了application这个私有namespace外，还有其他的私有namespace。目前是在1个如dev环境建立了如framework的私有namespace后，在test和其他环境这个framework的私有namespace同步不了，也不能新增相同的namespace，会提示名称已存在

**Comment by nobodyiam** [comment]
你是后增加的环境？参考一下这个文档：[2.1.2.1 从别的环境导入ApolloConfigDB的项目数据](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#2121-%E4%BB%8E%E5%88%AB%E7%9A%84%E7%8E%AF%E5%A2%83%E5%AF%BC%E5%85%A5apolloconfigdb%E7%9A%84%E9%A1%B9%E7%9B%AE%E6%95%B0%E6%8D%AE)

**Comment by pandalin** [comment]
不是的，就是项目里面想配置独立的私有namespace（非默认）以便于进行区分，不同人员维护不同的namespace。目前来看只能是先建公共的，再建关联的namespace才行

**Comment by nobodyiam** [comment]
目前私有的也可以不同人员维护不同的namespace啊，私有namespace在每个环境都有似乎也没啥问题吧？

**Comment by pandalin** [comment]
@nobodyiam 不同环境不能建相同的私有namespace啊

**Comment by pandalin** [comment]
@nobodyiam 谢谢，可以了，得再新建namespace的时候就选上所有环境就行了，而不能在一个环境新建后再采用同步的方式同步到其他环境

**Comment by yangyz** [comment]
@pandalin  截图看看  我的需求是  想满足 不同环境 私有namespace 名字可以相同，application 就是的，但为了区分  或者配置太多 想分几个namespace 来管理 。又不想 开发环境是 dev_framework  测试环境 是 test_framework  而是想  application 一样 ，通过选环境 来区分 而不是通过 namespace 名字来区分。
dev  环境   application  framework
test  环境  application framework

**Comment by pandalin** [comment]
@yangyz 是这样吗
![zzz](https://user-images.githubusercontent.com/7484610/42744420-095448ec-88ff-11e8-9fc5-f08814af9dc2.png)
![bb](https://user-images.githubusercontent.com/7484610/42744433-1d29c20c-88ff-11e8-8039-199dfc99665e.png)

**Comment by yangyz** [comment]
@pandalin  嗯 对是这样  在dev  demotest 加上配置 pre demotest 看的到吗， 我的需求就是看不到 ，每个环境有自己的 namespace(自定义名字)

**Comment by yangyz** [comment]
朋友 直接上个图 能区分开来的 你之前的图 看不出来  吧key 改成不一样 谢谢

**Comment by hahaduo** [comment]
以上个性化的配置，在程序里面如何使用呢？

**Comment by nobodyiam** [comment]
可以参考一下[Java客户端使用指南](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)

**Comment by yangyz** [comment]
@nobodyiam  如果一个环境下 有多个 配置文件 可以指定 那个先执行哪个后执行么  比如上图中 dev 环境下 有application  demotest   比如 application 先执行于  demotest

**Comment by nobodyiam** [comment]
@yangyz 可以的，在Java客户端使用指南里面都有说明
