### ISSUE TITLE
不同namespace PropertyPlaceholder无法替换的bug

### ISSUE THREAD

**Issue by wenchongyang** [ctripcorp/apollo#1246]
有一公共namespace  存放域名相关配置，业务项目中引用该公共namespace .在此业务项目中私有namespace  有一占位 "http://${domain.pay-center}:8080/ 直接使用ConfigService.getConfig("xxx").getProperty() 只能获取到原始的值，而不是替换后的值。

**Comment by nobodyiam** [comment]
是的，API方式目前不会做引用解析的

建议通过spring注入吧，这个方式是支持替换引用配置的。

**Comment by wenchongyang** [comment]
spring注入吧支持引用替换热更新么？即placeholder 只改占位值，对应的key值会跟踪动态变动么？比如{domain.pay}改了。其他的{domain.pay}/api/xxx 会相应的动态变动么？

**Comment by nobodyiam** [comment]
一层引用是支持的，比如a = ${b}, b = xx，如果b改成了yy，那么a也会变成yy

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
