### ISSUE TITLE
apollo项目在本地idea启动时pom文件中报错，导致maven install不可以

### ISSUE THREAD

**Issue by akenisocean** [ctripcorp/apollo#1250]
![apollo](https://user-images.githubusercontent.com/27925537/42732487-19b7b840-8855-11e8-8caf-c1099f1765c8.png)

**Comment by nobodyiam** [comment]
标红的这个是travis profile才会启用的，本地直接`mvn clean install -DskipTests=true`是不会有问题的。

**Comment by akenisocean** [comment]
谢谢，解决了，maven中添加跳过测试就解决了

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
