### ISSUE TITLE
新建名字空间的时候页面不出现public和private的选择

### ISSUE THREAD

**Issue by onethin** [ctripcorp/apollo#1251]
生产环境，新建名字空间的时候页面不出现public和private的选择，页面固定死是公共名字空间的画面，这要导致不能建立私有的名字空间，本来是有个public和private的选择。但是如果把项目的管理员添加给apollo，用apollo管理员用户进去就有(当前用户对该项目也有管理员权限)。奇怪的是就算用这个用户新建的项目，这样项目负责人管理员什么的都是他，也没有public和private的选择，不知道是什么原因？

**Comment by onethin** [comment]
0.10.2版本，测试环境没有出现

**Comment by nobodyiam** [comment]
从0.10.2开始默认是不开启private namespace选项的，可以通过一个配置项开启，参见 [admin.createPrivateNamespace.switch](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#6admincreateprivatenamespaceswitch)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
