### ISSUE TITLE
放弃灰度时 sendMessage 会走 2 次

### ISSUE THREAD

**Issue by stateIs0** [ctripcorp/apollo#1257]
biz  模块下 NamespaceService.deleteNamespace(Namespace, String)  会被多个地方调用，而该方法内部会调用 sendMessage，因此在某个级联操作时，会无意中触发 sendMessage，造成多次发送消息，configServer 也就会重复消费消息，徒增压力。

例如放弃灰度时，就会走两遍。

从方法调用链来看，全量发布时也会发生。

![image](https://user-images.githubusercontent.com/24973360/42794732-0a23dcd8-89b3-11e8-803f-e830ed978b26.png)

**Comment by nobodyiam** [comment]
仔细看了代码并且跑了一下，其实多次发送的消息是不同的，一个是主版本的release message，一个是灰度版本的release message。

两个release message都是需要发送的，所以不是重复消息。

**Comment by nobodyiam** [comment]
因为使用灰度的客户端其实自己是不知道灰度这个事情的，所以监听的是主版本，当灰度放弃的时候，需要更新这些被灰度的客户端。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
