### ISSUE TITLE
关于meta-server和start.up疑问

### ISSUE THREAD

**Issue by seguzhizi** [ctripcorp/apollo#1263]
1：meta-server的地址是否支持负载均衡的ip？
2：在config，admin，portal的启动脚本startup.sh中，里面的参数SERVER_URL有什么作用？
我看脚本里面默认的是SERVER_URL="http://localhost:$SERVER_PORT"，不知道部署时，是否需要将localhost替换成实际ip？
谢谢~！

**Comment by BillBearXiong** [comment]
很想知道Meta Server代表什么，在这个apollo架构中干什么用的啊？

**Comment by nobodyiam** [comment]
@seguzhizi 

1. master上的代码支持了meta server填多个ip，详见 #1214 
2. SERVER_URL是给启动阶段检查是否启动成功用的，不需要替换成实际IP，使用localhost即可

@BillBearXiong 

建议看一下[Apollo配置中心架构剖析](https://mp.weixin.qq.com/s/-hUaQPzfsl9Lm3IqQW3VDQ)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
