### ISSUE TITLE
各位大神，紧急求助，使用openapi无法获取配置信息，需要什么其他的配置吗？

### ISSUE THREAD

**Issue by hanyan0310** [ctripcorp/apollo#1265]
Apollo开放平台使用遇到问题，根据文档，自己增加了一个项目，然后使用生成的token无法获取到信息，

**Comment by nobodyiam** [comment]
照着[Apollo开放平台](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0)文档做，应该是没有问题的。

**Comment by hanyan0310** [comment]
嗯，端口弄错了导致访问不了，修改后就好了。多谢
