### ISSUE TITLE
Apollo-Poral通过Docker部署，无法正确获取meta_server

### ISSUE THREAD

**Issue by jason163** [ctripcorp/apollo#1266]
Apollo版本：0.11.0

通过源代码自己打包成镜像，通过Docer-Compose进行部署：
![image](https://user-images.githubusercontent.com/3665287/42932252-622d67ba-8b74-11e8-84b3-cd77148ef1d2.png)
ConfigServer&AdminServer正常启动

![image](https://user-images.githubusercontent.com/3665287/42932150-22aab962-8b74-11e8-92ef-c15b2c43b364.png)

但是Portal启动报错，
![image](https://user-images.githubusercontent.com/3665287/42932110-05267994-8b74-11e8-8084-8b344d3a344e.png)

Portal端通过环境变量传递而且容器内相应的环境变量有正常的值，但是Portal无法正确获取

**Comment by nobodyiam** [comment]
dev_meta目前要么是通过apollo-core.jar中的apollo-env.properties设置，要么是通过java的system property(-Ddev_meta=xxx)，不会读取系统环境变量的

**Comment by jason163** [comment]
@ @nobodyiam ${dev_meta}、${fat_meta}、${uat_meta}、${lpt_meta}、${pro_meta} 都通过在apollo-env.properties里面设置吗？这样打包的镜像对metaserver依赖太强了，不能通用

**Comment by zengqinglei** [comment]
@jason163 楼主，现在这个portal启动参数能读取环境变量问题解决了么？

**Comment by nobodyiam** [comment]
@jason163 @zengqinglei 

所以是否只要 dev_meta, fat_meta等可以通过系统环境变量配置就可以了？因为目前只读取了System.getProperties()，没有读取System.getenv()，如果是这样的话，后续可以稍微改一下代码。

**Comment by nobodyiam** [comment]
`-Denv=pro -Dpro_meta=xxx`这类是java的system property，可以通过JAVA_OPTS做配置，如：

```yaml
services:
  apollo-portal:
    environment:
      - JAVA_OPTS: "-Ddev_meta=xxx -Dpro_meta=xxx"
```
