### ISSUE TITLE
是否有什么方法能够知道连接apollo成功与否。

### ISSUE THREAD

**Issue by Anthony-Lu** [ctripcorp/apollo#1267]
如题。否则一直尝试重连，会花费很长时间。
比如在没有部署apollo的情况下，希望能立即就去读自己程序中的配置文件，而不是一直在尝试。

**Comment by nobodyiam** [comment]
如果设置env=Local的话，就不会读取远端了。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
