### ISSUE TITLE
多个关联公共namespace页面加载较慢

### ISSUE THREAD

**Issue by wenchongyang** [ctripcorp/apollo#1269]
如题：
主要原因，网络请求过多，主要集中在权限控制、每个命名空间单独请求。
15个关联命名空间， 总请求139 个请求 完成：1.99 分钟。如果集中请求，预计在1S内。

**Comment by nobodyiam** [comment]
是的，目前apollo前端针对数量非常多的namespace，或者非常多的配置，没有做很好的优化，导致页面渲染和加载都比较慢，这块还请大家一起献计献策，类似的还有 #1261
