### ISSUE TITLE
 配置地址变成了服务器的内网ip

### ISSUE THREAD

**Issue by stoneLee81** [ctripcorp/apollo#1270]
我现在的环境是，开发连接到腾讯的apollo dev配置服务器,在apollo-env.pro文件里面dev的配置如下：
dev.meta=http://dev.conf.xxxx.cn
当启动服务时，在打印里面发现连接的是云服务器的内网ip
http://172.16.16.6:8080/configs/2601/default/application?ip=192.168.2.41
但如果我用http://dev.conf.xxxx.cn/configs/2601/default/application?ip=192.168.2.41是可以访问的，请教下，这个是什么原因？

**Comment by rhaonan** [comment]
我脚本里配置的dev.meta也是一个域名 打包出的apollo-client使用的时候http://localhost:8080/services/config?appId=demo&ip=XXXX变成了localhost是什么情况

**Comment by rhaonan** [comment]
com.ctrip.framework.apollo.internals.AbstractConfigRepository - Sync config failed, will retry. Repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository, reason: Get config services failed from http://localhost:8080/services/config?appId=demo&ip=XXXX [Cause: Could not complete get operation [Cause: connect timed out]]

**Comment by SSHamlin** [comment]
apollo-client 启动的时候，ConfigServiceLocator.java updateConfigServices方法会请求http://××××/services/config重新获取meta service地址，而返回的meta server地址是内网ip+端口，所以会出现配置和输出的日志地址不一致的情况。

我也试过在外网使用apollo，我的解决方法是抛弃response中的homepageurl，
修改ConfigServiceLocator.java updateConfigServices方法，
在m_configServices.set(services);这句前面加上如下代码

`for (ServiceDTO service : services) {
            service.setHomepageUrl(m_configUtil.getMetaServerDomainName()+"/");
        }`

**Comment by nobodyiam** [comment]
恩，针对开发阶段的特殊情况，后续可以考虑加一个环境变量配置，允许用户指定config service列表，这样就可以跳过meta server了。

**Comment by JaredTan95** [comment]
@SSHamlin 可以在你启动Apollo-ConfigService的时候传入-Deureka.instance.ip-address=“你云服务器公网IP”,可以暂时解决这个问题。😄

**Comment by stoneLee81** [comment]
好的，多谢

**Comment by nobodyiam** [comment]
@stoneLee81 0.11.0版本增加了一个功能，允许跳过meta server直接指定config service的地址，这样你就不需要修改config service注册的IP了，只需要在本地开发时指定一下即可，详见 #1275 #1291

**Comment by PersonTH** [comment]
> @stoneLee81 0.11.0版本增加了一个功能，允许跳过meta server直接指定config service的地址，这样你就不需要修改config service注册的IP了，只需要在本地开发时指定一下即可，详见 #1275 #1291

在本地，客户端怎么指定？

**Comment by nobodyiam** [comment]
@PersonTH 

![image](https://user-images.githubusercontent.com/837658/57341710-17bb4180-716e-11e9-9384-40bdad97973b.png)

**Comment by RocketTH** [comment]
> @PersonTH
> 
> ![image](https://user-images.githubusercontent.com/837658/57341710-17bb4180-716e-11e9-9384-40bdad97973b.png)

谢谢，搞定了
