### ISSUE TITLE
如何切换使用https？

### ISSUE THREAD

**Issue by ChenXiaoping0708** [ctripcorp/apollo#1284]
目前看Apollo是使用http的，有没有采取单向认证和使用账号密码，并且使用https的已有方案？

**Comment by nobodyiam** [comment]
使用https应该没啥问题吧，只要弄好证书就行。

不过目前设计client连接config service是在内网环境下，所以目前是不带认证的

**Comment by nobodyiam** [comment]
client认证考虑是在客户端和服务端分别增加扩展点，每个公司可以根据自己的实际情况通过spi加载认证逻辑，如果有好的建议也欢迎一起讨论
