### ISSUE TITLE
带点的环境变量：apollo.refreshInterval

### ISSUE THREAD

**Issue by j782282271** [ctripcorp/apollo#1286]
你好作者：
apollo.refreshInterval环境变量用来配置client获取配置的频率。
linux环境变量的key中不允许含点，这个有什么办法吗？
错误：-bash: export: `apollo.refreshInterval=1': not a valid identifier
这个apollo.refreshInterval是-D参数还是系统环境变量

**Comment by nobodyiam** [comment]
apollo.refreshInterval 这个是 -D参数

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
