### ISSUE TITLE
Apollo架构设计？

### ISSUE THREAD

**Issue by MrSummer33** [ctripcorp/apollo#1287]
[Apollo架构设计](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1)

本人觉得，Apollo架构设计有点复杂。出了客户端，可以考虑将portal、configServer、adminServer合并。成本上考虑：维护三个服务和两个数据库，给运维、部署带来了比较大的工作量。
性能上考虑：配置变化的频率不会很大，所以大多数情况下，配置中心的压力也不会太大。

**Comment by MrSummer33** [comment]
@nobodyiam  才疏学浅，想了解一下其中的用意

**Comment by yiming187** [comment]
Apollo设计的背景是互联网级高可用性，可以从这方面多一些考虑。

**Comment by MrSummer33** [comment]
@nobodyiam @yiming187  谢谢回复，对于大规模集群，确实有必要保证配置中心的高可用，但对于中小型企业，是否可以采取集中式部署；
1:中小型企业，服务集群不大，配置中心的压力较小
2:集中部署也可以降低运维的成本

**Comment by MrSummer33** [comment]
@nobodyiam @yiming187 
分析了下apollo同步配置的逻辑，大概总结为以下，顺便有些疑问，忘执教以下。
***configServer通知client***
    &emsp; 1:portal调用AdminServer更改配置
    &emsp; 2:adminServer通过mysql通知configServer配置更改
    &emsp; 3:configServer 通过 ReleaseMessageListener(结合DeferredResult) 通知客户端有配置更新
***client拉取配置***
   &emsp;  1:client主动向config拉取，结合DeferredResult，完成推拉结合
    &emsp; 2:返回ReleaseMessage后重新拉去Release配置信息

***问题***
    &emsp;  1:为什么不直接返回更改的配置信息(Release)，而是返回配置ID(ReleaseMessage)？
    &emsp;  2:能否通过MQ来实现推送模式，通过普通http模式实现拉取模式？个人觉得这样能使整个架构更加简介清晰。

**Comment by nobodyiam** [comment]
1:为什么不直接返回更改的配置信息(Release)，而是返回配置ID(ReleaseMessage)？
考虑幂等性，所以需要返回配置ID，让客户端来拉取配置，从而可以确保配置的正确性。另外，就是使程序逻辑单一，保持简单。

2:能否通过MQ来实现推送模式，通过普通http模式实现拉取模式？个人觉得这样能使整个架构更加简介清晰。
通过MQ实现推送模式也是可以的，但是对于apollo这类最最基础的中间件，是不能依赖于消息的，因为消息系统需要依赖配置中心，不然就形成循环依赖了。

**Comment by MrSummer33** [comment]
@nobodyiam 好的，谢谢回复

**Comment by yiming187** [comment]
@MrSummer33 逻辑上apollo有很多组件，但部署上确实可以部署在一台机器，不同组件不同的进程，用了不同的端口。

**Comment by MrSummer33** [comment]
@yiming187  嗯，demo上就是将adminServer和configServer集中部署的，对于中小型项目部分模块集中部署会更加方便接入。
