### ISSUE TITLE
Springboot中@Configuration注解注入的配置不能刷新

### ISSUE THREAD

**Issue by 1528992118** [ctripcorp/apollo#1290]
<pre>

启动类：
@EnableApolloConfig(value = { "application", "swagger2", "log4j" })
@SpringBootApplication
@EnableTransactionManagement
@Import({ AopConfig.class, ExceptionConfig.class, RedisConfig.class, Swagger2Config.class,
        InterceptorScannerConfig.class, SecurityWebConfig.class, SSOFilterConfig.class, DubboConfig.class,
        CustomFastJsonConfig.class, UtilConfig.class, ApolloConfigListener.class })
@EnableAsync
public class RestApplication {

    public static void main(String[] args) {
        SpringApplication.run(RestApplication.class, args);
    }

}

监听类：

@Configuration
public class ApolloConfigListener {

    @Autowired
    private Swagger2Config Swagger2Config;

    @Autowired
    private RefreshScope refreshScope;

    @ApolloConfigChangeListener(value = { "application", "swagger2", "log4j", "mybatis" })
    private void onChange(ConfigChangeEvent changeEvent) {
        boolean swagger2CacheKeysChanged = false;
        for (String key : changeEvent.changedKeys()) {
            if (key.startsWith("swagger2.sso.")) {
                ConfigChange change = changeEvent.getChange(key);
                System.out.println(String.format(
                        "Found JavaConfigSample change - key: %s, oldValue: %s, newValue: %s, changeType: %s",
                        change.getPropertyName(), change.getOldValue(), change.getNewValue(), change.getChangeType()));
                swagger2CacheKeysChanged = true;
                break;
            }
        }

        if (swagger2CacheKeysChanged) {
            refreshScope.refresh("swagger2Config");
            //refreshScope.refresh("docket");
            System.out.println(Swagger2Config.toString());
        }

    }

}

</pre>
如上在springboot 启动类上注入具体配置，在Aopllo配置中心修改后，监听到了具体值的修改，但不能完成bean的重新注册，比如上面的Swagger2Config配置，我远程修改某些值后，配置类里的通过@Value获取的参数确实修改了，但没有完成bean的重新注册，spring容器中的bean里的参数还是原先的，并没有发生变化。

**Comment by nobodyiam** [comment]
如果要通过refresh scope刷新bean的话，需要这个bean上或者是创建bean的地方标注`@RefreshScope`的，请参考 https://github.com/ctripcorp/apollo/blob/master/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/spring/springBootDemo/config/SampleRedisConfig.java

或者你也可以参考一下apollo use case中刷新zuul properties的方式，https://github.com/ctripcorp/apollo-use-cases/blob/master/spring-cloud-zuul/src/main/java/com/ctrip/framework/apollo/use/cases/spring/cloud/zuul/ZuulPropertiesRefresher.java

**Comment by 1528992118** [comment]
你好，apollo有交流群吗，或者论坛，实际对接中还是有些问题

**Comment by nobodyiam** [comment]
![qq](https://raw.githubusercontent.com/ctripcorp/apollo/master/doc/images/tech-support-qq.png)

**Comment by 1528992118** [comment]
好的，谢谢了

**Comment by hoheyho** [comment]
楼主解决了没？我遇到一模一样的情况。
