### ISSUE TITLE
PostgreSQL适配

### ISSUE THREAD

**Issue by xiao0yy** [ctripcorp/apollo#1293]
由于想基于现有的CockroachDB部署一套Apollo，但官方文档中提供的适配方案不是很“友好”，所以重新做了一次PostgreSQL的适配。

* 仓库地址: https://github.com/xiao0yy/apollo/tree/feature/pg-adaptation
* 适配置代码commit: https://github.com/xiao0yy/apollo/commit/62ffab4781523ab1b451ef7e16471b30b1fe1d0b

> ## PostgreSQL适配
> 
> 基于[apollo v0.10.2](https://github.com/ctripcorp/apollo/tree/v0.10.2)对PostgreSQL做了适配，主要内容：
> 
> * 提供了"pg风格"的建表SQL: `scripts/sql/pg-configdb.sql`与`scripts/sql/pg-portaldb.sql`
>   * 统一使用小写+下划线命名
>   * 字符串全部使用`TEXT`
>   * 某些状态字段使用`BOOLEAN`
> * 对全部`@Entity`及部分`Repository`进行相应适配
>   * 表名字段名映射
>   * `SEQUENCE`映射
>   * 部分实体字段`int` -> `boolean`
>   * 部分HQL调整
>   * 部分SQL调整
> * Mysql Driver替换为PostgreSQL Driver(版本:42.2.4)
> * 加入`hibernate.dialect`与`hibernate.temp.use_jdbc_metadata_defaults`配置(使CockroachDB可用)
> * 去掉`spring.datasource.initSQL=set names utf8mb4`
> 
> 使用[PostgreSQL 9.5](https://www.postgresql.org/)与[CockroachDB 2.0.3](https://www.cockroachlabs.com/)手动测试通.
> 
> ### 未做工作项
> * 单元测试调整
> * Docker测试

因为代码更改不适合PR，所以在issue中做了说明。如有不合规范的地方，请关闭issue。

**Comment by nobodyiam** [comment]
非常感谢！后续我把文档更新一下

**Comment by ORGRUI** [comment]
棒
