### ISSUE TITLE
创建Namespace  - commnet 错别字

### ISSUE THREAD

**Issue by xie0723** [ctripcorp/apollo#1295]
[apollo wiki](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0)

**3.2.4 创建Namespace**
`
commnet | false | String | Namespace说明

错误：commnet 
正确： comment
`

**Comment by nobodyiam** [comment]
非常感谢，已经纠正~
