### ISSUE TITLE
apollo 配置了值，代码设置了默认值，一直取到的是默认值

### ISSUE THREAD

**Issue by hellosx** [ctripcorp/apollo#1297]
@Value("${key:default}")

apollo key = myvalue

代码中一直取到的是defalut

通过调试
Config config = ConfigService.getAppConfig();
config.getProperty("key", "default");
返回的是myvalue

不知道原因，很郁闷

**Comment by nobodyiam** [comment]
@EnableApolloConfig加了吗？
