### ISSUE TITLE
文本模式批量插入，备注如何添加？

### ISSUE THREAD

**Issue by part-time-job** [ctripcorp/apollo#1298]

**Comment by nobodyiam** [comment]
文本模式的话是完全按照properties格式的，如

```
#some comment
a=b
```

**Comment by part-time-job** [comment]
我知道 ，注释行支持 # 和 ！，我想问的是“备注”在批量模式下如何添加？
![image](https://user-images.githubusercontent.com/17715827/43374000-fbbf91dc-93df-11e8-9fe8-aa9b0a37dcbb.png)

**Comment by nobodyiam** [comment]
这个目前不支持

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
