### ISSUE TITLE
Macbook Apollo Client BUILD FAILURE

### ISSUE THREAD

**Issue by yuchao86** [ctripcorp/apollo#1301]
[INFO] Reactor Summary:
[INFO]
[INFO] Apollo ............................................. SUCCESS [  0.678 s]
[INFO] Apollo BuildTools .................................. SUCCESS [  1.333 s]
[INFO] Apollo Core ........................................ SUCCESS [  1.588 s]
[INFO] Apollo Client ...................................... FAILURE [  0.704 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.113 s
[INFO] Finished at: 2018-07-30T10:47:21+08:00
[INFO] Final Memory: 46M/368M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project apollo-client: Compilation failure: Compilation failure:
[ERROR] /Users/yuchao/AILab/apollo-config/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/RemoteConfigRepository.java:[17,40] 程序包com.ctrip.framework.apollo.build不存在
[ERROR] /Users/yuchao/AILab/apollo-config/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/ConfigServiceLocator.java:[13,40] 程序包com.ctrip.framework.apollo.build不存在
[ERROR] /Users/yuchao/AILab/apollo-config/apollo-client/src/main/java/com/ctrip/framework/apollo/util/http/HttpUtil.java:[3,40] 程序包com.ctrip.framework.apollo.build不存在
[ERROR] /Users/yuchao/AILab/apollo-config/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/RemoteConfigLongPollService.java:[16,40] 程序包com.ctrip.framework.apollo.build不存在
[ERROR] /Users/yuchao/AILab/apollo-config/apollo-client/src/main/java/com/ctrip/framework/apollo/ConfigService.java:[3,40] 程序包com.ctrip.framework.apollo.build不存在
[ERROR] /Users/yuchao/AILab/apollo-config/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/annotation/SpringValueProcessor.java:[3,40] 程序包com.ctrip.framework.apollo.build不存在
[ERROR] /Users/yuchao/AILab/apollo-config/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/DefaultConfigManager.java:[7,40] 程序包com.ctrip.framework.apollo.build不存在
[ERROR] /Users/yuchao/AILab/apollo-config/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/property/SpringValueDefinitionProcessor.java:[17,40] 程序包com.ctrip.framework.apollo.build不存在
[ERROR] /Users/yuchao/AILab/apollo-config/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/LocalFileConfigRepository.java:[17,40] 程序包com.ctrip.framework.apollo.build不存在
[ERROR] /Users/yuchao/AILab/apollo-config/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/AbstractConfig.java:[18,40] 程序包com.ctrip.framework.apollo.build不存在
[ERROR] /Users/yuchao/AILab/apollo-config/apollo-client/src/main/java/com/ctrip/framework/apollo/spi/DefaultConfigFactory.java:[8,40] 程序包com.ctrip.framework.apollo.build不存在
[ERROR] /Users/yuchao/AILab/apollo-config/apollo-client/src/main/java/com/ctrip/framework/apollo/spi/DefaultConfigFactoryManager.java:[5,40] 程序包com.ctrip.framework.apollo.build不存在
[ERROR] /Users/yuchao/AILab/apollo-config/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/config/PropertySourcesProcessor.java:[3,40] 程序包com.ctrip.framework.apollo.build不存在
[ERROR] /Users/yuchao/AILab/apollo-config/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/annotation/ApolloJsonValueProcessor.java:[3,40] 程序包com.ctrip.framework.apollo.build不存在
[ERROR] /Users/yuchao/AILab/apollo-config/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/RemoteConfigRepository.java:[79,20] 找不到符号
[ERROR] 符号:   变量 ApolloInjector

**Comment by nobodyiam** [comment]
这个看上去是代码少了，你重新clone一份，或者直接从github上下载吧，如果没啥定制需求的话，也可以直接从release页面下载:https://github.com/ctripcorp/apollo/releases

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
