### ISSUE TITLE
Macbook Pro下独立部署时16G内存也被挤爆致电脑死机，重现率100%

### ISSUE THREAD

**Issue by hahaduo** [ctripcorp/apollo#1302]
通过.github.zip方式独立部署，只启动了configservice和adminservice，内存逐渐被占满直到100%，各种参数调整也解决不了问题。如果在
idea中以开发模式启动就没有问题。不知道大家有没有遇到同样问题的。目前已经暂时放弃apollo的部署，切换回spring cloud config，等项目忙过了再回来看看问题。

**Comment by nobodyiam** [comment]
zip包中的startup.sh可以调jvm内存参数的

通过idea方式启动和github启动本质上没有啥区别，唯一的区别是idea方式启动了两个进程（config service和admin service集成在一起了），github的方式启动了3个进程

**Comment by pluto-tu** [comment]
调下jvm参数就好 apollo启动默认设置的-Xms -Xmx修改下 就可以了
