### ISSUE TITLE
不传releaseKey的返回代码

### ISSUE THREAD

**Issue by yezl77** [ctripcorp/apollo#1304]
请问通过不带缓存的Http接口从Apollo读取配置时，如果我不传releaseKey给服务器，其他都有，那么请问返回结果是怎么定义的？

**Comment by nobodyiam** [comment]
传releaseKey的意图是如果服务端没有更新，就直接返回304以节省流量和运算。不传的话就返回200和实际的配置。

**Comment by yezl77** [comment]
谢谢谢谢，我也在应用中证实了这一点，可以加到wiki，丰富一下

**Comment by nobodyiam** [comment]
好的，文档已补充。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
