### ISSUE TITLE
数据库密码用明文，能不能用加密以后的密码？

### ISSUE THREAD

**Issue by Neil2016** [ctripcorp/apollo#1305]
数据库密码用明文不好，能不能用加密以后的密码，解密需要在哪里修改？

**Comment by nobodyiam** [comment]
可以参考一下 https://github.com/ctripcorp/apollo-use-cases/tree/master/spring-boot-encrypt

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
