### ISSUE TITLE
有计划把apollo-client提交到maven仓库吗？aliyun或者mvn中央库或者其他？

### ISSUE THREAD

**Issue by otyyyywangwenbin** [ctripcorp/apollo#1307]

**Comment by nobodyiam** [comment]
apollo-client已经推送到Maven中央仓库, [点击此链接查看](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.ctrip.framework.apollo%22%20AND%20a%3A%22apollo-client%22)

**Comment by pandalin** [comment]
如果新增了自定义env的是不是还是得自己打包发布到自己的私有仓库呢

**Comment by otyyyywangwenbin** [comment]
已用，谢谢！
