### ISSUE TITLE
如何在portal中配置新的环境，目前只有DEV

### ISSUE THREAD

**Issue by hahaduo** [ctripcorp/apollo#1308]
如题，找了好久，但还是没有找到。我觉得页面上肯定有课配置的地方，但是就是没有找到。谁能给提示一下，多谢了。

**Comment by nobodyiam** [comment]
由于新增环境操作很少，所以目前主要是通过一些手工配置的，参考一下 [Portal如何增加环境？](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#4-portal%E5%A6%82%E4%BD%95%E5%A2%9E%E5%8A%A0%E7%8E%AF%E5%A2%83)吧
