### ISSUE TITLE
spring配置的redis bean刷新问题

### ISSUE THREAD

**Issue by kkrgwbj** [ctripcorp/apollo#1310]
你好,这边按照文档采用的是RefreshScope方式来刷新bean.刷新是可以成功刷新的.并且我改动了url后都成功的改了.但是连接池的连接还是用的老的.这种如何处理?
修改前:
redis.url = 192.168.10.145
修改后:
redis.url = 192.168.10.151
我在debug过程中发现是改了.然而连接还是用的145的.这种问题,不单单限于redis 包括datasource同样存在诸如此类的问题.

**Comment by kkrgwbj** [comment]
![image](https://user-images.githubusercontent.com/6836934/43509103-41e8c62c-95a4-11e8-856f-434998a4be05.png)

**Comment by kkrgwbj** [comment]
![image](https://user-images.githubusercontent.com/6836934/43511585-5883266e-95ab-11e8-94e6-95abc08deb53.png)
目前测试可以用该方式来实现  比给的demo中的方案来说相对简单许多.

**Comment by kkrgwbj** [comment]
![image](https://user-images.githubusercontent.com/6836934/43512054-a2121014-95ac-11e8-91f2-6949a25de66e.png)
红框的地方漏掉了一些东西.

**Comment by nobodyiam** [comment]
refresh应该也可以的，不过连接释放的地方需要确认一下，是否优雅关闭的。

建议参考一下 https://github.com/ctripcorp/apollo-use-cases/tree/master/dynamic-datasource
