### ISSUE TITLE
PortalSettings 无法获取配置表数据

### ISSUE THREAD

**Issue by xiaopan0513** [ctripcorp/apollo#1311]
![1](https://user-images.githubusercontent.com/8357717/43511103-2b3e8550-95aa-11e8-9906-bbf91accfa6b.jpg)
![2](https://user-images.githubusercontent.com/8357717/43511107-2c85eb4c-95aa-11e8-8b3b-12981a4742c5.jpg)

RefreshableConfig的PostConstruct方法在PortalSettings后面，但是PortalSettings依赖RefreshableConfig的初始化，否则获取不到配置

**Comment by nobodyiam** [comment]
你是遇到了啥问题？我们跑下来没有遇到这方面的问题嘛

PortalSettings依赖PortalConfig(RefreshableConfig)，所以是PortalConfig先初始化吧。

**Comment by xiaopan0513** [comment]
实例化顺序是按依赖来的，但是PostConstruct方法不是的。我debug调试，是先进入PortalSettings的PostConstruct方法，再执行RefreshableConfig的，所以获取不到配置
