### ISSUE TITLE
ConfigService.getAppConfig(); 指定appId加载

### ISSUE THREAD

**Issue by stoneLee81** [ctripcorp/apollo#1316]
如果在类里面通过这种方式不依赖spring ConfigService.getAppConfig(); 去指定加载appId的key-value,该如何实现？

**Comment by stoneLee81** [comment]
这样的，我这是加密的公共类，可能会在不同的子项目里面用到，如果不指定appId,那么需要在各个子项目配置对应的密匙，如果不能的话，就只能走rpc，在某个单独的服务链开这个加密的remote,给其它子项目调用

**Comment by nobodyiam** [comment]
你这个使用公共namespace就可以了吧，参考一下 [Apollo核心概念之“Namespace”](https://github.com/ctripcorp/apollo/wiki/Apollo%E6%A0%B8%E5%BF%83%E6%A6%82%E5%BF%B5%E4%B9%8B%E2%80%9CNamespace%E2%80%9D)

**Comment by stoneLee81** [comment]
@nobodyiam 多谢指点，可以了
