### ISSUE TITLE
apollo关于DB读写分离的问题

### ISSUE THREAD

**Issue by linrol** [ctripcorp/apollo#1318]
我现在有两个库，架设的master-salve主从模式，在apollo怎么才能实现读写分离和数据库的主从同步呢？好像文档上关于数据库这块的说明比较少

**Comment by nobodyiam** [comment]
这块一般的公司内部都很成熟了，所以文档并没有特别说明。

目前config service和admin service都有写操作，所以还是要连master的。

至于主从同步啥的，一般公司的DBA自己会搞定的吧。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
