### ISSUE TITLE
apollo集群环境下怎么保证session一致的问题

### ISSUE THREAD

**Issue by linrol** [ctripcorp/apollo#1319]
apollo分布式搭建环境中apollo-portal配置为集群环境下如何保证session一致呢？

**Comment by nobodyiam** [comment]
ctrip的实现是基于公司的sso的，由sso组件实现登录信息在集群环境下保持一致。

默认提供的是一个简单的基于spring security的实现，这个可以看看spring security的玩法，应该也有集群同步的吧，可以研究一下。

**Comment by DeanJi** [comment]
可以用springsession+redis实现session共享

**Comment by klioen** [comment]
可以使用nginx的一致性hash

**Comment by nobodyiam** [comment]
#3869 fixes this.
