### ISSUE TITLE
访问/notifications/v2接口失败

### ISSUE THREAD

**Issue by wanyxkhalil** [ctripcorp/apollo#1320]
在NotificationControllerV2类pollNotification方法中返回DeferredResult<ResponseEntity<List<ApolloConfigNotification>>>，而在RemoteConfigLongPollService类doLongPollingRefresh方法中调用结果返回接收类为HttpResponse<List<ApolloConfigNotification>>，后者的body为list，从接口中返回的json无法转换。
请问一下怎么处理

**Comment by nobodyiam** [comment]
具体啥问题？你是自己写的第三方客户端吗？

**Comment by wanyxkhalil** [comment]
apollo里config工程的NotificationControllerV2接口，在LongPolling的时候返回值的处理

**Comment by nobodyiam** [comment]
所以你遇到啥问题了？

**Comment by wanyxkhalil** [comment]
接口返回的数据是：
{"body":[{"messages":{"details":{"demo+default+TEST1.hikari":13},"empty":false},"namespaceName":"TEST1.hikari","notificationId":13},{"messages":{"details":{"demo+default+application":19},"empty":false},"namespaceName":"application","notificationId":19},{"messages":{"details":{"demo+default+TEST1.jpa":14},"empty":false},"namespaceName":"TEST1.jpa","notificationId":14},{"messages":{"details":{"demo+default+TEST1.mybatis":15},"empty":false},"namespaceName":"TEST1.mybatis","notificationId":15}],"headers":{},"statusCode":"OK"}
而apollo-client中的接收方的类为List，导致json解析出错。看代码client中是只要了boby部分，不太确定是那部分出错。
这是client中的代码
![image](https://user-images.githubusercontent.com/21099937/43621479-46af33d2-970a-11e8-8033-2a01bb488b06.png)

**Comment by nobodyiam** [comment]
@wanyxkhalil 

这个看上去不是apollo返回的数据，你有修改过apollo后端代码吗？[ResponseEntity](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/ResponseEntity.html)是spring的代码，在实际返回的时候会转换成http的形式，比如header -> response header, statusCode -> status等，不会像你上面贴的那样原样返回的。

**Comment by wanyxkhalil** [comment]
嗯，没有修改这部分的。不过这部分影响范围较小，改一下就好了。谢
