### ISSUE TITLE
让apollo支持yml配置

### ISSUE THREAD

**Issue by ylpu** [ctripcorp/apollo#1321]
今天在apollo上开发了支持yml配置，其中有几个小问题：
1.LocalFileConfigRepository 222行保存到本地文件的时候数据如果有int,long,boolean等类型，保存的时候会报错
2.AbstractConfig 448,449行如果数据为int,long等类型，会拿不到数据。
以上问题都已经解决，目前可以支持yml，是否会有其它问题还需要测试

**Comment by nobodyiam** [comment]
@ylpu 我理解yml的配置应该是做在portal这一层，类似于目前的文本模式。实际保存在数据库中的应该还是kv的格式，所以理论上而言，应该对客户端没有影响？

**Comment by ylpu** [comment]
@nobodyiam ，我想了两种方式，一种是改portal里的FileTextResolver，让它保存成kv的格式，但是修改后页面要把kv还原成yml原来的样子吧；一种是改客户端RemoteConfigRepository中的transformApolloConfigToProperties，在这里面转换。

**Comment by nobodyiam** [comment]
恩，可能更倾向于第一种，不过对格式的保持可能有点难度

**Comment by nobodyiam** [comment]
我新开了一个PR #1944，支持yml类型的namespace注入到Spring中去，大家可以看一下~

**Comment by nobodyiam** [comment]
[1.3.0](https://github.com/ctripcorp/apollo/releases/tag/v1.3.0)版本已经发布，支持了Yml/Yaml格式的namespace和Spring/Spring Boot集成。
