### ISSUE TITLE
第三方应用用用户名和密码可以登录apollo吗?

### ISSUE THREAD

**Issue by wentianmng** [ctripcorp/apollo#1322]
第三方应用用用户名和密码可以登录apollo吗?

**Comment by nobodyiam** [comment]
类似sso？这个集成一下就可以了，参考[Portal-实现用户登录功能](https://github.com/ctripcorp/apollo/wiki/Portal-%E5%AE%9E%E7%8E%B0%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95%E5%8A%9F%E8%83%BD)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
