### ISSUE TITLE
关于RetryableRestTemplate

### ISSUE THREAD

**Issue by kentchenjh** [ctripcorp/apollo#1327]
这几天在阅读源码，看到RetryableRestTemplate部分，看名字应该是能够重试的RestTemplate。看了下实现，发现是RestTemplate发送请求的时候捕获异常，如果是一些特定类型的异常就会触发canRetry方法，但是判断可以retry后，只有一行代码是记录日志，并没有看到如何进行重试的操作。望指点，谢谢！

**Comment by fredxiangdong** [comment]
嗨，你好，我也是上周刚开始接触，说下我的理解，可以一起探讨下。
retry中的确是只有一行记录日志，但是仔细看的话，如果非异常的正常情况，或者非重试的异常，都是进行了相应return，而需要重试的场景，依旧会在for循环里，而for循环的services，是提供该服务的列表地址，即下次换个服务提供者继续尝试。
关于services的取得地方是AdminServiceAddressLocator.getServiceList方法中的cache中获取，而该cache执行put方法，是在refreshServerAddressCache中，通过调用services/admin接口，将服务提供者put进cache中。
相应services/admin接口反馈信息如下：
[
  {
    appName: "APOLLO-ADMINSERVICE",
    instanceId: "192.168.0.103:apollo-adminservice:8090",
   homepageUrl: "http://192.168.0.103:8090/"
  }
]

**Comment by nobodyiam** [comment]
是的，这里的重试是指换一台服务器重试的意思。

**Comment by kentchenjh** [comment]
感谢解答。我原先的理解有误，没有仔细想，其实配置的更新只用通知一个admin service就可以了，毕竟同个env下的admin service下都是共用一个database。
