### ISSUE TITLE
apollo整合Spring Boot Actuator的问题

### ISSUE THREAD

**Issue by wcx945** [ctripcorp/apollo#1332]
在apollo配置了Spring Boot Actuator的启动端口为8090，management.port=8090
程序时正常启动了，但是使用8090端口访问不到actuator应用
![default](https://user-images.githubusercontent.com/17427648/43709374-389f02e4-999f-11e8-865e-71ac5793fdab.png)
![default](https://user-images.githubusercontent.com/17427648/43709389-468c8192-999f-11e8-9ef6-b6ad4f5f2ac6.png)
正常使用properties文件是没问题的
补充：当前项目是web项目，会开启8888端口，如果不配置Actuator的启动端口会默认使用8888的端口，现在使用8888端口是可以访问Actuator应用。但是现在在已经配置了端口，期望使用配置的端口去访问Actuator。

**Comment by wcx945** [comment]
问题已解决，增加application.properties文件增加apollo.bootstrap.enabled=true配置项即可

**Comment by yobuke** [comment]
这个可能是apollo的一个issue。
我改了源码，后来实验成功了。
**目的：为了让Spring boot Admin server可以监控到 apollo admin/config server通过actuator暴露的端点。**

**修改如下：**

![image](https://user-images.githubusercontent.com/3202232/55277378-6e955600-533a-11e9-8b8d-c400efd4a08d.png)


![image](https://user-images.githubusercontent.com/3202232/55277393-95ec2300-533a-11e9-988b-fd9d0781376e.png)


![image](https://user-images.githubusercontent.com/3202232/55277403-aa302000-533a-11e9-9856-57ea51bce22e.png)


![image](https://user-images.githubusercontent.com/3202232/55277409-d2b81a00-533a-11e9-9b9d-77b39d7588a4.png)


![image](https://user-images.githubusercontent.com/3202232/55277413-dba8eb80-533a-11e9-8122-6d15b178adc8.png)


目前还存在一些问题：
1. Metrics are not supported for Spring Boot 1.x applications.
![image](https://user-images.githubusercontent.com/3202232/55277446-48bc8100-533b-11e9-972a-344e17002e65.png)


 2. Fetching traces failed.
Cannot read property 'map' of undefined
![image](https://user-images.githubusercontent.com/3202232/55277449-5a9e2400-533b-11e9-922a-fd1464f04690.png)

3. env加载失败
![image](https://user-images.githubusercontent.com/3202232/55277454-76092f00-533b-11e9-8e32-0e2b3df7e4e6.png)


@nobodyiam

**Comment by ex-allen** [comment]
我接入 springboot actuator 2.0.5 改造完也是同样的问题。

**Comment by nobodyiam** [comment]
apollo最近的版本服务端已经升级到spring boot 2.0.5了
