### ISSUE TITLE
是否可以自动修改配置

### ISSUE THREAD

**Issue by rhaonan** [ctripcorp/apollo#1335]
Portal后台是否提供自动修改配置项的接口或其他方式？
有一些配置项会不断学习定期机器更新，不希望每次通过后台人工操作，希望可以机器自动修改项目配置，请问有什么好的方式，Portal后台是否有对外的接口可用。

**Comment by nobodyiam** [comment]
请参考[Apollo开放平台](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
