### ISSUE TITLE
Release表有什么特殊的吗？

### ISSUE THREAD

**Issue by klioen** [ctripcorp/apollo#1337]
你好，我按照[Quick-Start](https://github.com/ctripcorp/apollo/wiki/Quick-Start)在本地部署了spring-demo，运行起来没有任何问题，但是当我想查看Release表的时候报以下错误：

mysql> select * from Release;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Release' at line 1

别的表都没有问题。

**Comment by zzzwt** [comment]
RELEASE在mysql里边是关键字  需要加上反引号

**Comment by klioen** [comment]
@zzzwt 原来如此，感谢～
