### ISSUE TITLE
多应用配置点明文指向数据库配置，是否有继承复用概念

### ISSUE THREAD

**Issue by schild** [ctripcorp/apollo#1338]
多应用配置部署大部分都是相同的配置，数据库连接，mq连接和密码，redis连接和密码；
这样带来的问题就是改变某一个配置,，所有的应用都要改；还有就是部署比较麻烦

**Comment by nobodyiam** [comment]
可以使用公共Namespace，具体请参考 [Apollo核心概念之“Namespace”](https://github.com/ctripcorp/apollo/wiki/Apollo%E6%A0%B8%E5%BF%83%E6%A6%82%E5%BF%B5%E4%B9%8B%E2%80%9CNamespace%E2%80%9D)

**Comment by schild** [comment]
谢谢~
