### ISSUE TITLE
 wiki - 客户端 meta server 配置说明错误

### ISSUE THREAD

**Issue by chendifan** [ctripcorp/apollo#1343]
https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#122-apollo-meta-server

第5种配置 meta server 的方式中，properties 文件应为 com.ctrip.framework.apollo.core.MetaDomainConsts#getCustomizedMetaServerAddress 中用的 apollo.meta，而不应该带 “-D” 前缀

**Comment by nobodyiam** [comment]
非常感谢，已经修正！
