### ISSUE TITLE
使用 @ApolloConfig 注解时，子容器的 Bean 不进行 PostProcess 的问题

### ISSUE THREAD

**Issue by chendifan** [ctripcorp/apollo#1344]
如题，若项目为 SpringMVC 项目，存在两个容器，父容器扫描除 Controllers 以外的所有 bean，子容器只扫描 Controllers，所以如果在 Controllers 中如下使用：

``` java
@ApolloConfig
private Config config;
```

是注入不进来的，原因应该是 com.ctrip.framework.apollo.spring.annotation.ApolloAnnotationProcessor 被扫描到了父容器中，而子容器不会再进行 processField()，除非在子容器中再声明一下这个 Processor。

是否添加一下这个问题的说明，防止别人再趟这个坑？

**Comment by nobodyiam** [comment]
能够提交一个demo？我们看一下

**Comment by chendifan** [comment]
请参考 [test-post-processor]( https://github.com/chendifan/test-post-processor) 

如 demo 所配置的那样，MVC 子容器没有扫描 com.ctrip.framework.apollo.spring.annotation 包，若将 demo 的 /src/main/resources/spring-servlet.xml 第 18 行注释掉，访问 /test/apollo 为 true。

打开注释，或者在 <context:component-scan> 标签的 base-package 把 com.ctrip.framework.apollo.spring.annotation 给包括进来，结果：访问 /test/apollo 为 false。

**Comment by nobodyiam** [comment]
我看了一下，你这个demo不能工作的原因是因为没有在xml中加 `<apollo:config />`，没有这个注解，apollo是不会被spring带起来的。。。

具体参考一下[3.2.1.1 基于XML的配置](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#32-spring%E6%95%B4%E5%90%88%E6%96%B9%E5%BC%8F)吧。

**Comment by chendifan** [comment]
有点尴...

**Comment by wu560130911** [comment]
这个问题我也遇到了，主要是注解那里没写需要额外配置xml才能生效；
