### ISSUE TITLE
监听 ApplicationPreparedEvent 类型事件的监听器为什么在容器启动后才添加进来？

### ISSUE THREAD

**Issue by chendifan** [ctripcorp/apollo#1347]
如 com.ctrip.framework.apollo.portal.PortalApplication#main，添加 ApplicationPidFileWriter 监听器（26行）是调用 SpringApplication.run（25行） 之后，这样的话，写 pid 的这个监听器还能起作用吗？

**Comment by nobodyiam** [comment]
恩，这样写是没有作用的，这段代码貌似写了两年多没动过，似乎也没啥用。后续修一下吧。
