### ISSUE TITLE
apollo 支持集成测试

### ISSUE THREAD

**Issue by zhangzheng88** [ctripcorp/apollo#1349]
原因：
       集成测试的目标是将应用依赖的服务(如apollo)或者组件(如mysql)在本地mock一个出来，这样就避免了对真实服务或者组件的依赖， apollo作为一个广泛使用的配置中心服务，应该提供一个mock的apollo服务来支持应用的集成测试。
      
特性：
      1   能够从本地配置文件读取配置并注入到应用中
      2  提供修改，发布配置的api接口，并能够触发应用的listener的执行

**Comment by nobodyiam** [comment]
感谢 @zhangzheng88 ，1.1.0版本已经发布，包含了apollo-mockserver模块，文档也已经更新：[六、测试模式](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#%E5%85%AD%E6%B5%8B%E8%AF%95%E6%A8%A1%E5%BC%8F)
