### ISSUE TITLE
Apollo支持huawei CSE服务注册发现中心？

### ISSUE THREAD

**Issue by dongjiang1989** [ctripcorp/apollo#1351]

**Comment by nobodyiam** [comment]
Apollo对服务注册和发现是弱依赖，因为对client和portal而言，只是从meta server获取服务地址而已。

如果需要接入其它注册中心的话，只需要把config service和admin service按照其它注册中心的方式注册上去，然后修改一下 [ServiceController](https://github.com/ctripcorp/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/metaservice/controller/ServiceController.java)即可。
