### ISSUE TITLE
为什么我清掉了本地缓存，并且注释掉了meta.server,依然可以取到配置中心的资源

### ISSUE THREAD

**Issue by GINTOPN** [ctripcorp/apollo#1352]
![image](https://user-images.githubusercontent.com/20829195/43891989-5b5e2bba-9bfd-11e8-9ef1-19049d95a40d.png)

**Comment by GINTOPN** [comment]
我把app.id和dev.meta都放在了app.properties中

**Comment by GINTOPN** [comment]
如果我把dev.meta放在apollo_dev.properties中并且apollo_dev.properties是在resources目录下，就会报如下异常
![image](https://user-images.githubusercontent.com/20829195/43892788-824f3bf4-9bff-11e8-9840-ca82adf71259.png)

**Comment by nobodyiam** [comment]
报这个错一般说明 meta server地址配置错了，你打开 http://192.168.3.11:8080 看看

**Comment by GINTOPN** [comment]
我打开这个地址，是这样的
![image](https://user-images.githubusercontent.com/20829195/43934011-931ce7f8-9c7f-11e8-9e8d-af5c124d23a8.png)
完全没有问题

**Comment by nobodyiam** [comment]
。。。。所以是配错了URL。。。

meta server地址指向的是config service的地址，不是portal的地址

https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1#133-meta-server

**Comment by GINTOPN** [comment]
emmmm，我的锅~~多谢大神指点，没好好理解架构图
在client与service之间还加了一层封装了eraka的metaService，问题已经解决
