### ISSUE TITLE
apollo meta 获取错误

### ISSUE THREAD

**Issue by wangrongruo** [ctripcorp/apollo#1353]
配置多huan环境支持的portal时,读取环境配置地址失败.
直接安装方式配置在apollo-env.properties中,错误信息
 Env is down. env: DEV, failed times: 3, meta server address: http://config.local
![_20180810105235](https://user-images.githubusercontent.com/20267736/43936632-fae1a278-9c8b-11e8-8403-a4c50319a1be.png)
![_20180810105830](https://user-images.githubusercontent.com/20267736/43936701-5d9c8b94-9c8c-11e8-9eef-dd9c392a4074.png)
源码安装方式,meta地址读取为空,只能获取本地环境配置信息.

**Comment by wangrongruo** [comment]
各环境中的eureka服务可以正常发现config与admin服务.

**Comment by wangrongruo** [comment]
我已在项目config目录中新增了apollo-env.properties文件,添加了环境meta配置,但还是无法读取文件,始终使用的是默认配置.
![_20180810112704](https://user-images.githubusercontent.com/20267736/43937509-a64f0fca-9c90-11e8-9436-05a2c0798678.png)

**Comment by wangrongruo** [comment]
重新编译打包后,发现已可以获取meta配置.原因未知.

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
