### ISSUE TITLE
关于云主机部署docker的dotnetcore版本总是获取到内网ip地址的问题

### ISSUE THREAD

**Issue by xwb2535** [ctripcorp/apollo#1358]
部署问题里面有如下解释说，注：如果Apollo部署在公有云上，本地开发环境无法连接，但又需要做开发测试的话，客户端可以升级到0.11.0版本及以上，然后通过-Dapollo.configService=http://config-service的公网IP:端口来跳过meta service的服务发现

请问，具体是在哪里增加这个配置，我好几个地方增加了都不对，.net core客户端，还是只发现了云主机上docker的内网ip地址，一直无法运行。

**Comment by echokk11** [comment]
需要设置
```
System.setProperty("apollo.configService", "http://dev.apollo.ing.ngarihealth.com");
```
已经解决。

**Comment by xwb2535** [comment]
@echokk11  谢谢哈，他们说了，可以通过注册jvm配置实现java的端。java应该是很好解决的，毕竟他们的都是java的版本。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by jxharp** [comment]
@nobodyiam  .net 客户端的这个功能有计划添加吗？ 最近在阿里云上的k8s里面测试apollo，也是同样的问题，内网ip. 暂时无奈只能放弃apollo了。只要能解决立马回来

**Comment by nobodyiam** [comment]
@jxharp 你们用的是apollo.net的哪个版本？标准版还是dot net core版本？

**Comment by wuchang** [comment]
.net core 忽略了~~~~

**Comment by jxharp** [comment]
请问有计划把.net core的加上外网访问的功能吗？ 


现在在云上用不起来啊




------------------ 原始邮件 ------------------
发件人: "wuchang"<notifications@github.com>;
发送时间: 2019年6月2日(星期天) 中午12:25
收件人: "ctripcorp/apollo"<apollo@noreply.github.com>;
抄送: "732709"<harpsmell@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [ctripcorp/apollo] 关于云主机部署docker的dotnetcore版本总是获取到内网ip地址的问题 (#1358)




.net core 忽略了~~~~

**Comment by nobodyiam** [comment]
.net core版本已经支持了，参见 https://github.com/ctripcorp/apollo.net/pull/55
