### ISSUE TITLE
Portal用户无法正常退出

### ISSUE THREAD

**Issue by DeanJi** [ctripcorp/apollo#1359]
使用1.0.0版本，apollo-portal项目下的nav.html的/user/logout改成/logout后用户退出后没有跳转到登入页面
浏览器：IE11 、Chrome49.0.2623.110

**Comment by nobodyiam** [comment]
看了一下代码，应该是你的项目中用了自定义登录，默认因为使用的是/user/logout，所以就无法登出了。

在PR #1363 中我调整了一下，改成一样了。

**Comment by nobodyiam** [comment]
1.1.0版本已经发布，包含了该问题修复，更多信息可以参考： https://github.com/ctripcorp/apollo/releases/tag/v1.1.0
