### ISSUE TITLE
关于postProcessBeanFactory，spring项目(非springboot)中如何在postProcessBeanFactory之前加载配置信息

### ISSUE THREAD

**Issue by GINTOPN** [ctripcorp/apollo#1360]

**Comment by nobodyiam** [comment]
是为了解决什么场景？

之前有人是在启动时通过API方式获取配置使用的

**Comment by GINTOPN** [comment]
其实我开始是这么想得，在application-context.xml中有一个标签： <import reource= ${env}/config/***.xml/>；在启动的时候，配置环境变量 Denv = dev来引入对应的xml，但是这个${env}貌似是在postProcessBeanFactory加载之前就已经占位了。不知道我的理解有没有问题

**Comment by GINTOPN** [comment]
标签是这种形式的： <import resource = ${env}/config/xxx.xml/>

**Comment by GINTOPN** [comment]
标签是这种形式的 <import resource = ${env}/config/xxx.xml>

**Comment by GINTOPN** [comment]
标签是这种形式的 import resource = ${env}/config/xxx.xml

**Comment by nobodyiam** [comment]
-D参数在启动前就引入了
