### ISSUE TITLE
java的SSM框架整合Apollo1.0拉去不到配置文件

### ISSUE THREAD

**Issue by liuch2333** [ctripcorp/apollo#1361]
在SSM整合apollo1.0时，可以从apollo服务中心获取配置到本地缓存，但是项目读取不到apollo的配置文件

**Comment by nobodyiam** [comment]
`@EnableApolloConfig`是否加上了？建议再检查一下相关配置吧，如果找不到问题的话，可以传一个demo上来我们看一下。

**Comment by liuch2333** [comment]
这是引用apollo的配置：
![image](https://user-images.githubusercontent.com/42340934/44075108-01738e4a-9fce-11e8-935a-29ff6904aeb4.png)
这是app.properties:
![image](https://user-images.githubusercontent.com/42340934/44075150-2899d362-9fce-11e8-8a8f-b507d72a8a8f.png)
这是apollo-env.properties：
![image](https://user-images.githubusercontent.com/42340934/44075169-400605ca-9fce-11e8-9eca-3a575e6bd3a7.png)
这是servee.properties:
![image](https://user-images.githubusercontent.com/42340934/44075190-57aeddc8-9fce-11e8-9677-18eba0556a1a.png)
以上就是我的全部配置了

**Comment by nobodyiam** [comment]
看截图没啥问题，客户端日志有啥异常吗？

如果还找不到问题的话，可以尝试debug一下，[PropertySourcesProcessor](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/config/PropertySourcesProcessor.java#L62)
