### ISSUE TITLE
apollo加载配置时@value是否覆盖原有@value功能

### ISSUE THREAD

**Issue by llyeean** [ctripcorp/apollo#1362]
apollo加载配置时，开启了@EnableApolloConfig注解，有部分配置放至apollo，部分配置依旧放至项目resources下的application.yaml文件中，在使用@value获取本地配置时，获取不到，去掉@EnableApolloConfig即可获取到本地配置，
项目环境：spring boot，采用application.yaml配置。
是不是apollo复写了@value的原有功能？求解答！！！

**Comment by nobodyiam** [comment]
`@Value`是Spring解析的，不是Apollo解析的，你看一下application.yaml是否是自己加载的，不是通过spring boot加载的？

**Comment by nobodyiam** [comment]
上传个demo我们看看？

**Comment by YPRY** [comment]
@nobodyiam   同有这个问题   自己加载@value 是通过 PropertyPlaceholderConfigurer  方式  然后apollo 的覆盖的 原有的 value  任何自己加载的value 都去apollo 里取了

**Comment by nobodyiam** [comment]
看一下这个

https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#32-spring%E6%95%B4%E5%90%88%E6%96%B9%E5%BC%8F

![image](https://user-images.githubusercontent.com/837658/44467731-2ef4e600-a656-11e8-821f-938ba20755ff.png)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
