### ISSUE TITLE
新建管理员，无法创建私有nameSpace吗？

### ISSUE THREAD

**Issue by fengyuzhe** [ctripcorp/apollo#1365]
新建用户，项目负责人和管理员都指给新用户。但使用新用户登录该项目时，无法创建私有namespace
![qq 20180814140622](https://user-images.githubusercontent.com/6385909/44074467-42784168-9fcb-11e8-8178-19ab57c0c8b3.png)

**Comment by java-longmiao** [comment]
![default](https://user-images.githubusercontent.com/31102821/44087867-b5b02510-9ff3-11e8-9fcf-e0ba3bb14fe3.png)
或者apollo管理页面有系统参数设置，超级管理员有权限admin.createPrivateNamespace.switch = true即可

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
