### ISSUE TITLE
请教一下，我现在是非springcloud环境，是传统的spring项目；那么我现在要实现热更新，类似于refreshscope这种方式，应该如果操作

### ISSUE THREAD

**Issue by GINTOPN** [ctripcorp/apollo#1366]

**Comment by GINTOPN** [comment]
我的配置文件都放在我的xml里面，请问这些placeholder该如何热更新，或者说ApolloConfigChangeListener这个方法应该怎么写
![image](https://user-images.githubusercontent.com/20829195/44075582-db0149b2-9fcf-11e8-986f-f9148f44bf6c.png)
![image](https://user-images.githubusercontent.com/20829195/44075591-e236f574-9fcf-11e8-9204-3cfc2f690edd.png)

**Comment by nobodyiam** [comment]
最新的版本已经支持配置热更新了，不过你截图中的都是连接池配置，这些光配置更新是不够的，还需要重建连接池才行，可以参考一下 https://github.com/ctripcorp/apollo-use-cases/tree/master/dynamic-datasource

**Comment by GINTOPN** [comment]
![image](https://user-images.githubusercontent.com/20829195/44127478-0b9ee6d8-a070-11e8-9ff3-f90a962999d1.png)
我是这样实现的，请问是否理解恰当

**Comment by nobodyiam** [comment]
看下上面贴的demo吧

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
