### ISSUE TITLE
adminservice和configservice该如何从apollo-master分离出来呢

### ISSUE THREAD

**Issue by BillBearXiong** [ctripcorp/apollo#1367]

**Comment by nobodyiam** [comment]
具体点呢？

**Comment by BillBearXiong** [comment]
比如说adminservice这个项目 现在不是又apollo-master的pom文件管理的吗？如果我单独把admin拿出来，admin会有依赖master中的pom文件中的jar包依赖吗? 会有影响吗？我现在的项目要上Privotal cloud Foundary的 需要注意什么吗？

**Comment by nobodyiam** [comment]
如果是部署的话，没啥关系的，直接把打出来的包部署到云上即可。

目前部署包已经都上传到release页面了，可以直接下载，https://github.com/ctripcorp/apollo/releases

**Comment by BillBearXiong** [comment]
好的   我试试  谢谢

**Comment by BillBearXiong** [comment]
大神 还是没整明白，你说的部署包(比如)apollo-configservice-1.0.0-github.zip是这个吗？直接能上PCF吗？

**Comment by BillBearXiong** [comment]
因为我们平时 是建项目，上传代码上gitlab(公司自己搭的) 然后通过jenkins部署到Privotal cloud Foundary上去，我现在想自己把congfig，admin和portal分别从apollo里直接分离出来，形成一个单独的项目，然后分别上传到gitlab上去，分别部署，这样能行吗？

**Comment by nobodyiam** [comment]
如果是要直接jenkins部署的话，通过maven命令就可以了啊，比如如果你要在CI上单独打包config，那么就执行`mvn clean package -pl apollo-configservice -am -DskipTests=true`，不需要把项目拆开的。

**Comment by BillBearXiong** [comment]
ok  pcf上已经部署成功了，多谢大神

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
