### ISSUE TITLE
apollo-client 初始化时发送get请求到ServiceController从eureka取出来instance的homeUrl是adminservice http://localhost:8090的而不是configservice http://localhost:8080

### ISSUE THREAD

**Issue by java-longmiao** [ctripcorp/apollo#1369]
`[apollo-demo][main]2018-08-14 18:30:19,569 INFO  [com.ctrip.framework.foundation.internals.provider.DefaultApplicationProvider] App ID is set to ssmt by app.id property from /META-INF/app.properties
[apollo-demo][main]2018-08-14 18:30:19,575 INFO  [com.ctrip.framework.foundation.internals.provider.DefaultServerProvider] Loading /opt/settings/server.properties
[apollo-demo][main]2018-08-14 18:30:19,576 INFO  [com.ctrip.framework.foundation.internals.provider.DefaultServerProvider] Environment is set to [DEV] by JVM system property 'env'.
[apollo-demo][main]2018-08-14 18:30:19,577 INFO  [com.ctrip.framework.foundation.internals.provider.DefaultServerProvider] Data Center is set to [apollo] by JVM system property 'idc'.
[apollo-demo][main]2018-08-14 18:30:35,015 INFO  [com.ctrip.framework.apollo.internals.DefaultMetaServerProvider] Located meta services from apollo.meta configuration: http://localhost:8080!
[apollo-demo][main]2018-08-14 18:30:35,041 INFO  [com.ctrip.framework.apollo.core.MetaDomainConsts] Located meta server address http://localhost:8080 for env DEV from com.ctrip.framework.apollo.internals.DefaultMetaServerProvider
[apollo-demo][main]2018-08-14 18:30:48,083 WARN  [com.ctrip.framework.apollo.internals.RemoteConfigRepository] Load config failed, will retry in 1 SECONDS. appId: ssmt, cluster: apollo, namespaces: apollo
[apollo-demo][main]2018-08-14 18:31:00,641 WARN  [com.ctrip.framework.apollo.internals.AbstractConfigRepository] Sync config failed, will retry. Repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository, reason: Load Apollo Config failed - appId: ssmt, cluster: apollo, namespace: apollo, url: http://localhost:8090/configs/ssmt/apollo/apollo?dataCenter=apollo&ip=172.16.8.7 [Cause: [status code: 404] Could not find config for namespace - appId: ssmt, cluster: apollo, namespace: apollo, please check whether the configs are released in Apollo!]
[apollo-demo][main]2018-08-14 18:31:21,958 WARN  [com.ctrip.framework.apollo.internals.RemoteConfigRepository] Load config failed, will retry in 1 SECONDS. appId: ssmt, cluster: apollo, namespaces: apollo
[apollo-demo][Apollo-RemoteConfigLongPollService-1]2018-08-14 18:31:21,960 WARN  [com.ctrip.framework.apollo.internals.RemoteConfigLongPollService] Long polling failed, will retry in 1 seconds. appId: ssmt, cluster: apollo, namespaces: apollo, long polling url: http://localhost:8090/notifications/v2?cluster=apollo&dataCenter=apollo&appId=ssmt&ip=172.16.8.7&notifications=%5B%7B%22namespaceName%22%3A%22apollo%22%2C%22notificationId%22%3A-1%7D%5D, reason: java.io.FileNotFoundException: http://localhost:8090/notifications/v2?cluster=apollo&dataCenter=apollo&appId=ssmt&ip=172.16.8.7&notifications=%5B%7B%22namespaceName%22%3A%22apollo%22%2C%22notificationId%22%3A-1%7D%5D [Cause: http://localhost:8090/notifications/v2?cluster=apollo&dataCenter=apollo&appId=ssmt&ip=172.16.8.7&notifications=%5B%7B%22namespaceName%22%3A%22apollo%22%2C%22notificationId%22%3A-1%7D%5D [Cause: http://localhost:8090/notifications/v2?cluster=apollo&dataCenter=apollo&appId=ssmt&ip=172.16.8.7&notifications=%5B%7B%22namespaceName%22%3A%22apollo%22%2C%22notificationId%22%3A-1%7D%5D]]
[apollo-demo][main]2018-08-14 18:31:29,448 WARN  [com.ctrip.framework.apollo.internals.LocalFileConfigRepository] Sync config from upstream repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository failed, reason: Load Apollo Config failed - appId: ssmt, cluster: apollo, namespace: apollo, url: http://localhost:8090/configs/ssmt/apollo/apollo?dataCenter=apollo&ip=172.16.8.7 [Cause: [status code: 404] Could not find config for namespace - appId: ssmt, cluster: apollo, namespace: apollo, please check whether the configs are released in Apollo!]`

**Comment by nobodyiam** [comment]
检查以下几点：

1. http://localhost:8080 查看eureka信息
2. http://localhost:8080/services/config 查看config service信息

**Comment by java-longmiao** [comment]
这个homeUrl拿的是adminservice的地址而不是configservice的地址
![default](https://user-images.githubusercontent.com/31102821/44095966-b50361f4-a00c-11e8-8b33-e03a6046b741.png)
eureka信息是正常的
![default](https://user-images.githubusercontent.com/31102821/44096136-2354c684-a00d-11e8-99e3-837033de5590.png)

**Comment by nobodyiam** [comment]
我估计你是改了apollo-configservice的eureka.instance.homePageUrl，所以你在eureka页面上点击 apollo-configservice后面的那个链接也会调到http://localhost:8090的页面。

**Comment by xy83918** [comment]
我这边从eureka取出来的信息也不对，咋破

**Comment by xy83918** [comment]
我在本机docker启动的，现在eureka拿到的ip地址不对，有什么办法吗？

**Comment by xy83918** [comment]
https://github.com/spring-cloud/spring-cloud-netflix/issues/432 how to fix this issue on our side

**Comment by nobodyiam** [comment]
@xy83918 look like your issue was solved, see #1348

**Comment by xy83918** [comment]
i just useing docker_quick_start nothing more config ,eureka get the ip is internal docker server ip out side server can not access , if change it to localhost:port it can be access , normally it auto by eureka get ip address

**Comment by xy83918** [comment]
i just clone it and use script/docker-quick-start docker-compose up and it can not work

**Comment by xy83918** [comment]
i just using testcase for test our project, use localhost:8080/xxx/xxx that can get correct json string but console log it can not connect server and url default url just using eureka instance get ip docker default ip is 172.20.0.2 port is internal 8080 it can not get  docker yml config mapping that canot be access
