### ISSUE TITLE
Apollo配置中心页面搜索Chrome浏览器不跳转

### ISSUE THREAD

**Issue by maoplus** [ctripcorp/apollo#1370]
在配置中心页面搜索某个字段，微软Edge、IE浏览器可以跳转到关键字的位置，Chrome浏览器不行。
Apollo版本：Apollo V0.6.3 Release，经测试最新release也不跳转。Chrome版本：Version 68.0.3440.106 (Official Build) (64-bit)，其他Chrome版本也同样的问题。

**Comment by slankka** [comment]
最新版本 1.1.1-SNAPSHOT 也是。谷歌浏览器，火狐浏览器，都不能Ctrl+F 跟随，当配置项很多很多的时候，需要手动滚动一点点找，正常情况下是搜索框回车浏览器自动滚动到目标位置。

**Comment by codepiano** [comment]
我们也遇到了这个问题，查了一下是因为用了 [jquery.nicescroll](https://github.com/inuyaksa/jquery.nicescroll) 导致 html 标签被加了 `overflow:hidden` 样式。

搜索了一下似乎各个浏览器现在更改了行为，在`ctrl + f` 时不再滚动到 `overflow:hidden` 的元素里面，由于`ctrl + f` 不会触发浏览器事件，也就是说可能大部分禁止原生滚动条，自定义滚动条的插件都有这个问题。

我不是前端开发，通过我搜到的资料来看，似乎这个问题只能强制修改使用了 nicescroll 滚动标签的元素，把 `overflow:hidden` 去掉，但是这样可能破坏 nicescroll 的行为，比如功能失效或者出现两个滚动条。还有一种办法就是把 nicescroll 去掉，我看 apollo 使用这个组件似乎也没有特别的目的。

**Comment by slankka** [comment]
我将NiceScroll换成最新3.7.6 版本，问题依旧。 https://github.com/inuyaksa/jquery.nicescroll/issues/766
正在尝试解决办法。

**Comment by codepiano** [comment]
> 我将NiceScroll换成最新3.7.6 版本，问题依旧。 [inuyaksa/jquery.nicescroll#766](https://github.com/inuyaksa/jquery.nicescroll/issues/766)
> 正在尝试解决办法。

不管用，nicescroll 官网都有这问题，浏览器改了默认行为以后这问题应该在 nicescroll 层面无解。你要想设置，可以强行把 html 标签上的 `overflow:hidden` 删掉，就能翻页了。但是这样会出现两个滚动条，你还要修改样式，隐藏原生的滚动条。但是这样的话可能会干扰 nicescroll 的行为，再用 nicescroll 就没有多少意义了。

想让 `ctrl + f` 翻页生效很简单，不超过几行代码，但是整个问题很棘手。

**Comment by nobodyiam** [comment]
多谢几位的反馈，这个问题我们再跟进一下

**Comment by codepiano** [comment]
我们在 portal 里面完全去掉了 nicescroll 这个组件，目前没发现什么使用上的问题，不过不知道会不会影响触屏使用。
有需要我可以提一个 pr

**Comment by nobodyiam** [comment]
@codepiano 

劳烦提个PR吧，这个问题还挺影响使用的，多谢！

**Comment by nobodyiam** [comment]
[1.2.0](https://github.com/ctripcorp/apollo/releases/tag/v1.2.0)版本已经发布，去除了nicescroll组件
