### ISSUE TITLE
从别的环境导入apolloconfigdb的项目数据

### ISSUE THREAD

**Issue by rhaonan** [ctripcorp/apollo#1373]
配置中心配置了PRO和DEV两个环境，但是最近DEV环境的configDB机器故障数据丢失了，恢复后数据丢失了，所以我按照官方文档从RPO环境导入了APP，AppNamespace，Cluster，Namespace这四个表。

但是从protal后台看并不起作用，DEV环境仍有问题，adminservice的日志错误提示是app not found for appId XXX，但是新建的项目DEV环境就正常了？

我看源码这个adminservice的接口/apps/{appid}也没加缓存什么的，直接同步库为什么不起作用？

**Comment by rhaonan** [comment]
新创建项目是正常的，protal后台dev和pro环境都有，但是我通过库导入四个表过去的数据protal后台dev环境报错，就是adminservice那个接口找不到appid

**Comment by nobodyiam** [comment]
admin service没有缓存的，不过spring jpa的entity层可能有session缓存。

你确定报 app not found for appId XXX 的appId，在ConfigDB.App表里面有数据，且isDeleted=0？

**Comment by rhaonan** [comment]
找到问题了，ConfigDB.App表里面有数据，但是isDeleted=1，我不知道为什么会csv导入数据，会把0导入成1
