### ISSUE TITLE
本地通过源码构建成功，如果上云，直接把自己打的.zip文件放上去吗？

### ISSUE THREAD

**Issue by BillBearXiong** [ctripcorp/apollo#1375]
大神，你好  我自己根据文档打了config admin portal的压缩包，我是解压之后，用cmd  java -jar XXX.jar 是run起来的，并且client端也实现了刷新功能，如果我要部署到PCF上去，是不是要直接把定制好的.zip这个文件放云上，解压，跑起来？    然后config和admin是怎么联系起来的？是通过eureka吗？

**Comment by nobodyiam** [comment]
上云应该就是按照分布式部署文档即可，config和admin是通过eureka联系起来的。

你直接java -jar xxx.jar应该有问题吧，因为这个是前台运行的，建议执行startup.sh，那个是后台service方式运行的。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
