### ISSUE TITLE
对springboot启动注入支持

### ISSUE THREAD

**Issue by BazingaLyn** [ctripcorp/apollo#1377]
看源码是使用ApolloApplicationContextInitializer 来实现的，是不是使用EnvironmentPostProcessor 去做这个动作更好一点啊

**Comment by nobodyiam** [comment]
恩，貌似`EnvironmentPostProcessor`的阶段更靠前一些，倒是可以尝试一下。

你是有遇到啥具体的问题吗？

**Comment by nobodyiam** [comment]
[1.2.0](https://github.com/ctripcorp/apollo/releases/tag/v1.2.0)版本已经发布，支持了通过EnvironmentPostProcessor注入配置
