### ISSUE TITLE
maven中央仓库中的client如何使用自定义的env环境

### ISSUE THREAD

**Issue by pandalin** [ctripcorp/apollo#1384]
portal、config、admin在v.0.11.0的版本基础上自定义了env环境，现在想升级到v1.0.0（不想升级portal、config、admin），只想升级client，有没有办法使用中央仓库的1.0.0版本，又能使用自定义的env环境
还是说只有按照原来的方式，自己打jar到自己的私有nexus仓库

**Comment by nobodyiam** [comment]
client如果使用传`apollo.meta`的方式，其实是可以不需要自定义环境的，因为对apollo-client而言，env只是用来定位meta server用的。

**Comment by pandalin** [comment]
看了下1.0.0的实现，因为不想每个client都去指定apollo.meta，运维还得根据不同环境配置不同的地址。发现做个jar加入apollo-env.properties，指定不同环境地址，实现自己的MetaServerProvider也能满足需求，即可。非常感谢！
