### ISSUE TITLE
宋大神，能请教一个很简单的问题吗？

### ISSUE THREAD

**Issue by BillBearXiong** [ctripcorp/apollo#1385]
portal和admin是怎么产生联系的呀？

**Comment by nobodyiam** [comment]
portal从meta server获取到admin service的服务列表，然后通过ip直连的方式访问服务，具体可以看下 [Apollo配置中心设计](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
