### ISSUE TITLE
关于application从未发布会阻止客户端从配置中心获取配置的缺陷

### ISSUE THREAD

**Issue by yezl77** [ctripcorp/apollo#1387]
大大，你好
关于 “此namespace从来没有发布过，Apollo客户端将获取不到配置并记录404日志信息，请及时发布。”
这个设置是否合理，举例子，我一般都不会使用默认的application,而是自己创建，而且我得客户端也只监听自己创建的namespace，那么我不应该还要去首次发布不相关的application,（只是随便填了点东西）
这是我对这个设置不太理解的地方，能否去掉这个限制。

**Comment by nobodyiam** [comment]
这个并不是限制，只是一个提示，并不是说application namespace没发布过会导致客户端获取不到其它namspace的配置，而是说因为application namespace没有发布过，所以客户端如果要获取`application` namespace的话，是获取不到的。

所以，对你这种情况使用是没有任何影响的，界面的提示文字可能需要优化一下。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
