### ISSUE TITLE
关于refreshInterval设置的问题

### ISSUE THREAD

**Issue by ssgdla** [ctripcorp/apollo#1389]
您好！
默认的拉取配置频率是5分钟，请问具体在哪里设置呢？谢谢！

**Comment by nobodyiam** [comment]
可以通过`-Dapollo.refreshInterval=1`这样来设置，可以参考代码[ConfigUtil](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/util/ConfigUtil.java#L144)，不过一般没有必要改这个配置，因为apollo是有实时推送机制的。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
