### ISSUE TITLE
配置中心打开项目配置时报错如下  

### ISSUE THREAD

**Issue by xiewsh** [ctripcorp/apollo#1390]
Could not initialize class com.ctrip.framework.apollo.core.MetaDomainConsts] with root cause

我重新打了一个apollo-portal包 竟然报这个错 我打包没有报错，而且启动apollo-portal 也没有报错，就是浏览器访问项目配置时出现错误

**Comment by nobodyiam** [comment]
看下具体的堆栈吧

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
