### ISSUE TITLE
1.1.0 版本报 Code:404 Msg:namesapces not exist  异常

### ISSUE THREAD

**Issue by oooooooz** [ctripcorp/apollo#1391]
进去公益环境 http://140.143.100.23:8070/  选择 test0727 这个项目，打开配置页面，报 ”加载配置出错， Code:404 Msg:namesapces not exist ” 异常，我看有人已经反馈过，这个 bug 应该还没修复。我今天升级到了 1.1.0-SNAPSHOT，同样也有这个异常

@nobodyiam  ， 需要堆栈的话我晚点上班补上来，不过到到公益环境选那个项目应该也能看到了

**Comment by nobodyiam** [comment]
公益环境那个看到了，是有人把 test0727 的 application namespace删掉了，后续可能要加一个判断，不允许删除application namespace

**Comment by oooooooz** [comment]
明白。请教另一个问题：如果继承了公共的命名空间，应用是 spring boot 的话必须在 application.properties 里面类似这样加入 

> apollo.bootstrap.namespaces = application,FX.apollo 

显示地注入非默认的 application 命名空间应用才能获取吗？我发现如果不这样做就获取不到**非 application** 的配置，但我这个配置又不是 spring boot 启动阶段必须使用的，这个不太理解。我想可能是我的使用方式不对 ？望解答，感谢 ！

下面是我的应用配置，继承了一个公共命名空间，如果不在 application.properties 显示注入 CPS_DEPT1.test-demo-biz-ns 这个命名空间，应用就拿不到配置：

![image](https://user-images.githubusercontent.com/3099411/44503552-854f3c80-a6c9-11e8-81d2-253fc4c6be3e.png)

@nobodyiam

**Comment by nobodyiam** [comment]
在apollo里面，关联不是为了让应用对该公共namespace有可见性，而是为了去覆盖公共namespace中的配置。

对于大部分的应用而言，是不需要关联公共namespace的，举个例子，你如果维护了公司的一个公共RPC组件，然后你在apollo上创建了一个公共namespace保存rpc公共组件的配置，这种情况下，是不需要所有使用到你这个公共RPC组件的人去关联了公共namespace后才能使用rpc公共组件的，只要公共rpc组件中声明需要使用到这个公共namespace即可。

就实际的场景而言，一般也不会说新加了一个namespace后不需要改代码就使用的，所以目前apollo的设计是需要在客户端显式声明需要加载的namespace。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by oooooooz** [comment]
公司有部门使用碰到另外个问题，请教一下。场景是这样的，用 spring boot 拉起一个 spring 容器，然后在 bean 中再拉起另外一个 spring 容器，结果第二个容器取不到 apollo 的配置。起两个容器这个做法虽然不妥，但理论第二个容器应该能正常拿到才对，不知为何？麻烦宋大神回复一下，感谢感谢 @nobodyiam

具体代码差不多是这样：

>     public static void main(String[] args) {
> //        ConfigurableApplicationContext context ;
>         SpringApplication.run(DubboServiceBootApp.class);
> 
>      // 这个容器取不到 apollo 的配置
>         FileSystemXmlApplicationContext context = new FileSystemXmlApplicationContext("classpath:spring-apollo.xml");
>         Map<String,String> map = (Map<String, String>) context.getBean("context-attrs");
>         System.out.println(map.get("dubbo.registry.address")+","+map.get("mpi.encryptCert.path"));
>     } 

spring-apollo.xml 的内容如下：

>     <apollo:config order="2" namespaces="application"/>
> 
>     <bean class="org.springframework.context.support.PropertySourcesPlaceholderConfigurer">
>     <property name="properties">
>         <props>
>             <prop key="apollo.bootstrap.enabled">true</prop>
>         </props>
>     </property>
>     </bean>
> 
>  
>     <bean id="context-attrs" class="java.util.HashMap">
>         <constructor-arg>
>             <map>
>                 <entry key="dubbo.registry.address" value="${timeout}"/>
>                 <entry key="mpi.encryptCert.path" value="${url}" />
>             </map>
>         </constructor-arg>
>     </bean>


第二个容器启动报无法解析占位符 ${timeout}：

Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'timeout' in string value "${timeout}"

**Comment by nobodyiam** [comment]
两个容器似乎是有些问题的，能否上传一个可运行的demo？我们看一下是否可以支持一下

**Comment by oooooooz** [comment]
感谢啊，我迟点整个 demo 上来给你看看

**Comment by oooooooz** [comment]
@nobodyiam  1.1.0-SNAPSHOT 目前这个版本适合在生产上使用吗？我们在开发测试环境用了一段时间，暂无发现什么问题

**Comment by nobodyiam** [comment]
@oooooooz 

多容器启动，第二个容器拿不到配置的问题，跑了你的demo以后我已经知道原因了，是之前一段保护性代码导致的，因为没有遇到过多容器的场景，所以当异常处理了。后续我看一下怎么兼容一下，多谢！

**Comment by oooooooz** [comment]
好的，那段保护性代码可以发上来看看是哪段吗？我之前猜测是因为 BeanRegistrationUtil.registerBeanDefinitionIfNotExists 仅注册单例的原因。多谢多谢 @nobodyiam

**Comment by oooooooz** [comment]
父子容器这种场景也建议考虑兼容一下

**Comment by nobodyiam** [comment]
@oooooooz 

提交了PR #1436，可以看一下，本地测试之前提交的`dubbo-demo-service3`代码示例，已经OK了。

**Comment by oooooooz** [comment]
好的
