### ISSUE TITLE
日志一直输出Load config failed，Sync config failed

### ISSUE THREAD

**Issue by reignsr** [ctripcorp/apollo#1392]
日志中一直在持续输出Load config failed，Sync config failed，will retry In 1 SECONDS………………，但是不影响使用，配置的获取、更新、加载都正常，只是日志不停地输出上述内容，占用空间增长很快。
1、该日志内容是何缘故？为何会提示失败？
2、如果上述内容无关紧要，该日志是否可以关闭？
<img width="1047" alt="_428de31e-5b5b-4316-9a73-5450fef6ba84 1" src="https://user-images.githubusercontent.com/814702/44441389-d9411f00-a5fe-11e8-956f-466438e65edd.png">
<img width="861" alt="_af51a901-4dfd-413a-9cb1-93a6e2e8065e" src="https://user-images.githubusercontent.com/814702/44441395-e100c380-a5fe-11e8-809f-6a866b314c36.png">

**Comment by nobodyiam** [comment]
这个是load config失败了，正常不应该失败的，你打开这个URL看看。

**Comment by reignsr** [comment]
暂时定位到，代码里多指定了一个不存在的命名空间。估计是这个问题，还未验证。

**Comment by nobodyiam** [comment]
@Brian-West

看上去是meta server配错了，meta server url应该配置config service的地址，不是portal的地址

**Comment by DeanJi** [comment]
这个问题我也遇到了，客户端是jdk1.8没问题，jdk1.6就有这个问题。楼主的客户端jdk是什么版本？我跟了一下代码，是HttpUtil.java的这行代码response = CharStreams.toString(isr）报超时错误。楼主可以调试一下，看是不是也是这行报错？

**Comment by DeanJi** [comment]
@nobodyiam，有个疑问，为什么长连接的HttpRequest有手动设置readTimeout为90秒，而5分钟一次的定时拉取没有手动设置readTimeout，而在HttpUtil被系统设置成5秒？从而引起read timed out异常。

**Comment by nobodyiam** [comment]
@DeanJi 

5秒的readTimeout是Apollo的默认值，不是系统设置的，另外这个timeout也是可以自定义的，详见 [ConfigUtil](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/util/ConfigUtil.java)

**Comment by nobodyiam** [comment]
长连接的特点是长，所以是90秒，因为目前服务端默认是60秒才返回。

5分钟一次的连接是短连接，一般API请求5秒也肯定够了，我们生产环境平均响应时间是1毫秒以内。如果5秒都不够的话，那说明服务端存在性能问题，需要看一下内存、GC、CPU等情况。

**Comment by DeanJi** [comment]
你们服务端几个cpu，内存多少方便透露一下吗

**Comment by nobodyiam** [comment]
参考一下 [Apollo性能测试](https://github.com/ctripcorp/apollo/wiki/Apollo%E6%80%A7%E8%83%BD%E6%B5%8B%E8%AF%95)

**Comment by Brian-West** [comment]
@nobodyiam 果然是

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by fanlingyin** [comment]
还在吗 想问一下注册中心改成自己的eureka，metaserver 还是configservice的地址吗  我也一直报这个错

**Comment by nobodyiam** [comment]
@fanlingyin 

meta server还是config service的地址

**Comment by vhye** [comment]
我也遇到过这种情况，只有定时轮询报readtimeout，后来发现是weblogic默认的httphandler覆盖了sun的，改了源码指定handler就没问题了

**Comment by jiayaoO3O** [comment]
> 我也遇到过这种情况，只有定时轮询报readtimeout，后来发现是weblogic默认的httphandler覆盖了sun的，改了源码指定handler就没问题了
@vhye 可以详细说说吗?我也是weblogic定时轮询报错, 但是功能完全正常, 只是会报这个警告, 不知道为什么, 发现你说weblogic默认的httphandler覆盖了sun的, 那要怎么修改呢?

**Comment by dzjfromChina** [comment]
我也遇到了这个问题,如果命名空间没有值,并且在项目中引用了就会出现这个

**Comment by Yawngan0912** [comment]
这里并没有这个application的命名空间，但是一直告警Load config failed, will retry in 1 SECONDS. appId: document-test, cluster: default, namespaces: application

**Comment by Anilople** [comment]
> 这里并没有这个application的命名空间，但是一直告警Load config failed, will retry in 1 SECONDS. appId: document-test, cluster: default, namespaces: application

可以试试到`document-test`这个项目里，发布一下`application`这个namespace？（不需要添加任何配置，直接点发布即可）

**Comment by SayGoodbyeWithSmile** [comment]
我的经历是：不要留有空的Namespace，将空的Namespace填上值就可以了
