### ISSUE TITLE
apollo 用@EnableApolloConfig配置    原有value注解值不生效

### ISSUE THREAD

**Issue by gongsiran** [ctripcorp/apollo#1393]
apollo加载配置时，开启了@EnableApolloConfig注解，有部分配置放至apollo，部分配置依旧放至项目resources下的自定义文件中，通过  PropertyPlaceholderConfigurer  方式 加载  在使用@value获取本地配置时，获取不到，去掉@EnableApolloConfig即可获取到本地配置。
项目环境：spring boot
是不是apollo复写了@value的原有功能？求解答！！！

**Comment by YPRY** [comment]
PropertyPlaceholderConfigurer  方式加载代码：
@Configuration
@Slf4j
public class PropertiesLoad {

    private static String PROPERTIES_PATH = PathUtil.getConfigPath() + "/parameter.properties";

    private static String APPLICATION_PROPERTIES = PathUtil.getConfigPath() + "/application.properties";
    @Bean
    public static PropertyPlaceholderConfigurer getPropertyPlaceholderConfigurer() throws FileNotFoundException {
        log.info("PropertiesLoad  start ================");
        PropertyPlaceholderConfigurer configurer = new PropertyPlaceholderConfigurer();
        configurer.setLocations(new FileSystemResource(PROPERTIES_PATH));
        log.info("PropertiesLoad  end ================");
        return configurer;
    }
}

**Comment by YPRY** [comment]
麻烦大佬不忙的时候 解答一下 @nobodyiam  @marsqing  @ameizi @yiming187 @qmwu2000

**Comment by nobodyiam** [comment]
看一下这个

https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#32-spring%E6%95%B4%E5%90%88%E6%96%B9%E5%BC%8F

![image](https://user-images.githubusercontent.com/837658/44467731-2ef4e600-a656-11e8-821f-938ba20755ff.png)

**Comment by DeanJi** [comment]
这个问题我也遇到了，使用PropertySourcesPlaceholderConfigurer问题解决。

**Comment by YPRY** [comment]
@DeanJi   我换成了  PropertySourcesPlaceholderConfigurer  不管用呢 。
![image](https://user-images.githubusercontent.com/12728656/44562564-b775a280-a78c-11e8-8671-281d7a084706.png)

**Comment by YPRY** [comment]
@DeanJi  能把你的加载方式发下吗

**Comment by DeanJi** [comment]
![9a2f85e1-6530-4c70-9cc8-99c4c9b1cf93](https://user-images.githubusercontent.com/24695243/44563490-0e7d7680-a791-11e8-8f77-c065dc5c5aee.jpeg)

**Comment by YPRY** [comment]
@DeanJi   谢谢啦  我加了个  order 居然就可以了。

**Comment by YPRY** [comment]
谢谢两位。EnableApolloConfig 注解  默认order 为 Integer.MAX_VALUE  而我的那种引入方式  默认Order 也为 Integer.MAX_VALUE  指定下 order 别重复 就好了。  再次感谢 ！ @DeanJi   @nobodyiam

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by githubshihaibo** [comment]
你好，大佬，我这边也遇到一个问题，我是maven项目，多个module，其中一个module, @Configuration  
 public class JavaBean   {@Value("${***}")},，我项目无法启动。无法获取到@Value里面的值。帮忙看看
