### ISSUE TITLE
pro环境关联公共namespace取值有问题

### ISSUE THREAD

**Issue by randomSpirit** [ctripcorp/apollo#1395]
情景：
有dev和pro两个环境。
在dev下点击新建namespace，选了pro和dev，关联公共namespace。
操作完成后portal和数据库里pro和dev都有新增的关联namespace。

问题：
dev下默认namespace和关联namespace都能正常使用。
pro下默认namespace能正常使用，关联namespace获取404，单独发布一次pro关联namespace后，获取空{}

请问这是什么情况？有出现过么 @nobodyiam

**Comment by randomSpirit** [comment]
![default](https://user-images.githubusercontent.com/7530593/44458480-fbf02980-a638-11e8-9e72-2f37c95ee76a.png)
![default](https://user-images.githubusercontent.com/7530593/44458507-10342680-a639-11e8-99ce-a01b462879f9.png)
![default](https://user-images.githubusercontent.com/7530593/44458549-30fc7c00-a639-11e8-941e-47b7a42d2765.png)

**Comment by nobodyiam** [comment]
看上去是pro环境下的公共namespace没有发布过配置，你加载`http://10.18.40.119:8080/configs/auto-video-service/default/backend.auto-video-service` 看看

**Comment by randomSpirit** [comment]
![default](https://user-images.githubusercontent.com/7530593/44500005-1833ab00-a6b9-11e8-8c08-354520ac2f5d.png)
这个有的

**Comment by randomSpirit** [comment]
![default](https://user-images.githubusercontent.com/7530593/44507625-cd785a00-a6dd-11e8-9c8f-6dd4b00194d8.png)
dev乱填什么appId都有值 @nobodyiam

**Comment by randomSpirit** [comment]
![default](https://user-images.githubusercontent.com/7530593/44508775-277b1e80-a6e2-11e8-81f8-b72eba06a1a3.png)
![default](https://user-images.githubusercontent.com/7530593/44508790-34980d80-a6e2-11e8-92a2-61d96ef5cddd.png)
pro环境只能取到覆盖的，跟没有关联上一样

**Comment by oooooooz** [comment]
@randomSpirit 你们 pro 环境要想取到 公共namespace 的配置，是必须要在应用中显示注入公共namespace 吗（像下面那样）？我原以为如果是关联了 namespace ，不用显示注入也可以像默认那样获取，实际测了下好像不行。

> @EnableApolloConfig(value = "pub_ns1") 

或者在 application.properties 增加配置：

> apollo.bootstrap.enabled = true
> apollo.bootstrap.namespaces = application,pub_ns1

**Comment by randomSpirit** [comment]
@oooooooz 有配置的
`@EnableApolloConfig({"application","backend.auto-video-service"})`
dev能获取，pro获取不了

**Comment by nobodyiam** [comment]
@randomSpirit

你这个感觉上是PRO环境中ApolloConfigDB.AppNamespace中的数据有问题，你看一下这张表里面的 backend.auto-video-service 相关记录是否存在，以及isPublic是否为true

**Comment by randomSpirit** [comment]
![default](https://user-images.githubusercontent.com/7530593/44560344-d7539900-a781-11e8-9e46-8aa0caff0864.png)
@nobodyiam

**Comment by nobodyiam** [comment]
@randomSpirit 

加QQ支持群后续看一下吧

**Comment by randomSpirit** [comment]
@nobodyiam 加了qq和微信的，在群里艾特过，我再发一次？

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
