### ISSUE TITLE
apollo的命名空间可以通过外部化的方式去指定吗？

### ISSUE THREAD

**Issue by wulinjie122** [ctripcorp/apollo#1396]
@EnableApolloConfig("x") 感觉很不方便，比如，我们项目组有5个开发，每个人想建一套自己的配置，所以这5个人的命名空间肯定是不一样的，但是通过注解的方式就相当于把代码写死了，不灵活

**Comment by nobodyiam** [comment]
如果是本地开发的话，通过集群区分不同开发的配置，或者如果只有少量配置不同的话，可以通过-DsomeKey=someValue来覆盖

**Comment by zzzwt** [comment]
我修改源码把需要的namespace放到application.properties里边去了

**Comment by nobodyiam** [comment]
如果用的是apollo.bootstrap.enabled的话，namespace写在application.properties里面，详见 [在Spring Boot初始bootstrap阶段注入配置](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#3213-%E5%9C%A8spring-boot%E5%88%9D%E5%A7%8Bbootstrap%E9%98%B6%E6%AE%B5%E6%B3%A8%E5%85%A5%E9%85%8D%E7%BD%AE)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
