### ISSUE TITLE
com.ctrip.framework.apollo.biz.grayReleaseRule，这个package的命名是否应该为全小写

### ISSUE THREAD

**Issue by ryphnyuan** [ctripcorp/apollo#1400]
一般的java编码规范都会说，package命名要全小写。如

![default](https://user-images.githubusercontent.com/37541919/44561786-002b5c80-a789-11e8-84f3-9b8adc647310.jpg)

**Comment by nobodyiam** [comment]
是的，当时也是纠结了一下，对于gray release rule没法找到一个全小写的package命名，所以就写成grayReleaseRule了，如果有好的idea也可以提个PR

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
