### ISSUE TITLE
本地缓存文件没删除删除

### ISSUE THREAD

**Issue by hsiangbinhua** [ctripcorp/apollo#1401]
第一次加载程序能在本地目录下创建文件
![image](https://user-images.githubusercontent.com/3953400/44572665-223bd380-a7b7-11e8-8a0e-2a9d37fa477c.png)
![image](https://user-images.githubusercontent.com/3953400/44572677-2d8eff00-a7b7-11e8-95dc-a5ff2f496e7c.png)
 当我将application 在控制台删除掉：
![image](https://user-images.githubusercontent.com/3953400/44572721-50b9ae80-a7b7-11e8-88d6-491b3b02d18c.png)
 重新启动客户端：为何这个application文件还在呢？
![image](https://user-images.githubusercontent.com/3953400/44572770-79da3f00-a7b7-11e8-96fd-f40ba095d3bf.png)
   请教大神，，该如何做才能自动删除？ 或客户端热删除（不重启客户端应用）：
  我的客户端配置：
  
![image](https://user-images.githubusercontent.com/3953400/44572950-e8b79800-a7b7-11e8-9bd9-d0350df1862c.png)

**Comment by nobodyiam** [comment]
本地文件不会做删除的，另外，除非这个namespace已经没人用了，一般也是不能删除的

**Comment by hsiangbinhua** [comment]
@nobodyiam  如果本地文件不删除，情况如：1、如果应用有配置默认apollo:config。且新config和默认的config配置了相同key，如k1=v1，是取哪个，谁覆盖谁，以order为准？若都没配置order呢？

**Comment by nobodyiam** [comment]
如果是同一个namespace，则没有新config和默认config的区分，始终是远端的config覆盖本地的config。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
