### ISSUE TITLE
Long polling 一次请求耗时60多S?大多耗时到哪儿去了？

### ISSUE THREAD

**Issue by java-longmiao** [ctripcorp/apollo#1404]
`logger.debug("Long polling from {}", url);
        HttpRequest request = new HttpRequest(url);
        request.setReadTimeout(LONG_POLLING_READ_TIMEOUT);

        transaction.addData("Url", url);

        final HttpResponse<List<ApolloConfigNotification>> response =
            m_httpUtil.doGet(request, m_responseType);

        logger.debug("Long polling response: {}, url: {}", response.getStatusCode(), url);`

**Comment by java-longmiao** [comment]
NotificationControllerV2执行耗时就几毫秒

**Comment by howHzz** [comment]
就是NotificationControllerV2，也是60秒
