### ISSUE TITLE
回滚BUG

### ISSUE THREAD

**Issue by BDataAndy** [ctripcorp/apollo#1407]
修改timeout配置，由100改到200，发布后再回滚，配置回滚到100，但是配置列表上面显示的仍为200

**Comment by DeanJi** [comment]
页面显示200，状态变成修改，未发布。就是你之前修改的值200，你可以根据需要再发布，没什么毛病吧

**Comment by BDataAndy** [comment]
无法直观的识别出配置的当前值

**Comment by nobodyiam** [comment]
配置的当前值，你其实是指当前已发布的值吧？这个是可以看到的，如下图所示：

![image](https://user-images.githubusercontent.com/837658/44720382-38200000-aaf9-11e8-9929-1ca3704814c1.png)

**Comment by BDataAndy** [comment]
感谢Apollo团队提供的支持，希望Apollo越来越好

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by hardyxia2018** [comment]
回滚会偶发出现回滚配置显示不生效的情况， 即 在前端UI 修改某一个key 的值，发布之后 配置变更，然后点击回滚按钮， 再次对回滚的值进行发布，发现客户端实际值已经变更（回滚成功的），但是UI显示依旧是未回滚的值~~ ~   版本V1.2

**Comment by nobodyiam** [comment]
@hardyxia2018 

是否能提供一下重现步骤？目前的demo站点上也是1.2版本的

演示环境（Demo）:
  * 106.12.25.204:8070
  * 账号/密码:apollo/admin

**Comment by hardyxia2018** [comment]
我用的是你的环境，步骤分别如图12345 ，bug复现
[image: 1.jpg]
[image: 2.jpg]
[image: 3.jpg]
[image: 4.jpg]
[image: 5.jpg]

Jason Song <notifications@github.com> 于2019年1月24日周四 下午4:32写道：

**Comment by furaul** [comment]
> 配置的当前值，你其实是指当前已发布的值吧？这个是可以看到的，如下图所示：
> 
> ![image](https://user-images.githubusercontent.com/837658/44720382-38200000-aaf9-11e8-9929-1ca3704814c1.png)

我最近也碰到这个问题。
对于一些新手不太好理解，虽然可以悬浮查看已发布的值。
因为回滚都是比较紧急的状态，难以完全确认发布的值是什么，慌张之下以为回滚没有成功，认为再点击一次发布才是回滚成功，哪知道又是变回错误的值了。
能否加个配置项，决定回滚之后namespace在页面的展示状态，默认值是回滚后namespace保留上次发布的值，同时是未发布状态；修改配置项之后，回滚之后，页面展示的就是回滚之后的值，是已发布状态。

**Comment by nobodyiam** [comment]
@furaul

![image](https://user-images.githubusercontent.com/837658/148311027-391b9fa3-e56c-426f-86c6-8efb8162c98a.png)

目前有两个操作：
1. 回滚：回滚已发布的配置
![image](https://user-images.githubusercontent.com/837658/148311135-adfa6449-5f9a-4952-85b1-8d847d1ac51a.png)

2. 撤销：撤销未发布的修改
![image](https://user-images.githubusercontent.com/837658/148311202-67b255d1-8cb4-4147-968c-c3059e1f3dca.png)

你所提议的是增加第三种操作（通过选项），来实现回滚+撤销一起做的效果？
目前的提示应该已经比较清晰了，建议给新人讲解下？不太建议再增加第三种操作，会使理解复杂度大大升高。

**Comment by suangya** [comment]
> @furaul
> 
> ![image](https://user-images.githubusercontent.com/837658/148311027-391b9fa3-e56c-426f-86c6-8efb8162c98a.png)
> 
> 目前有两个操作：
> 
> 1. 回滚：回滚已发布的配置
>    ![image](https://user-images.githubusercontent.com/837658/148311135-adfa6449-5f9a-4952-85b1-8d847d1ac51a.png)
> 2. 撤销：撤销未发布的修改
>    ![image](https://user-images.githubusercontent.com/837658/148311202-67b255d1-8cb4-4147-968c-c3059e1f3dca.png)
> 
> 你所提议的是增加第三种操作（通过选项），来实现回滚+撤销一起做的效果？ 目前的提示应该已经比较清晰了，建议给新人讲解下？不太建议再增加第三种操作，会使理解复杂度大大升高。

您好，xml文件是不是没有撤销配置的功能？这个功能只有properties文件才有吗？

**Comment by nobodyiam** [comment]
@suangya properties 配置项比较多，所以提供了撤销配置的能力。xml 文件可以直接从更改历史中找到配置并恢复。
