### ISSUE TITLE
发布和回滚支持选择配置项吗

### ISSUE THREAD

**Issue by DeanJi** [ctripcorp/apollo#1408]
同步配置的时候可以根据需要选择想要同步的配置项，发布和回滚目前好像是默认全部修改项的发布和回滚，能支持根据需要选择要发布和回滚的配置项吗？

**Comment by nobodyiam** [comment]
这个会增加很多使用上的困扰和交互的复杂性，不建议这么做。

**Comment by DeanJi** [comment]
能不能举个例子，有什么使用困扰和交互复杂性？

**Comment by nobodyiam** [comment]
功能总能实现，不过功能也不是越多越好。

在出故障的时候，一般会希望尽量减少思考，所以更倾向于一键回滚。

在普通发布时，用户如果觉得某个配置项不应该被发布，那也可以手工把该配置回退掉。

在发布和回滚时，如果加上了可选配置项，确实对部分场景有用，不过会使得发布和回滚这两个原本非常简单的操作，变得复杂，需要用户思考。

**Comment by DeanJi** [comment]
嗯嗯，谢谢宋大哥这么详细的解答

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
