### ISSUE TITLE
portal启动的时候为什么会去读ApolloConfigDB的ServerConfig表的配置呢？

### ISSUE THREAD

**Issue by angusguo** [ctripcorp/apollo#1409]
编译的时候修改了build.sh，只保留了dev环境。部署在k8s同一个namespace，发现portal只在启动的时候访问了一次数据库提示连接超时，在对应的pod容器中访问mysql没有问题，随后一直报各种环境meta找不到，也没有尝试重连数据库。
![image](https://user-images.githubusercontent.com/21055794/44699533-3f261e80-aab7-11e8-96b7-0179d9e755b4.png)

**Comment by angusguo** [comment]
这个问题应该不是连不上库的问题，发现下边有从库里边拿到eureka链接：
![image](https://user-images.githubusercontent.com/21055794/44702019-e01ad680-aac3-11e8-90a3-69bcadd670fd.png)
但是有个问题：为什么portal总是尝试链接配置文件和环境变量中不存在的meta server？
![image](https://user-images.githubusercontent.com/21055794/44702125-66cfb380-aac4-11e8-821b-33881db5f4e5.png)

**Comment by angusguo** [comment]
@nobodyiam 麻烦大佬帮忙看下什么问题，portal一直在报错连不上meta server

**Comment by angusguo** [comment]
![image](https://user-images.githubusercontent.com/21055794/44707741-f894ec00-aad7-11e8-99a9-99de97d05cb5.png)
发现找不到classpath中的配置文件才去找那些meta server的，求问怎么解决？

**Comment by nobodyiam** [comment]
portal在设计上就是会访问meta server来获取admin service的服务列表的，你这个报错应该是fat环境的meta server地址没有正确配置。

另外，看截图你的portal数据库中的server config数据貌似错了，ApolloPortalDB的ServerConfig中不应该有eureka.service.url配置的，这个是ApolloConfigDB中的配置项，所以你得看一下到底是数据库连错了还是数据搞错了。

**Comment by angusguo** [comment]
@nobodyiam 是的大佬，但是我容器环境变量和配置文件没有配置UAT、FAT等等这些环境，只配置了dev；另外portal config admin我连得都是同一个db实例，就是不清楚为什么会去读ApolloConfigDB的ServerConfig表的数据，日志中也没有其他信息，我确定sql没有导错，您能提供下可能的排查方向吗？

**Comment by angusguo** [comment]
@nobodyiam 看样子是可以连到库的，上边的截图我看也是有去读configDB的，portaldb和configdb我都是放在一个mysql实例中的；
是的正常情况portal 应该读取portaldb的，我不明白为什么会去读configdb，难道是我用root授权的原因，可是我之前有个正常的环境mysql也是用root访问的？
此外我检查了下：
![image](https://user-images.githubusercontent.com/21055794/44761774-02216100-ab77-11e8-8fa8-29d9565ce206.png)

**Comment by nobodyiam** [comment]
是不是portal的数据库连接串填了ApolloConfigDB的？

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
