### ISSUE TITLE
portal配置meta地址，updateMetaServerAddresses逻辑有点问题导致出现警告日志

### ISSUE THREAD

**Issue by ccnext** [ctripcorp/apollo#1413]
![image](https://user-images.githubusercontent.com/11516263/44721237-d319d980-aafb-11e8-802b-e67fe32262dc.png)
portal内置的定时检查meta服务地址会报上述警告信息
看源码发现如下：
![image](https://user-images.githubusercontent.com/11516263/44721295-0492a500-aafc-11e8-84b2-b0796fdd8ca8.png)
红框会通过发起对meta地址的健康检查，但是meta服务地址例如:http://10.1.1.1:8800,直接访问时http状态码是404
则该meta地址会被认为已经下线
![image](https://user-images.githubusercontent.com/11516263/44721402-5f2c0100-aafc-11e8-804e-8aa911fbf2f2.png)

不知道是我meta配置的不正确还是代码逻辑本身有点问题
目前临时修改健康检查的代码为
![image](https://user-images.githubusercontent.com/11516263/44721454-897dbe80-aafc-11e8-8c85-3f4716a3dfda.png)

**Comment by nobodyiam** [comment]
meta服务地址的根路径应该是通的，不应该是404的，比如：http://140.143.100.23:8080/

需要注意的是meta server目前是和config service部署在一起的，所以meta server地址应该是指向config service的地址

**Comment by ccnext** [comment]
谢谢回复
我试了你给的例子地址，例子是把eureka跟config service、meta service部署在一起的。
但是我这边的情况不太一样，我们有自己的eureka，所以我的meta server和config service只是一个普通服务，他们的入口地址 http://xxx.xx.xx.xx:xx/ 默认是404的。

**Comment by nobodyiam** [comment]
好的，看来是一个兼容问题，我们修一下，访问 http://xxx.xx.xx.xx:xx/health 应该是可以的吧
