### ISSUE TITLE
portal 配置双机通过域名访问无法登陆

### ISSUE THREAD

**Issue by ccnext** [ctripcorp/apollo#1414]
portal服务配置了两台,通过域名进行反代和lb，域名配置好之后，用默认管理员账户无法登入系统
输入用户名密码，提交后仍返回登录页
通过IP:PORT访问单机可以正常登录
profile：github,auth

**Comment by nobodyiam** [comment]
默认的auth使用的是spring security的简单实现，应该没有支持集群登录，看看nginx是否可以配置session sticky，或者可以帮忙看看spring security是否可以配置为支持集群登录啥的

**Comment by DeanJi** [comment]
我们公司使用F5是支持session共享的，如果你使用的lb不支持session共享，可使用springsession+redis实现，网上有很多例子。

**Comment by ccnext** [comment]
好的。那我们自己解决下。谢谢
