### ISSUE TITLE
LDAP Release

### ISSUE THREAD

**Issue by qinyuxiaoxiao** [ctripcorp/apollo#1418]
Hi Le, 

When will 1.1.0 version be released please? I noticed in the master branch, the LDAP authentication configuration has been improved much and will be much simple and easier. I'm looking forward to 1.1.0 release. Apollo is a great project, as I agreed with you when I was still in CTrip. :)

**Comment by nobodyiam** [comment]
Thanks for your kind support!

1.1.0 release may take while since we still want to incorporate several important features. 

However, I think you could install apollo 1.0.0 and upgrade apollo-portal alone to 1.1.0-SNAPSHOT, as there is no change to apollo-configservice and apollo-adminservice yet.

**Comment by qinyuxiaoxiao** [comment]
Thanks a lot for your suggestion! I will try it.

**Comment by nobodyiam** [comment]
apollo 1.1.0 is released now, you may refer the [release note](https://github.com/ctripcorp/apollo/releases/tag/v1.1.0) for more information. Thanks for your support!

**Comment by qinyuxiaoxiao** [comment]
Thank you very much!

On 6 Oct 2018, at 22:38, Jason Song <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1418<https://github.com/ctripcorp/apollo/issues/1418>.
