### ISSUE TITLE
服务器端数据存储mysql一点小提问

### ISSUE THREAD

**Issue by zhaoxp1** [ctripcorp/apollo#1419]
对源码还不是太深入，简单看了下，有点小疑问：用过一些配置中心，大多数服务端机器上都会以hash或b+树建立索引存放数据，mysql上数据有变化时事件通知各个服务器进行存储，client的长连接请求访问服务器文件而不是mysql。

关于这点，有过考量吗

**Comment by nobodyiam** [comment]
你说的这个也是一个不错的方案。

对Apollo而言，我们设计时考虑到大部分公司都有比较成熟的mysql运维和高可用方案，所以就没有选择使用本地文件。Apollo客户端会在本地缓存配置文件，Apollo的服务端也可以[打开开关](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#3config-servicecacheenabled---%E6%98%AF%E5%90%A6%E5%BC%80%E5%90%AF%E9%85%8D%E7%BD%AE%E7%BC%93%E5%AD%98)将配置缓存在内存中。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
