### ISSUE TITLE
env.meta支持多个host配置（逗号分割）问题

### ISSUE THREAD

**Issue by ruanxingshi** [ctripcorp/apollo#1421]
现在apollo-configservice是在：http://x.x.x.1:8602/,http://x.x.x.2:8602/部了两个服务做负载，可是我浏览器访问：http://x.x.x.1:8602/会报404错误，导致server.properties文件里的apollo.meta配了多个地址的时候，调NetUtil里的pingUrl方法的时候返回的是false.所以做不到slb.

这里想问下，为什么我部的apollo-configservice在浏览器里输入http://x.x.x.1:8602/会报404,而我apollo-adminservice部在8601端号上，在在浏览器里输入http://x.x.x.1:8601/得得到”apollo-adminservice“，

这两个服务的启动脚本我也用的是编译出来的。

**Comment by nobodyiam** [comment]
config service是没启用eureka? 看看是不是和 #1413 一样？

**Comment by ruanxingshi** [comment]
我和1413的情况差不多，也是配置在自己的eureka上的，不过为什么apollo-adminservice正常，而apollo-configservice不行呢

**Comment by nobodyiam** [comment]
1.1.0版本已经发布，包含了该问题修复，更多信息可以参考： https://github.com/ctripcorp/apollo/releases/tag/v1.1.0
