### ISSUE TITLE
直接使用安装包部署，如何修改bootstrap.yml

### ISSUE THREAD

**Issue by luckyqiao** [ctripcorp/apollo#1425]
你好！在[分布式部署指南](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97)中有这么一段话：

> 最后一种方式是直接指定要注册的IP+PORT，可以通过JVM System Property在运行时传入，如-Deureka.instance.homePageUrl=http://${指定的IP}:${指定的Port}，或者也可以修改apollo-adminservice或apollo-configservice 的bootstrap.yml文件

请问如果直接使用release中打包好的安装包，要如何修改bootstrap.yml文件使其生效呢？

**Comment by nobodyiam** [comment]
通过-D传入即可，可以修改startup.sh中的JAVA_OPTS
