### ISSUE TITLE
传统java应用（非springboot）接入apollo

### ISSUE THREAD

**Issue by DeanJi** [ctripcorp/apollo#1426]
各位大神，请教一个问题：
传统应用：APP1，使用spring3.1.1
APP1引用了一个jar包，比如mq.jar，mq.jar需要读classpath下的一个配置文件xx.properties。未接入apollo之前只要在classpath下存在xx.properties，mq.jar就能正常运行。
现在想把xx.properties里的配置放到apollo，对apollo客户端做了一些小改动，让apollo在classpath生成xx.properties，并且先于mq.jar调用xx.properties。

问题：如何保证apollo生成xx.properties的时机先于mq.jar调用xx.properties的时机？

备注：
1、mq.jar没有接入apollo
2、不要求配置热更新，只要配置发布后重启应用AAP1能取到最新配置即可

**Comment by oooooooz** [comment]
我觉得你们这个场景就没必要用 apollo 了，你们的问题是如何方便地把配置写到配置文件。apollo 不是这么用

**Comment by nobodyiam** [comment]
做也是可以的，比如使用api方式获取到apollo的配置，然后写到classpath中。

至于如何保证时机，这个也比较简单，spring启动过程中有好几个hook点的，比如postProcessBeanFactory之类的，可以查阅相关文档看看。

**Comment by DeanJi** [comment]
我说的这个mq.jar是一个纯java的jar包，里面没有使用spring，所以postProcessBeanFactory应该无法控制，在mq.jar包里有一个static代码块会去加载xx.properties。问题是apollo拉取配置的时机如何才能早于这个static块？

**Comment by nobodyiam** [comment]
如果没有使用spring，那岂不是更简单了。。。

你只要保证加载mq的类之前之前运行就可以了。

**Comment by DeanJi** [comment]
这些jar包都是放在公司私服的，一般我们拿来即用，不会对jar包内容进行修改的。

**Comment by nobodyiam** [comment]
不是让你改mq.jar，是让你在使用mq功能前加载apollo。

**Comment by DeanJi** [comment]
嗯，这就回到我最初的问题了，mq.jar里有一个static代码块，应用启动时就会自动加载xx.properties，怎么做才能让加载apollo先于mq.jar里的static块？
