### ISSUE TITLE
ReleaseMessageServiceWithCache 内存不释放问题和重复处理配置问题

### ISSUE THREAD

**Issue by zyong2004** [ctripcorp/apollo#1428]
private ConcurrentMap<String, ReleaseMessage> releaseMessageCache;
 这个属性，启动的初始化一次，后面都是更新和设置，配置更新后发布消息，在客户端处理完这个消息后，不是应该从map中删除已经处理的key么？

**Comment by zyong2004** [comment]
如果不删除，是不是每次调用/notifications/v2  都会得到前面的key，是不是属于重复刷新配置？  不是应该有变动才刷新配置么？

**Comment by nobodyiam** [comment]
感觉你理解错了，建议debug跟一下代码吧

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
