### ISSUE TITLE
请教下ENV能配置到application.yml中吗？

### ISSUE THREAD

**Issue by cy1ng** [ctripcorp/apollo#1429]
apollo的配置想集中一点，好像没看到说能配到spring boot的yml文件中

**Comment by cy1ng** [comment]
好的  了解。 之前是打算在application.yml用不同的profile的,不过这样也是要手动自动环境的，暂时就用启动命令来选择环境了

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by shenhuaxx** [comment]
有一种场景是项目中存在一个特定目录(env)，底下存放各个环境的application.yml等文件。经过CI构建出来的交付包(zip)包带有启动脚本、jar、env目录等，发到不同环境就使用evn下不同环境的application.yml等文件。
这种场景已经把application.yml等文件按环境制备了。通过修改application.yml去调整apollo的env岂不是比调整启动命令更合理一点？
而且针对spring boot的场景，app.id不在apollo.xxx的序列下面感觉也是很割裂的。
现在很多公司基本都是spring boot一把梭了，主战场还是在spring boot。
如果有可能还是请再考虑考虑。

**Comment by Anilople** [comment]
> 有一种场景是项目中存在一个特定目录(env)，底下存放各个环境的application.yml等文件。经过CI构建出来的交付包(zip)包带有启动脚本、jar、env目录等，发到不同环境就使用evn下不同环境的application.yml等文件。 这种场景已经把application.yml等文件按环境制备了。通过修改application.yml去调整apollo的env岂不是比调整启动命令更合理一点？ 而且针对spring boot的场景，app.id不在apollo.xxx的序列下面感觉也是很割裂的。 现在很多公司基本都是spring boot一把梭了，主战场还是在spring boot。 如果有可能还是请再考虑考虑。

One solution is that, the zip file generate by CI, will be use in every environment, the file application.yml only keep one.

i.e 1 .zip file or 1 .jar file will be use from test environment to production environment. If config is different, through system properties to change it when startup. 

i.e it is not that through application.yml to choose apollo's config, it is that through apollo to choose application.yml, use -Dapollo.meta=xxx or environment or other way.
