### ISSUE TITLE
公共Namespace的一个问题

### ISSUE THREAD

**Issue by kentchenjh** [ctripcorp/apollo#1430]
对比公共和私有namespace，发现创建namespace的时候，私有的有各种类型，但公共的只有properties一种类型。请问是什么原因？

**Comment by oooooooz** [comment]
没看出来不同类型之间在 apollo 有何区别。默认 properties 能解决绝大部分场景需求了吧

**Comment by nobodyiam** [comment]
公共的namespace主要是为了支持继承和覆盖，所以目前只有properties一种类型，对公共配置而言应该也够用了。

**Comment by kentchenjh** [comment]
恩，properties类型满足了几乎大部分的需求。了解了，谢谢。
