### ISSUE TITLE
apollo客户端缓存文件并发读写问题

### ISSUE THREAD

**Issue by DeanJi** [ctripcorp/apollo#1431]
apollo客户端应用是一个集群，比如有5台机器都部署同一个应用A，由于是集群修改其中一台机器的某个文件，也会作用到其他4台机器上。当apollo发布配置的时候，5台机器同时修改apollo的缓存文件，会不会出问题？

**Comment by oooooooz** [comment]
修改本地缓存文件也会自动同步到配置中心？apollo 有这个特性吗，记得 wiki 上没写这个

**Comment by nobodyiam** [comment]
5台机器刷新5台机器自己的缓存文件，貌似没啥问题啊？

**Comment by DeanJi** [comment]
这5台机器是一个集群，其中一台机器修改了某个文件，这个文件会同步到其他四台机器

**Comment by DeanJi** [comment]
嗯，这是我们自己的同步机制。同一个应用部署在多台机器上应该要有同步机制吧，不然要是有个什么修改的话就要登入到每台机器上改。这个同步机制貌似会跟apollo写缓存文件出现并发问题，有没有什么好的解决方案？

**Comment by nobodyiam** [comment]
这个机制我倒是头一次听说，感觉怪怪的，难道应用日志也会互相复制？

不过貌似也没啥关系吧，同步过去的文件反正也是一样的。

**Comment by DeanJi** [comment]
日志是不同步的。一般也不会有什么问题，就是担心apollo在A机器写文件，同步机制从B机器往A机器复制文件，两者同时发生，出现并发问题。

**Comment by nobodyiam** [comment]
日志如果不同步，apollo的本地缓存也可以设置为不同步吧。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
