### ISSUE TITLE
quick start 根本用不了，无论是cmd下，还是docker

### ISSUE THREAD

**Issue by gnsilence** [ctripcorp/apollo#1433]
cmd 下是直接闪退没任何日志，
docker直接是
(ERRORERROR: Windows named pipe error: 膸碌脥艂艕艊藳禄碌藵脰赂露篓碌脛脦脛慕牛藝艁 (code: 2))
有人遇见过吗，
java jdk环境测试正确1.8，mysql 5.7.2
git bash 2.18

**Comment by nobodyiam** [comment]
请按照quick start文档中描述的操作，不是双击demo.sh。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
