### ISSUE TITLE
AdminServiceHealthIndicator里面的health如何检测down的情况？

### ISSUE THREAD

**Issue by lin1658** [ctripcorp/apollo#1434]
宋大神，您好，请教一下，系统的health check，一直返回0，系统怎么检查health down的？靠appService.findAll(pageable)抛异常吗？
public class AdminServiceHealthIndicator implements HealthIndicator {

  @Autowired
  private AppService appService;

  @Override
  public Health health() {
    int errorCode = check();
    if (errorCode != 0) {
      return Health.down().withDetail("Error Code", errorCode).build();
    }
    return Health.up().build();
  }

  private int check() {
    PageRequest pageable = new PageRequest(0, 1);
    appService.findAll(pageable);
    return 0;
  }

}

**Comment by nobodyiam** [comment]
是的，意在检测数据库连接是否正常。

另外，HealthIndicator的机制建议google了解一下。

**Comment by lin1658** [comment]
多谢了！
