### ISSUE TITLE
env环境变量无法读取问题

### ISSUE THREAD

**Issue by linrol** [ctripcorp/apollo#1437]
Environment is set to null. Because it is not available in either (1) JVM system property 'env', (2) OS env variable 'ENV' nor (3) property 'env' from the properties InputStream

**Comment by AoleiC** [comment]
忍不住回复一句，提供的信息太少了，让大神们怎么帮你分析？

**Comment by coolbaobei** [comment]
优先读取配置文件的，如果没有加server.properties,就读JVM的，最后查询系统环境变量；如果都没设置，那就真的读不到了。多半是你的key写的有问题

**Comment by leesing0107** [comment]
你的ENV配置不是是没有配置，编译脚本或者启动脚本中都可以配置的

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by ZereChen** [comment]
VM options设置成 -Denv=DEV
