### ISSUE TITLE
Apollo配置的是defaultZone，而Eureka有zone分区的概念，可否启用zone就近机房调用配置中心

### ISSUE THREAD

**Issue by david1228** [ctripcorp/apollo#1438]
Apollo配置的是defaultZone，而Eureka有zone分区的概念，可否启用zone就近机房调用配置中心？
比如Apollo生产环境分别部署在A机房(bj-a)和B机房(tj-b)，A机房的eureka.instance.metadata-map.zone=bj-a，B机房的eureka.instance.metadata-map.zone=tj-b
因为Meta Server对注册中心获取做了封装，是不是上述zone，即使配置上也不会生效了呢？

**Comment by nobodyiam** [comment]
Apollo没有使用Eureka的zone分区，而是自己简单实现了同机房服务注册，可以参考 [分布式部署指南 - Eureka服务Url](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#1eurekaserviceurl---eureka%E6%9C%8D%E5%8A%A1url)的注3部分。

客户端的话，需要域名解析实现同机房解析即可，比如A机房的meta server地址解析到A机房，这样客户端只会拿到A机房的config service列表。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
