### ISSUE TITLE
宋大神 有个问题

### ISSUE THREAD

**Issue by BillBearXiong** [ctripcorp/apollo#1439]
![image](https://user-images.githubusercontent.com/37796324/45012775-34393400-b04b-11e8-88c5-16fe0c606968.png)

   在PCF上部署的时候   项目管理页面 添加管理员的时候   被公司的WAF防火墙挡了    content-TYpe：application/json  请求的数据应该不是json格式的   应该只是一个字符串

**Comment by nobodyiam** [comment]
额，waf防火墙还挺智能的。。。这个看上去是前端传的content type不太对

**Comment by nobodyiam** [comment]
Fixed in #1443

**Comment by BillBearXiong** [comment]
解决了   改了代码  现在测下来  好像没什么事

**Comment by nobodyiam** [comment]
在 #1443 里面已经改过了呀。

**Comment by nobodyiam** [comment]
1.1.0版本已经发布，包含了该问题修复，更多信息可以参考： https://github.com/ctripcorp/apollo/releases/tag/v1.1.0
