### ISSUE TITLE
请问对于Spring mvc的项目或者普通的java项目怎么采用jasypt进行数据加密

### ISSUE THREAD

**Issue by whai888** [ctripcorp/apollo#1440]
对于数据库的密码是系统启动的时候加载的，不是手工建立连接，不知道怎么进行数据加密。
采用Spring boot的项目，通过你的case是可以成功的，但是Spring mvc的项目就不行，麻烦给点思路。谢谢

**Comment by coolbaobei** [comment]
用druid 自带的加密试试呢

**Comment by nobodyiam** [comment]
原理都是一样的，因为jdbc连接的时候需要明文的。

可以使用druid，那个自带加密的，或者自己在客户端实现加解密。

demo给的是spring-boot整合了Jasypt，如果不是spring mvc的话，自己集成[Jasypt](http://www.jasypt.org/)也可以的。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
