### ISSUE TITLE
configservice和Adminservice

### ISSUE THREAD

**Issue by huihui1112** [ctripcorp/apollo#1442]
configservice和Adminservice 这两个服务 如果不部署在同一台服务器上 也没问题吧?
我这边的portal 正式部署的时候 报这个 
No available admin server. Maybe because of meta server down or all admin server down. Meta server address: 很难想通.
![image](https://user-images.githubusercontent.com/30152557/45028594-3796e480-b078-11e8-97dc-4de4a20b3802.png)

**Comment by huihui1112** [comment]
访问 http://config-test.yiyaowang.com:8080/services/admin  是有结果的  这个地址我在机器上改了hosts.
另外补充下
这是在阿里云虚拟机上部署的... 这个Ip呢 在虚拟机上 ping 也ping得通... 
这次直接注册中心写的ip地址 但还是..出现这个
![image](https://user-images.githubusercontent.com/30152557/45066961-78800f00-b0f3-11e8-867d-d2632cd9fa65.png)

**Comment by nobodyiam** [comment]
这个错误提示貌似很明显了吧，你到portal机器上 curl http://10.6.218.119:8080/services/admin 看看。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
