### ISSUE TITLE
configservice adminservcie这些服务启动的时候 需要在本地的/opt/setting/server.properties放东西吗

### ISSUE THREAD

**Issue by huihui1112** [ctripcorp/apollo#1445]
两个问题  第一个 :configservice adminservcie这些服务启动的时候 需要在本地的/opt/setting/server.properties放东西吗
我之前一直以为 只有客户端需要放.
第二个问题: portal这个服务如果不放这个server.properties文件的话  启动会一直报错. 看日志会说 没指定env 然后portal去连测试环境 预生产环境的注册中心 一直报错 提示 如图:
![image](https://user-images.githubusercontent.com/30152557/45073667-dff98700-b112-11e8-85db-0f0daaf8c557.png)

**Comment by nobodyiam** [comment]
第一个问题，可以不放

第二个问题，错误提示很明显了，connect timeout，portal连不上10.6.218.119

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
