### ISSUE TITLE
8080和8090端口无故挂掉，可能是什么原因？

### ISSUE THREAD

**Issue by banshaotuan** [ctripcorp/apollo#1446]
查看apollo-portal.log  提示连接Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused

查看apollo-service.log 没看到错误信息，如附件，这如何解决？

**Comment by nobodyiam** [comment]
端口怎么会无故挂掉，进程你看看在不在？

lsof -nPi | grep 8080 也可以看一下

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
