### ISSUE TITLE
IP地址问题

### ISSUE THREAD

**Issue by wlkfec** [ctripcorp/apollo#1453]
我在本地简单测试配置服务，apoollo服务搭建到了阿里云服务器上，然后我在本地配置的是服务器公网IP地址，然后获取到的配置信息转换成服务器的内网地址了，导致获取配置失败，请问这种情况该如何解决？

**Comment by hitfire** [comment]
![image](https://user-images.githubusercontent.com/22113766/45145440-3a6a1480-b1f3-11e8-91cc-47920a28814a.png)
可以参考[常见问题](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#3-admin-server-%E6%88%96%E8%80%85-config-server-%E6%B3%A8%E5%86%8C%E4%BA%86%E5%86%85%E7%BD%91ip%E5%AF%BC%E8%87%B4portal%E6%88%96%E8%80%85client%E8%AE%BF%E9%97%AE%E4%B8%8D%E4%BA%86admin-server%E6%88%96config-server)
在启动时绑定注册ip就ok了

**Comment by wlkfec** [comment]
谢谢  这个方法可行  也怪我没有仔细看文档  东西蛮多  还得多研究  ：）

**Comment by nobodyiam** [comment]
如果只是给本地调试用的话，可以不用绑定注册IP，直接客户端指定config service地址也可以的

![image](https://user-images.githubusercontent.com/837658/45164036-30acd500-b224-11e8-8099-fb063a02f789.png)
