### ISSUE TITLE
xml格式的配置文件如何加载呢？

### ISSUE THREAD

**Issue by yueny** [ctripcorp/apollo#1454]
你好。
在实际项目中，存在xml格式的配置文件。这种如果通过apollo加载？

**Comment by yueny** [comment]
apollo namespace 名字为 address xml格式。
配置内容
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<envs>
    <why>快速定位到你想去的地方</why>

    
    <env name="公共模块" code="env_common">
        <address value="xxx" href="xxx"></address>
        <address value="xxx" href="xxx/"></address>
    </env>
</envs>

**Comment by yueny** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<envs>
    <why>快速定位到你想去的地方</why>

    
    <env name="公共模块" code="env_common">
        <address value="xxx" href="xxx"></address>
        <address value="xxx" href="xxxx/"></address>
    </env>
</envs>

**Comment by nobodyiam** [comment]
可以通过api方式获取，[ConfigService.getConfigFile](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/ConfigService.java#L64)

**Comment by nobodyiam** [comment]
目前不能

**Comment by yueny** [comment]
谢谢

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
