### ISSUE TITLE
宋大神 springboot

### ISSUE THREAD

**Issue by BillBearXiong** [ctripcorp/apollo#1455]
大神 springboot 何时升到2.0？

**Comment by BillBearXiong** [comment]
今天把springboot springclou分别升级到2.0.3  和F版本   apollo加入F版本的eureka的是一直报这个异常  然后我把apollo 加入E版本的eureka  没有报错 。
[一个异常.txt](https://github.com/ctripcorp/apollo/files/2359929/default.txt)

**Comment by nobodyiam** [comment]
apollo客户端支持spring boot 2.0的，服务端后面会做升级的，不建议你自己升级，而且升级貌似也没有很大的好处？

**Comment by nobodyiam** [comment]
apollo服务端已经升级spring boot到2.0.5，spring cloud到Finchley.SR1，详情参见 #1527

**Comment by nobodyiam** [comment]
1.1.0版本已经发布，apollo服务端已经升级spring boot和spring cloud到最新版本，更多信息可以参考： https://github.com/ctripcorp/apollo/releases/tag/v1.1.0
