### ISSUE TITLE
多环境配置的名字必须是dev、fat、uat、pro这四个吗，如果我想自己定义环境名称，就会报错！

### ISSUE THREAD

**Issue by liuxhui** [ctripcorp/apollo#1456]
多环境配置的名字必须是dev、fat、uat、pro这四个吗，如果我想自己定义环境名称，就会报错！

**Comment by limitAp** [comment]
https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#42-%E6%B7%BB%E5%8A%A0%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84%E7%8E%AF%E5%A2%83

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by panol** [comment]
https://ctripcorp.github.io/apollo/#/zh/deployment/distributed-deployment-guide?id=_2131-%E8%B0%83%E6%95%B4apolloportaldb%E9%85%8D%E7%BD%AE

**Comment by kezhenxu94** [comment]
> https://ctripcorp.github.io/apollo/#/zh/deployment/distributed-deployment-guide?id=_2131-%E8%B0%83%E6%95%B4apolloportaldb%E9%85%8D%E7%BD%AE 站点404

https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_2131-调整apolloportaldb配置

@panol 和本 issue 无关的问题请新开 issue 或在 [Discussion](https://github.com/apolloconfig/apollo/discussions) 提问
