### ISSUE TITLE
关于client的ip问题

### ISSUE THREAD

**Issue by sunshanpeng** [ctripcorp/apollo#1457]
通过查看`NetworkInterfaceManager`这个类的代码，发现获取ip的规则如下
```java
private void load() {
    String ip = getProperty("host.ip");

    if (ip != null) {
      try {
        m_local = InetAddress.getByName(ip);
        return;
      } catch (Exception e) {
        System.err.println(e);
        // ignore
      }
    }

    try {
      Enumeration<NetworkInterface> interfaces = NetworkInterface.getNetworkInterfaces();
      List<NetworkInterface> nis = interfaces == null ? Collections.<NetworkInterface>emptyList() : Collections.list(interfaces);
      List<InetAddress> addresses = new ArrayList<InetAddress>();
      InetAddress local = null;

      try {
        for (NetworkInterface ni : nis) {
          if (ni.isUp() && !ni.isLoopback()) {
            addresses.addAll(Collections.list(ni.getInetAddresses()));
          }
        }
        local = findValidateIp(addresses);
      } catch (Exception e) {
        // ignore
      }
      if (local != null) {
        m_local = local;
        return;
      }
    } catch (SocketException e) {
      // ignore it
    }

    m_local = InetAddress.getLoopbackAddress();
  }
```

```java
public InetAddress findValidateIp(List<InetAddress> addresses) {
    InetAddress local = null;
    int maxWeight = -1;
    for (InetAddress address : addresses) {
      if (address instanceof Inet4Address) {
        int weight = 0;

        if (address.isSiteLocalAddress()) {
          weight += 8;
        }

        if (address.isLinkLocalAddress()) {
          weight += 4;
        }

        if (address.isLoopbackAddress()) {
          weight += 2;
        }

//        // has host name
        // TODO fix performance issue when calling getHostName
        if (!Objects.equals(address.getHostName(), address.getHostAddress())) {
          weight += 1;
        }

        if (weight > maxWeight) {
          maxWeight = weight;
          local = address;
        }
      }
    }
    return local;
  }
```

# 这里ip的获取权重是如何考虑的？

我发现在多网卡的机器上，同一个客户端在配置中心的ip和注册中心Eureka的ip是不一样的。
Eureka注册时候用的ip是通过InetUtils.findFirstNonLoopbackAddress()方法获取的，看起来就是取第一个有效的ipv4地址。
配置中心使用的权重过滤原因是什么，特别是`Objects.equals(address.getHostName(), address.getHostAddress())`对比hostName和hostAddress这个，因为我去掉这个权重后就能保持一致了

**Comment by nobodyiam** [comment]
多网卡的时候希望找一个『最正确』的IP，所以设计了一种权重的机制。

使用`Objects.equals(address.getHostName(), address.getHostAddress())`增加权重的好处是运维可以提升某块网卡的权重，比如在/etc/hosts中加一条映射记录。

**Comment by sunshanpeng** [comment]
好的，多谢。
另外想请教一下，如果我这边希望跟注册在eureka上的ip一致，比如参考`InetUtils.findFirstNonLoopbackAddress()`这个方法，修改ip的获取规则有什么风险吗？

**Comment by nobodyiam** [comment]
没啥风险，不过最简单的方式就是在`/etc/hosts`文件中加一条映射记录，可以参考 [6. 客户端多块网卡造成获取IP不准，如何解决？](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#6-%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%A4%9A%E5%9D%97%E7%BD%91%E5%8D%A1%E9%80%A0%E6%88%90%E8%8E%B7%E5%8F%96ip%E4%B8%8D%E5%87%86%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3)

**Comment by nobodyiam** [comment]
代码就是这么写的，我们公司都是这么用的呀，除非其它网卡有其它更高的权重？

**Comment by DeanJi** [comment]
这个权重机制看得有点懵，为什么SiteLocalAddress权重就+8，LinkLocalAddress权重就+4，LoopBackAddress权重就+2？

**Comment by nobodyiam** [comment]
为了区分重要程度

**Comment by sunshanpeng** [comment]
好的，谢谢

**Comment by nobodyiam** [comment]
还有一种方式就是通过`-Dhost.ip=30.50.28.161`来覆盖

**Comment by nobodyiam** [comment]
[1.4.0](https://github.com/ctripcorp/apollo/releases/tag/v1.4.0)版本调整了网卡获取逻辑，如果有多网卡，且都是普通网卡的话，可以通过调整它们在系统中的顺序来改变优先级，顺序在前的优先级更高。

**Comment by seguzhizi** [comment]
> ![637552f3-cd04-48dd-b806-159eef723b13](https://user-images.githubusercontent.com/24695243/45465135-6a12a280-b746-11e8-9b55-8af9e458894f.jpeg)
> 宋哥，如截图，apollo客户端取到的IP是eth0的IP，而不是配在/etc/hosts里eth1的IP。

兄弟，你这个问题解决了吗？我现在遇到的问题和你的是一模一样的。。。
配置了/etc/hosts，但是portal拉取到的还是eth0的ip，无语了

另外，@nobodyiam，由于客户端实例很多，使用-Dhost.ip的方式实在难以开展，请问还有别的办法吗？
最后，在请问下，portal界面展示的全部实例ip列表，这里的ip有实际作用吗？portal下发配置，是不是依赖这里的ip呢？
O(∩_∩)O谢谢

**Comment by nobodyiam** [comment]
1.4.0版本开始会通过网卡顺序决定用哪个IP

https://github.com/ctripcorp/apollo/pull/1986

portal页面上展示的实例ip只是展示用，实际下发配置是客户端自己连上来获取的。
