### ISSUE TITLE
apollo 1.0.0版本自动更新Spring Placeholder BUG

### ISSUE THREAD

**Issue by mingbotang** [ctripcorp/apollo#1458]
AutoUpdateConfigChangeListener类：

      // 2. check whether the value is really changed or not (since spring property sources have hierarchies)
      if (!shouldTriggerAutoUpdate(changeEvent, key)) {
        continue;
      }
判断是否自动更新
private boolean shouldTriggerAutoUpdate(ConfigChangeEvent changeEvent, String changedKey) {
    ConfigChange configChange = changeEvent.getChange(changedKey);

    if (configChange.getChangeType() == PropertyChangeType.DELETED) {
      return true;
    }

    return Objects.equals(environment.getProperty(changedKey), configChange.getNewValue());
  }
其中Objects.equals(environment.getProperty(changedKey), configChange.getNewValue());对比环境上下文中的值与apollo修改事件的值是否相等，修改的值与环境上下文的值肯定是不相等的。
而!shouldTriggerAutoUpdate(changeEvent, key)加上了非导致修改的值不等于原值就不会更新。

**Comment by nobodyiam** [comment]
这个不是BUG啊，你实际测试一下就知道了。
