### ISSUE TITLE
可否考虑添加一个功能，注册一个回调接口的实现，能自行扩展配置value的转换

### ISSUE THREAD

**Issue by onethin** [ctripcorp/apollo#1459]
可以注册一个回调接口，输入参数可以是配置key和value，输出就是value，应用拿到值的是处理过后的value。主要目的是能扩展个性化的参数值处理，比如自定义的加密等，有些公司的配置加密方式有自己的规定。

**Comment by nobodyiam** [comment]
这是一个很好的建议，之前的想法是提供一个spi，然后apollo在拿到远端配置后调用该spi对配置做处理，比如解密动作。

不过粒度可能不是一个key和value，更多的可能是给一堆key和value。

欢迎继续讨论~

**Comment by nobodyiam** [comment]
With the introduction of [ApolloInjectorCustomizer](https://github.com/apolloconfig/apollo/pull/3602), users could create an injector customizer to customize the apollo objects.
For example, you could create a customized `ConfigFactory` that wraps `DefaultConfigFactory`. In the implementation of `create` and `createConfigFile`, you could get the original `Config` and `ConfigFile` objects and then it's easy to wrap the value processing logic.
