### ISSUE TITLE
quick start始终都是超时状态

### ISSUE THREAD

**Issue by guochao205** [ctripcorp/apollo#1460]
$ ./demo.sh start
==== starting service ====
Service logging file is ./service/apollo-service.log
Started [19156]
Waiting for config service startup........................
Config service failed to start in 120 seconds! Please check ./service/apollo-service.log for more information.

**Comment by nobodyiam** [comment]
看上去要么是服务启动太慢，要么就是已经启动失败了，具体可以根据提示看一下日志。

**Comment by guochao205** [comment]
> 
> 
> 看上去要么是服务启动太慢，要么就是已经启动失败了，具体可以根据提示看一下日志。

嗯看着是目录有问题？

./service/apollo-service.jar: line 168: /c/Program: No such file or directory

**Comment by nobodyiam** [comment]
请确保是使用Git bash运行的，脚本针对它有特殊支持：https://github.com/nobodyiam/apollo-build-scripts/blob/master/demo.sh#L55

**Comment by nobodyiam** [comment]
看上去没有没有认出来是windows，https://github.com/nobodyiam/apollo-build-scripts/blob/master/demo.sh#L19

执行`echo "$(expr substr $(uname -s) 1 5)"`看看结果是啥？

**Comment by guochao205** [comment]
> 
> 
> 看上去没有没有认出来是windows，https://github.com/nobodyiam/apollo-build-scripts/blob/master/demo.sh#L19
> 
> 执行`echo "$(expr substr $(uname -s) 1 5)"`看看结果是啥？

![win](https://user-images.githubusercontent.com/10596072/45882061-93cf6780-bddf-11e8-8f55-7b5f6d920d54.png)

**Comment by nobodyiam** [comment]
看下你本地的demo.sh，和最新的比较一下，看看下面这段逻辑有没有

![image](https://user-images.githubusercontent.com/837658/45885260-879bd800-bde8-11e8-94df-940e641a5513.png)

**Comment by guochao205** [comment]
> 
> 
> 看下你本地的demo.sh，和最新的比较一下，看看下面这段逻辑有没有
> 
> ![image](https://user-images.githubusercontent.com/837658/45885260-879bd800-bde8-11e8-94df-940e641a5513.png)

![default](https://user-images.githubusercontent.com/10596072/45912200-1b54bf00-be50-11e8-901c-9d32c83d0c1e.png)

**Comment by Clearlove9** [comment]
解决了我的问题~

**Comment by xiaominyuan** [comment]
> 解决了我的问题~

请问是如何解决的呢

**Comment by moxuemeivip** [comment]
> 解决了我的问题~

请问是怎么解决的呢？我也遇到了这个问题

**Comment by eejron** [comment]
新版本的JDk安装包不需要配置JAVE_HOME也能正常执行Java程序了，因为安装时在Path默认配置了：C:\Program Files (x86)\Common Files\Oracle\Java\javapath，这个路径下也有java.exe的。

但是这个执行脚本依赖JAVA_HOME，所以需要配置下JAVA_HOME。

**Comment by lxCanty** [comment]
有大神知道这个问题怎么解决吗：apollo的configService服务启动异常

**Comment by Clearlove9** [comment]
邮件已收到，谢谢！

**Comment by nobodyiam** [comment]
> 有大神知道这个问题怎么解决吗：apollo的configService服务启动异常

You may check the logs for more information.

**Comment by lxCanty** [comment]
但是日志里面报的错误实在是 太多了，而且在Google上找不到什么解决办法




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apolloconfig/apollo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月20日(星期二) 上午8:55
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [apolloconfig/apollo] quick start始终都是超时状态 (#1460)





  
有大神知道这个问题怎么解决吗：apollo的configService服务启动异常
  
You may check the logs for more information.

**Comment by Clearlove9** [comment]
邮件已收到，谢谢！
