### ISSUE TITLE
关于配置变化监听机制的优化建议

### ISSUE THREAD

**Issue by fjlxq1994** [ctripcorp/apollo#1461]
宋大哥你好，在使用客户端时，我发现ApolloConfigChangeListener这一注解通过value时传入了namespace，但是给了一个默认的application的namespace，在实际使用过程中，我们发现namespace基本上是和配置文件中指定的APOLLO_BOOTSTRAP_NAMESPACES这一配置，想说能否在value缺失时指定namespace为当前应用配置的namespace。
且另有1.0.0的客户端可以通过配置ApolloConfigChangeListener的interestedKeys来监听特定的key。我发现这里的key似乎是全键监听，不是前缀，但是有的时候我们的配置在某个前缀变化时就会去做回调响应，这个特性是否也可以考虑加入优化下。
以上提到的两个特性都是我们业务在使用过程中遇到的，如宋哥考虑具备一定的通用性，希望能在未来的版本加上这两个特性。谢谢！

**Comment by nobodyiam** [comment]
第一个建议，因为注解方式不光是提供给spring boot使用的，还有不少spring的应用，所以之前是给了application这个默认namespace。改成默认为apollo.bootstrap.namespaces看上去是个合理的建议，但是这会给已有代码带来兼容性问题，所以在想到更好的方案之前先维持现状吧。

第二个建议很不错，可以增加一个API
