### ISSUE TITLE
Apollo配置在spring boot上下文刷新之后排序变了？

### ISSUE THREAD

**Issue by ChunMengLu** [ctripcorp/apollo#1463]
## 初始化时
<img width="896" alt="apollo 01" src="https://user-images.githubusercontent.com/2115440/45272165-31709000-b4de-11e8-8411-ecd5ece0e12b.png">

## 上下文刷新后
<img width="889" alt="apollo-02" src="https://user-images.githubusercontent.com/2115440/45272176-3b928e80-b4de-11e8-97bf-2992b3f94730.png">

这是，如果有相同的配置 Apollo 优先级就变得很低了。

**Comment by ChunMengLu** [comment]
<img width="923" alt="apollo-03" src="https://user-images.githubusercontent.com/2115440/45272830-21f34600-b4e2-11e8-8339-48f08d5e31b9.png">

**Comment by nobodyiam** [comment]
#1432 应该已经修复该问题了，正式版本还未发布，可以在本地验证一下。

**Comment by ChunMengLu** [comment]
本地测试 ok 了
