### ISSUE TITLE
请问 使用 google.inject方式，如何配置 apollo.meta

### ISSUE THREAD

**Issue by yueny** [ctripcorp/apollo#1464]
请问 使用 google.inject方式，如何配置 apollo.meta

**Comment by nobodyiam** [comment]
apollo.meta和是否使用google.inject方式没啥关系吧，参考一下 [1.2.2 Apollo Meta Server](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#122-apollo-meta-server)吧

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
