### ISSUE TITLE
apollo-client 1.0.0有个bug，apollo.meta配置多个地址会报没有可用服务。

### ISSUE THREAD

**Issue by vincentcui** [ctripcorp/apollo#1465]
![image](https://user-images.githubusercontent.com/3062191/45291195-0ad54800-b524-11e8-86dc-5a23ba6c5338.png)
看了下源码，应该是这块少拼了url后面的内容，正确代码应该如下：
`if (NetUtil.pingUrl(address + "/services/config")) {`

**Comment by nobodyiam** [comment]
这个已知是如果config service没有启动eureka server的话，会存在该问题，详见 #1413

已经在PR #1415 中修复

**Comment by nobodyiam** [comment]
1.1.0版本已经发布，包含了该问题修复，更多信息可以参考： https://github.com/ctripcorp/apollo/releases/tag/v1.1.0
