### ISSUE TITLE
zuul配置未生效

### ISSUE THREAD

**Issue by ahmu** [ctripcorp/apollo#1466]
有个问题请教一下，参考apollo-use-cases/spring-cloud-zuul，在springboot项目中增加ZuulPropertiesRefresher配置后。更新配置后并未生效，可能的原因有哪些？

**Comment by nobodyiam** [comment]
先把demo项目跑起来理解一下刷新逻辑，然后再改到自己的spring boot项目会更顺手一些。

先检查一下配置是否正确获取并更新了，然后可以到`org.springframework.cloud.netflix.zuul.ZuulServerAutoConfiguration.ZuulRefreshListener#onApplicationEvent`中打个断点，看看是否收到了`RoutesRefreshedEvent`

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
