### ISSUE TITLE
Users表中Username长度是64，但是Authorities表中Username长度是50，创建超过50长度的用户，会报错

### ISSUE THREAD

**Issue by ryphnyuan** [ctripcorp/apollo#1467]
![image](https://user-images.githubusercontent.com/37541919/45333643-e459f000-b5a9-11e8-9d11-b060c529196a.png)

**Comment by nobodyiam** [comment]
确实。。。方便提个PR改一下吗？

另外，你是真的有那么长的用户名？

**Comment by ryphnyuan** [comment]
并没有，只是在整理apollo的数据库接口，看到了这个地方，就试了一下~~

**Comment by ryphnyuan** [comment]
solved
