### ISSUE TITLE
Apollo的主页问题

### ISSUE THREAD

**Issue by FishMeat** [ctripcorp/apollo#1468]
Apollo主页怎么不展示全部项目，只展示个人创建的项目？
这样很不方便，每次都要搜下项目，再加入收藏。

**Comment by nobodyiam** [comment]
后续会支持展示自己创建的项目以及自己有权限的项目

**Comment by nobodyiam** [comment]
#1528 已经提交，现在我的项目会显示所有我作为管理员的项目

**Comment by nobodyiam** [comment]
1.1.0版本已经发布，包含了该项改进，更多信息可以参考： https://github.com/ctripcorp/apollo/releases/tag/v1.1.0
