### ISSUE TITLE
关联公共namespace不显示具体数据

### ISSUE THREAD

**Issue by tandanzZ** [ctripcorp/apollo#1469]
app.id=1100002 在DEV环境且部门代码配置为FK，为1100002添加public的namespace为base，
在FDEV环境新建一个应用且同步配置到FAT关联了FX.base后，关联的公共配置信息提示如下：

当前公共namespace的所有者 1100002 没有关联此namespace,请联系1100002的所有者在1100002项目里关联此namespace

怎样做才能正常显示FX.base的配置文件信息呢？

**Comment by tandanzZ** [comment]
![image](https://user-images.githubusercontent.com/6389333/45366246-fb7ff880-b610-11e8-850e-4974ef2a1a97.png)

**Comment by tandanzZ** [comment]
一定要这样操作才能获取到吗 是不是ID要保持一致才行？

**Comment by nobodyiam** [comment]
id不一致应该没关系的

**Comment by tandanzZ** [comment]
新加环境了  不能在应用里面补全环境 这样导致公共配置不能读取

**Comment by nobodyiam** [comment]
恩，补全逻辑目前只做了application namespace，这个后续要优化一下
