### ISSUE TITLE
docker_quick_start 起不来

### ISSUE THREAD

**Issue by shenge08** [ctripcorp/apollo#1473]
## 启动config报错
Config service failed to start in 120 seconds! Please check ./service/apollo-service.log for more information
## 启动portal报错
portal service failed to start in 120 seconds! Please check ./service/portal-service.log for more information

## 原因
启动脚本（demo.sh）的超时（默认启动时间为120秒）,可能时主机配置太差导致
## 解决方法
1. 手动启动名字为apollo-quick-start的容器（容器会在120秒后被关闭）
2. 进入容器docker exec -it apollo-quick-start bash
3. 进入/apollo-quick-start目录
4. 修改demo.sh （declare -i max_counter=24# 24*5=120s）-> declare -i max_counter=120# 120*5=600s）
5.退出容器，重启apollo-quick-start容器

**Comment by nobodyiam** [comment]
或许可以把启动等待时间通过命令传进去？

**Comment by amwson** [comment]
很容易启动，虚机最低配置1核2G。提前安装docker-ce和docker-compose

**Comment by Heier2013** [comment]
![_20181124164117](https://user-images.githubusercontent.com/9792980/48966210-cf68f680-f007-11e8-922c-a080145f8bb0.png)
1核2G的vps，120s启动一直报错，改为600s就ok了。

**Comment by jason1004** [comment]
> 或许可以把启动等待时间通过命令传进去？

等待时间怎样传？可以给一个demo 吗

**Comment by nobodyiam** [comment]
@jason1004 可以先手动改下demo.sh脚本
