### ISSUE TITLE
哪个版本准备支持@ConfigurationProperties的动态更新？

### ISSUE THREAD

**Issue by maxiaolong** [ctripcorp/apollo#1475]
@ConfigurationProperties(prefix = "redis.cache")
@Component("sampleRedisConfig")
public class SampleRedisConfig {
}

**Comment by nobodyiam** [comment]
spring cloud自身已经支持了，可以参考一下 https://github.com/ctripcorp/apollo-use-cases/blob/master/spring-cloud-zuul/src/main/java/com/ctrip/framework/apollo/use/cases/spring/cloud/zuul/ZuulPropertiesRefresher.java#L48

**Comment by maxiaolong** [comment]
> spring cloud自身已经支持了，可以参考一下 https://github.com/ctripcorp/apollo-use-cases/blob/master/spring-cloud-zuul/src/main/java/com/ctrip/framework/apollo/use/cases/spring/cloud/zuul/ZuulPropertiesRefresher.java#L48

有其他方式可以支持，但是都要手动写监听；你们后期有计划支持ConfigurationProperties的自动刷新吗？如果有我们先等一下（我们如果自己实现没有官方考虑的周全，如果后期官方支持了我们的client版本和官方差异太大，不方便后期升级），如果近期没有这个计划我们先做一些client端的定制，我们有很多项目要接apollo，所以想问一下，近期的版本有打算支持吗？非常感谢

**Comment by maxiaolong** [comment]
好的，谢谢
