### ISSUE TITLE
PRO点击发布配置需要多次点击才发布成功？

### ISSUE THREAD

**Issue by limitAp** [ctripcorp/apollo#1477]
您好,我目前是这样配置的，dev环境只配置了一套,pro环境配置了三套,dev环境在界面上点击发布配置没问题,但是pro环境需要多次点击才发布成功?请问可能是什么原因?望指点!谢谢!

**Comment by nobodyiam** [comment]
多次点击是啥意思？界面截图？系统日志有啥异常吗？

**Comment by limitAp** [comment]
谢谢宋老师的回复,具体如下!
![image](https://user-images.githubusercontent.com/18351359/45495129-35820380-b7a5-11e8-8745-84474646feab.png)
![image](https://user-images.githubusercontent.com/18351359/45495205-5f3b2a80-b7a5-11e8-88eb-2847bae07e32.png)
portal日志里并没有任何报错迹象

**Comment by nobodyiam** [comment]
看这个截图，估计是你不同环境的admin service都注册到pro的eureka了。

打开 http://{pro_meta_url}/services/admin 就知道了。

**Comment by limitAp** [comment]
宋老师，您好。还是遇到上次问题。我们pro环境防止迭机 分布式部署了三套。三套共用的一个数据库集群。
以下是portal.mata配置
![image](https://user-images.githubusercontent.com/18351359/46157769-0ee8c000-c2af-11e8-9cd2-4db6110950f2.png)
数据库中ApolloConfigDB_Pro配置如下
![image](https://user-images.githubusercontent.com/18351359/46157886-49eaf380-c2af-11e8-83cc-f78688002cc6.png)
结果39挂了，发现不能用了。界面上点击发布
![image](https://user-images.githubusercontent.com/18351359/46158231-ffb64200-c2af-11e8-839f-2b21e66df607.png)
并没有变灰。没有发布成功。是否是我的部署方式有问题？

**Comment by limitAp** [comment]
之前pro点击发布多次才成功有没有可能是延迟这种可能性的原因？

**Comment by limitAp** [comment]
之前pro点击发布多次才成功有没有可能是延迟这种可能性的原因？因为有时候点一次就成功，而有时候需要点击多次？
