### ISSUE TITLE
新建的项目配置如何自动创建之前环境已经存在的集群

### ISSUE THREAD

**Issue by yueny** [ctripcorp/apollo#1479]
新建的项目配置如何自动创建之前环境已经存在的集群。
比如在DEV环境下存在集群。那如何让后续创建的所有项目，DEV环境都有相应的集群。
现在每次新建项目，都要重复的创建好多次集群信息。 这个有没有一种设置？

**Comment by nobodyiam** [comment]
集群是为了独立配置使用的，如果应用在不同集群间的配置是一样的，那就没有必要创建单独的集群。

基于这个考量，所以Apollo不会为应用自动创建集群，用户可以根据实际情况自行创建。

**Comment by yueny** [comment]
好的。 感谢

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
