### ISSUE TITLE
private namespace删除创建方案的改进

### ISSUE THREAD

**Issue by Adol1111** [ctripcorp/apollo#1484]
### 问题
新版private namespace已经支持删除，但如果真的发生了误删除（某个环境误删除），需要彻底删除所有环境的apollo才能重新创建。如果该namespace正在被使用（特别是生产环境），那么只能通过改数据库的方式恢复。

### 建议
创建namespace时，如果发现当前环境已存在namespace，直接跳过，只需要为已删除的环境进行创建即可。这样即使发生了误删除，恢复也比较简单，不怕被误删除。不知道有没有其他的问题？

**Comment by nobodyiam** [comment]
感谢建议，目前确实会产生这个问题，不过改变创建namespace的语义可能不太好，因为本质上不是创建一个namespace，而是针对某个环境恢复一个private namespace？

**Comment by Adol1111** [comment]
也可以，至少有一个界面可以进行恢复，改数据库还是太麻烦了

**Comment by nobodyiam** [comment]
@reignsr 是的，这块后续需要优化的

**Comment by zouyx** [comment]
@Adol1111 @reignsr 场景是只需要恢复namespace还是连namespace里的配置也需要一起恢复？

那release和release history会涉及到吗？

有没有更详细的场景？或者说实际要解决的问题。

**Comment by reignsr** [comment]
@zouyx 我所说的追加环境的场景，跟 @Adol1111 说的误删除恢复，虽然都是命名空间重名不能创建，但是在需求上还是有差异的，我只需要在补缺环境中可以自动同步建立其他环境先前已经存在的命名空间，使各环境命名空间保持一致。最不济，也得在补缺环境后，能够允许在新环境中，创建较其他环境缺失的同名命名空间。我的需求不需要namespace中的配置数据，release相关数据当然也不需要，实际情况新追加的环境本身也没有发布过。

**Comment by Adol1111** [comment]
@zouyx 我两者都可以接受，只要能恢复误删除的配置就行，大不了麻烦一点再手动配置一下。当然能恢复被删了的namespace记录是最好了。不然的话，每次都要去手动改数据库什么的，就太麻烦了。而且生产环境可能还没有相应的权限。

**Comment by zouyx** [comment]
明白，其实是两个需求不一样的需求。。

**Comment by nobodyiam** [comment]
[1.2.0](https://github.com/ctripcorp/apollo/releases/tag/v1.2.0)版本已经发布，增加了『补缺Namespace』功能，支持补全缺失的公共namespace和私有namespace信息。
