### ISSUE TITLE
Spring 任务相关问题

### ISSUE THREAD

**Issue by yueny** [ctripcorp/apollo#1485]
在使用spring任务时， 在配置中心设置任务执行cron。如何实现配置中心任务变更后， 任务执行周期也生效。 目前是不生效的。需要自己去刷。
例子 @Scheduled(cron = "${task.demo.cron:0/10 * * * * ?}")

**Comment by nobodyiam** [comment]
如果是Bean的话，可以尝试用@RefreshScope，如果是其它形式的话，可以看看是否有刷新任务执行周期的API。

配置中心能确保的是配置在更新后推送到客户端，对于这类有初始化逻辑的情况，还需要根据实际情况对接的。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
