### ISSUE TITLE
关于多级配置中心的问题

### ISSUE THREAD

**Issue by GINTOPN** [ctripcorp/apollo#1486]
背景：我用的是SpringBoot的项目，迁移的是spring的项目。
迁移的spring项目中有一个是用spring-context注入的bean，如下图，这是一个map，还是String-Object的形式
![image](https://user-images.githubusercontent.com/20829195/45624973-5b1d4e80-babe-11e8-85c1-41cce7e6cf58.png)
如果我用springboot项目，想把这种注入形式写到配置中心中(不能使用aplication-context.xml，因为是springboot项目)，请问配置中心应该怎么写

**Comment by nobodyiam** [comment]
这个和配置中心本身没啥关系的，可以google一下spring相关的文档。

如果用ConfigurationProperties的话，可以参考[SampleRedisConfig](https://github.com/ctripcorp/apollo/blob/master/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/spring/springBootDemo/config/SampleRedisConfig.java)

**Comment by GINTOPN** [comment]
好的，谢谢大佬
