### ISSUE TITLE
是否考虑后续支持应用版本概念

### ISSUE THREAD

**Issue by reignsr** [ctripcorp/apollo#1487]
个人理解，当下版本的apollo可以从项目、环境、集群、命名空间几个维度去管理配置参数，官方是否有考虑后续提供版本的维度？适用于应用的多版本部署，滚动发布以及回滚操作。描述一个典型场景：
1、apollo中添加应用 v0.1对应的参数；
2、apollo发布配置参数，应用 v0.1上线；
3、apollo中调整参数适用于应用 v0.2；（增删改都可能发生）
4、apollo发布配置参数，应用 v0.2上线；（配置发布动作可能多次）
5、应用 v0.2上线后发现问题，短时间内不能修复，需要回滚到应用 v0.1版本；
此时，apollo中需要将配置参数恢复到0.1版本的状态，否则无法适用于0.1版本的程序，若是参数变化较多则比较麻烦。
建议官方后续提供一个应用版本的概念，可以从这个维度去维护配置，应用访问配置中心时也许指明对应的版本，类似disconf中的版本概念。

**Comment by nobodyiam** [comment]
这个之前有提过的，参考 #1399

**Comment by reignsr** [comment]
@nobodyiam 看过 #1399 ，个人感觉版本的加入并不会给所有使用场景都带来复杂度，现在没有版本概念，我们可以理解为现在大家都是统一使用了一个默认版本，就像默认的命名空间application。增加了版本概念后，不需要版本更迭的则可以永远使用一个初始版本，而有需要的人则可以自定义版本并依据版本使用配置，可以实现配置的快速切换，也能够支持同一应用的多版本发布。
个人认为未来对于软件产品发布上线的持续性、连贯性需求将越来越迫切，更多的应用系统会追求业务不中断，服务不停机的发布模式，更多的使用蓝绿部署，滚动发布，如果配置中心没有版本维度支持，将很难满足未来的发展需求。
另，以集群替代版本变通使用，首先从概念上让使用者感觉很奇怪，不易理解，再有就是我们已经使用了集群，用于分划同一环境下的不同节点的服务器集合，已经无法再用作分划版本。

**Comment by nobodyiam** [comment]
@reignsr 

感谢分析，很透彻！这块在业务上确实是有场景的，不过如何设计好这个模型，如何让用户用起来简单，这个可能需要仔细思考一下，如果有任何建议，也欢迎随时提出！
