### ISSUE TITLE
请问下作者有计划apollo未来支持yml格式么？

### ISSUE THREAD

**Issue by Dreamroute** [ctripcorp/apollo#1488]
如题：properties在复杂格式，以及数组等方面的表现比起yml要稍微差一点，未来有计划支持yml格式么？谢谢。

**Comment by nobodyiam** [comment]
之前有不少人提到过的，倾向于社区贡献，可以参考 #653

**Comment by nobodyiam** [comment]
我新开了一个PR #1944，支持yml类型的namespace注入到Spring中去，大家可以看一下~

**Comment by nobodyiam** [comment]
[1.3.0](https://github.com/ctripcorp/apollo/releases/tag/v1.3.0)版本已经发布，支持了Yml/Yaml格式的namespace和Spring/Spring Boot集成。
