### ISSUE TITLE
springboot项目中application.properties中的配置怎么覆盖apollo中的配置

### ISSUE THREAD

**Issue by liuyi9608** [ctripcorp/apollo#1489]
本地的配置怎么覆盖apollo中的配置？

**Comment by liuyi9608** [comment]
我测了一下，在本地application.properties文件中写跟apollo key一样的配置，他读取的是apollo中的配置，现在我是想本地覆盖一下，怎么做到？求大神解答~~~

**Comment by nobodyiam** [comment]
本地覆盖可以通过System Property，比如-Dxx=yy

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
