### ISSUE TITLE
v1.0.0 版本，按照文档中的流程进行apollo的K8S部署时，出现一个问题，请看看

### ISSUE THREAD

**Issue by bbqtk** [ctripcorp/apollo#1491]
我的开发环境是mac，K8S环境为1.10，完全按照官方文档来走，没有进行任何改动，出错的提示如下图：
<img width="1409" alt="2018-09-17 8 08 21" src="https://user-images.githubusercontent.com/19991733/45679893-2962c100-bb6c-11e8-8d7c-420e6dc6bbe0.png">
****

**Comment by nobodyiam** [comment]
@AiotCEO 对这个问题不知是否有经验？

**Comment by bbqtk** [comment]
老哥，請把這個bug改了吧，我直接在dockerfile中把
ENTRYPOINT ["/apollo-admin-server/entrypoint.sh"]  注释掉了,启动一切正常，因为在dockerfile中已经声明了环境变量了，不需要entrypoint.sh这个替换的过程了，直接在K8S的部署文件中定义configMap就可以了。K8S部署一切正常。还有一个文档中没有说明，alpine-bash:3.8 这个镜像是私有的，需要我们自己去打包的，目录在 apollo-on-kubernets/alpine-bash-3.8-image。

**Comment by nobodyiam** [comment]
@AiotCEO @bbqtk 

两位看看这个是否是个问题？如果是的话，是否可以提交一个PR？

**Comment by AiotCEO** [comment]
@bbqtk 

这个是提供了两种方式，一种是 configmap 方式，一种是 kubernetes 环境变量方式。如果不需要环境变量方式，注释掉即可

**Comment by yanmaipian** [comment]
@AiotCEO @bbqtk   我也遇到了/apollo-config-server/entrypoint.sh: line 13: can't create /apollo-config-server/config/application-github.properties: Read-only file system 这个问题，我在网上也找了好久，以为是权限问题，试着把目录权限修改成 777 并重新打成镜像，但是没能解决，觉得是k8s问题。

**Comment by yanmaipian** [comment]
@bbqtk @AiotCEO  从kubernetes1.9版本开始secret, configMap, downwardAPI and projected volumes 默认就为readonly，及时制定了volumeMounts.readOnly=false 参数也没有任何效果，
![image](https://user-images.githubusercontent.com/12362162/49875440-faeb3e00-fe5b-11e8-93ae-50f8420ee56c.png)

**Comment by tigermysql** [comment]
> 老哥，請把這個bug改了吧，我直接在dockerfile中把
> ENTRYPOINT ["/apollo-admin-server/entrypoint.sh"] 注释掉了,启动一切正常，因为在dockerfile中已经声明了环境变量了，不需要entrypoint.sh这个替换的过程了，直接在K8S的部署文件中定义configMap就可以了。K8S部署一切正常。还有一个文档中没有说明，alpine-bash:3.8 这个镜像是私有的，需要我们自己去打包的，目录在 apollo-on-kubernets/alpine-bash-3.8-image。

hi，可以请教一下，注释掉之后，数据库的信息不是已经dockerfile env了吗  k8s还需要configMap？

**Comment by FANHIDE** [comment]
HI,请问这个bug还没修复吗？

**Comment by nobodyiam** [comment]
有环境可以重现的可以帮忙提交一个PR修复一下

**Comment by huzhou520** [comment]
确实有这个问题， 估计用k8s搭建的人都会遇到，不过不是多难解决。

**Comment by nobodyiam** [comment]
已经在PR #2113 中修复

**Comment by nobodyiam** [comment]
[1.4.0](https://github.com/ctripcorp/apollo/releases/tag/v1.4.0)版本已经发布，修复了此问题。
