### ISSUE TITLE
HttpMediaTypeNotAcceptableException: Could not find acceptable representation

### ISSUE THREAD

**Issue by shmilyah** [ctripcorp/apollo#1497]
apollo config 和 admin 启动后一直会报 HttpMediaTypeNotAcceptableException: Could not find acceptable representation 这个异常，有遇到过吗？能解决吗？求教。。。

**Comment by nobodyiam** [comment]
抓下包看看请求来自哪里，应该不是正常的http请求。

**Comment by shmilyah** [comment]
嗯，查出原因了，是 spring boot admin 健康检查的请求

**Comment by shmilyah** [comment]
多谢

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
