### ISSUE TITLE
部门id存在中文时候，创建的public namespace无法被关联

### ISSUE THREAD

**Issue by eledstudy** [ctripcorp/apollo#1499]
部门id存在中文时候，创建的public namespace无法被关联

**Comment by nobodyiam** [comment]
orgId请用英文吧，orgName可以用中文。

校验代码：https://github.com/ctripcorp/apollo/blob/master/apollo-common/src/main/java/com/ctrip/framework/apollo/common/utils/InputValidator.java#L27

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
