### ISSUE TITLE
宋大神，想问一下，apollo在配置中修改了，实时更新到应用，这个能不能关闭

### ISSUE THREAD

**Issue by liuyi9608** [ctripcorp/apollo#1500]
在springboot环境或者spring环境或者普通ava环境怎么把热部署关闭

**Comment by liuyi9608** [comment]
apollo.autoUpdateInjectedSpringProperties = false 加入了这个配置，不起作用

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
