### ISSUE TITLE
宋大神，有没有关于连接mycat的相关配置，现有的事务方式对mycat不支持

### ISSUE THREAD

**Issue by zhhaanngg123** [ctripcorp/apollo#1501]
如题。。。

**Comment by zhhaanngg123** [comment]
我这边实现了一种方式。
在configservice和adminservice的Application启动类加上
@EnableJpaRepositories(basePackages = "com.ctrip.framework.apollo.biz", enableDefaultTransactions = false)
的注解，来关闭jpa的默认事务，同时要保留显式的声明事务注解@Transactional

**Comment by nobodyiam** [comment]
是mycat不支持jpa的事务方式？

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by kayleyang** [comment]
在使用mycat时需要关闭spring-data-jpa默认的事务管理机制. 
原因如下:
mycat对于开启了事务的查询,插入等操作,都会走主库
spring-data-jpa默认的事务管理机制对查询操作执行的是只读事务,只读事务mycat认为也是事务，
在我的一个[issue](https://github.com/ctripcorp/apollo/issues/2018)里也是这个原因，因为com.ctrip.framework.apollo.biz.service.ItemService.update没有显式的声明事务注解@transactional

**Comment by nobodyiam** [comment]
这个感觉是mycat特殊的逻辑了，apollo就是一个普通的spring jpa程序，可以查询一下相关的配置方式
