### ISSUE TITLE
多个项目中使用，有一个项目始终读到默认值

### ISSUE THREAD

**Issue by tianguangshu** [ctripcorp/apollo#1503]
多个项目使用，采用spring注解模式，
有一个始终读到默认值，其他正常
能否提供一下排查思路。

@EnableApolloConfig
@Value
 @ApolloJsonValue

**Comment by nobodyiam** [comment]
一般是由于配置原因导致没有加载到配置，可以看一下客户端日志是否有异常

也可以调试一下`com.ctrip.framework.apollo.spring.config.PropertySourcesProcessor#initializePropertySources`方法，看看是否跑到了。

**Comment by tianguangshu** [comment]
跑到了，
每次变更新的配置后，@ApolloJsonValue的set方法也能进去，但是value 是默认值。

**Comment by tianguangshu** [comment]
客户端日志没有异常

**Comment by tianguangshu** [comment]
https://github.com/ctripcorp/apollo/blob/5440572b027091a580b5192ef4d7d3b35b5e43bc/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/property/PlaceholderHelper.java#L34
这一行的值就不对了。。。

**Comment by nobodyiam** [comment]
随便找一个bean，注入一下`Environment`，然后看environment里面的propertySources，是不是在apollo之前还有其它的配置源？

另外，也可以看看是不是和这个类似：#1463

**Comment by tianguangshu** [comment]
![image](https://user-images.githubusercontent.com/29251231/45947930-9ec90880-c028-11e8-9f04-e447da837d04.png)

**Comment by tianguangshu** [comment]
apollo 是在第一个

**Comment by nobodyiam** [comment]
这个看上去是正确的，因为apollo的property source已经注入进去了，可以看一下里面的配置是不是都有了。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
