### ISSUE TITLE
关于配置实时生效的问题

### ISSUE THREAD

**Issue by huihui1112** [ctripcorp/apollo#1504]
因为之前自己直接修改数据源呀  日志级别啊  zookeeper这些属性时 发现配置没有实时产生变化.像日志这种 我就自己做了代码处理. 但是最近需要培训第一批接入配置中心的开发人员 我这边需要彻底弄清楚哪些配置会生效  哪些配置不会生效......心里没底啊.
跟某个大神朋友讨论 说  可能是基于配置实现的功能需要手动处理.
但我还是想过来听下 贵团队的意见.....   想知道不会生效的配置的准确范围

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
