### ISSUE TITLE
Portal登录异常

### ISSUE THREAD

**Issue by uncarman2017** [ctripcorp/apollo#1507]
按分布式部署service，五个环境共用一个portal, portal登陆时报如下异常，请问原因。
{
    "exception": "org.springframework.web.HttpRequestMethodNotSupportedException",
    "message": "Request method 'POST' not supported",
    "status": 400,
    "timestamp": "2018-09-22T20:22:20.366"
}

**Comment by uncarman2017** [comment]
是portal登录页，按了登录后服务端返回这个json格式异常

**Comment by nobodyiam** [comment]
后端有异常堆栈吗？

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
