### ISSUE TITLE
删除公共命名空间的异常

### ISSUE THREAD

**Issue by jimiyi** [ctripcorp/apollo#1510]
今天我在一个应用A上删除了公共的Namespace，然后再另一个应用B上，创建同名的公共Namespace，提示创建不了，提示APPNamespace已经存在，我看了下表的数据，Namespace里关于那个公共配置isDelete已经至成了1，但是appNamespace表里那个公共配置isDelete还是0

**Comment by nobodyiam** [comment]
在应用上删除的是namespace，一个关联的对象，如果需要删除app namespace，需要通过管理员工具

![image](https://user-images.githubusercontent.com/837658/46016921-c394ad00-c108-11e8-8c51-df70a943d9f4.png)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
