### ISSUE TITLE
同一个环境下，如何对apollo-config-service, apollo-admin-service做实例冗余？

### ISSUE THREAD

**Issue by hepyu** [ctripcorp/apollo#1512]
RT, 为了apollo的可用性，我理解每个环境都应该至少有2个实例（最好3个），比如当一个config-service挂了，还有另个一冗余提供服务；admin-server同理。
我理解apollo本身也应该有个集群的概念来保证其自身的可用性吧。

我看了下文档和相关代码，貌似apollo目前只能是每个环境一个admin和config。怎么实现上述的场景呢？

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
