### ISSUE TITLE
本地缓存加载顺序保证不了

### ISSUE THREAD

**Issue by honghuliu** [ctripcorp/apollo#1516]
你好，我发现本地缓存的文件没有进行排序？好多同类的文件分布比较混乱？还有就加载的顺序也没能保证。
例如：shiro.filter-chains是一个LinkHashMap,我的配置项
`    private Map<String, String> filterChains = new LinkedHashMap<String, String>();
`
`spring.datasource....`
`spring.datasource....`
`spring.datasource....`
`shiro.filter-chains[/xxx1/**]=anon`
`shiro.filter-chains[/xxx2/**]=anon`
`shiro.filter-chains[/xxx3/**]=anon`
`shiro.filter-chains[/xxx4/**]=anon`
`shiro.filter-chains[/**]=authc`
本地磁盘顺序就乱了
`shiro.filter-chains[/xxx3/**]=anon`
`spring.datasource....`
`shiro.filter-chains[/xxx1/**]=anon`
`spring.datasource....`
`shiro.filter-chains[/xxx4/**]=anon`
`spring.datasource....`
`shiro.filter-chains[/xxx1/**]=anon`
`shiro.filter-chains[/**]=authc`
加载到filterChains的顺序也是无序的
目前解决的方案把
filter-chains转化成了数组了

**Comment by honghuliu** [comment]
shiro.filter-chains[/xxx1/**] = anon
shiro.filter-chains[/xxx2/**] = anon
shiro.filter-chains[/xxx3/**] = anon
shiro.filter-chains[/**] = authc

**Comment by honghuliu** [comment]
`shiro.filter-chains[/xxx1/**] = anon
shiro.filter-chains[/xxx2/**] = anon
shiro.filter-chains[/xxx3/**] = anon
shiro.filter-chains[/**] = authc`

**Comment by honghuliu** [comment]
建议支持yml

**Comment by nobodyiam** [comment]
spring的property source本来就没有顺序，或者说也不需要顺序的，建议配置和顺序解耦

**Comment by honghuliu** [comment]
> spring的property source本来就没有顺序，或者说也不需要顺序的，建议配置和顺序解耦

嗯嗯，谢谢
