### ISSUE TITLE
spring cloud 版本升级

### ISSUE THREAD

**Issue by sx1436431264** [ctripcorp/apollo#1520]
是否 兼容更高版本的spring cloud config和eureka

**Comment by nobodyiam** [comment]
apollo客户端对spring cloud版本没有要求

**Comment by sx1436431264** [comment]
感谢回复，我理解apollo-configservice 和 apollo-adminservice apollo-client直接更改pom文件中的spring-cloud版本号到2.1.0就可以了是把？

**Comment by sx1436431264** [comment]
我试了一下configservice和adminservice都无法升级到2.0.1.RELEASE

**Comment by nobodyiam** [comment]
apollo服务端如果要升级的话，建议看一下spring cloud的升级文档和注意事项

**Comment by nobodyiam** [comment]
apollo服务端已经升级spring boot到2.0.5，spring cloud到Finchley.SR1，详情参见 #1527

**Comment by nobodyiam** [comment]
1.1.0版本已经发布，apollo服务端已经升级spring boot和spring cloud到最新版本，更多信息可以参考： https://github.com/ctripcorp/apollo/releases/tag/v1.1.0
