### ISSUE TITLE
外网无法拉取服务器上apollo信息的问题

### ISSUE THREAD

**Issue by shicanLeft** [ctripcorp/apollo#1537]
服务器上搭建了apollo ，本地可以访问到公网暴露的3个服务【8070 8080 8090 】<---使用服务器公网IP.,

问题：本地使用springboot项目 去拉取apollo配置中心的信息时，发现会去请求服务器内网ip的8080 服务。
因为是请求内容  响应time out ，无法读取到服务器上apollo的配置信息，请问要怎么解决

**Comment by nobodyiam** [comment]
[分布式部署指南#14网络策略](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#14%E7%BD%91%E7%BB%9C%E7%AD%96%E7%95%A5)

![image](https://user-images.githubusercontent.com/837658/46581203-18b8b300-ca67-11e8-9ceb-468e6b317ae3.png)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
