### ISSUE TITLE
启动时出现问题

### ISSUE THREAD

**Issue by chenghao520kyr** [ctripcorp/apollo#1538]
本地启动appllo-configserver项目时会出现pid - 2864 just quit unexpectedly, please check logs under /opt/logs/100003171 and /tmp for more information!
!，大神知道是什么原因吗？

**Comment by chenghao520kyr** [comment]
![problem](https://user-images.githubusercontent.com/40078342/46591908-9f65a280-caf0-11e8-92e9-9bf1f90e0e0c.jpg)

**Comment by nobodyiam** [comment]
pid - 2864 just quit unexpectedly, please check logs under /opt/logs/100003171 and /tmp for more information!

这句话提示很清楚了，到这两个路径下看看有没有日志信息

**Comment by CaseyGit** [comment]
你好，请问怎么解决的呀

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by Hackcr** [comment]
> 本地启动appllo-configserver项目时会出现pid - 2864 just quit unexpectedly, please check logs under /opt/logs/100003171 and /tmp for more information!
> !，大神知道是什么原因吗？

怎么处理的？日志都没打出来。也不晓得原因。

**Comment by nobodyiam** [comment]
@Hackcr /opt/logs/100003171 and /tmp 这两个目录下应该有的

**Comment by chenm1xuexi** [comment]
是如何解决的

**Comment by hwangqf** [comment]
如何解决的附上方案

**Comment by KaiwenSu-Kelvin** [comment]
> 已成功，谢谢大神

你好，请问可以说下是如何解决的吗，谢谢~
