### ISSUE TITLE
请教一个问题，公共namespace获取时，一直404。我是.net客户端

### ISSUE THREAD

**Issue by thicktao** [ctripcorp/apollo#1539]
1、私有namespace : http://192.168.50.42:8080/configs/realtimeservice/dev/application?ip=192.168.50.104 可以正常访问；
2、公共namespace: http://192.168.50.42:8080/configs/realtimeservice/dev/redis?ip=192.168.50.104 一直报404错误

错误如下：
[Error,9,2018/10/8 14:59:57:897]->Com.Ctrip.Framework.Apollo.Exceptions.ApolloConfigStatusCodeException: [status code: 404] Could not find config for namespace - appId: realtimeservice, cluster: dev, namespace: redis, please check whether the configs are released in Apollo!

![apollo](https://user-images.githubusercontent.com/40555417/46595468-1b6ce400-cb0b-11e8-8ea6-38b30a1575a9.png)

**Comment by nobodyiam** [comment]
从你的截图中没看到名为redis的公共namespace啊？

**Comment by thicktao** [comment]
![image](https://user-images.githubusercontent.com/40555417/46639961-d5ac2c00-cb9b-11e8-9337-c57669cc494c.png)
不好意思，截图未截完整哈，两个公共namespace，都是404.

**Comment by nobodyiam** [comment]
这个是部门前缀，在1.1.0版本是可以选择不自动加这个前缀的

**Comment by thicktao** [comment]
Ok 我试试

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
