### ISSUE TITLE
springboot中集成apollo，用注解的方式无法统一设置，要多处设置命名空间

### ISSUE THREAD

**Issue by linsongze** [ctripcorp/apollo#1541]
@ApolloConfig
  @ApolloConfigChangeListener
  @EnableApolloConfig

    这三个注解都必须要指定namespace（默认是application），然而java里面没有办法用数组做常量，这样，一旦改动ns，就要一起改三个地方，，，，
有没有办法可以统一配置的。

**Comment by nobodyiam** [comment]
目前没有很好的办法，不过如果用了spring的话，@ApolloConfig一般就用不着了吧，@ApolloConfigChangeListener用的场景一般也比较有限的，不太需要监听所有namespace的配置变化吧？

**Comment by linsongze** [comment]
@EnableApolloConfig(value={"a","b"}),同样的，我也需要监控a,b两个地方进行变更。。现实使用，应该很少有初始化的时候读a/b两个配置，，，然后只需要变更b的吧。。。除非a的配置都是需要重启应用才能够生效的。。

**Comment by linsongze** [comment]
其实建议吧，，可以在ApolloConfigRegistrar之前通过类似于System.properties的形式让用户注入apollo的默认NS,如果没有注入的，才用application....毕竟NS 在一个项目里面写好几个地方，，忘记改了还是很蛋疼的，能够统一比较理想。

**Comment by nobodyiam** [comment]
恩，很好的建议，我们考虑一下
