### ISSUE TITLE
spring cloud eureka client 心跳服务停止了  在调用刷新方法之后refreshScope.refresh

### ISSUE THREAD

**Issue by xjr100419** [ctripcorp/apollo#1544]
spring cloud version Dalston.SR4
apollo client 0.11.0
业务服务 正常注册到 eureka  
但在 监听ApolloConfigChangeListener事件 里面调用刷新 方法后 refreshScope.refresh
业务服务跟eureka的 心跳就停止了DiscoveryClient

**Comment by xjr100419** [comment]
换成refreshScope.refreshAll(); 就没有这个问题了。

**Comment by nobodyiam** [comment]
是eureka地址变了需要刷新？

**Comment by xjr100419** [comment]
`10:09:39.861 [DiscoveryClient-CacheRefreshExecutor-0] DEBUG c.n.d.s.t.j.AbstractJerseyEurekaHttpClient - Jersey HTTP GET http://localhost:6006/eureka//apps/delta?; statusCode=200
10:09:39.861 [DiscoveryClient-CacheRefreshExecutor-0] DEBUG c.netflix.discovery.DiscoveryClient - Got delta update with apps hashcode UP_1_
10:09:39.861 [DiscoveryClient-CacheRefreshExecutor-0] DEBUG c.netflix.discovery.DiscoveryClient - Added instance GZ-PC-0103:gateway:4000 to the existing apps in region null
10:09:39.861 [DiscoveryClient-CacheRefreshExecutor-0] DEBUG c.netflix.discovery.DiscoveryClient - The total number of instances fetched by the delta processor : 1
10:09:39.861 [DiscoveryClient-CacheRefreshExecutor-0] DEBUG c.netflix.discovery.DiscoveryClient - The total number of all instances in the client now is 1
10:09:39.861 [DiscoveryClient-CacheRefreshExecutor-0] DEBUG c.netflix.discovery.DiscoveryClient - Completed cache refresh task for discovery. All Apps hash code is Local region apps hashcode: UP_1_, is fetching remote regions? false 
`

eureka地址没变  是DiscoveryClient 的定时心跳服务停了  没发去获取新的注册信息

**Comment by xjr100419** [comment]
额 我用项目提供的demo 来改造一下添加eureak注册 也没问题。
我自己看看 哪里问题吧

**Comment by nobodyiam** [comment]
看看是不是引用了spring-boot-devtools

**Comment by xjr100419** [comment]
应该是  spring cloud 版本问题
https://github.com/spring-cloud/spring-cloud-netflix/issues/3223
