### ISSUE TITLE
实例列表时间更新问题

### ISSUE THREAD

**Issue by shanjingheng** [ctripcorp/apollo#1545]
默认显示的是DataChange时间大于一天前的,想知道在调用哪个接口时会更新InstanceConfig的DataChange时间，调用long polling的接口和获取配置的接口我看都没有更新时间。

**Comment by nobodyiam** [comment]
可以看下[InstanceConfigAuditUtil.audit](https://github.com/ctripcorp/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/util/InstanceConfigAuditUtil.java#L61)逻辑。
