### ISSUE TITLE
公共命名空间里的值被修改后不能自动更新

### ISSUE THREAD

**Issue by hepyu** [ctripcorp/apollo#1550]
RT。

如下图：
caf.logger.default是关联的一个公共空间，这个公开空间定义了所有的logger的默认日志级别。
图1-图标3，初始化可以获取到公共空间里的定义。
但是当把公共空间里的某项修改后（图2），无法触发图标4的ApolloConfigChangeListener。这是为何呢？
我看apollo-client的代码，应该也支持啊（图3），还是我用的有问题呢？

图1
![image](https://user-images.githubusercontent.com/3917749/46737702-c7aaf800-ccce-11e8-81c8-956168a38172.png)

图2
![image](https://user-images.githubusercontent.com/3917749/46737823-19538280-cccf-11e8-91ef-5156389f6043.png)

图3
![image](https://user-images.githubusercontent.com/3917749/46737993-8535eb00-cccf-11e8-9218-11296df38fc3.png)

**Comment by hepyu** [comment]
我启用了3个configservice，会不会是不同的configservice的本地cache不一致？造成long-polling失误？

**Comment by nobodyiam** [comment]
配置修改发布后一定会通知到客户端的（除非日志中有报错信息），然后客户端会计算配置是否有变化，如果变了才会触发onChange。

可以在图3的61行加个断点看看，如果没进来的话，可以打开客户端的DEBUG级别日志看看。

**Comment by hepyu** [comment]
好，我调一下。

还有一个问题，我启用3个configservice，当我关闭2个后，应用程序经常报long polling failed(timeout)，我看代码这里是简单随机取configservice，如图1。这里以后会考虑client做容错么。
我的启动方式是图2.

图1：
![image](https://user-images.githubusercontent.com/3917749/46776281-7a19a400-cd3d-11e8-912b-3387595381f8.png)

图2：
![image](https://user-images.githubusercontent.com/3917749/46776303-91589180-cd3d-11e8-8023-3e65398ee93a.png)

**Comment by hepyu** [comment]
> 配置修改发布后一定会通知到客户端的（除非日志中有报错信息），然后客户端会计算配置是否有变化，如果变了才会触发onChange。
> 
> 可以在图3的61行加个断点看看，如果没进来的话，可以打开客户端的DEBUG级别日志看看。

现在不出现了（可能是因为之前我全部重启configservice了），再出现时，我会这样调试下。

**Comment by nobodyiam** [comment]
客户端的容错方式是重试，有问题的服务实例拉出是依靠定期的从meta server拉取服务列表
