### ISSUE TITLE
apollo portal

### ISSUE THREAD

**Issue by FANHIDE** [ctripcorp/apollo#1551]
用kubernetes部署apollo。
其中admin-service的地址为：ip:32310
        config-service的地址为：ip:30002

![image](https://user-images.githubusercontent.com/29531967/46738937-fc6c7e80-ccd1-11e8-9a13-3ad376a35dc7.png)

在eureka中已经看到adminservice和config service注册成功
![image](https://user-images.githubusercontent.com/29531967/46739086-51a89000-ccd2-11e8-83ae-f38d78f5dc94.png)
![image](https://user-images.githubusercontent.com/29531967/46739108-5d945200-ccd2-11e8-8403-83ee85fdbf73.png)
但是，在portal中打开时，会提示
![image](https://user-images.githubusercontent.com/29531967/46739212-99c7b280-ccd2-11e8-9e5a-e3e5c06a75c9.png)
打开portal的pod，报错信息如下：
![image](https://user-images.githubusercontent.com/29531967/46739290-c8458d80-ccd2-11e8-9dfb-90f9e69839e0.png)
请问应该如何解决？
另外，是否能够支持注册中心为zookeeper?

**Comment by nobodyiam** [comment]
看上去是portal请求admin service失败了，看看连通性吧

注册中心可以替换为zookeeper，接入后修改[DiscoveryService](https://github.com/ctripcorp/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/metaservice/service/DiscoveryService.java)实现即可

**Comment by FANHIDE** [comment]
在portal中telnet admin service，确实是连不通的。是通过nodeport开放的admin service的端口，这个连不通有可能是什么原因？

**Comment by nobodyiam** [comment]
这个要看看具体的网络策略了
