### ISSUE TITLE
配置中包含placeholder无法自动更新

### ISSUE THREAD

**Issue by jieqian** [ctripcorp/apollo#1552]
### step1: 创建2个配置，其中一个配置的值用placeholder依赖另外一个配置，比如:
key | value
------------ | ------------
var.env | dev
url | http://${var.env}.xxx.com

### step2: 客户端使用@value来获取配置的代码:
BizConfig.class
```java
@Configuration
@EnableApolloConfig
public class BizConfig {
    @Bean
    public BizConfigValue bizConfigValue(){
        return new BizConfigValue();
    }
}
```

BizConfigValue.class
```java
@Data
public class BizConfigValue {
    @Value("${url:http://sandbox.xxx.com}")
    private String url;
}
```

ApplicationController.class
```java
...
    @Autowired
    private BizConfigValue bizConfigValue;

    @RequestMapping(value="/test", method=RequestMethod.GET)
    public String apolloTest() {
        return bizConfigValue.getUrl();
    }
...
```
启动服务，并在浏览器输入http://localhost:8080/test
输出的内容为http://dev.xxx.com

### step3: 修改env的配置并发布:
key | value
------------ | ------------
var.env | qa
url | http://${env}.xxx.com

此时再在浏览器输入http://localhost:8080/test
输出的内容还是http://dev.xxx.com

**Comment by nobodyiam** [comment]
嵌套property由于需要在运行时扫描`@Value`得到关联的配置项，所以需要在配置项里面包含引用的key才行，比如`@Value("${${someKey}.${anotherKey}}")`，这个在`someKey`和`anotherKey`变化时都会重新注入。

你的例子中，从`@Value("${url:http://sandbox.xxx.com}")`是找不到关联的配置项的。

**Comment by jieqian** [comment]
恩，昨天我也看源码了，springValueRegistry需要一上来把所有的key注册一遍，所以改成@Value("${url:http://${var.env}.xxx.com}")就可以了

**Comment by JerryPlayer** [comment]
这个有办法用一条apollo配置实现不？

**Comment by JerryPlayer** [comment]
> 这个有办法用一条apollo配置实现不？
可以通过取巧方式实现：@value("${http:http://${var.env}.xxx.com}")
这样url就不需要在apollo上配置了，同时要求在apollo上不存在key是http的配置。
这样取不到key为http的配置，默认为"",从而实现该功能。当然http可以换成任意字符，只要apollo上不存在就可以
