### ISSUE TITLE
更改了zk地址，没有实时生效

### ISSUE THREAD

**Issue by nautLiu** [ctripcorp/apollo#1559]
更改了生产环境的zookpeer地址，配置没有实时生效

**Comment by nobodyiam** [comment]
是的，配置中心能保证的是配置推送到应用程序，对于一些需要初始化的场景（比如数据库连接、redis连接、zk连接等），是需要额外的逻辑来实现热切换的，可以参考一下[apollo-use-cases](https://github.com/ctripcorp/apollo-use-cases)
