### ISSUE TITLE
apollo目前支持配置变量吗（嵌套变量）？

### ISSUE THREAD

**Issue by lin1658** [ctripcorp/apollo#1567]
Jason 您好，我直接说吧，举个栗子：
JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.55.x86_64 

CLASSPATH=$JAVA_HOME/lib/tools.jar 

apollo client：拿到的CLASSPATH=/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.55.x86_64/lib/tools.jar

目前apollo是否有类似的功能？

**Comment by nobodyiam** [comment]
apollo api方式不支持，不过如果你是和spring一起用的话是支持的，可以参考一下[UT代码](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/test/java/com/ctrip/framework/apollo/spring/JavaConfigPlaceholderAutoUpdateTest.java#L517)

**Comment by lin1658** [comment]
thx a lot
