### ISSUE TITLE
Will Apollo consider an empty value "" as DELETED?

### ISSUE THREAD

**Issue by chickenlj** [ctripcorp/apollo#1569]
ADDED,
MODIFIED,
DELETED;

**Comment by nobodyiam** [comment]
No, DELETED means the key is GONE in Apollo, see [AbstractConfig. calcPropertyChanges](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/AbstractConfig.java#L470).

A key with empty value "" will not be treated as DELETED.

**Comment by chickenlj** [comment]
Got it, thanks for the reply.
