### ISSUE TITLE
关于长轮询能否改成mqtt通讯方式

### ISSUE THREAD

**Issue by sx1436431264** [ctripcorp/apollo#1570]
您好,目前这种长论询和定时拉取方式可否改成mqtt的方式
1.mqtt方式存在幂等性无法保证的问题?
2.mqtt单节点服务支持的客户端数量会更多?

**Comment by nobodyiam** [comment]
长连采用HTTP而非TCP的主要考虑点是多语言的适配，另外目前一般的公司机器规模也不太会达到百万级别，所以没有啥必要切换到mqtt方式。

采用异步servlet，单机可以支撑1W个连接，也就是一万个客户端。

**Comment by sx1436431264** [comment]
明白了，感谢！
