### ISSUE TITLE
如何确认修改的配置已经被客户端同步了呢？

### ISSUE THREAD

**Issue by otyyyywangwenbin** [ctripcorp/apollo#1574]
如何确认修改的配置已经被客户端同步了呢？在config service里日志里没有看到相关信息，需要在客户端监听的时候自己记日志吗？

**Comment by nobodyiam** [comment]
1. namespace的实例列表可以看到
2. 客户端也有监控打点，不过前提是tracer实现接入了你们自己的监控系统

**Comment by otyyyywangwenbin** [comment]
OK，看到了，谢谢！
![image](https://user-images.githubusercontent.com/6299773/47138217-5fba6a00-d2eb-11e8-8050-299b199e55c5.png)
