### ISSUE TITLE
sso实现portal用户登陆

### ISSUE THREAD

**Issue by randomSpirit** [ctripcorp/apollo#1575]
`{"timestamp":"2018-10-17T12:04:08.538+0800","status":405,"error":"Method Not Allowed","message":"Request method \u0027POST\u0027 not supported","path":"/"}`
sso验证后是通过POST跳转回来的，apollo这边能在哪配置支持post么？ @nobodyiam

**Comment by randomSpirit** [comment]
`DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported]`

**Comment by randomSpirit** [comment]
`HandlerMapping： WelcomePageHandlerMapping
HandlerExecutionChain：ParameterizableViewController
HandlerAdapter：SimpleControllerHandlerAdapter
`
![default](https://user-images.githubusercontent.com/7530593/47071610-8b275100-d226-11e8-9759-fa61b5310e44.png)

**Comment by randomSpirit** [comment]
找到原因了，因为PortalApplication用了@EnableAutoConfiguration注解。
1. spring-boot-autoconfigure自带WelcomePageHandlerMapping
2. DispatcherServlet初始化的时候将WelcomePageHandlerMapping加入了HandlerMapping。而doDispatch的时候匹配到了WelcomePageHandlerMapping。
3. ParameterizableViewController是WelcomePageHandlerMapping的rootHandler，ParameterizableViewController的supportedMethods只支持GET和HEAD，所以处理时报错。

现在在看有没有什么解决方法

**Comment by randomSpirit** [comment]
> 
> 
> SSO跳回来用POST貌似也是挺罕见的。。

今天试了一天，除了暴力redirect，没找到解决办法……
把自带的/signin改成post也不支持，是因为security的原因么 @nobodyiam

**Comment by randomSpirit** [comment]
我新写的处理器映射支持方法加上了POST，能转发到静态资源，但是资源处理器ResourceHttpRequestHandler没法重写了。最后还是用redirect吧……

对了sso过来post我猜是因为forward过来的，为了保留参数啥的，所以sso登陆是post，过来也是post了。

给后来人留个参考资料吧：
https://blog.afnf.net/blog/50

http://thecoderider.com/one-more-reason-for-spring-mvc-http-status-405-request-method-post-not-supported/

`    @Bean
    public SimpleUrlHandlerMapping simpleUrlHandlerMapping() {
        SimpleUrlHandlerMapping handlerMapping = new SimpleUrlHandlerMapping();
        ParameterizableViewController controller = new ParameterizableViewController();
        controller.setSupportedMethods("GET", "POST", "HEAD");
        controller.setViewName("forward:index.html");
        handlerMapping.setRootHandler(controller);
        handlerMapping.setOrder(1);
        return handlerMapping;
    }`

**Comment by wujun234** [comment]
抱歉，6年前的记忆已丢失了，试试问AI吧😂
