### ISSUE TITLE
configservice的生产环境服务器  执行lsof -i:8080命令 发现了大量的进程 连接状态为CLOSE_WAIT

### ISSUE THREAD

**Issue by huihui1112** [ctripcorp/apollo#1577]
![image](https://user-images.githubusercontent.com/30152557/47066341-51e7e480-d218-11e8-886a-5f177e7218d5.png)
情况如下 生产环境只有两台configservice服务器  但是其中一台不知道为什么出了意外.  线上目前没连几个应用. 报了这个错 我也很纳闷.  把服务杀掉重启后  目前正常.  但是出现这种大量CLOSE_WAIT的状况  想来这边求解...

**Comment by nobodyiam** [comment]
看看172.21.7.58和172.21.7.59是什么机器？

**Comment by huihui1112** [comment]
> 看看172.21.7.58和172.21.7.59是什么机器？
两台阿里云预生产的虚拟机   做订单功能的.  线上配置中心暂时没接几个应用呢...

**Comment by nobodyiam** [comment]
看上去是这两台机器建了很多连接到8080端口

**Comment by huihui1112** [comment]
是啊. 我以为你们这边可能发生过这样的问题 那这样的话 没办法 应用杀了后 重启也没这毛病.

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
