### ISSUE TITLE
【各个环境的mete_server信息是否支持手动配置】

### ISSUE THREAD

**Issue by sunnyvinson** [ctripcorp/apollo#1578]
![image](https://user-images.githubusercontent.com/13216698/47077551-c714e300-d233-11e8-8c6b-15aec68fdee0.png)
现在环境列表支持了界面上更新环境列表，是否考虑meta server地址的更新也实现界面操作呢？

**Comment by nobodyiam** [comment]
恩，环境这块后续是要整一下，主要是由于添加环境的操作频率非常低，所以之前就直接手工搞定了

**Comment by nobodyiam** [comment]
恩，后续需要考虑一下
