### ISSUE TITLE
有没有官方的 docker 镜像，以及 helm chart ？

### ISSUE THREAD

**Issue by kaelzhang** [ctripcorp/apollo#1579]
安装最快的办法还是 `helm install` 了，不知道宋老板有没有计划搞一个。

顺便再搞个官方的 helm charts repo 服务

不过这个也要求 apollo 能够支持基础启动设置从环境变量中读取（k8s 风格），可能需要对项目进行一些改造。

**Comment by nobodyiam** [comment]
目前是提供了基本的Dockfile和部署脚本，可以参考一下[Docker部署](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#15-docker%E9%83%A8%E7%BD%B2)和[Kubernetes支持](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#16-kubernetes%E6%94%AF%E6%8C%81)。

helm chart还没研究过。。。有兴趣提个PR协助一下吗？:-)

**Comment by qct** [comment]
@kaelzhang https://github.com/qct/apollo-helm

最近正在推动k8s改造，顺便写了个chart。

**Comment by nobodyiam** [comment]
@qct 

非常感谢，不知是否可以在wiki上加个链接到 https://github.com/qct/apollo-helm ?

**Comment by qct** [comment]
@nobodyiam 当然可以  :smile:

**Comment by nobodyiam** [comment]
@qct 

非常感谢，[wiki](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#16-kubernetes%E6%94%AF%E6%8C%81)已添加。
