### ISSUE TITLE
这边有开发人员配置spring bean中的某个属性的时候 用的数组 

### ISSUE THREAD

**Issue by huihui1112** [ctripcorp/apollo#1581]
![image](https://user-images.githubusercontent.com/30152557/47146174-19223b00-d2fe-11e8-8ee2-75e8524f17a4.png)
但是我这样配置的话 是没用的... 
不知道你们研发人员  之前有考虑到这种情况吗.... 
还是说 得自己在初始化的 把字符串解析成数组....

**Comment by nobodyiam** [comment]
这个完全是spring的配置方式，和apollo没关系的，如果不生效的话，查一下spring的相关文档吧

**Comment by huihui1112** [comment]
嗯 明白.

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
