### ISSUE TITLE
支持服务端解析引用变量吗?

### ISSUE THREAD

**Issue by hobo212** [ctripcorp/apollo#1582]
在service1的application中有a=1 x=${c},并引用了公共namespace PUB.COMMON c=3;
请问能不能在服务器端就将x解析完成,再发给客户端,并且可以在portal中看到引用的value?

**Comment by nobodyiam** [comment]
目前不支持在服务端解析，因为这个需要结合客户端实际的cluster，灰度等信息才可以计算的。

客户端如果使用spring的话，是支持引用变量的。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
