### ISSUE TITLE
关于apollo长连接报错的问题请教一下

### ISSUE THREAD

**Issue by linrol** [ctripcorp/apollo#1583]
![image](https://user-images.githubusercontent.com/18043615/47193939-f177b500-d387-11e8-8d9a-7f717770f48d.png)
一直在报长连接错误的问题，想问一下这个是因为什么原因造成的

**Comment by nobodyiam** [comment]
日志最后有具体的错误信息的

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
