### ISSUE TITLE
【功能建议】 建议增加通过文件配置eureka地址

### ISSUE THREAD

**Issue by inix** [ctripcorp/apollo#1584]
版本：V1.1.0

eureka地址部署成功之后，需要手动修改数据库内的配置；
能否增加通过文件的方式去修改，在kubernetes集群部署的时候可以通过configMap的方式修改。

**Comment by nobodyiam** [comment]
eureka.service.url是支持-D参数修改的，configMap可以转换为-D参数吗？

通过文件修改貌似和改数据库也没啥区别。

**Comment by inix** [comment]
kuberntes 有一键安装的包管理器 Helm Chart，目前我正在把项目中的yaml文件编写转化成helm chart 一键安装包。
需要注册的 eureka.service.url地址，可以通过模板文件写好对应地址，通过配置文件ConfigMap方式挂载到文件，这样方便很多。可以实现真正的一键安装。

**Comment by nobodyiam** [comment]
eureka.service.url也支持通过Spring的配置文件方式配置的，比如application.properties

**Comment by inix** [comment]
@nobodyiam 
你好，我详细看了文档，`meta service` 有详细的配置步骤和查找步骤，在这里有描述 [apollo meta server](https://github.com/ctripcorp/apollo/wiki/Java客户端使用指南#122-apollo-meta-server)。
请问 `eureka.service.url` 的规则跟`meta service url`的也是一样的吗？

**Comment by nobodyiam** [comment]
`eureka.service.url`不太一样，应该说是简化了很多，具体可以看一下 [BizConfig](https://github.com/ctripcorp/apollo/blob/master/apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/config/BizConfig.java#L47)，它本质上是从spring的environment中获取的，所以支持所有spring支持的配置方式，同时也支持从apollo config db的serverconfig方式，因为有 [BizDBPropertySource](https://github.com/ctripcorp/apollo/blob/master/apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/service/BizDBPropertySource.java)

**Comment by inix** [comment]
@nobodyiam 
你好，感谢提醒，经过测试，根据[kuberntes的安装过程](https://github.com/ctripcorp/apollo/blob/master/scripts/apollo-on-kubernetes/README.md)，我写到 admin server和config server的application-github.properties文件里，跟数据库连接配置放在一起。目前经过测试，可以正常注册服务。

文件 `/apollo-admin-server/application-github.properties`:
```bash
spring.datasource.url = ...
spring.datasource.username = ... 
spring.datasource.password = ...
eureka.service.url = http://invincible-markhor-statefulset-config-server-dev-0.invincible-markhor-service-meta-server-dev.sre:8080/eureka,http://invincible-markhor-statefulset-config-server-dev-1.invincible-markhor-service-meta-server-dev.sre:8080/eureka,http://invincible-markhor-statefulset-config-server-dev-2.invincible-markhor-service-meta-server-dev.sre:8080/eureka
```

文件 `/apollo-config-server/application-github.properties `：
```bash
spring.datasource.url = ...
spring.datasource.username = ... 
spring.datasource.password = ...
eureka.service.url = http://invincible-markhor-statefulset-config-server-dev-0.invincible-markhor-service-meta-server-dev.sre:8080/eureka,http://invincible-markhor-statefulset-config-server-dev-1.invincible-markhor-service-meta-server-dev.sre:8080/eureka,http://invincible-markhor-statefulset-config-server-dev-2.invincible-markhor-service-meta-server-dev.sre:8080/eureka
```
