### ISSUE TITLE
目前好像yml支持不太好

### ISSUE THREAD

**Issue by AndyMocan** [ctripcorp/apollo#1585]
和springboot集成什么时候支持yml配置目前好像只支持properties

**Comment by nobodyiam** [comment]
yml只是一个展现形式，在spring boot内部还是转成kv形式使用的。

之前也有一些用户提过这个需求，后续会考虑在界面上提供一个类似目前文本模式的方式。

**Comment by nobodyiam** [comment]
我新开了一个PR #1944，支持yml类型的namespace注入到Spring中去，大家可以看一下~

**Comment by nobodyiam** [comment]
[1.3.0](https://github.com/ctripcorp/apollo/releases/tag/v1.3.0)版本已经发布，支持了Yml/Yaml格式的namespace和Spring/Spring Boot集成。
