### ISSUE TITLE
本地开发可不可以关闭apollo注册中心呀

### ISSUE THREAD

**Issue by neatlife** [ctripcorp/apollo#1587]
开发走本地的application.properties配置，但是apollo配置中心还是会尝试去连接配置中心，导致本地启动比较慢，有没有参数可以在启动时关闭apollo配置中心呀

**Comment by nobodyiam** [comment]
参考一下[本地开发模式](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#%E4%BA%94%E6%9C%AC%E5%9C%B0%E5%BC%80%E5%8F%91%E6%A8%A1%E5%BC%8F)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
