### ISSUE TITLE
单机部署外网无法访问

### ISSUE THREAD

**Issue by gnsilence** [ctripcorp/apollo#1588]
在百度云服务器上放着，外网在浏览器访问没有问题，在.Net客户端一直访问显示的是云服务器的内网，无法获取namespace，需要改哪里的配置吗，已经试过将各个服务，数据库都改为外网ip，还是无法访问

**Comment by nobodyiam** [comment]
参考一下[网络策略](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#14%E7%BD%91%E7%BB%9C%E7%AD%96%E7%95%A5)

**Comment by zouyx** [comment]
@gnsilence 应该是需要制定对应网卡的ip，如果全网卡可以0.0.0.0

* 配置0.0.0.0

按照运维标准来说，会发生以下两种情况

1.运维不允许

2.不给覆盖外网网卡

* 配置生产内网ip

通过反向代理进来

运维应该是推荐这种操作。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
