### ISSUE TITLE
提供的演示环境不可用

### ISSUE THREAD

**Issue by 267443698** [ctripcorp/apollo#1589]
提供的演示环境不可用

**Comment by zouyx** [comment]
@267443698 我这里好像没什么问题，你能提供一下错误信息，方便定位。

**Comment by nobodyiam** [comment]
貌似admin service挂了，我们恢复一下 @JaredTan95

**Comment by 267443698** [comment]
> @267443698 我这里好像没什么问题，你能提供一下错误信息，方便定位。

怎么现在演示环境给关了？昨天具体问题是没法添加环境，没法添加namespace，新增项目后，基本什么都不能做。

**Comment by inix** [comment]
@267443698 把apollo的docker示例自己本地跑一下就可以启动了，很方便的。

**Comment by nobodyiam** [comment]
演示环境加回来了:
* 106.12.25.204:8070
* 账号/密码:apollo/admin
