### ISSUE TITLE
公开配置名称带有中文前缀后无法被关联

### ISSUE THREAD

**Issue by NijiadeIX** [ctripcorp/apollo#1593]
在创建公共配置的时候如果部门名称是中文的，是可以创建成功的，因为在调用createAppNamespace的时候没有带上部门名称，在isValidAppNamespace的时候是可以通过的。而在关联这个公共配置的时候，在AdminService里面的isValidClusterNamespace是无法通过的。

**Comment by nobodyiam** [comment]
这个和 #1499 一样，orgId请用英文吧，orgName可以用中文。

**Comment by FuleChu** [comment]
> 这个和 #1499 一样，orgId请用英文吧，orgName可以用中文。
部门里带数字会不会有影响呢？ 我现在的公共配置部门里带有数字，也是获取不到公共配置。
