### ISSUE TITLE
非properties类型的配置文件为什么不支持灰度

### ISSUE THREAD

**Issue by NijiadeIX** [ctripcorp/apollo#1594]
如题

**Comment by nobodyiam** [comment]
主要是考虑到非properties格式使用的较少，而且无法覆盖部分配置，只能全部覆盖，所以没有做支持

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by codjust** [comment]
宋总，这个灰度的功能对其他的格式还是有需求呀，我们用的yaml的格式，我们的需求是灰度的时候能指定灰度的主机就行了，不需要部分覆盖，被选中灰度的主机全部覆盖就可以了

**Comment by nobodyiam** [comment]
@codjust
