### ISSUE TITLE
apollo是否支持占位符

### ISSUE THREAD

**Issue by githubjunbushiwannengde** [ctripcorp/apollo#1596]
我有2分配置文件,一份application.yml,为公共配置文件
该配置有个属性:
server:
  apollo-test-port: 10065

另外有个私有配置文件
apollo-test.yml,该配置有个属性,
server:
  port: ${server.apollo-test-port}

其中私有配置文件,使用到了占位符, 请问下,这种在阿波罗有实现吗?如果有,需要怎么做?

**Comment by githubjunbushiwannengde** [comment]
但是,现在不是已经支持了yml的配置了吗?创建namespace是可以创建yml的

**Comment by githubjunbushiwannengde** [comment]
> yml格式目前不支持和spring整合，使用properties格式，结合spring是支持占位符的。

但是,现在不是已经支持了yml的配置了吗?创建namespace是可以创建yml的

**Comment by nobodyiam** [comment]
目前非properties格式是通过api方式获取的，ConfigService.getConfigFile

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
