### ISSUE TITLE
在不同的环境中增加Namespace,提示已存在

### ISSUE THREAD

**Issue by oawang** [ctripcorp/apollo#1599]
有DEV PRO 环境，创建了一个自定义的Namespace，只指定了DEV环境，此时再在PRO环境创建同名字的Namespace，提示已存在

**Comment by oawang** [comment]
之前创建Namespace时，只在dev下创建，然后多加了一个pro环境，此时想在pro环境加个Namespace，提示已存在 ，怎么解决
![1](https://user-images.githubusercontent.com/11540251/47329811-9f48d380-d6a8-11e8-9670-7136b4a4b911.png)
![2](https://user-images.githubusercontent.com/11540251/47329818-a2dc5a80-d6a8-11e8-9918-cef5bcaf9ee0.png)

**Comment by nobodyiam** [comment]
[1.2.0](https://github.com/ctripcorp/apollo/releases/tag/v1.2.0)版本已经发布，增加了『补缺Namespace』功能，支持补全缺失的公共namespace和私有namespace信息。
