### ISSUE TITLE
[问题请教] 部署一套环境、通过集群来区分环境

### ISSUE THREAD

**Issue by casyFire** [ctripcorp/apollo#1601]
您好，请教个问题。
部署多套成本比较大，所以我们打算多个环境只部署一套，通过不同的集群来区分环境，请问这样会有什么问题么？需要做的改动大概有哪些？

**Comment by nobodyiam** [comment]
生产和测试建议还是分开部署，不同的测试环境可以通过集群区分。

**Comment by casyFire** [comment]
想问下当时为啥考虑多套环境 要 部署多套、多个数据库，这样太增加成本了，没加一个环境，增加一套成本。而不是多套环境部署一套，公用一套数据库？

**Comment by nobodyiam** [comment]
一般的实践是测试环境和生产环境需要隔离的，互不影响

**Comment by zouyx** [comment]
其实通常情况下，生产环境是需要放在隔离区，与开发测试互相不能访问

我的建议是开发测试可以一套，生产分开部署，以免互相影响

**Comment by casyFire** [comment]
明白，多谢各位~
