### ISSUE TITLE
使用apollo配置管理中心时报错Could not complete get operation [Cause: connect timed out]

### ISSUE THREAD

**Issue by chengbaoxing1** [ctripcorp/apollo#1603]
使用apollo配置管理中心时报错Could not complete get operation [Cause: connect timed out] 
这个是什么情况呢？跟了下代码他是根据url获取对应的配置信息的，每次就卡死然后报错了

**Comment by chenkunyun** [comment]
telnet你的Apollo meta server的ip和端口。这里有可能是网络不通，也有可能是你meta server的close_wait连接数过多

**Comment by zouyx** [comment]
建议curl一下meta server的url，看看返回什么信息。如果通过反向代理之类软件建议查看access log

**Comment by leexk** [comment]
昨天我也碰到了相同的问题。app_id 不存在（通常是写错，比如 abc_def 写成 abc-def）也会报告这个错误。
请检查之

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by dreamazhang** [comment]
> case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by dreamazhang** [comment]
> case先关闭了，如还有问题，可以提供更多信息，或进群交流。
我也遇到了相同的问题。app_id是正确的，Loading config from Sync config from upstream repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository failed, reason: Load Apollo Config failed - appId: organization, cluster: default, namespace: application, url: http://172.20.0.4:8080/configs/organization/default/application?ip=192.168.44.132 [Cause: Could not complete get operation [Cause: connect timed out]]

**Comment by nobodyiam** [comment]
@dreamazhang

`connect timed out`这个是指连不上远端服务器，建议参考一下分布式部署中的网络策略部分

**Comment by freshgeek** [comment]
[网络策略部分](https://github.com/apolloconfig/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#14-%E7%BD%91%E7%BB%9C%E7%AD%96%E7%95%A5)
我是手动指定了homepageurl
