### ISSUE TITLE
多服务情况下人员的权限分配问题

### ISSUE THREAD

**Issue by shanjingheng** [ctripcorp/apollo#1604]
项目很多，并且采取的是一个版本新建一个namespace的方法，方便集群中使用多版本。针对这种使用方式，用户的权限分配有什么方便的方式分配吗。因为目前从ui上看到需要对每一个项目的每一个namespace单独设置权限

**Comment by nobodyiam** [comment]
一个版本新建一个namespace，那每次都要改代码吧，可以考虑一个版本一个集群，这样只要配置集群即可，不需要改代码，也不需要改权限
