### ISSUE TITLE
贡献一个Go的客户端

### ISSUE THREAD

**Issue by shima-park** [ctripcorp/apollo#1605]
@nobodyiam  贡献一个Go的客户端  [git地址](https://github.com/shima-park/agollo)

**Comment by nobodyiam** [comment]
已经更新到[Go、Python、NodeJS、PHP等客户端使用指南](https://github.com/ctripcorp/apollo/wiki/Go%E3%80%81Python%E3%80%81NodeJS%E3%80%81PHP%E7%AD%89%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)

**Comment by shima-park** [comment]
收到
