### ISSUE TITLE
是否可以提供一个动态修改sleuth采样率的示例

### ISSUE THREAD

**Issue by stephen-liu1974** [ctripcorp/apollo#1610]
就像动态修改zuul路由的那个例子一样，给出一个动态修改sleuth提交zipkin采样率的例子，谢谢！

**Comment by nobodyiam** [comment]
后续可以加一下，不过原理都差不多的，具体接入方式应该google一下也能找到

**Comment by adriancole** [comment]
if you do dynamic sample rates, let me know.. there is some prior art available:

rate limited sampler: https://github.com/openzipkin/brave/pull/819

old zookeeper adaptive group-based sampler: https://github.com/openzipkin-attic/zipkin-zookeeper

**Comment by nobodyiam** [comment]
This issue is closed for now. Please provide more information if further assistance is needed, Thanks!
