### ISSUE TITLE
一直报 code 404: Msg: No message available

### ISSUE THREAD

**Issue by yunnian** [ctripcorp/apollo#1611]
各项功能都是，求解，着急。。

![image](https://user-images.githubusercontent.com/5779513/47599450-29fb3c80-d9e1-11e8-8280-8196ce207dce.png)

![image](https://user-images.githubusercontent.com/5779513/47599445-1223b880-d9e1-11e8-8ad8-00d2b6675053.png)

**Comment by nobodyiam** [comment]
打开Network面板，看看是哪个请求404了，然后再结合portal和admin service的日志排查一下

**Comment by yunnian** [comment]
![image](https://user-images.githubusercontent.com/5779513/47601651-64c39b80-da06-11e8-9515-fc722bbb1b48.png)


![image](https://user-images.githubusercontent.com/5779513/47601634-3cd43800-da06-11e8-8b32-340577b45c00.png)

**Comment by yunnian** [comment]
配置名叫 .env 是不是这个导致的，前面有个.

**Comment by yunnian** [comment]
确实这个导致的，这是个bug namespage 前面不能有.
