### ISSUE TITLE
配置中心配置日志级别不生效

### ISSUE THREAD

**Issue by githubjj1987** [ctripcorp/apollo#1612]
配置中心配置：
![tim 20181029171412](https://user-images.githubusercontent.com/13885051/47640209-1b0db900-db9e-11e8-823d-ff17d99651cb.png)
测试代码：
		System.out.println(log.isErrorEnabled());
		System.out.println(log.isWarnEnabled());
		System.out.println(log.isInfoEnabled());
		System.out.println(log.isDebugEnabled());
控制台输出：
true
true
true
false
我项目中application.properties里面没有做任何配置

**Comment by githubjj1987** [comment]
// 服务启动时执行，读取配置中心的日志级别，进行第一次修改
        @PostConstruct
	private void refreshLoggingLevels() {
		Set<String> keyNames = config.getPropertyNames();
		for (String key : keyNames) {
			if (containsIgnoreCase(key, LOGGER_TAG)) {
				String strLevel = config.getProperty(key, "info");
				LogLevel level = LogLevel.valueOf(strLevel.toUpperCase());
				loggingSystem.setLogLevel(key.replace(LOGGER_TAG, ""), level);
				logger.info("{}:{}", key, strLevel);
			}
		}
	}

**Comment by witt-bit** [comment]
> 配置中心配置： ![tim 20181029171412](https://user-images.githubusercontent.com/13885051/47640209-1b0db900-db9e-11e8-823d-ff17d99651cb.png) 测试代码： System.out.println(log.isErrorEnabled()); System.out.println(log.isWarnEnabled()); System.out.println(log.isInfoEnabled()); System.out.println(log.isDebugEnabled()); 控制台输出： true true true false 我项目中application.properties里面没有做任何配置

你应该加
```shell
--apollo.bootstrap.eagerLoad.enabled=true --apollo.bootstrap.namespaces=true
```
