### ISSUE TITLE
Long polling failed, will retry in 120 seconds. reason: Could not complete get operation [Cause: Read timed out]

### ISSUE THREAD

**Issue by zwz1437** [ctripcorp/apollo#1617]
@nobodyiam 开发和测试环境都正常，在上预发的时候出现Long polling failed, will retry in 120 seconds. reason: Could not complete get operation [Cause: Read timed out]，查看了预发环境通过nginx转发，时间的设置大于60s，对应的/notification/v2地址在配置发生变化时可以正常访问一次，一旦加载新的配置后再轮询会出现long polling failed，请问这是什么原因呢？这个warn是否会影响正常的配置加载？

**Comment by nobodyiam** [comment]
一旦加载新的配置后，下次轮询没有新配置的话服务端是会hold住连接60秒的，不过客户端设置的超时时间是[90秒](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/RemoteConfigLongPollService.java#L57)，所以不应该read time out的，是否nginx有点问题？

另外，long polling为啥要走nginx？

**Comment by zwz1437** [comment]
我的理解就是：long polling failed后，客户端无法实时接收到配置是否更新的消息。客户端没有收到推送通知，过30秒后重连的时候，服务端也会识别出该客户端漏了消息，会将最新的配置信息推送给客户端。不知道是否正确？

**Comment by nobodyiam** [comment]
是的

**Comment by zwz1437** [comment]
@nobodyiam 关联多个公共namespqce，相同key的取值问题想请教一下
1.关联多个公共namespace，相同的key只有一个生效，和加载的顺序有关，使用第一次加载到的value
2.请问，如果其他namespace改变这个key值，会加载哪个value？
3.在进行长轮询/定时轮询时，加载的哪个namespace的值？

**Comment by nobodyiam** [comment]
如果是api方式，没有你说到的问题。

如果是spring方式，由于spring的property sources机制，所以排在前面的namespace优先，如何控制namespace的顺序？请参考[Spring整合方式](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#32-spring%E6%95%B4%E5%90%88%E6%96%B9%E5%BC%8F)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
