### ISSUE TITLE
【问题请教】 apollo项目本身可以把配置放到配置中心么？

### ISSUE THREAD

**Issue by casyFire** [ctripcorp/apollo#1619]
apollo项目本身可以把配置放到配置中心么？是引入client包么？比如在configservice中使用就引入一个client包，不会有什么问题么？

**Comment by nobodyiam** [comment]
这样会产生循环依赖的，所以目前apollo本身的配置是不通过apollo管理的

**Comment by casyFire** [comment]
好的

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
