### ISSUE TITLE
Apollo不适配sql server吗？

### ISSUE THREAD

**Issue by pengxdCSDN** [ctripcorp/apollo#1620]

**Comment by nobodyiam** [comment]
可以参考下[oracle和pg适配代码](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#12-mysql)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
