### ISSUE TITLE
apollo在不同的kubernetes集群间如何同步配置

### ISSUE THREAD

**Issue by vmulex** [ctripcorp/apollo#1624]
不同环境的微服务集群，在不同的kubernetes集群中，portal是如何与不同环境的集群建进行通信的，目前A环境的Portal通过B集群暴露端口可以链接到configserver，但是adminserver是通过访问eureka中获取的集群内的地址，无法访问。这块我们是怎么做的呢

**Comment by nobodyiam** [comment]
可以看一下[网络策略](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#14%E7%BD%91%E7%BB%9C%E7%AD%96%E7%95%A5)

**Comment by fudali113** [comment]
![image](https://user-images.githubusercontent.com/16189465/48911660-47bba480-eeae-11e8-87ad-a8935cb79a52.png)
我看到客服端是可以跳过 `meta service` 的，但是https://github.com/ctripcorp/apollo/blob/5d67ce64a354869096c38989c68b02b165204b60/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/component/AdminServiceAddressLocator.java#L118:24 中获取获取admin service 还是需要用过  `meta service` 来进行获取；

这样子对于没有打通各个环境网络的情况是不是不太友好的，比如：
* 我不同环境使用不同的vpc，vpc之间进行了隔离的，我使用 `Portal ` 通过`meta service` 拿到的ip可能就是就是内网ip，虽然也可以通过[网络策略](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#14%E7%BD%91%E7%BB%9C%E7%AD%96%E7%95%A5)进行配置外网ip，但是这样子会增加部署的成本；
* 是否在使用 `Portal ` 访问`meta service` 和`admin service` 的时候是没有任何验证的？这是不是也是基于打通各个环境网络的情况下的情况呢？


![image](https://user-images.githubusercontent.com/16189465/48912393-73d82500-eeb0-11e8-9939-265e2a369d82.png)
还有我发现其实在某一个环境中，config service 与 admin service 是没有任何交互的(基于 wiki 给出的架构图)，那么其实在某个环境的 `meta service` 只是为了给外部发现 admin service 和 config service 的功能，这对于在有SLB的情况下(比如 k8s 环境)，`meta service` 的意义是不是并不是很大？

基于以上我的理解(如果我的理解有偏差，希望您能帮助我进行更好的理解)；
我有两个提议：
* 是不是可以提供直接在 `Portal ` 中配置`admin service`的地址并加上验证？
* 是不是可以提供一个启动选项关闭`meta service`?


@nobodyiam 希望能与您进行讨论

**Comment by nobodyiam** [comment]
@fudali113 

meta service的用途就是实现服务发现和注册，它是一个逻辑角色，只是为了简化部署，所以和config service部署在一个jvm进程而已。

像k8s这样，似乎确实不需要一个单独的meta service了，可以想一下是否有比较好的一套模型可以兼容非k8s和k8s环境，欢迎讨论~
