### ISSUE TITLE
How to consume more than one Cluster in one application.

### ISSUE THREAD

**Issue by chickenlj** [ctripcorp/apollo#1625]
I can easily have several Config instances in one application, each Config maps to a Namespace and I can decide which Namespace the Config mapping to through the API. 
But for Cluster, according to my understanding, all these Configs consume values from the same cluster which is determined at the very beginning, there's no API to customize the namespace for each Config.

**Comment by nobodyiam** [comment]
Cluster is a deployment concept, which in our opinion is out of program's concern, so there is no way to consume more than one cluster. However, apollo does support many ways to [specify the runtime cluster](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#1242-cluster%E9%9B%86%E7%BE%A4)(in Chinese).

> all these Configs consume values from the same cluster

This is actually not 100% true, say some application A consumes 2 namespaces (N1 and N2) and has 2 instances A1 and A2.

Suppose:
* A1 is deployed in cluster C1.
* A2 is deployed in cluster C2.
* N1 has configs in `C1` and `default` clusters
  * N1 is not configured in `C2` cluster, which means instances in `C2` cluster will use the config in `default` cluster
* N2 has configs in `C2` and `default` clusters
  * N2 is not configured in `C1` cluster, which means instances in `C1` cluster will use the config in `default` cluster

Then:
* A1 will consume N1 from `C1` cluster and N2 from `default` cluster
* A2 will consume N1 from `default` cluster and N2 from `C2` cluster

More information on how cluster works could be found [here](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E4%BB%8B%E7%BB%8D#44-%E9%85%8D%E7%BD%AE%E8%8E%B7%E5%8F%96%E8%A7%84%E5%88%99)(in Chinese).

**Comment by chickenlj** [comment]
Thanks for the input.
