### ISSUE TITLE
关于python-flask应用接入apollo的问题

### ISSUE THREAD

**Issue by Smith-Wang** [ctripcorp/apollo#1626]
尝试在flask应用中接入apollo的客户端。在[pyapollo](https://github.com/filamoon/pyapollo)基础上进行了一些更改。
现在有一个问题：据我理解，由于java是静态类型的，把请求apollo server获取到的配置（JSON字符串）直接作为placeholder注入给bean就可以了，具体类型由实例化时进行替换；那么python是动态类型，如果把获取到的JSON配置不加转义就注入给flask的配置对象，会造成flask应用读取参数类型错误，启动报错。
想在客户端加一个参数转义，但是涉及一个转义规则的问题。
请问之前是否有类似的python应用案例？谢谢！

**Comment by Smith-Wang** [comment]
比如java里面，方法入参时候声明了参数类型，这样从容器获取配置时可以转换成你需要的。
但是python是动态格式的，入参时没有规定类型，flask框架默认你传入配置的是他需要的格式，然后直接解析。
事实上我之前有一份python配置对象是类似这样的（flask里面是声明一个config对象）：
<pre><code>
    DEBUG = True
    SQLALCHEMY_DATABASE_URI = 'mysql://someuser:somepw@localhost:3306/testdb?charset=utf8'
    SQLALCHEMY_BINDS = None
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SQLALCHEMY_ECHO = False
    SQLALCHEMY_POOL_TIMEOUT = 20
    SQLALCHEMY_POOL_RECYCLE = 1500
    SQLALCHEMY_DATABASE_CHAR_CODE = u"utf8_general_ci"</code></pre>
比如这里DEBUG参数应该是bool类型，下面uri就是String。但服务器的配置是没有类型区分的，如果把请求结果直接导入给flask.config，那么True可能就变成了'True'。flask尝试解析bool量转换成int。就会报错。

        ValueError: invalid literal for int() with base 10: 'True'

**Comment by nobodyiam** [comment]
明白了，java其实是使用者做转换的，比如spring会根据字段类型做转换。

apollo目前都是按照string存到数据库的，所以框架层是没法转的。

@filamoon 不知对这块是否有所了解？

**Comment by yuekui** [comment]
@Smith-Wang 可以尝试在client端用json.loads来做转换：
`
def _loads(self, data):
        if isinstance(data, dict):
            for k, v in data.items():
                data[k] = json.loads(v)
        return data
`
