### ISSUE TITLE
k8s部署后，本地访问问题--本地获取不到apollo里的配置

### ISSUE THREAD

**Issue by magnificence-dream** [ctripcorp/apollo#1627]
按照 “https://github.com/ctripcorp/apollo/blob/master/scripts/apollo-on-kubernetes/README.md”

这里的介绍部署的

将站点发布到apollo对应的机器后，能够正常访问到apollo的配置信息，但是本地获取apollo数据，一直获取不到，怀疑是metaserver的instance info问题：
![image](https://user-images.githubusercontent.com/39826801/47774606-7a97d000-dd28-11e8-981f-902ea03890da.png)
这里是Pod的IP，是个内网地址

我要怎么修改，本地才可以访问，谢谢~

**Comment by ruanxingshi** [comment]
确实，从日志看，客户端应用是从meta_server直接获取到了config_server的pod地址，然后就直接尝试跟这个pod的ip地址建立长链接。问题是pod的地址只能在k8s内部被访问到，难道应用的客户端只能跟apollo部署在同一个k8s中吗？

**Comment by magnificence-dream** [comment]
是的 ，是pod的IP，如果是多个Pod，Instance Info ipAddr会随机出现某个Pod的IP

**Comment by ruanxingshi** [comment]
直接获取pod地址做长链接的做法感觉很难适应现在的环境。可以尝试获取代理服务器的地址吗？slb或者nginx？

**Comment by nobodyiam** [comment]
可以参考一下[网络策略](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#14%E7%BD%91%E7%BB%9C%E7%AD%96%E7%95%A5)

**Comment by nobodyiam** [comment]
可以通过-D指定的，不需要重新生成jar文件的

**Comment by magnificence-dream** [comment]
文档上有这个说明，不过没找到对应的文件呢，能提示下吗，非常感谢~

**Comment by nobodyiam** [comment]
可以参考 #1631

**Comment by inix** [comment]
@magnificence-dream 
可以把eureka.service.url写入admin server和config server 的application-github.properties文件里，这个方式更方便。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by haoprogrammer** [comment]
> 谢谢，问题解决了
> 按照这个修改的：强制指定admin server和config server向eureka注册的IP和Port
> 
> 这样修改完后，需要重新生成jar文件，不过每次部署的时候 可能ip地址不一样，就需要重新来一遍，比较麻烦

可以具体说下怎么修改的吗？我k8s集群部署后在本地访问也遇到一样的问题，感谢感谢
![image](https://user-images.githubusercontent.com/31644888/51171112-f8f91c80-18ea-11e9-9bfc-b894b5a0afec.png)
![image](https://user-images.githubusercontent.com/31644888/51171143-0f06dd00-18eb-11e9-8ee1-9d352f75f2f5.png)

**Comment by magnificence-dream** [comment]
我是这样解决的：
      --》 对apollo-config-service创建一个slb的服务，得到对应的IP；
      --》修改apollo-configservice/src/main/resources/META-INF/bootstrap，如下：
             
--》安装maven并重新生成jar并重新生成镜像


PS：数据库的配置不用动，只调整config-service下的bootstrap.yaml即可



r1renhw@163.com
 
发件人： haoprogrammer
发送时间： 2019-01-15 17:41
收件人： ctripcorp/apollo
抄送： magnificence; Mention
主题： Re: [ctripcorp/apollo] k8s部署后，本地访问问题--本地获取不到apollo里的配置 (#1627)
谢谢，问题解决了
按照这个修改的：强制指定admin server和config server向eureka注册的IP和Port
这样修改完后，需要重新生成jar文件，不过每次部署的时候 可能ip地址不一样，就需要重新来一遍，比较麻烦
可以具体说下怎么修改的吗？我k8s集群部署后在本地访问也遇到一样的问题，感谢感谢

**Comment by haoprogrammer** [comment]
不好意思，我看不到您修改的apollo-configservice/src/main/resources/META-INF/bootstrap的内容，另外，您的意思是自己写了一个管理apollo-config的k8s的serviceAPI对象，不用官方事例，这个意思吗？

**Comment by haoprogrammer** [comment]
感谢感谢，已解决。我是用的宿主机的ip:端口。k8s的service模式是nodeport。
![image](https://user-images.githubusercontent.com/31644888/51178034-65304c00-18fc-11e9-8709-b36a67f0d28f.png)
参考：[网络策略
](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#14%E7%BD%91%E7%BB%9C%E7%AD%96%E7%95%A5)
