### ISSUE TITLE
Quick Start报错，有人帮忙看看是什么问题吗？

### ISSUE THREAD

**Issue by ferry1376122** [ctripcorp/apollo#1630]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; n
ested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Cannot determine embedded database drive
r class for database type NONE. If you want an embedded database please put a supported one on the classpath. If you have database settings to be loaded from
 a particular profile you may need to active it (the profiles "github" are currently active).

**Comment by nobodyiam** [comment]
这个不是root cause，建议往上找一下第一个出错信息。

一般是数据库连接配置的不对
