### ISSUE TITLE
 有抽象服务注册和发现这块的业务吗？能支持将Eureka切换到Consul吗？

### ISSUE THREAD

**Issue by xiaoxing598** [ctripcorp/apollo#1632]
我们现在用的Consul可以使用阿波罗吗？

**Comment by nobodyiam** [comment]
可以，不过需要修改一下 metaservice package下的实现

**Comment by xiaoxing598** [comment]
请麻烦给一下修改示例，非常感谢！

**Comment by nobodyiam** [comment]
meta service的实现很简单直白了，无非就是封装了eureka的服务发现接口。

如果要切到consul的话，只需要封装consul的服务发现接口即可。

另外，貌似也没啥理由需要切换到consul，因为apollo的eureka是自带的，不会带来额外的运维成本。

**Comment by xiaoxing598** [comment]
tks
