### ISSUE TITLE
多个环境的问题，只有一个dev环境是没有问题的，后来添加了FAT,UAT环境，.net core代码没有做修改竟然获取不到数据了，

### ISSUE THREAD

**Issue by zpc870921** [ctripcorp/apollo#1634]
多个环境的问题，只有一个dev环境是没有问题的，后来添加了FAT,UAT环境，.net core代码没有做修改竟然获取不到数据了，请问需要做什么修改吗？盼望解答！
443813032@qq.com  
![tim 20181102122803](https://user-images.githubusercontent.com/9030696/47893952-ef8b1700-de9a-11e8-9f89-3ef9d5f99c1d.png)

**Comment by nobodyiam** [comment]
获取不到配置的话，在客户端有日志的，可以看一下

**Comment by zpc870921** [comment]
解决了，谢谢了

**Comment by lmz-json** [comment]
我想请问一下，比如一开始你只有一个DEV环境，我现在就是这样，那后面是怎么添加其他环境的呢

**Comment by nobodyiam** [comment]
@lmz-json 可以看看[3.1.1 apollo.portal.envs - 可支持的环境列表](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_311-apolloportalenvs-%e5%8f%af%e6%94%af%e6%8c%81%e7%9a%84%e7%8e%af%e5%a2%83%e5%88%97%e8%a1%a8)中的备注内容
