### ISSUE TITLE
非properties格式文件有没有办法通过占位符读取到apollo配置？

### ISSUE THREAD

**Issue by xgbyl** [ctripcorp/apollo#1637]
maven项目，用于部署服务的脚本文件中通过${}引入了一些配置，原先这些配置是在pom.xml中定义的，迁移至apollo后，如何能够在pom.xml中得到这些配置，进而使脚本文件的配置生效呢？
![default](https://user-images.githubusercontent.com/41046248/47904920-c9786d80-dec0-11e8-8a22-d77ee35753c4.png)

**Comment by nobodyiam** [comment]
这个如果要支持的话，可能要写maven插件了，在maven打包的时候做替换。

**Comment by zouyx** [comment]
我觉得简单点的方法是可以通过shell读取apollo的配置然后进行替换也可以

不需要写maven插件那么复杂

**Comment by xgbyl** [comment]
> 我觉得简单点的方法是可以通过shell读取apollo的配置然后进行替换也可以
> 
> 不需要写maven插件那么复杂

可以指点一下如何通过shell直接读取Apollo配置吗？Apollo目前貌似是不支持的吧

**Comment by zouyx** [comment]
[通过不带缓存的http接口从apollo读取配置](https://github.com/ctripcorp/apollo/wiki/%E5%85%B6%E5%AE%83%E8%AF%AD%E8%A8%80%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97#13-%E9%80%9A%E8%BF%87%E4%B8%8D%E5%B8%A6%E7%BC%93%E5%AD%98%E7%9A%84http%E6%8E%A5%E5%8F%A3%E4%BB%8Eapollo%E8%AF%BB%E5%8F%96%E9%85%8D%E7%BD%AE)

通过这个使用curl可以读取出来的

**Comment by xgbyl** [comment]
> 
> 
> [通过不带缓存的http接口从apollo读取配置](https://github.com/ctripcorp/apollo/wiki/%E5%85%B6%E5%AE%83%E8%AF%AD%E8%A8%80%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97#13-%E9%80%9A%E8%BF%87%E4%B8%8D%E5%B8%A6%E7%BC%93%E5%AD%98%E7%9A%84http%E6%8E%A5%E5%8F%A3%E4%BB%8Eapollo%E8%AF%BB%E5%8F%96%E9%85%8D%E7%BD%AE)
> 
> 通过这个使用curl可以读取出来的

试了一下  通过这种方法可以得到配置  非常感谢两位的解答 @zouyx @nobodyiam

**Comment by zouyx** [comment]
不用客气，主要是能解决你的问题 ☺️
