### ISSUE TITLE
项目管理员没有权限

### ISSUE THREAD

**Issue by Alibner** [ctripcorp/apollo#1638]
A创建的项目a，在应用负责人哪里选择了B；

![image](https://user-images.githubusercontent.com/10595993/47913056-9d1b1c00-ded5-11e8-85e2-767e5975df55.png)

完了，A可以对项目a执行，配置的新增，修改，发布等操作；但是操作不了集群、namespace和管理项目。

B的账户，登录，无法对项目a进行配置的新增，修改，发布等操作，但是可以管理集群，namespace，和管理项目。

这里是不是有些问题，还是说，A创建的应用只能选择应用负责人A。

![image](https://user-images.githubusercontent.com/10595993/47913258-6691d100-ded6-11e8-961e-303755c00097.png)

----

**Comment by nobodyiam** [comment]
创建人默认拥有新创建namespace的编辑和发布权限

项目管理员拥有项目的管理权限，项目管理员可以给任何人授权编辑和发布某个namespace，包括他自己

**Comment by Alibner** [comment]
了解了，谢谢！
