### ISSUE TITLE
未来发展

### ISSUE THREAD

**Issue by jifengnan** [ctripcorp/apollo#1639]
阿里现在正在和spring合作推出了新的动态配置服务（含注册中心）Nacos，目前正在孵化中，预计明年初孵化完成，正式成为spring cloud中的一员。

Apollo作为一个相当成熟的框架，会不会在Nacos出世后渐渐被替代呢。

Apollo有没有考虑过和Apache或者Spring等知名的开源组织合作，成为其一个顶级项目从而扩大影响力呢。

**Comment by nobodyiam** [comment]
感谢关注！

最近国内开源氛围确实越来越好了，涌现出了不少优秀开源项目和社区，我们非常乐于看到国内开源界大步向前、百花齐放的形势，作为其中一员，Apollo也会紧跟趋势，为开源出一份力。

所以后续在持续更新、维护Apollo产品的同时，我们也会视时机看是否需要进入Apache孵化，从而更好地为开源事业贡献力量~

**Comment by JaredTan95** [comment]
期待进入apache

**Comment by DeanJi** [comment]
@nobodyiam portal页面支持国际化语言，有没有在计划中？

**Comment by nobodyiam** [comment]
@DeanJi 

如果要提交Apache孵化的话，多语言肯定是要支持的，这块大家如果有好的想法也欢迎一起贡献~

**Comment by kezhenxu94** [comment]
国际化早已支持, 不知道进入 Apache 孵化是否还有可能,
