### ISSUE TITLE
不支持回滚到任意版本

### ISSUE THREAD

**Issue by millzhj** [ctripcorp/apollo#1642]
现在只能回滚到上一个版本，不能回滚到任意版本，这个是有什么意图吗？

**Comment by nobodyiam** [comment]
一般情况下回滚都是回滚到上一个版本，跨版本回滚可能会出现问题。

默写情况下可能存在跨版本回滚的场景，如果场景较多的话，后续可以考虑支持一下。

**Comment by millzhj** [comment]
有计划开发这个功能吗，我们场景较多，如果要开发，估计多久能够完成呢？谢谢

**Comment by casyFire** [comment]
请问下，跨版本回滚可能会出现什么问题呢？

**Comment by nobodyiam** [comment]
用户理解上会不那么直观，容易犯错

**Comment by nobodyiam** [comment]
implemented by #3093
