### ISSUE TITLE
发现不了新添加的Namespace

### ISSUE THREAD

**Issue by xiaoxing598** [ctripcorp/apollo#1643]
# 步骤
在控制台添加新的Namespace

![apollo_issue](https://user-images.githubusercontent.com/5615719/47988500-54ee3a80-e11d-11e8-8f09-a51d1b0ba4b9.png)

在应用中启用新的Namespace

```java
@EnableApolloConfig({"application", "params"})
```

# 结果

只有application加载进来了，params却没有，发现日志中有错误。

```
WARN 10552 --- [figRepository-1] c.c.f.a.i.AbstractConfigRepository      
 : Sync config failed, will retry. Repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository, reason: Load Apollo Config failed -
 appId: SampleApp, cluster: default, namespace: params, 
url: http://10.0.0.0:8080/configs/SampleApp/default/params?ip=10.0.0.0
 [Cause: [status code: 404] Could not find config for namespace - 
appId: SampleApp, cluster: default, namespace: params, 
please check whether the configs are released in Apollo!]
```

# 期望

这两个{"application", "params"}配置都能够加载到。

**Comment by nobodyiam** [comment]
非properties格式需要写全namespace名字的，{"application", "params.yml"}

另外，目前yml格式支持有限，不支持直接注入到spring里面，需要自己通过ConfigService.getConfigFile获取后解析的

**Comment by xiaoxing598** [comment]
谢谢！这种常见问题可以补充到文档里面。

**Comment by anjia0532** [comment]
@xiaoxing598 怎么支持yml的？新建的时候没法选格式啊？1.1.2版本

**Comment by xiaoxing598** [comment]
类型选择private就可以了

**Comment by anjia0532** [comment]
@xiaoxing598 谢谢指点，还真没注意到
