### ISSUE TITLE
启动指定meta还需要再指定-Denv吗

### ISSUE THREAD

**Issue by Alibner** [ctripcorp/apollo#1644]
sprint boot客户端接入apollo以后，在启动的时候，只需要指定一个-Dapollo.meta还需要再指定-Denv吗？

我看wiki说，-Denv是可选参数；

而且我理解，一个环境对应一个meta server 的地址，那理应当就能拉下来对应的环境配置。 是不是这样的？

**Comment by Alibner** [comment]
@nobodyiam

**Comment by Alibner** [comment]
我这边研发刚刚测试，指定了 dev 的meta server地址，然后 指定 env 为 fat ，也能把fat的配置文件给拉下来？ 是这样吗？ @nobodyiam

**Comment by nobodyiam** [comment]
代码中优先读取apollo.meta，如果apollo.meta没有指定，才会读取${env}.meta信息。

所以，如果指定了dev 的meta server地址，那么就只会读取dev环境的配置，不会读取fat环境的配置。除非fat环境的config service注册到dev环境上去了。

**Comment by Alibner** [comment]
谢谢！

**Comment by Alibner** [comment]
最后我再弱弱的问一句，是不是两个环境的config service也就是meta server不能部署到同一个机器上呀。如果部署了就有可能只全都注册到同一个环境的注册中心，导致修改配置全环境会混乱。。。
是不是有这种可能。

**Comment by nobodyiam** [comment]
可以部署在同一台机器上，端口不一样就行，同时ApolloConfigDB.ServerConfig中的eureka.service.url得配置对

**Comment by Alibner** [comment]
好的，非常感谢。
