### ISSUE TITLE
请问以后会支持nodejs吗？

### ISSUE THREAD

**Issue by letiscoding** [ctripcorp/apollo#1645]
请问以后会支持nodejs吗？

**Comment by nobodyiam** [comment]
目前有nodejs客户端的，详见[Go、Python、NodeJS、PHP等客户端使用指南](https://github.com/ctripcorp/apollo/wiki/Go%E3%80%81Python%E3%80%81NodeJS%E3%80%81PHP%E7%AD%89%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by lvgithub** [comment]
看这个，https://github.com/lvgithub/ctrip-apollo-client
