### ISSUE TITLE
自定义缓存问题

### ISSUE THREAD

**Issue by chengbaoxing1** [ctripcorp/apollo#1646]
我在application.properties中自定义了缓存路径apollo.cacheDir=XXX/XXX，但是目录创建了，缓存文件没有生成到这个自定义缓存路径里面，而是生成在 bin目录下面到 config-cache目录下面了 什么情况？

**Comment by JaredTan95** [comment]
你可以试试`-Dapollo.cacheDir=XXX/XXX`方式。

**Comment by nobodyiam** [comment]
估计是指定的路径没有写权限，所以fallback到working directory了。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
