### ISSUE TITLE
transfrom单词拼写错误

### ISSUE THREAD

**Issue by fengss** [ctripcorp/apollo#1647]
https://github.com/ctripcorp/apollo/blob/6a090dad0fd30c8e445947cf29e29860119ed276/apollo-common/src/main/java/com/ctrip/framework/apollo/common/utils/BeanUtils.java#L48

**Comment by nobodyiam** [comment]
多谢指出，是否方便提个PR？

**Comment by kezhenxu94** [comment]
已经在 #1830 解决
