### ISSUE TITLE
Apollo REST接口咨询

### ISSUE THREAD

**Issue by reignsr** [ctripcorp/apollo#1648]
看了“Apollo开放平台”页面（https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0）关于开放api的介绍，咨询几个问题：
1、该页面中列出的接口是否是rest接口的全部内容？是否还有其他接口没有写出，如果有，哪里可以看到完整的接口文档？
2、如果上述页面中已经是全部接口，想请教比如“获取所有app信息（appid、APP名称等）”，“获取有修改待发布的namespace”，“变更了的配置”等该如何实现？是否考虑提供类似接口？
3、既然提供了创建namespace接口，是否进一步提供namespace授权接口（修改和发布权限）？
“Apollo开放平台”页面中介绍的接口，对于第三方应用不能直接访问数据库的情况下，难以实现以上需求。望考量！

**Comment by nobodyiam** [comment]
1. 有部分灰度发布相关的api还没列出，可以在 https://github.com/ctripcorp/apollo/tree/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller 看到所有的接口
2. 获取所有app信息目前确实没有，不过实现比较简单，可以提个PR。获取有修改待发布的namespace，这个功能在apollo都没有的，为啥第三方系统需要这个功能？变更了的配置这个可以参考apollo portal的实现，简而言之是把namespace的配置和namespace最近一次发布的配置做diff
3. open api访问namespace的权限是通过管理员授权的，所以不需要授权接口。如果是要为普通用户授权的话，感觉直接在apollo操作也挺方便的，不需要在第三方应用做吧。

**Comment by reignsr** [comment]
@nobodyiam 首先感谢详尽的回复！
第3点，创建namespace的接口如果能够正常工作，意味着第三方应用已经得到了app级别的“Master”授权，即项目管理员权限，这个权限是可以为namespace的修改和发布动作授权的。我的想法是，接口既然允许创建namespace，为何不进而为当前创建的namespace进行授权，以完成完整工作。
我们是要是实现手机端的操控，一些主要的动作希望可以在手机端完成，而不再登陆portal界面。所以如果接口全面一些，我们实现就更简单一点。

**Comment by nobodyiam** [comment]
@reignsr 

恩，理解了，不过这块工作量相对比较大，使用的场景也比较少，看看后续是否可以加上。
