### ISSUE TITLE
使用官方DockerFile部署的问题

### ISSUE THREAD

**Issue by CaseyGit** [ctripcorp/apollo#1649]
ADD failed: stat /var/lib/docker/tmp/docker-builder438618080/apollo-configservice-1.1.2-SNAPSHOT-github.zip: no such file or directory

![image](https://user-images.githubusercontent.com/44695991/48055138-d14e4f80-e1e9-11e8-85bd-1727cc178792.png)

**Comment by qtwang** [comment]
@CaseyGit 这个问题解决了吗，我也在windows环境下安装docker进行打包遇到同样的问题

**Comment by DCaInIao** [comment]
@CaseyGit @qtwang  我也遇到同样的问题，需要把apollo-configservice-${VERSION}-github.zip拷贝到当前目录，在执行docker build就好了
