### ISSUE TITLE
配置meta service信息问题

### ISSUE THREAD

**Issue by NGU-Sunshie** [ctripcorp/apollo#1655]
请问一下各位大神，如果我在ApolloConfigDB中，按集群配置了eureka.service.url。
Cluster：{default：http://1.1.1.1:8080/eureka/}
Cluster：{SHAOY：http://2.2.2.2:8080/eureka/}
Cluster：{SHAJQ ：http://3.3.3.3:8080/eureka/}

那么我配置apollo-portal的meta service信息时候，是不是应该把所有的eureka都配进去？
就像这样：dev.meta=http://1.1.1.1:8080，http://2.2.2.2:8080，http://3.3.3.3:8080

SHAOY和SHAJQ集群间的eureka会相互注册吗？

还有一个问题，就是同一台服务器怎么才能同时启动两个ConfigService呢？如果同时启用两个ConfigService合不合理啊？

**Comment by nobodyiam** [comment]
meta service一般建议是配置域名的，如果配IP的话，视实际部署情况，一般是把所有的的meta service都配进去。

SHAOY和SHAJQ集群间的eureka不会相互注册吗？

同一台服务器可以同时启动两个ConfigService，端口不同即可。

**Comment by NGU-Sunshie** [comment]
> meta service一般建议是配置域名的，如果配IP的话，视实际部署情况，一般是把所有的的meta service都配进去。
> 
> SHAOY和SHAJQ集群间的eureka不会相互注册
> 
> 同一台服务器可以同时启动两个ConfigService，端口不同即可。
感谢宋老师的耐心回复。谢谢
