### ISSUE TITLE
什么时候有计划提供一个springboot版本的apollo？

### ISSUE THREAD

**Issue by littlefisher666** [ctripcorp/apollo#1657]
现在springboot已经出现很久了，不知道apollo什么时候能够提供一个springboot的版本，所有的配置能够在application.yml或者bootstrap.yml中进行配置

**Comment by litttlefisher** [comment]
@nobodyiam 自定配置的功能，通过@EnableApolloConfig注解实现。可针对于您所述的配置，未能真正的改造为springboot结构。这些配置，应该集中于一个XxxProperties.java文件中，例如ApolloProperties。然后使用@ConfigurationProperties注解进行扫描。同时该工程要加入spring-boot-configuration-processor的依赖，以生成spring-configuration-metadata.json文件。在idea中，如果在application.yml中配置信息，如果该参数已被维护在spring-configuration-metadata.json中，那么会通过代码提示的快捷键看到的

**Comment by nobodyiam** [comment]
多谢建议！

**Comment by litttlefisher** [comment]
还望能提供一个starter进行封装，这样看到这个工程，也就知道确实进行了springboot的封装的
