### ISSUE TITLE
@Value注解值无法更新

### ISSUE THREAD

**Issue by GreedyPirate** [ctripcorp/apollo#1659]
项目启动后正确的获取到了字段的值，在项目运行期间再次修改这个字段，本地缓存文件更新了，但是我通过接口访问这个字段还是旧值，通过跟踪源码到`SpringValue#injectField`方法，field.set的都是新值，更诡异的是我第二次修改这个字段，断点获取到的值竟然是上一次修改的值

以下是我的测试接口代码
```
public class ApolloTestController {
    @Value("${test.name}")
    private String value;

    @RequestMapping(value = "/api/test")
    public String getValue(){
        return value;
    }
}
```
不管我修改多少次，返回的都是项目启动第一次获取到的值 @nobodyiam 请指教一下

**Comment by GreedyPirate** [comment]
找到原因了，在比较过bean的hashcode后，确定是两个不同的bean实例，我的项目是SpringMVC项目，我把这个字段定义在了Controller层，属于SpringMVC容器管理，而我把`<apollo:config/>`定义在了Spring父容器的xml里，所以要么把字段定义到Service层，要么在spring-mvc.xml里定义`<apollo:config/>`，经过测试可以获取到，不知道我这样理解对不对 @nobodyiam

**Comment by nobodyiam** [comment]
如果是不同的容器，是要单独配置`<apollo:config/>`的

**Comment by GuiSong01** [comment]
在比较过bean的hashcode后，确定是两个不同的bean实例
---这个地方不同的bean实例，是指那个bean实例？
