### ISSUE TITLE
yml里数组格式转化为property放到apollo,spring cloud gateway启动失败

### ISSUE THREAD

**Issue by jevislee** [ctripcorp/apollo#1660]
比如
spring:
  cloud:
    gateway:
      routes:
        - id: demo
          uri: lb://demo
          predicates:
          - Path=/demo/**
通过snakeyaml工具转成如下property
spring.cloud.gateway.routes=[{id=demo, uri=lb://demo, predicates=[Path=/demo/**]}]

但是spring cloud gateway启动报错
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'spring.cloud.gateway.routes' to java.util.List<org.springframework.cloud.gateway.route.RouteDefinition>:

    Reason: failed to convert java.lang.String to @javax.validation.constraints.NotNull @javax.validation.Valid org.springframework.cloud.gateway.route.RouteDefinition

Action:

Update your application's configuration

**Comment by jevislee** [comment]
以后spring cloud gateway将会代替zuul,而spring cloud gateway官方文档里的路由判断都是用的yml数组格式,文档地址https://cloud.spring.io/spring-cloud-gateway/single/spring-cloud-gateway.html

请重视一下这个问题,谢谢

**Comment by nobodyiam** [comment]
数组好像不是这么写的，参考一下[SampleRedisConfig.java](https://github.com/ctripcorp/apollo/blob/master/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/spring/springBootDemo/config/SampleRedisConfig.java#L25)

**Comment by jevislee** [comment]
spring.cloud.gateway.routes[0].id = demo
spring.cloud.gateway.routes[0].uri = lb://demo
spring.cloud.gateway.routes[0].predicates[0] = Path=/demo/**

搞定了,不过真的挺绕人的...
