### ISSUE TITLE
0.9升级0.11后 用户管理不能用

### ISSUE THREAD

**Issue by dinggel** [ctripcorp/apollo#1665]
org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported
![image](https://user-images.githubusercontent.com/22829724/48469292-6c1dde00-e829-11e8-8844-fff3e5726598.png)

**Comment by nobodyiam** [comment]
是不是没有启动auth profile？

**Comment by dinggel** [comment]
@nobodyiam 这个怎么启动

**Comment by dinggel** [comment]
我是用打包后生成的脚本启动的，0.91版本也没有这个东西

**Comment by nobodyiam** [comment]
apollo提供的[打包脚本](https://github.com/ctripcorp/apollo/blob/master/scripts/build.sh#L36)默认会启用`auth`profile的，一旦启用`auth` profile，会自动注入[SpringSecurityUserService](https://github.com/ctripcorp/apollo/blob/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/configuration/AuthConfiguration.java#L248)的。

你报的这个错就是因为注入的不是SpringSecurityUserService导致的 - 详见[UserInfoController](https://github.com/ctripcorp/apollo/blob/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/UserInfoController.java#L49)

**Comment by dinggel** [comment]
原先就是auto。注入的时候还是default，这个怎么破

**Comment by nobodyiam** [comment]
如果是照着文档操作的不会出现这个问题的。。。你是自己打包的吗？

**Comment by dinggel** [comment]
是按照文档打包的，逐个替换每个环境的服务
后面加了启动参数好了-Dspring.profiles.active=github,auth
