### ISSUE TITLE
同一个环境不同集群相同配置

### ISSUE THREAD

**Issue by supertojob** [ctripcorp/apollo#1668]
你好！
我手头的系统是这样的：区分线上（PRO）/线下（DEV）环境，线上环境有不同的集群（idc1/idc2）。

希望同一个环境下业务相关数据只需要配置一次（比如某个商品的价格，线上所有环境应该都相同），不想通过手动同步数据到不同集群来实现；
而服务相关数据同一环境不同集群配置可以不同（比如数据库连接）。

请教一下Apollo有没有比较好的方式支持？
期待回复，非常感谢！

**Comment by supertojob** [comment]
非常感谢这么快收到您的回复！

可能我没把问题描述清楚，这个方案我考虑过，问题是还需要区分线上/线下环境，希望线上所有的集群业务数据都一样，线下的所有集群业务数据都一样，但线上/线下相同的配置项值可以不一样。比如，线上价格5块钱，线下价格1块钱。

期待回复，非常感谢！

**Comment by nobodyiam** [comment]
公共namespace的配置是区分环境的

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
