### ISSUE TITLE
我自己实现了ConfigChangeListener，然后用bean注入，onChange实现了两次监听这个是为啥？

### ISSUE THREAD

**Issue by a583743253** [ctripcorp/apollo#1669]
@Bean
    public void initListener() {
        List<ConfigPropertySource> configPropertySources = configPropertySourceFactory.getAllConfigPropertySources();
        for (ConfigPropertySource configPropertySource : configPropertySources) {
            configPropertySource.addChangeListener(new ApolloListener());
        }
    }

public class ApolloListener implements ConfigChangeListener {
    private final static Logger logger = LoggerFactory.getLogger(ConfigChangeListener.class);

    @Override
    public void onChange(ConfigChangeEvent configChangeEvent) {
        try {
            logger.info("配置文件值发生了改变，需要重启,时间戳为：{}.", System.currentTimeMillis());

        } catch (Exception e) {
            logger.info("重启项目时发生错误！！！！！");
            e.printStackTrace();
        }
    }
}

**Comment by nobodyiam** [comment]
看看是不是addChangeListener执行了多次？

**Comment by a583743253** [comment]
> 看看是不是addChangeListener执行了多次？还可以在loggr.info时把this的hashcode输出一下。

已经找到问题了，由于configPropertySourceFactory.getAllConfigPropertySources();是一个list，然后我addChangeListener中直接add监听，没有break，ConfigPropertySource加了两次，实现了监听两次，
如下图实现添加就好了


    @Bean
    public void initListener() {
        List<ConfigPropertySource> configPropertySources = configPropertySourceFactory.getAllConfigPropertySources();
        for (ConfigPropertySource configPropertySource : configPropertySources) {
            configPropertySource.addChangeListener(new Test());
            break;
        }
    }

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
