### ISSUE TITLE
apollo SpringValueRegistry不释放引用触发full gc

### ISSUE THREAD

**Issue by shanjingheng** [ctripcorp/apollo#1670]
jdk版本　1.8.0_102
　
写个了程序验证了下使用@Value的对象是不会被回收的，若是多例的情况下，就会造成很多对象无法回收。　是否需要将bean改成弱引用，或若不需要onchange的功能，有开关设置不存储
  for (String key : keys) {
      SpringValue springValue = new SpringValue(key, value.value(), bean, beanName, field, false);
      springValueRegistry.register(key, springValue);
      logger.debug("Monitoring {}", springValue);
    }

![image](https://user-images.githubusercontent.com/19594851/48529123-bc9a4780-e8cc-11e8-8bce-50c2e4351310.png)

![image](https://user-images.githubusercontent.com/19594851/48529157-d89de900-e8cc-11e8-8376-64e1b82effe0.png)

**Comment by nobodyiam** [comment]
1. spring value目前是会用强引用hold住bean的，不过一般Spring中bean不会频繁创建的，所以之前有考虑过改为弱引用，只是觉得没有很大必要，不过后续这个确实可以做一下。

2. 目前是有开关来控制是否需要自动更新spring中注入的值得，参见[3.2.2 Spring Placeholder的使用](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#322-spring-placeholder%E7%9A%84%E4%BD%BF%E7%94%A8)

**Comment by nobodyiam** [comment]
@shanjingheng 

PR #1676 已经修复该问题
