### ISSUE TITLE
部署configservice和adminservice的时候，为什么会一直找server_config这张表

### ISSUE THREAD

**Issue by lihongzheng001** [ctripcorp/apollo#1671]
![image](https://user-images.githubusercontent.com/44185425/48539367-dc903200-e8f1-11e8-8acc-a3a8cce12201.png)

**Comment by nobodyiam** [comment]
看上去是配置文件不对，Naming strategy是在[apollo-common的application.properties](https://github.com/ctripcorp/apollo/blob/master/apollo-common/src/main/resources/application.properties)中定义的，是否自己改过代码或配置文件？
