### ISSUE TITLE
apollo-configservice启动失败

### ISSUE THREAD

**Issue by chlin7** [ctripcorp/apollo#1672]
2018年 11月 15日 星期四 16:26:33 CST ==== Starting ==== 
Unable to find Java
2018年 11月 15日 星期四 16:26:33 CST Failed to start apollo-configservice.jar, return code: 1

**Comment by nobodyiam** [comment]
这一段是Spring Boot的启动脚本，可以参考对照一下

```bash
# Find Java
if [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]]; then
    javaexe="$JAVA_HOME/bin/java"
elif type -p java > /dev/null 2>&1; then
    javaexe=$(type -p java)
elif [[ -x "/usr/bin/java" ]];  then
    javaexe="/usr/bin/java"
else
    echo "Unable to find Java"
    exit 1
fi
```

**Comment by chlin7** [comment]
> 这一段是Spring Boot的启动脚本，可以参考对照一下
> 
> ```shell
> # Find Java
> if [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]]; then
>     javaexe="$JAVA_HOME/bin/java"
> elif type -p java > /dev/null 2>&1; then
>     javaexe=$(type -p java)
> elif [[ -x "/usr/bin/java" ]];  then
>     javaexe="/usr/bin/java"
> else
>     echo "Unable to find Java"
>     exit 1
> fi
> ```

这段代码在startup.sh文件没有，需要自己添加是吗？谢谢

**Comment by chlin7** [comment]
> 这一段是Spring Boot的启动脚本，可以参考对照一下
> 
> ```shell
> # Find Java
> if [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]]; then
>     javaexe="$JAVA_HOME/bin/java"
> elif type -p java > /dev/null 2>&1; then
>     javaexe=$(type -p java)
> elif [[ -x "/usr/bin/java" ]];  then
>     javaexe="/usr/bin/java"
> else
>     echo "Unable to find Java"
>     exit 1
> fi
> ```

这段代码在startup.sh里面没有，需要自己添加是嘛？ 谢谢了

**Comment by nobodyiam** [comment]
这个是spring boot的启动脚本，不在startup.sh里面，是在jar里面的。

贴出来只是想让你根据它的逻辑去排查一下为啥会报`Unable to find Java`

**Comment by chlin7** [comment]
ok
