### ISSUE TITLE
@Vaule获取不到值

### ISSUE THREAD

**Issue by chlin7** [ctripcorp/apollo#1673]
发布key为spring.datasource.url的值之后可以获取到，后来删除这个之后，新发布一个key为dbUrl的值，通过@Value获取的时候，获取不到，但是之前spring.datasource.url依旧可以获取到（已经删除且重新发布），这是有缓存的问题嘛

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
