### ISSUE TITLE
How to set value into Apollo?

### ISSUE THREAD

**Issue by chickenlj** [ctripcorp/apollo#1674]
Dubbo has a portal OPS in here https://github.com/apache/incubator-dubbo-ops. This system is used for service governance, we need to save various configuration or router rules into the backend config center like Apollo. So I want to know is there any API in the SDK that can allow me to write the values in?

**Comment by nobodyiam** [comment]
Yes, apollo has a set of open apis, please refer [Apollo开放平台](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0) for more information. There is also an [open api java client](https://mvnrepository.com/artifact/com.ctrip.framework.apollo/apollo-openapi) which encapsulates the open apis.

**Comment by chickenlj** [comment]
Got it thanks.
