### ISSUE TITLE
springboot启动如何拉取apollo的公共配置项以及应用的关联配置项

### ISSUE THREAD

**Issue by jackBaozz** [ctripcorp/apollo#1680]
目前有这样的需求场景.

1.springboot启动
在应用的application.properties里面配置了
app.id=10086
apollo.meta=http://xx.xx.xx.xx:18003
apollo.cacheDir=E:/temp/cache
apollo.cluster=default
apollo.bootstrap.enabled=true
apollo.bootstrap.namespaces=application-yml,application,FX.apollo

2.在应用10086的关联namespace里面,我只需要配置需要覆盖公共namespace的配置项比如 service.port=9999 ,其他配置项的都从公共namespace里面获取

3.然后完成本地应用10086的启动流程

以上是需求场景.

但目前用springboot启动,只能默认读取应用 私有的namespace (application.properties) . 如果能指定本地应用10086启动的时候去读取的配置是 apollo上 应用10086, 关联的namespace 感觉也是可行的.

不知道这种场景如何处理?

**Comment by nobodyiam** [comment]
假设公共namespace有`public1`和`public2`，那么

设置`apollo.bootstrap.namespaces=application,public1,public2`即可。

**Comment by jackBaozz** [comment]
> 假设公共namespace有`public1`和`public2`，那么
> 
> 设置`apollo.bootstrap.namespaces=application,public1,public2`即可。

可能我描述的不是太清楚.目前我这个测试模块启动配置是这样的


这个这个应用在apollo的配置是这样的
![1](https://user-images.githubusercontent.com/5772152/48745265-b1b52d80-eca5-11e8-9b19-068c89683c34.jpg)

我目前就想让程序启动时候加载的配置直接读取这个 关联的dev.app-public-config.properties而不是读私有的application.properties
![2](https://user-images.githubusercontent.com/5772152/48745273-bbd72c00-eca5-11e8-8d0f-ff8817a9468c.jpg)


PS 按着你说的这种配置方法无效,依然读的是私有的application.properties

**Comment by nobodyiam** [comment]
到[ApolloApplicationContextInitializer.initialize](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/boot/ApolloApplicationContextInitializer.java#L93)加个断点看看，按照程序逻辑是会读取application和dev.app-public-config.properties的，除非运行时的`apollo.bootstrap.namespaces`配置被覆盖了。

**Comment by jackBaozz** [comment]
> 到[ApolloApplicationContextInitializer.initialize](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/boot/ApolloApplicationContextInitializer.java#L93)加个断点看看，按照程序逻辑是会读取application和dev.app-public-config.properties的，除非运行时的`apollo.bootstrap.namespaces`配置被覆盖了。

![image](https://user-images.githubusercontent.com/5772152/48776374-ae07c200-ed0a-11e8-8480-102801dea803.png)
不好意思, 暂时跟踪的时候看到这里已经加载了配置的namespace且配置项已经都到ConfigurableEnvironment里面去了. 接下来如何加载让springboot启动还没看到源码怎么处理的. 
但不知道为何 同一个配置项比如server.port=9999 , 生效的都是application.properties这个namespace里面的?


另做了个极端的实验, 把这个10086应用在apollo上的application.properties以及本地的缓存文件10086+default+application.properties 都删除了 .
就算我在启动的配置项上配置了
`app.id=10086
apollo.meta=http://10.5.51.43:18003
apollo.cacheDir=E:/temp/cache
apollo.cluster=default
apollo.bootstrap.enabled=true
#apollo.bootstrap.namespaces=application,application-yml,FX.apollo
apollo.bootstrap.namespaces=application-yml`
springboot启动的时候也没有加载application-yml里面的配置项,能让应用启动成功.

给我的感觉
`apollo.bootstrap.namespaces=application-yml`这个只是 namespace是否获取,与springboot启动获取的本地application.properties无关. springboot应用启动默认或者优先级最高的就是apollo上的这个应用的叫 application.properties的namespace

**Comment by nobodyiam** [comment]
看看是否有其它地方注入`application.properties`，比如是否有`@EnableApolloConfig`？

**Comment by jackBaozz** [comment]
> 看看是否有其它地方注入`application.properties`，比如是否有`@EnableApolloConfig`？

![image](https://user-images.githubusercontent.com/5772152/48875339-6e88c500-ee33-11e8-942b-b1633751123d.png)
确实有一个这个注解填写了 application , 但是如果是没有包括 application, 比如我只填写下面图的这一个,项目是直接启动不了的(在apollo上面 application和application-yml内容一样,只是一个是properties另一个是yml格式)
![image](https://user-images.githubusercontent.com/5772152/48875364-a132bd80-ee33-11e8-8e48-655488bd53c9.png)

我本项目把apollo的配置填写在本应用的`application.properties`里面. 设想的情况是当应用启动的时候去拉取apollo上面的这个10086应用的`application-yml.yml`这个里面的配置信息,但目前发现`@EnableApolloConfig`只能配置为`application`才能正常启动应用

**Comment by nobodyiam** [comment]
非properties格式的namespace目前不支持和spring集成，详见[获取非properties格式namespace的配置](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#314-%E8%8E%B7%E5%8F%96%E9%9D%9Eproperties%E6%A0%BC%E5%BC%8Fnamespace%E7%9A%84%E9%85%8D%E7%BD%AE)

**Comment by nobodyiam** [comment]
到[PropertySourcesProcessor.initializePropertySources](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/config/PropertySourcesProcessor.java#L63)调试一下就知道了

**Comment by jackBaozz** [comment]
看了几天源码 启动客户端项目的时候,客户端启动加载的配置是根据`apollo.bootstrap.namespaces=application,application2,application3`
的配置按顺序加载,且取第一个.

目前根据我这边boss的需求,把所有与这个应用有关的配置项全部都合并到application里面了,再返回给客户端拉取的请求结果集里面了. 顺便还加了几个接口到OpenAPI模块里.

多谢指导

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by skyyan2000** [comment]
我也碰到相同了问题了，请问楼主如何处理的
