### ISSUE TITLE
关于server.tomcat配置的疑问

### ISSUE THREAD

**Issue by zollty** [ctripcorp/apollo#1682]
我看只配置了
server.tomcat.accept-count=5000
却没有配置
server.tomcat.max-threads=？
默认最大线程是200，由于是异步长连接方式处理，server端线程长时间不会释放（DeferredResult的超时时间为60秒），如果客户端非常多，这200个线程被瞬间占满，剩下4800个会被卡在阻塞队列里面（注意到，如果要等60秒才能得到处理，那么这4000多个请求何时才能处理完，而且每个请求都是有超时时间的，恐怕还没轮到处理就已经超时了）
为了印证，我特意查看了tomcat的源代码，并做了实验。
线程池处理请求的关键代码如下：
```java
while (running) {
    ...    
    //if we have reached max connections, wait
    countUpOrAwaitConnection(); //先检查maxConnections，达到最大值则等待
 
    ...
    // Accept the next incoming connection from the server socket
    socket = serverSock.accept();
 
    ...
    processSocket(socket); // 线程异步处理（实际上调用Executor.execute(sc) ）
 
    ...
    countDownConnection(); //计数-1
    closeSocket(socket);
}

void processSocket(SocketWrapperBase<S> socket) {
    SocketProcessorBase<S> sc = createSocketProcessor(socket);
    Executor executor = getExecutor();
    executor.execute(sc); // 交给线程池执行
    ...
}
```

对于Apollo这样的系统，如果客户端连接很多（超过200个），是否应该把tomcat.max-threads也设置大一点？

**Comment by nobodyiam** [comment]
async servlet和普通的servlet不一样的，async servlet只会占连接，不会占tomcat线程，可以看一下[Asynchronous Processing](https://docs.oracle.com/javaee/7/tutorial/servlets012.htm)

**Comment by zollty** [comment]
多谢解答。之前我已有了解过 AsyncServlet。    
这篇文章我也看了，只是它没有说明底层的实现原理，    

如何能不占线程？据我了解，即便是wait状态，仍然是会占线程的，    

所以，这个异步处理，不是简单的把线程wait，    

我想请求的线程已经释放了、回归到了线程池，但请求的状态被保存了起来，以便处理完成后由其他线程继续完成响应。    

但是目前我从Tomcat的源码中还没找到这段代码，以后再看吧。    

问题先关了，再次感谢！

**Comment by nobodyiam** [comment]
差不多是你理解的样子，具体可以看`org.apache.catalina.core.AsyncContextImpl`和`org.apache.coyote.http11.Http11Processor`

**Comment by ZJRui** [comment]
> 多谢解答。之前我已有了解过 AsyncServlet。 这篇文章我也看了，只是它没有说明底层的实现原理，
> 
> 如何能不占线程？据我了解，即便是wait状态，仍然是会占线程的，
> 
> 所以，这个异步处理，不是简单的把线程wait，
> 
> 我想请求的线程已经释放了、回归到了线程池，但请求的状态被保存了起来，以便处理完成后由其他线程继续完成响应。
> 
> 但是目前我从Tomcat的源码中还没找到这段代码，以后再看吧。
> 
> 问题先关了，再次感谢！

由tomcat工作线程把AsyncContext对象传递给业务处理线程，同时tomcat工作线程归还到工作线程池，这一步就是异步开始
开启业务逻辑处理线程，并将AsyncContext 传递给业务线程。executor.execute(new AsyncRequestProcessor(asyncCtx, secs));
