### ISSUE TITLE
portal出现收藏的项目无法展示在首页

### ISSUE THREAD

**Issue by sunnyvinson** [ctripcorp/apollo#1684]
收藏了几个项目，但是不显示在首页
![image](https://user-images.githubusercontent.com/13216698/48704371-4df11d00-ec31-11e8-9dbc-780f7b668595.png)
点击之后
![image](https://user-images.githubusercontent.com/13216698/48704385-59dcdf00-ec31-11e8-9bfc-e9c416ed34dd.png)

**Comment by nobodyiam** [comment]
看看F12是否有报错啥的？

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
