### ISSUE TITLE
applicaion.properties挪到application命名空间的问题

### ISSUE THREAD

**Issue by ruanxingshi** [ctripcorp/apollo#1687]
原来项目里的applicaion.properties的内容有关于发送邮件的配置：
spring.mail.host=smtp.exmail.qq.com
spring.mail.username=*******
spring.mail.password=*****
spring.mail.port=*****
应用启动是正常的，我挪到application命名空间启动就报错了：
APPLICATION FAILED TO START

Description:

Field javaMailService in com.skc.core.communication.email.SampleEmailServiceImpl required a bean of type 'org.springframework.mail.javamail.JavaMailSender' that could not be found.
- Bean method 'mailSender' not loaded because AnyNestedCondition 0 matched 2 did not; NestedCondition on MailSenderAutoConfiguration.MailSenderCondition.JndiNameProperty @ConditionalOnProperty (spring.mail.jndi-name) did not find property 'jndi-name'; NestedCondition on MailSenderAutoConfiguration.MailSenderCondition.HostProperty @ConditionalOnProperty (spring.mail.host) did not find property 'host'

Action:

Consider revisiting the conditions above or defining a bean of type 'org.springframework.mail.javamail.JavaMailSender' in your configuration.

**Comment by iluoxuan** [comment]
bootstrap阶段注入，就可以了

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
