### ISSUE TITLE
Rancher+Docker部署成功后，configservice和adminservice频繁重启，导致portal不能正常工作，请大神指教

### ISSUE THREAD

**Issue by CaseyGit** [ctripcorp/apollo#1689]
![image](https://user-images.githubusercontent.com/44695991/48760786-ed6de880-ece1-11e8-9987-d63696252b82.png)
我是修改了startup.sh的源码，
![image](https://user-images.githubusercontent.com/44695991/48760824-18f0d300-ece2-11e8-910e-91aafd9a050a.png)
87行为大神源码，但是在我运行过程中在这一行始终无法启动,jar
然后改为了88行的代码。config/admin/portal都修改了
就这样部署成功了可以正常启动，
![image](https://user-images.githubusercontent.com/44695991/48761009-88ff5900-ece2-11e8-9f7b-09dcc8403e41.png)
![image](https://user-images.githubusercontent.com/44695991/48761032-961c4800-ece2-11e8-9570-3bdca281949d.png)
但是config和admin会因为我添加的第88行代码而频繁重启（非常频繁，几乎是刚启动成功就重启），因为老是重启，portal只有偶尔才能找到config和admin，，请问大神这是为什么呀。恳请大神指教

**Comment by CaseyGit** [comment]
仔细看了日志，启动config和admin失败，
![image](https://user-images.githubusercontent.com/44695991/48761369-6d488280-ece3-11e8-945a-6bf5b43d3b74.png)
大神您帮我看一下是不是我哪里错误了。

**Comment by CaseyGit** [comment]
![image](https://user-images.githubusercontent.com/44695991/48763503-65d7a800-ece8-11e8-8c57-e5006d080453.png)
在自己虚拟机上用同样dockerfile 打出configservice镜像并启动，没有出现这样的情况，

**Comment by CaseyGit** [comment]
![image](https://user-images.githubusercontent.com/44695991/48765974-58bdb780-ecee-11e8-9bab-cad5c6868052.png)
还会chuxia出现这个error

**Comment by nobodyiam** [comment]
不能修改为java -jar的，因为这样就变成前台启动了，默认的启动方式是后台启动的。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
