### ISSUE TITLE
环境变量设置PRO 获取到的还是DEV的值

### ISSUE THREAD

**Issue by chlin7** [ctripcorp/apollo#1690]
配置了启动环境变量为PRO，但是实际获取到的值还是DEV的值，麻烦咨询一下，是哪里配置有问题。
（在Protal管理界面已经可以管理DEV和PRO两种类型的值了）
以下是启动打印日志：
Environment is set to [PRO] by JVM system property 'env

**Comment by nobodyiam** [comment]
可以打开客户端debug日志，看看实际连接的meta server和config service是不是pro的
