### ISSUE TITLE
open api java client能否提供查询接口？

### ISSUE THREAD

**Issue by nzomkxia** [ctripcorp/apollo#1691]
目前在做Dubbo控制台：https://github.com/apache/incubator-dubbo-ops，其中需要对配置进行读写操作。在对apollo平台做适配时，发现open api java client没有单个key的查询接口，请问能否提供一下，谢谢。

**Comment by nobodyiam** [comment]
apollo的模型和zk不太一样，zk是基于path(key)来管理和推送配置的，apollo是基于appId + cluster + namespace的。

所以用户在通过apollo管理dubbo配置的时候，是需要提供namespace以及对应的认证token的。

dubbo-ops具体是希望实现一个什么样的场景？

**Comment by nzomkxia** [comment]
Dubbo的服务治理规则会放在配置中心，用户在Dubbo Ops上做服务治理：有规则的写入和读取两种操作，目前open api java client可以进行写配置的操作，但是没有读取单个配置的接口，所以希望能提供，谢谢。

**Comment by nobodyiam** [comment]
可以使用 [ApolloOpenApiClient.getNamespace](https://github.com/ctripcorp/apollo/blob/master/apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/client/ApolloOpenApiClient.java#L71)获取该namespace下所有的配置，后续我们加一个获取单个配置的接口~

**Comment by nzomkxia** [comment]
好的，谢谢

**Comment by nobodyiam** [comment]
增加了获取单个配置的接口，详见[ApolloOpenApiClient.getItem](https://github.com/ctripcorp/apollo/blob/master/apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/client/ApolloOpenApiClient.java#L96)，会在1.2.0版本发布（预计12月初）

**Comment by nobodyiam** [comment]
[1.2.0](https://github.com/ctripcorp/apollo/releases/tag/v1.2.0)版本已经发布，增加了获取单个配置的接口。

**Comment by nzomkxia** [comment]
谢谢

**Comment by Leowuqunqun** [comment]
@nobodyiam  是否可以提供一个获取多个项目 多个key的接口？
