### ISSUE TITLE
configservice和adminservice注册到统一的Eureka后，无法获取/info /health信息

### ISSUE THREAD

**Issue by lihongzheng001** [ctripcorp/apollo#1693]
![image](https://user-images.githubusercontent.com/44185425/48816878-e21cca80-ed7e-11e8-9692-b04cb61c0d29.png)
![image](https://user-images.githubusercontent.com/44185425/48816890-f2cd4080-ed7e-11e8-84dc-f9d0747c3172.png)

**Comment by nobodyiam** [comment]
看看config service和admin service的启动日志，是否有映射/info和/health？默认都是有的

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
