### ISSUE TITLE
关于apollo权限管控的问题

### ISSUE THREAD

**Issue by lucissfer** [ctripcorp/apollo#1695]
在使用过程中发现apollo的用户权限管控做的不是很到位，没有用户分组的概念；
我们当前的部署架构是一个portal管理所有环境（包括生产环境），给开发创建了一个账号后，开发就可以直接创建项目，默认成为这个项目的管理员并同时拥有这个项目所有环境的配置发布权限，这样一来就意味着开发可以直接修改生产环境的配置，这对于运维来说是不可接受的。
请教一下，如果需要对开发的账号做权限限制，仅允许开发人员对开发、测试环境拥有配置修改、发布权限应该如何设置呢？

**Comment by nobodyiam** [comment]
可以让运维创建项目，设置项目管理员。

之前有些公司的实践是修改了apollo的代码，只允许超级管理员创建app，这块后续可以考虑提交一个PR，作为一个可选功能使用

**Comment by steveguoshao** [comment]
权限这一块还真的需要细化，不同人看一个项目不同环境的不同的命名空间，没有权限的人不能搜索到项目，现在是没有权限的人也能搜索到项目

**Comment by nobodyiam** [comment]
@steveguoshao，可以参考[配置查看权限](https://github.com/ctripcorp/apollo/wiki/Apollo%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#%E5%85%AD%E5%85%B6%E5%AE%83%E5%8A%9F%E8%83%BD%E9%85%8D%E7%BD%AE)

**Comment by cws1981** [comment]
权限是否可以细化到某一个key级别，比如有的配置如数据库帐号密码，不希望被看到，有的业务配置可以让开发自己去添加。就同一个命名空间 不同配置项权限不一样。

**Comment by nobodyiam** [comment]
目前的模型不支持到key级别的
