### ISSUE TITLE
关于对application.yml格式支持

### ISSUE THREAD

**Issue by chlin7** [ctripcorp/apollo#1698]
麻烦咨询一下，现在对于application.yml格式支持了吗，是否和application.properties保持同步了，谢谢

**Comment by nobodyiam** [comment]
暂时还没有，关注下 #653 吧

**Comment by lishangzhi** [comment]
application.yml 现在还没有支持么？

**Comment by nobodyiam** [comment]
我新开了一个PR #1944，支持yml类型的namespace注入到Spring中去，大家可以看一下~

**Comment by nobodyiam** [comment]
[1.3.0](https://github.com/ctripcorp/apollo/releases/tag/v1.3.0)版本已经发布，支持了Yml/Yaml格式的namespace和Spring/Spring Boot集成。
