### ISSUE TITLE
一台服务器上部署多个相同的应用，如何区分

### ISSUE THREAD

**Issue by jackythao** [ctripcorp/apollo#1702]
你好，我的一个应用app1需要在一台服务器上部署多个实例，用不同的端口来区分，这样在apollo的portal上如何能区分不同的实例呢？谢谢

**Comment by nobodyiam** [comment]
目前只支持通过appId+ip来区分

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
