### ISSUE TITLE
spring-test多个test context

### ISSUE THREAD

**Issue by KKKIIO** [ctripcorp/apollo#1703]
```java
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration
public class Test1 {
    @Value("${prop1}")
    String prop1;

    @Test
    public void test1() {
        System.out.println("prop1 = " + prop1);
    }

    @EnableApolloConfig({"namespace1"})
    @Configuration
    static class Config1 {
    }
}
```
```java
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration
public class Test2 {
    @Value("${prop2}")
    String prop2;

    @Test
    public void test() {
        System.out.println("use2.prop2 = " + prop2);
    }

    @EnableApolloConfig({"namespace2"})
    @Configuration
    static class Config2 {
    }
}
```
单独运行任一测试都没问题，用maven运行所有测试就会出现获取不到prop2的问题，如果多个测试使用同一配置也没问题（spring缓存test context），请问这是bug吗？或者正确的测试方式是什么？

**Comment by nobodyiam** [comment]
要标记`@ DirtiesContext`吧，参考 https://github.com/ctripcorp/apollo/blob/f79f1ac719068a69d25a70663d9be412090b7400/apollo-client/src/test/java/com/ctrip/framework/apollo/spring/BootstrapConfigTest.java#L48

**Comment by KKKIIO** [comment]
> 要标记`@ DirtiesContext`吧，参考
> 
> [apollo/apollo-client/src/test/java/com/ctrip/framework/apollo/spring/BootstrapConfigTest.java](https://github.com/ctripcorp/apollo/blob/f79f1ac719068a69d25a70663d9be412090b7400/apollo-client/src/test/java/com/ctrip/framework/apollo/spring/BootstrapConfigTest.java#L48)
> 
> Line 48 in [f79f1ac](/ctripcorp/apollo/commit/f79f1ac719068a69d25a70663d9be412090b7400)
> 
>  public static class TestWithBootstrapEnabledAndDefaultNamespacesAndConditionalOn extends

我试过在Test1和Test2 class上加`@DirtiesContext`，还是一样的错，我从spring文档中理解的`@DirtiesContext`应该是控制context cache的，而不同`@Configuration`spring是不会做cache的，想请教一下，我是哪里理解错了或遗漏了？

**Comment by nobodyiam** [comment]
我在本地试了一下，使用和你相同的程序，不加`@DirtiesContext`也都是OK的，没有问题。

<img width="1001" alt="config" src="https://user-images.githubusercontent.com/837658/48967832-71e1a380-f021-11e8-91e5-681af072e820.png">

![test](https://user-images.githubusercontent.com/837658/48967834-7908b180-f021-11e8-8d73-314a01791b9a.png)

**Comment by KKKIIO** [comment]
刚刚做了几次测试，我发现用了1.1.0版本以上的apollo-client就没有问题，而1.0.0及以下的会出现问题，而公司用的是没在maven官方仓库的0.10.2.1-RELEASE版本，尴尬

**Comment by nobodyiam** [comment]
恩，那就能说通了，多spring context支持是在[1.1.0](https://github.com/ctripcorp/apollo/releases/tag/v1.1.0)加入的
