### ISSUE TITLE
目前开发环境都需要将每个应用修改vm参数，可以从配置文件读取vm参数么

### ISSUE THREAD

**Issue by it-noob** [ctripcorp/apollo#1705]
目前开发环境如果要集成使用，需要配置`-Denv=DEV -Ddev_meta=http://localhost:8080`来在springboot应用启动时，知道从dev_meta获取配置信息，个人感觉使用体验和风格不太优雅，是否可以改为读取配置文件中，类似于springboot的获取激活当前什么环境配置文件一样。否则，团队中其他人拉去代码，都需要在各自的开发环境的启动命令里，配置vm参数来设置系统环境变量，略感繁琐

**Comment by nobodyiam** [comment]
从1.0.0版本支持通过spring boot的配置文件来配置meta server地址的，把apollo.meta放在application-{profile}.properties中即可，详见[1.2.2 Apollo Meta Server](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#122-apollo-meta-server)

**Comment by it-noob** [comment]
抱歉，文档没读完就来乱发issue。谢谢作者大大回复。
