### ISSUE TITLE
如何获取apollo-client连接状态

### ISSUE THREAD

**Issue by hw-mm-payment** [ctripcorp/apollo#1708]
集成了apollo配置中心后，想要提供监控的机制，当在应用启动时，如果apollo客户端连接不上config service，或者应用启动后，config service不可用，能够获取客户端的连接状态，提供告警的机制。
     或者有更好的方法吗？

**Comment by nobodyiam** [comment]
可以通过[Config.getSourceType](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/Config.java#L221)判断

**Comment by hw-mm-payment** [comment]
谢谢~之前使用的是1.0.0版本，所以没有找到该方法。
