### ISSUE TITLE
关于adminservice权限的问题

### ISSUE THREAD

**Issue by ihoping** [ctripcorp/apollo#1709]
你好，我这边看到apollo-adminservice中好像并没有做权限管理，只有门户portal做了权限管理，那是不是说任何人都可以绕过8070(protal)直接调用8090(adminservice)来修改配置呢

**Comment by CharkeyQK** [comment]
参考这个： #1498

**Comment by nobodyiam** [comment]
内网应用的安全级别和外网应用是不一样的，如果有这方面需求，可以通过防火墙控制

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
