### ISSUE TITLE
【server端推送配置更新到客户端失败，报错】

### ISSUE THREAD

**Issue by sunnyvinson** [ctripcorp/apollo#1712]
你好！
      今天在使用上遇到一个问题：
      apollo server端是用docker形式运行起来的，在portal上修改配置后，c++客户端无法接收到server端推送的更新消息，抓包后发现报400错误 bad request；但是直接用jar形式运行服务端，c++客户端是可以接收到server端推送的更新消息，然后我通过监听事件触发后，把新配置写入到文件里

       烦请帮忙解惑下，感谢

**Comment by sunnyvinson** [comment]
抓包截图
![image](https://user-images.githubusercontent.com/13216698/49085687-8924c900-f28d-11e8-8ead-8fe2513baeb2.png)

**Comment by nobodyiam** [comment]
url中的参数要做encoding的，截图中的`notifications=[{"namespaceName":"application","notificationId":0}]`这个value没有做encoding吧

**Comment by nobodyiam** [comment]
就是普通的url encoding，比如应该是`notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A0%7D%5D`

**Comment by sunnyvinson** [comment]
谢谢，已经解决

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
