### ISSUE TITLE
apollo 注册到自定义的eureka，如何从自定义eureka端拿到注册的apollo服务地址

### ISSUE THREAD

**Issue by hylhaha** [ctripcorp/apollo#1713]
apollo 注册到自定义的eureka，如何从自定义eureka端拿到注册的apollo服务地址，而不是直连配置中心的config服务地址

**Comment by nobodyiam** [comment]
参考一下[DiscoveryService](https://github.com/ctripcorp/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/metaservice/service/DiscoveryService.java)

**Comment by hylhaha** [comment]
没太看懂这段代码，能否指点一二，给些思路？

**Comment by nobodyiam** [comment]
代码就是从eureka获取config service等的地址，这个是eureka的范畴了，建议看下spring cloud netflix中和eureka相关的文档说明

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
