### ISSUE TITLE
public namespace怎么管理？

### ISSUE THREAD

**Issue by wingyiu** [ctripcorp/apollo#1716]
哪里修改公共的值呢？怎么看出哪个是关联的namespace呢？怎么区分覆盖前后的值呢？

**Comment by ferry1376122** [comment]
这个问题我也迷糊了很久，不过搞清楚了。
所谓的公共namespace其实是跟着应用走的，也就是在A应用下创建的public namespace是在A应用下的，那么A应用是没有办法关联本身的公共namespace，直接修改这个公共的namespace即可。当有B应用需要使用A创建的public namespace的时候，做关联才会看到关联相关配置。

**Comment by nobodyiam** [comment]
参考一下[Apollo核心概念之“Namespace”](https://github.com/ctripcorp/apollo/wiki/Apollo%E6%A0%B8%E5%BF%83%E6%A6%82%E5%BF%B5%E4%B9%8B%E2%80%9CNamespace%E2%80%9D)

1. 哪里修改公共的值呢？ 
如果是修改全局的，那么就修改公共namespace下的配置。如果只修改某个应用的，那么关联公共namespace后再做覆盖。

2. 怎么看出哪个是关联的namespace呢？
公共namespace在页面上会显示公共两个字，关联的会显示关联两个字

3. 怎么区分覆盖前后的值呢？
在配置界面上可以区分，在客户端拿到配置时只有一个值，没法区分

**Comment by ferry1376122** [comment]
按照我说的  你到b应用下新建namespace  关联a创建的公共的 namespace  然后在b的界面你就可以看到了

**Comment by ferry1376122** [comment]
[](https://github.com/ferry1376122/learngit/blob/master/QQ%E5%9B%BE%E7%89%8720181129103647.png)
[](https://github.com/ferry1376122/learngit/blob/master/QQ%E5%9B%BE%E7%89%8720181129103804.png)

**Comment by ferry1376122** [comment]
![image](https://github.com/ferry1376122/learngit/blob/master/QQ%E5%9B%BE%E7%89%8720181129103647.png)
![image](https://github.com/ferry1376122/learngit/blob/master/QQ%E5%9B%BE%E7%89%8720181129103804.png)

**Comment by nobodyiam** [comment]
可以看一下 http://106.12.25.204:8070/

如果有不清楚的，可以在上面这个环境中创建项目，演示你的问题

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
