### ISSUE TITLE
两台apollo做集群发布应用冲突

### ISSUE THREAD

**Issue by yuynagforhacker** [ctripcorp/apollo#1718]
你好，我在两台服务器上搭建apollo全环境
IP：111，112
在111上开启adminserver、configserver、portalserver
在112上开启adminserver、configserver
两台服务器分别用各自的mysql，eureka指向两个服务器IP

成功启动后，在111portal上发布test项目和未发布test1项目，强制刷新portal页面的时候发现冲突，时而是test项目发布，时而test项目未发布，时而出现test1，怀疑是eureka冲突了，但是怎么解决？
尝试将112的eureka指定为client，但是在build的时候会报错

**Comment by yuynagforhacker** [comment]
111上重启了configserver后恢复稳定，不知道是不是因为重启的原因还是因为两台eureka同步好了

**Comment by nobodyiam** [comment]
打开管理员工具 - 系统信息看看，多数是不同环境的服务都注册到同一个eureka上去了

**Comment by yuynagforhacker** [comment]
> 打开管理员工具 - 系统信息看看，多数是不同环境的服务都注册到同一个eureka上去了

环境: DEV、FAT、UAT、PRO
Active: true
Meta server地址: http://192.168.103.111:8080,http://192.168.103.112:8080
并且check都没有问题，项目构建的时候是4个环境全勾选了，按理说应该是4个都能出现，但是还是会有不稳定的情况发生，是不是两个eureka没有同步？连接发生冲突，在抢master？

**Comment by nobodyiam** [comment]
不是只有两个环境吗，为啥系统信息有4个环境？

部署文档参考分布式部署文档，或者建议看一下视频吧 - https://pan.baidu.com/s/1rUAphfVq9fnEMqRrscDk-w#list/path=%2F%E5%88%B6%E4%BD%9C%E8%A7%86%E9%A2%91%2Fapollo&parentPath=%2F%E5%88%B6%E4%BD%9C%E8%A7%86%E9%A2%91

**Comment by yuynagforhacker** [comment]
是测试环境用的，全部指向了两台服务器的8080，这样做会有影响吗？因为部署的时候测试不想用太多服务器，而想体验多环境分布式部署，所以采用了现在这么个折中的办法

**Comment by nobodyiam** [comment]
所以是两个物理环境，4个逻辑环境？其中两个环境是重复的？

**Comment by yuynagforhacker** [comment]
是这个意思，准确的说应该是只有一个环境，4个逻辑环境，因为4个meta指向都是这两台服务器。设计理念是这样的，开始是想用独立的eureka，后来实现起来有难度，要考虑兼容性的问题，改用两个apollo内置的eureka，因为是运维环境没有spring框架，想用apollo来搭建起简易的eureka集群来体验apollo分布式集群的部署，现在问题就是出在搭建后应用发布变化的问题

**Comment by nobodyiam** [comment]
4个meta指向两台服务器，但是两台服务器又分别连接了两个数据库？那这样的话，是会出现你所描述的现象。

建议参考一下[1.3、环境](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#13%E7%8E%AF%E5%A2%83)

**Comment by yuynagforhacker** [comment]
数据库指向如果是指向同一个portalDB和各自的configDB这样是不是也会有问题？那么实际的MySQL指向应该是怎么样的？这个图说实话我没太看懂，我理解的是所有环境指向同一个portalDB，然后每个Apollo都用自己的configDB，但是还是会有这个问题，是一个环境使用一个数据库吗？大佬能细讲一下这个环境图吗？

**Comment by yuynagforhacker** [comment]
现在我已经部署好了，基本上稳定了，目前的架构是一个portal作为管理，管理两个环境，地址为111，4台服务器的portalDB全部指向111，dev环境的eureka为111，112，pro环境eureka为113，114，每个环境各使用一个configDB，这样就稳定多了，避免了那个现象，但是有时发布会过慢，查看CPU并不高，不知道是不是和这种架构有关？

**Comment by yuynagforhacker** [comment]
多谢大佬答疑，后期有问题还得请教您

**Comment by nobodyiam** [comment]
这个理论上是可以的，不过对mysql运维就提出要求了
