### ISSUE TITLE
关联pulic namespace 修改不能实时部署吗？

### ISSUE THREAD

**Issue by ferry1376122** [ctripcorp/apollo#1719]
我把testcase路由的测试案例中的配置文件建立个公共的namespace在logger项目下，然后zuul项目关联该public namespace，我在zuul项目启动后修改了zuul.routes.test.url的地址，再刷新页面没有跳转。没有实时更新。

**Comment by nobodyiam** [comment]
项目中需要引用该公共namespace

**Comment by ferry1376122** [comment]
大神还在吗？问个问题  我理解的公共的namespace是跟着应用走的 对吗？那么如果这个应用修改或者删除这个namespace  岂不是会影响所有使用这个公共namespace的应用？

**Comment by nobodyiam** [comment]
是的，所以公共namespace无法随便删除的

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by AF-lmf** [comment]
我也发现了相同的问题，不知道是自己的操作有误还是什么情况；

**Comment by AF-lmf** [comment]
我也发现了相同的问题，不知道是自己的操作有误还是什么情况；
目前尝试了1.6.1和1.6.0两个版本。
在使用项目私有的配置文件时，数据源配置修改是可以被监听到并且完成热加载的；但是在使用关联的公共配置时，数据源配置修改无法被监听到。

**Comment by AF-lmf** [comment]
> 我也发现了相同的问题，不知道是自己的操作有误还是什么情况；
> 目前尝试了1.6.1和1.6.0两个版本。
> 在使用项目私有的配置文件时，数据源配置修改是可以被监听到并且完成热加载的；但是在使用关联的公共配置时，数据源配置修改无法被监听到。

难道是关联的公共配置不支持实时加载嘛？

**Comment by nobodyiam** [comment]
@AF-lmf 实时加载是在客户端实现的，对客户端而言，它不感知 namespace 是私有的还是公共的，所以建议在客户端打开 debug 日志看看配置加载和更新的过程是否有问题

**Comment by AF-lmf** [comment]
> @AF-lmf 实时加载是在客户端实现的，对客户端而言，它不感知 namespace 是私有的还是公共的，所以建议在客户端打开 debug 日志看看配置加载和更新的过程是否有问题

您好，首先感谢您能回复，看到你的建议后我打开了客户端的Debug日志，并且在该客户端关联的公共namespace下覆盖了原有配置，但是客户端并没有打印预想中的debug日志，监听配置更新的代码也没有任何响应。

**Comment by nobodyiam** [comment]
@AF-lmf 检查下客户端是否正确配置了需要引入的公共namespace
