### ISSUE TITLE
公共的namespace的问题

### ISSUE THREAD

**Issue by ferry1376122** [ctripcorp/apollo#1721]
我理解的公共的namespace是跟着应用走的 对吗？那么如果这个应用修改或者删除这个namespace 岂不是会影响所有使用这个公共namespace的应用？

**Comment by nobodyiam** [comment]
是的，所以公共namespace无法随便删除的

**Comment by ferry1376122** [comment]
那变更呢？比如公用的namespace所在的应用，就这个应用突然想覆盖这个公用的一个属性  而其他应用又保持不变？这要怎么解决呢？这个应用不能关联  如果修改  只能修改公用namespace本身啊

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
