### ISSUE TITLE
继承dubbo配置不生效

### ISSUE THREAD

**Issue by wingyiu** [ctripcorp/apollo#1722]
com.alibaba.boot:dubbo-spring-boot-starter:0.2.0
springboot 2.0.3-RELEASE
dubbo 2.6.2

META-INFO/app.properties
````
app.id=user
apollo.bootstrap.enabled = true
apollo.meta=http://localhost:8080
env=DEV
apollo.cluster=default
````

不生效啊

**Comment by wingyiu** [comment]
`apollo.bootstrap.enabled = true`放在app.properties是不生效的

**Comment by nobodyiam** [comment]
请参考 https://github.com/ctripcorp/apollo-use-cases/tree/master/spring-boot-dubbo

[文档](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#3213-spring-boot%E9%9B%86%E6%88%90%E6%96%B9%E5%BC%8F%E6%8E%A8%E8%8D%90)里面没说过`apollo.bootstrap.enabled = true`这个是放在app.properties里面啊

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
