### ISSUE TITLE
删除一个配置或者删除整个propertity的属性为什么项目依然能正常启动？

### ISSUE THREAD

**Issue by qingfeng9924** [ctripcorp/apollo#1725]
请问，如题，我删除了项目，同时也删除了本地的缓存文件；client启动依然生效，请问是什么原因呢？

**Comment by qingfeng9924** [comment]
是否和config-service.cache.enabled 这个缓存设置有关系？

**Comment by nobodyiam** [comment]
删除了项目，config service的缓存中也就没有配置了。

项目能否起来和配置是否有没啥关系吧，除非你的项目强依赖配置

**Comment by qingfeng9924** [comment]
感谢您的回复。我的配置里包含了比如数据源相关配置，我在portal端删除项目配置后，重启项目依然能正常运行，不知道数据源这些信息是怎么返回回来的

**Comment by nobodyiam** [comment]
客户端开一下debug日志，能看到配置从哪里来的

**Comment by qingfeng9924** [comment]
正准备从源码debug呢，是通过界面删除的，没有直接操作过数据库
