### ISSUE TITLE
config启动报错

### ISSUE THREAD

**Issue by zndbl** [ctripcorp/apollo#1727]
在阿里云上部署，一切正常，项目都跑起来了，但是在公司的虚拟机上部署config，启动报
![1f5961216a6566c6f02ba140b7f60de](https://user-images.githubusercontent.com/20933115/49227484-287bc480-f424-11e8-8ae1-6ed7df8ef20f.png)

**Comment by nobodyiam** [comment]
有日志信息吗？

**Comment by zndbl** [comment]
好诡异，opt目录下并没有日志文件夹出现

**Comment by zndbl** [comment]
阿里云是centos7,公司的机子是centos6,会和这个有关吗

**Comment by zndbl** [comment]
日志里提示
![1543571423 1](https://user-images.githubusercontent.com/20933115/49281821-85c95180-f4c8-11e8-9bf2-017bf68830a0.jpg)
[](url)
然后更新start-stop-daemon版本，启动就正常了，猜测是低系统版本导致的

**Comment by nobodyiam** [comment]
恩，Spring boot的启动脚本依赖start-stop-daemon

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
