### ISSUE TITLE
我们公司内部有些是使用TDDL的 依赖diamond

### ISSUE THREAD

**Issue by huihui1112** [ctripcorp/apollo#1729]
我们公司内部有些是使用TDDL的 依赖diamond,不知道阿波罗配置中心是否还好和TDDL进行整合呢.

**Comment by nobodyiam** [comment]
tddl默认实现是写死从diamond获取配置的，要接入apollo的话，应该只需要参照[TAtomDsConfHandle](https://github.com/alibaba/tb_tddl/blob/master/tddl-atom-datasource/src/main/java/com/taobao/tddl/jdbc/atom/TAtomDsConfHandle.java)实现一下和配置对接的部分即可

**Comment by huihui1112** [comment]
大佬厉害. 回头研究下! 找到入口就敢动手了 谢谢.

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
