### ISSUE TITLE
spring boot 某些属性设置无效，只能本地设置

### ISSUE THREAD

**Issue by Gold-yuan** [ctripcorp/apollo#1730]
management.endpoint.shutdown.enabled = true
feign.hystrix.enabled = true
这个两个属性放在apollo配置则无效，放在本地的application中就有效。有人遇到过吗，什么情况？

**Comment by Gold-yuan** [comment]
补充说明：下面是actuator配置完整配置，除了management.endpoint.shutdown.enabled = true这个属性无效，其他属性在apollo中配置之后均能正确加载。
`
### actuator配置
# 开启所有端点
management.endpoints.web.exposure.include = shutdown,health,info
# 开启shutdown端点，用于正常停止微服务
management.endpoint.shutdown.enabled = true
# 开启health端点
management.endpoint.health.enabled = true
# 显示health详情
management.endpoint.health.show-details = always
# 设置actratot地址
management.endpoints.web.base-path = /actuator
`

**Comment by nobodyiam** [comment]
是按照 [3.2.1.3 Spring Boot集成方式（推荐）](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#3213-spring-boot%E9%9B%86%E6%88%90%E6%96%B9%E5%BC%8F%E6%8E%A8%E8%8D%90)配置的吗？

**Comment by newpant** [comment]
遇到同样的问题，应该是 **apollo.bootstrap.enabled=true** 这句没有配置或是没有配置到正确的位置。我本来是放在bootstrap.properties里，但没启作用，后来放到application里就正常了。SpringBoot 2.1.0-RELEASE，apollo 1.2.0

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
