### ISSUE TITLE
启动太慢了，链接metaServer时间太长

### ISSUE THREAD

**Issue by panGod** [ctripcorp/apollo#1735]
![image](https://user-images.githubusercontent.com/25611131/49356382-8a7b4900-f706-11e8-90aa-77484fc45cd8.png)
正常启动只需要5秒，在Located meta server address http://localhost:8080 的时候所花费的时间大概在15s左右，请问是否哪里配置的问题导致建立连接的速度慢了

**Comment by nobodyiam** [comment]
打开debug日志，看一下详细信息

**Comment by sxyseo** [comment]
这边本地开发环境，启动时间也挺长的，等好几分钟。
同时集成了Cat。不知道是apollo的等待时间长，还是Cat连服务端费时。
麻烦帮忙看看，感谢。
![apollo_1](https://user-images.githubusercontent.com/8522164/50507154-2bb3b000-0ab7-11e9-850d-713a5484a454.png)
![apollo_2](https://user-images.githubusercontent.com/8522164/50507430-86014080-0ab8-11e9-94b2-2a91076ee817.png)

**Comment by nobodyiam** [comment]
看上去是连CAT慢

**Comment by sxyseo** [comment]
@nobodyiam 

> 看上去是连CAT慢

将Cat从项目中移除后，发现还是会在获取配置的时候停留1分钟左右。
是否是apollo获取配置的方式不对？还是其他原因导致？
![apollo_20190107153528](https://user-images.githubusercontent.com/8522164/50754872-1e09e180-1292-11e9-9ebe-a01305185b90.png)

**Comment by sxyseo** [comment]
> @nobodyiam
> 
> > 看上去是连CAT慢
> 
> 将Cat从项目中移除后，发现还是会在获取配置的时候停留1分钟左右。
> 是否是apollo获取配置的方式不对？还是其他原因导致？
> ![apollo_20190107154333](https://user-images.githubusercontent.com/8522164/50755147-1ac32580-1293-11e9-9d53-9f4b85627598.png)

看到日志 无法找到meta server address

> Could not find meta server address, because it is not available in neither (1) JVM system property 'apollo.meta', (2) OS env variable 'APOLLO_META' (3) property 'apollo.meta' from server.properties nor (4) property 'apollo.meta' from app.properties

是否是配置方式的问题？

**Comment by sxyseo** [comment]
换成JVM system的方式还是需要停留1分钟左右。

![apollo_20190107160331](https://user-images.githubusercontent.com/8522164/50756027-d1280a00-1295-11e9-9568-c9635302b624.png)

**Comment by sxyseo** [comment]
> 是否有很多网卡之类的？之前有遇到过WINDOWS台式机由于有很多虚拟网卡，导致获取hostname很慢 - https://github.com/ctripcorp/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/foundation/internals/NetworkInterfaceManager.java#L46

非常感谢，目前环境是windows，确实存在很多虚拟网卡，大概有10多个（安装了VM，Docker等等虚拟机）难怪比同事的机器慢那么多。应该就是这个问题。

通过计算权重，最后得出来的ip地址不是本地物理网卡的ip。

![apollo_20190108134259](https://user-images.githubusercontent.com/8522164/50811937-a5675b80-134b-11e9-97a0-fd962c84044a.png)

**Comment by sxyseo** [comment]
> > 是否有很多网卡之类的？之前有遇到过WINDOWS台式机由于有很多虚拟网卡，导致获取hostname很慢 - https://github.com/ctripcorp/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/foundation/internals/NetworkInterfaceManager.java#L46
> 
> 非常感谢，目前环境是windows，确实存在很多虚拟网卡，大概有10多个（安装了VM，Docker等等虚拟机）难怪比同事的机器慢那么多。应该就是这个问题。
> 
> 通过计算权重，最后得出来的ip地址不是本地物理网卡的ip。
> 
> ![apollo_20190108134640](https://user-images.githubusercontent.com/8522164/50811989-da73ae00-134b-11e9-9d4c-0343624af8a5.png)

由于是开发环境，所有这个问题目前的解决方案是，禁用不需要的虚拟网卡（有需要的时候再启用），启动项目时间明显缩短，
非常感谢。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by zhongyong** [comment]
感谢，我把vm网卡关闭启动快多了。

**Comment by mingge007** [comment]
启动太慢 问题依然在，linux 两个网卡也慢

**Comment by mingge007** [comment]
![image](https://user-images.githubusercontent.com/24642365/93956767-7c883380-fd85-11ea-9388-18b92149e6e2.png)

**Comment by nobodyiam** [comment]
@mingge007 

看一下客户端版本，在 #2152 提交过这块的性能优化
