### ISSUE TITLE
关于apollo 配置管理中心敏感信息加密的问题

### ISSUE THREAD

**Issue by xunxiaoying** [ctripcorp/apollo#1736]
您好！
  公司准备使用apollo配置中心，现在需要把现有的Spring mvc 的配置移植到apollo配置中心管理，原项目对数据库用户进行加密处理，自定义Spring的PropertyPlaceHolder 实现加密信息转换，请问在apollo里面对于这种数据库密码的加密信息如何处理。

**Comment by nobodyiam** [comment]
可以参考[spring-boot-encrypt](https://github.com/ctripcorp/apollo-use-cases/tree/master/spring-boot-encrypt)，用到了jasypt，对应spring mvc也应该可以用的

**Comment by caowenliang** [comment]
我使用1.0.0版本 spring cloud config 中的加密方式{cipher}d01e64867xxxxxxxx 可以使用 
升级到1.1.2版本就不可以了 尽管可以解密 但没有覆盖

**Comment by nobodyiam** [comment]
看jasypt-spring-boot的[EncryptablePropertySourceConverter](https://github.com/ulisesbocchio/jasypt-spring-boot/blob/master/jasypt-spring-boot/src/main/java/com/ulisesbocchio/jasyptspringboot/EncryptablePropertySourceConverter.java)实现是把property source代理掉，然后在getProperty的时候做解密

**Comment by xunxiaoying** [comment]
谢谢

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
