### ISSUE TITLE
更改环境为pro后，打开配置中心管理界面 项目信息页面 出错http://localhost:8070/config.html?#/appid=testph

### ISSUE THREAD

**Issue by qazuc88** [ctripcorp/apollo#1738]
操作步骤

1.更新 apollo.portal.envs 值为PRO 
2.执行 demo.sh  start
3 打开配置中心管理界面
4.打开其中一个项目
5,。提示 系统出错或联系系统负责人

**Comment by nobodyiam** [comment]
看一下portal日志就知道了，或者也可以打开`管理员工具 - 系统信息`页面看一下

**Comment by qazuc88** [comment]
日志显示PRO_Meta not found

**Comment by nobodyiam** [comment]
quick start应该只支持dev一个环境吧

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
