### ISSUE TITLE
Long polling failed

### ISSUE THREAD

**Issue by hylhaha** [ctripcorp/apollo#1741]
![_20181205170122](https://user-images.githubusercontent.com/34212239/49502139-6f980880-f8af-11e8-97dd-a7eab6ee5a6b.png)
通过docker配置，但是调取的地址变成容器内部ip，导致无法访问到，也根据网络策略配置了 ignoredInterfaces:
            - docker0
            - veth.*
这是什么问题呢，如何修改

**Comment by nobodyiam** [comment]
这个要看一下docker容器里面是不是有其它网卡，如果没有的话，可以通过`-Deureka.instance.ip-address=${指定的IP}`参数指定一下。

如果是本地测试的话，可以通过`-Dapollo.configService=http://${指定的IP}:端口`直接指定config service的地址。

具体参考一下[1.4、网络策略](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#14%E7%BD%91%E7%BB%9C%E7%AD%96%E7%95%A5)

**Comment by hylhaha** [comment]
您好，为什么是本地测试 用-Dapollo.configService=http://${指定的IP}:端口 这个呢？正式部署时候不能用这种方式么

**Comment by nobodyiam** [comment]
@hylhaha

这个方式跳过了服务发现，如果服务宕机了，会导致客户端仍然会访问宕机的服务

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
