### ISSUE TITLE
apollo-portal 启动无法找到 apollo.meta

### ISSUE THREAD

**Issue by JasonWiki** [ctripcorp/apollo#1743]
1. 我是基于最新的 master 分支 build 编译的，改了部分端口地址
  apollo-adminservice  -> 20102 (原来 8090)
  apollo-configservice  -> 20101 (原来 8080)
  apollo-portal              -> 20100 (原来 8070)

2. 数据库
ApolloConfigDB 的 serverconfig 表 eureka.service.url 属性为 eureka.service.url=http://xxx.xxx.xxx:20101/eureka/ (就是原  apollo-configservice 的地址)

ApolloPortalDB 的 serverconfig 表 apollo.portal.envs 属性为
apollo.portal.envs=dev

3. 问题: 启动 apollo-portal 的时候报错误
  启动脚本:  
    portal/scripts/startup.sh

  启动配置: portal/config (注释了一部分)

  #local.meta=http://localhost:20101
  #dev.meta=http://apollo-dev-meta-server:20101
  #fat.meta=http://apollo-fat-meta-server:20101
  #uat.meta=http://apollo-uat-meta-server:20101
  #lpt.meta=${lpt_meta}
  pro.meta=http://xxx.xxx.xxx:20102 (使用  apollo-adminservice 的地址)

  报错内容：

   2018-12-06 16:59:34.148 ERROR 3268 --- [Apollo-ServiceLocator-1] c.c.f.a.p.c.AdminServiceAddressLocator   : Get admin server address from meta server failed. env: DEV, meta server address:http://apollo.meta

org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://apollo.meta/services/admin": apollo.meta: 未知的名称或服务; nested exception is java.net.UnknownHostException: apollo.meta: 未知的名称或服务
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:696)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:644)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:296)

PS: configservice 和 adminservice 都可以正常启动并且成功注册到 eureka 

请问这个 apollo.meta 是啥

**Comment by vflong** [comment]
portal 数据库表 ServerConfig apollo.portal.envs 这个值要改成 pro，默认是 dev，与 pro.meta 保持一致。

**Comment by JasonWiki** [comment]
问题解决了谢谢楼上

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
