### ISSUE TITLE
关于共有namespace删除问题

### ISSUE THREAD

**Issue by xunxiaoying** [ctripcorp/apollo#1744]
我新建了一个公有namespace ，关联了一下，然后我又删除了这个关联，然后删除了这个公有的namespace，然后我重新在建一个重名的公共namespace的时候提示namespace已经存在，公有的namespace创建了就不能删除了吗？

**Comment by nobodyiam** [comment]
在项目中删除的是namespace，appnamespace并没有删除，如果要删除appnamespace的话，需要通过 管理员工具页面操作，详见 [5. 如何删除应用、集群、Namespace？](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#5-%E5%A6%82%E4%BD%95%E5%88%A0%E9%99%A4%E5%BA%94%E7%94%A8%E9%9B%86%E7%BE%A4namespace)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
