### ISSUE TITLE
大家的namespace是怎么用的

### ISSUE THREAD

**Issue by luger1990** [ctripcorp/apollo#1745]
看文档介绍了解到namespace是存储一些公共配置。举个例子：部门有好几个redis地址，分别是redis1，redis2，redis3，reids4。可能不同项目都去连接，所以我就把这些redis连接的配置放到namespace中。那么我是把所有的reids配置放到一个namespace中呢还是每个redis都创建一个namespace。大家感觉哪个更合理？

**Comment by nobodyiam** [comment]
这个属于管理范畴了，放在一起或者是分开存放都可以，具体要看实际的场景。

**Comment by luger1990** [comment]
@nobodyiam 恩恩  想了想还是分开吧 更清晰一些 多谢了！
