### ISSUE TITLE
请教大神，目前版本是0.11.0，若只升级portal到1.1.0   是否存在兼容问题？

### ISSUE THREAD

**Issue by timZhangww** [ctripcorp/apollo#1747]
请问大神，目前版本是0.11.0，若只升级portal到1.1.0   是否存在兼容问题？

**Comment by timZhangww** [comment]
client 版本  也是 0.11.0

**Comment by vflong** [comment]
数据都在数据库里面，数据库结构没有大改动，我从 0.11.0 全部升级到 1.1.2 没发现问题。

**Comment by nobodyiam** [comment]
apollo的服务端始终是向后兼容的，也就是说对客户端版本不做要求，服务端可以随意升级，只要不比客户端版本低就可以

**Comment by timZhangww** [comment]
请问  configservice, adminservice, portal升级到最新， 数据库  是否  可以  不升级？

**Comment by vflong** [comment]
![image](https://user-images.githubusercontent.com/8759947/49706667-37ebe080-fc62-11e8-8aed-0eeb994f0bfe.png)
There is no schema change between v1.1.2 and v1.2.0.
结构没有变化，数据库没啥升级的。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
