### ISSUE TITLE
有个非常弱的问题

### ISSUE THREAD

**Issue by spjich** [ctripcorp/apollo#1748]
为了保证高可用，ConfigService和AdminService都是无状态以集群方式部署的，为了解决服务发现问题从而引入了Eureka。 这里为什么不直接使用nginx作为反向代理？

**Comment by nobodyiam** [comment]
@spjich 

客户端需要和config service保持长连接，如果走nginx，对nginx的压力会比较大（考虑6位数的长连数量），所以设计是发现服务列表，然后ip直连，不过如果机器规模比较小，那用nginx会比较简单

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
