### ISSUE TITLE
密文配置

### ISSUE THREAD

**Issue by BennyChang0** [ctripcorp/apollo#1751]
你好，请问下apollo什么时候能够支持配置项选择是否加密保存呢？

**Comment by nobodyiam** [comment]
和 #1459 类似，后续会考虑一下如何实现

**Comment by BennyChang0** [comment]
> 和 #1459 类似，后续会考虑一下如何实现

目前1.1.2这个版本有什么扩展途径呢？

**Comment by nobodyiam** [comment]
可以参考 https://github.com/ctripcorp/apollo-use-cases/tree/master/spring-boot-encrypt

**Comment by nobodyiam** [comment]
see #3187
