### ISSUE TITLE
0.10.2 客户端配置集群

### ISSUE THREAD

**Issue by gqhuang14920** [ctripcorp/apollo#1753]
版本0.10.2
rem meta server url, different environments should have different meta server addresses
set fat_meta="http://apollotest.log.com:20140,http://apollotest.log.com:20132"

客户问题
 Sync config from upstream repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository failed, reason: Get config services failed from http://apollotest.log.com:20140,http://apollotest.log.com:20132/services/config?appId=BASE_FST_20180803&ip=192.168.3.19 [Cause: Could not complete get operation [Cause: For input string: "20140,http:" [Cause: For input string: "20140,http:"]]]
2018/12/09 15:45:36,921 WARN  [main] AbstractConfigReposit

怎么解决哈

**Comment by nobodyiam** [comment]
0.11.0版本以上支持multiple meta server addresses，https://github.com/ctripcorp/apollo/releases/tag/v0.11.0

**Comment by gqhuang14920** [comment]
不升级能用SLB吗

**Comment by gqhuang14920** [comment]
如果升级到1.2.0   数据库表有改变吗

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
