### ISSUE TITLE
Apollo的多级缓存究竟是几级？分别在何时触发？

### ISSUE THREAD

**Issue by 2129zxl** [ctripcorp/apollo#1754]
看wiki介绍说Apollo采用多级缓存，请问具体是在哪些环节做了缓存呢？这些缓存机制分别是在何时触发？比如我知道的客户端的缓存文件是在成功连接到是配置中心时会触发并存储在本地。其他的具体是什么呢？非常感谢

**Comment by nobodyiam** [comment]
内存和本地文件缓存。

应用重启时如果读远端配置失败，会加载本地文件缓存到内存。

**Comment by 2129zxl** [comment]
非常感谢！
