### ISSUE TITLE
apollo配置在初始化过滤器之前加载

### ISSUE THREAD

**Issue by githubzouqf** [ctripcorp/apollo#1756]
apollo目前是否不支持在过滤器注册之前加载配置数据，以便过滤器初始化参数从apollo中获取
通过apollo.bootstrap.enabled 和apollo.bootstrap.namespaces 配置似乎仍然无法实现提前到过滤器注册之前的位置

**Comment by nobodyiam** [comment]
过滤器是指什么？

可以尝试一下 1.2.0版本增加的`apollo.bootstrap.eagerLoad.enabled=true`，参考一下[3.2.1.3 Spring Boot集成方式](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#3213-spring-boot%E9%9B%86%E6%88%90%E6%96%B9%E5%BC%8F%E6%8E%A8%E8%8D%90)的第三点

**Comment by githubzouqf** [comment]
是这样的，我在项目中集成cas, 想把cas的几个过滤器初始化参数放在apollo中，并通过FilterRegistrationBean注册过滤器，但是我发现cas的认证过滤器filter注册顺序高于apollo的配置初始化顺序，导致在注册过滤器bean的时候取不到apollo的配置，我先试一下apollo.bootstrap.eagerLoad.enabled=true是否可以。

**Comment by githubzouqf** [comment]
非常感谢大佬的回复，已经解决这个问题了，管用

**Comment by Burt-L** [comment]
这个问题终于得到了解决，感谢大佬们

**Comment by jackBaozz** [comment]
> 过滤器是指什么？
> 
> 可以尝试一下 1.2.0版本增加的`apollo.bootstrap.eagerLoad.enabled=true`，参考一下[3.2.1.3 Spring Boot集成方式](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#3213-spring-boot%E9%9B%86%E6%88%90%E6%96%B9%E5%BC%8F%E6%8E%A8%E8%8D%90)的第三点

![image](https://user-images.githubusercontent.com/5772152/50584893-25557780-0ead-11e9-98cb-30c5b30bc44f.png)
这个能不能xie写个例子？不知道logback-spring.xml里面如何配置，apollo才能够读取到和填充进来？？》》

**Comment by nobodyiam** [comment]
logback-spring是和spring集成的，和apollo没有关系。

apollo只是把配置注入到spring里面，默认的注入方式晚于日志组件的初始化，通过`apollo.bootstrap.eagerLoad.enabled=true`可以使apollo配置注入提前到日志组件初始化之前

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
