### ISSUE TITLE
@ApolloConfigChangeListener监听能否知道触发的是什么事件?

### ISSUE THREAD

**Issue by objectboy2016** [ctripcorp/apollo#1757]
@ApolloConfigChangeListener
    private void onChange(ConfigChangeEvent changeEvent) {
        if (changeEvent.isChanged("dbUserName2")) {
            System.out.println(config.getIntProperty("dbUserName2", 0));
        }
    }

回滚与发布执行上列代码, 但是压根无法判断其是不是回滚还是发布, 没有一个字段确定其是何操作吗?

**Comment by nobodyiam** [comment]
回滚和发布本质上都是一次发布，目前在客户端无法区分

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
