### ISSUE TITLE
若干台不同的配置中心之间如何同步

### ISSUE THREAD

**Issue by sunnyvinson** [ctripcorp/apollo#1760]
有两套apollo配置中心，配置中心A和配置中心B，是否有方式能够将配置中心A上的配置，同步到配置中心B上去面去呢？

**Comment by nobodyiam** [comment]
@JaredTan95 

这个是否就是你上次说的 环境之间的配置同步 功能？

**Comment by JaredTan95** [comment]
我想是的




| |
谭建
邮箱：tanjian20150101@163.com
|

签名由 网易邮箱大师 定制

在2018年12月11日 20:05，Jason Song 写道：

@JaredTan95

这个是否就是你上次说的 环境之间的配置同步 功能？

**Comment by nobodyiam** [comment]
[1.3.0](https://github.com/ctripcorp/apollo/releases/tag/v1.3.0)版本已经发布，增加了import和export配置的接口。
