### ISSUE TITLE
python接入apollo

### ISSUE THREAD

**Issue by reignsr** [ctripcorp/apollo#1761]
看过其他语言接入的官方接口说明，以及 @filamoon 提供的python客户端代码，有些疑问：
1、接口中没有env，那么返回的配置，是包含了所有的环境吗？
2、config_server_url指的是configservice的地址还是portal的地址？
3、按接口格式访问了一下，始终返回 {"timestamp":"2018-12-11T17:40:33.976+0800","status":404,"error":"Not Found","message":"Could not load configurations with appId: psc-b2cpacs-tpp, clusterName: default, namespace: application","path":"/configs/psc-b2cpacs-tpp/default/application"}，但这个app是正常可以访问的。问题到底在哪里？

**Comment by nobodyiam** [comment]
config_server_url指向的是config service地址，所以返回的是该环境的配置

返回404说明配置没有发布，不是app不存在

**Comment by reignsr** [comment]
@nobodyiam 非常感谢！之前url里多写了个字母。>_<|||
