### ISSUE TITLE
portal不支持系统环境变量里面配置meta server地址？

### ISSUE THREAD

**Issue by kyvli** [ctripcorp/apollo#1762]
我在系统的环境变量里面设置了下面的参数：
export FAT_META="http://1.1.1.1:8080"
但是好像无法被portal读取到，是不支持吗？只能在配置文件中配置？

**Comment by nobodyiam** [comment]
1.2.0的版本支持了读取system environment，具体看下代码 https://github.com/ctripcorp/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/apollo/core/internals/LegacyMetaServerProvider.java#L36

**Comment by kyvli** [comment]
好的，我测试一下

**Comment by kyvli** [comment]
另外还有一个问题，configservice的地址，你的建议是生产环境使用slb来做负载均衡，可以屏蔽ip地址的变化，但是如果我这样配置fat.meta=http://apollo-configsvc-node1:8080,http://apollo-configsvc-node2:8080，用host解析或者内部dns把node1和node2来指向configserver的ip，这样不是也可以屏蔽ip地址的变化，又可以少配置一个nginx服务吗
