### ISSUE TITLE
namespace没有发布过和namespace发布空配置的区别

### ISSUE THREAD

**Issue by awayings** [ctripcorp/apollo#1763]
DEV环境下创建两个idc(default和idc1)，默认有application的namespace。
1. idc1的集群下的application没有发布过。ConfigService.getConfig("application")能获取到default集群下application的配置.
2. idc1的集群发布空配置。ConfigService.getConfig("application")能获取到只能获取到空配置 。因为只有一次发布，所以也不能回滚。

请问下有没有什么方法可以让idc1的配置回到没有发布过的状态。

**Comment by nobodyiam** [comment]
可以删除idc1集群下的application namespace

**Comment by awayings** [comment]
速度真快
