### ISSUE TITLE
关于adminservice的一个问题

### ISSUE THREAD

**Issue by xunxiaoying** [ctripcorp/apollo#1765]
您好，请教一个关于服务发现的问题
我在一个机器上安装了DEV和UAT环境，每个环境有自己的configservice和adminservice通过端口区分不同的服务，那么对于DEV环境来说，是如何发现自己环境相对的configservice和adminservice呢？

**Comment by nobodyiam** [comment]
config service和admin service都会注册到各个环境的eureka，客户端和portal通过meta server找到对应的config service和admin service

**Comment by xunxiaoying** [comment]
现在有环境配置如下：
dev 环境：
config server (meta serve)地址：http://1.1.1.1:8080,admin server地址：http://1.1.1.1:8081;
uat 环境：
config server(meta server) 地址：http://1.1.1.1:9090,admin server地址：http://1.1.1.1:9091;
portal :
dev 环境的meta server:http://1.1.1.1:8080
uat  环境的meta server:http://1.1.1.1:9090
portal 通过meta server 是如何找到对应的admin server的呢？是通过在哪里配置什么来发现的吗？

**Comment by nobodyiam** [comment]
看一下 com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator 吧

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
