### ISSUE TITLE
官方Dockerfile构建出错

### ISSUE THREAD

**Issue by lchpersonal** [ctripcorp/apollo#1768]
Step 1/11 : FROM openjdk:8-jre-alpine
 ---> 2e01f547f003
Step 2/11 : MAINTAINER ameizi <sxyx2008@163.com>
 ---> Using cache
 ---> 817eb25e48dc
Step 3/11 : ENV VERSION 1.2.0
 ---> Using cache
 ---> 06f6a7e25010
Step 4/11 : RUN echo "http://mirrors.aliyun.com/alpine/v3.8/main" > /etc/apk/repositories     && echo "http://mirrors.aliyun.com/alpine/v3.8/community" >> /etc/apk/repositories     && apk update upgrade     && apk add --no-cache procps unzip curl bash tzdata     && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime     && echo "Asia/Shanghai" > /etc/timezone
 ---> Using cache
 ---> 7962101fab18
Step 5/11 : ADD apollo-configservice-${VERSION}-github.zip /apollo-configservice/apollo-configservice-${VERSION}-github.zip
 ---> Using cache
 ---> f040222ba567
Step 6/11 : RUN unzip /apollo-configservice/apollo-configservice-${VERSION}-github.zip -d /apollo-configservice
 ---> Using cache
 ---> 1a50f793f379
Step 7/11 : RUN rm -rf /apollo-configservice/apollo-configservice-${VERSION}-github.zip
 ---> Using cache
 ---> 65ba0f4919cb
Step 8/11 : RUN sed -i '$d' /apollo-configservice/scripts/startup.sh
 ---> Running in ccafd67ff750
sed: /apollo-configservice/scripts/startup.sh: No such file or directory
The command '/bin/sh -c sed -i '$d' /apollo-configservice/scripts/startup.sh' returned a non-zero code: 

一直报这个错，不知道什么原因？

**Comment by yanmaipian** [comment]
文件格式是dos需要在linux使用dos2unix 文件转换成unix格式，这点很恶心

**Comment by nobodyiam** [comment]
@lchpersonal 

执行docker build之前需要把apollo-configservice-${VERSION}-github.zip拷贝到当前目录的，这个做了吗？

**Comment by nobodyiam** [comment]
@yanmaipian 

哪个文件是dos格式？

**Comment by lchpersonal** [comment]
已解决

**Comment by sunny-aria** [comment]
@lchpersonal 怎么解决的说下呗

**Comment by zouchengli** [comment]
错误信息贴出来啊


Haodong <notifications@github.com> 于2019年4月17日周三 下午6:06写道：
