### ISSUE TITLE
请教下apollo在spring的value注解下的变量是否应该用volatile修饰？

### ISSUE THREAD

**Issue by hhrpower** [ctripcorp/apollo#1769]

**Comment by nobodyiam** [comment]
如果会变的话，可以用volatile修饰

**Comment by Q-RK** [comment]
[DefaultConfig](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/DefaultConfig.java#L35) 中的成员变量 m_configProperties 类型是 AtomicReference\<Properties\> ，是不是本身就能保证线程见的可见性？

**Comment by Anilople** [comment]
> [DefaultConfig](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/DefaultConfig.java#L35) 中的成员变量 m_configProperties 类型是 AtomicReference<Properties> ，是不是本身就能保证线程见的可见性？

参考 AtomicReference 的javadoc

> An object reference that may be updated atomically

是的
