### ISSUE TITLE
apollo-portal多环境配置切换问题

### ISSUE THREAD

**Issue by BennyChang0** [ctripcorp/apollo#1772]
本地调试点击页面左上角FAT的default集群会访问http://localhost:8070/apps/10000001/envs/FAT/clusters/default/missing-namespaces，
但是请求报错
exception: "org.springframework.web.HttpRequestMethodNotSupportedException"
message: "Request method 'GET' not supported"
status: 400

控制台错误日志：
2018-12-13 11:44:47.878 ERROR 45390 --- [nio-8070-exec-2] c.c.f.a.p.c.RetryableRestTemplate        : Http request failed, uri: /apps/10000001/appnamespaces, method: GET

这是什么情况，有点费解 portal支持这样的请求，
@RequestMapping(value = "/apps/{appId}/envs/{env}/clusters/{clusterName}/missing-namespaces", method = RequestMethod.GET)

**Comment by nobodyiam** [comment]
这个应该不会报错啊？能重现吗？

**Comment by BennyChang0** [comment]
用户登录后点击某个项目，这时portal会以GET方式调用adminservice的apps/{appId}/appnamespaces，发现apolloconfigdb.appnamespace表没有找到appId=xxx的数据；再以GET方式调用portal的/apps/{appId}/envs/{env}/clusters/{clusterName}/missing-namespaces。
这时走到AdminServiceAPI.getAppNamespaces(String appId, Env env)方法，这应该又请求到adminservice的apps/{appId}/appnamespaces地址。

**Comment by BennyChang0** [comment]
![Uploading 10_09_37__12_18_2018.jpg…]()

点击10002项目配置后，页面请求地址：
GET http://10.80.177.35:8070/apps/10002/envs/FAT/clusters/default/missing-namespaces 400

Request URL: http://10.80.177.35:8070/apps/10002/envs/FAT/clusters/default/missing-namespaces
Request Method: GET
Status Code: 400 
Remote Address: 10.80.177.35:8070
Referrer Policy: no-referrer-when-downgrade

{exception: "org.springframework.web.HttpRequestMethodNotSupportedException",…}
exception: "org.springframework.web.HttpRequestMethodNotSupportedException"
message: "Request method 'GET' not supported"
status: 400
timestamp: "2018-12-18T10:00:09.038"

为什么会访问/missing-namespaces这个地址

**Comment by BennyChang0** [comment]
我是拉取完成的1.2.0分支的源码，应该没有遗漏。不明白为什么会400

**Comment by nobodyiam** [comment]
代码如果正确的话不会400的，除非实际运行的还是老的代码。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
