### ISSUE TITLE
configdb与portaldb存在相同的表

### ISSUE THREAD

**Issue by WinsonOne** [ctripcorp/apollo#1774]
想了解下，为什么两个数据库中要存在相同的App与AppNamespace表

**Comment by nobodyiam** [comment]
元数据，config service和admin service也需要使用，所以会从portal db同步到config db

**Comment by WinsonOne** [comment]
可以只维护一份吧，admin service的portal db只保留权限，如果需要admin service查询config db数据时，直接通过微服务的方式调用config service

**Comment by nobodyiam** [comment]
App与AppNamespace表是跨环境的，对所有环境都是一样的，所以需要保存在portal db里面

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
