### ISSUE TITLE
无法获取公共namespace配置

### ISSUE THREAD

**Issue by baoshuai02** [ctripcorp/apollo#1776]
在docker中部署,public namespace配置无法获取,创建这个namespace的appid可以获取,其它appid都无法获取

**Comment by nobodyiam** [comment]
看一下config db中app namespace里面是否有正确的记录？

**Comment by baoshuai02** [comment]
具体原因没有找到, 只是重启了下docker容器就可以获取了, 怀疑是有什么缓存, 谢谢解答

**Comment by nobodyiam** [comment]
访问一下 http://{config-service-url}:{port}/configs/xxxxxx/default/{公共namespace} 看看返回什么？

另外，如果是1.2.0版本，portal上会检测是否app namespace有问题的。

**Comment by FuleChu** [comment]
> 访问一下 http://{config-service-url}:{port}/configs/xxxxxx/default/{公共namespace} 看看返回什么？
> 
> 另外，如果是1.2.0版本，portal上会检测是否app namespace有问题的。

我也遇到这个问题，版本1.1.1，就是公共配置读取不到，看报错信息好像是把公共的namespace当作当前连接的appid下的一个私有的namespace：
Sync config failed, will retry. Repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository, reason: Load Apollo Config failed - appId: welfare-atomic-card, cluster: default, namespace: welfare2.image-config, url: http://x'x'x'x:xxxxxxx/configs/welfare-atomic-card/default/welfare2.image-config?ip=10.1.31.70 [Cause: [status code: 404] Could not find config for namespace - appId: welfare-atomic-card, cluster: default, namespace: welfare2.image-config, please check whether the configs are released in Apollo!]

**Comment by nobodyiam** [comment]
可以升级到1.2.0版本，portal上会检测是否app namespace有问题的。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by cypggs** [comment]
> 可以升级到1.2.0版本，portal上会检测是否app namespace有问题的。

返回404，很奇怪，删除后也不能新建立，提示已经存在；
后来在管理页面那边删除，再重新建立就可以获取了。

**Comment by ronaldo-bo** [comment]
有时删掉重建也没用，可以试试重启apollo configservice，我们这样解决了
