### ISSUE TITLE
apollo-core中的META-INF.services

### ISSUE THREAD

**Issue by BennyChang0** [ctripcorp/apollo#1777]
请问下为什么设置为LegacyMetaServerProvider，而apollo-client中设置的是DefaultMetaServerProvider
为什么这么设计呢？

**Comment by nobodyiam** [comment]
LegacyMetaServerProvider是兼容老的${env}_meta的设置方式，DefaultMetaServerProvider是新的apollo.meta的设置方式

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
