### ISSUE TITLE
nginx https反向代理到portal

### ISSUE THREAD

**Issue by kyvli** [ctripcorp/apollo#1778]
我在nginx上配上了https访问，并且设置了相关header,但是在输入账号和密码登录后会跳转到http协议，然后再手动改成https访问页面都是正常的，是什么原因呢？

nginx 相关header设置：
proxy_set_header   X-Real-IP          $remote_addr;
proxy_set_header   X-Forwarded-For    $proxy_add_x_forwarded_for;
proxy_set_header   X-Forwarded-Proto  $scheme;
proxy_set_header   X-Forwarded-Port   $server_port;

portal的配置文件，增加了下面的配置：
server: 
  tomcat: 
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
  use-forward-headers: true

我们自己的springboot项目都是通过这种方式来支持https访问的，是哪里不一样？

**Comment by nobodyiam** [comment]
`输入账号和密码登录后会跳转到http协议`，这个跳转回的地址是否正确？

**Comment by nobodyiam** [comment]
你是用的默认spring security的登录实现吗？还是接入了自己公司的sso？

**Comment by nobodyiam** [comment]
我照着[这篇文章](https://www.thomasvitale.com/https-spring-boot-ssl-certificate/)配置了一下https，登录后跳转是正常的，可以尝试一下。

![image](https://user-images.githubusercontent.com/837658/50042689-578b6a80-00a1-11e9-9ab3-ba6878f97b83.png)

**Comment by kyvli** [comment]
嗯，解决了，还有一个问题，我用的是阿里slb，并且自定义了端口号，slb不支持设置X-Forwarded-Port这个字段，导致后端无法正确获得反向代理的端口号，所以有办法修改这个端口号吗

**Comment by nobodyiam** [comment]
可以参考一下 `org.springframework.security.web.authentication.AbstractAuthenticationTargetUrlRequestHandler#determineTargetUrl`这个方法

**Comment by kyvli** [comment]
可惜我不会java，所以是不是没有办法了

**Comment by nobodyiam** [comment]
代码挺简单的，可以设置`useReferer=true`，然后通过在header中传入`Referer`来实现，不过现阶段确实需要简单代码配置一下，参考：https://stackoverflow.com/questions/26833452/spring-boot-redirect-to-current-page-after-successful-login

**Comment by dishuihengxin** [comment]
@kyvli  @nobodyiam 我使用Nginx代理两台server的portal是没问题的，提供给你参考一下：
```bash

upstream portal.com{
        ip_hash;
        server ip1:8070;
        server 1p2:8070;
}
.....

 location / {
                proxy_pass http://portal.com;
                proxy_set_header   Host $host;
                proxy_set_header   X-Forwardes-For $remote_addr;
        }

```

**Comment by nobodyiam** [comment]
可以试一下1.3.0版本，这儿版本的重定向是用相对路径重定向的
