### ISSUE TITLE
源码下载下来，运行时候会找不到db配置+application-github.properties这个文件有毒

### ISSUE THREAD

**Issue by zhikaichen123** [ctripcorp/apollo#1779]
下载源码，直接运行AdminServiceApplication或者ConfigServiceApplication或者PortalApplication，会提示
DB配置没有，
然后我的解决方案是：
开头加上注解
@PropertySource(value = {"classpath:application-github.properties"})  //先加载指定的配置文件

这样就能找到db配置，但是又发现application-github.properties这个默认的文件有毒（可能创建的时候编码格式不对，加了乱子八糟东西），无论如何配置，都会提示数据库连接失败
然后我的解决方案是：
重新创建一个db.properties文件，指定编码格式utf-8,并且程序开头配置
@PropertySource(value = {"classpath:db.properties"})  //先加载指定的配置文件

以上，搞定

**Comment by nobodyiam** [comment]
源码执行的话，请参考 [Apollo开发指南](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
