### ISSUE TITLE
不同人员管理不同环境的配置

### ISSUE THREAD

**Issue by kyvli** [ctripcorp/apollo#1780]
比如开发人员只允许查看管理开发环境的配置，测试人员只允许查看管理测试平台的配置，目前是不是只能在各个项目里面配置，没有办法统一配置？

**Comment by java-longmiao** [comment]
我做过相应的改造，接入自己的sso，重新设计user表，对不同的人员分类，按类型展示不同的环境列表即可。

**Comment by nobodyiam** [comment]
@java-longmiao  是在已有的权限体系之外再加了一层控制？

**Comment by steveguoshao** [comment]
目前也有这样的需求
