### ISSUE TITLE
configservice启动后，貌似存在延时，导致应用立即获取配置失败

### ISSUE THREAD

**Issue by sunnyvinson** [ctripcorp/apollo#1787]
![image](https://user-images.githubusercontent.com/13216698/50087250-635e6480-023a-11e9-958a-58882886e9ed.png)
这三个时间点，哪个是客户端apollo-env.properties通过ip:7901，可以获取到配置的时间呢？

场景：
    配置中心和各类应用做成自动化部署的一个包，进行部署；
    启动顺序里控制，通过监听7902（adminservice）端口启动成功后（7902又依赖7901configservice起来，7902端口起来也需要花费时间），开始启动应用，应用会从配置中心获取数据作为应用的启动参数，但是出现的结果：监听到7902起来后，去启动应用，应用日志提示获取apollo配置失败

**Comment by sunnyvinson** [comment]
![image](https://user-images.githubusercontent.com/13216698/50087785-18455100-023c-11e9-8019-59b8c94c95c9.png)

这个是应用启动时的日志记录，有准确时间

**Comment by nobodyiam** [comment]
eureka注册实例比较慢，且eureka client有缓存，所以导致客户端从meta server获取实例比较慢，按照eureka的说明，最多可能会有90秒的延迟。

不过只有客户端和服务端都是第一次启动才会有这个影响，因为客户端是有config service服务列表缓存的。

**Comment by sunnyvinson** [comment]
前半句话的意思，不知道我有没有理解错误，configservice自己作为微服务客户端时，启动的过程需要将自己进行缓存方便后用，这一块也会占用一定的时间，而这部分时间也被计算进延迟时间之内了吗

**Comment by nobodyiam** [comment]
这块是eureka client的逻辑，可以看一下[DiscoveryService](https://github.com/ctripcorp/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/metaservice/service/DiscoveryService.java)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
