### ISSUE TITLE
spec.template.spec.initContainers[1].name: Duplicate value

### ISSUE THREAD

**Issue by weihc02** [ctripcorp/apollo#1789]
部署时提示：
The Deployment "deployment-apollo-portal-server" is invalid: 
* spec.template.spec.initContainers[1].name: Duplicate value: "check-service-apollo-admin-server-dev"
* spec.template.spec.initContainers[2].name: Duplicate value: "check-service-apollo-admin-server-dev"
* spec.template.spec.initContainers[3].name: Duplicate value: "check-service-apollo-admin-server-dev"

**Comment by nobodyiam** [comment]
通过什么方式部署的？

**Comment by wulaiwei** [comment]
文件   service-apollo-portal-server.yaml
![image](https://user-images.githubusercontent.com/16910820/51891894-60c76100-23db-11e9-80e1-d390b3b24245.png)
你好这边是否应该修复为对应的 prod beta alpha  
windows +  kubernetes   
-------------------
修改后部署成功

**Comment by nobodyiam** [comment]
方便提交一个PR吗？

**Comment by wulaiwei** [comment]
@nobodyiam 
你好,这边关于spec.template.spec.initContainers[1].name: Duplicate value 的问题
已经提交了PR

**Comment by nobodyiam** [comment]
@wulaiwei 非常感谢！

**Comment by nobodyiam** [comment]
[1.3.0](https://github.com/ctripcorp/apollo/releases/tag/v1.3.0)版本已经发布，包含了该fix
