### ISSUE TITLE
设置meta server地址失败

### ISSUE THREAD

**Issue by tanxiaosheng** [ctripcorp/apollo#1790]
一般是在application.properties中设置apollo.meta，那么每个应用都要设置一遍，在自定义的spring-boot-starter中，初始化应用上下文之前，通过System.setProperty设置apollo.meta，调试进去，DefaultMetaServerProvider也能够读取正确的apollo.meta地址，但是还是不能读取配置中心的配置，这是为什么呢？同时还发现了日志打印功能也坏掉了...

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
