### ISSUE TITLE
Apollo1.0版本 namespace误删不能恢复问题

### ISSUE THREAD

**Issue by limitAp** [ctripcorp/apollo#1791]
宋老师你好，1.0版本下。我创建一个test.yml (dev uat fat)都有。但是我不小心删除uat test.yml 用管理员工具把namespace重新删了。 再去创建test.yml显示失败!第一次点击报错如下
![7n2afwl qb48y 0i fpro](https://user-images.githubusercontent.com/18351359/50133940-ceef1300-02c8-11e9-85dc-023f2b0ad155.png)
但是界面没有看到
然后我再点击一次显示已经存在
![4 0 a g2 8qmv zfu3 ln5](https://user-images.githubusercontent.com/18351359/50134086-6ce2dd80-02c9-11e9-9270-b177ca03fa77.png)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
