### ISSUE TITLE
ApolloConfigChangeListener事件 key更新，发布无反应或者有时候会通知有时候不通知

### ISSUE THREAD

**Issue by zhikaichen123** [ctripcorp/apollo#1793]
如题，ApolloConfigChangeListener对数据变化的感应不灵敏，有些key比如logger.level能90%触发，但是其它key，类似key1,key2这种，MODIFIED完全不触发！
   然后我的解决方案是，
@Configuration
@EnableApolloConfig    +    @Value

这种才能有变化就正常触发！

**Comment by nobodyiam** [comment]
这个和key无关的，不存在灵敏和不灵敏的问题。。。

有多种配置方式，具体可以参考Java客户端使用文档，其中一种就是

```java
@Configuration
@EnableApolloConfig
public class AppConfig {
}
```

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
