### ISSUE TITLE
tomcat-embed-core这个项目在哪里能找到jar

### ISSUE THREAD

**Issue by wuzhaozhongguo** [ctripcorp/apollo#1796]
有没有提供maven仓库

**Comment by nobodyiam** [comment]
你是指`com.ctrip.3rdparty.tomcat.embed:tomcat-embed-core`？这个只有在ctrip profile启用时才会用到，在你本地编译不应该启用ctrip相关的profile，自然也是不会用到的。

**Comment by wuzhaozhongguo** [comment]
非常感谢
