### ISSUE TITLE
关于注册不上eureka的坑

### ISSUE THREAD

**Issue by qylhjhd** [ctripcorp/apollo#1797]
apollo 用自定义的key eureka.service.url 代替了eureka.client.service-url.defaultZone 重写了EurekaClientConfig的实现，具体类BizConfig 的eurekaServiceUrls方法

**Comment by nobodyiam** [comment]
是的，主要是为了便于通过数据库、环境变量等动态配置eureka的地址

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
