### ISSUE TITLE
报错数据库表不存在或跟库表不一致的问题

### ISSUE THREAD

**Issue by qylhjhd** [ctripcorp/apollo#1798]
spring.datasource.url = jdbc:mysql://localhost:3306/ApolloConfigDB?characterEncoding=utf8
spring.datasource.username = root
spring.datasource.password = 123456
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.show_sql=false
spring.h2.console.enabled = true
spring.h2.console.settings.web-allow-others=true

需要配置上hibernate的配置  在项目 test/resources/application.properties里面有相关的配置

**Comment by nobodyiam** [comment]
travis ci和其他用户跑上去都没问题啊，是不是改过代码？

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
