### ISSUE TITLE
动态刷新配置文件，不重启项目，不能热更新

### ISSUE THREAD

**Issue by alxjerr** [ctripcorp/apollo#1799]
配置中心里有这样一个配置：
test.info = test-info
在程序中用@Value("${test.info}")读取配置信息；
然后配置了监听如下：
`
@Component
public class RefreshConfig implements ApplicationContextAware {

    private static final Logger logger = LoggerFactory.getLogger(RefreshConfig.class);

    private ApplicationContext applicationContext;

    @ApolloConfigChangeListener
    public void onChange(ConfigChangeEvent changeEvent) {
        refreshProperties(changeEvent);
    }

    private void refreshProperties(ConfigChangeEvent changeEvent) {
        logger.info("Refreshing  properties!");

        this.applicationContext.publishEvent(new EnvironmentChangeEvent(changeEvent.changedKeys()));

        logger.info(" properties refreshed!");
    }

    @Override
    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        this.applicationContext = applicationContext;
    }
}`

将配置test.info的值修改后，不能热更新。

**Comment by nobodyiam** [comment]
`@Value`不需要通过`EnvironmentChangeEvent`就可以热更新的，不需要监听配置变化，如果没更新的话应该是配置有误，建议看一下日志或参考一下apollo-demo: https://github.com/ctripcorp/apollo/tree/master/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/spring
