### ISSUE TITLE
配置文件加载优先级的问题

### ISSUE THREAD

**Issue by alxjerr** [ctripcorp/apollo#1800]
本地环境变量中的配置、apollo配置中心的配置、`classpath:/` , `classpath:/config` , `file:./ `, `file:./config/config/`这些里面的配置，加载的优先级是什么样子的呢。

**Comment by nobodyiam** [comment]
本地环境变量中的配置 > apollo配置中心的配置 > 本地文件的配置

本地文件的配置顺序参考Spring Boot的说明

**Comment by alxjerr** [comment]
本地环境变量有Path，在apollo配置中心也写了个Path属性：
`Path = 配置中心的path
test.info = ${Path}`
在程序中用@Value获取test.info
![image](https://user-images.githubusercontent.com/19329840/50318685-ac920b00-04fd-11e9-8ccc-e874645d4c3c.png)
最后的输出结果是：
![image](https://user-images.githubusercontent.com/19329840/50318693-c3386200-04fd-11e9-917b-f713b33cf34d.png)

是我的测试方式有问题吗，还是说明apollo配置中心的配置 > 本地环境变量中的配置

**Comment by nobodyiam** [comment]
你的本地环境变量是啥？

我前面提到的本地环境变量是Java的System Property

**Comment by alxjerr** [comment]
噢噢，我指的是environment property

**Comment by HiBrant** [comment]
@nobodyiam 
按照spring boot的配置优先级顺序：命令行参数 > 环境变量 > 配置文件
但是我在使用apollo的过程中发现：
环境变量 > apollo配置，同时，apollo配置 > 命令行参数，与spring boot的配置优先级存在冲突
不知道算不算bug？

举例说明：
我有一个spring-boot-web的项目名为test.jar，假设启动命令为：
java -jar -Dserver.port=11111 test.jar --server.port=22222
在没有接入apollo的情况下，端口号为22222
但是在接入apollo的情况下，端口号为11111
命令行参数被忽略了！

**Comment by nobodyiam** [comment]
是的，这个问题是由于apollo的property source放在太前面所致，按照你描述的逻辑，应该要放在稍微后面一点，相关的代码在下面两个地方，不知道你是否能提交个PR修复一下？

1. https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/boot/ApolloApplicationContextInitializer.java#L91
2. https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/config/PropertySourcesProcessor.java#L62

**Comment by HiBrant** [comment]
@nobodyiam 
荣幸之至

**Comment by kyleleeli** [comment]
修复了吗？

**Comment by cy2008** [comment]
最新版本问题仍然存在

**Comment by heheliu321** [comment]
环境变量 > apollo配置，怎么解决？

**Comment by chendong-df** [comment]
解决了吗

**Comment by qixiaobo** [comment]
Same problem here

**Comment by nobodyiam** [comment]
2.1.0 版本开始，Java 客户端支持配置是否[覆盖系统属性](https://www.apolloconfig.com/#/zh/client/java-sdk-user-guide?id=_1248-%e8%a6%86%e7%9b%96%e7%b3%bb%e7%bb%9f%e5%b1%9e%e6%80%a7)
