### ISSUE TITLE
Apollo SpringBoot EnvironmentPostProcessor优先级问题

### ISSUE THREAD

**Issue by chutian52** [ctripcorp/apollo#1802]
通常情况下spring(boot）对各个组件的排序顺序按下述方式优先级执行
（1）PriorityOrdered（包含注解@Priority）
（2）Ordered（包含注解@Ordered）
（3）未实现上述2个接口（含注解）

如果我想在apollo获取配置后再处理其他信息的话，可能就会导致无法实现。例如，我想添加一些默认配置，而后可以使用apollo去修改默认行为。
如果我获取属性的方式是自上而下的话（例如dubbo获取properties），由于apollo的PropertySource是在最上面的，这样会导致默认的properties会覆盖apollo中的配置信息。
dubbo获取subproperties的方法为
```
public static Map<String, String> getSubProperties(PropertySources propertySources, String prefix) {

        Map<String, String> subProperties = new LinkedHashMap<String, String>();

        String normalizedPrefix = prefix.endsWith(".") ? prefix : prefix + ".";

        for (PropertySource<?> source : propertySources) {
            if (source instanceof EnumerablePropertySource) {
                for (String name : ((EnumerablePropertySource<?>) source).getPropertyNames()) {
                    if (name.startsWith(normalizedPrefix)) {
                        String subName = name.substring(normalizedPrefix.length());
                        Object value = source.getProperty(name);
                        subProperties.put(subName, String.valueOf(value));
                    }
                }
            }
        }

        return subProperties;

    }
```
environment中的PropertySource顺序
<img width="733" alt="default" src="https://user-images.githubusercontent.com/11222742/50270191-b834f180-046b-11e9-8368-af18eb56c515.png">
这样，很容易造成dubbo的配置被覆盖。

**个人建议**
建议Apollo实现Ordered接口，这样开发人员可以在Apollo的基础上添加自定义PropertySource

**Comment by nobodyiam** [comment]
感谢建议！

`建议Apollo实现Ordered接口，这样开发人员可以在Apollo的基础上添加自定义PropertySource`这个能展开说明一下吗？

因为目前的PropertySource就是插在最前面的，能做的可能是增加一个配置项设置插在哪个位置，或是插在哪个之前、之后？

**Comment by chutian52** [comment]
@nobodyiam 
在之前的项目中，我们为了简化开发人员对于默认配置的二次配置，我们通常实现`EnvironmentPostProcessor`来添加默认配置来实现兜底，默认情况下是在SpringBoot的`ConfigFileApplicationListener`的DEFAULT_ORDER的后面执行默认的配置兜底实现（例如dubbo的默认protocol等），即统一配置。

对于SpringBoot项目。在不考虑spring-cloud的前提下，可以触发的基本事件为
`ApplicationStartedEvent`->`ApplicationEnvironmentPreparedEvent` -> `ApplicationContextInitializer` ->`ApplicationPreparedEvent`（不包含Spring ApplicationContext本身的fresh触发事件）.
Apollo 加载配置信息的默认实现是在`ApplicationEnvironmentPreparedEvent`（`EnvironmentPostProcessor`）和`ApplicationContextInitializer`，并且没有实现`PriorityOrdered`和`Ordered`两个接口，如果开发人员使用Apollo的话，则实现顺序可能依赖于springboot-tools中的`LaunchedURLClassLoader`对资源的加载的优先级（`META-INF/spring.factories`）
对于提议中提起的dubbo配置，如果Apollo的默认配置加载在本身实现的后面（依赖于Springboot对资源加载的顺序），很容易导致Apollo中的配置被覆盖的情况。即我所说的兜底配置覆盖了默认的Apollo配置。我现在的解决方案是使用`ApplicationPreparedEvent`这一事件来解决潜在的顺序问题。但是我觉得可能存在的情况是Apollo无法覆盖application.properties中的配置信息（目前发现的是在Dubbo的`@EnableDubboConfig`，其默认的subPrefix策略就是覆盖，最上面的（Apollo）会被下面的（例如我们的兜底或application.properties）中的配置信息覆盖

**潜在的解决方案**
1. 在文档中提示开发人员使用`ApplicationPreparedEvent`来实现上述兜底方案
2. 让`ApolloApplicationContextInitializer`实现`Ordered`接口，为开发人员提供另外一种潜在的兜底解决方案

**Comment by nobodyiam** [comment]
@chutian52 

感谢详尽的解释，我提交了一个PR #1809，增加了`Ordered`接口，看看是不是能满足你的场景？

不过有一点需要注意的是，目前apollo有一个逻辑会确保apollo的property source始终在第一位（参见[PropertySourcesProcessor. ensureBootstrapPropertyPrecedence](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/config/PropertySourcesProcessor.java#L90)），如果要改变这个行为的话，可能需要增加一个配置项，比如`apollo.allowOverride=true`

**Comment by chutian52** [comment]
@nobodyiam 非常感谢。
我个人觉得，`apollo.allowOverride=true`这个配置项是属于锦上添花的事情。
对于开发人员而言，一般的实现兜底方案总是要先判断是否是有属性已经存在，如果不存在，再添加应该就没有问题了。毕竟，对于老旧项目新接入apollo的项目而言，有可能会在使用习惯上丢弃原有的一些默认配（未配置到Apollo的公共项），开发人员可能未关注到，有可能导致项目启动失败问题。
Apollo在第一位，我觉得没什么问题，只要属性不重复，或者不会出现dubbo这种会覆盖行为的操作，都不会有问题

**Comment by chutian52** [comment]
@nobodyiam OK，持续关注中...
