### ISSUE TITLE
应用中的配置怎样才能覆盖掉公共配置？

### ISSUE THREAD

**Issue by xiaoxing598** [ctripcorp/apollo#1803]
为了给所有项目添加公共配置，特别创建一个新项目“common”，并添加一公共配置文件“common”，目前各个项目可以读取到common的配置，但发现各个项目中的配置无法覆盖common中的，理论上要能够覆盖才符合公共配置的使用场景。

**Comment by alxjerr** [comment]
经测试，添加的公共的namesapce中的配置，加载的优先级好像是最低的。

**Comment by alxjerr** [comment]
项目的配置是写在程序服务中的，还是写在项目在apollo中对应的appid中的呀。

**Comment by nobodyiam** [comment]
应用中关联公共namespace，然后就可以覆盖了，请参考[Apollo核心概念之“Namespace”](https://github.com/ctripcorp/apollo/wiki/Apollo%E6%A0%B8%E5%BF%83%E6%A6%82%E5%BF%B5%E4%B9%8B%E2%80%9CNamespace%E2%80%9D)和[2.3 应用覆盖公用组件配置步骤](https://github.com/ctripcorp/apollo/wiki/Apollo%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#23-%E5%BA%94%E7%94%A8%E8%A6%86%E7%9B%96%E5%85%AC%E7%94%A8%E7%BB%84%E4%BB%B6%E9%85%8D%E7%BD%AE%E6%AD%A5%E9%AA%A4)

**Comment by xiaoxing598** [comment]
也就说需要在每个项目中创建一个新common配置，来进行关联？

**Comment by nobodyiam** [comment]
需要覆盖的才需要关联，不需要覆盖的不需要关联
