### ISSUE TITLE
默认namespace最低优先级的疑惑

### ISSUE THREAD

**Issue by alxjerr** [ctripcorp/apollo#1804]
![image](https://user-images.githubusercontent.com/19329840/50319340-d2211380-0501-11e9-80fd-90072ba1f23f.png)
这个最低优先级挺疑惑的，说的默认配置优先级最低，但它的优先级比本地的SpringBoot配置文件的优先级还高，也比后创建的namespace的优先级高。

**Comment by nobodyiam** [comment]
这个是指多个`EnableApolloConfig`之间的顺序

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
