### ISSUE TITLE
client与meta_server之间连接能否增加鉴权功能

### ISSUE THREAD

**Issue by asukaliy1** [ctripcorp/apollo#1810]
client目前为spring boot，了解到，可以通过敏感配置信息加密的方法，然后在程序内解密，可以实现安全；

但是有没有办法实现client与meta_server之间通过鉴权连接，比如在程序代码中包含一个token，meta_server验证token正确后才允许配置下拉。

这个功能能不能简单的通过修改源代码实现呢，谢谢~

**Comment by nobodyiam** [comment]
是可以实现的，可以在http的header中传入token，在服务端做校验。

后续版本会考虑加入提供扩展点支持鉴权，如有好的建议也欢迎随时提出~

**Comment by xilu0** [comment]
@nobodyiam  header中传入token鉴权的功能原生实现吗？

**Comment by nobodyiam** [comment]
@xilu0 目前还没实现，初步考虑是提供扩展点从而可以插入每个公司自己的逻辑，如有好的建议也欢迎随时提出~

**Comment by nobodyiam** [comment]
做认证是可以的，就看是否有必要了

**Comment by wenj91** [comment]
> @xilu0 目前还没实现，初步考虑是提供扩展点从而可以插入每个公司自己的逻辑，如有好的建议也欢迎随时提出~

这个比较好， 提供拓展点让用户实现自己的业务逻辑

**Comment by zgfh** [comment]
有什么开发计划吗？

**Comment by nobodyiam** [comment]
see #2099
