### ISSUE TITLE
Apollo服务端能否支持在线升级到最新版本？

### ISSUE THREAD

**Issue by WengJim** [ctripcorp/apollo#1813]
如题。大佬觉得是否适合哦？

**Comment by WengJim** [comment]
> 在线升级是指？
> 
> 通过 https://github.com/ctripcorp/apollo/releases 页面下载最新的包，部署到服务器上就升级完成了

我的意思是指，在服务器上执行命令在线升级到最新的版本。不用通过GitHub下载最新的包。

**Comment by nobodyiam** [comment]
目前还不支持
