### ISSUE TITLE
权限问题

### ISSUE THREAD

**Issue by fladdy** [ctripcorp/apollo#1815]
系统特性中有一项是不允许项目成员查看指定环境的配置，
但按照我目前的实践结果，如果不把某个用户设置为项目成员，那么在项目列表里连项目名称都看不到，设置为项目成员后，那么第一条的限制又会失效，是我的姿势不对吗？

btw：我是想让开发人员的账户只能查看，修改，发布开发环境的配置，测试人员的账户只能查看，修改，发布测试环境的配置。

**Comment by kezhenxu94** [comment]
用户可以通过搜索看到项目

**Comment by fladdy** [comment]
@kezhenxu94 感谢。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
