### ISSUE TITLE
客户端配置负载均衡

### ISSUE THREAD

**Issue by gqhuang14920** [ctripcorp/apollo#1816]
我这边配置 server.properties属性文件
env=dev
apollo.meta=http://apollotest.gqh.com:20134,http://apollotest.gqh.com:20135,http://apollotest.gqh.com:20132
但是在客户端没有看到负载均衡的代码，，，看到选择可以用的meta.server代码。

如果选择的meta.server服务中间挂了，会重新选择吗

**Comment by nobodyiam** [comment]
会重新选择的，参见[MetaDomainConsts](https://github.com/ctripcorp/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/apollo/core/MetaDomainConsts.java#L193)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
