### ISSUE TITLE
缓存

### ISSUE THREAD

**Issue by objectboy2016** [ctripcorp/apollo#1817]
apollo-quick-start 1.2版本
apollo server定义: 
test.name=apollotest
项目中properties文件中使用:
test.name=${test.name} 能够得到test.name的输出值为apollotest

问题: 
修改 test.name=2222222,再将apollo的缓存文件删除(\opt\data),  target目录删除, 然后重新编译, 得到的结果依然是test.name=apollotest    按道理来说应该是 test.name=2222222  才是  ,
请问是有地方漏写才导致这种情况的吗?

**Comment by nobodyiam** [comment]
文件缓存只有在连不上服务的时候才会用到，所以不需要删除，也不需要重新编译，修改后能实时更新的。如果没有实时更新，建议打开DEBUG级别日志看看。

**Comment by objectboy2016** [comment]
> 文件缓存只有在连不上服务的时候才会用到，所以不需要删除，也不需要重新编译，修改后能实时更新的。如果没有实时更新，建议打开DEBUG级别日志看看。

test.name=2222222 这个是没有用apollo   ,  而是直接赋值  但是读出来的结果依然还是apollo的结果,

**Comment by nobodyiam** [comment]
apollo中如果没有值，怎么可能被程序读到呢。。。建议仔细检查一下。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
