### ISSUE TITLE
spring boot 客户端 控制台不显示日志，日志使用的logback

### ISSUE THREAD

**Issue by sunshuangli** [ctripcorp/apollo#1818]
Connected to the target VM, address: '127.0.0.1:57412', transport: 'socket'

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.0.1.RELEASE)

log.debug("batch" + batch);
log.info("timeout" + timeout);
log.error("batch");

这三个级别的日志都不会在控制台显示，项目启动成功之后，怎么操作就是上面那些日志

**Comment by nobodyiam** [comment]
这个是spring boot的使用问题吧，和apollo没有关系吧？
