### ISSUE TITLE
Java客戶端如何更新Apollo中的配置

### ISSUE THREAD

**Issue by xiejiashuai** [ctripcorp/apollo#1819]
# 现在有一个场景是需要使用Java API 更新配置信息，而不是通过页面进行更新，也没有找到相关文档介绍？能给提供下使用Java API 手动更新配置相关的Demo吗 ？

**Comment by xiejiashuai** [comment]
> 操作配置信息的接口在 `adminservice` 模块下的 `com.ctrip.framework.apollo.adminservice.controller.ItemController` 类中, 新建/修改分别对应 `com.ctrip.framework.apollo.adminservice.controller.ItemController#create` 和 `com.ctrip.framework.apollo.adminservice.controller.ItemController#update` 方法, 可以通过 `restTemplate` 方便地进行调用, 项目内就有这样的操作, 可以参考 `portal` 模块下的 `com.ctrip.framework.apollo.portal.api.AdminServiceAPI` 类. 如果不使用 Spring 的 `RestTemplate`, 使用任何 Java 的 Http 框架请求也可以

会有权限校验吗？ 感觉你们是否应该给出wiki呢？

**Comment by nobodyiam** [comment]
open api有java api的，参考[Apollo开放平台](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
