### ISSUE TITLE
宋大神 问题请教

### ISSUE THREAD

**Issue by BillBearXiong** [ctripcorp/apollo#1820]
大神  你好。有一个问题向你请教。是这样的，公司关于数据库，redis，mongoDb等一下密码，安全部门也想搭一套apollo来管理这些密码，请问  一个apollo client能连接两套apollo service吗？

**Comment by asukaliy1** [comment]
一个apollo portal可以管理多个环境，你应用里配下连不同的meta server就可以呃

**Comment by nobodyiam** [comment]
一个apollo-client同时只能连一个环境的，密码这些可以放在同一个apollo里面，存储的时候做好加密，使用的时候做好解密就可以了。

如果一定要单独部署一个apollo的话，就需要自己搞一个client来连这个单独的apollo了，如果用途很简单（比如只需要启动的时候加载），那直接调用apollo的http接口就可以了。

**Comment by BillBearXiong** [comment]
> 一个apollo-client同时只能连一个环境的，密码这些可以放在同一个apollo里面，存储的时候做好加密，使用的时候做好解密就可以了。
> 
> 如果一定要单独部署一个apollo的话，就需要自己搞一个client来连这个单独的apollo了，如果用途很简单（比如只需要启动的时候加载），那直接调用apollo的http接口就可以了。

大神   密码这些应该是不会去动态更改的  就像您说的那样  只是项目部署的时候加载，那么请问你所说的直接调用apollo的http接口是暴露在哪里  可以指明一下嘛？多谢

**Comment by BillBearXiong** [comment]
> 一个apollo portal可以管理多个环境，你应用里配下连不同的meta server就可以呃

大神  你好  你的意思是项目中的apollo-env.properties配置文件  比如dev环境  dev。mate=ip+port，ip+port  可以这样?

**Comment by nobodyiam** [comment]
比如安全部门写一个jar包，直接通过url获取apollo配置，参见[其它语言客户端接入指南](https://github.com/ctripcorp/apollo/wiki/%E5%85%B6%E5%AE%83%E8%AF%AD%E8%A8%80%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
