### ISSUE TITLE
请教宋大神：新增环境后，使用自定义Apollo Meta Server地址定位逻辑，这个ENV枚举依赖的core，client需要自己打包吗？

### ISSUE THREAD

**Issue by Evilsylvana** [ctripcorp/apollo#1822]
问题如标题所示：
我们与携程的环境参数不一样，新增了sit和prod这2个环境。这样在自定义Apollo Meta Server地址定位逻辑实现com.ctrip.framework.apollo.core.spi.MetaServerProvider时会依赖现成的client和core的包，如果不手动重新编译打包，ENV这个枚举值是不会有我们自定义的SIT和PROD枚举的。
所以com.ctrip.framework.apollo.core.spi.MetaServerProvider 这个接口是否有String入参的，而不是枚举入参。或者还有什么其他的办法？

**Comment by nobodyiam** [comment]
客户端其实不依赖ENV的，主要你的MetaServerProvider提供一个meta sever地址就可以了。

portal依赖ENV的，只需要重新打包portal即可。

**Comment by Evilsylvana** [comment]
后来想了下，忽略入参ENV，直接自己实现，没来得及关闭issue，谢谢 @nobodyiam 
`@Override
    public String getMetaServerAddress(Env targetEnv) {
        List<String> profiles = getActiveProfile();
        if (profiles.contains(PROD_PROFILE)) {
            return domains.get(PROD_PROFILE);
        } else if (profiles.contains(SIT_PROFILE)) {
            return domains.get(SIT_PROFILE);
        } else {
            //默认返回dev的profile
            return domains.get(DEV_PROFILE);
        }
    }

    @Override
    public int getOrder() {
        return ORDER;
    }

    /**
     *
     * @return
     */
    private List<String> getActiveProfile() {
        // 1. Try to get environment from JVM system property
        String profiles = System.getProperty("spring.profiles.active");
        if (isEmptyString(profiles)) {
            // 2. Try to get environment from OS environment variable
            profiles = System.getenv("spring.profiles.active");
        }
        if (isEmptyString(profiles)) {
            //默认返回开发环境profile
            return Collections.singletonList(DEV_PROFILE);
        }
        String[] activeProfiles = profiles.split(",");
        if (isEmptyArrays(activeProfiles)) {
            return Collections.singletonList(DEV_PROFILE);
        } else {
            return Arrays.asList(activeProfiles);
        }
    }`
