### ISSUE TITLE
脚本启动和停止的问题

### ISSUE THREAD

**Issue by tmjGitAccount** [ctripcorp/apollo#1823]
请问下shell脚本中的 ./###.jar 这种启动方式是如何实现的?

还有经过我本人测试,./*.jar start命令与./*.jar stop命令,后边的参数无影响,实际效果都会去启动服务,请问有人知道原因吗?

**Comment by nobodyiam** [comment]
这个是spring boot的功能，参考一下 https://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html

**Comment by tmjGitAccount** [comment]
> 这个是spring boot的功能，参考一下 https://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html

好的感谢!
