### ISSUE TITLE
Windows 本地客服端读取不到apollo配置中心的配置

### ISSUE THREAD

**Issue by 2lusy** [ctripcorp/apollo#1824]
Sync config failed, will retry. Repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository, reason: Load Apollo Config failed - appId: springboot_properties_appid, cluster: default, namespace: application, url: http://106.12.25.204:8070/configs/springboot_properties_appid/default/application?ip=192.168.56.1 [Cause: Could not complete get operation [Cause: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $ [Cause: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $]]]

**Comment by nobodyiam** [comment]
8070是portal的端口吧？meta server地址默认指向config service，一般是8080

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by wmhiness** [comment]
apollo-configservice 服务部署到了外网，然后我本地电脑访问读取配置 读不到数据也不报错 就是null。
![image](https://user-images.githubusercontent.com/23610780/99873897-384acf80-2c1e-11eb-9598-31ae1caf52ba.png)

**Comment by nobodyiam** [comment]
@wmhiness 看下日志信息吧，另外可以参考下 https://github.com/ctripcorp/apollo.net/issues/54

**Comment by wmhiness** [comment]
> @wmhiness 看下日志信息吧，另外可以参考下 [ctripcorp/apollo.net#54](https://github.com/ctripcorp/apollo.net/issues/54)

已经解决了 谢谢
