### ISSUE TITLE
请教大神，client 异常现象

### ISSUE THREAD

**Issue by timZhangww** [ctripcorp/apollo#1825]
线上：三台configservice ，两台是内网ip，一台是外网ip。client内网可以访问服务端，外网不通。

现在日志一直报错：Long polling failed, will retry in  。感觉每30秒   都会新随机一个服务端ip。

看了doLongPollingRefresh这个方法，当有一个ip可用时 就一直使用该ip。理应 不会一直报错的。

client版本是 0.11.0               本地debug  未出现这种情况。

**Comment by nobodyiam** [comment]
long polling为了负载均衡，也会切换服务器的，这个策略一直都有的，详见 https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/RemoteConfigLongPollService.java#L181

**Comment by timZhangww** [comment]
非常感谢， 下午着急，看漏了。
