### ISSUE TITLE
apollo.bootstrap.enabled 实现逻辑有问题

### ISSUE THREAD

**Issue by huafangyuan** [ctripcorp/apollo#1826]
![image](https://user-images.githubusercontent.com/20010297/50515295-af34c780-0ade-11e9-9682-56c3a3f535ea.png)
对于springBoot启动listener启动要早，对于这些需要加载配置，apollo实现原理ApolloApplicationContextInitializer就会加载不到配置项，而是读取项目本身配置
尤其对于springboot dubbo项目，就会出现问题；应该实现逻辑ApplicationListener<ApplicationEnvironmentPreparedEvent>接口，对PropertyResource进行处理

**Comment by huafangyuan** [comment]
springBoot dubbo 启动加载配置OverrideDubboConfigApplicationListener可以参考一下

**Comment by huafangyuan** [comment]
![image](https://user-images.githubusercontent.com/20010297/50515422-ad1f3880-0adf-11e9-9c7b-676348353968.png)

**Comment by huafangyuan** [comment]
刚看了，我之前用的是1.1.0;既然logback和dubbo配置加载优先，用一个配置项apollo.bootstrap.enabled不更方便一些嘛。方案一的实现可以通过实现ApplicationEnvironmentPreparedEvent监听，加载顺讯可以设置最高级@Order(value = Ordered.HIGHEST_PRECEDENCE) 来解决

**Comment by nobodyiam** [comment]
加载太靠前还是有点副作用的，比如在加载配置的时候没有日志

**Comment by oawang** [comment]
> 加载太靠前还是有点副作用的，比如在加载配置的时候没有日志

目前1.2.0版本，发现加了apollo.bootstrap.eagerLoad.enabled=true 配置后，如果此时配置中心访问不了，启动时候日志（Sync config failed, will retry. Repository {}, reason: {}）就不会输出

**Comment by oawang** [comment]
有没有更好的解决方案，加载太前是有点副作用
