### ISSUE TITLE
apollo.bootstrap.namespaces属性在bootstrap.properties文件中不起作用

### ISSUE THREAD

**Issue by mark0614** [ctripcorp/apollo#1827]
描述：在springboot项目中，apollo.bootstrap.namespaces属性在bootstrap.properties文件中不起作用，但是把文件命名成application.properties就可以，这是什么鬼？

**Comment by nobodyiam** [comment]
之前测试放在两个文件都是可以的呀，你能上传一个有问题的简易项目吗？

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
