### ISSUE TITLE
Auditing Enhancement

### ISSUE THREAD

**Issue by kezhenxu94** [ctripcorp/apollo#1831]
Hi @nobodyiam , I found that the auditing in this project is achieved by calling `com.ctrip.framework.apollo.biz.service.AuditService#audit(java.lang.String, java.lang.Long, com.ctrip.framework.apollo.biz.entity.Audit.OP, java.lang.String)` every time we perform CUD operations, one example is in the class `com.ctrip.framework.apollo.biz.service.AppNamespaceService`:

```java
  @Transactional
  public void createDefaultAppNamespace(String appId, String createBy) {
    // ...
    auditService.audit(AppNamespace.class.getSimpleName(), appNs.getId(), Audit.OP.INSERT,
                       createBy);
  }
```

this causes the auditing scatters everywhere, I'm planing to refactor this by using `EntityListeners` and `AuditingEntityListener` provided by Spring, which gathers all auditing operations in one place and no need to call `audit` explicitly.

If it is good to you, I'll work on it ASAP.

Regards.

**Comment by nobodyiam** [comment]
Sounds a good idea.

**Comment by kezhenxu94** [comment]
After investigating in this issue for a while, there are some drawbacks to fix it:
1. Not all modifications needs auditing, 
2. Introducing `EntityListeners` requires some extra dependencies, which I don't think is worthwhile.
3. Needs much refactoring
So I'll close this issue for now
