### ISSUE TITLE
同一应用在不同机器上不同配置

### ISSUE THREAD

**Issue by danielf8008** [ctripcorp/apollo#1836]
你好！
由于客户端因公所在机器有多网卡，所以需强制指定IP在配置里。如每台机器用一个namespace区分，感觉有些繁琐。有什么Best Practice？
谢谢

**Comment by nobodyiam** [comment]
这类跟着机器走的配置建议还是作为机器的环境环境走吧，如system env, system property等

如果这类配置很多的话，可以通过集群来区分

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
