### ISSUE TITLE
Unable to create local config cache directory /config-cache, reason: /config-cache

### ISSUE THREAD

**Issue by xiaoxing598** [ctripcorp/apollo#1838]
获取缓存路径的策略是什么？有显式配置缓存目录 `apollo.cacheDir=/tmp/data/cache-dir`，但却没有获取到，仍然使用相对路径 `config-cache/*` 作为绝对路径 `/config-cache/*` 。

```
Persist local cache file /config-cache/test+default+redis.properties failed, reason: /config-cache/test+default+redis.properties (没有那个文件或目录).
c.c.f.a.i.LocalFileConfigRepository : Unable to create local config cache directory /config-cache, reason: /config-cache. Will not able to cache config file.

```

**Comment by nobodyiam** [comment]
默认路径是`/opt/data/config-cache`，所以你是不是在其它地方设置过了？

**Comment by xiaoxing598** [comment]
我只在项目中有配置，不知道是哪里有影响，可以指导我如何排查这个问题吗？

**Comment by nobodyiam** [comment]
分别到 `com.ctrip.framework.apollo.spring.boot.ApolloApplicationContextInitializer#fillSystemPropertyFromEnvironment` 和 `com.ctrip.framework.apollo.util.ConfigUtil#getDefaultLocalCacheDir`加个断点排查一下这个配置是从哪里来的

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
