### ISSUE TITLE
Required String parameter 'notifications' is not present

### ISSUE THREAD

**Issue by nazavoya** [ctripcorp/apollo#1840]
我请求的地址是：
https://apollo-config-03.nazavoya.com/notifications/v2?cluster=aliyun-huabei2&dataCenter=aliyun-huabei2&appId=ba se-cas-server&ip=192.168.78.1&notifications=%5B%7B"namespaceName"%3A"application"%2C"notificationId"%3A210002%7D%2C% 7B"namespaceName"%3A"application-cas"%2C"notificationId"%3A210001%7D%5D

但是服务端给的提示是：
2019-01-06 11:21:50.072 ERROR 19326 --- [http-nio-8081-exec-6] .c.f.a.c.c.GlobalDefaultExceptionHandler : Required String parameter 'notifications' is not present

org.springframework.web.bind.MissingServletRequestParameterException: Required String parameter 'notifications' is not present

我上面的请求中是有notifications这个参数的，不知道为啥报错？

**Comment by kezhenxu94** [comment]
@nazavoya 你的 URL 编码有问题, 试试这个:

https://apollo-config-03.nazavoya.com/notifications/v2?cluster=aliyun-huabei2&dataCenter=aliyun-huabei2&appId=base-cas-server&ip=192.168.78.1&notifications=%5b%7b%22namespaceName%22%3a%22application%22%2c%22notificationId%22%3a210002%7d%2c%7b%22namespaceName%22%3a%22application-cas%22%2c%22notificationId%22%3a210001%7d%5d

**Comment by kezhenxu94** [comment]
大小写没有影响, 你后面发的这个 URL 应该不会有 notification 参数报错了, 试了一下是超时, 后面这个主要是参数 `notifications` 中的 `notificationId` 和我上面发的的不一样, 改成和上面的一样之后是可以的, 我发的和你发的两个区别只有 `notificatioinId` 值, 可以参考一下:

https://apollo-config-03.nazavoya.com/notifications/v2?cluster=aliyun-huabei2&dataCenter=aliyun-huabei2&appId=base-cas-server&ip=192.168.78.1&notifications=[{"namespaceName":"application","notificationId":240001},{"namespaceName":"application-cas","notificationId":240002}]

https://apollo-config-03.nazavoya.com/notifications/v2?cluster=aliyun-huabei2&dataCenter=aliyun-huabei2&appId=base-cas-server&ip=192.168.78.1&notifications=[{"namespaceName":"application","notificationId":210002},{"namespaceName":"application-cas","notificationId":210001}]

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
