### ISSUE TITLE
Apollo同步配置API接口

### ISSUE THREAD

**Issue by x00422559** [ctripcorp/apollo#1841]
目前官网的文档没有看到同步配置的API接口，只看到了新增删除查询等，请问同步配置的接口目前有实现吗

**Comment by nobodyiam** [comment]
感觉open api不需要提供同步配置这个粒度，通过api获取配置，然后再update就可以了？

**Comment by x00422559** [comment]
> 感觉open api不需要提供同步配置这个粒度，通过api获取配置，然后再update就可以了？

嗯，这样子也能实现。还有一个问题想请教一下，为什么apollo的这些API接口要对value进行校验呀，我们正在使用的系统有很多地方value值是空的，导致调用API的时候就会报错，请问有什么比较好的解决办法吗

**Comment by nobodyiam** [comment]
我记得文本模式是可以把value改成空的，所以value为空应该是可以的，你能看下现在是哪里做的判断吗？如果逻辑看了没问题的话，可以提个PR修改一下这块逻辑。

**Comment by neatlife** [comment]
https://www.vultr.com/?ref=7365104

**Comment by x00422559** [comment]
找着判断的地方，checkNotEmpty(itemDTO.getValue(), "Item value");，将这行注释掉之后，CloseableHttpResponse ignored = put(path, itemDTO)，这行代码会抛出异常（Request to apollo open api failed, status code: 400, reason: , message: {"exception":"com.ctrip.framework.apollo.common.exception.BadRequestException","message":"key, value and dataChangeLastModifiedBy can not be empty","status":400,"timestamp":"2019-01-09T14:32:32.499"}）
感觉是Apollo源码某处对这个做了判断

**Comment by x00422559** [comment]
多谢~~~我看这个代码merge的时候是block状态，是还需要管理员审核吗

**Comment by kezhenxu94** [comment]
@x00422559. 需要 @nobodyiam 审核合并

**Comment by nobodyiam** [comment]
Yes, I will take a look and get back to you soon.
