### ISSUE TITLE
同一台机器(相同ip) 启动两个应用(不同port) 使用灰度发布如何精确到其中一个应用

### ISSUE THREAD

**Issue by Accelerater** [ctripcorp/apollo#1842]
因为在灰度发布中 灰度规则匹配的是一个ip 所以如果我只想改其中一个的话是不是行不通？

**Comment by Accelerater** [comment]
谢谢宋大神回复 

灰度的粒度是appId + ip没错。但我这里两个应用指的是，在同一台虚机上启两个应用，这两个应用的ip是一样的，只不过启动的端口不一样。用的也是同一个配置组下的同一个namespace。

那这种情况下appId + ip是不是定位不到？需要细分粒度到appId + ip + port？

**Comment by nobodyiam** [comment]
两个应用的appId是不同的呀，难道你是同一个应用在同一台机器上启了两个进程？

**Comment by Accelerater** [comment]
是的 之前没说清楚 不好意思😥

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
