### ISSUE TITLE
如何在有cat 客户端的情况下 不初始化 cat客户端

### ISSUE THREAD

**Issue by 15215138270** [ctripcorp/apollo#1845]
![image](https://user-images.githubusercontent.com/13743439/50814524-f92a7280-1354-11e9-9491-f10abb3eb1a8.png)

现发现 cat 本地客户端初始化很慢，决定 本地调试时，根据配置 ，不初始化cat客户端。但是发现 Apollo 会 自动初始化cat客户端。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by nisiyong** [comment]
@15215138270 本地环境一般不使用CAT可以配置下环境变量，`CAT_ENABLED=false`。
这些CAT自身提供的，可以解决你这个问题
