### ISSUE TITLE
客户端注册很慢，是我配置问题还是都是这么慢？

### ISSUE THREAD

**Issue by lishangzhi** [ctripcorp/apollo#1849]
![image](https://user-images.githubusercontent.com/30685470/50874585-96da7c00-13ff-11e9-9415-f8d365a8e353.png)
![image](https://user-images.githubusercontent.com/30685470/50874595-9fcb4d80-13ff-11e9-9bd9-6535d962fe7b.png)
Started AuthBootstrap in 423.943 seconds (JVM running for 424.745)

**Comment by nobodyiam** [comment]
建议启用debug模式看看卡在哪里了

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
