### ISSUE TITLE
springboot 多环境配置集成apollo如何在启动时指定namespace

### ISSUE THREAD

**Issue by pany1708** [ctripcorp/apollo#1850]
目前项目为springboot通过application-dev.properties、application-uat.properties、application-prd.properties来区分不同环境，启动时java -jar xx.jar --spring.profiles.active=uat 这样的方式来获取对应环境的配置信息，现在集成apollo之后，比如在appid=test下有3个namespace-dev、uat、prd，我如何在启动的时候通过传入参数从apollo中获取指定namespace下的配置？
目前是用@EnableApolloConfig("uat")这样的方式，但是感觉不够灵活。

**Comment by lishangzhi** [comment]
https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#124-%E5%8F%AF%E9%80%89%E8%AE%BE%E7%BD%AE

**Comment by lishangzhi** [comment]
> 目前项目为springboot通过application-dev.properties、application-uat.properties、application-prd.properties来区分不同环境，启动时java -jar xx.jar --spring.profiles.active=uat 这样的方式来获取对应环境的配置信息，现在集成apollo之后，比如在appid=test下有3个namespace-dev、uat、prd，我如何在启动的时候通过传入参数从apollo中获取指定namespace下的配置？
> 目前是用@EnableApolloConfig("uat")这样的方式，但是感觉不够灵活。

https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#124-%E5%8F%AF%E9%80%89%E8%AE%BE%E7%BD%AE

**Comment by TryMost** [comment]
我现在也有这个问题，当我更改了部分配置需要重新加载bean的时候@EnableApolloConfig不能很好的支持不同namespace这个有点麻烦。

**Comment by TryMost** [comment]
启动方式可以通过配置namespace在properties里面apollo.bootstrap.namespaces:=dev/uat/prd来控制，但是我还遇到了一个问题，就是在namespace中更新了配置发布之后，spring中的bean需要重新加载，但是只能通过@EnableApolloConfig的方式指定namespace，感觉十分的不灵活，请问有没有什么别的方案呢？

**Comment by nobodyiam** [comment]
@pany1708 

https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#3213-spring-boot%E9%9B%86%E6%88%90%E6%96%B9%E5%BC%8F%E6%8E%A8%E8%8D%90

**Comment by pany1708** [comment]
1 apollo的namespace中新建dev.properties ,  uat.properties
2 在bootstrap.properties里增加
apollo.bootstrap.enabled = true
apollo.bootstrap.namespaces = sit
3 启动时指定 java -jar xx.jar --apollo.bootstrap.namespaces=uat
非常感谢各位的回复
