### ISSUE TITLE
1.2.0版本，拉取不到私有namespace配置

### ISSUE THREAD

**Issue by xiaopang185** [ctripcorp/apollo#1856]

**Comment by nobodyiam** [comment]
客户端会有错误日志的，可以看一下

**Comment by xiaopang185** [comment]
您好 目前看应该不是客户端问题
![image](https://user-images.githubusercontent.com/20180464/51010319-cc619f80-158e-11e9-9cfa-1780474f273a.png)
上面那个图是在configService机子上执行的 第一个是公共配置，下面两个都是私有的，都是提示404报错。
附上命名空间列表
![image](https://user-images.githubusercontent.com/20180464/51010368-fc10a780-158e-11e9-95f3-8ac7bb4691fd.png)

**Comment by bluewu** [comment]
我也遇到类似的问题

**Comment by xiaopang185** [comment]
你最后是怎么解决的?

**Comment by nobodyiam** [comment]
读取配置这块逻辑很简单的，首先通过appnamespace（内存缓存）判断是公共还是private namespace，然后直接从数据库读取配置。

除非手动改过数据库导致appnamespace的内存缓存不一致？不然不会读取不到配置的

**Comment by xiaopang185** [comment]
不好意思，我把app_id 填错了。
