### ISSUE TITLE
请问一下，我在apollo发布配置文件之后，项目这边的配置值也改变了，可是怎么让配置生效啊

### ISSUE THREAD

**Issue by 13221071988** [ctripcorp/apollo#1857]

**Comment by 13221071988** [comment]
项目不重新启动，怎么让修改的值生效呢

**Comment by nobodyiam** [comment]
api方式或者是spring `@Value`等方式都是实时生效的，其它如`@ConfigurationProperties`或者是数据库连接池之类的，可以参考[apollo-use-cases](https://github.com/ctripcorp/apollo-use-cases)

**Comment by 13221071988** [comment]
谢谢
