### ISSUE TITLE
宋大神，请问apollo数据库的隔离级别设置是什么？代码中没找到相关配置呢？

### ISSUE THREAD

**Issue by denghuichao** [ctripcorp/apollo#1860]

**Comment by kezhenxu94** [comment]
@denghuichao  没有配置就是使用底层数据库默认的隔离级别嘛，跟你数据库设置的相关，[MySQL 文档](https://dev.mysql.com/doc/refman/8.0/en/innodb-transaction-isolation-levels.html) 说 InnoDB 引擎默认隔离级别是 `REPEATABLE READ`。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
