### ISSUE TITLE
关于客户端连接过程的一点建议

### ISSUE THREAD

**Issue by mandarenmanman** [ctripcorp/apollo#1861]
[apollo-demo][main]2019-01-12 11:33:43,904 WARN  [com.ctrip.framework.foundation.internals.provider.DefaultApplicationProvider] app.id is not available from System Property and /META-INF/app.properties. It is set to null
[apollo-demo][main]2019-01-12 11:33:43,909 INFO  [com.ctrip.framework.foundation.internals.provider.DefaultServerProvider] Environment is set to null. Because it is not available in either (1) JVM system property 'env', (2) OS env variable 'ENV' nor (3) property 'env' from the properties InputStream.
[apollo-demo][main]2019-01-12 11:33:43,909 DEBUG [com.ctrip.framework.foundation.internals.provider.DefaultServerProvider] Data Center is set to null. Because it is not available in either (1) JVM system property 'idc', (2) OS env variable 'IDC' nor (3) property 'idc' from the properties InputStream.
[apollo-demo][main]2019-01-12 11:33:43,953 WARN  [com.ctrip.framework.apollo.internals.DefaultMetaServerProvider] Could not find meta server address, because it is not available in neither (1) JVM system property 'apollo.meta', (2) OS env variable 'APOLLO_META' (3) property 'apollo.meta' from server.properties nor (4) property 'apollo.meta' from app.properties
[apollo-demo][main]2019-01-12 11:33:43,957 WARN  [com.ctrip.framework.apollo.core.utils.ResourceUtils] No available properties: apollo-env.properties
[apollo-demo][main]2019-01-12 11:33:43,957 WARN  [com.ctrip.framework.apollo.core.MetaDomainConsts] Meta server address fallback to http://apollo.meta for env UNKNOWN, because it is not available in all MetaServerProviders
[apollo-demo][main]2019-01-12 11:33:43,957 WARN  [com.ctrip.framework.apollo.util.ConfigUtil] app.id is not set, please make sure it is set in classpath:/META-INF/app.properties, now apollo will only load public namespace configurations!
[apollo-demo][main]2019-01-12 11:33:48,415 WARN  [com.ctrip.framework.apollo.util.ConfigUtil] app.id is not set, please make sure it is set in classpath:/META-INF/app.properties, now apollo will only load public namespace configurations!
[apollo-demo][main]2019-01-12 11:33:48,415 WARN  [com.ctrip.framework.apollo.util.ConfigUtil] app.id is not set, please make sure it is set in classpath:/META-INF/app.properties, now apollo will only load public namespace configurations!
[apollo-demo][main]2019-01-12 11:33:50,417 WARN  [com.ctrip.framework.apollo.internals.AbstractConfigRepository] Sync config failed, will retry. Repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository, reason: Get config services failed from http://apollo.meta/services/config?appId=ApolloNoAppIdPlaceHolder&ip=192.168.1.118 [Cause: Could not complete get operation [Cause: apollo.meta]]
[apollo-demo][main]2019-01-12 11:33:50,417 DEBUG [com.ctrip.framework.apollo.internals.RemoteConfigRepository] Schedule periodic refresh with interval: 5 MINUTES
[apollo-demo][main]2019-01-12 11:33:50,419 WARN  [com.ctrip.framework.apollo.util.ConfigUtil] app.id is not set, please make sure it is set in classpath:/META-INF/app.properties, now apollo will only load public namespace configurations!
[apollo-demo][Apollo-RemoteConfigLongPollService-1]2019-01-12 11:33:50,422 DEBUG [com.ctrip.framework.apollo.internals.RemoteConfigLongPollService] Long polling will start in 2000 ms.
[apollo-demo][main]2019-01-12 11:33:50,423 WARN  [com.ctrip.framework.apollo.util.ConfigUtil] app.id is not set, please make sure it is set in classpath:/META-INF/app.properties, now apollo will only load public namespace configurations!
[apollo-demo][main]2019-01-12 11:33:50,440 WARN  [com.ctrip.framework.apollo.util.ConfigUtil] app.id is not set, please make sure it is set in classpath:/META-INF/app.properties, now apollo will only load public namespace configurations!
[apollo-demo][main]2019-01-12 11:33:50,440 WARN  [com.ctrip.framework.apollo.util.ConfigUtil] app.id is not set, please make sure it is set in classpath:/META-INF/app.properties, now apollo will only load public namespace configurations!
[apollo-demo][Apollo-RemoteConfigLongPollService-1]2019-01-12 11:33:52,442 WARN  [com.ctrip.framework.apollo.util.ConfigUtil] app.id is not set, please make sure it is set in classpath:/META-INF/app.properties, now apollo will only load public namespace configurations!
[apollo-demo][main]2019-01-12 11:33:52,442 WARN  [com.ctrip.framework.apollo.internals.LocalFileConfigRepository] Sync config from upstream repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository failed, reason: Get config services failed from http://apollo.meta/services/config?appId=ApolloNoAppIdPlaceHolder&ip=192.168.1.118 [Cause: Could not complete get operation [Cause: apollo.meta]]
[apollo-demo][main]2019-01-12 11:33:52,443 WARN  [com.ctrip.framework.apollo.util.ConfigUtil] app.id is not set, please make sure it is set in classpath:/META-INF/app.properties, now apollo will only load public namespace configurations!
[apollo-demo][main]2019-01-12 11:33:54,445 WARN  [com.ctrip.framework.apollo.util.ConfigUtil] app.id is not set, please make sure it is set in classpath:/META-INF/app.properties, now apollo will only load public namespace configurations!
[apollo-demo][Apollo-RemoteConfigLongPollService-1]2019-01-12 11:33:54,451 WARN  [com.ctrip.framework.apollo.internals.RemoteConfigLongPollService] Long polling failed, will retry in 1 seconds. appId: ApolloNoAppIdPlaceHolder, cluster: default, namespaces: application, long polling url: null, reason: Get config services failed from http://apollo.meta/services/config?appId=ApolloNoAppIdPlaceHolder&ip=192.168.1.118 [Cause: Could not complete get operation [Cause: apollo.meta]]
[apollo-demo][main]2019-01-12 11:33:56,449 WARN  [com.ctrip.framework.apollo.internals.LocalFileConfigRepository] Sync config from upstream repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository failed, reason: Get config services failed from http://apollo.meta/services/config?appId=ApolloNoAppIdPlaceHolder&ip=192.168.1.118 [Cause: Could not complete get operation [Cause: apollo.meta]]
[apollo-demo][Apollo-RemoteConfigLongPollService-1]2019-01-12 11:33:56,449 WARN  [com.ctrip.framework.apollo.util.ConfigUtil] app.id is not set, please make sure it is set in classpath:/META-INF/app.properties, now apollo will only load public namespace configurations!
[apollo-demo][main]2019-01-12 11:33:56,450 WARN  [com.ctrip.framework.apollo.util.ConfigUtil] app.id is not set, please make sure it is set in classpath:/META-INF/app.properties, now apollo will only load public namespace configurations!
[apollo-demo][main]2019-01-12 11:33:56,452 WARN  [com.ctrip.framework.apollo.internals.AbstractConfigRepository] Sync config failed, will retry. Repository class com.ctrip.framework.apollo.internals.LocalFileConfigRepository, reason: Load config from local config failed! [Cause: Cannot read from local cache file C:\opt\data\ApolloNoAppIdPlaceHolder\config-cache\ApolloNoAppIdPlaceHolder+default+application.properties]
[apollo-demo][main]2019-01-12 11:33:56,454 WARN  [com.ctrip.framework.apollo.util.ConfigUtil] app.id is not set, please make sure it is set in classpath:/META-INF/app.properties, now apollo will only load public namespace configurations!
[apollo-demo][main]2019-01-12 11:34:00,729 WARN  [com.ctrip.framework.apollo.util.ConfigUtil] app.id is not set, please make sure it is set in classpath:/META-INF/app.properties, now apollo will only load public namespace configurations!
[apollo-demo][Apollo-RemoteConfigLongPollService-1]2019-01-12 11:34:00,729 WARN  [com.ctrip.framework.apollo.internals.RemoteConfigLongPollService] Long polling failed, will retry in 2 seconds. appId: ApolloNoAppIdPlaceHolder, cluster: default, namespaces: application, long polling url: null, reason: Get config services failed from http://apollo.meta/services/config?appId=ApolloNoAppIdPlaceHolder&ip=192.168.1.118 [Cause: Could not complete get operation [Cause: apollo.meta]]
[apollo-demo][Apollo-RemoteConfigLongPollService-1]2019-01-12 11:34:02,732 WARN  [com.ctrip.framework.apollo.util.ConfigUtil] app.id is not set, please make sure it is set in classpath:/META-INF/app.properties, now apollo will only load public namespace configurations!
[apollo-demo][main]2019-01-12 11:34:02,732 WARN  [com.ctrip.framework.apollo.internals.LocalFileConfigRepository] Sync config from upstream repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository failed, reason: Get config services failed from http://apollo.meta/services/config?appId=ApolloNoAppIdPlaceHolder&ip=192.168.1.118 [Cause: Could not complete get operation [Cause: apollo.meta]]
[apollo-demo][main]2019-01-12 11:34:02,732 WARN  [com.ctrip.framework.apollo.util.ConfigUtil] app.id is not set, please make sure it is set in classpath:/META-INF/app.properties, now apollo will only load public namespace configurations!
[apollo-demo][main]2019-01-12 11:34:02,733 WARN  [com.ctrip.framework.apollo.internals.DefaultConfig] Init Apollo Local Config failed - namespace: application, reason: Load config from local config failed! [Cause: Cannot read from local cache file C:\opt\data\ApolloNoAppIdPlaceHolder\config-cache\ApolloNoAppIdPlaceHolder+default+application.properties].

这里我并未配置环境信息，根据客户端文档显示读取环境信息是根据优先级读取的,这里如果用户设置的时候以优先级最低的方式设置环境信息，客户端还是需要从高到低依次读取，是否可以在前置一个参数，指定环境信息读取优先级，假设参数为level，参数为 system,classpath,file 当指定环境信息为file时直接读取C:\opt\settings 下的文件信息，避免其他级别的环境信息读取，节省环境信息的读取时间

**Comment by nobodyiam** [comment]
感谢建议！不过目前读取环境也就3个步骤，system property -> system environment -> server.properties，最慢的也就是server.properties这一次文件IO了，总体而言并不会慢，感觉没必要为这个优化新增一个配置项。

app.id和cluster等也是同理，其实加载配置最慢的是从远端拉取配置的时候，因为拉不到的时候会有多次重试，每次重试间隔为1秒。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
