### ISSUE TITLE
Dockerfile-ENV与官方Release版本不匹配的问题

### ISSUE THREAD

**Issue by kevinten10** [ctripcorp/apollo#1862]
在Dockerfile中的环境变量为 :
ENV VERSION 1.3.0-SNAPSHOT

在官方的Release中为：
Apollo v1.2.0 Release

在dockerfile中需要以下包：
apollo-configservice-${VERSION}-github.zip

但我下载下来的是：
apollo-adminservice-1.2.0-github.zip

请教大佬，需要手动修改吗。

**Comment by JaredTan95** [comment]
@kevinten10  master 分支中的是最新源码版本，并不一定是发布版本，所以Dockerfile是适用master源码的。如果你需要根据Apollo v1.2.0 Release和Dockerfile制作镜像，则需要更改。

**Comment by kevinten10** [comment]
嗯嗯，手动更改为Release版本后部署成功了，感谢大佬们的开源工作。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
