### ISSUE TITLE
kubernetes启动Apollo服务报错Read-only file system

### ISSUE THREAD

**Issue by haoprogrammer** [ctripcorp/apollo#1864]
官方事例： 改动数据库连接和eureka.service.url 后 ，
![image](https://user-images.githubusercontent.com/31644888/51096809-519cbc80-17fa-11e9-9f8d-b2ce09a813f0.png)
执行kubectl apply -f service-apollo-config-server-prod.yaml
statefulset-apollo-config-server-prod一直启动不起来，查看日志报错如下:

`/apollo-config-server/entrypoint.sh: line 14: can't create /apollo-config-server/config/application-github.properties: Read-only file system`

尝试在Dockerfile中用mount -o remount rw /，仍然报错。
![image](https://user-images.githubusercontent.com/31644888/51096878-dbe52080-17fa-11e9-8a5a-9e31a99eb10e.png)

我用的操作系统是：centos:7.6
          用户为：root
请问下此问题如何解决，感谢

**Comment by haoprogrammer** [comment]
目前解决方案是注释掉Dockerfile中的entrypoint.sh
![image](https://user-images.githubusercontent.com/31644888/51172017-49717980-18ed-11e9-8cb0-a741a48cac46.png)，使用k8s的configmap管理

**Comment by huangtao1** [comment]
因为部署的yml中使用了configmap来挂载,所以是read-only的。但是dockerfile里面的entrypoint也处理了这个目录,所以报错。

**Comment by wulaiwei** [comment]
你好，
![image](https://user-images.githubusercontent.com/16910820/51735968-ceb21680-20c3-11e9-9867-7926139b3797.png)
注释后  ，错误提示为这个
standard_init_linux.go:207: exec user process caused "no such file or directory"

我用的操作系统是：windows10
请问下此问题如何解决，感谢

**Comment by haoprogrammer** [comment]
> 你好， 注释后，错误提示为这个 standard_init_linux.go：207：exec用户进程导致“没有这样的文件或目录”
> ![图片](https://user-images.githubusercontent.com/16910820/51735968-ceb21680-20c3-11e9-9867-7926139b3797.png)
> 
> 
> 我用的操作系统是：windows10 
> 请问下此问题如何解决，感谢
[windows和linux下编码不一致，你可以参考](https://www.cnblogs.com/cf532088799/p/7719935.html)，解决下。
k8s部署运行apollo我是在linux上，操作系统centos 7.6，本地调试的话是参考

**Comment by haoprogrammer** [comment]
> 因为部署的yml中使用了configmap来挂载,所以是read-only的。但是dockerfile里面的entrypoint也处理了这个目录,所以报错。

感谢解惑。当时这个好折腾，重新挂载目录，重拷贝配置文件 再删除都试，实在没办法才注释掉。

**Comment by wulaiwei** [comment]
你好这边已经解决了这个问题
解决方案：
第一步 
![image](https://user-images.githubusercontent.com/16910820/51880284-9fe0bc80-23b1-11e9-9b6a-34d998574d68.png)
第二步：
sed -i -e 's/\r$//' startup-kubernetes.sh
环境版本
windows10

**Comment by nobodyiam** [comment]
已经在PR #2113 中修复

**Comment by nobodyiam** [comment]
[1.4.0](https://github.com/ctripcorp/apollo/releases/tag/v1.4.0)版本已经发布，修复了此问题。
