### ISSUE TITLE
apollo 的环境设置为dev，拉取到的属性为default

### ISSUE THREAD

**Issue by wesleycheung** [ctripcorp/apollo#1866]
最近将手头的一个Springcloud项目中的Spring boot 升为2.0.7，SpringCloud升为Finchley.SR2 
然后对应的apollo也由0.7.2改为1.1.0，并且更新其配置文件app.properties
```
app.id=1000045
env=DEV
```
项目启动时，启动日志中有如下描述:
```c.c.f.f.i.provider.DefaultServerProvider 124 -- [] Environment is set to [DEV] by property 'env' in server.properties.```

然而本地拉取到的文件名为 `1000045+default+application` 
而不是原来0.7.2版本时的 `1000045+dev+application` 

请问这个可能的原因是什么？

**Comment by nobodyiam** [comment]
老版本有逻辑会默认把dev环境认为是dev集群，这个是ctrip特有的逻辑，在0.8.0版本去除了，可以参考 

https://github.com/ctripcorp/apollo/commit/f30ab9c98ea743ac92097de6ec84bf57af4ac703#diff-2fb39b6d01e83058a059a71b47c711edL74

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
