### ISSUE TITLE
关于signin登录的问题

### ISSUE THREAD

**Issue by zkshun12** [ctripcorp/apollo#1867]
从git上clone的源码，在本地通过idea启动，调用signin  post接口，提示找不到接口，但是通过scripts打包放到tomcat运行，则没有问题？
全局搜索signin登录接口，根本没有发现post类型的
请问这是有什么高级配置吗

**Comment by nobodyiam** [comment]
本地启动需要激活auth profile，参考

https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97#223-vm-options%E9%85%8D%E7%BD%AE

**Comment by zkshun12** [comment]
能否可以屏蔽登录验证，开放所有的接口访问？

**Comment by zkshun12** [comment]
thanks

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
