### ISSUE TITLE
quick start 支持 consul 吗

### ISSUE THREAD

**Issue by Dangerxfh** [ctripcorp/apollo#1873]
quick start 下的包支持consul自定义注册中心吗

**Comment by zengqinglei** [comment]
我也想这么做

**Comment by nobodyiam** [comment]
quick start不支持，分布式部署的话可以修改一下meta service的实现

**Comment by zengqinglei** [comment]
@nobodyiam 可否提供修改meta service的实现文档，如有Markdown这种文档，最好了，多谢！

**Comment by nobodyiam** [comment]
修改点其实很简单，而且和apollo本身无关的

1. 去除代码中的`@EnableEurekaServer`和`@EnableEurekaClient`，改为使用consul的注解
2. 修改`com.ctrip.framework.apollo.metaservice.service.DiscoveryService`的逻辑，接入consul
