### ISSUE TITLE
ConfigService如何获取多个namespaces配置文件

### ISSUE THREAD

**Issue by liyufu** [ctripcorp/apollo#1879]
ConfigService如何获取多个namespaces配置文件。
Spring可以通过配置 <apollo:config namespaces="application,public"/>
如果非spring项目，获取多个namesspaces的值怎么处理？
原因是因为application里面配置依赖public的全局变量。
想达到这种效果ConfigService.getConfig("application,public")

**Comment by nobodyiam** [comment]
ConfigService.getConfig每次只能获取一个，如果要获取多个的话，可以自己建一个CompositeConfig类，get多次namespace的config，然后getProperty方法重载为依次调用多个config的getProperty，类似org.springframework.core.env.CompositePropertySource

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
