### ISSUE TITLE
apollo能配置空字符串值吗？

### ISSUE THREAD

**Issue by ldcsaa** [ctripcorp/apollo#1882]
有些环境的配置想设置为“空字符串值”，请问apollo能实现吗？
例如：
my.conf.val=

**Comment by kezhenxu94** [comment]
@ldcsaa 见 #1841

**Comment by nobodyiam** [comment]
[PR 1852](https://github.com/ctripcorp/apollo/pull/1852)应该只解决了open api的问题，对于portal页面过来的可能还是不允许的

**Comment by kezhenxu94** [comment]
查了下，Portal 接口并没有对 value 是否为空作限制，只是检查 value 长度有没有超过限制而已

**Comment by ldcsaa** [comment]
> 查了下，Portal 接口并没有对 value 是否为空作限制，只是检查 value 长度有没有超过限制而已

不对呀，portal页面设置不了空字符串，提示 “value不能为空”，也无法提交。

**Comment by kezhenxu94** [comment]
看来是前端做了校验
