### ISSUE TITLE
namespace名称不能大于32个字符的bug

### ISSUE THREAD

**Issue by Saintchi** [ctripcorp/apollo#1888]
如图所示：
![image](https://user-images.githubusercontent.com/5926734/51324754-7e74fc00-1aa6-11e9-8bba-c960b1771b46.png)

说明：
-----
在appId=a，创建了一个私有的dynamic_logger是可以的；
在appId=b，再次创建私有的dynamic_logger时候，页面报错！估计是js校验或者页面切换导致的问题。

**Comment by Saintchi** [comment]
这个bug，目前我通过修改jar包里面的 static/scripts/controller/NamespaceController.js文件，暂时将32修改为128，数据库字段长度暂时未修改。

**Comment by yzh1798** [comment]
在前端校验namespace长度的时候会使用 部门名称+namespace 名称进行校验，而后台存数据库的内容为 namespace名称+namespace类型(properties类型直接就是名称),所以在创建私有namespace的时候可能要注意当部门号的长度,这个问题会不会是你appId中a和b的部门号不一致呢？

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by hemkvo** [comment]
hi
 部署的apollo 2.1.0 版本  也出现了这个问题 我需要怎么解决呢

**Comment by HadwinLing** [comment]
> hi 部署的apollo 2.1.0 版本 也出现了这个问题 我需要怎么解决呢

最后你怎么处理的呀？
