### ISSUE TITLE
Springboot 项目启动 Apollo 警告：Cannot enhance @Configuration bean definition

### ISSUE THREAD

**Issue by ldcsaa** [ctripcorp/apollo#1889]
Springboot 项目启动 Apollo 总是提示下列警告，请问是什么问题？

> 13:08:15.109 <org.springframework.context.annotation.ConfigurationClassPostProcessor>  WARN [main]: Cannot enhance @Configuration bean definition 'com.ctrip.framework.apollo.spring.boot.ApolloAutoConfiguration' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.

**Comment by kezhenxu94** [comment]
@ldcsaa 参加 #1156

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
