### ISSUE TITLE
json的namespace删除不掉？疑似bug

### ISSUE THREAD

**Issue by Saintchi** [ctripcorp/apollo#1890]
![image](https://user-images.githubusercontent.com/5926734/51371212-80859c00-1b34-11e9-9b15-1c005b418d30.png)

admin管理员，进来删除namespace，查询时候，右上角提示如下：
![image](https://user-images.githubusercontent.com/5926734/51371286-ba56a280-1b34-11e9-83b0-751bb37e4955.png)

application查询正常，如下图：
![image](https://user-images.githubusercontent.com/5926734/51371346-d9553480-1b34-11e9-86a3-0ecca1ae87ec.png)

**Comment by nobodyiam** [comment]
补缺namespace出现的话，就说明app namespace不存在，估计是环境中间有不可用的情况。

**Comment by xiangzilv123** [comment]
同样出现了这个问题，删除namespac后，刷新后有时会提示 上述信息

**Comment by nobodyiam** [comment]
如果要彻底删除appnamespace的话，需要通过管理员工具的删除功能

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
