### ISSUE TITLE
ConfigService不带缓存的Http接口返回值非标准JSON

### ISSUE THREAD

**Issue by idoop** [ctripcorp/apollo#1892]
**1.0.0版本之后的ConfigService不带缓存的Http接口返回值非标准JSON**,同时Header中缺少`Content-Length`字段.
1.0.0及之前版本无此问题.
拿Repo上的演示demo来说,请求 `http://106.12.25.204:8080/configs/myappa/default/TEST1.public`
用fiddler抓到的Raw包长这样:
![fiddler](https://user-images.githubusercontent.com/1930318/51377782-b16ecc80-1b46-11e9-8e3c-40cf91753baa.png)

**Comment by nobodyiam** [comment]
看了一下，transfer-encoding是chunked，所以content-length就没了，这个是正常了，应该是spring boot 2.0改为流式写了。

json用curl看了一下是正常的，看看是不是你的抓包工具没有很好的支持chunked

curl -i http://106.12.25.204:8080/configs/myappa/default/TEST1.public
```
HTTP/1.1 200
Content-Disposition: inline;filename=f.txt
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: SAMEORIGIN
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Fri, 18 Jan 2019 11:57:03 GMT

{"appId":"myappa","cluster":"default","namespaceName":"TEST1.public","configurations":{"test":"123123","Kafka":"Ugly"},"releaseKey":"20190118115422-aea2805d89110729"}
```

**Comment by idoop** [comment]
OK,感谢回复.
