### ISSUE TITLE
Seems like to be a bug of OPS - Namespace?

### ISSUE THREAD

**Issue by chickenlj** [ctripcorp/apollo#1893]
1. At first, I created a NS for my project, this NS extends from global NS `dubbo`
![aaa](https://user-images.githubusercontent.com/18097545/51379709-fdbc0b80-1b4a-11e9-9c21-a1ebad321e81.jpg)

2. Then I created a private NS also named `dubbo` in this project. The old one was overridden without any warning.
![bbb](https://user-images.githubusercontent.com/18097545/51379714-00b6fc00-1b4b-11e9-8a4d-dda65fc65cbd.jpg)

3. But when I want to turn this private `dubbo` to public again, I found that there's no way to achieve that. But I can repeatedly create the same `dubbo` NS (private or public) again and again with successful feedbacks but with no real effects.

Seems like the only way I can do that is: remove the private `dubbo` NS in here; then recreate a public one.
![ccc](https://user-images.githubusercontent.com/18097545/51380501-d23a2080-1b4c-11e9-8e6c-7529b4f210db.jpg)

**Comment by nobodyiam** [comment]
You are right, it's a bug...
