### ISSUE TITLE
项目通过docker部署之后，怎么使用apollo的灰度

### ISSUE THREAD

**Issue by liuyi9608** [ctripcorp/apollo#1899]
灰度规则要求配置ip，但是项目现在走的docker发布，获取不到ip这个怎么解决，求大神赐教

**Comment by nobodyiam** [comment]
尝试加一下 -Dhost.ip=xxx

**Comment by liuyi9608** [comment]
> 尝试加一下 -Dhost.ip=xxx

项目通过k8s  docker部署之后，获取不到ip，只有hostName

**Comment by nobodyiam** [comment]
获取ip的代码如下，可以参考一下，另外就算是用k8s，ip总还是有的啊

https://github.com/ctripcorp/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/foundation/internals/NetworkInterfaceManager.java#L86

**Comment by liuyi9608** [comment]
> 获取ip的代码如下，可以参考一下，另外就算是用k8s，ip总还是有的啊
> 
> https://github.com/ctripcorp/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/foundation/internals/NetworkInterfaceManager.java#L86

好的谢谢送大神，我研究一下~~

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
