### ISSUE TITLE
MySql Host is blocked because of many connection errors 

### ISSUE THREAD

**Issue by gqhuang14920** [ctripcorp/apollo#1900]
经常出现这个问题了 adminServer服务中连不上mysql

**Comment by nobodyiam** [comment]
默认应该是10个连接吧，看一下都是哪些ip在连接mysql数据库

**Comment by gqhuang14920** [comment]
同一个ip在短时间内产生太多（超过mysql数据库max_connection_errors的最大值）中断的数据库连接而导致的阻塞；

**Comment by nobodyiam** [comment]
`show processlist;`可以看到当前的连接明细，如果确认是admin service连接的话，可以通过配置控制一下最大连接数

```properties
spring.datasource.hikari.maximum-pool-size=15
```

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
