### ISSUE TITLE
Http接口从Apollo读取配置

### ISSUE THREAD

**Issue by 842172470** [ctripcorp/apollo#1901]
文档中有提到两个http接口，分别为带缓存和不带缓存的，我试了下，修改发布后，两个接口取到的都是最新的配置，请问什么情况下，两个接口取得数据会有差异呢？我打算用http带缓冲的接口取配置，不知道会有什么潜在的问题？

**Comment by nobodyiam** [comment]
没有啥潜在的问题，不带缓存的接口也可以通过配置（config-service.cache.enabled）打开缓存的
