### ISSUE TITLE
kubernetes部署service-apollo-portal-server.yaml错误

### ISSUE THREAD

**Issue by pcazheng** [ctripcorp/apollo#1905]
initContainers:name 都为check-service-apollo-admin-server-dev 部署失败

**Comment by nobodyiam** [comment]
提供下更多的信息吧

**Comment by pcazheng** [comment]
路径：https://github.com/ctripcorp/apollo/blob/master/scripts/apollo-on-kubernetes/kubernetes/service-apollo-portal-server.yaml
122行
initContainers:

        # 确保 admin-service 正常提供服务
        - image: alpine-bash:3.8
          name: **check-service-apollo-admin-server-dev**
          command: ['bash', '-c', "curl --connect-timeout 2 --max-time 5 --retry 60 --retry-delay 1 --retry-max-time 120 service-apollo-admin-server-dev.sre:8090"]
        - image: alpine-bash:3.8
          name: check-service-apollo-admin-server-dev
          command: ['bash', '-c', "curl --connect-timeout 2 --max-time 5 --retry 60 --retry-delay 1 --retry-max-time 120 service-apollo-admin-server-test-alpha.sre:8090"]
        - image: alpine-bash:3.8
          name: ### check-service-apollo-admin-server-dev
          command: ['bash', '-c', "curl --connect-timeout 2 --max-time 5 --retry 60 --retry-delay 1 --retry-max-time 120 service-apollo-admin-server-test-beta.sre:8090"]
        - image: alpine-bash:3.8
          name: ### **check-service-apollo-admin-server-dev**
          command: ['bash', '-c', "curl --connect-timeout 2 --max-time 5 --retry 60 --retry-delay 1 --retry-max-time 120 service-apollo-admin-server-prod.sre:8090"]

name都为check-service-apollo-admin-server-dev 部署失败

**Comment by nobodyiam** [comment]
[1.3.0](https://github.com/ctripcorp/apollo/releases/tag/v1.3.0)版本已经发布，已经修复此问题
