### ISSUE TITLE
config-service的启动端口启动的时候能否可配置？

### ISSUE THREAD

**Issue by mstao** [ctripcorp/apollo#1906]

**Comment by nobodyiam** [comment]
config service是一个标准的spring boot应用，可以通过server.port来配置，不过需要注意的是修改了端口后还要同步修改eureka.service.url和meta server的配置，具体参考[部署apollo-configservice](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#231-%E9%83%A8%E7%BD%B2apollo-configservice)的注3部分。

**Comment by mstao** [comment]
如果用docker就不需要考虑这个端口冲突了，因为8080端口比较常用，部署Apollo服务端时可能会与应用的端口冲突。好的，十分感谢~
