### ISSUE TITLE
配置文件中设置的env不生效

### ISSUE THREAD

**Issue by rk-pisces** [ctripcorp/apollo#1909]
使用版本为1.1.2，在配置文件bootstrap.yml中配置了env=dev和dev.meta=http...无效，启动日志如下

09:34:12.167 [main] INFO com.ctrip.framework.foundation.internals.provider.DefaultServerProvider : Environment is set to null. Because it is not available in either (1) JVM system property 'env', (2) OS env variable 'ENV' nor (3) property 'env' from the properties InputStream. 

09:34:12.290 [main] WARN com.ctrip.framework.apollo.internals.DefaultMetaServerProvider : Could not find meta server address, because it is not available in neither (1) JVM system property 'apollo.meta', (2) OS env variable 'APOLLO_META' (3) property 'apollo.meta' from server.properties nor (4) property 'apollo.meta' from app.properties 

使用apollo.meta正常，使用vm option设置env和dev.meta也正常。

**Comment by kezhenxu94** [comment]
> (3) property **'apollo.meta'** from server.properties nor (4) property **'apollo.meta'** from app.properties

日志说的是配置 `apollo.meta`, 你配的是 `dev.meta`?

**Comment by rk-pisces** [comment]
wiki里说的是配置 env=环境 和 环境_meta=...，我看了日志提示才改成apollo.meta的。问题是在VM option里使用-Denv=dev -Ddev_meta=http://localhost:8080可以正常启动，但是把这两个配置写到配置文件里就出现上述的异常了。

**Comment by kezhenxu94** [comment]
@rk-pisces 你是直接在 `bootstrap.yml` 中配置 `env=dev` 和 `dev.meta=http..` 这样格式吗? `yml` 格式是这样的:
```yml
env: dev
dev.meta: http...
```

**Comment by kezhenxu94** [comment]
> wiki里说的是配置 env=环境 和 环境_meta=...，我看了日志提示才改成apollo.meta的。问题是在VM option里使用-Denv=dev -Ddev_meta=http://localhost:8080 可以正常启动，但是把这两个配置写到配置文件里就出现上述的异常了。

wiki 链接发一下? 应该是要修改 apollo-env.properties 文件或者指定启动参数吧?

**Comment by rk-pisces** [comment]
wiki地址是
```
https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97
```

里面说的是修改apollo-env.properties， 我试了一下放在apollo-env.properties是可以的。这里的配置文件原来是固定的 ，我开始以为不管放在哪个配置文件中都可以生效的。

感谢！

**Comment by kezhenxu94** [comment]
👌 可以关闭 issue
