### ISSUE TITLE
1.2 版本回滚bug

### ISSUE THREAD

**Issue by hardyxia2018** [ctripcorp/apollo#1912]
回滚会偶发出现回滚配置显示不生效的情况， 即 在前端UI 修改某一个key 的值，发布之后 配置变更，然后点击回滚按钮， 再次对回滚的值进行发布，发现客户端实际值已经变更（回滚成功的），但是UI显示依旧是未回滚的值~~ ~ 版本V1.2

**Comment by feng257** [comment]
个人觉得应该不是bug，你看下那个值显示的是上一次发布的值，状态是未发布，所以应该是回滚了之前的状态。

**Comment by hardyxia2018** [comment]
回滚后点击发布后，UI显示的依旧是未回滚的值
示例： k1 对应旧值A ，将其值修改为B，点击发布，UI显示k1 的值为B，客户端获取的为B， ok此处没毛病；   点击回滚按钮，UI显示值为B，未发布， 点击发布，UI显示依旧为B，客户端获取值为A。难道这不算bug么？

**Comment by nobodyiam** [comment]
@hardyxia2018 

我按照你的case在demo环境试了一下，没有发现你说的这个问题。

http://106.12.25.204:8070/config.html?#/appid=config-test-app

```
Apollo Config Demo. Please input key to get the value. Input quit to exit.
> k1
> [apollo-demo][main]2019-01-24 16:41:50,263 INFO  [com.ctrip.framework.apollo.demo.api.SimpleApolloConfigDemo] Loading key : k1 with value: A
[apollo-demo][Apollo-Config-1]2019-01-24 16:42:02,505 INFO  [com.ctrip.framework.apollo.demo.api.SimpleApolloConfigDemo] Changes for namespace application
[apollo-demo][Apollo-Config-1]2019-01-24 16:42:02,506 INFO  [com.ctrip.framework.apollo.demo.api.SimpleApolloConfigDemo] Change - key: k1, oldValue: A, newValue: B, changeType: MODIFIED
> k1
> [apollo-demo][main]2019-01-24 16:42:04,557 INFO  [com.ctrip.framework.apollo.demo.api.SimpleApolloConfigDemo] Loading key : k1 with value: B
[apollo-demo][Apollo-Config-1]2019-01-24 16:42:13,488 INFO  [com.ctrip.framework.apollo.demo.api.SimpleApolloConfigDemo] Changes for namespace application
[apollo-demo][Apollo-Config-1]2019-01-24 16:42:13,488 INFO  [com.ctrip.framework.apollo.demo.api.SimpleApolloConfigDemo] Change - key: k1, oldValue: B, newValue: A, changeType: MODIFIED
> k1
> [apollo-demo][main]2019-01-24 16:42:15,742 INFO  [com.ctrip.framework.apollo.demo.api.SimpleApolloConfigDemo] Loading key : k1 with value: A
[apollo-demo][Apollo-Config-1]2019-01-24 16:42:30,518 INFO  [com.ctrip.framework.apollo.demo.api.SimpleApolloConfigDemo] Changes for namespace application
[apollo-demo][Apollo-Config-1]2019-01-24 16:42:30,518 INFO  [com.ctrip.framework.apollo.demo.api.SimpleApolloConfigDemo] Change - key: k1, oldValue: A, newValue: B, changeType: MODIFIED
> k1
> [apollo-demo][main]2019-01-24 16:42:33,872 INFO  [com.ctrip.framework.apollo.demo.api.SimpleApolloConfigDemo] Loading key : k1 with value: B

```

**Comment by hardyxia2018** [comment]
这个不是必现问题。
 回滚发布后客户端是正常，只是显示不对~~
另 现在测试的不是用quickStart，是按分布式部署方式build的

**Comment by KingWang1** [comment]
![image](https://user-images.githubusercontent.com/11324138/51819708-58552480-230e-11e9-9857-3b3312b91eb9.png)
![image](https://user-images.githubusercontent.com/11324138/51819753-7d499780-230e-11e9-8254-b7808dac5d10.png)
先点击回滚按钮查看值是回滚后的值，但是为什么点击发布没有回滚成功，还是回滚前的值

**Comment by hardyxia2018** [comment]
@nobodyiam 
用你的环境测试 bug 浮现，操作步骤1--5
![image](https://user-images.githubusercontent.com/44759712/52397370-3585f580-2af0-11e9-9366-093017f8cdaf.png)

![image](https://user-images.githubusercontent.com/44759712/52397374-3d459a00-2af0-11e9-9d23-2b16628222ab.png)


![image](https://user-images.githubusercontent.com/44759712/52397378-3fa7f400-2af0-11e9-9204-8b411912e2c8.png)

![image](https://user-images.githubusercontent.com/44759712/52397383-45053e80-2af0-11e9-95ac-9d58eaa4d63a.png)

![image](https://user-images.githubusercontent.com/44759712/52397387-49315c00-2af0-11e9-8e56-3379a448e135.png)

**Comment by nobodyiam** [comment]
@hardyxia2018 

多谢反馈，根据你的描述，是符合回滚的设计场景的，所以不是bug。不过不同的用户对回滚有不同的理解，所以可能存在一定的误解。

这里的回滚机制类似于发布系统，发布系统中的回滚操作是将部署到机器上的安装包回滚到上一个部署的版本，但代码仓库中的代码是不会回滚的，从而开发可以在修复代码后重新发布。

Apollo中的回滚也是类似的机制，点击回滚后是将发布到客户端的配置回滚到上一个已发布版本，也就是说客户端读取到的配置会恢复到上一个版本，但页面上编辑状态的配置是不会回滚的，从而开发可以在修复配置后重新发布。

**Comment by hardyxia2018** [comment]
@nobodyiam  ok 明白明白，我的意思就是说前端UI和客户端获取不一致的情况，回滚发布后，客户端获取确实符合预期。  ~~ 建议加一个回滚记录，否则时间久 久不确定客户端与服务端UI是否一致的了

**Comment by nobodyiam** [comment]
@hardyxia2018 

回滚的记录在发布历史中可以看到的

![image](https://user-images.githubusercontent.com/837658/52412612-3c296280-2b1a-11e9-8ff1-b5d1b11a985e.png)

**Comment by hardyxia2018** [comment]
好的，感谢~

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by lancelothuxi** [comment]
这个合理么，正常理解都是页面也回滚到志气之前配置，然后点击发布才生效吧，生产踩坑了。
