### ISSUE TITLE
获取记录被谁修改的接口

### ISSUE THREAD

**Issue by hardyxia2018** [ctripcorp/apollo#1913]
现在好像没有提供某记录被谁修改的接口，如果要获取被谁修改，客户端则需要查询服务端的数据库commit表数据。

**Comment by nobodyiam** [comment]
客户端为啥要获取是谁修改的？用户在portal界面上可以看的

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
