### ISSUE TITLE
appllo configservice 在linux环境下启动start.sh脚本报错

### ISSUE THREAD

**Issue by panGod** [ctripcorp/apollo#1915]
appllo configservice 在linux环境下启动start.sh脚本报错No pid file found, startup may failed. Please check logs under /opt/logs/100003171 and /tmp for more information!

但是在/opt/logs/下面找不到任何日志，求帮助

**Comment by panGod** [comment]
改了一下脚本，输出了一下报错日志，
ls: cannot access apollo-configservice*.pid: No such file or directory

**Comment by nobodyiam** [comment]
到/tmp目录下看看

**Comment by nobodyiam** [comment]
直接用java -jar运行apollo-configservice的jar跑一下看看

**Comment by panGod** [comment]
使用Java -jar就可以跑了

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by liutao5121** [comment]
我认为这是一个脚本bug，apollo2.0.1版本configservice模块启动脚本也报错：
No pid file found, startup may failed

**Comment by HadwinLing** [comment]
> 我认为这是一个脚本bug，apollo2.0.1版本configservice模块启动脚本也报错： No pid file found, startup may failed

后面你们是怎么处理的呀？
