### ISSUE TITLE
docker-compose 里面的 Apollo 是最新的吗?

### ISSUE THREAD

**Issue by wujunze** [ctripcorp/apollo#1917]
你好:
       请问docker-compose 里面的 Apollo 是最新的吗?

**Comment by nobodyiam** [comment]
docker compose中使用的是apollo的quick start版本，是最新的1.2.0

https://cloud.docker.com/u/nobodyiam/repository/docker/nobodyiam/apollo-quick-start

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
