### ISSUE TITLE
请问怎么增加 修改部门

### ISSUE THREAD

**Issue by wujunze** [ctripcorp/apollo#1918]
![image](https://user-images.githubusercontent.com/12997869/51668308-dd81c600-1ffc-11e9-9f9e-62807bdee2db.png)

请问怎么增加 修改部门   如图    docker-compose 安装的

**Comment by nobodyiam** [comment]
https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#2131-%E8%B0%83%E6%95%B4apolloportaldb%E9%85%8D%E7%BD%AE

**Comment by hardyxia2018** [comment]
改db数据

**Comment by wujunze** [comment]
> https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#2131-%E8%B0%83%E6%95%B4apolloportaldb%E9%85%8D%E7%BD%AE



> 改db数据

 好的 我试试  不考虑做成功能吗

**Comment by Zhang21** [comment]
兄弟，看文档呀，更改对应Key里面的值。

**Comment by nobodyiam** [comment]
@wujunze 

环境增加在实际部署中是比较少出现的，所以目前没有特意做一个功能

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
