### ISSUE TITLE
环境列表不显示

### ISSUE THREAD

**Issue by tanxiaosheng** [ctripcorp/apollo#1919]
安装了dev和prod两个环境，启动portal之后环境列表只显示dev，找不到prod，并没有补缺环境的提示，在portal页面的系统信息中，正常显示pro和dev的信息，都注册成功，查看日志也没有报错或者警告，这是什么原因呢？如何定位问题？

**Comment by nobodyiam** [comment]
https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#4-portal%E5%A6%82%E4%BD%95%E5%A2%9E%E5%8A%A0%E7%8E%AF%E5%A2%83

文档先看一下，是否有遗漏的配置，再看一下Portal的日志

**Comment by tanxiaosheng** [comment]
重新部署了一下，只开启prod环境和portal，发现了portal日志报错，
No available admin server.Maybe because of meta server down or all admin server down.Meta server address :http://apollo.meta
但是portal日志也显示Located meta server address http://service-apollo-config-server-prod.apollo:8080.
curl这个地址也是没问题的。
我进入到config server和admin server    @@@日志也没有报错，eureka.service.url地址也是正确的，1.2.0版本，通过configmap传入地址，curl测试这些地址也是没问题的。
@nobodyiam

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by wwwsky86** [comment]
用的apollo 2.1.0 版本，遇到类似问题：
自定义了3个环境，“qa,pre,prod”
管理员工具-系统参数-ConfigDB配置管理，切换环境，“qa、pre” 显示正常
切到prod环境，报错:
      message: "No available admin server. Maybe because of meta server down or all admin server down. Meta server address: http://apollo.meta",status: 500

三个环境的配置如下：
# cat /opt/apollo/apollo-portal/config/apollo-env.properties  |grep -vi "^#"
qa.meta=http://10.10.209.67:8080,http://10.10.209.68:8080,http://10.10.209.69:8080
pre.meta=http://10.10.209.64:8080
prod.meta=http://172.20.19.83:8080

如果把 prod换成 pro 或 proda （修改：portal DB配置，apollo-env.properties），均为正常。ENV的关键字“PROD” 就报错
