### ISSUE TITLE
添加自定义环境ENV，客户端无法使用

### ISSUE THREAD

**Issue by roneywei** [ctripcorp/apollo#1920]
1、修改com.ctrip.framework.apollo.core.enums.Env类，在其中加入SIT枚举：

    public enum Env{
      LOCAL, DEV, SIT, FWS, FAT, UAT, LPT, PRO, TOOLS, UNKNOWN;
      ...
    }

2、修改com.ctrip.framework.apollo.core.enums.EnvUtils类，在其中加入SIT枚举的转换逻辑：

    public final class EnvUtils {
      
      public static Env transformEnv(String envName) {
        if (StringUtils.isBlank(envName)) {
          return Env.UNKNOWN;
        }
        switch (envName.trim().toUpperCase()) {
          ...
          case "SIT":
            return Env.SIT;
          ...
          default:
            return Env.UNKNOWN;
        }
      }
    }

3、修改apollo-env.properties，增加sit.meta占位符：

        local.meta=${local_meta}
        dev.meta=${dev_meta}
        sit.meta=${sit_meta}
        fat.meta=${fat_meta}
        uat.meta=${uat_meta}
        lpt.meta=${lpt_meta}
        pro.meta=${pro_meta}

4、修改com.ctrip.framework.apollo.core.internals.LegacyMetaServerProvider类，增加读取SIT环境的meta server地址逻辑：
    
    private void initialize() {
        Properties prop = new Properties();
        prop = ResourceUtils.readConfigFile("apollo-env.properties", prop);
    
        domains.put(Env.LOCAL, getMetaServerAddress(prop, "local_meta", "local.meta"));
        domains.put(Env.DEV, getMetaServerAddress(prop, "dev_meta", "dev.meta"));
        domains.put(Env.SIT, getMetaServerAddress(prop, "sit_meta", "sit.meta"));
        domains.put(Env.FAT, getMetaServerAddress(prop, "fat_meta", "fat.meta"));
        domains.put(Env.UAT, getMetaServerAddress(prop, "uat_meta", "uat.meta"));
        domains.put(Env.LPT, getMetaServerAddress(prop, "lpt_meta", "lpt.meta"));
        domains.put(Env.PRO, getMetaServerAddress(prop, "pro_meta", "pro.meta"));
    }

以上是我在服务端添加的针对自定义的sit环境，在客户端使用的时候，无法使用

![image](https://user-images.githubusercontent.com/5858867/51672039-7d435200-2005-11e9-85e2-f6969c94d618.png)

请问，是不是要修改客户端依赖

客户端依赖了core模块
![image](https://user-images.githubusercontent.com/5858867/51672367-4883ca80-2006-11e9-9f41-efed3f3224d2.png)

**Comment by nobodyiam** [comment]
建议客户端通过apollo.meta来获取meta server地址，如果希望客户端识别sit环境的话，需要重新发布apollo-core.jar的

**Comment by roneywei** [comment]
我知道可以通过发包解决此问题，但是有没有办法不发布包能让客户端识别sit环境？

**Comment by nobodyiam** [comment]
客户端不需要识别环境的，客户端只需要知道apollo.meta地址就可以了，比如可以在server.properties中设置sit环境的apollo.meta地址，那么客户端就会自动识别了，更多信息可以参考一下java客户端使用文档

**Comment by roneywei** [comment]
好的，多谢，我去试一下看看行不行

**Comment by roneywei** [comment]
问题已经解决，谢谢
