### ISSUE TITLE
接入程序启动出现404错误

### ISSUE THREAD

**Issue by lx3xun** [ctripcorp/apollo#1923]
`
![image](https://user-images.githubusercontent.com/6147862/51728064-b6350280-20a9-11e9-80b1-b8254b33e9bb.png)

`
程序启动正常可以获取到服务器的配置，但是一直提示404错误。

**Comment by nobodyiam** [comment]
404说明对应的配置不存在或者没有发布

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
