### ISSUE TITLE
本地部署后，创建公共namespace，获取不到公共namespace的配置

### ISSUE THREAD

**Issue by benxiaohaimx** [ctripcorp/apollo#1924]
本地部署后，创建公共namespace，获取不到公共namespace的配置，关联公共namespace也还是获取不到，请问这应该是哪方面问题呢？谢谢。

**Comment by nobodyiam** [comment]
可以跟着config controller的代码看一下， 可能的原因是新环境的appnamespace数据没有补全，如果1.2.0版本的话，页面上会有补缺namespace的提示的

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
