### ISSUE TITLE
能不能设置多个管理员

### ISSUE THREAD

**Issue by sunnyvinson** [ctripcorp/apollo#1927]
现在只有一个apollo/admin，请问能不能设置多个管理员？同等权限的

**Comment by Zhang21** [comment]
兄弟，看文档呀。

这个功能可以的，修改某个key的值就行了。

**Comment by nobodyiam** [comment]
可以参考[3.superAdmin - Portal超级管理员](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#3superadmin---portal%E8%B6%85%E7%BA%A7%E7%AE%A1%E7%90%86%E5%91%98)

**Comment by sunnyvinson** [comment]
> 可以参考[3.superAdmin - Portal超级管理员](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#3superadmin---portal%E8%B6%85%E7%BA%A7%E7%AE%A1%E7%90%86%E5%91%98)

去年接触时候，这块文档好像没有说多个之间用逗号隔开，刚查看了最新文档发现有了，多谢

**Comment by sunnyvinson** [comment]
> 可以参考[3.superAdmin - Portal超级管理员](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#3superadmin---portal%E8%B6%85%E7%BA%A7%E7%AE%A1%E7%90%86%E5%91%98)

去年接触时候，这块文档好像没有说多个之间用逗号隔开，刚查看了最新文档发现有了，多谢

> 兄弟，看文档呀。
> 
> 这个功能可以的，修改某个key的值就行了。

已经找到

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
