### ISSUE TITLE
hi,if my prod cluster across several countries, how to deploy it?

### ISSUE THREAD

**Issue by ermazi** [ctripcorp/apollo#1928]
i have two methods:
1. one prod admin&config server cluster, use logical CLUSTER to distinguish, but this will depend on network. i dont know if config server with reply with the nearest adminserver
2. multi prod envs, like CNPRO,IDPRO,INPRO. all env cluster use common portal service

any recommends

**Comment by nobodyiam** [comment]
please take a look at #1294 first, it may help

**Comment by nobodyiam** [comment]
This issue is closed for now. Please provide more information if further assistance is needed, Thanks!
