### ISSUE TITLE
使用docker部署1.2.0以后，创建项目报错

### ISSUE THREAD

**Issue by 601704655** [ctripcorp/apollo#1931]
创建项目的时候报错，请问一下这个怎么解决，我直接下载的idoop镜像，数据库版本是5.7以上，![4ksbo3 d s ytk7n6g0nw](https://user-images.githubusercontent.com/47140430/51899500-1bf8f580-23ee-11e9-991c-52998c77a203.png)

**Comment by kezhenxu94** [comment]
@601704655 能不能提供一下后台的日志? 像错误堆栈信息?

**Comment by 601704655** [comment]
@kezhenxu94 我找到原因了，是因为ServiceConfig表中的organizations的value中orgId有空格就会报错

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
