### ISSUE TITLE
apollo admin service 实际的作用是什么？

### ISSUE THREAD

**Issue by hardyxia2018** [ctripcorp/apollo#1934]
如题

**Comment by kezhenxu94** [comment]
@hardyxia2018 可以参考 WIKI [Apollo配置中心设计#12-架构模块](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1#12-%E6%9E%B6%E6%9E%84%E6%A8%A1%E5%9D%97)

> Admin Service提供配置的修改、发布等功能，服务对象是Apollo Portal（管理界面）

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
