### ISSUE TITLE
开放平台添加配置和修改配置的接口可以统一吗

### ISSUE THREAD

**Issue by lixiaolihua** [ctripcorp/apollo#1936]
### 开放平台添加配置和修改配置的接口可以统一吗

就是在更新配置时，没有就自动添加一个新配置，有就更新已有的配置。类似数据库中的upsert操作。

**Comment by nobodyiam** [comment]
有一个createOrUpdateItem接口的，portal需要版本为1.1.0及以上

https://github.com/ctripcorp/apollo/blob/master/apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/client/ApolloOpenApiClient.java#L119

**Comment by lixiaolihua** [comment]
已经解决了

update接口加一个`createIfNotExists=true`参数就可以了
