### ISSUE TITLE
使用idoop部署docker版本apollo以后，无法获取到config真实ip

### ISSUE THREAD

**Issue by 601704655** [ctripcorp/apollo#1938]
客户端项目配置apollo.meta的是公网地址，结果config服务获取的是docker里面的ip地址，这个怎么解决
![image](https://user-images.githubusercontent.com/47140430/51969554-a9e8e500-24af-11e9-99d7-b4455096a08c.png)

**Comment by nobodyiam** [comment]
参考一下[1.4、网络策略](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#14%E7%BD%91%E7%BB%9C%E7%AD%96%E7%95%A5)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by boyxiaopang** [comment]
这个问题实际不是部署问题,是客户端应该如何配置,才能在portal里看到客户端程序的真实ip
