### ISSUE TITLE
docker-compose下怎样启用cors

### ISSUE THREAD

**Issue by lly277365** [ctripcorp/apollo#1942]
你好，想问一下怎样在docker-compose下支持js跨域读取配置，目前报错不支持cors，是否有类似consul下面这种的配置：
"http_config": {
	"response_headers": {
	  "Access-Control-Allow-Origin": "*"
	}
}
谢谢

**Comment by lly277365** [comment]
> 在什么情况下需要跨域？

很多情况都会有吧，例如开发阶段，本机是localhost，apollo配置中心的地址可能是192.168.0.195，这样在前端直接读取配置时就跨域了

**Comment by nobodyiam** [comment]
`前端直接读取配置`是指js通过ajax获取配置？

这个要修改com.ctrip.framework.apollo.common.controller.WebMvcConfig，增加以下代码，参考 https://spring.io/blog/2015/06/08/cors-support-in-spring-framework#global-cors-configuration

```java
    @Override
    public void addCorsMappings(CorsRegistry registry) {
        registry.addMapping("/**");
    }
```

**Comment by lly277365** [comment]
多谢了
