### ISSUE TITLE
AtomicReference的使用场景疑问

### ISSUE THREAD

**Issue by lhl4546** [ctripcorp/apollo#1943]
版本：master
类：com.ctrip.framework.apollo.internals.DefaultConfig
问题描述：DefaultConfig中的m_resourceProperties变量为何要用AtomicReference包装？
问题背景：在DefaultConfig类中有个字段m_resourceProperties，从DefaultConfig代码上下文来看这个字段仅用于存放一个Properties的引用，全文对m_resourceProperties这个变量的引用仅有get\set方法，而AtomicReference的get\set方法并未有任何特殊之处，仅用于获取、设置一个volatile变量而已。如果只是为了达到安全变更Properties引用的目的，那么直接在DefaultConfig中声明一个volatile修饰的Properties变量即可，完全不必使用AtomicReference。
根据[jls17.7](https://docs.oracle.com/javase/specs/jls/se11/html/jls-17.html#jls-17.7)节所述，java层面的reference读写是原子操作。

**Comment by nobodyiam** [comment]
看了下代码，确实没有啥特殊之处，是可以用volatile代替的
