### ISSUE TITLE
请问 configservice 中 /services/meta 及其后面的meta service发现逻辑是否还有用

### ISSUE THREAD

**Issue by qct** [ctripcorp/apollo#1950]
https://github.com/ctripcorp/apollo/blob/c8f84a63048644d1ca39d5f250d8eb53ee9efd40/apollo-configservice/src/main/java/com/ctrip/framework/apollo/metaservice/controller/ServiceController.java#L25

https://github.com/ctripcorp/apollo/blob/c8f84a63048644d1ca39d5f250d8eb53ee9efd40/apollo-configservice/src/main/java/com/ctrip/framework/apollo/metaservice/service/DiscoveryService.java#L30

**Comment by nobodyiam** [comment]
看代码没地方用到

**Comment by qct** [comment]
:+1: 谢谢
