### ISSUE TITLE
portal 里面部分项目不显示“新加配置”按钮

### ISSUE THREAD

**Issue by filamoon** [ctripcorp/apollo#1951]
求助，是哪个表的配置数据缺失，导致不显示这个按钮？在文本模式下可以添加新配置项，就是不太方便。

**Comment by nobodyiam** [comment]
properties格式的namespace才可以用表格模式编辑，其它格式的是只有文本模式的

**Comment by filamoon** [comment]
是 properties 格式的，表格可以编辑可以删除，但是没有“添加”按钮

**Comment by nobodyiam** [comment]
是关联的公共namespace吧？一般对于公共namespace是覆盖为主，所以目前没有新增配置按钮，通过文本模式确实可以绕过这个限制

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by zihan524** [comment]
> 是关联的公共namespace吧？一般对于公共namespace是覆盖为主，所以目前没有新增配置按钮，通过文本模式确实可以绕过这个限制

对呀，通过文本模式或者灰度发布新增一个key=value的配置，这样有效吗？可以读到这个新增的key=value的配置不而不影响公共配置的覆盖和获取。

**Comment by zihan524** [comment]
> 是关联的公共namespace吧？一般对于公共namespace是覆盖为主，所以目前没有新增配置按钮，通过文本模式确实可以绕过这个限制

还有一点是覆盖此配置的时候修改key为不同的值也可以新增一个配置。
