### ISSUE TITLE
多实例部署，每个实例都由SIT,UAT,PRO, 能否公用一套Portal

### ISSUE THREAD

**Issue by etdick** [ctripcorp/apollo#1955]
我有个系统，需要多个客户部署，每个客户都有SIT,UAT,PRO（A客户SIT地址 ip1，B客户SIT地址为iP2）  请问我能否用一套Portal管理。如果可以，请问meta service应该如何配置？

**Comment by nobodyiam** [comment]
对客户端只需要配置apollo.meta即可，不需要配置env信息，比如在a客户的sit环境配置apollo.meta=http://ip1

对portal，可以创建多个环境，比如sit1, sit2, uat1, uat2等，然后sit1_meta=http://ip1, sit2_meta=http://ip2，这块需要定制一下portal，增加自定义的环境，更多信息可以参考[添加自定义的环境](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#42-%E6%B7%BB%E5%8A%A0%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84%E7%8E%AF%E5%A2%83)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
