### ISSUE TITLE
高可用部署时无故跳转到首页

### ISSUE THREAD

**Issue by wkcaeser** [ctripcorp/apollo#1957]
在项目配置管理页面，点击环境列表选择环境或者下面的管理项目、添加集群、添加namespace功能时，偶尔会出现直接跳转到首页的情况。

随机触发，当操作间隔时间较长时触发频率较高

**Comment by nobodyiam** [comment]
portal做了高可用部署是指部署了多台？登录是用的公司sso还是默认的spring security？默认的spring security不支持集群登录的，有可能会出现跳转。

**Comment by wkcaeser** [comment]
用的默认的，portal有两个节点，用阿里云的slb做的主备    我刚刚试了下slb后面就挂一个节点，也还是触发了

**Comment by wkcaeser** [comment]
![flash1](https://user-images.githubusercontent.com/19384711/52760233-c5282880-3049-11e9-8d6e-7a021254d163.png)
![flash2](https://user-images.githubusercontent.com/19384711/52760237-c9ecdc80-3049-11e9-8683-54db07553f30.png)
这个flash.js是干嘛？会触发无故跳转到主页这个行为时，我看network，每次点击后只要加载flash.js，就会出现，如果没有加载就是正常的。 
从network上看，触发这种情况就伴随着flash.js

**Comment by wkcaeser** [comment]
![portal](https://user-images.githubusercontent.com/19384711/52761294-c0657380-304d-11e9-8df8-562d358d23c2.png)
跳转时还一个一闪而过的错误提示，好像是因为录屏帧数不够，截取不出来

**Comment by nobodyiam** [comment]
apollo代码中没有flash.js的，你改过 default_sso_heartbeat.html 这个文件？

**Comment by wkcaeser** [comment]
没有。  我刚刚又试验了下截屏，好像找到原因了

![apollobug](https://user-images.githubusercontent.com/19384711/52774228-b5273d80-3077-11e9-8dbb-01827073ac2e.png)
应该是这个原因

flash.js我搜索代码也没发现，但是我看network里面有

**Comment by wkcaeser** [comment]
看错误提示应该是点击按钮操作时需要获取appID，但是没有获取到，所以导致页面由项目配置页面直接弹到首页去了。但是我对前端不太熟，目前还不知道原因

**Comment by nobodyiam** [comment]
是否能稳定重现？另外，是否有其它的ajax加载失败的？

**Comment by wkcaeser** [comment]
多操作几次就偶尔会出现下    而且这个错误提示貌似还不是我之前看到的那个  我今天应该一共看到三个错误提示   一个是这个没获取到appId  还一个是上面那个angular编译错误啥的    还有个错误提示挺长的，上午出现的，但是录屏的时候看到了，但是截取的时候可能因为录屏帧率不够，那一瞬间没有录进来，现在那个错误没复现出来      不过闪退到首页这个算是能稳定复现的

**Comment by wkcaeser** [comment]
每次出现这种情况，好像都是network会加载flash.js，然后卡顿一下出现   但是我搜索代码并没有找到flash.js      

![flash1](https://user-images.githubusercontent.com/19384711/52775156-f0c30700-3079-11e9-8aac-cbd0fd688854.png)
flash.js这个请求也挺奇怪的

**Comment by wkcaeser** [comment]
[13秒复现](https://cache.wkcaeser.com/vedio/portalbug.mp4)
[4min多次复现](https://cache.wkcaeser.com/vedio/portal1.mp4)

这是我录的屏，您可以看看

**Comment by nobodyiam** [comment]
flash.js那个ip你认识吗？是不是某个chrome插件导致的？

**Comment by wkcaeser** [comment]
不认识  我查了下是澳大利亚的     我chrome上会产生影响的应该就只有Adblock Plus，但是我看Adblock Plus显示此页面没有拦截过东西

**Comment by wkcaeser** [comment]
而且这个在别的同事电脑也能复现，基本排除了插件影响吧

**Comment by nobodyiam** [comment]
另外，也可以用你的浏览器试一下demo环境，http://106.12.25.204:8070/

**Comment by nobodyiam** [comment]
default_sso_heartbeat.html的返回内容也看一下吧

**Comment by wkcaeser** [comment]
复现了

**Comment by wkcaeser** [comment]
这个demo环境也有flash.js   
 default_sso_heartbeat.html结果是200，这个flash.js我看好像是default_sso_heartbeat.html里面内嵌的
![sso](https://user-images.githubusercontent.com/19384711/52777231-413c6380-307e-11e9-9889-6f936de877b3.png)

**Comment by nobodyiam** [comment]
我感觉你的网络环境被劫持了。。

**Comment by wkcaeser** [comment]
谢谢您。确实是网络劫持，然后采用https解决的。但是在解决过程中发现一个问题，我的服务前面有反向代理，然后通过在代理上配置TLS来做https访问的，但是在使用过程发现，还是/sso_heartbeat这个请求，他内部是个重定向，重定向到default_sso_heartbeat.html的。但是这个重定向的结果是个http请求，导致这个心跳请求直接被游览器给屏蔽掉了，这个是由于servlet重定向默认使用的绝对地址导致的，我修改了配置项进行了修复 #1967
