### ISSUE TITLE
portal端口错误，启动失败

### ISSUE THREAD

**Issue by tanxiaosheng** [ctripcorp/apollo#1958]
因为项目需要，修改了基础镜像，因此重新制作了apollo的镜像，同时修改了启动脚本，其中启动portal jar包的部分，修改为java -jar apollo-portal.jar start，启动JAVA_OPTS中-Dserver.port=8070，保持不变，但是启动portal之后发现Tomcat initialized with port(s): 8080 (http)，为什么启动的不是指定的8070端口，而变成了8080端口呢？导致k8s检测8070端口的readiness一直失败 @nobodyiam

**Comment by tanxiaosheng** [comment]
找到原因了，使用fabric8的基础镜像，不支持直接执行shell脚本，所以无法使用./apollo-portal.jar的方式执行，因此一开始使用了java -jar的方式执行，导致配置参数都没有生效。但是如果使用sh apollo-portal.jar的方式执行会报错，apollo-portal.jar: line 151: syntax error: unexpected "(" (expecting "fi")，
 这是由于与bash不兼容导致的，能不能考虑修复一下问题？
随便说一下apollo-portal.jar中application.yml中的server.port=8080，而不是8070。 @nobodyiam

**Comment by nobodyiam** [comment]
bash那个是spring boot的脚本，可以通过vi apollo-portal.jar来查看脚本内容。

application.yml中server.port=8080这个后续改一下，不过一般都是通过startup.sh启动的，这个配置不会起作用

**Comment by nobodyiam** [comment]
#1961 修改了application.yml中的server.port

**Comment by tanxiaosheng** [comment]
看到jar包中的启动脚本了，这一段脚本是怎么加上去的呢？如何修改？启动失败的原因就是这段脚本和当前镜像的shell不兼容，arguments=(-Dsun.misc.URLClassPath.disableJarChecking=true $JAVA_OPTS -jar $jarfile $RUN_ARGS "$@") ,不支持()的形式进行赋值。

**Comment by nobodyiam** [comment]
这个是spring boot插件打进去的，你要不试试升级spring boot maven plugin的版本后重新打包试试，当前是1.3.5，比较老，https://github.com/ctripcorp/apollo/blob/master/pom.xml#L429

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
