### ISSUE TITLE
有考虑做不同环境配置比较功能吗

### ISSUE THREAD

**Issue by borisbao** [ctripcorp/apollo#1966]
有考虑做不同环境配置比较功能吗?
看到同步的时候 其实有比较的
能单独开放一个入口吗

**Comment by kezhenxu94** [comment]
我可以尝试做一下，后续提 PR

**Comment by woodslee** [comment]
+1，这个功能很好

**Comment by kezhenxu94** [comment]
@borisbao @woodslee 
刚刚提交了一个 PR, 可以看看是否符合需求 :)

比较按钮放在原来同步按钮旁边, 这个按钮的位置在哪里还可以再讨论:

![image](https://user-images.githubusercontent.com/15965696/53154291-69374400-35f5-11e9-8aca-3004a79e4f6b.png)

对比界面如图:
![image](https://user-images.githubusercontent.com/15965696/53154357-908e1100-35f5-11e9-887e-ed5bf10a42e3.png)

![image](https://user-images.githubusercontent.com/15965696/53154273-60df0900-35f5-11e9-81cd-d98cd1b319e7.png)

**Comment by nobodyiam** [comment]
[1.4.0](https://github.com/ctripcorp/apollo/releases/tag/v1.4.0)版本已经发布，增加了不同环境/集群比较配置的功能。
