### ISSUE TITLE
Docker部署问题

### ISSUE THREAD

**Issue by 3234523682** [ctripcorp/apollo#1968]
你好，部署时遇到一个问题，麻烦有空时给予解答。执行以下命名后，服务是启动了，但是服务启动完成后，docker容器就会自动关闭。
docker run -p 8080:8080 -d -v /tmp/logs:/opt/logs --name apollo-configservice apollo-configservice

**Comment by nobodyiam** [comment]
一般是启动失败导致的，看看日志吧

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
