### ISSUE TITLE
更新最新代码，发现代码打包失败，针对mockito-core不存在ArgumentMatchers类

### ISSUE THREAD

**Issue by roneywei** [ctripcorp/apollo#1974]
![image](https://user-images.githubusercontent.com/5858867/52941643-4530f400-33a4-11e9-87b7-3bb84e8fd2e1.png)

**Comment by nobodyiam** [comment]
maven refresh一下，mockito的版本已经升级到2.15.0了

**Comment by roneywei** [comment]
问题已经解决，谢谢
