### ISSUE TITLE
1.3新版本数据导入问题

### ISSUE THREAD

**Issue by Li-JH** [ctripcorp/apollo#1975]
请问1.3新版本的数据导入接口应该怎么用？写了个springboot工程去调用这个服务，怎么也调不通，这里面有权限问题吗？可不可以给个示例代码？谢谢。

**Comment by nobodyiam** [comment]
导入接口目前是放在portal这一层的，没有放在open api这一层，所以调用的时候需要带上portal已认证用户的cookie
