### ISSUE TITLE
portal部署后，访问无需用户验证

### ISSUE THREAD

**Issue by bluewu** [ctripcorp/apollo#1976]
使用buld.bat打包，“-Dapollo_profile=github,auth”没有修改的，发布启动后。直接访问端口即可进入界面。不需要用户登录。

**Comment by nobodyiam** [comment]
jps -v看一下实际运行的profile是什么

**Comment by bluewu** [comment]
前边是jvm的内存参数  -Duser.timezone=Asia/Shanghai -Dclient.encoding.override=UTF-8 -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom -Dserver.port=8072 -Dlogging.file=/opt/logs/apollop

**Comment by bluewu** [comment]
-Djava.security.egd=file:/dev/./urandom   portal文件start.sh里边的这个文件，是什么作用呢。

**Comment by nobodyiam** [comment]
没看到profile相关的参数？

**Comment by bluewu** [comment]
5643 jar -Xms256m -Xmx256m -Xmn96m -Xss256k -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=85 -XX:CMSFullGCsBeforeCompaction=5 -XX:+UseCMSCompactAtFullCollection -Xverify:none -XX:+PrintGCTimeStamps -XX:+PrintGCDetails -Xloggc:/data/apollo/eureka/gc.log
3535 apollo-portal.jar -Dsun.misc.URLClassPath.disableJarChecking=true -Xms256m -Xmx256m -Xss256k -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=384m -XX:NewSize=128m -XX:MaxNewSize=128m -XX:SurvivorRatio=8 -XX:+UseParNewGC -XX:ParallelGCThreads=4 -XX:MaxTenuringThreshold=9 -XX:+UseConcMarkSweepGC -XX:+DisableExplicitGC -XX:+UseCMSInitiatingOccupancyOnly -XX:+ScavengeBeforeFullGC -XX:+UseCMSCompactAtFullCollection -XX:+CMSParallelRemarkEnabled -XX:CMSFullGCsBeforeCompaction=9 -XX:CMSInitiatingOccupancyFraction=60 -XX:+CMSClassUnloadingEnabled -XX:SoftRefLRUPolicyMSPerMB=0 -XX:+CMSPermGenSweepingEnabled -XX:CMSInitiatingPermOccupancyFraction=70 -XX:+ExplicitGCInvokesConcurrent -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCApplicationConcurrentTime -XX:+PrintHeapAtGC -XX:+UseGCLogFileRotation -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Duser.timezone=Asia/Shanghai -Dclient.encoding.override=UTF-8 -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom -Dserver.port=8072 -Dlogging.file=/opt/logs/apollop

**Comment by nobodyiam** [comment]
想起来了，build.sh/bat在打包的时候会把apollo_profile[传进去](https://github.com/ctripcorp/apollo/blob/master/scripts/build.bat#L36)的，会体现在[application.yml文件](https://github.com/ctripcorp/apollo/blob/master/apollo-portal/src/main/resources/application.yml)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
