### ISSUE TITLE
portal密码数据库重置成初始密文密码仍然无法登录

### ISSUE THREAD

**Issue by LzxUser** [ctripcorp/apollo#1977]
在ApolloPortalDB库中修改user表Password值为
$2a$10$7r20uS.BQ9uBpf3Baj3uQOZvMVvB1RN3PYoKE94gtz2.WAOuiiwXS
仍然无法重置登录

**Comment by jengchauwei** [comment]
把数据库密码替换一下，密码admin加密后实际密文是
$2b$12$FhrJImcSlc30OW/cYoKPeuc2ziWIRFcg.wslsJMobZmLU27f2EBr2
