### ISSUE TITLE
openapi权限问题

### ISSUE THREAD

**Issue by chenkunyun** [ctripcorp/apollo#1978]
在”开放平台授权管理"界面，可以对token“赋权”
这里通过debug发现，Apollo在实现的时候并不是按照界面提示的“不选择则所有环境都有权限”。
当不选择的时候，用户使用openapi sdk访问的时候会提示403权限不够。
通过断点调试，发现问题在这里:
ConsumerRolePermissionService.consumerHasPermission方法
实现的时候还是考虑了环境的。

**Comment by chenkunyun** [comment]
@nobodyiam 
宋大，这里是故意这么设计吗？

**Comment by nobodyiam** [comment]
感谢反馈，这是一个bug，参见 PR #1985
