### ISSUE TITLE
namespace长度限制在前端放宽或可配置

### ISSUE THREAD

**Issue by Colstuwjx** [ctripcorp/apollo#1979]
Hi,

portal创建namespace时似乎会[对namespace长度做校验](https://github.com/ctripcorp/apollo/blob/master/apollo-portal/src/main/resources/static/scripts/controller/NamespaceController.js#L120)，这一步之前的出发点是啥？能否放宽这个配置或做成一个系统参数可配置？

谢谢！

**Comment by nobodyiam** [comment]
这个主要是后端数据库的schema做了限制，所以前端也相应做了检查，如果需要放宽或做成配置项的话，需要先调整一下schema

**Comment by Colstuwjx** [comment]
这块是不是不太一致？我看namespace表本身的限制是 [500个字符](https://github.com/ctripcorp/apollo/blob/master/scripts/db/migration/configdb/V1.0.0__initialization.sql#L238)，但是 appnamespace的name又是限制成 [32个字符](https://github.com/ctripcorp/apollo/blob/master/scripts/db/migration/portaldb/V1.0.0__initialization.sql#L48)

**Comment by nobodyiam** [comment]
是的，已appnamespace的为准，因为这个是入口

**Comment by Colstuwjx** [comment]
ok

**Comment by fruitboy0001** [comment]
您好！schema里面修改了，前端需要怎么修改呢？
