### ISSUE TITLE
ApolloConfigChangeListener问题

### ISSUE THREAD

**Issue by DeanJi** [ctripcorp/apollo#1980]
使用ApolloConfigChangeListener监听配置修改，客户端有4个实例，监听到配置修改的时间差异较大，可能是什么问题引起的呢？

**Comment by DeanJi** [comment]
![43135df6-9f96-4c7f-b314-ab2c636341c8](https://user-images.githubusercontent.com/24695243/52999489-ed0bf780-3460-11e9-80f1-33027131f837.jpeg)

**Comment by nobodyiam** [comment]
在客户端上tcpdump看一下long polling的推送情况，可能是网络问题所致

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
