### ISSUE TITLE
ReleaseMessageScanner问题

### ISSUE THREAD

**Issue by DeanJi** [ctripcorp/apollo#1981]
ReleaseMessageScanner.java在apollo-biz中，每隔1秒钟扫描一次数据库，而apollo-adminservice和apollo-configservice又同时引用apollo-biz，所以apollo-adminservice和apollo-configservice启动后都会每隔1秒钟扫描一次数据库做同样的事情，这样是否有必要？可否只留一个就好？

**Comment by nobodyiam** [comment]
apollo-adminservice不会创建这个bean的

**Comment by DeanJi** [comment]
Thank you, closing this issue...
