### ISSUE TITLE
获取配置失败（地址被篡改）

### ISSUE THREAD

**Issue by BMambaYe** [ctripcorp/apollo#1982]
18:26:34,148 <com.ctrip.framework.apollo.internals.DefaultMetaServerProvider>  INFO [main]: Located meta services from apollo.meta configuration: http://118.31.6.121:7080!
18:26:34,158 <com.ctrip.framework.apollo.core.MetaDomainConsts>  INFO [main]: Located meta server address http://118.31.6.121:7080 for env DEV from com.ctrip.framework.apollo.internals.DefaultMetaServerProvider
18:26:54,035 <com.ctrip.framework.apollo.internals.RemoteConfigRepository>  WARN [main]: Load config failed, will retry in 1 SECONDS. appId: wsc-gateway, cluster: default, namespaces: application
18:26:56,037 <com.ctrip.framework.apollo.internals.AbstractConfigRepository>  WARN [main]: Sync config failed, will retry. Repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository, reason: Load Apollo Config failed - appId: wsc-gateway, cluster: default, namespace: application, url: http://192.168.0.10:7080/configs/wsc-gateway/default/application?ip=10.188.190.62 [Cause: Could not complete get operation [Cause: connect timed out]]

日志中明明打出meta server在  http://118.31.6.121:7080  下面又报出http://192.168.0.10:7080/configs/wsc-gateway/default/application从这个地址中获取配置失败？？这个怎么回事 因为192.168.0.10是服务器的本地局域网ip 外部当然访问不了了，为什么会被篡改为局域网ip呢？  我将下面的ip改为118.31.6.121 即可正常访问配置。有大神遇到这个问题，或者能知道原因帮忙解决么？

**Comment by nobodyiam** [comment]
参考一下[1.4、网络策略](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#14%E7%BD%91%E7%BB%9C%E7%AD%96%E7%95%A5)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by 17661977890** [comment]
Long polling failed, will retry in 32 seconds. appId: VSC-AU, cluster: default, namespaces: application+service, long polling url: null, reason: Get config services failed from http://172.31.96.34:9008/services/config?appId=VSC-AU&ip=192.168.2.161 [Cause: Could not complete get operation [Cause: connect timed out]]

**Comment by 17661977890** [comment]
Long polling failed, will retry in 32 seconds. appId: VSC-AU, cluster: default, namespaces: application+service, long polling url: null, reason: Get config services failed from http://172.31.96.34:9008/services/config?appId=VSC-AU&ip=192.168.2.161 [Cause: Could not complete get operation [Cause: connect timed out]] 
我这个是什么问题，我也获取不到配置信息
Sync config failed, will retry. Repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository, reason: Get config services failed from http://172.31.96.34:9008/services/config?appId=VSC-AU&ip=192.168.2.161 [Cause: Could not complete get operation [Cause: connect timed out]]
