### ISSUE TITLE
1.1.2版本 下载下来demo运行，当配置修改时为什么不会取到最新的配置值，而1.3版本客户端没问题

### ISSUE THREAD

**Issue by wangguoliang777** [ctripcorp/apollo#1984]

**Comment by nobodyiam** [comment]
可以看一下日志，估计是meta server没设置？

**Comment by wangguoliang777** [comment]
> 可以看一下日志，估计是meta server没设置？
在app.properties里已添加了apollo.meta。
我现在是在运行springbootdemo，这边只要将1.2.1的客户端包变成1.3.0，同时SpringBootApolloRefreshConfig里将@ApolloConfigChangeListener改成@ApolloConfigChangeListener(value = {ConfigConsts.NAMESPACE_APPLICATION, "TEST1.apollo", "application.yaml"},
          interestedKeyPrefixes = {"redis.cache."})
就能正常收到更新内容的日志。在未修改之前，配置中心更新后，客户端无法收到更新日志。但本地缓存的文件里的内容是已经变了。这情况不知道是因为什么？

**Comment by nobodyiam** [comment]
取决于配置在哪个namespace里面，默认的@ApolloConfigChangeListener只监听application一个namespace

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
