### ISSUE TITLE
点击补缺环境  404 

### ISSUE THREAD

**Issue by zhuer0632** [ctripcorp/apollo#1987]
环境: FAT
Active: true  
四个表已经填充好了数据,  App , AppNamespace ,Cluster , Namespace  

点击补缺环境的时候 , 提示404

**Comment by nobodyiam** [comment]
看一下admin service和Portal的日志，看下是什么东西404了

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
