### ISSUE TITLE
apollo client有获取当前项目所有namespace的接口吗？

### ISSUE THREAD

**Issue by tanxiaosheng** [ctripcorp/apollo#1988]
如题，想要获取当前项目下创建的namespace，因为每个namespace文件的大小有限制，需要创建相同前缀的一系列namespace，还有就是namespace的文件大小限制怎么修改呢？ @nobodyiam

**Comment by nobodyiam** [comment]
namespace大小没有限制的，对每个key的大小是有限制的，可以通过[item.value.length.limit](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#5-itemvaluelengthlimit---%E9%85%8D%E7%BD%AE%E9%A1%B9-value-%E6%9C%80%E5%A4%A7%E9%95%BF%E5%BA%A6%E9%99%90%E5%88%B6)来控制

获取当前项目下的namespace可以通过[open api](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0)

**Comment by tanxiaosheng** [comment]
创建的namespace是yaml格式，超过20000还是会提示超出限制，而不是限制每一个配置项的大小，yaml格式的namespace在1.3.0版本之前应该是没有配置项的概念吧？应该不对yaml等文件限制大小。
获取当前项目的所有namespace，如果使用open api 还需要额外依赖，而且需要配置token，建议在apollo client的ConfigService类中增加获取当前项目下所有namespace的方法。 @nobodyiam

**Comment by nobodyiam** [comment]
yaml格式其实内部也是按照k-v模型存储的，所以可以通过[item.value.length.limit](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#5-itemvaluelengthlimit---%E9%85%8D%E7%BD%AE%E9%A1%B9-value-%E6%9C%80%E5%A4%A7%E9%95%BF%E5%BA%A6%E9%99%90%E5%88%B6)来控制

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
