### ISSUE TITLE
关于应用项目的创建和删除权限管理

### ISSUE THREAD

**Issue by Colstuwjx** [ctripcorp/apollo#1990]
Hi，

我这边使用的版本是apollo v1.3.0，发现普通用户可以创建应用项目和namespace，但是创建出来了之后没有删除功能...  这块有计划做成RBAC的权限认证模式吗？或者至少能做成只有超级管理员才能建和删？

还有一个问题，删除应用的时候，是级联的把所属的appnamespace和cluster都删掉吗？这里前端没找到提示，不太有底...

谢谢！

**Comment by Colstuwjx** [comment]
看了下删除应用的[代码](https://github.com/ctripcorp/apollo/blob/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/AppService.java#L160)，是级联删除的，但是，是不是缺少了删除集群这一步？

**Comment by nobodyiam** [comment]
普通用户删除的是当前集群下的namespace，目前在管理员工具中提供了删除appnamespace的能力（所有环境和集群）

**Comment by Colstuwjx** [comment]
好的，感谢。
