### ISSUE TITLE
配置重复写入configDB的bug

### ISSUE THREAD

**Issue by flysnow911** [ctripcorp/apollo#1991]
portal在多线程新增相同配置的场合，有可能会出现相同配置重复写入configDB的bug。
bug复现步骤：

1. 开发环境，apollo版本1.2.0，1.3.0没有试。
2. 在apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/ItemService.java类的updateConfigItemByText()方法中，updateItems(appId, env, clusterName, namespaceName, changeSets)这行代码之前打断点。这样多线程执行的情况下，不同线程能构造出相同的changeSets。
3. portal开多窗口通过页面上【文本】功能提交相同配置。
4. 释放断点，多线程相继执行updateItems(appId, env, clusterName, namespaceName, changeSets)方法，由于不同线程提交的数据都一样，且下层服务也没有幂等 防重校验，导致DB中出现相同配置。

**Comment by xiaoxing598** [comment]
我觉得这个有配置变更记录就行

**Comment by flysnow911** [comment]
> 这个有配置变更记录就行

portal的页面上会出现重复Key，影响后续使用。我司版本已修复bug。

**Comment by nobodyiam** [comment]
下层是有防重校验的，不过由于没有引入分布式锁且数据库也无法加唯一索引（需要支持软删），所以在你说的情况下确实会出现重复。

想请教一下，你们是如何修复这个bug的？

**Comment by flysnow911** [comment]
> 下层是有防重校验的，不过由于没有引入分布式锁且数据库也无法加唯一索引（需要支持软删），所以在你说的情况下确实会出现重复。
>>  嗯 对，下层确实有锁。

> 想请教一下，你们是如何修复这个bug的？
>> biz模块的ItemSetService.java的updateSet方法中，对changeSet中的createItems和updateItems做相同的写库逻辑：key存在的话，就update，否则add。 配合Controller中的@preAcquireNamespaceLock就能解决这个问题。期待更优雅的解决方法。

**Comment by richardwei2008** [comment]
> > 下层是有防重校验的，不过由于没有引入分布式锁且数据库也无法加唯一索引（需要支持软删），所以在你说的情况下确实会出现重复。
> > > 嗯 对，下层确实有锁。
> 
> > 想请教一下，你们是如何修复这个bug的？
> > > biz模块的ItemSetService.java的updateSet方法中，对changeSet中的createItems和updateItems做相同的写库逻辑：key存在的话，就update，否则add。 配合Controller中的@preAcquireNamespaceLock就能解决这个问题。期待更优雅的解决方法。

@flysnow911 这样也没法保证不重复吧？
@nobodyiam 用 deleted_at 时间戳表示组合唯一索引？0表示可用

**Comment by nobodyiam** [comment]
唯一索引带上时间戳貌似也无法确保的

**Comment by flysnow911** [comment]
> > > 下层是有防重校验的，不过由于没有引入分布式锁且数据库也无法加唯一索引（需要支持软删），所以在你说的情况下确实会出现重复。
> > > > 嗯 对，下层确实有锁。
> > 
> > 
> > > 想请教一下，你们是如何修复这个bug的？
> > > > biz模块的ItemSetService.java的updateSet方法中，对changeSet中的createItems和updateItems做相同的写库逻辑：key存在的话，就update，否则add。 配合Controller中的@preAcquireNamespaceLock就能解决这个问题。期待更优雅的解决方法。
> 
> @flysnow911 这样也没法保证不重复吧？
这样做，生产上暂时还没出现过key重复的问题。

**Comment by flysnow911** [comment]
> > > 下层是有防重校验的，不过由于没有引入分布式锁且数据库也无法加唯一索引（需要支持软删），所以在你说的情况下确实会出现重复。
> > > > 嗯 对，下层确实有锁。
> > 
> > 
> > > 想请教一下，你们是如何修复这个bug的？
> > > > biz模块的ItemSetService.java的updateSet方法中，对changeSet中的createItems和updateItems做相同的写库逻辑：key存在的话，就update，否则add。 配合Controller中的@preAcquireNamespaceLock就能解决这个问题。期待更优雅的解决方法。
> 
> @flysnow911 这样也没法保证不重复吧？
> @nobodyiam 用 deleted_at 时间戳表示组合唯一索引？0表示可用

ooKeeper JMX enabled by default
Using config: /opt/zookeeper/bin/../conf/zoo.cfg
Mode: follower

> > > 下层是有防重校验的，不过由于没有引入分布式锁且数据库也无法加唯一索引（需要支持软删），所以在你说的情况下确实会出现重复。
> > > > 嗯 对，下层确实有锁。
> > 
> > 
> > > 想请教一下，你们是如何修复这个bug的？
> > > > biz模块的ItemSetService.java的updateSet方法中，对changeSet中的createItems和updateItems做相同的写库逻辑：key存在的话，就update，否则add。 配合Controller中的@preAcquireNamespaceLock就能解决这个问题。期待更优雅的解决方法。
> 
> @flysnow911 这样也没法保证不重复吧？
这样做，我司生产环境暂时没出现过key重复问题。

**Comment by flysnow911** [comment]
> > > 下层是有防重校验的，不过由于没有引入分布式锁且数据库也无法加唯一索引（需要支持软删），所以在你说的情况下确实会出现重复。
> > > > 嗯 对，下层确实有锁。
> > 
> > 
> > > 想请教一下，你们是如何修复这个bug的？
> > > > biz模块的ItemSetService.java的updateSet方法中，对changeSet中的createItems和updateItems做相同的写库逻辑：key存在的话，就update，否则add。 配合Controller中的@preAcquireNamespaceLock就能解决这个问题。期待更优雅的解决方法。
> 
> @flysnow911 这样也没法保证不重复吧？
这样做，我司生产再没出现过key重复的问题。

**Comment by flysnow911** [comment]
> >下层是有防重校验的，不过由于没有引入分布式锁且数据库也无法加唯一索引（需要支持软删），所以在你说的情况下确实会出现重复。

 >嗯 对，下层确实有锁。

>>想请教一下，你们是如何修复这个bug的？

 >biz模块的ItemSetService.java的updateSet方法中，对changeSet中的createItems和updateItems做相同的写库逻辑：key存在的话，就update，否则add。 配合Controller中的@preAcquireNamespaceLock就能解决这个问题。期待更优雅的解决方法。

> @flysnow911 这样也没法保证不重复吧？

  @richardwei2008 这样做，我司生产环境再没出现过key重复的问题。
