### ISSUE TITLE
请问Http接口现在暂时没有“环境”这个参数？

### ISSUE THREAD

**Issue by Doubleuncle** [ctripcorp/apollo#1994]
那是不是意味着，如果我想分生产和测试两个环境，就需要我自己搭两套节点，通过url来区分？

**Comment by xiaoxing598** [comment]
你要仔细看一下文档就明白了，重点看环境那部分。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
