### ISSUE TITLE
protal用户信息更新失败

### ISSUE THREAD

**Issue by rhaonan** [ctripcorp/apollo#1997]
处于安全性考虑，数据库设置了SQL_SAFE_UPDATES=1，即更新操作的where语句需要包含主键。

但是protal源码里更新用户表的sql语句是用的是username，而非主键Id
        update users set password = ?, enabled = ? where username = ?

这里改一下是否会好些？

**Comment by nobodyiam** [comment]
可以考虑提交一个PR支持一下

**Comment by nobodyiam** [comment]
感谢PR，[1.4.0](https://github.com/ctripcorp/apollo/releases/tag/v1.4.0)版本已经发布。
