### ISSUE TITLE
关于部分配置的归属问题

### ISSUE THREAD

**Issue by bpw123** [ctripcorp/apollo#1998]
如果有一些配置被封装在一些基础包中访问，理论上不归属于任何一个应用，那么请问该怎么确定这些配置的nameSpace

**Comment by kezhenxu94** [comment]
> 如果有一些配置被封装在一些基础包中访问，理论上不归属于任何一个应用，那么请问该怎么确定这些配置的nameSpace

@bpw123 能否使用 public 的 namespace? 参见 [Apollo核心概念之“Namespace”
](https://github.com/ctripcorp/apollo/wiki/Apollo%E6%A0%B8%E5%BF%83%E6%A6%82%E5%BF%B5%E4%B9%8B%E2%80%9CNamespace%E2%80%9D)

**Comment by bpw123** [comment]
我的理解是这样，namespace不论是public和private的在管理的维度都是归属于项目的（如果理解的不对还请指正），那么我之前说的这些配置，可能在创建时很难去界定属于哪个项目，不知道你们这边是怎么解决这类问题的

**Comment by kezhenxu94** [comment]
> 如果有一些配置被封装在一些基础包中访问，理论上不归属于任何一个应用，那么请问该怎么确定这些配置的nameSpace

比如我们这边的类似使用 dubbo 的基础包的配置, 会使用类似于 company-dubbo 的 namespace 来管理 dubbo 相关的配置, 也就是说给你说的这些配置进行归类(到一个项目中), 仅供参考

**Comment by nobodyiam** [comment]
一般是给公共组件创建一个项目，然后在里面创建public namespace，在sdk中获取public namespace即可，不要在sdk中指定app.id

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
