### ISSUE TITLE
演示demo账号密码登陆不了，能否设置一个每天重置账户密码为apollo/admin的任务

### ISSUE THREAD

**Issue by ydc201211** [ctripcorp/apollo#1999]

**Comment by nobodyiam** [comment]
好主意，后续我弄一下

**Comment by hovangv5** [comment]
请问演示demo的账号密码重置了吗，貌似密码被改了？

**Comment by ydc201211** [comment]
> 请问演示demo的账号密码重置了吗，貌似密码被改了？

只能联系项目相关人员设置密码

**Comment by nobodyiam** [comment]
我试了一下账号密码是对的

**Comment by hovangv5** [comment]
@nobodyiam 现在可以登录了，2天前确实是无法登录。为了排除我敲错的可能，我直接复制了README里面的账号密码试过了，登录时提示密码错误。

@ydc201211 好的，感谢建议

**Comment by nobodyiam** [comment]
演示环境已经加上了每分钟重置apollo密码任务
