### ISSUE TITLE
uat环境，不想使用apollo配置，有没有开关

### ISSUE THREAD

**Issue by roneywei** [ctripcorp/apollo#2000]
在uat环境，我不想使用配置中心，我想直接使用项目的配置文件，请问有没有开关？

![image](https://user-images.githubusercontent.com/5858867/53223756-5d0ebd80-36ad-11e9-8581-83e5d0249ae4.png)

**Comment by nobodyiam** [comment]
改为false就生效的，除非是项目中使用到了apollo的注解，比如`EnableApolloConfig`，`ApolloConfigChangeListener`

**Comment by nobodyiam** [comment]
还有一种方式是设置env=Local

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by roneywei** [comment]
ok，已经解决，谢谢
