### ISSUE TITLE
能否提供一份操作手册？

### ISSUE THREAD

**Issue by roneywei** [ctripcorp/apollo#2001]
能否提供一份配置中心的操作手册

![image](https://user-images.githubusercontent.com/5858867/53225098-d9a39b00-36b1-11e9-90ad-6d3ebfc815c5.png)

**Comment by nobodyiam** [comment]
[Apollo使用指南](https://github.com/ctripcorp/apollo/wiki/Apollo%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)

**Comment by roneywei** [comment]
好的，多谢

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
