### ISSUE TITLE
ldap登录之后不是管理员权限

### ISSUE THREAD

**Issue by huzhou520** [ctripcorp/apollo#2005]
apollo对接ldap之后，默认的项目管理员账户（apollo）就登录不了了。用ldap账户登录又管理不了项目，这个问题请问怎么办

**Comment by nobodyiam** [comment]
修改super admin的配置

https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#3superadmin---portal%E8%B6%85%E7%BA%A7%E7%AE%A1%E7%90%86%E5%91%98

**Comment by huzhou520** [comment]
多谢 问题已解决
