### ISSUE TITLE
client 没有做权限验证，是否任何一个client 都能拉取其他appID的配置

### ISSUE THREAD

**Issue by LHRchina** [ctripcorp/apollo#2006]
FYI, 如果client端配置的app.properties中配的是其他appID ,那就能拉取其他app的配置了？这块儿没有做相应的权限控制吗

**Comment by nobodyiam** [comment]
apollo设计是考虑内网运行的，所以目前没有client的权限验证

不过这块确实是可以补充的

**Comment by LHRchina** [comment]
> apollo设计是考虑内网运行的，所以目前没有client的权限验证
> 
> 不过这块确实是可以补充的

OK,理解了。
