### ISSUE TITLE
关于配置批量修改的需求

### ISSUE THREAD

**Issue by thinkerFenglm** [ctripcorp/apollo#2007]
如果一次性需要修改十几个配置的时候，一个一个修改很耗时间，通过文本编辑这种方式修改的话，又有可能造成一些误操作

**Comment by kezhenxu94** [comment]
文本方式修改完, 可以切换回表格模式确认变更, 确认没错之后再选择发布

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
