### ISSUE TITLE
超级用户设置

### ISSUE THREAD

**Issue by hardyxia2018** [ctripcorp/apollo#2009]
对于新增用户，需要对每个项目对该用户授权，能否在添加用户的时候直接设置为超级用户，等同于apollo用户一样，或者修改数据库某个字段以实现？

**Comment by nobodyiam** [comment]
详见[superAdmin - Portal超级管理员](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#3superadmin---portal%E8%B6%85%E7%BA%A7%E7%AE%A1%E7%90%86%E5%91%98)，不过不建议对每个新增用户都授予超级用户权限

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
