### ISSUE TITLE
代码版本与apollo存储的配置版本关联

### ISSUE THREAD

**Issue by mdyzsz91** [ctripcorp/apollo#2013]
git上的代码版本与apollo上项目配置的版本关联。方便服务回顾的时候，能拉取正确的配置。有好的方案吗

**Comment by nobodyiam** [comment]
see #1399 

代码和配置绑定会增加用户理解成本，而且一般而言还是建议配置要兼容新旧代码版本，因为改配置能做成原子的，但是发布应用做不到原子的，中间一定会有一个中间状态的，所以配置应该是要能兼容新老应用的
