### ISSUE TITLE
同一个Spring Boot项目可以用两个appId下面的配置吗

### ISSUE THREAD

**Issue by 188** [ctripcorp/apollo#2019]
比如：有两个appId对应两个Apollo，本来是对两个项目的，但是现在有需求A项目也可以读取B项目中的Apollo配置，这怎么实现呀？

**Comment by nobodyiam** [comment]
多应用间共享配置可以通过public namespace

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
