### ISSUE TITLE
为项目添加私有namespace后所有环境配置点击都报错

### ISSUE THREAD

**Issue by fantasylw** [ctripcorp/apollo#2020]
![image](https://user-images.githubusercontent.com/46509421/53721518-5e569c00-3e9e-11e9-94af-05c85a297c62.png)

步骤：
1. 打开需要管理的项目
2. 点击添加集群
3. 输入集群名字，选择UAT环境。提交
4. 提示成功后，继续点击 添加namespace
5. 点击切换创建namespace
6. 输入baseConfig，选择private
7. 提交。
8. 随后点击返回项目

结果：
如图，报错。无论点击哪个环境都是如此。

接口：
url:/apps/bm-unbusiness-admin/envs/PRO/clusters/default/namespaces
返回：
{"exception":"org.springframework.dao.IncorrectResultSizeDataAccessException","message":"result returns more than one elements; nested exception is javax.persistence.NonUniqueResultException: result returns more than one elements","status":500,"timestamp":"2019-03-05T16:54:32.708"}

注：
点击别的项目不报错。只是这个项目报错了！

**Comment by nobodyiam** [comment]
看一下admin service的日志

**Comment by fantasylw** [comment]
找别的开发删除了新增的namespace后解决了。
