### ISSUE TITLE
在k8s里启动服务的时候报错 Text file busy

### ISSUE THREAD

**Issue by huzhou520** [ctripcorp/apollo#2021]
三个服务启动都报了相同的错误，尝试修改!后面加一个空格 #! /bin/bash  还是不行。

执行这个命令启动 
kubectl apply -f service-apollo-config-server-prod.yaml

错误信息：
/apollo-config-server/scripts/startup-kubernetes.sh: ./apollo-configservice.jar: /bin/bash: bad interpreter: Text file busy

**Comment by nobodyiam** [comment]
参考一下 #1450 ？

**Comment by huzhou520** [comment]
ok 多谢

**Comment by Anilople** [comment]
Duplicate of #1450
