### ISSUE TITLE
关于单机项目部署的用户体验

### ISSUE THREAD

**Issue by g5niusx** [ctripcorp/apollo#2022]
在部署单机的阿波罗的时候，因为 [apollo-env.properties](https://github.com/ctripcorp/apollo/blob/master/apollo-portal/src/main/resources/apollo-env.properties) 里面包含有各个环境的meta的配置，而数据库的初始化脚本里面没有增加对应的环境配置，在第一次部署启动完成以后，创建项目会报错。是否可以将pollo-env.properties里面的其他环境的配置注释或者将数据库的初始化[环境脚本](https://github.com/ctripcorp/apollo/blob/master/scripts/db/migration/portaldb/V1.0.0__initialization.sql)补全,这样第一次部署的时候就没有报错了。

**Comment by nobodyiam** [comment]
apollo-env.properties里面的只是配置数据，实际环境列表是读取serverconfig中的apollo.portal.envs信息的，所以第一次部署也最多是默认的dev环境报错，对其它环境不会出现问题吧？

**Comment by g5niusx** [comment]
> apollo-env.properties里面的只是配置数据，实际环境列表是读取serverconfig中的apollo.portal.envs信息的，所以第一次部署也最多是默认的dev环境报错，对其它环境不会出现问题吧？

我刚才排查了一下，是因为 apollo-env.properties 里面的 local.meta 配置了 实际的地址，但是导入的脚本里面是 dev 环境，两者不一致，所以第一次部署项目进去 simpleapp 会报错。后续要不要把导入环境修改成 local 呢。。这样第一次部署项目完毕进入 simpleapp 就不会报错了

**Comment by nobodyiam** [comment]
默认应该是dev的，local是本地开发环境的意思，不会在portal界面上显示

**Comment by g5niusx** [comment]
ok。明白了。感谢宋大～😄
