### ISSUE TITLE
apollo 服务改为一个进程

### ISSUE THREAD

**Issue by chengbinghan** [ctripcorp/apollo#2023]
hello

      apollo 是一个优秀的产品，给我们公司和业务开发带来了极大的方便，在此感谢携程的开发团队。
 
       最近使用有两个问题，有点疑问希望可以解答一下。
      1、 apollo（1.3版本） 启动时三个进程，portal、adminservice、configservice。最近根据实际业务场景需求（客户要求），需要给三个进程改为一个进程部署运行，我们的方案是简单修改源码，将adminservice，configservie作为一个jar包依赖，在portal 启动的时候顺便启动二者，不过都是在portal 所在的 jvm 虚拟机进程中运行。这样apollo 部署运行就是一个进程了，不知道思路是否可行？
 
      2、我们目前apollo(portal, configservice ,adminservice )版本是0.10.2.如果升级到最新的1.3版本（portal,configservice,adminservice均升级），看到issus 有人讨论相关问题，但是还是有些疑问，比如
     a,数据库表要升级吗？
     b,接口，或我们的代码调用apoll 的地方是否要做相应的修改？
     c,有没有升级相关文档？
      

      十分感谢谢！！！！

**Comment by nobodyiam** [comment]
1. 三个进程有各自的角色，admin service和config service可以合在一起，不过portal没必要吧，而且要支持多环境的话，portal肯定是独立的

2. 升级信息可以参考[release notes](https://github.com/ctripcorp/apollo/releases)

**Comment by chengbinghan** [comment]
好的，谢谢。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
