### ISSUE TITLE
是否可以启动时打印从apollo拿到的所有配置信息

### ISSUE THREAD

**Issue by litttlefisher** [ctripcorp/apollo#2024]
如题，由于环境配置、namespace等等内容，分布在不同的地方，启动时经常无法确定是否拿到正确的配置，所以希望能够在启动时打印配置信息

**Comment by kezhenxu94** [comment]
不建议做这个功能，考虑到Apollo可能被用来配置敏感信息（如数据库密码等），如果打印在日志中可能会导致泄露，如果有需要的话其实也可以自己在程序中打印的。

![image](https://user-images.githubusercontent.com/15965696/53806806-f03ad380-3f88-11e9-8955-b27f14cf3e77.png)

**Comment by nobodyiam** [comment]
如果是spring boot应用的话，可以开启[actuator](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html)查看配置的信息

**Comment by litttlefisher** [comment]
@nobodyiam actuator这个需要个性化开发一个endpoint的吧？原生就已经支持打印配置吗？

**Comment by nobodyiam** [comment]
内置的`env` endpoint应该就可以
