### ISSUE TITLE
value配置的大小有没有限制

### ISSUE THREAD

**Issue by jintonghuoya** [ctripcorp/apollo#2025]
对于value的配置有没有大小的限制，或者到了多大，就会变慢，毕竟加上网络传输以及本地写文件以及内存都需要时间？？？

**Comment by nobodyiam** [comment]
默认20000，可以调整的，参考[item.value.length.limit - 配置项 value 最大长度限制)(https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#5-itemvaluelengthlimit---%E9%85%8D%E7%BD%AE%E9%A1%B9-value-%E6%9C%80%E5%A4%A7%E9%95%BF%E5%BA%A6%E9%99%90%E5%88%B6)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
