### ISSUE TITLE
k8s 启动，卡在Pending

### ISSUE THREAD

**Issue by veryrich** [ctripcorp/apollo#2026]
按照[官方给的方法](https://github.com/ctripcorp/apollo/tree/master/scripts/apollo-on-kubernetes)，启动pod后，全部都是pending状态
![image](https://user-images.githubusercontent.com/12951051/53859734-93d3c480-4019-11e9-9fc5-1f677f481faf.png)

describe 显示：
![image](https://user-images.githubusercontent.com/12951051/53859827-ed3bf380-4019-11e9-8c48-da1ca2aa0ab8.png)

**Comment by Callistol** [comment]
确定你的nodes里面有这个标签
![image](https://user-images.githubusercontent.com/17273914/55303344-2e3bf200-5478-11e9-96c9-f16847e2b92b.png)
