### ISSUE TITLE
将Config Service和Admin Service注册到我们自己维护的Eureka上，但我们自己的eureka用到了分区的，此时该如何配置ApolloConfigDB中的eureka.service.url

### ISSUE THREAD

**Issue by HandsomSheng** [ctripcorp/apollo#2027]
如题，我们将com.ctrip.framework.apollo.configservice.ConfigServiceApplication中的@EnableEurekaServer改为@EnableEurekaClient，想用自己的eureka，但是我们自己的eureka用到了Region和Zone，请问ApolloConfigDB.ServerConfig表中的eureka.service.url该如何配置

**Comment by nobodyiam** [comment]
这种情况建议就留空，然后通过-D参数按照正常的eureka配置来配，参见[ApolloEurekaClientConfig](https://github.com/ctripcorp/apollo/blob/master/apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/eureka/ApolloEurekaClientConfig.java)的逻辑

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
