### ISSUE TITLE
docker 部署完成configserver报错

### ISSUE THREAD

**Issue by jsonchina** [ctripcorp/apollo#2029]
apollo-fat-65877796b4-qrhd5:apollo-configservice:8080 - was unable to send heartbeat

**Comment by nobodyiam** [comment]
是持续打这个日志吗？如果是的话，检查一下和配置的eureka.service.url是否网络是通的

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
