### ISSUE TITLE
关于mete server的疑问

### ISSUE THREAD

**Issue by ruanxingshi** [ctripcorp/apollo#2031]
看设计的架构图meta server是起到一个门面的作用，所有访问通过meta server来获取具体的服务实例，可以我看具体实现的代码并不是这样的，ConfigServiceLocator、AdminServiceAddressLocator都是分别请求的ServiceController的/services/config和/services/admin来获取的具体的服务实例的，并没有求/service/meta
想问下：这个meta server有没有起到具体的实际作用

**Comment by nobodyiam** [comment]
meta server地址是配置在client和portal侧的，访问的services/config和/services/admin就是从meta server获取服务列表。

/services/meta确实没有用到
