### ISSUE TITLE
quick start里面提供的demo.sh,对于jdk环境判断的脚本有问题

### ISSUE THREAD

**Issue by haimycc** [ctripcorp/apollo#2033]
demo.sh中68行
if [[ "$_java" ]]; then
      version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
      if [[ "$version" < "1.8" ]]; then
          echo "Java version is $version, please make sure java 1.8+ is in the path"
          exit 1
      fi
  fi

在jdk11的情况下 "11.0.2" < "1.8" 在demo.sh中的结果为true 导致脚本中断
应该修改为
`echo "$version < 1.8" | bc`

**Comment by nobodyiam** [comment]
能否提个PR？

**Comment by xiaomujiadong** [comment]
![QQ截图20190323115834](https://user-images.githubusercontent.com/9440884/54861381-04414c00-4d63-11e9-9365-eb3fdc6711cd.png)

这是报错的信息，但是把demo下的72行的exit 1注释掉，可以启动。

**Comment by sanwancoder** [comment]
我也遇到同样的问题

修改sh文件即可 

![捕获_meitu_1](https://user-images.githubusercontent.com/10041958/58459347-c34c2600-815d-11e9-8665-3c9b1cb0f92b.jpg)
