### ISSUE TITLE
首次配置变更下发有延迟

### ISSUE THREAD

**Issue by monkeyming** [ctripcorp/apollo#2034]
在apollo修改配置后，在应用刚启动的时候，新配置推送到应用大概需要20-30秒，好像那块阻塞了；第一次新配置到达后，再修改，基本上可以实时到达了；监听器注入方式，是通过config.addListener(lisenter,keys)方式添加的

**Comment by nobodyiam** [comment]
long polling是定时发车机制，启动时会等两秒再发车，两秒内发现的namespace会赶上，如果启动比较慢，2秒后获取的namespace就要等下一班车做监听

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
