### ISSUE TITLE
是否可以支持多租户呢？

### ISSUE THREAD

**Issue by littlefisher666** [ctripcorp/apollo#2038]
如题，希望Apollo能够支持多租户，或者说是否基于现在的Apollo情况下，怎么能够做到多租户的支持

**Comment by nobodyiam** [comment]
目前还不支持

**Comment by litttlefisher** [comment]
是否有打算支持呢？

**Comment by nobodyiam** [comment]
后续会做考虑

**Comment by litttlefisher** [comment]
携程内部是否有相关的设计，我考虑能否自己开发下

**Comment by nobodyiam** [comment]
内部目前还没有多租户的场景，一般在云上产品形态可能会考虑租户

**Comment by litttlefisher** [comment]
那我这边自行设计多租户的实现方式了

暂时考虑是新增一张租户表，跟命名空间表是一对多的关系，这样进行存储。原命名空间下的配置信息，理解为默认配置，不同租户上，如果有key相同的配置，则用租户上的参数覆盖默认配置。

使用时，暂时仅考虑`@ConfigurationProperties`和`@Value`的解决方案，应用启动是，自动注入的是默认参数，代码执行到相应代码的时候，根据线程上下文中配置的租户号进行匹配。

这样设计不知道合理否

**Comment by nobodyiam** [comment]
租户我理解应该是一个完全隔离的概念，所以可能需要在所有的实体上都增加租户这个信息

**Comment by litttlefisher** [comment]
对于“支持多租户”可能理解不同。我所理解并需要使用的是应用程序是多租户环境，需要让apollo支持应用程序针对于不同的租户做不同的配置。而您所说的“多租户”，是指让apollo支持多租户。我这边暂时没有遇到需要apollo支持多租户的情况，不知道是否要做到这一步

另外，我加您微信了，还希望能详聊，在issue中效率有点低

**Comment by Jlber** [comment]
> 携程内部是否有相关的设计，我考虑能否自己开发下



> 对于“支持多租户”可能理解不同。我所理解并需要使用的是应用程序是多租户环境，需要让apollo支持应用程序针对于不同的租户做不同的配置。而您所说的“多租户”，是指让apollo支持多租户。我这边暂时没有遇到需要apollo支持多租户的情况，不知道是否要做到这一步
> 
> 另外，我加您微信了，还希望能详聊，在issue中效率有点低

请问您现在多租户功能改造得咋样啦  我这也有这需求

**Comment by littlefisher666** [comment]
@Jlber sorry, 已经从当时需求的公司离职了，所以我这边并没有跟进开发了的

**Comment by diwenzheng** [comment]
我也有这样的需求 麻烦问下多租户的 还在开发吗

**Comment by diwenzheng** [comment]
@nobodyiam
