### ISSUE TITLE
Apollo使用MySQL时用关键字作为表名报错

### ISSUE THREAD

**Issue by finefuture** [ctripcorp/apollo#2039]
MySQL有个保留关键字RELEASE (R)，Apollo建表时也有release这张表，导致查询错误。
报错的JPA Repository：com.ctrip.framework.apollo.biz.repository.ReleaseRepository
报错方法：findFirstByAppIdAndClusterNameAndNamespaceNameAndIsAbandonedFalseOrderByIdDesc()
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Release release0_ where ( release0_.isDeleted = 0) and release0_.AppId='10000021' at line 1

希望能尽量在建表时避免使用MySQL关键字

**Comment by nobodyiam** [comment]
apollo有配置的，你改了代码导致配置没生效？

https://github.com/ctripcorp/apollo/blob/master/apollo-common/src/main/resources/application.properties#L8

**Comment by finefuture** [comment]
我是下载的release包在windows下启动，自己也加了hibernate的那个配置，后来才没exception，只是觉得应该尽量避免这样建表

**Comment by nobodyiam** [comment]
是的
