### ISSUE TITLE
文本格式和表格格式展示不一致

### ISSUE THREAD

**Issue by DeanJi** [ctripcorp/apollo#2041]
文本格式是按照行号从小到大展示配置项，但是表格格式由于放在map，展示是无序的，是否考虑优化，使两种格式的展示一致？

**Comment by nobodyiam** [comment]
能举个展示不一致的例子吗？

**Comment by DeanJi** [comment]
抱歉，说错了。是本地缓存文件的配置是无序的。

**Comment by DeanJi** [comment]
有一些传统应用(非微服务应用，团队思想保守)接入apollo后担心apollo服务端不稳定，所以他们很关注缓存文件的正确性，就会去对比缓存文件的内容是不是跟服务端的配置是一致的，由于无序很难比较。
