### ISSUE TITLE
mac 环境 本地搭建测试,一直未找到配置中心

### ISSUE THREAD

**Issue by gaodxsuper** [ctripcorp/apollo#2042]
Long polling failed, will retry in 32 seconds. appId: demo, cluster: default, namespaces: application, long polling url: null, reason: Get config services failed from http://apollo.meta/services/config?appId=demo&ip=10.20.1.118 [Cause: Could not complete get operation [Cause: apollo.meta]]

代码配置;数据库配置都是8080.这是因为ip 不是localhost 所以导致的么?

**Comment by nobodyiam** [comment]
apollo.meta地址没配导致的，参考一下java客户端使用文档中的相关内容吧

**Comment by g5niusx** [comment]
可以参考一下 [apollo客户端](https://www.g5niusx.com/2019/03/apollo-2.html) 里面的配置 😄

**Comment by gaodxsuper** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    已经解决了,谢谢!!
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                gdxsuper
                            
                    
                        
                            
                                    gdxsuper@sina.cn
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2019年03月13日 16:02，_g5niusx<notifications@github.com> 写道： 


可以参考一下 apollo客户端 里面的配置 😄



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
