### ISSUE TITLE
apollo是否和我们具体项目中的ribbon冲突

### ISSUE THREAD

**Issue by ZEROyongyong** [ctripcorp/apollo#2044]
我现在的项目是springcloud然后采用的是eureka注册中心，现在本地不使用注册中心eureka, 然后在apollo的配置中心上添加配置如下
ribbon.eureka.enabled = false
ucenter.ribbon.listOfServers = localhost:8010
结果ribbon的配置没有生效；
然后就不用apollo配置中心了，直接在项目下建application.properties文件并且把上面配置放入application.properties中结果ribbon的配置生效了；

**Comment by nobodyiam** [comment]
尝试一下spring boot方式接入吧，那个加载配置阶段会更早一些
