### ISSUE TITLE
如何获取token

### ISSUE THREAD

**Issue by bad2cat** [ctripcorp/apollo#2046]
@nobodyiam 你好，我想在程序中调用apollo portal中的一个接口，想问一下怎么能获取到token

**Comment by g5niusx** [comment]
token好像在数据库里面存着。可以直接获取。

**Comment by nobodyiam** [comment]
portal的接口需要通过用户登录，一般是通过cookie

open api的接口不需要用户登录，可以通过开放平台获取token

**Comment by bad2cat** [comment]
我是想通过api获取到配置的发布历史，看了之前的问题，这个好像没有open api,是不是只能去数据库获取发布的历史信息了？？
![image](https://user-images.githubusercontent.com/18734778/54424156-43f9a980-474d-11e9-9969-500e6ae39d8d.png)

**Comment by nobodyiam** [comment]
如果是内部系统的话，可以直接调用admin service的接口，或者可以在open api中增加一个controller
