### ISSUE TITLE
key 值包含斜杆"/"的时候，开放平台 使用 key值@PathVariable 存在编码问题

### ISSUE THREAD

**Issue by xiangxiuhui** [ctripcorp/apollo#2050]

**Comment by nobodyiam** [comment]
key不建议包含`/`，不过可以尝试一下让tomcat允许

https://tomcat.apache.org/tomcat-8.5-doc/config/systemprops.html#Security

![image](https://user-images.githubusercontent.com/837658/54374140-7bb71180-46b9-11e9-8cd6-41e1c032b3dc.png)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
