### ISSUE TITLE
生产实践中，遇到如下问题：公共配置中引用子项目配置，需重启方才生效

### ISSUE THREAD

**Issue by ooooor** [ctripcorp/apollo#2052]
公共配置中：login.success.url = ${web.endpoint}
项目中：web.endpoint=aaa.com
项目中使用: @(${login.success.url})，获取配置信息

更改web.endpoint的配置，成功发布，需重启应用才能生效．

**Comment by nobodyiam** [comment]
是的，上述的两层级联case目前是不支持自动更新的，属于设计之中的行为，有[UT](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/test/java/com/ctrip/framework/apollo/spring/JavaConfigPlaceholderAutoUpdateTest.java#L702)对应的。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
