### ISSUE TITLE
当项目存在yml文件和properties文件时怎么配置

### ISSUE THREAD

**Issue by HelloTwar** [ctripcorp/apollo#2053]
我们项目目录结构如下：

resources:
  config(文件夹)
      env.properties
      test.properties
      uat.properties
  application.yml

现在是application.yml里面配置了一些项目的基本信息，例如项目的端口号之类的基础信息不变的。
config目录下面配置的是例如像数据库链接之类的跟环境有关的配置。
如果我们现在接入Apollo怎么做？

**Comment by nobodyiam** [comment]
不变的信息可以留着不动，把和环境相关或者会变的配置放到apollo管理即可，具体可以看下java客户端使用文档

**Comment by HelloTwar** [comment]
> 不变的信息可以留着不动，把和环境相关或者会变的配置放到apollo管理即可，具体可以看下java客户端使用文档

好的，谢谢。解决了

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
