### ISSUE TITLE
多数据源的动态切换

### ISSUE THREAD

**Issue by alxjerr** [ctripcorp/apollo#2054]
目前demo是单数据源的动态切换，如果系统中用的是多数据源，怎么动态切换呢。

**Comment by nobodyiam** [comment]
这个没啥区别吧，无非就是需要把数据源的配置和数据源关联起来

**Comment by g5niusx** [comment]
我刚才测试了一下我写这个[apollo 动态切换数据源](https://github.com/g5niusx/apollo-demo/blob/master/apollo-spring-boot/src/main/java/com/apollo/demo/spring/boot/ApolloSpringBootApplication.java)，你可以参考一下 @alxjerr

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
