### ISSUE TITLE
语法检查

### ISSUE THREAD

**Issue by chengbinghan** [ctripcorp/apollo#2055]
您好
      我们在开发，生产环境中使用apollo,发现各部分功能都很好用，但是，其中的语法检查，比如我们的xml ，yaml 等明显语法有问题，但是配置还是通过了。 是个很大的痛点。虽然看官网说1.3版本已经有相关功能了，不过语法检查不是很强，几乎为0。不知下个版本是否有增强计划？

谢谢

**Comment by nobodyiam** [comment]
yaml的检查是比较完善的吧（参见下面的截图），xml和json目前只有语法高亮，没有做检查

![image](https://user-images.githubusercontent.com/837658/54476102-3e2ac380-4834-11e9-9a1d-9765d85f5931.png)

**Comment by chengbinghan** [comment]
如下图：输入一堆任意的东西，点击语法检查，还是会报，语法正确，并且入库了。
![image](https://user-images.githubusercontent.com/37525039/54487940-c096a000-4893-11e9-9fe8-4fd34092e252.png)

如数据库：
![image](https://user-images.githubusercontent.com/37525039/54488003-936be100-48d7-11e9-8b5b-586fb820c85e.png)

**Comment by chengbinghan** [comment]
语法检验是通过高亮查看吗？

**Comment by nobodyiam** [comment]
我在demo环境试了一下，会检测出错误的，http://106.12.25.204:8070/config.html?#/appid=524

![image](https://user-images.githubusercontent.com/837658/54491892-ef952c00-48fc-11e9-8364-ff34eb4e5e6f.png)

**Comment by chengbinghan** [comment]
谢谢答复，我验证了一下，是我环境的问题，不好意思。十分感谢

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
