### ISSUE TITLE
将配置放到Apollo之后，使用@value获取配置失败

### ISSUE THREAD

**Issue by DorraChen** [ctripcorp/apollo#2057]
将配置放到Apollo之后，使用@value获取配置时获取不到，获取方式：
`
@Value("${Globalparam.SysAuthDevInterceptor}")
private boolean startauth;`
报错：
`nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'Globalparam.SysAuthDevInterceptor' in value "${Globalparam.SysAuthDevInterceptor}" ` 
但是我用@ConfigurationProperties的方式去获取基本的配置（比如那些关于数据库的配置）时是可以获取到值的，
请问一下为什么@Value的方式获取不到呢？如果我就想用@Value去获取该怎么办？

**Comment by g5niusx** [comment]
如果是spring boot的项目，可以参考一下这个[demo](https://www.g5niusx.com/2019/03/apollo-2.html)

**Comment by DorraChen** [comment]
> 如果是spring boot的项目，可以参考一下这个[demo](https://www.g5niusx.com/2019/03/apollo-2.html)
我除了没有支持动态刷新，其他的配置也有，为什么我用@Value就获取不到呢

**Comment by g5niusx** [comment]
> > 如果是spring boot的项目，可以参考一下这个[demo](https://www.g5niusx.com/2019/03/apollo-2.html)
> > 我除了没有支持动态刷新，其他的配置也有，为什么我用@value就获取不到呢

看一下这个。[spring整合](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#32-spring%E6%95%B4%E5%90%88%E6%96%B9%E5%BC%8F)
需要注意的是，如果之前有使用org.springframework.beans.factory.config.PropertyPlaceholderConfigurer的，请替换成org.springframework.context.support.PropertySourcesPlaceholderConfigurer。Spring 3.1以后就不建议使用PropertyPlaceholderConfigurer了，要改用PropertySourcesPlaceholderConfigurer。

**Comment by DorraChen** [comment]
> > > 如果是spring boot的项目，可以参考一下这个[demo](https://www.g5niusx.com/2019/03/apollo-2.html)
> > > 我除了没有支持动态刷新，其他的配置也有，为什么我用@value就获取不到呢
> 
> 看一下这个。[spring整合](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#32-spring%E6%95%B4%E5%90%88%E6%96%B9%E5%BC%8F)
> 需要注意的是，如果之前有使用org.springframework.beans.factory.config.PropertyPlaceholderConfigurer的，请替换成org.springframework.context.support.PropertySourcesPlaceholderConfigurer。Spring 3.1以后就不建议使用PropertyPlaceholderConfigurer了，要改用PropertySourcesPlaceholderConfigurer。

**Comment by DorraChen** [comment]
> > > 如果是spring boot的项目，可以参考一下这个[demo](https://www.g5niusx.com/2019/03/apollo-2.html)
> > > 我除了没有支持动态刷新，其他的配置也有，为什么我用@value就获取不到呢
> 
> 看一下这个。[spring整合](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#32-spring%E6%95%B4%E5%90%88%E6%96%B9%E5%BC%8F)
> 需要注意的是，如果之前有使用org.springframework.beans.factory.config.PropertyPlaceholderConfigurer的，请替换成org.springframework.context.support.PropertySourcesPlaceholderConfigurer。Spring 3.1以后就不建议使用PropertyPlaceholderConfigurer了，要改用PropertySourcesPlaceholderConfigurer。

改了之后依旧不行，考虑是加载顺序的问题。如何让Apollo配置优先加载进来呢？

**Comment by g5niusx** [comment]
`<apollo:config/>`有 `order` 的设置，值越小，配置级别越高。如果是注解注入，应该也有对应的配置项，设置的小一点就好了
