### ISSUE TITLE
通过不带缓存的Http接口从Apollo读取配置 如何选择env

### ISSUE THREAD

**Issue by chenguang9239** [ctripcorp/apollo#2058]
请问，根据URL: {config_server_url}/configs/{appId}/{clusterName}/{namespaceName}?releaseKey={releaseKey}&ip={clientIp}，没有提供传递env参数(比如PRO/FAT)？如何想获取某个env下的配置应该怎么写这个URL呢？

**Comment by g5niusx** [comment]
`{config_server_url}`知道的情况下，其实就已经确定了环境
`dev` ---> `127.0.0.1`
`fat` ---> `127.0.0.2`
通过这种请求来，所以我理解的是不需要带环境标志。
如果配置了 ha 负载均衡，可以直接请求对应环境的 ha 地址

**Comment by chenguang9239** [comment]
> `{config_server_url}`知道的情况下，其实就已经确定了环境
> `dev` ---> `127.0.0.1`
> `fat` ---> `127.0.0.2`
> 通过这种请求来，所以我理解的是不需要带环境标志。
> 如果配置了 ha 负载均衡，可以直接请求对应环境的 ha 地址

是这样的

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
