### ISSUE TITLE
如何将Spring的i18n文件放到Apollo对接

### ISSUE THREAD

**Issue by HelloTwar** [ctripcorp/apollo#2062]
我们项目有个这样的需求，要求把系统所有的错误状态码配置成国际化的，并且将配置好的文件放在Apollo维护。请问要怎样配置

**Comment by nobodyiam** [comment]
这个可以分成两步来做，第一步apollo怎么和spring对接，这个看apollo的文档即可，第二步国际化的代码怎么和spring对接，这个查一下相关资料。

如果国际化的代码不是和spring对接，而是直接读取的resources下的文件，那么这个可能要看下是否可以直接通过api方式和apollo对接，apollo的namespace概念就类似于文件

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
