### ISSUE TITLE
如何在一个项目中配置多个app.id

### ISSUE THREAD

**Issue by bad2cat** [ctripcorp/apollo#2063]
碰到项目中的一个需求，需求是从apollo上获取其他项目的配置文件，如果将app.id写到环境变量的话，每次修改环境变量都要重启项目。所以想问一下，能不能在项目中配置多个app.id，这样就可以不用重启项目了

**Comment by nobodyiam** [comment]
从概念上来讲一个应用只有一个app.id身份的，所以是不支持动态修改app.id的

如果要获取其他项目的配置文件的话，可以通过公共namespace

**Comment by bad2cat** [comment]
@nobodyiam 你好，还想问一下，app.id现在是由Apollo自己去配置文件中读取的，而开发人员是通过在代码里指定该app.id下namespace来获取配置。

将来会不会把app.id也让开发去自己代码里设置，而不是由apollo直接去配置文件读取？？

**Comment by g5niusx** [comment]
> @nobodyiam 你好，还想问一下，app.id现在是由Apollo自己去配置文件中读取的，而开发人员是通过在代码里指定该app.id下namespace来获取配置。
> 
> 将来会不会把app.id也让开发去自己代码里设置，而不是由apollo直接去配置文件读取？？

这个你可以自己实现的。通过 `System.setProperty()`,应该可以实现代码注入app.id,参考 `DefaultApplicationProvider` 这个类

**Comment by bad2cat** [comment]
好的，谢谢
