### ISSUE TITLE
openApi getNamespaces 内部时间转换异常

### ISSUE THREAD

**Issue by zhouxiaohai** [ctripcorp/apollo#2065]
![image](https://user-images.githubusercontent.com/17846308/54672363-cfe74900-4b32-11e9-81b9-b5cff4d23594.png)

apollo-openapi:1.3.0 通过gson转成class报时间转换异常。

**Comment by zhouxiaohai** [comment]
![image](https://user-images.githubusercontent.com/17846308/54675210-1475e300-4b39-11e9-8338-301d1255c8bb.png)
取出来时间貌似非UTC格式

**Comment by DeanJi** [comment]
使用的gson版本是2.8.0吗

**Comment by nobodyiam** [comment]
麻烦给一下运行时gson的版本以及服务端的返回值，这个日期格式应该是可以支持的

**Comment by DeanJi** [comment]
我之前使用低版本的gson-2.2.4，出现同样的问题，使用2.8.0就ok了

**Comment by zhouxiaohai** [comment]
![image](https://user-images.githubusercontent.com/17846308/54728270-d10e8980-4bb7-11e9-853f-8429dd48a0a2.png)
我用的是apollo依赖2.3.1

**Comment by zhouxiaohai** [comment]
![image](https://user-images.githubusercontent.com/17846308/54728332-3a8e9800-4bb8-11e9-80b5-8f22a3c495d5.png)
客户端返回的值

**Comment by zhouxiaohai** [comment]
![image](https://user-images.githubusercontent.com/17846308/54728634-fac8b000-4bb9-11e9-8f58-50fa7ac30a2f.png)


> 我之前使用低版本的gson-2.2.4，出现同样的问题，使用2.8.0就ok了

谢谢! 按照你的操作是可以的了.

**Comment by nobodyiam** [comment]
apollo open api默认的传递依赖是2.8.0的，应该是项目中其它地方覆盖了这个传递依赖的版本

mvn dependency:tree -Dverbose -Dincludes=:gson

```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ apollo-openapi ---
[INFO] com.ctrip.framework.apollo:apollo-openapi:jar:1.3.0
[INFO] \- com.ctrip.framework.apollo:apollo-core:jar:1.3.0:compile
[INFO]    \- com.google.code.gson:gson:jar:2.8.0:compile
```

**Comment by yaningxu** [comment]
我也遇到解析时间异常了，重写了client 修复。麻烦作者改下换下format格式
xception: Unparseable date: "2019-07-17T19:31:43.686+0800"

Gson gson = (new GsonBuilder()).setDateFormat("yyyy-MM-dd\'T\'HH:mm:ssZ").create();

yyyy-MM-dd'T'HH:mm:ss.SSSZ（对）
yyyy-MM-dd\'T\'HH:mm:ssZ（错）

**Comment by nobodyiam** [comment]
@yaningxu 

麻烦提供下重现步骤吧

**Comment by yaningxu** [comment]
就是正常调用api进行添加命名空间和配置时返回的报文时间格式和代码的format不一致。看你们讲gson版本导致，我那个gson的确被传递依赖给降级了，也许高版本gson做了时间格式兼容处理，但根本的问题的确是api返回的时间格式和代码不一致

**Comment by nobodyiam** [comment]
@yaningxu 

看上去确实是你说的这个问题，PR建议拆小，按照功能分开提交吧，这样review和合并更有针对性。

**Comment by yaningxu** [comment]
好的
