### ISSUE TITLE
请问app，cluster，namespace，item个数过多会影响apollo性能吗？

### ISSUE THREAD

**Issue by otyyyywangwenbin** [ctripcorp/apollo#2068]
1.  如果app个数在500，每个app的cluster的个数在10，每个cluster的namespace在10，每个namespace的item个数在100左右，这种情况是否会影响apollo client的配置生效的时效性以及apollo portal的性能？看到性能测试的数据只有client连接数的多少，还是说app，cluster等等这种个数的多少对性能没有影响？

2. 另外一个问题，一个namespace里，是用很多key-value，还是用一个key配一个大value，这2种使用哪种更好？

谢谢！

**Comment by nobodyiam** [comment]
1. 可以看下config service相关的代码，和app等数量关系不大

2. 这个看实际使用场景，一般建议key-value的粒度，管理和使用简单

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
