### ISSUE TITLE
求答 openapi 接口疑问？

### ISSUE THREAD

**Issue by zhouxiaohai** [ctripcorp/apollo#2069]
场景：介于我司做私有化部署，所有配置希望自动化完成。 

现集成遇到以下几个暂时不满足的问题：
1. 第三方应用创建接口是否可以开放？
2. 开放平台API中貌似没找到可以创建关联namespace接口？
3. 覆盖配置是否createOrUpdate就可以完成（未测试的原因我无法创建关联namespace）？
4. token是否永久有效 (现两天有效中)？

请宋顺大哥或携程兄弟们帮我解答下，感谢！

**Comment by nobodyiam** [comment]
1. open api的token目前权限是在app维度的，所以目前open api是无法创建应用的。针对这个情况，可能要新增一个专用的token来创建app

2. open api的定位更多地是帮助用户通过第三方系统录入配置，所以关联namespace接口目前还没有

上述两点实现起来也不难，可以自己实现一下，然后提个PR上来~

3. 是

4. token默认永久有效，不过在接口和模型上是有有效期的，具体看下 com.ctrip.framework.apollo.portal.controller.ConsumerController#createConsumer

**Comment by zhouxiaohai** [comment]
谢谢宋大哥的建议，目前已得到可解方案。

**Comment by valiantLoving** [comment]
> 谢谢宋大哥的建议，目前已得到可解方案。

方便说下怎么处理吗, 我也想通过 api 来新建项目
