### ISSUE TITLE
jdk1.8可以启动，但是相同配置换成jdk9，jdk11，jdk12都无法启动

### ISSUE THREAD

**Issue by ZaneGeng** [ctripcorp/apollo#2073]
[root@bogon scripts]# ./startup.sh 
2019年 03月 23日 星期六 00:26:11 CST ==== Starting ==== 
Started [5636]
Waiting for server startup.
pid - 5636 just quit unexpectedly, please check logs under /opt/logs/100003171 and /tmp for more information!

apollo的配置都没问题，但是jdk切到9,11,12都如上报错，换成jdk8就可用，想问下怎么解决在高jdk下使用？

**Comment by ZaneGeng** [comment]
log文件显示：
Unrecognized VM option 'UseParNewGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by nobodyiam** [comment]
Unrecognized VM option 'UseParNewGC'

gc参数先去掉试试

**Comment by kezhenxu94** [comment]
> Unrecognized VM option 'UseParNewGC'
> 
> gc参数先去掉试试

@nobodyiam I'm working on this, simply removing the VM options doesn't work, some dependencies must be added due to modularity above JDK 9

**Comment by nobodyiam** [comment]
@kezhenxu94 

Thanks! Looking forward to it!

**Comment by kezhenxu94** [comment]
> @kezhenxu94
> 
> Thanks! Looking forward to it!

Done, have a look if you've got some time :)

**Comment by nobodyiam** [comment]
@kezhenxu94 

Nice job! It may take me some time to set up environments and do some basic verifications.

**Comment by microtol** [comment]
我想提个问题，有没有谁试验过能不能把oracle jdk 换成openjdk？
因为linux默认都是openJDK。要安安装oracle jdk还是有点麻烦的。

**Comment by nobodyiam** [comment]
docker镜像中用的都是open jdk

**Comment by li55626437** [comment]
我的jdk版本是java version "1.8.0_271"  怎么也报这个错：pid - 24788 just quit unexpectedly, please check logs under /opt/logs/100003171 and /tmp for more information! ，但是在日志里又没看到具体的错误ERROR

**Comment by nobodyiam** [comment]
@li55626437 日志里应该有的，可以仔细检查一下，或者可以尝试 java -jar apollo-configservice.jar 前台运行看看报错信息
