### ISSUE TITLE
spring项目，会识别XML文件中的CDATA区域中的${name},注入失败

### ISSUE THREAD

**Issue by wenhongli** [ctripcorp/apollo#2076]
最近传统的spring项目，要引入apollo。通过java的配置方式，然后项目在启动的时候会识别到XML中的CDATA区域短信模板中的${name}，并注入，但是其实CDATA区域就是让其忽略注入的。根本没有name这个配置项，然后启动报错，有没有什么方法让其忽略CDATA区域

**Comment by nobodyiam** [comment]
这个注入不是apollo做的，是spring注入的，应该和是否引入apollo没啥关系吧？

**Comment by wenhongli** [comment]
> 这个注入不是apollo做的，是spring注入的，应该和是否引入apollo没啥关系吧？

不是的..spring没有注入CDATA区域的占位符，引入apollo后才注入的，我已经把占位符改成@{name}了，问题解决了

**Comment by nobodyiam** [comment]
能否上传一个简单demo？因为apollo做的只是在spring中增加了一个property source而已，不会去解析xml的

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
