### ISSUE TITLE
ConfigChangeListener是否能监听到由哪个operator引发的配置变化？

### ISSUE THREAD

**Issue by finefuture** [ctripcorp/apollo#2077]
目前我是自己在configservice的ConfigController修改了返回内容的代码以及ApolloConfig新增了一个字段

**Comment by nobodyiam** [comment]
客户端为啥要知道是哪个operator的操作引起的？这个属于portal的范畴啊

**Comment by finefuture** [comment]
目前我有一个场景需要用到，就是比如在应用程序中使用OpenApi修改配置，这时候会有一个operator，在portal界面修改这时候也有一个operator（即登录账户），这时候如果使用了监听器，会有需要过滤是哪个operator引起的配置变化以使用不同的应对策略

**Comment by nobodyiam** [comment]
如果实在有这个需求，建议增加一个operator配置项

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
