### ISSUE TITLE
docker镜像层下载不下来

### ISSUE THREAD

**Issue by abelzhyb** [ctripcorp/apollo#2080]
docker镜像有一层下载不下来
Status: Downloaded newer image for mysql:5.7
Pulling apollo-quick-start (nobodyiam/apollo-quick-start:)...
latest: Pulling from nobodyiam/apollo-quick-start
6c40cc604d8e: Downloading   这一层下载不了，试了好几次
e78b80385239: Download complete
f41fe1b6eee3: Download complete
f81fe3873b24: Download complete
6ee996dcbacb: Download complete
bf515fdbd069: Download complete
5e4fe6eab272: Download complete
7d18aca46713: Download complete
cdbb4cafaa13: Download complete

ERROR: error parsing HTTP 408 response body: invalid character '<' looking for beginning of value: "<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n\n"

**Comment by nobodyiam** [comment]
检查下网络，或者弄一个镜像加速吧

```
Pulling apollo-quick-start (nobodyiam/apollo-quick-start:)...
latest: Pulling from nobodyiam/apollo-quick-start
6c40cc604d8e: Pull complete
e78b80385239: Pull complete
f41fe1b6eee3: Pull complete
f81fe3873b24: Pull complete
6ee996dcbacb: Pull complete
bf515fdbd069: Pull complete
5e4fe6eab272: Pull complete
7d18aca46713: Pull complete
cdbb4cafaa13: Pull complete
Creating apollo-dbdata ... done
Creating apollo-db     ... done
Creating apollo-quick-start ... done
```

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
