### ISSUE TITLE
请教下权限分配处理问题

### ISSUE THREAD

**Issue by Doubleuncle** [ctripcorp/apollo#2085]
现情况如下，我们有很多集群环境，所有集群里都有一份同名的namespace,且namespace里所有配置项都一致，只是对应的值各集群不尽相同。
现在希望能做到的是每个集群有一个自己的用户，这个用户只能修改和发布自己集群下的namespace。

但是现有的授权貌似只能通过namesapce层面，且授权某个用户后，他就可以在全部集群里去修改。

请问有没有好的方案可以实现如上的需求？

**Comment by Doubleuncle** [comment]
目前考虑的做法是把应用这一层看作集群项，给不同集群建立不同的应用，每个用户只能看到自己的应用，并修改自己应用下的namespace,cluster这一项就没有再用了，算是一种变通。

**Comment by nobodyiam** [comment]
apollo的权限模型目前能支持到同一个namespace在不同的环境权限不同，还不支持到集群级别粒度

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
