### ISSUE TITLE
我感觉 adminservice configservice 接口都暴露了 不安全啊 

### ISSUE THREAD

**Issue by davidclj** [ctripcorp/apollo#2089]
我感觉 adminservice configservice 接口都暴露了 不安全啊
http://106.12.25.204:8080/configs/apollo-demo/default/application
上面这个地址是你们的demo，我可以绕过portal直接访问configservice了

@nobodyiam 是不是啊？

**Comment by nobodyiam** [comment]
config service设计是内网服务，本来就不需要通过portal访问的

**Comment by flysnow911** [comment]
> config service设计是内网服务，本来就不需要通过portal访问的

自己人也要防着^_^

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
