### ISSUE TITLE
接入ldap后，创建项目不能选择应用负责人

### ISSUE THREAD

**Issue by jason-wei1127** [ctripcorp/apollo#2090]
![image](https://user-images.githubusercontent.com/19190008/55069811-d855fb80-50bf-11e9-9532-48e03cc1e1f2.png)
1.3版，接入AD后，可以使用域用户正常登录，但在创建项目时，不能选择应用负责人，没办法创建项目。

**Comment by nobodyiam** [comment]
建议仔细参考一下[接入说明](https://github.com/ctripcorp/apollo/wiki/Portal-%E5%AE%9E%E7%8E%B0%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95%E5%8A%9F%E8%83%BD#2-active-directory%E6%8E%A5%E5%85%A5%E6%96%B9%E5%BC%8F)，看看是不是设置了不正确的filter

**Comment by jason-wei1127** [comment]
ldap:
  mapping: # 配置 ldap 属性
    objectClass: "user" # ldap 用户 objectClass 配置
    loginId: "sAMAccountName" # ldap 用户惟一 id，用来作为登录的 id
    userDisplayName: "cn" # ldap 用户名，用来作为显示名
    email: "userPrincipalName" # ldap 邮箱属性
  filter: # 可选项，配置过滤，目前只支持 memberOf
    memberOf: "OU=IT1,DC=test,DC=com,DC=cn|OU=IT2,DC=test,DC=com,DC=cn" #希望允许IT1和IT2两个部门的用户登录访问，创建项目

上面是我的配置参数，请帮忙看下是否正确，谢谢！

**Comment by nobodyiam** [comment]
建议先把filter memberof去掉试试，估计是这个配置不对导致被过滤掉了

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by lcb1208** [comment]
> ldap:
> mapping: # 配置 ldap 属性
> objectClass: "user" # ldap 用户 objectClass 配置
> loginId: "sAMAccountName" # ldap 用户惟一 id，用来作为登录的 id
> userDisplayName: "cn" # ldap 用户名，用来作为显示名
> email: "userPrincipalName" # ldap 邮箱属性
> filter: # 可选项，配置过滤，目前只支持 memberOf
> memberOf: "OU=IT1,DC=test,DC=com,DC=cn|OU=IT2,DC=test,DC=com,DC=cn" #希望允许IT1和IT2两个部门的用户登录访问，创建项目
> 
> 上面是我的配置参数，请帮忙看下是否正确，谢谢！

解决了么

**Comment by 0412jiangchong** [comment]
> 遇到同样问题，并没有任何过滤,能拉我进群么？

**Comment by biubiue** [comment]
> > 遇到同样问题，并没有任何过滤,能拉我进群么？

我解决了，大致是配置的不对，记不太清了
