### ISSUE TITLE
service高可用选取和系统信息页面中显示问题

### ISSUE THREAD

**Issue by reignsr** [ctripcorp/apollo#2091]
部署了apollo-1.3.0版本，针对SIT和UAT环境部署了高可用，每个环境都是两个service节点，经测试验证，高可用方案有效，会从其中一个节点中获取配置，当某个节点停机后，会随即切换到另一个节点获取配置。先赞一个！ 另有两个疑问：

1、client获知meta server有两个节点后，如何选取从哪个节点获取配置？
日志中看到是这样的：
Selecting meta server address for: http://172.18.168.107:8181,http://172.18.169.5:8181
Selected meta server address http://172.18.169.5:8181 for http://172.18.168.107:8181,http://172.18.169.5:8181
尝试了交换两个地址的先后顺序，也没有发现规律。

2、portal的“系统信息”页面中，高可用部署的多个service节点，有时只显示一个。请问是什么情况？
各个节点的运行状态正常，日志中也能看到相应的消息。重新登陆portal，“系统信息”页面列表中的多节点会时有时无。如图所示：

**显示了多个节点：**
![apollo-ha-info](https://user-images.githubusercontent.com/814702/55070180-a7c29180-50c0-11e9-893f-9b7b1165343a.jpg)

**只显示一个节点：**
![apollo-single-info](https://user-images.githubusercontent.com/814702/55070192-ad1fdc00-50c0-11e9-8709-e0c07a07ed83.jpg)

**Comment by nobodyiam** [comment]
1. 可以参考 com.ctrip.framework.apollo.core.MetaDomainConsts#updateMetaServerAddresses，是随机选一个测试，如果可用就用了

2. 是从meta server上获取的列表，你可以分别打开两个meta server地址看看上面注册的服务信息
