### ISSUE TITLE
appid大小不一致导致不能拉取配置更新

### ISSUE THREAD

**Issue by flypigarmy** [ctripcorp/apollo#2092]
当appid中存在字母时，如果客户端配置和portal中配置的appid大小写不一致，仍然可以获取配置，当配置发生更改，客户端无法收到最新的配置推送。建议appid大小写不敏感或禁用字母，否则容易产生莫名其妙的问题。

**Comment by nobodyiam** [comment]
是的，因为推送时是内存中找对应的客户端的，后续可以改为不区分大小写
