### ISSUE TITLE
Controller中的有些path中的:.+是啥意思哦

### ISSUE THREAD

**Issue by DeanJi** [ctripcorp/apollo#2093]
比如：@GetMapping(value = "/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/items/{key:.+}")
  public OpenItemDTO getItem(@PathVariable String appId, @PathVariable String env, @PathVariable String clusterName,
      @PathVariable String namespaceName, @PathVariable String key) {

{key:.+}中的:.+是什么意思？

**Comment by kezhenxu94** [comment]
> 比如：@GetMapping(value = "/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/items/{key:.+}")
> public OpenItemDTO getItem(@PathVariable String appId, @PathVariable String env, @PathVariable String clusterName,
> @PathVariable String namespaceName, @PathVariable String key) {
> 
> {key:.+}中的:.+是什么意思？

@DeanJi 与正则表达式一样的意思, 表示匹配任意大于一个字符长度的串(Key 至少一个字符)

**Comment by ryphnyuan** [comment]
一般是处理最后一个参数包含小数点的情况，比如上面的例子里面的key是abc.defg，如果不加:.+的话，获取到的参数就只有abc。
springboot 2.x应该解决了这个问题了。

**Comment by DeanJi** [comment]
为啥其他好多接口没有加:.+?

**Comment by ryphnyuan** [comment]
只有参数是Path的最后一段才需要，中间的带点是可以正常获取的。
比如"/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/items/{key:.+}")
这里面appId、clusterName、namespaceName带小数点都没事，但是key带小数点就不行了，所以要加:.+
代码里面有几处没加的不知道是不是遗漏了

**Comment by DeanJi** [comment]
感谢解答
