### ISSUE TITLE
建议登录请求给密码加密，密码这样直接暴露出来，请问大家是怎么解决的

### ISSUE THREAD

**Issue by sundjly** [ctripcorp/apollo#2094]
![image](https://user-images.githubusercontent.com/23523003/55140760-cf266680-5173-11e9-8532-a98ec93fb04e.png)

密码这样直接暴露出来

大家是怎么解决的

谢谢了

**Comment by g5niusx** [comment]
前台页面的登陆吗？这个需要自己开发一下吧。

**Comment by g5niusx** [comment]
这个应该需要自己开发一下来。可以使用 `js` 来对传输的密码做一次加密。

**Comment by sundjly** [comment]
嗯嗯 ，已经解决了，用原生的form表单提交实现的，点击提交按钮，对数据加密，然后在调用submit方法

**Comment by nobodyiam** [comment]
@sundjly 服务端是通过什么方式解密的？如果通用的话，非常欢迎提交一个PR
