### ISSUE TITLE
筛选ReleaseMessage的疑问

### ISSUE THREAD

**Issue by ruanxingshi** [ctripcorp/apollo#2095]
ReleaseMessageScanner 会有一个定时线程每次抓取500条记录，这里会不会出现重复的问题，比如confinservice要是做了集群有两个节点的话，这两个节点分别有一个线程在定时执行，那就会抓取到重复的记录吧

**Comment by nobodyiam** [comment]
release message可以认为是广播消息，所以是需要不同的config service获取到相同的记录的

**Comment by ardenxu** [comment]
在学习releasemessage的实际处理。请问宋工configservice 定时扫描数据库查询是否有新release message。但实际客户端配置更新，仍然是通过longpoll的方式获取的，这个理解是否正确。

**Comment by nobodyiam** [comment]
@ardenxu 可以看下[配置发布后的实时推送设计](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1#21-%E9%85%8D%E7%BD%AE%E5%8F%91%E5%B8%83%E5%90%8E%E7%9A%84%E5%AE%9E%E6%97%B6%E6%8E%A8%E9%80%81%E8%AE%BE%E8%AE%A1)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
