### ISSUE TITLE
请教一下list热更新的问题。

### ISSUE THREAD

**Issue by qiaokeke** [ctripcorp/apollo#2096]
1. 问题
* 你好，我的问题是这样的，我的配置是list，我要实时获取list的变化，重启应用可以获取到配置，但是不能热更新
2. 配置
```
aaa.bbbList[0].ccc = 288016
aaa.bbbList[0].ddd = true
aaa.bbbList[1].ccc = 22222
aaa.bbbList[1].ddd = false
aaa.bbbList[2].ccc = 485503
aaa.bbbList[2].ddd = true
aaa.bbbList[3].ccc = 666666
aaa.bbbList[3].ddd = false
```
3. 代码
```
@Component
@ConfigurationProperties(prefix = "aaa")
@Data
public class RoomScheduConfig {

    List<Bbb> bbbList;

}

```

**Comment by g5niusx** [comment]
热更新需要加 `refreshScope` 来动态更新 bean 。refreshScope 是 spring-cloud-context 的依赖
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-context</artifactId>
    <version>2.1.1.RELEASE</version>
  </dependency>
```

**Comment by qiaokeke** [comment]
> 热更新需要加 `refreshScope` 来动态更新 bean 。refreshScope 是 spring-cloud-context 的依赖
> 
> ```
> <dependency>
>     <groupId>org.springframework.cloud</groupId>
>     <artifactId>spring-cloud-context</artifactId>
>     <version>2.1.1.RELEASE</version>
>   </dependency>
> ```

嗯，又看了一遍文档，这样确实可以。但是用起来比较麻烦，还要引入其他依赖。请问有没有更好的办法来注入list beans，而不是 @ConfigurationProperties(prefix = "aaa")

**Comment by g5niusx** [comment]
我所知道的也是这种。。其他的不清楚～😄

**Comment by nobodyiam** [comment]
spring cloud的话，还可以使用EnvironmentChangeEvent，参见[spring-cloud-logger](https://github.com/ctripcorp/apollo-use-cases/blob/master/spring-cloud-logger/src/main/java/com/ctrip/framework/apollo/use/cases/spring/cloud/logger/LoggerLevelRefresher.java#L51)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
