### ISSUE TITLE
正常拉取到配置了但是一直报一个错误

### ISSUE THREAD

**Issue by jsonchina** [ctripcorp/apollo#2097]
reason: Could not complete get operation [Cause: Unexpected end of file from server]

**Comment by nobodyiam** [comment]
1. 看下meta server配置是否正确
2. 可以wireshark看一下网络包

**Comment by jsonchina** [comment]
meta server配置是正确的,用fiddler看了下 没看出啥毛病

**Comment by jsonchina** [comment]
> 1. 看下meta server配置是否正确
> 2. 可以wireshark看一下网络包
meta server配置是正确的,用fiddler看了下 没看出啥毛病

**Comment by hujintao000** [comment]
问题解决了没有呢

**Comment by nobodyiam** [comment]
可以根据提示的URL通过curl访问一下

**Comment by hicker000** [comment]
通过curl访问的结果
{"exception":"org.springframework.web.bind.MissingServletRequestParameterException","message":"Required String parameter \u0027appId\u0027 is not present","status":500,"timestamp":"2019-04-17T12:37:36.324"}

**Comment by nobodyiam** [comment]
你这个日志是说访问的url里面缺少appId信息

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
