### ISSUE TITLE
configService部署启动抛错

### ISSUE THREAD

**Issue by haosufu** [ctripcorp/apollo#2098]
反复Cannot execute request on any known server， 我在serverconfig表已经特别指定configService本身的地址和IP了

**Comment by haosufu** [comment]
补充serverconfig表的eureka.service.url

**Comment by nobodyiam** [comment]
单机启动时报错是正常，因为自己向自己注册，自己的端口还没起来

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
