### ISSUE TITLE
apollo集群部署,session不共享导致无法登录问题

### ISSUE THREAD

**Issue by tqy-github** [ctripcorp/apollo#2100]
Apollo架构V5
V4版本已经是比较完整的Apollo架构全貌，现在还剩下最后一个环节：Portal也是无状态以集群方式部署的，用户如何发现和访问Portal？答案也是简单的传统做法，用户通过域名+NginxLB间接访问Portal集群。
以上是《携程Apollo配置中心架构剖析》by波波的架构方案
我们在生产环境apollo-portal部署了3套,使用一个VIP进行了负载均衡绑定,发现登录跳转提示无法登录.发现apollo-portal是有状态的,请问session共享需要使用方自己实现吗,还是说建议portal只部署一套即可

**Comment by nobodyiam** [comment]
默认提供的基于spring security的方案目前登录状态是在session中的，可以考虑改造下或者接入公司自己的sso

**Comment by nisiyong** [comment]
我也遇到了这个问题，生产部署两个apollo-portal，用LVS vip绑定这两个rs，发现要重复登录，即session不共享问题。

## 解决方法
调整LVS 调度策略，改为Srch(基于ip hash)，默认是Wrr(轮询)。
