### ISSUE TITLE
频繁出现env is not set

### ISSUE THREAD

**Issue by JarvisZhu** [ctripcorp/apollo#2102]
服务启动时是以java -Denv=PRO -jar的形式来指定的，启动时正常，服务运行一段时间后，非常频繁打印出“env is not set, please make sure it is set in /opt/settings/server.properties!”。
这边能观察到的一个现象就是：服务频繁GC，三分钟一个gc文件，但是我看源码，项目启动后获取到环境值赋值到类变量里了，频繁gc应该不影响吧？
望解答，谢谢。

**Comment by nobodyiam** [comment]
env是在程序启动的时候初始化的，不应该是运行一段时间后才打印的，建议Heap dump一下看看DefaultServerProvider中的状态

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
