### ISSUE TITLE
springboot整合apollo遇到问题

### ISSUE THREAD

**Issue by xiaolaing** [ctripcorp/apollo#2106]
您好：
          我目前遇到一个需求，就是springboot项目整合apollo后，想继续从resources 下的application.properties中来读取数据，想请教您，项目启动后，apollo-client能否完成对application.properties中参数的实时更新？我是否必须手动添加从application.properties中动态获取配置信息的功能？

**Comment by nobodyiam** [comment]
本质上而言，apollo的配置和application.properties中的配置都是通过spring管理的，所以不需要区别看待。

**Comment by xiaolaing** [comment]
谢谢你！
Jason Song <notifications@github.com> 于2019年4月2日周二 下午11:38写道：

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
