### ISSUE TITLE
Apollo的k8s部署问题

### ISSUE THREAD

**Issue by tanxiaosheng** [ctripcorp/apollo#2107]
在实际的生产环境，使用k8s部署apollo遇到很多问题，首先就是配置的同步和迁移非常麻烦，能否考虑支持properties和yml文件的导入和导出，并且支持配置文件的自动导入，这样的话各个项目的配置也便于归档和迁移。
还有就是现在apollo的部署配置还是有点分散，比如portal的环境列表只能在portal数据库的serverconfig中修改apolllo.portal.envs的值，经常忘记修改，应该在apollo-env.properties中配置，这样的话就可以和各个环境的meta地址一起配置，推荐减少数据库中的系统配置参数。
最后一个问题就是目前没有一个很好的方案，解决在公有云上部署多套k8s环境，用一个portal管理多套环境的配置。

**Comment by nobodyiam** [comment]
1. apollo的页面上有文本模式的，可以直接以properties格式复制和粘贴来实现导出和导入

2. apolllo.portal.envs这个也可以通过管理员工具-系统参数页面配置的
不过环境这块是一直想优化的，理想情况是全部在管理员工具中配置，不需要手动改apollo-env.properties文件

3. 公有云上部署多套k8s环境，用一个portal管理多套环境的配置
这个现在的问题是portal无法连通各个环境？

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
