### ISSUE TITLE
求助！！如何删除环境？如何修改namespace的名称？

### ISSUE THREAD

**Issue by 308299160** [ctripcorp/apollo#2110]
找了半天没有找到删除环境的按钮。namespace名字随便取的，现在想换一个，如何操作？必须删除了重建吗？

**Comment by nobodyiam** [comment]
可以通过管理员工具删除appnamespace后重建

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
