### ISSUE TITLE
eclipse导入项目，测试部分代码报错

### ISSUE THREAD

**Issue by joney888999** [ctripcorp/apollo#2114]
是不是应该在顶层的maven pom.xml文件中引入相关的mockito测试包，我这边引入了<dependency>
			    <groupId>org.mockito</groupId>
			    <artifactId>mockito-core</artifactId>
			    <version>2.25.1</version>
			    <scope>test</scope>
			</dependency>

还有有报错的地方，RemoteConfigLongPollServiceTest这个类，101行报错，是不是对应的版本不对

**Comment by nobodyiam** [comment]
项目应该是没问题的，毕竟travis ci一直在跑的，所以不需要自己手动修改任何代码。

项目clone下来之后，可以先用原始的`mvn clean compile`编译一下

**Comment by jack888999** [comment]
![image](https://user-images.githubusercontent.com/48112557/55707743-ec322380-5a16-11e9-96c5-a8d29cf1ac71.png)

**Comment by nobodyiam** [comment]
建议项目clone下来之后，先用原始的mvn clean compile跑一下，目测应该是你本地eclipse的问题

**Comment by wAlec42** [comment]
你遇到的问题是单元测试报错提示”java.lang.IllegalStateException: Failed to load ApplicationContext“吗？如果是这个的话在/test/resources/下建一个bootstrap.yml测试就正常了（空的就行)
