### ISSUE TITLE
客户端在不同的环境下namespaces不同，如何使用@ApolloConfigChangeListener监听当前环境的namesapces

### ISSUE THREAD

**Issue by 13827475135** [ctripcorp/apollo#2118]
如题，有什么办法之在一个方法上加@ApolloConfigChangeListener，而不是在每个环境下，分别监控而使用多次@ApolloConfigChangeListener

**Comment by nobodyiam** [comment]
可以使用API方式监听

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
