### ISSUE TITLE
为什么我启动configservice和adminservice后，Eureka上会多一个UNKONWN的application

### ISSUE THREAD

**Issue by shihuiyong789** [ctripcorp/apollo#2119]
RT
![UNKNOWN APPLICATION](https://user-images.githubusercontent.com/44158189/55777666-28c35500-5ad3-11e9-8086-2677fe4f2d80.png)

**Comment by 13827475135** [comment]
点击localhost进去会跳转到哪里

**Comment by shihuiyong789** [comment]
跳转到：http://192.168.26.1:8080/info
返回：{}

**Comment by shihuiyong789** [comment]
![image](https://user-images.githubusercontent.com/44158189/55778150-b489b100-5ad4-11e9-8063-47c49f13aa0f.png)
我本地的ipconfig

**Comment by nobodyiam** [comment]
和apollo-configservice注册上来的是同一个地址吗？是否用的quick start启动的？

**Comment by shihuiyong789** [comment]
> 和apollo-configservice注册上来的是同一个地址吗？是否用的quick start启动的？
是用的quick start启动的，我只修改了demo.sh里面的jdk和database信息。理论上应该和configservice注册的是同一个地址吧

**Comment by nobodyiam** [comment]
quick start的打包方式和分布式部署的不同，貌似确实遇到会出现UNKNOWN的情况，因为quick start只供demo使用，所以目前还没去定位原因

**Comment by ls5201314** [comment]
> RT
> ![UNKNOWN APPLICATION](https://user-images.githubusercontent.com/44158189/55777666-28c35500-5ad3-11e9-8086-2677fe4f2d80.png)

我有相同的问题，多了过UNKNOWN服务请问解决了吗？

**Comment by ls5201314** [comment]
> RT
> ![UNKNOWN APPLICATION](https://user-images.githubusercontent.com/44158189/55777666-28c35500-5ad3-11e9-8086-2677fe4f2d80.png)

我也有相同的问题，多了一个UNKNOWN服务请问解决了吗？
