### ISSUE TITLE
请问k8s部署的服务如何对接apollo

### ISSUE THREAD

**Issue by hankimgh** [ctripcorp/apollo#2120]
k8s服务的配置信息是在configmap.yml，请问如何对接Apollo？如何实现自动刷新配置？是否有demo参考一下？
谢谢！

**Comment by nobodyiam** [comment]
如果是普通的应用，直接通过sdk对接即可

apollo目前还没有和config map对接的机制

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
