### ISSUE TITLE
客户端接入404

### ISSUE THREAD

**Issue by roneywei** [ctripcorp/apollo#2121]
服务端已经发布，客户端获取不到
![image](https://user-images.githubusercontent.com/5858867/55857001-92f4fc00-5b9e-11e9-9a57-dbcdb65dafea.png)
![image](https://user-images.githubusercontent.com/5858867/55857016-9be5cd80-5b9e-11e9-9a0a-8864a08b569b.png)
![image](https://user-images.githubusercontent.com/5858867/55857027-a607cc00-5b9e-11e9-9509-772f9dbbbb0b.png)

**Comment by zouchengli** [comment]
检查下eureka暴露出来的地址吧

roneywei <notifications@github.com> 于2019年4月10日周三 下午2:41写道：

**Comment by roneywei** [comment]
我知道啥问题了，ApolloConfigDB部署的问题，谢谢

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
