### ISSUE TITLE
application.yml与application.properties有配置项冲突时哪个生效?

### ISSUE THREAD

**Issue by gundamff** [ctripcorp/apollo#2122]

**Comment by nobodyiam** [comment]
apollo的namespace优先级比本地文件高

**Comment by gundamff** [comment]
怪我没说清楚,补充下
2个namespace都在apollo内的,如:
本地 application.properties
`apollo.bootstrap.namespaces = application.yaml,application`

apollo:
application.properties
`spring.datasource.url = AAAAAAAA`

application.yaml
```
spring:
  datasource:
     url:BBBBBBBBBBBBB
```

我测试结果是 yaml的会覆盖掉properties,这里的优先级有个配置会不会好一些

**Comment by nobodyiam** [comment]
这里是谁在前谁的优先级高，比如application.yaml在前，所以它的优先级高

**Comment by gundamff** [comment]
测试过了 这里前后顺序换过来也还是yaml的优先级高

**Comment by nobodyiam** [comment]
不应该的，代码里面就是按照声明的顺序
