### ISSUE TITLE
k8s配置文件错误

### ISSUE THREAD

**Issue by liuda1980** [ctripcorp/apollo#2123]
apollo/scripts/apollo-on-kubernetes/kubernetes/中的yaml配置文件都有错误，需要修改。
修改点有2个
1、eureka.service.url地址中需要加上空间名称 sre
2、dev，pod，test等环境 需要用自己的注册中心。

**Comment by nobodyiam** [comment]
之前已经有一个PR做过类似的修复了，验证也是OK的，可以看一下 #2113

**Comment by sunnoy** [comment]
当前部署Apollo组件都在sre namespace内，eureka只是提供内部config和admin的服务注册，URL也就不需要加sre。如果要把Apollo组件多namespace部署，请自行添加。并且对于Apollo这种类型的服务也不推荐多namespace部署。

**Comment by nobodyiam** [comment]
[1.4.0](https://github.com/ctripcorp/apollo/releases/tag/v1.4.0)版本修复了几个k8s部署的问题，可以再按照[apollo-on-kubernetes](https://github.com/ctripcorp/apollo/blob/master/scripts/apollo-on-kubernetes/README.md)说明部署一下。

**Comment by wangycc** [comment]
![image](https://user-images.githubusercontent.com/12569878/60578794-6d9a1780-9db4-11e9-8705-f5e5ccfd5764.png)
@nobodyiam 请问，我这里注册的不是容器IP而是hostname,导致resolve失败

**Comment by liuda1980** [comment]
有详细问题描述吗？
  

 

 ------------------ 原始邮件 ------------------
  发件人: "notifications"<notifications@github.com>;
 发送时间: 2019年7月3日(星期三) 下午5:05
 收件人: "ctripcorp/apollo"<apollo@noreply.github.com>;
 抄送: "硫哒"<35045343@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [ctripcorp/apollo] k8s配置文件错误 (#2123)

 

 

@nobodyiam 请问，我这里注册的不是容器IP而是hostname,导致resolve失败

**Comment by wangycc** [comment]
@liuda1980 谢谢，没有问题，该issue已经关闭
