### ISSUE TITLE
配置中心配置的属性在logback-spring.xml获取不到

### ISSUE THREAD

**Issue by roneywei** [ctripcorp/apollo#2125]
配置中心配置的属性在logback-spring.xml获取不到
配置中心配置的信息
![image](https://user-images.githubusercontent.com/5858867/55868251-ae6c0100-5bb6-11e9-9b8d-22df5902b644.png)

logback-spring.xml
![image](https://user-images.githubusercontent.com/5858867/55868343-dd827280-5bb6-11e9-96c0-e995da8d2784.png)

结果
![image](https://user-images.githubusercontent.com/5858867/55868403-fd199b00-5bb6-11e9-96eb-dca54b3e2173.png)

**Comment by nobodyiam** [comment]
参考一下[https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#3213-spring-boot%E9%9B%86%E6%88%90%E6%96%B9%E5%BC%8F%E6%8E%A8%E8%8D%90](3.2.1.3 Spring Boot集成方式)中的第三部分 - 将Apollo配置加载提到初始化日志系统之前(1.2.0+)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by roneywei** [comment]
ok，已经解决，谢谢
