### ISSUE TITLE
spring 3.1.3通过xml的方式配置context:property-placeholder 引入的配置如何进行设置哪？

### ISSUE THREAD

**Issue by youjunyi** [ctripcorp/apollo#2127]
spring 3.1.3通过xml的方式配置context:property-placeholder 引入的配置如何进行设置哪？
是删除context:property-placeholder吗 还是修改context:property-placeholder 哪
<context:property-placeholder location="classpath:jdbc.properties"/>这个配置  应该如何修改 当我删掉这个配置的时候 配置成
<apollo:config namespaces="jdbc" order="1"/> 时候 本地C盘里是有文件的但是 在项目里不起作用
谢谢

**Comment by nobodyiam** [comment]
对照[3.2 Spring整合方式](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#32-spring%E6%95%B4%E5%90%88%E6%96%B9%E5%BC%8F)再仔细看一下吧

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
