### ISSUE TITLE
K8S部署apollo时出错

### ISSUE THREAD

**Issue by Jacksonary** [ctripcorp/apollo#2128]
&mesp;安照github上的说明来搞，在执行`kubectl-apply.sh`后，Pod状态为CrashLoopBackOff，查看日志提示`standard_init_linux.go:185: exec user process caused "no such file or directory"`，原因未知，请求帮忙，还有交流群号是什么

**Comment by nobodyiam** [comment]
可以先参照kubectl-apply.sh中的内容手动一个一个执行，应该是没问题的

**Comment by kinbod** [comment]
镜像有问题，，，镜像里面没有bash命令，如果你用的是alpine-jre的话，需要每次更新安装bash，busybox

**Comment by Jacksonary** [comment]
@nobodyiam 
我按照脚本里面一个一个的执行，还有有问题，去掉探针后可以configure容器可以启动了，但是出现了admin日志中出现`org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set`异常

**Comment by Jacksonary** [comment]
`standard_init_linux.go:185: exec user process caused "no such file or directory"`这个问题解决了，是因为编码问题导致的

**Comment by kinbod** [comment]
那估计是应用的问题
