### ISSUE TITLE
多环境yaml配置文件，解析错误

### ISSUE THREAD

**Issue by 308299160** [ctripcorp/apollo#2130]
client版本：1.3.0
当我一个配置文件中，同时包含了两个环境的配置时，比如一个dev，一个test。
文件样式大致如下：
spring:
  profiles: dev
  
swagger:
  enable: true
  ....
  ....
---
spring:
  profiles: test

swagger:
  enable: false

---

spring:
  profiles:
    active: dev

正常来说，应该是激活dev,生效配置为swagger.enable=true，但是，实际生效配置为test,swagger.enable=false。
原因是YamlParser在解析融合配置时，后面test的配置覆盖了前面的配置

**Comment by nobodyiam** [comment]
配置按环境分开吧

**Comment by 308299160** [comment]
> 配置按环境分开吧

目前是这样解决的。我只是觉得这应该算是一个小bug，可以修复

**Comment by nobodyiam** [comment]
恩，可以参照spring的做法来实现一下，如果能contribute一下就更好了~
