### ISSUE TITLE
使用docker方式部署报错

### ISSUE THREAD

**Issue by caopengfei** [ctripcorp/apollo#2131]
[root@web1 apollo]# docker-compose up
Creating network "apollo_default" with the default driver
Pulling apollo-dbdata (alpine:latest)...
latest: Pulling from library/alpine
bdf0201b3a05: Pull complete
Digest: sha256:28ef97b8686a0b5399129e9b763d5b7e5ff03576aa5580d6f4182a49c5fe1913
Status: Downloaded newer image for alpine:latest
Pulling apollo-db (mysql:5.7)...
5.7: Pulling from library/mysql
27833a3ba0a5: Pull complete
864c283b3c4b: Pull complete
cea281b2278b: Pull complete
8f856c14f5af: Pull complete
9c4f38c23b6f: Pull complete
1b810e1751b3: Pull complete
5479aaef3d30: Pull complete
1d924ec3d520: Pull complete
1ab7ae63ac60: Pull complete
08aa5f3680e9: Pull complete
a832d0a0972a: Pull complete
Digest: sha256:dba5fed182e64064b688ccd22b2f9cad4ee88608c82f8cff21e17bab8da72b81
Status: Downloaded newer image for mysql:5.7
Pulling apollo-quick-start (nobodyiam/apollo-quick-start:latest)...
latest: Pulling from nobodyiam/apollo-quick-start
6c40cc604d8e: Pull complete
e78b80385239: Pull complete
f41fe1b6eee3: Pull complete
f81fe3873b24: Pull complete
6ee996dcbacb: Pull complete
bf515fdbd069: Pull complete
5e4fe6eab272: Pull complete
7d18aca46713: Pull complete
cdbb4cafaa13: Pull complete
Creating apollo-dbdata ... done
Creating apollo-db ... done
Creating apollo-quick-start ... done
Creating apollo-db ... 
Creating apollo-quick-start ... 
Attaching to apollo-dbdata, apollo-db, apollo-quick-start
apollo-dbdata exited with code 0
apollo-db             | Initializing database
apollo-db             | 2019-04-12T01:27:37.900253Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
apollo-quick-start    | ==== starting service ====
apollo-quick-start    | Service logging file is ./service/apollo-service.log
apollo-db             | 2019-04-12T01:27:42.202871Z 0 [Warning] InnoDB: New log files created, LSN=45790
apollo-quick-start    | Started [49]
apollo-db             | 2019-04-12T01:27:42.542550Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
apollo-db             | 2019-04-12T01:27:42.618865Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: 2afda912-5cc2-11e9-b5fc-0242ac140003.
apollo-db             | 2019-04-12T01:27:42.668129Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
apollo-db             | 2019-04-12T01:27:42.668468Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
apollo-db             | 2019-04-12T01:27:43.910537Z 1 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:27:43.910557Z 1 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:27:43.910563Z 1 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:27:43.910574Z 1 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:27:43.910577Z 1 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:27:43.910584Z 1 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:27:43.910602Z 1 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:27:43.910609Z 1 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
apollo-db             | Database initialized
apollo-db             | Initializing certificates
apollo-db             | Generating a RSA private key
apollo-db             | .....................+++++
apollo-db             | ......+++++
apollo-db             | unable to write 'random state'
apollo-db             | writing new private key to 'ca-key.pem'
apollo-db             | -----
apollo-db             | Generating a RSA private key
apollo-db             | .......................................+++++
apollo-db             | ............................+++++
apollo-db             | unable to write 'random state'
apollo-db             | writing new private key to 'server-key.pem'
apollo-db             | -----
apollo-db             | Generating a RSA private key
apollo-db             | ...+++++
apollo-db             | .............................+++++
apollo-db             | unable to write 'random state'
apollo-db             | writing new private key to 'client-key.pem'
apollo-db             | -----
apollo-db             | Certificates initialized
apollo-db             | MySQL init process in progress...
apollo-db             | MySQL init process in progress...
apollo-db             | 2019-04-12T01:28:04.128245Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
apollo-db             | 2019-04-12T01:28:05.676034Z 0 [Note] mysqld (mysqld 5.7.25) starting as process 90 ...
apollo-db             | 2019-04-12T01:28:07.015980Z 0 [Note] InnoDB: PUNCH HOLE support available
apollo-db             | 2019-04-12T01:28:07.016020Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
apollo-db             | 2019-04-12T01:28:07.016024Z 0 [Note] InnoDB: Uses event mutexes
apollo-db             | 2019-04-12T01:28:07.016027Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
apollo-db             | 2019-04-12T01:28:07.016029Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
apollo-db             | 2019-04-12T01:28:07.016032Z 0 [Note] InnoDB: Using Linux native AIO
apollo-db             | 2019-04-12T01:28:07.016360Z 0 [Note] InnoDB: Number of pools: 1
apollo-db             | 2019-04-12T01:28:07.016533Z 0 [Note] InnoDB: Using CPU crc32 instructions
apollo-db             | 2019-04-12T01:28:07.018554Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
apollo-db             | 2019-04-12T01:28:07.027454Z 0 [Note] InnoDB: Completed initialization of buffer pool
apollo-db             | 2019-04-12T01:28:07.042439Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
apollo-db             | 2019-04-12T01:28:07.508157Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
apollo-db             | MySQL init process in progress...
apollo-db             | 2019-04-12T01:28:08.770585Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
apollo-db             | 2019-04-12T01:28:08.770700Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
apollo-db             | 2019-04-12T01:28:09.215161Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
apollo-db             | 2019-04-12T01:28:09.322701Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
apollo-db             | 2019-04-12T01:28:09.322722Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
apollo-db             | 2019-04-12T01:28:09.323757Z 0 [Note] InnoDB: Waiting for purge to start
apollo-db             | 2019-04-12T01:28:09.373836Z 0 [Note] InnoDB: Waiting for purge to start
apollo-db             | 2019-04-12T01:28:09.423955Z 0 [Note] InnoDB: Waiting for purge to start
apollo-db             | 2019-04-12T01:28:09.474110Z 0 [Note] InnoDB: 5.7.25 started; log sequence number 2524141
apollo-db             | 2019-04-12T01:28:09.474304Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
apollo-db             | 2019-04-12T01:28:09.478494Z 0 [Note] Plugin 'FEDERATED' is disabled.
apollo-db             | MySQL init process in progress...
apollo-db             | 2019-04-12T01:28:10.643117Z 0 [Note] InnoDB: Buffer pool(s) load completed at 190412  9:28:10
apollo-db             | 2019-04-12T01:28:10.813985Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
apollo-db             | MySQL init process in progress...
apollo-db             | 2019-04-12T01:28:10.922078Z 0 [Warning] CA certificate ca.pem is self signed.
apollo-db             | 2019-04-12T01:28:10.939995Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
apollo-db             | 2019-04-12T01:28:11.320836Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:28:11.320876Z 0 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:28:11.320883Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:28:11.321027Z 0 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:28:11.321038Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:28:11.321174Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:28:11.606184Z 0 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:28:11.606204Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:28:13.608035Z 0 [Note] Event Scheduler: Loaded 0 events
apollo-db             | 2019-04-12T01:28:13.608258Z 0 [Note] mysqld: ready for connections.
apollo-db             | Version: '5.7.25'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server (GPL)
apollo-db             | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
apollo-db             | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
apollo-db             | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
apollo-db             | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
apollo-db             | 2019-04-12T01:28:24.807868Z 4 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:28:24.807896Z 4 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:28:24.807902Z 4 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:28:24.807917Z 4 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:28:24.807920Z 4 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:28:24.807941Z 4 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:28:24.807980Z 4 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:28:24.807987Z 4 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 
apollo-db             | 2019-04-12T01:28:24.841699Z 0 [Note] Giving 0 client threads a chance to die gracefully
apollo-db             | 2019-04-12T01:28:24.841718Z 0 [Note] Shutting down slave threads
apollo-db             | 2019-04-12T01:28:24.847967Z 0 [Note] Forcefully disconnecting 0 remaining clients
apollo-db             | 2019-04-12T01:28:24.847990Z 0 [Note] Event Scheduler: Purging the queue. 0 events
apollo-db             | 2019-04-12T01:28:24.848054Z 0 [Note] Binlog end
apollo-db             | 2019-04-12T01:28:24.848406Z 0 [Note] Shutting down plugin 'ngram'
apollo-db             | 2019-04-12T01:28:24.848417Z 0 [Note] Shutting down plugin 'partition'
apollo-db             | 2019-04-12T01:28:24.848420Z 0 [Note] Shutting down plugin 'BLACKHOLE'
apollo-db             | 2019-04-12T01:28:24.848422Z 0 [Note] Shutting down plugin 'ARCHIVE'
apollo-db             | 2019-04-12T01:28:24.848424Z 0 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
apollo-db             | 2019-04-12T01:28:24.848439Z 0 [Note] Shutting down plugin 'MRG_MYISAM'
apollo-db             | 2019-04-12T01:28:24.848443Z 0 [Note] Shutting down plugin 'MyISAM'
apollo-db             | 2019-04-12T01:28:24.848454Z 0 [Note] Shutting down plugin 'INNODB_SYS_VIRTUAL'
apollo-db             | 2019-04-12T01:28:24.848457Z 0 [Note] Shutting down plugin 'INNODB_SYS_DATAFILES'
apollo-db             | 2019-04-12T01:28:24.848458Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESPACES'
apollo-db             | 2019-04-12T01:28:24.848460Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN_COLS'
apollo-db             | 2019-04-12T01:28:24.848462Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN'
apollo-db             | 2019-04-12T01:28:24.848463Z 0 [Note] Shutting down plugin 'INNODB_SYS_FIELDS'
apollo-db             | 2019-04-12T01:28:24.848465Z 0 [Note] Shutting down plugin 'INNODB_SYS_COLUMNS'
apollo-db             | 2019-04-12T01:28:24.848467Z 0 [Note] Shutting down plugin 'INNODB_SYS_INDEXES'
apollo-db             | 2019-04-12T01:28:24.848468Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESTATS'
apollo-db             | 2019-04-12T01:28:24.848470Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLES'
apollo-db             | 2019-04-12T01:28:24.848471Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
apollo-db             | 2019-04-12T01:28:24.848473Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
apollo-db             | 2019-04-12T01:28:24.848475Z 0 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
apollo-db             | 2019-04-12T01:28:24.848477Z 0 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
apollo-db             | 2019-04-12T01:28:24.848479Z 0 [Note] Shutting down plugin 'INNODB_FT_DELETED'
apollo-db             | 2019-04-12T01:28:24.848480Z 0 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
apollo-db             | 2019-04-12T01:28:24.848482Z 0 [Note] Shutting down plugin 'INNODB_METRICS'
apollo-db             | 2019-04-12T01:28:24.848483Z 0 [Note] Shutting down plugin 'INNODB_TEMP_TABLE_INFO'
apollo-db             | 2019-04-12T01:28:24.848485Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
apollo-db             | 2019-04-12T01:28:24.848487Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
apollo-db             | 2019-04-12T01:28:24.848488Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
apollo-db             | 2019-04-12T01:28:24.848490Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
apollo-db             | 2019-04-12T01:28:24.848492Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
apollo-db             | 2019-04-12T01:28:24.848493Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
apollo-db             | 2019-04-12T01:28:24.848495Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM'
apollo-db             | 2019-04-12T01:28:24.848497Z 0 [Note] Shutting down plugin 'INNODB_CMP_RESET'
apollo-db             | 2019-04-12T01:28:24.848498Z 0 [Note] Shutting down plugin 'INNODB_CMP'
apollo-db             | 2019-04-12T01:28:24.848500Z 0 [Note] Shutting down plugin 'INNODB_LOCK_WAITS'
apollo-db             | 2019-04-12T01:28:24.848502Z 0 [Note] Shutting down plugin 'INNODB_LOCKS'
apollo-db             | 2019-04-12T01:28:24.848503Z 0 [Note] Shutting down plugin 'INNODB_TRX'
apollo-db             | 2019-04-12T01:28:24.848505Z 0 [Note] Shutting down plugin 'InnoDB'
apollo-db             | 2019-04-12T01:28:24.848555Z 0 [Note] InnoDB: FTS optimize thread exiting.
apollo-db             | 2019-04-12T01:28:24.848641Z 0 [Note] InnoDB: Starting shutdown...
apollo-db             | 2019-04-12T01:28:24.948778Z 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
apollo-db             | 2019-04-12T01:28:25.053146Z 0 [Note] InnoDB: Buffer pool(s) dump completed at 190412  9:28:25
apollo-db             | 2019-04-12T01:28:26.558723Z 0 [Note] InnoDB: Shutdown completed; log sequence number 12358813
apollo-db             | 2019-04-12T01:28:26.559012Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
apollo-db             | 2019-04-12T01:28:26.559022Z 0 [Note] Shutting down plugin 'MEMORY'
apollo-db             | 2019-04-12T01:28:26.559037Z 0 [Note] Shutting down plugin 'CSV'
apollo-db             | 2019-04-12T01:28:26.559045Z 0 [Note] Shutting down plugin 'sha256_password'
apollo-db             | 2019-04-12T01:28:26.559048Z 0 [Note] Shutting down plugin 'mysql_native_password'
apollo-db             | 2019-04-12T01:28:26.579115Z 0 [Note] Shutting down plugin 'binlog'
apollo-db             | 2019-04-12T01:28:26.596783Z 0 [Note] mysqld: Shutdown complete
apollo-db             | 
apollo-db             | 
apollo-db             | MySQL init process done. Ready for start up.
apollo-db             | 
apollo-db             | 2019-04-12T01:28:27.207947Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
apollo-db             | 2019-04-12T01:28:27.209379Z 0 [Note] mysqld (mysqld 5.7.25) starting as process 1 ...
apollo-db             | 2019-04-12T01:28:27.238999Z 0 [Note] InnoDB: PUNCH HOLE support available
apollo-db             | 2019-04-12T01:28:27.239019Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
apollo-db             | 2019-04-12T01:28:27.239022Z 0 [Note] InnoDB: Uses event mutexes
apollo-db             | 2019-04-12T01:28:27.239025Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
apollo-db             | 2019-04-12T01:28:27.239027Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
apollo-db             | 2019-04-12T01:28:27.239029Z 0 [Note] InnoDB: Using Linux native AIO
apollo-db             | 2019-04-12T01:28:27.239214Z 0 [Note] InnoDB: Number of pools: 1
apollo-db             | 2019-04-12T01:28:27.239307Z 0 [Note] InnoDB: Using CPU crc32 instructions
apollo-db             | 2019-04-12T01:28:27.240692Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
apollo-db             | 2019-04-12T01:28:27.246306Z 0 [Note] InnoDB: Completed initialization of buffer pool
apollo-db             | 2019-04-12T01:28:27.248061Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
apollo-db             | 2019-04-12T01:28:27.276516Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
apollo-db             | 2019-04-12T01:28:27.416529Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
apollo-db             | 2019-04-12T01:28:27.416621Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
apollo-db             | 2019-04-12T01:28:27.498735Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
apollo-db             | 2019-04-12T01:28:27.499327Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
apollo-db             | 2019-04-12T01:28:27.499337Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
apollo-db             | 2019-04-12T01:28:27.499667Z 0 [Note] InnoDB: Waiting for purge to start
apollo-db             | 2019-04-12T01:28:27.549815Z 0 [Note] InnoDB: 5.7.25 started; log sequence number 12358813
apollo-db             | 2019-04-12T01:28:27.550101Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
apollo-db             | 2019-04-12T01:28:27.551372Z 0 [Note] Plugin 'FEDERATED' is disabled.
apollo-db             | 2019-04-12T01:28:27.562023Z 0 [Note] InnoDB: Buffer pool(s) load completed at 190412  9:28:27
apollo-db             | 2019-04-12T01:28:27.619240Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
apollo-db             | 2019-04-12T01:28:27.619463Z 0 [Warning] CA certificate ca.pem is self signed.
apollo-db             | 2019-04-12T01:28:27.620835Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
apollo-db             | 2019-04-12T01:28:27.620900Z 0 [Note] IPv6 is available.
apollo-db             | 2019-04-12T01:28:27.620910Z 0 [Note]   - '::' resolves to '::';
apollo-db             | 2019-04-12T01:28:27.620935Z 0 [Note] Server socket created on IP: '::'.
apollo-db             | 2019-04-12T01:28:27.622988Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
apollo-db             | 2019-04-12T01:28:27.637581Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:28:27.637619Z 0 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:28:27.637626Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:28:27.637643Z 0 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:28:27.637647Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:28:27.637655Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:28:27.640113Z 0 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:28:27.640129Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
apollo-db             | 2019-04-12T01:28:27.748882Z 0 [Note] Event Scheduler: Loaded 0 events
apollo-db             | 2019-04-12T01:28:27.749020Z 0 [Note] mysqld: ready for connections.
apollo-db             | Version: '5.7.25'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
apollo-db             | 2019-04-12T01:28:36.782098Z 2 [Note] Unknown database 'ApolloConfigDB'
apollo-db             | 2019-04-12T01:28:37.853230Z 3 [Note] Unknown database 'ApolloConfigDB'
apollo-db             | 2019-04-12T01:28:43.026070Z 4 [Note] Unknown database 'ApolloConfigDB'
apollo-quick-start    | Waiting for config service startup........................
apollo-quick-start    | Config service failed to start in 120 seconds! Please check ./service/apollo-service.log for more information.
apollo-quick-start exited with code 1

**Comment by xiamaoxuan** [comment]
什么原因
