### ISSUE TITLE
config-service-url中ip变化导致读取不到信息

### ISSUE THREAD

**Issue by sendreams** [ctripcorp/apollo#2132]
我用spring boot，在application.properties配置文件做如下配置
`#Apollo
app.id=avic-server
apollo.meta=http://172.17.60.217:8080
apollo.bootstrap.enabled = true
apollo.bootstrap.namespaces = application`

config-service-url地址为172.17.60.217，可是为什么程序启动时，地址莫名其妙的变成了172.18.0.3，导致无法获取配置信息。
下面为spring boot输出的日志。

:: Spring Boot ::        (v2.0.3.RELEASE)

09:35:37.251 [main] INFO  c.c.f.f.i.p.DefaultApplicationProvider - App ID is set to avic-server by app.id property from System Property
09:35:37.255 [main] INFO  c.c.f.f.i.p.DefaultServerProvider - Environment is set to [DEV] by OS env variable 'ENV'.
09:35:37.309 [main] INFO  c.c.f.a.i.DefaultMetaServerProvider - Located meta services from apollo.meta configuration: http://172.17.60.217:8080!
09:35:37.315 [main] INFO  c.c.f.apollo.core.MetaDomainConsts - Located meta server address http://172.17.60.217:8080 for env DEV from com.ctrip.framework.apollo.internals.DefaultMetaServerProvider
09:35:38.971 [main] WARN  c.c.f.a.i.RemoteConfigRepository - Load config failed, will retry in 1 SECONDS. appId: avic-server, cluster: default, namespaces: application
09:35:40.973 [main] WARN  c.c.f.a.i.AbstractConfigRepository - Sync config failed, will retry. Repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository, reason: Load Apollo Config failed - appId: avic-server, cluster: default, namespace: application, url: http://172.18.0.3:8080/configs/avic-server/default/application?ip=192.168.1.237 [Cause: Could not complete get operation [Cause: connect timed out]]
09:35:41.998 [main] WARN  c.c.f.a.i.RemoteConfigRepository - Load config failed, will retry in 1 SECONDS. appId: avic-server, cluster: default, namespaces: application
09:35:43.989 [Apollo-RemoteConfigLongPollService-1] WARN  c.c.f.a.i.RemoteConfigLongPollService - Long polling failed, will retry in 1 seconds. appId: avic-server, cluster: default, namespaces: application, long polling url: http://172.18.0.3:8080/notifications/v2?cluster=default&appId=avic-server&ip=192.168.1.237&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A-1%7D%5D, reason: Could not complete get operation [Cause: connect timed out]
09:35:44.001 [main] WARN  c.c.f.a.i.LocalFileConfigRepository - Sync config from upstream repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository failed, reason: Load Apollo Config failed - appId: avic-server, cluster: default, namespace: application, url: http://172.18.0.3:8080/configs/avic-server/default/application?ip=192.168.1.237 [Cause: Could not complete get operation [Cause: connect timed out]]
09:35:45.003 [main] WARN  c.c.f.a.i.RemoteConfigRepository - Load config failed, will retry in 1 SECONDS. appId: avic-server, cluster: default, namespaces: application
09:35:45.990 [Apollo-RemoteConfigLongPollService-1] WARN  c.c.f.a.i.RemoteConfigLongPollService - Long polling failed, will retry in 2 seconds. appId: avic-server, cluster: default, namespaces: application, long polling url: http://172.18.0.3:8080/notifications/v2?cluster=default&appId=avic-server&ip=192.168.1.237&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A-1%7D%5D, reason: Could not complete get operation [Cause: connect timed out]
09:35:47.004 [main] WARN  c.c.f.a.i.LocalFileConfigRepository - Sync config from upstream repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository failed, reason: Load Apollo Config failed - appId: avic-server, cluster: default, namespace: application, url: http://172.18.0.3:8080/configs/avic-server/default/application?ip=192.168.1.237 [Cause: Could not complete get operation [Cause: connect timed out]]
09:35:47.005 [main] WARN  c.c.f.a.i.AbstractConfigRepository - Sync config failed, will retry. Repository class com.ctrip.framework.apollo.internals.LocalFileConfigRepository, reason: Load config from local config failed! [Cause: Cannot read from local cache file C:\opt\data\avic-server\config-cache\avic-server+default+application.properties]
09:35:48.007 [main] WARN  c.c.f.a.i.RemoteConfigRepository - Load config failed, will retry in 1 SECONDS. appId: avic-server, cluster: default, namespaces: application

**Comment by sendreams** [comment]
`<dependency>
		    <groupId>com.ctrip.framework.apollo</groupId>
		    <artifactId>apollo-client</artifactId>
		    <version>1.3.0</version>
		</dependency>`

1.2.0和1.3.0都试过，结果一样，百思不解。

**Comment by sendreams** [comment]
我大概知道原因了，我是用docker部署的，返回的是docker镜像中的ip地址。
<img width="901" alt="Snap1" src="https://user-images.githubusercontent.com/4160051/56006625-2eee4700-5d08-11e9-9193-d9655032294e.png">

**Comment by sendreams** [comment]
如果用镜像的方式部署，客户端岂不是读取不到配置信息？

**Comment by kinbod** [comment]
就是，我也是遇到这个问题了，这个就需要过滤注册IP，但是至于如何过滤就不知道了。

**Comment by kinbod** [comment]
你这个问题现在解决了没有呢？

**Comment by sendreams** [comment]
> 你这个问题现在解决了没有呢？

没，不用docker方式了，就用传统部署方式了。

**Comment by nobodyiam** [comment]
参考一下[网络策略](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#14%E7%BD%91%E7%BB%9C%E7%AD%96%E7%95%A5)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by boboweiqi** [comment]
1.docker方式部署，修改尝试修改docker-compose.yaml的映射端口配置(原8080改为8060)，如下：
![image](https://user-images.githubusercontent.com/23556927/173732917-d24533a6-20bf-4f1f-8f9e-f4f3e8ba2335.png)

2.参考[跳过Apollo Meta Server服务发现](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#1222-%E8%B7%B3%E8%BF%87apollo-meta-server%E6%9C%8D%E5%8A%A1%E5%8F%91%E7%8E%B0)
如idea中配置VM:-Dapollo.configService=http://localhost:8060,启动

**Comment by boboweiqi** [comment]
1.docker方式部署，修改尝试修改docker-compose.yaml的映射端口配置(原8080改为8060)，如下：
![image](https://user-images.githubusercontent.com/23556927/173732917-d24533a6-20bf-4f1f-8f9e-f4f3e8ba2335.png)

2.参考[跳过Apollo Meta Server服务发现](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#1222-%E8%B7%B3%E8%BF%87apollo-meta-server%E6%9C%8D%E5%8A%A1%E5%8F%91%E7%8E%B0)
如idea中配置VM:-Dapollo.configService=http://localhost:8060,启动
