### ISSUE TITLE
k8s部署apollo之后外部应用无法访问配置中心

### ISSUE THREAD

**Issue by kinbod** [ctripcorp/apollo#2133]
k8s安装好apollo集群后使用对外的30002端口访问config-server的时候返回的服务列表[{"appName":"APOLLO-CONFIGSERVICE","instanceId":"statefulset-apollo-config-server-dev-1.service-apollo-meta-server-dev.sre.svc.cluster.local:apollo-configservice:8080","homepageUrl":"http://10.42.4.39:8080/"},{"appName":"APOLLO-CONFIGSERVICE","instanceId":"statefulset-apollo-config-server-dev-0.service-apollo-meta-server-dev.sre.svc.cluster.local:apollo-configservice:8080","homepageUrl":"http://10.42.5.25:8080/"},{"appName":"APOLLO-CONFIGSERVICE","instanceId":"statefulset-apollo-config-server-dev-2.service-apollo-meta-server-dev.sre.svc.cluster.local:apollo-configservice:8080","homepageUrl":"http://10.42.2.28:8080/"}] 

然后报错：
http://10.42.5.25:8080/notifications/v2?cluster=default&appId=xboot&ip=192.168.80.1&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A-1%7D%5D, reason: Could not complete get operation [Cause: connect timed out] 

10.42.5.25这些IP都是clusterIP，外部无法访问

**Comment by nobodyiam** [comment]
参考一下[网络策略](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#14%E7%BD%91%E7%BB%9C%E7%AD%96%E7%95%A5)

**Comment by kinbod** [comment]
好的，问题已经解决了，谢谢
