### ISSUE TITLE
Apollo实现无配置化

### ISSUE THREAD

**Issue by standup-jb** [ctripcorp/apollo#2136]
请教一下，想用apollo把所有的配置文件都替换掉。实现一次war包，多环境运行。但是现在发现log4j的每个环境目录不一样。如果把log4j的配置放到apollo里面，那在项目启动apollo-client将配置正确获取前，这段时间的日志就没法正确的保存。请问有什么思路可以解决这个问题吗？

**Comment by nobodyiam** [comment]
考虑使用静态配置？比如通过环境变量传入？

**Comment by standup-jb** [comment]
> 考虑使用静态配置？比如通过环境变量传入？
你好。不好意思。你说的我有点没看懂，我猜测了一下你的意思。
1. 将log4j.appender.file.File 这个变量通过环境变量传入。不同的环境传入不同的值。
2. 将多个环境的log4j.properties文件打入war包。最后传入环境变量Env=TEST or Env= PRO。通过环境变量来选择使用那个log4j.properties。
不知道您推荐的方法是使用1 还是使用2.
感觉1和2 都不是完美的方法，都可能存在一些问题。问题如下
1. 如果使用1，每个项目都得配置一个环境环境。每个项目的环境变量还不相同。这样很麻烦。
2. 如果使用2，每个项目，war里面就等于有多个环境的配置。为了实现一次打包。反而引入了更多的配置。

**Comment by nobodyiam** [comment]
静态配置比如通过maven profile的方式，对不同的环境打包时传入不同的profile，然后把对应的文件打进包里

**Comment by standup-jb** [comment]
> 静态配置比如通过maven profile的方式，对不同的环境打包时传入不同的profile，然后把对应的文件打进包里

大佬。我们的目标就是做到一次打包，多环境运行。所以不同环境打包这个问题就不行了。
现在我已经解决了这个问题了。自己写了一个Log4jListener 放在web.xml里面org.springframework.web.context.ContextLoaderListener 之前。tomcat 的加载顺序是 listener->filter->servlet。我自己写的log4jListener将log4j配置从配置中心拿到。现在已经可以做到项目里面一个配置都没有了。而且一次打包。多个环境运行。

**Comment by standup-jb** [comment]
感谢大佬的解惑。

**Comment by nobodyiam** [comment]
这个思路挺好的

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
