### ISSUE TITLE
请问怎么改apollo管理账号密码啊 默认是apollo/admin

### ISSUE THREAD

**Issue by catterlai** [ctripcorp/apollo#2137]
请问怎么改apollo管理员账号密码啊 默认是apollo/admin

**Comment by nobodyiam** [comment]
如果使用的是默认的登录方式，那么超级管理员登录系统后打开`管理员工具 - 用户管理`，输入用户名和密码后即可修改用户密码，建议同时修改超级管理员apollo的密码。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by kikupotter** [comment]
@nobodyiam 宋老师，apollo的管理员账号(apollo)密码给人改错了，现在无法登陆。针对这种意外的情况，还有什么办法重置apollo密码吗？

**Comment by nobodyiam** [comment]
@kikupotter 可以直接修改ApolloPortalDB.Users表中的数据，初始密码可以从apollo安装脚本中获取

**Comment by 0xCryptoZen** [comment]
> [@nobodyiam](https://github.com/nobodyiam) 宋老师，apollo的管理员账号(apollo)密码给人改错了，现在无法登陆。针对这种意外的情况，还有什么办法重置apollo密码吗？

登录到Apollo的数据库（通常是MySQL）

sql-- 连接到ApolloPortalDB数据库
use ApolloPortalDB;

-- 查看用户表结构
desc Users;

-- 找到apollo管理员账户
select * from Users where Username = 'apollo';

重置密码

sql-- 将密码重置为 "admin"（加密后的值）
UPDATE Users SET Password = '$2a$10$7r20uS.BQ9uBpf3Baj3uQOZvMVvB1RN3PYoKE94gtz2.WAOuiiwXS' 
WHERE Username = 'apollo';
这会将密码重置为 admin
