### ISSUE TITLE
有没有meta service的使用文档

### ISSUE THREAD

**Issue by DCaInIao** [ctripcorp/apollo#2138]
不是说把eureka的服务发现与注册封装成了mete service吗，我怎么用啊，没有文档，到头来我还是使用原生的eureka接口？

**Comment by nobodyiam** [comment]
对apollo的客户端，它始终是和meta service交互，不会和eureka交互，具体看下[ServiceController](https://github.com/ctripcorp/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/metaservice/controller/ServiceController.java)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
