### ISSUE TITLE
同时编辑导致误发布的BUG

### ISSUE THREAD

**Issue by ladder1984** [ctripcorp/apollo#2141]
同一个namespace，在编辑完成到发布之前，如果有他人编辑此namespace但未发布，会把别人的修改发布并且在发布的预览看不到。

一个复现场景如下：

1. A 打开配置页面;
2. B 打开配置页面;
3. B 添加一个配置, 但不发布;
4. A 在他打开的页面点击发布按钮, 系统提示"配置没有变化", A 继续点击发布, 就会将 B 的配置发布出去.

在DEMO地址106.12.25.204:8070可复现。

**Comment by nobodyiam** [comment]
生产环境建议开启[namespace.lock.switch - 一次发布只能有一个人修改开关，用于发布审核](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#2-namespacelockswitch---%E4%B8%80%E6%AC%A1%E5%8F%91%E5%B8%83%E5%8F%AA%E8%83%BD%E6%9C%89%E4%B8%80%E4%B8%AA%E4%BA%BA%E4%BF%AE%E6%94%B9%E5%BC%80%E5%85%B3%E7%94%A8%E4%BA%8E%E5%8F%91%E5%B8%83%E5%AE%A1%E6%A0%B8)
