### ISSUE TITLE
apollo的@ConfigurationProperties通过@RefreshScope给第三方框架带来的问题

### ISSUE THREAD

**Issue by XiangNick** [ctripcorp/apollo#2145]
由于项目中大量使用到了@ConfigurationProperties的配置，并且使用的注册中心是eurkea，在接入apollo的过程中，需要对@ConfigurationProperties的配置进行动态刷新。注意到github的wiki上提到了该配置的刷新方法——采用EnvironmentChangeEvent或RefreshScope，在apollo的监听事件里refresh该bean。
![image](https://user-images.githubusercontent.com/18380811/56281165-82b0c400-613e-11e9-8a26-ed0721e93636.png)
但是在实际测试中发现，每次在portal中修改有@ConfigurationProperties的配置bean，都会触发eureka的下线再上线操作。

跟进源码发现，
![image](https://user-images.githubusercontent.com/18380811/56281264-c9062300-613e-11e9-90a5-2c1dae0d5695.png)
该方法会抛出含有指定bean名称的RefreshScopeRefreshedEvent的Spring事件。

然而由于eureka也有对该事件的监听，并且eureka并没有判断bean的名称，直接下线再上线服务。
![image](https://user-images.githubusercontent.com/18380811/56281289-d6231200-613e-11e9-8f03-aa9557b28958.png)
这样就导致，标注了@ConfigurationProperties的apollo相关配置，在运行时如果想动态更新，势必会引起如Eureka之类的第三方框架的“刷新”动作。

很多第三方框架都对RefreshScopeRefreshedEvent事件很敏感，比如eureka会重新注册应用，zuul会重新刷新路由表。

那么在使用apollo的过程中，如果使用了@ConfigurationProperties的apollo相关配置，还想在运行时动态刷新，是否就会导致第三方框架的连锁反应呢。还有什么其他方案吗。

**Comment by nobodyiam** [comment]
使用 EnvironmentChangeEvent 这个方案应该不会触发eureka的自动刷新吧

**Comment by XiangNick** [comment]
> 使用 EnvironmentChangeEvent 这个方案应该不会触发eureka的自动刷新吧

好的，EnvironmentChangeEvent 确实可以刷新配置，同时也不会触发第三方框架如zuul、eureka的更新行为。但是需要注意的是，使用EnvironmentChangeEvent的方案的时候，配置类的bean不能标注@RefreshScope的注解，或者要在整个调用链都标注该注解，否则还是会配置不生效。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
