### ISSUE TITLE
SpringBoot SpringApplication.setSources()方法添加xml文件，无法获取Apollo配置

### ISSUE THREAD

**Issue by JarvisZhu** [ctripcorp/apollo#2146]
SpringBoot框架，主启动类上已经添加了@ImportResource("application.xml")，在这个xml中已经引入了Apollo命名空间以及<apollo:config />等。

项目中有这样一个场景：根据某个启动参数来额外加载某个特定的xml文件，我在主启动类中这样写：

> Set set = new HashSet();
set.add("context-111.xml");//根据启动参数选择到的某个特定xml文件
SpringApplication application = new SpringApplication(Application.class);
application.setSources(set);
application.run(args);

在context-111.xml中，有这样的bean配置：
`<bean class="${listener.class}">
    <property name="name" value="${listener.name}" />
</bean>`

经测试，class="${listener.class}"这种写法无法获取到Apollo配置，报ClassNotFoundException，而其它的占位符都能获取到Apollo配置。

所以请教一下，这个问题有什么解决思路？

**Comment by nobodyiam** [comment]
先把listener.class定义到本地文件，然后通过@PropertySource注入spring看看是否可以，怀疑是class不支持占位符

**Comment by JarvisZhu** [comment]
如果直接加载，而不是像上面那样application.setSources(set);  那么class="${listener.class}"没有问题，这个是可以支持的。

**Comment by nobodyiam** [comment]
话说为啥要`application.setSources(set);`，直接`@ImportResource`不满足需求？

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
