### ISSUE TITLE
软件链接的方式启动失败了,不知道哪里出问题了,能帮忙给个思路吗?

### ISSUE THREAD

**Issue by davidclj** [ctripcorp/apollo#2147]
![image](https://user-images.githubusercontent.com/8056826/56348289-b2240700-61f8-11e9-97b4-429f321d2bfa.png)

@nobodyiam 
@nobodyiam

**Comment by nobodyiam** [comment]
有更多日志信息吗？

**Comment by davidclj** [comment]
在apollo-adminservice.conf开头加上一行USE_START_STOP_DAEMON=false 就好了
我的系统是suse
@nobodyiam

**Comment by nobodyiam** [comment]
这个用的是spring boot的启动脚本，之前只在centos上测试过，可能确实和操作系统兼容性有关

**Comment by geek-larry** [comment]
亲测有效，apollo-quick-start安装，报错日志，start-stop-daemon 不支持的命令

start-stop-daemon: unrecognized option '--no-close'
BusyBox v1.27.0 (2017-07-11 11:17:13 CST) multi-call binary.
......
apollo-service.conf/apollo-portal.conf第一行添加
USE_START_STOP_DAEMON=false
