### ISSUE TITLE
支持xml合并功能吗？

### ISSUE THREAD

**Issue by andyyumiao** [ctripcorp/apollo#2149]
namespace支持xml及yaml的配置项合并吗？即使用private namespace替代public namespace部分内容，而且貌似public namespace不支持yaml及xml等格式？

**Comment by nobodyiam** [comment]
`使用private namespace替代public namespace部分内容`，这个是支持的，只要把private namespace的优先级高于public namespace即可

public namespace目前不支持yaml及xml等格式

**Comment by andyyumiao** [comment]
> `使用private namespace替代public namespace部分内容`，这个是支持的，只要把private namespace的优先级高于public namespace即可
> 
> public namespace目前不支持yaml及xml等格式

谢谢回复，也就是说目前不支持yaml及xml内容替换，只支持properties内容替换吧？

**Comment by andyyumiao** [comment]
> `使用private namespace替代public namespace部分内容`，这个是支持的，只要把private namespace的优先级高于public namespace即可
> 
> public namespace目前不支持yaml及xml等格式

另外还想问下，public namespace不支持yaml、xml等的原因是？有特殊考虑吗？

**Comment by nobodyiam** [comment]
public namespace在设计时的主要考虑场景是对于公共配置且会被应用方覆盖的，所以properties格式可能最合适。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
