### ISSUE TITLE
创建公共的namespace后，类似datsource，suagger-ui这些系统自动获取的配置项应该如何从中获取呢，谢谢。

### ISSUE THREAD

**Issue by ForBobo** [ctripcorp/apollo#2151]
我创建了一个公共的namespace，把几个项目都相同的配置剪切了出来，但是公共的namespace里面配置的datasource这些项并不能像获取application里的配置一样自动获取，需要如何解决呢。谢谢。

**Comment by nobodyiam** [comment]
指定对应的namespace即可，具体参考一下Java客户端使用文档

**Comment by ForBobo** [comment]
哈哈，不好意思啊，没有仔细看文档，昨天看过这一章了，说的是要添加配置文件，然后把需要的namespace加进去。可不可以把关于集群，namespace这些配置外置化呢？可以在打包后放到启动脚本中吗？

**Comment by nobodyiam** [comment]
集群支持通过-D参数传入的，namespace如果是spring boot的话也是可以通过外置化的application.properties或-D参数传入的，具体参考一下Java客户端使用文档

**Comment by ForBobo** [comment]
Ok，不胜感激，谢谢

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
