### ISSUE TITLE
k8s下注入APOLLO_META的问题

### ISSUE THREAD

**Issue by jiaxinxuan** [ctripcorp/apollo#2154]
按照文档说明,在env=dev时,应当注入DEV_META=http://xxx,我尝试得到的情况是,注入不生效,改成APOLLO_META=http://xxx生效,请问是不是代码改动后未及时同步更新文档?

**Comment by nobodyiam** [comment]
代码是对的，需要注意的是如果环境信息也是通过system environment注入的话，那么`ENV`也是需要大写的


https://github.com/ctripcorp/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/apollo/core/internals/LegacyMetaServerProvider.java#L24

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
