### ISSUE TITLE
client端获取apollo.meta的SLB地址，只用于服务发现，开墙到具体机器和SLB地址比较繁琐，为何不直接通过SLB拿取配置呢？

### ISSUE THREAD

**Issue by hanyidreamer** [ctripcorp/apollo#2155]
这样减少很多开墙动作

**Comment by hanyidreamer** [comment]
新增机器节点，而且要对接入端通知，开墙需要添加

**Comment by nobodyiam** [comment]
对于中大型公司是不建议通过slb链路走长连接的，这样对slb压力太大，考虑连接数在6位数的情况

不多对于小型公司，你的建议确实是可以的，针对这种，目前的方式可以使用`-Dapollo.configService=http://xxx`来跳过meta server的服务发现

**Comment by hanyidreamer** [comment]
了解原因了，谢谢，主要是apollo和接入方机器扩充都需要通知到接入方开墙，开墙量和通知造成的使用成本有点大。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
