### ISSUE TITLE
使用ENC加密后，在apollo控制台更新数据，重新获取到的是不是最新的

### ISSUE THREAD

**Issue by tqy-github** [ctripcorp/apollo#2156]
结合jasypt-spring-boot实现Apollo中存储加密配置,使用ENC加密后，在apollo控制台更新数据，重新获取到的是不是最新的，但是客户端缓存文件却已经更新了，properties和yml都测试过了，com.ctrip.framework.apollo.Config可以读到更新的加密串

**Comment by nobodyiam** [comment]
方便上传个简单的demo吗？

**Comment by tqy-github** [comment]
场景很简单,只要配置了ENC(密文),Spring客户端启动后,在portal修改ENC(密文2),Spring客户端通过@Value注入的变量无法实时更新,100%重现,经过查看源码,发现在模块apollo-client中AutoUpdateConfigChangeListener类可能点有问题,如截图,ENC密文时永远不会相等,所以忽略了更新spring value.
![image](https://user-images.githubusercontent.com/21071100/56601496-de42ec00-662d-11e9-88ff-53e02bb60c12.png)

**Comment by nobodyiam** [comment]
看上去和 #2162 相关

**Comment by nobodyiam** [comment]
Fixed via [PR 2173](https://github.com/ctripcorp/apollo/pull/2173)

**Comment by tqy-github** [comment]
Thank you!

**Comment by tqy-github** [comment]
The client library of maven mvnrepository.com is still old. When will it be updated ?

**Comment by tqy-github** [comment]
@nobodyiam The client library of maven mvnrepository.com is still old. When will it be updated ?

**Comment by tqy-github** [comment]
@nobodyiam The client library 1.3.0 of maven mvnrepository.com is still old. When will it be updated ?

**Comment by tqy-github** [comment]
@nobodyiam The client library (apollo-cllient-1.3.0.jar) of maven repository is still old. When will it be updated ?

**Comment by nobodyiam** [comment]
Early May

**Comment by nobodyiam** [comment]
Early May

**Comment by denghuichao** [comment]
> 结合jasypt-spring-boot实现Apollo中存储加密配置,使用ENC加密后，在apollo控制台更新数据，重新获取到的是不是最新的，但是客户端缓存文件却已经更新了，properties和yml都测试过了，com.ctrip.framework.apollo.Config可以读到更新的加密串

请问怎么实现jasypt加密配置值？不是加密项目配置文件
