### ISSUE TITLE
集成springboot-email，出现JavaMailSender无法注入的问题。

### ISSUE THREAD

**Issue by CoolJacks** [ctripcorp/apollo#2157]

**Comment by nobodyiam** [comment]
这个似乎和apollo本身没啥关系？

**Comment by CoolJacks** [comment]
新建一个项目引入spring-boot-starter-mail正常启动，使用apollo下载下来的配置文件出现 找不到注入的Bean  nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.mail.javamail.JavaMailSender' available

**Comment by CoolJacks** [comment]
bootstrap阶段注入可以了
