### ISSUE TITLE
Given final block not properly padded

### ISSUE THREAD

**Issue by spenxu** [ctripcorp/apollo#2160]
apollo 中配置经过对称加密的字符串会报错，比如配置的值为：
EncryptXnHILxq2dFQ=

就会报错

**Comment by nobodyiam** [comment]
麻烦提供一下重现步骤，我本地测试没有这个问题

![image](https://user-images.githubusercontent.com/837658/56817238-c8c10280-6877-11e9-8e50-83eed3891c42.png)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
