### ISSUE TITLE
是否可以将Eureka替换成Zookeeper?

### ISSUE THREAD

**Issue by liuxg-github** [ctripcorp/apollo#2161]
各位大神，是否可以将Eureka替换为Zookeeper？有什么需要注意的地方？谢谢。

**Comment by sunqiangwei** [comment]
我们公司，将Apollo容器化部署的时候，把Eureka的功能给去掉了，直接使用k8s的服务注册与发现服务，至于将eureka替换成zookeeper，估计也不难吧

**Comment by pandalin** [comment]
> 我们公司，将Apollo容器化部署的时候，把Eureka的功能给去掉了，直接使用k8s的服务注册与发现服务，至于将eureka替换成zookeeper，估计也不难吧

你好，这块能说下是如何做的吗
