### ISSUE TITLE
apollo跟jasypt-spring-boot-2.1.0.jar不兼容

### ISSUE THREAD

**Issue by XiangNick** [ctripcorp/apollo#2162]
场景：同样的配置，两个工程。工程A无jasypt-spring-boot-2.1.0.jar依赖，工程B有。结果普通的Spring Placeholder配置，远程修改后。工程A可实时刷新，工程B不行。

原因：apollo在启动时，在PropertySourcesProcessor里，特意将自己的CompositePropertySource放在最前面，以确保在配置更新时能从environment拿到最新的配置跟远程服务通知的配置比对。在com.ctrip.framework.apollo.spring.property.AutoUpdateConfigChangeListener#shouldTriggerAutoUpdate方法中，如果从environment里拿到的配置跟远程通知的配置不同，则就算接收到了远程的通知，也不更新配置。

而jasypt-spring-boot这个jar，是在springboot工程中常用的加密敏感配置如数据库配置的jar。而jasyptspringboot的EncryptableEnumerablePropertySourceWrapper实现了PropertySource接口并代理了默认的CompositePropertySource，他的getProperty方法，走到的是com.ulisesbocchio.jasyptspringboot.caching.CachingDelegateEncryptablePropertySource的getProperty方法，是直接从一个ConcurrentMapCache的缓存中读取配置。

这样就导致在接入apollo的客户端工程里，如果引入了jasypt-spring-boot，在org.springframework.core.env.PropertySourcesPropertyResolver#getProperty方法中，由于jasypt代理了默认apollo使用的CompositePropertySource，并且将启动时的配置存入缓存，这样每次接收到远程配置变更通知时，jasypt的EncryptableEnumerablePropertySourceWrapper都会从ConcurrentMapCache的缓存中读取配置，而非从CompositePropertySource里实时读取配置，这样就会导致引入了jasypt-spring-boot的apollo客户端，无法实时更新配置。

**Comment by tonyd1989** [comment]
我这边也发现了这个问题，加入jasypt-spring-boot-2.1.0.jar后，更新配置不生效，查询源码，应该是同样的原因

**Comment by nobodyiam** [comment]
@XiangNick 

看了一下jasypt-spring-boot 2.1.0确实有这个问题，建议使用1.16版本，可以参考apollo-use-cases中的[spring-boot-encrypt](https://github.com/ctripcorp/apollo-use-cases/tree/master/spring-boot-encrypt)

**Comment by wujinqing** [comment]
下面是我的一种解决方案：
1.CachingDelegateEncryptablePropertySource自带了一个refresh()可以清理缓存。
2.参考jaspyt自带的com.ulisesbocchio.jasyptspringboot.caching.RefreshScopeRefreshedEventListener刷新缓存的方案。

**Comment by wujinqing** [comment]
3.我自己写了一个类似的类：
public class JaspytRefreshScopeRefreshedEventListener {
    private final ConfigurableEnvironment environment;
    private final EncryptablePropertySourceConverter converter;

    public JaspytRefreshScopeRefreshedEventListener(ConfigurableEnvironment environment, EncryptablePropertySourceConverter converter) {
        this.environment = environment;
        this.converter = converter;
    }

    public void refresh() {
        refreshCachedProperties();
        decorateNewSources();
    }

    private void decorateNewSources() {
        MutablePropertySources propSources = environment.getPropertySources();
        converter.convertPropertySources(propSources);
    }

    private void refreshCachedProperties() {
        PropertySources propertySources = environment.getPropertySources();
        propertySources.forEach(this::refreshPropertySource);
    }

    @SuppressWarnings("rawtypes")
    private void refreshPropertySource(PropertySource<?> propertySource) {
        if (propertySource instanceof CompositePropertySource) {
            CompositePropertySource cps = (CompositePropertySource) propertySource;
            cps.getPropertySources().forEach(this::refreshPropertySource);
        } else if (propertySource instanceof EncryptablePropertySource) {
            EncryptablePropertySource eps = (EncryptablePropertySource) propertySource;
            eps.refresh();
        }
    }
}

4.自定义一个ApolloConfigChangeListener监听器，在onChange()方法中判断更新的属性值如果以“ENC(”开头则，调用第3步的类的刷新方法，刷新缓存。
public class ApolloConfigChangeListener implements ConfigChangeListener {
    private JaspytRefreshScopeRefreshedEventListener listener;

    public ApolloConfigChangeListener() {
    }

    public void lazySet(JaspytRefreshScopeRefreshedEventListener listener)
    {
        this.listener = listener;
    }
    @Override
    public void onChange(ConfigChangeEvent changeEvent) {
        changeEvent.changedKeys().forEach(k -> {
            ConfigChange configChange = changeEvent.getChange(k);

            String propertyName = configChange.getPropertyName();
            String newValue = configChange.getNewValue();
            PropertyChangeType changeType = configChange.getChangeType();

            if(newValue.startsWith("ENC(") && Assert.isNotNull(this.listener))
            {
                this.listener.refresh();
            }
        });
    }
}
5.通过这个方法在我在最新版本jasypt-spring-boot：3.0.3，也能实现Apollo的字段刷新。
