### ISSUE TITLE
[疑问]  client 获取 namespace 的疑问？

### ISSUE THREAD

**Issue by wg421338916** [ctripcorp/apollo#2163]
[疑问] client 获取 namespace 的时候每次都是每5分钟或都接受到relase message 的时候立刻从 config server 全量获取到然后在和本地 cache 比较吗？ 每个namespace 没有版本控制吗？

**Comment by wg421338916** [comment]
另外能否提供公共的 基于 apollo 配置封装的 redis，zookeeper，mysql 组建这些，

比如：我想用redis的话，我引入redis的包和redis的配置包， redis的相关配置配置成公共的。

这样每个项目用基础组建的时候都可以不太关心他们的配置了，就配置一次就好了。

**Comment by nobodyiam** [comment]
`基于 apollo 配置封装的 redis，zookeeper，mysql 组建这些`，这些不属于apollo自身组件的范畴，不过欢迎基于apollo和这类组件的客户端提供如`apollo-redis-client`等上层组件
