### ISSUE TITLE
怎样一次性的获取合并多个namespace内容？

### ISSUE THREAD

**Issue by andyyumiao** [ctripcorp/apollo#2165]
如题，我想问的是能不能使用java注解或者配置文件的方式，一次性的导入多个namespace，并且按顺序合并namespace内容并得到结果。我在官网介绍发现下面的用法，是解决这种场景的吗？但没看明白该怎样调用的？

@Configuration
@EnableApolloConfig(value = {"TEST1.sys_application","sys_application"}, order = 2)
public class AnotherAppConfig {

}

**Comment by nobodyiam** [comment]
这个用法是把多个namespace的配置按照order注入到spring中，效果就是按顺序合并namespace内容并得到结果，跑个demo测试一下就明白了

**Comment by andyyumiao** [comment]
> 这个用法是把多个namespace的配置按照order注入到spring中，效果就是按顺序合并namespace内容并得到结果，跑个demo测试一下就明白了

上面的用法是针对spring整合的方式，如果使用api的方式不支持合并namespace吗？比如：Config config = ConfigService.getConfig("application.yml")，貌似一次只能加载一个namespace的

**Comment by nobodyiam** [comment]
API方式使用的话，可以先自己写一个CompositeConfig，然后传入多个namespace，在CompositeConfig加载多个config然后做排序和层级话处理，比如getProperty的时候从优先级高的config开始取

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
