### ISSUE TITLE
portal-页面显示错误(当有灰度配置时,主版本有key的value为空时,灰度显示已删除)

### ISSUE THREAD

**Issue by pfthink** [ctripcorp/apollo#2167]
![image](https://user-images.githubusercontent.com/31644641/56782523-1e66c200-681a-11e9-891a-5f6989d969f0.png)

![image](https://user-images.githubusercontent.com/31644641/56782556-3fc7ae00-681a-11e9-9369-c1d16eb6e8dc.png)

**Comment by pfthink** [comment]
com.ctrip.framework.apollo.portal.service.NamespaceService#transformNamespace2BO
     --->com.ctrip.framework.apollo.portal.service.NamespaceService#parseDeletedItems
  看了下代码 是这段逻辑 如果灰度配置与releaseItems对比，不存在话 设置了deleted＝true,导致页面显示不正确，不明白这段逻辑 目的是啥？

**Comment by nobodyiam** [comment]
应该是js有些问题，之前配置项是不允许值为空的，所以通过判断值是否为空来判断该配置是否被删除了，后续改过一次允许配置项的值为空，不过这里的判断没改，所以导致了该问题，提了个PR #2172 应该能解决这个问题。
