### ISSUE TITLE
ldap的groupSearch不支持多组配置

### ISSUE THREAD

**Issue by xingmin860818** [ctripcorp/apollo#2168]
在将apollo接入ldap时，想要配置授权多个组用户，以便将登录人缩小至部门，但是发现配置后系统无法识别，配置信息：
ldap:
  mapping: # 配置 ldap 属性
    objectClass: "inetOrgPerson" # ldap 用户 objectClass 配置
    loginId: "uid" # ldap 用户惟一 id，用来作为登录的 id
    userDisplayName: "cn" # ldap 用户名，用来作为显示名
    email: "mail" # ldap 邮箱属性
  group: # 启用group search，启用后只有特定group的用户可以登录apollo
    objectClass: "group"  # 配置groupClassName
    groupBase: "ou=group" # group search base
    groupSearch: "(|(cn=group1)(cn=group2))" # group filter
    groupMembership: "memberUid" # group memberShip eg. member or memberUid

组内成员登录系统报错：

org.springframework.dao.EmptyResultDataAccessException: Incorrect result size: expected 1, actual 0
        at org.springframework.ldap.core.LdapTemplate.searchForObject(LdapTemplate.java:1542)
        at org.springframework.ldap.core.LdapTemplate.searchForObject(LdapTemplate.java:1520)
        at org.springframework.ldap.core.LdapTemplate.searchForObject(LdapTemplate.java:1531)
        at com.ctrip.framework.apollo.portal.spi.ldap.FilterLdapByGroupUserSearch.searchForUser(FilterLdapByGroupUserSearch.java:70)

请问是配置有误，还是目前系统不支持多组搜索

**Comment by nobodyiam** [comment]
`org.springframework.dao.EmptyResultDataAccessException: Incorrect result size: expected 1, actual 0`，这个错是说搜索到的用户是0个，所以应该是配置错误所致的

**Comment by xingmin860818** [comment]
> `org.springframework.dao.EmptyResultDataAccessException: Incorrect result size: expected 1, actual 0`，这个错是说搜索到的用户是0个，所以应该是配置错误所致的

我的配置也发出来了，可以帮忙看下哪里有问题吗?

**Comment by nobodyiam** [comment]
看格式是对的，但是具体的值对不对，这个要结合你实际系统里面的数据看的，建议先简化条件跑起来，再慢慢增加过滤条件。

另外，也可以debug进ldap相关的代码看看

**Comment by xingmin860818** [comment]
> 看格式是对的，但是具体的值对不对，这个要结合你实际系统里面的数据看的，建议先简化条件跑起来，再慢慢增加过滤条件。
> 
> 另外，也可以debug进ldap相关的代码看看

配置单group是没问题的，debug倒是可以找人做，但是我想知道目前版本是不是支持这种写法，如果不支持，将来多久会支持。

**Comment by xingmin860818** [comment]
宋神，请问配置多组搜索不成功是哪里的问题啊？

**Comment by nobodyiam** [comment]
这个是ldap的搜索能力，apollo的ldap集成代码只是把这个条件传递给ldap做搜索和过滤，可以看下 com.ctrip.framework.apollo.portal.spi.ldap.LdapUserService#searchUserInfoByGroup 这个方法
