### ISSUE TITLE
docker build 失败

### ISSUE THREAD

**Issue by wx8217** [ctripcorp/apollo#2174]
Dockerfile 中unzip后scripts 目录不在apollo-protal目录下。

**Comment by nobodyiam** [comment]
麻烦提供一下完整的重现步骤

**Comment by wx8217** [comment]
我用最新版的源码编译都，把zip文件拷贝到相应的docker目录下，使用docker build 又成功 了！！

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
