### ISSUE TITLE
docker安装apollo启动成功，客户端读取配置报错

### ISSUE THREAD

**Issue by dreamazhang** [ctripcorp/apollo#2176]
你好,读取配置文件ip为什么是容器的IP，不是docker所在物理机的IP？
 Loading config from http://****(nobodyiam/apollo-quick-start容器的ip):8080/configs/organization/default/application?ip=客户端的ip

导致客户端读取配置读取不到？

**Comment by nobodyiam** [comment]
参考一下分布式部署文档中的网络策略部分

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
