### ISSUE TITLE
在配置页面删除Namespace为什么没有真实删除

### ISSUE THREAD

**Issue by Sonion** [ctripcorp/apollo#2180]
![image](https://user-images.githubusercontent.com/21966559/56959260-6c175d80-6b7f-11e9-9fc7-4609b946f321.png)
在配置页面中选择删除Namespace，为什么没有去删除ApolloConfigDB.AppNamespace中的数据，我知道需要去管理员界面删除，但是我想知道这里的删除为什么这么设计？

**Comment by nobodyiam** [comment]
如果把appnamespace比作class的话，namespace就可以比作是实例化的对象，它在不同的环境，不同的集群都有实例，所以删除Namespace时只是删除了该appnamespace在某个环境某个集群下的一个实例

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
