### ISSUE TITLE
如何最小化apollo的内存占用？

### ISSUE THREAD

**Issue by li-peng** [ctripcorp/apollo#2183]
demo.sh启动后两个进程占用1.4G，内存消耗太大了，怎样才可以使用更少的内存？500M以下就好了。

**Comment by nobodyiam** [comment]
可以设置jvm的xmx, xms等参数

**Comment by li-peng** [comment]
> 可以设置jvm的xmx, xms等参数
嗯，我是看启动后已用内存确实很高，现在调整了参数，确实占用很少了，感谢您的回复。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
