### ISSUE TITLE
除application的以外的namespace无法用@Value直接获取

### ISSUE THREAD

**Issue by tuwq** [ctripcorp/apollo#2186]
![TIM截图20190504225514](https://user-images.githubusercontent.com/33643926/57180901-f5040100-6ebf-11e9-9e0b-5d0098add934.png)
![TIM截图20190504225744](https://user-images.githubusercontent.com/33643926/57180912-0baa5800-6ec0-11e9-9839-3207ac58a480.png)
![TIM截图20190504225903](https://user-images.githubusercontent.com/33643926/57180937-37c5d900-6ec0-11e9-956e-fb2a6b2bcadf.png)
用config可以获取,但@value不行

**Comment by nobodyiam** [comment]
所有namespace都是统一处理的，不会区分是不是application。建议注入Environment，然后看下`org.springframework.core.env.ConfigurableEnvironment#getPropertySources`
