### ISSUE TITLE
配置页面, 滚动条非常卡

### ISSUE THREAD

**Issue by xiaochunyong** [ctripcorp/apollo#2187]
http://x.x.x.x:9090/config.html 这个页面很卡啊...  能不能用浏览器自己的滚动条

**Comment by nobodyiam** [comment]
是什么版本？apollo 1.2.0修复过一次页面性能慢的问题

**Comment by xiaochunyong** [comment]
1.0.0

**Comment by xiaochunyong** [comment]
没注意看消息~~ 又想来提issue了....然后看到2个月前的....问了下, 说是基于1.0定制的....不好升😔

**Comment by buhichan** [comment]
请不要用nice-scroll了, 用浏览器自己的滚动条, nice-scroll太弱智了, 求求你们了, 用户体验太傻了, ctrl f都用不了 我真的服了!!!!!!!

**Comment by nobodyiam** [comment]
@buhichan

**Comment by buhichan** [comment]
> @buhichan
> 
> 1.2.0版本已经移除nice-scroll了，详见 #1621

谢谢
