### ISSUE TITLE
关于namespace的疑问。。。

### ISSUE THREAD

**Issue by andyyumiao** [ctripcorp/apollo#2188]
我发现在任意环境的任意集群下，创建一个私有namespace，此namespace会自动被增加到该应用的所有环境的所有集群下，创建私有namespace的页面并没有选择发布到哪个环境下的选项，这样导致所有环境的集群下多出来很多其他人创建的namespace。。。。
想问下是我使用的方式有问题还是就是这样设计的？

**Comment by nobodyiam** [comment]
目前是这么设计的
