### ISSUE TITLE
namespace的设计疑问

### ISSUE THREAD

**Issue by andyyumiao** [ctripcorp/apollo#2189]
创建namespace会自动同步到同应用所有环境的所有集群下，想问下为什么这样设计呢？这样不同环境的不同集群下，岂不是多了很多无用的namespace？删掉之后还会报namespace缺失？

**Comment by nobodyiam** [comment]
目前对私有的namespace是这个逻辑

**Comment by Sonion** [comment]
不论是私有还是共有都是这个逻辑吧，其实我也好奇为什么这么设计，或者说后期针对这点会做改造吗？

**Comment by nobodyiam** [comment]
主要是考虑为大部分场景使用简单吧，暂时还没有很强的诉求需要改造，不过也欢迎提交PR

**Comment by nobodyiam** [comment]
主要是考虑为大部分场景使用简单吧，暂时还没有很强的诉求需要改造，不过也欢迎提交PR
