### ISSUE TITLE
如何修改apoll-portal中的启动端口server.port

### ISSUE THREAD

**Issue by walkingWind** [ctripcorp/apollo#2190]
在进行本地模拟多环境，部署时，用script/build.bat 进行打包，发现不管怎么修改配置server.port，jar包打好后，apoll-portal的tomcat启动端口都是80。
不管怎么修改application.yml，或者参数注入-Dserver.port都无法改变最终的启动端口

求教，在用script/build.bat进行打包时，如何修改这个启动端口？

**Comment by nobodyiam** [comment]
startup.sh里面可以修改端口的

**Comment by walkingWind** [comment]
首先感谢回答，但是这个应该是不对的吧。首先我的startup.sh里的设置是SERVER_PORT=8070，然后，我是打成了jar包，用java -jar命令直接启动的，所以跟shell脚本应该没什么关系吧，我是windows的。我尝试了很多方式，发现打成jar包后，启动端口都没有修改成功。我下载的版本是apollo源码版本是1.2.0-SNAPSHOT。最后，我发现只有java -jar xxx.jar --server.port=8888这一种方式可以修改启动端口。我不知道为什么，配置的端口一直无法正常运行，所以，还是想请教下

**Comment by nobodyiam** [comment]
这个是spring boot的配置逻辑，建议看一下spring boot相关的文档。java -jar运行的话，--server.port和-Dserver.port都是可以的，不过-D参数要卸载-jar前面。

**Comment by walkingWind** [comment]
我不使用参数注入端口时，我写在application.yml的server.port为什么没有生效呢？似乎只有apollo-portal模块没有改变端口成功，apollo-adminservice，apollo-configservice模块，都是可以的

**Comment by nobodyiam** [comment]
看下打出来的jar包中实际的配置是什么吧

**Comment by tandanzZ** [comment]
-D 方式可行

**Comment by ChongDun** [comment]
server.port参数建议提到build.sh里，谢谢
