### ISSUE TITLE
使用跟踪

### ISSUE THREAD

**Issue by matinaNone** [ctripcorp/apollo#2191]
请问 "可以看到当前哪些客户端在使用哪些配置" 这一功能在哪里展现？

**Comment by nobodyiam** [comment]
实例列表

![image](https://user-images.githubusercontent.com/837658/57203075-29221380-6fdf-11e9-8cbf-8ca75618e5d5.png)

**Comment by matinaNone** [comment]
感谢回复，实例列表已看到。
启动SimpleApolloConfigDemo.java，在控制台输入key，对应的value输出，刷新实例列表，并没有看到调用IP和获取时间呢？

**Comment by nobodyiam** [comment]
那说明没连上或者看错namespace了
