### ISSUE TITLE
建议：是否有增加app粒度配置一键导入导出功能，方便备份和同步等需求。

### ISSUE THREAD

**Issue by hanyidreamer** [ctripcorp/apollo#2192]
需求背景：
公司开发、生产、测试环境落在不同机房，公司规则不允许跨机房访问DB以减少延时和防止多环境共用DB导致DB入口流量占满情况，生产也需全部隔离，portal也必须独立环境部署，因此所有组件部署三套，存在这个配置同步问题。

**Comment by nobodyiam** [comment]
duplicated with #1681
