### ISSUE TITLE
多级目录的配置应该怎样设计？

### ISSUE THREAD

**Issue by andyyumiao** [ctripcorp/apollo#2193]
目前我知道的是apollo支持4层配置：应用/环境/集群/namespace。
但比如这种：/druid/dev/idc/network/gateway，每级目录都有独立的配置项应该怎样设计？

**Comment by nobodyiam** [comment]
一般会通过集群来实现同一环境不同配置的区分，你说的场景有点抽象，能举个具体的例子么

**Comment by andyyumiao** [comment]
> 一般会通过集群来实现同一环境不同配置的区分，你说的场景有点抽象，能举个具体的例子么

比如这种更多层的划分：/集群/集市/队列/业务线/模块/框架，这个有6层，每一层都会有些公有和私有配置，使用apollo应该怎样设计每层的配置项？

**Comment by nobodyiam** [comment]
实际的使用场景是什么？

粗略的解法是每一层都创建一个自己的公共namespace，里面配置该层自己关心的公共配置，如果希望封装比较好的话，每一层自己提供一个jar包来引入自己的配置，如果希望简单起见的话，那就让应用按照顺序分别引入这些公共namespace
