### ISSUE TITLE
logback日志从Apollo实时读取

### ISSUE THREAD

**Issue by newWSmile** [ctripcorp/apollo#2194]
我现在想做成把logback的文本全部放到Apollo的一个key中，然后项目启动的时候加载@Value 把这个value重新弄成文本，再走logback的日志，进而启动。不知道这样的思路是否可以呢？

**Comment by nobodyiam** [comment]
如果要这样实现的话，估计要改logback的配置获取逻辑了，一般是建议通过stringProperty注入，或者通过spring boot的logging.xxx来注入配置，可以参考下[spring-cloud-logger](https://github.com/ctripcorp/apollo-use-cases/blob/master/spring-cloud-logger)
