### ISSUE TITLE
拉取不到共有namespace，情况如下

### ISSUE THREAD

**Issue by dingchen265** [ctripcorp/apollo#2196]
使用了springboot，对于Config我们使用的的@ApolloConfig注入，然后进入这个配置看到是默认拉取application的配置，我想要拉取私有的application和关联的其他nameapace，请问我应该怎么获取到配置其他namespace的配置

**Comment by dingchen265** [comment]
already resolved。是我的配置错了

**Comment by mqmjingba** [comment]
您好，请问是哪配置错了？我也遇到相同的问题
