### ISSUE TITLE
新建namespace 后，接着删除，然后再重建，就会提示已经存在，无法新建

### ISSUE THREAD

**Issue by wangbinqiang** [ctripcorp/apollo#2198]
比如新建一个  abcd.properties 的namespace， 然后删除它， 然后再新建一个 abcd.properties , 
页面就会提示   “ 创建失败，code：400  private namespace  abcd.properties already exists！ ”
这应该是 该系统， 没有使用 IsDeleted 字段，  每次出现这种问题，我们这边都得去删除数据库的2张表，
很是麻烦。

**Comment by nobodyiam** [comment]
如果要彻底删除私有namespace，请使用 管理员工具 - 删除应用、集群、AppNamespace 功能
如果删完想恢复，1.2.0+版本页面左侧会出现补缺namespace按钮的
