### ISSUE TITLE
改造参考：客户端缓存配置有序 & 注册中心Eureka替换为zookeeper

### ISSUE THREAD

**Issue by hanyidreamer** [ctripcorp/apollo#2201]
以下两点改造有需要可以参看，欢迎review指正

Apollo配置中心改造一-让客户端获取到的配置缓存有序
https://blog.csdn.net/u014732209/article/details/89553392

Apollo配置中心改造二-注册中心Eureka替换为zookeeper
https://blog.csdn.net/u014732209/article/details/89555535

改造背景一：
微服务配置中心承载着配置托管角色，出问题排查需要查看本地缓存配置，确认生效配置，此时发现apollo配置中心缓存下来不保证与portal同序，配置非常多情况下排查比较麻烦。
改造背景二：
许多公司微服务项目已经在使用zookeeper，为了方便服务管理，替换为zookeeper比较利于运维团队管理统一的注册中心。

**Comment by liuxg-github** [comment]
最近在看如何将eureka改为zookeeper，哈哈，雪中送炭啊

**Comment by hanyidreamer** [comment]
@liuxg-github 那欢迎验证下，之前改造的，看看文章有没有漏修改点

**Comment by liuxg-github** [comment]
每太看懂这个配置configservice、adminservice、portal组件bootstrap.properties均添加zk配置？

**Comment by liuxg-github** [comment]
在pom.xml中enreka相关依赖应该都要替换吧，不仅仅是apollo-biz下的eureka-client？

**Comment by hanyidreamer** [comment]
@liuxg-github 三个服务都需要注册服务，外层pom文件添加zk相关依赖即可，文中apollo-biz给config和admin添加了，portal又单独添加了，等会修改下

**Comment by liuxg-github** [comment]
原getConfigServiceInstances、getMetaServiceInstances等返回的是List<InstanceInfo>，替换后返回的应该是List<ServiceInstance>，这个还是说明下吧

**Comment by liuxg-github** [comment]
编译后，部署时，应该还是跟eureka类似，无需在单独安装zookeeper，包含在容器中，启动程序即启动zookeeper？

**Comment by hanyidreamer** [comment]
@liuxg-github 返回值都是一样的，方法体改了而已，文中只写方法体说明方法出入参和名称都一样的，生产去年就已经投入使用了，未改变aollo调用关系情况下换为zk而已，需要其他功能的话自行再改造下即可。

**Comment by nobodyiam** [comment]
@hanyidreamer 

感谢建议，已经添加到WIKI中：[14. 注册中心Eureka如何替换为zookeeper？](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#14-%E6%B3%A8%E5%86%8C%E4%B8%AD%E5%BF%83eureka%E5%A6%82%E4%BD%95%E6%9B%BF%E6%8D%A2%E4%B8%BAzookeeper)

**Comment by liuxg-github** [comment]
对于adminservice的是否也是参照configservice去掉eureka，改用zookeeper?

**Comment by hanyidreamer** [comment]
@liuxg-github 是的，eureka都去掉，按照步骤改造，再下载zk服务端启动运行代码试试

**Comment by liuxg-github** [comment]
试了，服务这些都可以起来了，管理端也可以登录进去，但是在进入项目后，会报系统错误，是不是还有某些配置导致的？

**Comment by liuxg-github** [comment]
你好，通过你说的方法，我已经把各服务启来了，但是在portal启动后，会出现如下一些错误信息：
2019-05-09 13:30:40.775 ERROR 1524 --- [HealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env is down. env: DEV, failed times: 16, meta server address: http://localhost:8080/
2019-05-09 13:30:50.809 ERROR 1524 --- [HealthChecker-1] c.c.f.a.p.c.RetryableRestTemplate        : Http request failed, uri: /health, method: GET

看这个应该是还是通过eureka去检测状态，这个需要改相关配置屏蔽解决吗？谢谢

**Comment by liuxg-github** [comment]
你好，按照你说的方法，configservice、adminservice和portal都可以起来了，管理界面也可以登录，但是portal起来会不停提示health失败的问题，如下：
2019-05-09 16:16:33.786 ERROR 16084 --- [HealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env is down because health check failed for 2 times, which equals to down threshold. env: DEV, meta server address: http://localhost:8080/
2019-05-09 16:16:43.851 ERROR 16084 --- [HealthChecker-1] c.c.f.a.p.c.RetryableRestTemplate        : Http request failed, uri: /health, method: GET
 
然后在点击进入项目时，就会出现系统出错的提示，跟踪了下，感觉就是上面health检查失败导致的，现在还不明白怎么这块，有时间的话，烦请指点迷津，谢谢。

**Comment by hanyidreamer** [comment]
@liuxg-github 你试试再拷贝我文中zk配置或注释掉下面试试
#management.endpoints.web.base-path=/actuator 
如果还不行你改为下面看看
management.endpoints.web.base-path=/

**Comment by liuxg-github** [comment]
不行，那是不是要把原有的eureka.instance等的配置去掉？
刚才我把判断IsUp直接返回未做health判断，查询、发布等就没什么问题了。

**Comment by hanyidreamer** [comment]
你直接看看/health能不能访问到你的组件健康检查，或看启动日志健康检查是什么路由，apollo内部HealthApi好像直接访问/healthy，management.endpoints.web.base-path=/ 应该就行，我配置在文章中，一切正常

**Comment by hanyidreamer** [comment]
@liuxg-github 你看看机器哪个路由可以访问到监控检查，好像我记得看到apollo的HealthApi直接写的访问/healthy，你看看如何配置，我文中配置启动正常

**Comment by liuxg-github** [comment]
可以了，是因为我把adminservice配置成management.endpoint.health.show-details=always，把这个配置屏蔽掉就没问题了，刚开始搞apollo和zookeeper，很多不太清楚，十分感谢大神。
