### ISSUE TITLE
分布式部署配置中心某个服务健康检查出现 UNKNOWN

### ISSUE THREAD

**Issue by jingfeigithub** [ctripcorp/apollo#2202]
分布式部署配置中心某个服务健康检查出现 UNKNOWN：
解决方式：
把bootstrap.yml里的
eureka:
  client:
    healthcheck:
      enabled: true
注释，并且添加到application.yml里即可。
需要把adminservice和configservice的都改一下

**Comment by nobodyiam** [comment]
多谢建议，能简单解释下背后的原理吗？
