### ISSUE TITLE
多层级的树形结构，apollo有解决方案吗？

### ISSUE THREAD

**Issue by andyyumiao** [ctripcorp/apollo#2205]
比如这种结构，/a/b/c/d/e/f/g/h，即树形目录而不是扁平目录，也就是说层级之间有父子关系，每层都有一些公有和私有配置。
我尝试过用namespace拼接多层子目录，但是namespace长度限制32个字符，貌似这种方式也行不通，求解？

**Comment by nobodyiam** [comment]
实际的使用场景是什么？

粗略的解法是每一层都创建一个自己的公共namespace，里面配置该层自己关心的公共配置，如果希望封装比较好的话，每一层自己提供一个jar包来引入自己的配置，如果希望简单起见的话，那就让应用按照顺序分别引入这些公共namespace

**Comment by andyyumiao** [comment]
> 实际的使用场景是什么？
> 
> 粗略的解法是每一层都创建一个自己的公共namespace，里面配置该层自己关心的公共配置，如果希望封装比较好的话，每一层自己提供一个jar包来引入自己的配置，如果希望简单起见的话，那就让应用按照顺序分别引入这些公共namespace

具体的业务场景是：比如有一些hadoop集群；每个集群的服务不一样，总体分为hdfs、yarn服务；hdfs分为Data Node、Name Node等节点；yarn分为Node Manager、Resource Manager等节点；然后不同的节点下面又有很多各自的配置文件，比如hdfs常用的hdfs-site.xml文件等。我们想把hadoop的配置文件全都抽到配置中心来统一管理，这样一来，从业务
