### ISSUE TITLE
只想部署一套环境，在portal上根据环境不同来给开发、测试、生产用，即三个环境的meta server都填同一个地址，所以修改apollo.portal.envs=dev,fat,pro，但发现不生效，请问为什么呢？难道还会去检测各环境的meta server地址必须不一样吗？

### ISSUE THREAD

**Issue by lh62863** [ctripcorp/apollo#2209]

**Comment by tanis9254** [comment]
这个meta servert填的是哪个地址 configserver还是Eureka啊

**Comment by nobodyiam** [comment]
meta server填的是config service的地址，如果不生效的话，可以到管理员工具 - 系统信息页面看一下，也可以看一下apollo-portal的日志

**Comment by tanis9254** [comment]
> meta server填的是config service的地址，如果不生效的话，可以到管理员工具 - 系统信息页面看一下，也可以看一下apollo-portal的日志

已经生效了 生产环境部起来
