### ISSUE TITLE
apollo.meta设置域名应用启动警告[Cause: Could not complete get operation [Cause: Unexpected end of file from server]]

### ISSUE THREAD

**Issue by reignsr** [ctripcorp/apollo#2210]
配置HAProxy后，apollo.meta设置为域名地址，启动应用时警告（写ip正常）：WARN  com.ctrip.framework.apollo.internals.RemoteConfigLongPollService - Long polling failed, will retry in 1 seconds. appId: debug-app, cluster: default, namespaces: T-QA.common.conn, long polling url: null, reason: Get config services failed from http://dev-meta.ts-accs.epay/services/config?appId=debug-app&ip=10.59.42.93 [Cause: Could not complete get operation [Cause: Unexpected end of file from server]]

**Comment by reignsr** [comment]
问题暂时解决，HAProxy里的mode改成http就正常了，tcp就有警告。
官方是不是考虑下兼容性问题？

**Comment by nobodyiam** [comment]
apollo-client是使用http协议访问服务端的，建议抓包看下HAProxy在tcp mode下的response和http mode下的有啥不同？

**Comment by reignsr** [comment]
好的，回头抓包看看，再给你反馈。

**Comment by stanleyls** [comment]
> 好的，回头抓包看看，再给你反馈。

同问
