### ISSUE TITLE
请问apollo有 api 可以第三方添加删除修复配置项吗?

### ISSUE THREAD

**Issue by ShireCiel** [ctripcorp/apollo#2211]
请问apollo有 api 可以第三方添加删除修复配置项吗?
如果没有，可不可以考虑加一个？
自动化 很需要的。

**Comment by nobodyiam** [comment]
参考一下[Apollo开放平台](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0)

**Comment by ShireCiel** [comment]
> 参考一下[Apollo开放平台](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0)

谢谢
