### ISSUE TITLE
升级1.4.0版本后出现portal界面显示配置错乱

### ISSUE THREAD

**Issue by reignsr** [ctripcorp/apollo#2212]
升级1.4.0版本后，创建了一个私有的txt格式命名空间，首次发布该命名空间成功，随后修改其内容再次发布，出现异常，发布后界面仍显示“有修改”。此后若干App均出现怪异现象：
1、刷新浏览器，界面显示配置参数的状态呈现不规律的新增、删除、修改标记的“有修改”状态，有时甚至命名空间下参数变成空的了；
2、通过管理员工具删除那个txt格式命名空间，四个环境中三个环境正常删除，一个环境的数据没有删掉，数据库里该数据的IsDeleted还是0；
最终，手工清理了数据库里的异常数据，并版本回退1.3.0，恢复正常。

**Comment by nobodyiam** [comment]
是否能提供下详细的重现步骤？我在demo环境无法重现该问题。。

另外，txt格式新增了一个枚举的，各admin service是否都已经升级？

**Comment by reignsr** [comment]
adminservice升级了，我后续再做测试看看吧。
