### ISSUE TITLE
使用apollo的同时，怎么让本地的application.yml生效

### ISSUE THREAD

**Issue by fangchao3652** [ctripcorp/apollo#2214]
测试的时候，想用本地的覆盖配置中心的配置，该怎么配置啊？

**Comment by nobodyiam** [comment]
可以参考一下[本地开发模式](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#%E4%BA%94%E6%9C%AC%E5%9C%B0%E5%BC%80%E5%8F%91%E6%A8%A1%E5%BC%8F)和[测试模式](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#%E5%85%AD%E6%B5%8B%E8%AF%95%E6%A8%A1%E5%BC%8F)

**Comment by shelltea** [comment]
@nobodyiam  本地开发模式是全部配置都使用本地的，如果我希望一部分公共配置使用配置中心的，一部分配置使用本地的，能够支持吗？

**Comment by nobodyiam** [comment]
@shelltea 可以参考 #1560
