### ISSUE TITLE
增加不同模块权限控制

### ISSUE THREAD

**Issue by mrtylerzhou** [ctripcorp/apollo#2219]
我们项目组已经使用了近半年时间了,目前向全公司推广有一个很大的问题就是管理问题.阿波罗的所有模块都列在了一个页面里.线上配置被误操作可能导致非常严重的结果.希望能增加更为细致的权限控制,比如某些用户只能访问某些模块的配置,甚至同一模块的配置不同用户只能访问不同的环境(比如普通开发人员可以访问dev配置,而管理员可以访问pro配置)等.

**Comment by nobodyiam** [comment]
1. 同一模块的配置不同用户只能访问不同的环境(比如普通开发人员可以访问dev配置,而管理员可以访问pro配置)等.

apollo 0.11.0及以上版本支持权限按环境给的

2. 某些用户只能访问某些模块的配置

权限是到namespace级别的，所以天然就支持这个场景。如果你是指的查看权限的话，可以参考[配置查看权限](https://github.com/ctripcorp/apollo/wiki/Apollo%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#61-%E9%85%8D%E7%BD%AE%E6%9F%A5%E7%9C%8B%E6%9D%83%E9%99%90)
