### ISSUE TITLE
apollo版本升级

### ISSUE THREAD

**Issue by xingmin860818** [ctripcorp/apollo#2223]
您好，
      我们目前生产使用的是0.7版本，想升级到1.30，服务端测试升级没问题了，但是不知道java客户端是否需要变动，没有找到客户单相关的说明，请问需要变动吗？

**Comment by nobodyiam** [comment]
客户端不升级也可以用，如果希望使用新版本的能力，可以考虑升级。主要的变化是1.0.0版本，具体可以看下 https://github.com/ctripcorp/apollo/releases/tag/v1.0.0
