### ISSUE TITLE
加强权限认证

### ISSUE THREAD

**Issue by matinaNone** [ctripcorp/apollo#2225]
目前支持：在要接入的应用程序中配置app.id=xxxx，就可以获取到此appid在配置中心的配置信息。
我的期望：希望权限认证度高一些。加入token认证，同时配置app.id和已绑定的token，才能加 载到这个应用的配置。就像第三方应用调用openapi的方式一样。
有什么建议：1.是直接修改Apollo-core组件，将认证过程完善？
                      2.还可以通过其他方式实现吗？
一个无关的小问题：客户应用在启动后，加载到内存的过程是什么样的？没有在文档中查阅到这一点，还请指教~

**Comment by nobodyiam** [comment]
duplicated with #1810

客户应用在启动后，加载到内存的过程是什么样的？

可以参考[DefaultConfig](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/DefaultConfig.java)

**Comment by matinaNone** [comment]
通过搜索以前的issue，发现和  [#2099](https://github.com/ctripcorp/apollo/issues/2099) 是一个意思
