### ISSUE TITLE
能否将：ENV 扩展做成SPI的方式？

### ISSUE THREAD

**Issue by waveng** [ctripcorp/apollo#2227]
能否将：ENV 扩展做成SPI的方式？用户需要扩展自定义的环境时，实现该SPI就可以进行环境扩展？？

**Comment by nobodyiam** [comment]
这是一个可能的解法，目前另一个思路是把ENV和客户端解开（客户端只需要感知apollo.meta即可），然后在apollo-portal中通过把env作为一个可录入的实体对象来管理，这样用户通过界面操作就可以方便地增减环境了。

**Comment by waveng** [comment]
嗯，不管哪种方案，只要能够实现无需改动代码既可以实现动态扩展环境，向量是最好的。但现有的情况，需要直接改代码，不太友好

**Comment by nobodyiam** [comment]
是的，这块是希望解决的，前面提到的通过把env作为一个可录入的实体对象来管理目前还没开始做的原因是还没想好如何兼容老版本的使用方式，所以或许env扩展成spi是一个更可行的方式
