### ISSUE TITLE
启动端口问题

### ISSUE THREAD

**Issue by Doubleuncle** [ctripcorp/apollo#2228]
因为我的8080端口已经占用，只能换端口。我在config的startup.sh里将端口修改为7080，启动后未成功，我查看日志启动的端口为什么仍然为8080？

**Comment by Doubleuncle** [comment]
configDB数据库中serverconfig表中的信息已更改为http://localhost:7080/eureka/

**Comment by Doubleuncle** [comment]
启动的是分布式版本里的config……日志报tomcat启动的端口仍然是8080

**Comment by nobodyiam** [comment]
startup.sh里面修改SERVER_PORT变量即可，该变量会通过-Dserver.port传入，优先级是最高的。

**Comment by Doubleuncle** [comment]
> startup.sh里面修改SERVER_PORT变量即可，该变量会通过-Dserver.port传入，优先级是最高的。

SERVER_PORT已经修改为7080，但是貌似并没有启到作用……我自己的电脑的虚拟机修改以后就换了端口，但是单位虚拟机就不行。您看有可能是因为环境问题么？

**Comment by Doubleuncle** [comment]
> startup.sh里面修改SERVER_PORT变量即可，该变量会通过-Dserver.port传入，优先级是最高的。

我echo了一下，SERVER_PORT 和 JAVA_OPTS里的-Dserver.port都是7080，
但是后面日志信息仍然是：Tomcat initialized with port(s):8080 (https)

**Comment by Doubleuncle** [comment]
修改了stratup.sh，用--name='spring' --server.port=7080强制让其跑了7080端口

**Comment by nobodyiam** [comment]
startup.sh里面修改SERVER_PORT变量肯定可以的，因为脚本中是通过-Dserver.port传入的，如果不行的话，可以ps aux看一下实际运行时传入的参数
