### ISSUE TITLE
网络情况不佳下,configservice容易假死

### ISSUE THREAD

**Issue by ayanjoyful** [ctripcorp/apollo#2230]
网络情况不佳下,configservice容易假死

**Comment by nobodyiam** [comment]
有更详细的描述吗？

**Comment by ayanjoyful** [comment]
我用的是一个比较老的版本,0.7.0使用的,这几天我们部署到生产环境后,发现meta.server 8080服务我直接访问失败,超时.meta server 发现处于假死状态了. 有时候系统能自己恢复,我用jstack 工具也无法查看.提示Unable to open socket file: target process not responding or HotSpot VM not loaded.其他两个工程是正常的.能大致判断是什么原因造成的吗?环境用的ECS服务器.

> 有更详细的描述吗？

**Comment by nobodyiam** [comment]
用jstack -F看看呢

**Comment by ayanjoyful** [comment]
> 用jstack -F看看呢
用jstack -F 看过,发现没有死锁. 我在猜想有没有可能和ECS网络环境有问题呢,我搭建的apoll 发现都是ECS环境中有这个问题,其他部署没发现这个问题.我这个猜想的话有什么建议可监控的方法吗?谢谢大神.

**Comment by nobodyiam** [comment]
apollo提供了[Tracer](https://github.com/ctripcorp/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/apollo/tracer/Tracer.java)，并针对cat提供了实现，如果有cat的话，可以直接对接。如果没有的话，可以尝试实现Tracer spi来获取精细粒度监控，或者也可以安装一些支持监控jvm的apm软件，可以看到应用的一些状态。

**Comment by ayanjoyful** [comment]
> apollo提供了[Tracer](https://github.com/ctripcorp/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/apollo/tracer/Tracer.java)，并针对cat提供了实现，如果有cat的话，可以直接对接。如果没有的话，可以尝试实现Tracer spi来获取精细粒度监控，或者也可以安装一些支持监控jvm的apm软件，可以看到应用的一些状态。

好的 谢谢
