### ISSUE TITLE
补缺namespace

### ISSUE THREAD

**Issue by liang524132** [ctripcorp/apollo#2234]
多次测试apollo1.3.0与1.4.0, 删除namespace,在http://localhost:8070/config.html?#/appid= 界面多刷新几次就出现补缺namespace的提示和操作；查看了源码与数据库表：删除namespace，只设置了ApolloConfigDB namespace表isdeleted=true，ApolloConfigDB appnamespace与 ApolloPortalDB appnamespace表该appid的namespace字段isdeleted还是为false；点击了 补缺namespace 操作，也只在ApolloConfigDB namespace表又新建了一条appid的namespace。还发现，只有在删除项目appid操作才设置ApolloConfigDB appnamespace表，ApolloConfigDB namespace表，ApolloPortalDB appnamespace 表的改appid下面全部的namespace的isdeleted为true。
疑问：
1、为什么删除namespace操作，只设置ApolloConfigDB namespace表isdeleted为true，而其他有关namespace两个表isdeleted还是为false
2、为什么判断 补缺namespace 操作，多次刷新http://localhost:8070/config.html?#/appid= 界面才会出现 补缺namespace；很多次打开该界面显示正常
3、com.ctrip.framework.apollo.portal.controller.NamespaceController#findMissingNamespaceNames；
	// AppNamespaces should be the same
    Set<String> missingAppNamespaceNames = Sets.difference(portalDbAllAppNamespaceNames, configDbAppNamespaceNames);
    // Private namespaces should all exist
    Set<String> missingNamespaceNames = Sets.difference(portalDbPrivateAppNamespaceNames, configDbNamespaceNames);
	这个方法判断缺少namespace，求差集，为什么要以ApolloPortalDB appnamespace表数据放在前面，而不是ApolloConfigDB appnamespace、namespace表数据作为求差集放在前面；求两个A、B集合差集；A-B 与 B-A结果是不同的
4、前端js判断逻辑是否正确，ConfigBaseInfoController.js findMissingNamespaces方法
$scope.findMissingNamespaces = function () {
        $scope.missingNamespaces = [];
        // only check missing private namespaces when app exists in current env
        if ($rootScope.pageContext.env && $scope.missEnvs.indexOf($rootScope.pageContext.env) === -1) {
          AppService.find_missing_namespaces($rootScope.pageContext.appId, $rootScope.pageContext.env,
              $rootScope.pageContext.clusterName).then(function (result) {
                  $scope.missingNamespaces = AppUtil.collectData(result);
                  if ($scope.missingNamespaces.length > 0) {
                      toastr.warning("当前环境有Namespace缺失，请点击页面左侧『补缺Namespace』补齐数据");
                  }
          });
        }
    };

当$rootScope.pageContext.env 为“”， $scope.missEnvs也为[]; 多刷新几次有时$rootScope.pageContext.env有值，比如 “DEV”，$scope.missEnvs一样为[] ; $scope.missEnvs.indexOf($rootScope.pageContext.env) == -1 条件成立，觉得这样判断不太严谨；判断条件应该再加上$scope.missEnvs.length > 0 ;

**Comment by nobodyiam** [comment]
1. 如果把appnamespace比作class的话，namespace就是这个class在不同环境不同集群的instance，所以在页面上删除的是instance，也就是namespace实体。

3. portaldb中的appnamespace是原始数据，configdb中的是从portal同步过去的

4. 前端判断逻辑确实发现有时候无法反映真实情况，如果确有问题的话，欢迎提交PR~
