### ISSUE TITLE
无需校验即可通过Http接口从Apollo读取配置

### ISSUE THREAD

**Issue by Vane-L** [ctripcorp/apollo#2235]
在调研apollo的过程中发现，可以通过http接口读取所有配置，请问这是否应该做一定的权限控制呢？
 curl {config_server_url}/configs/{appId}/{clusterName}/{namespaceName}即可获取任意项目的任意namespace的配置

**Comment by nobodyiam** [comment]
config service设计是在公司内网运行，所以对接口访问没有做权限控制，如果有好的建议也欢迎讨论~
