### ISSUE TITLE
openapi调用时可以获取到所有app信息

### ISSUE THREAD

**Issue by matinaNone** [ctripcorp/apollo#2240]
访问openapi接口 http://{url}:{port}/openapi/v1/apps，参数带上已申请的token，就可以返回所有app信息，我理解的token是和某个app绑定的，只能获取到这个绑定的app信息。所以为什么要开放能获取到所有app信息的接口呢？

**Comment by matinaNone** [comment]
还有，只要参数带上任何一个token，那么可以访问到其他app的配置信息，比如访问http://{url}:{port}/openapi/v1/apps/{appid1}/envclusters接口时，传的token并不是绑定在appid1上的，依然可以获取到信息。发现源代码中是这样设计的：
Long consumerId = consumerAuthUtil.getConsumerId(token);
    if (consumerId == null) {
      response.sendError(HttpServletResponse.SC_UNAUTHORIZED, "Unauthorized");
      return;
    }
只要查询到token有对应的consumerId，就认为是合法的，校验就通过了，那和appid绑定还有什么意义呢？

**Comment by nobodyiam** [comment]
和appid绑定是控制写操作的，读操作目前是都允许的

**Comment by matinaNone** [comment]
明白了，谢谢~

**Comment by dreamxgn** [comment]
使用openapi客户端访问，提示404错误呢
Request to apollo open api failed, status code: 404, reason: , message: {"timestamp":"2021-06-17T15:07:50.567+0800","status":404,"error":"Not Found","message":"No message available","path":"/openapi/v1/apps"}
