### ISSUE TITLE
同一java客户端，怎样监听多个应用、多个集群下的namespace？

### ISSUE THREAD

**Issue by andyyumiao** [ctripcorp/apollo#2244]
我们的场景是，每台服务器都部署上百种类型的应用服务，每个应用都有很多集群，我们想把这些应用的配置都放到配置中心管理，举例来说，我们通常需要在同一台机器上监听这些组合：
应用1，集群1，namespace1
应用1，集群2，namespace2
应用1，集群3，namespace1
应用1，集群3，namespace3
应用2，集群1，namespace3
应用4，集群7，namespace2
.....
有上百种组合，但我们不可能在一台机器上开上百个代理。。。怎样实现这种需求？

**Comment by nobodyiam** [comment]
这里说的应用是我们通常意义上理解的一个独立进程吗？如果是独立进程的话每个应用配置自己appid和集群信息即可。

**Comment by andyyumiao** [comment]
> 这里说的应用是我们通常意义上理解的一个独立进程吗？如果是独立进程的话每个应用配置自己appid和集群信息即可。

对，这些应用通常部署在同一台机器上，我们想对这些应用无侵入接入配置中心，思路就是做个一个配置代理进程，监听到配置变化后，生成配置文件，直接覆盖应用对应的配置文件，但是apollo的一个client好像只能监听一个应用+一个集群的，怎么解决我们这种场景？

**Comment by nobodyiam** [comment]
可以通过http方式接入，具体看下第三方应用接入的文档
