### ISSUE TITLE
Spring MVC 项目如何集成

### ISSUE THREAD

**Issue by LuoLee** [ctripcorp/apollo#2245]
现在有一个传统的Spring MVC项目想集成Apollo，但是按照[Java客户端使用指南](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)的方式添加了XML配置文件，发现似乎并没有任何效果。
以下是集成步骤：
1. 在`webapp/WEB-INF/`下新增`apollo.xml`配置文件：
```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:apollo="http://www.ctrip.com/schema/apollo"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
       http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context.xsd
       http://www.ctrip.com/schema/apollo http://www.ctrip.com/schema/apollo.xsd">
    <apollo:config />
    <context:annotation-config />
</beans>
```
2. 在`web.xml`配置文件中`contextConfigLocation`参数指定的配置文件中`import`上面创建的`apollo.xml`文件：
```
<import resource="apollo.xml"></import>
```

3. 在`META-INF`目录下新增`app.properties`文件：
```
app.id=zx
apollo.meta=http://172.16.14.4:8080
apollo.autoUpdateInjectedSpringProperties=true
apollo.bootstrap.enabled=true
apollo.bootstrap.namespaces="application,fiss.UP"
```

至此配置完毕了，但是启动项目并没有效果，不知是哪里还缺少配置或是配置有误？

**Comment by nobodyiam** [comment]
先参考文档和[apollo-demo](https://github.com/ctripcorp/apollo/tree/master/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/spring/xmlConfigDemo)项目理解并跑通，然后再结合自己的程序配置和运行中的日志排查一下问题。
