### ISSUE TITLE
apollo 接入LDAP后  memberOf: "CN= " 只能是用户名 不能是组名吗

### ISSUE THREAD

**Issue by station19** [ctripcorp/apollo#2248]
1,) apollo 接入LDAP后  memberOf: "CN= " 只能是用户名 不能是组名吗

2,) 还有 apollo怎么 设置项目环境权限为用户组, 每次去添加权限 一个一个namespace添加  , 太耗时间做

apollo版本 v1.3

**Comment by nobodyiam** [comment]
[基于memberof过滤用户](https://github.com/ctripcorp/apollo/wiki/Portal-%E5%AE%9E%E7%8E%B0%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95%E5%8A%9F%E8%83%BD#111-%E5%9F%BA%E4%BA%8Ememberof%E8%BF%87%E6%BB%A4%E7%94%A8%E6%88%B7)，支持OpenLDAP，是组名

权限目前还不支持用户组

**Comment by station19** [comment]
> [基于memberof过滤用户](https://github.com/ctripcorp/apollo/wiki/Portal-%E5%AE%9E%E7%8E%B0%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95%E5%8A%9F%E8%83%BD#111-%E5%9F%BA%E4%BA%8Ememberof%E8%BF%87%E6%BB%A4%E7%94%A8%E6%88%B7)，支持OpenLDAP，是组名
> 
> 权限目前还不支持用户组

嗯嗯,  支持用户组的话就很很方便啦,  不然每次 针对namespace 的权限和项目权限 , 在人员变动的时候 都要去手动修改, 工作量很大啊

**Comment by R1hug0** [comment]
> 
> 
> [基于memberof过滤用户](https://github.com/ctripcorp/apollo/wiki/Portal-%E5%AE%9E%E7%8E%B0%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95%E5%8A%9F%E8%83%BD#111-%E5%9F%BA%E4%BA%8Ememberof%E8%BF%87%E6%BB%A4%E7%94%A8%E6%88%B7)，支持OpenLDAP，是组名
> 
> 权限目前还不支持用户组

Memberof 是不是不支持 Active Directory,在测试中怎么写都无法调试成功,配置如下
memberOf: "OU=it,DC=rrjc,DC=com|OU=dev,DC=rrjc,DC=com"

**Comment by station19** [comment]
> > [基于memberof过滤用户](https://github.com/ctripcorp/apollo/wiki/Portal-%E5%AE%9E%E7%8E%B0%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95%E5%8A%9F%E8%83%BD#111-%E5%9F%BA%E4%BA%8Ememberof%E8%BF%87%E6%BB%A4%E7%94%A8%E6%88%B7)，支持OpenLDAP，是组名
> > 权限目前还不支持用户组
> 
> Memberof 是不是不支持 Active Directory,在测试中怎么写都无法调试成功,配置如下
> memberOf: "OU=it,DC=rrjc,DC=com|OU=dev,DC=rrjc,DC=com"

 老铁, 你的CN 呢

#只有apollo组里的用户能访问
  filter:
    memberOf: "CN=apollo,OU=test,DC=ky-tech,DC=com,DC=cn"
