### ISSUE TITLE
apollov1.3升级到v1.4后 check 提示 "Code:500 Msg:Required String parameter 'instanceId' is not present"

### ISSUE THREAD

**Issue by station19** [ctripcorp/apollo#2250]
apollov1.3升级到v1.4后 check 提示500错误

管理员工具--- 系统信息 里

对应的  Check Health , 点击 check 提示 "Code:500 Msg:Required String parameter 'instanceId' is not present"
但是  环境的 Active: true 

这是什么情况, check 检测加了字段吗?

#v1.4官方demo check url
http://106.12.25.204:8070/system-info/health?instanceId=instance-300408ep:apollo-configservice:8080

#v1.3升级 v1.4应用后 的check url
http://apollo.ooxx.com/system-info/health?host=apollo03:apollo-adminservice:8090

Instance Id 值显示都变了 
v1.4  显示 instance-300408ep:apollo-configservice:8080
v1.3升级v1.4 后显示 apollo03:apollo-configservice:8080

虽然好像对使用没什么影响,具体其他的还没检测,我只是推了个配置好像能用, 但是这确切不是个完美的方法, 希望提供一下解决方法补充下字段 ,谢谢

**Comment by haoprogrammer** [comment]
同样遇到了这样的问题，请问下这个问题是您怎么解决的。感谢。

**Comment by Scenx** [comment]
请问你是怎么解决的

**Comment by nobodyiam** [comment]
刷新一下浏览器缓存
