### ISSUE TITLE
请问Eureka的集群配置能不能交由Apollo来管理？

### ISSUE THREAD

**Issue by zwdgit** [ctripcorp/apollo#2251]
请问Eureka的集群配置能不能交由Apollo来管理？使得通过Apollo来动态维护Eureka各节点和节点间的关系

**Comment by nobodyiam** [comment]
应该可以的，比如自定义扩展一个EurekaClientConfigBean并实现`org.springframework.cloud.netflix.eureka.EurekaClientConfigBean#getEurekaServerServiceUrls`方法
