### ISSUE TITLE
spring.main.allow-bean-definition-overriding=true 配置失效

### ISSUE THREAD

**Issue by Blovus** [ctripcorp/apollo#2252]
报错如下
![image](https://user-images.githubusercontent.com/26241965/57984923-11449800-7a93-11e9-83cd-6500ccef3dff.png)
原因是Spring Boot 2.1.0 版本以上后，feiginclent不允许重名，所以需要添加该配置。
但在apollo中配置不生效。（加了 apollo.bootstrap.enabled=true 也无效）
spring-boot.version ： 2.1.3.RELEASE
spring-cloud.version ： Finchley.M7
feign.version 2.1.1.RELEASE
不知道哪位大神看一下是怎么回事，是我的问题哈市Apollo有bug？

**Comment by nobodyiam** [comment]
配置一下eagerLoad试试

**Comment by Blovus** [comment]
> 配置一下eagerLoad试试

解决了谢谢。但这样会有什么缺点嘛

**Comment by nobodyiam** [comment]
@Blovus 

缺点是在apollo初始化的时候，日志还没初始化，所以一开始的日志会看不到
