### ISSUE TITLE
apollo版本升级 1.1.0-SNAPSHOT TO 1.4.0

### ISSUE THREAD

**Issue by hdpter** [ctripcorp/apollo#2253]
您好，
我们目前生产使用的是1.1.0-SNAPSHOT版本

apollo-adminserver apollo-configserver apollo-portal 从1.0.0 升级到 1.4.0版本

apollo-client 继续使用1.0.0版本 是否有问题呢？

因为很多工程使用的是apollo-clinet  1.0.0 版本

**Comment by nobodyiam** [comment]
只要服务端的版本比客户端版本高即可
