### ISSUE TITLE
提个需求

### ISSUE THREAD

**Issue by zhaoyunhai1216** [ctripcorp/apollo#2257]
filter.mqtt.server.host=top.mqtt.tusvn.net
filter.mqtt.server.port=1883
filter.mqtt.server.connstr=tcp://${filter.mqtt.server.host}:${filter.mqtt.server.port}

希望能够提供类似上面的， 引用支持

**Comment by nobodyiam** [comment]
如果是把配置注入spring使用的话，天然是支持的，如果是api方式使用的话，目前还不支持
