### ISSUE TITLE
apollo接入ldap后，系统添加的账户无法登陆

### ISSUE THREAD

**Issue by xingmin860818** [ctripcorp/apollo#2258]
apollo接入ldap后，系统已有的账户无法登陆，而且创建时提示500，apollo设计是无法两种账户同时支持的吗？

**Comment by nobodyiam** [comment]
是的，同时只能支持一种账户体系

**Comment by whale2019** [comment]
那admin用户怎么设置呢？

**Comment by BosonMao** [comment]
那接入ldap以后，admin用户怎么设置呢？我用ldap用户登录以后，不能创建部门

**Comment by BosonMao** [comment]
@nobodyiam

**Comment by raoxiaoyan** [comment]
在数据库表serverconfig，修改superadmin，添加用户名即可发自我的华为手机-------- 原始邮件 --------发件人： whale2019 <notifications@github.com>日期： 2019年11月20日周三 11:47收件人： ctripcorp/apollo <apollo@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： Re: [ctripcorp/apollo] apollo接入ldap后，系统添加的账户无法登陆 (#2258)那admin用户怎么设置呢？

**Comment by BosonMao** [comment]
@raoxiaoyan 谢谢，修改以后，重启服务可以了，但是部门这一项 不能手动删除或添加吗？

**Comment by BosonMao** [comment]
@nobodyiam

**Comment by BosonMao** [comment]
数据库里也没看到关于部门的表，求回复啊

**Comment by BosonMao** [comment]
数据库里已经找到了
