### ISSUE TITLE
http long polling接口，是不是post更合适？

### ISSUE THREAD

**Issue by lookstorm** [ctripcorp/apollo#2259]
{config_server_url}/notifications/v2?appId={appId}&cluster={clusterName}&notifications={notifications}

比如notifications是一个数组，如果监听的namespace有数百个，这个http请求肯定会超长，为什么不做成post？

**Comment by nobodyiam** [comment]
因为在语义上是一个 get notifications 的动作，所以权衡再三，还是用了GET
