### ISSUE TITLE
添加了两个权限CreateApplication和AllowAddAppMaster，请问需要pr么

### ISSUE THREAD

**Issue by wkcaeser** [ctripcorp/apollo#2262]
``` txt 
       目前apollo 有简单的账号和权限体系，但是其账号体系（除了超管）内的所有账号在系统内部都是属于平级的，而其权限体系只在单个项目内生效。
```
存在的问题：
- 1、任意账号都拥有新建项目的权限，不利于项目统一管理
- 2、项目管理员（非超管）拥有随意新增项目管理员的权限，不利于权限的管理和限制  
``` txt
      目前我司的公用组件的保密信息（如各类数据库的连接地址 、密码等）是通过一个统一项目配置各种public类型的namespace来统一管理并供需要的项目使用的，但是由于任意账号都有新建项目的权限，在新建项目后通过继承public的namespace可以获取到需要保密的配置信息。
```
所以为了解决这个问题，在1.4的基础上进行了部分开发，主要内容如下：
- 1、添加了两个权限CreateApplication和AllowAddAppMaster
- 2、可以为账号分配CreateApplication权限，有用此权限的账号才允许创建项目，superAdmin账户无影响
- 3、可以为应用分配AllowAddAppMaster权限，分配了此权限的项目，其普通项目管理员才被允许为此项目添加管理员
- 4、新增的两个权限皆可主动分配和收回

**Comment by wkcaeser** [comment]
![image](https://user-images.githubusercontent.com/19384711/58075585-a1412980-7bda-11e9-9d94-85f90c33befa.png)

![image](https://user-images.githubusercontent.com/19384711/58075707-f3824a80-7bda-11e9-8e5b-95536baa0eed.png)



![1](https://user-images.githubusercontent.com/19384711/58075910-6f7c9280-7bdb-11e9-87bb-d2cdbaebc26f.png)

**Comment by nobodyiam** [comment]
非常感谢！

**1. 任意账号都拥有新建项目的权限，不利于项目统一管理**

这个在部分公司确实是个问题，之前的想法是增加一个配置项来控制是否只允许超管来创建项目。

你的建议确实更好，能够把这个权限分给非超管人员，不过这里可能需要考虑的是apollo不只有内置用户的情况，还有大量的sso和ldap接入的情况，对于这类情况该如何分配这个权限得思考一下。

**2. 项目管理员（非超管）拥有随意新增项目管理员的权限，不利于权限的管理和限制**

这个好像目前不是一个普遍的问题

**Comment by wkcaeser** [comment]
针对第一个问题可以进行适配，目前只考虑了内置情况。因为没有接入ldap，所以我还没有了解相应部分的具体逻辑，后续我会调研下，然后给出相应的方案，到时候可以再讨论。

对于第二个我觉得可以把这个功能改成一个配置项，有需要的时候开启就可以了

不过能确认项目有这方面的需求，那么我接下来的开发会考虑兼容性的问题

**Comment by wkcaeser** [comment]
加的这两项功能原本的初衷在于解决公司配置安全性的问题，所以仅针对公司使用的验证方式进行的修改，后续我会处理其他的验证方式

**Comment by station19** [comment]
其实主要是针对  LDAP 之类的 需求比较多, 如果是内置用户 ,完全满足了 ... 都不需要增加权限

一旦接入LDAP 账户多了, 用起来 权限问题 就比较突出, 而且改权限相当累

**Comment by nisiyong** [comment]
> 这个在部分公司确实是个问题，之前的想法是增加一个配置项来控制是否只允许超管来创建项目。

@nobodyiam 这个配置很有用啊，只给超管权限创建已经能满足管理上的要求了。而且改动应该不会特别多，能先添加这个新特性吗？

**Comment by nobodyiam** [comment]
@nisiyong 

先看下 @wkcaeser 这边后续的设想吧，`增加一个配置项来控制是否只允许超管来创建项目`这个可以作为备选方案

**Comment by wkcaeser** [comment]
下周或者下下周我给出方案和pr   然后根据大家建议再进行修改

**Comment by wkcaeser** [comment]
![image](https://user-images.githubusercontent.com/19384711/58849634-a5327880-86bd-11e9-880f-b907095b6f10.png)
大致的交互界面，这两个权限功能都是可配置开启和关闭的，目前在整理中，测试完了可以考虑提pr, 如果我没理解错权限部分的交互逻辑的话，这个应该是各种认证方式都兼容的

**Comment by wkcaeser** [comment]
#2309

**Comment by wkcaeser** [comment]
#2309
