### ISSUE TITLE
单机多进程模型

### ISSUE THREAD

**Issue by neal-zhu** [ctripcorp/apollo#2263]
现在通过 ip 来标示一个客户端的行为对单机多进程的部署情况非常不友好，在灰度下发配置的时候，会导致下发配置的行为未定义。有时候会下发到单个进程，有时候多个。是否可以改为用 ip:port(:timestamp) 的方式来标示一个客户端呢？

**Comment by nobodyiam** [comment]
确实有这个问题，不过ip+port对用户也不友好，除非用户自己去看这个端口是哪个进程的，比如在服务端看到 1.1.1.1:23451和1.1.1.1:25432，其实也分不清谁是谁
