### ISSUE TITLE
Client: Long Polling - doLongPollingRefresh 不停重试后，Cause : unable to create new native thread

### ISSUE THREAD

**Issue by HabenChan** [ctripcorp/apollo#2264]
如下图。

![企业微信截图_15584337163170](https://user-images.githubusercontent.com/15723833/58088750-e58df300-7bf5-11e9-92c3-42ecd0fb7bfe.png)

另外上图红框处的 IP 是如何获取？

**Comment by bg1011** [comment]
应该是本地线程不够了~

https://www.cnblogs.com/myshare/archive/2016/02/02/5177135.html

**Comment by HabenChan** [comment]
@bg1011   thx。

**Comment by cookzhang** [comment]
遇到到同样的问题

`17-Jul-2020 14:57:20.808 警告 [RMI TCP Connection(2)-127.0.0.1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads Web应用程序[citi-out]似乎启动了一个名为[Apollo-RemoteConfigLongPollService-1]的线程，但未能停止它。这很可能会造成内存泄漏。线程的堆栈跟踪：[
 java.net.SocketInputStream.socketRead0(Native Method)
 java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
 java.net.SocketInputStream.read(SocketInputStream.java:171)
 java.net.SocketInputStream.read(SocketInputStream.java:141)
 java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
 java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
 java.io.BufferedInputStream.read(BufferedInputStream.java:345)
 sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
 sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
 sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593)
 sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
 java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
 com.ctrip.framework.apollo.util.http.HttpUtil.doGetWithSerializeFunction(HttpUtil.java:98)
 com.ctrip.framework.apollo.util.http.HttpUtil.doGet(HttpUtil.java:70)
 com.ctrip.framework.apollo.internals.chj.ChjRemoteConfigLongPollService.doLongPollingRefresh(ChjRemoteConfigLongPollService.java:163)
 com.ctrip.framework.apollo.internals.chj.ChjRemoteConfigLongPollService.access$100(ChjRemoteConfigLongPollService.java:42)
 com.ctrip.framework.apollo.internals.chj.ChjRemoteConfigLongPollService$2.run(ChjRemoteConfigLongPollService.java:117)
 java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 java.util.concurrent.FutureTask.run(FutureTask.java:266)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)]
`
