### ISSUE TITLE
DatabaseMessageSender中使用BlockingQueue有些不理解，希望解答

### ISSUE THREAD

**Issue by ooooor** [ctripcorp/apollo#2265]
https://github.com/ctripcorp/apollo/blob/f5c90d58b395e342eef9c732e09d1a1e09754ce2/apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/message/DatabaseMessageSender.java#L30

声明了BlockingQueue<Long> toClean = Queues.newLinkedBlockingQueue(CLEAN_QUEUE_MAX_SIZE)，但代码中只使用了offer/poll，并没有产生阻塞效果，是有什么其他意图嘛，望解答。

**Comment by nobodyiam** [comment]
好像没啥其它意图

**Comment by ooooor** [comment]
好的，就看源码时候有些懵，感谢解答
