### ISSUE TITLE
接入新环境问题

### ISSUE THREAD

**Issue by henryjun0** [ctripcorp/apollo#2266]
在原有dev环境基础上，接入了新环境fat，数据库初始化，迁移都做了，portal没有报错，但是原来dev数据展示不正确，每刷一次都不一样，一会新建未发布，一会删除未发布，一会已发布，公共属性一直都是删除未发布，不知道为什么

**Comment by nobodyiam** [comment]
看现象是两个环境的eureka互相注册了
