### ISSUE TITLE
解决一个服务启动失败的问题

### ISSUE THREAD

**Issue by hunterlodge** [ctripcorp/apollo#2267]
今天遇到config-service启动超时并且失败的问题，没有在日志目录中看到任何日志，后来偶然注意到启动脚本输出中打印的日志:
Already running [5567] 
就猜想是不是因为pid文件引起的（因为我们的服务器昨晚异常重启过，实际上5567号进程更根本不存在）。删除目录下的apollo-adminservice_softwareinstallationsapolloadmin-service.pid文件，果然启动成功了

因为没有日志，花了挺长时间调查这个问题，特此分享！

希望apollo能优化一下，至少在日志中体现出问题原因，或者提高容错性！

**Comment by nobodyiam** [comment]
我在当前版本测试了一下，貌似没有这个问题，因为在下面的脚本里面会先通过`isRunning "$pid"`来判断pid是否运行的，可以通过`vi apollo-configservice.jar`来查看启动脚本。

```bash
132 # Action functions
133 start() {
134   if [[ -f "$pid_file" ]]; then
135     pid=$(cat "$pid_file")
136     isRunning "$pid" && { echoYellow "Already running [$pid]"; return 0; }
137   fi
138   do_start "$@"
139 }
```
