### ISSUE TITLE
.net 客户端无法像java一样获取k8s的正确地址

### ISSUE THREAD

**Issue by jxharp** [ctripcorp/apollo#2269]
.net 客户端无法跳过meta service的服务发现，应该是没这个功能。  最近在阿里云上的k8s里面测试apollo，也是同样的问题，只能获取内网ip. 暂时无奈只能放弃apollo了。只要能解决立马回来

**Comment by nobodyiam** [comment]
如果公司有.net开发同学的话，可以仿照java的加一下这个逻辑，代码逻辑还是比较简单的，#1275
