### ISSUE TITLE
在kubernetes中使用apollo配置中心缓存目录问题

### ISSUE THREAD

**Issue by zewade** [ctripcorp/apollo#2271]
你好，请问在kubernetes环境中使用apollo配置中心时，是否有必要将每个微服务的apollo缓存目录挂载到容器外，以保证apollo不可用时，服务还能读取到配置。如果同一个微服务起了多个副本是否可以挂载到同一个缓存目录，会不会引起冲突？

**Comment by nobodyiam** [comment]
建议独立挂载，比如对于灰度发布场景，同一个微服务的不同机器上的配置可能是不同的

**Comment by zewade** [comment]
> 建议独立挂载，比如对于灰度发布场景，同一个微服务的不同机器上的配置可能是不同的

感谢回复，另外在k8s或者docker跑的话，灰度发布是否不好用，因为要配置灰度生效的IP，而容器的IP每次重启都会变化。

**Comment by nobodyiam** [comment]
是的，目前对动态IP的场景还没想好如何支持灰度发布，如果有好的建议也欢迎提出

**Comment by kingtiger2** [comment]
@nobodyiam 我有个想法,k8s的ip规则有规律,每台机器的网段是固定的.比如172.12.20.* .如果apollo的管理界面能支持这种模糊的ip匹配,也是一种解决办法

**Comment by nobodyiam** [comment]
@kingtiger2 这是一个可以实现的方案，不过不确定是否具有普适性，后续可能更希望基于k8s的label来实现灰度。

**Comment by kingtiger2** [comment]
lable的话涉及到k8s的api了,会不会麻烦,可否考虑基于版本

**Comment by nobodyiam** [comment]
版本具体是指？这里的关键点其实在于apollo需要有一个通用的标识能识别出需要被灰度的客户端，只要有了这个标识，灰度的实现就自然而然了
