### ISSUE TITLE
关联了其他appId的public namespce后，拉取不到继承的配置信息

### ISSUE THREAD

**Issue by mqmjingba** [ctripcorp/apollo#2282]
采用spring boot 集成的方式，在一个appid中创建了一个public的命名空间（jyxsh.jyxsh.base-conf），在新的appid里面关联这个公共命名空间，关联后在客户端的配置如下：app.id=jyxsh
apollo.meta=http://192.168.1.196:8080
apollo.bootstrap.enabled = true
apollo.bootstrap.namespaces =jyxsh.jyxsh.base-conf
结果只有当前关联内新加的配置信息可以读取，继承的公共命名空间的配置信息无法被拉去，采用了JAVA API的方式也拉去不到

**Comment by mqmjingba** [comment]
@nobodyiam 帮忙确认细是我用法不对吗？

**Comment by mqmjingba** [comment]
已经可以复现这个问题了，admin、config 两个服务重启下就可以解决这个问题，正在排查原因

**Comment by nobodyiam** [comment]
是否有人工操作数据库的情况？

**Comment by mqmjingba** [comment]
没有，我在一个QQ群里面说过这个事，但是没有任何人回答，我就自己弄源码想看看，结果一跑源码发现是好的，后来定位到只要重启下就可以，怀疑命名空间的刷新机制有问题，话说哪里讨论Apollo的比较，准备深度使用，之前加的那个群发现没有讨论问题的

**Comment by nobodyiam** [comment]
config service里面有appnamespace的缓存，如果有人工修改数据库的情况才会出现在一段时间内缓存可能和数据库不一致的情况，具体可以看一下com.ctrip.framework.apollo.configservice.service.AppNamespaceServiceWithCache

**Comment by mqmjingba** [comment]
好的，谢谢
