### ISSUE TITLE
apollo对xml/json/yml的支持

### ISSUE THREAD

**Issue by yangweiy2018** [ctripcorp/apollo#2283]
database中是以KV的形式存储,那么能不能除了properties以外的其他格式也转换成KV去存储,而不是简单的直接定义一个content: data,来存储.

**Comment by nobodyiam** [comment]
xml, json这种都没法转换成KV存储的吧

**Comment by yangweiy2018** [comment]
可以的哈 比如 ｛a：｛b:1}} 可以转换成a:b=1 这样的 我写了一个jsonresolve的扩展 同理XML也可以 而不是把它们当成value 指定content为key 发自我的华为手机-------- 原始邮件 --------主题：Re: [ctripcorp/apollo] apollo对xml/json/yml的支持 (#2283)发件人：Jason Song 收件人：ctripcorp/apollo 抄送：yangweiy2018 ,Author xml, json这种都没法转换成KV存储的吧

**Comment by nobodyiam** [comment]
这个看上去不是标准的处理方式吧。。

**Comment by yangweiy2018** [comment]
应该是标准的，至少net core 自带的iconfiguration 是这样处理的 并且json XML 本身也是键值对发自我的华为手机-------- 原始邮件 --------主题：Re: [ctripcorp/apollo] apollo对xml/json/yml的支持 (#2283)发件人：Jason Song 收件人：ctripcorp/apollo 抄送：yangweiy2018 ,Author 这个看上去不是标准的处理方式吧。。

**Comment by nobodyiam** [comment]
是否有啥相关的文章介绍？

**Comment by yangweiy2018** [comment]
Hi Jason,


你可以去读.net core 对configuration处理的源码,还有就是可以参考json转Map对象的时候,如果是数组,应该怎么转换.


thanks.




------------------ Original ------------------

**Comment by czd890** [comment]
xml 没法这么处理，分不清楚那个是attribute，那个是childnode. @yangweiy2018
