### ISSUE TITLE
接入SSO

### ISSUE THREAD

**Issue by rhaonan** [ctripcorp/apollo#2285]
目前线上使用了Spring Security的用户登录体系，数据库里保留的都是这些用户，如果想迁移换成接入公司SSO登录的话应该如何做呢？  
迁移替换的代价大么，已经入库的用户数据需要全部清洗么？ 有没有案例参考一下~ 感谢~

**Comment by nobodyiam** [comment]
只要用户名一样的话，没有迁移成本，如果用户名不一样的话，需要洗一遍数据

**Comment by rhaonan** [comment]
> 只要用户名一样的话，没有迁移成本，如果用户名不一样的话，需要洗一遍数据

用户名很多不一样，那么config库里涉及到用户名的表都需要清洗对吧？

另外还有一个问题请教下，使用SSO登录portal库里users表应该没有用了吧，看了下ctrip的UserService接口实现是用的都是rest api，都是直接调用ctrip的SSO系统拿的用户信息么？

**Comment by rhaonan** [comment]
> > 只要用户名一样的话，没有迁移成本，如果用户名不一样的话，需要洗一遍数据
> 
> 用户名很多不一样，那么config库里涉及到用户名的表都需要清洗对吧？
> 
> 另外还有一个问题请教下，使用SSO登录portal库里users表应该没有用了吧，看了下ctrip的UserService接口实现是用的都是rest api，都是直接调用ctrip的SSO系统拿的用户信息么？

**Comment by nobodyiam** [comment]
ctrip登录用的是sso，搜索用户是调用rest api

**Comment by rhaonan** [comment]
最后实现搜索用户还保留了users表，首次SSO登录的用户，会在users表里记录一条数据。

**Comment by maxiaoyin** [comment]
> ctrip登录用的是sso，搜索用户是调用rest api



SSO，需要在哪里设置cookie和session呢，我最近也在对接SSO，这块我是一头雾水，能大概指导下么
