### ISSUE TITLE
修改为自己的eureka之后，多环境下添加配置失效

### ISSUE THREAD

**Issue by wangjinhe** [ctripcorp/apollo#2287]
先描述一下我的配置：

1. 按照wiki上的提示配置为自己的eureka，https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#8-%E5%B0%86config-service%E5%92%8Cadmin-service%E6%B3%A8%E5%86%8C%E5%88%B0%E5%8D%95%E7%8B%AC%E7%9A%84eureka-server%E4%B8%8A

2.  开发环境部署config-server和admin-server和 Portal
3.  测试环境部署config-server和admin-server(说明：目前我们还没有测试环境，只是在一台机器上部署了这两个服务)
4.  开发和测试环境连接相同的eureka(都是开发环境的eureka)

问题如下：

1. 通过 Portal在开发环境添加配置，发布之后，多刷新几次页面，又变成了未发布状态，提示“有修改”，有时还显示“已删除”

后来看到系统信息中，每一个环境下，都有多个admin-server和config-server

请问作者，是不是不同环境的config-server不能注册到相同的eureka上？ @nobodyiam

**Comment by wangjinhe** [comment]
![Uploading image.png…]()

**Comment by wangjinhe** [comment]
![22](https://user-images.githubusercontent.com/12496272/58457462-5a62af00-8159-11e9-95c2-a06070f85ea7.png)

**Comment by nobodyiam** [comment]
开发和测试环境要连接不同的eureka

**Comment by wangjinhe** [comment]
好的，非常谢谢

**Comment by wwr** [comment]
> 开发和测试环境要连接不同的eureka

如果开发和测试等多个环境是同一个Eureka集群，是不是意味着多环境这项功能基本没用了？只能通过不同环境指定不同的app id？或者直接使用Apollo默认自带的Eureka注册中心

**Comment by nobodyiam** [comment]
如果是这样的话，还是建议使用Apollo默认自带的Eureka注册中心
