### ISSUE TITLE
关于集群cluster指定问题

### ISSUE THREAD

**Issue by nisiyong** [ctripcorp/apollo#2289]
你好，我仔细阅读了"Java客户端使用指南"，我实现了MetaServerProvider，利用环境变量ENV来选择meta server的地址。

目前应用启动只需配置环境变量ENV即可，但是在Apollo多集群的情况下，需要指定-Dapollo.cluster或-Didc，我想请问下cluster可以支持环境变量指定吗？比如APOLLO_CLUSTER。

**Comment by nobodyiam** [comment]
可以通过环境变量`IDC`

**Comment by nisiyong** [comment]
感谢，测试可以。我关闭issue吧
