### ISSUE TITLE
关于SpEL的支持问题

### ISSUE THREAD

**Issue by xuyuji** [ctripcorp/apollo#2290]
各位好：
        我这几天看了下apollo-client的实现，了解到SpringValueProcessor和SpringValueDefinitionProcessor都过滤掉了非${...}模式的Value处理，然后在PlaceholderHelper.resolvePropertyValue里面看到了对SpEL的处理，如下：
    // resolve expressions like "#{systemProperties.myProp}
    return evaluateBeanDefinitionString(beanFactory, strVal, bd);
很好奇这是什么玩法，前面明明已经过滤掉了，或者还有其他什么地方有处理我没注意到？

望解惑。

**Comment by nobodyiam** [comment]
com.ctrip.framework.apollo.spring.property.SpringValue#placeholder，这个存的是原始的placeholder

**Comment by xuyuji** [comment]
@nobodyiam 这个我知道，在保存SpringValue之前，有通过placeholderHelper.extractPlaceholderKeys处理value值，只处理${}参数，#{}形式的都被过滤掉了。
按这个逻辑，springValueRegistry中保存的SpringValue里应该是没有SpEL形式的记录的。

**Comment by nobodyiam** [comment]
建议debug一下源码会更清楚一些
