### ISSUE TITLE
请问apollo是否可以管理nginx的配置文件

### ISSUE THREAD

**Issue by tpeng1129** [ctripcorp/apollo#2291]
项目的nginx配置文件经常变动，不知是否可以让apollo管理nginx的conf配置文件，让nginx从apollo读取conf配置

**Comment by nobodyiam** [comment]
可以的，ctrip就有这种用法，可以通过rest接口拉取配置后写入conf文件

**Comment by tpeng1129** [comment]
apollo里的配置文件没有conf，是否需要存成properties，然后自行解析数据后生成conf文件到nginx服务器

**Comment by nobodyiam** [comment]
可以用txt格式，私有namespace

**Comment by Jerrywgl** [comment]
您好按照您的方法，我获取到配置配置列表如下:

'003', 'cluster' => 'default', 'namespaceName' => 'nginx.conf', 'configurations' => array ( 'haha' => '1222', 'work' => '1000', 'worker_connections' => '10240', 'worker_processes' => '4', 'worker_rlimit_nofile' => '10000', 'listen' => '8080', ), 'releaseKey' => '20191104181002-f4a91b6436099406', ); 这个格式nginx是不能直接用，得自己写脚本解析下格式吗?非常感谢

**Comment by JaredTan95** [comment]
> 您好按照您的方法，我获取到配置配置列表如下:
> 
> '003', 'cluster' => 'default', 'namespaceName' => 'nginx.conf', 'configurations' => array ( 'haha' => '1222', 'work' => '1000', 'worker_connections' => '10240', 'worker_processes' => '4', 'worker_rlimit_nofile' => '10000', 'listen' => '8080', ), 'releaseKey' => '20191104181002-f4a91b6436099406', ); 这个格式nginx是不能直接用，得自己写脚本解析下格式吗?非常感谢

是的。
