### ISSUE TITLE
添加@RefreshScope 的ConfigurationProperties配置类无法动态刷新配置

### ISSUE THREAD

**Issue by yingziisme** [ctripcorp/apollo#2292]
使用applicationContext.publishEvent(new EnvironmentChangeEvent(changeEvent.changedKeys()));
来动态刷新配置的时候，如果该配置类上有@RefreshScope ，则无法更新配置项
去掉这个注解即正常使用

**Comment by nobodyiam** [comment]
EnvironmentChangeEvent或RefreshScope两者取其一即可，如果有兴趣的话可以看下spring cloud中相关的代码，应该是代码中有判断的

**Comment by kostark** [comment]
apollo 1.4.0 + sc G3，根据 wiki 文档和 `ConfigurationProperties` 自动刷新的示例代码，不能获取刷新到最新的值。

```java
@Data
@RefreshScope
@Component
@ConfigurationProperties("env")
public class EnvConfig {
	private String name;
	private App app;
	private Database database;

        @PostConstruct
	private void post() {
                log.info("..."); // this.toString();
        }
}
```
顺序如下：
- 启动应用，输出 post 方法日志，对应 rest 接口返回正确数据
- 修改配置并发布
- 控制台输出获取到的最新配置，此时没有执行 post 方法。请求 rest 接口返回的是旧版配置信息

**Comment by nobodyiam** [comment]
需要显式调用refreshScope.refresh

**Comment by kostark** [comment]
@nobodyiam 谢谢，看来是我理解错了。
