### ISSUE TITLE
容器化下，灰度如何不依赖ip配置

### ISSUE THREAD

**Issue by larryxuzhen** [ctripcorp/apollo#2293]
k8s中，一个应用的ip可能漂移，但是apollo的灰度好像必须显示配置固定ip，能不能通过百分比配置，比如30%的当前实例使用灰度配置，其他使用原配置。

**Comment by nobodyiam** [comment]
对于k8s的场景确实需要解一下灰度配置的规则问题，之前有想法是借助于label来实现，使用百分比来实现的话，还没想清楚一些细节
