### ISSUE TITLE
spring4(不是springboot)如何使用jasypt集成apollo，目前spring4和jasypt测试正常

### ISSUE THREAD

**Issue by tqy-github** [ctripcorp/apollo#2295]
spring4(不是springboot)如何使用jasypt集成apollo，目前spring4和jasypt测试正常，但是在xml配置<apollo:config/>就报错，请问Apollo在spring（注意不是springboot）下支持集成jasypt吗？如果不支持，自己实现有什么好的思路？

**Comment by nobodyiam** [comment]
apollo和spring集成，jasypt和spring集成，所以apollo和jasypt之间应该没啥关系

如果有报错的话，可以看下报错信息

**Comment by tqy-github** [comment]
通过调试验证，当xml存在加载本地properties和apollo同时，apollopropertyConfigurer中配置order=0才能拿到本地配置，否则xml配置了EL ${...}注入参数时，在容器启动会报错参数找不到：

  <bean id="environmentVariablesConfiguration"
    class="org.jasypt.encryption.pbe.config.EnvironmentStringPBEConfig">
  <property name="algorithm" value="PBEWithMD5AndDES" />
  <property name="password" value="xxx" />
  </bean>

  <bean id="configurationEncryptor"
    class="org.jasypt.encryption.pbe.StandardPBEStringEncryptor">
    <property name="config" ref="environmentVariablesConfiguration" />
  </bean>

  <bean id="propertyConfigurer"  
    class="org.jasypt.spring4.properties.EncryptablePropertySourcesPlaceholderConfigurer">
    <constructor-arg ref="configurationEncryptor" />
    <property name="locations">
      <list>
        <value>classpath:application.properties</value>
      </list>
    </property>
  <property name="order" value="0"></property>
  </bean>
  <apollo:config />
  <bean class="com.ysm.config.Data" id="data">
    <property name="username" value="${db.password}"></property>
  </bean>
现在最新的问题是，本地properties加密串可以自动解密，apollo的参数没有自动解密，上面配置有问题吗

**Comment by tqy-github** [comment]
通过调试验证，当xml存在加载本地properties和apollo同时，apollopropertyConfigurer中配置order=0才能拿到本地配置，否则xml配置了EL ${...}注入参数时，在容器启动会报错参数找不到：
`  
  <bean id="environmentVariablesConfiguration"
    class="org.jasypt.encryption.pbe.config.EnvironmentStringPBEConfig">
  <property name="algorithm" value="PBEWithMD5AndDES" />
  <property name="password" value="xxx" />
  </bean>

  <bean id="configurationEncryptor"
    class="org.jasypt.encryption.pbe.StandardPBEStringEncryptor">
    <property name="config" ref="environmentVariablesConfiguration" />
  </bean>

  <bean id="propertyConfigurer" 
    class="org.jasypt.spring4.properties.EncryptablePropertySourcesPlaceholderConfigurer">
    <constructor-arg ref="configurationEncryptor" />
    <property name="locations">
      <list>
        <value>classpath:application.properties</value>
      </list>
    </property>
  <property name="order" value="0"></property>
  </bean>
  <apollo:config />
  <bean class="com.xxx.config.Data" id="data">
    <property name="username" value="${db.password}"></property>
  </bean>`
现在最新的问题是，本地properties加密串可以自动解密，apollo的参数没有自动解密，上面配置有问题吗

**Comment by tqy-github** [comment]
<bean id="environmentVariablesConfiguration"
    class="org.jasypt.encryption.pbe.config.EnvironmentStringPBEConfig">
  <property name="algorithm" value="PBEWithMD5AndDES" />
  <property name="password" value="xxx" />
  </bean>

**Comment by tqy-github** [comment]
` 
  <bean id="environmentVariablesConfiguration"
    class="org.jasypt.encryption.pbe.config.EnvironmentStringPBEConfig">
  <property name="algorithm" value="PBEWithMD5AndDES" />
  <property name="password" value="xxx" />
  </bean>`

**Comment by tqy-github** [comment]
通过调试验证，当xml存在加载本地properties和apollo同时，apollopropertyConfigurer中配置order=0才能拿到本地配置，否则xml配置了EL ${...}注入参数时，在容器启动会报错参数找不到：
` 
  <bean id="environmentVariablesConfiguration"
    class="org.jasypt.encryption.pbe.config.EnvironmentStringPBEConfig">
  <property name="algorithm" value="PBEWithMD5AndDES" />
  <property name="password" value="xxx" />
  </bean>`
` <bean id="configurationEncryptor"
    class="org.jasypt.encryption.pbe.StandardPBEStringEncryptor">
    <property name="config" ref="environmentVariablesConfiguration" />
  </bean>`
`  <bean id="propertyConfigurer"
    class="org.jasypt.spring4.properties.EncryptablePropertySourcesPlaceholderConfigurer">
    <constructor-arg ref="configurationEncryptor" />
    <property name="locations">
      <list>
        <value>classpath:application.properties</value>
      </list>
    </property>
  <property name="order" value="0"></property>
  </bean>`
` <bean class="com.xxx.config.Data" id="data">
    <property name="username" value="${db.password}"></property>
  </bean>`
现在最新的问题是，本地properties加密串可以自动解密，apollo的参数没有自动解密，上面配置有问题吗

**Comment by nobodyiam** [comment]
我们只测试过spring boot jasypt，没测试过单独jasypt的，你能方便上传一个有问题的demo程序吗？

**Comment by xlixlixli** [comment]
@tqy-github 你的问题解决了吗，spring怎么在集成Apollo之后进行敏感信息解密呢？

**Comment by likeSquirrel** [comment]
@tqy-github 我重写了RemoteConfigRepository类中的getConfig方法，手动解密的。
