### ISSUE TITLE
如果namespace太多，页面会卡顿吗？

### ISSUE THREAD

**Issue by lookstorm** [ctripcorp/apollo#2297]
比如同一个应用的某个集群下总共有一万多个namespace，页面是一次性加载出所有namespace来显示吗？如果只想修改其中的一个namespace，有没有快捷搜索之类的功能？

**Comment by nobodyiam** [comment]
现在是这样的效果

![image](https://user-images.githubusercontent.com/837658/58748445-9f654900-84ab-11e9-810c-66eca568de0d.png)

**Comment by lookstorm** [comment]
> 现在是这样的效果
> 
> ![image](https://user-images.githubusercontent.com/837658/58748445-9f654900-84ab-11e9-810c-66eca568de0d.png)

如果单页namespace太多，有没有快捷搜索指定namespace的方法？

**Comment by lepdou** [comment]
> 如果单页namespace太多，有没有快捷搜索指定namespace的方法？

Ctrl + F O__O "…
