### ISSUE TITLE
apollo.bootstrap.namespaces 配置没有作用

### ISSUE THREAD

**Issue by qianglu1989** [ctripcorp/apollo#2298]
version:1.4.0
在yml 和 properties 中都试验了 apollo.bootstrap.namespaces 这个属性 没有任何效果，程序还是默认读取 application,配置如下
 apollo.bootstrap.enabled = true
apollo.bootstrap.namespaces=application,jg.pub-test
程序不读取 jg.pub-test 公共配置 
只有这么配置 @EnableApolloConfig({"application","jg.pub-test"})
才会读取 jg.pub-test 公共配置 

看了下加在源码 发现如下
![image](https://user-images.githubusercontent.com/8486184/58680114-0219f000-8399-11e9-9399-fc507a394ecf.png)
这个是写死了加载吗，还是说现有版本已经不支持apollo.bootstrap.namespaces 加载方式了，当然 -D 的启动方式也不好使
这个是使用问题还是版本bug

**Comment by qianglu1989** [comment]
这个公共配置目前只能针对于自己项目体系吗，能否支持全部项目，非同一app.id的项目

**Comment by nobodyiam** [comment]
com.ctrip.framework.apollo.spring.boot.ApolloApplicationContextInitializer#initialize(org.springframework.core.env.ConfigurableEnvironment)
