### ISSUE TITLE
docker快速启动，ide工具联调存在问题。

### ISSUE THREAD

**Issue by Jxin-Cai** [ctripcorp/apollo#2302]
RemoteConfigRepository类,205行assembleQueryConfigUrl()方法获得url为机器上的ip地址。而如果是访问的docker容器挂载的宿主机。那么这个url的ip会变成容器的vip。进而宿主机外部的网络便访问不到这个url。 所以，快速启动demo里面，docker单机项目无法使用。除非将jar包也做容器编排，并和apollo放在同个网络。 对开发体验极不友好。

**Comment by nobodyiam** [comment]
参考一下[admin server 或者 config server 注册了内网IP，导致portal或者client访问不了admin server或config server](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#3-admin-server-%E6%88%96%E8%80%85-config-server-%E6%B3%A8%E5%86%8C%E4%BA%86%E5%86%85%E7%BD%91ip%E5%AF%BC%E8%87%B4portal%E6%88%96%E8%80%85client%E8%AE%BF%E9%97%AE%E4%B8%8D%E4%BA%86admin-server%E6%88%96config-server)

**Comment by wfp119** [comment]
我也是这个情况，需要自己制作镜像吗？docker部署使用外部机器部署的项目获取配置有些麻烦

**Comment by SingleDispatcher** [comment]
> 我也是这个情况，需要自己制作镜像吗？docker部署使用外部机器部署的项目获取配置有些麻烦

上面大佬提供的连接我尝试了，没成功，容器里面不识别宿主机外网Ip。docker快速启动基本算废了，失去简单易用的特性。

1.如果是学习，建议走同局域网，且不用容器编排搭建，手搭后就不存在返回无法识别的内网地址这种bug了。
2.如果是公司环境搭建，用容器编排将所有服务至于同一个网络下就能识别了。
