### ISSUE TITLE
apollo-client版本向下兼容不

### ISSUE THREAD

**Issue by hanyidreamer** [ctripcorp/apollo#2304]
RT,以前基于1.1.0用了很久，若client升级1.3.0，服务端不升级能兼容不？

**Comment by nobodyiam** [comment]
一般的兼容是指客户端老版本，服务端新版本的情况，这个apollo是肯定兼容的。

你这个不太一样，不过看了一下，apollo client 1.3.0和apollo config service 1.1.0应该也是兼容的。

**Comment by hanyidreamer** [comment]
ok，了解，主要是对1.1.0服务端有一些改造，暂时未升级情况下有项目需要使用yml相关配置，大致试了下拉取暂时没发现什么问题
