### ISSUE TITLE
/META-INF/app.properties 中设置 cacheDir 的问题

### ISSUE THREAD

**Issue by erystasius** [ctripcorp/apollo#2306]
看了文档和源码，发现并不支持从 /META-INF/app.properties 中设置 cacheDir，不知是出于什么考虑。

我们现在面临的问题是，同一台机器会运行同一个应用的多个实例，每个实例对应不同的环境，因此会链接不同的 Apollo Server。因此需要通过配置 cacheDir 区分不同的 Apollo Server 的缓存文件。这种场景下，机器级别的 System Environment 和 server.properties 都不适用，同时我们的应用也不是 Spring Boot 应用。Java System Properties 是有效的，但是我们比较希望把这个配置打进包里来方便管理。

希望可以从 /META-INF/app.properties 中配置 cacheDir，不知能否支持？

**Comment by lepdou** [comment]
> 看了文档和源码，发现并不支持从 /META-INF/app.properties 中设置 cacheDir，不知是出于什么考虑

这个是因为之前没有考虑到单机部署多实例的场景。

这个最快的解决办法是自己实现一下，在 /META-INF/app.properties 增加 cacheDir 配置项，并且 System Environment > server.properties > /META-INF/app.properties。

**Comment by erystasius** [comment]
OK，我实现一下提个 PR

**Comment by DuLerWeil** [comment]
> OK，我实现一下提个 PR

哈，被你早一步，我们的项目和你的场景完全一样，也是自己临时改了client源码应急的。准备回头来提PR。。
