### ISSUE TITLE
代码下载下来后，如何开始？

### ISSUE THREAD

**Issue by liangjian103** [ctripcorp/apollo#2310]
代码下载下来后，如何开始？
希望能提供详细的步骤 把它运行起来，例如创建数据库 初始化脚本，修改某个配置文件 连接自己的数据库，这些都找不到，弄了一下午 没把程序跑起来，看说明都是运行后的。 我现有工程如何与之结合，需要做哪些修改？ 希望能在这方面有说明，这样我们也好快速的上手使用和优化它。

**Comment by nobodyiam** [comment]
建议先参考一下[Quick Start](https://github.com/ctripcorp/apollo/wiki/Quick-Start)把apollo跑起来体验一下，现有工程如何结合可以参考[Java客户端使用指南](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)、[.Net客户端使用指南](https://github.com/ctripcorp/apollo/wiki/.Net%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)、[Go、Python、NodeJS、PHP等客户端使用指南](https://github.com/ctripcorp/apollo/wiki/Go%E3%80%81Python%E3%80%81NodeJS%E3%80%81PHP%E7%AD%89%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)

后续要真实部署的话，可以参考[分布式部署指南](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97)
