### ISSUE TITLE
登录portal后js频繁报错

### ISSUE THREAD

**Issue by yipingw** [ctripcorp/apollo#2312]
apollo版本：1.4.0
k8s版本：alicloud 1.12
部署方式：k8s，所有pod运行正常，容器应用运行正常，内网通讯无任何问题
访问方式：公网ip+端口

问题描述：
使用默认用户名密码登录后页面内容丢失，打开chrome的devtool查看有angular相关的js报错，初步判断是没拿到数据库数据导致，但我已按照本项目中k8s教程执行了相关的sql，请指教。

内容一片空白
![image](https://user-images.githubusercontent.com/2724357/58925557-952c9e80-877a-11e9-9c68-ccf53fbbd4bb.png)

报angular相关js错误
![image](https://user-images.githubusercontent.com/2724357/58925593-ab3a5f00-877a-11e9-8d10-2b8486538490.png)

详细错误信息
![image](https://user-images.githubusercontent.com/2724357/58925611-b5f4f400-877a-11e9-91c8-4a2b0a1738c3.png)

![image](https://user-images.githubusercontent.com/2724357/58925624-bee5c580-877a-11e9-879a-2c75b0ab64df.png)

![image](https://user-images.githubusercontent.com/2724357/58925640-c86f2d80-877a-11e9-84b1-a8af63728fbb.png)

**Comment by nobodyiam** [comment]
首先可以尝试一下把ajax访问的url直接通过浏览器访问看看得到什么结果

其次可以看一下portal服务端的日志

**Comment by yipingw** [comment]
问题原因找到了，我登录到数据库所在容器，查看日志发现access denied的错误，判断可能和在k8s中创建的portal相关service有关，再次检查portal的mysql服务，发现该服务没有指向正确的mysql容器，更新配置后问题解决。谢谢宋顺兄！
