### ISSUE TITLE
apollo有没有初始化属性完成事件？

### ISSUE THREAD

**Issue by songwei1024** [ctripcorp/apollo#2314]
您好，我将logback.xml放在了apollo中管理，通过实现Slf4JLoggingSystem来自行加载日志系统；但是apollo初始化在日志加载前面，所以初始化阶段不会有任何日志输出；
我想在apollo拉取配置阶段延用代码中的logback.xml文件，等初始化完成后有个事件可以让我重新加载apollo里的logback配置，从而完成日志的动态管理，不知道这类事件是否能提供呢？

**Comment by nobodyiam** [comment]
可以参考[spring-cloud-logger](https://github.com/ctripcorp/apollo-use-cases/tree/master/spring-cloud-logger)
