### ISSUE TITLE
apollo-client 支持服务名访问吗？

### ISSUE THREAD

**Issue by 2229499815** [ctripcorp/apollo#2319]
为什么apollo不支持服务名访问？看了一些相关介绍，多环境配置通过maven -p参数去指定，然后上线同样需要修改环境地址，这样不是很友好，如果需要实现线上线下环境自动切换需要通过添加代码的方式去做环境判断，如果能支持服务名访问，那么就可以做到代码0入侵。

**Comment by nobodyiam** [comment]
目前apollo的方式是通过预先提供meta server地址（{env}.meta或apollo.meta）的方式实现一套代码在不同环境运行，是支持代码0入侵的。

如果要通过服务名访问的话，那就需要依赖服务注册中心了，然后就需要配置服务注册中心的地址，本质上是一样的吧，而且一般设计上配置中心比服务注册中心更下层，也就意味着配置中心不能依赖服务注册中心。
