### ISSUE TITLE
客户端支持跨系统监听吗？

### ISSUE THREAD

**Issue by DeanJi** [ctripcorp/apollo#2323]
监控系统Monitor想监听应用系统APP1的配置变化，支持吗？

**Comment by nobodyiam** [comment]
原生的sdk不支持跨系统监听，可以直接通过http接口来监听，详见[其它语言客户端接入指南](https://github.com/ctripcorp/apollo/wiki/%E5%85%B6%E5%AE%83%E8%AF%AD%E8%A8%80%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97)
