### ISSUE TITLE
0.9升级1.4.0后，用户管理相关功能失效

### ISSUE THREAD

**Issue by imshi** [ctripcorp/apollo#2327]
原0.9版本：编译安装
目标1.4.0版本：直接下载release包安装
各项配置修改启动成功后，portal页面上用户相关的接口（用户搜索、添加等）都会报500错误，请教怎么解决

**Comment by imshi** [comment]
apollo-portal相关ERROR日志如下：
`
28624 2019-06-11 18:36:48.013 ERROR 7553 --- [http-nio-8070-exec-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : Unknown column 'userpo0_.Email' in 'field list'
28625 2019-06-11 18:36:48.014 ERROR 7553 --- [http-nio-8070-exec-3] .c.f.a.c.c.GlobalDefaultExceptionHandler : could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exce
      ption.SQLGrammarException: could not extract ResultSet
`

**Comment by nobodyiam** [comment]
0.9.0到1.4.0没有schema change，从上面的error日志中貌似看不出是啥原因导致的

**Comment by imshi** [comment]
嗯，看更新日志的确没有schema change，这边隔天重启portal后奇迹般的正常了，搞不清楚什么原因。。
先感谢吧~
