### ISSUE TITLE
项目启动报WARN

### ISSUE THREAD

**Issue by liuzedong** [ctripcorp/apollo#2328]
## 日志
2019-06-12 12:04:59.670|/|WARN |main|o.s.b.c.p.PropertySourcesDeducer|Multiple PropertySourcesPlaceholderConfigurer beans registered [propertySourcesPlaceholderConfigurer, org.springframework.context.support.PropertySourcesPlaceholderConfigurer], falling back to Environment

## Apollo Client  => ConfigPropertySourcesProcessor
![image](https://user-images.githubusercontent.com/13012417/59322808-99246780-8d0a-11e9-89f9-f691a6846d47.png)

## Spring boot  => org.springframework.boot.context.properties.PropertySourcesDeducer
![image](https://user-images.githubusercontent.com/13012417/59322909-f3bdc380-8d0a-11e9-8fa1-6d0499a62b45.png)

## 
这个能修复下吗？ 项目使用 sentry， 每次项目启动 都收到 邮件提醒。

**Comment by nobodyiam** [comment]
apollo在注册PropertySourcesPlaceholderConfigurer时会检查是否已经存在这个bean的，如果不存在才会添加。

建议在报warning的地方加个断点看下另外一个bean是谁加进来的。

**Comment by liuzedong** [comment]
PropertySourcesPlaceholderConfigurer 这个bean是在，spring-boot-autoconfigure.jar : org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration
中加载进来的，
![image](https://user-images.githubusercontent.com/13012417/59970893-c6db9d00-95a3-11e9-9942-97d9db392977.png)

**Comment by nobodyiam** [comment]
我跑了[SpringBootSampleApplication](https://github.com/ctripcorp/apollo/blob/master/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/spring/springBootDemo/SpringBootSampleApplication.java)这个sample，貌似没能复现这个问题？

**Comment by liuzedong** [comment]
异常：2019-06-27 10:27:31.108  INFO 7255 --- [           main] com.example.demo.DemoApplication         : No active profile set, falling back to default profiles: default
2019-06-27 10:27:31.533  INFO 7255 --- [           main] o.s.c.a.ConfigurationClassPostProcessor  : Cannot enhance @Configuration bean definition 'com.ctrip.framework.apollo.spring.boot.ApolloAutoConfiguration' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.
2019-06-27 10:27:33.731  WARN 7255 --- [           main] o.s.b.c.p.PropertySourcesDeducer         : Multiple PropertySourcesPlaceholderConfigurer beans registered [propertySourcesPlaceholderConfigurer, org.springframework.context.support.PropertySourcesPlaceholderConfigurer], falling back to Environment
2019-06-27 10:27:33.969  INFO 7255 --- [           main] com.example.demo.DemoApplication         : Started DemoApplication in 4.017 seconds (JVM running for 5.27)


# SpringBoot使用https://start.spring.io/  创建最简化项目
![image](https://user-images.githubusercontent.com/13012417/60228781-66f83580-98c6-11e9-9362-a27fc42207c3.png)
![image](https://user-images.githubusercontent.com/13012417/60228819-85f6c780-98c6-11e9-8f02-cdb26c58de86.png)

# demo地址
https://github.com/liuzedong/apollo-demo

**Comment by nobodyiam** [comment]
确实能重现这个问题，看了一下，如果在DemoApplication上打上注解`EnableApolloConfig`就不会出现这个WARN日志，尚未仔细定位区别在哪儿

```java
@SpringBootApplication
@EnableApolloConfig
public class DemoApplication {
	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}
}
```

**Comment by liuyukuai** [comment]
- 第一次加载是org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration加载而来，beanName是"propertySourcesPlaceholderConfigurer" 

- Apollo Client => ConfigPropertySourcesProcessor这个类是通过类的全路径判断的，所以判断不出来是否加载了
`
  public static boolean registerBeanDefinitionIfNotExists(BeanDefinitionRegistry registry, String beanName, Class<?> beanClass, Map<String, Object> extraPropertyValues) {
       **// 这里是否能通过beanClass判断？**
 **if (registry.containsBeanDefinition(beanName)) {**
            return false;
        } else {
            String[] candidates = registry.getBeanDefinitionNames();
            String[] arr$ = candidates;
            int len$ = candidates.length;

            for(int i$ = 0; i$ < len$; ++i$) {
                String candidate = arr$[i$];
                BeanDefinition beanDefinition = registry.getBeanDefinition(candidate);
                if (Objects.equals(beanDefinition.getBeanClassName(), beanClass.getName())) {
                    return false;
                }
            }

            BeanDefinition beanDefinition = BeanDefinitionBuilder.genericBeanDefinition(beanClass).getBeanDefinition();
            if (extraPropertyValues != null) {
                Iterator i$ = extraPropertyValues.entrySet().iterator();

                while(i$.hasNext()) {
                    Entry<String, Object> entry = (Entry)i$.next();
                    beanDefinition.getPropertyValues().add((String)entry.getKey(), entry.getValue());
                }
            }

            registry.registerBeanDefinition(beanName, beanDefinition);
            return true;
        }
    }
`

- 加上@EnableApolloConfig这个确实就不报了，这个有定位到原因吗？

**Comment by 1156721874** [comment]
这个bug在1.7.1修复了吗，有没有临时解决方案？
