### ISSUE TITLE
application.properties和application.yml两个文件中对同一个列表进行处理，会出现结果不正确乱序问题

### ISSUE THREAD

**Issue by wuxiantian** [ctripcorp/apollo#2332]
springboot项目没有引入apollo做配置中心结果实例如图：
![sp2](https://user-images.githubusercontent.com/10464435/59489267-4090ce00-8eb4-11e9-93ce-f6680a9f12df.png)
![sy1](https://user-images.githubusercontent.com/10464435/59489281-4b4b6300-8eb4-11e9-8591-e8d586eced98.png)

application.properties和application.yml对同一个对象进行配置，springboot处理是按加载顺序来处理，先加载application.properties,不会出现覆盖和扩展处理，结果如下图：
![sr2](https://user-images.githubusercontent.com/10464435/59489284-4dadbd00-8eb4-11e9-8ff1-9312de6f24e8.png)

springboot项目引入apollo做配置中心结果实例如图：
![ap2](https://user-images.githubusercontent.com/10464435/59489297-58685200-8eb4-11e9-8a62-95b3b81f306e.png)
![ay2](https://user-images.githubusercontent.com/10464435/59489300-5a321580-8eb4-11e9-945b-d06e49350ef6.png)

apollo加载配置文件顺序如下图：
![aa](https://user-images.githubusercontent.com/10464435/59489392-a1b8a180-8eb4-11e9-902c-2115b57c6224.png)

 application.properties和application.yml对同一个对象进行配置，按设置apollo加载配置文件的顺序，先加载application.properties文件，然后加载application.yml文件，加载后数据出现如下图结果，数据结果错误，会进行数组合并，并且数组下标为0的数据替换不了
![ar2](https://user-images.githubusercontent.com/10464435/59489306-5bfbd900-8eb4-11e9-8798-250b042192c0.png)

请教下 这个问题是什么原因？

PS: 我这边有两个配置文件application.properties和application.yml对同一个对象进行配置，是引用了Apollo OpenApi开放接口, 调用Apollo OpenApi是对application.properties进行配置，而在apollo-portal上操作是对application.yml配置文件。这样是为了区分项目管理人员和运维人员的操作

**Comment by nobodyiam** [comment]
这个merge是spring boot的行为，我本地测试了一下，spring boot 1.5.9是不会merge的，spring boot 2.0.5是会merge的

**Comment by wuxiantian** [comment]
> spring boot 1.5.9是不会merge的

你好 是需要我这边的引用apollo的项目 需要把版本从2.0.5改为1.5.9吗？ 因为项目中一些类都是用的spring2.XX 的  我这边在没有引入apollo之前,  本地测试过springboot2.0.5的不存在合并的问题 只会根据加载顺序读取优先级高的properties配置内容  如上面问题描述图片说明
