### ISSUE TITLE
调用openApi接口新增配置，非properties格式配置生成结果有问题

### ISSUE THREAD

**Issue by wuxiantian** [ctripcorp/apollo#2334]
对apollo-portal上的项目application-test.yml配置文件调用openApi接口新增配置，请求参数如下图：
![oy](https://user-images.githubusercontent.com/10464435/59492227-17c00700-8ebb-11e9-8d20-c36cb9219bf1.png)

apollo-portal上的application-test.yml配置文件中只有value的值没有显示key，结果如下图：
![or](https://user-images.githubusercontent.com/10464435/59492440-9157f500-8ebb-11e9-9572-3ed4937bb164.png)

然后我调整把key的值也存入value中，请求参数如下图：
![oy1](https://user-images.githubusercontent.com/10464435/59492884-8356a400-8ebc-11e9-9c2a-d4b122106294.png)

apollo-portal上的application-test.yml配置文件中只有value的值是key=value，key的值分级没有显示冒号“：”而是“.”，而且展示的也不符合yml配置文件的格式要求，结果如下图：
![or1](https://user-images.githubusercontent.com/10464435/59493001-c87ad600-8ebc-11e9-80da-93cbd625c2be.png)

apollo开放平台文档说明如下图：
![ao1](https://user-images.githubusercontent.com/10464435/59493702-06c4c500-8ebe-11e9-95b5-cac03c874599.png)

调用新增配置接口的参数 除了env,appId,clusterName,namespaceName参数值是固定的，必须填的就key,value,dataChangeCreatedBy三个字段。想请教下，如果是调用apollo openapi对yml格式的配置文件进行新增配置（修改、删除）处理时，请求的key和value如何传值才能在apollo-portal上生成符合要求的yml格式？key和value的格式是有什么要求？文档上没有说明。

![ao](https://user-images.githubusercontent.com/10464435/59493582-c5ccb080-8ebd-11e9-8d2f-f5149a999d9e.png)

**Comment by nobodyiam** [comment]
感谢提醒，这块之前文档上确实没有写明，现在已经补上了。

非properties格式的key固定为content，value为文件全部内容。
