### ISSUE TITLE
@magnificence-dream  我只是添加了ingress.kubernetes.io/affinity: "cookie"，没有添加cookie-hash和cookie-name 相关的annotation。

### ISSUE THREAD

**Issue by huyipow** [ctripcorp/apollo#2337]
@magnificence-dream  我只是添加了ingress.kubernetes.io/affinity: "cookie"，没有添加cookie-hash和cookie-name 相关的annotation。
@nobodyiam 我用的1.0.0版本， portal service里的sessionAffinity: ClientIP 是不是只在通过expose的node IP 方式直连service才行，通过 ingress load balancer IP方式再连portal service貌似不行，因为ingress连service的ip是随机的？

_Originally posted by @zczc0128 in https://github.com/ctripcorp/apollo/issues/1543#issuecomment-428404382_

**Comment by wangycc** [comment]
参考 #1543
