### ISSUE TITLE
快速部署的时候,8080端口先启动，可以访问，之后8070的端口启动，也可以访问8070端口，但是8080的端口就会挂了

### ISSUE THREAD

**Issue by zhengganwen** [ctripcorp/apollo#2339]

**Comment by zhengganwen** [comment]
![image](https://user-images.githubusercontent.com/24824955/59554366-5f868180-8fd4-11e9-937a-b9215d48d386.png)

**Comment by zhengganwen** [comment]
![image](https://user-images.githubusercontent.com/24824955/59554439-6792f100-8fd5-11e9-8984-d8466dbbac2c.png)
8080端口启动
![image](https://user-images.githubusercontent.com/24824955/59554470-dcfec180-8fd5-11e9-8cbc-376c471c80b0.png)
8070端口启动
![image](https://user-images.githubusercontent.com/24824955/59554474-ee47ce00-8fd5-11e9-9c39-646e23420735.png)
8080端口失败
![image](https://user-images.githubusercontent.com/24824955/59554478-fd2e8080-8fd5-11e9-981a-82b9af48b893.png)

**Comment by nobodyiam** [comment]
看下是不是内存不够导致进程挂了
