### ISSUE TITLE
apollo数据库密码加密存储

### ISSUE THREAD

**Issue by tanxiaosheng** [ctripcorp/apollo#2342]
安全规范，需要将configDB和portalDB的数据库密码加密存储，如何去修改源码，实现该功能呢？ @nobodyiam

**Comment by AngusLean** [comment]
单独的namespace, 在你的ApolloConfigChangeListener里对指定的key进行解密处理．

**Comment by nobodyiam** [comment]
仿照 com.ctrip.framework.apollo.common.datasource.TitanEntityManager 构造出DataSource出来即可

**Comment by tanxiaosheng** [comment]
已经成功加密，谢谢
