### ISSUE TITLE
关于 ConfigService.getConfigFile 获取最新配置？

### ISSUE THREAD

**Issue by xjr100419** [ctripcorp/apollo#2344]
ConfigService.getConfigFile  是否总会拿到最新的配置

监听更新
` @ApolloConfigChangeListener({"list.yml"})
    private void onChange(ConfigChangeEvent changeEvent) {
        ConfigFile configFile = ConfigService.getConfigFile("list", ConfigFileFormat.YML);
        //刷新 缓存
   }`

但我看代码 ConfigService.getConfigFile实际 也会放到静态变量里面的。
没看出来 是否一直获取最新更新？
`ConfigFile configFile = m_configFiles.get(namespaceFileName);`

**Comment by nobodyiam** [comment]
会拿到最新配置的，建议debug跟进去看一下源码

**Comment by xjr100419** [comment]
十分感谢  暂时没看出来 我详细debug一下代码
