### ISSUE TITLE
两个用户同时编辑一个namesapce页面时，后发布的用户会强制删除前面用户发布的新增字段

### ISSUE THREAD

**Issue by zhu04303661** [ctripcorp/apollo#2345]
两个用户同时编辑一个配置组时，一个用户先新增字段进行发布的，另一个用户在发布前并不会提示有新增字段，而时提示将新增字段删除

重现步骤：
1.A用户打开一个namesapce的配置页面，并开启编辑模式
2.B用户打开同一个namesapce的配置页面，并开启编辑模式
3.A用户新增字段X，并发布
4.B用户修改其他字段，并未发现新增的字段
5.B用户发布自己的修改字段，发布页面提示X字段删除

**Comment by zhu04303661** [comment]
如果操作用户没有注意到这个标识的化，这个删除操作就会被发布出去，可能造成故障

**Comment by nobodyiam** [comment]
可以配置[namespace.lock.switch](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#2-namespacelockswitch---%E4%B8%80%E6%AC%A1%E5%8F%91%E5%B8%83%E5%8F%AA%E8%83%BD%E6%9C%89%E4%B8%80%E4%B8%AA%E4%BA%BA%E4%BF%AE%E6%94%B9%E5%BC%80%E5%85%B3%E7%94%A8%E4%BA%8E%E5%8F%91%E5%B8%83%E5%AE%A1%E6%A0%B8)
