### ISSUE TITLE
 Operation not permitted

### ISSUE THREAD

**Issue by tuyongjian** [ctripcorp/apollo#2347]
Administrator@PC-20170315WQST MINGW64 /f/mySoft/apollo-quick-start
$ ./demo.sh start
Windows new JAVA_HOME is: /c/Program
Files/Java/JDK18~1.0_1
Java version is , please make sure java 1.8+ is in the path
==== starting service ====
Service logging file is ./service/apollo-service.log
ln: failed to create hard link './service/apollo-service.jar' => 'apollo-all-in-one.jar': Operation not permitted
chmod: cannot access './service/apollo-service.jar': No such file or directory
./demo.sh: line 115: ./service/apollo-service.jar: No such file or directory
Failed to start service, return code: 127. Please check ./service/apollo-service.log for more information.

1.

**Comment by nobodyiam** [comment]
没有权限写目录？

**Comment by tuyongjian** [comment]
开始放在f盘不行，放到桌面就可以了，不知道啥原因


发自我的iPhone

------------------ Original ------------------
