### ISSUE TITLE
openapi 是否可以提供回滚接口？

### ISSUE THREAD

**Issue by liuyuanxiang** [ctripcorp/apollo#2351]
openapi 是否可以支持回滚？这个功能感觉是很有必要的，虽然我在自己的系统可以记录上次修改了那些，但你们提供但接口不支持一次性添加/修改/删除多个配置项，配置项只能一个个添加/修改删除，这样要请求多次接口，感觉用起来不方便，建议扩展一下，谢谢。
基于上面的描述，建议增加回滚接口，修改 `添加/修改/删除配置接口` 改为这次多个配置的添加/修改/删除

**Comment by JaredTan95** [comment]
added in https://github.com/ctripcorp/apollo/pull/2581.
