### ISSUE TITLE
Spring敏感信息加密问题

### ISSUE THREAD

**Issue by xlixlixli** [ctripcorp/apollo#2353]
之前项目中使用的是继承PropertyPlaceholderConfigurer，覆盖convertProperty(String propertyName, String propertyValue)方法进行敏感信息解密。加入Apollo之后，项目启动时调用不到convertProperty方法了。但是使用PropertySourcesPlaceholderConfigurer也不知该如何解密。问题类似于https://github.com/ctripcorp/apollo/issues/1736。但是看了您的回答仍然没太懂，还请给与帮助。

**Comment by xlixlixli** [comment]
@nobodyiam

**Comment by nobodyiam** [comment]
可以参考 jasypt 的实现方式，它的原理是把apollo的propertysource包了一下，然后每次getProperty的时候都会先调用它的方法，在它的方法里面就可以判断当前值是否需要解密了

**Comment by diarbao** [comment]
你需要继承PropertySourcesPlaceholderConfigurer这个类。然后重写里面的processProperties 和mergeProperties方法。具体可以百度一下
