### ISSUE TITLE
Unable to determine jdbc url from datasource

### ISSUE THREAD

**Issue by CLOUD321321** [ctripcorp/apollo#2354]
哪位大神帮忙看看，为啥我修改的数据库地址是105，然后日志中显示的是106连不上哩。。。配置文件及日志请见附件。
[root@localhost apollo]# ./demo.sh start
==== starting service ====
Service logging file is ./service/apollo-service.log
jdbc:mysql://192.168.1.105:3306/ApolloConfigDB?characterEncoding=utf8
Started [8715]
Waiting for config service startup........................
Config service failed to start in 120 seconds! Please check ./service/apollo-service.log for more information.
[apollo-service.log](https://github.com/ctripcorp/apollo/files/3302355/apollo-service.log)
[demo.sh.txt](https://github.com/ctripcorp/apollo/files/3302359/demo.sh.txt)

**Comment by nobodyiam** [comment]
看样子你对jdbc报错的信息没有理解，192.168.1.106是访问数据库的机器IP，不是数据库自己的IP

java.sql.SQLException: Access denied for user 'root'@'192.168.1.106' (using password: YES)

**Comment by CLOUD321321** [comment]
了解了，多谢指正。
