### ISSUE TITLE
HandlerInterceptorAdapter无法获取发布的配置

### ISSUE THREAD

**Issue by Kong16** [ctripcorp/apollo#2355]
首先感谢apollo团队。
我这边在学习SpringBoot，同时集成了apollo，采用quick-start的模式，多次测试在拦截器中无法获取发布的新配置（环境没问题，Controller里可以），感觉拦截器在apollo之前注入容器，是不是这个原因？请求大神们指导如何在拦截器使用的解决方案，谢谢

**Comment by nobodyiam** [comment]
apollo是一个普通的spring boot + spring mvc的应用，没啥特殊的，建议先通过IDE方式把代码跑通
