### ISSUE TITLE
spring-mvc的父子容器配置热更新问题

### ISSUE THREAD

**Issue by wkcaeser** [ctripcorp/apollo#2356]
spring-mvc有上下文容器和dispatcher， 如果bean加载在dispatcher的容器后，拉取配置没问题，但是热更新获取不到

**Comment by lepdou** [comment]
可以看一下客户端有没有错误日志

**Comment by nobodyiam** [comment]
我记得老版本是有这个问题的，最近的版本已经修过了

**Comment by wkcaeser** [comment]
通过将所有的内容都在spring mvc的上下文容器中配置解决了
