### ISSUE TITLE
APOLLO 接入springboot admin actuator的问题

### ISSUE THREAD

**Issue by ex-allen** [ctripcorp/apollo#2358]
1. springboot actuator的版本为 2.0.5.Release.

1.
![image](https://user-images.githubusercontent.com/33972878/59734355-bfef1a80-9283-11e9-9929-e492960eea1e.png)
2.
![image](https://user-images.githubusercontent.com/33972878/59734467-1b210d00-9284-11e9-9463-91b1ed171bd6.png)
3.
![image](https://user-images.githubusercontent.com/33972878/59734482-2c6a1980-9284-11e9-9a56-36f2c69c177d.png)
4.
![image](https://user-images.githubusercontent.com/33972878/59734543-6e935b00-9284-11e9-9d55-f259b20c6fe3.png)
5.
![image](https://user-images.githubusercontent.com/33972878/59734563-7fdc6780-9284-11e9-92d3-5c1447d22b08.png)
6.
![image](https://user-images.githubusercontent.com/33972878/59734598-aa2e2500-9284-11e9-9aa3-a6aaba375ace.png)
7. springboot admin 应用报的错
![image](https://user-images.githubusercontent.com/33972878/59734607-b914d780-9284-11e9-80ec-a3127b822440.png)
8 apollo报的错
![image](https://user-images.githubusercontent.com/33972878/59734666-eeb9c080-9284-11e9-88b5-cde999493a62.png)

 有没有遇到的，怎么解决呢？

**Comment by lepdou** [comment]
这个看上去是 json 格式有问题？

**Comment by ex-allen** [comment]
> 这个看上去是 json 格式有问题？

 apollo 默认使用了 gson，但是原有的spring boot admin 报解析出错，且只是部分节点，难道跟 jackson 不兼容？

**Comment by nobodyiam** [comment]
json格式照理说应该是互相兼容的，能看到具体是什么样的内容导致不兼容吗？

**Comment by ex-allen** [comment]
https://stackoverflow.com/questions/39900183/gson-and-spring-actuator   由于 eureka的应用都接入了actuator,  故apollo 我们目前只展示部分的无问题的节点，具体没有太深究
