### ISSUE TITLE
需要获取EmbeddedApollo中MockWebServer的port信息

### ISSUE THREAD

**Issue by slievrly** [ctripcorp/apollo#2361]

**Comment by nobodyiam** [comment]
在什么场景需要这个信息？

**Comment by slievrly** [comment]
在开源项目中，我们内部集成了apollo配置中心，但是在ci的时候需要一些集成测试，而在代码中我们是通过地址端口api连接的，所以我们使用这个嵌入式的EmbeddedApollo做集成测试时，拿不到相应的端口信息。

**Comment by nobodyiam** [comment]
看一下通过system property `apollo.configService` 获取mock的服务地址是否满足需求？

详见设置的[代码](https://github.com/ctripcorp/apollo/blob/master/apollo-mockserver/src/main/java/com/ctrip/framework/apollo/mockserver/EmbeddedApollo.java#L103)

**Comment by slievrly** [comment]
@nobodyiam tks, I will try.
