### ISSUE TITLE
能否在属性注入被引用之前进行拦截做一些修改

### ISSUE THREAD

**Issue by lmzhizhe** [ctripcorp/apollo#2363]
能否在属性注入被引用之前进行拦截做一些修改？
我现在想对属性从服务器down下来后，在使用之前 统一做一些增强修改，是否有拦截器或者其它统一的入口呢？

**Comment by lepdou** [comment]
如果需要做拦截修改，是否可以通过 ChangeListener 的功能实现？

**Comment by nobodyiam** [comment]
可以参考jasypt的做法，把apollo的property source包一层，这样所有getProperty的方法都会经过你的代码，可以实现拦截了
