### ISSUE TITLE
apollo删除某个log日志级别配置，如何在spring cloud中同步删除某个日志级别的配置

### ISSUE THREAD

**Issue by luffyace** [ctripcorp/apollo#2364]
如题，默认日志级别是warn，在apollo中后期增加了com.test 这个包下面的日志级别为info，如果现在把这个包的日志级别删除掉，spring cloud中如何同步？看了demo的spring cloud同步代码，并没有把删除的配置删除掉。

**Comment by nobodyiam** [comment]
[LoggerLevelRefresher](https://github.com/ctripcorp/apollo-use-cases/blob/master/spring-cloud-logger/src/main/java/com/ctrip/framework/apollo/use/cases/spring/cloud/logger/LoggerLevelRefresher.java)是监听了`logging.level.`开头的配置变化，包括新增、修改和删除事件的
