### ISSUE TITLE
添加用户管理和项目管理页面

### ISSUE THREAD

**Issue by polegek** [ctripcorp/apollo#2365]
目前公司接入apollo已经有一段时间了，但是由于开发人员较多，且项目也较多，运维对项目的管理不太方便，希望能有一个用户列表和项目列表能够统一查看和管理，不知道能否支持

**Comment by lepdou** [comment]
@polegek 用户和项目管理，这一块确实做得比较薄弱。
目前已经有用户和项目的数据和服务，主要是前端这一块需要投入一些开发精力，应该工作量不是很大。短期内，我们这边没有开发资源，不知是否可以提 PR~
