### ISSUE TITLE
UI language

### ISSUE THREAD

**Issue by pw-ility** [ctripcorp/apollo#2370]
Awesome project! Does UI interface support English?Or how can I change UI language to English?Thank you very much.

**Comment by nobodyiam** [comment]
Thanks!

We do really want to support i18n, the major work should be limited to the front-end(angular js).
Currently we don't have enough resource to start this work, but we would appreciate if any kind of help/suggestion could be provided.

**Comment by nobodyiam** [comment]
#2452 was released with apollo 1.5.1, which now support English UI interface
