### ISSUE TITLE
我使用源代码自己构建的1.3.0版本，启动后不用登陆就可以添加命名空间和配置参数？

### ISSUE THREAD

**Issue by majinding** [ctripcorp/apollo#2371]
使用源代码构建好jar文件后，使用docker部署的。
如题，现在启动后可以不输入用户名和密码直接进入管理界面。
如何才能只有输入了用户名和密码之后才可以进入管理界面呢 ？

截图如下
图1: 启动系统，直接进入到了管理界面，（并且apollo这个账号无法退出，用户管理页面可以打开，但是不能提交修改或添加账号/密码）(下面3张图)
<img width="1642" alt="1" src="https://user-images.githubusercontent.com/2681645/59958202-4189b700-94d5-11e9-84af-e3b151c1280c.png">

<img width="1642" alt="4" src="https://user-images.githubusercontent.com/2681645/59958145-6c274000-94d4-11e9-9671-4022c30c6a7d.png">

<img width="1651" alt="5" src="https://user-images.githubusercontent.com/2681645/59958147-6c274000-94d4-11e9-87d4-7cc1c5bc7454.png">

图2:自己手动输入登陆地址
<img width="1181" alt="2" src="https://user-images.githubusercontent.com/2681645/59958093-c5db3a80-94d3-11e9-9c9c-240c98cf5b8a.png">

图3:填写用户名和密码后
<img width="1476" alt="3" src="https://user-images.githubusercontent.com/2681645/59958204-4c444c00-94d5-11e9-8665-eb6bc26d8a92.png">

**Comment by nobodyiam** [comment]
请参考[Portal-实现用户登录功能](https://github.com/ctripcorp/apollo/wiki/Portal-%E5%AE%9E%E7%8E%B0%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95%E5%8A%9F%E8%83%BD)，建议看一下apollo自带的startup.sh，默认会启用`auth` profile的，在这个profile下会使用spring security实现用户登录。

**Comment by majinding** [comment]
好的，非常感谢，已经验证启用auth的profile确实成功了。
但是在start.sh中没有看到有启用github和auth的profile参数了？

**Comment by nobodyiam** [comment]
恩，前面说错了，是在[build.sh](https://github.com/ctripcorp/apollo/blob/master/scripts/build.sh#L36)中设置的

**Comment by majinding** [comment]
好的， 谢谢。
