### ISSUE TITLE
dot net core 客户端2.0版 GetProperty除string类型外其他类型只能返回defaultValue,代码没有返回类型转换后的值

### ISSUE THREAD

**Issue by 19279217** [ctripcorp/apollo#2372]
public static bool? GetProperty([NotNull]this IConfig config, string key, bool? defaultValue)
        {
            if (config == null) throw new ArgumentNullException(nameof(config));

            if (!config.TryGetProperty(key, out var str) || str == null) return defaultValue;

            if (!bool.TryParse(str, out var value))
                Logger().Error(new ApolloConfigException($"GetBooleanProperty for {key} failed, return default value {defaultValue}"));

            return defaultValue;
        }

在bool.TryParse 成功的情况下应该return  value

**Comment by nobodyiam** [comment]
看上去确实是有这个问题

**Comment by pengweiqhca** [comment]
问题已经修复，请更新包
