### ISSUE TITLE
本地开发环境直连config-service带来的安全风险

### ISSUE THREAD

**Issue by xuqiming** [ctripcorp/apollo#2373]
如果Apollo部署在公有云上，本地开发环境无法连接，但又需要做开发测试的话，客户端可以升级到0.11.0版本及以上，然后通过-Dapollo.configService=http://config-service的公网IP:端口来跳过meta service的服务发现。

这是部署文档上的一句话，但是如果我真的使用了这种方法，就相当于把config-service暴露在公网上了，当然也可以通过防火墙或安全组限制ip访问，但是本地ip无法确定，有可能我的同事遍布全国各地，我们需要协同开发，有没有什么办法可以解决这种问题呢？

**Comment by wkcaeser** [comment]
难道你们没vpn么

**Comment by xuqiming** [comment]
> 难道你们没VPN么

嗯， 这确实也是个好办法
