### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by Yakir6** [ctripcorp/apollo#2374]
https://github.com/ctripcorp/apollo/blob/master/apollo-portal/src/main/resources/static/scripts/directive/item-modal-directive.js

159行 scope.valueWithHiddenChars = $sce.trustAsHtml(valueWithHiddenChars);
使用啦angularjs危险函数，直接把用户数据渲染到页面中，如果valueWithHiddenChars变量中包含恶意脚本就会被执行。

**Comment by nobodyiam** [comment]
确实有这个隐患，不过触发条件是用户点了『检测隐藏字符』，所以风险应该还是比较小的，对于实现这个功能有什么建议吗？
