### ISSUE TITLE
关于分布式部署指南，网络策略疑问

### ISSUE THREAD

**Issue by lookstorm** [ctripcorp/apollo#2375]
在分布式部署指南中，我对 1.4、网络策略部分有点疑问，apollo-configservice和apollo-adminservice需要把自己的IP和端口注册到Meta Server，这里有三种方式？

第二种方式是：
eureka:
  instance:
    ip-address: ${指定的IP}

第三种方式是：
eureka:
  instance:
    homePageUrl: http://${指定的IP}:${指定的Port}
    preferIpAddress: false

但是第一种方式（如下）没看明白，这个是在哪里指定的ip？
spring:
      application:
          name: apollo-configservice
      profiles:
        active: ${apollo_profile}
      cloud:
        inetutils:
          ignoredInterfaces:
            - docker0
            - veth.*

**Comment by nobodyiam** [comment]
第一种方式是把某些网卡忽略掉的意思，适用于机器上有多个网卡和IP，比如既有内网IP又有外网IP
