### ISSUE TITLE
怎么添加环境？

### ISSUE THREAD

**Issue by libra1010** [ctripcorp/apollo#2380]
![image](https://user-images.githubusercontent.com/9667153/60073154-3e4f2f00-9752-11e9-9a7c-d017876c0e3b.png)

**Comment by nobodyiam** [comment]
[Portal如何增加环境？](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#4-portal%E5%A6%82%E4%BD%95%E5%A2%9E%E5%8A%A0%E7%8E%AF%E5%A2%83)
