### ISSUE TITLE
Spring项目，使用 @ApolloConfigChangeListener，每隔5分钟才会监听到最新配置

### ISSUE THREAD

**Issue by ericren** [ctripcorp/apollo#2385]
我在Spring项目里，使用 @ApolloConfigChangeListener，想监听更改的key和value信息，
但每次更改发布完以后，不能监听到变化，而是每隔5分钟，感觉有个任务，会监听到最新配置，请问Apollo是不是有推和拉两种模式？我猜测，推的模式未生效，但每隔5分钟有个任务是拉的模式，这时候才把最新的配置拉到，请问是这样吗？
这是我的代码：
`
@Configuration
@EnableApolloConfig
public class XXXApolloCfgListener {

    @ApolloConfigChangeListener("abc")
    private void onChange(ConfigChangeEvent changeEvent){
        for (String key : changeEvent.changedKeys()) {
            ConfigChange change = changeEvent.getChange(key);
            System.out.println(DateFormatUtils.format(new Date(),"yyyy-MM-dd HH:mm:ss") + String.format(" Found change - key: %s, oldValue: %s, newValue: %s, changeType: %s", change.getPropertyName(), change.getOldValue(), change.getNewValue(), change.getChangeType()));
        }

    }

}`
我需要怎么才可以立即监听到key和value的变化？目前使用的Apollo版本是1.2.1

**Comment by ericren** [comment]
使用的Apollo版本是1.2.1

**Comment by xuqiming** [comment]
我遇到过类似的问题，我的原因是appid是大写的，但在项目里却写了小写的，最后数据可以拉，但是却收不到更新推送，所以你可以检查一下appid。

**Comment by ericren** [comment]
> 
> 
> 我遇到过类似的问题，我的原因是appid是大写的，但在项目里却写了小写的，最后数据可以拉，但是却收不到更新推送，所以你可以检查一下appid。

我的appid都是小写，每隔5分钟能拉到，但是推送的时候监听不到。

**Comment by xuqiming** [comment]
还有namespace那些看看有没有问题， 再不行就调试找原因，问题太泛。

**Comment by nobodyiam** [comment]
目前已知的原因是appid大小写不一致会导致这个情况，因为在内存中有缓存，而java的缓存默认是区分大小写的，notify的时候会忽略，而数据库默认不区分大小写的，所以在5分钟一次的定时拉取中能拉到最新数据。

建议在客户端打开针对`com.ctrip.framework.apollo`的debug日志，里面可以看到具体的long polling url和服务端的响应，方便排查问题。

**Comment by ericren** [comment]
> 
> 
> 目前已知的原因是appid大小写不一致会导致这个情况，因为在内存中有缓存，而java的缓存默认是区分大小写的，notify的时候会忽略，而数据库默认不区分大小写的，所以在5分钟一次的定时拉取中能拉到最新数据。
> 
> 建议在客户端打开针对`com.ctrip.framework.apollo`的debug日志，里面可以看到具体的long polling url和服务端的响应，方便排查问题。

谢谢宋大哥@nobodyiam 和@xuqinming的帮助。

**Comment by LiuQiangWangWanHong** [comment]
@configuration
@EnableApolloConfig
public class XXXApolloCfgListener {

@ApolloConfigChangeListener("abc")
private void onChange(ConfigChangeEvent changeEvent){
    for (String key : changeEvent.changedKeys()) {
        ConfigChange change = changeEvent.getChange(key);
        System.out.println(DateFormatUtils.format(new Date(),"yyyy-MM-dd HH:mm:ss") + String.format(" Found change - key: %s, oldValue: %s, newValue: %s, changeType: %s", change.getPropertyName(), change.getOldValue(), change.getNewValue(), change.getChangeType()));
    }

}

这个会监听到我的配置变化 现在没有生效  但是我怎么让他变化的配置生效
