### ISSUE TITLE
portal公网上的多环境配置管理

### ISSUE THREAD

**Issue by xuqiming** [ctripcorp/apollo#2386]
目前我们公司有两个环境：dev、pro，这两个环境之间内网互不连通。

基于一个portal管理多个环境配置，我打算把apollo部署在pro环境上，然后去管理dev与pro的配置。

但是我发现，一个portal管理多个环境的配置，前提必须是所有环境都必须是portal内网可以访问到的，像我目前的情况，dev与pro不在一个内网环境下，是不是无法实现portal多环境配置管理呢？

**Comment by lawrencewu** [comment]
需要打通Dev,Pro环境的网络, 或者经过中间代理网络转发.

**Comment by xuqiming** [comment]
也不用做代理，portal直接访问dev上mate server的公网ip就行，但是mate server，也就是eureka注册的是内网地址，就算从mate server请求回来了admin service的所有服务地址，但也是内网地址，还是无法访问。

引用文档的一句话：
> 如果Apollo部署在公有云上，本地开发环境无法连接，但又需要做开发测试的话，客户端可以升级到0.11.0版本及以上，然后通过-Dapollo.configService=http://config-service的公网IP:端口来跳过meta service的服务发现

client访问是如此，portal访问也是如此，不经过mate server， 直接访问admin service。

相比于上面说的这么多，我可能还是更倾向于与每个环境搭建一个potral，这样好像来的更简单。

**Comment by nobodyiam** [comment]
每个环境搭建一个potral的问题是需要自己同步应用和namespace的信息

**Comment by xuqiming** [comment]
但是目前的状况，有没有更好的方法呢，望指点。 @nobodyiam

**Comment by dawsonyan186** [comment]
修改configservice和adminservice启动脚本startup.sh中的JAVA_OPTS，增加
-Deureka.instance.prefer-ip-address=true -Deureka.instance.ip-address=公网IP
