### ISSUE TITLE
数据库连接失败

### ISSUE THREAD

**Issue by shemTian** [ctripcorp/apollo#2387]
# 配置信息
![image](https://user-images.githubusercontent.com/14309614/60311595-76d94d80-998a-11e9-820e-e438f061fa7c.png)

# 手工连接数据库成功
![image](https://user-images.githubusercontent.com/14309614/60311105-54decb80-9988-11e9-8fd3-b1cb106c8e8f.png)
# 日志报错
![image](https://user-images.githubusercontent.com/14309614/60311200-c9196f00-9988-11e9-960e-dfe72f45fde7.png)
# 启动信息
![image](https://user-images.githubusercontent.com/14309614/60311261-08e05680-9989-11e9-8f12-3d2eccb49008.png)
# 说明
根据报错日志来看，连接数据库时候并没有使用配置的用户名称
```Access denied for user ''@'180.168.129.34' (using password: NO)```

**Comment by shemTian** [comment]
## 结案，被自己蠢哭
portal数据库连接配置信息搞错了，从上面的configcopy下来，用户名和密码的key值忘记修改
![image](https://user-images.githubusercontent.com/14309614/60312073-72ae2f80-998c-11e9-80a8-acace2d40a61.png)

引以为戒，顺便建议一下，配置略显麻烦^_^，人工操作多，就容易犯错

**Comment by nobodyiam** [comment]
目前手工步骤确实略多，比较容易犯错，see #1424
