### ISSUE TITLE
Apollo多集群 某个集群有个namespace未发布 会默认拉取default下这个namespace的配置

### ISSUE THREAD

**Issue by zyy1993** [ctripcorp/apollo#2388]

**Comment by zyy1993** [comment]
目前发现有这个问题 是设计如此吗

**Comment by nobodyiam** [comment]
是的，详见[配置获取规则](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E4%BB%8B%E7%BB%8D#44-%E9%85%8D%E7%BD%AE%E8%8E%B7%E5%8F%96%E8%A7%84%E5%88%99)

**Comment by jsonchina** [comment]
这个是跨多个环境的吗,意思如果是uat环境.会默认去读dev环境default集群的配置吗

**Comment by zyy1993** [comment]
> default

不会跨环境 但是一个环境下有多个集群 会跨集群

**Comment by jsonchina** [comment]
> > default
> 
> 不会跨环境 但是一个环境下有多个集群 会跨集群
但是 我们实际使用的时候,发现跨环境读取到default集群的配置了

**Comment by nobodyiam** [comment]
@jsonchina 看下是否是不同环境的config service注册到一个环境上去了

**Comment by jsonchina** [comment]
> @jsonchina 看下是否是不同环境的config service注册到一个环境上去了

没有确认了下 config server注册地址是对的,我看看是不是 他们用错了
