### ISSUE TITLE
Spring Cloud Config 解密覆盖失效

### ISSUE THREAD

**Issue by lijiahaoneil** [ctripcorp/apollo#2389]
我在升级了Apollo到1.4.0的版本以后，原Spring Cloud Config的解密覆盖失效了，
password = {cipher}密钥
无法使用，在不更换新的加密方式的情况下，有没有可以通过配置就能解决的方案？

**Comment by nobodyiam** [comment]
根据spring cloud config的[说明](https://cloud.spring.io/spring-cloud-static/spring-cloud-config/1.2.0.RELEASE/#_encryption_and_decryption)，它这个解密是在服务端做的，不是在客户端做的，所以不通用。

apollo配合加密的话可以参考[spring-boot-encrypt](https://github.com/ctripcorp/apollo-use-cases/tree/master/spring-boot-encrypt)

**Comment by lijiahaoneil** [comment]
我把客户端版本号退回1.0.0了，正常了

**Comment by asasas234** [comment]
这个问题我也遇到了，debug了下源码，com.ctrip.framework.apollo.spring.config.PropertySourcesProcessor#ensureBootstrapPropertyPrecedence 是这个方法导致的，在spring cloud 强制把name=decrypted 的PropertySource加到最优先之后，走到了这个方法，然后这里又强制把apollo的放到了最优先导致的。

<img width="1665" alt="image" src="https://user-images.githubusercontent.com/4795442/168814805-2ea9def9-6b62-4391-bc37-2b7497c75ec0.png">
我是这么改的， 不过这么写感觉不太优雅，写死了decrypted
