### ISSUE TITLE
新添加的用户可查看所有项目的配置

### ISSUE THREAD

**Issue by kongzhenhao** [ctripcorp/apollo#2390]
在spring security模式下，新添加的用户虽然在页面中看不到项目信息，但通过指定项目ID构造URL的方式，可查看到所有项目配置信息。如，/config.html?#/appid=xxxx。请问有什么方法可以防止新增用户通过这种方式查看所有项目信息？

**Comment by nobodyiam** [comment]
可以参考[apollo如何配置查看权限?](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#12-apollo%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE%E6%9F%A5%E7%9C%8B%E6%9D%83%E9%99%90)
