### ISSUE TITLE
新手请教：是否仅支持手工portal发布配置

### ISSUE THREAD

**Issue by wengchanghe-ray** [ctripcorp/apollo#2391]
配置是否只能通过Portal进行发布？如果想通过一个主发布服务器 往配置中心上自动更新设置，其他客户端接受设置，是否可行？

**Comment by nobodyiam** [comment]
参考一下[Apollo开放平台](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0)
