### ISSUE TITLE
应用集成了java的client，启动后，报404

### ISSUE THREAD

**Issue by zhiguangliu** [ctripcorp/apollo#2394]
应用集成了apollo的java客户端，启动之后报错如下：
13:17:43.416 logback [Apollo-RemoteConfigLongPollService-1] WARN  c.c.f.a.i.RemoteConfigLongPollService - Long polling failed, will retry in 120 seconds. appId: EcFrame, cluster: default, namespaces: application, long polling url: null, reason: Get config services failed from http://192.168.103.200:8070/services/config?appId=EcFrame&ip=192.168.11.1 [Cause: Could not complete get operation [Cause: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $ [Cause: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $]]]

程序是springboot的程序，但是集成是用的api方式集成，配置用的是META-INF/app.properties方式。目标是以后可以独立运行。
http://192.168.103.200:8070可以正常访问
http://192.168.103.200:8070/services/config?appId=EcFrame&ip=192.168.11.1这个地址报404

**Comment by zhiguangliu** [comment]
服务器端用的是Quick Start，客户端依赖的是
        <dependency>
            <groupId>com.ctrip.framework.apollo</groupId>
            <artifactId>apollo-client</artifactId>
            <version>1.4.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
因为我自己项目里有guava20，所以排除了客户端的guava依赖。

**Comment by zhiguangliu** [comment]
问题已经解决了。在查看服务器版本的页面，忽然发现一行字：
Meta server地址: http://localhost:8080
然后我配置文件里配置的是管理页面的8070端口。
建议在文档中再补充说明一下这几个端口的用途。
![image](https://user-images.githubusercontent.com/8967130/60413402-684b9a00-9c07-11e9-8159-d7ef6eeb61ea.png)

**Comment by nobodyiam** [comment]
meta server的端口应该是8080

**Comment by zhiguangliu** [comment]
问题已经解决。
