### ISSUE TITLE
eureka闭源了，为啥不换成Nacos

### ISSUE THREAD

**Issue by GuoHaoJava** [ctripcorp/apollo#2395]

**Comment by wkcaeser** [comment]
为什么要换？

1、eureka虽然闭源了，但是现在的eureka是满足使用的

2、在配置中心的场景中，eureka这种主要侧重AP的组件明显更加有优势

3、nacos功能太杂了

**Comment by wkcaeser** [comment]
就算要换的话，zk、consul这种也比nacos更加靠谱吧

**Comment by nobodyiam** [comment]
1. eureka闭源的是从未正式发布过的2.x版本，apollo集成的是1.x版本
2. apollo使用的eureka可以认为是apollo的内部逻辑，只是为了支持自身config service/admin service的注册和发现，目前来看是够用的
