### ISSUE TITLE
延长登陆过期时间

### ISSUE THREAD

**Issue by Bismarcharis** [ctripcorp/apollo#2396]
在无任何操作的情况下，登陆很快就会过期，希望能够延长这个登陆过期时间，请问需要改哪里？

**Comment by nobodyiam** [comment]
https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

试一下`server.servlet.session.timeout`?

**Comment by xuezm01** [comment]
@Bismarcharis  ,你好,请问这个问题您解决啦吗, 我也有遇到这个情况,目前只能采取最笨的版本,开发同学修改配置时,先 copy出来,修改完成在粘贴进去.

**Comment by nobodyiam** [comment]
是使用了默认的spring security登录方式并且portal多机部署？

如果是这样的话，在负载均衡上可以设置一下session sticky

**Comment by Bismarcharis** [comment]
> https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
> 
> 试一下`server.servlet.session.timeout`?
