### ISSUE TITLE
配置页面没有滚动条

### ISSUE THREAD

**Issue by sKabYY** [ctripcorp/apollo#2399]
我用的1.2.0版本和1.4.0版本，配置页面和编辑框都没有滚动条，配置项很多的时候翻起来非常麻烦。

**Comment by nobodyiam** [comment]
页面可以滚动的呀，非常麻烦是指？

**Comment by sKabYY** [comment]
配置非常多的时候，有滚动条的话可以直接拉到底部，现在只能用鼠标中键往下一直滚T_T

**Comment by nobodyiam** [comment]
用键盘的方向键也可以的，比如mac上是 Command + ↓
