### ISSUE TITLE
服务ip的问题

### ISSUE THREAD

**Issue by JunminZhang** [ctripcorp/apollo#2403]
getLocalIp这个方法在读取ip的时候如果有多网卡（例如虚拟机、VPN等），可能导致多实例客户端连接不上配置中心

**Comment by nobodyiam** [comment]
getLocalIp目前只是用来获取客户端的ip作为一个标识传给服务端做记录使用的，不会导致连不上配置中心

**Comment by JunminZhang** [comment]
> 
> 
> getLocalIp目前只是用来获取客户端的ip作为一个标识传给服务端做记录使用的，不会导致连不上配置中心

ConfigService和AdminService的homepageUrl也会收到影响，导致portal连接不上

**Comment by nobodyiam** [comment]
ConfigService和AdminService的homepageUrl是eureka获取的，可以看下分布式部署文档中的网络策略部分
