### ISSUE TITLE
同时使用ApolloConfig和ApolloConfigChangeListener，配置更新时，ApolloConfigChangeListener无效

### ISSUE THREAD

**Issue by lq6767667q** [ctripcorp/apollo#2404]
同时使用ApolloConfig和ApolloConfigChangeListener时：

    @ApolloConfigChangeListener({"param"})
    public void onParamChange(ConfigChangeEvent changeEvent) {
       ....
    }

    @ApolloConfig(value = "param")
    private Config config;

每次更新配置，config发生更新，onParamChange方法无效，去掉@ApolloConfig后onParamChange就正常

**Comment by lq6767667q** [comment]
发现是因为使用了config.getProperty(key)方法以后，对应key更新就无法获取了

**Comment by lq6767667q** [comment]
发现是因为System.setProperty(key)后，就无法再获取到key的更新了

**Comment by nobodyiam** [comment]
升级到1.4.0版本看看
