### ISSUE TITLE
集成mybatis-plus出现问题

### ISSUE THREAD

**Issue by xavierzhao** [ctripcorp/apollo#2406]
当前使用版本
springBootVersion = '2.1.3.RELEASE'
springCloudVersion = 'Greenwich.RELEASE'
mybatisPlusVersion = '3.1.0'
ctripApolloVersion = '1.4.0' // 携程Apollo配置中心

该问题是怎么引起的？

没集成apollo之前启动没问题，集成后出现问题

重现步骤
mybaits-plus配置
mybatis-plus:
mapper-locations: classpath:/mapper/*Mapper.xml
global-config:
banner: false
db-config:
id-type: 0
field-strategy: 1
table-underline: true
logic-delete-value: 1
logic-not-delete-value: 0
configuration:
map-underscore-to-camel-case: true

报错信息
APPLICATION FAILED TO START

Description:

Failed to bind properties under 'mybatis-plus.global-config.db-config.id-type' to com.baomidou.mybatisplus.annotation.IdType:

Property: mybatis-plus.global-config.db-config.id-type
Value: 0
Origin: "mybatis-plus.global-config.db-config.id-type" from property source "ApolloBootstrapPropertySources"
Reason: failed to convert java.lang.String to com.baomidou.mybatisplus.annotation.IdType
Action:

Update your application's configuration. The following values are valid:

AUTO
ID_WORKER
ID_WORKER_STR
INPUT
NONE
UUID

**Comment by xavierzhao** [comment]
从错误日志上看应该是属性转化出问题了，ApolloBootstrapPropertySources，请问这块代码在哪里？

**Comment by nobodyiam** [comment]
com.ctrip.framework.apollo.spring.boot.ApolloApplicationContextInitializer#initialize(org.springframework.core.env.ConfigurableEnvironment)

**Comment by xavierzhao** [comment]
@nobodyiam 谢谢，问题已经解决了，是我配置有问题
