### ISSUE TITLE
Placeholder 占位符引用时的配置无法实时更新

### ISSUE THREAD

**Issue by bkblack** [ctripcorp/apollo#2410]
![image](https://user-images.githubusercontent.com/22416031/60588704-36cefc00-9dca-11e9-9462-a4a58e38b8e2.png)

**Comment by nobodyiam** [comment]
是的，对于这种情况目前不支持自动更新，这个在PR #972 中也提到了

![image](https://user-images.githubusercontent.com/837658/60767323-1d3ef480-a0e9-11e9-9f93-48281548246c.png)

**Comment by bkblack** [comment]
@nobodyiam 解决了，有空我提个PR吧
