### ISSUE TITLE
官方文档跑不通

### ISSUE THREAD

**Issue by VernZHYF** [ctripcorp/apollo#2414]
apollo-use-cases-mater中的spring-boot-logger无法运行，文档写的和实际完全不一样，什么鬼？？？？
只改了appid和meta，持续报错。
Long polling failed, will retry in 1 seconds. appId: {}, cluster: default, namespaces: application, long polling url: null, reason: Get config services failed from http:………………&ip=10.201.40.137 [Cause: Could not complete get operation [Cause: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $ [Cause: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $]]]

**Comment by liangshen001** [comment]
![屏幕快照 2019-07-06 上午8 31 52](https://user-images.githubusercontent.com/22604816/60749151-8a0e9d80-9fc8-11e9-9be2-bd738c611052.png)
使用root权限会报这个错
不使用root权限又会报权限问题
![屏幕快照 2019-07-06 上午8 37 58](https://user-images.githubusercontent.com/22604816/60749230-79aaf280-9fc9-11e9-8d59-a56864aa463a.png)

**Comment by VernZHYF** [comment]
解决了，配置错误
