### ISSUE TITLE
有没有计划支持yaml在线编辑类似properties，以及同步yaml配置

### ISSUE THREAD

**Issue by xavierzhao** [ctripcorp/apollo#2416]
有没有计划支持yaml在线编辑类似properties，以及同步yaml配置

**Comment by nobodyiam** [comment]
yaml在线编辑现在已经支持了吧，还是说你希望把yaml转成properties格式按照k-v编辑？

**Comment by xavierzhao** [comment]
@nobodyiam 希望把yaml转成properties格式按照k-v编辑

**Comment by xavierzhao** [comment]
目前yaml也不支持同步配置（dev -> test-alpha等等），只能通过URL手动输入才可以同步

**Comment by nobodyiam** [comment]
对于这种情况，可以先用外部的工具把yml转成properties，然后以properties的文本模式录入

https://www.toyaml.com/

**Comment by xavierzhao** [comment]
> 对于这种情况，可以先用外部的工具把yml转成properties，然后以properties的文本模式录入
> 
> https://www.toyaml.com/

这个我明白，就是想问问后期会支持吗？不太喜欢properties，如果后期会支持可以继续等待

**Comment by nobodyiam** [comment]
1. yaml的在线编辑和发布已经支持了，客户端1.3.0版本及以上支持直接注入yaml的namespace
2. yaml同步配置暂时还是以文本模式呈现，不会像properties那样支持到key级别
3. 如果希望支持按key级别同步配置，可以先通过外部工具转成properties后录入，这是一次性工作

**Comment by xavierzhao** [comment]
现在为了同步方便改成了properties，但是发现#相关的注释不会同步过去
