### ISSUE TITLE
appId字段长度是否能长一点？

### ISSUE THREAD

**Issue by newWSmile** [ctripcorp/apollo#2418]
我在使用的时候 如果需要做产品线的划分必须在服务前面加前缀 导致32位长度不够用。
现在我想加长长度，从代码来看我只需要做两部：
1 修改页面JS校验
2 修改数据mysql字段varchar长度
请问作者还有其他需要注意的点嘛

**Comment by nobodyiam** [comment]
主要是这两个点，之前强制appid长度的原因是如果太长了，估计没人记得住自己的app id
