### ISSUE TITLE
客户端拉取全部配置

### ISSUE THREAD

**Issue by rhaonan** [ctripcorp/apollo#2421]
嗨，请问下想一次性拉取namespace上的所有KV，客户端有提供这样的方法么？
1、API的方式，config接口仅有getProperty方法，需要传入key来拿到value。现在客户端也不清楚有哪些key，怎么才能拿到所有的key value呢？ api的方式好像不行。
2、Spring boot的方式，@ConfigurationProperties 给所有的key都加个统一前缀，使用map的方式获取所有的KV。 可以实现，但是很不方便。
3、客户端直接http调用configservice的queryConfig接口。失去了引入client的jar包的意义，也没有长轮询监听配置变化了，并不友好。

所以，现在在客户端不清楚key有哪些的时候拉取一个namespace的所有KV信息怎么实现比较好？

**Comment by nobodyiam** [comment]
com.ctrip.framework.apollo.Config#getPropertyNames，这个接口可以拿到所有的key

**Comment by rhaonan** [comment]
> getPropertyNames

这个可以拿到所有key，获取所有value是需要循环调用getProperty方法么，对于配置比较多的情况下是不是不太友好？

**Comment by nobodyiam** [comment]
都是内存遍历，性能上没啥影响的，话说什么场景需要拿到所有的key和value？

**Comment by rhaonan** [comment]
> 都是内存遍历，性能上没啥影响的，话说什么场景需要拿到所有的key和value？

了解了。业务方具体我也不太清楚，大概是一个灵活配置的页面，前端根据key的数量及KV的内容灵活做不同展示吧，使用场景较为特殊的话我这边自己改下client的放到私服给他们用吧，感谢回答！
