### ISSUE TITLE
portal service构建失败

### ISSUE THREAD

**Issue by lookstorm** [ctripcorp/apollo#2428]
[INFO] Reactor Summary:
[INFO] 
[INFO] Apollo ............................................. SUCCESS [  0.462 s]
[INFO] Apollo BuildTools .................................. SUCCESS [  1.800 s]
[INFO] Apollo Core ........................................ SUCCESS [  0.453 s]
[INFO] Apollo Client ...................................... SUCCESS [  5.727 s]
[INFO] Apollo Common ...................................... SUCCESS [  1.596 s]
[INFO] Apollo Biz ......................................... SUCCESS [  0.962 s]
[INFO] Apollo ConfigService ............................... SUCCESS [  0.336 s]
[INFO] Apollo AdminService ................................ SUCCESS [  0.884 s]
[INFO] Apollo Open Api .................................... SUCCESS [  0.834 s]
[INFO] Apollo Portal ...................................... FAILURE [  5.348 s]
[INFO] Apollo Assembly .................................... SKIPPED
[INFO] Apollo Demo ........................................ SKIPPED
[INFO] Apollo Mock Server ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.468 s
[INFO] Finished at: 2019-07-08T12:10:52+08:00
[INFO] Final Memory: 171M/949M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project apollo-portal: Compilation failure: Compilation failure:
[ERROR] /Users/yumiao3/workspace/apollo/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/FavoriteService.java:[86,43] 找不到符号
[ERROR] 符号:   方法 findById(long)
[ERROR] 位置: 类型为com.ctrip.framework.apollo.portal.repository.FavoriteRepository的变量 favoriteRepository
[ERROR] /Users/yumiao3/workspace/apollo/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/FavoriteService.java:[94,43] 找不到符号
[ERROR] 符号:   方法 findById(long)
[ERROR] 位置: 类型为com.ctrip.framework.apollo.portal.repository.FavoriteRepository的变量 favoriteRepository
[ERROR] /Users/yumiao3/workspace/apollo/apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/service/ConsumerService.java:[120,30] 找不到符号
[ERROR] 符号:   方法 findById(long)
[ERROR] 位置: 类型为com.ctrip.framework.apollo.openapi.repository.ConsumerRepository的变量 consumerRepository
[ERROR] /Users/yumiao3/workspace/apollo/apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/service/ConsumerService.java:[188,28] 找不到符号
[ERROR] 符号:   方法 saveAll(java.lang.Iterable<com.ctrip.framework.apollo.openapi.entity.ConsumerAudit>)
[ERROR] 位置: 类型为com.ctrip.framework.apollo.openapi.repository.ConsumerAuditRepository的变量 consumerAuditRepository
[ERROR] /Users/yumiao3/workspace/apollo/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/defaultimpl/DefaultRolePermissionService.java:[68,37] 找不到符号
[ERROR] 符号:   方法 saveAll(java.lang.Iterable<com.ctrip.framework.apollo.portal.entity.po.RolePermission>)
[ERROR] 位置: 类型为com.ctrip.framework.apollo.portal.repository.RolePermissionRepository的变量 rolePermissionRepository
[ERROR] /Users/yumiao3/workspace/apollo/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/defaultimpl/DefaultRolePermissionService.java:[101,27] 找不到符号
[ERROR] 符号:   方法 saveAll(java.lang.Iterable<com.ctrip.framework.apollo.portal.entity.po.UserRole>)
[ERROR] 位置: 类型为com.ctrip.framework.apollo.portal.repository.UserRoleRepository的变量 userRoleRepository
[ERROR] /Users/yumiao3/workspace/apollo/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/defaultimpl/DefaultRolePermissionService.java:[122,27] 找不到符号
[ERROR] 符号:   方法 saveAll(java.util.List<com.ctrip.framework.apollo.portal.entity.po.UserRole>)
[ERROR] 位置: 类型为com.ctrip.framework.apollo.portal.repository.UserRoleRepository的变量 userRoleRepository
[ERROR] /Users/yumiao3/workspace/apollo/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/defaultimpl/DefaultRolePermissionService.java:[197,50] 找不到符号
[ERROR] 符号:   方法 findAllById(java.util.Set<java.lang.Long>)
[ERROR] 位置: 类型为com.ctrip.framework.apollo.portal.repository.RoleRepository的变量 roleRepository
[ERROR] /Users/yumiao3/workspace/apollo/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/defaultimpl/DefaultRolePermissionService.java:[238,60] 找不到符号
[ERROR] 符号:   方法 saveAll(java.util.Set<com.ctrip.framework.apollo.portal.entity.po.Permission>)
[ERROR] 位置: 类型为com.ctrip.framework.apollo.portal.repository.PermissionRepository的变量 permissionRepository
[ERROR] /Users/yumiao3/workspace/apollo/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/ctrip/WebContextConfiguration.java:[32,21] 找不到符号
[ERROR] 符号:   方法 setInitParameter(java.lang.String,Strings.is[...]verIP)
[ERROR] 位置: 类型为javax.servlet.ServletContext的变量 servletContext
[ERROR] /Users/yumiao3/workspace/apollo/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/ctrip/WebContextConfiguration.java:[34,21] 找不到符号
[ERROR] 符号:   方法 setInitParameter(java.lang.String,Strings.is[...]rPort)
[ERROR] 位置: 类型为javax.servlet.ServletContext的变量 servletContext
[ERROR] /Users/yumiao3/workspace/apollo/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/ctrip/WebContextConfiguration.java:[36,21] 找不到符号
[ERROR] 符号:   方法 setInitParameter(java.lang.String,Strings.is[...]ceUrl)
[ERROR] 位置: 类型为javax.servlet.ServletContext的变量 servletContext
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :apollo-portal

**Comment by nobodyiam** [comment]
看上去是maven拉spring data的依赖没拉到，建议把本地maven中的spring data相关依赖删除后重新编译一下
