### ISSUE TITLE
deployment must be as jar with context path：/

### ISSUE THREAD

**Issue by vihunk** [ctripcorp/apollo#2432]
我们公司全部采用war容器化部署，默认会包含上下文路径，目前前端代码里面是写死的/路径。

**Comment by nobodyiam** [comment]
目前确实是这样的

**Comment by loupipalien** [comment]
nginx 反向代理 portal 也只能是 "/", 非 ”/“ 的 context-path, 部分接口和静态文件的路径就不对了 :bug:

**Comment by WANG352775707** [comment]
这个问题有考虑解决一下吗？我门目前也遇到这个问题了

**Comment by nobodyiam** [comment]
这块主要是前端代码需要梳理一下

**Comment by nobodyiam** [comment]
PR #2754 will solve this problem, please take a look
