### ISSUE TITLE
环境变量指定APOLLO_META，启动依然报错提示没有 apollo.meta

### ISSUE THREAD

**Issue by kollyQAQ** [ctripcorp/apollo#2433]
机器配置了环境变量
> [ops_sit@x risk_access]$ echo $APOLLO_META
http://192.168.209.xxx:8080/    

但是服务启动依然报错
> 2019-07-09 16:49:51.099|WARN|c.c.f.apollo.internals.DefaultMetaServerProvider - Could not find meta server address, because it is not available in neither (1) JVM system property 'apollo.meta', (2) OS env variable 'APOLLO_META' (3) property 'apollo.meta' from server.properties nor (4) property 'apollo.meta' from app.properties

请问是什么原因

紧急求助

**Comment by nobodyiam** [comment]
代码应该是不会错的，建议排查一下系统变量是否设置正确了，比如启动java的用户是否能获取到
