### ISSUE TITLE
现在在不同集群中期望能公用某些配置，怎么弄

### ISSUE THREAD

**Issue by guanfengchen** [ctripcorp/apollo#2435]
现在我们会有不同的集群，但是不同集群中某些配置其实是公用的，麻烦请假一下怎么操作配置比较好。
现在有个想法就是建一个项目，然后项目上建NameSpace，然后把那个项目的NameSpace关联到现有项目的不同集群里面，不知道这个方法是否是正确的做法

**Comment by nobodyiam** [comment]
建一个项目，在里面的默认集群下建公共namespace填入配置即可，其它项目不需要关联该公共namespace的，除非需要进行覆盖
