### ISSUE TITLE
配置的生效范围

### ISSUE THREAD

**Issue by seafowlro** [ctripcorp/apollo#2436]
服务的部署层次：
1 单台，只有一台虚拟机。
2 集群：在一个机房内，多个节点构成一个集群。
3 服务线：我不知道是否有专有名词来描述，意思就是：一个service部署在多个地方，比如：北京、上海、深圳。这里，可以认为是3个集群构成一个服务线。

单台--->集群--->服务线。

一个配置，这里简化为一个key-value，的生效范围分为三种：
1 在服务线生效。
2 在一个集群内有有效。
3 在单个节点有效。

apollo现在的版本，可以做一个配置的服务线、集群范围内生效，好像没有单节点的生效功能？
若有，请指点一下哈，多谢；若没有，是否可以将“配置在单节点范围内生效” 的功能加进去？

配置在单节点范围内生效：一个集群里有5台节点，一个配置在这5台节点上不相同；不同的节点，有不同的配置。

**Comment by wkcaeser** [comment]
你可以看下cluster的概念，应该能满足你的需求

**Comment by seafowlro** [comment]
> 你可以看下cluster的概念，应该能满足你的需求

cluster是说：一个配置在一个cluster里面，不同的节点都一样。我现在是想在一个cluster里面，不同的节点，不一样。

**Comment by wkcaeser** [comment]
每个节点指定成单独的idc就可以做到了   主要是你这个需求感觉很奇怪，在一个集群里面配置还要不一样，那就说明这些节点就不该是一个集群呀    所以为不同的节点指定不同的cluster就可以达到效果

**Comment by seafowlro** [comment]
> 每个节点指定成单独的idc就可以做到了 主要是你这个需求感觉很奇怪，在一个集群里面配置还要不一样，那就说明这些节点就不该是一个集群呀 所以为不同的节点指定不同的cluster就可以达到效果

一个节点组成一个cluster，这和现实的生活中的cluster的概念不一样。
我是想：配置的生效范围可以做到一个节点，一个集群，多个集群。这样的话，配置的生效返回就和实际的部署方式一一对应了起来。

**Comment by wkcaeser** [comment]
配置需要具体到节点这种需求真不场景  部署服务不可能只有单节点吧     这里折中办法就是把这个节点当成一个cluster来处理

**Comment by seafowlro** [comment]
> 配置需要具体到节点这种需求真不常见 部署服务不可能只有单节点吧 这里折中办法就是把这个节点当成一个cluster来处理

单节点的服务确实少见，但在一个集群里面，可以让不同的节点有不同的配置。

**Comment by wkcaeser** [comment]
一个集群内不同的节点有不同的配置   那么这还算一个集群么

**Comment by wkcaeser** [comment]
水平拓展的时候怎么弄

**Comment by seafowlro** [comment]
> 一个集群内不同的节点有不同的配置 那么这还算一个集群么

我觉得：一个小小的配置不同，并不违背n个节点组成一个集群。集群只是为了更好的服务更多的用户，这是一个宏观的概念；而一个配置是一个节点里面的事情。

**Comment by seafowlro** [comment]
> 水平拓展的时候怎么弄

加节点，改配置就可以了。
我们这边有个场景：不同的节点都有一个外网的IP，每个节点都不一样。

**Comment by wkcaeser** [comment]
> > 水平拓展的时候怎么弄
> 
> 加节点，改配置就可以了。
> 我们这边有个场景：不同的节点都有一个外网的IP，每个节点都不一样。

这种场景这个配置不是应该读取环境变量来获取的么，这是一个依赖于当前机器的配置项，依赖当前机器获取不是更好

**Comment by seafowlro** [comment]
> > > 水平拓展的时候怎么弄
> > 
> > 
> > 加节点，改配置就可以了。
> > 我们这边有个场景：不同的节点都有一个外网的IP，每个节点都不一样。
> 
> 这种场景这个配置不是应该读取环境变量来获取的么，这是一个依赖于当前机器的配置项，依赖当前机器获取不是更好

你说的这种方式可行，但不是最好的。通过设置环境变量是可以。但是，它却失去了apollo带来的种种好处，比如动态更新，配置的权限审计。若所有的配置项放在一个地方，这样是不是更好一些。

上面的这个例子只是“每个节点有不同的配置”的其中一个例子。并不是所有的case都和环境变量相关。

**Comment by wkcaeser** [comment]
我的理解如果是一个集群，那么集群内任何一个节点都应该是一样的，最好还是无状态的   那么在集群扩容的时候就可以直接进行，比如制作镜像直接复制而不需要去改动任何东西  所以配置应该是以集群为单位的，如果每个节点上的配置（非依赖于机器本身信息的配置，这类应该在机器上自动获取）都不一样，那就不应该划在一个集群里面

**Comment by nobodyiam** [comment]
这里可以区分物理集群和逻辑集群，物理集群可以是一个，但如果配置不同的话，我理解在『逻辑』上他们的集群是不同的。

在apollo中物理集群是idc，逻辑集群是apollo.cluster，可以通过设置不同的apollo.cluster来实现机器之间的配置不一样
