### ISSUE TITLE
client 端jdk是否存在降级的可能性  #483后续

### ISSUE THREAD

**Issue by yumendedao** [ctripcorp/apollo#2438]
最新版本的1.4.0，无法降级到jdk1.6，因为core中使用了1.7版本的nio
因版本更新，在#483中的patch也已经无法使用
目前的版本确定是无法降版本了？？

**Comment by nobodyiam** [comment]
建议还是推动升级吧，别说1.6，现在1.7都已经不被官方支持了，后续的开源软件估计都是1.8起步了。。

**Comment by yumendedao** [comment]
人手问题和时间问题，现在无法推动升级，只能先放弃在1.6项目使用apollo，感谢回答

**Comment by nobodyiam** [comment]
1.6项目如果对动态配置要求不太高的话，可以参照apollo-client写个简单组件通过Http接口接入
