### ISSUE TITLE
阿波罗在阿里云部署遇到的问题

### ISSUE THREAD

**Issue by 897180673** [ctripcorp/apollo#2441]
最近在阿里云服务器上面部署了apollo，跑起来没有问题，各方面正常

然后在自己的电脑上建了一个springboot 的客户端去读取配置

读取不了，看报错的日志，访问的是阿里云的内网的ip

感觉很奇怪，因为springboot 的客户端配置文件 配置的是阿里云的公网的ip

然后访问阿里云8080端口发现，apollo包含了一个eureka

在注册列表里面有几个实例，当我点击的实例的时候，跳转页就是阿里云的内网ip

阿里云主机ifconfig看到的也只有内网ip

推测是和这个有点关系

发了工单给阿里云的，解释说是  专有网络

![image](https://user-images.githubusercontent.com/19344284/61016217-747ee680-a3c1-11e9-982b-9371ff3b3328.png)

我把springboot应用打包放到阿里云上面，和apollo server同一台服务器就是ok 的没有问题。

如果我就是想本地调试使用

请问apollo 这边有好的解决办法解决这个问题么？

**Comment by JaredTan95** [comment]
@897180673  `-Dapollo.configService=http://config-service的公网IP:端口`, 在本地客户端配置Config Service地址跳过Meta Server试试。

**Comment by 897180673** [comment]
不行，还是获取的是 阿里云的内网

![image](https://user-images.githubusercontent.com/19344284/61025156-5fff1600-a3e2-11e9-8263-62c591858ff0.png)

**Comment by nobodyiam** [comment]
apollo.configService 这个是-D参数，不是配置在文件里面的

**Comment by 897180673** [comment]
OK了,感谢

**Comment by nb2019** [comment]
我就是参考上面的操作 本地怎么调试都不行 服务器上都可以

**Comment by nb2019** [comment]
而且 注册也配置了公网，本地配置也能拉取下来，就是读不到

**Comment by nb2019** [comment]
@nobodyiam 我也是阿里云上部署的Apollo 现在其他服务器正常，唯有本地电脑不行程序读不到配置文件，换了两台开发机器也不行，idea  vm里面也添加了 Apollo-configserver=公网的地址 还是报错

**Comment by nb2019** [comment]
Apollo 版本是1.6的 客户端也是1.6的

**Comment by 897180673** [comment]
> Apollo 版本是1.6的 客户端也是1.6的

JaredTan95 这个人已经回答了 我用他的办法 ok了

**Comment by nb2019** [comment]
@nobodyiam 按照上面的兄弟配置的 本地开发环境 配置能拉取下来 ，程序读不到配置 还是报错 不清楚什么原因 版本也换了 还是不行
