### ISSUE TITLE
Docker build报错：ERROR: http://mirrors.aliyun.com/alpine/v3.8/main: No such file or directory

### ISSUE THREAD

**Issue by wxb2dyj** [ctripcorp/apollo#2445]
按照“分布式指南”之“1.5 Docker部署”时，执行构建命令“docker build -t apollo-configservice .”时的打印信息如下：
Status: Downloaded newer image for openjdk:8-jre-alpine
 ---> f7a292bbb70c
Step 2/12 : MAINTAINER ameizi <sxyx2008@163.com>
 ---> Running in 26e4b2f8bcb5
Removing intermediate container 26e4b2f8bcb5
 ---> 6c6b7c53fc27
Step 3/12 : ENV VERSION 1.5.0-SNAPSHOT
 ---> Running in 5a48fd9a3f6d
Removing intermediate container 5a48fd9a3f6d
 ---> 7f2aa98cb12c
Step 4/12 : ENV SERVER_PORT 8080
 ---> Running in 928de2468b7e
Removing intermediate container 928de2468b7e
 ---> 563600383481
Step 5/12 : ENV DS_URL ""
 ---> Running in 1a248cc2839e
Removing intermediate container 1a248cc2839e
 ---> 0e0cf58fced1
Step 6/12 : ENV DS_USERNAME ""
 ---> Running in bb63cd4ae4c3
Removing intermediate container bb63cd4ae4c3
 ---> 5cf019dde268
Step 7/12 : ENV DS_PASSWORD ""
 ---> Running in f921dc4fa0d1
Removing intermediate container f921dc4fa0d1
 ---> aa623d07fc44
Step 8/12 : RUN echo "http://mirrors.aliyun.com/alpine/v3.8/main" > /etc/apk/repositories     && echo "http://mirrors.aliyun.com/alpine/v3.8/community" >> /etc/apk/repositories     && apk update upgrade     && apk add --no-cache procps unzip curl bash tzdata     && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime     && echo "Asia/Shanghai" > /etc/timezone
 ---> Running in b5ca8062b5d0
fetch http://mirrors.aliyun.com/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://mirrors.aliyun.com/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
**ERROR: http://mirrors.aliyun.com/alpine/v3.8/main: No such file or directory
WARNING: Ignoring APKINDEX.e3d33561.tar.gz: No such file or directory
ERROR: http://mirrors.aliyun.com/alpine/v3.8/community: No such file or directory
WARNING: Ignoring APKINDEX.39d9158a.tar.gz: No such file or directory**
2 errors; 53 distinct packages available
The command '/bin/sh -c echo "http://mirrors.aliyun.com/alpine/v3.8/main" > /etc/apk/repositories     && echo "http://mirrors.aliyun.com/alpine/v3.8/community" >> /etc/apk/repositories     && apk update upgrade     && apk add --no-cache procps unzip curl bash tzdata     && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime     && echo "Asia/Shanghai" > /etc/timezone' returned a non-zero code: 2

这个源是不是有问题了？

**Comment by nobodyiam** [comment]
源应该没有问题，看一下是不是docker中访问网络有问题？
