### ISSUE TITLE
请问如何实现：apollo如何通过Skywalking监控服务调用链？

### ISSUE THREAD

**Issue by bg1011** [ctripcorp/apollo#2448]

**Comment by kezhenxu94** [comment]
Hi @bg1011 , 你是想监控哪些服务调用了 Apollo 吗? 建议在 SkyWalking [新建 issue](https://github.com/apache/skywalking/issues/new), 不过注意由于 SkyWalking 是 Apache 项目, 只能使用英文提 issue 哈

**Comment by nobodyiam** [comment]
@bg1011  apollo在0.4.0版本的时候抽了一层[Tracer SPI](https://github.com/ctripcorp/apollo/releases/tag/v0.4.0)出来，所以应该是可以接入各种监控系统的，如果对Skywalking比较熟悉的话，欢迎提交PR。

**Comment by hepyu** [comment]
我理解应该原生支持吧，apollo虽然是long polling，但说白了也是http，而skywalking是支持http链路追踪的。

**Comment by hepyu** [comment]
这个是apollo-1.4.0使用的httpclient包：
![image](https://user-images.githubusercontent.com/3917749/65829590-965d7a80-e2d9-11e9-8296-7c80ec0ed6de.png)

这个是skywalking-6.4.0支持的httpclient-plugin：
![image](https://user-images.githubusercontent.com/3917749/65829608-bab95700-e2d9-11e9-9b08-25d1e58d450f.png)

两者是吻合的，正打算试。

**Comment by hepyu** [comment]
看代码以及实践，确实都不行，SK目前是没有做处理的。

**Comment by JaredTan95** [comment]
> 看代码以及实践，确实都不行，SK目前是没有做处理的。

看标题我将问题拆分两种情况：
1、 监控Apollo-Config、Admin、Portal之间的调用以及拓扑。
2、 监控Apollo-Client 与 Config之间的调用及拓扑。

第一种情况：Portal与Config/Admin之间采用RestTemplate/HttpClient 发起调用，这个插件在Skywalking支持列表。
因此，你可以看到如下截图：

![image](https://user-images.githubusercontent.com/12468337/66534384-9ca8ed80-eb48-11e9-9468-28b170d30a3f.png)

![image](https://user-images.githubusercontent.com/12468337/66534405-b0ecea80-eb48-11e9-9a8e-36f89aa1b987.png)

第二种情况，Apollo-Client 采用的是 HttpURLConnection 发起Http请求。应该和 HttpClient 有些区别。目前 Skywalking 并没有针对 HttpURLConnection 采集的插件，所以抓取不到链路。后续看具体需求Skywalking社区会考虑增加该插件。

**Comment by kezhenxu94** [comment]
> 目前 Skywalking 并没有针对 HttpURLConnection 采集的插件

@JaredTan95 有的吧, 在可选插件中, https://github.com/apache/skywalking/pull/3171

**Comment by JaredTan95** [comment]
> > 目前 Skywalking 并没有针对 HttpURLConnection 采集的插件
> 
> @JaredTan95 有的吧, 在可选插件中, [apache/skywalking#3171](https://github.com/apache/skywalking/pull/3171)

哦，一时忘了这个可选插件。

**Comment by JaredTan95** [comment]
采用HttpURLConnection 是可以追踪到的：


可选插件使用可以灿开一下： https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/README.md#bootstrap-class-plugins

**Comment by JaredTan95** [comment]
暂时关闭了。

**Comment by hepyu** [comment]
赞！我研究研究~

**Comment by nobodyiam** [comment]
Nice!

**Comment by hepyu** [comment]
@JaredTan95 

按照这个方案，我在我们生产环境的K8S里上线了，确实work:
![image](https://user-images.githubusercontent.com/3917749/66728848-0a6f5500-ee7a-11e9-8c07-9386ef50a285.png)

后续整理下放到这个issue。

**Comment by hepyu** [comment]
生产实践落地方案的总结位于：
https://github.com/hepyu/k8s-app-config/tree/master/product/standard/apollo-skywalking-pro

默认使用local pv，可以直接容器化运行。生产环境需要改为云存储。

**Comment by nobodyiam** [comment]
非常感谢，案例已经加入wiki

https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1#512-skywalking
