### ISSUE TITLE
如何为集群分群权限？

### ISSUE THREAD

**Issue by oojeek** [ctripcorp/apollo#2449]
我们的场境是一个项目有多个集群，不同的人管理各自负责的集群，相互之间不能修改配置，如何为同一个项目不同集群分配权限？

**Comment by nobodyiam** [comment]
目前的权限模型是到环境+Namespace级别，不支持集群级别。

好奇问一下，同一套代码在同一个环境的不同集群由不同的人负责？是出一个什么样的管理场景呢？

**Comment by oojeek** [comment]
> 目前的权限模型是到环境+Namespace级别，不支持集群级别。
> 
> 好奇问一下，同一套代码在同一个环境的不同集群由不同的人负责？是出于一个什么样的管理场景呢？

我们主要开发行业软件，软件部署在私有云环境，同一套软件会被多个客户使用，但每个客户的配置文件有差异，每个运维会负责一部分客户，因此配置文件的管理就成了一个比较大的麻烦。apollo配置中心从功能上可以较大程度地解决我现在遇到的问题，我的想法是把配置中心安装在阿里云上，把每个客户当成一个集群，遇到的问题就是configservice的外网安全性问题和权限问题

**Comment by nobodyiam** [comment]
每个客户使用不同的appId？通过appId区分的话权限隔离性是最好的。

如果大部分配置都一样的话，可以把一样的配置放在公共namespace里面，每个客户覆盖自己不一样的就好了。
