### ISSUE TITLE
unicode配置无法转成中文

### ISSUE THREAD

**Issue by voyagertanyao** [ctripcorp/apollo#2450]
在apollo上面将value配置成中文unicode格式，但是java程序中利用@value("${xxx}")获取的结果没有转义成中文，请问是否是配置apollo的时候用中文就行了？

**Comment by kezhenxu94** [comment]
> 在apollo上面将value配置成中文unicode格式，但是java程序中利用@value("${xxx}")获取的结果没有转义成中文，请问是否是配置apollo的时候用中文就行了？

是的，直接测试一下就可以验证了 :)
