### ISSUE TITLE
《使用apollo配置zuul动态路由不能保证数据有序性的问题》

### ISSUE THREAD

**Issue by MrtKing** [ctripcorp/apollo#2451]
我在apollo中的配置如下
![1](https://user-images.githubusercontent.com/48673349/61298563-06974c80-a811-11e9-821b-092c2f1923a6.jpg)

Zuul启动后读取到的配置是无序的，如下
![2](https://user-images.githubusercontent.com/48673349/61299562-e6688d00-a812-11e9-8e38-595163308ea1.jpg)

这样就会导致在请求 /user/debug/** 时，在做match()的时候被  /user/**  先匹配到了，然后返回并结束匹配过程
![3](https://user-images.githubusercontent.com/48673349/61300211-24b27c00-a814-11e9-87ce-117205fb3646.jpg)

这样就会导致 /user/debug/** 匹配的服务始终不能被访问，只有 /user/** 匹配的服务能访问。
可能我描述的不是很清楚，另附上一篇 Zuul的路径匹配文章：
http://blog.didispace.com/spring-cloud-tips-zuul-path-config/

**Comment by nobodyiam** [comment]
这里分为两块，服务端发布的配置可以通过简单的修改为LinkedHashMap来[实现](https://github.com/nobodyiam/apollo/commit/f7ed6cd41fe79c68fd1e7289c6a10522972db596)，不过客户端最终是使用Properties来存储配置的，而Properties继承自Hashtable，所以默认会重新排序的，不知是否有啥好的建议？

**Comment by Jiiiiiin** [comment]
@nobodyiam https://github.com/ctripcorp/apollo/issues/2273 @MrtKing 建议大家在这里一起讨论讨论 呵呵

**Comment by songdragon** [comment]
> 这里分为两块，服务端发布的配置可以通过简单的修改为LinkedHashMap来[实现](https://github.com/nobodyiam/apollo/commit/f7ed6cd41fe79c68fd1e7289c6a10522972db596)，不过客户端最终是使用Properties来存储配置的，而Properties继承自Hashtable，所以默认会重新排序的，不知是否有啥好的建议？

试着使用LinkedHashMap替代Proerties，实现了一版。testcase都能通过。本地测试了下，顺序是正确的。不知道有没有更好的方法。
