### ISSUE TITLE
使用Docker部署Apollo后.net客户端集成homepageUrl问题

### ISSUE THREAD

**Issue by 786744873** [ctripcorp/apollo#2453]
使用Docker部署Apollo后.用net客户端集成，发现访问了http://47.111.XXX.XXX:1042/services/config?appId=xxx_front_end_server&ip=192.168.103.204地址，然后收到返回[{"appName":"APOLLO-CONFIGSERVICE","instanceId":"6cd0279a50a8:apollo-configservice:8080","homepageUrl":"http://192.168.112.3:8080/"}]，这里返回的地址192.168.112.3是docker内部的宿主地址，应该返回47.111.XXX.XXX才对，请问如何处理

**Comment by nobodyiam** [comment]
参考[网络策略](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#14%E7%BD%91%E7%BB%9C%E7%AD%96%E7%95%A5)

**Comment by vincentshow** [comment]
> 参考[网络策略](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#14%E7%BD%91%E7%BB%9C%E7%AD%96%E7%95%A5)

这里面的方案貌似要修改启动脚本`start.sh`，但是[docker-quick-start](https://github.com/ctripcorp/apollo/tree/master/scripts/docker-quick-start)示例中使用的`nobodyiam/apollo-quick-start`这个`image`没有提供额外的修改方式。

是不是能够修改下该`image`的启动逻辑，增加覆盖默认设置的操作？还是说对`docker`部署，apollo官方推荐的方式就是不用已有的`image`，要自己`build`？

**Comment by nobodyiam** [comment]
quick start是用做demo的，实际部署的时候可以按照[Docker部署](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#15-docker%E9%83%A8%E7%BD%B2)打镜像
