### ISSUE TITLE
为什么MetaServer不能支持多个环境

### ISSUE THREAD

**Issue by Nonlone** [ctripcorp/apollo#2456]
根据这里 [传送门](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#2131-%E8%B0%83%E6%95%B4apolloportaldb%E9%85%8D%E7%BD%AE) 所说，一个环境需要一个ConfigServer和AdminServer，而按照配置建议，ConfigServer和MetaServer在一个JVM实例，这样子情况下，是不是就是一个环境就是一个MetaServer？这样子在配置 env 这个参数有什么意义？MetaServer不能提供多个环境的配置数据吗

**Comment by wkcaeser** [comment]
控制环境的有两个参数  一个叫env  一个叫cluster（IDC）   cluster的名字随便定，env就那几个固定的

**Comment by Nonlone** [comment]
就是两者的意思其实是相反的，我理解DC肯定是网络隔离的，但是ENV不一定需要强的网络隔离，我用阿波罗env这个参数来做DC划分，用cluster这个参数做环境

**Comment by wkcaeser** [comment]
env属于大环境的划分  比如开发、测试、线上   而cluster（IDC）是来做大环境内部的划分的，比如不同的IDC，但他们都属于线上环境

**Comment by Nonlone** [comment]
我明白这样子理解，但是如果环境划分的时候直接就直接 应用隔离了，这样子在应用规模小的时候有点资源浪费，所以想开发和测试这些内部环境共用一个MetaServer，生产当然是隔离另外一个

**Comment by wkcaeser** [comment]
开发和测试如果用的同一套网络的话，可以只用两个大环境0-0  不是的话就没办法了

**Comment by nobodyiam** [comment]
开发和测试环境可以用一套环境，通过集群来区分
