### ISSUE TITLE
回滚操作问题,版本1.4

### ISSUE THREAD

**Issue by JanberHu** [ctripcorp/apollo#2458]
删除部分配置后，执行回滚操作
![Snipaste_2019-07-19_17-35-28](https://user-images.githubusercontent.com/48580920/61526434-fec3ec00-aa4c-11e9-8bd9-62133cda50f2.png)
删除标识还在，有删除标识的配置可以生效，但如果继续添加新配置点击发布，带有删除标识的配置在发布后仍会被删除，我想保留删除的配置，那回滚操作没有意义

**Comment by kezhenxu94** [comment]
回滚是指回滚已经发布了的配置，你删除的配置没有发布所以回滚操作不会把他们加回来，这个时候只能手动添加回这些删除的配置了

**Comment by Reason0701** [comment]
https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#2-%E6%9C%AC%E5%9C%B0%E8%BF%90%E8%A1%8C%E6%97%B6portal%E4%B8%80%E7%9B%B4%E6%8A%A5env-is-down

**Comment by nobodyiam** [comment]
#2952 已经增加撤销配置修改功能
