### ISSUE TITLE
关于Apollo自身日志填满磁盘的问题

### ISSUE THREAD

**Issue by kevinten10** [ctripcorp/apollo#2459]
**问题描述如下：**

我在阿里云学生服务器通过docker部署了apollo，硬盘容量为50GB，运行数月之后，硬盘几乎填满，导致docker容器被kill。怀疑是apollo自身的日志导致。

想请问apollo系统对自身产生的日志有无过期清除策略，如何及时的清理apollo自身产生的日志呢？

**Comment by kezhenxu94** [comment]
@kevinten10 Apollo 日志打印使用 logback 框架，可以修改 logback.xml 使用 rotate  file appender 并且指定单个日志文件大小/保留天数/日志文件数等，详情可以参考 logback 文档或 Google
