### ISSUE TITLE
构建出来的镜像运行报错 Error loading shared library libstdc++.so.6

### ISSUE THREAD

**Issue by beckjin** [ctripcorp/apollo#2460]
Error: failed /usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/server/libjvm.so, because Error loading shared library libstdc++.so.6: Exec format error (needed by /usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/server/libjvm.so)

**Comment by nobodyiam** [comment]
贴一下重现步骤吧？

**Comment by beckjin** [comment]
1. 拉取 master 最新的源代码
1. 编译
1. 执行以下3步
   ![image](https://user-images.githubusercontent.com/7261408/61585983-237aa980-ab9c-11e9-9348-bff156e2b96f.png)
1.  docker run 就出现了如下错误：
   Error: failed /usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/server/libjvm.so, because Error loading shared library libstdc++.so.6: Exec format error (needed by /usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/server/libjvm.so)

**Comment by nobodyiam** [comment]
我本地按照这个步骤跑没有遇到问题。。

你是否改过Dockerfile的内容？或者尝试一下把镜像文件都删掉重新拉取一次吧

```bash
docker ps
```

```bash
CONTAINER ID        IMAGE                  COMMAND                  CREATED              STATUS              PORTS                    NAMES
39775de7aeb3        apollo-configservice   "/apollo-configservi…"   About a minute ago   Up About a minute   0.0.0.0:8080->8080/tcp   apollo-configservice
```

**Comment by beckjin** [comment]
我重新安装了 docker，正常了。
