### ISSUE TITLE
替换成zookeeper

### ISSUE THREAD

**Issue by colben** [ctripcorp/apollo#2461]
如果只用来做配置管理，是否可以换成 zookeeper ？

**Comment by nobodyiam** [comment]
zookeeper在设计上是用来做分布式协调的，当然它可以用来做配置管理，只是可能不是特别合适。

我猜你是指apollo使用到的eureka替换成zookeeper？这里eureka和zookeeper的角色是服务发现，不是配置管理。

**Comment by Xpecya** [comment]
借个楼，我猜他想说的（或者说是我想问的）是，注意到apollo中似乎是没有手写paxos算法（以及其他类似算法）的部分，根据文档描述，分布式环境下的数据依然是在mysql单机上维护，mysql挂了就靠缓存，缓存如果没开启就game over。这种做法...倒不能说不可行，只不过，对于更看重安全性，拒绝缓存策略的用户，是不是可以考虑将mysql的部分替换为基于zookeeper集群的配置中心？这样起码访问压力可以分担出去，还可以随时做扩容...此外就是，是否考虑过应用MyCAT等mysql集群化方案替换目前的mysql单机？从我个人的角度，我可能更希望看见zookeeper的方式，you opinions? thank you

**Comment by nobodyiam** [comment]
其实很难讲把mysql的部分替换为zk是否能提升『安全性』，毕竟对大部分公司而言，运维mysql的成本远低于zk。
至于mysql这一层是否使用集群化方案，这个对apollo是透明的，可以自己基于成本和实际使用场景的角度加以考虑。
