### ISSUE TITLE
提供的http接口中 message 及 datacenter传入的是什么内以及其作用

### ISSUE THREAD

**Issue by Stuart2333** [ctripcorp/apollo#2467]
正在修改C++下的客户端，对http接口上message/datacenter的作用不太清楚

**Comment by nobodyiam** [comment]
datacenter是指物理的数据中心，也就是机房的意思，具体可以参考[1.2.4.2 Cluster（集群）](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#1242-cluster%E9%9B%86%E7%BE%A4)
