### ISSUE TITLE
./demo.sh stop时报错

### ISSUE THREAD

**Issue by ayamzh** [ctripcorp/apollo#2468]
on bean with name 'scopedTarget.eurekaClient': org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'eurekaInstanceConfigBean': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!  8080 8070端口都没法释放

**Comment by nobodyiam** [comment]
看一下最上面的报错
