### ISSUE TITLE
docker build 失败，怀疑dockerfile 路径有问题

### ISSUE THREAD

**Issue by xingxing9688** [ctripcorp/apollo#2470]
v1.4.0 版本  构建
docker build -t apollo-configservice .   失败，提示
Step 5/8 : ADD apollo-configservice-${VERSION}-github.zip /apollo-configservice/apollo-configservice-${VERSION}-github.zip
ADD failed: stat /var/lib/docker/tmp/docker-builder282786745/apollo-configservice-1.4.0-github.zip: no such file or directory

使用的dockerfile 如下

FROM openjdk:8-jre-alpine
MAINTAINER ameizi <sxyx2008@163.com>

ENV VERSION 1.4.0

RUN echo "http://mirrors.aliyun.com/alpine/v3.8/main" > /etc/apk/repositories \
    && echo "http://mirrors.aliyun.com/alpine/v3.8/community" >> /etc/apk/repositories \
    && apk update upgrade \
    && apk add --no-cache procps unzip curl bash tzdata \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone

ADD apollo-configservice-${VERSION}-github.zip /apollo-configservice/apollo-configservice-${VERSION}-github.zip

RUN unzip /apollo-configservice/apollo-configservice-${VERSION}-github.zip -d /apollo-configservice \
    && rm -rf /apollo-configservice/apollo-configservice-${VERSION}-github.zip \
    && sed -i '$d' /apollo-configservice/scripts/startup.sh \
    && echo "tail -f /dev/null" >> /apollo-configservice/scripts/startup.sh

EXPOSE 8080

CMD ["/apollo-configservice/scripts/startup.sh"]

**Comment by kezhenxu94** [comment]
@xingxing9688 Dockerfile 同级目录下有 apollo-configservice-1.4.0-github.zip 吗？需要先手动下载 apollo-configservice-1.4.0-github.zip

**Comment by xingxing9688** [comment]
同级目录是没有这个zip 报的，但是在target 目录是有的

**Comment by kezhenxu94** [comment]
> 同级目录是没有这个zip 报的，但是在target 目录是有的

你得把它复制过来

**Comment by xingxing9688** [comment]
明白了，谢谢，docker build 的时候需要在同级目录才可以，不是同级无法ADD 谢谢啊！
docker  build 完毕执行一个命令就可以了
cp ./apollo-configservice/target/apollo-configservice-*-github.zip   ./apollo-configservice/src/main/docker
