### ISSUE TITLE
Apollo嵌入到iframe无法显示

### ISSUE THREAD

**Issue by bg1011** [ctripcorp/apollo#2472]
请问：目前发现把Apollo的Portal嵌入到iframe中无法显示，应该修改那个配置吗？
Refused to display 'http://xxxx:8070/signin' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

**Comment by WANG352775707** [comment]
在portal的AuthConfiguration中 写了 http.headers().frameOptions().sameOrigin(); 限定了同源。
需要改代码http.headers().frameOptions().disable().addHeaderWriter(new StaticHeadersWriter("X-FRAME-OPTIONS", "ALLOW-FROM example1.com"));  允许嵌在example1.com中

**Comment by WANG352775707** [comment]
http.headers().frameOptions().disable(); 可禁用该策略，但同时会带来安全问题，所有网站都可嵌入
