### ISSUE TITLE
为什么要将ConfigService和EurekaServer放在同一个进程

### ISSUE THREAD

**Issue by crecel** [ctripcorp/apollo#2475]
Apollo源码为什么要将ConfigService和Eureka服务端放在同一个进程，而AdminService和Eureka客户端放在同一个进程

**Comment by nobodyiam** [comment]
可以看下[Why Eureka](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E4%BB%8B%E7%BB%8D#451-why-eureka)

**Comment by crecel** [comment]
> 可以看下[Why Eureka](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E4%BB%8B%E7%BB%8D#451-why-eur
