### ISSUE TITLE
start-failed 由于start-stop-daemon 版本 

### ISSUE THREAD

**Issue by bzzhang** [ctripcorp/apollo#2484]
![image](https://user-images.githubusercontent.com/12998976/62093768-17ce6780-b2ad-11e9-94e9-15b211a3a001.png)

由于start-stop-daemon版本不支持--no-close 选项导致apollo config和admin服务起不起来

**Comment by bzzhang** [comment]
![image](https://user-images.githubusercontent.com/12998976/62093704-e6ee3280-b2ac-11e9-8f64-50a808e304b4.png)

**Comment by nobodyiam** [comment]
操作系统是suse？可以参考下 #2147
