### ISSUE TITLE
ApolloApplicationContextInitializer执行时，application.yml的配置还没有加载，导致无法获取到apollo.bootstrap.enabled变量

### ISSUE THREAD

**Issue by iGloria170** [ctripcorp/apollo#2485]
ApolloApplicationContextInitializer执行时，application.yml的配置还没有加载，导致无法获取到apollo.bootstrap.enabled变量
![image](https://user-images.githubusercontent.com/36941023/62122732-fc894980-b2f8-11e9-832e-8c03e9ccad3a.png)
![image](https://user-images.githubusercontent.com/36941023/62122791-1b87db80-b2f9-11e9-9ee0-1d0d562f9d67.png)

springcloud版本 Finchley.SR2 
springboot 2.1.2

**Comment by nobodyiam** [comment]
这里应该会进来两次的，第一次是bootstrap阶段（读取bootstrap.yml），第二次进来会读取application.yml

**Comment by iGloria170** [comment]
嗯，是会进来第二次的。拉不到配置原来是运维配置的内网域名没做解析导致的(-_-;) ；不过稍稍延误了下上线上环境的时间┐（´ー）┌
