### ISSUE TITLE
apollo测试环境占用虚拟内存40G问题

### ISSUE THREAD

**Issue by zhou405X** [ctripcorp/apollo#2486]
昨天遇到一个问题 , apollo线下环境占用了40个G的虚拟内存, 导致其他系统启动不了 
请问为什么会占用这么大的虚拟内存, 如何改进
![TIM截图20190731143448](https://user-images.githubusercontent.com/24349911/62188945-63157280-b3a0-11e9-9690-197a5dd408dd.png)

**Comment by nobodyiam** [comment]
jvm参数是否限制了堆，metaspace等大小？

**Comment by zhou405X** [comment]
> jvm参数是否限制了堆，metaspace等大小？

没有限制 ,直接用的git上面的配置

**Comment by nobodyiam** [comment]
加个限制吧
