### ISSUE TITLE
这个字段 好像没有作用，openApi ,,    // whether to append namespace prefix for public namespace name     private boolean appendNamespacePrefix = true;

### ISSUE THREAD

**Issue by chenGit1763113879QQ** [ctripcorp/apollo#2487]
// whether to append namespace prefix for public namespace name
    private boolean appendNamespacePrefix = true;

**Comment by nobodyiam** [comment]
这个字段是open api的调用方设置的，服务端会读取这个属性做不同的处理

**Comment by chenGit1763113879QQ** [comment]
> 这个字段是open api的调用方设置的，服务端会读取这个属性做不同的处理
建立namespace 的时候 也没有什么前缀？？1.3版本的

**Comment by nobodyiam** [comment]
appendNamespacePrefix=true时，对公共namespace会自动添加部门前缀

**Comment by chenGit1763113879QQ** [comment]
2019-08-08 16:06:05.082 DEBUG [main] c.c.l.apollo.openapi.client.HttpClient: 请求 = ///apps/dev1_1_appId18/appnamespaces, 参数： {"name":"system7","appId":"dev1_1_appId18","format":"properties","isPublic":true,"appendNamespacePrefix":true,"comment":"公共配置7","dataChangeCreatedBy":"apollo","dataChangeLastModifiedBy":null,"dataChangeCreatedTime":null,"dataChangeLastModifiedTime":null}
 生成新的 nameSpace 返回结果为：HttpResponseProxy{HTTP/1.1 200  [X-Content-Type-Options: nosniff, X-XSS-Protection: 1; mode=block, Cache-Control: no-cache, no-store, max-age=0, must-revalidate, Pragma: no-cache, Expires: 0, X-Frame-Options: SAMEORIGIN, Content-Type: application/json;charset=UTF-8, Transfer-Encoding: chunked, Date: Thu, 08 Aug 2019 08:06:05 GMT] ResponseEntityProxy{[Content-Type: application/json;charset=UTF-8,Chunked: true]}}
{
  "name": "system7",
  "appId": "dev1_1_appId18",
  "format": "properties",
  "isPublic": true,
  "comment": "公共配置7",
  "id": 10035,
  "isDeleted": false,
  "dataChangeCreatedBy": "apollo",
  "dataChangeCreatedTime": "2019-08-08T16:06:05.490+0800",
  "dataChangeLastModifiedBy": "apollo",
  "dataChangeLastModifiedTime": "2019-08-08T16:06:05.490+0800"
}

**Comment by chenGit1763113879QQ** [comment]
http://106.12.25.204:8070/config.html?#/appid=dev1_1_appId18

**Comment by chenGit1763113879QQ** [comment]
没有 对公共namespace会自动添加部门前缀

**Comment by nobodyiam** [comment]
我测试是OK的。

POST /openapi/v1/apps/dev1_1_appId18/appnamespaces HTTP/1.1
Authorization: 填入token
Content-Length: 154
Content-Type: application/json; charset=UTF-8
Host: 106.12.25.204:8070
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.6 (Java/1.8.0_201)
Accept-Encoding: gzip,deflate


```json
{
    "name":"test-create-namespace",
    "appId":"dev1_1_appId18",
    "format":"properties",
    "isPublic":true,
    "appendNamespacePrefix":true,
    "dataChangeCreatedBy":"test1"
}
```

返回的结果
```json
{
    "name":"dev1.test-create-namespace",
    "appId":"dev1_1_appId18",
    "format":"properties",
    "isPublic":true,
    "appendNamespacePrefix":true,
    "comment":"",
    "dataChangeCreatedBy":"test1",
    "dataChangeLastModifiedBy":"test1",
    "dataChangeCreatedTime":"2019-08-10T21:00:16.783+0800",
    "dataChangeLastModifiedTime":"2019-08-10T21:00:16.783+0800"
}
```
