### ISSUE TITLE
apollo集成prometheus

### ISSUE THREAD

**Issue by tanxiaosheng** [ctripcorp/apollo#2489]
为了监控apollo的状态，需要集成prometheus， 但是集成过程中出现问题，应该是gson导致返回json序列化失败，请问有没有集成prometheus组件的计划？另外集成actuator也有类似的问题，许多指标返回json序列化失败。 @nobodyiam

**Comment by nobodyiam** [comment]
apollo使用gson应该只是为了性能考虑，功能上应该没啥影响的，你可以先把 com.ctrip.framework.apollo.common.controller.HttpMessageConverterConfiguration 上的`@Configuration`注解去掉看看是否集成prometheus就没有问题了？

**Comment by tanxiaosheng** [comment]
还是不行，一直在报错误，我引入的是micrometer-registry-prometheus

HttpMediaTypeNotAcceptableException: Could not find acceptable representation
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:239)

@nobodyiam

**Comment by tanxiaosheng** [comment]
apollo-common/src/main/java/com/ctrip/framework/apollo/common/controller/WebMvcConfig.java中

configurer.ignoreAcceptHeader(true).defaultContentType(MediaType.APPLICATION_JSON_UTF8)

只接受 json 但是 prometheus返回的是text/plain， 当初设计的时候为什么限制只接受json呢？ @nobodyiam

**Comment by nobodyiam** [comment]
这个设置是默认返回json的意思吧？

是否能提供下和prometheus集成的步骤？

**Comment by JaredTan95** [comment]
我们这边已经集成了prometheus，稍后PR :P

**Comment by JaredTan95** [comment]
close, supported.

**Comment by xixikaikai** [comment]
> 已经集成了prometheus，稍后PR :P

go to: 0510
