### ISSUE TITLE
apollo多数据中心部署问题

### ISSUE THREAD

**Issue by yechao4j** [ctripcorp/apollo#2490]
我们公司的业务特点：服务需要在全国多个省，如北京、广东、江苏、浙江等部署同一个服务，还有海外几个大区：北美、南美、新加坡、欧洲也部署了该服务。
请问在这种场景下Apollo服务该怎么部署比较好？
主要是考虑到跨全球网络不是非常好，如果中心化部署，担心各区域获取Apollo配置或修改后同步配置会比较慢，延迟较大。
有什么好的建议吗?

**Comment by lepdou** [comment]
建议 Portal 和 Admin Server 国内部署一套就可以。Config Server 可以 local 部署，并且启动的时候，加上机房信息。同时注册到 eureka 的时候，带上机房信息。最后，修改一下 Apollo-Client，可以根据机房信息过滤 Config Server ，这样就能实现拉配置机房内收敛。因为 Config Server 有内存缓存，所以异地读库也只会发生一次。
按照上面的部署方式，写配置都是国内同一个机房，所以没有延迟问题。Config Server 感知配置发布事件也是通过轮训数据库的。美国到新加坡的延迟差不到200ms，所以整个延迟也就是几百毫秒，是能够接受的。
多数据中心主要解决客户端读配置的问题，实现了机房内收敛，就能解决。

**Comment by yechao4j** [comment]
Thanks, i will try it later.

**Comment by yechao4j** [comment]
@lepdou 我看ctrip部署策略，https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#22124-%E9%85%8D%E7%BD%AEapollo-portal%E7%9A%84meta-service%E4%BF%A1%E6%81%AF
每个环境，每个机房都部署了configservice和adminservice，我们生产环境有多个数据中心，线下也有多个环境：dev, fat, uat等，是不是每个数据中心和每个环境都要部署adminservice和configservice？

**Comment by lepdou** [comment]
@yechao4j 
每个环境必须部署一套 AdminService 和 ConfigService ~
至于数据中心，没有强制要求每个数据中心都部署，主要是解决跨机房读数据的问题。
