### ISSUE TITLE
apollo支持自动登录吗

### ISSUE THREAD

**Issue by zewade** [ctripcorp/apollo#2492]
大家好，请教一个问题。公司想把apollo portal嵌入到运维管理平台，请问一下不改portal的代码，如何在管理平台点击portal首页的链接的时候，把用户名和密码传过去，从而跳过登录页面，直接访问首页？

**Comment by nobodyiam** [comment]
接入公司统一的SSO即可

**Comment by zewade** [comment]
目前还不接单点登录。只是使用apollo内置的spring security是否有现成的方法简单实现跳过登录这个功能

**Comment by nobodyiam** [comment]
这个可能要对登录页面做一点改造，比如识别到url参数中有用户名等信息时自动填充并提交登录表单，不过这个会在url中暴露用户名和密码信息，不推荐

**Comment by xiaojun207** [comment]
apollo的登录是一个post的接口：/signin，参数是：
username: apollo, password: admin, login-submit: 登录
这样三个参数。
你可以在你们的运维平台里面，做一个登录提交的中间代码（不需要修改apollo代码）。

> 这个可能要对登录页面做一点改造，比如识别到url参数中有用户名等信息时自动填充并提交登录表单，不过这个会在url中暴露用户名和密码信息，不推荐

这里是post方法，不会在url里暴露用户名密码。不过，这个操作需要在浏览器上做，需要把用户名和密码传输到前台。

**Comment by happyyangyuan** [comment]
> 接入公司统一的SSO即可

请问SSO对接的指引文档有没有呀？
