### ISSUE TITLE
apollo 如何做到子系统如 portal 与adminservice 之间的数据一致性的？

### ISSUE THREAD

**Issue by HaapyArthur** [ctripcorp/apollo#2493]
apollo 如何做到子系统如 portal 与adminservice 之间的数据一致性的？

Portal 在同步 App 到 Admin Service 时，发生网络异常，或者由于其他原因导致同步失败。那么此时App信息只 存在于 Portal ，而不在于 Admin Service 中，这时Apollo是如何做到最终一致的？

**Comment by nobodyiam** [comment]
页面上会出现『补缺环境』和『补缺namespace』按钮

**Comment by HaapyArthur** [comment]
我下载源代码本地调试，启动了portal服务，故意把adminservice 服务停掉(想模拟网络超时)了，
然后页面没出现『补缺环境』和『补缺namespace』按钮，而是提示联系『管理员』

**Comment by nobodyiam** [comment]
『补缺环境』和『补缺namespace』是在admin service正常的情况下才会出现，admin service如果停掉了是没法补缺的。
