### ISSUE TITLE
能否提供自定义Injector SPI的功能？

### ISSUE THREAD

**Issue by kongzhenhao** [ctripcorp/apollo#2494]
我们想实现自己的Injector，能否在Injector扫描时优先返回自定义的，如果没有再返回apollo自身的？

**Comment by nobodyiam** [comment]
自定义`META-INF/services/com.ctrip.framework.apollo.internals.Injector`文件并确保该文件在apollo的classpath之前就可以了，参见apollo-test：https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/test/resources/META-INF/services/com.ctrip.framework.apollo.internals.Injector
