### ISSUE TITLE
@ApolloConfigChangeListener无法监听到yml文件变化

### ISSUE THREAD

**Issue by mrhxf** [ctripcorp/apollo#2495]
在配置中心修改properties文件参数之后，客户端可以监听到变化，但是修改yml配置之后，客户端毫无反应，请大神帮帮忙

**Comment by nobodyiam** [comment]
1.3.0版本以上支持，namespace名字记得要带上后缀，比如`@ApolloConfigChangeListener("xxx.yaml")`，参见[3.2.3 Spring Annotation支持](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#323-spring-annotation%E6%94%AF%E6%8C%81)
