### ISSUE TITLE
宋大神，请问怎么优雅的在服务端支持连接数限流？

### ISSUE THREAD

**Issue by denghuichao** [ctripcorp/apollo#2497]
需要在服务端添加长连接数限流，包括服务端总连接数以及单个IP发起的连接数限制。请教下有没有优雅的方式实现这样的需求？需要限流配置能够动态调整。

**Comment by nobodyiam** [comment]
是指apollo的服务端增加连接数限流？

服务端总连接数可以通过配置tomcat参数来实现，不过貌似不支持动态调整
单个IP发起的连接数限制这个要代码实现了

**Comment by denghuichao** [comment]
谢谢，已经通过代码实现。是指configservice long polling连接数限制。
