### ISSUE TITLE
无法读取关联的公共配置

### ISSUE THREAD

**Issue by ahxinin** [ctripcorp/apollo#2499]
V1.5版本，新建了一个父项目，并创建了一个公共的namespace；然后创建子项目，关联到公共的namespace，提示以下信息：
当前公共namespace的所有者* 没有关联此namespace,请联系* 的所有者在* 项目里关联此namespace

**Comment by nobodyiam** [comment]
打开公共namespace的项目页面，看下页面是否左侧是否有`补缺namespace`的按钮

**Comment by nobodyiam** [comment]
打开公共namespace的项目页面，看下页面是否左侧是否有`补缺namespace`的按钮

**Comment by ahxinin** [comment]
HA配置问题，导致部分接口302了。已经解决，谢了。
