### ISSUE TITLE
apollo容器化后apollo-portal启动多个pod无法登陆的问题

### ISSUE THREAD

**Issue by hepyu** [ctripcorp/apollo#2500]
RT，我根据apollo官方提供的k8s容器化方法制作镜像容器化后，admin和config都是配置了3副本，没有问题。

但是当我把apollo-portal也改为3副本时，apollo-portal输入正确的用户名和密码就登陆不了了，是不是有session之类的机制啥的呢。

将apollo-portal改为一个副本时，就正常了。

**Comment by nobodyiam** [comment]
看下`sessionAffinity: ClientIP`是否配置了，https://github.com/ctripcorp/apollo/blob/master/scripts/apollo-on-kubernetes/kubernetes/service-apollo-portal-server.yaml#L69

**Comment by hepyu** [comment]
@nobodyiam 根据apollo官方的配置，我把admin,config,portal都加上了sessionAffinity: ClientIP，但依然不行；

我访问apollo-portal不是走的NodePort，而是走的ingress代理，会不会是这个原因？

**Comment by hepyu** [comment]
> @nobodyiam 根据apollo官方的配置，我把admin,config,portal都加上了sessionAffinity: ClientIP，但依然不行；
> 
> 我访问apollo-portal不是走的NodePort，而是走的ingress代理，会不会是这个原因？

@nobodyiam 是这个原因，再把ingress加一个亲和性就可以了：
![image](https://user-images.githubusercontent.com/3917749/62858999-85a77400-bd2e-11e9-8a43-be26371e6694.png)
