### ISSUE TITLE
Spring3.x集成Apollo后.无法监听到配置的变化

### ISSUE THREAD

**Issue by tanrui988** [ctripcorp/apollo#2501]
已经增加了监听,在项目运行中,发现值还是没有变化. 是不是还需要做其他的配置？
Config apolloConfig = ConfigService.getAppConfig();

apolloConfig.addChangeListener(new ConfigChangeListener() {
            @Override
            public void onChange(ConfigChangeEvent configChangeEvent) {
                for (String key : configChangeEvent.changedKeys()) {
                    ConfigChange change = configChangeEvent.getChange(key);
                    System.setProperty(String.valueOf(key), String.valueOf(change.getNewValue()));
                }
            }
        });

**Comment by nobodyiam** [comment]
先打开客户端的debug日志看看

**Comment by tanrui988** [comment]
@nobodyiam 大佬. 我看了下源码发现点问题，想跟您确认下. config通过长连接获取配置然后与DefaultConfig.m_configProperties里做比对.比较出有差异的配置,然后再去调用自定义的ConfigChangeListener.  在方法DefaultConfig.updateAndCalcConfigChanges的177行里有一段代码:
change.setNewValue(this.getProperty(change.getPropertyName(), change.getNewValue()));
这里是设置新的值给change对象. 但是这个getProperty的获取方式有点问题.他的第一步居然是获取System.getProperty(key)的值. 然后才获取m_configProperties的值. 实际上m_configProperties对象里是在前面几行代码里更新的，肯定是最新的数据. 但是这里去先获取了System里的值. 由于我们项目是比较旧的，所以在工程启动的时候会将所有的配置信息全部加载到System里. 所以就导致这一步始终获取到的是旧值. 导致后面change.setNewValue时覆盖了新的值.从而导致了我的ConfigChangeListener没有生效.  
请帮忙看看我的理解对否？ 谢谢解答。

**Comment by nobodyiam** [comment]
这个是设计的行为，system property的配置优先级最高

**Comment by tanrui988** [comment]
如果是这样的话，那我们启动的时候就不能向system property赋值了. 这样就等于在system property旧值. 会导致在Apollo Protal里修改了配置后无法监听到了. 
另外请问, 按照您的设计, system property 的值来自于哪里？ 怎么设置的？在配置变化的时候,变更的值会先更新到system property ？
谢谢解答

**Comment by nobodyiam** [comment]
system property一般认为是用于单机临时调整的配置，比如-D参数
