### ISSUE TITLE
ApolloJsonValue对于配置中包含空格，｛，｝等特殊字符用string解析异常

### ISSUE THREAD

**Issue by yesterday11** [ctripcorp/apollo#2502]
ApolloJsonValue：会用Gson将值转换为对应的对象
内部使用的是Gson解析json数据，配置内容如果包含空格，｛，｝等，用String类型接受会报json解析异常，原因是对于接受类型String的json，Gson把这些符号当作终结符，解析的时候只会返回出现这些特殊符前面的字符，完整性校验时就会报json解析异常。
目前是用@value注解代替ApolloJsonValue，不知道能不能优化

**Comment by nobodyiam** [comment]
能写一下复现步骤吗？

另外，用`@Value`注解是拿到原始string吧，通过啥再转成对象？

**Comment by yesterday11** [comment]
在apollo上配置，  比如key: apollo.test   value：hello 空格
hello与空格之间是特殊字符，比如空格，｛，｝
![image](https://user-images.githubusercontent.com/29722582/62847688-20418c00-bd0a-11e9-9941-f6684fff8b2b.png)
在项目中配置获取如下：
```@RestController
@Api(description = "test")
@RequestMapping("/apllo")
public class Demoendpoint {
    @ApolloJsonValue("${apollo.test}")
    private String test;
    @ApiOperation(value = "配置")
    @GetMapping(value = "test")
    public Result<Map<String, Object>> getConfigWarnings() {
        return Result.success();
    }

}```

在启动的时候会报：
> Initialization of bean failed; nested exception is com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 8 path $

**Comment by nobodyiam** [comment]
你是说填入的是`hello { } `这种？这个不是json啊，下面的这个才是json的示例

```json
[{"someString":"hello ,{} ","someInt":100},{"someString":"world!","someInt":300}]
```

**Comment by yesterday11** [comment]
嗯嗯，有些弹窗配置中，有需要加入空格的场景，方便客户端换行。｛｝这两个字符，只是一起举个栗子，重点在空格这块，现在貌似只能用@value处理。
>  @ApolloJsonValue("${apollo.test}")
>     private String test;

**Comment by nobodyiam** [comment]
你能举个实际的例子吗？加空格也没问题啊

```json
[
    {
        "someString": "hello ,   { }    ",
        "someInt": 100
    },
    {
        "someString": "world!",
        "someInt": 300
    }
]
```

**Comment by yesterday11** [comment]
不好意思，可能是我描述的问题：
![image](https://user-images.githubusercontent.com/29722582/63671024-09725d80-c811-11e9-9fba-631aa4e1160c.png)

配置：这个配置的只是一行文字，中间含有空格，不是一个具体对象

`hello 空格`

接收配置：
```
@ApolloJsonValue("${apollo.test}")
private String test;
```

**Comment by nobodyiam** [comment]
看明白了。。

这类非json的数据不应该使用`@ApolloJsonValue`注入的，使用`@Value`即可。
