### ISSUE TITLE
DefaultApplicationProvider 的 initialize 方法初始化问题

### ISSUE THREAD

**Issue by kangjiabang** [ctripcorp/apollo#2508]
DefaultApplicationProvider 的 initialize 方法初始化 时候首先通过 当前的类加载器加载/META-INF/app.properties 文件。
InputStream in = Thread.currentThread().getContextClassLoader().getResourceAsStream(/META-INF/app.properties);
加载不到然后根据
当前类的getResourceAsStream方法加载，
ClassLoader 加载文件时默认不需要添加前缀 "/"，因此getContextClassLoader().getResourceAsStream(/META-INF/app.properties); 不会加载到文件，应该写成
Thread.currentThread().getContextClassLoader().getResourceAsStream(/META-INF/app.properties);

**Comment by tanrui988** [comment]
现在导致了什么问题？

**Comment by kangjiabang** [comment]
> 现在导致了什么问题？

没有什么问题，就是这块代码先使用contextClassLoader加载不到资源，只能使用 DefaultApplicationProvider.class.getResourceAsStream(APP_PROPERTIES_CLASSPATH) 才能加载。

**Comment by nobodyiam** [comment]
merged
