### ISSUE TITLE
请教一个关于apollo性能的问题

### ISSUE THREAD

**Issue by KT924** [ctripcorp/apollo#2509]
就微服务的框架来看，当一个业务系统拆分成多个应用的时候，按照apollo客户端获取配置的方式来看，假设现在我有上万个服务第一次接入到apollo的时候，应用与应用之间同时去拉取配置的话是否会造成网络抖动或者其他的性能问题？谢谢！

**Comment by tanrui988** [comment]
上万个服务这个量级还是很吓人的。不是一般企业能够吼住的. 即使有.我理解拉取配置的时候都是通过HTTP请求去获取的，获取的配置也小得很.所以应该不会有性能问题的.我的个人理解。

**Comment by KT924** [comment]
虽然上述的情况是比较极端，但是我自己理解按照这种方式去推配置的时候，如果我的配置文件较大，服务比较多的时候，就会造成网络带宽的占用吧。这方面还是缺少了数据的支撑。

**Comment by tanrui988** [comment]
也要权衡下，配置文件很大。能变化的有多少.要结合实际项目吧。往极端了想,这种阻塞不会是长时间的.反而是长连接是否会影响。看宋大佬之前的回复说，不会有问题。

**Comment by nobodyiam** [comment]
1. config service可以无限扩展的
2. config service可以开启配置缓存
3. apollo的[NotificationControllerV2](https://github.com/ctripcorp/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/controller/NotificationControllerV2.java#L272)在推送配置时如果发现推送的客户端比较多，会采用分批方式推送
