### ISSUE TITLE
ConfigService.getConfigFile()读取properties的时候会漏掉一些配置

### ISSUE THREAD

**Issue by qtzheng** [ctripcorp/apollo#2510]
如题：当配置文件很大时getContext（）方法读取到的字符串不全。我在使用过程中发现13个配置项只读取到了11个配置项。
版本：1.4.0
spring boot版本：2.1.6

**Comment by nobodyiam** [comment]
提供下完整的重现步骤？

**Comment by qtzheng** [comment]
.properties后缀没写，加上后缀就没问题了。
