### ISSUE TITLE
http方式请求配置数据的时候，不能选择「环境列表」里面自定义的环境吗

### ISSUE THREAD

**Issue by zfuming** [ctripcorp/apollo#2511]
目前通过http方式请求，只有cluster，没有看到选择环境，这导致的问题是，我在同一个server_url下面创建了多个环境，我就只能通过http获取到第一个环境的配置
http://{server_url}/configfiles/json/{app_id}/{cluster}/{namespace}

**Comment by nobodyiam** [comment]
每个环境需要部署独立的config service/admin service和configdb

**Comment by zfuming** [comment]
那我现在一个config service里面添加了不同的环境，怎么样获取不同环境的配置呢？

**Comment by nobodyiam** [comment]
每个环境的config service的url都是不同的呀
