### ISSUE TITLE
使用apollo-mockserver构建单元测试出错

### ISSUE THREAD

**Issue by ankelen** [ctripcorp/apollo#2513]
22:17:15.663 [main] DEBUG com.ctrip.framework.apollo.internals.RemoteConfigRepository - Loading config from http://localhost:63125/configs/ApolloNoAppIdPlaceHolder/default/application?ip=192.168.0.112
Exception in thread "MockWebServer" java.lang.NoSuchFieldError: H2_PRIOR_KNOWLEDGE
	at okhttp3.mockwebserver.MockWebServer$3.processConnection(MockWebServer.java:488)
	at okhttp3.mockwebserver.MockWebServer$3.execute(MockWebServer.java:443)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by nobodyiam** [comment]
提供下重现步骤

**Comment by ankelen** [comment]
1. 引入apollo-mockserver依赖
2. 在test下新建resources文件夹，并在其下添加mockdata-application.properties文件（只有两行，即key1=value1和key2=value2）
3. 使用ApolloMockServerApiTest.java中的测试代码
```java
public class Demo {
    @ClassRule
    public static EmbeddedApollo embeddedApollo = new EmbeddedApollo();
    
    @Test
    public void testGetProperty() throws Exception {
        Config applicationConfig = ConfigService.getAppConfig();
        assertEquals("value1", applicationConfig.getProperty("key1", null));
        assertEquals("value2", applicationConfig.getProperty("key2", null));
    }
}
```
4. 运行测试，发生上述错误

**Comment by nobodyiam** [comment]
看上去是你运行时的okhttp3的版本比较老所致，默认传递依赖的版本是3.11.0。

![image](https://user-images.githubusercontent.com/837658/62832652-67754180-bc64-11e9-98cc-27898d528f14.png)

**Comment by ankelen** [comment]
是的，我看到apollo-mockserver中依赖的okhttp和mockwebserver都是3.11.0，但是我引用到项目后，okhttp版变成了3.8.1
![image](https://user-images.githubusercontent.com/22792543/62833459-a362d380-bc71-11e9-8c35-0340ff6895e9.png)

**Comment by nobodyiam** [comment]
应该是被上层的dependencyManagement覆盖了，自己设置一下吧

**Comment by ankelen** [comment]
嗯，自己设置是没问题。主要是被SpringCloud中的dependencyManagement覆盖掉了
