### ISSUE TITLE
查看配置的时候,未发布的配置应该排在最前面吧(个人觉得这样比较人性化一点),不然去查看的时候得翻很久

### ISSUE THREAD

**Issue by caoxi1994** [ctripcorp/apollo#2516]
查看配置的时候,未发布的配置应该排在最前面吧(个人觉得这样比较人性化一点),不然去查看的时候得翻很久,

**Comment by nobodyiam** [comment]
在发布状态上增加排序能力？

![image](https://user-images.githubusercontent.com/837658/63219492-95e3a700-c1a5-11e9-802d-a51d1958ee95.png)

**Comment by caoxi1994** [comment]
是哈

**Comment by JaredTan95** [comment]
supported.
