### ISSUE TITLE
怎么支持细颗粒度筛选

### ISSUE THREAD

**Issue by godsoul** [ctripcorp/apollo#2521]
请问用这个配置心中，怎么增加细颗粒度的筛选呢，比如根据渠道号 客户端版本 ios还是android 当前时间，来控制具体的配置输入，每个筛选是独立的。
能给个实现思路吗？

**Comment by nobodyiam** [comment]
apollo支持4个维度区分配置：

1. 应用
2. 环境
3. 集群(cluster)
4. 命名空间(namespace)

一般会通过集群来实现你上面提到的需求，不过如果颗粒度很细的话，会导致集群非常多？
