### ISSUE TITLE
ApolloApplicationContextInitializer源码中的一个小疑惑

### ISSUE THREAD

**Issue by 351524388** [ctripcorp/apollo#2522]
com.ctrip.framework.apollo.spring.boot.ApolloApplicationContextInitializer
中有一行代码是这么写的
  private static final String[] APOLLO_SYSTEM_PROPERTIES = {"app.id", ConfigConsts.APOLLO_CLUSTER_KEY,
      "apollo.cacheDir", ConfigConsts.APOLLO_META_KEY};
为何有些使用接口常量，有些直接用字符串？

**Comment by nobodyiam** [comment]
应该都可以使用接口常量
