### ISSUE TITLE
.net 客户端的本地开发模式不支持

### ISSUE THREAD

**Issue by czd890** [ctripcorp/apollo#2525]
修改C:\opt\settings\server.properties文件，设置env为Local：

在apollo.net 项目中搜索 server.properties，没有任何结果。是不是.net客户端没有实现这个特性呀

**Comment by nobodyiam** [comment]
支持的

dotnet-core:
https://github.com/ctripcorp/apollo.net/blob/dotnet-core/Apollo/Internals/ConfigRepositoryFactory.cs#L23

dotnet-4.0:
https://github.com/ctripcorp/apollo.net/blob/master/Apollo/Spi/DefaultConfigFactory.cs#L23
