### ISSUE TITLE
用户密码频繁失效

### ISSUE THREAD

**Issue by reignsr** [ctripcorp/apollo#2526]
目前使用apollo-1.4.0，使用apollo原生的用户管理和安全认证方式，最近几个月隔三差五就有用户的密码失效不能登陆，重新设置密码后正常。最近一次还出现了超级管理员apollo用户密码失效的现象。看了看apollo的密码加解密算法，似乎也没有有效期的限制。
没有人为篡改密码，也排除输入错误，出现这种情况的用户、时间点和时间间隔也没什么规律可寻。
请问官方是否在密码上有什么设定？或者有可能是什么原因？ @nobodyiam

**Comment by nobodyiam** [comment]
没有啥设定啊，估计是被人为改过吧？建议遇到失效的密码后看下数据库中的Password hash值是否变了

**Comment by reignsr** [comment]
我们再观察下吧，有问题再请教。多谢！

**Comment by haroldchenhao** [comment]
今天遇到了同样的问题，管理员apollo账号突然登录报错。

**Comment by reignsr** [comment]
@haroldchenhao 我们依旧会出现用户密码失效问题，已经出现过不少用户了。可以确定的是，肯定不是人工修改的，因为只有管理员有设置用户密码的权限，至今还未搞清出现问题的原因。

**Comment by haroldchenhao** [comment]
@reignsr 管理员apollo账号的密码失效怎么解决的？ 我重置了Users表的apollo密码为默认安装sql中的密码 '$2a$10$7r20uS.BQ9uBpf3Baj3uQOZvMVvB1RN3PYoKE94gtz2.WAOuiiwXS'，登录还是提示失败=.=

**Comment by reignsr** [comment]
@haroldchenhao 密码的hash值直接复制到表里好像是不行，我之前也试过。我有两套apollo服务，等于两套portal，两套用户，我想把其中一套的用户数据都复制到另一套的数据库中，结果，复制过去的密码都不好使。随便问一下 @nobodyiam ，这是啥原因？
@haroldchenhao 你的情况可以这样处理，在portaldb的serverconfig表的superAdmin字段中追加有效用户，使用这个用户登陆。然后在界面上重置apollo超级用户的密码。

**Comment by reignsr** [comment]
@haroldchenhao 超级管理员建议多设置几个用户，避免出现密码失效问题。我这里设置了三个用户。

**Comment by haroldchenhao** [comment]
@reignsr 嗯，好的，这些建议确实不错，谢了。 我刚才看了看默认的 sql 排查了下，发现失效的 apollo 用户在 Authorities 表中不存在导致无法登陆，手动 insert 之后就正常了。你可以观察下是不是这个原因。

**Comment by reignsr** [comment]
@haroldchenhao 多谢！我也排查下。

**Comment by nobodyiam** [comment]
@reignsr 密码的hash值和环境无关的，比如初始化脚本中`apollo`的密码hash值就是代表了`admin`

**Comment by CodFrm** [comment]
我们也遇到这问题了,很恐怖

之前同事的不行,今天管理员账号不行了

**Comment by CodFrm** [comment]
后续发现 `Authorities` 表中的`('apollo', 'ROLE_user')` 记录消失了,添加了一条之后可以登录了

@reignsr 可以试一下

**Comment by reignsr** [comment]
@CodFrm 感谢！我这边也确认了原因了。不过还没深入探寻Authorities 表的数据为什么会无故缺失。好在这个问题总算是解决了。

**Comment by shelltea** [comment]
遇到了同样的问题，十几个用户的密码失效。

**Comment by reignsr** [comment]
@shelltea 目前确认 Authorities 表中对应用户的记录消失了，手工添加后可以正常登录。解决方案如此，暂时还不清楚出现这种情况的原因是什么，如有发现， 望能告知。

**Comment by shelltea** [comment]
@reignsr  好的，感谢。我们对Authorities表增加了一些监控，看能否找到原因。
