### ISSUE TITLE
外网client connect timed out

### ISSUE THREAD

**Issue by SoWhatI** [ctripcorp/apollo#2527]
我在内网部署，然后对外是meta域名，但在外网启动client后，会报Long polling failed, will retry in 16 seconds. appId: ---, cluster: ---, namespaces: ---, long polling url: http://---:8080/notifications/v2?--- reason: Could not complete get operation [Cause: connect timed out]，好像是直接用configservice的内网ip连接超时，请问大神应该怎么解决呢。

**Comment by xiaojun207** [comment]
你的问题，应该是网络外部通过meta域名，返回的实际configserverIp是内网地址，所以读取不到。
你可以尝试，客户端（0.11.0版本及以上）通过-Dapollo.configService=http://config-service的公网IP:端口来跳过meta service的服务发现

详细可以看一下
[分布式部署指南](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97)中，“1.4、网络策略”

**Comment by SoWhatI** [comment]
> 你的问题，应该是网络外部通过meta域名，返回的实际configserverIp是内网地址，所以读取不到。
> 你可以尝试，客户端（0.11.0版本及以上）通过-Dapollo.configService=[http://config-service的公网IP:端口来跳过meta](http://config-service%E7%9A%84%E5%85%AC%E7%BD%91IP:%E7%AB%AF%E5%8F%A3%E6%9D%A5%E8%B7%B3%E8%BF%87meta) service的服务发现
> 
> 详细可以看一下
> [分布式部署指南](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97)中，“1.4、网络策略”

文档中说不要把configservice直接暴露公网啊。

> apollo-configservice和apollo-adminservice是基于内网可信网络设计的，所以出于安全考虑，请不要将apollo-configservice和apollo-adminservice直接暴露在公网

**Comment by WANG352775707** [comment]
你好，请问你现在有解决方案了吗？

**Comment by nobodyiam** [comment]
如果实在要外网访问的话，可以考虑为config service申请一个slb给外网访问，在slb上设置一些安全策略
