### ISSUE TITLE
关于其他语言接入，请求接口并没有保持住60s，直接返回了304。

### ISSUE THREAD

**Issue by wanghuaijing** [ctripcorp/apollo#2531]

**Comment by wanghuaijing** [comment]
if (mergedReleaseKey.equals(clientSideReleaseKey)) {
      // Client side configuration is the same with server side, return 304
      response.setStatus(HttpServletResponse.SC_NOT_MODIFIED);
      Tracer.logEvent("Apollo.Config.NotModified",
          assembleKey(appId, appClusterNameLoaded, originalNamespace, dataCenter));
      return null;
    }

**Comment by nobodyiam** [comment]
保持住60秒指的是notifications接口，详见[1.4 应用感知配置更新](https://github.com/ctripcorp/apollo/wiki/%E5%85%B6%E5%AE%83%E8%AF%AD%E8%A8%80%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97#14-%E5%BA%94%E7%94%A8%E6%84%9F%E7%9F%A5%E9%85%8D%E7%BD%AE%E6%9B%B4%E6%96%B0)
