### ISSUE TITLE
如何支持用户不可新增App权限？

### ISSUE THREAD

**Issue by shidong697800** [ctripcorp/apollo#2533]
apollo支持创建多个用户，每个用户都可以创建App，且App默认只对自身可见。有这样一种场景，为保证App的统一管理，我们想要统一由管理者创建App，保持最高权限，同时下发给不同的用户去管理App，但下发的用户不能新增和删除App，只能更改 发布数据等。我如何做到不同用户 不可新建App？目前有解决方式么。

**Comment by lawrencewu** [comment]
在点击 "创建" 项目的时候, 判断是不是有权限就好了

**Comment by nobodyiam** [comment]
在最新的master代码中已经有这块的代码合入了，#2309
