### ISSUE TITLE
win10下快速启动项目失败

### ISSUE THREAD

**Issue by 891877295** [ctripcorp/apollo#2536]
本机git是最新版的。
报错信息
./service/apollo-service.jar: line 168: /c/Program: No such file or directory

**Comment by 891877295** [comment]
本机git是最新版的。
报错信息
./service/apollo-service.jar: line 168: /c/Program: No such file or directory

**Comment by kezhenxu94** [comment]
Duplicate of #512

**Comment by nobodyiam** [comment]
安装git bash最新版应该能解决这个问题
