### ISSUE TITLE
BaseEntity类中的IsDeleted字段定义中columnDefinition="Bit default '0'"语法错误，在MySql数据库中，无法自动创建表。

### ISSUE THREAD

**Issue by lvyuqi** [ctripcorp/apollo#2539]
BaseEntity类中的IsDeleted字段定义中columnDefinition="Bit default '0'"语法错误，在MySql数据库中，无法自动创建表。
"Bit default '0'"需要去掉单引号，修改为 "Bit default 0"，
或者去掉 columnDefinition="Bit default '0'"，hibernate自动创建tinyInt类型字段，支持boolean。
或者，更改为 columnDefinition="boolean default false"

**Comment by nobodyiam** [comment]
默认安装都是通过apollo提供的sql文件做的，不会在mysql中自动创建表的？你是特意为之？

不过确实没有测试过在mysql中自动创建表，跑ut的时候是在h2中自动创建表。

**Comment by lvyuqi** [comment]
我们在使用hibernate场景下，很少使用sql创建表，一般都是用hibernate自动创建，所以，发现有这种问题。

**Comment by nobodyiam** [comment]
目前来看这个对大部分用户没有影响，不过也欢迎提交PR~
