### ISSUE TITLE
同一开发环境配置双活数据间没有同步

### ISSUE THREAD

**Issue by jiayaoO3O** [ctripcorp/apollo#2542]
### 问题 : 通过设置之后 , 在apollo页面中添加数据 , 会发生点击发布之后页面刷新 , 数据没有出现 , 还是空白 , 即点击发布其实只是发布到A机器上了,B机器还是空白.
刷新前:
![image](https://user-images.githubusercontent.com/22891632/63631511-29f8b700-c65b-11e9-8ff8-c3c15a4cd316.png)
刷新后:
![image](https://user-images.githubusercontent.com/22891632/63631514-3aa92d00-c65b-11e9-9011-39631cdbc49d.png)

### 配置如下:
1.两台机子的数据库的配置,都添加了对方的eureka:
![image](https://user-images.githubusercontent.com/22891632/63631418-cfab2680-c659-11e9-8e4e-e9cd87f7089a.png)
![image](https://user-images.githubusercontent.com/22891632/63631422-eb163180-c659-11e9-9766-f322929596c6.png)
2.运行portal的A机子的apollo-env.properties中的dev.mate只添加了自己
![image](https://user-images.githubusercontent.com/22891632/63631435-2e70a000-c65a-11e9-9777-968dbae54954.png)
3.运行了portal的A机子的eureka信息页面
![image](https://user-images.githubusercontent.com/22891632/63631492-de460d80-c65a-11e9-8e78-610bc91f1d44.png)

B机子的eureka信息页面
![image](https://user-images.githubusercontent.com/22891632/63631486-d4bca580-c65a-11e9-9008-a1ccddd336de.png)
Apollo系统信息页面
![image](https://user-images.githubusercontent.com/22891632/63631357-e309c200-c658-11e9-8c19-be5c7d88868a.png)
请问我想要双活还有哪些位置没有设置对?为什么两台机子的eureka信息页面不一致?

**Comment by jiayaoO3O** [comment]
我是不是理解错了?其实实际上同一开发环境的的两个机子,使用的是同一个数据库而不是单独的两个数据库?

**Comment by nobodyiam** [comment]
一个环境使用一个configdb，不管部署了多少个config service/admin service

**Comment by jiayaoO3O** [comment]
@nobodyiam 我后来想明白过来了,谢了 👍
