### ISSUE TITLE
@ConfigurationProperties(prefix= 热更新示例代码问题

### ISSUE THREAD

**Issue by hubuyt** [ctripcorp/apollo#2546]
![image](https://user-images.githubusercontent.com/11042146/63676465-928f9180-c81d-11e9-9a9c-b8e826d26972.png) 图中红色代码是异步的吧 ，打日志没有意义啊

**Comment by hubuyt** [comment]
我自己试验，经常出现前后打印值一样的

**Comment by nobodyiam** [comment]
销毁bean是同步执行的，所以再次打印出来的应该是新的值
