### ISSUE TITLE
修改ApolloConfigDB.ServerConfig的值这一步真让人头疼

### ISSUE THREAD

**Issue by loboan** [ctripcorp/apollo#2548]
如果没有设置这个注册中心地址为configServer的地址，项目 能够正常运行，但是创建工程的时候一直报错。找了半天问题，最后在文档里面看到这句配置。改完就好了，好恶心啊这个配置，不能通过配置文件或者给个系统设置来修改么，那样会简单很多。

**Comment by nobodyiam** [comment]
服务端的参数都支持-D或在application.properties方式配置的
