### ISSUE TITLE
apollo 的各个server 以及portal使用docker化，然后起本地的client访问，初始化始终失败

### ISSUE THREAD

**Issue by wtf182** [ctripcorp/apollo#2549]
![image](https://user-images.githubusercontent.com/22926569/63739395-98d64a00-c8bf-11e9-9cbc-e1cb5bbde71b.png)

client去连Apollo的eureka，获取到eureka的IP始终是docker内部的IP，而不是我配置的IP，怎么才能使它使用配置的IP，而不是docker容器内的？

**Comment by jiayaoO3O** [comment]
看分布式部署文档的网络设置那一部分,有个注册指定ip到meta server的介绍的
