### ISSUE TITLE
如何有效控制 InstanceConfig 中的记录数量

### ISSUE THREAD

**Issue by haoyu36** [ctripcorp/apollo#2550]
apollo 运行一段时间后，InstanceConfig 数据表记录会非常多，除了手动删除外，apollo 有没有接口可以控制，比如只保留一定时间内的，或者可以直接关闭写记录

**Comment by nobodyiam** [comment]
这个数量和客户端实例数量有关的，运行一段时间后应该是处于一个比较平稳的状态，不会一直增长的
