### ISSUE TITLE
编辑、发布互斥操作，对”namespacelock“使用的是物理删除

### ISSUE THREAD

**Issue by yesterday11** [ctripcorp/apollo#2551]
namespacelock表预留的有IsDeleted字段，但每次编辑、发布操作完后，表中新增的数据都会物理删除，不知道这块是出于什么考虑

> 重现步骤：
> 
> > 1.将 namespace.lock.switch 配置设置为true
> > 2.A用户编辑配置，B用户发布

**Comment by nobodyiam** [comment]
锁是通过数据库的唯一键来实现的，按照目前的表结构如果做软删的话没法实现
