### ISSUE TITLE
openApi getNamespace method can't get public namespace （openApi无法获取公共命名空间）

### ISSUE THREAD

**Issue by thankuu** [ctripcorp/apollo#2553]
#### version

```xml 
<dependency>
        <groupId>com.ctrip.framework.apollo</groupId>
        <artifactId>apollo-openapi</artifactId>
        <version>1.4.0</version>
</dependency>
```

#### describe

- 项目未进行创建关联公共命名空间时，无法通过openApi获取对应项目（非公共项目）下的改命名空间。
1.  假设有`common`,` app`两个项目
2. 在`common`项目下创建`FX.common`公共`namespace`, 通过以下方法无法直接在`app`下获取`FX.common`命名空间，返回404状态码。
```java 
OpenNamespaceDTO commonDTO = apolloOpenApiClient.getNamespace("app",
                            env,
                            cluster,
                            "FX.common");
```
3. 在`app`项目下通过控制台创建关联命名空间`FX.common`后，通过以上方法可以正常获取。
4. 如果不通过控制台，而使用openApi以下方法创建，则返回400状态码，内容为`Public AppNamespace FX.common already exists in appId: common`。
``` java
OpenAppNamespaceDTO openAppNamespaceDTO = new OpenAppNamespaceDTO();
                    openAppNamespaceDTO.setAppId("app");
                    openAppNamespaceDTO.setName("FX.common");
                    openAppNamespaceDTO.setPublic(false);
                    openAppNamespaceDTO.setFormat("properties");
                    openAppNamespaceDTO.setDataChangeCreatedBy("apollo");
                    apolloOpenApiClient.createAppNamespace(openAppNamespaceDTO);
```

> 能否提供一个方法通过openApi关联公共namespace,使其能够获取并修改

**Comment by nobodyiam** [comment]
getNamespace返回的是app下某个集群中的namespace对象
createAppNamespace是为app创建appNamespace对象

两者操作的对象不同，所以会有上述的行为

目前open api中还没有关联公共namespace的接口，不过主体逻辑都已经有了，可以参考`com.ctrip.framework.apollo.portal.controller.NamespaceController#createNamespace`写一下open api的实现

**Comment by JianleiZhang** [comment]
> getNamespace返回的是app下某个集群中的namespace对象
> createAppNamespace是为app创建appNamespace对象
> 
> 两者操作的对象不同，所以会有上述的行为
> 
> 目前open api中还没有关联公共namespace的接口，不过主体逻辑都已经有了，可以参考`com.ctrip.framework.apollo.portal.controller.NamespaceController#createNamespace`写一下open api的实现

你好，请问能给一个关联公共Namespace的OpenApi示例吗？

**Comment by nobodyiam** [comment]
@JianleiZhang 看了下，目前没有关联公共namespace的接口，如果有需求的话，可以贡献一个

**Comment by JianleiZhang** [comment]
> @JianleiZhang 看了下，目前没有关联公共namespace的接口，如果有需求的话，可以贡献一个

有需要的，但是我不会Java，所以能否麻烦您提供一下。
