### ISSUE TITLE
设置apollo.bootstrap.enable=true后，配置在apollo中的spring.profiles.include配置无法读取

### ISSUE THREAD

**Issue by xiejiefeng** [ctripcorp/apollo#2555]
spring boot版本为2.1.5
spring cloud版本为Greenwich.SR2
已经在bootstrap.yml中添加
apollo:
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
可是依旧读取不到配置在apollo中的spring.profiles.include，导致启动发生异常。

**Comment by nobodyiam** [comment]
能给个详细一些的例子吗？
