### ISSUE TITLE
env的设计目的是什么呢？指定了metaServer是不是就相当于指定了env呢？

### ISSUE THREAD

**Issue by zhiguangliu** [ctripcorp/apollo#2558]
如题。
实际使用中，不配置这个东西也是可以的。而且env的配置是在应用以外的，相当于是服务器级别的配置。
请问为什么要做这个设计呢？这个配置的实际使用场景是什么呢？

**Comment by zhiguangliu** [comment]
我刚刚试了一下，我本机设置env=dev，然后指定了生产环境的metaServer，获取到的是生产环境的配置。

**Comment by jiayaoO3O** [comment]
mate server是可以配置很多个环境的,如果你设置的是apollo.meta=xxxx,那就是指定了某一个环境;如果你设置的是dev.meta=xxxx,那你就可以设置很多条服务信息,例如dev.meta,fat.meta,pro.meta等等,这个时候你设置了env=dev那就读取dev.meta;如果你设置了env=fat,那就读取fat.meta

**Comment by wkcaeser** [comment]
env这个配置项我的理解是主要用于多机房或者网络完全隔离的几个环境

**Comment by jiayaoO3O** [comment]
每一层环境只有"一个"meta server , apollo默认支持4层环境,分别是dev fat uat pro ,而他们的地址便是dev.meta=xxx ; fat.meta=xxx  ; uat.meta=xxx ; pro.meta=xxx , 他们是4个不同的地址,你问env设计的目的是什么,就是为了让运行的程序能够通过判断env的值,来自动选择上面4个地址中的配置信息.

**Comment by jiayaoO3O** [comment]
如果你整个系统只用到一层,例如只使用一个dev层,那你并不需要指定什么env等于什么环境,因为只有一个环境,这个时候你在配置文件中直接指定apollo.meta(注意是apollo.meta不是dev.meta)就可以指定metaserver了,但是如果你有多层环境,那就需要按照我上面说的,配置多条地址,然后配置env等于对应的环境名字

**Comment by zhiguangliu** [comment]
谢谢，理解了。
