### ISSUE TITLE
log4j2-spring.xml如何配置才能从Apollo下发并生效？

### ISSUE THREAD

**Issue by Gsealy** [ctripcorp/apollo#2559]
您好，

> 当前环境：
> Apollo: 1.4.0
> spring boot: 2.1.4.RELEASE
> spring cloud: Greenwich.SR2

我现在想把`log4j2-spring.xml`放到Apollo上，经查好像从1.3.0就已经支持了，但是我这边能拉取配置，但是无法生效，还是会使用默认的日志配置加载，LogSystem没加载xml配置

**bootstrap.properties** 配置如下
```properties
app.id=xxx-config
apollo.meta=http://IP:8080/
apollo.bootstrap.enabled=true
apollo.bootstrap.namespaces=application,log4j2-spring.xml
apollo.bootstrap.eagerLoad.enabled=true
```
服务端就正常新建`log4j2-spring.xml`的私有Namespace，填写配置且发布成功，如下图所示：

![image](https://user-images.githubusercontent.com/26080361/63990554-f6180880-cb16-11e9-8e79-034a0bfb80fa.png)

请问现在是可以把Log xml配置放在Apollo上面吧？那我应该如何操作呢？

**Comment by nobodyiam** [comment]
log4j2-spring.xml还是放在代码中的，里面一些动态的配置可以通过stringProperty从apollo读取

**Comment by Gsealy** [comment]
@nobodyiam 感谢感谢，那我先这么处理吧

**Comment by nisiyong** [comment]
> log4j2-spring.xml还是放在代码中的，里面一些动态的配置可以通过stringProperty从apollo读取

@nobodyiam log4j2-spring.xml如果引用apollo上的key，测试了都无效。这两个配置都加了
```
apollo.bootstrap.enabled=true
apollo.bootstrap.eagerLoad.enabled=true
```

**Comment by Gsealy** [comment]
@nisiyong 不是`log4j2-spring.xml`去获取key，是系统可以获取apollo配置，然后结合在一起。例如，动态配置Log等级，`logging.level`可以放到Apollo上，一些基本的配置就可以放到`log4j2-spring.xml`里面

**Comment by nobodyiam** [comment]
@nisiyong 

log4j2-spring.xml中的stringProperty可以放在apollo上的

**Comment by PeterLiuWT00376** [comment]
@nobodyiam, “log4j2-spring.xml中的stringProperty可以放在apollo上的”，您说的这个方式，可以提供一个demo吗？或者具体的参考文档？

**Comment by nisiyong** [comment]
这个问题后来我扩展了log4j2的加载逻辑，让其优先从apollo上加载log4j2.xml这个namespace，加载不到就走log4j2的默认逻辑

**Comment by Gsealy** [comment]
我是修改了源码，然后在公共 namespace 中，加了一个properties的log4j2的配置

**Comment by nobodyiam** [comment]
@PeterLiuWT00376 

上述描述有误，应是`logback-spring.xml`

https://github.com/ctripcorp/apollo-use-cases/blob/master/spring-boot-dubbo/spring-boot-dubbo-provider/src/main/resources/logback-spring.xml

**Comment by yanghaiyan** [comment]
我也遇见过这个问题，log4j2会加载两次配置，先是加载apollo的配置，设置日志级别，后来还会加载本地的配置文件，来设置日志级别，这样会导致apollo配置中的的日志配置被本地覆盖掉

**Comment by HuiBear** [comment]
@nisiyong 你好，如果是绕过meta-server，直接连接config-service，apollo-pluigin-log4j2是不起作用的，我现在的环境是在k8s环境，没有用apollo所提供的注册中心，而是用k8s自己的service

**Comment by nisiyong** [comment]
@HuiBear 跟 k8s 无关，你可以看下这个文档，需要设置参数启用下
https://github.com/apolloconfig/apollo-java/tree/main/apollo-plugin/apollo-plugin-log4j2

**Comment by HuiBear** [comment]
@nisiyong 我设置了这个参数，跟踪了一下代码，这个拿配置是从本地缓存拿，而我的log4j2的配置是放在apollo上，它是拿不到的，我再设置一个参数apollo.cache.file.enable为false，从远程去拉去配置，也是拉不到。

**Comment by HuiBear** [comment]
@nisiyong 我设置了这个参数，跟踪了一下代码，这个拿配置是从本地缓存拿，而我的log4j2的配置是放在apollo上，它是拿不到的，我再设置一个参数apollo.cache.file.enable为false，这样会从远程拉取，但是因为configServer应该是没有加载配置，还是拉不到

**Comment by nisiyong** [comment]
注意namespace是log4j2.xml
