### ISSUE TITLE
支持的@value后台配置更新功能，如果key删除了 没有从本地内存删掉 还是可以读到的

### ISSUE THREAD

**Issue by ruizhiLiu** [ctripcorp/apollo#2560]

**Comment by nobodyiam** [comment]
如果`@Value`表达式中没有指定默认值的话，key删除后在更新`@Value`时会失败的，所以会保留之前的值。日志中应该会出现`Auto update apollo changed value failed, ...`。

**Comment by ruizhiLiu** [comment]
> 如果`@Value`表达式中没有指定默认值的话，key删除后在更新`@Value`时会失败的，所以会保留之前的值。日志中应该会出现`Auto update apollo changed value failed, ...`。

这个value值不应该也是放在内存里面 像apolloConfig一样 可以删除的吗
