### ISSUE TITLE
apollo 回滚

### ISSUE THREAD

**Issue by 17664206081** [ctripcorp/apollo#2563]
回滚后提示成功,但是没有回滚

**Comment by jiayaoO3O** [comment]
尽量多地提供一些信息,不然就一句话很难定位问题的.

**Comment by 17664206081** [comment]
我修改了apollo 配置, 现在想改回来, 点了回滚,也发布完成了,但是配置的值却还是以前的值

**Comment by happyguy1986** [comment]
使用yaml的配置，无法回滚，操作方式，1,创建一个yml的namespace ，为了方便使用spring cloud的yaml, 发布   2.修改yaml, 将其中关于hystrix的相关项去掉 ，发布  3.点击回滚，发现有修改的提示，但是你看显示的配置文件，还是旧的

**Comment by nobodyiam** [comment]
参考下[1.6 回滚已发布配置](https://github.com/ctripcorp/apollo/wiki/Apollo%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#16-%E5%9B%9E%E6%BB%9A%E5%B7%B2%E5%8F%91%E5%B8%83%E9%85%8D%E7%BD%AE)

**Comment by happyguy1986** [comment]
好的，谢谢大神
