### ISSUE TITLE
Apollo安全漏洞问题

### ISSUE THREAD

**Issue by tanxiaosheng** [ctripcorp/apollo#2566]
apollo 1.3.5版本有没有升级spring boot的计划?
建议升级到最新，尤其是apollo configservice, adminservice ,portal三个服务，现在安全漏洞扫描发现很多问题， spring security, fasterxml jackson，jpa,  dom4j,  guava等组件版本太低，存在安全风险。 @nobodyiam

**Comment by nobodyiam** [comment]
apollo现在用的spring boot是2.0.5

其它安全风险可以给个检查方法吗？下一个大版本发布可以考虑升一下级

**Comment by tanxiaosheng** [comment]
扫描工具应该是公司安全部门出的，主要是扫描二进制文件，各类开源软件的漏洞问题。主要问题还是开源软件版本太低，存在很多已知的漏洞，推荐使用spring boot 2.1.6.RELEASE，在此基础上再做适配

**Comment by ljw930824** [comment]
@tanxiaosheng 公司采用sonar来扫描？
