### ISSUE TITLE
1.4.0版本的portal 使用apollo /admin报错，

### ISSUE THREAD

**Issue by charles-liming** [ctripcorp/apollo#2567]
1.4.0版本的portal 使用apollo /admin报错，

**Comment by jiayaoO3O** [comment]
建议多添加一点详细的信息,就一句话看得让人摸不着头脑

**Comment by charles-liming** [comment]
使用官方打好的安装包，启动portal 后，使用apollo/admin 登录 显示用户名密码错误

**Comment by jiayaoO3O** [comment]
数据库搭建好没有?数据库信息填写对了吗?meta server写对没有?eureka地址在数据库里面修改了吗?都截图发上来这才叫有用的信息啊.

**Comment by charles-liming** [comment]
错误的环境已清空，但是我的解决方案跟步骤是这样的，
1、修改了portal的env 配置，肯定没有错
2、修改了portaldb 支持的环境为 dev，fat，uat，pro
3、修改了每个configdb的eureka_url 为实际的地址，
4、启动portal 后使用默认密码登录失败，
5,、无奈使用源码打包后重新打包部署，数据库的信息不变，1.4.0的源码的configserver 的pom文件增加一个jaxb-core依赖包，因为打了几次包，启动eureka的时候，都报错缺少一个类java.lang.ClassNotFoundException：com.sun.xml.bind.v2.model.annotation.AnnotationReader(Caused by: java.lang.ClassNotFoundException: com.sun.xml.bind.v2.model.annotation.AnnotationReader)
所以，加了一个jaxb-core依赖包，重新打包启动正常，很清楚了吧
