### ISSUE TITLE
当通默认namespace获取配置与系统环境变量配置发生冲突问题

### ISSUE THREAD

**Issue by uzdz** [ctripcorp/apollo#2570]
```java
@Override
  public String getProperty(String key, String defaultValue) {
    // step 1: check system properties, i.e. -Dkey=value
    String value = System.getProperty(key);
...
```

在我的mac系统中，系统环境变量中存在user.name=uzdz的变量对。

然后我在apollo中也设置了同样名称变量key。当这种情况下，apollo会永远优先获取系统环境变量的值，而放弃apollo中设置的值，即使设置监听也不会被触发。

这样设计是为了什么？

**Comment by jiayaoO3O** [comment]
![image](https://user-images.githubusercontent.com/22891632/64322342-fae82b00-cff4-11e9-9638-647ee7e3187a.png)
System.getProperty(key)的优先级是比环境变量高的

**Comment by uzdz** [comment]
tks
