### ISSUE TITLE
本地调用FAT环境的数据,一直返回的是默认的DEV的数据

### ISSUE THREAD

**Issue by 15292137182** [ctripcorp/apollo#2572]
![image](https://user-images.githubusercontent.com/24935555/64320452-29fc9d80-cff1-11e9-9dd7-45f5e0b18f81.png)

apollo两个环境的配置
![image](https://user-images.githubusercontent.com/24935555/64320496-3ed93100-cff1-11e9-9ac7-d2ede892c29b.png)

一直返回的DEV的数据
![image](https://user-images.githubusercontent.com/24935555/64320519-4ef11080-cff1-11e9-8bb7-e31a91043bdf.png)

请问是不是我哪里配置有问题

**Comment by jiayaoO3O** [comment]
如果你同时设置了dev和fat两个环境,那一定是在某一个位置需要设置下面两个东西的,一个是dev.meta=xxx ; fat.meta=xxx ;另一个是在某一个位置里面设置了env=dev或者env=fat,找找你有没有设置上面两个东西.

**Comment by 15292137182** [comment]
找到问题了 

![image](https://user-images.githubusercontent.com/24935555/64322436-24a15200-cff5-11e9-9b1c-e2f47197a9a1.png)
这是我DEV环境的config地址


要在app.properties 文件里面修改 apollo.meta 的值指向FAT的环境就好了
![image](https://user-images.githubusercontent.com/24935555/64322398-17846300-cff5-11e9-8a8b-fc13bd52fae5.png)

**Comment by jiayaoO3O** [comment]
你这样是不对的,设置apollo.eta=xxx,只能用于一个环境,如果你需要多个环境,例如dev和fat,那就应该设置为dev.meta=xxx ; fat.meta=xxx ; 然后通过指定当前环境env=dev或者env=fat来选择环境.
你现在这样子直接用apollo.meta=xxx,那你会发现你每次换环境都要修改这个IP地址

**Comment by 15292137182** [comment]
![image](https://user-images.githubusercontent.com/24935555/64322967-20296900-cff6-11e9-91ee-770e74d98b9b.png)
我刚试了一下 这样不行啊

源码里面取得就是这个值啊 apollo.meta

![image](https://user-images.githubusercontent.com/24935555/64323032-40592800-cff6-11e9-920f-17d06933a4e5.png)

**Comment by jiayaoO3O** [comment]
![image](https://user-images.githubusercontent.com/22891632/64323238-ac3b9080-cff6-11e9-9623-9b9d164c915e.png)
![image](https://user-images.githubusercontent.com/22891632/64323247-afcf1780-cff6-11e9-9890-dc368e8f617b.png)

**Comment by 15292137182** [comment]
加了apollo-env.properties配置文件可以了.
但有个问题就是在app.properties文件里面配置了apollo.meta并指定了地址,好像apollo-env.properties里面的配置就失效了,如果在app.properties文件里面不配置了apollo.meta就报错.

![image](https://user-images.githubusercontent.com/24935555/64324447-fde51a80-cff8-11e9-920a-4670bb3e5eda.png)

**Comment by jiayaoO3O** [comment]
如果你在正确的位置创建了apollo-env.properties,并且apollo-env.properties里面写了正确的dev.meta = xxx(注意名字是dev.meta而不是apollo.meta) , 并且你在正确的位置创建了server.properties并且里面正确地写了env=dev , 那只在app.properties中写个app.id=xxx就可以让程序正常跑起来了.

**Comment by 15292137182** [comment]
现在是正常了,只是看到有警告有些不舒服 , 好了就不管了,还是得说蟹蟹
