### ISSUE TITLE
 apollo-configservice -1.4.0  版本打的包启动报错

### ISSUE THREAD

**Issue by charles-liming** [ctripcorp/apollo#2573]
报错如下：缺少
Java Code Examples for com.sun.xml.internal.bind.v2.model.annotation.AnnotationReader

处理方法：
修改 apollo-configservice  pom文件，添加如下依赖
<dependency>
    <groupId>com.sun.xml.bind</groupId>
    <artifactId>jaxb-impl</artifactId>
    <version>2.2.11</version>
</dependency>
----------------------------------以下为添加的依赖，重新打包即可
<dependency>
    <groupId>com.sun.xml.bind</groupId>
    <artifactId>jaxb-core</artifactId>
    <version>2.2.11</version>
</dependency>

**Comment by nobodyiam** [comment]
麻烦把环境信息贴一下，比如jdk版本等

**Comment by charles-liming** [comment]
![image](https://user-images.githubusercontent.com/34326414/64590019-25612c00-d3d9-11e9-979a-15b6d9a0faa1.png)
上述是打包环境
![image](https://user-images.githubusercontent.com/34326414/64590086-4aee3580-d3d9-11e9-9f10-ec423ec2ba25.png)
上述是服务运行环境

**Comment by nobodyiam** [comment]
1.8在travis ci和本地环境上都是OK的，没法重现该问题
