### ISSUE TITLE
publish_info接口缺陷

### ISSUE THREAD

**Issue by reignsr** [ctripcorp/apollo#2575]
publish_info接口调用isNamespaceNotPublished方法中，判断itemsModifiedAfterLastPublish列表为空即返回false，
```
if (CollectionUtils.isEmpty(itemsModifiedAfterLastPublish)) {	
    return false;	
}
```
此处没有考虑items变更集中仅存在删除配置项的情况。由于删除的item在发布前已经被标记为isDeleted=1，而默认查询设置了isDeleted=0，所以删除的item不会出现在itemsModifiedAfterLastPublish列表中，因此不能以itemsModifiedAfterLastPublish列表为空判定是否有待发布。
该缺陷已自行修复，github上提了个PR #2568 ，但是check failed。不知道是不是我提PR的方式不对。
![image](https://user-images.githubusercontent.com/814702/64331263-0e02f700-d005-11e9-8ecc-ef612f5e0a25.png)

**Comment by JaredTan95** [comment]
check原因可以查看： https://travis-ci.org/ctripcorp/apollo/builds/581218386?utm_source=github_status&utm_medium=notification
