### ISSUE TITLE
假定多个服务同时接入同一个apollo_Id配置，无法直观查到apolloId所对应的服务实例

### ISSUE THREAD

**Issue by yocaning** [ctripcorp/apollo#2576]
![image](https://user-images.githubusercontent.com/30205139/64332117-92a24500-d006-11e9-9896-35005c686174.png)

如上图，期待能反查到有哪些服务能够用到这个配置

**Comment by nobodyiam** [comment]
想知道一个应用中哪个interface用了哪些配置？

**Comment by yocaning** [comment]
> 想知道一个应用中哪个interface用了哪些配置？

期望是多个应用接入同一个配置，能看出那个应用使用了当前apollo配置，但是图中app_id这个参数是默认的apollo_id不是实质上的app_id不知道我这样描述是否理解清楚

**Comment by nobodyiam** [comment]
每个应用都有自己的appId，图中展示的App ID就是应用自己的appId，对不同的应用是不同的。
