### ISSUE TITLE
Apollo的配置可以通过Spring的@Value（“${key}”）注解将value的值赋值给Entity对象属性作为值？

### ISSUE THREAD

**Issue by RamboSean** [ctripcorp/apollo#2577]
Entity：
public class abc(){
          @Value("${key}")
          private String v;

          ........
}

获取value：
Abc a = new Abc();
String value = a.getV();
System.out.println();

**Comment by nobodyiam** [comment]
`@Value`是Spring负责注入的，可以测试一下

**Comment by wutan** [comment]
> Entity：
> public class abc(){
> @value("${key}")
> private String v;
> 
> ```
>       ........
> ```
> 
> }
> 
> 获取value：
> Abc a = new Abc();
> String value = a.getV();
> System.out.println();
请问 有什么办法可以实现吗

**Comment by helhades** [comment]
可以，但是总会有点延时
