### ISSUE TITLE
Apollo支持本地配置文件优先级高于Apollo配置中心配置文件吗

### ISSUE THREAD

**Issue by wutan** [ctripcorp/apollo#2579]
apollo能通过参数调整apollo配置文件优先级吗？能实现部分配置采用本地配置文件，部分配置使用Apollo配置中心文件吗

**Comment by lepdou** [comment]
这个不支持。如果优先级不统一的话，会不会导致理解成本变更，容易造成混乱？

**Comment by nobodyiam** [comment]
@wutan
