### ISSUE TITLE
多环境配置不同的时候重复的key没有合并

### ISSUE THREAD

**Issue by bg1011** [ctripcorp/apollo#2580]
目前部署的多环境集群，当开发和生成配置同步的时候，会出现重复的key，重复的key没有合并，如下：
![image](https://user-images.githubusercontent.com/16810083/64508285-a8b64b00-d30f-11e9-8020-1a232c031258.png)

**Comment by lepdou** [comment]
具体的复现步骤能否发一下

**Comment by bg1011** [comment]
步骤：
1. 已经配置了开发，测试，生产环境，并且有配置项；
2. 然后在开发环境增加配置项，并且同步到其他环境，发现其他环境会有重复的值；
3.通过编辑模式修改，然后保存无效，只能通过界面一个一个删除。

**Comment by nobodyiam** [comment]
看下管理员工具 - 系统信息，是否不同环境的admin service注册串了，或者是不同环境的admin service使用了同一个config db

**Comment by xiongrt** [comment]
> 看下管理员工具 - 系统信息，是否不同环境的admin service注册串了，或者是不同环境的admin service使用了同一个config db

目前是一个，但是配置两个环境，会导致本环境的有重复的key么？

**Comment by nobodyiam** [comment]
![image](https://user-images.githubusercontent.com/837658/65945596-e584e600-e466-11e9-99a7-5d754acbd11e.png)
