### ISSUE TITLE
在serResult方法中为什么不把namespace的最新配置一起返回而要再重新请求一遍？

### ISSUE THREAD

**Issue by JYBeYonDing** [ctripcorp/apollo#2582]
NotificationControllerV2在得知有配置发布后是如何通知到客户端的呢？

实现方式如下：

客户端会发起一个Http请求到Config Service的notifications/v2接口，也就是NotificationControllerV2，参见RemoteConfigLongPollService
NotificationControllerV2不会立即返回结果，而是通过Spring DeferredResult把请求挂起
如果在60秒内没有该客户端关心的配置发布，那么会返回Http状态码304给客户端
如果有该客户端关心的配置发布，NotificationControllerV2会调用DeferredResult的setResult方法，传入有配置变化的namespace信息，同时该请求会立即返回。客户端从返回的结果中获取到配置变化的namespace后，会立即请求Config Service获取该namespace的最新配置。
（问题：在serResult方法中为什么不把namespace的最新配置一起返回而要再重新请求一遍？）

**Comment by lepdou** [comment]
通知类的设计一般都是这样设计的，只通知变更，再拉取。我理解最主要的原因是，保持接口逻辑简单，职责清晰，不会出错。
notifications/v2 接口主要有两个职责：
1. 定时比对版本。（每次建连的时候，都会先 check 一次）
2. 监听变更
另外一个接口就是用来拉取配置。
