### ISSUE TITLE
portal登录简单认证和LDAP同时生效吗？

### ISSUE THREAD

**Issue by pengweiqhca** [ctripcorp/apollo#2583]
测试发现开启LDAP登录之后，apollo超级管理员账号就不能登录了，能否当开启LDAP后，如果找不到用户就到数据库中查找？

**Comment by nisiyong** [comment]
@pengweiqhca 可以在LDAP添加一个apollo账号，用来做管理员账号。我们这边是这么做的

**Comment by nobodyiam** [comment]
无法同时生效，可以把ldap的某个帐号设置为apollo的超级管理员

**Comment by russellgao** [comment]
@nobodyiam 请问如何把ldap的某个帐号设置为apollo的超级管理员 ？

**Comment by russellgao** [comment]
已经找到方法 : 

在 apolloportaldb.serverconfig 表中 增加一条记录：

```
-- 多个user 用 逗号分隔
INSERT INTO `apolloportaldb`.`serverconfig`(`Key`, `Value`, `Comment`) VALUES ('superAdmin', 'user1,user2,...', 'Portal超级管理员');
```
