### ISSUE TITLE
配置的Key按大小写不敏感校验重复

### ISSUE THREAD

**Issue by zhiguangliu** [ctripcorp/apollo#2584]
目前在做既有系统迁移至Apollo的工作。原来的系统中有两个key，大小写不同，无法迁移到Apollo中。
如果改动代码，还会涉及历史数据的修改，比较麻烦。
是否可以通过修改数据库的大小写敏感的选项，或者其他什么方法，能让Apollo支持“Key”和“KEY”同时配置到一个application中吗？

**Comment by lepdou** [comment]
这个主要是 mysql 默认是大小写不明感的，改一下 mysql 设置成大小写敏感应该就可以。可以试一下

**Comment by zhiguangliu** [comment]
验证了一下，需要同时修改数据库和代码。暂时放弃该方案。统一系统中的key为大写了
