### ISSUE TITLE
关于0.11.0升级1.4.0版本

### ISSUE THREAD

**Issue by 474420502** [ctripcorp/apollo#2585]
我对比一下0.11.0升级1.4.0版本, 发现少了很多表, 会不会有影响?
gif太多了, 只能发个精简版
![3](https://user-images.githubusercontent.com/9397764/64525969-af0aee00-d334-11e9-8b24-18c02ad68294.gif)

**Comment by lepdou** [comment]
apollo的版本都是向前兼容的，应该没啥问题。

**Comment by 474420502** [comment]
@lepdou  thanks, 那我就直接升1.4.0吧.
