### ISSUE TITLE
Is the configuration modification interface an atomic operation?

### ISSUE THREAD

**Issue by SmileEye** [ctripcorp/apollo#2586]
Hello, for this operation：

**http://{portal_address}/openapi/v1/envs/{env}/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/items/{key}**

At the same time call this interface, modify the same key value will cause problems?

thanks.

**Comment by lepdou** [comment]
修改配置不是原子操作，会存在并发问题。
Apollo 的方案是，通过业务加锁控制并发。开关打开后，一次发布只能由一个人修改配置，不能两个人同时修改。当然极限情况下还是不能防止并发变更。不过并发修改配置影响不是很大，因为不会影响客户端的配置，所以只要在发布的时候，做好 review 影响不是很大。

**Comment by SmileEye** [comment]
嗯嗯，谢谢您的回复！

**Comment by SmileEye** [comment]
> 修改配置不是原子操作，会存在并发问题。
> Apollo 的方案是，通过业务加锁控制并发。开关打开后，一次发布只能由一个人修改配置，不能两个人同时修改。当然极限情况下还是不能防止并发变更。不过并发修改配置影响不是很大，因为不会影响客户端的配置，所以只要在发布的时候，做好 review 影响不是很大。

嗯嗯，谢谢您的回复！

**Comment by SmileEye** [comment]
> 修改配置不是原子操作，会存在并发问题。
> Apollo 的方案是，通过业务加锁控制并发。开关打开后，一次发布只能由一个人修改配置，不能两个人同时修改。当然极限情况下还是不能防止并发变更。不过并发修改配置影响不是很大，因为不会影响客户端的配置，所以只要在发布的时候，做好 review 影响不是很大。

您好，再请教一下，加锁的开关是在哪里设置的? 没有在接口入参或者apollo平台上找到类似的设置。

**Comment by SmileEye** [comment]
> 修改配置不是原子操作，会存在并发问题。
> Apollo 的方案是，通过业务加锁控制并发。开关打开后，一次发布只能由一个人修改配置，不能两个人同时修改。当然极限情况下还是不能防止并发变更。不过并发修改配置影响不是很大，因为不会影响客户端的配置，所以只要在发布的时候，做好 review 影响不是很大。

您好，再请教个问题，没有在接口入参或者apollo平台上找到加锁类似的设置，是不是默认操作已经加锁了?

**Comment by SmileEye** [comment]
> 修改配置不是原子操作，会存在并发问题。
> Apollo 的方案是，通过业务加锁控制并发。开关打开后，一次发布只能由一个人修改配置，不能两个人同时修改。当然极限情况下还是不能防止并发变更。不过并发修改配置影响不是很大，因为不会影响客户端的配置，所以只要在发布的时候，做好 review 影响不是很大。

您好，再请教个问题，没有在接口入参或者apollo平台上找到加锁开关类似的设置，是不是默认操作已经加锁了?
