### ISSUE TITLE
读取yml配置失败

### ISSUE THREAD

**Issue by Diyuzhou** [ctripcorp/apollo#2588]
Controller
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.beans.factory.annotation.Value;

@RequestMapping("/order")
@RestController
public class OrderController {
    @Value("${test.one}")
    private String testOne;
    //@Configuration
    @RequestMapping("/info")
    public String orderInfo() {
       return "order info date : " + "&&&&"+this.testOne;
    }
}

以jvm参数的形式启动-Denv=DEV -Dapp.id=test -Dapollo.meta=http://ip:8080 -Dapollo.bootstrap.enabled=true -Dapollo.bootstrap.namespaces=application.yml -DcacheDir=./config

发现本地cash目录里竟然是test+default+application.yml.properties

**Comment by Diyuzhou** [comment]
请问读取yml配置是不是需要其他的配置

**Comment by Diyuzhou** [comment]
另外尝试使用1.4.0直接使用项目启动加载的方式，将参数写入本地项目的bootstrap.yml，指定namespace，结果连接apollo服务器时一直报读取application，我没有指定，这是怎么会是

**Comment by Diyuzhou** [comment]
读取yml配置失败的问题在读取properties时不存在

**Comment by nobodyiam** [comment]
缓存文件是以Properties格式存储的，这个没问题的。

**Comment by maodunWorld** [comment]
我也同样遇到这个问题，在发布的YML的namespace无法读取到，但是发布properties的Namespace可以正常读取，我用的quickstart的版本。

**Comment by maodunWorld** [comment]
访问yml namespace需要添加后缀名yml,搞定了
