### ISSUE TITLE
0.9.0版本-不同app应用在portal修改配置导致修改混乱

### ISSUE THREAD

**Issue by cjy2012** [ctripcorp/apollo#2592]
这种情况非必现，偶现，无法正常复现，具体如下： 应用A修改配置item1 = 123456，使得应用B的某个key：Item = 123456，也就是应用A做了修改，导致应用B中某一个key的value为应用A的修改值123456，但是此用户其实没有应用B的修改权限

**Comment by nobodyiam** [comment]
看代码似乎不应该出现这个情况，看下对应的commit表记录？

**Comment by jiyunchenPKU** [comment]
查看了下commit表中没有记录，但是数据的确被修改了，是其中一个namespace中的配置被修改了

**Comment by nobodyiam** [comment]
如果是程序修改的一定会有commit记录的
