### ISSUE TITLE
window7下启动apollo报java_home not found

### ISSUE THREAD

**Issue by chinghonsun** [ctripcorp/apollo#2593]
![Feige图片20190912150920](https://user-images.githubusercontent.com/4075785/64761711-52474780-d56f-11e9-9fb6-72756740d60d.png)

**Comment by nobodyiam** [comment]
1. 安装git bash
2. 设置JAVA_HOME环境变量

**Comment by chinghonsun** [comment]
这个就是git bash啊。环境变量也设置了的

**Comment by nobodyiam** [comment]
安装一下最新版本的git bash吧，应该有cygpath这个命令的
