### ISSUE TITLE
有一次发布历史，点击“回滚”后显示“没有可以回滚的发布历史”

### ISSUE THREAD

**Issue by nisiyong** [ctripcorp/apollo#2595]
## 问题

我的配置已经发布过一次，在修改时不小心删了很多key，修改后保存，没有点击“发布”所以不影响。但是我想恢复成上一次发布配置，却无法恢复。
![image](https://user-images.githubusercontent.com/8198862/64902409-48d9ee80-d6d9-11e9-9581-1ac01dc744b8.png)
![image](https://user-images.githubusercontent.com/8198862/64902414-7c1c7d80-d6d9-11e9-92de-989da001cc3b.png)

## 结果

有一次发布历史，点击“回滚”后显示“没有可以回滚的发布历史”

## 期望

在已有修改的情况下，也能回滚到指定的历史版本，即放弃当前的修改。
类似与Git放弃工作区和暂存区的变更，直接reset到某个commit。

考虑到当前“回滚”的功能实现不太一样，也可以考虑添加一个“重置”的功能（放弃未发布的修改项）

**Comment by nobodyiam** [comment]
#2952 已经增加撤销配置修改功能
