### ISSUE TITLE
同服务不同namespace空间中有相同key但是值不能隔离

### ISSUE THREAD

**Issue by geelian** [ctripcorp/apollo#2597]
@Configuration
@EnableApolloConfig
public class A{
    @Value("test:a")
    Integer test;
}

@Configuration
@EnableApolloConfig("B")
public class B{
    @Value("test:a")
    Integer test;
}

在配置中心 A中的test和 B的test值不同  但使用时 test是相同的  test会和其中一个命名空间的值相同 client-1.4.0 想请教一下这个是由于spring的影响  2次覆盖了吗 ？

**Comment by nobodyiam** [comment]
是的，这个是Spring的覆盖逻辑，如果希望独立使用不同namespace的相同key，可以注入`@ApolloConfig`通过Config对象使用。
