### ISSUE TITLE
服务的管理员权限扩展

### ISSUE THREAD

**Issue by junozhou** [ctripcorp/apollo#2601]
目前服务的管理员，可以自己给自己开通编辑、发布的权限，这样不能很好的控制住权限。
希望提供只能编辑的管理员
因为如果不是管理员，大家没办法看到namespace，而手动给大家开通编辑权限太麻烦了，而且费时。提供一个API也是很好的，感谢🙏

**Comment by nobodyiam** [comment]
一般项目的管理员本身也就是项目的成员，比如主管、项目负责人之类的，应该不会有纯的管理员角色，所以想问下`只能编辑的管理员`是一个什么样的场景？

API的话，可以在open api中增加，这块逻辑比较简单，欢迎PR~
