### ISSUE TITLE
请考虑支持应用的默认命名空间和公共命名空间为其他可选的配置格式

### ISSUE THREAD

**Issue by aioloswong** [ctripcorp/apollo#2602]
asp.net core 程序默认使用json格式的配置文件作为程序默认配置格式，所以在创建应用的时候可否增加一个下拉选择项，用于选择应用默认命名空间的配置格式？

  另外对于公共命名空间也是同样的道理，希望配置格式也可以改成可配置的。这2个改动相对来说都是比较小的。希望能支持这2个功能，感谢！

**Comment by nobodyiam** [comment]
目前私有的namespace是可以选择格式的，可以考虑`创建应用的时候可否增加一个下拉选择项，用于选择应用默认命名空间的配置格式`。

公共namespace这块目前还不支持非properties格式，得仔细考虑一下是否可以开放其它格式。
