### ISSUE TITLE
关于Portal通过负载均衡后自动跳转协议问题

### ISSUE THREAD

**Issue by xfrogcn** [ctripcorp/apollo#2603]
portal部署在后端，通过负载均衡公开到外网，在负载均衡上配置了HTTPS，外部通过https访问。

问题：
通过https访问后，portal自动跳转到登陆页面时，协议不正确，跳转的是http协议，所以无法访问。

（负责均衡通过x-forwarded-proto头指定了外部访问协议为https）

**Comment by nobodyiam** [comment]
参考一下 #1778
