### ISSUE TITLE
namespace支持的文件的不支持yml

### ISSUE THREAD

**Issue by ordercard** [ctripcorp/apollo#2608]
为什么设置公共的namespace的时候不支持yml格式的呢？我们项目中也有公共的yml，但是我看到的支持propertys格式的

**Comment by JaredTan95** [comment]
公共namespace设置yml格式的话，可能对namespace关联覆盖单个值不太友好。

**Comment by ordercard** [comment]
不会吧，就按照正常的spring property source覆盖不就完了吗？ 我记得 yml最终会变成一个 key-value的集合，我没觉得不太友好，我们现在用的spring-cloud-config yml配置中 相同的key-value就是后者文件覆盖前面的
