### ISSUE TITLE
本机启动 nobodyiam/apollo-quick-start镜像 设置-Deureka.instance.homePageUrl=http://127.0.0.1:8080管理后台报错

### ISSUE THREAD

**Issue by ordercard** [ctripcorp/apollo#2609]
我修改了文档中提供的一个快速启动镜像 因为我是想本地启动docker容器后，然后通过idea直接连接docker中的配置中心，发现不行，最终通过 修改了 nobodyiam/apollo-quick-start镜像中的 demo.sh脚本 增加了：
-Deureka.instance.homePageUrl=http://127.0.0.1:8080 的java一个环境变量
但是这个时候虽然idea能联通了。但是在管理平台上只要创建新的项目就提示 
![image](https://user-images.githubusercontent.com/22793054/65375622-4fb0c480-dcca-11e9-812d-f50da75b02ce.png)
而且根据点击补缺环境还是提示这个

**Comment by nobodyiam** [comment]
看一下 管理员工具 - 系统信息 页面以及portal的日志

**Comment by ordercard** [comment]
算了，我把我的应用打包放到docker里面去了，估计是地址不应该填写本机地址导致的
