### ISSUE TITLE
yaml配置的array取值不方便

### ISSUE THREAD

**Issue by gangly** [ctripcorp/apollo#2610]
在apollo上redis.yaml配置了:
`
password: abcd1234
hosts: 
- redis-dev01.dd.com:7000
- redis-dev01.dd.com:7001
`
发现客户端取值时必须用
getProperty("host[0]", "")才能取到redis-dev01.dd.com:7000

**Comment by nobodyiam** [comment]
建议搭配`@ConfigurationProperties`使用，参考 com.ctrip.framework.apollo.demo.spring.springBootDemo.config.SampleRedisConfig
