### ISSUE TITLE
如何关联非 default 集群下面的公共 namespace

### ISSUE THREAD

**Issue by Joe798** [ctripcorp/apollo#2612]
你好，请教一个问题。
公共的 namespace 放在某个 app 的 cluster 下，
例如 appId = public-config，cluster = A ，namespace = sofeware01 。
 
另外一个 app 的 cluster 下，
例如 appId = 001-config，cluster = A-001 ，创建 namespace 关联  sofeware01 。
结果，关联的却是 public-config 的 default 集群下面的 sofeware01 。

如何操作才能使 A-001 集群下面的 sofeware01 关联到 A 集群下面的 sofeware01 ？

**Comment by Joe798** [comment]
设想用 com.ctrip.framework.apollo.common.dto.ClusterDTO.parentClusterId 解决这个需求。
因此，创建集群时需要关联父集群。

**Comment by nisiyong** [comment]
如果应用指定了cluster，那么获取namespace的时候，无论是自己私有的还是公共的。都会优先获取同cluster的namespace，如果获取不到才会用default的namespace。
所以你要解决这个问题，可以让应用的cluster名称与公共配置的namespace所在的cluster名字保持一致。

**Comment by Joe798** [comment]
目前的代码实现是你所说的这个规则。
要实现所期望的功能，可以在获取default的同名namespace前加一个规则：获取parentCluster的同名namespace 。

代码实践中。

**Comment by nobodyiam** [comment]
集群的parentClusterId是用于灰度发布的，用在namespace关联上不太合适。

namespace如果需要关联特定集群的公共namespace建议还是采用默认规则 - 让应用的cluster名称与公共配置的namespace所在的cluster名字保持一致。
