### ISSUE TITLE
读取yml格式的私有文件为null

### ISSUE THREAD

**Issue by ordercard** [ctripcorp/apollo#2613]
在client读取yml格式的文件的时候client控制台未报错，但是代码中读取不到值，我试的properties格式的文件是可以的。
我使用的是nobodyiam/apollo-quick-start快速启动镜像
错误如下
![image](https://user-images.githubusercontent.com/22793054/65483545-32007c80-decf-11e9-8524-661966a06608.png)
![image](https://user-images.githubusercontent.com/22793054/65483550-33ca4000-decf-11e9-8d16-e05c6500b91d.png)
![image](https://user-images.githubusercontent.com/22793054/65483553-34fb6d00-decf-11e9-9925-4c62d50ddc20.png)

**Comment by JaredTan95** [comment]
可以提供一个最小代码示例吗？




| |
谭建
邮箱：tanjian20150101@163.com
|

签名由 网易邮箱大师 定制

在2019年09月24日 13:30，夏至未至 写道：

在client读取yml格式的文件的时候client控制台未报错，但是代码中读取不到值，我试的properties格式的文件是可以的。
错误如下

**Comment by ordercard** [comment]
最终检查出来是我客户端版本1.1过低的问题用了1.4的就好了，我本地在environment打了断点，yml格式的文件子低版本上面只有一个key为content ,而value的值为文件的内容，修正下版本就好了。打扰了，sorry

**Comment by tonatywsun** [comment]
> 最终检查出来是我客户端版本1.1过低的问题用了1.4的就好了，我本地在环境打了断点，yml格式的文件子低版本上面只有一个键为内容，而值的变量文件的内容，修正下版本就好了。打扰了，抱歉

我也是这个问题啊，我***，搞了半天
