### ISSUE TITLE
同个应用的不同实例存在部分配置值就是要求不同的，此时Apollo应该怎么管理

### ISSUE THREAD

**Issue by sandy0823** [ctripcorp/apollo#2615]
服务器A\B均安装了 app 应用，A、B两个实例配置部分是相同的（业务参数），部分是不同的（服务器相关参数：使用内存大小、使用端口）；
请问：
  是要在Apollo 上 app 应用下建立两个集群分别管理A、B实例配置？还是通过一个集群来处理这两个有差异性的配置？

**Comment by jiayaoO3O** [comment]
在apollo上创建两个app,然后将公共部分从Aapp继承到Bapp,不同的部分各写各的

**Comment by nobodyiam** [comment]
如果配置值长期不同，可以用两个集群来区分，相同配置放在公共namespace下。如果配置值短期不同，则可以用灰度发布来实现。
