### ISSUE TITLE
集群状态下是否支持切换服务发现框架

### ISSUE THREAD

**Issue by xqxyxchy** [ctripcorp/apollo#2618]
原生只支持eureka，但是我们客户使用的服务发现框架是consul，不知道能不能提供相关的支持方式。
提供切换或者提供一种自己扩展的方案。

**Comment by nobodyiam** [comment]
可以参照`com.ctrip.framework.apollo.configservice.ConfigServerEurekaServerConfigure`和`com.ctrip.framework.apollo.configservice.ConfigServerEurekaClientConfigure`加个配置来切换

**Comment by xqxyxchy** [comment]
好的，谢谢。
