### ISSUE TITLE
存储方式能否支持其他存储手段

### ISSUE THREAD

**Issue by xqxyxchy** [ctripcorp/apollo#2619]
我们客户使用的都是oracle的数据库，他们期望能将存储统一到oracle中或者elasticsearch中。
不知道是否有相应的扩展方式可以实现这样的需求。

**Comment by nobodyiam** [comment]
可以参考下

![image](https://user-images.githubusercontent.com/837658/65946150-174a7c80-e468-11e9-823b-689eb6fd7ce7.png)

https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#12-mysql
