### ISSUE TITLE
多数据中心部署apollo，不同的数据中心有着各自的configDB，是需要db同步还是apollo已经做了同步

### ISSUE THREAD

**Issue by ordercard** [ctripcorp/apollo#2620]
主要是我们公司 在全球一共有7个数据中心，如果配置configDB只放在中国的话，你也知道的网络不稳定，而且我们又不是专线，所以我才想到是 每个数据中心都分别有 config-service, admin-service，同时配置了对应的configDB数据库。
  问题如下：
  中国机房  中国产线集群 部署了 config-service, admin-service，同时配置了单独的configDB数据库。
美国机房 美国产线集群  部署了config-service, admin-service, 同时也部署了单独的configDB数据库.
portal部署一个。这个时候我把中国区的配置通过点击同步配置按钮到美国区或者德国区的话，是apollo代码层面上帮我们把需要同步的数据同步到了美国产线集群的congDB数据库里面吗？
还是需要单独的配置？

**Comment by nobodyiam** [comment]
有两种方式：

1. 中国区和美国区作为同一个环境使用，configdb部署一套，然后做db层面的数据同步，可以参考 #1294 
2. 中国区和美国区作为两个环境使用，configdb部署两套，不需要做db层面的数据同步
