### ISSUE TITLE
数据库和Redis修改配置不生效

### ISSUE THREAD

**Issue by sunnyfrank** [ctripcorp/apollo#2621]
数据库和Redis的配置更新了，但是没有生效，environment里的配置信息也更新了，就是不生效

**Comment by nobodyiam** [comment]
参考下[dynamic-datasource](https://github.com/ctripcorp/apollo-use-cases/tree/master/dynamic-datasource)

**Comment by wzce** [comment]
> 参考下[dynamic-datasource](https://github.com/ctripcorp/apollo-use-cases/tree/master/dynamic-datasource)

我也碰到类似的问题，若使用默认的命名空间application则正常，自定义私有的namespace，使用的例子也是dynamic-datasource，在dynamic-datasource里定义使用指定的namespace（非默认的application）的配置，配置不能热更，冷启动是正常的；此外，发现一个现象，使用文本（text）形式进行配置批量更新时，发布后也不能进行热更，冷启动配置正常。

**Comment by sunnyfrank** [comment]
redis的不会写啊 ，是不是只要涉及到连接池的配置，都无法实时刷新
