### ISSUE TITLE
Apollo 1.2.0  读取不了日志配置

### ISSUE THREAD

**Issue by LiuQiangWangWanHong** [ctripcorp/apollo#2626]
在application.yml 文件配置
apollo:
  bootstrap:
    enabled: true
    namespaces: application
    eagerLoad:
      enabled: true

能访问其他属性 就是日志部分配置不能访问

**Comment by nobodyiam** [comment]
可以支持日志配置放在Apollo管理（如logging.level.root=info或logback-spring.xml中的参数），更多信息可以参考 #1614

**Comment by LiuQiangWangWanHong** [comment]
可以了  日志配置文件没有打包到  。。。。。
