### ISSUE TITLE
apollo-client & apollo-openapi使用场景，集成方式（读、写、监听配置变化）

### ISSUE THREAD

**Issue by dongzl** [ctripcorp/apollo#2635]
Apollo team：
你们好，最近我正在将 Apollo 集成到 [Apache ShardingSphere](https://github.com/apache/incubator-shardingsphere) 项目中，作为配置中心的一种实现，ShardingSphere 需要使用配置中心的如下功能：

1. 根据 key 读取 value 值；
2. 根据 key 更新 value 值；
3. 监听到某个 key 配置信息的变更。

我在阅读 Apollo 帮助文档中了解到可以通过 **apollo-client** & **apollo-openapi** 两种方式进行集成，但是有些疑问需要确认一下：

**apollo-client**：可以满足 1、3 需求；但无法满足2，无法直接根据 key 进行数据更新；
**apollo-openapi**：可以满足1、2需求；但无法满足3，无法监听到某个 key 配置信息的变更。

可能需要将两种方式都集成到 ShardingSphere 才能满足所有需要。

请问一下，如果要满足上述1、2、3的需要，集成两种 API 是最好的实现吗？
或者有其他方式能同时满足该需求吗？谢谢~

**Comment by nobodyiam** [comment]
apollo-client和apollo-openapi分别服务于两种不同的场景，所以它们的功能设计层面是不同的。

1. apollo-client
服务对象是使用配置的应用，比如开发人员在控制台修改配置，应用能实时监听到配置的变化并获取到值。在功能层面就对应了1和3。

2. apollo-openapi
服务对象是第三方的配置管理系统，比如dba的运维系统可以通过apollo-openapi写入数据库连接的配置，然后应用能实时监听到数据库连接配置的变化从而可以做相应切换。这个场景可以类比于开发人员直接在控制台修改配置的场景，所以在功能层面是对应了1和2。

ShardingSphere我理解应该是存在两部分的组件，管控台使用apollo-openapi修改配置，接入端(sharding-jdbc)使用apollo-client获取配置？

**Comment by dongzl** [comment]
@nobodyiam ,您好，感谢您的解答。我理解了两套API对应了不同的使用场景。

对于 ShardingSphere 目前主要发布的两个产品，**Sharding-JDBC** 和 **Sharding-Proxy**，ShardingSphere 有关注册中心的功能也在进行比较大重构 
[ConfigCenter should replace RegistryCenter in some places.](https://github.com/apache/incubator-shardingsphere/issues/3095)，
我比较熟悉**Sharding-Proxy**，我理解Sharding-Proxy在启动初始化的时候也会将一些本地配置文件配置信息同步到配置中心，同时在内部也会进行配置读取，监听配置变化等操作，
[org.apache.shardingsphere.orchestration.config.api.ConfigCenter](https://github.com/apache/incubator-shardingsphere/blob/dev/sharding-orchestration/sharding-orchestration-config/sharding-orchestration-config-api/src/main/java/org/apache/shardingsphere/orchestration/config/api/ConfigCenter.java)

目前看接口的重构还没有将配置信息的读写操作进行分开定义，如果按照目前 Apollo 的设计理念，要集成到 ShardingSphere 是不是只能将两套API一起集成，或者有别的更好的实现方式吗？

Thanks.

**Comment by nobodyiam** [comment]
> 我比较熟悉Sharding-Proxy，我理解Sharding-Proxy在启动初始化的时候也会将一些本地配置文件配置信息同步到配置中心，同时在内部也会进行配置读取，监听配置变化等操作；配置初始化后也可能会在控制台进行配置修改，Sharding-Proxy 需要监听到配置变化

所以在这个场景Sharding-Proxy承担了两个角色：

**1. 配置修改者**
在启动时把本地配置文件同步到配置中心，这里的操作对象是编辑态的配置。

Apollo对于配置修改是强管控的，需要有namespace的编辑、发布权限，所以要使用apollo-openapi并且事先申请有权限的token。

**2. 配置读取者**
在运行时读取配置、监听配置变化，这里读取的对象是发布态的配置。apollo对发布态的配置读取和监听是不需要申请token的。

由于两者操作的对象不同，所以apollo-openapi对接的后端是Portal，apollo-client对接的后端是Config Service，在架构上两者也有很大不同（比如Config Service的可用性要求比Portal高很多），更多信息可以参考[Apollo配置中心设计](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1)。

另外，由于应用配置对程序的正确运行非常重要，稍有差错就可能导致程序出错，所以一般而言，不太建议应用程序同时做自身配置的修改者和读取者，因为程序直接修改生效的话，缺少了一个review配置差异的过程（在Apollo中对应着配置的修改和发布两个步骤）。

综上，建议在逻辑上把Sharding-Proxy分为两个角色，配置修改的部分接入apollo-openapi，配置读取、监听的部分接入apollo-client，两者在逻辑上应该是独立的。

**Comment by dongzl** [comment]
@nobodyiam 收到，感谢您的建议，我再调整一下集成的思路和方式~
