### ISSUE TITLE
问个无法正常的问题.

### ISSUE THREAD

**Issue by 474420502** [ctripcorp/apollo#2643]
mysql有个中间件5.5的, 但是后端是5.7版本. 这样使用会不会有问题.
其次曾经连接正常升级到1.4.0后. 操作两次后. 再也无法正常.
这样的数据库使用会有影响吗?

**Comment by nobodyiam** [comment]
具体有啥错误？

**Comment by 474420502** [comment]
@nobodyiam  等下吧. 两个不同版本(configservice adminservice)的连接同一个mysql的数据db有什么问题吗.  我的问题就是我公司使用的人完全不按官方要求去使用, 乱改. 我现在需要恢复, 和 升级. 太多问题了. 等我整理一下再问.

**Comment by 474420502** [comment]
@nobodyiam  sorry, 问题太复杂. 太多, 环境修改和修改原版内容. 我自己解决算了. 麻烦了.
