### ISSUE TITLE
请教portal配置反向代理的问题

### ISSUE THREAD

**Issue by JunminZhang** [ctripcorp/apollo#2649]
在nginx配置location，转发的时候为什么系统会返回包含location的路径404呢，是nginx配置错误了吗
![图片](https://user-images.githubusercontent.com/34052378/66635872-a0209f80-ec42-11e9-9801-51bbf411478f.png)

![图片](https://user-images.githubusercontent.com/34052378/66635952-c8a89980-ec42-11e9-9bc6-1719d8fb4813.png)

**Comment by nobodyiam** [comment]
转发到后端的路径应该是`/apps`，不是`/configuration/apps`

**Comment by JunminZhang** [comment]
> 
> 
> 转发到后端的路径应该是`/apps`，不是`/configuration/apps`

嗯应该是/apps，但是我nginx配置的是不带/configuration的转发过去之后还是带上了/configuration
