### ISSUE TITLE
关于env=Local的情况，提个小建议，或者说是小需求

### ISSUE THREAD

**Issue by helhades** [ctripcorp/apollo#2650]
env=local时 可以使用本地配置文件获取配置 但是配置文件位置必须是apollo.cache的路径下的config-cache目录 ，而且文件名字还得是appid+clusterid+namespace 这样的硬编码规则有点不灵活

希望可以通过绝对或者相对路径直接指定任何文件作为local模式下的配置文件 可以多个文件用逗号一类的分隔。例如：
-Dapollo.config.files="c:\config\application.properties,d:\config\log.properties"

说下我提出这个问题的背景，现在开发的系统分dev，uat，prod三个环境，都是3个配置文件，现在后两个环境迁移apollo，dev属于local模式 ，但是已有配置文件已经存在，我希望能够不去改动现有dev下的配置文件的名字和路径就可以无缝迁移到apollo。这就算是我的需求吧。谢谢

**Comment by nobodyiam** [comment]
目前的设计初衷是保持local模式和远端模式的模型一致，只对访问方式做了抽象，从而可以实现最大程度的代码复用以及可维护性。

所以建议还是保持这个规则，本地做一次初始化把文件放到对应的位置即可。

**Comment by helhades** [comment]
@nobodyiam 你说的这模型保持一致，我发现个问题，如果不配置cache属性的话，默认的路径和远程同步配置保存到本地的路径是一样的，也就是说，如果我先用local模式放一些文件到默认路径下，这时如果切换为非local（比如uat）环境，远程的配置就会覆盖自己在本地配置好的文件，不算什么大问题吧，也是个坑
