### ISSUE TITLE
Apollo Portal登录能否加上验证码以防止暴力破解？

### ISSUE THREAD

**Issue by tanxiaosheng** [ctripcorp/apollo#2651]
现在使用Apollo，发现很多问题，首先就是Apollo的portal登录没有提供图形验证码的功能，以防止暴力破解，不符合公司的安全规范， 后续版本能够加上这个功能？
另外，还需要考虑SQL注入，权限管理，是否存在越权的安全问题，实际生产环境中使用，还是需要考虑很多安全问题，尤其是Portal存在用户操作，要求比较严格。 @nobodyiam

**Comment by nobodyiam** [comment]
目前默认提供的spring security登录页面确实没有验证码功能，后续可以尝试加一下。不过还是建议接入公司自己的SSO系统，一方面可以提升用户使用体验，一方面也能统一做安全策略。

你提到的其它问题如SQL注入、权限管理等问题应该是不存在的，如果有发现，欢迎提交issue和PR。
