### ISSUE TITLE
Appollo初始化时，使用的引用项目的app.id

### ISSUE THREAD

**Issue by jiangxiaoqiang** [ctripcorp/apollo#2659]
使用的客户端版本：1.2.0

在A服务中，引用B服务后，A服务启动时获取到的app.id是B服务的app.id，经过跟踪是从ApolloApplicationContextInitializer类的fillSystemPropertyFromEnvironment方法中初始化了B服务的app.id变量，在A服务中从System Properties能够取得app id（实际是B服务的app id）就直接忽略了本地服务（A服务）的app id配置：

```
private void fillSystemPropertyFromEnvironment(ConfigurableEnvironment environment, String propertyName) {
    if (System.getProperty(propertyName) != null) {
      return;
    }

    String propertyValue = environment.getProperty(propertyName);

    if (Strings.isNullOrEmpty(propertyValue)) {
      return;
    }

    System.setProperty(propertyName, propertyValue);
  }
```

不知何种情况下会导致此问题。B服务的app.id在application.properties中定义。

**Comment by jiayaoO3O** [comment]
根据说明文档,不同的配置app.id方式是有优先级的,你可以去看看部署指南是不是优先级因素没有考虑

**Comment by nobodyiam** [comment]
B服务发布的jar包中不应该包含app.id，并且应该使用公共namespace
