### ISSUE TITLE
请问下配置中心有没有英文版本？

### ISSUE THREAD

**Issue by mimi-glomax** [ctripcorp/apollo#2665]
请问下有没有英文版本供国外同事使用？

**Comment by nobodyiam** [comment]
http://106.12.25.204:8070/

最新版本已经支持英文了，可以体验一下，正式版本预计本月发布。

![image](https://user-images.githubusercontent.com/837658/67056855-773b6580-f180-11e9-9f80-67c33edc8524.png)

**Comment by mimi-glomax** [comment]
赞
