### ISSUE TITLE
容器化环境中注册中心的必要性

### ISSUE THREAD

**Issue by kentchenjh** [ctripcorp/apollo#2666]
在k8s环境中的apollo，感觉eureka没有存在的必要，本身k8s已经有服务发现功能了，并且比eureka更加完善(比如服务下线被剔除的速度)。
是否考虑做一个注册中心开关，或者提供一种应用可以直接填地址访问的方式。

**Comment by nobodyiam** [comment]
eureka现在并没有对外暴露，只是作为config service/admin service的一个内部实现，所以技术上来讲确实是可以通过一些配置来实现接入k8s的service体系，可以看下apollo-configservice中meta service的实现，看看是否有比较好的方式可以实现这一目的。

**Comment by kentchenjh** [comment]
目前确实对meta service做了一点改造，实现了走k8s service。不过因为meta service的存在，在组件拿地址前始终会多调用一次。不过这种改造是应该是代价较小的一种方式。
