### ISSUE TITLE
配置项的值有长度限制吗？

### ISSUE THREAD

**Issue by Jinnrry** [ctripcorp/apollo#2668]
如果我把项目用户的权限配置以JSON格式存在apollo中合适吗？内部项目，只有几百个用户，经常会有这种类似的需求，存db中太麻烦了，又不方便改，不知道存apollo中以后用户多了会不会出问题

**Comment by wkcaeser** [comment]
有限制，但是可以动态修改的。

**Comment by sc750531323** [comment]
value有多长的限制，在哪里修改的

**Comment by sc750531323** [comment]
see link: https://github.com/ctripcorp/apollo/issues/2025
