### ISSUE TITLE
Apollo-portal问题

### ISSUE THREAD

**Issue by HandsomSheng** [ctripcorp/apollo#2672]
portal只能起一个实例吗？现在我们有六个实例，每台机器都起了一个portal，然后用一个域名执行指向这些机器的IP，每次指向的IP都是随机的，但是当用域名访问登录的时候，会始终重定向到登录页，请问这种情况如何解决

**Comment by nobodyiam** [comment]
可以配置一下session sticky

**Comment by born198x** [comment]
@nobodyiam session sticky 在哪配 怎么配呢？

**Comment by nobodyiam** [comment]
@born198x 在负载均衡器上配置
