### ISSUE TITLE
请问支持https的接口吗

### ISSUE THREAD

**Issue by qiluge** [ctripcorp/apollo#2681]
目前看是不支持https的接口访问的，数据都是http的rest接口拿到的，请问要换成https的方式该改哪些配置？

**Comment by nobodyiam** [comment]
参考下面的文档试试：

https://cloud.spring.io/spring-cloud-static/spring-cloud.html#_registering_a_secure_application

**Comment by qiluge** [comment]
请问有没有限制读取config、修改config的安全策略可以配。比如读取config时，服务端和客户端相互鉴别身份。

**Comment by nobodyiam** [comment]
see #2099
