### ISSUE TITLE
在虚拟机docker搭建的docker-quick-start，主机拿到的却是docker的ip

### ISSUE THREAD

**Issue by zhongpeile** [ctripcorp/apollo#2682]
在虚拟机docker搭建的docker-quick-start，主机拿到的不是虚拟机的ip地址的服务，而是是docker的ip地址服务，虚拟机的ip是172.16.186.X，而docker-quick-start的docker服务的ip是172.18.0.4，eureka返回的却是docker-quick-start的docker服务的ip的地址，导致无法获取服务，请问怎么解决？

**Comment by nobodyiam** [comment]
参考下[网络策略](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#14%E7%BD%91%E7%BB%9C%E7%AD%96%E7%95%A5)

**Comment by SparklerDeng** [comment]
> 参考下[网络策略](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#14%E7%BD%91%E7%BB%9C%E7%AD%96%E7%95%A5)

网络策略里说可以加EUREKA_INSTANCE_IP_ADDRESS等参数来解决，试过无效。怀疑nobodyiam/apollo-quick-start里的image没有接收这些参数。能不能重新推新的image，把相关参数改成可传递
谢谢

**Comment by nobodyiam** [comment]
@SparklerDeng EUREKA_INSTANCE_IP_ADDRESS这个是程序中读的，容器启动时OS ENV里面有应该就可以的

**Comment by huangsunting** [comment]
SpringBoot下可以试一下。

/**
 * 用于解决本地无法连接configService的问题
 * https://www.apolloconfig.com/#/zh/client/java-sdk-user-guide?id=_1222-跳过apollo-meta-server服务发现
 */
@Order(-1)
public class ApolloMetaConfigInitializer implements ApplicationContextInitializer<ConfigurableApplicationContext> {

    @Override
    public void initialize(ConfigurableApplicationContext applicationContext) {
        ConfigurableEnvironment environment = applicationContext.getEnvironment();
        String[] activeProfiles = environment.getActiveProfiles();
        if (isEnvNotConfigured(activeProfiles) || isDev(activeProfiles)) {
            // 不走服务发现逻辑，直接指定configService地址
            String apolloMeta = environment.getProperty("apollo.meta", "http://localhost:8080");
            System.setProperty("apollo.config-service", apolloMeta);
        }
    }

    private boolean isDev(String[] activeProfiles) {
        String activeProfile = activeProfiles[0];
        return "dev".equals(activeProfile);
    }

    private boolean isEnvNotConfigured(String[] activeProfiles) {
        return activeProfiles.length == 0;
    }
}

@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication app = new SpringApplication(Application.class);
        app.addInitializers(new ApolloMetaConfigInitializer());
        app.run(args);
    }

}
