### ISSUE TITLE
关于apollo支持yml的几个问题

### ISSUE THREAD

**Issue by sg6303** [ctripcorp/apollo#2685]
1.yml文件如何友好的添加到apollo

2.yml支持覆盖，比如有application.yml和application-dev.yml ，那么 后者里面的key与前者一样的时候，会覆盖。而在apollo如何表现

3.如果在项目中，有dev、fat、prod三种环境。三种环境都logback.yml的命名空间，如果将fat中的logback.yml命名空间单独删除。会一直报错，说要补充命名空间。所以只能在 管理员工具那边 统一删除。这样无法做到单个删除。其实目的是想单个环境拥有某个命名空间，而其他环境没有

**Comment by nobodyiam** [comment]
1. 创建yml格式的private namespace即可

2. 这个是spring的行为，注入namespace时，order小的优先级高，order一样的话，先注入的优先级高

3. private namespace目前是需要所有环境都有的

**Comment by sg6303** [comment]
1. 公共的namespace好像不支持 yml格式是吗？

**Comment by nobodyiam** [comment]
目前公共的namespace只支持properties格式

**Comment by chg87599671** [comment]
@nobodyiam 请问yml格式的namespace，可以获取整个yml文件的内容吗？我希望拿到全部内容自己解析kv，不需要apollo解析。

**Comment by zouyx** [comment]
@chg87599671 config.getContent()，应该是能拿到整个内容的。

**Comment by chg87599671** [comment]
@zouyx com.ctrip.framework.apollo.Config 这个接口，以及几个实现类都没有getContent()方法哦。我是1.4版本。
不过我已经通过http请求拿到了。thanks
`http://apollo-host:8080/configs/appid/cluster/namespace`

**Comment by zouyx** [comment]
@chg87599671 参考这里：https://github.com/ctripcorp/apollo/blob/5440572b027091a580b5192ef4d7d3b35b5e43bc/apollo-client/src/main/java/com/ctrip/framework/apollo/ConfigService.java#L64
