### ISSUE TITLE
恩，多个公共namespace之间共享一部分配置，确实是一个场景，这块看看是否有好的解决方案

### ISSUE THREAD

**Issue by dingguangbiao** [ctripcorp/apollo#2687]
恩，多个公共namespace之间共享一部分配置，确实是一个场景，这块看看是否有好的解决方案

_Originally posted by @nobodyiam in https://github.com/ctripcorp/apollo/issues/2538#issuecomment-526895520_

有好的方案吗？目前也遇到了这种场景，感觉要是支持多继承就可以了

**Comment by helhades** [comment]
同问，貌似看文档没找到公共的共享方式，不过要是用yaml自己的继承方式可以间接解决吧，我乱说的。

**Comment by JaredTan95** [comment]
https://github.com/ctripcorp/apollo/issues/2538#issuecomment-526895520 重复了。
