### ISSUE TITLE
对于.Net版本中getConfig方法疑惑

### ISSUE THREAD

**Issue by ankelen** [ctripcorp/apollo#2691]
我有一个.Net服务，并把配置按类型分成了两个命名空间（在同一个集群下）。
我发现getConfig方法如果不传命名空间的话，会默认使用application命名空间，我能不能使用某个方法从所有已加载的命名空间中去获取配置呢？

**Comment by nobodyiam** [comment]
可以自己实现一个聚合Config，让它获取多个namespace
