### ISSUE TITLE
Protal的ServerConfig表字段问题

### ISSUE THREAD

**Issue by JunminZhang** [ctripcorp/apollo#2698]
在测试修改系统参数的时候，发现无法修改，排查后发现是因为字段key与关键字冲突
![QQ截图20191025155937](https://user-images.githubusercontent.com/34052378/67553816-9cac0e80-f740-11e9-929a-7a8f962233c4.png)
![QQ截图20191025155907](https://user-images.githubusercontent.com/34052378/67553817-9d44a500-f740-11e9-81a2-bffb0615e6a1.png)
把实体类Key的name改成`key`后解决了，不知道是不是版本问题

**Comment by JunminZhang** [comment]
![图片](https://user-images.githubusercontent.com/34052378/67554471-11337d00-f742-11e9-9d7d-72d4031a8f66.png)

**Comment by g5niusx** [comment]
`update ServerConfig sc set sc.Key ='123',value='456' where Id = '6';`

**Comment by g5niusx** [comment]
`update ServerConfig sc set sc.Key ='123',value='456' where Id = '6';`
可以使用这种方法来更新。 😄

**Comment by nobodyiam** [comment]
可以用 管理员工具 - 系统参数 页面来设置
