### ISSUE TITLE
apollo如何支持spring-security-rsa的方式加密

### ISSUE THREAD

**Issue by sg6303** [ctripcorp/apollo#2700]
公司这边原来使用秘钥进行对敏感数据加密，比如 数据库连接的用户名和密码 等。配置如下
encrypt:
  key-store:
    location: classpath:/server.jks
    password: aaabbb
    secret: aaabbb
    alias: aaabbb
spring:
  security:
     basic:
       enabled: true

那么切换为apollo的时候，如何更好的支持，原来密码加密完了之后是  {cipher} 开头的。
我看了 apollo的使用里面，里面有一个是 用 jasypt 加密。但是这样 配置的时候需要配置上
加密盐和加密后的字符串是 ENC开头的，所有我所有的都要重新配置一遍。而且客户端也要重新支持 jasypt  。这样改动有点大，有没有 直接支持  {cipher}  这种方式加密的？？

**Comment by nobodyiam** [comment]
可以模仿jasypt的实现方式，加一个property sources，当发现值是 {cipher} 开头的时候做一次解密

**Comment by sg6303** [comment]
1.后面我发觉其实jasypt好像并不安全啊。只要得到 jasypt.encryptor.password 和 加密后的密文串，也就是 ENC里面的内容。就可以利用命令
 java -cp jasypt-1.9.2.jar org.jasypt.intf.cli.JasyptPBEStringDecryptionCLI input="BQS9PejHSU+1dY3cdmXaVw==" password=klklklklklklklkl 
去解密。能得到原内容，这样其实不安全啊。本地的服务会有缓存，大家都可以从缓存文件 拿到这些然后去解密，一样起不到 加密效果，这个要怎么弄比较安全些呢？

2.出于对上面这个问题的考虑，是否使用 原来那种密钥加密会好些呢？之前你说可以模仿jasypt的实现方式，这个大致上是要怎么弄来着？？

**Comment by sg6303** [comment]
3.可以不要有本地缓存吗？

**Comment by nobodyiam** [comment]
这个和本地是否有缓存无关，安全系数主要取决于加密的算法和秘钥的获取机制。秘钥可以考虑在运行时从服务端获取，不过怎么安全的获取是另一个需要考虑的点。

jasypt的实现方式很简单，debug一次就明白了。

**Comment by wl4g** [comment]
> 这个和本地是否有缓存无关，安全系数主要取决于加密的算法和秘钥的获取机制。秘钥可以考虑在运行时从服务端获取，不过怎么安全的获取是另一个需要考虑的点。
>
> 我认为可以模仿ssl/tls的方式（增加握手动作），即：在client与server首次建立连接时，client将生成的公钥rsa_pub发送给server，然后server生成临时aes_key用rsa_pub加密然后返回给client，client收到后用私钥rsa解密，这样就可以使用aes_key安全的传输数据了（连接的信任问题可以使用自签证书，初始导入来解决），个人认为还算比较完善，不知是否我想过于简单了？

**Comment by wl4g** [comment]
> 这个和本地是否有缓存无关，安全系数主要取决于加密的算法和秘钥的获取机制。秘钥可以考虑在运行时从服务端获取，不过怎么安全的获取是另一个需要考虑的点。
> 
> jasypt的实现方式很简单，debug一次就明白了。

我认为完全可以模仿ssl/tls（增加握手）来解决，启动完成后client生成rsa/rsa_pub发送给server，然后server收到后生成临时aes_key用这个rsa_pub加密然后返回给client，client再使用私钥rsa解密，这样就可以使用这个aes_key安全的传输配置数据了，（其中还有连接信任问题，可以用自签证书解决），你就得这个方案是否可行？？

**Comment by nobodyiam** [comment]
@wl4g 这里要解决的应该不是传输过程中的数据安全问题，而是希望数据配置的时候就是加密的

**Comment by nobodyiam** [comment]
see #3187
