### ISSUE TITLE
启动完portal包后，登录进去后发现环境列表无数据

### ISSUE THREAD

**Issue by javaxiaoyetan** [ctripcorp/apollo#2701]
按步骤启动完三个jar后，登录进portal,创建完一个项目后发现环境列表里面没有值。
添加集群的时候也发现选择环境的选项没有，这是为什么呢？ 我看数据库里面有一个默认的dev环境。
![image](https://user-images.githubusercontent.com/16789696/67656837-e474a500-f98f-11e9-8551-31f36c3893de.png)

![image](https://user-images.githubusercontent.com/16789696/67656854-ee96a380-f98f-11e9-9bf7-eaf323d62222.png)

![image](https://user-images.githubusercontent.com/16789696/67656864-f9513880-f98f-11e9-8b91-f8c3dbf08b95.png)

**Comment by nobodyiam** [comment]
看下portal的日志，应该是dev环境的admin service不可用
