### ISSUE TITLE
i18n 没有彻底

### ISSUE THREAD

**Issue by mghio** [ctripcorp/apollo#2703]
![image](https://user-images.githubusercontent.com/43461943/67744867-ae055b80-fa5d-11e9-96e1-24be9c0adbef.png)

**Comment by nobodyiam** [comment]
再刷一下页面，或者清一下缓存试试

![image](https://user-images.githubusercontent.com/837658/67820223-56193400-faf3-11e9-9405-73d6ce7f1579.png)
