### ISSUE TITLE
配置值很大的问题

### ISSUE THREAD

**Issue by ywf4026** [ctripcorp/apollo#2704]
请问下，配置值很大的情况下，大概20万字符，Apollo的后台页面就卡死了，发布不了了，请问有什么措施可以解决这个问题?

我能想到的是：
1.将配置拆分成多个namespace，每个2W个字符，这样大概新建10个namespace就行，但是带来的问题是：
在启动加载时，这些namespace需要写死，可是，我这个配置还要支持动态刷新的，这样就做不到动态刷新了，因为namespace写死在代码里了。不知道namespace支持通配符吗？比如
@EnableApolloConfig(value = "feature-*.yaml")
我试了下是不行的，不知道是不是我使用姿势有问题？还有，我能重写个EnableApolloConfig注解，使他具有通配符功能，可行吗？

还望解答，谢谢了~~

**Comment by nobodyiam** [comment]
20万个字符的配置，基本上可以认为是业务数据而非应用配置了吧，另外，对这么大的一个配置，发布的时候也无法很容易的判断出来修改的值是否正确，所以这类配置不建议通过apollo来管理。

如果要考虑分拆的话，有一个建议是通过API方式来获取后再拼接，比如在一个namespace下存放分拆的namespace列表，拿到列表后再通过api方式获取单个namespace。
