### ISSUE TITLE
Error reported when deploying Apollo config

### ISSUE THREAD

**Issue by liran0705** [ctripcorp/apollo#2711]
The configuration is as follows：
spring.datasource.url = jdbc:mysql://10.20.0.66:3306/ApolloConfigDB?characterEncoding=utf8
spring.datasource.username = apollo
spring.datasource.password = 'apollo'

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class

**Comment by nobodyiam** [comment]
please check whether the configuration file is loaded, e.g. is the spring profile right?

**Comment by alec185** [comment]
这个问题是怎么解决的
