### ISSUE TITLE
请教下如何开发格式校验功能

### ISSUE THREAD

**Issue by ywf4026** [ctripcorp/apollo#2712]
我希望对namespace的Value作格式校验，我看了下源码，初步决定在adminservice模块的ItemController.create里写，如下图红色箭头处插入格式校验：
![image](https://user-images.githubusercontent.com/3722641/67844675-24c35700-fb39-11e9-827d-54e74526e252.png)

具体是这样做的：
使用SPI，针对每个namespace、key都写一个SPI校验逻辑，如果校验异常，抛出BadRequestException异常

不知道方案是否合理，或者是否有更合适的方案，还望赐教，谢谢了！

**Comment by nobodyiam** [comment]
可以先参考yaml格式namespace的syntax check实现一个弱校验

![image](https://user-images.githubusercontent.com/837658/67910892-71517580-fbbf-11e9-9132-d3a7f3910737.png)
