### ISSUE TITLE
是否有支持动态加载 namespace 的功能？

### ISSUE THREAD

**Issue by odirus** [ctripcorp/apollo#2714]
如题，我们希望能够动态加载 namespace，而不是在启动的时候通过参数决定要加载 namespace。

**Comment by nobodyiam** [comment]
可以通过API方式来实现

**Comment by odirus** [comment]
> 可以通过API方式来实现

感谢。我现在是启动阶段去处理的，如果系统中有设置 "apollo.bootstrap.namespaces" 则读取系统值，否则从 Apollo 的 application 空间读取该配置值。

其他有类似需求的同学，也可以参考我的代码实现。
