### ISSUE TITLE
使用apollo配置dubbo之后，无法注册service到nacos

### ISSUE THREAD

**Issue by makingtime** [ctripcorp/apollo#2716]
使用apollo配置dubbo的一些配置之后，现在本地的application.properties中只剩下了apollo相关的一些配置，
下面这些dubbo相关的配置都放在apollo上的dubbo namespace（类型:properties）里了：

```
dubbo.application.name = xxx
dubbo.scan.base-packages = xxx
dubbo.protocol.name = dubbo
dubbo.protocol.port = -1
dubbo.registry.protocol = nacos
dubbo.registry.address = xxx:8848
```

但是启动provider之后, nacos注册中心的服务列表中没有这个provider,
把这些配置都放到本地（本地的apollo配置没删除），就可以正常注册（apollo上的配置删除和不删除都一样）

本地application.properties的配置
```
app.id = 1001
apollo.meta = http://xxx.xxx:8080
apollo.bootstrap.enabled = true
apollo.bootstrap.namespaces = application,application-commons
dubbo.config-center.address=apollo://xxx.xxx:8080
```

**Comment by makingtime** [comment]
把`dubbo.scan.base-packages = xxx.xxx` 放到本地就好了，这个配置是不能放到apollo上吗？

**Comment by nobodyiam** [comment]
这个配置加载时机需要在比较前面，使用eagerLoad方式试试

**Comment by makingtime** [comment]
试了在本地加上`apollo.bootstrap.eagerLoad.enabled=true`，但是还是一样，跟本地配置`dubbo.scan.base-packages = xxx.xxx`的区别是少了很多`org.apache.dubbo.config.AbstractConfig`的日志，也没有注册服务到nacos的日志

**Comment by nobodyiam** [comment]
是否能上传一个最简化的demo样例？

**Comment by tybln** [comment]
> 试了在本地加上`apollo.bootstrap.eagerLoad.enabled=true`，但是还是一样，跟本地配置`dubbo.scan.base-packages = xxx.xxx`的区别是少了很多`org.apache.dubbo.config.AbstractConfig`的日志，也没有注册服务到nacos的日志

加上试试
apollo.bootstrap.enabled = true
apollo.bootstrap.namespaces = application,dubbo

**Comment by makingtime** [comment]
> 
> 
> > 试了在本地加上`apollo.bootstrap.eagerLoad.enabled=true`，但是还是一样，跟本地配置`dubbo.scan.base-packages = xxx.xxx`的区别是少了很多`org.apache.dubbo.config.AbstractConfig`的日志，也没有注册服务到nacos的日志
> 
> 加上试试
> apollo.bootstrap.enabled = true
> apollo.bootstrap.namespaces = application,dubbo

在`apollo.bootstrap.namespaces` 里加上 `dubbo` namespacke就好了

**Comment by tybln** [comment]
> > > 试了在本地加上`apollo.bootstrap.eagerLoad.enabled=true`，但是还是一样，跟本地配置`dubbo.scan.base-packages = xxx.xxx`的区别是少了很多`org.apache.dubbo.config.AbstractConfig`的日志，也没有注册服务到nacos的日志
> > 
> > 
> > 加上试试
> > apollo.bootstrap.enabled = true
> > apollo.bootstrap.namespaces = application,dubbo
> 
> 在`apollo.bootstrap.namespaces` 里加上 `dubbo` namespacke就好了

dubbo starter需要在启动前加载配置
