### ISSUE TITLE
namespace删除没效果

### ISSUE THREAD

**Issue by sg6303** [ctripcorp/apollo#2717]
现在有两个namespace，一个是 application.properties 另一个是 application.yml。 两个namespace 都有同一个配置key 。比如是 application.properties中的common.key=1，application.yml的common.key=2  ，项目启动的时候，启动脚本也传递了common.key=3，启动成功后，common.key是等于1。
然后把application.properties 的common.key=1删除了并发布，此时取到的值是 common.key=2 ，然后再把application.yml 的namespace整个都删除了。此时取到的值 依然还是  common.key=2 ？ 为什么不是 3 呢？？
看了下 namespace删除之后，本地的缓存没有删除那个缓存文件，应该是取到了缓存文件里面的值。这个感觉挺有问题的

**Comment by ywf4026** [comment]
我也发现这个问题了，删除key或者namespace都用的是本地缓存

**Comment by nobodyiam** [comment]
删除整个namespace的前提是没有应用在使用这个namespace，上述的情况建议把namespace的配置清空后发布一次。

**Comment by sg6303** [comment]
如果说前提是没有应用在使用这个namespace的话。那删除那边是否要做一次校验呢，有在使用的时候，不应删除。如果不做校验的话，大家不知道这个前提，就会容易产生这个问题

**Comment by nobodyiam** [comment]
在项目页面上删除namespace是会校验的，如果有应用在使用会阻止删除

![image](https://user-images.githubusercontent.com/837658/68169468-409a8300-ffa7-11e9-9a26-a978554d10a1.png)

通过管理员工具删除的话不会阻止删除

**Comment by sg6303** [comment]
对，如果是通过 项目页面上删除。接下来进来的时候就会有个问题，老是会提示 补充namespace
![image](https://user-images.githubusercontent.com/3842903/68266250-7d3eab00-0089-11ea-9881-df5b570a89e2.png)

如果是通过 管理员工具的话，就直接删除。就不提示。所以还是感觉有点怪怪的。

**Comment by nobodyiam** [comment]
删除namespace是比较重的操作，一般用于建错namespace的情况，如果namespace已经有使用了，删除还是得非常慎重
