### ISSUE TITLE
key删除不生效

### ISSUE THREAD

**Issue by ywf4026** [ctripcorp/apollo#2719]
请教下，遇到个Apollo删除key的问题：
在已加动态刷新监听情况下，
        this.applicationContext.publishEvent(new EnvironmentChangeEvent(changeEvent.changedKeys()));

删除key后，对应的value并未变null，最后跟踪spring源码(springboot2.1.0)，发现是Binder.bindObject在property找不到情况下，就不再bind了，所以之前是啥值还是啥值。

![image](https://user-images.githubusercontent.com/3722641/67952055-a396bd80-fc27-11e9-8f89-788d4f0105c1.png)

这个是spring的问题吗？
很想能删除key,可是就是删除不掉，请大佬赐教，多谢了！

**Comment by nobodyiam** [comment]
一般配置删除还是很少见的，你能说下是什么场景？

**Comment by ywf4026** [comment]
偏业务的配置会比较多

**Comment by nobodyiam** [comment]
或者说删除key的场景希望最终生效的是什么值？如果placeholer上没有指定默认值的话，实际上也没法做重新的bind，猜测可能是这个原因所以spring就干脆不做重新bind了

**Comment by ywf4026** [comment]
如果是ConfigurationProperties的话，默认值其实就是java类型自己的默认值。
其他配置加载情况没想过

**Comment by nobodyiam** [comment]
apollo原生api是支持你说的场景的，目前来看是spring的placeholder处理不支持，比如`${someKey}`，对于这个placeholder，如果someKey没有定义的话，它是无法完成bind动作的，如果是在启动阶段就会造成启动失败。

**Comment by ywf4026** [comment]
嗯，我改用refreshScope实现吧。多谢指教了
