### ISSUE TITLE
apollo不支持对所有配置进行多维度的逻辑划分以至于不能支持从不同视角来主动搜索配置这很不方便尤其是apollo也并未提供全文搜索功能

### ISSUE THREAD

**Issue by freelogic** [ctripcorp/apollo#2721]
比如有个产品使用apollo， 平台名字为K，它包含10个sprintboot的模块M1到M10，支持提供三个业务功能B1,B2,B3并且在apollo里面有200个配置项。那么其实，我们应该有（但apollo现在并不支持）不同的视角（逻辑划分）来归类这200个配置项（根据《012原理》“所有问题都是归类问题”）；

比如用模块M1到M10来划分，将200个配置项，洒在10个模块的namespace里面，然后来做增删改查；
比如再用上层业务需求B1到B3的三个namespace来划分这200个参数；
再比如用配置归类，DB归为一类，kafka归为一类，REDIS,等等分类，来做namespace，对200个配置再次做划分；

等等，多种划分，有些同事习惯这样，有些习惯那样，没有好坏！！！只有合适！！！哪种最方便？？？没有最方便，只有更方便！！！

但是，apollo不支持逻辑多次划分，而且也不支持全局全文搜索，所以这极其不方便！！！！！！！！！！！

apollo的产品经理的能力太差了！！！！！！！！！1111

**Comment by lepdou** [comment]
欢迎大神提 PR~

**Comment by JaredTan95** [comment]
欢迎大神提 PR~

**Comment by freelogic** [comment]
我只能说比较遗憾了。这样一个逻辑划分的功能，对DB来说只是增加一些字段而已，并不影响物理存储，但是通过归类法的应用，对上次应用层来看，确实方便了很多。分类永远要超过数据，没有分类的数据不是好数据，分类本身也是数据，我们以前喜欢叫“元数据”，其实“数据及数据的分类都是数据”。
这些也不增加DB压力。 apollo可能的定位是一个处理1万个配置一下的小系统，1万个配置，对任何正常的关系型DB没有任何压力可言。 可惜了。我要有人力，团队肯定是开发产品经理自己的业务，哪有时间来support开源的apollo呀。再举个例子：
谷歌的picasso，还算一个小软件吧？牛不牛，很烂，为啥，他企图做一些小分类，自动找找人脸归一个类，找找时间归一个类，找找景物归一个类（景物它目前还没做）。其实这是一个什么问题？数据领域只有一个问题“就是归类问题”，我们可以为picasso增加一个“归类管理”，一个维度定义一颗归类树，比如“时间归类树1”，“时间归类树2”，“景物归类树1”，“人脸归类树2”，维度很多，哪怕一个时间维度，也有多种归类法，按照天的平展大列表也是树TREE数据结构的特殊形式，如果按照YYYY/MM/DD可以构成三层的分类树，或叫归类树，都一个意思。可惜谷歌也不愿意做，可能因为如果搞了归类树，但是能自动归类的机器学习算法不多。比如我想按照旅游点归类，按照party的性质归类，目前cv和图像识别领域才刚刚弄一个人脸识别才起步，商汤，谷歌，face++几家要商用，要99.5%以上还很难。所以其他的场景识别，上下文语义还很早呢，所以分类这个没有丝毫难度的IT手段倒没法推进了。推进后没有插件不行。汽车虽好，发动机不行，没有不同型号的发动机来换配件，要车子好有啥用？
但是apollo不一样，一个管理万把配置的系统，要做到全球第一，超过谷歌，轻轻松松，分分钟。 做好我说的逻辑二次划分，做分类树，让apollo可以定义分类树，一种分类一个表，或者放在一起也行。一张表，一个entity，不会超过500行代码，差不多了。当然，apollo的源码我没仔细看过。我java团队的一个同事看过，并且开发了一个跨域的功能，你们不给PR就算了。我下次问问他，实在不行，真给做了算了。
不过你们做了全局KEY搜索，实现了我提交的另一个issue，这个很感谢，等下一个版本1.6.0.
程序和程序的设计，看缘分和慧根了。
