### ISSUE TITLE
请问jar包直接执行是怎么实现的 我看启动脚本里这么写的./$SERVICE_NAME".jar" start 

### ISSUE THREAD

**Issue by baiyun1102** [ctripcorp/apollo#2725]
我看启动脚本里这么写的./$SERVICE_NAME".jar" start 

[root@node1 adminservice]# ./apollo-adminservice.jar stop
Stopped [5258]
[root@node1 adminservice]# ./apollo-adminservice.jar start
Started [5575]
[root@node1 adminservice]#

**Comment by nobodyiam** [comment]
这个是Spring Boot的自启动jar包，可以找下相关文档说明
