### ISSUE TITLE
如何更新nginx的配置?

### ISSUE THREAD

**Issue by Jerrywgl** [ctripcorp/apollo#2728]
有大神知道怎么用于更新nginx的配置并使之生效吗?或者给一个类似的列子也可以。非常感谢

**Comment by nobodyiam** [comment]
通过http接口获取到配置后更新nginx的配置文件，然后reload即可

**Comment by Jerrywgl** [comment]
您好按照您的方法，我获取到配置配置列表如下:

'003', 'cluster' => 'default', 'namespaceName' => 'nginx.conf', 'configurations' => array ( 'haha' => '1222', 'work' => '1000', 'worker_connections' => '10240', 'worker_processes' => '4', 'worker_rlimit_nofile' => '10000', 'listen' => '8080', ), 'releaseKey' => '20191104181002-f4a91b6436099406', ); 这个格式nginx是不能直接用，得自己写脚本解析下格式吗?非常感谢

**Comment by nobodyiam** [comment]
是的，需要自己解析一下的，另外apollo也提供接口可以直接获取properties格式的

https://github.com/ctripcorp/apollo/wiki/%E5%85%B6%E5%AE%83%E8%AF%AD%E8%A8%80%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97#122-http%E6%8E%A5%E5%8F%A3%E8%BF%94%E5%9B%9E%E6%A0%BC%E5%BC%8F
