### ISSUE TITLE
必须加apollo.bootstrap.enabled,apollo.bootstrap.namespaces才能读取到配置

### ISSUE THREAD

**Issue by tybln** [ctripcorp/apollo#2730]
同一个项目，用0.8版本一切正常，用1.5和1.6启动获取不了配置，必须加apollo.bootstrap.enabled，apollo.bootstrap.namespaces才能读取到配置。确认是不需要在启动前就需要加载配置的，因为0.8也没这个功能。请问可能是哪里有问题？

**Comment by nobodyiam** [comment]
能否提供下更多信息？

**Comment by tybln** [comment]
> 能否提供下更多信息？

还有个疑问是在本地是完全ok的，但测试环境有问题，测试环境docker部署。上面问题描述都是在同一个测试环境下出现的

**Comment by tybln** [comment]
问题解决了，项目中有个依赖包是之前的版本导致的
