### ISSUE TITLE
apollo如何快速复制dev环境的数据到uat环境的数据进行部署？

### ISSUE THREAD

**Issue by yizhishang** [ctripcorp/apollo#2735]
公司环境一套-dev，
客户环境一套-uat

试过表导出导入，报错了呢

**Comment by yizhishang** [comment]
公司环境一套-dev，
客户环境一套-uat

试过表导出导入，报错了呢

**Comment by nobodyiam** [comment]
如果是同一个portal新增环境的话，可以参考

https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#2121-%E4%BB%8E%E5%88%AB%E7%9A%84%E7%8E%AF%E5%A2%83%E5%AF%BC%E5%85%A5apolloconfigdb%E7%9A%84%E9%A1%B9%E7%9B%AE%E6%95%B0%E6%8D%AE
