### ISSUE TITLE
client在spring环境但无spring-boot时会异常

### ISSUE THREAD

**Issue by qyudy** [ctripcorp/apollo#2737]
Apollo-client在spring环境下，如果没有引入spring-boot的jar依赖，那么运行时会报java.lang.ClassNotFoundException: org.springframework.boot.env.EnvironmentPostProcessor
查看源码是因为com.ctrip.framework.apollo.spring.boot.ApolloApplicationContextInitializer强依赖了spring-boot的类导致的
我们公司项目不太合适引入spring-boot，这里怎么修改成可选的依赖？

**Comment by nobodyiam** [comment]
ApolloApplicationContextInitializer只在spring boot环境下才会启用(仅通过[spring.factories](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/resources/META-INF/spring.factories)引用)，在spring环境下不会启用的，建议再仔细看下实际的使用方式。

**Comment by qyudy** [comment]
问题出在ApolloApplicationContextInitializer类既作为spring的ApplicationContextInitializer实例又作为springboot的EnvironmentPostProcessor实例：
`
org.springframework.context.ApplicationContextInitializer=\
com.ctrip.framework.apollo.spring.boot.ApolloApplicationContextInitializer
org.springframework.boot.env.EnvironmentPostProcessor=\
com.ctrip.framework.apollo.spring.boot.ApolloApplicationContextInitializer
`

将ApolloApplicationContextInitializer里的EnvironmentPostProcessor接口实现另外建一个类放置即可：
`
org.springframework.boot.env.EnvironmentPostProcessor=\
com.ctrip.framework.apollo.spring.boot.ApolloBootApplicationContextInitializer
`
