### ISSUE TITLE
关联公共namespace的接口有吗

### ISSUE THREAD

**Issue by shawyouxh** [ctripcorp/apollo#2740]
在文档中只找到了创建namespace的接口：
https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0
![image](https://user-images.githubusercontent.com/7700226/68368388-ea7a3b00-0172-11ea-9651-44ff679caeb7.png)

如果想关联已有的公共namespace要如何请求呢？

**Comment by nobodyiam** [comment]
目前的版本仅有创建appnamespace的接口，没有创建namespace的接口，如确有场景需要，可以考虑提交PR

**Comment by shawyouxh** [comment]
> 目前的版本仅有创建appnamespace的接口，没有创建namespace的接口，如确有场景需要，可以考虑提交PR

是否可以关联已有的公共namespace，不是自己创建新的

**Comment by nobodyiam** [comment]
是的，`创建namespace的接口`其实说的就是关联公共的namespace。

创建appnamespace的接口是真正创建一个namespace。

**Comment by shawyouxh** [comment]
> 是的，`创建namespace的接口`其实说的就是关联公共的namespace。
> 
> 创建appnamespace的接口是真正创建一个namespace。

好的，谢谢

**Comment by ddy4633** [comment]
这里可以理解为创建namespace，其实就是让app中的namespace去关联已经存在的公共namespace吗？

**Comment by nobodyiam** [comment]
@ddy4633 

AppNamespace 和 Namespace 是两个实体，前者可以认为是 namespace 的元数据定义，后者是在具体某个环境和集群中创建的 namespace 实体，类似 class 和 instance 的关系。

**Comment by linzhoulxyz** [comment]
请问现在有接口能实现该功能吗？看文档好像还是没看到。
