### ISSUE TITLE
是否考虑开放所有对应接口，使得能在界面上完成的动作，都可以通过程序完成

### ISSUE THREAD

**Issue by kinsight** [ctripcorp/apollo#2741]
我们在进行devops的开发，所有的环境通过cmdb、docker自动化生成、销毁，但是每个环境产生的访问地址，资源密码等等都会有所不同，需要能够通过程序自动化完成，手工维护的效率太低。大部分的接口都有，就是生成集群环境的，可以考虑增加进去，最大限度开放掉

**Comment by nobodyiam** [comment]
这是个值得考虑的建议，目前apollo的openapi也是部分实现了自动化的能力。不过完全开放所有接口，通过程序完成所有的操作，对于大部分apollo的用户而言价值并不大，所以如确有实际需求的话，欢迎提交PR。
