### ISSUE TITLE
下载到的xml文件回车换行符被转成\r\n字符串导致解析异常

### ISSUE THREAD

**Issue by NieChao** [ctripcorp/apollo#2743]
apollo团队你们好：
 最近在写c++的apollo客户端，发现通过{config_server_url}/configfiles/{appId}/{clusterName}/{namespaceName}?获取的文件同potal上的不一致，表现为两个方面：
1、冒号前面会带有转义字符\
2、xml文件会将回车换行符直接转换成\r\n，导致解析异常。
请问是否存在该问题，客户端该如何有效解决？

**Comment by nobodyiam** [comment]
1、冒号前面会带有转义字符
这个是properties格式的规范

2、xml文件会将回车换行符直接转换成\r\n，导致解析异常。
是的，目前换行符会以`\n`存储，程序中需要处理一下

![image](https://user-images.githubusercontent.com/837658/68521877-58904080-02e0-11ea-9620-d4d7ed281b5a.png)

![image](https://user-images.githubusercontent.com/837658/68521885-634ad580-02e0-11ea-9dfa-9ee62ba3e2f1.png)
