### ISSUE TITLE
通配符的匹配很全面, 但无法找到元素 'apollo:config' 的声明。

### ISSUE THREAD

**Issue by quanquan-dane** [ctripcorp/apollo#2744]
spring 4.1.6整合apollo出现问题，org.xml.sax.SAXParseException; lineNumber: 14; columnNumber: 31; cvc-complex-type.2.4.c: 通配符的匹配很全面, 但无法找到元素 'apollo:config' 的声明。

![image](https://user-images.githubusercontent.com/6870297/68524715-f39b1180-0304-11ea-89c3-327a10390baf.png)
![image](https://user-images.githubusercontent.com/6870297/68524722-04e41e00-0305-11ea-9d4b-0b8c86d29867.png)

**Comment by nobodyiam** [comment]
这个声明在apollo-client的jar包中

https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/resources/META-INF/spring.schemas

**Comment by quanquan-dane** [comment]
那对应的在spring-config.xml里面如何配置？？

**Comment by quanquan-dane** [comment]
> 这个声明在apollo-client的jar包中
> 
> https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/resources/META-INF/spring.schemas
那对应的在spring-config.xml里面如何配置？？

**Comment by quanquan-dane** [comment]
http://www.ctrip.com/schema/apollo    http://www.ctrip.com/schema/apollo.xsd这两个忘记在xsi:schemaLocation=加了
