### ISSUE TITLE
加入  <apollo:config namespaces="application"/> 配置后  @Autowired 为 null

### ISSUE THREAD

**Issue by seqwait** [ctripcorp/apollo#2747]
spring4 采用原始的xml 配置但是 好像
<apollo:config namespaces="application"/>
加入这个后
\<bean id="xxx" class="xxxx.service" init="init"\>
service 下dao 的 @Autowired 就注入不进去.
下面是web.xml中内容 apollo配置放在 commonContext.xml里面
  <context-param>
        <param-name>contextConfigLocation</param-name>
        <param-value>
            WEB-INF/config/spring/commonContext.xml
            WEB-INF/config/spring/mobileServerContext.xml
            WEB-INF/config/spring/mobileUserContext.xml
        <param-value>
 <context-param>

**Comment by nobodyiam** [comment]
`<apollo:config namespaces="application"/>`，加入这个后apollo会往Spring的property sources中增加一个配置源，不会有其它动作，所以不会影响到bean的创建和注入的
