### ISSUE TITLE
发布页面卡顿问题

### ISSUE THREAD

**Issue by ywf4026** [ctripcorp/apollo#2749]
![image](https://user-images.githubusercontent.com/3722641/68573811-70fc8880-04a3-11ea-9664-bae8f11c9679.png)

请问：发布页面在查看变更tab下，在值很大的情况下滚动很卡，甚至卡死，请问这个性能有优化的必要吗？谢谢了！

**Comment by nobodyiam** [comment]
有优化的必要，目前这个在前端展示的时候并没有做很多优化，如果有啥好的想法也欢迎PR~
