### ISSUE TITLE
目前有多个配置数据体积不大，但是属于业务配置，建议通过apollo来配置吗？

### ISSUE THREAD

**Issue by chaoyebugao** [ctripcorp/apollo#2755]
首先这不是一个issue。
涉及多个应用共享某些配置，但本身属于业务类型配置，比如“手续费”。想知道有没有人一样这么做...

**Comment by wkcaeser** [comment]
我们就有这么干的，刚好借助apollo的权限管理来给业务人员分配权限

**Comment by nobodyiam** [comment]
如果配置数据不大，且更新频率不高的话，倒是可以。

如果配置数据格式比较复杂，建议自己写管理页面，然后通过open api写到apollo。

**Comment by chaoyebugao** [comment]
> 如果配置数据不大，且更新频率不高的话，倒是可以。
> 
> 如果配置数据格式比较复杂，建议自己写管理页面，然后通过open api写到apollo。

现在就是这么干的 (*￣︶￣)
