### ISSUE TITLE
源码疑问 

### ISSUE THREAD

**Issue by yu757371316** [ctripcorp/apollo#2756]
为什么我的项目接了apollo以后，打印Envionment连的PropertySource信息ApolloBootstrapPropertySources和ApolloPropertySources内容为空呢？

**Comment by JaredTan95** [comment]
你得确保你的client已经从Apollo 服务端拉取到配置了。

**Comment by yu757371316** [comment]
> 你得确保你的client已经从Apollo 服务端拉取到配置了。

我搞错了，没指定本地命名空间。。。
