### ISSUE TITLE
请教个利用apollo实现动态数据源切换问题

### ISSUE THREAD

**Issue by ywf4026** [ctripcorp/apollo#2757]
我看了下这个实例，https://github.com/ctripcorp/apollo-use-cases/tree/master/dynamic-datasource/src/main/java/com/ctrip/framework/apollo/use/cases/dynamic/datasource
有个疑问请教下：

apollo配置推送，客户端拉取配置后，其实还有怎么处理配置的过程，像数据源切换，涉及创建连接等过程，中间很有可能失败，但Apollo不管这些配置是否真正生效了，只在实例列表中告知了配置的获取时间，是否真正生效未知。

如果有另一个配置推送依赖其他配置真正生效，而又不能放置在同一个namespace中，这种问题该怎么解决，谢谢指教了！！

**Comment by nobodyiam** [comment]
1. 是的，apollo也只能知晓客户端是否拉取到配置了，至于配置拉取后的行为是否正确，这个apollo是不感知的，建议通过业务监控来做观察

2. 有依赖关系的配置建议放在一个namespace，不然对于配置的维护者而言，很容易出错吧
