### ISSUE TITLE
请教,Apollo 如何做到像springboot那样支持List/Map 类型配置

### ISSUE THREAD

**Issue by kuixiang** [ctripcorp/apollo#2758]
1 . 背景描述：
我们应用场景是有个公共配置，放到mysql里，比如：
```
PK c1 c2 c3
----------------
key1 v11 v12 v13
key2 v21 v22 v23
...
```

2. 目前用法：
2.1 用法一：  SpringBoot 里可以支持List类型，比如某properties文件
```
config.list[0].c1=v01
config.list[0].c2=v02
config.list[1].c1=v11
config.list[1].c2=v12
```
可以绑定模型到 
private List<Model> config = Arrays.asList(
new Model(v01,v02)
,new Model(v11,v12)
)
里，然后 应用 List 转 Map

2.2 用法二：SpringBoot里直接配置Map类型
```
config.key1.c1=v11
config.key1.c2=v12
config.key2.c1=v21
config.key2.c2=v22
```
可以绑定模型到 
Map<String,Model> config = new HashMap()
config.put(key1,new Model(v11,v12));
config.put(key2,new Model(v21,v22));

3.  迁移到apollo 用法
用法一： 先按照key后按照字段索引信息
```
key1.c1=v11
key1.c2=v12
key2.c1=v21
key2.c2=v22
```

用法二： 先按照字段，然后按照key来索引信息
```
c1.key1=v11
c2.key1=v12
c1.key2=v21
c1.key2=v22
```

用法三： 用Ａpollo的 @JsonValue 绑定技术
```
1. 配置key="[{'c1':'v11','c2':'v12'},{'c1':'v21','c2':'v22'}]"
@JsonValue(value="key")
private List<Model> items;
```

4. 我的问题
上述3种用法都用起来比较别扭，难以做到像SpringBoot那样绑定到Ｌist 或者Ｍap对象
有什么好的建议么？

**Comment by nobodyiam** [comment]
Apollo支持Spring Boot的用法的，把原来的配置直接原封不动贴到apollo里面即可。

可以参考下：https://github.com/ctripcorp/apollo/blob/master/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/spring/springBootDemo/config/SampleRedisConfig.java
