### ISSUE TITLE
dotnet客户端ApolloOptions.Cluster和ApolloOptions.DataCenter有什么用处

### ISSUE THREAD

**Issue by Ivony** [ctripcorp/apollo#2762]
目前似只支持集群，是不是说DataCenter属性是没用的？

**Comment by nobodyiam** [comment]
![image](https://user-images.githubusercontent.com/837658/69001942-76822480-0922-11ea-8b1c-17d353f797f4.png)

**Comment by Ivony** [comment]
明白了，DataCenter就是idc，也就是上一级集群。
其实与其这样不如把集群名字做成级联的，例如dc1/clusterA，先找dc1/clusterA，找不到再找dc1，再找不到找default。
