### ISSUE TITLE
 .Net 客户端是否支持 4.0 ？

### ISSUE THREAD

**Issue by Joe798** [ctripcorp/apollo#2763]
[.Net客户端使用指南](https://github.com/ctripcorp/apollo/wiki/.Net%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#11-%E7%8E%AF%E5%A2%83%E8%A6%81%E6%B1%82)

 .Net 客户端是否支持 4.0 ？
如果需要支持 4.0，可以怎么处理？

@nobodyiam

**Comment by nobodyiam** [comment]
duplicated with https://github.com/ctripcorp/apollo.net/issues/101

.Net客户端一直支持4.0的
.Net Core客户端2.2.0版本支持了
