### ISSUE TITLE
apollo多集群环境问题

### ISSUE THREAD

**Issue by xingmin860818** [ctripcorp/apollo#2764]
请问apollo多集群模式下，服务启动会去尝试连接其他集群的meta server地址吗？
因为我从日志里面看到去尝试连接了，想确认一下这种行为是正确的吗

**Comment by nobodyiam** [comment]
client只会连接一个环境的meta server
portal会连接多个环境的meta server

**Comment by xingmin860818** [comment]
但是我看服务日志里面回去连接其他集群的地址，虽然是不通的，但是会延长启动时间。这可能是什么原因导致的呢？

**Comment by nobodyiam** [comment]
提供下具体的信息吧？数据配置是什么，日志是什么？

**Comment by xingmin860818** [comment]
好的，配置：
1. A地区一套完整的集群，B地区新增了一个FAT环境的节点，部署了admin和config两个服务，指定连接了A地区的fat库。
2. fat库serverconfig表添加一条记录（原default集群也在使用）：eureka.service.url  idcB http://b.b.b.b:8080/eureka
3. portal服务器在apollo-env.properties配置中的fat.meta后新增了新的meta地址：fat.meta=http://a.a.a.a:8080,http://b.b.b.b:8080

4. 用户在管理平台新建cluster idcB
5. 服务启动时指定idc为idcB，meita地址为新增地址，环境fat

在idcB环境启动服务过程中和服务运行过程都会尝试去连接default（A地区）的metaserver并且提示超时（因为网络不通），反之也一样。虽然不影响业务启动，但是会增加启动时间，而且日志上会使研发产生误解

**Comment by nobodyiam** [comment]
分别看下A地区和B地区meta server上注册的服务地址，应该分别只有本机房的节点，然后每个机房的客户端分别指定本机房的meta server即可。

http://a.a.a.a:8080
http://b.b.b.b:8080

**Comment by xingmin860818** [comment]
在访问idcB的地址时，eureka界面中还是显示Datacenter为default，提示：No instances available，我看有人说config启动的时候要指定自己的机房，而我启动的时候没有做任何修改，请问是这个原因吗？

**Comment by nobodyiam** [comment]
https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#1-eurekaserviceurl---eureka%E6%9C%8D%E5%8A%A1url

![image](https://user-images.githubusercontent.com/837658/70006398-e68ddd00-15a7-11ea-8b49-cf16d7f7f61b.png)
