### ISSUE TITLE
应用中的apollo没有读取本服务的配置，而是读取了依赖服务的配置

### ISSUE THREAD

**Issue by licongyang** [ctripcorp/apollo#2765]
我的apollo版本是1.5.0，本地正常的服务，放到服务器时，apollo没有读取的服务的配置，而是读取内部依赖的配置信息 ，就是 A(apollo配置a) ，B(apollo配置b)， 然后a引用b（-cp 指向b的jar），结果服务器启动A时,结果apollo配置应用的B的配置b。请问这个版本是否存在这个问题，问题是否已修复喃

**Comment by nobodyiam** [comment]
1. 请确认b的jar里面没有配置app.properties
2. 可以打开debug日志看下配置拉取的详情
3. apollo迄今为止的所有版本都不会读取错配置

**Comment by licongyang** [comment]
a和b都是apollo客户端，同样b.jar包里application.properties也是有apollo配置的，但是namespaces配置是b的。

**Comment by licongyang** [comment]
符合你说的第一条，a虽然依赖b,但是启动a时，不应该是读取a的apollo配置嘛？

**Comment by nobodyiam** [comment]
一个应用只有一个appId，所以公共的jar包里面不能配置appId

**Comment by licongyang** [comment]
@nobodyiam 非常感谢您提到情况，后续我们在使用时会注意这点。我们本来是一个应用下父子结构，每个子module都存在配置apollo信息并单独部署情况。现我们已经把配置信息单独提取出来，唯一的bootstrap配置该应用公共信息，包括appid,meta...,每个单独部署的module的配置文件application确定profile,对应profile得到该module对应namespaces，来达到不同module(服务)应用不同配置信息.
