### ISSUE TITLE
页面创建未显示的namespace失败

### ISSUE THREAD

**Issue by LMHHY** [ctripcorp/apollo#2766]
背景：在前端页面创建的namespace失败，提示此namespace已存在，而前端显示的namespace并没有此名称的，对此表示疑惑。
原因：对于前端页面来说，页面只显示未被逻辑删除的namespace，不显示逻辑删除的namespace。新创建的namespace已被逻辑删除

**Comment by LMHHY** [comment]
建议在创建前事先判断是否已经逻辑删除，若已被逻辑删除。即可创建此名字的namespace。NameSpace表的主键为(namespace_name,is_del)

**Comment by nobodyiam** [comment]
是指删除了namespace，没有删除appnamespace吗？

关联的namespace可以在项目页面中删除，私有的namespace一般不建议删除，或者可以找管理员使用`管理员工具 - 删除应用、集群、AppNamespace`页面删除
