### ISSUE TITLE
新建private的namespace会自动带上部门名计算namespace总长度

### ISSUE THREAD

**Issue by jun-jia** [ctripcorp/apollo#2768]
新建private namespace的时候，前面没有部门选项，但保存的时候系统计算private namespace总长度还是把部门的长度也算进去了，要求不能超过32位，改小了namespace长度之后再保存然后查数据库里的记录也显示private namespace的名字前面是带上了部门前缀的。也就是部门如果已经有了15位，那private namespace就不能超过17位。

这个问题之前用1.4.0是没有的，升级到了1.5.1就出现了。不知道这是个bug，还是现在有意这样设计？

**Comment by nobodyiam** [comment]
看了下代码，是一个前端计算的问题，会导致检查private namespace长度的时候把部门的长度也计算进去，不过实际创建的namespace是不会带上部门前缀的。

另外，看代码这个问题应该从一开始就存在了，不是最近的版本才产生的，详情可以看下 #2784
