### ISSUE TITLE
portal里面的链接无法支持自定义contextPath

### ISSUE THREAD

**Issue by qyudy** [ctripcorp/apollo#2770]
apollo-portal里的所有链接，包括html、图片、js、后台访问地址，都是基于空contextPath的，如果自定义server.servlet.context-path参数，那么所有链接都404了
现有的链接，有/开头的绝对路径，又有错误的../../开头的路径，实在是很不规范，改起来也不方便

**Comment by nobodyiam** [comment]
see #2754
