### ISSUE TITLE
1.4.0版本启用缓存后新增配置项，客户端取不到

### ISSUE THREAD

**Issue by qtzheng** [ctripcorp/apollo#2774]
1.4.0版本启用缓存后新增配置项，客户端取不到值

**Comment by nobodyiam** [comment]
已知并没有这个问题，请先确认下使用方式和相关日志，如果确信有问题，麻烦提供下重现步骤

**Comment by qtzheng** [comment]
> 已知并没有这个问题，请先确认下使用方式和相关日志，如果确信有问题，麻烦提供下重现步骤

通过设置APOLLO_CACHEDIR环境变量开启本地缓存 ，服务器也开启了缓存

**Comment by nobodyiam** [comment]
> 顺便问一下springboot 应用yml中的配置是不是没法被Apollo中的配置替换

会被替换的，可以注入一个environment对象看下里面的propertysources，apollo的应该在最前面

**Comment by qtzheng** [comment]
> > 顺便问一下springboot 应用yml中的配置是不是没法被Apollo中的配置替换
> 
> 会被替换的，可以注入一个environment对象看下里面的propertysources，apollo的应该在最前面

`@FeignClient(name="test",utl="${test.url}")`
上面这段代码没法从配置中心取到test.url的值

**Comment by nobodyiam** [comment]
可以尝试一下sring boot接入方式和eagerLoad方式

**Comment by qtzheng** [comment]
新增的配置项客户端取不到，配置中心重启后客户端才能生效

**Comment by nobodyiam** [comment]
`新增的配置项客户端取不到，配置中心重启后客户端才能生效`是啥意思？提供下详细信息吧
