### ISSUE TITLE
namespace如何使用

### ISSUE THREAD

**Issue by zlingqu** [ctripcorp/apollo#2776]
项目A，有模块A1、A2，配置项
公共k=v 
A1私有：k1=v1 
A2私有：k2=v2

配置时有两种选择：
方案1、
appid=A，建三个namespace
    namespace=A0,public类型，有k=v
	namespace=A1,私有类型，关联A0
	namespace=A2，私有类型，关联A0

方案2：
appid=A0,并有namespace,public类型,名字使用一个特殊的名字，比如A0-public全局唯一，有k=v
appid=A1,并有namespace，私有类型，名字默认，关联A0的A0-public
appid=A2，并有namespace,私有类型，名字默认，关联A0的A0-public

应该选择哪个方案？

**Comment by nobodyiam** [comment]
建议先看下[Apollo核心概念之“Namespace”](https://github.com/ctripcorp/apollo/wiki/Apollo%E6%A0%B8%E5%BF%83%E6%A6%82%E5%BF%B5%E4%B9%8B%E2%80%9CNamespace%E2%80%9D)
