### ISSUE TITLE
单元测试中不能刷新@ConfigurationProperties修饰的类的值

### ISSUE THREAD

**Issue by Ahaochan** [ctripcorp/apollo#2780]
单元测试用例: [`L78`](https://github.com/Ahaochan/project/blob/70e6f1916630c8eb6858106392dadd98d171d7fd/ahao-spring-boot-apollo/src/test/java/moe/ahao/spring/boot/apollo/SpringIntegrationTest.java#L78)

下面是简化的代码加注释
```java
    @Test
    @DirtiesContext
    public void testConfigurationProperties() throws Exception {
        Assertions.assertEquals("root", dbProperties.username);
        Assertions.assertEquals("root", dbProperties.password);

        // 1. 修改 username 为 ahao, 监听到修改事件
        apollo.addOrModifyProperty("db", "username", "ahao");
        ConfigChangeEvent updateEvent1 = testBean.future.get(5000, TimeUnit.MILLISECONDS);
        Assertions.assertEquals("ahao", updateEvent1.getChange("username").getNewValue());
        // Thread.sleep(10000); // ConfigurationProperties 未能及时刷新, 即使 sleep等待事件消费 也不行
        // Assertions.assertEquals("ahao", dbProperties.username);

        // 2. 此时如果不走下面的代码, 另一个单元测试 testInject() 会检测到 username 已经改为 ahao

        // 3. 还原 username 为 root
        apollo.addOrModifyProperty("db", "username", "root");
        ConfigChangeEvent updateEvent2 = testBean.future.get(5000, TimeUnit.MILLISECONDS);
        Assertions.assertEquals("root", updateEvent2.getChange("username").getNewValue());
    }
```

这边是通过`EnvironmentChangeEvent`来刷新配置的, 在`web`环境下测试可用.
```java
    applicationContext.publishEvent(new EnvironmentChangeEvent(changeEvent.changedKeys()));
```
官方提供的单元测试例子里没有`ConfigurationProperties`相关的测试，还请帮忙解答一下，谢谢~

**Comment by nobodyiam** [comment]
这个是spring cloud的逻辑，看下相关源码？应该是 org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder ？

**Comment by Ahaochan** [comment]
感谢指引入口, 看了下`ConfigurationPropertiesRebinder`源码, 当事件触发的时候, 会去销毁所有`@ConfigurationProperties`修饰的类, 然后重新初始化.
```java
if (bean != null) {
    this.applicationContext.getAutowireCapableBeanFactory().destroyBean(bean);
    this.applicationContext.getAutowireCapableBeanFactory().initializeBean(bean, name);
    return true;
}
```

当`DBProperties`类在`web`环境运行时, 我们可以在`ConfigurationPropertiesRebinder`类里的`ConfigurationPropertiesBeans`对象的`beans`属性看到`DBProperties`这个`Bean`.
![image](https://user-images.githubusercontent.com/17980786/69510014-10c31780-0f76-11ea-889f-1b7e9d5c44d2.png)

但是当`DBProperties`类在`test`环境运行时, `beans`属性里却找不到`DBProperties`这个`Bean`.
事件确实有被消费掉, 只是因为没有`DBProperties`这个`Bean`, 所以导致`DBProperties`不能通过销毁再初始化, 来刷新里面的属性值.
![image](https://user-images.githubusercontent.com/17980786/69510034-289a9b80-0f76-11ea-9602-23bd2fff89b1.png)

当执行另一个单元测试`testInject()`时, 会重新初始化`DBProperties`, 所以里面的值就改变了.

现在卡住的点是, 为什么在`test`包里, `ConfigurationPropertiesBeans`就找不到`DBProperties`了?

-------------------------------------

玄学调试, 加了个`Starter.class`, 发现解决问题了.
```java
@ContextConfiguration(classes = {ApolloConfig.class, SpringIntegrationTest.TestConfiguration.class})
@ContextConfiguration(classes = {Starter.class, ApolloConfig.class, SpringIntegrationTest.TestConfiguration.class})
```
可以知道, 肯定又是`@SpringBootApplication`这个注解里面又做了什么操作.
依次排插, 发现只要加上`@EnableAutoConfiguration`就没问题, 没有加上`@EnableAutoConfiguration`就失败.

修复`commit`: [R34](https://github.com/Ahaochan/project/commit/b46ae9b0752d496aa6cd1eaaf04ca29f5586b25d#diff-a95496d19d9bf6d9fa4797b79f018f6aR34)
