### ISSUE TITLE
logback参数无法替换

### ISSUE THREAD

**Issue by lizhichao999** [ctripcorp/apollo#2781]
<?xml version="1.0" encoding="UTF-8"?>
<configuration scan="true" scanPeriod="60 seconds">

  <appender name="Console" class="ch.qos.logback.core.ConsoleAppender">
    <encoder>
      <pattern>%d %-4relative [%thread] %-5level %logger{35} [%X{traceId}]- %msg %n
      </pattern>
    </encoder>
  </appender>
	<appender name="APPENDER"
		class="ch.qos.logback.core.rolling.RollingFileAppender">
		<rollingPolicy
			class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
			
			<fileNamePattern>e:/data/logs/app-${server.port}-%d{yyyy-MM-dd}-%i.log</fileNamePattern>
			
			<maxHistory>${common.logback.maxHistory}</maxHistory>
      		
			<totalSizeCap>${common.logback.totalSizeCap}</totalSizeCap>
		    <maxFileSize>${common.logback.maxFileSize}</maxFileSize>
		    
		</rollingPolicy>
		<encoder>
			
			<pattern>%d %-4relative [%thread] %-5level %logger{35} [%X{traceId}]- %msg%n
			</pattern>
		</encoder>
	 </appender>
	
	<appender name="ERRORAPPENDER"
		class="ch.qos.logback.core.rolling.RollingFileAppender">
		<rollingPolicy
			class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
			
			<fileNamePattern>e:/data/logs/error/app-${server.port}-%d{yyyy-MM-dd}-%i.log</fileNamePattern>
			
			<maxHistory>${common.logback.maxHistory}</maxHistory>
      		
			<totalSizeCap>${common.logback.totalSizeCap}</totalSizeCap>
      		<maxFileSize>${common.logback.maxFileSize}</maxFileSize>
      
		</rollingPolicy>
		<encoder>
			
			<pattern>%d %-4relative [%thread] %-5level %logger{35} [%X{traceId}]- %msg%n
			</pattern>
		</encoder>
		<filter class="ch.qos.logback.classic.filter.LevelFilter"> 
           <level>ERROR</level>  
           <onMatch>ACCEPT</onMatch>  
           <onMismatch>DENY</onMismatch>  
        </filter>  
	</appender>

	  
    <logger name="com.hd.dc" additivity="false">  
        <level value="INFO" />   
        <appender-ref ref="APPENDER"/>  
        <appender-ref ref="ERRORAPPENDER"/>   
    </logger> 
        
     <root>  
        <level value="INFO" />
        <appender-ref ref="APPENDER" />  
        <appender-ref ref="ERRORAPPENDER"/> 
        <appender-ref ref="Console" />
    </root>
</configuration>

ERROR in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1321203216 - maxFileSize property is mandatory.
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:169)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithSpecificConfig(AbstractLoggingSystem.java:67)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:57)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:117)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:269)
	... 14 more

**Comment by nobodyiam** [comment]
参考一下 https://github.com/ctripcorp/apollo-use-cases/commit/08b49559da7be0ea8f269c6c40c7a2e38f295025
