### ISSUE TITLE
无法创建namespace的情况

### ISSUE THREAD

**Issue by gsralex** [ctripcorp/apollo#2783]
多个环境下，一个portal，存在对某个appid，无法创建namespace的情况

具体表现是，两个环境，一个dev，和一个fat
dev使用的数据库中的表Namespace无法插入默认的Application记录

**Comment by nobodyiam** [comment]
看下后台服务的日志

**Comment by gsralex** [comment]
后台adminservice日志已经正常。没有报错，且前台是可以创建成功项目的。

有两个环境，一个是fat，一个是dev。

fat可以正常insert Namespace表，dev无法insert。且只有这个项目名称会。

一开始只有dev，后来加入fat，这个项目在一开始有dev的时候就是存在的。后来删除应用就再也好不了了。

尝试过truncate dev和fat的configdb表。这个appid依然不行，但是创建其他appid的项目一切正常。

**Comment by gsralex** [comment]
![image](https://user-images.githubusercontent.com/2240270/69506785-12d3a900-0f6b-11ea-994e-ae5a6915567d.png)


dev的configservice提示这个：
com.ctrip.framework.apollo.common.exception.ServiceException: appnamespace not unique
2019-11-25 10:04:50.858 ERROR 960769 --- [http-nio-8090-exec-5] .c.f.a.c.c.GlobalDefaultExceptionHandler : app not found for appId coral

**Comment by nobodyiam** [comment]
点击补缺环境看下

**Comment by gsralex** [comment]
试过了，依然不会插入，而且只有一个特定名称的app.id才会。这个app.id早期只有dev环境，后面才加入test环境

**Comment by nobodyiam** [comment]
如果是后期新增了环境的话，要手动同步一下数据，可以参考[2.1.2.1 从别的环境导入ApolloConfigDB的项目数据](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#2121-%E4%BB%8E%E5%88%AB%E7%9A%84%E7%8E%AF%E5%A2%83%E5%AF%BC%E5%85%A5apolloconfigdb%E7%9A%84%E9%A1%B9%E7%9B%AE%E6%95%B0%E6%8D%AE)
