### ISSUE TITLE
能通过openapi删除namespace吗？

### ISSUE THREAD

**Issue by wolking** [ctripcorp/apollo#2785]
想通过openapi删除namespace，但看文档好像没提供，源码也没有

**Comment by nobodyiam** [comment]
目前没有这个功能

**Comment by wolking** [comment]
@nobodyiam 有计划提供这个功能吗？

**Comment by nobodyiam** [comment]
删除namespace是比较危险且少见的动作，所以建议还是用到到apollo界面上做操作
