### ISSUE TITLE
如何对openapi进行mock测试

### ISSUE THREAD

**Issue by dongzl** [ctripcorp/apollo#2786]
Apollo Team：

你们好，最近内部系统集成了apollo-opanapi，并通过一些方法实现对配置数据的更新。现在需要实现一些单元测试代码，进行CI集成测试，所以对于openapi目前又mock server的功能实现吗？

我阅读了wiki，目前的 apollo-mockserver 我理解是不是仅是针对 ConfigService的 mock 实现，没有对 openapi 进行 mock 支持，谢谢！

**Comment by nobodyiam** [comment]
通过mockito mock `ApolloOpenApiClient`对象即可
