### ISSUE TITLE
想请教下，SpringBoot 项目中 env,idc 有没有办法在 yaml 中配置

### ISSUE THREAD

**Issue by frank-lam** [ctripcorp/apollo#2788]
每个人本地还得配置 environment variables 中配置环境变量 env,idc，有没有办法可以直接在 yaml 中配置。尝试设置 System.setProperty 进行自定义设置，但是不知道 springboot 中需要在什么时机进行设置

**Comment by zjh-neverstop** [comment]
可以在server.properties文件中进行设置，`linux`系统在：`/opt/settings/server.properties`，`windows`系统在：`C:/opt/settings/server.properties`

或者可以查看源码 [DefaultServerProvider.java](https://github.com/ctripcorp/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/foundation/internals/provider/DefaultServerProvider.java)

**Comment by frank-lam** [comment]
@zjh-neverstop 看过源码了，通过配置在环境变量或者 C:/opt/settings/server.properties 中肯定是可以的。但是对于 SpringBoot 项目，本地调试还要去配置一个额外的东西，不能直接配置在 yaml 中，我觉得是不合适的。如果是在服务端部署，或者是通过 Docker 环境肯定可以的
