### ISSUE TITLE
apollo配置忽略健康检查未生效

### ISSUE THREAD

**Issue by songwenh** [ctripcorp/apollo#2791]
在Apollo里面配置忽略应用的redis健康检查，但是未生效，配置在应用bootstrap.yml里面就能生效。
配置apollo:
![image](https://user-images.githubusercontent.com/31386856/69594887-ac1cc100-1038-11ea-92b2-54777a388c44.png)
不生效
![image](https://user-images.githubusercontent.com/31386856/69594881-a8893a00-1038-11ea-8478-04ce36e01f9e.png)
配置bootstrap.yml:    ok.
![image](https://user-images.githubusercontent.com/31386856/69595036-4250e700-1039-11ea-9192-267f328ef35d.png)

**Comment by nobodyiam** [comment]
`apollo.bootstrap.eagerLoad.enabled=true`配置下看看？

**Comment by songwenh** [comment]
> `apollo.bootstrap.eagerLoad.enabled=true`配置下看看？
> 
> [https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C% 87％E5％8D％97＃3213-spring-boot％E9％9B％86％E6％88％90％E6％96％B9％E5％BC％8F％E6％8E％A8％E8％8D％90](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#3213-spring-boot%E9%9B%86%E6%88%90%E6%96%B9%E5%BC%8F%E6%8E%A8%E8%8D%90)

谢谢 @nobodyiam ，问题解决了，需要同时配置
     apollo.bootstrap.enabled = true
     apollo.bootstrap.eagerLoad.enabled = true
