### ISSUE TITLE
http监控

### ISSUE THREAD

**Issue by fanlingyin** [ctripcorp/apollo#2792]
想问一下，针对一个项目，我需要用到缓存，也需要写一个job不拉去缓存配置，定时访问config来监控config是否挂掉这样，支持配置吗

**Comment by nobodyiam** [comment]
没太看明白？你想知道config是否挂掉？这个可以访问config的`/health`接口

**Comment by fanlingyin** [comment]
我现在通过 apollo.metaServer+/configs/checkServer/default/application  自己定义了一个app 然后默认namespace中获取某个值，进行校验，是不是做复杂了
