### ISSUE TITLE
不得不吐槽一下

### ISSUE THREAD

**Issue by yangQingYu123** [ctripcorp/apollo#2793]
docker部署真的。。。

**Comment by nobodyiam** [comment]
开源共建，如果有体验不好的地方，大家可以一起来提建议和PR的~

**Comment by ygqygq2** [comment]
@nobodyiam 为什么不整合CI，自动打包成docker镜像。

**Comment by nobodyiam** [comment]
@ygqygq2 很好的建议，可以单开一个issue，把所希望达到的状态描述一下
