### ISSUE TITLE
[bug]当发布的ReleaseComment为空时,直接调用Matcher.quoteReplacement(releaseHistory.getReleaseComment())将会产生空指针异常

### ISSUE THREAD

**Issue by jiayaoO3O** [ctripcorp/apollo#2801]
https://github.com/ctripcorp/apollo/blob/0bc91cc11464b1a27ef5dd227615995cb8db00a1/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/component/emailbuilder/ConfigPublishEmailBuilder.java#L147
第147行当发布的ReleaseComment为空时,直接调用`Matcher.quoteReplacement(releaseHistory.getReleaseComment())`将会产生空指针异常,releaseHistory中其他的字段都不会为空,但是ReleaseComment是有可能为空的.

**Comment by nobodyiam** [comment]
有重现步骤吗？看已有的数据中release comment没有Null的情况

**Comment by jiayaoO3O** [comment]
调用集成的邮件服务,当代码跑到这个位置的时候,读取ReleaseComment,但是ReleaseComment这个值是可以不填的,所以导致release comment成为了null , 我用的是Oracle版本,不知道会不会有数据库方面的区别,如果MySQL版的确定不会因为没有ReleaseComment而导致空值产生,那可能是我这边的问题.

**Comment by nobodyiam** [comment]
目前来看从程序中写入的应该都是空值，而不是null，不过从程序严谨性来讲这里确实可以判断一下
