### ISSUE TITLE
同步配置的时候，不能同步删除的配置吗？

### ISSUE THREAD

**Issue by wujianbiao** [ctripcorp/apollo#2802]
删除配置的时候，一般会现在dev 环境删除，验证无误之后，想把 dev 的配置同步到其他环境。可是同步的时候发现，删除的配置无法同步，也就是说如果我想删除配置，需要在各个环境手动执行重复的删除行为。有更好的方式吗？

**Comment by nobodyiam** [comment]
目前没有更好的方式
