### ISSUE TITLE
当 AppId 叫 search 时会和搜索接口冲突

### ISSUE THREAD

**Issue by wcp1231** [ctripcorp/apollo#2803]
最近升级了新版 portal 的时候发现有个叫 search 的服务信息显示不正常，发现是获取 app 信息的时候和搜索接口冲突了。
查了一下提交记录，在 b4e0a62269a104c07d8edcbb74cfa40a2ca9bfa6 这个提交加上 search 接口，会导致获取 appid 为 search 的服务信息失败

**Comment by rrfeng** [comment]
@wcp PR 吧
