### ISSUE TITLE
apollo密码忘记

### ISSUE THREAD

**Issue by chenghongxi** [ctripcorp/apollo#2804]
想咨询个问题，我是通过脚本安装apollo，之后管理密码忘记。直接更改users表的password字段，重启后。  还是无法登录

**Comment by nobodyiam** [comment]
同时检查一下authorities表

**Comment by chenghongxi** [comment]
password字段更新成默认加密值，update无法更新。这个是被锁住了么？

**Comment by PostgreSQL1989** [comment]
> 同时检查一下authorities表

我们也遇到这个问题了，改了users表的密码也没有用，后来发现authorities表居然丢了apollo这个用户的数据，插入数据就行了

**Comment by nobodyiam** [comment]
authorities表是被人误删了吗？
