### ISSUE TITLE
迁移到Apollo后, Web管理后台页面响应特别慢

### ISSUE THREAD

**Issue by zitirich** [ctripcorp/apollo#2810]
项目中的管理后台服务率先进行尝试, 页面响应特别慢, 偶尔会超时; Pro环境是双configservice; 在同一个内网环境; 配置方面 @EnableApolloConfig 使用的 1个私有的application + N个公有的namespace; 另外, config-service.cache.enabled 设置成true 和 false 没有明显差异; 请问是哪里漏掉了吗, 盼回复?

**Comment by nobodyiam** [comment]
打开debug日志看下

**Comment by zitirich** [comment]
感谢回复, 
项目中引用了pagehelper, 相关配置未能生效, 分页失败导致部分页面异常卡顿;  
改写到原.yml文件中已经可以使用了, 问题已初步解决;
我先结贴了, 然后研究一下启动顺序, 回头Q群交流.
