### ISSUE TITLE
Springboot怎么在工具类中获取apollo配置

### ISSUE THREAD

**Issue by FFFro** [ctripcorp/apollo#2811]
使用各种方法都是null

**Comment by WERNERWAN1** [comment]
直接读取数据库数据。

**Comment by g5niusx** [comment]
可以參考一下[https://www.g5niusx.com/2019/03/apollo-2.html](获取配置)
```java
@Slf4j
public class Boot {
    public static void main(String[] args) throws InterruptedException {
        Config appConfig = ConfigService.getAppConfig();
        String property  = appConfig.getProperty("timeout", "");
        log.info("读取到配置:{}", property);
    }
}
```
上面的代码就实现了util获取代码

**Comment by FFFro** [comment]
> 可以參考一下[https://www.g5niusx.com/2019/03/apollo-2.html](%E8%8E%B7%E5%8F%96%E9%85%8D%E7%BD%AE)
> 
> ```java
> @Slf4j
> public class Boot {
>     public static void main(String[] args) throws InterruptedException {
>         Config appConfig = ConfigService.getAppConfig();
>         String property  = appConfig.getProperty("timeout", "");
>         log.info("读取到配置:{}", property);
>     }
> }
> ```
> 
> 上面的代码就实现了util获取代码

这样可以了，那如果需要动态刷新配置这个是不是就不能生效了

**Comment by sunshanpeng** [comment]
控制台修改配置发布后，重新从这个方法里面取到的配置就是最新的。

**Comment by g5niusx** [comment]
> > 可以參考一下[https://www.g5niusx.com/2019/03/apollo-2.html](%E8%8E%B7%E5%8F%96%E9%85%8D%E7%BD%AE)
> > ```java
> > @Slf4j
> > public class Boot {
> >     public static void main(String[] args) throws InterruptedException {
> >         Config appConfig = ConfigService.getAppConfig();
> >         String property  = appConfig.getProperty("timeout", "");
> >         log.info("读取到配置:{}", property);
> >     }
> > }
> > ```
> > 
> > 
> > 上面的代码就实现了util获取代码
> 
> 这样可以了，那如果需要动态刷新配置这个是不是就不能生效了

你可以给他增加监听事件，然后手动更新。
