### ISSUE TITLE
多环境配置，dev 修改参数，pro 中也被修改了？

### ISSUE THREAD

**Issue by WERNERWAN1** [ctripcorp/apollo#2812]
我的配置流程：构建库 ApolloConfigDB_dev 、ApolloConfigDB、ApolloPortalDB，根据build.bat 在windows 下打包。以下是打包时修改的命令：
@echo off

rem apollo config db info
set apollo_config_db_url="jdbc:mysql://10.10.22.187:3306/ApolloConfigDB_dev?characterEncoding=utf8"
set apollo_config_db_username="root"
set apollo_config_db_password="ysjr2016"

rem apollo portal db info
set apollo_portal_db_url="jdbc:mysql://10.10.22.187:3306/ApolloPortalDB?characterEncoding=utf8"
set apollo_portal_db_username="root"
set apollo_portal_db_password="ysjr2016"

rem meta server url, different environments should have different meta server addresses
set dev_meta="http://10.11.11.112:8803"
set pro_meta="http://10.10.22.174:8501"

set META_SERVERS_OPTS=-Ddev_meta=%dev_meta%  -Dpro_meta=%pro_meta%

rem =============== Please do not modify the following content =============== 
rem go to script directory
cd "%~dp0"

cd ..

rem package config-service and admin-service
echo "==== starting to build config-service and admin-service ===="

call mvn clean package -DskipTests -pl apollo-configservice,apollo-adminservice -am -Dapollo_profile=github -Dspring_datasource_url=%apollo_config_db_url% -Dspring_datasource_username=%apollo_config_db_username% -Dspring_datasource_password=%apollo_config_db_password%

echo "==== building config-service and admin-service finished ===="

echo "==== starting to build portal ===="

call mvn clean package -DskipTests -pl apollo-portal -am -Dapollo_profile=github,auth -Dspring_datasource_url=%apollo_portal_db_url% -Dspring_datasource_username=%apollo_portal_db_username% -Dspring_datasource_password=%apollo_portal_db_password% %META_SERVERS_OPTS%

echo "==== building portal finished ===="

pause

本地启动打包的apollo-adminservice-1.5.0-SNAPSHOT.jar   、apollo-configservice-1.5.0-SNAPSHOT.jar  在测试服务器上也启动过了apollo-admin、apollo-configservice、apollo-portal. 并修改了  ApolloPortalDB.ServerConfig 中的 apollo.portal.envs = DEV,PRO 。ApolloConfigDB_dev.ServerConfig 中的 eureka.service.url=http://10.10.22.174:8500 （我们用的注册中心是 consul）。ApolloConfigDB.ServerConfig 中的 eureka.service.url=http://10.10.22.174:8500 。

当在测试服务器上修改dev 下的配置项时，pro 下的配置项也修改了？？？？？？这是怎么回事呢？

**Comment by WERNERWAN1** [comment]
一直都是只写了一个库，就是之前的ApolloConfigDB。另外一个ApolloConfigDB_dev 一直没有被访问修改。是因为meta 配置的原因吗？

**Comment by ht-coder-wu** [comment]
我好像也遇到了这个问题，我没有在打包区分环境，而是在服务器建立了configService、configService_prod目录，使用相同的包，在application-github.properties  配置中配置不同的数据源，startup.sh中配置不同的端口，两个服务同时注册到现有eureka中，没有使用configService内置eureka，此时修改默认dev环境中配置，发布，prod环境中的配置同时被删除掉了。 暂时没解决

**Comment by ht-coder-wu** [comment]
如果我不统一注册到一个eureka中，每台configService 配置单独端口，使用内置eureka，没有这个问题
