### ISSUE TITLE
最新版本对mysql5.7.28不支持运行不起来

### ISSUE THREAD

**Issue by Stone2016** [ctripcorp/apollo#2815]
最新版本对mysql5.7.28不支持运行不起来
Caused by: org.hibernate.exception.SQLGrammarException: could not extract ResultSet

**Comment by nobodyiam** [comment]
apollo的demo环境使用的就是5.7.28，跑的是没问题的。建议再检查一下日志信息。

**Comment by Stone2016** [comment]
apollo配置中心支持数据源的热更新吗？

**Comment by nobodyiam** [comment]
目前apollo自身还没有支持数据源的热更新，因为数据库配置是静态传入的
