### ISSUE TITLE
多环境portal一直启动不起来

### ISSUE THREAD

**Issue by xuejian0811** [ctripcorp/apollo#2818]
![image](https://user-images.githubusercontent.com/30763922/70215941-8e0e3980-1779-11ea-9f8d-25f058805a42.png)

**Comment by xuejian0811** [comment]
直接下载的 .zip的包   不支持自定义多环境吗？必须要修改源码吗

**Comment by JaredTan95** [comment]
> 直接下载的 .zip的包 不支持自定义多环境吗？必须要修改源码吗

是的。

**Comment by WERNERWAN1** [comment]
通过集群来实现了单个appId, 不同环境不同配置。

**Comment by xuejian0811** [comment]
> > 直接下载的 .zip的包 不支持自定义多环境吗？必须要修改源码吗
> 
> 目前支持的环境应该满足你的需求了，具体可以看看这里。[1.3、环境](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#13%E7%8E%AF%E5%A2%83)

好的  多谢
