### ISSUE TITLE
长轮询+定时轮询的疑惑

### ISSUE THREAD

**Issue by junjun-yang** [ctripcorp/apollo#2821]
我看Apollo源码时对此处有点疑惑，长轮询收到通知后就会去请求一次配置更新接口，逻辑上来讲这样已经可以保证配置的及时发现了，为什么还要加上定时轮询？

目前网上收集到的有两种解释，但说服力都不是很强。
1、定时轮询是一种fallback机制，防止长轮询失效（什么情况下长轮询会失效？）
2、长轮询的作用是实时感知配置变更，定时轮询是保证服务最终一致性（长轮询接收到通知之后就会请求一次配置更新接口，为什么保证不了一致性？）

**Comment by wkcaeser** [comment]
长轮询失效很常见呀。  比如网络波动就有可能导致连接实际断开了，但是客户端根本就没感觉呀。 本地开发的时候还遇到一种情况，长轮询一直都没成功过，或者很容易就断了，这时候就完全依赖于定时轮询了，但是这种情况的原因目前不知道是为啥

**Comment by junjun-yang** [comment]
这种网络波动导致的连接断开，超过指定超时时间后客户端会主动进行下一次长轮询，配置也能得到更新。
你说的后一种长轮询一直没成功或者很容易断开的情况倒是没遇到过

**Comment by lhl4546** [comment]
> 长轮询失效很常见呀。 比如网络波动就有可能导致连接实际断开了，但是客户端根本就没感觉呀。 本地开发的时候还遇到一种情况，长轮询一直都没成功过，或者很容易就断了，这时候就完全依赖于定时轮询了，但是这种情况的原因目前不知道是为啥

回答有些牵强，长链接失效有两种情况，一种是网络短暂波动，这种情况靠心跳检测就能修复，另一种是网络长期故障，这种你即使用定时轮询也没用。使用长链接+定时轮询可能只有作者才知道为什么这么使用

**Comment by wkcaeser** [comment]
> > 长轮询失效很常见呀。 比如网络波动就有可能导致连接实际断开了，但是客户端根本就没感觉呀。 本地开发的时候还遇到一种情况，长轮询一直都没成功过，或者很容易就断了，这时候就完全依赖于定时轮询了，但是这种情况的原因目前不知道是为啥
> 
> 回答有些牵强，长链接失效有两种情况，一种是网络短暂波动，这种情况靠心跳检测就能修复，另一种是网络长期故障，这种你即使用定时轮询也没用。使用长链接+定时轮询可能只有作者才知道为什么这么使用

你仔细看提的问题呀，问的是为啥要加长轮询    网络波动导致长轮询失效，心跳检测可以修复，现在没有心跳检测，所以用定时轮询来兜底   我是这么理解的

**Comment by skay0424** [comment]
借口，我有个地方不解，定时拉取是大于最大id的500条数据，为什么是大于最大id呀，这样会不会存在小于这个id的同步不到的情况呀

**Comment by zouyx** [comment]
@wkcaeser @lhl4546 可以参考下该 issue https://github.com/zouyx/agollo/issues/10 ，是不是你们一直想找的答案。
