### ISSUE TITLE
修改配置项时无法提交

### ISSUE THREAD

**Issue by haoyu36** [ctripcorp/apollo#2823]
在修改配置后，提交按钮是灰色的，无法提交

**Comment by nobodyiam** [comment]
麻烦提供下重现步骤

**Comment by haoyu36** [comment]
找到原因了，通过 openapi 修改的注释太长，超过64个字符了。然后在面板打开时提交按钮是灰色的，这时是没有提醒的

**Comment by haoyu36** [comment]
请问能不能通过修改数据库配置自定义字符数

**Comment by nobodyiam** [comment]
fixed by #2849
