### ISSUE TITLE
如何使用master代码打包编译成jar并部署k8s

### ISSUE THREAD

**Issue by ChuckyThh** [ctripcorp/apollo#2824]
我很高兴看到apollo portal支持基于path的反向代理 #2754，因为我们正需要此功能，但是这个功能还没有作为release版本发布，所以我们在尝试下载master的代码自己编译打包，但是打出来的包部署到k8s上会报以下错误

$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Failed to determine a suitable driver class
2019-12-06 17:08:17.148  INFO 45 --- [main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2019-12-06 17:08:17.233  WARN 45 --- [main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
2019-12-06 17:08:17.292  INFO 45 --- [main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-12-06 17:08:17.322 ERROR 45 --- [main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class

Action:

Consider the following:
        If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
        If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

无法读到application-github.properties上的配置，关于application-github.properties配置，我们按照的是apollo-on-kubernetes中ConfigMap做配置的，并且我们使用apollo1.5.1release的版本的jar是可以运行的。

我的问题是：我们使用master上的源代码打包是可行的吗？如果可行，打包是需要什么操作，或者需要修改哪一处？

**Comment by ChuckyThh** [comment]
@nobodyiam

**Comment by nobodyiam** [comment]
参考[2.2.2 通过源码构建](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#222-%E9%80%9A%E8%BF%87%E6%BA%90%E7%A0%81%E6%9E%84%E5%BB%BA)

**Comment by ChuckyThh** [comment]
问题解决，启动时添加-Dapollo_profile=github,auth -DprefixPath=/apollo -Dserver.servlet.context-path=/apollo参数

我是用Idea编译的，-Dapollo_profile=github,auth必须添加，否则会出现#2142 Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.这样的报错
