### ISSUE TITLE
@ConfigurationProperties目前无法自动更新的问题

### ISSUE THREAD

**Issue by luoluo001** [ctripcorp/apollo#2825]
您好大佬：
      这里有个疑问当前版本的@ConfigurationProperties这种形式没法自动更新，必须通过调用RefreshScope来完成自动刷新，但实际上@Value这个自动更新是apollo.autoUpdateInjectedSpringProperties这个配置来决定的。
     我的疑惑在于，@ConfigurationProperties 是通过监听某些namespace来完成回调再手动调用RefreshScope 的refresh 或者refreshAll来完成刷新。这个设计是为了定制化刷新的考虑吗。如果我本身通过代码来获取@ConfigurationProperties的preffix+key ,构建SpringValue对象并添加到springValueRegistry，之后刷新统一交由apollo.autoUpdateInjectedSpringProperties这个配置会不会有什么问题。

**Comment by nobodyiam** [comment]
理论上似乎可以，可以尝试实现一下

**Comment by luoluo001** [comment]
谢谢解答！  这边已完成了

**Comment by luoluo001** [comment]
以下是我的实现，设计的会有点粗糙：  使用ApolloConfigPropProcessor 去继承ApolloProcessor 实现BeanFactoryAware。重写postProcessBeforeInitialization方法，第1部分是获取bean上的注解@ConfigurationProperties，如果存在则获取前缀，然后利用findAllField获取所有filed遍历调用processField，这里的processField是重新定义的多了一个preffic，定义 protected abstract void processField(Object bean, String beanName, Field field,String preffic);这个是主要的实现逻辑。第2部分是@Configuration这种bean需要获取方法，判断方法上是否存在@Bean同时@ConfigurationProperties 如果存在则方法就是需要处理的方法，然后获取到对应的方法名对应的bean。调用processMethod（子类重写），通过传入的返回bean与对应的信息调用字段的处理逻辑完成处理。最后将该处理通过ConfigPropertySourcesProcessor和ApolloConfigRegistrar完成注册。不知道这样实现是否有什么弊端，如有的话烦请大佬指点哈。

`package com.ctrip.framework.apollo.spring.annotation;

import org.springframework.aop.framework.AdvisedSupport;
import org.springframework.aop.framework.AopProxy;
import org.springframework.aop.support.AopUtils;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.BeanFactory;
import org.springframework.beans.factory.BeanFactoryAware;
import org.springframework.beans.factory.config.BeanPostProcessor;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.Ordered;
import org.springframework.core.PriorityOrdered;
import org.springframework.util.ClassUtils;
import org.springframework.util.ReflectionUtils;
import org.springframework.util.StringUtils;

import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.lang.reflect.Proxy;
import java.util.LinkedList;
import java.util.List;
import java.util.Optional;

/**
 * Created by：luo
 * date: 2019/12/6.
 * desc：
 */
public abstract class ApolloConfigPropProcessor extends ApolloProcessor implements BeanFactoryAware{
    private BeanFactory beanFactory;

    /**
     * 无论怎么处理都需要把原始bean返回了
     * @param bean
     * @param beanName
     * @return
     * @throws BeansException
     */
    @Override
    public Object postProcessBeforeInitialization(Object bean, String beanName) throws BeansException {
        //当前涉及到只有configuration 和直接在类上使用@Configuraiton两种形式使用到@ConfigrationProperties
        //需要判定这个bean是啥，如果是@Configuration 需要判定方法，是否存在注解，如果是本身有则处理所有的字段即可
        ConfigurationProperties annotation = bean.getClass().getAnnotation(ConfigurationProperties.class);
        if(annotation!=null){
            for (Field field : findAllField(bean.getClass())) {
                String preffic = annotation.value();
                if(com.ctrip.framework.apollo.core.utils.StringUtils.isBlank(preffic)){
                    preffic = annotation.prefix();
                }
                processField(bean, beanName, field,preffic);
            }
        }

        if (!(ClassUtils.isCglibProxyClass(bean.getClass())||Proxy.isProxyClass(bean.getClass()))) {
            return bean;//不是代理对象
        }

        Class<?> beanOriginClazz = null;
        try {
            if(AopUtils.isJdkDynamicProxy(bean)) {
                beanOriginClazz = getJdkDynamicProxyTargetObject(bean);
            } else { //cglib
                beanOriginClazz =  getCglibProxyTargetObject(bean);
            }
        }catch (Exception e){
            e.printStackTrace();
        }
       if(beanOriginClazz!=null){
//           Configuration configuration = bean.getClass().getDeclaredAnnotation(Configuration.class);
           Configuration conf = beanOriginClazz.getDeclaredAnnotation(Configuration.class);
           if(conf!=null){
               for(Method method:findAllMethod(beanOriginClazz)){
                   Object returnBean = beanFactory.getBean(method.getName());
                   processMethod(returnBean,method.getName(),method);
               }
           }
       }
        return bean;
    }


    private List<Method> findAllMethod(Class clazz) {
        final List<Method> res = new LinkedList<>();
        ReflectionUtils.doWithMethods(clazz, new ReflectionUtils.MethodCallback() {
            @Override
            public void doWith(Method method) throws IllegalArgumentException, IllegalAccessException {
                //过滤袋bean与ConfigurationProp同时两个注解的方法才需要处理
                Bean annotation = method.getAnnotation(Bean.class);
                if(annotation==null){
                    return;
                }
                ConfigurationProperties cp = method.getAnnotation(ConfigurationProperties.class);
                if(cp==null){
                    return;
                }
                res.add(method);
            }
        });
        return res;
    }

    @Override
    protected void processField(Object bean, String beanName, Field field) {
        //不用这两个方法了，重置一个新的方法主要逻辑在processField里面
    }

    /**
     *
     * @param bean
     * @param beanName
     * @param field
     * @param preffic ConfigurationProp 里面的前缀
     */
    protected abstract void processField(Object bean, String beanName, Field field,String preffic);

    /**
     * 实际上@Configuration需要的是当前方法返回值的这个bean
     * @param beanFactory
     * @throws BeansException
     */
    @Override
    public void setBeanFactory(BeanFactory beanFactory) throws BeansException {
        this.beanFactory = beanFactory;
    }

    public BeanFactory getBeanFactory() {
        return beanFactory;
    }


    private static Class getCglibProxyTargetObject(Object proxy) throws Exception {
        String className = proxy.getClass().getName().split("\\$\\$")[0];
        Class<?> clazz = Class.forName(className);
        return clazz;
    }


    private Class getJdkDynamicProxyTargetObject(Object proxy) throws Exception {
        Field h = proxy.getClass().getSuperclass().getDeclaredField("h");
        h.setAccessible(true);
        AopProxy aopProxy = (AopProxy) h.get(proxy);

        Field advised = aopProxy.getClass().getDeclaredField("advised");
        advised.setAccessible(true);

        Object target = ((AdvisedSupport)advised.get(aopProxy)).getTargetSource().getTarget();

        return target.getClass();
    }
}
`

`package com.ctrip.framework.apollo.spring.annotation;

import com.ctrip.framework.apollo.spring.property.SpringValue;
import com.ctrip.framework.apollo.spring.property.SpringValueRegistry;
import com.ctrip.framework.apollo.spring.util.SpringInjector;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.BeanFactory;
import org.springframework.beans.factory.BeanFactoryAware;
import org.springframework.boot.context.properties.ConfigurationProperties;

import java.lang.reflect.Field;
import java.lang.reflect.Method;

/**
 * Created by：luo
 * date: 2019/12/6.
 * desc：
 */
public class ConfigurationPoopProcessor extends ApolloConfigPropProcessor{

    private final SpringValueRegistry springValueRegistry;
    public ConfigurationPoopProcessor(){
        springValueRegistry = SpringInjector.getInstance(SpringValueRegistry.class);
    }

    @Override
    protected void processField(Object bean, String beanName, Field field, String preffic) {
        String placeholder = "${" + preffic + "." +field.getName()+ "}";
        SpringValue springValue = new SpringValue(preffic + "." +field.getName(), placeholder, bean, beanName, field, false);
        springValueRegistry.register(getBeanFactory(), preffic + "." +field.getName(), springValue);
    }

    @Override
    protected void processMethod(Object bean, String beanName, Method method) {
        ConfigurationProperties annotation = method.getAnnotation(ConfigurationProperties.class);
        String preffic = annotation.value();
        if(com.ctrip.framework.apollo.core.utils.StringUtils.isBlank(preffic)){
            preffic = annotation.prefix();
        }
        for (Field field : findAllField(bean.getClass())) {
            processField(bean, beanName, field,preffic);
        }
    }
}
`

**Comment by nobodyiam** [comment]
建议对各种场景都做一下完整测试，比如map, list等，参考

https://github.com/ctripcorp/apollo/blob/master/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/spring/springBootDemo/config/SampleRedisConfig.java

**Comment by luoluo001** [comment]
> 建议对各种场景都做一下完整测试，比如map, list等，参考
> 
> https://github.com/ctripcorp/apollo/blob/master/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/spring/springBootDemo/config/SampleRedisConfig.java

好的，这个确实没考虑到 谢谢大佬！

**Comment by luoluo001** [comment]
谢谢 这边仿造SpringValueRegister和SpringValue ，写了SpringConfPropRegister和SpringConfValue。主要代码在Propcessor那边将获取到的存在ConfigurationProperties，注册到SpringConfPropRegister,然后再AutoUpdateConfigChangeListener 添加SpringConfValue完成更新，其中更新机制利用ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization手动去刷新配置。这边测试看了下特殊的也都可以完成刷新。
