### ISSUE TITLE
Config Service和Admin Service如何实现双活

### ISSUE THREAD

**Issue by lizhichao999** [ctripcorp/apollo#2831]
Config Service和Admin Service如何实现双活

**Comment by nobodyiam** [comment]
参考一下[Apollo配置中心设计](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1)和[Apollo配置中心架构剖析](https://mp.weixin.qq.com/s/-hUaQPzfsl9Lm3IqQW3VDQ)
