### ISSUE TITLE
namespace.lock.switch关闭之后，个别ns会出现发布失败的问题

### ISSUE THREAD

**Issue by hays2hong** [ctripcorp/apollo#2837]
用的比较老的版本0.9，但是我看最新版本貌似还是有这个问题，com.ctrip.framework.apollo.biz.service.ReleaseService#checkLock方法没有校验目前namespace.lock.switch是否开启，所以如果开关关闭之前namespaceLock有记录的话，会导致发布失败，提示"Config can not be published by yourself."

**Comment by nobodyiam** [comment]
如果直接跳过检查的话，lock数据还在，下次打开namespace.lock.switch会出现更诡异的问题，所以可以考虑下关闭switch时把lock相关数据都清除掉

**Comment by hays2hong** [comment]
关闭switch时，自动触发清理数据应该是可以的吧？

**Comment by hays2hong** [comment]
另外还是没有理解会出现什么诡异问题，只有在关闭的情况下跳过checkLock，打开的情况下跟现状是一致的吧

**Comment by nobodyiam** [comment]
诡异的问题是指在关闭后，该namespace又经过了多次修改和发布，再次打开的时候就会提示一个之前的lock信息
