### ISSUE TITLE
docker客户端应用 获取ip的问题

### ISSUE THREAD

**Issue by ywf4026** [ctripcorp/apollo#2838]
我的应用是docker bridge方式部署的，在apollo后台的实例列表里显示该应用的ip是172.17.0.2, 是docker容器的ip，而不是主机的ip。这个问题该怎么解决，谢谢了！

![image](https://user-images.githubusercontent.com/3722641/70698965-5cf6b180-1d03-11ea-941e-f7e3f2b0e143.png)

**Comment by nobodyiam** [comment]
可以看下 com.ctrip.framework.foundation.internals.NetworkInterfaceManager 的逻辑
