### ISSUE TITLE
apllo 为什么不支持实时刷新端口

### ISSUE THREAD

**Issue by chenchenggen007** [ctripcorp/apollo#2842]
- [ ] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) of this repository and believe that this is not a duplicate.

**Describe the bug**

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

### Additional Details & Logs

- Version
- Error logs
- Configuration
- Platform and Operating System

**Comment by nobodyiam** [comment]
请详细描述下你的问题

**Comment by chenchenggen007** [comment]
我每次修改配置文件，springboot 应用都要重启，不然不生效，比如我server.port=8080改成8081 ，应用程序端口号没改过来。必须重启服务。感觉apollo热更新是假的

**Comment by nobodyiam** [comment]
建议参考一下 https://github.com/ctripcorp/apollo-use-cases

apollo能确保配置的值实时更新，对于一些有初始化逻辑的场景是需要程序自己监听配置变化事件并做处理的，比如server.port。

**Comment by liquanjin** [comment]
请问参数热更新，是否支持更新为null。
比如：  策略的配置，仅仅在A、Btest或指定的时间内需要。如果不要改配置了，是否支持删除apollo中对应的配置项，然后对应Bean中的属性都变成null？

目标测试下来结果不支持。即使通过 ConfigChangeEvent 的方式也不行

**Comment by nobodyiam** [comment]
apollo是支持删除配置的，你指的bean中的属性是通过spring注入的吧，这个要看你spring注入的placeholder怎么写了
