### ISSUE TITLE
为啥不同的环境，配置是一样的？

### ISSUE THREAD

**Issue by nangergong** [ctripcorp/apollo#2845]
我配置了两个环境，一个DEV，一个PRO
发现两个环境的配置是一样的
也就是如果我在DEV下修改了某个key的值
PRO环境下那个key的值同步变化
怎么回事？
我在apollo客户端的apollo-env.properties的配置如下
dev.meta=http://192.168.0.8:8082
pro.meta=http://192.168.0.8:8082

是因为两个环境共享一个meta服务的原因吗？
难道同一个meta服务被两个环境共享的话不能环境隔离？

**Comment by ywf4026** [comment]
是用同一个数据库吧？要不同环境不同数据库的

**Comment by nangergong** [comment]
> 是用同一个数据库吧？要不同环境不同数据库的

为什么不能共享同一个数据库呢？
