### ISSUE TITLE
请教个配置动态刷新问题

### ISSUE THREAD

**Issue by ywf4026** [ctripcorp/apollo#2846]
我看springcloud的配置中心使用refreshScope动态刷新代码(org.springframework.cloud.context.refresh.ContextRefresher#refresh)，它在refreshAll之前会有一个EnvironmentChangeEvent事件发出，如下图:
![image](https://user-images.githubusercontent.com/3722641/70958379-0814bb80-20b4-11ea-83bd-26d22019ef78.png)

但在Apollo的文档给出的例子里，只需要refresh就行，如下图：
![image](https://user-images.githubusercontent.com/3722641/70958550-9426e300-20b4-11ea-8a1d-de355486e219.png)

请问下，这个EnvironmentChangeEvent事件需要发出吗？如果是的话，在源码哪里写着呢?

谢谢指教了！

**Comment by nobodyiam** [comment]
EnvironmentChangeEvent可以用来刷新ConfigurationProperties，是不是需要发出可以按照自己的实际情况来选择的

**Comment by ywf4026** [comment]
> EnvironmentChangeEvent可以用来刷新ConfigurationProperties，是不是需要发出可以按照自己的实际情况来选择的

谢谢！我有个疑惑是：示例中，在refresh前并没有发出EnvironmentChangeEvent，可是ConfigurationProperties刷新成最新的，按理讲应该不会是最新的才对。是Apollo有做特殊处理吗？

**Comment by nobodyiam** [comment]
两种方式选其一即可
