### ISSUE TITLE
如何以模糊的方式读取一些配置？

### ISSUE THREAD

**Issue by julyzz** [ctripcorp/apollo#2848]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nobodyiam** [comment]
请详细地描述一下问题

**Comment by julyzz** [comment]
项目中定义了多个配置，配置项的名称都有共同的前缀（如：log.mask.keys.A,log.mask.keys.B...）；是否有方法可以一次性将这些相同前缀的配置项获取到？

**Comment by nobodyiam** [comment]
可以用`@ConfigurationProperties`
