### ISSUE TITLE
Apollo部署到k8s中， 我开发本地测试环境怎么连接部署到k8s中的Apollo？

### ISSUE THREAD

**Issue by xiaoyaolaotou** [ctripcorp/apollo#2853]
Apollo部署到k8s中， 我开发本地测试环境怎么连接部署到k8s中的Apollo？ 我configserver是通过ingress域名的方式到外面， 我开发本地测试环境怎么连接apollo？

**Comment by nobodyiam** [comment]
可以参考下面的做法

> 如果Apollo部署在公有云上，本地开发环境无法连接，但又需要做开发测试的话，客户端可以升级到0.11.0版本及以上，然后通过-Dapollo.configService=http://config-service的公网IP:端口 来跳过meta service的服务发现

https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#14%E7%BD%91%E7%BB%9C%E7%AD%96%E7%95%A5

**Comment by xiaoyaolaotou** [comment]
已成功连接, 多谢!

**Comment by lifh1234** [comment]
请问是怎么处理的，我也是ingress，设置了-Dapollo.configService 仍然不行，请问还需要做什么处理呢
备注：我ingress域名是可以访问的，如下：
curl http://apollo.config.com/dev
[
  {
    "appName": "apollo-configservice",
    "instanceId": "apollo-configservice:http://apollo.config.com/dev",
    "homepageUrl": "http://apollo.config.com/dev"
  },
  {
    "appName": "apollo-adminservice",
    "instanceId": "apollo-adminservice:http://apollo-service-dev-apollo-adminservice.sre:8090",
    "homepageUrl": "http://apollo-service-dev-apollo-adminservice.sre:8090"
  }
]

**Comment by lifh1234** [comment]
我的启动配置如下：
-Denv=dev -Dapp.id=test1 -Dapollo.configService=http://apollo.config.com/dev -Dapollo.bootstrap.namespaces=application

springcloud的配置文件：bootstrap.yml，配置如下
apollo:
  bootstrap:
    enable: true
  meta: http://apollo.config.com/dev

启动的一直报错：
Load Apollo Config failed - appId: test1, cluster: default, namespace: application, url: http://apollo.config.com/dev/configs/test1/default/application?ip=192.168.245.1 [Cause: Could not complete get operation [Cause: Can't connect to SOCKS proxy:connect timed out]]

而我在浏览器访问：http://apollo.config.com/dev/configs/test1/default/application?ip=192.168.245.1 是有数据返回的，如下：
{
  "appId": "test1",
  "cluster": "default",
  "namespaceName": "application",
  "configurations": {
    "config3.name": "config3.nameconfig3.nameconfig3.nameconfig3.name"
  },
  "releaseKey": "20210126171407-bdad958a15471cd0"
}
