### ISSUE TITLE
apollo 所有配置项能够支持在线导入导出吗？

### ISSUE THREAD

**Issue by LifeiLABoat** [ctripcorp/apollo#2854]
1、研发环境与生产环境网络不通，因此在生产环境发布时所有配置项需要从零配置。
2、如果有导入导出功能，那么就可以直接在生产环境发布时一键引入，神清气爽！

**Comment by nobodyiam** [comment]
1. 可以用文本模式来实现导入和导出
2. 可以通过open api来实现导入和导出
3. 可以调用portal的导入导出接口，#1767

**Comment by LifeiLABoat** [comment]
最新版的apollo 有这个界面直接进行操作吗？还是要自己调用接口实现？

**Comment by nobodyiam** [comment]
1是有界面操作的。

**Comment by LifeiLABoat** [comment]
Thanks
