### ISSUE TITLE
撤销操作

### ISSUE THREAD

**Issue by Ivony** [ctripcorp/apollo#2856]
简单说，我们需要一个功能可以简单的撤销目前命名空间的一个或者多个**尚未提交的**配置变更。

已经提交的变更可以通过回滚来实现，但是尚未提交的修改撤销却非常繁琐。

其实这个事情并没有那么复杂，因为没有这个功能的时候，我们是通过查询当前已经提交的值并且将值重新设置为当前提交的值来实现的。我们只需要一个功能可以简化这个查看已提交的值，复制，修改，粘贴，确认这一系列的操作。

如果撤销可能存在麻烦的问题，那么这一系列的操作也会存在，这两者效果是一样的。

所以不理解为什么没有撤销。

**Comment by nisiyong** [comment]
#2595 同样的需求
