### ISSUE TITLE
查看当前已提交的值

### ISSUE THREAD

**Issue by Ivony** [ctripcorp/apollo#2857]
当我们对很多配置做出了更改而尚未提交的时候，有时候我们会想知道当前程序获取到的配置到底是什么？例如紧急的插入了一个Bug的报告。所以我们需要一个视图，显示尚未提交的原始值长啥样（或者说当前程序获取到的值是什么），而不是显示我正在修改而尚未提交的值。

**Comment by nobodyiam** [comment]
这个功能是有的

![image](https://user-images.githubusercontent.com/837658/71318780-61c02000-24d0-11ea-9460-a4ceae592b2b.png)

**Comment by Ivony** [comment]
有没有想过当有几十个配置被修改的时候，目前的这个交互并没有解决问题？

如果有一个视图切换的按钮，切换修改值和提交值的显示多好？

**Comment by nobodyiam** [comment]
如果要看完整的已发布的值，可以到发布历史查看
