### ISSUE TITLE
批量回滚

### ISSUE THREAD

**Issue by Ivony** [ctripcorp/apollo#2858]
有时候我们并不想回滚到上一个版本，而是上上一个，或者上上上一个，或者我们知道某个日期之前的正常的，回滚到那个日期之前的版本。

当然，我们可以通过不断地点击回滚按钮来实现，但实际上，我们并不知道当前已经回滚到了哪一个版本。在多次回滚的操作中也非常容易出现错误，或者使程序获取到错误的配置。也给操作日志带来大量的垃圾日志。

能否提供一个列表让我们选择回滚到哪一个具体的版本？

**Comment by nobodyiam** [comment]
可以尝试在发布历史中提供一个`回滚到此版本`的按钮
