### ISSUE TITLE
部分回滚

### ISSUE THREAD

**Issue by Ivony** [ctripcorp/apollo#2859]
有时候我们提交了大量的配置变更，结果发现有少数几个需要在未来变更的配置也一并提交了。回滚操作会将所有的配置一次性全部回滚，这带来了非常大的困扰。

当然，我们也可以通过手动将错误变更的配置改回来然后在提交。但显然人的操作是容易出现错误的，更何况在一大堆配置变更的记录中找到我们所要回滚的配置之前的值是非常考验眼力的事情。

**Comment by nobodyiam** [comment]
回滚动作一般都是在紧急时刻操作的，不建议在这个步骤上增加复杂的功能。

可以考虑对生产环境打开`namespace.lock.switch - 一次发布只能有一个人修改开关，用于发布审核`，从而确保每次有两个人参与配置的修改和发布，以减少错误提交配置的可能性。

**Comment by Ivony** [comment]
我得承认这个说法是有道理的，回滚的确不应该成为日常的操作，如果回滚的步骤或者实现过于复杂，的确会使得紧急回滚的时候造成误操作。
