### ISSUE TITLE
嵌套配置热更新的问题

### ISSUE THREAD

**Issue by spenxu** [ctripcorp/apollo#2862]
对于嵌套的配置，似乎无法热更新，是设计的时候没考虑到还是因为某些因素没做？
比如我修改了ff.gg并且发布了，属性name的值似乎不会变更。
![image](https://user-images.githubusercontent.com/29301435/71338603-80cfb800-258b-11ea-8c98-66b04ee1563a.png)

![image](https://user-images.githubusercontent.com/29301435/71338618-8f1dd400-258b-11ea-9bac-e64a77f6cd97.png)

**Comment by nobodyiam** [comment]
可以看下 #972 的说明，目前对嵌套是提供了有限的支持

![image](https://user-images.githubusercontent.com/837658/71387522-40c21100-262f-11ea-906f-f3bdfd90a7a9.png)

**Comment by spenxu** [comment]
> 可以看下 #972 的说明，目前对嵌套是提供了有限的支持
> 
> ![image](https://user-images.githubusercontent.com/837658/71387522-40c21100-262f-11ea-906f-f3bdfd90a7a9.png)

所以图中的第三点只变更normalChange 目前还是不支持是吗？

**Comment by spenxu** [comment]
> > 可以看下 #972 的说明，目前对嵌套是提供了有限的支持
> > ![image](https://user-images.githubusercontent.com/837658/71387522-40c21100-262f-11ea-906f-f3bdfd90a7a9.png)
> 
> 所以图中的第三点只变更normalChange 目前还是不支持是吗？

另外，其实第二点所谓的嵌套解析出来的形式还是 batch => Field,所以变更batch 肯定不会存在问题。

**Comment by nobodyiam** [comment]
是的，目前支持的是一层嵌套
