### ISSUE TITLE
Portal 1.6.0 404 of @GetMapping("/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces")

### ISSUE THREAD

**Issue by Anilople** [ctripcorp/apollo#2863]
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) of this repository and believe that this is not a duplicate.

**Describe the bug**
Suppose that my 
app-id is `dynamic`, 
env is `DEV`, 
cluster is `default`, 
namespace is `application`

For the method `findNamespaces` in class `com.ctrip.framework.apollo.portal.controller.NamespaceController`.
the get url is `/apps/dynamic/clusters/default/namespaces/application/items/deleted`
It is ok for `apollo-1.5.1`, return like follow:
```json
[
	{
		"baseInfo": {
			"id": 1,
			"appId": "dynamic",
			"clusterName": "default",
			"namespaceName": "application",
			"dataChangeCreatedBy": "apollo",
			"dataChangeLastModifiedBy": "apollo",
			"dataChangeCreatedTime": "2019-12-23T20:17:27.000+0800",
			"dataChangeLastModifiedTime": "2019-12-23T20:17:27.000+0800"
		},
		"itemModifiedCnt": 0,
		"items": [],
		"format": "properties",
		"isPublic": false,
		"parentAppId": "dynamic",
		"comment": "default app namespace",
		"isConfigHidden": false
	}
]
```
But in `apollo-1.6.0` (newest master branch)
There is some problem return.
```json
{
	"exception": "com.ctrip.framework.apollo.common.exception.NotFoundException",
	"message": "item not found for dynamic default application deleted",
	"status": 404,
	"timestamp": "2019-12-23T21:20:21.107"
}
```

The config service and admin service are same when the portal running.
portal 1.5.1 and portal 1.5.0 are running in the same machine(Win 10), the difference between them is the `server.port`.

**To Reproduce**
Just run `apollo-portal 1.6.0` newest on master branch

The problem in `apollo-1.6.0` cause the web ui cannot use.

**Expected behavior**

**Screenshots**

### Additional Details & Logs

- Version 1.6.0
- Error logs `org.springframework.web.client.HttpClientErrorException: 404`
- Configuration `same`
- Platform and Operating System `windows`

**Comment by JaredTan95** [comment]
according to your report, it looks like a bug. We will check it, and if you fix it, pull requests are welcomed.

**Comment by JaredTan95** [comment]
BTW, are you sure that your portal had connected `meta-server` correctly?

**Comment by Anilople** [comment]
> * [x]  I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
> * [x]  I have checked the [FAQ](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) of this repository and believe that this is not a duplicate.
> 
> **Describe the bug**
> Suppose that my
> app-id is `dynamic`,
> env is `DEV`,
> cluster is `default`,
> namespace is `application`
> 
> For the method `findNamespaces` in class `com.ctrip.framework.apollo.portal.controller.NamespaceController`.
> the get url is `/apps/dynamic/clusters/default/namespaces/application/items/deleted`
> It is ok for `apollo-1.5.1`, return like follow:
> 
> ```json
> [
> 	{
> 		"baseInfo": {
> 			"id": 1,
> 			"appId": "dynamic",
> 			"clusterName": "default",
> 			"namespaceName": "application",
> 			"dataChangeCreatedBy": "apollo",
> 			"dataChangeLastModifiedBy": "apollo",
> 			"dataChangeCreatedTime": "2019-12-23T20:17:27.000+0800",
> 			"dataChangeLastModifiedTime": "2019-12-23T20:17:27.000+0800"
> 		},
> 		"itemModifiedCnt": 0,
> 		"items": [],
> 		"format": "properties",
> 		"isPublic": false,
> 		"parentAppId": "dynamic",
> 		"comment": "default app namespace",
> 		"isConfigHidden": false
> 	}
> ]
> ```
> 
> But in `apollo-1.6.0` (newest master branch)
> There is some problem return.
> 
> ```json
> {
> 	"exception": "com.ctrip.framework.apollo.common.exception.NotFoundException",
> 	"message": "item not found for dynamic default application deleted",
> 	"status": 404,
> 	"timestamp": "2019-12-23T21:20:21.107"
> }
> ```
> 
> The config service and admin service are same when the portal running.
> portal 1.5.1 and portal 1.5.0 are running in the same machine(Win 10), the difference between them is the `server.port`.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> Just run `apollo-portal 1.6.0` newest on master branch
> 
> The problem in `apollo-1.6.0` cause the web ui cannot use.
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> ### Additional Details & Logs
> * Version 1.6.0
> * Error logs `org.springframework.web.client.HttpClientErrorException: 404`
> * Configuration `same`
> * Platform and Operating System `windows`

Found it.
The new api added in `apollo-admin-1.6.0`, and `apollo-portal-1.6.0` must combine with this admin version. 
But my admin service is `1.5.1`. So cause the problem.

The new Api in `admin-1.6.0` is
`com.ctrip.framework.apollo.adminservice.controller.ItemController`'s method `findDeletedItems`,
`@GetMapping("/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/items/deleted")`
and in `portal-1.6.0` the code `com.ctrip.framework.apollo.portal.service.NamespaceService`'s method `transformNamespace2BO`, there is a logic to find **deleted items** in line 247 change to use new method `findDeletedItems` which call the new api in `admin-1.6.0`
