### ISSUE TITLE
通知方式为什么是客户端做轮询，为什么不是服务端发通知

### ISSUE THREAD

**Issue by liov** [ctripcorp/apollo#2865]
允许配置一个callback url，客户端收到通知再拉配置，同步改异步不好吗
难道是怕多个pod只有一个收到请求？解决方案多种多样啊

**Comment by nisiyong** [comment]
客户端是做http长轮训，默认一分钟超时。有变更的话实时通知。目前的实现是比较轻量合理的啊

**Comment by liov** [comment]
> 客户端是做http长轮训，默认一分钟超时。有变更的话实时通知。目前的实现是比较轻量合理的啊

那假如我的配置只是偶发性的变更，不管长轮询还是短轮询这不是浪费么

**Comment by nisiyong** [comment]
嗯，你的意思是我一天就变更一次，但是客户端却要每分钟轮训一次是吧。

其实我认为这个是取舍问题，http长轮询实现简单，且跨语言通用，你算下来每分钟最多也就上千个请求，对配置中心负载来说，完全没问题，而是能做到变更实时通知。你用callback url，服务端还要记录，还要反过来去通知客户端，我觉得这对服务端来说复杂话了，也没必要

**Comment by cciechao** [comment]
有变更的话，也不是实时通知，主要是看等待时间，你把等待时间调高或者在等待时间内频繁修改配置，就能发现这个问题.....获取配置全靠client端主动去拉

**Comment by liov** [comment]
好吧，我想我有空的话可以试着实现一下poll和push同时存在
