### ISSUE TITLE
openAPI计划支持配置项的批量修改吗？

### ISSUE THREAD

**Issue by gt0012** [ctripcorp/apollo#2866]
openAPI计划支持配置项的批量修改吗？
目前openAPi中只有单个create以及update，或者是replace
有计划支持批量修改吗？
我看目前有个方法是 updateConfigItemByText，里面对比后产生一个changeSets，那么是否重写一个controller来对比产生一个changeSets走同样的保存是否就OK了?

**Comment by nobodyiam** [comment]
可以参照`com.ctrip.framework.apollo.portal.controller.ItemController#modifyItemsByText`在open api中增加一个接口
