### ISSUE TITLE
请问一个关于bootstrap.yml的问题

### ISSUE THREAD

**Issue by burningg** [ctripcorp/apollo#2869]
我现在在阿里云k8s里部署了一个apollo。
我在部署apollo的configservice时，因为一些原因，创建了一个slb的service，暴露了一个external IP，我把这个Ip配在了configservice里的bootstap.yml文件里，替换了，如下：
```
eureka:
  instance:
    hostname: ${hostname:localhost}
```
=》
```
eureka:
  instance:
    hostname: http://111.11.118.35:8080
```

这个ip地址是service的external Ip。

现在由于我要迁移站点，导致这个ip发生变化，我们需要重新构建镜像，并且不同环境的都需要重新构建，我们认为这样是不对的。

现在我们想了解一下${hostname:localhost}这个占位符是什么意思，
再者，如果我们想把这个external IP 配置在kubernetes的ConfigMap里，是否有什么方式可以做到。
谢谢

**Comment by nobodyiam** [comment]
Eureka的配置说明具体可以看下`org.springframework.cloud.netflix.eureka.EurekaInstanceConfigBean#getHostName`

apollo的bootstrap.yml中默认设置`preferIpAddress: true`，所以我理解设置hostname是无效的，eureka会使用机器的ip地址去注册（除非设置了preferIpAddress: falsea）。

不过我理解你的意图是希望config service/admin service把自己的k8s service ip注册上去吧，这个可以用Java System Property来设置：`-Deureka.instance.ip-address=${指定的IP}`，也支持OS Environment Variable：`EUREKA_INSTANCE_IPADDRESS=${指定的IP}`，所以不需要写在代码里面的。
