### ISSUE TITLE
关于多机房中采用数据库主从同步来保证多机房可用性的问题？

### ISSUE THREAD

**Issue by wkcaeser** [ctripcorp/apollo#2870]
假设两个机房，在数据库中配置eureka.service.url 不同cluster的地址，来做到两个机房机房都是各自独立的eureka集群，假设机房A的数据库为master（db1），机房B的数据库做从库(db2)（因为是热备，这个库也有写入权限），然后数据库之间通过otter来同步数据。   机房A的eureka集群访问db1，机房B访问db2， 然后所有配置修改操作都在机房A进行，这样能够做到双机房配置的同步并且高效。    

但是最近发现一个问题，服务在连接config-server的时候也会进行写入，会写入服务自身的信息，即portal界面上那个实例列表的功能，但是这块好像不是通过app_id、env、cluster等来做的关联，通过现象来看更像是通过自增主键来的。因为主库是自己的自增序列，而从库也会进行写入，所以两边通过id关联的时候关联关系就会错乱，在机房B的portal服务上看实例列表就很奇怪，会展示其他appId的实例。

**Comment by nobodyiam** [comment]
目前ConfigService中是会写入实例信息的，看描述我理解应该是两边的Instance和InstanceConfig表的自增id没有错开导致互相覆盖了吧？

**Comment by wkcaeser** [comment]
应该是的   apollo中很多地方是根据实际内容而不是自增id去关联的，没想到这块是根据id来的，两边id没错开导致了这个问题
