### ISSUE TITLE
配置中心乱码问题

### ISSUE THREAD

**Issue by Shenkc** [ctripcorp/apollo#2872]
DEV环境正常，增加了FAT环境以后就乱码了，在properties中输入以后点√中文就变问好了
![image](https://user-images.githubusercontent.com/46162066/71469204-57b95c80-2803-11ea-8aa8-7693a2aaf5d0.png)

**Comment by nobodyiam** [comment]
看下数据库的字符集是否正确

**Comment by Shenkc** [comment]
> 看下数据库的字符集是否正确

您好，数据库字符集正确，发现数据库内的数据内容出现？？乱码情况，将其改过来之后，配置中心也没有出现乱码情况，但是却无法成功发布，背景：DEV环境没有问题，搭建FAT环境时，使用的docker部署到另一台机器上串联上的，不知道是不是FAT环境数据库缺失ApolloPortalDB的原因

**Comment by Shenkc** [comment]
两个环境数据库字符集都是utf8mb4

**Comment by nobodyiam** [comment]
看下后端portal的日志
