### ISSUE TITLE
公共NameSpace是游离的

### ISSUE THREAD

**Issue by jiang4yu** [ctripcorp/apollo#2874]
- 使用文档中说：
**公共NameSpace是游离的**，
- 但是没有为游离状态的NameSpace提供有独立的创建入口，
- 创建得通过某一项目来进行创建，操作上与文档中描述的 “游离”相驳了

- 所以希望提供一个独立的创建接口并进行管理

**Comment by nobodyiam** [comment]
独立的创建接口意味着啥？

权限管理、操作审计等模型应该还是和项目非常类似的，所以感觉没有很大的必要重新搞一套模型出来
