### ISSUE TITLE
Apollo修改key长度配置不生效

### ISSUE THREAD

**Issue by GuiSong01** [ctripcorp/apollo#2875]
- [ ] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) of this repository and believe that this is not a duplicate.

**Describe the bug**
在管理员工具系统参数修改apollo key配置长度，只会保存到ApolloPortalDB库中，ApolloConfigDB数据库中serverconfig没有更新，校验key长度是在ConfigService做的，这样导致更新key的默认长度后并不能生效。
界面上前端校验中，key的长度限制没有从后台获取，也会导致更新key长度后不生效问题。
是否当前key长度只是有配置，不支持更新？
**To Reproduce**
1. 进入管理员工具，系统参数，修改key长度限制（大于128），参数：item.key.length.limit
2. 在界面上新增一个key长度超过128，但是没有超过设定值的字符串，会校验不过
3. 通过openapi写入一个长度超过128的key，写入失败
4. 

**Expected behavior**
界面上有key长度限制的参数，参数支持更新后生效，比如，期待key长度超过128后，直接在系统参数中更新即可满足诉求。
需要同时更新ApolloConfigDB中serverconfig数据库中配置，更新item表中字段key长度限制，支持portal上校验key长度的值，从后台获取
**Screenshots**

### Additional Details & Logs

- Version
- Error logs
- Configuration
- Platform and Operating System

**Comment by nobodyiam** [comment]
item.key.length.limit是apollo config db的配置，所以需要在数据库中直接修改，不支持通过系统参数页面修改。这个修改后，通过openapi写入是OK的。

不过前端界面上的配置是一个js文件，所以这块还得看看是否能和后端配置联动

https://github.com/ctripcorp/apollo/blob/master/apollo-portal/src/main/resources/static/scripts/valdr.js#L72
