### ISSUE TITLE
Server failed to start in 240 seconds

### ISSUE THREAD

**Issue by loadingkang** [ctripcorp/apollo#2878]
服务正常启动，也可以正常访问，但是执行结果显示Server failed to start in 240 seconds，看了下start.sh，启动时间超过240s就会出现这个错误，但是我应用是正常启动了，eureka也能看到注册上去的服务，感觉start.sh脚本是不是有点问题

**Comment by nobodyiam** [comment]
可能是机器性能较差，导致启动太慢了，startup.sh现在最多等待240s，超过时间还没启动成功就会提示启动失败

**Comment by loadingkang** [comment]
4C4G的机器，里面基本没有跑什么东西，而且查看服务日志文件的时候，应用很快就启动成功并且可以正常访问，但是start.sh脚本还处于starting状态，到240s的时候就提示fail了

**Comment by nobodyiam** [comment]
检查脚本很简单，就是`curl -X GET --silent --connect-timeout 1 --max-time 2 --head $SERVER_URL | grep "HTTP"`，可以跑一下看看

https://github.com/ctripcorp/apollo/blob/759d364339e731623feb9058f77684bb713f9062/apollo-configservice/src/main/scripts/startup.sh#L139
