### ISSUE TITLE
能否支持一键操作多个key-value 变更

### ISSUE THREAD

**Issue by oneal32** [ctripcorp/apollo#2879]
实际场景中，会存在针对一些大活动、突发情况等进行降级操作，会涉及到多个apollo开关。可以考虑加上改功能：针对不同场景，预设多个key-value值，并提供发布一键发布。

**Comment by nobodyiam** [comment]
这个本来就是支持的，多次修改一次发布，或者用文本模式也是可以一次修改多个配置项的。

至于你说的`针对不同场景，预设多个key-value值，并提供发布一键发布`，这个就是常说的`预案`了，可以通过open api接入来实现自动化的

**Comment by oneal32** [comment]
谢谢。看了一下[文档](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0)，通过openApi可以满足我的场景.
