### ISSUE TITLE
项目启动时使用System.setProperty设置过之后配置，@ApolloConfigChangeListener和api实现ConfigChangeListener都不能监听到配置变化

### ISSUE THREAD

**Issue by llyboy** [ctripcorp/apollo#2884]
项目启动时使用System.setProperty设置过之后配置，@ApolloConfigChangeListener和api实现ConfigChangeListener都不能监听到配置变化，有可能会第一次监听到，后续就不能监听到了，还望大神能给予解答

**Comment by nobodyiam** [comment]
因为程序实现中system property的优先级最高，详见

https://github.com/ctripcorp/apollo/blob/fb9b24a747766eb1aaf26eae01593d76d5b3adf0/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/DefaultConfig.java#L73
