### ISSUE TITLE
用源码打包后启动，读不到config目录下的配置

### ISSUE THREAD

**Issue by Alec-Zeng** [ctripcorp/apollo#2886]
背景：由于我司数据库使用Oracle，且各环境非常独立，所以利用1.4.0版本的源码，参考一些网上资料，进行了数据库适配和环境适配的改造

打包方式：使用idea编译器，直接执行assembly命令打包出来的zip包，没有使用build.bat和build.sh

问题1：本地启动和打包后启动时都读不到数据库配置
解决：如图，加了一行source的配置，强行读配置
![image](https://user-images.githubusercontent.com/59472896/71719406-3b4b9e80-2e59-11ea-8107-ec9ff5d56ae9.png)

问题2：数据库配置能读到之后，发现修改打包后的config目录下的application-github.properties里的数据库配置，发现无效，始终读取到的旧的配置，经查，发现是因为jar里包含了这个文件，始终读取的是jar里写死的，然后把jar里的配置去掉，修改pom.xml，如图：
![image](https://user-images.githubusercontent.com/59472896/71719809-713d5280-2e5a-11ea-8df4-25429d11e475.png)

发现还是有问题，还是读到旧的配置了，然后继续跟踪发现，读到了apollo-common包里的配置（注：croe/common/biz/client四个module都做了微调，改名并重新打包放到公司的maven私服，引用的也是重新打包的jar），然后删掉了apollo-common里的application-github.properties配置文件，重新打包，结果报application-github.properties找不到了，但是在打包好的包里的config目录下是有这个文件的，同时也有把config目录加到class-path里
apollo-configservice的jar的class-path配置见上一张图
ConfigServiceApplication.java里的@PropertySource尝试过[classpath:application-github.properties]、[classpath*:application-github.properties]、[classpath*:config/application-github.properties]都无效，都是报配置文件找不到

无奈，只能在这里求助一下了，求大神解救

**Comment by Alec-Zeng** [comment]
第二个图好像看不到，这里写成文本补充一下：
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-jar-plugin</artifactId>
	<configuration>
		<archive>
			<manifestEntries>
				<Class-Path>config/ libs/ojdbc6.jar</Class-Path>
			</manifestEntries>
		</archive>
		<excludes>
			<exclude>application-github.properties</exclude>
		</excludes>
	</configuration>
</plugin>

**Comment by nobodyiam** [comment]
建议按照[分布式部署的方式打包](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#222-%E9%80%9A%E8%BF%87%E6%BA%90%E7%A0%81%E6%9E%84%E5%BB%BA)

**Comment by Alec-Zeng** [comment]
把一些改过的配置改回原样，修改build脚本，执行build脚本打包，结果可以了
两者区别在于build脚本里执行mvn package时有带参数，应该是我之前直接打包没有这些参数的原因
