### ISSUE TITLE
源码构建与注册中心剥离

### ISSUE THREAD

**Issue by RexFang** [ctripcorp/apollo#2887]
之前花了些时间把阿波罗相关的文档都看了一遍，最近花了1.5天的时间尝试通过源码构建JAR，同时尝试把注册中心从阿波罗剥离出来，从而达到升级注册中心的目的。但是在构建源码费了老大劲，同时发现部分JAR有被定制化改造过的迹象，但是Maven仓库中又没有找到，例如：
<dependency>
    <groupId>com.ctrip.3rdparty.tomcat.embed</groupId>
    <artifactId>tomcat-embed-core</artifactId>
</dependency>
除此之外，Maven依赖还排除了大量的SpringBoot的相关依赖，要想自己构建，着实要花很大的力气，代价有点大。

**Comment by nobodyiam** [comment]
com.ctrip.3rdparty.tomcat.embed
tomcat-embed-core

这些jar是ctrip特有的，只在ctrip相关maven profile下才会被使用到，开源用户不会使用到的，请仔细看下maven profile的配置。
