### ISSUE TITLE
portal服务连接了dev和fat两个环境（保持两个环境数据库一致）。在配置文件中增加一个配置项，发现另一个环境也增加了。这边发布会发现可能在另一个环境里面发布。一个配置项发现要发布很多次。而且它可能几秒钟后又恢复到之前的发布过的值

### ISSUE THREAD

**Issue by HuaFirst123** [ctripcorp/apollo#2889]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HuaFirst123** [comment]
不太清楚为啥会出现这种情况

**Comment by HuaFirst123** [comment]
如果portal服务只连了一个环境，那么不会有这个问题。

**Comment by nobodyiam** [comment]
apolloconfigdb对每个环境都需要独立一套

**Comment by HuaFirst123** [comment]
> apolloconfigdb对每个环境都需要独立一套

这个已经是每个环境部署了一套。每个config和admin都有一套自己的configdb,我的想法是，是不是可能与都注册到了同一个eureka中有关。我的几套环境都注册到了同一个eureka中。名称也是一样的。您看是这样导致的问题吗

**Comment by HuaFirst123** [comment]
找到问题所在了。我这边的不同环境的config和admin的服务都注册到了我们项目的注册中心上。导致每次增加配置信息时会同时增加多个。现在每套环境使用不同的注册中心就没有问题了。
