### ISSUE TITLE
apollo  config service CPU占的怎么太高了

### ISSUE THREAD

**Issue by lizhichao999** [ctripcorp/apollo#2893]
apoll config service太耗CPU了
![image](https://user-images.githubusercontent.com/34128722/71949249-d5229b00-320d-11ea-97e0-03c7eb5e5901.png)
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
46873 appdepl+  20   0 4728876 1.502g  17100 S  91.7  9.6   1042:33 java
16G的机子
/app/jdk1.8.0_141/bin/java -Dsun.misc.URLClassPath.disableJarChecking=true -Xms6144m -Xmx6144m -Xss256k -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=384m -XX:NewSize=4096m -XX:MaxNewSize=4096m -XX:SurvivorRatio=8 -server -XX:-ReduceInitialCardMarks -XX:ParallelGCThreads=4 -XX:MaxTenuringThreshold=9 -XX:+DisableExplicitGC -XX:+ScavengeBeforeFullGC -XX:SoftRefLRUPolicyMSPerMB=0 -XX:+ExplicitGCInvokesConcurrent -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Duser.timezone=Asia/Shanghai -Dclient.encoding.override=UTF-8 -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom -Dserver.port=8080 -Dlogging.file=/data/logs/100003171/apollo-configservice.log -XX:HeapDumpPath=/data/logs/100003171/HeapDumpOnOutOfMemoryError/ -XX:+UseParNewGC -Xloggc:/data/logs/100003171/gc.log -XX:+PrintGCDetails -XX:+UseConcMarkSweepGC -XX:+UseCMSCompactAtFullCollection -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=60 -XX:+CMSClassUnloadingEnabled -XX:+CMSParallelRemarkEnabled -XX:CMSFullGCsBeforeCompaction=9 -XX:+CMSClassUnloadingEnabled -XX:+PrintGCDateStamps -XX:+PrintGCApplicationConcurrentTime -XX:+PrintHeapAtGC -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=5M -jar /data/webapps/apollo-configservice-1.5.1/apollo-configservice.jar

**Comment by wkcaeser** [comment]
看上去有点像内存配置有问题，导致在不停的gc，正常情况下启动起码会占用2G左右内存。之前我也遇到过，你可以打印下线程信息，看看是不是gc线程

**Comment by lizhichao999** [comment]
> 看上去有点像内存配置有问题，导致在不停的gc，正常情况下启动起码会占用2G左右内存。之前我也遇到过，你可以打印下线程信息，看看是不是gc线程

这都配置了快6G内存

**Comment by wkcaeser** [comment]
你这内存配置写的有问题呀，整体6G，新生代都分配了4G       你打印下线程信息，占用cpu的十有八九是gc线程

**Comment by wkcaeser** [comment]
你这配置我不知道理解的对不对     总体6G，新生代分了4G？     你打印下jvm的线程信息，十有八九是gc线程      先 top -H -p   pid  看下线程情况，应该会有几个百分百占用的线程

**Comment by lizhichao999** [comment]
有几个，然后怎么看呀？

**Comment by lizhichao999** [comment]
> 你这配置我不知道理解的对不对 总体6G，新生代分了4G？ 你打印下jvm的线程信息，十有八九是gc线程 先 top -H -p pid 看下线程情况，应该会有几个百分百占用的线程

有几个然后怎么样？

**Comment by nobodyiam** [comment]
top -H 结合 jstack 就可以知道是什么线程在吃CPU
