### ISSUE TITLE
config service 高可用客户端如何调用,-Dapollo.meta=http://ip:8080,http://ip2:8080  中间逗号隔开吗

### ISSUE THREAD

**Issue by lizhichao999** [ctripcorp/apollo#2895]
config service高可用2个实例，客户端是不是 -Dapollo.meta=http://ip:8080,http://ip2:8080

**Comment by nobodyiam** [comment]
可以这么做，不过建议的做法是在实例前面加一个slb，这样客户端的meta server信息就不会变了
