### ISSUE TITLE
@ConfigurationProperties注解导致类型从Integer转为String

### ISSUE THREAD

**Issue by FengYD** [ctripcorp/apollo#2896]
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) of this repository and believe that this is not a duplicate.

**Describe the bug**
使用@ConfigurationProperties注解，项目中属性定义为Object，从apollo读取配置后该属性为String类型，从本地配置文件读取配置之后该属性为Integer类型
apollo-client 1.4.0
jdk 1.8
spring-boot 2.2.1.RELEASE

**To Reproduce**
1. 在apollo中添加类型为yml的私有namespace，在其中添加一个属性
test.test: 1000
2. 在项目中定义test类型为Object，使用@ConfigurationProperties获取test.test的值，test的实际类型为String
3. 删除apollo中属性，在本地文件定义一个test.test: 1000
4. 在项目中获取test.test的值，test的实际类型为Integer

**Expected behavior**
希望配置在本地和在apollo中定义的时候，其类型是相同的

**Screenshots**

### Additional Details & Logs

- Version
- Error logs
- Configuration
- Platform and Operating System

**Comment by nobodyiam** [comment]
test类型为啥是object？

**Comment by FengYD** [comment]
> test类型为啥是object？
意思是我在程序中定义为Object类型之后无法获取其实际类型。
具体的应用场景是spring-cloud-gateway 2.2.1.RELEASE 一个配置的问题，配置key为response-timeout
https://cloud.spring.io/spring-cloud-gateway/reference/html/#per-route-timeouts

**Comment by g5niusx** [comment]
> > test类型为啥是object？
> > 意思是我在程序中定义为Object类型,通过@ ConfigurationProperties之后无法获取其实际类型。
> > 具体的应用场景是spring-cloud-gateway 2.2.1.RELEASE 一个配置的问题，配置key为metadata，
> > 这个被定义为Map<String, Object>,使用@ ConfigurationProperties注入之后，对应的数据就称为了字符串而不是数值
> > https://cloud.spring.io/spring-cloud-gateway/reference/html/#per-route-timeouts

是否可以贴一下代码？😊

**Comment by g5niusx** [comment]
@FengYD 
- spring boot 的 yaml 实现
spring boot 加载 `application.yml` 文件的时候，使用了 https://github.com/spring-projects/spring-boot/blob/56e30258fbb9ee5aae5cd516a8f7364d2efa1835/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/source/ConfigurationProperty.java#L39-L41 来存储对应的 key-value。yaml 文件里面是有数据类型区分的。所以当你在本地使用 yaml 来加载的时候，`10000` 会被当 `integer` 来加载。如果你使用了 `application.properties` 它的类型也会变成 `string`
- apollo 的实现
apollo 使用了 https://github.com/ctripcorp/apollo/blob/42edb9da963df986538edcda4ff58d474fb3abed/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/AbstractConfigFile.java#L31 来存储远程加载的配置，因为 `properties` 的 `setProperty(String key, String value)` 只能使用 `string` 类型，所以在`bind field` 的时候，被绑定成了 `string` 类型

**如有解释错误，请见谅。😊**

**Comment by nobodyiam** [comment]
@g5niusx 应该就是你所说的原因

**Comment by nobodyiam** [comment]
进一步解释下，由于apollo的实现中使用了Properties作为配置存储，所以虽然在apollo解析yaml时能知道配置的类型（如Integer），但是在存储的时候都会统一转为String类型，如下图所示：

![image](https://user-images.githubusercontent.com/837658/75085734-145f3e00-5567-11ea-9117-dc822323fa78.png)

https://github.com/ctripcorp/apollo/blob/62cdc90d668dcae4d21fe79235194e201603e85d/apollo-client/src/main/java/com/ctrip/framework/apollo/util/yaml/YamlParser.java#L141

**Comment by ywf4026** [comment]
@nobodyiam 那这个问题是没办法解决的罗？
