### ISSUE TITLE
支持二进制配置文件管理

### ISSUE THREAD

**Issue by nisiyong** [ctripcorp/apollo#2899]
**Is your feature request related to a problem? Please describe.**

在微服务架构中，推崇“应用配置分离”的原则。在未使用配置中心之前，我们的配置都是以文件的方式存储，有properties，json等等格式。Apollo抽象了Namespace模型与传统的配置文件相对应，并且支持了Namespace级别的审计，灰度发布等高级特性。

但是在传统的配置文件中，还包含了第三方证书等二进制文件。Namespace模型并没有包含到，尽管Namespace支持多种类型，如properties，yaml，json，txt等，但是这些都是文本，并非二进制。由于二进制配置文件无法支持，目前并无法做到真正的“应用配置分离”，期望能在Apollo之上扩展该功能，当然如何做希望大家能一起探讨下。

**Describe the solution you'd like**

当前文本类型的配置都是结合`ApolloConfigDB`.`Item`表使用的，如何是propeteis类型的配置，每一个配置项会对应`item`表的一行；如果是非properties类型的Namespace，则是该Namespace的所有内容，对应`item`表的一行，存放到longtext类型的Value字段上。

扩展Namespace，新增一张管理二进制文件的表，与Namespace模型关联，也是为了复用Namespace的权限管理等操作。

**Describe alternatives you've considered**

当前Apollo不支持二进制文件，我们的方案暂时分为两种：
1. 所有环境的的二进制文件打包到jar里，在利用profile来区分文件或apollo配置文件路径
2. 二进制文件由运维分发到服务器指定路径，apollo配置路径读取。（但是对于容器应用来说不太友好）

**Additional context**
None

**Comment by christinkaka** [comment]
二进制文件作为配置文件对配置中心编辑可能还是吃力一些，因为可能装载、读取方式都千差万别。如果真的要在现有基础上做，换我就会把这些二进制文件hex过后作为文本传给应用程序再进行转二进制流，嘻嘻

**Comment by nisiyong** [comment]
@christinkaka 

之前有想过直接用Namespace的txt格式存文件的base64，不过在某些场景还是无法满足业务需求。比如，在金融场景和第三方机构对接，他们有些提供的sdk读取文件，入参就只是路径而已，要是他们提供的是InputStream我们还可以自己转化传进去。

配置中心管理文件的话，我们也可以限制大小，一般问题也不大。使用的话，我觉得默认缓存到指定路径即可，如默认的`/opt/data/`下，支持下文件热更新就够了，不像properties那么复杂。

**Comment by nobodyiam** [comment]
二进制配置文件如果要放在apollo管理的话，我理解是完全不同于当前文本配置的设计的，复用程度会比较低。

是否可以考虑借助于外部存储，比如文件实际存储在外部存储（比如s3, oss等），然后保存文件引用信息（文本）到apollo？

**Comment by nisiyong** [comment]
应用的配置文件还是有区别也普通文件。

只考虑外部存储的话，其实是缺失了配置文件治理的能力（权限管理，发布管理等），并且给每个应用客户端带来了复杂性。我个人目前较希望Apollo能治理配置的类型能多这一种二进制文件类型。

**Comment by nobodyiam** [comment]
如果是保存文件引用信息（文本）到apollo的话，其实配置文件治理的能力（权限管理，发布管理等）还是可用的吧，对客户端会有一定的工作量，不过应该可以通过封装一个统一的SDK来简化用户的使用。

因为对二进制文件的内容是不可读的，所以觉得放在apollo存储和传输似乎并没有带来太多的好处。

**Comment by nisiyong** [comment]
最后还是在Apollo扩展了该模块，做功能独立且简单的文件管理，减少第三方存储的依赖。
客户端可以通过开关决定是否启用该功能，启动时会优先同步一次，后续定期同步更新。

## Preview
![image](https://user-images.githubusercontent.com/8198862/77281468-0d605280-6d02-11ea-8a60-5406d0219a97.png)

![image](https://user-images.githubusercontent.com/8198862/77281636-7fd13280-6d02-11ea-8175-dd2850bbe8ca.png)

## Tips

- 在对应的环境集群中上传文件后，客户端会每分钟同步文件到本地
- 通过application.properties文件配置apollo.file-sync.enabled=true启用文件同步功能
- 默认文件同步目录：/opt/data/{appId}/file-cache/
- 当应用要加载文件时，建议文件路径配置到application namespace中

**Comment by nisiyong** [comment]
@MingJunDuan 
As mentioned above, we have extended this feature on the internal apollo version. But the community will consider more cases, maybe I can create a PR if anyone needs it.
