### ISSUE TITLE
xml使用apollo解析问题

### ISSUE THREAD

**Issue by goldYuisniubienough** [ctripcorp/apollo#2900]
使用xml获取apollo配置时，在加载xml时出现了个错误
Bean creation exception on non-lazy FactoryBean type check: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cZKRcFacade': Initialization of bean failed; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Integer' for property 'timeout'; nested exception is java.lang.NumberFormatException: For input string: "${frwp.rc.facility.bps.timeout}"

但是apollo和本地缓存里面都是有这个key的，frwp.rc.facility.bps.timeout = 30000
而且检查了也没有空格，回车之类的字符，不知道为什么会出现这个问题

**Comment by nobodyiam** [comment]
对照下 xml config demo看看哪里配置不对了

https://github.com/ctripcorp/apollo/tree/master/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/spring/xmlConfigDemo
