### ISSUE TITLE
关于logback-spring.xml日志配置文件问题

### ISSUE THREAD

**Issue by Flaky-Pastry** [ctripcorp/apollo#2901]
用的1.5.1版本
springboot项目，2.1.5，原先项目中有logback-spring.xml日志配置文件，将application.properties文件迁移到配置中心之后
1. 设置eagerLoad enabled 为true，在apollo配置中心配置logging.config=classpath：logback-xxxx.xml 服务端启动日志无法打印，启动成功后的所有日志都无法输出，logback-xxxx中的配置完全没有生效

2.取消eagerload设置，服务端启动日志可以打印到控制台，但是启动日志和启动后的业务日志都无法输出到文件

如果想把logback-spring.xml完全移到apollo配置中心需要怎么配置？如果留在项目中又需要怎么配置？

**Comment by nobodyiam** [comment]
目前能支持的是通过springProperty把需要变化的配置放在apollo中管理，参考 https://github.com/ctripcorp/apollo-use-cases/blob/master/spring-boot-dubbo/spring-boot-dubbo-provider/src/main/resources/logback-spring.xml
