### ISSUE TITLE
如何将 Eureka 注册的地址改为公网地址

### ISSUE THREAD

**Issue by liuyang001** [ctripcorp/apollo#2904]
使用场景 ：

    1.  apollo 使用  docker 部署在腾讯云服务器 
              apollo-adminservice:8090 
              apollo-configservice:8080
                   
                           都是注册的内网地址
  
    
    2.  本地测试 springboot 拉取配置 

    
 结果 ： 本地 无法访问 云服务器 内网地址

**Comment by liuyang001** [comment]
请问如何将    apollo-adminservice  和   apollo-configservice 的注册地址改为公网 地址

**Comment by liuyang001** [comment]
![image](https://user-images.githubusercontent.com/19657854/72203254-29df4380-34a4-11ea-9b65-3bee9ab24714.png)

**Comment by JaredTan95** [comment]
将公网eureka 地址填到这里就好了。。。

**Comment by liuyang001** [comment]
感谢提醒，已处理
