### ISSUE TITLE
error:Table 'apolloconfigdb.role' doesn't exist

### ISSUE THREAD

**Issue by ShenZhenzly** [ctripcorp/apollo#2905]
您好，启动portal的时候报错：pid - 7102 just quit unexpectedly, please check logs under /opt/logs/100003173 and /tmp for more information! 查看日志找到一个error:Table 'apolloconfigdb.role' doesn't exist，我使用的是分布式部署指南里面的apolloconfigdb.sql和apolloportaldb.sql手动创建的数据库，请问这个怎么解决。

**Comment by nobodyiam** [comment]
portal应该连接apolloportaldb，看下数据库连接串是否写错了
