### ISSUE TITLE
CPU占用太高，三个容器启动100%，四核心16G机子呀

### ISSUE THREAD

**Issue by duronfly** [ctripcorp/apollo#2907]
CPU占用太高，三个容器启动100%，四核心16G机子呀

**Comment by nisiyong** [comment]
可以先排查下是哪个线程占用cpu较高

**Comment by nobodyiam** [comment]
看描述像是GC的问题，用top -H看下是哪个线程，另外也看下堆大小的分配是否合理

**Comment by zhaoyuxi** [comment]
> CPU占用太高，三个容器启动100%，四核心16G机子呀

我的环境也多次出现，堆栈是Spring LRU Cache并发冲突，你有解决吗？

**Comment by zhaoyuxi** [comment]
> 看描述像是GC的问题，用top -H看下是哪个线程，另外也看下堆大小的分配是否合理

我的环境也多次出现，堆栈是有200多个线程阻塞在Spring LRU Cache，问题同下
https://github.com/spring-projects/spring-framework/issues/24671
