### ISSUE TITLE
 meta server address:http://apollo.meta

### ISSUE THREAD

**Issue by hongjie6688** [ctripcorp/apollo#2908]
apollo-portal 启动的时候报错

**Comment by g5niusx** [comment]
贴一下报错信息？

**Comment by hongjie6688** [comment]
![image](https://user-images.githubusercontent.com/23434200/72588216-8faf4d80-3932-11ea-82e3-2898c335efdb.png)
![image](https://user-images.githubusercontent.com/23434200/72588252-a5bd0e00-3932-11ea-8c82-1e1e62eae74b.png)
不知道为啥用配置文件的 就提示找不到apollo.meta 
![image](https://user-images.githubusercontent.com/23434200/72588277-bbcace80-3932-11ea-9bf8-0faa4eddcfd9.png)

**Comment by g5niusx** [comment]
直接注入 `apollo.meta` 试试？

**Comment by nobodyiam** [comment]
在apollo-env.properties文件里面需要写`dev.meta=http://xxx`，通过环境变量传的时候是写dev_meta

**Comment by xysjun** [comment]
![image](https://user-images.githubusercontent.com/58758725/74085901-dec34b00-4ab8-11ea-84ec-451ea90d49f0.png)
![image](https://user-images.githubusercontent.com/58758725/74085912-fdc1dd00-4ab8-11ea-9d84-40e181f23a38.png)
![image](https://user-images.githubusercontent.com/58758725/74085916-0c0ff900-4ab9-11ea-9886-209b641e2aa2.png)
一样的问题

**Comment by xysjun** [comment]
![image](https://user-images.githubusercontent.com/58758725/74085932-32359900-4ab9-11ea-9a12-74b3316cb273.png)

**Comment by nobodyiam** [comment]
debug一下看看，看看配置是否正确读到了
