### ISSUE TITLE
apollo修改数据库账户密码，如何让spring的bean重启加载

### ISSUE THREAD

**Issue by ffyyhh995511** [ctripcorp/apollo#2909]

**Comment by huangxfchn** [comment]
第一步，使用  `@RefreshScope` 定义你的 Datasource，RefreshScope在 spring-cloud-context 模块
```
@ConfigurationProperties(prefix = "druid")
@RefreshScope
@Component("druidDatasource")
public class RefreshScopeDruidDatasource extends DruidDataSource {
}
```

第二步，注入 spring-cloud-context 模块的 `RefreshScope` bean，并调用 `refresh` 方法，指定Datasource 的 beanName
```
@Configuration
@EnableApolloConfig
public class DruidConfigChangeHandler {

    @Resource
    private RefreshScope refreshScope;

    @ApolloConfigChangeListener(value = "application", interestedKeys = "druid.password")
    public void appConfigChangeHandler(ConfigChangeEvent changeEvent) {
        refreshScope.refresh("druidDatasource");
    }

}
```

**Comment by ffyyhh995511** [comment]
大神，我自己创建了一个命名空间application.yml，确定已发布

我的配置文件如下配置
app:
  id: demo
apollo:
  meta: http://127.0.0.1:8080
  bootstrap:
    enable: true
    namespaces: application.yml

但是启动的时候会报
RemoteConfigRepository failed, reason: Load Apollo Config failed - appId: demo, cluster: default, namespace: application, 
url: http://127.0.0.1:8080/configs/demo/default/application?ip=127.0.0.1 [Cause: [status code: 404] Could not find config for namespace 
- appId: demo, cluster: default, namespace: application, please check whether the configs are released in Apollo!]

感觉不能识别application.yml这个配置文件
