### ISSUE TITLE
Client 拉取配置后没有确认机制，后续是否考虑考虑添加Client确认机制

### ISSUE THREAD

**Issue by GuiSong01** [ctripcorp/apollo#2911]
**Is your feature request related to a problem? Please describe.**
服务监听到配置变更后，对于从配置中心获取的配置，存在部分对可靠性要求很高的场景需要校验配置是否正确，界面上需要实时感知到配置是否生效，这种场景需要client告知配置中心，配置是否实际被服务用到。

请教一下配置中心是否有这方面的考虑？或者利用其它的功能也能做到这个保证？

建议的方案：
ConfigService提供接口，开放给Client写入配置设置结果；

在获取配置实例后面添加配置成功或者失败的结果
![image](https://user-images.githubusercontent.com/18419834/72738767-3dde2000-3bdd-11ea-85f7-4849407b891a.png)

**Comment by nobodyiam** [comment]
场景比较复杂，建议通过业务监控来实现

**Comment by ZShUn** [comment]
个人感觉配置中心没必要这么复杂，包括配置是否生效以及校验完全可以通过业务监控在client完成，不需要确认机制
