### ISSUE TITLE
热更新不支持删除配置的热更新

### ISSUE THREAD

**Issue by liquanjin** [ctripcorp/apollo#2916]
-   I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.

-  I have checked the [FAQ](https://github.com/ctripcorp/apollo/wiki/部署&开发遇到的常见问题) of this repository and believe that this is not a duplicate.

### Describe the bug

使用@ConfigurationProperties + EnvironmentChangeEvent时，热更新不支持已删除配置的热更新。

```java
@Data
@ConfigurationProperties(prefix = "a.discovery.strategy",ignoreInvalidFields = true)
public class DiscoveryStrategyRootProperties {

    private List<String> testStrs ;
  
    private Boolean enabled = Boolean.FALSE;
}
```

然后手动实现动态热更新，通过 EnvironmentChangeEvent。

```java
public void refreshProperties(ConfigChangeEvent changeEvent) { 
      JsonUtil.toJson(changeEvent.changedKeys()));
        // 此刷新方式 可完成对 @ConfigurationProperties Bean 的刷新
        this.applicationContext.publishEvent(new EnvironmentChangeEvent(changeEvent.changedKeys()));
 

        changeEvent.changedKeys().stream()
                .forEach(key -> {
                    ConfigChange change = changeEvent.getChange(key);
                    log.info(" {} 属性正在更新. oldValue: {} ,newValue: {}", key, change.getOldValue(), change.getNewValue());
                });
        log.info("apollo 配置文件变更, 属性动态刷新完毕");
 
    }
```

apollo-client 1.3.0
jdk 1.8
spring-boot 2.1.9.RELEASE

### To Reproduce

1. 在apollo中添加类型为yml的私有application.yml，在其中添加多个属性

   ```yml
   a:
       discovery:
         strategy:
           enabled: true
           testStrs[0]: '01'
           testStrs[1]: '02'
   ```

   

2. 删除所有testStrs 集合的配置参数，热更新无法将testStrs 更新为null。 而是上一次有效热更新的结果

3. 同时，还有警告信息。奇怪的是我配置的namespaces为：application.yml，为什么提示信息是在 application 中找？而不是在application.yml 中找？

   ```tex
   Could not find config for namespace - appId: a-gateway, cluster: default, namespace: application, please check whether the configs are released in Apollo!]
   ```

   

**Expected behavior**
希望删除配置参数时，也可以实现热更新。而不是提示参数找不到

**Screenshots**

### Additional Details & Logs

- Version
- Error logs
- Configuration
- Platform and Operating System

**Comment by liquanjin** [comment]
其他的场景是可以热更新的。
比如集合新增配置：    testStrs[3]: '03' ； 逐一删除集合配置（只要不全部删完）都可以。

**Comment by nobodyiam** [comment]
see https://github.com/ctripcorp/apollo-use-cases/issues/12，是spring cloud自身的问题，可以通过refreshScope替代解决

**Comment by liquanjin** [comment]
是指通过 调用：
RefreshScope的 refreshAll(); 方法吗？
我试了还是不行

**Comment by nobodyiam** [comment]
参考下面的示例代码，我测试过，是可以的
https://github.com/ctripcorp/apollo/blob/76860444879f0bc4dd1411e51bf989be2eff6fff/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/spring/springBootDemo/refresh/SpringBootApolloRefreshConfig.java#L35

**Comment by liquanjin** [comment]
感谢提供的示例。
我现在是基础框架层面需要热更新，所以我面临的情况是可能不知道哪个Bean 需要更新。
我想想办法吧。感谢

**Comment by liquanjin** [comment]
不属于Apollo的bug，已关闭。

**Comment by liquanjin** [comment]
@nobodyiam 我试了下你提供的方式，依然不行。
我的SpringCloud 版本为2.1

**Comment by nobodyiam** [comment]
先跑一下apollo-demo中的示例，确保功能是OK的，然后再比较下是使用的方式不一样还是spring cloud的版本不一样
