### ISSUE TITLE
编译方式上的疑问

### ISSUE THREAD

**Issue by happyapple668** [ctripcorp/apollo#2919]
很多项目都需要在编译时候从maven-wrapper.properties文件配置的地址下载maven包，我本地本身就配置了maven，又下载很麻烦，虽然可以设置为本地zip包，但解压又多了一份安装包文件，为啥就不能用本地存在的呢？
这种方式有什么好处？或者是避免什么问题吗

**Comment by nobodyiam** [comment]
apollo可以直接本地mvn compile的，如果本地没有安装Maven的话，可以使用mvnw

**Comment by g5niusx** [comment]
> 很多项目都需要在编译时候从maven-wrapper.properties文件配置的地址下载maven包，我本地本身就配置了maven，又下载很麻烦，虽然可以设置为本地zip包，但解压又多了一份安装包文件，为啥就不能用本地存在的呢？
> 这种方式有什么好处？或者是避免什么问题吗

使用 `maven-wrapper.properties` 的好处是你可以直接使用工程里面指定的maven来做编译，这样会减少可能因为maven版本问题导致代码编译失败的问题。当然，你也可以直接使用 `mvn compile` 来编译工程 😄
