### ISSUE TITLE
 I/O error on GET request for

### ISSUE THREAD

**Issue by xysjun** [ctripcorp/apollo#2920]
![image](https://user-images.githubusercontent.com/58758725/74085978-a6703c80-4ab9-11ea-84c5-d037637dac1f.png)
![image](https://user-images.githubusercontent.com/58758725/74085984-b1c36800-4ab9-11ea-9309-e524800a595a.png)
![image](https://user-images.githubusercontent.com/58758725/74085991-bee05700-4ab9-11ea-9b1e-64bc2ade793a.png)
添加完自定义环境之后，启动报错

**Comment by nobodyiam** [comment]
debug一下看看，看看配置是否正确读到了
