### ISSUE TITLE
一个tomcat下部署多个war，导致app.id相同

### ISSUE THREAD

**Issue by chaos08** [ctripcorp/apollo#2921]
2020-02-09 15:26:39.244 [main] INFO  com.ctrip.framework.foundation.internals.provider.DefaultApplicationProvider 85 initAppId - App ID is set to [....] by app.id property from System Property
两个应用都被System Property设置成其中一个应用的app.id，之前是使用application.yml的方式配置的app.id，看了文档说这种方式不适用于一个tomcat下多个war，已经改成app.properties，但是app.id仍然没有修改过来，请教

**Comment by nobodyiam** [comment]
可以看下environment中的property sources，里面应该有app.id

**Comment by chaos08** [comment]
> 可以看下environment中的property sources，里面应该有app.id

不好意思，这个environment是指环境变量么，在里面没有找到。
下面的图里面也没有
![image](https://user-images.githubusercontent.com/26955524/74130576-501c0e80-4c1d-11ea-9f2d-fa80cae2ddf0.png)

**Comment by g5niusx** [comment]
应该是让你看一下 spring 的 `environment` 对象。里面的 `property sources` 是存储我们配置的 `propeties`的。这个需要你debug看一下了，或者把它输出到日志里面。

**Comment by chaos08** [comment]
> environment

非常感谢，我输出了所有的System Property，确实有app.id，但是我并没有设置，不知道从哪来的，我debug查一下

**Comment by chaos08** [comment]
> 应该是让你看一下 spring 的 `environment` 对象。里面的 `property sources` 是存储我们配置的 `propeties`的。这个需要你debug看一下了，或者把它输出到日志里面。

我在日志里面输出了所有的System Property，发现确实有app.id这个Property，但是我并没有设置这个，不知道这个来源是哪。。
![image](https://user-images.githubusercontent.com/26955524/74133075-b6eff680-4c22-11ea-9919-51b49645dcb5.png)
![image](https://user-images.githubusercontent.com/26955524/74133096-c66f3f80-4c22-11ea-8f75-95462a7fa008.png)

**Comment by g5niusx** [comment]
这个就是你配置的`app.properites`文件来注入进去的,当然通过系统环境变量、`-D app.id=xx`这些都可以注入进去，主要看你使用的场景。看你说同一个tomcat部署来多个war，你看一下是不是tomcat注入了一个全局的 `app.id`,有可能你们配置了tomcat的 `catalina.properties` 里面的 `shared.loader` 。当然也有其他的可能性。。

**Comment by nobodyiam** [comment]
@chaos08 

你先看下 com.ctrip.framework.apollo.spring.boot.ApolloApplicationContextInitializer#fillSystemPropertyFromEnvironment 这个逻辑

**Comment by qixiaobo** [comment]
The same problem meet with sofa-ark
