### ISSUE TITLE
长轮询总是返回http_code=200导致不断请求configService

### ISSUE THREAD

**Issue by UFO-Coder** [ctripcorp/apollo#2922]
hello,apollo在我们实际生产应用中，发现长轮询请求，服务端总是返回200.导致任务不断塞进定时任务线程池，且线程池存在OOM风险。(真实发生了OOM)
请问：
1.服务端总是返回200是否有问题?难道不应该正常返回304吗，我们生产基本没有频繁的的release配置。
大神，求解答！

**Comment by nobodyiam** [comment]
正常是返回304，估计不是通过apollo-client发起的请求吧，建议看下config service和apollo-client的代码实现
