### ISSUE TITLE
客户端是否可以配置不使用服务发现。

### ISSUE THREAD

**Issue by sKabYY** [ctripcorp/apollo#2923]
在k8s+istio上部署遇到long polling超时问题。
apollo长连接需要60秒以上的超时时间，而istio默认超时时间只有15秒。

istio不支持全局修改默认超时时间，只能单独配置某个域名或者地址。但是apollo客户端使用服务发现机制，通过IP直连configservice，没有固定的地址可以配置。

且k8s具备比较完善的动态伸缩能力了，服务发现似乎不是很有必要。
所以请问客户端是否可以配置不使用服务发现，直接使用域名/服务名连接。

**Comment by nobodyiam** [comment]
k8s下确实可以不需要自己实现服务发现了，可以通过 -Dapollo.configService=http://config-service-url:port 来跳过服务发现

**Comment by sKabYY** [comment]
apollo.configService=http://config-service-url:port

这个配置支持springboot吗？

**Comment by sKabYY** [comment]
> k8s下确实可以不需要自己实现服务发现了，可以通过 -Dapollo.configService=http://config-service-url:port 来跳过服务发现

apollo.configService=http://config-service-url:port

这个配置支持springboot吗？

**Comment by nobodyiam** [comment]
https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#1222-%E8%B7%B3%E8%BF%87apollo-meta-server%E6%9C%8D%E5%8A%A1%E5%8F%91%E7%8E%B0

**Comment by sKabYY** [comment]
谢谢解答！

实测了-Dapollo.configService=xxx （要放在java和-jar之间）和环境变量的方法有效。server.properties配置文件的方法没有试。

同时试了**使用springboot参数的方法不可行**：

1. 启动命令加参数--apollo.configService=xxx
2. 在springboot的配置文件中加上配置apollo.configService
