### ISSUE TITLE
openapi里是不是没有灰度的接口,还有删除namespace的接口

### ISSUE THREAD

**Issue by oldandwang** [ctripcorp/apollo#2924]
有个需求想通过接口对apollo进行配置操作。发现文档/sdk里找不到接口

**Comment by nobodyiam** [comment]
灰度 sdk中没有，接口是有实现的，可以看下 #1518

**Comment by oldandwang** [comment]
> 灰度 sdk中没有，接口是有实现的，可以看下 #1518

apollo/apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/NamespaceBranchController.java

**Comment by oldandwang** [comment]
> 灰度 sdk中没有，接口是有实现的，可以看下 #1518
com.ctrip.framework.apollo.openapi.v1.controller.NamespaceBranchController#findBranch

**Comment by oldandwang** [comment]
> 灰度 sdk中没有，接口是有实现的，可以看下 #1518

com.ctrip.framework.apollo.openapi.v1.controller.NamespaceBranchController#findBranch

![image](https://user-images.githubusercontent.com/16732036/74588090-a7164f00-5034-11ea-8816-bf2c39729e23.png)
这个方法 mapping 是不是写少了一个 {env}

**Comment by nobodyiam** [comment]
没有少写

**Comment by oldandwang** [comment]
@nobodyiam

**Comment by thinkin** [comment]
借楼问下 有第三方的sdk jar包支持灰度发布吗?
