### ISSUE TITLE
ConfigurationProperties中的ApolloConfigChangeListener在每次刷新配置后增加一次调用

### ISSUE THREAD

**Issue by ZetaChoi** [ctripcorp/apollo#2925]
``` java
@ConfigurationProperties(prefix = "object.sample")
@Component
public class SampleObjectVariable {
    private int expireSeconds = 0;
    private String clusterNodes = "";
    private int commandTimeout = 0;

    private Map<String, String> someMap = Maps.newLinkedHashMap();
    private List<String> someList = Lists.newLinkedList();

    @Autowired
    private ApplicationContext applicationContext;
    @ApolloConfigChangeListener
    private void onChange(ConfigChangeEvent changeEvent) {
        this.applicationContext.publishEvent(new EnvironmentChangeEvent(changeEvent.changedKeys()));
        System.out.println("objectApolloConfigRefresher: " + this);
    }
}
```

每次在后台发布一次配置，onChange方法都会增加一次调用，如图：
![image](https://user-images.githubusercontent.com/11292361/74898928-4ee5a100-53d6-11ea-95a8-1b5ab0086822.png)

demo已上传到Apollo技术支持3群。

**Comment by nobodyiam** [comment]
`this.applicationContext.publishEvent(new EnvironmentChangeEvent(changeEvent.changedKeys()));` 会触发`org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory#initializeBean(java.lang.Object, java.lang.String)`进而会调用`com.ctrip.framework.apollo.spring.annotation.ApolloProcessor#postProcessBeforeInitialization`

所以@ApolloConfigChangeListener不要放在会被重新初始化的bean里面
