### ISSUE TITLE
yaml 强制类型报错

### ISSUE THREAD

**Issue by ywf4026** [ctripcorp/apollo#2926]
HI, 遇到个问题：

Apollo上的Yaml配置：
redis.config.aroundpeople:
    **codec: !!org.redisson.codec.JsonJacksonCodec {}**
    masterSlaveServersConfig:

代码里的对应配置：
public class Config {
    **private Codec codec;**
    private ExecutorService executor;

启动报错：
Failed to bind properties under 'redis.config.aroundpeople.codec' to org.redisson.client.codec.Codec:
Property: redis.config.aroundpeople.codec
Value: org.redisson.codec.JsonJacksonCodec
Origin: "redis.config.aroundpeople.codec" from property source "ApolloPropertySources"
Reason: **No converter found capable of converting from type [java.lang.String] to type [org.redisson.client.codec.Codec]**

报错原因好像在中间传输过程中，!!{} 强制类型的标识丢失了，导致误认为是个String格式，所以报String到CodeC转换的错误

**Comment by nobodyiam** [comment]
duplicated with #2896 

![image](https://user-images.githubusercontent.com/837658/75085680-808d7200-5566-11ea-84ae-d16a26271254.png)
