### ISSUE TITLE
“UNKNOWN” Service registered to Eureka using “apollo-all-in-one.jar”?

### ISSUE THREAD

**Issue by nengc** [ctripcorp/apollo#2931]
When using “apollo-all-in-one.jar” in the Windows 7, there will a “UNKNOWN” Service.
![image](https://user-images.githubusercontent.com/19792047/75149157-4d044080-573c-11ea-8df4-22dfcfcfc196.png)

**Comment by nobodyiam** [comment]
This is a known issue with `apollo-all-in-one.jar`, it won't happen with standard deployments
