### ISSUE TITLE
生产环境-20台集群，有1台未动态获取到配置信息

### ISSUE THREAD

**Issue by yhsmy** [ctripcorp/apollo#2933]
管理界面显示全部读取的最新实例值，但根据业务数据来看并未获取到最新的值。
线上重启后消失。原因尚未查明。

1.4.0版本，有人碰到过吗？

**Comment by nobodyiam** [comment]
apollo-client会确保配置送达应用程序，如果业务数据看没有获取到最新的值，可以看下配置读取逻辑
