### ISSUE TITLE
引用了公共的namespace，通过curl拉不到关联信息

### ISSUE THREAD

**Issue by LvBay** [ctripcorp/apollo#2937]
环境：PRO
复现：A应用有一些公共Namespace，B应用关联了A应用的Namespace。在管理页面看到B应用显示正常，能加载出引用信息以及相关的配置项。

但是通过不带缓存的http接口 
```
curl 'http://host:8181/configs/B/default/APP_ALL'
```
返回值中只包含了application中的配置信息，关联的namespace中的信息没拿到。
请问下这是啥子原因？

**Comment by nobodyiam** [comment]
可以先参照代码逻辑排查一下

**Comment by LvBay** [comment]
找到原因了，重启apollo-configservice，apollo-portal即可
