### ISSUE TITLE
webSocket 替代 http 长轮询

### ISSUE THREAD

**Issue by mghio** [ctripcorp/apollo#2939]
Apollo 在获取配置信息时，会发起一个长轮询，即客户端发送一个超时时间很长的 Request，服务器hold 住这个连接（Apollo 默认是 30s），在有新数据达到时返回 Response。http1.1 的连接默认使用长连接，虽然长连接在一个 TCP 连接上可以传输多个 Request/Response 消息对，但是本质上还是会造成资源的浪费、实时性不强等问题。而 WebSocket 只需要建立一次 Request/Response 消息对，之后都是 TCP 连接，避免了需要多次建立 Request/Response 消息对而产生的冗余头部信息。当 Apollo 配置被修改后，服务端可以通知客户端，客户端再来获取最新配置，整个流程可以在一个 WebSocket 中进行。

**Comment by nobodyiam** [comment]
感谢建议，websocket 确实有不少好处，不过考虑到多语言实现的复杂度以及负载均衡策略等多方面，websocket 替代 http 长轮询可能没有太大的优势
