### ISSUE TITLE
建议增加可自定义配置文件的选项

### ISSUE THREAD

**Issue by liuyanglxh** [ctripcorp/apollo#2940]
目前macOS Catalina配置文件路径是硬编码在代码里的：/home/opt/java/apollo-config
但是系统升级到10.15后，/home目录会默认被隐藏，需要手动打开，并且每次重启电脑后都要再操作一次
希望可以在/home/opt/java这个路径的基础上，增加一个备用路径（不被系统限制），或者可以自定义路径
谢谢~

**Comment by nisiyong** [comment]
mac貌似没遇到你说的问题，默认路径`/opt/data`没问题

**Comment by nobodyiam** [comment]
默认缓存路径是`/opt/data`，也可以[自定义缓存路径](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#1231-%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BC%93%E5%AD%98%E8%B7%AF%E5%BE%84)

**Comment by liuyanglxh** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Hi，    可能是之前没描述清楚，现在问题是：    我看源码这段代码：com.ctrip.framework.foundation.internals.provider.DefaultServerProvider:34    server.properties这个配置文件的路径是写死的：String path = Utils.isOSWindows() ? "C:/home/opt/java/apollo-config/settings/server.properties" : "/home/opt/java/apollo-config/settings/server.properties";    但是现在macos10.15有个问题，重启电脑后/home这个目录会被隐藏起来，需要操作一下才会显示，所以每次重启电脑都比较麻烦；    我的意思是能否增加一个可以指定server.properties文件的选项？
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                759339000
                            
                    
                        
                            
                                    759339000@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2020年03月5日 10:42，nisiyong<notifications@github.com> 写道： 


mac貌似没遇到你说的问题，默认路径/opt/data没问题



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by nobodyiam** [comment]
@liuyanglxh 这段代码应该是你们自己改过的，另外server.properties中的属性都是可以通过-D参数传入的。

**Comment by liuyanglxh** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    嗯嗯，好的，多谢
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                759339000
                            
                    
                        
                            
                                    759339000@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2020年03月21日 20:51，Jason Song<notifications@github.com> 写道： 




@liuyanglxh 这段代码应该是你们自己改过的，另外server.properties中的属性都是可以通过-D参数传入的。



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
