### ISSUE TITLE
配置更新一致性问题

### ISSUE THREAD

**Issue by Parallelline1996** [ctripcorp/apollo#2941]
Apollo支持了配置的热发布，在v0.10.0版本支持了热更新。

而当前我在使用Spring Cloud Config的执行热更新的时候，通过阅读源码，以及简单测试，发现如果多个配置类进行热更新的时候，会出现部分配置类更新，部分配置类未更新的中间状态。但此时服务仍可以对外提供服务。但我们认为这个不太能接受。

请问：Apollo能否保证更新的原子性，即多个配置类处于相同的配置版本？或者，Apollo在实际生产应用中，采用了什么方式能避免这个非一致性的问题吗？还是说，生产中还是尽量不使用热更新？

**Comment by nobodyiam** [comment]
如果程序中强依赖配置同时更新的话，可以通过API接入方式来实现，比如把相关配置放在同一个对象中，然后监听更新事件后通过类似copy on write的方式实现
