### ISSUE TITLE
portal无法创建其它格式的namespace

### ISSUE THREAD

**Issue by luojieio** [ctripcorp/apollo#2944]
xml格式的namespace怎么创建的？只能通过API吗？portal上创建的namespace只有properties

**Comment by Anilople** [comment]
> xml格式的namespace怎么创建的？只能通过API吗？portal上创建的namespace只有properties

确保你知道如何通过portal的web界面，进入这个页面，然后就可以了
<img width="616" alt="create-xml" src="https://user-images.githubusercontent.com/15523186/76210732-ad68a700-623f-11ea-8b76-ef41852f2398.PNG">

**Comment by luojieio** [comment]
感谢，不过为何公共的不允许其它格式呢？

**Comment by Anilople** [comment]
> 感谢，不过为何公共的不允许其它格式呢？

可能是设计之处没有考虑那么多需求吧，你可以整理一下，提个issue讨论一下哈
