### ISSUE TITLE
源码构建的一些问题

### ISSUE THREAD

**Issue by zhaokejin** [ctripcorp/apollo#2946]
我看到了这个源码构建[源码构建](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#222-%E9%80%9A%E8%BF%87%E6%BA%90%E7%A0%81%E6%9E%84%E5%BB%BA)

假如我的机器上8080,8070,8090都被占用了，我想通过源码构建该怎么构建，修改哪些端口号构建呢？

**Comment by Anilople** [comment]
如果不清楚如何在构建时修改端口号，推荐使用[releases](https://github.com/ctripcorp/apollo/releases)中发布的版本。

**Comment by Anilople** [comment]
> 我看到了这个源码构建[源码构建](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#222-%E9%80%9A%E8%BF%87%E6%BA%90%E7%A0%81%E6%9E%84%E5%BB%BA)
> 
> 假如我的机器上8080,8070,8090都被占用了，我想通过源码构建该怎么构建，修改哪些端口号构建呢？

如果不清楚如何在构建时修改端口号，推荐使用[releases](https://github.com/ctripcorp/apollo/releases)中发布的版本。

**Comment by zhaokejin** [comment]
> > 我看到了这个源码构建[源码构建](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#222-%E9%80%9A%E8%BF%87%E6%BA%90%E7%A0%81%E6%9E%84%E5%BB%BA)
> > 假如我的机器上8080,8070,8090都被占用了，我想通过源码构建该怎么构建，修改哪些端口号构建呢？
> 
> 如果不清楚如何在构建时修改端口号，推荐使用[releases](https://github.com/ctripcorp/apollo/releases)中发布的版本。

我的意思是源码构建，以为端口号被占用了，才会修改，那个是不改端口的呀

**Comment by Anilople** [comment]
> > > 我看到了这个源码构建[源码构建](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#222-%E9%80%9A%E8%BF%87%E6%BA%90%E7%A0%81%E6%9E%84%E5%BB%BA)
> > > 假如我的机器上8080,8070,8090都被占用了，我想通过源码构建该怎么构建，修改哪些端口号构建呢？
> > 
> > 
> > 如果不清楚如何在构建时修改端口号，推荐使用[releases](https://github.com/ctripcorp/apollo/releases)中发布的版本。
> 
> 我的意思是源码构建，因为端口号被占用了，才会修改，那个是不改端口的呀

所以你是想自己打包，但是打包过程中因为端口已经被占用，导致你打包失败？

**Comment by zhaokejin** [comment]
> > > > 我看到了这个源码构建[源码构建](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#222-%E9%80%9A%E8%BF%87%E6%BA%90%E7%A0%81%E6%9E%84%E5%BB%BA)
> > > > 假如我的机器上8080,8070,8090都被占用了，我想通过源码构建该怎么构建，修改哪些端口号构建呢？
> > > 
> > > 
> > > 如果不清楚如何在构建时修改端口号，推荐使用[releases](https://github.com/ctripcorp/apollo/releases)中发布的版本。
> > 
> > 
> > 我的意思是源码构建，因为端口号被占用了，才会修改，那个是不改端口的呀
> 
> 所以你是想自己打包，但是打包过程中因为端口已经被占用，导致你打包失败？

导致部署上拉取失败，应该是configservice端口没有改好

**Comment by nobodyiam** [comment]
可以修改scripts/startup.sh中的SERVER_PORT

**Comment by zhaokejin** [comment]
> 可以修改scripts/startup.sh中的SERVER_PORT

可以了  谢谢
