### ISSUE TITLE
DefaultConfig中getProperty()和getIntProperty()实现方式为什么不一样

### ISSUE THREAD

**Issue by aitangyong** [ctripcorp/apollo#2947]
**Is your feature request related to a problem? Please describe.**
在高并发的情况下，如果配置值是string，通过getProperty存在性能问题，底层实现基于Properties(HashTable)；而getIntProperty没有这个问题，底层实现是增加了一次guava cache代理。

**Describe the solution you'd like**
我觉得getProperty也应该做一层缓存

**Describe alternatives you've considered**

**Additional context**

**Comment by aitangyong** [comment]
@nobodyiam 请问作者是基于什么考虑的，不为string类型的配置值增加缓存呢

**Comment by nobodyiam** [comment]
getIntProperty涉及到类型转换，所以做了一层缓存。getProperty直接从内存中获取的，没必要再加一层缓存。

**Comment by aitangyong** [comment]
内存缓存用了HashTable，这个getProperty()在高并发情况下，性能会下降的很多；后来我们把数据结构换成了hashmap，性能问题就解决了



---原始邮件---
发件人: "Jason Song"<notifications@github.com&gt;
发送时间: 2020年3月14日(周六) 下午5:19
收件人: "ctripcorp/apollo"<apollo@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"aitangyong"<574007350@qq.com&gt;;
主题: Re: [ctripcorp/apollo] DefaultConfig中getProperty()和getIntProperty()实现方式为什么不一样 (#2947)




 
getIntProperty涉及到类型转换，所以做了一层缓存。getProperty直接从内存中获取的，没必要再加一层缓存。

**Comment by nobodyiam** [comment]
是直接把Properties替换成HashMap？

**Comment by aitangyong** [comment]
> 是直接把Properties替换成HashMap？

修改了DefaultConfig.java的成员变量
修改前：private final AtomicReference<Properties> m_configProperties;
修改后：private final AtomicReference<HashMap> m_configProperties;

对于apollo-client都是读取操作，对这个变量是只读；修改这个的变量的时候，看着也是copyOnWrite的模式，将新的hashmap替换掉老的map

**Comment by cciechao** [comment]
请问一下，接入邮件通知成功了吗？能共享一下实现步骤及代码吗，万分感谢。
