### ISSUE TITLE
[建议对eureka进行增强]应用上下文地址非“/”时，Home Page Url地址错误

### ISSUE THREAD

**Issue by master336** [ctripcorp/apollo#2948]
apollo-configservice application.yml中指定server.servlet.context-path: /configcenter/
bootstrap.yml 仍使用默认配置，导致Home Page Url 不正确，需显性配置：
eureka.instance.home-page-url-path: /configcenter 
eureka.client.defaultZone:http://${eureka.instance.hostname}:8080/configcenter/eureka/
该问题导致configservice注册不成功以及无法正确获取配置

**Comment by nobodyiam** [comment]
这个是指eureka没有识别server.servlet.context-path？
