### ISSUE TITLE
1.6版本什么时候发布？

### ISSUE THREAD

**Issue by kelystor** [ctripcorp/apollo#2949]
文档（[https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#4-portal%E5%A6%82%E4%BD%95%E5%A2%9E%E5%8A%A0%E7%8E%AF%E5%A2%83](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#4-portal%E5%A6%82%E4%BD%95%E5%A2%9E%E5%8A%A0%E7%8E%AF%E5%A2%83)）有提到1.6版本支持直接自定义环境（而不需要修改代码），但releases页面未看到有1.6版本可以下载，请问什么时候会发布呢？

**Comment by nobodyiam** [comment]
预计下周

**Comment by nobodyiam** [comment]
[v1.6.1](https://github.com/ctripcorp/apollo/releases/tag/v1.6.1)已发布
