### ISSUE TITLE
Portal 对Https的支持

### ISSUE THREAD

**Issue by cjk87927** [ctripcorp/apollo#2954]
使用nginx做反向代理并配置https,但访问根路径会跳转到http上去
![image](https://user-images.githubusercontent.com/6744728/76412535-bd62c100-63ce-11ea-8a60-9032c59ff549.png)

Version: 1.5.1

**Comment by cjk87927** [comment]
不好意思,是由于nginx配置错误导致的问题
可用配置:
location / {
        proxy_pass http://apollo-portal;
        proxy_set_header   Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto "https";
    }

**Comment by feixia5712** [comment]
请教大佬如何配置的，登录进去之后就会跳转到http的80端口，还需要单独使用nginx做重定向吗

**Comment by chaoyebugao** [comment]
> 不好意思,是由于nginx配置错误导致的问题
> 可用配置:
> location / {
> proxy_pass http://apollo-portal;
> proxy_set_header Host $host;
> proxy_set_header X-Real-IP $remote_addr;
> proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> proxy_set_header X-Forwarded-Proto "https";
> }

配置了，还是一样...
