### ISSUE TITLE
是否可以提供类似Spring Cloud Config的服务端的加解密方案

### ISSUE THREAD

**Issue by hjdongxuxu** [ctripcorp/apollo#2955]
目前实现敏感信息的加解密方案都是在client 端完成的，意味着会暴露公钥在项目的本地配置中，这样的话，只要知道加密的内容（在 apollo 中配置的），就意味着我不需要有在线服务器的权限，就是可以直接解密拿到解密后的内容的，这样非常不安全。

是否可以提供类似 spring cloud config 的加解密方案？这样的话，只有在线的服务器才可以获取到解密后在线的敏感信息。
这样只要控制好在线服务、在线配置中心的访问权限，在其他的环境就无法去获取到解密后的信息了，也能方便的实现 spring cloud config 到 apollo 的迁移了

**Comment by nobodyiam** [comment]
1.6.0版本支持了access key机制来实现敏感配置的获取，可以看下是否满足需求 #2828

**Comment by hjdongxuxu** [comment]
看了这块，access key主要还是用来做访问鉴权的，但是配置本身还是明文，如果有访问配置或者数据库的权限，还是能够看到明文的配置的。
利用 accessKey 只能通过控制敏感配置的权限的方式来一定程度了实现对于敏感配置的安全控制。
PS：还是期望后续版本能够直接实现对于加密配置的支持，目前看了一些方案，只能通过覆盖DefaultConfig的方式去实现对于配置的加密支持。

**Comment by nobodyiam** [comment]
可以参考下 https://github.com/ctripcorp/apollo-use-cases/tree/master/spring-boot-encrypt

**Comment by nobodyiam** [comment]
see #3187
