### ISSUE TITLE
项目下namespace太多，希望可以有隐藏功能或者搜索namespace的功能，谢谢

### ISSUE THREAD

**Issue by junozhou** [ctripcorp/apollo#2957]

**Comment by nobodyiam** [comment]
现在默认超过10个namespace就会自动隐藏的

![image](https://user-images.githubusercontent.com/837658/76679373-ec6d7280-661a-11ea-8159-cd903a018681.png)

**Comment by christinkaka** [comment]
namespace多的话确实是个问题，即使显示隐藏了，最后刷页面还要查询public状态，这个比较耗时
