### ISSUE TITLE
Value注解解析List,Duration失效

### ISSUE THREAD

**Issue by wuweidi** [ctripcorp/apollo#2967]
spring的@Value注解支持List或者Duration类型的配置
#### application.proporties
```
test.list=AAA,BBB
test.time=5m
```

#### Test.java
```
//可得到 list=["AAA","BBB"] 
@Value("${test.list}")
private List<String> list;

//可得到time为5分钟
@Value("${test.time}")
private Duration time;
```
但是集成apollo以后，以上两种类型就无法解析了；
虽然Apollo接入文档里面有ApolloJsonValue注解可以解决List的问题，但Duration仍然还没找到合适替代方式；
如果能兼容原来spring的解析方式，开发者就可以更平滑的接入apollo，而不需要在代码层面调整配置的读取方式了。

**Comment by nobodyiam** [comment]
请上传一个最简的demo协助定位问题，我尝试按照你的说明在本地application.properties中配置，`@Value`提示失败

```java
Caused by: java.lang.IllegalStateException: Cannot convert value of type 'java.lang.String' to required type 'java.time.Duration': no matching editors or conversion strategy found

```

**Comment by wuweidi** [comment]
> 请上传一个最简的demo协助定位问题，我尝试按照你的说明在本地application.properties中配置，`@Value`提示失败
> 
> ```java
> Caused by: java.lang.IllegalStateException: Cannot convert value of type 'java.lang.String' to required type 'java.time.Duration': no matching editors or conversion strategy found
> ```

**Comment by wuweidi** [comment]
就是这个提示
直接用springboot应用，不加入apollo依赖和注解，duration类型是可以支持的
但是假如依赖和和Apollo注解后，就会把这个错了，也就是我如题说的失效问题

**Comment by nobodyiam** [comment]
我本地构造了一个不依赖apollo的spring boot项目，还是报前面我贴的这个错

**Comment by wuweidi** [comment]
实际是在两个springboot项目中使用的，都是我自己搭建的应用，能分析出的差异就是，一个依赖apollo，另一个没有依赖。
但是我刚刚又试了下，用一个新的springboot应用，依赖或不依赖，都没有报错，跟我预期不太一样，我周一回公司了再试验下。
Issue我先关闭，确认以后再开启。
