### ISSUE TITLE
添加的备注怎么可以获取到

### ISSUE THREAD

**Issue by lifenglsf** [ctripcorp/apollo#2968]
通过http的api获取配置，发现无法获取配置对应的备注内容，有什么办法可以获取备注内容吗。这个备注内容就是对每个配置项的说明

**Comment by nobodyiam** [comment]
openapi可以获取

**Comment by lifenglsf** [comment]
> openapi可以获取

有openapi的相关资料的地址吗

**Comment by lifenglsf** [comment]
@nobodyiam 有openapi相关资料的地址吗，wiki中没有看到

**Comment by nobodyiam** [comment]
https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0
