### ISSUE TITLE
关于自定义Apollo-client的问题

### ISSUE THREAD

**Issue by szxiaoanda** [ctripcorp/apollo#2970]
目前已通过LegacyMetaServerProvider实现Apollo-client，想做到多个项目依赖自定义的Apollo-client零配置使用Apollo，但是目前只能实现地址的零配置，appid还是需要各个项目指定，请问有方法可以不用各个项目指定appid吗？

**Comment by Anilople** [comment]
将appid设置成和instance在注册中心上的名字一致是否可行？

**Comment by nobodyiam** [comment]
可以参考 com.ctrip.framework.apollo.spring.boot.ApolloApplicationContextInitializer#initializeSystemProperty
