### ISSUE TITLE
对于ENV枚举中没有的环境，会报unknown，官方解决方案不友好

### ISSUE THREAD

**Issue by number-0** [ctripcorp/apollo#2971]
在jvm参数指定环境 -Denv=DEV6，启动后发现如下日志
“Located meta server address *** for env UNKNOWN from com.ctrip.framework.apollo.internals.DefaultMetaServerProvider”，

原因：ENV枚举中不支持DEV6，所以报了此日志

官方解决方案：修改Env和EnvUtils源码，然后重新打包，这个操作感觉不是很友好
建议：有各种途径可以解决，但不要报 env UNKNOWN，或者去修改源码，看到这个日志真是浑身不舒服

**Comment by nobodyiam** [comment]
apollo-client中已经不再强依赖env了，只需要指定`apollo.meta`就可以了
