### ISSUE TITLE
多个用户密码失效

### ISSUE THREAD

**Issue by shelltea** [ctripcorp/apollo#2975]
我们使用版本是1.4.0，最近一段时间，不断有用户反馈无法登录，提示密码错误，已排除输入错误或人为修改密码导致。重置密码后正常。

搜索了一下Issues，发现之前已有用户反馈：#2526，但没有找到具体原因。

我们目前对Authorities表增加了一些监控，同时发现这个表同一用户会有多条重复记录：
![image](https://user-images.githubusercontent.com/864375/77278572-a8552e80-6cfa-11ea-94b9-31853ff8f90f.png)
也发现有的用户完全没有记录。

**Comment by nobodyiam** [comment]
是否曾经手工修改过Users或Authorities表？目前疑似是下面这个PR引入的一个问题

https://github.com/ctripcorp/apollo/pull/2016/files#diff-112777af9fb5c15325455cbaf745ce43R244

**Comment by shelltea** [comment]
> 是否曾经手工修改过Users或Authorities表？目前看疑似是下面这个PR引入的一个问题
> 
> https://github.com/ctripcorp/apollo/pull/2016/files#diff-112777af9fb5c15325455cbaf745ce43R244

没有手工修改过这两个表，增加用户都是在界面操作的。

**Comment by kezhenxu94** [comment]
fixed by #2977
