### ISSUE TITLE
前端portal超时时间无法设置，现在特别长？

### ISSUE THREAD

**Issue by longshenaa** [ctripcorp/apollo#2979]
- [ ] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) of this repository and believe that this is not a duplicate.

**Describe the bug**

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

### Additional Details & Logs

- Version
- Error logs
- Configuration
- Platform and Operating System

**Comment by nobodyiam** [comment]
麻烦详细描述下问题

**Comment by longshenaa** [comment]
当我登录上portal之后，如果不操作，session几乎不会超时。设置超时时间有时也不会严格执行，是apollo有啥机制么？发自我的华为手机-------- 原始邮件 --------发件人： Jason Song <notifications@github.com>日期： 2020年3月28日周六 19:43收件人： ctripcorp/apollo <apollo@noreply.github.com>抄送： longshenaa <yanqingzhangzz@sina.com>, Author <author@noreply.github.com>主    题： Re: [ctripcorp/apollo] 前端portal超时时间无法设置，现在特别长？ (#2979)

麻烦详细描述下问题

**Comment by nobodyiam** [comment]
session不超时是特意这么设计的，前端有一个定期刷新session的机制。

**Comment by longshenaa** [comment]
好的，谢谢。麻烦问下，这是基于什么考虑的呢，如果前端会话一直不超时，感觉不是很安全呢。发自我的华为手机-------- 原始邮件 --------发件人： Jason Song <notifications@github.com>日期： 2020年3月29日周日 11:09收件人： ctripcorp/apollo <apollo@noreply.github.com>抄送： longshenaa <yanqingzhangzz@sina.com>, Author <author@noreply.github.com>主    题： Re: [ctripcorp/apollo] 前端portal超时时间无法设置，现在特别长？ (#2979)

session不超时是特意这么设计的，前端有一个定期刷新session的机制。

**Comment by nobodyiam** [comment]
主要考虑是内网使用，所以希望用户可以保留页面，随时可用

**Comment by longshenaa** [comment]
那怎么设置可以使得会话能有超时时间呢，源码中没有找到啊发自我的华为手机-------- 原始邮件 --------发件人： Jason Song <notifications@github.com>日期： 2020年4月4日周六 15:39收件人： ctripcorp/apollo <apollo@noreply.github.com>抄送： longshenaa <yanqingzhangzz@sina.com>, Author <author@noreply.github.com>主    题： Re: [ctripcorp/apollo] 前端portal超时时间无法设置，现在特别长？ (#2979)

主要考虑是内网使用，所以希望用户可以保留页面，随时可用
