### ISSUE TITLE
SpringBootTest单元测试，使用不同的ActiveProfiles，生成ApplicationContext时，配置属性未更新

### ISSUE THREAD

**Issue by huangzhonghao** [ctripcorp/apollo#2983]
背景：有两个Test方法，需要连接不同的数据库，所以配置了不同的ActiveProfiles

@RunWith(SpringRunner.class)
@SpringBootTest
@ActiveProfiles("dev")

@RunWith(SpringRunner.class)
@SpringBootTest
@ActiveProfiles("uat")

期望：
两个测试方法分别连接不同的数据库

实际：
两个测试方法都连接在一个数据库

原因：
springboottest，会根据ActiveProfiles不同，创建两个application context，断点调试发现配置项还是一样的，导致连接的数据库还是同一个

这种场景有什么推荐的解决方案？

ref：https://reflectoring.io/spring-boot-test/

**Comment by nobodyiam** [comment]
可以看下`org.springframework.test.annotation.DirtiesContext`，另外这个问题似乎和apollo没啥直接关联？

**Comment by huangzhonghao** [comment]
补充一下情况
1、profiles配置了不同的集群
2、一个命令运行着两个测试

我调试代码发现，虽然初始化了2次applicationContext，但是ConfigUtil.initCluster只会被执行一次，导致集群不会修改，拉取的配置还是同一个

**Comment by nobodyiam** [comment]
可以看下 apollo-mockserver 这个项目是否满足你的场景
