### ISSUE TITLE
配置获取的一个优化建议

### ISSUE THREAD

**Issue by aitangyong** [ctripcorp/apollo#2987]
apollo是根据cluster+namespace+key获取的，
cluster不存在就用default集群的，
如果cluster集群存在，但是namespace不存在(未发布)，也是使用dealut集群下的配置，
如果cluster下存在namespace并且已经发布了，就不会使用default集群下的配置了！

一个应用部署到3个机房，application下的kv其实差别不大，大部分都是一样的；但是由于上面的机制，必须配置多次；修改的话，几个集群都要修改，比较麻烦也容易改漏。

所以想请教下，能否优化下上面的流程，如果key在cluser+namespace不存在，就去找default下面的。当然有些情况是不需要的，比如删除。能否对key进行一些约束，比如符合某些格式的key，就继续从default寻找。
@nobodyiam

**Comment by Anilople** [comment]
> apollo是根据cluster+namespace+key获取的，
> cluster不存在就用default集群的，
> 如果cluster集群存在，但是namespace不存在(未发布)，也是使用dealut集群下的配置，
> 如果cluster下存在namespace并且已经发布了，就不会使用default集群下的配置了！
> 
> 一个应用部署到3个机房，application下的kv其实差别不大，大部分都是一样的；但是由于上面的机制，必须配置多次；修改的话，几个集群都要修改，比较麻烦也容易改漏。
> 
> 所以想请教下，能否优化下上面的流程，如果key在cluser+namespace不存在，就去找default下面的。当然有些情况是不需要的，比如删除。能否对key进行一些约束，比如符合某些格式的key，就继续从default寻找。
> @nobodyiam

你的意思是，配置的粒度变成某条k-v，然后根据集群的排序，会产生优先级，就像namspace那样？

**Comment by aitangyong** [comment]
> > apollo是根据cluster+namespace+key获取的，
> > cluster不存在就用default集群的，
> > 如果cluster集群存在，但是namespace不存在(未发布)，也是使用dealut集群下的配置，
> > 如果cluster下存在namespace并且已经发布了，就不会使用default集群下的配置了！
> > 一个应用部署到3个机房，application下的kv其实差别不大，大部分都是一样的；但是由于上面的机制，必须配置多次；修改的话，几个集群都要修改，比较麻烦也容易改漏。
> > 所以想请教下，能否优化下上面的流程，如果key在cluser+namespace不存在，就去找default下面的。当然有些情况是不需要的，比如删除。能否对key进行一些约束，比如符合某些格式的key，就继续从default寻找。
> > @nobodyiam
> 
> 你的意思是，配置的粒度变成某条k-v，然后根据集群的排序，会产生优先级，就像namspace那样？

嗯是的， 觉得目前以namespace的维度，有点大。多机房部署的时候，配置量多

**Comment by Anilople** [comment]
> > > apollo是根据cluster+namespace+key获取的，
> > > cluster不存在就用default集群的，
> > > 如果cluster集群存在，但是namespace不存在(未发布)，也是使用dealut集群下的配置，
> > > 如果cluster下存在namespace并且已经发布了，就不会使用default集群下的配置了！
> > > 一个应用部署到3个机房，application下的kv其实差别不大，大部分都是一样的；但是由于上面的机制，必须配置多次；修改的话，几个集群都要修改，比较麻烦也容易改漏。
> > > 所以想请教下，能否优化下上面的流程，如果key在cluser+namespace不存在，就去找default下面的。当然有些情况是不需要的，比如删除。能否对key进行一些约束，比如符合某些格式的key，就继续从default寻找。
> > > @nobodyiam
> > 
> > 
> > 你的意思是，配置的粒度变成某条k-v，然后根据集群的排序，会产生优先级，就像namspace那样？
> 
> 嗯是的， 觉得目前以namespace的维度，有点大。多机房部署的时候，配置量多

**同步配置**或许有用

![image](https://user-images.githubusercontent.com/15523186/78014471-8f8fed00-737a-11ea-8500-c0463bc466be.png)

**Comment by aitangyong** [comment]
> > > > apollo是根据cluster+namespace+key获取的，
> > > > cluster不存在就用default集群的，
> > > > 如果cluster集群存在，但是namespace不存在(未发布)，也是使用dealut集群下的配置，
> > > > 如果cluster下存在namespace并且已经发布了，就不会使用default集群下的配置了！
> > > > 一个应用部署到3个机房，application下的kv其实差别不大，大部分都是一样的；但是由于上面的机制，必须配置多次；修改的话，几个集群都要修改，比较麻烦也容易改漏。
> > > > 所以想请教下，能否优化下上面的流程，如果key在cluser+namespace不存在，就去找default下面的。当然有些情况是不需要的，比如删除。能否对key进行一些约束，比如符合某些格式的key，就继续从default寻找。
> > > > @nobodyiam
> > > 
> > > 
> > > 你的意思是，配置的粒度变成某条k-v，然后根据集群的排序，会产生优先级，就像namspace那样？
> > 
> > 
> > 嗯是的， 觉得目前以namespace的维度，有点大。多机房部署的时候，配置量多
> 
> **同步配置**或许有用
> 
> ![image](https://user-images.githubusercontent.com/15523186/78014471-8f8fed00-737a-11ea-8500-c0463bc466be.png)

嗯目前我们是这样做的，不过还是觉得有点麻烦，比较是人操作，容易漏

**Comment by nobodyiam** [comment]
目前的模型设计下，不太能实现key粒度级别的优先级。可以考虑使用公共namespace，把共性的配置放在公共namespace中，个性化的配置放到各自cluster下
