### ISSUE TITLE
the same name of cluster.  can't delete.

### ISSUE THREAD

**Issue by 474420502** [ctripcorp/apollo#2988]
**Describe the bug**

![image](https://user-images.githubusercontent.com/9397764/77897830-c7306380-72ac-11ea-9f33-0ae4eb81a31b.png)

![image](https://user-images.githubusercontent.com/9397764/77897737-aa942b80-72ac-11ea-9da5-b50cb26f41c7.png)

**To Reproduce**
1.  create  two the same name of  cluster.  
2.  delete cluster
.
**Expected behavior**

**Screenshots**

### Additional Details & Logs

- Version 1.4.0
- Error logs 
- Configuration
- Platform and Operating System

**Comment by nobodyiam** [comment]
I think the problem is how to avoid creating 2 clusters with the same name, as there is no unique index on the table...

How about you manually soft delete one of the 2 duplicated cluster in the db?

**Comment by 474420502** [comment]
our  development say that  normal operation with 2 times.

**Comment by nobodyiam** [comment]
Could you please provide the steps to duplicate this issue? 
We have a demo environment: http://106.54.227.205/

**Comment by 474420502** [comment]
I have detected this bug @nobodyiam !
1 .that need want 2 ENV that  point to the same adress. 
2. the  name lenght is 32 char.
 
![image](https://user-images.githubusercontent.com/9397764/79036025-87e00c00-7bf6-11ea-848a-b17ac4c51cd4.png)
![image](https://user-images.githubusercontent.com/9397764/79036048-cfff2e80-7bf6-11ea-9f3b-6470018a803c.png)

click

**Comment by 474420502** [comment]
i reproduce this bug.

**Comment by nobodyiam** [comment]
`1 .that need want 2 ENV that point to the same adress.`

This is the root cause, each environment should point to a different set of services.
