### ISSUE TITLE
docker-compose up 无法拉取镜像

### ISSUE THREAD

**Issue by ericse9899** [ctripcorp/apollo#2992]
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ]

**Describe the bug**
以apollo-build-scripts执行 docker-compose up时无法拉取镜像.
Pulling apollo-quick-start (apollo-quick-start:latest)...
ERROR: pull access denied for apollo-quick-start, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

### Additional Details & Logs

- CentOS 7
- Docker version 19.03.8, build afacb8b
- docker-compose version 1.18.0, build 8dd22a9

**Comment by nobodyiam** [comment]
检查下本地docker的配置吧，镜像是可以拉取的

https://hub.docker.com/r/nobodyiam/apollo-quick-start

**Comment by whyyue** [comment]
> 检查下本地docker的配置吧，镜像是可以拉取的
> 
> https://hub.docker.com/r/nobodyiam/apollo-quick-start

我也遇到这个问题，搜了一些解决方案都不行https://blog.csdn.net/weixin_43414429/article/details/97003932
