### ISSUE TITLE
/notifications/v2  400

### ISSUE THREAD

**Issue by metadeng** [ctripcorp/apollo#2993]
本地调试启动的时候能获取到配置，但是一会出现：
![image](https://user-images.githubusercontent.com/13793036/78245997-fe0bb100-751a-11ea-98ef-4b1f115d8e50.png)

curl 对应的接口返回：
`{"timestamp":"2020-04-02T19:45:34.006+0800","status":400,"error":"Bad Request","message":"InvalidAppId","path":"/notifications/v2"}`
请问这是配置错误还是？

**Comment by nobodyiam** [comment]
是否修改过apollo-client的代码？可以结合下面的服务端代码看下
com.ctrip.framework.apollo.configservice.filter.ClientAuthenticationFilter#doFilter

**Comment by metadeng** [comment]
未修改相应代码

**Comment by nobodyiam** [comment]
到 com.ctrip.framework.apollo.configservice.filter.ClientAuthenticationFilter#doFilter debug一下吧？
