### ISSUE TITLE
CAS认证问题

### ISSUE THREAD

**Issue by lklikai** [ctripcorp/apollo#2994]
我想问一下portal如何接入第三方的系统里面，配置方面如何更改

**Comment by nobodyiam** [comment]
参考下[Portal 实现用户登录功能](https://github.com/ctripcorp/apollo/wiki/Portal-%E5%AE%9E%E7%8E%B0%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95%E5%8A%9F%E8%83%BD)
