### ISSUE TITLE
添加 Properties getProps() 方法一次性获取所有配置

### ISSUE THREAD

**Issue by wangxianghu** [ctripcorp/apollo#2995]
**Is your feature request related to a problem? Please describe.**
    对于常规Java应用，apollo当前提供的方法已经完全够用，但是在大数据环境下使用时，虽说可以使用Java客户端获取指定的配置，但是诸如Flink这样的大数据计算引擎，其内部已经封装了获取参数的工具类 ParameterTool，以及Flink自己实现的Configuration配置类，这些内置的配置类一次配置，全生命周期可用，非常方便。 而apollo当前提供Config接口不能与ParameterTool以及Configuration集成，而jdk中的Properties可以。所以希望通过Properties作为媒介，实现一次性获取apollo提供的所有参数。当然，先获取所有属性名再遍历获取所有值也可行，但是略显麻烦。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nobodyiam** [comment]
我注意到ParameterTool有`public static ParameterTool fromPropertiesFile(InputStream inputStream)`方法，可以加载一个input stream进来，所以可以使用下面的方式

```java
ConfigFile configFile = ConfigService.getConfigFile("application", ConfigFileFormat.Properties);
ParameterTool parameterTool = ParameterTool.fromPropertiesFile(new ByteArrayInputStream(configFile.getContent().getBytes()));
```
