### ISSUE TITLE
jar包无法下载

### ISSUE THREAD

**Issue by lklikai** [ctripcorp/apollo#2997]
<dependencies>
				<dependency>
					<groupId>com.ctrip.framework.apollo-sso</groupId>
					<artifactId>apollo-sso-ctrip</artifactId>
				</dependency>
				<dependency>
					<groupId>com.ctrip.framework.apollo-ctrip-service</groupId>
					<artifactId>apollo-email-service</artifactId>
				</dependency>
			</dependencies>
以上jar包无法下载，是携程的内部仓库吗？

**Comment by nobodyiam** [comment]
这几个包只在携程内部发布时会使用，归属在特定的maven profile下的。

**Comment by lklikai** [comment]
> 这几个包只在携程内部发布时会使用，归属在特定的maven profile下的。

那我们发布的时候就用不了cript这种profile了吗?

**Comment by nobodyiam** [comment]
不需要使用ctrip相关的profile，使用默认的打包脚本或者下载release包即可
