### ISSUE TITLE
使用Dockerfile构建的镜像，启动报错

### ISSUE THREAD

**Issue by shuangovo** [ctripcorp/apollo#3000]
sh: -Dspring.datasource.username=root: not found

**Comment by shuangovo** [comment]
这是我的docker-compose

version: '2.2'
services:
  apollo-configservice:
    build: apollo-configservice
    container_name: apollo-configsevice
    environment:
      DS_URL: jdbc:mysql://xxx:3306/ApolloConfigDB?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&autoReconnect=true
      DS_USERNAME: root
      DS_PASSWORD: root
    ports:
      - 8080:8080
    volumes:
      - ./logs/apollo-configservice:/opt/logs
    networks:
      - apollo
  apollo-adminservice:
    build: apollo-adminservice
    container_name: apollo-adminservice
    environment:
      DS_URL: jdbc:mysql://xxx:3306/ApolloConfigDB?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&autoReconnect=true
      DS_PASSWORD: root
      DS_PASSWORD: root
    ports:
      - 8090:8090
    volumes:
      - ./logs/apollo-adminservice:/opt/logs
    networks:
      - apollo
  apollo-portal:
    build: apollo-portal
    container_name: apollo-portal
    environment:
      DS_URL: jdbc:mysql://xxx:3306/ApolloPortalDB?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&autoReconnect=true
      DS_USERNAME: root
      DS_PASSWORD: root
      DEV_META: http://localhost:8080
    ports:
      - 8070:8070
    volumes:
      - ./logs/apollo-portal:/opt/logs
    networks:
      - apollo
networks:
  apollo:
    driver: bridge

**Comment by nobodyiam** [comment]
quick start使用的[demo.sh](https://github.com/nobodyiam/apollo-build-scripts/blob/master/demo.sh)没有识别DS_URL、DS_USERNAME等变量

**Comment by chanjjaeseo** [comment]
我也遇到了同样的问题，从release中下载1.6.1版本然后用dockerfile打包后启动日志中报错
"sh: -Dspring.datasource.username=root: not found"
如果去掉datasource中的url不包含"&"则不报错

附上启动参数
`
-Xms2048m -Xmx2048m -Xss256k -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=2048m -XX:SurvivorRatio=8 -XX:ParallelGCThreads=4 -XX:MaxTenuringThreshold=9 -XX:+DisableExplicitGC -XX:+ScavengeBeforeFullGC -XX:SoftRefLRUPolicyMSPerMB=0 -XX:+ExplicitGCInvokesConcurrent -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/logs/100003172/HeapDumpOnOutOfMemoryError/ -XX:-OmitStackTraceInFastThrow -Duser.timezone=Asia/Shanghai -Dclient.encoding.override=UTF-8 -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom -Dspring.datasource.url=jdbc:mysql://xxxxx:3306/ApolloConfigDB?useSSL=false&characterEncoding=utf8 -Dspring.datasource.username=root -Dspring.datasource.password=password -Dserver.port=8090 -Dlogging.file=/opt/logs/100003172/apollo-adminservice.log
`

**Comment by nobodyiam** [comment]
@chanjjaeseo datasource的url用引号括起来试试

**Comment by chanjjaeseo** [comment]
> @chanjjaeseo datasource的url用引号括起来试试

你好，宋顺大神我现在已经解决了这个问题。
只需要把docker-compose文件的环境变量替换为如下: 
`
environment:
      - spring_datasource_url : jdbc:mysql://xxxxx:3306/ApolloConfigDB?useSSL=false&characterEncoding=utf8
      - spring_datasource_username: root
      - spring_datasource_password: password
`
目前猜测这个问题可能是由于-D启动参数包含特殊符号，导致异常转码产生的。
也希望你们如果认为这个方案可行的话更新下官方文档，因为可能也会有很多人跟我遇到同样的问题。

**Comment by shuangovo** [comment]
可以的，确实解决了

**Comment by nobodyiam** [comment]
感谢反馈，我提交了 PR #3098 ，可以避免这个问题
