### ISSUE TITLE
apollo配置加载优先级低于SpringBootCondition

### ISSUE THREAD

**Issue by kody1025** [ctripcorp/apollo#3001]
参考了https://github.com/ctripcorp/apollo/issues/2885#issue-544832098

版本：1.5.1

同时添加
# will inject 'application' namespace in bootstrap phase
apollo.bootstrap.enabled = true
# put apollo initialization before logging system initialization
apollo.bootstrap.eagerLoad.enabled=true

但发现还是Condition的matches方法在apollo配置加载前执行

**Comment by nobodyiam** [comment]
只需要设置`apollo.bootstrap.enabled`即可，可以参考下apollo-demo

https://github.com/ctripcorp/apollo/blob/be664483032c3b1aca075ee043f5d7fd97ee4c2e/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/spring/springBootDemo/config/SampleRedisConfig.java#L52

**Comment by kody1025** [comment]
已解决
如果要用yml，就需要用以下配置才能在spring bean创建前加载
# will inject 'application' and 'FX.apollo' namespaces in bootstrap phase
apollo.bootstrap.namespaces = application,application.yml
