### ISSUE TITLE
更新key值时，不存在就插入

### ISSUE THREAD

**Issue by jinhailli** [ctripcorp/apollo#3002]
现在修改配置时，如果不存在就会报错。
{
    "exception": "com.ctrip.framework.apollo.common.exception.NotFoundException",
    "message": "item not found for 1_yynovel_yynovel_conf_d default 1_yynovel_conf_test test123",
    "status": 404.0,
    "timestamp": "2020-04-09T10:29:12.302"
}。
想问一下，可以加一个功能，不存在就直接插入这个key吗？

**Comment by nobodyiam** [comment]
你是用的open api？有createOrUpdate的模式的，可以参考下

https://github.com/ctripcorp/apollo/blob/be664483032c3b1aca075ee043f5d7fd97ee4c2e/apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/client/ApolloOpenApiClient.java#L157

**Comment by jinhailli** [comment]
> 你是用的open api？有createOrUpdate的模式的，可以参考下
> 
> https://github.com/ctripcorp/apollo/blob/be664483032c3b1aca075ee043f5d7fd97ee4c2e/apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/client/ApolloOpenApiClient.java#L157

我们是用的Http REST接口，现在有这个功能的接口吗？

**Comment by jinhailli** [comment]
经过查看例子，发现更新配置时，url后面加上?createIfNotExists=true，并且在body的json里面加上"dataChangeCreatedBy":"user"例如：
{
    "key":"test123",
    "value":"3000",
    "comment":"超时时间",
    "dataChangeLastModifiedBy":"user",
    "dataChangeCreatedBy":"user"
}
就可以了，希望官方在文档上加上这个说明。
