### ISSUE TITLE
1.6.1版本portal跳过了登录接口且退出登录不了

### ISSUE THREAD

**Issue by chao1003** [ctripcorp/apollo#3003]
访问8070端口跳过了登录直接以apollo用户名进去了，点击退出登录重定向到/还是直接进去所以退不出去，输入url  8070/signin到登录接口后，输入用户名密码点击登录抛出异常 {"exception":"org.springframework.web.HttpRequestMethodNotSupportedException","message":"Request method \u0027POST\u0027 not supported","status":400,

**Comment by nobodyiam** [comment]
你是自己启动的吧，需要确保github和auth这两个profile都设置了

https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97#223-vm-options%E9%85%8D%E7%BD%AE

**Comment by chao1003** [comment]
谢谢，我是源码打包在测服部署的，在启动脚本里加上这个启动参数，可以了

> 你是自己启动的吧，需要确保github和auth这两个profile都设置了
> 
> https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97#223-vm-options%E9%85%8D%E7%BD%AE
谢谢，我是源码打包在测服部署的，在的启动脚本里加上这个启动参数，已经好使了
