### ISSUE TITLE
Apollo client自定义敏感信息加密打包后放入项目启动版本冲突问题

### ISSUE THREAD

**Issue by hujiangang-git** [ctripcorp/apollo#3004]
@Jason Song 由于我们使用apollo配置中心要对敏感信息加密我们对贵公司提供的client源码中的DefaultConfig 类中进行了加密信息的解密代码所以需要自己对client打jar包然后引用到项目中,但是打完的包引用到spring boot项目中之后,spring boot版本为2.0以上时启动报错(class org.springframework.boot.cloud.CloudFoundryVcapEnvironmentPostProcessor is not assignable to interface org.springframework.context.ApplicationListener),如果使用spring boot 1.5.X 版本可以正常使用由于项目业务需求项目需要使用2.0以上版本,请问贵公司开发团队解决方案,另外我们自己打的jar大小为9360k 而贵公司提供的 client.jar为173k请问是什么原因,谢谢

**Comment by nobodyiam** [comment]
如果只是改了一点逻辑，重新打包后9360K的话，可以看下是否打包步骤有问题，下面是我们的打包脚本：
`mvn clean deploy -pl apollo-client -am -DskipTests=true`
