### ISSUE TITLE
Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $

### ISSUE THREAD

**Issue by chenqin091017** [ctripcorp/apollo#3006]
- 使用`docker-quick-start`的方式在本地安装`apollo`；

- 然后在本地springboot项目里面，引入`apollo`相关配置；

>自己的springboot项目(版本`2.1.8.RELEASE`)未注册进`apollo`的`eureka-server`中，而是注册到另外eureka集群服务中

   - pom.xml
      ```
             <dependency>
			<groupId>com.alibaba.mq-amqp</groupId>
			<artifactId>mq-amqp-client</artifactId>
			<version>1.0.3</version>
		</dependency>
      ```
   - 代码
      ```
     @ApolloConfig
      private Config config;
      ```
- 为了解决环境问题，在启动项中，增加启动命令`-Denv=DEV`,以解决`Located meta server address http://localhost:8070 for env UNKNOWN from com.ctrip.framework.apollo.internals.DefaultMetaServerProvider`报错信息；

- 但是最终项目启动的时候，依然还会报错以下的错误日志；
```
Sync config failed, will retry. Repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository, reason: Get config services failed from http://localhost:8070/services/config?appId=appName&ip=192.168.136.247 [Cause: Could not complete get operation [Cause: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $ [Cause: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $]]]
```

**Comment by nobodyiam** [comment]
http://localhost:8070 => http://localhost:8080

**Comment by chenqin091017** [comment]
thanks

**Comment by cornyu** [comment]
我也遇到同样的报错，通过postman访问接口是可以拿到配置信息的，但是springboot启动就报错：
ApolloConfigException(Could not complete get operation) [Cause: JsonSyntaxException(java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $) [Cause: IllegalStateException(Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $)]]]
