### ISSUE TITLE
配置发布邮件通知

### ISSUE THREAD

**Issue by cciechao** [ctripcorp/apollo#3008]
配置发生变更发送邮件通知，要是能集成到UI上操作，是不是更方便一点？

**Comment by nobodyiam** [comment]
集成到UI操作具体是指？

目前apollo是支持发送邮件的，可以参考下：[3.2 Portal接入邮件服务](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97#32-portal%E6%8E%A5%E5%85%A5%E9%82%AE%E4%BB%B6%E6%9C%8D%E5%8A%A1)

**Comment by cciechao** [comment]
公司没有java开发，实现起来还是比较困难的

**Comment by czd890** [comment]
比如说,有一个UI管理页面可以配置邮件通知的相关参数 或者一个脚本导入参数也可以.

要实现的功能:可配置发送用的邮箱账号,密码,imap地址,是否启用等之类的, 不在需要自己实现自己的emailService. 尽量让项目做到不需要二次开发,开箱即用.
@cciechao 是这个意思吗?
@nobodyiam 是否有计划?

**Comment by nobodyiam** [comment]
@czd890 暂时没有很强的需求，不过欢迎贡献~

**Comment by cciechao** [comment]
@czd890 对，是这个意思....

**Comment by fushiqinghuan111** [comment]
邮件配置 没有发现  配置发件人密码字段

**Comment by nobodyiam** [comment]
@fushiqinghuan111 参考文档实现一下自己的EmailService
