### ISSUE TITLE
apollo c语言客户端

### ISSUE THREAD

**Issue by lzeqian** [ctripcorp/apollo#3009]
最近用nginx改造新版本网关，其中用到apollo，未发现有其他c端开源项目，通过apollorestapi实现了一个，希望对其他c端开发人员有所帮助，地址：https://github.com/lzeqian/apollo。

**Comment by nobodyiam** [comment]
非常感谢，已在wiki中更新

![image](https://user-images.githubusercontent.com/837658/79033367-50666500-7be0-11ea-8198-3a28444b071c.png)
