### ISSUE TITLE
回调函数无法到达

### ISSUE THREAD

**Issue by panyaowei** [ctripcorp/apollo#3010]
您好啊，我是容器访问，配置中心。配置能够读取到。但是回调的却无法读取，我观察界面上实力列表显示的是我客户端的容器IP，不是宿主机IP。导致访问不行。能够让配置中心读取到我的宿主机IP 而不是容器IP

**Comment by nobodyiam** [comment]
配置中心不是通过回调IP实现推送的，是客户端long polling实现的，所以和ip本质上没啥关系。可以打开客户端的DEBUG日志看下
