### ISSUE TITLE
jasypt -2.1.1 适配apollo 1.4.0  热更新失败

### ISSUE THREAD

**Issue by bigbug-dachong** [ctripcorp/apollo#3011]
jasypt -2.1.1 适配apollo 1.4.0  热更新失败

前提是不想用 jasypt -1.16.  需要使用2.1.1版本

查了现有 issue ，并没有解决方案，声称在 apollo - 1.4.0解决了热更新问题，但实测仍有问题

**Comment by kevin-pro** [comment]
同样的问题，不知道作者是否有计划修复？

**Comment by nobodyiam** [comment]
参考下 #2170 ？

**Comment by kevin-pro** [comment]
#2170 comment中给的方案看起来不是很好，能在apollo的代码里进行修复吗

**Comment by nobodyiam** [comment]
这个本质上应该是jasypt缓存值的问题，可以看下jasypt是否有刷新缓存的机制
