### ISSUE TITLE
Could not load configurations with appId: webhost, clusterName: default, namespace: application

### ISSUE THREAD

**Issue by MikyChow** [ctripcorp/apollo#3015]
apollo访问配置文件报404错误.
1. 配置已经发布
2. appid正确
3.url: http://106.54.227.205:8080/configs/webhost/default/application?ip=192.168.28.231
![image](https://user-images.githubusercontent.com/5389478/79405776-e414a880-7fc7-11ea-9ba6-644bb9daefa2.png)
![image](https://user-images.githubusercontent.com/5389478/79405800-ef67d400-7fc7-11ea-803a-b80a90209327.png)

**Comment by nobodyiam** [comment]
报404的namespace是`db`

**Comment by MikyChow** [comment]
多谢回复,因为我以为时namespace的问题,所以多弄了几个namespace,所以图片穿错了,
而且即使是db的namespace也应该有值才对吧
![image](https://user-images.githubusercontent.com/5389478/79704992-872a3280-82e6-11ea-92fc-f6a04a2ffe6b.png)

**Comment by nobodyiam** [comment]
你是在用Demo环境？但是这个环境并没有webhost这个appId

http://106.54.227.205

**Comment by MikyChow** [comment]
> 你是在用Demo环境？但是这个环境并没有webhost这个appId
> 
> http://106.54.227.205

不是demo环境哦,我在本地k8s集群搭建的环境.可以在地址栏里面看到

**Comment by MikyChow** [comment]
> 你是在用Demo环境？但是这个环境并没有webhost这个appId
> 
> http://106.54.227.205

发现问题了,是以为我没有指定MetaServer导致的,但是我这样配置难道不是应该用Dev的MetaServer吗?
![image](https://user-images.githubusercontent.com/5389478/79819255-2d943780-83bc-11ea-826f-783b8475f217.png)

另外由于我是K8s部署,即使我指定了MetaServer,返回的也是集群内ConfigServer的地址,我修改devapolloconfigdb.serverconfig的eureka.service.ur依然无效呢.

**Comment by nobodyiam** [comment]
可以参考[4.3 如何跳过meta service的服务发现](https://github.com/ctripcorp/apollo.net/blob/dotnet-core/Apollo.Configuration/README.md#43-%E5%A6%82%E4%BD%95%E8%B7%B3%E8%BF%87meta-service%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%8F%91%E7%8E%B0)

**Comment by MikyChow** [comment]
> 可以参考[4.3 如何跳过meta service的服务发现](https://github.com/ctripcorp/apollo.net/blob/dotnet-core/Apollo.Configuration/README.md#43-%E5%A6%82%E4%BD%95%E8%B7%B3%E8%BF%87meta-service%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%8F%91%E7%8E%B0)

解决了,谢谢
