### ISSUE TITLE
apollo在ns未配置下客户端会卡顿几秒

### ISSUE THREAD

**Issue by wu560130911** [ctripcorp/apollo#3017]
apollo-client在ns未配置时，虽会抛404异常，但是仍做重试，导致使用方会卡顿几秒；
RemoteConfigRepository.loadApolloConfig()

**Comment by wu560130911** [comment]
![image](https://user-images.githubusercontent.com/4394967/79452575-eeac5d80-801a-11ea-9c9a-18b6dff78dbc.png)

**Comment by nobodyiam** [comment]
这里倒是可以尝试优化，404的话就不用重试了

**Comment by wu560130911** [comment]
https://github.com/ctripcorp/apollo/pull/3056
