### ISSUE TITLE
部署在k8s中的重启问题

### ISSUE THREAD

**Issue by superchen180** [ctripcorp/apollo#3018]
deployment-apollo-admin-server和statefulset-apollo-config-server为什么会一直重启
![image](https://user-images.githubusercontent.com/16790305/79527071-48ec0380-8099-11ea-929b-acd3610a6312.png)

**Comment by zlingqu** [comment]
看起啦是被k8s干掉了，因为端口的健康检查失败了。

**Comment by superchen180** [comment]
> 看起啦是被k8s干掉了，因为端口的健康检查失败了。

为什么会这样 可以解决嘛 0.0

**Comment by zlingqu** [comment]
> > 看起啦是被k8s干掉了，因为端口的健康检查失败了。
> 
> 为什么会这样 可以解决嘛 0.0

你pod没有起来，所以端口没监听。 建议检查下pod日志，为何没有起来

**Comment by superchen180** [comment]
> > > 看起啦是被k8s干掉了，因为端口的健康检查失败了。
> > 
> > 
> > 为什么会这样 可以解决嘛 0.0
> 
> 你pod没有起来，所以端口没监听。 建议检查下pod日志，为何没有起来

它一直在重启 
![image](https://user-images.githubusercontent.com/16790305/79530159-25c55200-80a1-11ea-8e8f-c5bf4f94adf7.png)
![image](https://user-images.githubusercontent.com/16790305/79530186-383f8b80-80a1-11ea-9a94-11ae542daf1e.png)

生产和测试都有重启的现象 但是测试环境会获取不到配置 搞不懂..

**Comment by nobodyiam** [comment]
describe pod看下？
