### ISSUE TITLE
YAML 的 LIST 格式支持问题

### ISSUE THREAD

**Issue by RadixIsatidis** [ctripcorp/apollo#3020]
YML 文件种的配置形式类似
```yaml
property-key:
  - value 1
  - value 2
  - value 3
```
调试过程中发现在 `com.ctrip.framework.apollo.internals.AbstractConfig` 中，值存在 `m_configProperties` 属性上，对应值类似：
```
property-key[0] = value 1
property-key[1] = value 2
property-key[2] = value 3
```
当前情况下，用预期的key `property-key` 是无法获取到数据的
但是按照 YML 规则，应该可以获取到 List 或者 Set 类型的数据集合。

**Comment by nobodyiam** [comment]
参考下[SampleRedisConfig](https://github.com/ctripcorp/apollo/blob/master/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/spring/springBootDemo/config/SampleRedisConfig.java)

**Comment by RadixIsatidis** [comment]
> 参考下[SampleRedisConfig](https://github.com/ctripcorp/apollo/blob/master/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/spring/springBootDemo/config/SampleRedisConfig.java)

然后又引出新的问题了。
刚还看了代码，YMAL文件解析是有歧义的。
[这行代码](https://github.com/ctripcorp/apollo/blob/82790e5f4a38ed4c2534545686b641f224f0887a/apollo-client/src/main/java/com/ctrip/framework/apollo/util/yaml/YamlParser.java#L91)，将单个字符的key加上方括号，解析时当作List，但实际上这里其实更多可能是一个Map。

由此可见，Apollo中对于YMAL和Properties的转换有问题。

**Comment by RadixIsatidis** [comment]
> 参考下[SampleRedisConfig](https://github.com/ctripcorp/apollo/blob/master/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/spring/springBootDemo/config/SampleRedisConfig.java)

直接绑定Bean是可以的，但通过`Config`的方法无法获取到YMAL定义的List。

**Comment by nobodyiam** [comment]
Properties properties = ((PropertiesCompatibleConfigFile) ConfigService.getConfigFile("application", ConfigFileFormat.YAML)).asProperties();
