### ISSUE TITLE
前端xss攻击缺陷

### ISSUE THREAD

**Issue by icebearwen** [ctripcorp/apollo#3025]
问题url:  http://106.54.227.205/config.html?#/appid=app-demo
登录后，新增属性： key=<script>alert(1)</script> value=<script>alert(2)</script> 
1. 在点击检查隐藏字符时触发弹框
![1587371591213](https://user-images.githubusercontent.com/33884247/79731298-a9db3c00-8324-11ea-9300-235177de7f4f.png)
2. 在点击删除 X 时，触发弹框
 
3. http://106.54.227.205/apps?appIds=    登录后，通过该页面暴漏用户邮箱等信息
4.  普通用户登录后，可访问管理员访问页面
  http://106.54.227.205/user-manage.html
  http://106.54.227.205/server_config.html
 
以上安全隐患请知悉。

**Comment by nobodyiam** [comment]
非常感谢！

1和2确实有这个潜在问题，我们看下如何修复

3是预期的行为

4看了下能打开页面，不过后端做了权限校验，所以暂无风险
