### ISSUE TITLE
多次点击刷新按键会出现不同的界面，会出现有修改，已发布和没有任何配置的界面，并且没有任何规律

### ISSUE THREAD

**Issue by SomeJoker** [ctripcorp/apollo#3026]
- [ ] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) of this repository and believe that this is not a duplicate.

**Describe the bug**

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

### Additional Details & Logs

- Version
- Error logs
- Configuration
- Platform and Operating System

**Comment by nobodyiam** [comment]
初步看是不同环境的admin service注册到同一个环境了，到 管理员工具 - 系统信息 一看便知。

**Comment by SomeJoker** [comment]
是的，是不同环境引起的，已经解决了
