### ISSUE TITLE
线上配置指定功能需求

### ISSUE THREAD

**Issue by HuHaichun** [ctripcorp/apollo#3028]
**Is your feature request related to a problem? Please describe.**
我们的线上同一应用有多台机器，比如三台
每台机器的大部分配置都是一致的，只有某个配置项不同，不如instance.id不同，分别为为instance.id = 1; instance.id = 2; instance.id = 3

**Describe the solution you'd like**
目前灰度发布中可以进行配置指定功能，能不能把这个功能也用到非灰度的情况，把个别个性化配置指定给不同的机器

**Describe alternatives you've considered**

**Additional context**

**Comment by nobodyiam** [comment]
1. 把相同配置抽成公共Namespace
2. 不同的配置按cluster配置或覆盖

**Comment by HuHaichun** [comment]
> 1. 把相同配置抽成公共Namespace
> 2. 不同的配置按cluster配置或覆盖

这样就需要每一台机器上的配置都不一样，指定不同的cluster, 对于这种单台机器的场景，是不太友好的，如果能从配置中心侧进行统一分配，那会直观友好一些

**Comment by nobodyiam** [comment]
所以是否可以抽象为多个灰度版本的功能？
