### ISSUE TITLE
1.6.0版本支持的有序配置不生效

### ISSUE THREAD

**Issue by chao1003** [ctripcorp/apollo#3030]
项目升级到最新的apollo版本,发现拉下来的配置还是和portrl上配置顺序不同

调试过程中发现apollo-client拉下来的配置值存在
 protected final AtomicReference<Properties> m_configProperties中，
 Properties 继承 Hashtable<Object,Object>，拉下来的时候就无序了，

在com.ctrip.framework.apollo.util中，创建了类OrderedProperties继承Properties,应该是为了解决Properties无序的问题，但是好像并没有将OrderProperties应用到项目中

将client中的Properties都置换成OrderedProperties，发现拉下来的配置都有序了，想请问一下，这样的更改是否有问题？

**Comment by nobodyiam** [comment]
参考[1.2.4.3 设置内存中的配置项是否保持和页面上的顺序一致](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#1243-%E8%AE%BE%E7%BD%AE%E5%86%85%E5%AD%98%E4%B8%AD%E7%9A%84%E9%85%8D%E7%BD%AE%E9%A1%B9%E6%98%AF%E5%90%A6%E4%BF%9D%E6%8C%81%E5%92%8C%E9%A1%B5%E9%9D%A2%E4%B8%8A%E7%9A%84%E9%A1%BA%E5%BA%8F%E4%B8%80%E8%87%B4)
