### ISSUE TITLE
spring-boot-demo 跑不起来。

### ISSUE THREAD

**Issue by wulinghui** [ctripcorp/apollo#3031]
![image](https://user-images.githubusercontent.com/36905201/79854448-06f5f100-83fc-11ea-97d0-b4e39ca31163.png)
![image](https://user-images.githubusercontent.com/36905201/79854470-0eb59580-83fc-11ea-937d-9cb69a4eb567.png)

**Comment by wulinghui** [comment]
四月 21, 2020 6:15:40 下午 sun.net.www.protocol.http.HttpURLConnection plainConnect0
非常详细: ProxySelector Request for http://apollo.meta/services/config?appId=100004458&ip=192.168.1.102
[apollo-demo][main]2020-04-21 18:15:41,861 WARN  [com.ctrip.framework.apollo.internals.AbstractConfigRepository] Sync config failed, will retry. Repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository, reason: Get config services failed from http://apollo.meta/services/config?appId=100004458&ip=192.168.1.102 [Cause: Could not complete get operation [Cause: apollo.meta]]
四月 21, 2020 6:15:41 下午 sun.net.www.protocol.http.HttpURLConnection plainConnect0
非常详细: ProxySelector Request for http://apollo.meta/services/config?appId=100004458&ip=192.168.1.102
四月 21, 2020 6:15:42 下午 sun.net.www.protocol.http.HttpURLConnection plainConnect0
非常详细: ProxySelector Request for http://apollo.meta/services/config?appId=100004458&ip=192.168.1.102
四月 21, 2020 6:15:43 下午 sun.net.www.protocol.http.HttpURLConnection plainConnect0
非常详细: ProxySelector Request for http://apollo.meta/services/config?appId=100004458&ip=192.168.1.102
[apollo-demo][main]2020-04-21 18:15:43,877 WARN  [com.ctrip.framework.apollo.internals.LocalFileConfigRepository] Sync config from upstream repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository failed, reason: Get config services failed from http://apollo.meta/services/config?appId=100004458&ip=192.168.1.102 [Cause: Could not complete get operation [Cause: apollo.meta]]
四月 21, 2020 6:15:44 下午 sun.net.www.protocol.http.HttpURLConnection plainConnect0
非常详细: ProxySelector Request for http://apollo.meta/services/config?appId=100004458&ip=192.168.1.102
[apollo-demo][Apollo-RemoteConfigLongPollService-1]2020-04-21 18:15:45,880 WARN  [com.ctrip.framework.apollo.internals.RemoteConfigLongPollService] Long polling failed, will retry in 32 seconds. appId: 100004458, cluster: default, namespaces: TEST1.apollo+application.properties+application+datasources.xml+application.yaml, long polling url: null, reason: Get config services failed from http://apollo.meta/services/config?appId=100004458&ip=192.168.1.102 [Cause: Could not complete get operation [Cause: apollo.meta]]
四月 21, 2020 6:15:45 下午 sun.net.www.protocol.http.HttpURLConnection plainConnect0
非常详细: ProxySelector Request for http://apollo.meta/services/config?appId=100004458&ip=192.168.1.102
四月 21, 2020 6:15:49 下午 sun.net.www.protocol.http.HttpURLConnection plainConnect0
非常详细: ProxySelector Request for http://apollo.meta/services/config?appId=100004458&ip=192.168.1.102
[apollo-demo][main]2020-04-21 18:15:50,133 WARN  [com.ctrip.framework.apollo.internals.LocalFileConfigRepository] Sync config from upstream repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository failed, reason: Get config services failed from http://apollo.meta/services/config?appId=100004458&ip=192.168.1.102 [Cause: Could not complete get operation [Cause: apollo.meta]]
[apollo-demo][main]2020-04-21 18:15:50,133 WARN  [com.ctrip.framework.apollo.internals.AbstractConfigRepository] Sync config failed, will retry. Repository class com.ctrip.framework.apollo.internals.LocalFileConfigRepository, reason: Load config from local config failed! [Cause: Cannot read from local cache file C:\opt\data\100004458\config-cache\100004458+default+datasources.xml.properties]
四月 21, 2020 6:15:50 下午 sun.net.www.protocol.http.HttpURLConnection plainConnect0
非常详细: ProxySelector Request for http://apollo.meta/services/config?appId=100004458&ip=192.168.1.102

**Comment by Anilople** [comment]
>  http://apollo.meta/services/config

注意里面的`apollo.meta`

**Comment by wulinghui** [comment]
嗯嗯，配置为  http://ip:8080

**Comment by wulinghui** [comment]
apollo.meta=http://47.113.116.215:8080
