### ISSUE TITLE
IE11 cannot access apollo project page normally

### ISSUE THREAD

**Issue by junhao521** [ctripcorp/apollo#3033]
- [ ] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) of this repository and believe that this is not a duplicate.

**Describe the bug**
I try to use IE11 to access apollo, but when i login and browser the project page, i find that the page cannot display normally. I use the demo address to test it (http://106.54.227.205/). For my local environment it does not work too.

**To Reproduce**

**Expected behavior**
apollo project page can not be displayed

**Screenshots**
(i don't why i can't upload the screeshots)

### Additional Details & Logs

- Version: apollo 1.6.1
- Error logs
- Configuration
- Platform and Operating System

**Comment by nobodyiam** [comment]
Please use Chrome or Firefox instead
