### ISSUE TITLE
调用apollo-portal中ItemController.modifyItemsByText修改配置项，最后客户端展示格式与预期格式不一致

### ISSUE THREAD

**Issue by HelloHaiNG** [ctripcorp/apollo#3036]
Apollo版本：1.5.1
请求方法：ItemController.modifyItemsByText()方法
参数configText：“dfsf = 45612↵fdsffdgdfgaef = 4865”
其他参数略
预期结果：
dfsg = 45612
fdsffdgdfgaef  = 4865
![111](https://user-images.githubusercontent.com/33769220/80188861-5b8bad00-8644-11ea-8b94-631ba2b7cbf6.png)
实际结果：
dfsf = 45612↵fdsffdgdfgaef = 4865
![22](https://user-images.githubusercontent.com/33769220/80188923-72ca9a80-8644-11ea-9092-25f35b503acb.png)
可见，客户端最后显示效果和期望效果不一致

**Comment by nobodyiam** [comment]
你是直接自己调用的？建议从页面上发起请求，然后和自己的调用参数比较一下哪里不一样。

**Comment by HelloHaiNG** [comment]
> 你是直接自己调用的？建议从页面上发起请求，然后和自己的调用参数比较一下哪里不一样。

知道原因了，被F12参数格式误导了，现在是正常的了，纯属自己的操作失误
