### ISSUE TITLE
quick start中下载的配置中心不显示Dev。右半边什么也没有。可惜不能上传图片

### ISSUE THREAD

**Issue by flyingbird2** [ctripcorp/apollo#3038]
https://blog.csdn.net/weixin_39394909/article/details/105754551
图片

**Comment by nobodyiam** [comment]
管理员工具 - 系统信息 看下

**Comment by flyingbird2** [comment]
> 管理员工具 - 系统信息 看下

https://blog.csdn.net/weixin_39394909/article/details/105754726
超时。可是为什么超时啊。这是按照步骤做的。从这里下的构建包

**Comment by majinding** [comment]
刚下载源代码试了下, 也出现了此问题? 有查出什么问题吗 ?

**Comment by majinding** [comment]
![image](https://user-images.githubusercontent.com/2681645/80695435-7fe5fe80-8b08-11ea-9eb8-397657cdc41a.png)

![image](https://user-images.githubusercontent.com/2681645/80695479-8ffdde00-8b08-11ea-9e61-9754d6ef3231.png)

**Comment by majinding** [comment]
浏览器访问很快, 不会出现超时, 但是程序里面就是会报这个超时, debug了下源代码, 也没发现什么问题,就是响应超时

**Comment by majinding** [comment]
我也不知道为什么, 但是我把参数
-Ddev_meta=http://localhost:8080/ 
调整为ip形式就可以了 
-Ddev_meta=http://192.168.100.102:8080/

**Comment by majinding** [comment]
经过反复验证, 应该是本地vpn导致的, 关闭vpn, 重启项目, 可以访问成功
