### ISSUE TITLE
无法拉取到配置文件。客户端为阿里云专有网络

### ISSUE THREAD

**Issue by bluexzh** [ctripcorp/apollo#3039]
apollo 的_configservice_/_adminservice_/_portal_都部署在一台服务器，注册走的是公网IP。客户端的服务器在阿里云专有网络，公网iP是弹性IP，发现客户端拉取不到配置文件，请问这个如何解决啊？

**Comment by nobodyiam** [comment]
看一下具体报错的信息吧
