### ISSUE TITLE
当一台虚拟机启动两个不同环境的apollo有些问题

### ISSUE THREAD

**Issue by ListenBoom** [ctripcorp/apollo#3040]
我在我自己的虚拟机上面配置了两个环境，分别为FAT和DEV环境。在build.sh中指定了每个环境中地址，但是在启动完毕后，在apollo的系统信息页面发现DEV环境的config和admin含有FAT环境的apollo ip信息，而FAT的config和admin同样含有DEV环境apollo ip信息    
![image](https://user-images.githubusercontent.com/63625782/80300414-1d6ec480-87cf-11ea-97b1-8080edd4e597.png)
    这四个服务均注册到了相同的eureka中

**Comment by nobodyiam** [comment]
两个环境的config/admin service需要使用各自环境独立的configdb，并且配置独立的eureka.service.url
