### ISSUE TITLE
apollo 基于  Go 语言的 php agent 客户端

### ISSUE THREAD

**Issue by GanymedeNil** [ctripcorp/apollo#3043]
基于个人需求做的一个使用 Go 语言开发的 PHP 配置更新服务。单个agent支持多项目，多 namespace。希望能给有同样需求的开发人员提供支持。https://github.com/go-microservices/php_conf_agent

**Comment by nobodyiam** [comment]
感谢贡献！已更新至[Go、Python、NodeJS、PHP等客户端使用指南](https://github.com/ctripcorp/apollo/wiki/Go%E3%80%81Python%E3%80%81NodeJS%E3%80%81PHP%E7%AD%89%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#apollo-go-%E5%AE%A2%E6%88%B7%E7%AB%AF-4)
