### ISSUE TITLE
客户端集成ulisesbocchio.jasypt后无法进行动态更新属性

### ISSUE THREAD

**Issue by rwbykit** [ctripcorp/apollo#3044]
服务集成了ulisesbocchio.jasypt的加解密后，在portal端更新配置后，服务的@Value注解无法获取对应的更新的配置属性，查看后发现ulisesbocchio.jasypt使用了CachingDelegateEncryptablePropertySource对象代理了Apollo的PropertySource，通过发布RefreshScopeRefreshedEvent事件做ulisesbocchio.jasypt的清理操作，但是ulisesbocchio.jasypt的RefreshScopeRefreshedEventListener类中的environment实际为StandardEnvironment, 发现Apollo的客户端自行添加的PropertySource实际是放到了StandardServletEnvironment中，通过RefreshScopeRefreshedEventListener的监听刷新事件（该事件实际为清除缓存）无法清除缓存，这样就获取不了对应的更新属性值，这种情况下，应该如何去做才能获得portal端的更新配置值了？

**Comment by nobodyiam** [comment]
看上去是ulisesbocchio.jasypt的清理操作有问题？
Apollo是通过`org.springframework.context.EnvironmentAware#setEnvironment`获取的environment，没有特定的要求

**Comment by rwbykit** [comment]
我在研究下吧
