### ISSUE TITLE
apolloportaldb.sql这个文件所有的版本通用吗？我搭建1.3.0版本切换tag没有apolloportaldb.sql文件

### ISSUE THREAD

**Issue by bruse-peng** [ctripcorp/apollo#3046]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
apolloportaldb.sql这个文件所有的版本通用吗？我搭建1.3.0版本切换tag没有apolloportaldb.sql文件

**Comment by nobodyiam** [comment]
1.3.0的位置在`scripts/db/migration/portaldb/V1.0.0__initialization.sql`
