### ISSUE TITLE
贡献一个golang客户端

### ISSUE THREAD

**Issue by hyperjiang** [ctripcorp/apollo#3049]
https://github.com/hyperjiang/lunar

无第三方库依赖，已经在货拉拉一些生产项目中应用，目前运行稳定。

**Comment by nobodyiam** [comment]
感谢贡献！已经收录至[Go、Python、NodeJS、PHP等客户端使用指南](https://github.com/ctripcorp/apollo/wiki/Go%E3%80%81Python%E3%80%81NodeJS%E3%80%81PHP%E7%AD%89%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#apollo-go-%E5%AE%A2%E6%88%B7%E7%AB%AF-5)
