### ISSUE TITLE
使用K8S集群部署configservice，eureka的instance url会有问题

### ISSUE THREAD

**Issue by oreoconan** [ctripcorp/apollo#3050]
使用K8S集群部署时，eureka的instance url显示是docker 内部ip地址，非对外透出IP。因K8S发布时configservice无法确定是部署在哪台宿主机上，每台主机上的docker ip也不同，参照文档里的忽略docker地址的方法无法处理，请问有什么好建议

**Comment by nobodyiam** [comment]
see #3054
