### ISSUE TITLE
apollo go语言客户端

### ISSUE THREAD

**Issue by n0trace** [ctripcorp/apollo#3057]
最近把公司配置接入到apollo,用的properties配置,发现拿到配置后再反序列化到config对象的时候有很多重复代码，于是开发了客户端 https://github.com/tagconfig/tagconfig 简化这一流程。

**Comment by nobodyiam** [comment]
多谢贡献，已经更新到[Go、Python、NodeJS、PHP等客户端使用指南](https://github.com/ctripcorp/apollo/wiki/Go%E3%80%81Python%E3%80%81NodeJS%E3%80%81PHP%E7%AD%89%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#apollo-go-%E5%AE%A2%E6%88%B7%E7%AB%AF-6)
