### ISSUE TITLE
如何在运行时清除namespace缓存或者切换meta-server

### ISSUE THREAD

**Issue by xulingfeng931027** [ctripcorp/apollo#3058]
我打算做一个生产环境和开发环境的配置对比工具,目前先通过 
 System.setProperty("apollo.meta", "http://172.16.10.61:8080");
    System.setProperty("app.id", "100086");
    ConfigFile configFile =
        ConfigService.getConfigFile(
            ConfigConsts.NAMESPACE_APPLICATION, ConfigFileFormat.Properties);
代码拿到了一个环境的配置  但是当我重新切换System.setProperty("apollo.meta", "http://172.16.10.24:8080");
    System.setProperty("app.id", "100095");的时候  再通过ConfigService.getConfigFile()方法,拿到的还是老的配置,拿不到新的  请问怎么清除第一次的缓存呢???

**Comment by nobodyiam** [comment]
如果只是用来做配置对比的话，可以直接使用HTTP接口获取配置，参见[其它语言客户端接入指南](https://github.com/ctripcorp/apollo/wiki/%E5%85%B6%E5%AE%83%E8%AF%AD%E8%A8%80%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97)
