### ISSUE TITLE
apollo的鉴权逻辑bug

### ISSUE THREAD

**Issue by dragontree101** [ctripcorp/apollo#3060]
在apollo的登录之后，我们写了一个内部的鉴权的header在cookies 里面，但是不知道为什么， 用apollo项目登录进去，可以创建项目， 但是创建的项目删除的时候 报了 403的错误。

然后删除对应的cookies之后，就可以正常删除了， 是不是使用的security 的验证方式存在问题？

希望只对特定的cookies 进行认证校验，对于其他的cookies需要进行忽略

**Comment by nobodyiam** [comment]
到 com.ctrip.framework.apollo.portal.component.PermissionValidator#isSuperAdmin debug一下吧
