### ISSUE TITLE
管理平台左侧的环境希望能用中文

### ISSUE THREAD

**Issue by jadedrip** [ctripcorp/apollo#3065]
Pro, Uat 这样的字眼始终不直观，希望通过配置改成中文
比如 Pro 改成 现网， Uat 改成 预发布，但中文只是在管理界面显示用

**Comment by Anilople** [comment]
> Pro, Uat 这样的字眼始终不直观，希望通过配置改成中文
> 比如 Pro 改成 现网， Uat 改成 预发布，但中文只是在管理界面显示用

直接在portal上，把Uat改为**UAT预发布**试试，不知道会不会乱码

**Comment by jadedrip** [comment]
我的意思是仅仅显示的时候用中文，否则配置环境用中文很可能有问题

**Comment by Anilople** [comment]
> 我的意思是仅仅显示的时候用中文，否则配置环境用中文很可能有问题

能否贴图？

关于 
> 否则配置环境用中文很可能有问题

这里的意思是？

我的理解是，只改portal，不会影响应用读配置。

对于应用读配置时，只要指明`apollo.meta`即可，不指明`env`也能读到配置。
