### ISSUE TITLE
java client auto updating value cause memory leak

### ISSUE THREAD

**Issue by libinglong** [ctripcorp/apollo#3068]
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) of this repository and believe that this is not a duplicate.

**Describe the bug**

_**the class ApolloProcessor is used to auto update the config value.
so we must store the bean so that we can update.
BUT,when we use prototype bean to do something,it becomes dangerous.
After creating the bean with beanfactory or applicationContext and doing something,
the bean should be recyclable.BUT now it is store in somewhere(the queue in thread pool or springValueRegistry) with strong refrence.**_

**To Reproduce**
**1. using prototype bean to do something repeatedly**

**Expected behavior**

**memory leak**

**Comment by nobodyiam** [comment]
I think this was fixed by #1676

**Comment by libinglong** [comment]
> I think this was fixed by #1676

thank you!
I should update my client version
by the way.
the spring bean can be recyclable now,but the weakrefrence of the bean not.
should we ignore it as it just use very little space.

**Comment by nobodyiam** [comment]
I think the same pr also added the clean up mechanism for SpringValue objects

https://github.com/ctripcorp/apollo/blob/4d56835c4979b372bf635eb42db98694d9e9fd7a/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/property/SpringValueRegistry.java#L63

**Comment by libinglong** [comment]
> I think the same pr also added the clean up mechanism for SpringValue objects
> 
> https://github.com/ctripcorp/apollo/blob/4d56835c4979b372bf635eb42db98694d9e9fd7a/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/property/SpringValueRegistry.java#L63

oh,sorry for my disregard.
I thought it was going to use CopyOnWriteArrayList to make thread safe on regist and removing.
