### ISSUE TITLE
yml格式的配置文件，对于@ConfigurationProperties的变量无法进行实时更新

### ISSUE THREAD

**Issue by dragontree101** [ctripcorp/apollo#3070]
如果使用properties的配置文件的时候，对于@ConfigurationProperties的变量可以坚挺到实时更新，

但是如果使用yml格式的配置文件，对于@ConfigurationProperties的变量无法进行实时更新，请问这个是使用问题， 还是存在的bug？

**Comment by tktkl** [comment]
文档有
https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#3223-configurationproperties%E4%BD%BF%E7%94%A8%E6%96%B9%E5%BC%8F

**Comment by nobodyiam** [comment]
@dragontree101 properties和yml在使用上是一样的，看下监听事件的namespace是不是对吧
