### ISSUE TITLE
疑惑，配置方面，注解与环境切换。

### ISSUE THREAD

**Issue by Lijiaqi1992** [ctripcorp/apollo#3071]
如题。
apollo部署版本1.6.1，
部署方式：1个protal，2个config，2个admin ，模仿2个环境。
springboot项目
使用版本
```
        <dependency>
            <groupId>com.ctrip.framework.apollo</groupId>
            <artifactId>apollo-client</artifactId>
            <version>1.6.0</version>
        </dependency>
```
遇到的问题： 

1. 任何类中没有使用@EnableApolloConfig，依然可以正常读取到apollo中配置，文档中写了需要此注解才行；

2. env的切换环境配置无效，只有切换了apollo.meta才有效。

**Comment by Anilople** [comment]
> 如题。
> apollo部署版本1.6.1，
> 部署方式：1个protal，2个config，2个admin ，模仿2个环境。
> springboot项目
> 使用版本
> 
> ```
>         <dependency>
>             <groupId>com.ctrip.framework.apollo</groupId>
>             <artifactId>apollo-client</artifactId>
>             <version>1.6.0</version>
>         </dependency>
> ```
> 
> 遇到的问题：
> 
> 1. 任何类中没有使用@EnableApolloConfig，依然可以正常读取到apollo中配置，文档中写了需要此注解才行；
> 2. env的切换环境配置无效，只有切换了apollo.meta才有效。

对于1. 不需要注解也可以读到配置，只要本地配置上打开就行了。

对于2. env不影响配置读取，`apollo.meta`才是读取的关键

**Comment by Lijiaqi1992** [comment]
> > 如题。
> > apollo部署版本1.6.1，
> > 部署方式：1个protal，2个config，2个admin ，模仿2个环境。
> > springboot项目
> > 使用版本
> > ```
> >         <dependency>
> >             <groupId>com.ctrip.framework.apollo</groupId>
> >             <artifactId>apollo-client</artifactId>
> >             <version>1.6.0</version>
> >         </dependency>
> > ```
> > 
> > 
> > 遇到的问题：
> > 
> > 1. 任何类中没有使用@EnableApolloConfig，依然可以正常读取到apollo中配置，文档中写了需要此注解才行；
> > 2. env的切换环境配置无效，只有切换了apollo.meta才有效。
> 
> 对于1. 不需要注解也可以读到配置，只要本地配置上打开就行了。
> 
> 对于2. env不影响配置读取，`apollo.meta`才是读取的关键

谢谢！
