### ISSUE TITLE
集群还是公共namespace

### ISSUE THREAD

**Issue by LOUISXUSEN** [ctripcorp/apollo#3074]
业务场景：
      微服务，多服务多环境，有公共配置。例如：注册中心地址，是创建三个公共namespace代表三个环境，还是有其他方式配置？

**Comment by Anilople** [comment]
> 业务场景：
> 微服务，多服务多环境，有公共配置。例如：注册中心地址，是创建三个公共namespace代表三个环境，还是有其他方式配置？

理论上都可以使用。如果要比较科学地使用配置中心，可以详细了解一下架构

**Comment by nobodyiam** [comment]
这里提到的环境对应于apollo的环境概念吗？如果对应地上的话，那创建一个公共namespace即可，在不同的环境下配置不同的值。如果对应不上的话，那可以用集群

**Comment by LOUISXUSEN** [comment]
> > 业务场景：
> > 微服务，多服务多环境，有公共配置。例如：注册中心地址，是创建三个公共namespace代表三个环境，还是有其他方式配置？
> 
> 理论上都可以使用。如果要比较科学地使用配置中心，可以详细了解一下架构

正在学习源码，但是先解决业务需求

**Comment by LOUISXUSEN** [comment]
> 这里提到的环境对应于apollo的环境概念吗？如果对应地上的话，那创建一个公共namespace即可，在不同的环境下配置不同的值。如果对应不上的话，那可以用集群

对，对应apollo的环境概念。周末细看了一下文档，结论使用namespace！
