### ISSUE TITLE
Portal服务的API接口无法获取关联的NameSpace配置

### ISSUE THREAD

**Issue by ImLeoChan** [ctripcorp/apollo#3075]
尝试用Portal服务的API接口去获取配置，
发现获取不到 **关联** 的NameSpace的配置，
所以想了解下是
- 本人使用姿势不对？
- 还是基于什么样的考虑设计成这样？

Portal服务的API接口相对于Config服务的API而言，有授权功能，
希望Portal服务的API接口也可以获取关联的NameSpace配置

**Comment by nobodyiam** [comment]
Portal的接口是服务于用户的，所以接口是分开的，在界面上也是通过单独的section展示关联的配置。

查找关联的Namespace，可以参考
`com.ctrip.framework.apollo.portal.controller.NamespaceController#findPublicNamespaceForAssociatedNamespace`

**Comment by ImLeoChan** [comment]
> 
> 
> Portal的接口是服务于用户的，所以接口是分开的，在界面上也是通过单独的section展示关联的配置。
> 
> 查找关联的Namespace，可以参考
> `com.ctrip.framework.apollo.portal.controller.NamespaceController#findPublicNamespaceForAssociatedNamespace`

associated-public-namespace这个功能不知道有没有考虑加进openapi里面？比如
`http://{portal_address}/openapi/v1/envs/{env}/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/associated-public-namespace`
通过这个接口就可以获取到一个namespace关联的公共namespace，感觉这个接口会应用在很多场景里面

**Comment by nobodyiam** [comment]
如果需要的话，可以提个PR
