### ISSUE TITLE
在只部署adminservice和configservice下，Apollo是否可以正常使用

### ISSUE THREAD

**Issue by HelloHaiNG** [ctripcorp/apollo#3076]
问：通过helm chart方式来部署k8s环境下的adminservice和configservice模块，不部署apollo-portal的情况下，通过rest方式调用adminservice controller中的接口是否可以实现apollo的各种功能？（已知，portal，adminservice和configservice都部署的情况下，调用portal中controller接口是可以实现Apollo的各种功能）
我的猜想：只部署adminservice和configservice的情况下，是无法实现apollo的各个功能，因为adminservice中缺少了部分apollo项目依赖（这些依赖是portal中引入了），导致部分功能无法正常使用

**Comment by jadedrip** [comment]
adminservice 是给管理平台用的。没管理平台只部署 configservice 都够了

**Comment by nobodyiam** [comment]
@HelloHaiNG 有一些元数据是从Portal同步到admin service的，不过理论上而言，没有portal也是能用的，只要你能模拟所有portal的行为。。。

**Comment by HelloHaiNG** [comment]
> @HelloHaiNG 有一些元数据是从Portal同步到admin service的，不过理论上而言，没有portal也是能用的，只要你能模拟所有portal的行为。。。

嗯嗯，我确认过了，admin service可以实现portal的基本配置功能

**Comment by HelloHaiNG** [comment]
> adminservice 是给管理平台用的。没管理平台只部署 configservice 都够了

确实是这样，只是只部署config service配置文件数据就没有流入了
