### ISSUE TITLE
是否可以做个一键发布？

### ISSUE THREAD

**Issue by jadedrip** [ctripcorp/apollo#3082]
namespace 比较多，一个一个发布有点累。
最好有个 一键发布，一次性发布所有有更改的 namespace

**Comment by nobodyiam** [comment]
配置变更不是高频行为，且危险性较高，所以感觉没有很大的必要做一键发布

**Comment by jadedrip** [comment]
一般仅仅在正式上线的时候才会发布配置，这时候namespace 比较多就很麻烦。
另外 namespace 默认是收缩状态，看不出来是否需要发布，这个也比较麻烦。

**Comment by nobodyiam** [comment]
> 另外 namespace 默认是收缩状态，看不出来是否需要发布，这个也比较麻烦。

这个倒是可以提一个 PR 优化一下
