### ISSUE TITLE
Eureka官方已经停止更新了，Apollo如何应对

### ISSUE THREAD

**Issue by bootsrc** [ctripcorp/apollo#3084]
Eureka官方已经停止更新了。Apollo是基于Eureka的。后面Apollo里的Eureka会被替换掉吗？
Apollo继续使用Eureka，有没有什么技术风险？

**Comment by born198x** [comment]
不要想太多

**Comment by nobodyiam** [comment]
eureka可以认为是apollo实现的一部分，对外部是不可见的，后续可以考虑使用其它方案，不过目前看没有太大必要

**Comment by jsyzthz** [comment]
提问题人估计看的是国内翻译的文章，理解有出入，其实官方只是停止2.x的开发，1.x的还在开发。就目前大部分都是用1.x的没有任何影响。况且1.x已经非常成熟了，企业开发不要过分追求新，关键要稳定。
