### ISSUE TITLE
namespace和配置删除后再创建同名的Namespace为什么报错呢？

### ISSUE THREAD

**Issue by li465141789** [ctripcorp/apollo#3085]
namespace和配置删除后再创建同名的Namespace为什么报错呢？

**Comment by nobodyiam** [comment]
使用管理员工具删除 appnamespace 即可。

**Comment by hujingzheng** [comment]
> 使用管理员工具删除 appnamespace 即可。

使用apollo-openapi 的依赖

**Comment by nobodyiam** [comment]
删除 namespace 影响较大，所以现在只开放给管理员操作，管理员登陆后右上方管理员工具里面能看到
