### ISSUE TITLE
 apollo  server 端升级后,  client 有依赖吗?需不需要 也要升级到对应版本

### ISSUE THREAD

**Issue by station19** [ctripcorp/apollo#3086]
我现在 apollo  server 端是 1.4版本,  client是  1.3,  我想升级 server端到 1.61,   client端 需要升级吗? 如果不升级client, 是不是 有能用1.61的所有功能不影响

**Comment by nobodyiam** [comment]
可以不升级 client

**Comment by station19** [comment]
> 可以不升级 client

感谢大佬回复, 谢谢

**Comment by station19** [comment]
> 可以不升级 client

这个密钥访问的功能 好像需要特定的 client版本呢 ??? 低版本不支持吧?
Tips:
每个环境最多可添加5个访问密钥
一旦该环境有启用的访问密钥，客户端将被要求配置密钥，否则无法获取配置
配置访问密钥防止非法客户端获取该应用配置，配置方式如下（需要apollo-client 1.6.0+版本）：
通过jvm参数-Dapollo.accesskey.secret
通过操作系统环境变量APOLLO_ACCESSKEY_SECRET
通过META-INF/app.properties或application.properties配置apollo.accesskey.secret（注意多环境secret不一样）

**Comment by nobodyiam** [comment]
如果要使用新的功能，是需要升级apollo-client的
