### ISSUE TITLE
Apollo管理中间件配置文件的解决方案

### ISSUE THREAD

**Issue by cuiyiping** [ctripcorp/apollo#3089]
**目前我们公司用apollo管理spring容器中的配置,这个比较有局限性,大家有没有想过如果可以一起管理redis,MongoDB,Nginx这种中间件的配置就太爽了**

**Comment by Anilople** [comment]
> **目前我们公司用apollo管理spring容器中的配置,这个比较有局限性,大家有没有想过如果可以一起管理redis,MongoDB,Nginx这种中间件的配置就太爽了**

可以给中间件定制一个外置管理程序，负责给中间件更新配置。

比如对于Redis，可以写个Java程序，实时抓取Apollo上的配置，然后推送到Redis所在的服务器上，并触发配置刷新。

**Comment by nobodyiam** [comment]
apollo服务端管理的是通用配置，Java客户端目前实现了api和spring两种方式的配置场景，其实也可以针对redis, mongo, nginx等实现更多的客户端，就可以管理这些中间件的配置了

**Comment by cuiyiping** [comment]
收到，您的想法对我挺有帮助



崔伊平 能源支撑部 
浙江鸿程计算机系统有限公司 
Zhejiang Hong Cheng Computer Systems Co., Ltd. 
地址:中国杭州市滨江区伟业路1号高新软件园2号楼 
Address: Building no.2 , Hangzhou High Tech Park , No.1 Weiye Road ,Binjiang 
District , Hangzhou , China; 
邮编（Postcode）:310053
传真(Fax):(0571)88489999
手机(Mobile):15868147729
邮箱(E-mail): cuiyp@zjhcsoft.com 
公司网址(The company web site): http://www.zjhcsoft.com 
特别注意：如邮件内容包含涉密信息，必须向收件人加以说明，内容如下： 
本电子邮件可能为保密文件。如果阁下非电子邮件所指定之收件人，谨请立即通知本 
人。敬请阁下不要使用、保存、复印、打印、散布本电子邮件及其内容，或将其用于 
其他任何目的或向任何人披露。
 
发件人： wxq
发送时间： 2020-05-21 22:11
收件人： ctripcorp/apollo
抄送： cuiyiping; Author
主题： [SPAM]Re: [ctripcorp/apollo] Apollo管理中间件配置文件的解决方案 (#3089)
目前我们公司用apollo管理spring容器中的配置,这个比较有局限性,大家有没有想过如果可以一起管理redis,MongoDB,Nginx这种中间件的配置就太爽了
可以给中间件定制一个外置管理程序，负责给中间件更新配置。
比如对于Redis，可以写个Java程序，实时抓取Apollo上的配置，然后推送到Redis所在的服务器上，并触发配置刷新。

**Comment by cuiyiping** [comment]
感谢您的回复，我会尝试写一些中间件的适配客户端



崔伊平 能源支撑部 
浙江鸿程计算机系统有限公司 
Zhejiang Hong Cheng Computer Systems Co., Ltd. 
地址:中国杭州市滨江区伟业路1号高新软件园2号楼 
Address: Building no.2 , Hangzhou High Tech Park , No.1 Weiye Road ,Binjiang 
District , Hangzhou , China; 
邮编（Postcode）:310053
传真(Fax):(0571)88489999
手机(Mobile):15868147729
邮箱(E-mail): cuiyp@zjhcsoft.com 
公司网址(The company web site): http://www.zjhcsoft.com 
特别注意：如邮件内容包含涉密信息，必须向收件人加以说明，内容如下： 
本电子邮件可能为保密文件。如果阁下非电子邮件所指定之收件人，谨请立即通知本 
人。敬请阁下不要使用、保存、复印、打印、散布本电子邮件及其内容，或将其用于 
其他任何目的或向任何人披露。
 
发件人： Jason Song
发送时间： 2020-05-24 20:46
收件人： ctripcorp/apollo
抄送： cuiyiping; Author
主题： [SPAM]Re: [ctripcorp/apollo] Apollo管理中间件配置文件的解决方案 (#3089)
apollo服务端管理的是通用配置，Java客户端目前实现了api和spring两种方式的配置场景，其实也可以针对redis, mongo, nginx等实现更多的客户端，就可以管理这些中间件的配置了
