### ISSUE TITLE
线程死锁 0.27.1

### ISSUE THREAD

**Issue by leery** [ctripcorp/apollo#3090]
main queue 使用fetch方法
<img width="497" alt="截屏2020-05-21 下午3 42 09" src="https://user-images.githubusercontent.com/8122336/82535852-193d8900-9b7a-11ea-8c25-5a5aba7485be.png">

**Comment by nobodyiam** [comment]
@leery 这个是啥程序？

**Comment by leery** [comment]
> @leery 这个是啥程序？

iOS端

**Comment by nobodyiam** [comment]
@leery apollo应该没有提供过ios客户端，能提供下ios客户端的代码地址吗？

**Comment by leery** [comment]
> @leery apollo应该没有提供过ios客户端，能提供下ios客户端的代码地址吗？

https://github.com/apollographql/apollo-ios，我好像问题提错地方了。
