### ISSUE TITLE
想请教一个问题，Environment is set to null.

### ISSUE THREAD

**Issue by gsralex** [ctripcorp/apollo#3092]
https://blog.csdn.net/zjh_746140129/article/details/86364371

需要这样来解决吗？
现在出现一个问题，spring.profile.active=test。但是还会去dev里面读取配置；目前是有dev和test的apollo配置

**Comment by gsralex** [comment]
一台机器上部署了两个springboot，一个一直是正常的，都是这样配置的，在application.yml
app.id: xxx
apollo.meta: xxx

**Comment by nobodyiam** [comment]
spring.profiles.active是spring的配置，对apollo是无效的。apollo区分环境的配置可以通过指定不同的apollo.meta地址来实现

**Comment by gsralex** [comment]
假设在一个meta上面有多个环境。比如有dev和test

**Comment by Anilople** [comment]
> 假设在一个meta上面有多个环境。比如有dev和test

你的使用方法出错了，应该搞2个不同的`apollo.meta`来区分`dev`和`test`

**Comment by gsralex** [comment]
没懂？不能一个meta支持两个吗？

**Comment by Anilople** [comment]
> 没懂？不能一个meta支持两个吗？

不要用`spring.profile.active=test`或者`spring.profile.active=dev`这种方式来使用Apollo，

使用了Apollo后，不要再用`profile`来区分环境这一套了。

你可以看下配置注入的原理就明白了。

**Comment by gsralex** [comment]
是的，感谢恢复，我端口配错了
