### ISSUE TITLE
生态共建

### ISSUE THREAD

**Issue by tianxiaoliang** [ctripcorp/apollo#3094]
https://github.com/go-chassis/go-archaius
该工程是go语言用于动态配置管理的轻量级框架。请看下使用介绍，和程序设计

近期有开发者贡献了插件，对接了apollo。也持续能够接到开发者的贡献。

可否在您的Readme文件中对该工程进行推荐，一起共建生态，感谢

**Comment by nobodyiam** [comment]
已推荐至[Go、Python、NodeJS、PHP等客户端使用指南](https://github.com/ctripcorp/apollo/wiki/Go%E3%80%81Python%E3%80%81NodeJS%E3%80%81PHP%E7%AD%89%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#apollo-go-%E5%AE%A2%E6%88%B7%E7%AB%AF-7)

**Comment by tianxiaoliang** [comment]
谢谢
