### ISSUE TITLE
建议提供版本发布触发outgoing webhook 实现订阅功能

### ISSUE THREAD

**Issue by hlinhz** [ctripcorp/apollo#3095]
类似[#3008](https://github.com/ctripcorp/apollo/issues/3008)的需求
希望可以添加版本提交/发布后触发webhook的功能，用户可以利用自主开发的API进行响应。无论是邮件还是其他可能性的的响应机制开发都转移对外，从用户角度对java就没有那么大的依赖性了。（是的，我们也没有java开发）

**Comment by nobodyiam** [comment]
good idea

**Comment by HuangSheng** [comment]
> good idea

不知道这个功能有人实现吗？我们倒是实现了一个类似的功能，接入钉钉提醒。如果没人实现的话我可以尝试提一个PR

**Comment by nobodyiam** [comment]
@HuangSheng 欢迎 PR
