### ISSUE TITLE
长连接请求都是超过60s返回状态码504

### ISSUE THREAD

**Issue by cciechao** [ctripcorp/apollo#3096]
如果都是最新的，则保持住请求60秒，如果60秒内没有配置变化，则返回HttpStatus 304。如果60秒内有配置变化，则返回对应namespace的最新notificationId, HttpStatus 200

按照上面实际验证发现在60秒以内，如果有配置变化是正常的
如果60秒以内没有配置变化，直接等待超过60秒返回504...

**Comment by zouyx** [comment]
如果是504，我觉得是代理层的超时时间没配置正确？如果正确应该是apollo metaserver 返回的304

**Comment by cciechao** [comment]
@zouyx 请问一下，如果是nginx的话，除了设置keepalive_timeout 还要设置其他的吗？谢谢

**Comment by zouyx** [comment]
> @zouyx 请问一下，如果是nginx的话，除了设置keepalive_timeout 还要设置其他的吗？谢谢

ng的超时时间一定要比 client 的要大，我记得java client 默认是60s，ng 的默认是75s，应该没问题才对？

**Comment by zdan** [comment]
今天检查nginx-ingress日志时，也遇到类似的504请求，在configMap中增加如下参数可以解决问题：
```js
// proxy-read-timeout 用于设置从上游服务器读取响应的超时时间。默认值为60秒。nginx参数为：proxy_read_timeout
proxy-read-timeout: 65
```

之所以在60秒以后出现504，与apollo长连接的实现逻辑有关：
1. `/notifications/v2`发起请求以后，如果配置有变更，则实时响应请求；
2. 如果配置无变更，则apollo默认会等待60秒，期间如无配置变更，在60秒后响应304状态码；
3. 但是nginx配置默认读取上游服务响应体的超时时间是60秒，超时则中断连接并响应504状态码。

也就是说，只要把读取响应体的超时时间设置为大于60秒可以规避该问题

**Comment by fenglangjunzi** [comment]
Good！
