### ISSUE TITLE
请问一下apollo高可用方案下，多个portal和多个configservice之间的数据同步原理是怎么样的

### ISSUE THREAD

**Issue by HelloHaiNG** [ctripcorp/apollo#3100]
如题：请问一下apollo高可用方案下，多个portal和多个configservice之间的数据同步原理是怎么样的

**Comment by nobodyiam** [comment]
可以参考下[服务端设计](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1#%E4%BA%8C%E6%9C%8D%E5%8A%A1%E7%AB%AF%E8%AE%BE%E8%AE%A1)

**Comment by HelloHaiNG** [comment]
> 可以参考下[服务端设计](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1#%E4%BA%8C%E6%9C%8D%E5%8A%A1%E7%AB%AF%E8%AE%BE%E8%AE%A1)

我后面看了分布式部署方式，关于apollo的生产环境部署我的理解是这样的（以k8s容器云部署为例）：
portal部署多个多个pod，同时数据库采用主从结构部署

**Comment by nobodyiam** [comment]
是的
