### ISSUE TITLE
Need to support Spring Profile

### ISSUE THREAD

**Issue by Macrame** [ctripcorp/apollo#3102]
**Is your feature request related to a problem? Please describe.**
Hope to **disable Apollo** effect while executing the unit tests.

**Describe the solution you'd like**
```
@Configuration
@EnableApolloConfig()
@Profile({"!development","!test"})
public class ApolloConfiguration 
```

**Describe alternatives you've considered**
You can detect **current active profiles** to decide to enable or disable this feature.

**Comment by nobodyiam** [comment]
You can enable Apollo with the Spring Boot integration way instead of `EnableApolloConfig`

```
apollo.bootstrap.enabled=true
```

And put the above config in the profile you like.

**Comment by Macrame** [comment]
Thanks your feedback. But `EnableApolloConfig` with a configuration class can be published to the maven library as a jar file while `apollo.bootstrap.enabled=true` can be defined in each application. I'd like to use jar library. Is there any better approach?

**Comment by nobodyiam** [comment]
duplicated with #3045
