### ISSUE TITLE
能否提供发布之前中间状态的便捷撤销功能？

### ISSUE THREAD

**Issue by flybird-tech** [ctripcorp/apollo#3117]
场景：
删除了某项配置，还未发布，此时不想删除了；
修改某项配置，还未发布，此时不想修改了；

目前没有快捷的方式撤销之前的删除或修改，只能反向操作；
比如不想删除了，需要新增相同key-value的项；不想修改了，需要把value改回原来的值；步骤稍微繁琐了一些，如果有一键撤销的方式，就方便很多。

**Comment by nobodyiam** [comment]
#2952 已经支持
