### ISSUE TITLE
能否在管理网页的namespace名称旁边显示备注信息？

### ISSUE THREAD

**Issue by flybird-tech** [ctripcorp/apollo#3118]
创建namespace的时候，有填写相关中文备注信息；
但是这个备注信息没有在应用的namespace列表中显示出来；
我们的项目会创建许多namespace，通常是英文名称，如果能够在namespace名称旁边显示中文备注信息，能方便我们区别每个namespace的具体用途，不至于出现误操作；
另外，namespace名称能否也支持修改，有些时候写错了英文单词，后面想改很困难？

**Comment by nobodyiam** [comment]
see #3112

**Comment by nobodyiam** [comment]
namespace 名称不支持修改，可以通过管理员工具删除后重建
