### ISSUE TITLE
关联了其他应用的public namespce后，拉取不到继承的配置信息

### ISSUE THREAD

**Issue by zhangkungit** [ctripcorp/apollo#3119]
apollo1.4.0版本
采用spring boot 集成的方式，在A应用中中创建了一个public的公共命名空间（common-config.yml），在B应用里面 关联这个公共命名空间，关联后在B应用客户端的配置如下：
apollo.bootstrap.enabled = true
apollo.bootstrap.namespaces =common-config.yml
结果：
只有B自己在 关联配置 新加的配置信息可以读取
继承A的 公共命名空间的 配置信息无法被拉取到
看了别人的提的issue：https://github.com/ctripcorp/apollo/issues/2282

重启admin service都不生效，还是无法获取 公共命名空间的配置

**Comment by zhangkungit** [comment]
重新验证了下：

- B不没有自己新增配置，关联A的公共命名空间（common-config.yml）是可以取到配置的

- 只要B新增配置，拉取到的配置只有B自己的，关联关系就失败了

**Comment by nobodyiam** [comment]
话说公共 namespace 目前支持 properties 格式，你是咋创建出一个 yml 的公共 namespace 的？

**Comment by zhangkungit** [comment]
是可以创建的公共的yml配置的，只是页面交互很奇怪：先在private上选择yml格式，然后再切回public，这样创建出来的就是 公共的yml配置。
**我们一直以为这是个前端bug**

**Comment by nobodyiam** [comment]
这确实是一个前端的bug
