### ISSUE TITLE
请问，我使用spring的xml配置方式集成apollo

### ISSUE THREAD

**Issue by lianbitangjin** [ctripcorp/apollo#3122]
<apollo:config/>
    <bean class="com.web.util.ApolloMallBean">
        <property name="ebizchargeAddress" value="${ebizchargeAddress}"/>
        <property name="ebizchargeTimeOut" value="${ebizchargeTimeOut}"/>
        <property name="ebizchargeSourcekey" value="${ebizchargeSourcekey}"/>
        <property name="ebizchargePin" value="${ebizchargePin}"/>
        <property name="ebizchargeClientIp" value="${ebizchargeClientIp}"/>
    </bean>

如上配置：
ApolloMallBean的实体类中的int类型属性没问题，string类型的属性的话 value="${ebizchargeAddress}"这个里面会报红，是为什么，有影响吗

**Comment by nobodyiam** [comment]
根据 IDE 的提示信息看一下吧，这个和 apollo就没啥关系了，应该没啥影响
