### ISSUE TITLE
开放平台授权求教

### ISSUE THREAD

**Issue by Newbwen** [ctripcorp/apollo#3129]
在http://{portal_address}/open/manage.html 输入第三方应用id查询，提示Token: App('1234')未创建，请先创建
请问这个AppId怎么创建的，或者我怎么获取这个id

**Comment by nobodyiam** [comment]
请参考wiki文档，在界面上创建即可
https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0#%E4%BA%8C-%E7%AC%AC%E4%B8%89%E6%96%B9%E5%BA%94%E7%94%A8%E6%8E%A5%E5%85%A5apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0
