### ISSUE TITLE
apollo/apollo-demo/xxx/springBootDemo依赖了cloud进行发布热

### ISSUE THREAD

**Issue by cq-zhaoqf** [ctripcorp/apollo#3130]
Spring Boot Demo, 里面依赖的是 Cloud 包的类进行的热发布, 还以为能开箱即用呢...  叹个气... 又不能偷懒了...

**Comment by nobodyiam** [comment]
更多使用案例可以参考[apollo-use-cases](https://github.com/ctripcorp/apollo-use-cases)
