### ISSUE TITLE
aopollo-env.properties和server.properties都配置了，无法加载apollo数据

### ISSUE THREAD

**Issue by lianbitangjin** [ctripcorp/apollo#3131]
aopollo-env.properties放在resources目录下，内容是:
`dev.meta=http://192.168.1.146:8080`

server.properties的目录是：C:\opt\settings  windows系统
而且opt下没有settings这个子目录，我手动建的，然后创建的server.properties，
内容是:`env=DEV`

启动项目，无法加载配置报错，然后没办法，
我只能在项目里的app.properties写死apollo.meta=http://192.168.1.146:8080
启动项目是可以加载配置的

请问上面那种方式配置环境为什么不行？

**Comment by lianbitangjin** [comment]
补充一点：项目是spring项目

**Comment by nobodyiam** [comment]
1. aopollo-env.properties，文件名是否正确？
2. apollo-env.properties 是在你自己的项目中放的？在 apollo-core 的 jar 包里面还有一个吧，加载顺序不确定的，可以考虑放在resources/config/apollo-env.properties 试试
