### ISSUE TITLE
可否将静态版本号改为 {revision}变量？

### ISSUE THREAD

**Issue by bjo2008cnx** [ctripcorp/apollo#3134]
when the version needs to be updated, we need to modify every pom.xml and then commit these files. 
Could you please replace version with {revision} variable so that only one file is required to modify?  Thanks very much.

**Comment by nobodyiam** [comment]
To replace the version of pom.xml, you may use the following commands:
`mvn versions:set -DnewVersion=x.x.x -DgenerateBackupPoms=false`

**Comment by bjo2008cnx** [comment]
Yes. What you say is a very good way to update version.  We used to update version in this way.
However, after use :mvn versions:set -DnewVersion=x.x.x -DgenerateBackupPoms=false,
we need to commit too many pom.xml files.

If  {revision} variable is used ,ONLY ONE files is needed to commit.
Could you please update it to  {revision} ? Thank you very very much.

**Comment by bjo2008cnx** [comment]
做apollo二开好久了，每次合并开源的新版本时，都需要把静态版本号改成${revision}, 重复劳动太多，申请开源版本升级为${revision}变量.（dubbo源码中使用了${revision},可参考）。有同感的同学吧 ？

**Comment by bjo2008cnx** [comment]
谢谢宋大佬先！

**Comment by nobodyiam** [comment]
This sounds like a good idea, would you please submit a pr for this?

**Comment by bjo2008cnx** [comment]
ok.

**Comment by bjo2008cnx** [comment]
pr 已提交，请大佬review

**Comment by bjo2008cnx** [comment]
宋大佬不屑于review这种小功能啊
