### ISSUE TITLE
应用内命名空间新增key时，若与其他命名空间存在的key重复，禁止添加

### ISSUE THREAD

**Issue by ChenAiYang** [ctripcorp/apollo#3135]
同一个应用内，不同命名空间出现相同的key后，获取值不可预期。能否将在命名空间内新建key时做一层检查？若有其他命名空间使用了该key，不允许用户创建。

在所有的issues里面搜索了下“重复key”，没有看到相关，所以单独提一个，若已经有此类问题，可以帮忙贴下链接吗？

**Comment by nobodyiam** [comment]
这个不建议作为系统的一个强校验，比如通过 API 方式引用 namespace 的场景，重复的 key 是不会有任何影响的，对 Spring 的场景确实是会有这个隐式规则，不过这个也是符合 Spring 的使用习惯的，比如在不同的配置文件里面都有同一个 key 的情况。
