### ISSUE TITLE
使用@ConditionalOnProperty注解无效

### ISSUE THREAD

**Issue by wade009** [ctripcorp/apollo#3137]
- [ ] 
在配置中心中配置 application.properties ,添加 datasource.pri.load=true.
@Configuration
public class EnableDataSourceConfig {
@ConditionalOnProperty(prefix = "datasource.pri",name = "load", havingValue = "true")
    @Bean(name="B")
    public Object createB(){
        System.out.println(2222);
        return new Object();
    }
}
无法创建此类
在ConditionalOnProperty的判断逻辑中，查看加载到的配置文件没有查询到配置到配置中心的数据

**Comment by nobodyiam** [comment]
参考下[3.2.1.3 Spring Boot集成方式（推荐）](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#3213-spring-boot%E9%9B%86%E6%88%90%E6%96%B9%E5%BC%8F%E6%8E%A8%E8%8D%90)

**Comment by wade009** [comment]
0.8.0版本是不是不行？

**Comment by wade009** [comment]
> 参考下[3.2.1.3 Spring Boot集成方式（推荐）](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#3213-spring-boot%E9%9B%86%E6%88%90%E6%96%B9%E5%BC%8F%E6%8E%A8%E8%8D%90)

0.8.0版本是不是不行
