### ISSUE TITLE
AutoUpdateConfigChangeListener 中onChange自动更新失效

### ISSUE THREAD

**Issue by JerryPlayer** [ctripcorp/apollo#3138]
hi，我们在使用apollo配置变量时，使用到了Spring 的SePL功能，但是在apollo控制台更新变量值时，更新的变量能推到客户端，但是客户端内存中变量地址未修改，具体case简化后如下
@Component
@Configuration
@EnableApolloConfig({"remote.address"})
public class RemoteConfig{
    @Value("${user.address}/user/gateway")
    private String userUrl;
......
    public String getUserUrl() {
        return userUrl;
    }
    public void setUserUrl(String userUrl) {
        this.userUrl = userUrl;
    }
}
}
假设apollo配置的user.address=a,项目启动后，直接使用userUrl,发现使用的时地址a.当把user.address改成b后，改动成功推送到client
2020-06-21 00:33:13.205 [Apollo-RemoteConfigRepository-1] DEBUG  c.c.f.a.i.RemoteConfigRepository.sync - Remote Config refreshed!
但是并未提示user.address值修改成功。debug发现
AutoUpdateConfigChangeListener这个类中的onChange事件
![image](https://user-images.githubusercontent.com/25799340/85207099-1f7d7b80-b359-11ea-8e43-00e3557ed97c.png)

如果将userUrl注解改成
    @Value("${user.address}")
    private String userUrl;
即去掉大括号后面的uri，则apollo更新，代码中的userUrl变量会立即更新，麻烦指点一下原因和修改办法，多谢

**Comment by JerryPlayer** [comment]
可以修改成@value("${http:${user.address}/user/gateway}")来实现，需要保证在apollo上不存在key是http的配置即可，大佬们看看是否有隐患

**Comment by nobodyiam** [comment]
看了下代码，是由于目前会判断表达式是否是以${.*}的形式存在，如果不符合就不会自动更新，后续可以考虑下放宽这个规则。
不过你的case中，是否考虑把整个配置值都放在配置中心？比如`@Value(${user.gateway.address})`

https://github.com/ctripcorp/apollo/blob/124ceaa0679633a4f1420487f83982aeb8707b20/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/property/PlaceholderHelper.java#L123
