### ISSUE TITLE
【用apollo内伤】有请受害者上场

### ISSUE THREAD

**Issue by netroby** [ctripcorp/apollo#3142]
Apollo 配置中心，是个好东西，但是我们在使用过程中， 尝尽了苦难。
不是抨击apollo，而是感觉人生艰难。 加班已经够苦逼，还得被apollo制裁。

说来话长，听我一一道来。

在没有apollo之前，我们配置文件都是在项目代码目录， 分环境,dev,pre.trunk,prod

四个环境网段隔离，互不通信。

修改配置的时候，或者比对配置差异的时候，编辑器diff能很好的工作。

切换到apollo之后，苦难开始了。

每个环境，都部署了独立的apollo

修改配置，要分别登录到每个环境的apollo。

并且配置文件超多之后，你想比对差异，非常麻烦。

我们需要把配置文件，从apollo 复制出来，建一个临时文件A， 然后从另外一个apollo，把配置同样复制出来，建立一个临时文件B，然后在比对两个文件的差异。

然后小心的修改有差异的地方。

日常开发过程中，就不断的执行这样低效率，令人恶心的操作。配置文件非常重要，千万不敢改错了。。

对于我们这些苦逼开发者来说。 apollo 给我们带来的收益，咱们还不好说。

但是日常被虐，已经成了家常便饭。

以上，不知所云： 被apollo搞得太鸡儿烦躁苦闷了，无处倾诉。

潸然泪下，苦逼不堪。

**Comment by cciechao** [comment]
Apollo确实有很多地方需要完善，很多常用的功能都需要二次开发，而且对java是强依赖的，这点特别不友好...

**Comment by standup-jb** [comment]
> Apollo 配置中心，是个好东西，但是我们在使用过程中， 尝尽了苦难。
> 不是抨击apollo，而是感觉人生艰难。 加班已经够苦逼，还得被apollo制裁。
> 
> 说来话长，听我一一道来。
> 
> 在没有apollo之前，我们配置文件都是在项目代码目录， 分环境,dev,pre.trunk,prod
> 
> 四个环境网段隔离，互不通信。
> 
> 修改配置的时候，或者比对配置差异的时候，编辑器diff能很好的工作。
> 
> 切换到apollo之后，苦难开始了。
> 
> 每个环境，都部署了独立的apollo
> 
> 修改配置，要分别登录到每个环境的apollo。
> 
> 并且配置文件超多之后，你想比对差异，非常麻烦。
> 
> 我们需要把配置文件，从apollo 复制出来，建一个临时文件A， 然后从另外一个apollo，把配置同样复制出来，建立一个临时文件B，然后在比对两个文件的差异。
> 
> 然后小心的修改有差异的地方。
> 
> 日常开发过程中，就不断的执行这样低效率，令人恶心的操作。配置文件非常重要，千万不敢改错了。。
> 
> 对于我们这些苦逼开发者来说。 apollo 给我们带来的收益，咱们还不好说。
> 
> 但是日常被虐，已经成了家常便饭。
> 
> 以上，不知所云： 被apollo搞得太鸡儿烦躁苦闷了，无处倾诉。
> 
> 潸然泪下，苦逼不堪。

你们公司是全部无配置化了么。所有的配置都放到apollo里面了么。

**Comment by nobodyiam** [comment]
> 每个环境，都部署了独立的apollo

为啥要这么部署啊，建议的部署方式是 config service/admin service 每个环境单独部署，portal 部署一个，管理不同环境。

![image](https://user-images.githubusercontent.com/837658/85668722-a5028200-b6f1-11ea-85a2-8af1fd70b70a.png)

![screenshot](https://raw.githubusercontent.com/ctripcorp/apollo/master/doc/images/apollo-home-screenshot.jpg)

**Comment by nisiyong** [comment]
使用姿势不对的问题，不需要每个环境部署Portal

**Comment by medusar** [comment]
使用姿势不对。

另外可以通过一些脚本来实现那些复杂的对比逻辑吧

**Comment by netroby** [comment]
@nobodyiam 每个环境网络都是隔离的。访问不了。

**Comment by nisiyong** [comment]
portal部署方式特别一点，可以让运维提供独立网络环境部署，该环境能通其他各个环境。Apollo部署文档应该都有说明清楚，请先仔细看看

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kingzhstyle** [comment]
我想你需要的是导出功能

**Comment by RickJou** [comment]
apollo作为微服务生态中的 配置中心,在CICD和自动化发版过程中优势是配置重用,统一管理,配置环境升级,热发布等等.
理论上说apollo所有环境的权限不会给每一个开发人员.
你说的问题不是apollo带来的问题,而是基础资源中不同环境网络无法通信导致没有一个界面可以看全所有环境的配置.
所以你需要解决的是,找运维打通不同环境的网络.

**Comment by netroby** [comment]
不能打通的。

**Comment by wuyudian1** [comment]
像我们做平台私有化部署的，用一个公共的portal 连接不同客户的配置中心么，不可能吧。
还是文本管理好用，这个东西太依赖手动操作了。要是能从文本批量导入，我只需要将文本配置做成jinja 模板，根据具体项目渲染一遍，然后批量导入，那才是完美。现在每个项目，修改apollo 的配置，就会占据绝大部分的交付时间，心累了，我们做事的有拗不过做决策的领导，必须用这个。

**Comment by TopSpoofer** [comment]
@wuyudian1 确实私有化部署不能打通网络，但是呢我们每个服务都有多个节点，现在就是用jar参数形式进行部署的，每次改一个服务的配置都累到死，apollo可以解决这部分问题，但是如果有10个私有化机房，每次发布就要登录10个apollo去修改配置，这部分问题还是没办法解决的。
