### ISSUE TITLE
client如何通知应用reload配置

### ISSUE THREAD

**Issue by whulyx** [ctripcorp/apollo#3148]
阅读了项目的相关文档之后，发现没有详细讲解client到应用这一部分的逻辑，所以比较好奇。
    目前apollo是支持了自定义应用的配置重载，还是说也支持了第三方应用（如mysql、nginx等）的配置重载？有哪里可以看到对应的实现方式吗？

**Comment by nobodyiam** [comment]
客户端有回调逻辑，应用可以注册监听器，可以参考下 [apollo-use-case](https://github.com/ctripcorp/apollo-use-cases)
