### ISSUE TITLE
现在同一个项目里面没法使用公共namespace进行关联，这个请看看是否有计划实施呢？

### ISSUE THREAD

**Issue by christinkaka** [ctripcorp/apollo#3149]
看了下代码，现在定义公共namespace实际上，其他相同应用/项目里面的集群是无法像其应用或集群去引用的，请帮忙看看这个有无规避方法？
实际诉求是一个应用下有很多集群，有些集群的namespace是有部分内容是一样的，希望是通过default生成公共的，其他集群来来用，根据实际情况来覆盖。

**Comment by nobodyiam** [comment]
公共的配置放在单独的项目里面（比如 A），然后在自己应用（比如 B）中按集群去覆盖一些不同的配置

**Comment by Macrame** [comment]
我也遇到这个问题，建立了项目A,创建了一个namespace叫global.又在项目B中的application这个命名空间去关联了A的global，两个都有内容，都发布了，但B项目真正获取配置时，只取到了B项目本身的application下的配置内容，关联的那个并没有出现

**Comment by Macrame** [comment]
也不叫做获取不到关联的，只是不知道应用到到底是怎么获取关联的，如果通过CURL命令使用`/configs/<serviceB>/default/application`只能获取到B项目自身的，使用`/configs/<serviceB>/default/global`可以获取到那个关联的。但是不知道项目内部是先获致一下application的再获致global的吗？我已经配置了
```
@EnableApolloConfig({"global", "application"})
```
但看起来不管它，它没获致global的，项目启动失败了。

**Comment by nobodyiam** [comment]
```java
@EnableApolloConfig({"global", "application"})
```

如果是这么配置的话，会同时注入`global`和`application`这两个namespace的配置，以`global`优先

**Comment by christinkaka** [comment]
> 公共的配置放在单独的项目里面（比如 A），然后在自己应用（比如 B）中按集群去覆盖一些不同的配置

目前貌似只能这么操作，但如果多个项目出来，最后结果可能会导致权限管理上有更高一个维度的管理关系了，比如这个公共项目的归属，引用范围，使用规范等的。
