### ISSUE TITLE
apolloportaldb field is not compliance with specifications

### ISSUE THREAD

**Issue by jiangcaijun** [ctripcorp/apollo#3150]
**Is your feature request related to a problem? Please describe.**
`apolloportaldb.sql` ,The keywords preset by MySQL are used

Related keywords like : position、key、value、commit。
you can see ： http://dev.mysql.com/doc/refman/5.7/en/keywords.html

in `Favorite` table,
` Position int(32) NOT NULL DEFAULT '10000' COMMENT '收藏顺序',`

in `Item` table,
  `Key varchar(128) NOT NULL DEFAULT 'default' COMMENT '配置项Key',`
 `Value longtext NOT NULL COMMENT '配置项值',`

in `Commit` table,

---
chinese 中文

不允许使用系统关键字如position、key、value、commit等作为表名或字段名：
http://dev.mysql.com/doc/refman/5.7/en/keywords.html

**Comment by jiangcaijun** [comment]
But the cost of modifying table fields is high, so this is a dilemma

**Comment by nobodyiam** [comment]
You are right, but I think it's ok,  as `Reserved words are permitted as identifiers if you quote them as described in Section 9.2, “Schema Object Names”:`

**Comment by jiangcaijun** [comment]
get ，and thank you。i will close this issue
