### ISSUE TITLE
客户端可以修改配置吗？

### ISSUE THREAD

**Issue by dahai118y** [ctripcorp/apollo#3152]
Java客户端可以修改配置项并发布吗？

**Comment by kingzhstyle** [comment]
这个应该是不可以的，发布应该是服务端才具备的功能

**Comment by nobodyiam** [comment]
可以参考下 [Apollo开放平台](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0)，不过一般确实不建议在客户端来修改配置，修改配置还是建议是人来操作
