### ISSUE TITLE
Double-Checked Locking

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [ctripcorp/apollo#3154]
Double-Checked Locking is widely cited and used as an efficient method for implementing lazy initialization in a multithreaded environment.
Unfortunately, it will not work reliably in a platform independent way when implemented in Java, without additional synchronization.

https://github.com/ctripcorp/apollo/blob/885e461cbad087ff01b1509a1b31efc44b09faff/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/DefaultConfigManager.java#L27-L44
Declare a volatile local variable config offers a much more elegant solution

https://github.com/ctripcorp/apollo/blob/885e461cbad087ff01b1509a1b31efc44b09faff/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/DefaultConfigManager.java#L47-L65
Declare a volatile local variable configFile offers a much more elegant solution

**Comment by nobodyiam** [comment]
I think local variable doesn't need to be `volatile`
