### ISSUE TITLE
ApolloConfigChangeListener不起效

### ISSUE THREAD

**Issue by zhanghao001** [ctripcorp/apollo#3162]
问题描述:

使用ApolloConfigChangeListener监听apollo的配置不起效,经过各个配置项的排查,发现问题是app.id的值在项目启动时,不区分大小写,所以旧代码里一直使用的小写.也一直都运行正常.
但是当使用@ApolloConfigChangeListener 监听时,appId的值必须区分大小写的严格一致才能监听到值变更.

建议:
要么启动时,精确匹配app.id的值,要么@ApolloConfigChangeListener监听时也不区分大小写.这种不一致的小问题,害我查了整整半天的代码...

**Comment by nobodyiam** [comment]
#2696 已经支持了配置推送更新不区分大小写
