### ISSUE TITLE
[安全合规加固]数据库明文存储

### ISSUE THREAD

**Issue by k3mlol** [ctripcorp/apollo#3163]
我公司大概有1K+的微服务，已经有800多用上了apollo，现在遇到安全问题是：数据库密码，密钥等核心敏感信息基本存储在apollo上，但是发现存储在数据库的信息是明文的。

这个是存在较大的潜在风险的，不知道携程的apollo团队能加密存储这些信息吗？或者针对这个问题的缓解方案？

**Comment by FlyingPigHasDream** [comment]
You can set the encryption.

**Comment by 1185430411** [comment]
加密操作可以自己做一下呀~

**Comment by k3mlol** [comment]
> 加密操作可以自己做一下呀~

已经上线了。。。怎么改。。。

**Comment by nobodyiam** [comment]
提供两个思路吧：

1. 对这部分配置可以通过[open api](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0)来管理，比如给DBA提供一套界面，做数据库的配置，然后通过open api把加密后的配置存储到apollo，下发到客户端后由数据库访问层的客户端解密后使用。

2. [配置访问秘钥](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#1244-%E9%85%8D%E7%BD%AE%E8%AE%BF%E9%97%AE%E7%A7%98%E9%92%A5)结合[配置查看权限](https://github.com/ctripcorp/apollo/wiki/Apollo%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#61-%E9%85%8D%E7%BD%AE%E6%9F%A5%E7%9C%8B%E6%9D%83%E9%99%90)，配置依然明文存，但是可以确保不会被其它人获取到

**Comment by k3mlol** [comment]
估计看很难搞的了，希望在wiki可以提醒一下之后使用平台的用户吧。自己加密敏感信息，，其实基本上存在apollo的都是敏感信息。。。上了线不好改，没人愿意动核心的源码的

**Comment by nobodyiam** [comment]
see #3187
