### ISSUE TITLE
一个环境下，一个appid下创建多个集群，那么应用读取配置的时候，怎么读取指定appid下面的某个集群的配置呢

### ISSUE THREAD

**Issue by HelloHaiNG** [ctripcorp/apollo#3164]
一个环境下，一个appid下创建多个集群，那么应用读取配置的时候，怎么读取指定appid下面的某个集群的配置呢

**Comment by nobodyiam** [comment]
指定[cluster](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#1242-cluster%E9%9B%86%E7%BE%A4)即可
