### ISSUE TITLE
SOS紧急！！！！！项目通过jvm参数传递集群的值security，读取配置混乱了，已使用很久，今天刚产生的问题。

### ISSUE THREAD

**Issue by zbhtz** [ctripcorp/apollo#3171]
我有一个项目，有两个集群一个default，一个security，springcloud项目通过jvm参数传递集群的值security，发现配置混乱了，有的namespace读取的还是default集群，有的namespace读取的还是security集群。apollo目前已使用很长时间，就今天新添加集群后，产生了这个问题，不知道怎么解决。

**Comment by nobodyiam** [comment]
![image](https://user-images.githubusercontent.com/837658/87223829-cd0d0900-c3b2-11ea-974b-8bed68d87a92.png)

**Comment by zbhtz** [comment]
关键是10个springboot项目，有5个是从security加载配置，另外5个是default加载配置，里面的启动脚本是部署在同一台机器且脚本内容一样

**Comment by nobodyiam** [comment]
开一下客户端 DEBUG 日志，会有详细的信息提示

**Comment by zbhtz** [comment]
你是说springboor 应用项目debug，还是哪里客户端开启debug模式？

**Comment by nobodyiam** [comment]
客户端，log日志级别跳到debug

**Comment by zbhtz** [comment]
调制DEBuUG模式发现配置先是加载指定的security集群配置，后面又去连接default集群了，不是说指定集群后，就不会在连接default集群了么？

**Comment by nobodyiam** [comment]
客户端的log可以发出来看看

**Comment by zbhtz** [comment]
![image](https://user-images.githubusercontent.com/37927220/87263997-65a9a300-c4f1-11ea-966d-81a6b0b0029c.png)

**Comment by zbhtz** [comment]
![image](https://user-images.githubusercontent.com/37927220/87264311-42332800-c4f2-11ea-8944-0816237ad53a.png)

**Comment by nobodyiam** [comment]
这个日志说明客户端指定了cluster为security，不过部分namespace在security集群下没有发布过配置，所以fallback到了default集群

**Comment by zbhtz** [comment]
换了一种配置
