### ISSUE TITLE
关联的命名空间中的配置获取不到

### ISSUE THREAD

**Issue by Macrame** [ctripcorp/apollo#3172]
### 2. 在项目中使用方式
定义了一个`ApolloConfiguration`类，以spring中的Java注解方式使用，其中的@profile可以先不用管它，目前apollo还不支持这个特性。
```
@Configuration
@EnableApolloConfig({"global", "application"})
@Profile({"!development","!test"})
public class ApolloConfiguration {

}
```
如上图，希望引入global和application这两个命名空间，其实global是个public的，就是用来定义一些通用的各个项目都要使用的配置项，application是每个项目自己特有的配置。每个项目都会关联到通用项目的global这个命名空间。
### 4. 在应用启动时的现象
在控制台会输出`/configs/<serviceB>/default/application`这样的请求路径，这样的请求只能访问到本项目application中的配置，获取不到global中定义的通用配置。使用`/configs/<serviceB>/default/global`才可以获致到公用配置。

**项目启动失败**

由于项目中使用了`@Value("${common.token.xxx}")`这样的配置解析，这个配置是在global中配置的，所以项目启动失败了。
现在我的疑问是：
1. 直接访问`/configs/<serviceB>/default/application`这样的路径，是应该能取到关联的命名空间的配置吗，还是本来就只能取到本项目的。如果只能取到本项目的，那apollo的客户端会负责把关联的再发起一次`/configs/<serviceB>/default/global`这样的请求去获取吗？
2. `@EnableApolloConfig`配置多个命令空间，是指配置多个不相关的命令空间吗？如果有关联了，是只配置一个应用的就可以了吗？看文档中[基于Java的配置（推荐）](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#3212-%E5%9F%BA%E4%BA%8Ejava%E7%9A%84%E9%85%8D%E7%BD%AE%E6%8E%A8%E8%8D%90)写的并不清楚，写多个命名空间时，如下:
```
@Configuration
@EnableApolloConfig
public class SomeAppConfig {
  @Bean
  public TestJavaConfigBean javaConfigBean() {
    return new TestJavaConfigBean();
  }
}
   
//这个是稍微复杂一些的配置形式，指示Apollo注入FX.apollo和application.yml namespace的配置到Spring环境中
@Configuration
@EnableApolloConfig({"FX.apollo", "application.yml"})
public class AnotherAppConfig {}
```
这看起来是需要多个`@Configuration`的类，但是`@EnableApolloConfig({"FX.apollo", "application.yml"})`中的**FX.apollo**和**pplication.yml**是什么呢，是命名空间的名字吗，命名空间中的名字为什么差异这么大，一个是`FX.apollo`另一个却是一个application加扩展名。让人非常迷惑。

我的需求就是，定义了一个叫global的公共的命名空间，每个项目自己的application命名空间都会关联到这个global。希望弄清楚 
@EnableApolloConfig到底怎么写，才能让项目中`@Value`这样的表达式能解析公共的或自己的配置。

希望得到回答，非常感谢。
另外，我曾经在其它的issue中提过建议，希望能支持通过enable的方式配置是否启动，同时也支持`@Profile`的特性。不知是否考虑此建议？

**Comment by nobodyiam** [comment]
> 我的需求就是，定义了一个叫global的公共的命名空间，每个项目自己的application命名空间都会关联到这个global。希望弄清楚
@EnableApolloConfig到底怎么写，才能让项目中@Value这样的表达式能解析公共的或自己的配置。

在EnableApolloConfig中设置要加载的namespace即可

```java
@Configuration
@EnableApolloConfig({"global", "application"})
public classAppConfig {}
```

> 支持@Profile的特性

这个是Spring的特性，和 apollo 本身没啥关系
```java
@Configuration
@EnableApolloConfig({"global", "application"})
@Profile("xxx")
public classAppConfig {}
```

> 希望能支持通过enable的方式配置是否启动

这个后续应该会支持
