### ISSUE TITLE
请问管理秘钥的加密方式是什么

### ISSUE THREAD

**Issue by panyaowei** [ctripcorp/apollo#3173]
String timestamp = "1576478257344";
String pathWithQuery = "/configs/100004458/default/application?ip=10.0.0.1";
String secret = "df23df3f59884980844ff3dada30fa97";
String actualSignature = Signature.signature(timestamp, pathWithQuery, secret);

请问变量pathWithQuery是什么意思

**Comment by nobodyiam** [comment]
加密方式是 hmacsha1，pathWithQuery就是加签的内容
