### ISSUE TITLE
About configservice startup happen error about SQL or table

### ISSUE THREAD

**Issue by tiandong19860806** [ctripcorp/apollo#3177]
1. follow install manual by github
- [Y ] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [ Y] I have checked the [FAQ]
reference manual:
https://github.com/ctripcorp/apollo/wiki/分布式部署指南

2. env
OS : centos 7.4 x64
apollo: 1.6.1
mysql: 8.0.18-cluster
java: 12.0.2

3. **Describe the bug**
first execute configdb and portaldb is both OK and check sql OK.
then I modify all apollo component 

4. **To Reproduce**
1.create configdb and portaldb by v1.6.1 sql file "apolloconfigdb.sql and apolloportaldb.sql"
2.modify the each component's config file properties about db connnection string.
3.startup the configservice jar by sh file "script/startup.sh"

5. **Expected behavior**
1.first to clear why the sql happen error to query not exists table and fields "serverconf0_.Cluster",
2.and to know how to fix the error, 
3.Finally to clear whether there is loss some sql file in step 1 "apolloconfigdb.sql and apolloportaldb.sql".

6. **Screenshots**
![image](https://user-images.githubusercontent.com/12596666/87224627-72c37680-c3b9-11ea-8f39-b674ccc9b3ef.png)

**Comment by tiandong19860806** [comment]
[apolloconfigdb.sql.txt](https://github.com/ctripcorp/apollo/files/4906796/apolloconfigdb.sql.txt)
[apolloportaldb.sql.txt](https://github.com/ctripcorp/apollo/files/4906797/apolloportaldb.sql.txt)

**Comment by tiandong19860806** [comment]
[Uploading apollo-configservice.log…]()

[Uploading gc.log…]()

**Comment by nobodyiam** [comment]
apollo-configservice and apollo-adminservice should connect to ApolloConfigDB instead of ApolloPortalDB

**Comment by tiandong19860806** [comment]
Hi Jason,
    this issue is caused by  error configure, it's OK now. thanks.

-----------------------------------

apollo-configservice and apollo-adminservice should connect to ApolloConfigDB instead of ApolloPortalDB

**Comment by tiandong19860806** [comment]
![image](https://user-images.githubusercontent.com/12596666/87241994-4bbd8100-c45b-11ea-852f-bcdf220bf707.png)
