### ISSUE TITLE
普通用户权限控制

### ISSUE THREAD

**Issue by energy-blockchian** [ctripcorp/apollo#3179]
部署方式：k8s部署，
docker镜像: apolloconfig/apollo-portal:latest

普通用户被配置成只允许修改和发布DEV, FAT两个环境的配置，但是UAT， PRO环境的私有namespace参数还是能够看得见，私有namespace里面会有一些数据库的帐号密码，不希望普通用户能够看得到。

**Comment by nobodyiam** [comment]
[apollo如何配置查看权限?](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#12-apollo%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE%E6%9F%A5%E7%9C%8B%E6%9D%83%E9%99%90)
