### ISSUE TITLE
希望可以避免使用8080端口

### ISSUE THREAD

**Issue by Macrame** [ctripcorp/apollo#3183]
在实际使用中，想部署apollo是经常会发现，它所需要的三个端口，特别是8080的端口，已经被其它已经部署好的重要的程序占用，就会带来很多麻烦，虽然理论上可以通过docker的端口映射来解决，但我更希望apollo在一开始就定义三个不以80xx这样的常用端口，比如9261,9262,9263这样的端口，可以有效避免一些冲突。
我当前是在部署时发现kubenetes的apisever使用的已经是8080端口了，apollo无法部署。

**Comment by L-Y-F** [comment]
你可以自己改呀，在各个项目的启动脚本里面就可以自己修改

**Comment by Macrame** [comment]
自己改虽然可以达到效果，但是带来的问题就是它已经变成自定义的了，那么每次发布了新版本，都需要自己来改。而如果官方从开始就避免使用这些很容易冲突的端口，则我们可以一直放心地使用官方构建好的包，而不需要自己打包。

**Comment by L-Y-F** [comment]
> 自己改虽然可以达到效果，但是带来的问题就是它已经变成自定义的了，那么每次发布了新版本，都需要自己来改。而如果官方从开始就避免使用这些很容易冲突的端口，则我们可以一直放心地使用官方构建好的包，而不需要自己打包。

其实不必太纠结这个问题；
1. 如果你的架构设计中，把分布式管理中心设计成独立的模块通过负载进行管理的话，那么也就不会产生端口冲突的问题
2. 如果你把分布式管理中心与自己的业务系统或者其他一些中间件服务耦合到一起的话，那么不管官方初始设置成什么端口，都会有一定的几率与部分用户的端口冲突，这个时候就是需要用户根据自己的服务端口段来自定义设计服务端口的。

**Comment by Macrame** [comment]
这是两个概念，就算一个管理中心正式环境是独立运行的，但在内网测试以及公网测试环境中，仍然有需要和其它主机共用相同服务器的可能。

> 那么不管官方初始设置成什么端口，都会有一定的几率与部分用户的端口冲突

这里说的当然就是指机率的大小了，很显然8080的机率非常大。
我现在是建议官方避免使用8080，并不是说此问题无法解决，但我仍然认为，官方改个端口是最好的做法，或者就像很多其它开源项目一样，可以在启动时通过参数决定监听哪个端口。

**Comment by nobodyiam** [comment]
可以通过 OS 环境变量`SERVER_PORT`修改端口，不需要修改apollo的代码的，8080 只是默认值。

https://github.com/ctripcorp/apollo/blob/0306b71b4637ce1c51fb86b5f09cb0fb241684e0/apollo-configservice/src/main/scripts/startup.sh#L5-L6

**Comment by Macrame** [comment]
非常感谢，这个方案很好。
