### ISSUE TITLE
日志配置logging.level.com.ctrip.framework.apollo=debug放在Apollo不起作用？

### ISSUE THREAD

**Issue by nengc** [ctripcorp/apollo#3184]
若将日志等级配置放在Apollo中进行配置，配置项不起作用。

**Comment by nobodyiam** [comment]
请参考[apollo-use-cases](https://github.com/ctripcorp/apollo-use-cases)

**Comment by szlzhm** [comment]
我也遇到这个问题。springboot+springboot-web模块就出现这个问题。纯springboot没问题。求处理。

**Comment by nobodyiam** [comment]
@szlzhm 可以在本地跑一下[spring-boot-logger](https://github.com/ctripcorp/apollo-use-cases/tree/master/spring-boot-logger) demo

**Comment by szlzhm** [comment]
这个demo的apollo-client是1.5.0版本，我的apollo使用的是0.10.2版本，因为是老项目，不能升级apollo。
另外，我做了一个demo，import的pom和您提到的demo一样，仅仅一个spring-boot-starter和一个apollo-client，没引用其他的。就是不能通过apollo来修改log的级别， 但是apollo中配置的其他配置项是生效的。我在这个项目的data/cache目录中看到项目已经把apollo中配置项完整拉到本地cache了的。但是配置项没有影响到Log的级别。

**Comment by nobodyiam** [comment]
spring-boot-starter-web包含了spring-boot-starter的。

你先不要自己建新项目，在本地把[spring-boot-logger](https://github.com/ctripcorp/apollo-use-cases/tree/master/spring-boot-logger) demo 跑通，然后再比较差异点。

**Comment by szlzhm** [comment]
这个demo是可以运行，但是不能说明没有问题。我把pom贴出来。
我的代码就是在这个例子基础上，修改了pom。
我debug出com.ctrip的日志，看到boot程序从apollo正确拿到配置，并且refresh成功。但是就是无法输出debug日志。
debug出com.ctrip的日志也必须要用-D启动参数中设置logging级别才能够看得到。
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.0.RELEASE</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<artifactId>spring-boot-logger</artifactId>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>com.ctrip.framework.apollo</groupId>
			<artifactId>apollo-client</artifactId>
			<version>1.5.0</version>
		</dependency>

	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>				
			</plugin>

			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<parameters>true</parameters>
					<compilerArgs>
						<arg>-parameters</arg>
					</compilerArgs>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-source-plugin</artifactId>
				<executions>
					<execution>
						<id>attach-source</id>
						<phase>verify</phase>
						<goals>
							<goal>jar-no-fork</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>

**Comment by szlzhm** [comment]
这个demo是可以运行，但是不能说明没有问题。我把pom贴出来。
我的代码就是在这个例子基础上，修改了pom。
我debug出com.ctrip的日志，看到boot程序从apollo正确拿到配置，并且refresh成功。但是就是无法输出debug日志。
debug出com.ctrip的日志也必须要用-D启动参数中设置logging级别才能够看得到apollo-client从apollo-meta来配置的行为日志。
发现日志级别配置项logging.level.com.ctrip放在application的namespace里面才能生效，在其他私有namespace或者关联的namespace里面都不生效。
我在EnableApolloConfig中已经填写了包含logging.level的namespace了，boot程序也从apollo的服务端拉倒logging.level的配置了的。


<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-parent</artifactId>
	<version>2.0.0.RELEASE</version>
</parent>
<modelVersion>4.0.0</modelVersion>
<artifactId>spring-boot-logger</artifactId>
<dependencies>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter</artifactId>
	</dependency>
	<dependency>
		<groupId>com.ctrip.framework.apollo</groupId>
		<artifactId>apollo-client</artifactId>
		<version>1.5.0</version>
	</dependency>
</dependencies>
<build>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>				
		</plugin>

		<plugin>
			<artifactId>maven-compiler-plugin</artifactId>
			<configuration>
				<parameters>true</parameters>
				<compilerArgs>
					<arg>-parameters</arg>
				</compilerArgs>
				<source>1.8</source>
				<target>1.8</target>
			</configuration>
		</plugin>
		<plugin>
			<artifactId>maven-source-plugin</artifactId>
			<executions>
				<execution>
					<id>attach-source</id>
					<phase>verify</phase>
					<goals>
						<goal>jar-no-fork</goal>
					</goals>
				</execution>
			</executions>
		</plugin>
	</plugins>
</build>
