### ISSUE TITLE
拉去配置失败 - Load config failed

### ISSUE THREAD

**Issue by Air433** [ctripcorp/apollo#3185]
com.ctrip.framework.apollo.internals.ConfigServiceLocator - Located config services from apollo.configService configuration: http://14.215.45.89:18080, will not refresh config services from remote meta service!
 com.ctrip.framework.apollo.internals.RemoteConfigRepository - Load config failed, will retry in 1 SECONDS. appId: sdcc-bms-providers, cluster: default, namespaces: application
 com.ctrip.framework.apollo.internals.AbstractConfigRepository - Sync config failed, will retry. Repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository, reason: Load Apollo Config failed - appId: sdcc-bms-providers, cluster: default, namespace: application, url: http://14.215.45.89:18080/configs/sdcc-bms-providers/default/application?ip=192.168.48.1 [Cause: Could not complete get operation [Cause: Unexpected end of file from server]]
 com.ctrip.framework.apollo.internals.RemoteConfigRepository - Load config failed, will retry in 1 SECONDS. appId: sdcc-bms-providers, cluster: default, namespaces: application
 com.ctrip.framework.apollo.internals.LocalFileConfigRepository - Sync config from upstream repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository failed, reason: Load Apollo Config failed - appId: sdcc-bms-providers, cluster: default, namespace: application, url: http://14.215.45.89:18080/configs/sdcc-bms-providers/default/application?ip=192.168.48.1 [Cause: Could not complete get operation [Cause: Unexpected end of file from server]]
 com.ctrip.framework.apollo.internals.RemoteConfigRepository - Load config failed, will retry in 1 SECONDS. appId: sdcc-bms-providers, cluster: default, namespaces: application
teConfigLongPollService-1] WARN  com.ctrip.framework.apollo.internals.RemoteConfigLongPollService - Long polling failed, will retry in 1 seconds. appId: sdcc-bms-providers, cluster: default, namespaces: application, long polling url: http://14.215.45.89:18080/notifications/v2?cluster=default&appId=sdcc-bms-providers&ip=192.168.48.1&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A-1%7D%5D, reason: Could not complete get operation [Cause: Unexpected end of file from server]
 com.ctrip.framework.apollo.internals.LocalFileConfigRepository - Sync config from upstream repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository failed, reason: Load Apollo Config failed - appId: sdcc-bms-providers, cluster: default, namespace: application, url: http://14.215.45.89:18080/configs/sdcc-bms-providers/default/application?ip=192.168.48.1 [Cause: Could not complete get operation [Cause: Unexpected end of file from server]]
 org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
 org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$7f1b7a47] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
 org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$9b357d44] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
teConfigLongPollService-1] WARN  com.ctrip.framework.apollo.internals.RemoteConfigLongPollService - Long polling failed, will retry in 2 seconds. appId: sdcc-bms-providers, cluster: default, namespaces: application, long polling url: http://14.215.45.89:18080/notifications/v2?cluster=default&appId=sdcc-bms-providers&ip=192.168.48.1&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A-1%7D%5D, reason: Could not complete get operation [Cause: Unexpected end of file from server]

**Comment by Air433** [comment]
知道什么问题了，原来阿波罗连不上会直接用上一次的配置……

**Comment by nobodyiam** [comment]
Cause: Unexpected end of file from server

连接服务端报错了
