### ISSUE TITLE
建议对代码做一次完整格式化

### ISSUE THREAD

**Issue by tangxy** [ctripcorp/apollo#3186]
目前基于apollo平台，做了适当的调整，增加对铭感字段加密存储的功能。
开发IDE eclipse， 并使用了项目中的code style配置，设置了保存文件时自动格式化，以及调整import 包顺序。 发现原部分代码的空格，参数位置换行位置均发生了变化。导致差异代码出现的差异较大，不利于以后进行代码合并操作。
因此建议平台对代码在规定 code style的要求下做一次全量的格式。

**Comment by lutianqi-java** [comment]
1、配置错乱的原因主要在于 （1） 发布的时候发布生成release  configuration 的用的hashmap 存储的数据 ，会导致乱序 
2、客户端拉取到配置之后会把拉取到的配置转换成properties ，properties 集成hashtable
3、apollo 发布后配置不能携带注释

**Comment by nobodyiam** [comment]
@lutianqi-java 原帖提得是另一个问题。。。不过针对你这个点，在apollo-1.6.0版本已经做了支持，详见[设置内存中的配置项是否保持和页面上的顺序一致](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#1243-%E8%AE%BE%E7%BD%AE%E5%86%85%E5%AD%98%E4%B8%AD%E7%9A%84%E9%85%8D%E7%BD%AE%E9%A1%B9%E6%98%AF%E5%90%A6%E4%BF%9D%E6%8C%81%E5%92%8C%E9%A1%B5%E9%9D%A2%E4%B8%8A%E7%9A%84%E9%A1%BA%E5%BA%8F%E4%B8%80%E8%87%B4)
