### ISSUE TITLE
apollo demo 登录时提示密码泄露

### ISSUE THREAD

**Issue by hongliuliao** [ctripcorp/apollo#3188]
- [ ] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) of this repository and believe that this is not a duplicate.

**Describe the bug**
在chrome浏览器中, 使用最新版本1.6的demo登录之后, 提示密码泄露, 具体参考如下图

**To Reproduce**
1. 启动1.6版本的apollo服务
2. 打开chrome浏览器, 输入 http://<server>:8070 回车
3. 在登录框中输入用户名 + 密码, 确认

**Screenshots**
![image](https://user-images.githubusercontent.com/1174006/87620722-e1098f80-c751-11ea-8129-1b32da5151b5.png)

### Additional Details & Logs

- Version: 1.6
- Configuration: 默认配置
- Platform and Operating System: mac chrome 83.0.4103.116

**Comment by nobodyiam** [comment]
我使用同样版本的Chomre访问 http://106.54.227.205/ ，貌似没有这个提示？
