### ISSUE TITLE
k8s部署apollo-service报错 ".mysql.rds.aliyuncs.com": must be a valid IP address, (e.g. 10.9.8.7)

### ISSUE THREAD

**Issue by lianfulei** [ctripcorp/apollo#3189]
helm install apollo-service-dev --set configdb.host=1.2.3.4后面省略了
k8s部署apollo-service的时候报这个错误：

Error: Endpoints "apollo-service-dev-apollo-configdb" is invalid: [subsets[0].addresses[0].ip: Invalid value: "*******.mysql.rds.aliyuncs.com": must be a valid IP address, (e.g. 10.9.8.7), subsets[0].addresses[0].ip: Invalid value: "*******.mysql.rds.aliyuncs.com": must be a valid IP address]

不支持阿里云的rds地址吗？

**Comment by nobodyiam** [comment]
如果是域名的话，需要设置service type为`ExternalName`

**Comment by lianfulei** [comment]
嗯，我自己找出来了，依然谢谢你
