### ISSUE TITLE
一个Portal管理多环境时，环境切换，配置显示错乱问题

### ISSUE THREAD

**Issue by hujun427** [ctripcorp/apollo#3196]
一个Portal管理多环境的时候，当点击DEV环境后（拉取配置耗时长），接着点击PRO环境（拉取配置耗时短），最终显示到页面的配置是DEV环境配置（环境列表选中的PRO），如果再进行配置文本修改的话会将DEV配置提交到PRO环境

**Comment by nobodyiam** [comment]
确实有出现这个问题的可能性，想到的一个可能解决方法是在加载到配置后，判断一下当前 env 和加载时的 env 是否一致，可以尝试一下

https://github.com/ctripcorp/apollo/blob/0341e5c80c714fbee8a15031303023bbe3e63dc6/apollo-portal/src/main/resources/static/scripts/controller/config/ConfigNamespaceController.js#L104-L116

**Comment by gp0014** [comment]
这个bug是否修复了。

**Comment by nobodyiam** [comment]
@gp0014 目前还没有人修复这个问题，你有兴趣提交一个 patch 吗？
