### ISSUE TITLE
请问怎么删除误建的集群？

### ISSUE THREAD

**Issue by ShengdongYan** [ctripcorp/apollo#3197]
我不小心新建了一个集群，有办法删除吗？
![image](https://user-images.githubusercontent.com/45132673/88130861-36d8ae80-cc0e-11ea-9005-9887f0258c22.png)

**Comment by liu844869663** [comment]
右上角管理员工具下面有'删除应用、集群、AppNamespce'选项

**Comment by ShengdongYan** [comment]
> 右上角管理员工具下面有'删除应用、集群、AppNamespce'选项

能麻烦截个图吗？我这没有管理员工具呀。

**Comment by ShengdongYan** [comment]
![image](https://user-images.githubusercontent.com/45132673/88271687-1f7eeb80-cd0a-11ea-96d1-b53ded27bf19.png)
我这里选项只有这些

**Comment by liu844869663** [comment]
得管理员用户

**Comment by nobodyiam** [comment]
![image](https://user-images.githubusercontent.com/837658/88446861-2cadee80-ce60-11ea-9bc9-0d89a6c9e586.png)
