### ISSUE TITLE
k8s环境pod"statefulset-apollo-config-server-dev-0"一直重启

### ISSUE THREAD

**Issue by Newbwen** [ctripcorp/apollo#3200]
kubectl describe pod/statefulset-apollo-config-server-dev-0 -n sre
Name:         statefulset-apollo-config-server-dev-0
Namespace:    sre
Priority:     0
Node:         controller/192.168.0.88
Start Time:   Thu, 23 Jul 2020 19:02:01 +0800
Labels:       app=pod-apollo-config-server-dev
              controller-revision-hash=statefulset-apollo-config-server-dev-76988fb4bb
              statefulset.kubernetes.io/pod-name=statefulset-apollo-config-server-dev-0
Annotations:  <none>
Status:       Running
IP:           192.169.0.11
IPs:
  IP:           192.169.0.11
Controlled By:  StatefulSet/statefulset-apollo-config-server-dev
Containers:
  container-apollo-config-server-dev:
    Container ID:   docker://a14fb9dba5c6c54f3865ebfdb5365f29fe61477453ecf8d48d3f82ff8f4cc171
    Image:          apollo-config-server:v1.0.0
    Image ID:       docker://sha256:1b937541f9c72f815d2cfc144fa5018a5140eb0b6b5838b8a16cb0d9471c5e6e
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Thu, 23 Jul 2020 19:23:06 +0800
      Finished:     Thu, 23 Jul 2020 19:26:05 +0800
    Ready:          False
    Restart Count:  7
    Liveness:       tcp-socket :8080 delay=120s timeout=1s period=10s #success=1 #failure=3
    Readiness:      tcp-socket :8080 delay=10s timeout=1s period=5s #success=1 #failure=3
    Environment:
      APOLLO_CONFIG_SERVICE_NAME:  service-apollo-config-server-dev.sre
    Mounts:
      /apollo-config-server/config/application-github.properties from volume-configmap-apollo-config-server-dev (rw,path="application-github.properties")
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-rjh8z (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  volume-configmap-apollo-config-server-dev:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      configmap-apollo-config-server-dev
    Optional:  false
  default-token-rjh8z:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-rjh8z
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                    From                 Message
  ----     ------     ----                   ----                 -------
  Normal   Scheduled  25m                    default-scheduler    Successfully assigned sre/statefulset-apollo-config-server-dev-0 to controller
  Normal   Created    25m                    kubelet, controller  Created container container-apollo-config-server-dev
  Normal   Started    25m                    kubelet, controller  Started container container-apollo-config-server-dev
  Normal   Pulled     10m (x6 over 25m)      kubelet, controller  Container image "apollo-config-server:v1.0.0" already present on machine
  Warning  Unhealthy  5m19s (x227 over 25m)  kubelet, controller  Readiness probe failed: dial tcp 192.169.0.11:8080: connect: connection refused
  Warning  BackOff    13s (x8 over 81s)      kubelet, controller  Back-off restarting failed container

**Comment by nobodyiam** [comment]
看下应用日志

**Comment by songxuexian** [comment]
遇到了同样的问题

**Comment by songxuexian** [comment]
我定位了下原因，是我的服务器上的CPU占满了，我用nodeselecter制定了一台空闲了服务器，就OK了
