### ISSUE TITLE
在k8s中部署portal，并设置prefix.path不生效

### ISSUE THREAD

**Issue by AndrewDi** [ctripcorp/apollo#3201]
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) of this repository and believe that this is not a duplicate.

**Describe the bug**
我在k8s中部署了apollo 1.7.0，需要使用ingress对外暴露portal服务，并且path是http://xxx/apollo

**To Reproduce**
1. Deploy apollo in k8s
2. set prefix.path=/apollo
3. brower http://xxx/apollo，page could not rander as expected

**Expected behavior**
通过ingress能够访问portal

**Screenshots**

### Additional Details & Logs

- Version
- Error logs
- Configuration
- Platform and Operating System

**Comment by nobodyiam** [comment]
prefix.path结合独立的nginx是可以工作的，详见[16. Portal挂载到nginx/slb后如何设置相对路径？](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#16-portal%E6%8C%82%E8%BD%BD%E5%88%B0nginxslb%E5%90%8E%E5%A6%82%E4%BD%95%E8%AE%BE%E7%BD%AE%E7%9B%B8%E5%AF%B9%E8%B7%AF%E5%BE%84)

ingress不生效，可能得看下在ingress上如何配置才能实现独立nginx的配置效果

```
location /apollo/ {
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://127.0.0.1:8070/;
}
```

**Comment by AndrewDi** [comment]
@nobodyiam 我的ingress也是用nginx来做的，查看配置，也是差不多的

**Comment by nobodyiam** [comment]
可以看下最终生成的nginx配置文件是什么样的，我之前也尝试过ingress，不过没有配置出类似下面的效果

```
location /apollo/ {
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://127.0.0.1:8070/;
}
```

**Comment by AndrewDi** [comment]
@nobodyiam 是的，域名是/没问题，如果配置`/apollo`，就不行呢。

**Comment by nobodyiam** [comment]
#3205 中增加了对`server.servlet.context-path`的支持，可以解决prefix.path不生效的问题，1.7.0-SNAPSHOT镜像已更新，可以按照如下配置验证：

```yaml
# use /apollo as root, should specify config.contextPath as /apollo
ingress:
  enabled: true
  hosts:
    - paths:
        - /apollo

config:
  ...
  contextPath: /apollo
  ...
```
