### ISSUE TITLE
createAppInLocal下的并发问题

### ISSUE THREAD

**Issue by JiZhihan** [ctripcorp/apollo#3203]
发现portal数据库app表中存在appid相同的记录，导致现在app删除不了，也不能进行覆盖。
看了下代码，猜测是并发引起的问题，在插入前的判断没有加锁，所以插入两条一样的数据，个人建议在appid加上Unique限制，其他表应该也要做同样的限制，不然都会有并发问题

**Comment by JiZhihan** [comment]
用了Jmeter做了下并发测试，确认可以插入多条同样appid记录，导致该app查看/删除 会报错

**Comment by JiZhihan** [comment]
alter   table app modify AppId varchar(100) default 'default' not null comment 'AppID';
ALTER   TABLE app ADD CONSTRAINT appUnique UNIQUE (AppId,IsDeleted);

把appid的长度变为100，不然创建唯一索引报错
然后创建唯一约束(AppId,IsDeleted) 

不知道这样的解决方法有什么问题没有

**Comment by nobodyiam** [comment]
目前确实有这个隐患

```
创建唯一约束(AppId,IsDeleted)
```

这个是不可行的，因为同一个appId可以被删除多次，比较好的方式是增加一个删除时间，然后创建唯一约束(AppId, DeletedTimeStamp)，不过这个对已有系统升级有较大成本（需要事先填充DeletedTimeStamp数据），所以一直未实行。

**Comment by JiZhihan** [comment]
> 目前确实有这个隐患
> 
> ```
> 创建唯一约束(AppId,IsDeleted)
> ```
> 
> 这个是不可行的，因为同一个appId可以被删除多次，比较好的方式是增加一个删除时间，然后创建唯一约束(AppId, DeletedTimeStamp)，不过这个对已有系统升级有较大成本（需要事先填充DeletedTimeStamp数据），所以一直未实行。

唯一约束(AppId,IsDeleted)确实会导致app只能删除一次，但考虑到具体使用场景以及改动成本，这个方案暂时比较折衷。您说的这个方案也给我一定帮助，感谢！
