### ISSUE TITLE
多模块项目接入Apollo无法读取本地配置

### ISSUE THREAD

**Issue by xiehanghang** [ctripcorp/apollo#3207]
项目是 SpringBoot 搭建的一个多模块项目
有一个 web 包，一个 common 包。
目前所有配置还在本地，未迁移到 Apollo 上。
web 启动时需要初始化 common 的 bean，现在的问题是无论是 @EnableApolloConfig 还是 apollo.bootstrap.enabled=true 的方式都不能成功初始化 common 包的 bean，从而导致 web 启动失败（还未把配置迁移到 Apollo，配置都还在本地）
正常来说不是应该配置中心没读到，然后从本地读取吗？

确定没有 @PropertyPlaceholderConfigurer 注解。
这里有个跟我很相像的问题：https://springboot.io/t/topic/1069/3

**Comment by nobodyiam** [comment]
如果配置在本地的话，那应该和apollo就没啥关系了。
可以上传一个demo，大家一起看看。

**Comment by xiehanghang** [comment]
> 如果配置在本地的话，那应该和apollo就没啥关系了。
> 可以上传一个demo，大家一起看看。

这是 Web 模块的启动类（未加 Apollo 启动的相关代码）

```java
@EnableSwagger2
@SpringBootApplication
@EnableRetry
@EnableAspectJAutoProxy(proxyTargetClass = true, exposeProxy = true)
@ComponentScan(basePackages = "com.company.department")
public class WebApplication {

  public static void main(String[] args) {
    Properties properties = new Properties();
    properties.put("department.open-falcon.metric.enabled", ConfigFactory.load().getString("department.open-falcon.metric.enabled"));

    SpringApplication application = new SpringApplication(WebApplication.class);
    application.setDefaultProperties(properties);

    application.run(args);
  }
}
```

这是 web 模块依赖 common 模块的其中一个 bean（web启动需要读取配置初始化这些 bean）

```java
@Configuration
@ConfigurationProperties(prefix = "redis")
@Data
@ToString
public class RedisConfiguration {

  private String sentinels;

  private String password;
..........
```



- 在没有引入 Apollo 的时候，common 模块的 RedisConfiguration 是能正确读取 web模块下的 redis.yml 配置并进行初始化的。

  引入之后 Apollo 之后，RedisConfiguration 就读取不到配置的属性从而导致初始化失败。

  但是可以读取到配置在 Apollo 的属性。

- SpringBoot 版本是 2.3.1。

- 引入 Apollo，看控制台发现一个 WARN 信息：

```
Multiple PropertySourcesPlaceholderConfigurer beans registered [properties, org.springframework.context.support.PropertySourcesPlaceholderConfigurer], falling back to Environment

Bean 'redisConfiguration' of type [com.xxx.common.kit.RedisConfiguration$$EnhancerBySpringCGLIB$$e896e19a] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
```

会不会是这个问题？

**Comment by nobodyiam** [comment]
@xiehanghang 是否可以上传一个完成的demo？从你贴的信息并没有看到让spring boot读取redis.yml文件的配置项？
