### ISSUE TITLE
发布后更新延迟问题

### ISSUE THREAD

**Issue by JiZhihan** [ctripcorp/apollo#3209]
36分和40分的时候release了一次
![360截图20200728151615320](https://user-images.githubusercontent.com/56993966/88631798-562b7c00-d0e5-11ea-950a-e1ed95791a1e.jpg)
配置等到39分和44分才更新
![1](https://user-images.githubusercontent.com/56993966/88631164-4eb7a300-d0e4-11ea-8de4-af8ee842d107.png)
另外还发现其他的error日志
![2](https://user-images.githubusercontent.com/56993966/88631384-a81fd200-d0e4-11ea-9363-d97a629be197.png)
这种是属于长轮询失败，所以靠定时轮询去更新导致的延迟？如果是这样，应该怎么排查长轮询失败的原因呢？

**Comment by nobodyiam** [comment]
看上去是apollo-core的版本和apollo-client不匹配所致，看下实际运行时apollo-core的版本吧，是否有`com.ctrip.framework.apollo.core.dto.ApolloConfigNotification#getMessages`这个方法

**Comment by JiZhihan** [comment]
感谢解答！
