### ISSUE TITLE
通过第三方应用管理Apollo配置，生成一个token，如何使用能够管理多个appid

### ISSUE THREAD

**Issue by wangjhfree** [ctripcorp/apollo#3211]
另外，如何通过接口创建一个应用，并获取到appid

**Comment by wangjhfree** [comment]
另外，如何通过接口创建一个应用，并获取到appid

**Comment by nobodyiam** [comment]
1. 生成一个token，如何使用能够管理多个appid
对这个token多次赋权即可

2. 如何通过接口创建一个应用，并获取到appid
这个目前不支持，需要在页面上创建
