### ISSUE TITLE
appId字段长度真的需要超过32个字符

### ISSUE THREAD

**Issue by Macrame** [ctripcorp/apollo#3213]
apollo配置服务限制为32个字符是真的非常太不方便了，项目的id基于每个公司有自己的规则，加上公司名称和团队名称这些前缀，很容易就超过32个了，至于你们考虑的是否能记住，这个我认为并不需要考虑，记不住的人自然会使用短的，不应该怕人记不住就强制不允许使用长的名称啊，况且谁会记这个id呢，没有必要记住，看项目时可以看Name的。强烈建议放开appId字段长度!!!这非常影响大家的使用，我把数据库中的字段长度都改了，但前端校验还是会限制为32，暂时还不想改代码自己编译，请问可以加到下一个版本的功能中吗？
我看到有好几次讨论这个相关问题
#2418

**Comment by nobodyiam** [comment]
可以提交个 PR，扩容一下，需要注意相关的表和校验逻辑都需要调整一下

**Comment by Macrame** [comment]
已经提交了一个PR，表和校验逻辑都改了，但看起来单元测试失败了，不过我确信并非由于我的修改而导致失败。我只修改了数字32->64，你有空看一下，谢谢！

**Comment by Macrame** [comment]
已经补充提交了一些k8s和flyway等那些文件夹中的AppId也增加到64了。你再看一下，谢谢！

**Comment by Macrame** [comment]
大佬，可以合并了吗
