### ISSUE TITLE
apollo创建一个普通用户能看到所有的项目，虽然没有操作的权限，但是对于数据配置很不安全

### ISSUE THREAD

**Issue by 1204709592** [ctripcorp/apollo#3214]
通过apollo页面，创建一个新用户，该用户可以在搜索项目里看到所有的项目，点进去还能看到内容，虽然没有操作权限，但是对于数据很不安全

**Comment by nobodyiam** [comment]
可以参考 [配置查看权限](https://github.com/ctripcorp/apollo/wiki/Apollo%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#61-%E9%85%8D%E7%BD%AE%E6%9F%A5%E7%9C%8B%E6%9D%83%E9%99%90)

**Comment by k3mlol** [comment]
还是建议写了安全的best practice. 配置中心算得上一个公司的重中之重了。

**Comment by nobodyiam** [comment]
@k3mlol 多谢建议，已经增加

![image](https://user-images.githubusercontent.com/837658/89702801-9e655c80-d977-11ea-9593-11dca1938969.png)
