### ISSUE TITLE
请教哪些地方有必要作为监控指标

### ISSUE THREAD

**Issue by JiZhihan** [ctripcorp/apollo#3215]
公司内部把Apollo接入了监控，目前只是监控jvm和服务器端口，请问源码中哪些指标有必要进行监控呢，比如发布的次数/用时？希望能得到一些建议，谢谢了！

**Comment by nobodyiam** [comment]
apollo自身有很多监控埋点，可以参考下[监控相关](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1#%E4%BA%94%E7%9B%91%E6%8E%A7%E7%9B%B8%E5%85%B3)
