### ISSUE TITLE
在发布接口中，messageSender.sendMessage的作用是什么？

### ISSUE THREAD

**Issue by andyyumiao** [ctripcorp/apollo#3223]
@Transactional
  @PostMapping("/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/releases")
  public ReleaseDTO publish(@PathVariable("appId") String appId,
                            @PathVariable("clusterName") String clusterName,
                            @PathVariable("namespaceName") String namespaceName,
                            @RequestParam("name") String releaseName,
                            @RequestParam(name = "comment", required = false) String releaseComment,
                            @RequestParam("operator") String operator,
                            @RequestParam(name = "isEmergencyPublish", defaultValue = "false") boolean isEmergencyPublish) {
    Namespace namespace = namespaceService.findOne(appId, clusterName, namespaceName);
    if (namespace == null) {
      throw new NotFoundException(String.format("Could not find namespace for %s %s %s", appId,
                                                clusterName, namespaceName));
    }
    Release release = releaseService.publish(namespace, releaseName, releaseComment, operator, isEmergencyPublish);

    //send release message
    Namespace parentNamespace = namespaceService.findParentNamespace(namespace);
    String messageCluster;
    if (parentNamespace != null) {
      messageCluster = parentNamespace.getClusterName();
    } else {
      messageCluster = clusterName;
    }
    messageSender.sendMessage(ReleaseMessageKeyGenerator.generate(appId, messageCluster, namespaceName),
                              Topics.APOLLO_RELEASE_TOPIC);
    return BeanUtils.transform(ReleaseDTO.class, release);
  }

**Comment by nobodyiam** [comment]
[2.1 配置发布后的实时推送设计](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1#21-%E9%85%8D%E7%BD%AE%E5%8F%91%E5%B8%83%E5%90%8E%E7%9A%84%E5%AE%9E%E6%97%B6%E6%8E%A8%E9%80%81%E8%AE%BE%E8%AE%A1)

**Comment by lutianqi-java** [comment]
1、configserver  NotificationControllerV2  类会轮询releaseMessage 中的消息 
2、发布消息后，轮询到客户端有需要发布的新的配置，长链接 会返回消息给客户端，客户端会调用queryConfig 的接口查询最新的数据
3、没这个发布message 方法的话只能等客户端定时调用queryConfig 接口才能查询到最近消息，保证不了配置实时性

**Comment by andyyumiao** [comment]
> 1、configserver NotificationControllerV2 类会轮询releaseMessage 中的消息
> 2、发布消息后，轮询到客户端有需要发布的新的配置，长链接 会返回消息给客户端，客户端会调用queryConfig 的接口查询最新的数据
> 3、没这个发布message 方法的话只能等客户端定时调用queryConfig 接口才能查询到最近消息，保证不了配置实时性

收到，非常感谢！！

**Comment by andyyumiao** [comment]
> [2.1 配置发布后的实时推送设计](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1#21-%E9%85%8D%E7%BD%AE%E5%8F%91%E5%B8%83%E5%90%8E%E7%9A%84%E5%AE%9E%E6%97%B6%E6%8E%A8%E9%80%81%E8%AE%BE%E8%AE%A1)

收到，多谢！！
