### ISSUE TITLE
配置中怎么添加不可见字符

### ISSUE THREAD

**Issue by godlockin** [ctripcorp/apollo#3226]
有些配置包含业务属性，比如停止词之类的，那就希望可以维护一个类似列表结构的数据。

目前我们使用的是通过键盘不可输入字符（e.g. \001）做分隔符，以避免出现停止词中包含常见分隔符（e.g. , | # 之类）无法正常处理的情况。

但是在apollo的value里加入 \001 ，程序会把它直接接收为字符串：
config：
这个\001可以\001忽略
value:
这个\001可以\001忽略
expect:
这个[\001转绎]可以[\001转绎]忽略

config：
这个\\001可以\\001忽略
value:
这个\\001可以\\001忽略
expect:
这个[\001转绎]可以[\001转绎]忽略

**Comment by nobodyiam** [comment]
apollo会把用户的原始输入传递给程序，所以用户如果输入的是`\001`这 **4** 个字符，那么程序中接收到的也就是这个 **4** 个字符，如果用户输入的是`\001`所代表的那 **1** 个不可见字符，那么程序接收到的也就是这 **1** 个不可见字符，所以问题是如何输入这个不可见字符？

> apollo 支持 utf8mb4 编码，所以对一些emoji，如`🚀`都是可以输入并接收的，不过`\001`这个字符如何输入得研究一下了
