### ISSUE TITLE
使用helm 部署apollo portal报错

### ISSUE THREAD

**Issue by mingbo00** [ctripcorp/apollo#3229]
安装portal：helm install apollo-portal apollo/apollo-portal --values values.yaml --debug
pod日志：
![image](https://user-images.githubusercontent.com/48288455/89605750-e06f9f00-d8a0-11ea-9c85-44ae01d8359f.png)

repo版本：
![image](https://user-images.githubusercontent.com/48288455/89605885-3e9c8200-d8a1-11ea-9aca-d238bcc04472.png)

values文件db配置：
![image](https://user-images.githubusercontent.com/48288455/89605944-65f34f00-d8a1-11ea-8f3e-32756c00e790.png)

**Comment by nobodyiam** [comment]
![image](https://user-images.githubusercontent.com/837658/89700863-7b7d7d00-d964-11ea-9053-56acb855e4aa.png)

profiles 你改写了？应该要有`github`的，另外，`auth`和`ldap`应该只写其中一个，要么是用原生的登录方式，要么是用ldap方式

**Comment by mingbo00** [comment]
![image](https://user-images.githubusercontent.com/48288455/92316939-5ea09c00-f02d-11ea-8194-1f6249b3bbad.png)
@nobodyiam 谢谢，我给解决了，我把数据库配置写到环境变量里就可以了
