### ISSUE TITLE
有更轻的使用方式吗？

### ISSUE THREAD

**Issue by mofadeyunduo** [ctripcorp/apollo#3237]
**Is your feature request related to a problem? Please describe.**
```
ConfigService.getAppConfig();
```
在文档里看到了这种使用方式，里面获取 META-Server 地址是通过各种类似 Spring 的方式注入的，比如 properties。

**Describe the solution you'd like**
更通用的解决方案，里面可以指定参数，生成 ConfigService。如果实际上有这种方法请通知我。

**Describe alternatives you've considered**

**Additional context**
我在做 Flink 应用，如果开发者不用、或者没用过  Spring 框架，那么这一套类似 Spring 框架的做法不是让人很好理解。

**Comment by harvies** [comment]
classpath下apollo-env.properties或者/opt目录都可以被加载

**Comment by harvies** [comment]
> classpath下apollo-env.properties或者/opt目录都可以被加载

https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97

![image](https://user-images.githubusercontent.com/16585330/89752345-94259880-db06-11ea-91a2-1eeb4b5e5033.png)

**Comment by mofadeyunduo** [comment]
感谢楼上的回答。文档我之前是看过的，我觉得我是了解大部分配置的。

我是觉得应该提供一个 ConfigService.getAppConfig("apollo path", "project", "namespace", "env") 这样很简单底层简单的接口，提供了 http 服务的基本封装就可以。我本身是从 Java 写到 Golang 又写到 Java（Flink），个人可能对 Java 这种配置方式比较厌恶，以前查看过 Spring 代码的时候复杂的工厂模式、深层次的继承会让人“迷路”。此外，我觉得跨平台的使用 Apollo（本人是 Golang 加上 Java 开发），对于 Java -D 选项会让其他语言的用户比较困惑。所以希望有一层很简单的 API，封装了 Apollo 的 HTTP 接口（本人在 Golang 代码里就是这么做的）。在上层比如本地容错其实是一个附加的业务（例如 viper，当然 viper 不一定是这种思想），也有很多种不同的实现，可以作为插件实现，相当于底层存储引擎不一样。

所以我的根本目的是想问有没有简单的 HTTP API 调用，我直接可以构造出来访问。

**Comment by nobodyiam** [comment]
@mofadeyunduo 可以看下[其它语言客户端接入指南](https://github.com/ctripcorp/apollo/wiki/%E5%85%B6%E5%AE%83%E8%AF%AD%E8%A8%80%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97)

**Comment by jiayaoO3O** [comment]
System.setProperty("env", env);
        System.setProperty(env.toLowerCase() + "_meta", metaServer);
        System.setProperty("app.id", appid);
        System.setProperty("apollo.cluster", cluster);
        Config config = ConfigService.getConfig(namespace);
        System.clearProperty("env");
        System.clearProperty(env.toLowerCase() + "_meta");
        System.clearProperty("app.id");
        System.clearProperty("apollo.cluster");
        return config;
@mofadeyunduo
