### ISSUE TITLE
请问Apollo的开源协议允许修改门户上面的logo和文字吗？

### ISSUE THREAD

**Issue by izhijian** [ctripcorp/apollo#3239]
![image](https://user-images.githubusercontent.com/18110266/89985600-e6ed8480-dcad-11ea-846f-360b03a439cc.png)

**Comment by jiayaoO3O** [comment]
哈哈哈哈用了携程的框架留个logo不过分吧哈哈宋哥心态炸了

**Comment by izhijian** [comment]
> 哈哈哈哈用了携程的框架留个logo不过分吧哈哈宋哥心态炸了

界面有点丑，想让前端优化，美化下门户，不知道行不行。会保留来源

**Comment by kezhenxu94** [comment]
内部怎么用都没问题。如果对外提供云服务，就得声明来源
