### ISSUE TITLE
对于私有的namespace,除了properties的namespace有灰度发布，同步配置，比较配置，撤销配置等相关操作，其他的namespace没有这些操作

### ISSUE THREAD

**Issue by dimiduhezi** [ctripcorp/apollo#3240]
对于私有的namespace,除了properties的namespace有灰度发布，同步配置，比较配置，撤销配置等相关操作，其他的namespace没有这些操作，这是原本就没有吗

**Comment by nobodyiam** [comment]
duplicated with #2927
