### ISSUE TITLE
非default集群关联NameSpace之后不做改动，获取不到配置？

### ISSUE THREAD

**Issue by ImLeoChan** [ctripcorp/apollo#3241]
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) of this repository and believe that this is not a duplicate.

**Describe the bug 场景描述**
![namespace关联bug-1](https://user-images.githubusercontent.com/26133407/90131100-272c3000-dd9e-11ea-812a-cfc45c62168a.jpg)
在「app-a」项目有集群「default」和命名空间「ns-1」，
在另外一个项目「app-b」中有两个集群，「default」和「cluster-b」，都关联了命名空间「ns-1」
![namespace关联bug-2](https://user-images.githubusercontent.com/26133407/90131466-c6e9be00-dd9e-11ea-97cf-4bb48de1c933.jpg)
其中在项目「app-b」中，「default」集群关联的命名空间ns-1覆盖了某些配置，「cluster-b」关联的命名空间ns-1没有做任何改动，
访问config服务的api：http://config服务api/app-b/cluster-b/default/ns-1 是访问不到的，
实际上会访问 http://config服务api/app-b/default/default/ns-1
想问问这个是bug吗？在这种场景下，http://config服务api/app-b/cluster-b/default/ns-1 就访问不到了

**Expected behavior**
在以上描述的场景中，希望访问 http://config服务api/app-b/cluster-b/cluster-b/ns-1 能获取集群「cluster-b」中ns-1的配置，而不是集群「default」中ns-1的配置

### Additional Details & Logs

- Version：1.6.1&1.7

**Comment by nobodyiam** [comment]
应该是能访问到的，可以在demo站点测试一下：http://106.54.227.205/

**Comment by GuiSong01** [comment]
我也遇到了同样的问题，只能获取到default集群下的配置，看了一下apollo-configservice queryConfigs接口代码，这个应该是Bug。
原因：
1、
先用接口传入的clusterName查询一下namespace的配置：
![image](https://user-images.githubusercontent.com/18419834/91957193-4af8eb00-ed38-11ea-9b55-5b9eca274237.png)
查询配置的逻辑如下：
![image](https://user-images.githubusercontent.com/18419834/91957306-6a901380-ed38-11ea-9f90-e4481df42ff9.png)
先用当前的cluster名称查询，也就是问题中的cluster-b，由于没有覆盖，所以查询为空。
然后通过dataCenter查询，dataCenter一般跟path里面的clusterName一样，所以还是查询不到。
最后会走到备用查询，查询到default集群的，所以这个方法最后返回的default集群的配置。

2、
查询完特有的，接下来会去查询公共的配置。
![image](https://user-images.githubusercontent.com/18419834/91957609-d83c3f80-ed38-11ea-92a7-6d30217e68e3.png)
这个时候共查询两个release，release[0]是当前项目default的配置，release[1]是公共namespace的配置。

3、
合并配置，问题就出现在合并配置的时候
![image](https://user-images.githubusercontent.com/18419834/91958119-7fb97200-ed39-11ea-866c-cbd88e5a7ddf.png)
把release表反转了，default的配置会覆盖公共的配置，最后获取到的就是当前项目default集群的配置。

当前使用的规避方案：
项目 app-b中cluster-b继承公共的namespace后，覆盖其中一个以上配置。

**Comment by nobodyiam** [comment]
@GuiSong01 你描述的是设计中的行为，和 @ImLeoChan 描述的应该不是同一件事情

**Comment by GuiSong01** [comment]
是同一个事情，@ImLeoChan 描述的是问题，我描述的是问题出现的原因
