### ISSUE TITLE
apollo服务端找不到docker中的java客户端

### ISSUE THREAD

**Issue by guajue666** [ctripcorp/apollo#3246]
报错如下 
c.c.f.apollo.internals.RemoteConfigLongPollService Long polling failed, will retry in 1 seconds. appId: blood-kb, cluster: default, namespaces: application+application.yml, long polling url: http://192.168.110.206:9080/notifications/v2?cluster=default&appId=blood-kb&ip=172.17.0.9&notifications=%5B%7B%22namespaceName%22%3A%22application.yml%22%2C%22notificationId%22%3A115%7D%5D, reason: Could not complete get operation [Cause: Read timed out]

**Comment by jiayaoO3O** [comment]
我也想知道为什么平时用的时候很正常, 但是程序会在后台包Warning警告说Could not complete get operation [Cause: Read timed out], 正常调用可以用为什么长连接会报timed out警告呢

**Comment by nobodyiam** [comment]
192.168.110.206 这个 IP 是config service的机器ip还是负载均衡的ip？
