### ISSUE TITLE
apollo portal 管理 k8s 多集群问题

### ISSUE THREAD

**Issue by zhousbo** [ctripcorp/apollo#3252]
**Is your feature request related to a problem? Please describe.**
我们每套环境分别搭建了一套 k8s 集群，我们希望使用一个 portal 管理多个 k8s 集群中的配置中心，但是 portal 服务启动之后默认从 meta server 中获取 admin service IP ，但是获取的地址是 k8s 集群内部 IP ，外部无法访问，导致现有 apollo on k8s 只适用于单个 k8s 集群，portal 无法实现跨集群的管理能力

**Describe the solution you'd like**
portal 是否可以自定义 admin server地址，如果没有定义 admin server地址，则从 meta server 获取admin server 地址， k8s 中的 admin server 则通过 ingress 或 NodePort 方式在内网暴露，由此实现跨集群的管理能力

**Comment by zhangggg** [comment]
可以的，今天刚调通，走ingress 或者nodeport 都能做，走ingress 的话记得把超时时间配长点

**Comment by zhousbo** [comment]
请教一下是将admin server暴露出去，然后修改admin server向eureka注册的地址实现的吗？

**Comment by zhousbo** [comment]
> 
> 
> 可以的，今天刚调通，走ingress 或者nodeport 都能做，走ingress 的话记得把超时时间配长点

请教一下是将admin server暴露出去，然后修改admin server向eureka注册的地址实现的吗？

**Comment by zhousbo** [comment]
我这里解决办法是往admin server和config server注入环境变量，并将服务以NodePort方式暴露出去
```
EUREKA_INSTANCE_PREFERIPADDRESS: true
EUREKA_INSTANCE_IPADDRESS: LB_IP
```
改变服务向eureka注册时的 IP 地址，这个IP地址是一个LB的地址，LB 8080端口转发给后端的NodePort

**Comment by zhangggg** [comment]
> > 可以的，今天刚调通，走ingress 或者nodeport 都能做，走ingress 的话记得把超时时间配长点
> 
> 请教一下是将admin server暴露出去，然后修改admin server向eureka注册的地址实现的吗？

我用的k8s版本，配置项可能跟你长得不太一样。
不过核心思路是，你注册进注册中心的服务地址，要能被外部（另外一个k8s）访问到

**Comment by zhangggg** [comment]
> @zhangggg helm里面可以设置`configService.config.adminServiceUrlOverride`，详见[配置项说明](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#24133-%E9%85%8D%E7%BD%AE%E9%A1%B9%E8%AF%B4%E6%98%8E)

这个配置看到了，楼上那位好像不是 helm 部署的，所以配置条目不太一样

**Comment by ccccaoxin** [comment]
apollo以ymal方式在k8s部署时，这个配置怎么操作呢？请教下 @nobodyiam

**Comment by nobodyiam** [comment]
@ccccaoxin [configService.config.adminServiceUrlOverride](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_241344-%e6%8c%87%e5%ae%9ameta-server%e8%bf%94%e5%9b%9e%e7%9a%84apollo-configservice%e5%9c%b0%e5%9d%80) should work

**Comment by szpnygo** [comment]
@nobodyiam 这种情况下是不是就无法保证admin和config内网了？client拿到的也是公网地址，走公网？

可以返回2个地址吗？portal拿公网地址，client拿内网地址。
