### ISSUE TITLE
Apollo 单env 多cluster 部署问题

### ISSUE THREAD

**Issue by zhangggg** [ctripcorp/apollo#3257]
我们生产环境有三个机房 A, B, C，想让三机房的应用访问各自的机房的 configService；同时，想做到数据库隔离，三机房的configDB使用自身的，以保证各自数据库异常时不影响其他两机房

想问下，使用一个env （PRD）三个cluster 能否实现该部署方式

看了[eureka-url](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#1-eurekaserviceurl---eureka%E6%9C%8D%E5%8A%A1url) 这个配置，似乎无法把configDB 数据库隔离开

**Comment by zhangggg** [comment]
> 如果是一个环境，那么configdb是同一个，如果是三个环境，那么configdb是三个独立的。
> 不过不建议三机房数据库隔离，除非三机房的数据完全不一样，不然配置成本较高。

如果按单环境单个configdb配置，那数据库就存在跨机房访问，这对我们这来说不太合适
在我这个应用场景里，是不是使用env 替代cluster 的概念更合适？

**Comment by wxlevel** [comment]
> ，是不是使用env 替代cluster 的概念更

我们就是按照cluster来划分环境的，比如 cn-dev, cn-stage, cn-pro, hk-stage,hk-pro,us-stage,us-pro 等等，
每个cluster 有各自独立的configdb

**Comment by zhangggg** [comment]
> 我们就是按照cluster来划分环境的，比如 cn-dev, cn-stage, cn-pro, hk-stage,hk-pro,us-stage,us-pro 等等，
> 每个cluster 有各自独立的configdb

是单个env里面设置了这么多个cluster吗？  配置方式方便提供参考下吗

**Comment by wxlevel** [comment]
> 是单个env里面设置了这么多个cluster吗？ 配置方式方便提供参考下吗

cn-dev    1台metaservice, 对应的有1个db  部署在公司内部
cn-stage 1台metaservice, 对应的有1个db  部署在公司内部
cn-pro    2台metaservice, 对应的有2个db  部署在阿里云
hk-stage 1台metaservice, 对应的有1个db  部署在HK阿里云
hk-pro    2台metaservice, 对应的有2个db  部署在HK阿里云
us-stage 1台metaservice, 对应的有1个db  部署在US Amazon
us-pro    2台metaservice, 对应的有2个db  部署在US Amazon

然后 2台 protal 及对应的有2个db  管理所有环境，部署在国内阿里云

**Comment by nobodyiam** [comment]
@wxlevel 

> 每个cluster 有各自独立的configdb

这个怎么理解？apollo的cluster是逻辑划分，同一个环境的不同cluster，数据应该是在同一个db？
