### ISSUE TITLE
Docker-desktop k8s 部署失败

### ISSUE THREAD

**Issue by quzhixue-Kimi** [ctripcorp/apollo#3259]
hi there,

参考https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#241-%E5%9F%BA%E4%BA%8Ekubernetes%E5%8E%9F%E7%94%9F%E6%9C%8D%E5%8A%A1%E5%8F%91%E7%8E%B0
中的方式,
configdb是希望部署在k8s集群内的,按照2.4.1.3.4.3 ConfigDB的host是k8s集群内的一个服务
configdb:
  host: apollo-configdb
  dbName: ApolloConfigDB
  userName: apollo
  password: apollo
  connectionStringProperties: characterEncoding=utf8&useSSL=false
service:
    # whether to create a Service for this host or not
    enabled: false
    fullNameOverride: ""
    port: 3306
    type: ClusterIP

其他在values.yaml中的配置都没有改,但是看configservice和adminservice中的日志,都是报数据库链接不上!

2020-08-24 14:59:17.864  INFO 29 --- [ost-startStop-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2020-08-24 14:59:48.859 ERROR 29 --- [ost-startStop-1] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Exception during pool initialization.

com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

不知道哪位有自己已经配置好的,并且启动起来的,可以分享下么?

我也看了下apollo-service/templates/service-configdb.yaml文件,
{{- if .Values.configdb.service.enabled -}}
当我把 service.enabled=false的时候,这个configdb的service不就不会创建了么!
那么
deployment-???.yaml的apollo.configdb.serviceName理论上还能有值?
spring.datasource.url = jdbc:mysql://{{include "apollo.configdb.serviceName" .}}:{{ .Values.configdb.service.port }}/{{ .Values.configdb.dbName }}{{ if .Values.configdb.connectionStringProperties }}?{{ .Values.configdb.connectionStringProperties }}{{ end }}

Sorry for your inconvenience.
BR
Kimi

**Comment by quzhixue-Kimi** [comment]
哦
{{- define "apollo.configdb.serviceName" -}}
{{- if .Values.configdb.service.enabled -}}
{{- if .Values.configdb.service.fullNameOverride -}}
{{- .Values.configdb.service.fullNameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name .Values.configdb.name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- else -}}
{{- .Values.configdb.host -}}
{{- end -}}
{{- end -}}

如果enabled=false, 就是去拿host去作为服务名了!对吧

**Comment by nobodyiam** [comment]
@quzhixue-Kimi 是的
