### ISSUE TITLE
最新版本的apollo-configservice(1.7.1) 镜像启动报错

### ISSUE THREAD

**Issue by dai19470** [ctripcorp/apollo#3261]
`
2020-08-25 17:19:37.479  WARN 34 --- [main] c.n.d.s.t.d.RetryableEurekaHttpClient    : Request execution failed with message: java.net.ConnectException: Connection refused (Connection refused)
2020-08-25 17:19:37.480 ERROR 34 --- [main] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_APOLLO-CONFIGSERVICE/ad2d8bd215fd:apollo-configservice:8080 - was unable to refresh its cache! status = Cannot execute request on any known server

com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
	at
.....

 `
run command:
`
docker run -p 8080:8080 \
    -e SPRING_DATASOURCE_URL="jdbc:mysql://fill-in-the-correct-server:3306/ApolloConfigDB?characterEncoding=utf8" \
    -e SPRING_DATASOURCE_USERNAME=FillInCorrectUser -e SPRING_DATASOURCE_PASSWORD=FillInCorrectPassword \
    -d -v /tmp/logs:/opt/logs --name apollo-configservice apolloconfig/apollo-configservice:${version}
`
if need configuration eureka's address url?

**Comment by jiayaoO3O** [comment]
你的docker run命令有没有将对应的参数改对的?mysq的路径, 数据库用户名和密码

**Comment by dai19470** [comment]
@jiayaoO3O  其他的都是改成了自己配置的。确定无误，错误信息是注册到eureka的错误，我没有配置外部eureka.使用自带的。

**Comment by jiayaoO3O** [comment]
你在docker的容器里面是否确定可以访问这个地址?
![image](https://user-images.githubusercontent.com/22891632/91408318-420aa400-e876-11ea-8872-5f335af28630.png)

**Comment by dai19470** [comment]
下面是我的配置，启动的报错。错误信息为第一次发的那个。数据库eurkea为红框的，我没有改。下面是截图
![image](https://user-images.githubusercontent.com/21135250/91424831-e4ce1d00-e88c-11ea-9c8d-283baca483a7.png)
![image](https://user-images.githubusercontent.com/21135250/91424858-ebf52b00-e88c-11ea-80fe-3129f769e1b6.png)
![image](https://user-images.githubusercontent.com/21135250/91424900-fb747400-e88c-11ea-8ad4-c235ba0b949a.png)

**Comment by jiayaoO3O** [comment]
adminservice和configservice都需要将自身ip和端口注册到红框的eureka里面,你直接写localhost,configservice可以访问,adminservice是没法访问的,要写configservice正确的ip地址

**Comment by wnjustdoit** [comment]
用 docker 的话，最好全部显式指定注册中心的地址（不能用 localhost，不然指向 docker 内部网络环境了，除非你的 docker 网络模式是 host 模式）：
`
    -e EUREKA_INSTANCE_IP_ADDRESS=192.168.1.249 \
    -e SERVER_PORT=8072 \
`

**Comment by GeorgePony** [comment]
You should deploy a standalone Eureka and then change the database config:

Update ServerConfig set Value='Your Eureka Url ' where Key = 'eureka.service.url';

```````````````````````````````````````````````````````````````````````````````````````````````````````````````````
The docker-compose.yml I written:

version: "3.3"
services:
  apollo-config:
    image: apolloconfig/apollo-configservice
    container_name: apollo-config
    ports:
      - "28080:8080"
    environment:
      SPRING_DATASOURCE_URL: myurl
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
      - /home/zhou/workspace/docker/volume/apollo/config-log:/opt/logs
  apollo-portal:
    image: apolloconfig/apollo-portal:latest
    container_name: apollo-portal
    ports:
      - "28070:8070"
    environment:
      SPRING_DATASOURCE_URL: myurl
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      APOLLO_PORTAL_ENVS: dev 
      DEV_META: myurl
    depends_on:
      - apollo-admin
          
  apollo-admin:
    image: apolloconfig/apollo-adminservice
    container_name: apollo-admin
    ports:
      - "28090:8090"
    environment:
      SPRING_DATASOURCE_URL: myurl
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
      - /home/zhou/workspace/docker/volume/apollo/admin-log:/opt/logs   
    depends_on:
      - apollo-config
