### ISSUE TITLE
现在有办法在管理后台能直接查询到namespace的内容？

### ISSUE THREAD

**Issue by tsaimn** [ctripcorp/apollo#3263]
背景
公司有很多公共的阿波罗项目，各个业务线的代码里面引用阿波罗的namespace。但是时间一长，就没人知道这个namespace是属于哪个阿波罗项目下的了。
有几个问题
1.新人入职的时候不知道这个namespace里面具体有什么配置项，不方便
2.如果要修改配置项，却找不到namespace在哪个项目下面
3.管理后台智能根据项目找namespace

建议
管理后台能不能增加一个根据namespace名称查询

**Comment by nobodyiam** [comment]
possible duplicate of #1926 ?
