### ISSUE TITLE
apollo中 portal从前端到DB的网络请求链路是怎么样的？

### ISSUE THREAD

**Issue by wxlevel** [ctripcorp/apollo#3264]
## apollo中 portal从前端到DB的网络请求链路是怎么样的？
我们就是按照cluster来划分环境的，比如 cn-dev (部署在公司内网), cn-stage (阿里云), cn-pro(阿里云), hk-stage(阿里云), hk-pro(阿里云),us-stage(阿里云),us-pro(阿里云) 等等，
每个环境 有各自独立的configdb 。 然后 一个 portal (部署在阿里云)上管理所有的环境
现在存在一个问题，访问cn-dev 特别慢，VPN加了带宽，还是慢。（最主要是慢在加载 namespace）

所以，我想请问portal 去加载 namespace 的网络请求链路是怎么样的？
 portal前端 -> http请求 -> **configservice** -> tcp请求 -> configdb 中的 namespace
 portal前端 -> http请求 -> **portal后端** -> tcp请求 -> configdb 中的 namespace 

是哪一种方式？  或者是别的方式？

**Comment by nobodyiam** [comment]
少量元数据是从 portaldb 获取的，大部分业务数据是从 adminservice/configdb 获取的
portal前端 -> http请求 -> adminservice -> tcp请求 -> configdb 中的 namespace

**Comment by wxlevel** [comment]
> 少量元数据是从 portaldb 获取的，大部分业务数据是从 adminservice/configdb 获取的
> portal前端 -> http请求 -> adminservice -> tcp请求 -> configdb 中的 namespace

好的，非常感谢大佬的解惑

**Comment by xiakedong** [comment]
> 少量元数据是从 portaldb 获取的，大部分业务数据是从 adminservice/configdb 获取的 portal前端 -> http请求 -> adminservice -> tcp请求 -> configdb 中的 namespace

能中间加一个LDAP吗？ 多个namepace的情况下网络是怎样的  谢谢
