### ISSUE TITLE
如果使用官方Apollo的docker镜像,启动容器的时候是否应该指定使用host模式

### ISSUE THREAD

**Issue by jiayaoO3O** [ctripcorp/apollo#3267]
如果使用官方的

> docker run -p 8090:8090 \
>     -e SPRING_DATASOURCE_URL="jdbc:mysql://fill-in-the-correct-server:3306/ApolloConfigDB?characterEncoding=utf8" \
>     -e SPRING_DATASOURCE_USERNAME=FillInCorrectUser -e SPRING_DATASOURCE_PASSWORD=FillInCorrectPassword \
>     -d -v /tmp/logs:/opt/logs --name apollo-adminservice apolloconfig/apollo-adminservice:${version}

命令, 作为bridge模式启动的时候, configservice和adminservice向注册中心注册的都是自身所在的docker子网的IP, 例如172.17.0.4,但是当客户端通过meta service获取到这些子网ip, 并不能在外部直接访问; 如果启动的时候指定网络为host, 这样容器就可以和doker处于同一网段, 客户端才可以直接通过ip:port进行访问.
所以是否应该在官方文档中指定使用host?或者容器应该通过什么方式来暴露一个能够让外部访问的ip呢?

**Comment by JaredTan95** [comment]
可以参考：https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E6%96%B9%E6%A1%88%E4%B8%89%E5%BC%BA%E5%88%B6%E6%8C%87%E5%AE%9Aadmin-server%E5%92%8Cconfig-server%E5%90%91eureka%E6%B3%A8%E5%86%8C%E7%9A%84ip%E5%92%8Cport 方式跳过meta server。

> 注：如果Apollo部署在公有云上，本地开发环境无法连接，但又需要做开发测试的话，客户端可以升级到0.11.0版本及以上，然后通过-Dapollo.configService=http://config-service的公网IP:端口来跳过meta service的服务发现，记得要对公网 SLB 设置 IP 白名单，避免数据泄露.

**Comment by jiayaoO3O** [comment]
那如果使用-Dapollo.configService=http://config-service的公网IP:端口来跳过meta service的服务发现, 可以通过ip:port,ip:port方式填写多个ip地址来让客户端做负载均衡吗?还是只能写一个IP地址?

**Comment by wnjustdoit** [comment]
-D 的意思是需要进入容器内，改动startup.sh中启动java进程的命令？
我用的这个命令：
`
docker run -p 8090:8090 \
    -e SPRING_DATASOURCE_URL="jdbc:mysql://$my_ip:3306/ApolloConfigDB?characterEncoding=utf8" \
    -e SPRING_DATASOURCE_USERNAME=root -e SPRING_DATASOURCE_PASSWORD=$my_passwd \
    -e EUREKA_INSTANCE_IP_ADDRESS=$eureka_ip \
    -e SERVER_PORT=8090 \
    -d -v /tmp/apollologs:/opt/logs --name apollo-adminservice apolloconfig/apollo-adminservice:1.7.1
`

**Comment by jiayaoO3O** [comment]
@wnjustdoit -Dapollo.configService是给你的客户端启动的时候传进去的参数,容器是不用修改的

**Comment by wnjustdoit** [comment]
> @wnjustdoit -Dapollo.configService是给你的客户端启动的时候传进去的参数,容器是不用修改的

好的，了解

**Comment by nobodyiam** [comment]
@jiayaoO3O 可以用逗号分隔写多个

**Comment by jiayaoO3O** [comment]
@nobodyiam 这个-Dapollo.configService能够通过apollo.configService=x.x.x.x写在配置文件里面吗?

**Comment by nobodyiam** [comment]
可以写在server.properties

https://github.com/ctripcorp/apollo/blob/65feb41074b41c895e222be242a12e586e3dfe62/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/ConfigServiceLocator.java#L74-L83
