### ISSUE TITLE
在Windows上用Git Bash运行时得到的IP地址是虚拟地址，导致其他机器无法获取到配置

### ISSUE THREAD

**Issue by hezhiqiang** [ctripcorp/apollo#3268]
在Windows上用Git Bash运行时得到的IP地址是虚拟地址，导致其他机器无法获取到配置，这个问题该如何解决？

**Comment by nobodyiam** [comment]
参考下[1.4 网络策略](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#14-%E7%BD%91%E7%BB%9C%E7%AD%96%E7%95%A5)
