### ISSUE TITLE
关联的公共的namespace配置无法通过@Value 注解注入

### ISSUE THREAD

**Issue by qiao52672** [ctripcorp/apollo#3269]
apollo 1.6.0版本
使用spring boot 方式接入，本身namespace 的配置可以通过spring 注解 @Value 注入，但是关联的公共的namespace中配置注解无法获取，但是可以通过代码ConfigService.getConfig(somePublicNamespace) 的方式获取。

这种情况是我程序的问题还是apollo暂时还不支持公共的namespace通过注解 @Value的方式注入呢

**Comment by nobodyiam** [comment]
公共 namespace 也需要在程序中配置引入，可以参考下[3.2.1.3 Spring Boot集成方式](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#3213-spring-boot%E9%9B%86%E6%88%90%E6%96%B9%E5%BC%8F%E6%8E%A8%E8%8D%90)

**Comment by qiao52672** [comment]
> 公共 namespace 也需要在程序中配置引入，可以参考下[3.2.1.3 Spring Boot集成方式](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#3213-spring-boot%E9%9B%86%E6%88%90%E6%96%B9%E5%BC%8F%E6%8E%A8%E8%8D%90)


项目中bootstrap.yml配置如下：
app:
  id: demo-service
apollo:
  meta: http://192.168.1.112:8080/
  namespace: application,OO7.business-rules
  bootstrap:
    enabled: true
其中OO7.business-rules 为公共namespace， OO7 为部门ID，

@RestController
@Slf4j
public class IndexController {
    @Value("${demo.key}")
    private String key;

    @Value("${business.rules.ldbiz.minprofitrate:1}")
    private String key2;

    @RequestMapping(value = {"/","/index"})
    public ResponseEntity<String> index()  {

        log.info("key=[{}]", key);
        log.info("key2=[{}]", key2);
        log.info("key3=[{}]", ConfigService.getConfig("OO7.business-rules").getProperty("business.rules.ldbiz.minprofitrate", "1"));
        return ResponseEntity.ok("success");
    }

}

其中business.rules.ldbiz.minprofitrate 为关联的公共namespace中的key,打印结果如下;
10:13:11.962 [http-nio-9002-exec-2] INFO  demo.service.controller.IndexController - key=[service1]
10:13:11.962 [http-nio-9002-exec-2] INFO  demo.service.controller.IndexController - key2=[1]
10:13:11.971 [http-nio-9002-exec-2] INFO  demo.service.controller.IndexController - key3=[0.53]

使用@Value 的方式没有获取打值，但是使用API的方式获取到了

是否还有哪个地方需要额外配置

**Comment by qiao52672** [comment]
我配置错了namespaces 和bootstrap 同级了
