### ISSUE TITLE
真机多env部署 portal加载缓慢问题

### ISSUE THREAD

**Issue by go-zend** [ctripcorp/apollo#3270]
我这里有两台服务器A和B，AB机器同时部署了ConfgiServer和AdminServer
A机器作为Pro环境，同时部署PortalServer，B机器作为Dev环境，
进入Portal管理后台，加载B环境的配置时，加载缓慢，大概时间在10s以上。
已经尝试切换CD机器以及数据库，此问题依然存在。
客户端请求B环境配置时没有问题。
请问此问题该如何排查，如何解决？

**Comment by go-zend** [comment]
健康检查请参见[截图](http://122.51.59.5)

**Comment by nobodyiam** [comment]
看下10网段的机器是否能访问通？
