### ISSUE TITLE
portal 首页“我的项目” 数据不正确

### ISSUE THREAD

**Issue by bnubobby** [ctripcorp/apollo#3271]
首页调用
/apps/by-owner?owner=apollo&page=0&size=10
接口， 
当超过一页时，第一页和第二页的数据有重复，导致有部分项目，无法显示

appid    有横线 "-" 和 点   "."
当修改size 为 100的时候，接口返回的数据齐全

版本：   v1.5.2 ~  v1.7.1

**Comment by JaredTan95** [comment]
通过  http://106.54.227.205:8070/apps/by-owner?owner=apollo&page=0&size=100，并没有复现你的问题
