### ISSUE TITLE
部署的集群中，有个日志文件apollo-portal_usrlocalapolloapollo-portal.log特别大

### ISSUE THREAD

**Issue by wxlevel** [ctripcorp/apollo#3272]
部署的集群中，有个日志文件apollo-portal_usrlocalapolloapollo-portal.log特别大，目前已经32GB，
不知道这个文件是干什么的，可以直接删除吗？
 从名字来看是用户本地数据？ 为什么这个文件会这么大？

**Comment by nobodyiam** [comment]
这个应该是stdout的日志文件，可以删除

**Comment by wxlevel** [comment]
> 这个应该是stdout的日志文件，可以删除

 好的，感谢。建议这种文件按日期拆分。这么大的日志文件也没法查看，也不知道为什么会这么大。今天已经涨到37G了

**Comment by wxlevel** [comment]
> 这个应该是stdout的日志文件，可以删除

昨天删除了这个文件，今天又继续跟踪了这个文件，又接近2G了，然后进去看里面的日志信息。大部分是如下图所示的异常。
![image](https://user-images.githubusercontent.com/38063110/91786450-3df5d200-ec3a-11ea-987e-52334ac13f9e.png)

> Get admin server address from meta server failed.
> apollo.meta: Name or service not known.

这个是因为网络问题吗？还是配置问题？

**Comment by WsWHL** [comment]
好像是没有配置对应环境地址，一直检查导致的异常，我把serverConfig中支持的环境列表里没有使用的几个删掉重启就好了

还有中检查方式就是使用超级管理员登录到后台，选择管理工具里的系统信息，就能看到那些环境配置有问题了

**Comment by nobodyiam** [comment]
G2G-EU-UAT 这个环境没有配置 meta service 地址
