### ISSUE TITLE
Apollo 大量数据更新

### ISSUE THREAD

**Issue by renjiahua945** [ctripcorp/apollo#3273]
一个应用配置中心存了几千条数据，数据大小2m，每次更新都是全量。有两个问题，4C8G的config当接入客户端40台，网络请求的带宽就到瓶颈了，cpu占用100%，tp50 达到了3000ms，完全没办法用。还会304错误

**Comment by nobodyiam** [comment]
配置中心建议只存储应用配置，不要存储业务数据。如果希望通过配置中心来管理版本通知的话，可以把业务数据放在数据库中，在配置中心中管理版本，当版本信息更新后程序再从数据库拉取业务数据。

**Comment by jacky1193610322** [comment]
我认为apollo应该有一个增量推送，否则配置量的增加确实会有带宽压力

**Comment by fengqi** [comment]
可以尝试把key分散在多个namespace。

**Comment by jacky1193610322** [comment]
分散之后 就会加重配置管理，最好还是支持版本diff

**Comment by renjiahua945** [comment]
> 可以尝试把key分散在多个namespace。

分散之后意味着，我需要在代码里注入不同的Config。根据namespace

**Comment by fengqi** [comment]
@renjiahua945 是挺麻烦的，但是还不支持增量的情况下，可以先这样缓解下。。。

**Comment by jacky1193610322** [comment]
这个有计划优化吗？
