### ISSUE TITLE
急！！！apollo创建一个应用并设置公共的namespace权限问题

### ISSUE THREAD

**Issue by 1204709592** [ctripcorp/apollo#3274]
apollo创建一个应用并设置公共的namespace，这个时候所有用户进入这个应用都能查看这个公共的namespace配置。我有个需求是实现多层级配置不希望所有用户都能看到，同时也希望其他应用能关联到这个namespace，可以让用户登录进来之后，那个搜索框里只出现自已有权限访问的appid吗，如果可以，这样就能规避了

**Comment by nobodyiam** [comment]
公共配置在设计上允许应用覆盖，所以目前是对所有用户公开的
