### ISSUE TITLE
使用ApolloJsonValue 注解时,传入的参数是指namespace还是配置中的key?如果是key,如何指定namespace?

### ISSUE THREAD

**Issue by jiayaoO3O** [ctripcorp/apollo#3283]
使用ApolloJsonValue 时,如果参数是指key值,那这个注解如何知道是哪个namespace的key呢?哪里传入namespace
* ApolloJsonValue annotated on fields example, the default value is specified as empty list - []
* <br />
* jsonBeanProperty=[{"someString":"hello","someInt":100},{"someString":"world!","someInt":200}]

@ApolloJsonValue("${jsonBeanProperty:[]}")
private List<JsonBean> anotherJsonBeans;

**Comment by Deep2018530** [comment]
我理解是namespace在boot项目配置文件中指定或者注解上指定，同时同一个命名空间不允许有相同的key（添加的时候portal会报错），其次是不同namespace如果不小心有相同的key，那么会被覆盖（具体覆盖的逻辑不太清楚，你可以就你的问题做实验）。

为什么不同的namespace会有相同的key呢？namespace不就是为了区分不同意义的item组的嘛？（比如jdbc就维护jdbc、kafka就维护kafka）

个人理解有错见谅~

**Comment by nobodyiam** [comment]
@jiayaoO3O `@ApolloJsonValue` 和 `@Value` 是一样的用法
