### ISSUE TITLE
ConfigService在@SpringBootTest测试用例场景获取覆盖值的问题

### ISSUE THREAD

**Issue by yesnomore** [ctripcorp/apollo#3295]
假设有个命名空间common，里面有参数a=1

然后应用xxx继承并覆盖命名空间common的参数a=2

SpringBoot实现ImportBeanDefinitionRegistrar接口，在registerBeanDefinitions里利用ConfigService可以获取到 a=2;

但是在SpringBoot的@SpringBootTest测试用例场景下，只能获取到a=1

求指点！！！！

**Comment by nobodyiam** [comment]
看下应用名是否正确设置了，可以打开 DEBUG 日志看看
