### ISSUE TITLE
application 中 spring.datasource.xx配置文件同步更新的问题

### ISSUE THREAD

**Issue by bg1115009656** [ctripcorp/apollo#3296]
我配置了 this.applicationContext.publishEvent(new EnvironmentChangeEvent(changeEvent.changedKeys()));
更新了spring.datasource.url
但datasource仍然连接旧的数据库，是怎么回事呢?

**Comment by Deep2018530** [comment]
这种数据库连接级别的配置需要重启服务或者动态重建连接切换数据源的，单单修改数据库配置信息是没用的。https://github.com/ctripcorp/apollo-use-cases 应该是可以参考下这里的~

**Comment by bg1115009656** [comment]
我用refreshScope和ConfigurationProperties实现了这个功能，不知道这样实现是否有其他风险？上面例子中更改数据库配置的例子，我觉得修改成本太高了

**Comment by nobodyiam** [comment]
@bg1115009656 demo示例能实现平滑热更新，用refreshScope要测试一下
