### ISSUE TITLE
apollo用docker部署，保存配置项过多，会报下面这个错

### ISSUE THREAD

**Issue by 407390911** [ctripcorp/apollo#3297]
![image](https://user-images.githubusercontent.com/6091725/92545701-4629bf00-f283-11ea-9c12-ace91db1fab0.png)

**Comment by 407390911** [comment]
我是把apollo部署到华为云上的，跟带宽有关系吗？(我们用的套餐是流量计费)

**Comment by nobodyiam** [comment]
@407390911 是否走了slb？看看slb对http body的大小是否有限制
