### ISSUE TITLE
Enable compression for the following resources to reduce their transfer size by 14.1KiB (78% reduction).

### ISSUE THREAD

**Issue by AsuraLuo** [ctripcorp/apollo#3300]
<img width="1012" alt="Screen Shot 2020-09-11 at 12 01 18 PM" src="https://user-images.githubusercontent.com/15855779/92857329-161b2100-f427-11ea-9823-7c5216cd81f8.png">

What can i do for remove the graphql get url more space and line?

**Comment by nobodyiam** [comment]
I think you should post this issue to [apollographql](https://github.com/apollographql)?
