### ISSUE TITLE
apollo在同步json文件如存在两个及以上的版本差异时,同步不及时

### ISSUE THREAD

**Issue by yuncai929** [ctripcorp/apollo#3301]
如果JSON文件在长度不变的情况下修改2次,客户端如没网后在联上,此时不会及时同步服务器端最新的JSON文件

**Comment by nobodyiam** [comment]
apollo 的配置同步是基于版本的，不会受长度影响，描述一下详细的重现步骤吧，可以使用demo站点 http://106.54.227.205/

**Comment by yuncai929** [comment]
你好,我把客户端断网了,然后在管理端把对应的JSON文件修改并发布两次以上,注意(修改时JSON文件的总长度是不变的),此时客户端联网后,最新的JSON文件是不会主动更新的.管理端在更新第三次,客户端才会收到最新的JSON文件.不明白,可以电话沟通18606162808
&nbsp;

希望破灭的时候就是新的希望诞生的时间!


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jason Song"<notifications@github.com&gt;; 
发送时间: 2020年9月16日(星期三) 上午8:14
收件人: "ctripcorp/apollo"<apollo@noreply.github.com&gt;; 
抄送: "李云"<258689361@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ctripcorp/apollo] apollo在同步json文件如存在两个及以上的版本差异时,同步不及时 (#3301)





 
apollo 的配置同步是基于版本的，不会受长度影响，描述一下详细的重现步骤吧，可以使用demo站点 http://106.54.227.205/

**Comment by nobodyiam** [comment]
@yuncai929 
断网后恢复的更新和你修改几次没有关系的（断网恢复后你不用修改，在一段时间后也会主动更新的），你在客户端打开 DEBUG 日志就能看到具体的信息。
原理简而言之就是客户端是通过 long polling 来实现更新的，如果断网的话，long polling 会进入错误重试阶段，为了避免错误重试太频繁，所以重试时间会以 1 秒、2 秒、4 秒、8 秒这样的数列递增，最大会到 120 秒。
所以，断网恢复后，最长需要 120 秒才会感知到配置更新，并拉取最新配置。

**Comment by yuncai929** [comment]
我测试过properties,xml,json,yaml,yml这几个文件,断网后更新都是相当快的.只有JSON文件不会更新,这是我测试几次都是这样的结果.我发ajax请求去取后台的配置文件,就JSON文件断网后不更新
&nbsp;

希望破灭的时候就是新的希望诞生的时间!


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jason Song"<notifications@github.com&gt;; 
发送时间: 2020年9月16日(星期三) 上午8:30
收件人: "ctripcorp/apollo"<apollo@noreply.github.com&gt;; 
抄送: "李云"<258689361@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ctripcorp/apollo] apollo在同步json文件如存在两个及以上的版本差异时,同步不及时 (#3301)





 
@yuncai929
 断网后恢复的更新和你修改几次没有关系的（断网恢复后你不用修改，在一段时间后也会主动更新的），你在客户端打开 DEBUG 日志就能看到具体的信息。
 原理简而言之就是客户端是通过 long polling 来实现更新的，如果断网的话，long polling 会进入错误重试阶段，为了避免错误重试太频繁，所以重试时间会以 1 秒、2 秒、4 秒、8 秒这样的数列递增，最大会到 120 秒。
 所以，断网恢复后，最长需要 120 秒才会感知到配置更新，并拉取最新配置。
