### ISSUE TITLE
在apollo配置spring.main.allow-bean-definition-overriding属性不生效

### ISSUE THREAD

**Issue by Rgege** [ctripcorp/apollo#3302]
项目中用到feign，多个feignclient 使用同一servicename ,需要显示配置spring.main.allow-bean-definition-overriding=true, 奇怪的是，把这个配置到apollo里面总是不能起效，必须得放到项目本地properties中

**Comment by nobodyiam** [comment]
用[Spring Boot集成方式](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#3213-spring-boot%E9%9B%86%E6%88%90%E6%96%B9%E5%BC%8F%E6%8E%A8%E8%8D%90)试试

**Comment by Rgege** [comment]
> 用[Spring Boot集成方式](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#3213-spring-boot%E9%9B%86%E6%88%90%E6%96%B9%E5%BC%8F%E6%8E%A8%E8%8D%90)试试

感谢，问题解决了 ，之前也是参考的springboot 集成的方式，但是忽略了要求Apollo版本1.2.0+

**Comment by xchguo** [comment]
> > 用[Spring Boot集成方式](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#3213-spring-boot%E9%9B%86%E6%88%90%E6%96%B9%E5%BC%8F%E6%8E%A8%E8%8D%90)试试
> 
> 感谢，问题解决了 ，之前也是参考的springboot 集成的方式，但是忽略了要求Apollo版本1.2.0+

你好，请问你是如何解决的呢？我按照springboot集成方式配置后还是不生效。

**Comment by yl-zhang** [comment]
遇到了同样的问题 ，现在只能放在application.yml中才生效

**Comment by Rgege** [comment]
> > > 用[Spring Boot集成方式](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#3213-spring-boot%E9%9B%86%E6%88%90%E6%96%B9%E5%BC%8F%E6%8E%A8%E8%8D%90)试试
> > 
> > 
> > 感谢，问题解决了 ，之前也是参考的springboot 集成的方式，但是忽略了要求Apollo版本1.2.0+
> 
> 你好，请问你是如何解决的呢？我按照springboot集成方式配置后还是不生效。

>我这边主要是讲Apollo版本升级到1.2.0之后的版本 然后参考Spring Boot集成方式配置就可以了
