### ISSUE TITLE
项目配置复制(导入导出)功能

### ISSUE THREAD

**Issue by gougouzcm** [ctripcorp/apollo#3303]
比如现在有一个项目是 A,现在想要新建一个项目B,需要把A的配置同步一份过去,这个时候就要创建B项目,在把A的namespace 一个一个的拷贝过去,也没有发现批量创建namespace入口,会导致这个过程很耗时。

使用场景:
公司有一个工程的脚手架程序,每次公司需要新开一个项目的时候从这个项目copy一个出来。
每次生成的项目都要copy一遍 模板工程的 apollo配置,有没有其他的方式可以方便一些。

1.提供rest api对接。
2.界面上提供导出导入功能。
选择一个应用，点击导出,导出 当前项目的所有namespace及其配置。
新建应用,点击导入,ok，新建的 namespace的权限为默认就行了。

**Comment by nobodyiam** [comment]
1. apollo 提供了 [open api](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0)，可以自己集成一下
2. apollo portal 目前有 [import](https://github.com/ctripcorp/apollo/blob/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/ConfigsImportController.java#L39) / [export](https://github.com/ctripcorp/apollo/blob/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/ConfigsExportController.java#L60) 接口，可以基于这两个接口增加一个页面入口

**Comment by gougouzcm** [comment]
> 1. apollo 提供了 [open api](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0)，可以自己集成一下
> 2. apollo portal 目前有 [import](https://github.com/ctripcorp/apollo/blob/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/ConfigsImportController.java#L39) / [export](https://github.com/ctripcorp/apollo/blob/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/ConfigsExportController.java#L60) 接口，可以基于这两个接口增加一个页面入口


好的，感谢，还是希望apollo自身可以提供导入导出界面。

**Comment by lanxiaolin-sz** [comment]
@nobodyiam 请问一下
这个apollo-portal是第几版的有 import / export 接口
<dependency>
            <groupId>com.ctrip.framework.apollo</groupId>
            <artifactId>apollo-portal</artifactId>
            <version>1.6.0</version>
        </dependency>
