### ISSUE TITLE
第三方应用接入Apollo开放平台后通过Authorization访问openapi接口仍然需要登录

### ISSUE THREAD

**Issue by izhijian** [ctripcorp/apollo#3307]
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) of this repository and believe that this is not a duplicate.

**Describe the bug**
第三方应用接入Apollo开放平台后通过Authorization访问会导致openapi会导致springsecurity的permitAll失效.
就是说当使用springsecurity作为Apollo的认证时，设置了permitAll过滤掉openapi的路径不拦截登录，但是实际是如果请求头里面带了Authorization的话permitAll方法的配置就失效了，通过携带token访问openapi接口仍然会拦截登录，但换个请求头名称就没有问题，比如讲Authorization换成其他的名称。这应该是springsecurity的机制，就算配置了permitAll但只要请求头里面包含了Authorization的请求头仍然会拦截认证。

我们对接Apollo的统一认证是keycloak，然后通过keycloak的springsecurity adapter接入统一认证的。

调试了流程是：访问Openapi的接口是 如果请求头里面携带了Authorization就会先拦截登录，然后才是开放平台的ConsumerAuthenticationFilter 过滤器的拦截校验token。

在本地尝试修改了ConsumerAuthenticationFilter类中的请求头名称可以按预想的实现。

**To Reproduce**
1. 使用springsecurity认证，弄一个开放平台的token
2. 使用token访问openapi：http://localhost:8070/openapi/v1/apps/test/envclusters
3. 会提示要登录
4. 

**Expected behavior**
期望可以正常访问openapi不登录

**Screenshots**
![image](https://user-images.githubusercontent.com/18110266/93437922-25a2da00-f8ff-11ea-8f72-3c53206efd34.png)
![image](https://user-images.githubusercontent.com/18110266/93437969-36ebe680-f8ff-11ea-845a-dd380f264c81.png)

### Additional Details & Logs

- Version
- Error logs
- Configuration
- Platform and Operating System

**Comment by nobodyiam** [comment]
apollo默认的spring security认证没问题的，看下是否keycloak有特殊配置之类的

![image](https://user-images.githubusercontent.com/837658/93656617-16866e00-fa5e-11ea-9980-5a09f6b16820.png)

**Comment by izhijian** [comment]
> apollo默认的spring security认证没问题的，看下是否keycloak有特殊配置之类的
> 
> ![image](https://user-images.githubusercontent.com/837658/93656617-16866e00-fa5e-11ea-9980-5a09f6b16820.png)

谢谢已经解决了，需要修改代码，过滤器问题
