### ISSUE TITLE
希望默认MetaServerProvider能延迟初始化以避免出现不必要的误导日志

### ISSUE THREAD

**Issue by longbowape** [ctripcorp/apollo#3311]
目前apollo-client提供了LegacyMetaServerProvider和DefaultMetaServerProvider两个默认MetaServerProvider，在service load的时候就会分别试图设置meta server，用户自定义MetaServerProvider已经成功设置地址之后会立即出现两条失败日志，其实这两个默认provider的初始化是完全没必要执行的。

WARN com.ctrip.framework.apollo.internals.DefaultMetaServerProvider - Could not find meta server address, because it is not available in neither (1) JVM system property 'apollo.meta', (2) OS env variable 'APOLLO_META' (3) property 'apollo.meta' from server.properties nor (4) property 'apollo.meta' from app.properties
WARN com.ctrip.framework.apollo.core.utils.ResourceUtils - No available properties: apollo-env.properties

**Comment by nobodyiam** [comment]
”延迟初始化“能展开说明一下吗？

**Comment by longbowape** [comment]
> ”延迟初始化“能展开说明一下吗？

将构造函数里的initialize调用移到getMetaServerAddress，如果属性metaServerAddress没有初始化，再才调用一次initialize，这样避免在ServiceBootstrap.loadAll(MetaServerProvider.class)加载类的时候就执行初始化的操作，感觉应该是不会影响正常功能的。

**Comment by nobodyiam** [comment]
我尝试理解一下，是说在真正获取地址的时候再做initialize，这样如果排序在前的MetaServerProvider已经获得了地址，那么后续的MetaServerProvider也就不需要initialize了，自然也就不会打印warn日志了？

**Comment by longbowape** [comment]
嗯，是这个意思

**Comment by nobodyiam** [comment]
@longbowape 可以提交个 PR
