### ISSUE TITLE
贡献2个客户端，go和python

### ISSUE THREAD

**Issue by xhrg** [ctripcorp/apollo#3312]
https://github.com/xhrg-product/apollo-client-python

https://github.com/xhrg-product/apollo-client-golang

**Comment by nobodyiam** [comment]
非常感谢，已经更新至[Go、Python、NodeJS、PHP等客户端使用指南](https://github.com/ctripcorp/apollo/wiki/Go%E3%80%81Python%E3%80%81NodeJS%E3%80%81PHP%E7%AD%89%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)
