### ISSUE TITLE
项目apollo-client依赖下载不下来

### ISSUE THREAD

**Issue by liuwenya1234** [ctripcorp/apollo#3313]
将apollo项目git clone下来后，执行mvn install后，本地maven仓库已经有坐标及jar包，但是编写apollo demo的过程中引入apollo-client依赖时报错，依赖下载不下来，报错信息及maven本地仓库坐标依赖jar如截图
![2](https://user-images.githubusercontent.com/14358709/93782425-2324e500-fc5d-11ea-92a8-e4d40e3cb6d4.PNG)
![3](https://user-images.githubusercontent.com/14358709/93782431-24eea880-fc5d-11ea-99fc-d129d5521e86.PNG)
![4](https://user-images.githubusercontent.com/14358709/93782438-27510280-fc5d-11ea-928c-8b5420619d0a.PNG)

**Comment by nobodyiam** [comment]
`mvn clean compile -U` 再试试，如果不行的话，可以试试国内的maven镜像

**Comment by liuwenya1234** [comment]
什么意思，我看本地仓库已经有这个client jar包了啊，主工程的pom版本也没有问题啊
