### ISSUE TITLE
Redirecting to inconsonant protocol when it is running behind a reserve proxy.

### ISSUE THREAD

**Issue by Ayden-Franklin** [ctripcorp/apollo#3314]
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) of this repository and believe that this is not a duplicate.

**Describe the bug**
I deployed apollo services to running on the kubernetes cluseter that manages all the inbound traffic via `Istio`, who controls  routes rules to be applied to traffic entering the cluster. Apollo works very well after I signed into the apollo protal. As the session expired, the browser received the HTTP response with status 302 and the target location `http://apollo-portal.xxx.com` regardless of the protocol of  original request(https). I wonder why the location is an absolute URI insteand of a relative **PATH** such as `/signin`.

**Expected behavior**
Redirect to the concordant URI. In my opinion, we just need to set the relative path as location for a 302 response.

**Screenshots**
![image](https://user-images.githubusercontent.com/10723556/93958001-0fc26880-fd88-11ea-9cda-b52400f44011.png)

### Additional Details & Logs

- Version
1.6.1

**Comment by Macrame** [comment]
Another solution is exposing the basic URL to configurable items or environment variables.

**Comment by nobodyiam** [comment]
Would you please follow the configuration advice from [14.3. Enable HTTPS When Running behind a Proxy Server](https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto-enable-https) and try it out?

```yaml
env:
  SERVER_TOMCAT_REMOTEIP_REMOTE_IP_HEADER: X-FORWARDED-FOR
  SERVER_TOMCAT_REMOTEIP_PROTOCOL_HEADER: X-FORWARDED-PROTO
```

**Comment by Macrame** [comment]
Thanks for feedback. But it has to effect yet. I know there isn't any problem caused by Apollo in contrast my proxy is not mature. According to the actual described on [stackoverflow](https://stackoverflow.com/questions/63583238/is-there-a-way-to-prevent-envoy-from-adding-specific-headers) the solution provided by Istio looks a little complicated. Thus, I still hope Apollo to be better for that situation to  expose the basic URL to configurable items or environment variables. Obviously, this is my suggestion instead of a bug caused by Apollo.

**Comment by Macrame** [comment]
The first choice is using `EnvoyFilter`, which provides a mechanism to customize the Envoy configuration generated by Istio Pilot. I'd like to keep it simple therefore I don't want to customize that configuration. Another choice is using an [Alpha api](https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/) in `Development`.

**Comment by nobodyiam** [comment]
@Macrame 

Thanks for the detailed feedback, however the redirect logic is part of the spring security module, which provides the mechanism described in [14.3. Enable HTTPS When Running behind a Proxy Server](https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto-enable-https). I'll try to take a look whether it provides the capability to configure a relative redirect url or not.
