### ISSUE TITLE
K8S部署，configservice配置使用ingress转发，密钥校验失败

### ISSUE THREAD

**Issue by sheng-jie** [ctripcorp/apollo#3316]
基于1.7.0的HELM包，成功部署Apollo至K8S。为了方便测试，使用Ingress暴露configservice供本地测试。
比如：config-svc的ingress路径配置为：http://www.example.com/apollo/dev-config-svc。

因为现在加密是根据path和querystring进行加密的，client端会使用完整path:/apollo/dev-config-svc/path进行加密，而ingresss转发后，会截掉/apollo/dev-config-svc部分，service端接收到的path和client的path就不一致了，因此会导致密钥校验失败。

**Comment by sheng-jie** [comment]
今天突然想到，可以修改ingress配置，以保留路径，同时修改config-service的context-path，与ingress路径保持一致。
但测试依然报错：
```
{
    "timestamp": "2020-09-24T19:43:37.599+0800",
    "status": 401,
    "error": "Unauthorized",
    "message": "Unauthorized",
    "path": "/mutone/apollo-dev-configsvc/notifications/v2"
}
```

从返回的path来看，请求路径也正确转发到pod中了。

因此，再次陷入混沌。

**Comment by nobodyiam** [comment]
看了下 ClientAuthenticationFilter 的代码，获取 path 是通过 `request.getServletPath`，导致丢失了 context path。
@nisiyong 也帮忙看看这块获取 path 的逻辑是否需要调整？

https://github.com/ctripcorp/apollo/blob/4d49504203fb6ef3cbfc13f546e3b3ab7cf07355/apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/filter/ClientAuthenticationFilter.java#L66-L74

![image](https://user-images.githubusercontent.com/837658/94328161-b7d36e00-ffe2-11ea-8ab7-0690636815c0.png)

**Comment by nisiyong** [comment]
@nobodyiam 好的，我看下怎么优化

**Comment by sheng-jie** [comment]
感谢👍，也看了apollo的源码，当时也有怀疑getservletpath，但没有去验证。

这里也要同步考虑更新下apollo-service的helm模板，因为像这种情形，肯定是要修改configservice的context-path的，因此values模板应该考虑添加context-path参数，像健康检查路径（现在默认是/health）也要能根据context-path进行设置。

**Comment by nisiyong** [comment]
@sheng-jie 
我这边在ConfigService端，密钥签名时使用了客户端请求端完整路径，可以解决你的问题，已经提交PR。
至于你说的`/health`等路径，context-path设置后是没问题的，可能是外部调用这类接口的地方要配合修改下。

**Comment by sheng-jie** [comment]
> @sheng-jie
> 我这边在ConfigService端，密钥签名时使用了客户端请求端完整路径，可以解决你的问题，已经提交PR。
> 至于你说的`/health`等路径，context-path设置后是没问题的，可能是外部调用这类接口的地方要配合修改下。

@nisiyong 

![](https://user-images.githubusercontent.com/12607748/94400661-0d06af80-019c-11eb-9830-4dfa4f280a49.png)

我说的是这里，chart模板中的就绪探针现在是固定的`/health`，如果指定了context-path，这里的就绪探针就要同步更新，类似这样：`path:  {{ .Values.configService.contextPath}}/health`。否则pod将无法正常启动。
