### ISSUE TITLE
高风险BUG：第三方应用接入token存在权限放大的问题，可读取未绑定的namespace配置

### ISSUE THREAD

**Issue by izhijian** [ctripcorp/apollo#3317]
问题描述：
第三方应用接入存在权限放大的问题，使用任意token可读取未绑定的其他项目的namespace配置。

环境：
github 官方v1.7.1版本，项目拉取下来未做任何修改，纯净版

复现步骤：
1、在同一个部门下创建两个不同的项目test、test2
![image](https://user-images.githubusercontent.com/18110266/94223150-ca39a300-ff21-11ea-8252-f9dc528fa3fe.png)
2、创建一个第三方应用，生成token，并绑定项目test的application.yml
![image](https://user-images.githubusercontent.com/18110266/94223234-01a84f80-ff22-11ea-82b2-bd5f51e1bddd.png)
3、通过openapi携带该token访问test2项目的namespace
![image](https://user-images.githubusercontent.com/18110266/94223363-53e97080-ff22-11ea-96bf-7b49cb4b1530.png)

如上图，发现能读取配置.
查看数据库发现应用的权限如下：
![image](https://user-images.githubusercontent.com/18110266/94232723-3542a400-ff39-11ea-9021-76f21eff00e6.png)

![image](https://user-images.githubusercontent.com/18110266/94223477-a591fb00-ff22-11ea-8bcc-9496452a166c.png)

期待：不能访问读取test2项目的配置
实际：能访问test2项目的配置，不合理，存在极大安全问题

**Comment by izhijian** [comment]
在演示环境http://106.54.227.205/也发现同样存在问题.
创建了第三方应用名称：test22
token：d3105852eb70c9f352560f7497a4874186d3f610
绑定了：appid=1456465
访问appid=test11的项目如下图：
![image](https://user-images.githubusercontent.com/18110266/94232506-bb121f80-ff38-11ea-9a1c-52073e5c480d.png)

**Comment by Deep2018530** [comment]
其实我们也发现过。。这个Portal界面生成token貌似是走个形式，源码里的过滤器貌似只是走库校验下存不存在就放行了。 我们用的1.1.1版本，以为是版本问题后面会修复。

**Comment by nobodyiam** [comment]
1. 目前只对 openapi token 的写操作做了权限控制，这部分权限控制是精细化到 namespace 粒度的
2. 对 openapi token 的读操作考虑到 openapi 有限的使用场景以及受控的使用环境，所以没有做限制，如果需求确实有价值的话，可以参考 #1531 实现一下对 openapi 的读权限控制
