### ISSUE TITLE
这个如何通过域名或者负载来访问我们的apollo配置

### ISSUE THREAD

**Issue by 18338739892** [ctripcorp/apollo#3319]
现在是新增加一台服务器,就要配置一对服务器ip白名单,很是麻烦,如何通过域名或者负载来访问的配置信息呢？谢谢

**Comment by nisiyong** [comment]
能否将问题详细描述下？是什么服务增加服务器等。

另外请先自信看下文档[Apollo配置中心设计](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1)及[分布式部署指南](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97)

如果是业务系统服务器访问需要白名单的话，是否可以考虑Apollo的密钥功能。[配置访问秘钥](https://github.com/ctripcorp/apollo/wiki/Apollo%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#62-%E9%85%8D%E7%BD%AE%E8%AE%BF%E9%97%AE%E7%A7%98%E9%92%A5)
