### ISSUE TITLE
设计OpenAPI的意义在于？

### ISSUE THREAD

**Issue by ChenAiYang** [ctripcorp/apollo#3322]
**可以解答下OpenAPI存在的意义吗？.**
个人理解起来，Portal中对配置修改、发布是个收敛操作入口的过程，而使用OpenAPI后，无异于开了个口子去破坏这种收敛性。并且OpenAPI在发布时，会发布某个命名空间所有的配置，这就可能会发布一些不希望当时被发布的配置，除非通过一些现有的手段来检测出来本次发布之前已经有哪些已经变动过然后做个提醒，可是如果这么做了，这和Portal的功能不就重叠了吗？
基于此，有点不太明白OpenAPI究竟是想解决什么场景下的问题，望解答，谢谢~

**Comment by nobodyiam** [comment]
主要是那些对配置有更多管控需求的场景
![image](https://user-images.githubusercontent.com/837658/94896146-61bd6980-04bf-11eb-85ee-96ceb37c0bd1.png)

**Comment by ChenAiYang** [comment]
> 主要是那些对配置有更多管控需求的场景
> ![image](https://user-images.githubusercontent.com/837658/94896146-61bd6980-04bf-11eb-85ee-96ceb37c0bd1.png)

可以举个例子吗？或者我能否这么理解：业务方通过OpenAPI实现一套定制化的Portal？
很抱歉您的回复中图片不可见

**Comment by nobodyiam** [comment]
@ChenAiYang 可以开启[namespace.lock.switch](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#2-namespacelockswitch---%E4%B8%80%E6%AC%A1%E5%8F%91%E5%B8%83%E5%8F%AA%E8%83%BD%E6%9C%89%E4%B8%80%E4%B8%AA%E4%BA%BA%E4%BF%AE%E6%94%B9%E5%BC%80%E5%85%B3%E7%94%A8%E4%BA%8E%E5%8F%91%E5%B8%83%E5%AE%A1%E6%A0%B8)

**Comment by ChenAiYang** [comment]
收到，谢谢~
另，对于OpenAPI，我能否如此理解：使用OpenAPI加业务方自己画UI，可以实现一套业务方定制化的Portal（实现数据校验）

**Comment by nobodyiam** [comment]
@ChenAiYang 基本上是可以的

**Comment by ChenAiYang** [comment]
> @ChenAiYang 基本上是可以的

收到，谢谢解答~
