### ISSUE TITLE
dev的关联配置拉不下来

### ISSUE THREAD

**Issue by stevencxb** [ctripcorp/apollo#3323]
创建了一个公共Namespace，在其他项目里面，dev一直拉不到配置，但是自己的私有配置就能拉下来，其他环境就是好的，请问下这大概是哪些原因造成的

**Comment by nobodyiam** [comment]
看下配置是否在 dev 环境发布了

**Comment by stevencxb** [comment]
发布了的，还是不行呢，

**Comment by nobodyiam** [comment]
dev环境是否是后增加的环境？如果是的话，参考下[从别的环境导入ApolloConfigDB的项目数据](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#2121-%E4%BB%8E%E5%88%AB%E7%9A%84%E7%8E%AF%E5%A2%83%E5%AF%BC%E5%85%A5apolloconfigdb%E7%9A%84%E9%A1%B9%E7%9B%AE%E6%95%B0%E6%8D%AE)，是否数据都补全了
