### ISSUE TITLE
为什么portalDB跟configDB都要保存App跟AppNameSpace信息呢？

### ISSUE THREAD

**Issue by daimingzhi** [ctripcorp/apollo#3327]
阅读源码发现portalDB跟configDB都保存了App跟AppNameSpace信息，并且表结构是一样的
但是并没有做数据一致性保证

不清楚为什么这么设计？App及AppNameSpace只保存在portalDB中有什么问题吗？

**Comment by nobodyiam** [comment]
数据一致性保证是通过页面上的补缺环境来实现的。

config service/admin service和config db是按环境部署的，无法连接portaldb
