### ISSUE TITLE
apollo-configservice-1.7.1单机部署报错longer than 15 characters, please use --exec instead of --name

### ISSUE THREAD

**Issue by zhangyj131** [ctripcorp/apollo#3328]
安装文档安装虚机单机的apollo，启动apollo-configservice-1.7.1时候apollo-configservice_mydataapollo-1.7.1apollo-configservice-1.7.1-github.log文件报错
start-stop-daemon: warning: this system is not able to track process names
longer than 15 characters, please use --exec instead of --name.
start-stop-daemon: user '197108' not found
使用系统是ubuntu1604，看了下启动脚本apollo-configservice-1.7.1-github/scripts/startup.sh，里面jar启动不是java -jar xx.jar方式启动，而是xx.jar start方式启动，不清除为什么报错这个错误？请指导下，现在无法部署，谢谢

**Comment by nobodyiam** [comment]
这个[看上去](https://stackoverflow.com/questions/51217606/how-can-i-fix-start-stop-daemon-warning-this-system-is-not-able-to-track-pro)是spring boot的一个兼容性问题，建议使用centos吧
