### ISSUE TITLE
为什么同时需要DefaultConfigPropertySourcesProcessorHelper跟DefaultApolloConfigRegistrarHelper

### ISSUE THREAD

**Issue by daimingzhi** [ctripcorp/apollo#3330]
在看客户端整合Apollo的源码的时候发现，当使用XML配置或者SpringBoot的方式进行整合时，是依赖DefaultConfigPropertySourcesProcessorHelper来向容器中注册一些bean工厂后置处理器跟bean后置处理器

但是在使用@EnableApolloConfig的方式进行整合时是通过DefaultApolloConfigRegistrarHelper来注册

这二者在功能上并没有什么区别，这种设计是为了版本兼容吗？还是有其它考虑呢？

**Comment by nobodyiam** [comment]
只是xml的入口和注解的入口有一点小的逻辑区别，没有太大的差别
