### ISSUE TITLE
OpenAPI 修改配置接口参数包含中括号报400错误

### ISSUE THREAD

**Issue by JianleiZhang** [ctripcorp/apollo#3335]
接口文档地址如下：
https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0#3211-%E4%BF%AE%E6%94%B9%E9%85%8D%E7%BD%AE%E6%8E%A5%E5%8F%A3

提交的参数为：test[0]

错误为：400，且无返回任何信息。

**Comment by JianleiZhang** [comment]
test(0)
test{1}
"test[0]"
这几种形式都可以提交。我怀疑是不是中括号被当初数组处理了？

**Comment by nobodyiam** [comment]
http 规范，url 参数需要做 encode，`test[0]` => `test%5B0%5D`

**Comment by JianleiZhang** [comment]
确实，是自己粗心了。
