### ISSUE TITLE
Question:it contains el expression in the value of properties, how i can declear the value as string? otherwise, the el will be parse.

### ISSUE THREAD

**Issue by zender-projects** [ctripcorp/apollo#3343]
- [ ] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) of this repository and believe that this is not a duplicate.

**Describe the bug**
Question:it contains el expression in the value of properties, how i can declear the value as string? otherwise, the el will be parse.
**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

### Additional Details & Logs

- Version
- Error logs
- Configuration
- Platform and Operating System

**Comment by zender-projects** [comment]
### 【异常告警】#{ruleName}\n告警级别：P1\n当前状态：noticed\n影响范围：#{scope}\n资源名称：#{name}\n开始时间：#{startTimeStr}\n持续时长：#{duration}\n告警详情：[#{alarmMessage}](#{swUrl})

@Value("${alarm.sw.notice.template}")
private String noticeTemplate

项目启动的时候会自动解析#{ruleName}，导致项目启动失败

**Comment by nobodyiam** [comment]
这个是 Spring 自动解析的，不是 apollo 的行为，建议换一个标识符吧，或者查一下 Spring 是否有相关的配置
