### ISSUE TITLE
重命名默认集群的名字

### ISSUE THREAD

**Issue by hulucc** [ctripcorp/apollo#3346]
我们这里有些环境对于默认集群是有特殊的名字的。哪怕是 display name 也可以。否则还需要和别人交代关联关系。
如果放弃使用默认集群的话，又浪费一个占位，同步配置的时候每次都要去掉所有环境的默认集群，并不是特别科学。
似乎也没有找到办法给用户隐藏某些集群的方法。
或者有什么更好的建议吗？

**Comment by nobodyiam** [comment]
这个比较自定义化了，应该可以通过修改前端的代码（比如做一个映射关系）来实现
