### ISSUE TITLE
idc跨网络后meta给出idc节点中的内网地址，导致外网apollo-portal无法请求内网的apollo-adminservice

### ISSUE THREAD

**Issue by xiangys0134** [ctripcorp/apollo#3351]
环境：分布式部署apollo，其中阿里云部署apollo-portal，公司内网部署一套apollo-configservice、apollo-adminservice 端口分别为55548、55549。
问题：apollo-portal日志显示在连接meta service后获取到内网ip(返回的apollo-adminservice内网ip加端口)，导致timeout超时，有遇到和我一样的问题吗？

2020-10-26 17:35:09.466 ERROR 20082 --- [Apollo-EnvHealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env health check failed, maybe because of meta server down or configure wrong meta server address. env: DEV, meta server address: http://mon.xuncetech.com:55548

com.ctrip.framework.apollo.common.exception.ServiceException: Admin servers are unresponsive. meta server address: http://mon.xuncetech.com:55548, admin servers: [ServiceDTO{appName='APOLLO-ADMINSERVICE', instanceId='apollo-configservice:apollo-adminservice:55549', homepageUrl='http://192.168.10.180:55549/'}]

**Comment by nisiyong** [comment]
可以在apollo-portal所在服务器，执行
```
telnet mon.xuncetech.com 55548
```
检查网络是否可达。如果不通，可能需要你们运维帮忙设置下网络策略

**Comment by xiangys0134** [comment]
网络可通，问题是apollo-portal部署在阿里云上，连接的meta server在公司内网(存在NAT网络)。我的理解是通过日志来看是meta server(公司内网)会告诉apollo-portal(阿里云)服务，apollo-admin(公司内网)地址(一个私网地址192.168.10.180:55549)，然后阿里云apollo-portal访问apollo-admin就报网络错误了。我看官方的分布式方案和我自己的理解就是这样的，也不知道我理解的对不对

**Comment by nisiyong** [comment]
@xiangys0134 是的，meta server（即configservice）承担服务注册与发现的功能，apollo-portal通过meta-server获取adminservice地址，然后去访问adminservice，所以你得保证portal能否访问每个环境的configservice和adminservice。

**Comment by xiangys0134** [comment]
apollo-admin有两个地址，一个是我做的端口映射的地址，在外网可以正常访问，一个是私网地址192.168.10.180:55549。通过meta-server获取的admin-service地址却是一个私网地址192.168.10.180:55549。admin-portal去连接的时候是连接的私网地址192.168.10.180:55549，然后就抛出上面的错误了。对于idc和公有云的SNAT模式下apollo分布式的部署好像就存在这种现象

**Comment by nisiyong** [comment]
apollo建议都部署在内网，特别是adminservice更加不能部署到外网，新版支持了token方式，但是还是不建议部署在外网。

你可以portal也部署在内网，保证和adminservice互通，然后加层外网的LB指向内部的portal。之前我们这边的运维同学也用过阿里云部署Apollo，只需要Portal加个对外的LB即可，最好能加上一些ip白名单。

**Comment by xiangys0134** [comment]
你的建议太好了，如果用这种方式部署的话我相信会没有问题的，谢谢

**Comment by nisiyong** [comment]
@xiangys0134 嗯，问题应该不大。等你验证没问题了，可以主动close issue

**Comment by xiangys0134** [comment]
已解决，参考https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97

**Comment by xiangys0134** [comment]
另外一种方式是直接指定要注册的IP，可以修改startup.sh，通过JVM System Property在运行时传入，如-Deureka.instance.ip-address=${指定的IP}，也可以通过OS Environment Variable，如EUREKA_INSTANCE_IP_ADDRESS=${指定的IP}，或者也可以修改apollo-adminservice或apollo-configservice 的bootstrap.yml文件，加入以下配置 将ip地址指定成固定外网ip后进行分布式搭建
