### ISSUE TITLE
startup.sh 定义的环境变量未被使用，之前是在 JAVA_OPTS 后面的是正常使用的，现在不能用了

### ISSUE THREAD

**Issue by xzxiaoshan** [ctripcorp/apollo#3352]
在 apollo/apollo-adminservice/src/main/scripts/startup.sh 中，提取了 SPRING_DATASOURCE_URL、SPRING_DATASOURCE_USERNAME 和 SPRING_DATASOURCE_PASSWORD ，但是后续没有加入到 JAVA_OPTS 中。

**Comment by nisiyong** [comment]
@xzxiaoshan 最好能够提供下哪个版本可用，哪个版本不可用

**Comment by nobodyiam** [comment]
@xzxiaoshan Spring 会读取 ENV 的，不需要加到 JAVA_OPTS 中
