### ISSUE TITLE
删除namespace很慢

### ISSUE THREAD

**Issue by ywf4026** [ctripcorp/apollo#3353]
由于删除namespace需要更新Commit,Release表的isDeleted字段为1，在表数据量比较大的时候，下面的update sql就很慢了：

mysql慢sql日志：
![image](https://user-images.githubusercontent.com/3722641/97248652-31a68380-183d-11eb-8b21-27649efd9395.png)

按where条件查询的explain，索引走的是namespaceName
![image](https://user-images.githubusercontent.com/3722641/97248787-79c5a600-183d-11eb-83bc-4895205df52d.png)

目前来看也没什么好的优化方式，是不是只能分页更新了，求赐教！！

**Comment by nobodyiam** [comment]
删除namespace应该是偶发的操作吧，如果很频繁的话，要考虑下分批了，比如分页查出记录，再按照id去操作
