### ISSUE TITLE
portal登录页面输入登录报400

### ISSUE THREAD

**Issue by zhangfan100** [ctripcorp/apollo#3365]
{"exception":"org.springframework.web.HttpRequestMethodNotSupportedException","message":"Request method \u0027POST\u0027 not supported","status":400,"timestamp":"2020-11-04T15:31:32.401"}

apollo 用的1.1.0版本 源码构建 源码没改啥 就用的自己的配置中心

**Comment by nobodyiam** [comment]
描述下详细步骤吧

**Comment by zhangfan100** [comment]
我下载的是1.1.0源码 本地构建，
1、configservice模块的com.ctrip.framework.apollo.configservice.ConfigServiceApplication类上@EnableEurekaServer改成@EnableEurekaClient
2、ApolloConfigDB_dev数据库表ServerConfig的eureka.service.url改成自己的配置中心eureka
3、安照官网步骤，修改模块的数据库连接信息
4、启动各个模块，日志也都没有问题
5、访问http://172.31.205.18:8190/signin  出现正常的登录界面，输入apollo/admin  登录进去后，返回的页面出现
{"exception":"org.springframework.web.HttpRequestMethodNotSupportedException","message":"Request method \u0027POST\u0027 not supported","status":400,"timestamp":"2020-11-05T09:32:14.982"}
6、同时看到登录的接口报400，请求的url =http://172.31.205.18:8190/signin  POST方式，参数 username=apollo&password=admin&login-submit=登录，接口返回值就是{"exception":"org.springframework.web.HttpRequestMethodNotSupportedException","message":"Request method \u0027POST\u0027 not supported","status":400,"timestamp":"2020-11-05T09:32:14.982"}
7、查看portal后端接口 确实没有post的signin接口，
8、但是我界面直接输入url=http://172.31.205.18:8190/  就到了正常的登录后的主界面，可以看到我的项目等也可以配置了。

请大佬分析分析啥原因哇

**Comment by zhangfan100** [comment]
我加入群里，申请还没通过，可否拉我进去下 谢谢 。QQ 279929067

**Comment by nobodyiam** [comment]
清一下浏览器缓存，或者下载最新的版本试试吧，之前没有用户反馈过这类问题
