### ISSUE TITLE
请问k8s部署模式下多应用（微服务）共享多集群方案如何配置？

### ISSUE THREAD

**Issue by chorylee001** [ctripcorp/apollo#3368]
ABCD微服务独立部署运行模块新建项目后仅可添加单个服务运行的集群和namespace及关联公共namespace，在PRO或者DEV环境中会存在多集群部署。请问如何统一配置默认集群，新建项目后各个环境均拥有集群列表呢？

**Comment by nobodyiam** [comment]
可以通过 open api 来[创建集群](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0#324-%E5%88%9B%E5%BB%BA%E9%9B%86%E7%BE%A4%E6%8E%A5%E5%8F%A3)

**Comment by chorylee001** [comment]
> 可以通过 open api 来[创建集群](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0#324-%E5%88%9B%E5%BB%BA%E9%9B%86%E7%BE%A4%E6%8E%A5%E5%8F%A3)

我的意思是集群配置是公共的，而不是要在每个新建应用（项目）的同时，都需要新建一套集群配置

**Comment by nobodyiam** [comment]
每个集群有一套公共配置？如果是这样的话，为公共namespace创建多个集群就可以了
