### ISSUE TITLE
Any method or api for adding key/value

### ISSUE THREAD

**Issue by zhujiancc** [ctripcorp/apollo#3371]
I want to add my key/value in my pragram not just add it in apollo setting page.
I couldn't find any doc for that. 
I don't know apollo whether suport it.
Please help me.

**Comment by zhujiancc** [comment]
find it in the soucecode

**Comment by zhujiancc** [comment]
there is a quetions about token:
![image](https://user-images.githubusercontent.com/19665595/98504154-32a1d100-2291-11eb-9100-23b86a048a7a.png)

cant it support "*" for token or some bulk operator

**Comment by nobodyiam** [comment]
> cant it support "*" for token or some bulk operator

Not for now, I'm not sure whether it's a good practice to do so...

**Comment by zhujiancc** [comment]
@nobodyiam  
I build a encrypt project for dealing with sensitive data. 
The service will create rsa cert for app,  and provide encrypt/decrypt,  just like below
![image](https://user-images.githubusercontent.com/19665595/101437292-cfb46000-394a-11eb-9726-cffeaa04351e.png)

I think it is too trouble for me to create a key in applo , and then encrypt in the secure service. 
So it is better to create key/value in this service. 
However expose a high permission is not good practice, but I think it is necessary when user want to extend apollo
