### ISSUE TITLE
AutoUpdateConfigChangeListener提示apollo成功自动更新配置，但是日志打印的依然是更新前的值，本地缓存文件里却已经修改为最新的值了

### ISSUE THREAD

**Issue by BlackRen09** [ctripcorp/apollo#3372]
AutoUpdateConfigChangeListener提示apollo成功自动更新配置，但是日志打印的依然是更新前的值，本地缓存文件里却已经修改为最新的值了，apollo版本为最新的1.7.0，springboot为2.2.4.RELEASE

**Comment by BlackRen09** [comment]
问题出现原因和 https://github.com/ctripcorp/apollo/issues/3242 一样

**Comment by yuanshuwei** [comment]
遇到同样的问题，请问您解决了吗
