### ISSUE TITLE
apollo会改变那些带有@Configuration配置类的顺序

### ISSUE THREAD

**Issue by roneywei** [ctripcorp/apollo#3373]
目前项目中使用了多数据源，之前配置中心使用的是spring-cloud，后面迁移至apollo。系统使用双数据源，使用spring-cloud的时候，数据源加载是按照A-B执行，换成apollo后，顺序变成B配置类先执行。请问下，apollo会改变那些带有@Configuration配置类的顺序？

**Comment by nobodyiam** [comment]
apollo 只是往 spring 中增加 PropertySource，不会改变`@Configuration`配置类的顺序

**Comment by roneywei** [comment]
多谢
