### ISSUE TITLE
百度云下载的apollo-quick-start-1.7.1部署linux报错

### ISSUE THREAD

**Issue by zhanglinlu** [ctripcorp/apollo#3378]
完全按照快速启动来搞的

linux上启动后：访问8070没问题但是进入配置
![image](https://user-images.githubusercontent.com/42115098/99137120-72870080-2663-11eb-8f9e-b5487786485e.png)
系统信息线就是这个
![image](https://user-images.githubusercontent.com/42115098/99137126-803c8600-2663-11eb-82ce-1cfd5b981986.png)
访问ip:8080访问不了
windows上完全没问题

**Comment by nobodyiam** [comment]
8080 进程没起来吧，看下 service 下的日志

**Comment by zhanglinlu** [comment]
这是apollo-service.log里面的
![image](https://user-images.githubusercontent.com/42115098/99140880-7e34f000-2680-11eb-95e9-766553aa78f7.png)
这是apollo-service_usrlocalapollo1.6.1service.log
![image](https://user-images.githubusercontent.com/42115098/99140929-e97ec200-2680-11eb-915b-c963abc603e1.png)
![image](https://user-images.githubusercontent.com/42115098/99140954-20ed6e80-2681-11eb-9f6e-30581f98e4fa.png)
![image](https://user-images.githubusercontent.com/42115098/99140915-c18f5e80-2680-11eb-90c4-c73b195eefc8.png)
![image](https://user-images.githubusercontent.com/42115098/99141067-141d4a80-2682-11eb-9876-512413b549ae.png)

**Comment by nobodyiam** [comment]
@zhanglinlu 可以看看 8080 进程是否还在，是否内存不足 kill 掉了

**Comment by zhanglinlu** [comment]
启动完成就没了，启动过程中还可以访问，多谢解答，可能就是内存不足的问题
