### ISSUE TITLE
既不Quick，也不Start

### ISSUE THREAD

**Issue by Brent-B-Welch** [ctripcorp/apollo#3379]
已经在demo.sh配置了jdbc url：
apollo_config_db_url=jdbc:mysql://localhost:3306/apolloconfigdb?characterEncoding=utf8&serverTimezone=UTC&useSSL=false
apollo_portal_db_url=jdbc:mysql://localhost:3306/apolloportaldb?characterEncoding=utf8&serverTimezone=UTC&useSSL=false
但是，始终报错：
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine suitable jdbc url

Action:

Consider the following:
        If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
        If you have database settings to be loaded from a particular profile you may need to activate it (the profiles github are currently active).

还遗漏了神马？

**Comment by Brent-B-Welch** [comment]
作者如果能提供debug功能，方便逐步跟踪问题，可能会少浪费您的support时间。现在，就像个黑洞，根本不知道是哪里出了问题

**Comment by nisiyong** [comment]
@Brent-B-Welch 如果要使用的话，我个人还是建议不用demo项目。如果想预览功能可以看主页README.md地址上的链接

**Comment by nobodyiam** [comment]
@Brent-B-Welch 

描述下你的使用步骤？操作系统环境？
从整体 support 情况看，quick start 按照文档来出问题的 case 基本没遇到过

**Comment by banzhiguo** [comment]
我也是同样的问题，url中只留下serverTimezone=UTC重启则可以，亲测可用

**Comment by nobodyiam** [comment]
@banzhiguo mysql 的版本是什么？

**Comment by nobodyiam** [comment]
url 中手动添加参数的话，注意要加双引号
```bash
apollo_config_db_url="jdbc:mysql://localhost:3306/ApolloConfigDB?characterEncoding=utf8&serverTimezone=Asia/Shanghai"
```

**Comment by banzhiguo** [comment]
那您在quick start的配置里就加上引号吧，此处不少人踩坑了



---原始邮件---
发件人: "Jason Song"<notifications@github.com&gt;
发送时间: 2021年1月3日(周日) 中午1:18
收件人: "ctripcorp/apollo"<apollo@noreply.github.com&gt;;
抄送: "banzhiguo"<516544181@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [ctripcorp/apollo] 既不Quick，也不Start (#3379)




 
url 中手动添加参数的话，注意要加双引号
 apollo_config_db_url="jdbc:mysql://localhost:3306/ApolloConfigDB?characterEncoding=utf8&amp;serverTimezone=Asia/Shanghai"

**Comment by nobodyiam** [comment]
已经在最新版本中默认加上引号，https://github.com/nobodyiam/apollo-build-scripts/commit/ee916e234a5d6c90a8a37cd4e186b93a7ac63cd6
