### ISSUE TITLE
Guice 与 Apollo 集成，如何实现自动刷新

### ISSUE THREAD

**Issue by coalchan** [ctripcorp/apollo#3381]
对于普通Java项目，不希望集成 Spring Boot 而仅仅引用 Guice ，这时使用 Apollo 也希望具有自动刷新配置的功能，各位大佬有何建议吗？

**Comment by nisiyong** [comment]
用Apollo的原生API即可，看文档[Java客户端使用指南](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#312-%E7%9B%91%E5%90%AC%E9%85%8D%E7%BD%AE%E5%8F%98%E5%8C%96%E4%BA%8B%E4%BB%B6)
