### ISSUE TITLE
除了直接改数据库，有删除用户的地方么？

### ISSUE THREAD

**Issue by dmanbu** [ctripcorp/apollo#3383]
如题

**Comment by nisiyong** [comment]
如果对用户管理有要求对话，建议内部使用LDAP或SSO方案。Apollo有对接文档

**Comment by nobodyiam** [comment]
可行的 workaround 方式有：
1. 在数据库中更新该 User 记录的 Enabled 值为 0
2. 在页面上修改该用户的密码

**Comment by nisiyong** [comment]
> 如果配置LDAP认证后，管理员账号和密码是哪个？

You could set some people as administrators from here. [3.1.4 superAdmin](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_314-superadmin-portal%e8%b6%85%e7%ba%a7%e7%ae%a1%e7%90%86%e5%91%98)

**Comment by dmanbu** [comment]
> * 中更新该 User 记录的 Enabled 值为 0
> * 在页面上修改该用户的密码

你需要改 portal 的数据库，把管理员账号改成 LDAP 中的同名账号

**Comment by zihan524** [comment]
建议新增删除用户的功能吧。禁用，改密码等，让强迫症用户受不了啊。

**Comment by nobodyiam** [comment]
用户管理页面已经支持直接禁用用户

![image](https://github.com/apolloconfig/apollo/assets/837658/bc164b80-4535-4f96-91e3-b4f3f0ff145d)

**Comment by zihan524** [comment]
@nobodyiam 不好意思，是想说的删除用户，不是禁用，禁用这个功能知道呢。
