### ISSUE TITLE
OpenAPI的修改与删除配置接口无法使用百分号％的Key

### ISSUE THREAD

**Issue by JianleiZhang** [ctripcorp/apollo#3384]
测试例子：key%key = value
两个接口均返回“404 Not Found”。
如果是新增接口则正常。
有问题的接口URL均包含"/items/$key"参数，但是$key已经使用url.PathEscape转义。

**Comment by nobodyiam** [comment]
这个是 spring security 默认的黑名单机制，参见 [setAllowUrlEncodedPercent](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/web/firewall/StrictHttpFirewall.html#setAllowUrlEncodedPercent-boolean-)
