### ISSUE TITLE
apollo-core的包里面包含了git.properties的文件

### ISSUE THREAD

**Issue by dragontree101** [ctripcorp/apollo#3386]
**Is your feature request related to a problem? Please describe.**
因为我们的框架项目， 会去检查应用项目否生成了git.properties 文件
当git.properties文件在自己的项目中没有生成的情况下， 会默认找到apollo-core里面的git.properties 文件， 则误认为已经生成了，导致后续的流程出现了一些异常。

建议：
删除apollo-core的包里面包含了git.properties的文件，因为git.properties的文件是应用标准文件，基础组件不应该包含这个文件。希望在新版本里面删除这个文件。

谢谢

**Comment by nisiyong** [comment]
Apollo可以考虑换个文件名即可，如`apollo-git.properties`

**Comment by dragontree101** [comment]
是的， 这个也可以。 现在我们的处理方案是， 自己生产的和检查的都是换了一个文件名称

**Comment by nobodyiam** [comment]
我提交了一个 #3390 把文件名改成了 apollo.git.properties

**Comment by dragontree101** [comment]
多谢！
