### ISSUE TITLE
portal数据问题有些疑惑帮忙看下哈

### ISSUE THREAD

**Issue by guohao9527** [ctripcorp/apollo#3387]
1、portal数据库数据丢失后，用官方sql初始化下能进去，但是找不到项目了。这些信息怎么从config同步过来哈
2、多个portal合并的话多个portal该怎么搞哈
在网上也没找到，只能麻烦官方帮忙解惑下哈

**Comment by nobodyiam** [comment]
> 1、portal数据库数据丢失后，用官方sql初始化下能进去，但是找不到项目了。这些信息怎么从config同步过来哈
可以从 configdb 中恢复 App 和 AppNamespace，不过 portaldb 中其它的数据比如权限类的信息只能自己重新设置了

> 2、多个portal合并的话多个portal该怎么搞哈
这个没有现成工具，可以手工搬迁方式或结合 open api 来做

**Comment by guohao9527** [comment]
> > 1、portal数据库数据丢失后，用官方sql初始化下能进去，但是找不到项目了。这些信息怎么从config同步过来哈
> 
> 可以从 configdb 中恢复 App 和 AppNamespace，不过 portaldb 中其它的数据比如权限类的信息只能自己重新设置了
> 
> > 2、多个portal合并的话多个portal该怎么搞哈
> 
> 这个没有现成工具，可以手工搬迁方式或结合 open api 来做

谢谢
