### ISSUE TITLE
http://***/notifications/v2?cluster=default&appId=******

### ISSUE THREAD

**Issue by xujieli1** [ctripcorp/apollo#3388]
源码里面这个方法解析我不是很明白，为什么要用小于号
com.ctrip.framework.apollo.configservice.controller.NotificationControllerV2#filterNotifications   203行 

![image](https://user-images.githubusercontent.com/44740578/99787511-cbbacc80-2b5a-11eb-9610-d91b26881e14.png)

根据我传入的notificationId去获取配置列表，为什么要用小于号，导致我传入相等的也获取不到

**Comment by nobodyiam** [comment]
这一段是用来处理 namespace 大小写不一致的场景的，具体逻辑可以参考上述的注释。

>根据我传入的notificationId去获取配置列表，为什么要用小于号，导致我传入相等的也获取不到

你是自己写了客户端吗？可以尝试debug一下代码，看描述应该和这段逻辑没关系

**Comment by xujieli1** [comment]
【自己没有写客户端】我的报错就是一只提示：Long polling failed, will retry in ** seconds.    我看到客户端代码逻辑是：从这个链接去获取，如果返回200或304是正常的，否则就是不行。本地不会有这个报错，但是测试环境一直有这个warn日志提示，不知道是什么原因，然后尝试改了一下这个notificationId，发现就OK了能获取到。

**Comment by xujieli1** [comment]
#3246 我的报错和这个报错一样的，http://apolloconfig.dev.xisland.cn 这个域名是config-service的域名

**Comment by hulucc** [comment]
我也遇到这个问题了，用比较大的notificationId，config svc就卡住不回复了，会504.

**Comment by nobodyiam** [comment]
@hulucc  apollo 不会返回 504 的，应该是你中间的 lb 超时时间配置的小了，可以尝试调大一些。如果调不了 lb 的超时时间，可以把 apollo long polling 的时间调短，参考 #2532

**Comment by hulucc** [comment]
> @hulucc apollo 不会返回 504 的，应该是你中间的 lb 超时时间配置的小了，可以尝试调大一些。如果调不了 lb 的超时时间，可以把 apollo long polling 的时间调短，参考 #2532

别自动忽略后半段话啊，curl localhost:8080也是卡住的，一个接口卡10秒没问题吗？

**Comment by hulucc** [comment]
我先放弃使用 `Notification` 了，所有的 notification 上去运行一段时间全挂了。定时全量同步吧

**Comment by hulucc** [comment]
> @hulucc apollo 不会返回 504 的，应该是你中间的 lb 超时时间配置的小了，可以尝试调大一些。如果调不了 lb 的超时时间，可以把 apollo long polling 的时间调短，参考 #2532

其他遇到这个问题的同学可以同步一个[认知](https://github.com/ctripcorp/apollo/wiki/%E5%85%B6%E5%AE%83%E8%AF%AD%E8%A8%80%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97#1412-%E8%AF%B7%E6%B1%82%E6%9C%8D%E5%8A%A1)，notification 的 http 请求有个设定是需要hold住60秒的，而并非我之前理解的每60秒去查一次或者走websocket之类的。
这种把短连接当长连接用的方法在很多中间件都会有问题，比如nginx，阿里云的slb等。
服务端改短可以配置环境变量 `LONG_POLLING_TIMEOUT`
helm:
```
env:
  LONG_POLLING_TIMEOUT: '"10"'
```
nginx ingress的话:
```
annotations:
  nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
```

slb对于这种请求似乎是会认为是死链接，经过一个内置的超时后就直接掐了，有人知道如何配置的话请赐教
