### ISSUE TITLE
Custom server.properties file's location

### ISSUE THREAD

**Issue by Anilople** [ctripcorp/apollo#3389]
**Is your feature request related to a problem? Please describe.**

Similar to #2734 

In some company, especially in financial company(bank), operation and maintenance are very strict.

If someone try to create a file `/opt/settings/server.properties`, he/she need **root user**. It will take a long troublesome process, may take several days whenever in test environment or production environment.

It is possible to custom `server.properties` file's location by user?

**Describe the solution you'd like**

User a environment varialbe like `APOLLO_OPT`(maybe other name) to represent the prefix, i.e `/opt`,

so the `/opt/settings/server.properties` is change to `${APOLLO_OPT}/settings/server.properties`

If `APOLLO_OPT` not exists, then use the default value `/opt`

**Describe alternatives you've considered**

Change the code in class `com.ctrip.framework.foundation.internals.provider.DefaultServerProvider`.

Use a static block to resolve `SERVER_PROPERTIES_LINUX` like follow
```java
  static {
    String prefix = System.getenv("APOLLO_OPT");
    if (null == prefix) {
      prefix = "/opt";
    }
    SERVER_PROPERTIES_LINUX = prefix + "/settings/server.properties";
  }
```

**Additional context**

**Comment by nobodyiam** [comment]
I think we could reference the logic to retrieve the cache dir

https://github.com/ctripcorp/apollo/blob/b8be1cd693668b1dc35f33b8381eba961e478615/apollo-client/src/main/java/com/ctrip/framework/apollo/util/ConfigUtil.java#L218-L246

**Comment by Anilople** [comment]
> I think we could reference the logic to retrieve the cache dir
> 
> https://github.com/ctripcorp/apollo/blob/b8be1cd693668b1dc35f33b8381eba961e478615/apollo-client/src/main/java/com/ctrip/framework/apollo/util/ConfigUtil.java#L218-L246

The code is in `apollo-client` module. 

But config service uses `/opt/settings/server.properties` too, move the part of code `com.ctrip.framework.apollo.util.ConfigUtil` to module `apollo-core`?

**Comment by nobodyiam** [comment]
What I meant is we could add the similar logic in DefaultServerProvider...
