### ISSUE TITLE
 1.7 版本 数据库没有key role.create-application.enabled 

### ISSUE THREAD

**Issue by lewisit** [ctripcorp/apollo#3392]
1.7 版本 数据库没有key role.create-application.enabled ，是不支持了，还是需要手动添加。

**Comment by nisiyong** [comment]
这个功能应该是自己手工添加配置的，详细看下文档[ role.create-application.enabled - 是否开启创建项目权限控制](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#10-rolecreate-applicationenabled---%E6%98%AF%E5%90%A6%E5%BC%80%E5%90%AF%E5%88%9B%E5%BB%BA%E9%A1%B9%E7%9B%AE%E6%9D%83%E9%99%90%E6%8E%A7%E5%88%B6)
