### ISSUE TITLE
springboot2.4中配置文件优先级变化问题？

### ISSUE THREAD

**Issue by wangkang09** [ctripcorp/apollo#3396]
springboot2.4时，配置文件优先级发生变化。问下会对 apollo 的配置读取及配置属性覆盖造成影响吗？

**Comment by nisiyong** [comment]
看下了[Spring-Boot-2.4-Release-Notes#config-file-processing-application-properties-and-yaml-files](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes#config-file-processing-application-properties-and-yaml-files)，变换点主要是针对使用Spring Profile特性的场景有影响，普通的`application.properties`或`application.yaml`应该是无缝升级的。

一般来说应用和配置完全分离，代码里只需要配置一个`application.properties`即可，应用获取Apollo不同环境或集群的配置，可以在启动jvm进程时通过系统参数或环境变量指定即可，环境差异的配置都维护在Apollo上。
