### ISSUE TITLE
Apollo 开放平台支持灰度发布

### ISSUE THREAD

**Issue by thinkin** [ctripcorp/apollo#3397]
**Is your feature request related to a problem? Please describe.**
现期望基于Apollo去做配置的分级发布（集成内部系统的分级发布），但是发现开放平台没有灰度发布的API

**Describe the solution you'd like**
提供灰度发布API（包括灰度规则创建 + 灰度发布/回滚）

**Describe alternatives you've considered**

**Additional context**

**Comment by Anilople** [comment]
Duplicate of #3408
