### ISSUE TITLE
今天突然打开一个项目 提示我项目不存在

### ISSUE THREAD

**Issue by vagile-cn** [ctripcorp/apollo#3398]
**Describe the bug**
今天打开这个项目突然就告诉我不存在。。。。不知道这是什么原因

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/22270643/100207715-e0c0a280-2f42-11eb-9a0b-833c650d206a.png)
![image](https://user-images.githubusercontent.com/22270643/100207746-e9b17400-2f42-11eb-95b4-de79ee1d1e48.png)

### Additional Details & Logs

- Version
- Error logs
- Configuration
- Platform and Operating System

**Comment by nisiyong** [comment]
一般不会出现这种情况，找到原因了吗？或者能否提供复现步骤

**Comment by nobodyiam** [comment]
是否在数据库中有手动删除过数据？分别看下 apollo-portal 和 apollo-adminservice 的日志吧

**Comment by vagile-cn** [comment]
啥也没动 也没手动删除啥。。。这些数据 库里都能看到 我现在就想知道 怎么恢复一下

**Comment by vagile-cn** [comment]
@nisiyong @nobodyiam 求助= = 这个该怎么恢复

**Comment by nisiyong** [comment]
你看能否重新建个项目，把配置迁移过去，这种方式最简单了

**Comment by nobodyiam** [comment]
> @nisiyong @nobodyiam 求助= = 这个该怎么恢复

也可以看看 apollo-portal 和 apollo-adminservice 的日志，看到底少了啥数据

**Comment by vagile-cn** [comment]
好的 我看下 谢谢二位 我先看下
@nisiyong @nobodyiam

**Comment by vagile-cn** [comment]
> 你看能否重新建个项目，把配置迁移过去，这种方式最简单了

主要老项目还删不掉。。。。。

**Comment by vagile-cn** [comment]
> > @nisiyong @nobodyiam 求助= = 这个该怎么恢复
> 
> 也可以看看 apollo-portal 和 apollo-adminservice 的日志，看到底少了啥数据

看了下 发现 没啥报错。。。。不知道这是咋了

**Comment by vagile-cn** [comment]
@nianjiang @nobodyiam 
这事 怪我。。。
项目名带AD 然后浏览器有个AD block 。。。。
这都什么事啊= =
