### ISSUE TITLE
NotificationControllerV2#pollNotification 中DeferredResult没有在异步线程中赋值是没有意义的

### ISSUE THREAD

**Issue by brucelwl** [ctripcorp/apollo#3399]
https://github.com/ctripcorp/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/controller/NotificationControllerV2.java#L181,L184

DeferredResult没有在异步线程中赋值是没有意义的, SpringMVC并不会为其在异步线程中执行,还是会占用Servlet线程

**Comment by nobodyiam** [comment]
这个是同步立即返回的场景

**Comment by brucelwl** [comment]
> 这个是同步立即返回的场景

https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1#212-config-service%E9%80%9A%E7%9F%A5%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%9A%84%E5%AE%9E%E7%8E%B0%E6%96%B9%E5%BC%8F

这边可是说的通过DeferredResult挂起请求

用DeferredResult搞同步返回,服...

**Comment by nobodyiam** [comment]
这里面有两个分支，一个分支是立即返回更新通知，另一个是挂起后等待更新通知

**Comment by brucelwl** [comment]
> 这里面有两个分支，一个分支是立即返回更新通知，另一个是挂起后等待更新通知
有劳指定具体分支,学习一下
