### ISSUE TITLE
DatabaseMessageSender#cleanMessage 会有并发问题的吧？

### ISSUE THREAD

**Issue by shenjianeng** [ctripcorp/apollo#3403]
```java
com.ctrip.framework.apollo.biz.message.DatabaseMessageSender#cleanMessage

 private void cleanMessage(Long id) {
    //double check in case the release message is rolled back
    ReleaseMessage releaseMessage = releaseMessageRepository.findById(id).orElse(null);
    if (releaseMessage == null) {
      return;
    }
```

这里虽然进行了 double check ，但是还是有可能两个节点同时运行，根据id去查的时候发现 ReleaseMessage 都不为空，然后向下执行吧？这里的 check 只能降低这种情况出现的概率，并不能彻底解决的吧？

**Comment by shenjianeng** [comment]
另外，DatabaseMessageSender#cleanMessage 在定时执行，执行的频率是写死在代码中的。

ReleaseMessageScanner 在定时扫描 DB，扫描的时间是可以配置的。

有没有可能在并发情况下，消息还没有被 ReleaseMessageScanner 扫描到，就已经被 DatabaseMessageSender 给 clean 了？

**Comment by nobodyiam** [comment]
>     //double check in case the release message is rolled back

这里的 check 不是为了防止两个节点同时运行，是为了防止这条 release message 记录被 rollback 掉了

> 有没有可能在并发情况下，消息还没有被 ReleaseMessageScanner 扫描到，就已经被 DatabaseMessageSender 给 clean 了？

clean 的是老的 release message，不是当前这条 release message

**Comment by shenjianeng** [comment]
两个节点，一个节点 id 7，一个节点 id 8 ，要是这个两个节点同时运行了，是不是就有可能有问题？
