### ISSUE TITLE
Apollo client local cache file delay

### ISSUE THREAD

**Issue by lovegwwp** [ctripcorp/apollo#3406]
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) of this repository and believe that this is not a duplicate.

**Describe the bug**

业务整合使用portal的源码，进行指定产品指定namespace的数据下发，数据下发内容包含一定量的富文本（此namesce文件下载本地缓存文件中约4m左右） 。更改当前namespace 的随机某个数值时，并且成功发布，但是过了几分钟 （小于5分钟的数据主动刷新是时间）本地文件仍然没有变化。求解

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

### Additional Details & Logs

- Version
- Error logs
- Configuration
- Platform and Operating System

**Comment by nisiyong** [comment]
看下客户端源码和日志，看是否请求超时失败之类的

**Comment by lovegwwp** [comment]
config 服务端 有正常的release message
![image](https://user-images.githubusercontent.com/33893474/100719423-93877980-33f7-11eb-9b40-45941cd3d1dc.png)

然而 客户端没有异常日志

**Comment by nisiyong** [comment]
客户端设置DEBUG级别看下日志，你可以结合源码看下

**Comment by lovegwwp** [comment]
postman操作接口下发且成功
![image](https://user-images.githubusercontent.com/33893474/100832309-8ffcfc80-34a2-11eb-92db-4646280b0796.png)

config 服务端-打印receive相关namesapce日志
![image](https://user-images.githubusercontent.com/33893474/100832373-ae62f800-34a2-11eb-9ad9-66d9cbc9a457.png)

客户端此时没有当前namesapce 相关响应，没有刷新本地缓存  取值依然是旧数值
![image](https://user-images.githubusercontent.com/33893474/100832470-e66a3b00-34a2-11eb-9b7b-468bb5aee71b.png)
本地缓存文件 没有刷新
![image](https://user-images.githubusercontent.com/33893474/100832488-f08c3980-34a2-11eb-8afb-28605f2ef278.png)

**Comment by nobodyiam** [comment]
看日志客户端没有收到配置更新通知，可以看一下是否会灰度发布之类的配置，或者看一下 config service 的负载情况，是否 gc 比较严重之类的。另外是否过了 5 分钟就能收到配置更新？

**Comment by wmhiness** [comment]
.net core 配置间隔时间主动拉取配置的节点什么啊？ .net core客户端可以自定义文件缓存路径吗

**Comment by lovegwwp** [comment]
这个数据延迟问题 应该是 我们在下发配置的时候 没有区分 appid  和namespacede 大小写导致的
譬如 我实际 的appid 是ABC namespace 是 MN  但是我业务中 对大小写不敏感 实际传入的 appid 是 Abc  namespce 是mn  
导致     publisher.publishEvent(event); 不对 

因此更改了（源码）代码
![image](https://user-images.githubusercontent.com/33893474/102312348-80ed7280-3fa9-11eb-9259-f3882deadd77.png)

原则上是我们这边业务原因导致的数据延迟，但是希望 apollo 开发人员  可以参考下类似我们这种业务需求，既然查询的时候 不区分大小写，是否在release 的时候也可以不区分不小写呢，做到一致性。

**Comment by nobodyiam** [comment]
这个在 1.6.0 版本修复过的，#2696
另外，你贴的这个是 portal 的接口，你们是自己的业务代码调了 portal 的接口做配置发布？

**Comment by lovegwwp** [comment]
对的   我们是自己的业务代码调了 portal 的接口做配置发布 ，我升级版本看下。感谢支持
