### ISSUE TITLE
【问题】关于配置信息的导入导出

### ISSUE THREAD

**Issue by lanxiaolin-sz** [ctripcorp/apollo#3409]
如[#3303](https://github.com/ctripcorp/apollo/issues/3303)
目前想要尝试使用import和export的功能，
不过我在配置的时候无法导入对应库-apollo-portal

```
       <dependency>
            <groupId>com.ctrip.framework.apollo</groupId>
            <artifactId>apollo-portal</artifactId>
            <version>1.6.0</version>
        </dependency>

```
请问是否是配置的原因，还是需要做别的操作呢？

**Comment by Anilople** [comment]
根据

https://mvnrepository.com/artifact/com.ctrip.framework.apollo

的结果

这个依赖并没有发布

可以自己写HTTP请求，或者使用curl，来访问portal的接口
