### ISSUE TITLE
helm部署 apollo 的问题

### ISSUE THREAD

**Issue by xbo729** [ctripcorp/apollo#3412]
1.ingress 暴露 protal 服务 与 service 服务 服务之间都能互相通信  但是拿取环境的时候 报错了
![7K 0VIE3WKRQZGOG{8Z~$U](https://user-images.githubusercontent.com/13294849/101117876-f3ae3380-3622-11eb-8b1b-bc165162b65f.png)
2.使用的是git上最新的helm脚本0.2.0版本 镜像版本用的latest 最新版本 具体helm 如下
apollo-service:
![50}( F39W8V TBDY`LB1JG5](https://user-images.githubusercontent.com/13294849/101118388-eba2c380-3623-11eb-8594-b42bf9c602ca.png)

apollo-protal:
![(@})_QBV`2A%N_J{MOK~6(4](https://user-images.githubusercontent.com/13294849/101118412-f0677780-3623-11eb-9278-94e3b7826c05.png)

具体接口报错信息
![UME7`HIRFG3T{C$FKM7G0T9](https://user-images.githubusercontent.com/13294849/101118417-f2313b00-3623-11eb-931e-74d7bd45eee2.png)

 希望能得到解决

**Comment by nobodyiam** [comment]
下面这两个配置配错了，建议先不要自行配置，用默认值应该也能跑起来
![image](https://user-images.githubusercontent.com/837658/101230846-d5a80800-36e2-11eb-9c89-57c6b7bf802a.png)

**Comment by xbo729** [comment]
经过一谈的测试 发现这个configserver 必须和meta server要一致 才不会导致这个问题的出现、目前已经正常运行
