### ISSUE TITLE
spring mvc项目如何在配置文件里面指定cluster集群？

### ISSUE THREAD

**Issue by KevinShinn** [ctripcorp/apollo#3414]
spring 项目如何在配置文件里面指定cluster集群？能够实现不同profile 打包指定不同的cluster？

**Comment by nisiyong** [comment]
不建议用Spring Profile来区分集群，建议在启动时指定集群环境变量或系统参数

**Comment by nobodyiam** [comment]
@KevinShinn spring boot项目可以，参见[1.2.4.2 Cluster（集群）](https://github.com/ctripcorp/apollo/wiki/%E5%85%B6%E5%AE%83%E8%AF%AD%E8%A8%80%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97#13-%E9%80%9A%E8%BF%87%E4%B8%8D%E5%B8%A6%E7%BC%93%E5%AD%98%E7%9A%84http%E6%8E%A5%E5%8F%A3%E4%BB%8Eapollo%E8%AF%BB%E5%8F%96%E9%85%8D%E7%BD%AE)，不过集群信息属于环境信息，所以还是建议通过环境变量、系统参数或本地文件方式来指定

**Comment by KevinShinn** [comment]
> @KevinShinn spring boot项目可以，参见[1.2.4.2 Cluster（集群）](https://github.com/ctripcorp/apollo/wiki/%E5%85%B6%E5%AE%83%E8%AF%AD%E8%A8%80%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97#13-%E9%80%9A%E8%BF%87%E4%B8%8D%E5%B8%A6%E7%BC%93%E5%AD%98%E7%9A%84http%E6%8E%A5%E5%8F%A3%E4%BB%8Eapollo%E8%AF%BB%E5%8F%96%E9%85%8D%E7%BD%AE)，不过集群信息属于环境信息，所以还是建议通过环境变量、系统参数或本地文件方式来指定

不是boot 项目有方法实现吗

**Comment by nisiyong** [comment]
一样的，是Java应用就行

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
