### ISSUE TITLE
不同版本的server 能放在一起群集吗？

### ISSUE THREAD

**Issue by RockyLOMO** [ctripcorp/apollo#3416]
目前群集版本是1.5.1，想升级到1.7.1，本地试了一下 client 1.5.1 和 server 1.7.1 兼容。

那么 如果把 server 1.7.1 的新部署一套 加入到 server 1.5.1群集里，然后再下线 1.5.1的server，这种是否会有问题？

**Comment by nobodyiam** [comment]
同一个集群中版本是可以不一样的，滚动升级都是这么玩的。
依赖层次上，apollo-adminservice 要先于 apollo-portal 完成集群升级。

**Comment by RockyLOMO** [comment]
好的谢谢
