### ISSUE TITLE
请问目前单个配置的最大大小支持多大？

### ISSUE THREAD

**Issue by ruanwenjun** [ctripcorp/apollo#3417]

**Comment by nobodyiam** [comment]
[item.value.length.limit - 配置项 value 最大长度限制](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#5-itemvaluelengthlimit---%E9%85%8D%E7%BD%AE%E9%A1%B9-value-%E6%9C%80%E5%A4%A7%E9%95%BF%E5%BA%A6%E9%99%90%E5%88%B6)
