### ISSUE TITLE
两套环境注册到了同一个registry,请问app.properties 的appId 需要修改吗。

### ISSUE THREAD

**Issue by dususu** [ctripcorp/apollo#3419]
两套环境注册到了同一个registry,请问app.properties 的appId 需要修改吗。

**Comment by nobodyiam** [comment]
你是指两套环境的 apollo-configservice 和 apollo-adminservice 注册到了同一个 registry？修改 appid 比较麻烦的，registry 还是分环境吧

**Comment by dususu** [comment]
好的。
