### ISSUE TITLE
apollo client AbstractConfig定制

### ISSUE THREAD

**Issue by xianyouQ** [ctripcorp/apollo#3421]
**Is your feature request related to a problem? Please describe.**
我们想将一些自有逻辑放到 client AbstractConfig中，所以想通过ApolloInjector SPI 加载自定义的Injector 实现来load 自己的AbstractConfig，但是目前ApolloInjector SPI 调用的是loadFirst，能将这个调用改成按照优先级来取吗

**Comment by nisiyong** [comment]
最好先描述下你这么做的原因是什么？

**Comment by nobodyiam** [comment]
恩，描述下场景会更有利于讨论。
另外，针对这块 spi 自定义，我们需要考虑一下自定义的粒度，如果只是针对某个 namespace 自定义的话，使用com.ctrip.framework.apollo.ConfigService#setConfigFactory(java.lang.String, com.ctrip.framework.apollo.spi.ConfigFactory)应该就能实现：
https://github.com/ctripcorp/apollo/blob/f8683a243e2a6515836de1c4222b96a40b106182/apollo-client/src/main/java/com/ctrip/framework/apollo/ConfigService.java#L97-L105

如果是针对所有 namespace 自定义的话，那可能就要实现自定义的 Injector 了：
https://github.com/ctripcorp/apollo/blob/f8683a243e2a6515836de1c4222b96a40b106182/apollo-client/src/main/java/com/ctrip/framework/apollo/build/ApolloInjector.java#L15-L31
