### ISSUE TITLE
documentation support

### ISSUE THREAD

**Issue by Anilople** [ctripcorp/apollo#3422]
### feature request about the documentation

A website like

* https://kubernetes.io/docs/home/
* https://skywalking.apache.org/
* https://nacos.io/en-us/docs/quick-start.html
* https://shardingsphere.apache.org/document/current/en/overview/

let user get better documentation experience.

User can **search** content they want, **edit** the page(need pull request), etc.

### Describe the solution you'd like

Create the `.md` file under folder `docs`, and open github page or use tool to generate the website.

#### tool choose?

* [Hugo](https://gohugo.io/)
* [docsify](https://docsify.js.org/#/)
* [jekyll](https://jekyllrb.com/)
* other...

#### a new github repository or not?

Skywalking is not use a new respository. https://github.com/apache/skywalking/tree/master/docs
Documentation under the folder `docs`

But kubernetes use a new respository. https://github.com/kubernetes/website

**Comment by nobodyiam** [comment]
Sounds a good idea! Personally I would prefer to put the docs in the same repository, but I'm open for other alternatives.

**Comment by nisiyong** [comment]
I like the skywalking project way. Although they use Hugo to build the official static website, the documents still keep in the main GitHub repo alongside the source code.

I think we can move the documents from Github Wiki to the sources code first, after that we consider building an apollo official static site, this is another topic.
