### ISSUE TITLE
app.id，app.env 和spring.application.name，spring.profiles.active 可否通用

### ISSUE THREAD

**Issue by DimonHo** [ctripcorp/apollo#3423]
app.id和app.env的配置似乎和spring.application.name，spring.profiles.active这两个配置重叠的，app.id和app.env能否自动识别spring.application.name，spring.profiles.active进行注入呢？

**Comment by Anilople** [comment]
> app.id和app.env的配置似乎和spring.application.name，spring.profiles.active这两个配置重叠的，app.id和app.env能否自动识别spring.application.name，spring.profiles.active进行注入呢？

让`spring.application.name`被`app.id`决定
```properties
spring.application.name = ${app.id}
```

但是关于`spring.profiles.active`，不知道下面这种配置方式是否可行
```properties
spring.profiles.active = ${app.env}
```

**Comment by DimonHo** [comment]
> > app.id和app.env的配置似乎和spring.application.name，spring.profiles.active这两个配置重叠的，app.id和app.env能否自动识别spring.application.name，spring.profiles.active进行注入呢？
> 
> 让`spring.application.name`被`app.id`决定
> 
> ```ini
> spring.application.name = ${app.id}
> ```
> 
> 但是关于`spring.profiles.active`，不知道下面这种配置方式是否可行
> 
> ```ini
> spring.profiles.active = ${app.env}
> ```

感觉重复配置了，我自定义了一个starter:  https://github.com/DimonHo/apollo-client-spring-boot-starter，兼容了这个特性

**Comment by nobodyiam** [comment]
app.id 和 spring.application.name 倒是可以尝试互补一下，不过上面的实现是把 spring.application.name 覆盖了 app.properties 中配置的 app.id 了，担心会对已有项目产生影响。

env 和 spring.profiles.active 在语义上不太一样，建议还是以环境信息传入，而且 spring.profiles.active 的值是可以逗号分隔传入多个的
