### ISSUE TITLE
portal进程总被linux系统kill

### ISSUE THREAD

**Issue by Oncesss** [ctripcorp/apollo#3424]
**Describe the bug**
apollo版本：0.11.0
portal进程不定时被kill掉，排查情况如下：
1. 使用root查找linux系统日志，明确指明进程被系统所kill
2. 开启linux系统的corefile限制后，进程被kill后产生对应进程的core文件
3. 使用jmap将core文件内存dump出，用mat工具排查后，发现内存只占用了几百M
4. 检查进程的GC文件，发现在portal进行文件备份时，会经常性出现application time 超过几百秒，几千秒的情况。且经常性是在配置文件backup 完成之后发生。
5. 最后通过日志输出，捕获到最后的日志输出：
Error in `java` : double free or corruption(!prev)
=======Backtrace==========
/lib64/libc.so.6(+0x81489)[0x7f3658d16489]
/usr/java/jdk1.8.0_151/jre/adm64/server/libjvm.so

**Comment by nobodyiam** [comment]
dmesg 看看？

**Comment by Oncesss** [comment]
> dmesg 看看？
是要看/var/log/下的系统日志吗？有存储的一次日志内容如下，111205是portal进程的进程号
abrt-hook-ccpp:Process 111205 (java) of user 1001 killed by SIGABRT - dumping core
abrt-hook-ccpp:Failed to create core_backtrace: waitpid failed:no child processes
systemd-logind: Removed session 49389
abrtd: Size of '/var/spool/abrt' >= 1000 MB (MaxCrashReportsSize), deleting old directory 'ccpp-2020-08-19-15:41:06-87437'

**Comment by nobodyiam** [comment]
> abrtd: Size of '/var/spool/abrt' >= 1000 MB (MaxCrashReportsSize), deleting old directory 'ccpp-2020-08-19-15:41:06-87437'

这个目录下是否有有用的信息？

另外，执行一下 `dmesg` 命令看看呢

**Comment by Oncesss** [comment]
最近出现这种情况的服务器dmesg命令中，进程挂掉对应的时间段内容如下：
`
DCCP：Activated CCID2（TCP-like)
DCCP：Activated CCID2（TCP-like)
sctp:Hash tables configured(bind 256/256)
warning:`turbostat` use 32-bit capabilities (legacy support in use)
`
/var/spool/abrt下有对应日期的文件夹，其中有生成的coredump文件和进程被kill的reason等文件，core文件内容如为：
`
Core was generated by `java -XX:+UseParNewGC -XX:ParalleGCThreads=4 -XX:MaxTenuringThreshold=9 -XX:+U',
Program terminated with signal 6,Aborted
`

**Comment by nobodyiam** [comment]
这个信息不是太详细，不过 java 进程被 kill 的较多情况是内存不够了

**Comment by Oncesss** [comment]
尝试升级过机器内存，内存从8G提升到16G后仍然会出现这种情况，而且主要出现在测试环境为主，开发环境未发生过

**Comment by nobodyiam** [comment]
> 检查进程的GC文件，发现在portal进行文件备份时，会经常性出现application time 超过几百秒，几千秒的情况。且经常性是在配置文件backup 完成之后发生。

这里的文件备份具体是指啥？
另外，测试环境和开发环境的 jvm 版本一样吗？
