### ISSUE TITLE
使用META-INF/app.properties配置文件使用apollo无法获取apollo.cluster的问题

### ISSUE THREAD

**Issue by wzxin-youxi** [ctripcorp/apollo#3427]
**Describe the bug**
在META-INF/app.properties下配置了apollo的环境，配置模板如下：
app.id=******
apollo.meta=http://ip:端口
apollo.cluster=state
apollo.cacheDir=./tmp
apollo.bootstrap.enabled=true
apollo.bootstrap.namespaces=application

在代码中调用ConfigService.getConfig(namespace);启用apollo，发现无法获取apollo.cluster为state的值，代码中获取的cluster还是为default。

**Reason**
1. 对比检查apollo-core和apollo-client的代码中，发现apollo.cluster在代码中的获取方式是先从System.properties下读取“apollo.cluster”为key的值（见apollo-client下ConfigUtil的initCluster方法），如果是在SpringBoot中使用apollo，apollo会在开始加载前通过Spring自动加载的方式在ApolloApplicationContextInitializer中将apollo.cluster参数加载到System.properties中，而如果不使用Spring的话，则System.properties中就没有apollo.cluster数据。
2. apollo.cluster从System.properties下获取不到值后，会从DefaultServerProvider类中获取m_dc的值作为cluster的值，DefaultServerProvider是通过读取“C:/opt/settings/server.properties”配置文件进行配置的，如果正好没有这个配置文件，则m_dc为null，则返回的apollo.cluster为空。
3. 如果以上两步都获取不到apollo.cluster的话，则apollo.cluster设置为默认值：default。
结论：从以上可知，如果不与spring的结合使用apollo的话，会导致配置文件中的apollo.cluster无法正确设置。

**我司处理方式**
首先将cluster的获取方式，即以上描述的内容，1和2对调，先从m_dc获取，没有的话，再从System.properties获取。
![image](https://user-images.githubusercontent.com/19815714/101852667-27e0a180-3b99-11eb-9215-7c149554ec69.png)

然后在读取/META-INF/app.properties的时候将参数设置到System.properties中。
![image](https://user-images.githubusercontent.com/19815714/101852766-565e7c80-3b99-11eb-8d37-04a379c4d211.png)
![image](https://user-images.githubusercontent.com/19815714/101852812-6e360080-3b99-11eb-9a47-b92d37d3d485.png)

- Platform and Operating System

**Comment by nisiyong** [comment]
你看下文档[1.2.4.2 Cluster（集群）](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#1242-cluster%E9%9B%86%E7%BE%A4)，没有说过可以从META-INF/app.properties设置cluster。

> 通过Spring Boot的配置文件
可以在Spring Boot的application.properties或bootstrap.properties中指定apollo.cluster=SomeCluster

虽然用SpringBoot支持这种方式，不过我还是不太建议。

不建议这么做也是合理的，应用代码里不应该写死环境或集群的配置。
应该环境差异的信息考虑外置化，如外部配置文件或启动时动态指定（如通过环境变量，或-D系统参数方式）

**Comment by wzxin-youxi** [comment]
> ，没有说过可以从META-INF/app.properties设置c

看了一下文档，确实是我没认真看文档导致配置都一起写在了app.properties中而出现的这个问题，学习了，多谢。
