### ISSUE TITLE
yaml 数组的方式要怎么支持？

### ISSUE THREAD

**Issue by RockyLOMO** [ctripcorp/apollo#3432]
貌似只支持array=1,2  这种写法

配置的value 
`- 1
- 2`

没有效果

**Comment by nobodyiam** [comment]
You may reference the following instructions:
https://github.com/ctripcorp/apollo/blob/03bc4b470b640a219cfb7c991f6b999553560e32/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/spring/springBootDemo/config/SampleRedisConfig.java#L16-L45

**Comment by RockyLOMO** [comment]
> You may refer the following instructions:
> https://github.com/ctripcorp/apollo/blob/03bc4b470b640a219cfb7c991f6b999553560e32/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/spring/springBootDemo/config/SampleRedisConfig.java#L16-L45

``` yaml
redis: 
  cache: 
    someList: 
      - c 
      - d
```

``` java
String[] someList;
```
When I fill in the key 'redis.cache.someList' and value '  -c\n  -d' on the portal page, the array I get in the program is ["  - c\n  -d"]

**Comment by nobodyiam** [comment]
This requires the usage of `@ConfigurationProperties`
