### ISSUE TITLE
v1.5.1 升级 v.1.6.0

### ISSUE THREAD

**Issue by kys1230** [ctripcorp/apollo#3436]
如标题所示, 目前在使用的是 v1.5.1 版本, 并根据添加自定义环境文档添加过符合我们使用需求的多个环境, 现在想升级至 v1.6.0 版本, 除了文档中所提到的<<如何从v1.5.1升级到v1.6.0>> 是否还有其他注意事项, 另外升级过后我原本定义的自定义环境是否还能正常使用?

**Comment by kys1230** [comment]
谁知道答案能回答一下吗?

**Comment by nobodyiam** [comment]
根据[Portal如何增加环境？](https://ctripcorp.github.io/apollo/#/zh/faq/common-issues-in-deployment-and-development-phase?id=_4-portal%e5%a6%82%e4%bd%95%e5%a2%9e%e5%8a%a0%e7%8e%af%e5%a2%83%ef%bc%9f)这个说明，升级过后仍然是适用的
