### ISSUE TITLE
K8S使用了Kong Ingress Controller，登陆成功后马上被踢出

### ISSUE THREAD

**Issue by RobertoHuang** [ctripcorp/apollo#3437]
K8S使用了Kong Ingress Controller，登陆成功后马上被踢出

感觉像是会话没保持住，这个要怎么解决？

**Comment by nisiyong** [comment]
Apollo的Session默认是在内存的，你可能要看看是不是请求分不到不同的Portal进程上。
可以考虑下ip hash的负载均衡策略

**Comment by RobertoHuang** [comment]
嗯 我现在是部署单个Portal节点 就可以了... 我再参考一下Kong的负载策略
