### ISSUE TITLE
1.5.1版本从官网下载发布包，启动后项目控制台不展示配置

### ISSUE THREAD

**Issue by 1725636955** [ctripcorp/apollo#3439]
- [ ] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) of this repository and believe that this is not a duplicate.

**Describe the bug**
使用脚本启动后，项目控制台报错，且配置不展示，切换微软的Edge浏览器则无此bug
谷歌浏览器报angular.min.js?v=20191109152139:113 Error: [$injector:unpr] http://errors.angularjs.org/1.5.1/$injector/unpr?p0=prefixPathFilterProvider%20%3C-%20prefixPathFilter
![image](https://user-images.githubusercontent.com/43667484/102181463-90a38300-3ee5-11eb-9a44-a60d0a9b9f50.png)

**To Reproduce**
1. 从发布界面https://github.com/ctripcorp/apollo/releases下载1.5.1的发布包
2. 启动项目
3. 创建一个配置
4. 打开配置

**Expected behavior**
谷歌显示正常

**Screenshots**
Edge正常显示
![image](https://user-images.githubusercontent.com/43667484/102181672-027bcc80-3ee6-11eb-95f7-e03343322602.png)
谷歌报错，谷歌版本为：版本 87.0.4280.88（正式版本） （64 位）
![image](https://user-images.githubusercontent.com/43667484/102181680-090a4400-3ee6-11eb-954d-d1459aa64fd7.png)

### Additional Details & Logs
只有谷歌控制台日志，java后台项目并无错误日志

- Version 1.5.1
- Error logs 谷歌控制台日志Error: [$injector:unpr] http://errors.angularjs.org/1.5.1/$injector/unpr?p0=prefixPathFilterProvider%20%3C-%20prefixPathFilter
- Configuration 普通配置
- Platform and Operating System linux centos 7

**Comment by nobodyiam** [comment]
用隐身模式打开试一下，或者清理一下缓存

**Comment by 1725636955** [comment]
> 用隐身模式打开试一下，或者清理一下缓存

今天又试了一下可以了，我是从1.6.0快照版降到1.5.1发布版的，之后就出现了这样的问题，不知道哪里的缓存，谢谢您了
