### ISSUE TITLE
如何配置 Apollo 使用 Keycloak

### ISSUE THREAD

**Issue by hmmxp** [ctripcorp/apollo#3441]
Dear All,

我看了 Portal 实现用户登录功能：实现方式三： 接入公司的统一登录认证系统
https://github.com/ctripcorp/apollo/wiki/Portal-%E5%AE%9E%E7%8E%B0%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95%E5%8A%9F%E8%83%BD#%E5%AE%9E%E7%8E%B0%E6%96%B9%E5%BC%8F%E4%B8%89-%E6%8E%A5%E5%85%A5%E5%85%AC%E5%8F%B8%E7%9A%84%E7%BB%9F%E4%B8%80%E7%99%BB%E5%BD%95%E8%AE%A4%E8%AF%81%E7%B3%BB%E7%BB%9F

我还是不清楚我需要如何配置我当前 Keycloak Client 的信息在 Apollo Portal, 我当前已经在 Keycloak 配置了一个 client 使用  openid-connect. 同时已经拥有 authorization_endpoint, token_endpooint, userinfo_endpoint.

我如何配置以上让 Apollo Portal 用户使用 keycloak 登入

**Comment by nobodyiam** [comment]
1. 按照 keycloak 的说明在 apollo-portal 中集成 keycloak 的登录功能
2. 按照[实现方式三： 接入公司的统一登录认证系统](https://github.com/ctripcorp/apollo/wiki/Portal-%E5%AE%9E%E7%8E%B0%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95%E5%8A%9F%E8%83%BD#%E5%AE%9E%E7%8E%B0%E6%96%B9%E5%BC%8F%E4%B8%89-%E6%8E%A5%E5%85%A5%E5%85%AC%E5%8F%B8%E7%9A%84%E7%BB%9F%E4%B8%80%E7%99%BB%E5%BD%95%E8%AE%A4%E8%AF%81%E7%B3%BB%E7%BB%9F)的说明实现 spi

**Comment by hmmxp** [comment]
> 1. 按照 keycloak 的说明在 apollo-portal 中集成 keycloak 的登录功能
> 2. 按照[实现方式三： 接入公司的统一登录认证系统](https://github.com/ctripcorp/apollo/wiki/Portal-%E5%AE%9E%E7%8E%B0%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95%E5%8A%9F%E8%83%BD#%E5%AE%9E%E7%8E%B0%E6%96%B9%E5%BC%8F%E4%B8%89-%E6%8E%A5%E5%85%A5%E5%85%AC%E5%8F%B8%E7%9A%84%E7%BB%9F%E4%B8%80%E7%99%BB%E5%BD%95%E8%AE%A4%E8%AF%81%E7%B3%BB%E7%BB%9F)的说明实现 spi

请问有没有比较详细的·说明, 比如配置需要在哪一项配置？

另外是否 按照 keycloak 的说明在 apollo-portal 中集成 keycloak 的登录功能， 这个有没有对应文档？

感谢

**Comment by hmmxp** [comment]
是否可以按照以下配置, 配置 spring security 

Spring Security集成Keycloak

配置application.properties

keycloak.realm=demo
keycloak.resource=login-app
keycloak.auth-server-url=http://localhost:8180/auth
keycloak.ssl-required=external
keycloak.public-client=true
keycloak.use-resource-role-mappings=true
keycloak.confidential-port=0
keycloak.principal-attribute=preferred_username
