### ISSUE TITLE
如何在没有外网下安装部署，需要提前下载哪些引用的docker镜像或者是预安装包？

### ISSUE THREAD

**Issue by zhaorongxi** [ctripcorp/apollo#3442]
需要在完全没有外网的环境下安装，都有哪些包需要预先准备好呢？？ @nobodyiam

**Comment by 1725636955** [comment]
> 需要在完全没有外网的环境下安装，都有哪些包需要预先准备好呢？？ @nobodyiam

docker部署
1. 下载发布包
2. 下载源码，切换到对应发布版本的源码。通过源码portal、config、admin三个模块的Dockerfile构建
宿主机构建，下载发布包直接启动
