### ISSUE TITLE
Client 端更新速度太慢，有时1s有时1分钟

### ISSUE THREAD

**Issue by renjiahua945** [ctripcorp/apollo#3445]
Client 端更新配置太慢，已经绑定了changeListener  但是更新速度有时1s 有时1分钟

**Comment by nobodyiam** [comment]
打开 DEBUG 日志看下

**Comment by renjiahua945** [comment]
debug发现是m_longPollFailSchedulePolicyInSecond 这个的问题，这个默认是120s,返回超级慢。如果改为10s,基本上可以5s内变更。大佬帮忙评估下，可不可以这么改

**Comment by klboke** [comment]
最好定位到真实问题，这个是用来兜底的

**Comment by renjiahua945** [comment]
那就是notifications 没有及时返回。我看见notifications 是异步的，他有变化没有及时返回。

**Comment by renjiahua945** [comment]
找到问题了 httprequest 的超时被我不小心删除掉了。导致没有返回
