### ISSUE TITLE
同一应用内命名空间相互引用问题

### ISSUE THREAD

**Issue by xchao263** [ctripcorp/apollo#3446]
场景：
产品中各模块的配置在同一个应用内，各模块使用各自的命名空间。

在某些场景下，同一功能模块会运行多个实例，各实例之间仅是少量配置有差异，如：TCP 监听端口、某些开关选项等，
一般做法是：把原的命名空间中 全部的配置 手工复制一份到 新命名空间中，此时 将产生大量重复 的配置。
一般情况下，同一应用内，不同命名空间之间存在相同配置的情况大量存在，如：kafka\redis 等通用连接参数信息等，我们当前是通过自定义实现了 “跨命名空间的引用”，如：在 namespace_B 中 key_xxx = ${namespace_A.key}，缺点是必须手工增加一个条目，没有“隐式继承、引用”效果。

“公共组件”方式无法满足此需求，因为那种方式只能引用其它 应用里创建的 public 命名空间。

需求：
同一应用内，新创建的命名空间也能按“像引用 其它应用下手公网命名空间”那样进行“引用” 本应用内的其它 命名空间，再按需要增加或修改（覆盖）相关 配置。

请考虑。

**Comment by klboke** [comment]
一个应用内，有默认的application的命名空间可以使用，相同功能的配置都可以放到这命名空间里，然后每个模块加载application和自己独有的命名空间，这个可以解决你的场景问题么？我们现在就是这么用的，场景和你类似

**Comment by xchao263** [comment]
> 一个应用内，有默认的application的命名空间可以使用，相同功能的配置都可以放到这命名空间里，然后每个模块加载application和自己独有的命名空间，这个可以解决你的场景问题么？我们现在就是这么用的，场景和你类似

不太一样，我们一个应用内，有很多个命名空间。各个命名空间都是独立的功能模块，之前没有关系。
现在的需求只是某个应用，因某些情况，要再RUN一份，但仅是个别、或 少量参数不一样，此时 我们的做法时，新建全新的命名空间，再从前一个里粘贴全部的内容，有针对性的修改，再使。
此过程要存在 手工复制全部已有内容的操作。

目标需求是：
新建的 命名空间 与 之前 能够有某种关联，而在新命名空间中，只修改那些需要修改的，同时还能加载出关联的那些配置。

**Comment by nobodyiam** [comment]
和 #2688 有些类似，可以参考下
