### ISSUE TITLE
1.7.1版本portal在windows IDEA正常启动后访问8070端口直接登入且无法正常退出，无法创建用户

### ISSUE THREAD

**Issue by zyexplorer** [ctripcorp/apollo#3449]
- [ ] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) of this repository and believe that this is not a duplicate.

**Describe the bug**

**To Reproduce**
1. 按文档修改好配置文件，顺序启动configservice、adminservice、portal
2. 访问http://localhost:8070  【正常应该是跳到登录页，实际直接跳到了登陆之后的home页面】
3. 在登陆之后的home页面的管理员工具->用户管理中新建用户 报错，无权限

**Expected behavior**

**Screenshots**

### Additional Details & Logs

- Version 1.7.1
- Error logs 
- Configuration
- Platform and Operating System

**Comment by Anilople** [comment]
> 正常应该是跳到登录页，实际直接跳到了登陆之后的home页面

According the doc
[Apollo开发指南](https://ctripcorp.github.io/apollo/#/zh/development/apollo-development-guide)

You should config as least

```properties
-Dapollo_profile=github,auth
```
to enable the login.

**Comment by zyexplorer** [comment]
感谢你的回复。然鹅，加了这个启动参数，并没有起作用，还是如上面问题描述的那样。

![image](https://user-images.githubusercontent.com/48943780/102981358-cbd82e80-4543-11eb-99b1-65e6b1eec944.png)
![image](https://user-images.githubusercontent.com/48943780/102981638-39845a80-4544-11eb-8689-1ff1073c078e.png)
![image](https://user-images.githubusercontent.com/48943780/102981712-591b8300-4544-11eb-8b97-965f1983b2d5.png)
![image](https://user-images.githubusercontent.com/48943780/102981750-63d61800-4544-11eb-9e34-d5f0420ddd79.png)

**Comment by zyexplorer** [comment]
> > 正常应该是跳到登录页，实际直接跳到了登陆之后的home页面
> 
> According the doc
> [Apollo开发指南](https://ctripcorp.github.io/apollo/#/zh/development/apollo-development-guide)
> 
> You should config as least
> 
> ```ini
> -Dapollo_profile=github,auth
> ```
> 
> to enable the login.

烦请查看上面截图。如果看不到截图，请增加以下host配置：

  192.30.253.112    Build software better, together 
  192.30.253.119    gist.github.com
  151.101.184.133    assets-cdn.github.com
  151.101.184.133    raw.githubusercontent.com
  151.101.184.133    gist.githubusercontent.com
  151.101.184.133    cloud.githubusercontent.com
  151.101.184.133    camo.githubusercontent.com
  151.101.184.133    avatars0.githubusercontent.com
  151.101.184.133    avatars1.githubusercontent.com
  151.101.184.133    avatars2.githubusercontent.com
  151.101.184.133    avatars3.githubusercontent.com
  151.101.184.133    avatars4.githubusercontent.com
  151.101.184.133    avatars5.githubusercontent.com
  151.101.184.133    avatars6.githubusercontent.com
  151.101.184.133    avatars7.githubusercontent.com
  151.101.184.133    avatars8.githubusercontent.com
  151.101.184.133    user-images.githubusercontent.com

**Comment by Anilople** [comment]
Maybe you can try follow steps:

1. Clear your portal database. Reinit it.
2. Simply use public config service, not yourself.
```properties
-Dapollo_profile=github,auth
-Ddev_meta=http://106.54.227.205:8080/
-Dserver.port=8070
-Dspring.datasource.url=jdbc:mysql://localhost:3306/ApolloPortalDB?characterEncoding=utf8
-Dspring.datasource.username=root
-Dspring.datasource.password=
```
database should change to yours
3. Restart portal by ide, use browser's Incognito mode to access it

**Comment by zyexplorer** [comment]
> Maybe you can try follow steps:
> 
> 1. Clear your portal database. Reinit it.
> 2. Simply use public config service, not yourself.
> 
> ```ini
> -Dapollo_profile=github,auth
> -Ddev_meta=http://106.54.227.205:8080/
> -Dserver.port=8070
> -Dspring.datasource.url=jdbc:mysql://localhost:3306/ApolloPortalDB?characterEncoding=utf8
> -Dspring.datasource.username=root
> -Dspring.datasource.password=
> ```
> 
> database should change to yours
> 3. Restart portal by ide, use browser's Incognito mode to access it

感谢耐心回复。
1.ApolloPortalDB数据库已删掉重新运行sql脚本初始化;
2.本地启动configservice和adminservice，portal连http://localhost:8080/启起来之后症状还是一样；
3.本地不启动configservice和adminservice，portal连http://106.54.227.205:8080/启起来之后症状还是一样；
下载源码本地运行达不到效果

**Comment by zyexplorer** [comment]
> Maybe you can try follow steps:
> 
> 1. Clear your portal database. Reinit it.
> 2. Simply use public config service, not yourself.
> 
> ```ini
> -Dapollo_profile=github,auth
> -Ddev_meta=http://106.54.227.205:8080/
> -Dserver.port=8070
> -Dspring.datasource.url=jdbc:mysql://localhost:3306/ApolloPortalDB?characterEncoding=utf8
> -Dspring.datasource.username=root
> -Dspring.datasource.password=
> ```
> 
> database should change to yours
> 3. Restart portal by ide, use browser's Incognito mode to access it

再次感谢热心回复。之前是从github上下载的是source源码包解压缩后导入IDEA的，然后配置一路正常，服务一路正常启动。整了两天，始终不行。刚刚直接从gitee上clone到IDEA，一样的方式，可以了，有登陆页面了。
