### ISSUE TITLE
Add more detail in development guide document

### ISSUE THREAD

**Issue by Anilople** [ctripcorp/apollo#3453]
Could add more detail in document [Apollo开发指南](https://ctripcorp.github.io/apollo/#/zh/development/apollo-development-guide) to guide newer to develop the project？

Some newers will stuck when they want to submit a pull request to apollo. 

The reason may be they don't know how to run apollo by own IDE.

Add more detail to development guide will give them great help.

**Comment by nobodyiam** [comment]
Is there any suggestion about what to add?

**Comment by Anilople** [comment]
### About config service

Guide developer how to check their config service health or not, through access some URI like http://106.54.227.205:8080/services/config

### About Portal

If someone just wanted to develop apollo-portal, can he/she use `-Dapollo.meta=http://106.54.227.205:8080`(address in Github README.md) directly?

Then developer don't need to start config service and admin service.
