### ISSUE TITLE
apollo configure环境复制批量修改数据库后批量发布问题

### ISSUE THREAD

**Issue by guohao9527** [ctripcorp/apollo#3454]
背景： 想复制一套新环境，涉及到多个应用，多个配置
操作： configure数据库复制了一份，然后修改了item表的mysql、redis等的配置。然后发现portal界面里面需要点击下发布，有什么方法能批量发布下哈或者什么更好的方法实现复制
说明：
1、看到open api可以实现接口发布，但是发现token得一个一个赋权，有点麻烦
2、直接修改release里面的内容，但是因为release太多10w+记录，要替换的地方又比较多，这个操作起来也有点麻烦
帮忙看看有什么好的办法哈

**Comment by nobodyiam** [comment]
目前能想到的就是通过 open api 发布配置，不过token确实需要一个一个授权，可以考虑写个 js 脚本，批量做一下授权？

**Comment by guohao9527** [comment]
> 目前能想到的就是通过 open api 发布配置，不过token确实需要一个一个授权，可以考虑写个 js 脚本，批量做一下授权？

谢谢哈
搞好忘记回复了，这边是找个普通token能读取到所有项目的cluster和namesapce，然后模拟用户登陆调用页面调试的发布接口进行发布，这样就不用token授权了。

**Comment by scottyungit** [comment]
> > 目前能想到的就是通过 open api 发布配置，不过token确实需要一个一个授权，可以考虑写个 js 脚本，批量做一下授权？
> 
> 谢谢哈 搞好忘记回复了，这边是找个普通token能读取到所有项目的cluster和namesapce，然后模拟用户登陆调用页面调试的发布接口进行发布，这样就不用token授权了。

你好 请问你是怎么模拟用户登录去发布的，我也不想去授权
