### ISSUE TITLE
nginx 代理8080服务后导致签名通不过

### ISSUE THREAD

**Issue by shenlanchenwei** [ctripcorp/apollo#3456]
- [ ] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) of this repository and believe that this is not a duplicate.

**Describe the bug**

**To Reproduce**
1. 通过Nginx代理API后，带签名的情况下无法通过验证，因为签名里加入了Url，这个签名策略能不能改一下

**Comment by shenlanchenwei** [comment]
#配置中心
location ^~/configCenter/
{
    proxy_pass http://192.168.10.161:8080/;
}

**Comment by shenlanchenwei** [comment]
我感觉签名部分，没有必要将域名部分也拿进去算，是不是只要保证参数一致就可以了

**Comment by nobodyiam** [comment]
签名考虑 path 应该也没啥大问题，不过目前再要改的话，就要考虑兼容性问题了。
另外，meta service 可以走 nginx，config service 由于有长连，不建议走 nginx
