### ISSUE TITLE
apollo-quick-start 的日志管理问题

### ISSUE THREAD

**Issue by diwenzheng** [ctripcorp/apollo#3457]
我们使用docker部署管理后,发现日志文件越来越多,导致硬盘容量越来越多.我现在的思路是按照quick-start介绍,修改apollo源码的配置,然后重新打包,发现日志配置无论我修改配置还是删除配置,日志永远管理不到,能不能提供一点帮助.

**Comment by diwenzheng** [comment]
@nobodyiam @yiming187 @ameizi 我尝试一直加入qq群,两三天了 似乎QQ群无人管理啊 困扰我几天了

**Comment by nobodyiam** [comment]
quick start 没有配置日志文件滚动，建议按照分布式部署文档来部署使用

**Comment by diwenzheng** [comment]
> quick start 没有配置日志文件滚动，建议按照分布式部署文档来部署使用

就是说 直接改源码配置,调整配置文件或者删除配置文件等,出的assemply的那个tar包更换至quick-start没用,这个是已知问题吗.

**Comment by diwenzheng** [comment]
> quick start 没有配置日志文件滚动，建议按照分布式部署文档来部署使用

你好,我刚才查阅了官方的分布式部署文档,似乎和quick-start无区别啊,区分的只有tar包,我看主分支的代码在logback的地方并没有配置这个压缩和删除功能。

**Comment by diwenzheng** [comment]
![image](https://user-images.githubusercontent.com/60613511/103203730-8abf9000-4930-11eb-9c38-a8d301eeb13f.png)

![image](https://user-images.githubusercontent.com/60613511/103203605-3caa8c80-4930-11eb-81fb-c21baae3d027.png)

![image](https://user-images.githubusercontent.com/60613511/103203562-27356280-4930-11eb-9b0a-9577524c24a3.png)
从这里看出 最大为10mb 不保存日志对吧  可是真正的目录里面确是 
![image](https://user-images.githubusercontent.com/60613511/103203749-96ab5200-4930-11eb-9468-cb17c58cc6da.png)

**Comment by diwenzheng** [comment]
@nobodyiam 我忽略了默认配置的地方,但是照目前情况来看 默认的似乎没用 我尝试按照back回滚的去重新出包 发现没用

**Comment by nobodyiam** [comment]
这个是在 application.properties 中配置的，按照 spring boot 的[说明](https://docs.spring.io/spring-boot/docs/2.1.2.RELEASE/reference/html/boot-features-logging.html#boot-features-custom-log-configuration)，是会滚动的

https://github.com/ctripcorp/apollo/blob/ad63e140afcf6bb0774f40a8fa3d3cc330c7439b/apollo-common/src/main/resources/application.properties#L19-L20

**Comment by diwenzheng** [comment]
我尝试一下,如果没问题,变关闭.

**Comment by diwenzheng** [comment]
亲测可用,还有一个问题,1.6.0-1.6.1的改动影响不大吧 或者博主是否能提供1.6.0的 apollo-build-script的包
