### ISSUE TITLE
如何多台机器进行分布式部署？

### ISSUE THREAD

**Issue by KevinShinn** [ctripcorp/apollo#3459]
看了一下文档还是感觉不是很清晰。假如我有10.0.0.1，10.0.0.2，10.0.0.3，10.0.0.4，四台机器，其中10.0.0.1，10.0.0.2，10.0.0.3三台机器，每台都部署一份apollo-adminservice和 apollo-configservice， 然后将三台机器的8080挂在一个负载均衡vip，10.0.0.4 部署apollo-portal，将meta地址指向vip， 这样可以吗？

**Comment by nobodyiam** [comment]
可以
