### ISSUE TITLE
通过程序触发阿波罗更新事件

### ISSUE THREAD

**Issue by mrtylerzhou** [ctripcorp/apollo#3460]
目前有一个web项目，其中配置主要基于于阿波罗，同时有一部分配置通过web界面可以修改，修改以后入库，同时更改zkserver数据，web项目里zkclient订阅更新事件，每当数据更新以后重新查询一次数据库把结果缓存到缓存对象里。这一部分配置之所以没有使用阿波罗一方面是因为配置数据是因为很多网点都可以有通过web界面修改配置的权限（通过管理员分配即可），并且这部分数据要入库做审计。

目前的架构中zk仅仅做事件发布和订阅事件使用，增加了项目不必要的复杂度，项目中已经使用了阿波罗，现想把阿波罗这一层去掉，想请问一下阿波罗能不能通过程序触发一次配置更新事件？（目前项目中已使用了@ApolloConfigChangeListener对更新事件做一些修改化处理，但是都是通过web界面手工修改配置触发的更新事件，如何通过接口的形式触发一次更新事件）

**Comment by nobodyiam** [comment]
不建议把 apollo 用做一个通知的程序，这个场景消息队列应该是更合适的。
如果通知频次很低的话，通过 apollo 也是能实现的，比如加入一个配置项存储数据版本或时间戳，每次数据库更新后通过 OpenApi 修改该配置项的值

**Comment by mrtylerzhou** [comment]
> 
> 
> 不建议把 apollo 用做一个通知的程序，这个场景消息队列应该是更合适的。
> 如果通知频次很低的话，通过 apollo 也是能实现的，比如加入一个配置项存储数据版本或时间戳，每次数据库更新后通过 OpenApi 修改该配置项的值

非常感谢，其实这些配置修改频率比较低，但是仍然不能保证不会修改（快递公司修改权限开放给了所有的网点），这一个简单场景使用消息队列引入了不必要的复杂度。我找一下关于openapi的资料看一下
