### ISSUE TITLE
Jpa执行MySQL特殊表和特殊字段的问题

### ISSUE THREAD

**Issue by dsfsfs** [ctripcorp/apollo#3466]
我的mysql 版本是 5.6.23，项目版本1.7.1

jpa查询Release表时，报错。还有插入表Item时，有关键字Key字段，也同样报错。

经查，得在对应实体中用 "[]"来设置表名和字段名。但这样要改源码才不会出错，这个是因为我的mysql版本低吗？

**Comment by nobodyiam** [comment]
这个在项目中已经配置过了

https://github.com/ctripcorp/apollo/blob/ad63e140afcf6bb0774f40a8fa3d3cc330c7439b/apollo-common/src/main/resources/application.properties#L9-L10
