### ISSUE TITLE
请问如何优先加载本地配置？

### ISSUE THREAD

**Issue by kscMaster** [ctripcorp/apollo#3469]
环境：我司使用Apollo搭建，线上、公司局域网测试环境、开发这三种。开发使用的是Windwos+测试环境，线上和测试环境使用Linux部署。

问题：Windows和Linux的路径不同，application里配置了一个文件路径，本机使用Windows的IDEA跑项目，测试环境Linux同样配置文件路径，但是路径不一样。现在本机的项目跑起来，会优先加载Apollo dev上的配置，这样读取的路径就是Linux的路径，因此在Windows上找不到该路径，接口就会报错了，请问怎么解决这个问题呢？
我想知道是否有优先加载本机配置的方法，或者针对我这样的问题该如何解决？

**Comment by nobodyiam** [comment]
参考下 #1560
