### ISSUE TITLE
第三方应用接入，授予权限支持批量操作吗？

### ISSUE THREAD

**Issue by brzyangg** [ctripcorp/apollo#3474]
**你的特性请求和某个问题有关吗？请描述**

使用第三方应用，以OpenAPI的方式接入apollo时，我想操作一大部分AppID，赋权支持批量操作吗？
如下图：（被管理的appId那里）
![image](https://user-images.githubusercontent.com/29059790/103599869-12188f00-4f41-11eb-81bf-3f46371a80ff.png)

**清晰简洁地描述一下你希望的解决方案**
我希望可以支持通配符，或者批量操作

**清晰简洁地描述一下这个特性的备选方案**
备选方案目前看来只能手动添加

**其它背景**

在这里添加和这个特性请求有关的背景说明、截图

**Comment by Anilople** [comment]
Duplicate of #3191

**Comment by wangycc** [comment]
+1

**Comment by blackysy** [comment]
+1

**Comment by citycan1991** [comment]
+1， 用于CI/CD及devops相关自动化里面很不方便

**Comment by No-SilverBullet** [comment]
https://github.com/No-SilverBullet/apollo-token-batcher 可以参考这个项目，能对openapi token批量授予应用的权限
