### ISSUE TITLE
apollo使用proxy代理主备的逻辑

### ISSUE THREAD

**Issue by diwenzheng** [ctripcorp/apollo#3475]
没按照文档做的分布式方案去执行,我们是使用nginx保证session一致性,并设置主备的逻辑,没有负载均衡的能力,只是单纯的主备.在我们服务启动的时候,如果proxy坏了,就会导致我们的服务启动不了,这个什么原因.我们的部署方案使用docker swarm的方式部署,nginx配置的 apollo-m 以及apollo-s的docker内置域名的方式.

**Comment by diwenzheng** [comment]
@nobodyiam

**Comment by diwenzheng** [comment]
我们本地启动服务如果没有apollo,就会自启动完成,但是加上proxy就会启动失败一直卡着.

**Comment by diwenzheng** [comment]
![image](https://user-images.githubusercontent.com/60613511/103623574-3db46d00-4f73-11eb-9e3d-f1094c749cf5.png)
以上为nginx节点,因为配置的是apollo-m的域名,那么也就是当apollo-m服务没启动,nginx也启动不成功,这时候我们发现服务会一直卡住。错误信息稍后我在提供。

**Comment by diwenzheng** [comment]
2021-01-05 16:33:37.330 - [WARN] - [main] - [c.c.f.a.i.LocalFileConfigRepository] - [LocalFileConfigRepository.java:167] - Sync config from upstream repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository failed, reason: Get config services failed from http://proxy-internal:8080/services/config?appId=ecs_01&ip=10.0.1.221 [Cause: Could not complete get operation [Cause: proxy-internal]]

**Comment by diwenzheng** [comment]
![image](https://user-images.githubusercontent.com/60613511/103624043-f11d6180-4f73-11eb-8929-30f4ce373e40.png)
我在本地不使用proxy节点的时候,发现可以启动成功显示的错误是 
![Uploading image.png…]()

**Comment by diwenzheng** [comment]
ps 如何让apollo不在打印 sync config fail 以及 重试啊

**Comment by nobodyiam** [comment]
看上去还是配置有问题吧，你访问下 http://proxy-internal:8080/services/config 看看

**Comment by diwenzheng** [comment]
> http://proxy-internal:8080/services/config
![image](https://user-images.githubusercontent.com/60613511/103723239-9126c980-500c-11eb-86e7-cf633eae0fda.png)

我的意思是当我们的集群产生片面性宕机的时候,nginx启动不成功会不会导致应用服务依赖apollo的启动不成功,可否关闭上面日志中的retry这些看着很闹心,我突然想到我们针对应用服务有一个健康检查当服务三分钟内启动不成功就会杀掉进程重新启动,正在考虑是否是因为这种原因,导致服务卡住启动不成功.

**Comment by nobodyiam** [comment]
可用性部分可以参考[四、可用性考虑](http://ctripcorp.github.io/apollo/#/zh/design/apollo-design?id=%e5%9b%9b%e3%80%81%e5%8f%af%e7%94%a8%e6%80%a7%e8%80%83%e8%99%91)，目前无法关闭 retry 日志，如果启动时 config service 不可用会增加启动时间（重试 + 超时），取决于所加载的 Namespace 个数

**Comment by diwenzheng** [comment]
> 可用性部分可以参考[四、可用性考虑](http://ctripcorp.github.io/apollo/#/zh/design/apollo-design?id=%e5%9b%9b%e3%80%81%e5%8f%af%e7%94%a8%e6%80%a7%e8%80%83%e8%99%91)，目前无法关闭 retry 日志，如果启动时 config service 不可用会增加启动时间（重试 + 超时），取决于所加载的 Namespace 个数

那可否降低重试的次数和设置超时时间?

**Comment by nobodyiam** [comment]
超时时间是可以配置的，重试次数可以提交个 PR 改成可配的

https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/util/ConfigUtil.java
