### ISSUE TITLE
麻烦问一下集群这个维度 设计之初为什么要叫做“集群”呢？ 这里的“集群”感觉与我们平时认知中的集群不太相同

### ISSUE THREAD

**Issue by lyj-stack** [ctripcorp/apollo#3476]

**Comment by nobodyiam** [comment]
[三、集群独立配置说明](http://ctripcorp.github.io/apollo/#/zh/usage/apollo-user-guide?id=%e4%b8%89%e3%80%81%e9%9b%86%e7%be%a4%e7%8b%ac%e7%ab%8b%e9%85%8d%e7%bd%ae%e8%af%b4%e6%98%8e)

说说哪里不太相同？
