### ISSUE TITLE
使用基于Kubernetes原生服务发现，apollo1.7.1，本地开发环境不能连接上apollo

### ISSUE THREAD

**Issue by xqhmz** [ctripcorp/apollo#3480]
WARN 8716 --- [ngPollService-1] c.c.f.a.i.RemoteConfigLongPollService    : Long polling failed, will retry in 2 seconds. appId: test1, cluster: default, namespaces: application, long polling url: http://apollo-service-dev-apollo-configservice.apollo:8080/notifications/v2?cluster=default&appId=test1&ip=192.168.1.111&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A-1%7D%5D, reason: Could not complete get operation [Cause: apollo-service-dev-apollo-configservice.apollo]
app:
  id: test1
apollo:
  meta: http:ip:30080/ 使用的是configservice的nodeport 

[
  {
    "appName": "apollo-configservice",
    "instanceId": "apollo-configservice:http://apollo-service-dev-apollo-configservice.apollo:8080",
    "homepageUrl": "http://apollo-service-dev-apollo-configservice.apollo:8080"
  },
  {
    "appName": "apollo-adminservice",
    "instanceId": "apollo-adminservice:http://apollo-service-dev-apollo-adminservice.apollo:8090",
    "homepageUrl": "http://apollo-service-dev-apollo-adminservice.apollo:8090"
  }
]

应该如何连接呢

**Comment by nobodyiam** [comment]
两种方式：
1. 参考[2.4.1.3.4.4 指定Meta Server返回的apollo-configservice地址](https://ctripcorp.github.io/apollo/#/zh/deployment/distributed-deployment-guide?id=_241344-%e6%8c%87%e5%ae%9ameta-server%e8%bf%94%e5%9b%9e%e7%9a%84apollo-configservice%e5%9c%b0%e5%9d%80)
2. 参考[1.2.2.2 跳过Apollo Meta Server服务发现](https://ctripcorp.github.io/apollo/#/zh/usage/java-sdk-user-guide?id=_1222-%e8%b7%b3%e8%bf%87apollo-meta-server%e6%9c%8d%e5%8a%a1%e5%8f%91%e7%8e%b0)

**Comment by xqhmz** [comment]
好的 谢谢，解决了
