### ISSUE TITLE
apollo前端用户密码和后端进行校验的逻辑代码在哪？apollo1.2版本存在用户密码明文传输的问题

### ISSUE THREAD

**Issue by RobinzhangPRO** [ctripcorp/apollo#3482]
apollo前端用户密码和后端进行校验的逻辑代码在哪？apollo1.2版本存在用户密码明文传输的问题，需要在用户密码校验这段逻辑加上明文加密功能。

**Comment by nobodyiam** [comment]
默认是 spring security 认证
https://github.com/ctripcorp/apollo/blob/41519f41fa390404c10d48a85e42de135f140aa2/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/configuration/AuthConfiguration.java#L230
