### ISSUE TITLE
应用管理员在web管理页面提示仍需要授权

### ISSUE THREAD

**Issue by pucheng83** [ctripcorp/apollo#3483]
部署的版本是1.7.1。

用户已经是项目负责人，但仍然无法添加和发布配置。

<img width="1264" alt="WX20210108-110719@2x" src="https://user-images.githubusercontent.com/12379685/103970108-6ff7e180-51a2-11eb-9a81-0763cb603fe9.png">

**Comment by nobodyiam** [comment]
配置权限是基于 Namespace 级别的，之前的设计理念是项目管理员不一定需要对项目中的每个 namespace 都进行配置管理操作
