### ISSUE TITLE
通过helm工具在k8s环境部署apollo-portal报错

### ISSUE THREAD

**Issue by biwenKey** [ctripcorp/apollo#3484]
我通过helm工具在部署apollo-portal有如下报错：
![image](https://user-images.githubusercontent.com/27846351/103970260-c533f300-51a2-11eb-8788-5d9db7c89f33.png)

以下是我在values.yaml文件中关于hosts相关的配置：
![image](https://user-images.githubusercontent.com/27846351/103970346-00362680-51a3-11eb-9679-e1c57a4408bb.png)

请问该报错如何解决？

**Comment by nobodyiam** [comment]
你开启了 tls，所以在 tls 下需要配置 hosts 和 secretName 等属性
