### ISSUE TITLE
是否能考虑一下升级依赖的 spring-boot 版本？

### ISSUE THREAD

**Issue by vdisk-group** [ctripcorp/apollo#3485]
我尝试着给 apollo-portal 添加 oauth2 登录功能，但是发现 apollo 使用的 spring-boot 版本太低了，没有 spring-boot-starter-oauth2-client 这个依赖。  
现在 spring-boot 2.1.x 都已经停止维护了，apollo 却还在用 2.0.5，是不是可以考虑升级一下依赖的 spring-boot 的版本呢？

**Comment by nobodyiam** [comment]
可以考虑升级一下
