### ISSUE TITLE
文档无法展示图片，影响阅读和理解

### ISSUE THREAD

**Issue by 1156721874** [ctripcorp/apollo#3487]
https://ctripcorp.github.io/apollo/#/zh/design/apollo-introduction?id=_32-%e7%95%8c%e9%9d%a2%e6%a6%82%e8%a7%88 文档无法展示图片，请开发团队，解决一下，图片展示不出来，影响阅读和理解。

**Comment by Anilople** [comment]
Reference https://github.com/ctripcorp/apollo/issues/3449#issuecomment-750125058

Image resource under domain https://raw.githubusercontent.com
