### ISSUE TITLE
多因子身份验证

### ISSUE THREAD

**Issue by Restlol** [ctripcorp/apollo#3490]
对于用户的安全性校验，MFA 有计划作为特性加入么请问

**Comment by nobodyiam** [comment]
可以接入企业内部的 SSO 系统，这样可以复用企业已有的各种身份认证手段，包括 MFA

**Comment by Restlol** [comment]
> 可以接入企业内部的 SSO 系统，这样可以复用企业已有的各种身份认证手段，包括 MFA

请问有相关教程或者切入点么

**Comment by nobodyiam** [comment]
[Portal实现用户登录功能](http://ctripcorp.github.io/apollo/#/zh/development/portal-how-to-implement-user-login-function)
