### ISSUE TITLE
配置中心配置的yml 内容，程序读取的时候如何保证顺序呢？

### ISSUE THREAD

**Issue by honestAnt** [ctripcorp/apollo#3493]
**你的特性请求和某个问题有关吗？请描述**
如果保证配置中心配置的 yml中的内容顺序 和 程序运行时 读取的是一致的呢？
清晰简洁地描述这个问题是什么。即，当碰到xxx时，总是感觉很麻烦
zuul进行路由的时候，如果配置了多个规则，会有顺序问题？

**清晰简洁地描述一下你希望的解决方案**
是否能支持配置中心的内容 在解析的时候也是按照顺序的呢？

**清晰简洁地描述一下这个特性的备选方案**

**其它背景**

在这里添加和这个特性请求有关的背景说明、截图

eg:
zuul:
  routes:
    xxx-1:
      path: /xxx/test/xx1
      url: http://xxxhost/test
      serviceId: xx1
    xxx-2:
      path: /xxx/**
      url: http://xxxhost/test2
      serviceId: xx2

如果xxx-2的规则跑到上面了，路由会优先这个，就会不符合预期！

**Comment by nobodyiam** [comment]
[1.2.4.3 设置内存中的配置项是否保持和页面上的顺序一致](https://ctripcorp.github.io/apollo/#/zh/usage/java-sdk-user-guide?id=_1243-%e8%ae%be%e7%bd%ae%e5%86%85%e5%ad%98%e4%b8%ad%e7%9a%84%e9%85%8d%e7%bd%ae%e9%a1%b9%e6%98%af%e5%90%a6%e4%bf%9d%e6%8c%81%e5%92%8c%e9%a1%b5%e9%9d%a2%e4%b8%8a%e7%9a%84%e9%a1%ba%e5%ba%8f%e4%b8%80%e8%87%b4)

**Comment by honestAnt** [comment]
> [1.2.4.3 设置内存中的配置项是否保持和页面上的顺序一致](https://ctripcorp.github.io/apollo/#/zh/usage/java-sdk-user-guide?id=_1243-%e8%ae%be%e7%bd%ae%e5%86%85%e5%ad%98%e4%b8%ad%e7%9a%84%e9%85%8d%e7%bd%ae%e9%a1%b9%e6%98%af%e5%90%a6%e4%bf%9d%e6%8c%81%e5%92%8c%e9%a1%b5%e9%9d%a2%e4%b8%8a%e7%9a%84%e9%a1%ba%e5%ba%8f%e4%b8%80%e8%87%b4)

收到，谢谢宋哥哈
