### ISSUE TITLE
当apollo服务端宕机后，不影响应用正常使用

### ISSUE THREAD

**Issue by walt-liuzw** [ctripcorp/apollo#3494]
**你的特性请求和某个问题有关吗？请描述**
我们公司的apollo支持很多业务使用，有个业务访问量太大，数据量也大，导致server 宕机
这样全公司的net java服务都出错了，影响太大了

**清晰简洁地描述一下你希望的解决方案**
希望当server宕机后，因为服务器下载了服务端缓存（放在opt文件夹下的），这样可以优先使用本地的缓存运行，仅当服务端跟客户端通信连接正常
才进行更新本地缓存的操作

**Comment by nobodyiam** [comment]
目前就是这么实现的，详见[四、可用性考虑](http://ctripcorp.github.io/apollo/#/zh/design/apollo-design?id=%e5%9b%9b%e3%80%81%e5%8f%af%e7%94%a8%e6%80%a7%e8%80%83%e8%99%91)

**Comment by walt-liuzw** [comment]
> 目前就是这么实现的，详见[四、可用性考虑](http://ctripcorp.github.io/apollo/#/zh/design/apollo-design?id=%e5%9b%9b%e3%80%81%e5%8f%af%e7%94%a8%e6%80%a7%e8%80%83%e8%99%91)

但是我们实际使用过程中，发现apollo宕机后，应用就是全部挂了呢

**Comment by nobodyiam** [comment]
看一下应用的启动日志吧，里面应该有 apollo 加载本地配置的一些信息

**Comment by Arthur-X-Wang** [comment]
另一种异常情景：
在容器部署场景下，即微服务重启、扩容等操作时，Apollo 集群不可达，业务容器拉取不到配置，本地也没有任何缓存配置。此时，业务容器会因缺少配置启动不起来。

假设正好某个情境下，业务容器大批量崩溃，Apollo也同时崩溃且段时间不可恢复，原本业务容器可以通过扩容使服务恢复，此时也完成不了这个，异常影响较大。

对于此种方案，我们考虑过本地默认配置，但是由于Apollo配置更新多次后，本地默认配置过于老旧。比如开关类的，这样更加不可控。

对于此种异常情景，Apollo是否有高可用设计？
