### ISSUE TITLE
openapi 调用修改配置接口修改json类型数据时，Comment丢失

### ISSUE THREAD

**Issue by zzxiagz** [ctripcorp/apollo#3497]
- [* ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [* ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [*  ] 我已经仔细检查过[FAQ](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**描述bug**

openapi 调用修改配置接口修改json类型数据时，Comment丢失

**复现**

通过如下步骤可以复现：

1. openapi 调用 items 接口更新json格式数据。
2. 附加Comment字段
3. 调用 namespaces 拉取更改更新的数据。

**期望**

期望namespaces 接口拉取的最新数据有Comment。

实际Comment是空的。

- 版本：jave-1.7.0
- 错误日志
- 配置：
- 平台和操作系统 linux

**Comment by nobodyiam** [comment]
我在 demo 站点 http://106.54.227.205/ 上试了一下，没有重现该问题，建议详细描述下重现步骤吧
