### ISSUE TITLE
请问，如何监听多个cluster

### ISSUE THREAD

**Issue by Cishangliang** [ctripcorp/apollo#3502]
请问，如何通过client监听多个cluster

**Comment by nobodyiam** [comment]
cluster 属于环境信息，一般情况下一个 client 应该只有一个 cluster 信息，在什么情况下需要监听多个 cluster 的配置？

**Comment by PaulYuanJ** [comment]
我现在通过mysql的长连接，监控Release这个表的主键id，来判断是否有更新，任何更新都可以发现，并推送到指定的webhook。
https://github.com/PaulYuanJ/python_notes/blob/main/mysql/apollo-mysql-pandas.py
