### ISSUE TITLE
目前是否有返回客户端执行状态的功能？如果有方便告知如何操作吗，或者是否可以增加

### ISSUE THREAD

**Issue by wuqiang3424** [ctripcorp/apollo#3508]
想法：

目前的模式是推送后，配置同步
至于是否同步成功，这个没有状态，不过可以从实力列表中可以查看到已经同步成功的节点

现在是想增加一个配置同步成功后，自动重启服务的功能，这个自动重启可以写入到客户端当中，等同步成功后自动重启，可是重启结果无法返回到Apollo配置中心中，比如nginx服务，同步后我可以自动检测配置情况，如果配置正确，可以返回一个正确结果到apollo配置中心中，这样就可以很方便的操作完毕了。

**Comment by nisiyong** [comment]
> 现在是想增加一个配置同步成功后，自动重启服务的功能

自动重启进程？

**Comment by wuqiang3424** [comment]
自动重启进程 我觉得可以加到客户端里面。

只是自动重启后，如果可以在apollo的发布界面有个返回状态就好了，比如重启成功或者失败的提示，而无需登录到后端节点上进行查看。

**Comment by nisiyong** [comment]
jvm进程不能自己重启自身，需要借用外部的的发布系统来控制

**Comment by wuqiang3424** [comment]
不是要重启自身，是重启其他的服务，比如tomcat、nginx等的服务，nginx这些重启后的状态结果返回到apollo发布平台

**Comment by nobodyiam** [comment]
建议在 apollo 上层来实现这个逻辑吧，比如有个管控系统先调用 apollo open api 推送配置，然后再收集 nginx 重启的情况并展示该次操作的状态。
apollo 作为基础服务还是应该尽量保持纯粹。

**Comment by wuqiang3424** [comment]
明白了，谢谢
