### ISSUE TITLE
为什么apollo那么吃内存，竟然吃掉3G内存。怎么解决

### ISSUE THREAD

**Issue by PonyoLoveCode** [ctripcorp/apollo#3509]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**描述bug**

简洁明了地描述一下bug

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nisiyong** [comment]
请提供相关数据支持

**Comment by wyz629871** [comment]
![image](https://user-images.githubusercontent.com/31715900/105936847-5fdf6d80-608f-11eb-9618-c690114700f0.png)

**Comment by wyz629871** [comment]
我也没搞什么分布式，我就是快速安装尝试用一下，但是这个安装完内存20%就没了

**Comment by wyz629871** [comment]
> 请提供相关数据支持
![image](https://user-images.githubusercontent.com/31715900/105937241-1e9b8d80-6090-11eb-8346-e84ee1426caf.png)
我就是快速安装试用一下，但是这个安装完成，直接20%内存没有了，是我安装需要设置什么，还是本身就是这样

**Comment by wyz629871** [comment]
![image](https://user-images.githubusercontent.com/31715900/105937909-6ec71f80-6091-11eb-873e-16fdafddc0a8.png)

kube-apiserver 管理整个生命周期也就是3.3，那么请问apollo内存耗在哪了？？？

**Comment by nisiyong** [comment]
@wyz629871 
默认脚本应该没有加`-Xms`和`-Xmx`，你加上去看看

**Comment by wyz629871** [comment]
> @wyz629871
> 默认脚本应该没有加`-Xms`和`-Xmx`，你加上去看看
我限制资源肯定是可以的，我想知道他内存花在哪了，java写得堆不是gc回收吗，栈内存程序运行完就释放。我现在是新安装一套再无任何访问的情况下就占了3G内存。

**Comment by nobodyiam** [comment]
java 的堆一旦占了内存是不会释放回系统的，gc 回收指得是在堆内回收，下次可以直接在堆内继续分配。
可以用 [jmap](https://docs.oracle.com/javase/7/docs/technotes/tools/share/jmap.html) 和 [MAT](https://www.eclipse.org/mat/) 看下具体的内存使用情况
