### ISSUE TITLE
针对release接口的一些问题

### ISSUE THREAD

**Issue by andyyumiao** [ctripcorp/apollo#3512]
针对release接口：@PostMapping("/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/releases")
其中的关键代码有：

Release release = releaseService.publish(namespace, releaseName, releaseComment, operator, isEmergencyPublish);
...
...
messageSender.sendMessage(ReleaseMessageKeyGenerator.generate(appId, messageCluster, namespaceName),
                  Topics.APOLLO_RELEASE_TOPIC);

请问：上面publish方法和sendMessage方法的作用分别是什么？哪个方法会触发通知客户端的呢？

**Comment by nisiyong** [comment]
客户端被通知到是采用的是`长轮训`的设计，你可以了解下此类`com.ctrip.framework.apollo.configservice.controller.NotificationControllerV2`

**Comment by andyyumiao** [comment]
> 客户端被通知到是采用的是`长轮训`的设计，你可以了解下此类`com.ctrip.framework.apollo.configservice.controller.NotificationControllerV2`

长轮训的设计我了解，我想问的是，publish和sendMessage方法，这两个方法哪个是触发的前置条件？这个在源码里没有找到明确的逻辑

**Comment by nisiyong** [comment]
release发布后表里有多一条数据，`ReleaseMessageScanner`会扫描新增的release后触发监听者。
具体你看下：
- com.ctrip.framework.apollo.configservice.controller.NotificationControllerV2#handleMessage
- com.ctrip.framework.apollo.biz.message.ReleaseMessageScanner#fireMessageScanned

**Comment by andyyumiao** [comment]
> * handleMessage
我注意到有个releasemessage表，ReleaseMessageScanner扫描的貌似是这张表，如果不执行sendMessage，是不是就不会触发监听？

**Comment by andyyumiao** [comment]
> > * handleMessage
> >   我注意到有个releasemessage表，ReleaseMessageScanner扫描的貌似是这张表，如果不执行sendMessage，是不是就不会触发监听？

我注意到有个releasemessage表，ReleaseMessageScanner扫描的貌似是这张表，如果不执行sendMessage，是不是就不会触发监听？

**Comment by andyyumiao** [comment]
> release发布后表里有多一条数据，`ReleaseMessageScanner`会扫描新增的release后触发监听者。
> 具体你看下：
> 
> * com.ctrip.framework.apollo.configservice.controller.NotificationControllerV2#handleMessage
> * com.ctrip.framework.apollo.biz.message.ReleaseMessageScanner#fireMessageScanned

我注意到有个releasemessage表，ReleaseMessageScanner扫描的貌似是这张表，如果不执行sendMessage，是不是就不会触发监听？

**Comment by nobodyiam** [comment]
> > release发布后表里有多一条数据，`ReleaseMessageScanner`会扫描新增的release后触发监听者。
> > 具体你看下：
> > 
> > * com.ctrip.framework.apollo.configservice.controller.NotificationControllerV2#handleMessage
> > * com.ctrip.framework.apollo.biz.message.ReleaseMessageScanner#fireMessageScanned
> 
> 我注意到有个releasemessage表，ReleaseMessageScanner扫描的貌似是这张表，如果不执行sendMessage，是不是就不会触发客户端通知？

按设计是这样
