### ISSUE TITLE
部署混乱是否意味着代码混乱？

### ISSUE THREAD

**Issue by huaqiangshishuaige** [ctripcorp/apollo#3513]
1、第一次在github上提issues,因为想不通这么多star的产品在我看设计得如此不堪！
2、想一想这个apolo也许符合中国软件行业的现状，领导看PPT，下面的程序员杂乱无章的开发！
3、说几个实际的问题：
3.1、为什么部署分quick-start版本和源码版本编译版本，你们自己都知道部署麻烦了，为什么不从根本下手简化部署反而自己搞了个基本无法生产使用的quick-start版本！
3.2、即使是源码版，在真实的使用中，注册中心肯定得用自己搭建的，而你们的源码直接把EurekaServer封装到config里面了。。。这是应届生都知道的你直接单独搞个模板负责EurekaServer不就行了吗！
-------
题外话：大厂难进，但大厂的程序员都是螺丝钉。。。这句话貌似有道理

**Comment by klboke** [comment]
看不下去了，来怼一下，我刚接触 apollo 的时候，和你的感觉是类似的，那是因为没花任何时间成本去了解这个开源项目，像这种人不配用开源项目，花钱用商业服务最适合，点两下按钮就可以用了。分一个一键部署版本也是充分考虑到一大波白嫖党实在无法入手才搞的，就像 skywalking 一样，下载安装包一键启动就可以用了，但是这样部署能上生产么？？？其他的也不想多解释了，对一个先入为主的瞎BB人来说，解释在多都是无用，直接劝退

**Comment by huaqiangshishuaige** [comment]
你这个回复的时间点真好！ 我刚改了源代码部署好。。随便反怼一下，没有对比就没有伤害，一直用nacos的我就是不习惯。nacos看五分钟明白了，然后花个一个小时基本能部署好。这个apollo,要不是领导强制要用，好家伙我早已经放弃了！最后纠正你一个观点，好东西就是好东西，设计得不行的东西就是不行！虽然是开源，但是不配拥有这么多star,还懂这个意思？

**Comment by klboke** [comment]
恰好大多数人能分辨好项目。能凭简单部署就判断一个项目是好的设计好的项目，直接劝退

**Comment by huaqiangshishuaige** [comment]
哎呀呀 说两点很重要的东西吧小伙儿
1、虽然是开源，但是个人开源和企业级的开源不是一个概念。这个apollo要是你开发出来的，我肯定说牛逼。但是企业开源就是大家来看这个企业软实力的时候了，国内做得最成功的就是阿里，虽然开源一堆东西不收费，但是附加的价值就在于把很多程序员和小企业往阿里云这个平台引入。
2、作为程序员，不要动不动就说源码底层架构。你有自己独立开发的产品或框架，这叫牛逼，否则在我这里就是装逼。。

**Comment by JaredTan95** [comment]
很高兴你能够花时间提出这么你的内心想法，说明 Apollo 对你或公司还是有价值的。存在即合理。
对 Apollo 的接触时间稍微长一点或者对设计文档多一些了解的人才能知道为何这样设计以及为什么这么多公司在使用。
针对你提出的 Quick-Start 问题，如果你有更好的意见，社区很欢迎大家参与贡献一起完善它。

**Comment by nobodyiam** [comment]
@huaqiangshishuaige 

非常抱歉给你带来了不好的体验，对于部署模型和对外依赖这些方面，其实 apollo 在设计之初是有过一些思考的：

* 环境隔离
    * 在部署模型上首先考虑的需求点是环境隔离，一方面是因为大部分公司的测试和生产环境都是网络隔离的，另一方面是不希望某个环境出现问题继而影响到其它环境（例如某个环境的 client 出问题，把 config service 打挂了），所以 service 和其对应的 db 就设计为在每个环境独立部署一套
    * 至于 service 为啥分成了 config service 和 admin service 两个，主要的考虑点是它俩的职责不太一样，一个是为 client 提供配置的读取服务，另一个是为 portal 提供配置的管控服务，两者的关注点不同，容量、可用性等方面也有不一样的特征
* 统一管控
    * 在部署模型上另一个考虑的需求点是统一管控，虽然 service 层独立部署了，但是我们不希望对用户的体验是割裂的，所以需要有一个统一的管控视图，并且要能实现跨环境的数据同步等，从而简化用户的使用
    * 不过统一管控遇到的一个直观问题就是 portal 如何能访问到各个环境的 service，这里确实对运维是提出了一定要求的。在 ctrip 的实现是在生产环境单独开辟了一个工具区（Tooling Zone）并且配置了特殊的防火墙规则，从而工具区的应用可以单向访问到其它所有环境的服务，所有管控类服务都会部署在这个区。
* 最小化对外依赖
    * 配置中心作为基础服务，所以对外部依赖需要尽可能地少，那为啥 apollo 不依赖外部的注册中心呢？这个主要还是看对  apollo 的定位，我们在设计伊始对 apollo 的定位是最底层的基础服务，包括注册中心也是 apollo 的使用者，所以默认的实现是把 Eureka 内置了。不过这个在不同的公司确实会有不同的定位，所以其实 apollo 也是支持使用外部注册中心的，可以参考[将Config Service和Admin Service注册到单独的Eureka Server上](http://ctripcorp.github.io/apollo/#/zh/faq/common-issues-in-deployment-and-development-phase?id=_8-%e5%b0%86config-service%e5%92%8cadmin-service%e6%b3%a8%e5%86%8c%e5%88%b0%e5%8d%95%e7%8b%ac%e7%9a%84eureka-server%e4%b8%8a)

结合以上这些原因，所以 quick start 的定位就比较清晰了，正如 quick start 文档中所说的：
> 为了让大家更快的上手了解Apollo配置中心，我们这里准备了一个Quick Start，能够在几分钟内在本地环境部署、启动Apollo配置中心。
> 不过这里需要注意的是，Quick Start只针对本地测试使用，如果要部署到生产环境，还请另行参考分布式部署指南。

不过 apollo 的分布式部署确实是有些复杂的，一方面是上述提到的环境隔离等因素，另一方面是工具化方面做得还不够自动化，这方面我们也在逐步改进中，比如除了源码构建外，现在也提供了[直接下载包](http://ctripcorp.github.io/apollo/#/zh/deployment/distributed-deployment-guide?id=_2211-%e7%9b%b4%e6%8e%a5%e4%b8%8b%e8%bd%bd%e5%ae%89%e8%a3%85%e5%8c%85)的方式，除了包部署外，还支持了[Docker部署](http://ctripcorp.github.io/apollo/#/zh/deployment/distributed-deployment-guide?id=_23-docker%e9%83%a8%e7%bd%b2)和[Helm Chart部署](http://ctripcorp.github.io/apollo/#/zh/deployment/distributed-deployment-guide?id=_24-kubernetes%e9%83%a8%e7%bd%b2)等方式。

最后，话说回来，我们都知道没有完美的架构，所谓的架构/设计都是基于特定的场景之下的，所以一定有其局限性。不过作为技术人员，肯定还是希望往更通用、更普适的方向演进，这也正是开源的魅力，通过开源，一方面能让更多的公司受益，另一方面也能通过社区接触到更多的场景，所以也欢迎大家一起在社区中讨论，提出建设性的意见~

**Comment by huaqiangshishuaige** [comment]
好的！ 随便吐槽一下换来这么专业的回答 值了！目前我已经知道怎么生产部署了，但无论咋的都得改源码。今天就不好意思吐槽了，针对部署来几个建议吧。
   一、部署没有那么难，只是你们写得难
       在源码里，build.bat能很方便的构建三个部署包，我们需要做的就是把admin和config中的@EnableEurekaServer改成@EnableEurekaClient，以及这两个项目中的bootstrap.yml中的Eureka连接地址改成自己的就行了。当前，config数据库里面的注册中心地址也改了，但是目前还没看表中的注册中心地址在哪儿用到。您们的官方文档，花了大量篇幅介绍Quick Start和Mysql如何导入。这个真的没必要，我和朋友的一句玩笑话是Apollo的部署手册就是小几万字的言情小说！

    二、建议去除Quick Start那个Demo包
        我的崩溃就是从Quick Start开始的，搭建一套环境，发现他内部已经集成了Eureka，这直接导致不能在真实的环境里跑。我这白花半个小时时间只为了证明Apollo是可演示的?

**Comment by nisiyong** [comment]
@huaqiangshishuaige 
从你的标题和加粗加大字体确实可以感受到你对Apollo不满的情绪，但是做技术不要这么浮躁。先了解是什么，再提问为什么。
每个产品都有自己的使用场景，单纯与nacos做部署难易的比较是没有意义的，因为他们的设计初衷与架构也是不相同的。

**你可以理解开源是免费的，但不能认为社区要对你做无条件的支持或负责！**

开源项目需要你的发声，更需要你深入了解项目并为其提供更好的建议。开源项目欢迎所有帮助项目与社区发展的人，纯粹的情绪发泄是无意义的。

另外，如果你想深入了解Apollo，还是建议你细心耐心看下[Apollo的文档](https://ctripcorp.github.io/apollo/#/zh/README)，觉得不合理或文档写的不好的，真心欢迎你提交PR参与贡献，我相信只要是合理的，对社区用帮助的，大家都会很感谢你的。:)

**Comment by huaqiangshishuaige** [comment]
@nisiyong  
如果一个程序员连简单的思维逻辑的都没有，再干下去算混不！我说的重点是部署问题，你上来就说没意义，完事儿直接教我怎么看文档了！我就是纯粹吐槽一下，人家官方出来给我解释一通我也怪不好意思的。。你丫直接给我上升到我对社区进行无理要求的地步了。。。也许我有点耍流氓了，我承认我是左冷禅，但是我想对你说：岳不群你好！

**Comment by yu199195** [comment]
。。。。。 强行吃瓜。。   宋顺老哥这么好的脾气。。

**Comment by HaojunRen** [comment]
不从技术角度层面，从另外一个层面想发表一下个人想法：
很多开源的作者跟绝大多数的人一样，忍受着996，也同样被内卷，放弃国情、元旦节日通宵达旦的为业界做贡献，所以无论从言行，还是从其它方面，首先应该致敬作者，尊重开源，很多言论是基于“开源产品一定要好，质量要过关，入门要简单，文档要齐全“，”那些开源产品需要无条件的免费的为用户服务”等想法为出发点

结合提问者的观点，Quick Start不够上生产的标准，无非是过于简单，没有面面俱到，但是如果Quick Start做的很丰富，那么有些使用者的观点会变成“太复杂了，入门成本太高”

**Comment by nobodyiam** [comment]
@huaqiangshishuaige 

> 一、部署没有那么难，只是你们写得难
在源码里，build.bat能很方便的构建三个部署包，我们需要做的就是把admin和config中的@EnableEurekaServer改成@EnableEurekaClient，以及这两个项目中的bootstrap.yml中的Eureka连接地址改成自己的就行了。当前，config数据库里面的注册中心地址也改了，但是目前还没看表中的注册中心地址在哪儿用到。您们的官方文档，花了大量篇幅介绍Quick Start和Mysql如何导入。这个真的没必要，我和朋友的一句玩笑话是Apollo的部署手册就是小几万字的言情小说！

按照[将Config Service和Admin Service注册到单独的Eureka Server上](http://ctripcorp.github.io/apollo/#/zh/faq/common-issues-in-deployment-and-development-phase?id=_8-%e5%b0%86config-service%e5%92%8cadmin-service%e6%b3%a8%e5%86%8c%e5%88%b0%e5%8d%95%e7%8b%ac%e7%9a%84eureka-server%e4%b8%8a)这个文档，1.5.0及以上版本就不需要自己源码打包了，可以直接修改 startup.sh 加入启动参数 `apollo.eureka.server.enabled=false` 即可。Eureka 地址也是直接修改 ApolloConfigDB.ServerConfig 中的 `eureka.service.url` 就可以了。

> 二、建议去除Quick Start那个Demo包
我的崩溃就是从Quick Start开始的，搭建一套环境，发现他内部已经集成了Eureka，这直接导致不能在真实的环境里跑。我这白花半个小时时间只为了证明Apollo是可演示的?

这个我觉得还是需要保留的，quick start 为大家提供了快速上手 apollo 的机会，而且它的定位本来就是为了演示，不是为了生产使用。
