### ISSUE TITLE
一个client端无法使用多个apollo集群

### ISSUE THREAD

**Issue by a364176773** [ctripcorp/apollo#3514]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**描述bug**

简洁明了地描述一下bug

https://github.com/seata/seata/issues/3493
如果我一个client中,需要2个apollo的集群,此时其中一个将会失效.

**复现**

通过如下步骤可以复现：

1. 先把A集群信息放入系统变量中
2. 拿到config实例
3. 再通过存储系统变量的方式ConfigService.getConfig
4. 此时拿到的是A集群的config实例

**期望**

希望可以增加通过传入properties对象来创建config,而不是直接读取系统变量来创建config实例

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nisiyong** [comment]
这个是不是应该让seata考虑不要直接用Apollo创建客户端实例，seata应该与Apollo松耦合才对。
如果seata需要用apollo配置，可以考虑直接用公共Namespace

**Comment by nobodyiam** [comment]
我理解应该不存在一个 client 需要连两个不同 apollo 集群的情况？能说明下实际的场景吗？

对于中间件的 client 而言，建议是使用公共 namespace 来做配置的管控，具体步骤可以参考[公共组件接入指南](https://ctripcorp.github.io/apollo/#/zh/usage/apollo-user-guide?id=%e4%ba%8c%e3%80%81%e5%85%ac%e5%85%b1%e7%bb%84%e4%bb%b6%e6%8e%a5%e5%85%a5%e6%8c%87%e5%8d%97)，一般情况下用户如果指定使用 apollo 配置中心的话，那相应 apollo 的配置如服务端地址也应该已经配置好了，所以我觉得 seata client 不需要去初始化 apollo client 也不应该去感知 apollo 的环境配置信息，直接获取相应 namespace 的配置就可以了。

**Comment by a364176773** [comment]
> 我理解应该不存在一个 client 需要连两个不同 apollo 集群的情况？能说明下实际的场景吗？
> 
> 对于中间件的 client 而言，建议是使用公共 namespace 来做配置的管控，具体步骤可以参考[公共组件接入指南](https://ctripcorp.github.io/apollo/#/zh/usage/apollo-user-guide?id=%e4%ba%8c%e3%80%81%e5%85%ac%e5%85%b1%e7%bb%84%e4%bb%b6%e6%8e%a5%e5%85%a5%e6%8c%87%e5%8d%97)，一般情况下用户如果指定使用 apollo 配置中心的话，那相应 apollo 的配置如服务端地址也应该已经配置好了，所以我觉得 seata client 不需要去初始化 apollo client 也不应该去感知 apollo 的环境配置信息，直接获取相应 namespace 的配置就可以了。

作为开发者,我们可以理解用namespace来隔离环境,但是对用户而言不是那么容易理解,比如用户有N个apollo的地址,就是想让client中的A组件用apollo地址1,而B组件用地址2,目前apollo的实现貌似无法实现这个需求,而nacos是构建properties进行构建nacosclient的实例来使用,这样就可以轻松隔离开多个集群

**Comment by a364176773** [comment]
比如我司有2个zk集群,一个给kafka,一个给dubbo使用,如果zk是按apollo的设计的话,那么如果我的client用了dubbo和kafka是否就无法用2个集群?我觉得这种需求是存在的

**Comment by nisiyong** [comment]
> 比如我司有2个zk集群,一个给kafka,一个给dubbo使用,如果zk是按apollo的设计的话,那么如果我的client用了dubbo和kafka是否就无法用2个集群?我觉得这种需求是存在的

zk地址的key是否可以做区分？我们也有多个zk集群，只用一个apollo client是没啥问题的。
我这边的做法是建多个公共namespace。如：

**dubboPublicNamespace.properties**
```
dubbo.zookeeper.address=
...
```

**kafkaPublicNamespace.properties**
```
kafka.zookeeper.address=
...
```

看你怎么初始化dubbo和kafka，不同key是不冲突的。另外Spring的话可以考虑key引用。如`foo.name=${bar.name}`

**Comment by a364176773** [comment]
> > 比如我司有2个zk集群,一个给kafka,一个给dubbo使用,如果zk是按apollo的设计的话,那么如果我的client用了dubbo和kafka是否就无法用2个集群?我觉得这种需求是存在的
> 
> zk地址的key是否可以做区分？我们也有多个zk集群，只用一个apollo client是没啥问题的。
> 我这边的做法是建多个公共namespace。如：
> 
> **dubboPublicNamespace.properties**
> 
> ```
> dubbo.zookeeper.address=
> ...
> ```
> 
> **kafkaPublicNamespace.properties**
> 
> ```
> kafka.zookeeper.address=
> ...
> ```
> 
> 看你怎么初始化dubbo和kafka，不同key是不冲突的。另外Spring的话可以考虑key引用。如`foo.name=${bar.name}`

我的意思是zk支持你上面说的区分，但是目前apollo只能通过namespace来区分了，而无法通过配置多个apollo-meta地址来区分，不过我可以理解apollo这么设计的思想，我这边跟seata那边反馈的用户做进一步解释，感谢各位的回复
