### ISSUE TITLE
apollo-demo默认有一个私有的namespace：application，已经发布过，但还是不能生成本地配置文件

### ISSUE THREAD

**Issue by xch900910** [ctripcorp/apollo#3515]
apollo-demo默认有一个私有的namespace：application，已经发布过，但还是不能生成本地配置文件

_Originally posted by @FlankMiao in https://github.com/ctripcorp/apollo/issues/815#issuecomment-341654179_
遇到一一样的问题，请问怎么解决了

**Comment by Anilople** [comment]
Duplicate of #815
