### ISSUE TITLE
对接ldap后portal user表无数据

### ISSUE THREAD

**Issue by metadeng** [ctripcorp/apollo#3516]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**描述bug**
参照文档（kubernetes部署apollo），对接了ldap（开启了memberof），发现ldap用户能登录，但是授权的时候发现无法选择用户（即数据库 user表除了apollo用户没有其他用户）

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**
对接ldap后，认证成功后应该将ldap的用户信息同步至数据user表

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nisiyong** [comment]
对接LDAP后，认证逻辑不会走user表了，不会有同步数据的功能。

请问下你想同步数据到表里是想做什么？

**Comment by nobodyiam** [comment]
接入 ldap 后无论是登录还是选择用户都是从 ldap 中查询的，可以看下 memberof 的配置是否正确，或者尝试先吧 memberof 去掉看看

**Comment by metadeng** [comment]
> 接入 ldap 后无论是登录还是选择用户都是从 ldap 中查询的，可以看下 memberof 的配置是否正确，或者尝试先把 memberof 去掉看看

已经处理好了，是memberof问题导致

**Comment by yuechenxv** [comment]
> > 接入 ldap 后无论是登录还是选择用户都是从 ldap 中查询的，可以看下 memberof 的配置是否正确，或者尝试先把 memberof 去掉看看
> 
> 已经处理好了，是memberof问题导致

您好，可否发一下脱敏的配置信息，我也遇到了这个情况，可以登陆，但是找不到其他同事账号，感谢！
