### ISSUE TITLE
是否可以为指定的ip添加配置

### ISSUE THREAD

**Issue by xaasu** [ctripcorp/apollo#3517]
**你的特性请求和某个问题有关吗？请描述**

一个应用下有10个实例，我希望某个实例的配置与另外9个不同，现在如果要做的话，可以通过灰度发布来实现，是否能将这种情况做成feature，对默认的配置进行覆盖，如果没做覆盖，仍然读取默认的配置

**清晰简洁地描述一下你希望的解决方案**

egg:  
databaseurl: xxx.xxx.xx:3306 
databaseurl@110.110.110.110: xxx.xx.xx:3307

ip为110.110.110.110接入该应用的服务，读取的databaseurl为xxx.xx.xx:3307
其他接入该应用的服务，读取databaseurl为：xxx.xxx.xx:3306 

**清晰简洁地描述一下这个特性的备选方案**

目前可以通过灰度发布110.110.110.110 ，设置databaseurl为xxx.xx.xx:3307 实现，但灰度从使用角度来说只是一种临时方案，用来做定制化不是很合适，希望能够实现一种永久方案

**其它背景**

在这里添加和这个特性请求有关的背景说明、截图

**Comment by nobodyiam** [comment]
可以试试集群功能
