### ISSUE TITLE
本地访问K8s集群，不能读取配置，提示[Cause: Could not complete get operation [Cause: Can't connect to SOCKS proxy:connect timed out]]

### ISSUE THREAD

**Issue by lifh1234** [ctripcorp/apollo#3518]
**版本：1.7.1**
**使用了ingress，转发的host是：http://apollo.config.com/dev**
我的配置如下：
   启动配置：
          -Denv=dev -Dapp.id=test1 -Dapollo.configService=http://apollo.config.com/dev -Dapollo.bootstrap.namespaces=application
  bootstrap.yml配置：
            apollo:
              bootstrap:
                enable: true
              meta: http://apollo.config.com/dev

**启动后一直报错，如下：**
Load Apollo Config failed - appId: test1, cluster: default, namespace: application, url: http://apollo.config.com/dev/configs/test1/default/application?ip=192.168.245.1 [Cause: Could not complete get operation [Cause: Can't connect to SOCKS proxy:connect timed out]]

**而我在浏览器访问：http://apollo.config.com/dev/configs/test1/default/application?ip=192.168.245.1 是有数据返回的，如下**：
{
  "appId": "test1",
  "cluster": "default",
  "namespaceName": "application",
  "configurations": {
    "config3.name": "config3.nameconfig3.nameconfig3.nameconfig3.name"
  },
  "releaseKey": "20210126171407-bdad958a15471cd0"
}

**http://apollo.config.com/dev 也是可以访问的，如下：**
  [
    {
    "appName": "apollo-configservice",
    "instanceId": "apollo-configservice:http://apollo.config.com/dev",
    "homepageUrl": "http://apollo.config.com/dev"
    },
  {
    "appName": "apollo-adminservice",
    "instanceId": "apollo-adminservice:http://apollo-service-dev-apollo-adminservice.sre:8090",
    "homepageUrl": "http://apollo-service-dev-apollo-adminservice.sre:8090"
    }
  ]

**我将此应用部署的在k8s集群类，是可以读取到配置的，只不过meta改成了service地址，如下：**
http://apollo-service-dev-apollo-configservice.sre:8080

**请问会是哪里的问题呢**

**Comment by lifh1234** [comment]
@nobodyiam  还烦请帮忙解答下，谢谢！这个问题确实困恼了我好久

**Comment by lifh1234** [comment]
已处理，我自己在idea中设置了k8s内网代理，导致解析域名

**Comment by Anilople** [comment]
Duplicate of #2853
