### ISSUE TITLE
目前经过测试，我配置访问控制，dev的数据库跟pro的数据中配置的token一致，但是dev会显示401错误

### ISSUE THREAD

**Issue by ziansong** [ctripcorp/apollo#3519]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**描述bug**

简洁明了地描述一下bug

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**
![image](https://user-images.githubusercontent.com/51153848/106081677-4522fc80-6154-11eb-8bd4-a9cf9400da64.png)

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by ziansong** [comment]
使用的是最新的1.7.1版本

**Comment by ziansong** [comment]
目前看test与pro tokens不一致也可以连接上，是我测试有问题还是本身有问题

**Comment by nobodyiam** [comment]
请详细描述一下你的参数配置情况，另外建议按照文档再自查一遍配置
* [apollo-adminservice 配置](http://ctripcorp.github.io/apollo/#/zh/deployment/distributed-deployment-guide?id=_6-admin-serviceaccesscontrolenabled-%e9%85%8d%e7%bd%aeapollo-adminservice%e6%98%af%e5%90%a6%e5%bc%80%e5%90%af%e8%ae%bf%e9%97%ae%e6%8e%a7%e5%88%b6)
* [apollo-portal 配置](http://ctripcorp.github.io/apollo/#/zh/deployment/distributed-deployment-guide?id=_12-admin-serviceaccesstokens-%e8%ae%be%e7%bd%aeapollo-portal%e8%ae%bf%e9%97%ae%e5%90%84%e7%8e%af%e5%a2%83apollo-adminservice%e6%89%80%e9%9c%80%e7%9a%84access-token)

**Comment by ziansong** [comment]
portal数据库中的配置
![image](https://user-images.githubusercontent.com/51153848/106409025-9a278100-647a-11eb-8e17-495cc6f69a05.png)
configdb中的配置
![image](https://user-images.githubusercontent.com/51153848/106409106-cba04c80-647a-11eb-88c0-0a6fa711bba7.png)

**Comment by nobodyiam** [comment]
不同环境的 configdb 都检查一下吧，另外也可以看下 admin service 的日志，应该会有 `Invalid access token: xxx` 这些
