### ISSUE TITLE
公司准备使用Apollo的4个环境，并且现有自己的Eureka，4个DB库对应的ServerConfig可以对应同一个Eureka吗，还是需要4个？

### ISSUE THREAD

**Issue by zzjmates** [ctripcorp/apollo#3531]
参考作者提供的：https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#8-%E5%B0%86config-service%E5%92%8Cadmin-service%E6%B3%A8%E5%86%8C%E5%88%B0%E5%8D%95%E7%8B%AC%E7%9A%84eureka-server%E4%B8%8A。

　我运行了4套环境，在同一个eureka服务集群环境下，数据库不同，但是修改了其中一个的配置，另外一个环境会同步修改的配置，但是需要自己手动点发布才能生效，如果管理员不点击的话，那就相当于是两套不同的配置了吧？麻烦懂的哥们分享下？？？？按照作者的说法我要是运行四个环境，并且要独立，那就是需要4个eureka服务，有没有实践过的朋友？

**Comment by Anilople** [comment]
需要4个，做物理上的隔离
