### ISSUE TITLE
portal服务的eureka请求地址是在哪配置的呢？

### ISSUE THREAD

**Issue by andyyumiao** [ctripcorp/apollo#3532]
如题，在项目里并没有找到，configservice正常启动了，但是portal链接的eureka始终是：http://localhost:8761/eureka/

求解惑

**Comment by Anilople** [comment]
参考 文档 [分布式部署指南](https://ctripcorp.github.io/apollo/#/zh/deployment/distributed-deployment-guide)

portal需要指定meta server即可

**Comment by hhj970815** [comment]
> 参考 文档 [分布式部署指南](https://ctripcorp.github.io/apollo/#/zh/deployment/distributed-deployment-guide)
> 
> portal需要指定meta server即可

i can't access the url

**Comment by hhj970815** [comment]
> 如题，在项目里并没有找到，configservice正常启动了，但是portal链接的eureka始终是：http://localhost:8761/eureka/
> 
> 求解惑

修改portal数据库里面的数据
