### ISSUE TITLE
SpringBoot + apollo，热加载的变量是否应该用volatile修饰实现多线程可见性

### ISSUE THREAD

**Issue by seunjjs** [ctripcorp/apollo#3533]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)：已检查
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)：已搜索，有一个相似的问题
- [x] 我已经仔细检查过[FAQ]：已检查(https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**描述疑问**

#1769 中也问到了该问题，Jason Song回答如果会变的话可以用volatile修饰。

**详细描述**

1. https://www.jianshu.com/p/3c06ffbf0d52 该文章中描述的场景可以复现
2. 但我在启动类上增加@SpringBootApplication注解后并不会出现线程一直运行的情况
3. 同时我在使用apollo配置注入时，不加volatile注解，也无法复现线程内缓存未刷新的情况
4. 请问，是Spring启动后做了特殊处理还是一切都是巧合？跟踪apollo的修改配置的代码发现就是对缓存的对象反射更新了下属性，因此我个人也觉得应该加上volatile。

**期望**

在官方文档中明确热加载的配置需要/不需要用volatile修饰

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：1.7.0
- 错误日志: 无
- 配置：办公机器
- 平台和操作系统:win10

**Comment by Anilople** [comment]
需要用volatile修饰

不使用volatile，程序可能跑很多次也不会出现问题，但是可能偶尔出现一次问题，并且难以复现

参考 [Java Language Specification 17.4. Memory Model](https://docs.oracle.com/javase/specs/jls/se8/html/jls-17.html#jls-17.4)

**Comment by Anilople** [comment]
Duplicate of #1769
