### ISSUE TITLE
apollo的秘钥采用UUID生成，非安全随机数，如何自定义秘钥生成算法

### ISSUE THREAD

**Issue by zhuweiquan** [ctripcorp/apollo#3538]
采用安全随机数的生成方式。
注：生成安全随机数：
A）使用java.security.SecureRandom.getInstanceStrong()，该方法是每次直接调用dev/random，所以可能会有阻塞，对性能有影响。
对于阻塞的问题，可以通过部署haveged进程来解决，但是同样对性能有影响。
B）可以使用NID_aes_256_ctr这个DRBG，也是满足密码学要求的安全随机数，但必须满足：
首次设置种子，并设置种子回调函数，根据安全要求选择每次设置种子还是隔段时间设置，无论哪种都要从/dev/random获取种子。
用bouncycastle的实现DRBG的方式（下面的代码），如果每次都设置种子，性能同样有影响，所以选择默认的“隔段时间设置种子”的方式，
下面的reSeedCounter的那段，可以解决性能影响的问题。

1.  public static void main(String[] args) throws NoSuchAlgorithmException {  
2.      long start = System.currentTimeMillis();  
3.      // 随机数种子，可能阻塞  
4.      SecureRandom source = SecureRandom.getInstanceStrong();  
5.      boolean predictionResistant = true; // /dev/random可以认为是活熵源  
6.    
7.      // NID_aes_256_ctr  
8.      BlockCipher cipher = new AESEngine();  
9.      int cipherLen = 256;  
10.   
11.     // 生成nonce  
12.     byte[] nonce = new byte[cipherLen / 8];  
13.     source.nextBytes(nonce);  
14.   
15.     boolean reSeed = false; // 是否每次取完随机数都重新刷新熵源  
16.     SecureRandom random =  
17.     new SP800SecureRandomBuilder(source, predictionResistant).buildCTR(cipher, cipherLen, nonce, reSeed);

**Comment by nobodyiam** [comment]
是指下面这个？能否先说明下问题是什么？

https://github.com/ctripcorp/apollo/blob/b728d42c3ab71c81a913e0756c50f59346b4abc9/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/AccessKeyController.java#L29-L37

**Comment by zhuweiquan** [comment]
我们需要用另外一种加密算法替换secret 的UUID生成方法。然后解密也一样

**Comment by zhuweiquan** [comment]
这个是需要改动源码吗

**Comment by nisiyong** [comment]
@zhuweiquan 
Apollo Client只是用这个secret作为客户端的请求的HMAC，并不是加密解密。当时设计的目的是为了防止ConfigService的请求被伪造，造成配置泄漏的安全问题。请问下你们这个改造的需求点是为啥？

**Comment by zhuweiquan** [comment]
我们公司对于用于密码学用途的随机数有着非常严格的要求，用于密码学用途的密钥（盐值,IV）都要是安全随机数，而UUID并非安全随机数，不能用于生成此处用于HMAC的密钥

**Comment by nobodyiam** [comment]
@nisiyong 

这个是否可以作为一个 spi 开放出去？默认使用 UUID 生成，不过用户可以自己提供其它方式？或者直接替换为更安全的随机数算法？
我理解这里只是通过 UUID 生成一个全局唯一的 string 吧，其实和加密解密也没啥关系。

**Comment by nisiyong** [comment]
> 这个是否可以作为一个 spi 开放出去？默认使用 UUID 生成

这个是可以的，确实只是个随机密钥而已。我抽空抽取下接口

**Comment by whg903** [comment]
这个accessKey的存储能否支持数据库加密存储，我们公司的安全也要求token、密码类的不能在数据库明文存储

**Comment by nisiyong** [comment]
@whg903 如果有需要，我觉得可以做个扩展。入库和出库让用户自定义逻辑，默认直接明文入库

**Comment by whg903** [comment]
嗯， 这个一个比较好的方式，包括Apollo本身数据库连接配置的加密等，都可以支持SPI等方式提供扩展，也提供默认实现，这样就非常方便了。

**Comment by nisiyong** [comment]
> Apollo本身数据库连接配置的加密

你是说Apollo的ConfigDB和PortalDB本身的连接配置吗？这个我认为不在考虑范围内。如果是业务数据库配置，那就是另外一个话题了

**Comment by whg903** [comment]
> > Apollo本身数据库连接配置的加密
> 
> 你是说Apollo的ConfigDB和PortalDB本身的连接配置吗？这个我认为不在考虑范围内。如果是业务数据库配置，那就是另外一个话题了

是ConfigDB和PortalDB本身的连接配置。我们公司主机层会部署有根密钥，要求各应用必须使用根密钥提供的接口对自己的涉密配置进行加解密处理，这样可以保证所有配置文件中都不存在明文密码。 根密钥的及其API的安全性，由另外的机制保证。

**Comment by nisiyong** [comment]
目前数据源的初始化用的是SpringBoot的本地文件Properties读取，如果你有特殊需要是不是可以考虑下这块逻辑的自定义加载初始化。每个公司的场景都不太一样，有些在主机权限上限制的比较好，默认的方式也足够了

**Comment by nobodyiam** [comment]
@whg903 apollo 自身数据库连接信息加密的场景可以参考下 #2342

**Comment by whg903** [comment]
> @whg903 apollo 自身数据库连接信息加密的场景可以参考下 #2342

@nobodyiam 谢谢，我们当前也是采用这种方式实现的。
不过如果有统一的机制，不需要修改开源代码和发布包，仅仅提供一个provider jar的方式，就更好了。
