### ISSUE TITLE
apollo-on-kubernetes 镜像文件与官方镜像不一致问题

### ISSUE THREAD

**Issue by kinsolee** [ctripcorp/apollo#3540]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**描述bug**
自行构建镜像时，按照 [文档](https://github.com/ctripcorp/apollo/blob/master/scripts/apollo-on-kubernetes/README.md) ，添加 jar 文件的路径与官方镜像不一致，[启动脚本](https://github.com/ctripcorp/apollo/blob/master/scripts/apollo-on-kubernetes/apollo-portal-server/scripts/startup-kubernetes.sh) 与官方镜像也不一致。导致启动找不到配置文件，日志也不是输出到 stdout/stderr

**期望**

dockerfile 与 官方镜像保持一致

**截图**

![image](https://user-images.githubusercontent.com/5144108/107105607-42b25800-6862-11eb-9fc2-4516bb4c7b1e.png)

**Comment by nobodyiam** [comment]
@kinsolee 

目前已经提供了[Helm Chart 部署方式](https://ctripcorp.github.io/apollo/#/zh/deployment/distributed-deployment-guide?id=_241-%e5%9f%ba%e4%ba%8ekubernetes%e5%8e%9f%e7%94%9f%e6%9c%8d%e5%8a%a1%e5%8f%91%e7%8e%b0)的部署方式，不需要自己打镜像，是否能满足你的需求？

**Comment by kinsolee** [comment]
> @kinsolee
> 
> 目前已经提供了[Helm Chart 部署方式](https://ctripcorp.github.io/apollo/#/zh/deployment/distributed-deployment-guide?id=_241-%e5%9f%ba%e4%ba%8ekubernetes%e5%8e%9f%e7%94%9f%e6%9c%8d%e5%8a%a1%e5%8f%91%e7%8e%b0)的部署方式，不需要自己打镜像，是否能满足你的需求？

我们有企业定制化需求，添加 feature 需要自己打镜像。

**Comment by kinsolee** [comment]
@nobodyiam  可以考虑使用 dockerfile 构建 jar 包的形式。 例如：
```dockerfile
FROM yourregistry.com/maven:3.6.3-jdk-8-slim AS builder
COPY . .
RUN mvn clean package -Dmaven.test.skip=true

FROM openjdk:8-jre-alpine3.8
RUN \
    echo "http://mirrors.aliyun.com/alpine/v3.8/main" > /etc/apk/repositories && \
    echo "http://mirrors.aliyun.com/alpine/v3.8/community" >> /etc/apk/repositories  && \
    apk update upgrade && \
    apk add --no-cache procps curl bash tzdata && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    mkdir -p /apollo-portal

ENV APOLLO_PORTAL_SERVICE_NAME="service-apollo-portal-server.sre" APOLLO_RUN_MODE="Docker"

EXPOSE 8070
COPY scripts/apollo-on-kubernetes/apollo-portal-server/ /apollo-portal/
COPY --from=builder apollo-portal/target/* /apollo-portal/
CMD ["/apollo-portal/scripts/startup-kubernetes.sh"]
```

**Comment by nobodyiam** [comment]
helm chart 和 apollo-on-kubernetes 的主要区别是前者使用了 k8s 原生的服务发现，后者使用了 eureka 做服务发现。
如果上述的区别不是问题的话，可以使用下面的方式打 docker 镜像，然后使用 helm chart 部署

1. ./scripts/build.sh
2. mvn docker:build -pl apollo-configservice,apollo-adminservice,apollo-portal

**Comment by kinsolee** [comment]
按上面的方法可以打包镜像了，谢谢！
