### ISSUE TITLE
RemoteConfigLongPollService-内存泄漏

### ISSUE THREAD

**Issue by gsunapoleonchen** [ctripcorp/apollo#3543]
RemoteConfigLongPollService中的三个Map只进不出，缓导致系统运行时间长了后，内存缓慢升高。

private final Multimap<String, RemoteConfigRepository> m_longPollNamespaces;
  private final ConcurrentMap<String, Long> m_notifications;
  private final Map<String, ApolloNotificationMessages> m_remoteNotificationMessages;

![image](https://user-images.githubusercontent.com/52982626/107310398-4abf0180-6ac7-11eb-80c1-517a8faf50d5.png)
![image](https://user-images.githubusercontent.com/52982626/107310452-688c6680-6ac7-11eb-902a-510bcec9d68b.png)

**Comment by nobodyiam** [comment]
这些都是 namespace 相关的必要数据，和 namespace 数量有关，占用的内存也是恒定的，泄露具体是指啥？
