### ISSUE TITLE
如何使用API去更新/删除一个配置项，当key中含有特殊字符的时候，如"//"。

### ISSUE THREAD

**Issue by PaulYuanJ** [ctripcorp/apollo#3544]
**描述bug**

我们是在Prometheus监控系统中搭配使用apollo作为配置监控项的前端接口的。当我们配置的时候，使用的key为这种类型的时候（key中含有特殊字符），不知道如何使用API接口去更新和删除：
```
key: "http://3.3.3.3/demo",
value: "{"targets": ["http://3.3.3.3/demo"], "labels": {"app_service": "demo", "component_name": "demo", "application_notes": "demo", "application_support": "somebody", "check_ip": "XXX.XXX.XXX.XXX", "check_type": "blackbox_exporter", "platform_support": "IT OPS"}}"
```

**截图**

下图为我们一个样例，我们有大量的key是http url的形式，这种情况在是用update和delete接口的时候不知道如何转义
![image](https://user-images.githubusercontent.com/32631327/107465627-aa87dc00-6b9d-11eb-956c-61fe9a918590.png)
![image](https://user-images.githubusercontent.com/32631327/107465728-dc993e00-6b9d-11eb-9972-c2914833444c.png)
![image](https://user-images.githubusercontent.com/32631327/107465791-f8044900-6b9d-11eb-9301-a413e51b3b5b.png)

### 额外的细节和日志

我尝试过将'/'用‘%2F’转义没有效果，用‘\/’也没有效果，网上也没有查询到类似我们这种用法，所以想要请教这块儿应该如何使用api。

多谢~

**Comment by nobodyiam** [comment]
see #2876，当 Key 中包含 '/' 时目前应该是不支持的，可能要考虑为 open api 增加基于 id 的接口

**Comment by snowy861227** [comment]
当 Key 中包含 '/' 时目前应该是不支持的，这个还会继续更新支持吗？
