### ISSUE TITLE
portal1.8.0启用ldap无法启动

### ISSUE THREAD

**Issue by SeesawLiu** [ctripcorp/apollo#3551]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**描述bug**

1.8.0 使用ldap时无法启动

**复现**

通过如下步骤可以复现：

1. profile 启用ldap
```
2021-02-18 14:12:24.582 ERROR 1 --- [ main] o.s.b.d.LoggingFailureAnalysisReporter :

***************************

APPLICATION FAILED TO START

***************************

Description:

The bean 'ldapContextSource', defined in class path resource [org/springframework/boot/autoconfigure/ldap/LdapAutoConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [com/ctrip/framework/apollo/portal/spi/configuration/AuthConfiguration$SpringSecurityLDAPAuthAutoConfiguration.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true
```
**期望**

正常启动

**截图**
![20210218151708](https://user-images.githubusercontent.com/6505183/108319406-5499e080-71fc-11eb-8856-92f23f703462.png)

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：1.8.0

**Comment by SeesawLiu** [comment]
添加以下配置
```
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.ldap.LdapAutoConfiguration
```

**Comment by nobodyiam** [comment]
Thanks for reporting this issue and this issue was fixed in [1.8.1 release](https://github.com/ctripcorp/apollo/releases/tag/v1.8.1)
