### ISSUE TITLE
config server 注册了内网IP，导致client访问不了

### ISSUE THREAD

**Issue by zhangzw218** [ctripcorp/apollo#3554]
**问题**
config server 注册了内网IP，比如172.0.0.3:8080这样的。在容器内部才能使用，比如我portal和config和admin在同一个docker环境，就可以正常使用。
但是外部的client就不行了，从eureka中获取服务地址之后访问不了。。

**我已经仔细检查过[FAQ]**
我找到了部署&开发问题 【3. admin server 或者 config server 注册了内网IP，导致portal或者client访问不了admin server或config server】
也看到了3个解决方案
方案一： 忽略某些网卡：我在容器中，找不到apollo-configservice/src/main/resources/application.yml这个路径
方案二和三，都需要修改startup.sh，我找到了这个文件，却找不到类似-Deureka.instance.ip-address=${指定的IP}这样的配置项。
bootstrap.yml文件也没有找到。
感觉这些方案，和docker内的情况不太一样？？
 (https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#3-admin-server-%E6%88%96%E8%80%85-config-server-%E6%B3%A8%E5%86%8C%E4%BA%86%E5%86%85%E7%BD%91ip%E5%AF%BC%E8%87%B4portal%E6%88%96%E8%80%85client%E8%AE%BF%E9%97%AE%E4%B8%8D%E4%BA%86admin-server%E6%88%96config-server)

**期望**

1.最好能通过方案一，通过忽略网卡的方式来排除虚拟IP，注册外网可用的IP，而不是指定某个IP就好了。
2.如果可以不修改那个application.yml文件（我也没有找到这个文件），如果可以通过输入想要忽略网卡的环境变量，而不需要修改任何文件就更好了，求解，我应该怎么做。

**截图**
这个是容器内的文件情况，如果需要修改文件的，应该改哪个配置文件？
![1111111112222](https://user-images.githubusercontent.com/40768649/108473159-9ee89380-72c8-11eb-855b-018529a57d42.png)

### 额外的细节和日志
- 版本：1.7.1
- 平台和操作系统:docker

**Comment by zhangzw218** [comment]
docker中，我找到了两个环境变量，解决了一部分问题，感谢https://github.com/ctripcorp/apollo/issues/3299的项目
EUREKA_INSTANCE_IP_ADDRESS: 192.168.yyy.zzz
这个是往Eureka注册时，指定一个服务IP,就是方案二的环境变量版本。
但注册了正确的IP，PORT还是8080，外部照样无法访问。
所以需要SERVER_PORT，改成:18080
然后PORTS: 18080:18080，改掉内部的服务接口，整个访问地址就全通了。
……
按照方案2是成功了，求问有没有docker环境变量的配置文档，我没有找到，想知道其中有没有直接指定IP:PORT的环境变量（方案三），或者注册时忽略一些网卡的环境变量（方案一）

**Comment by nobodyiam** [comment]
Spring 的配置可以是通过 application.yml 传入，也可以通过-D参数或环境变量传入的，不过命名方式会略有不同。

比如`-Deureka.instance.ip-address=${指定的IP}`通过环境变量就是`EUREKA_INSTANCE_IP_ADDRESS=${指定的IP}`，`-Deureka.instance.homePageUrl=http://${指定的IP}:${指定的Port}`通过环境变量就是`EUREKA_INSTANCE_HOME_PAGE_URL=http://${指定的IP}:${指定的Port}`

更多信息可以参考[网络策略](http://ctripcorp.github.io/apollo/#/zh/deployment/distributed-deployment-guide?id=_14-%e7%bd%91%e7%bb%9c%e7%ad%96%e7%95%a5)的说明
