### ISSUE TITLE
Portal中，用户有某个项目的UAT权限，没有DEV、FAT、PRO（编辑、发布）权限时,希望不要看到配置

### ISSUE THREAD

**Issue by zhangzw218** [ctripcorp/apollo#3559]
**描述bug**

Portal中，用户有某个项目的UAT权限，没有DEV、FAT、PRO权限时，
只有DEV看不到配置，会提示"您不是该项目的管理员，也没有该Namespace的编辑或发布权限，无法查看配置信息。"
FAT、PRO也不希望被看到配置，但现在，配置都可以看到，只是编辑不了。
……
我的目的是希望创建一个只能编辑查看DEV/FAT权限，但是看不到UAT/PRO权限的用户，但结果是，只有PRO我不给权限看不到，给了权限才能查看。
其他三个权限，不管给不给权限，都能看的清清楚楚。

**复现**

通过如下步骤可以复现：

1. 创建一个用户：Sample_Dev_Edit
2. 编辑SampleApp项目授权，为Dev添加编辑权限。
3. 结果：该用户登录后可以看到所有的环境配置（只是Dev能编辑，其他编辑不了）
3. 再尝试：关闭Dev的编辑权限，添加UAT编辑权限（不给任意一个权限的话，连项目都看不到，所以这里随便给一个）
4. 结果：Dev提示：您不是该项目的管理员，也没有该Namespace的编辑或发布权限，无法查看配置信息。这个是我想要的。
5. 但是，FAT/PRO用户也没有权限，却依然可以看到配置

**期望**

没有编辑权限、也没有发布权限的页面，不给与展示信息，我觉得Dev既然能做到，其他环境应该也能做到？
**截图**

![11111111111111111](https://user-images.githubusercontent.com/40768649/108593553-5ce64d00-73af-11eb-9135-d0348e953649.png)
![222222222222](https://user-images.githubusercontent.com/40768649/108593556-5eb01080-73af-11eb-9125-e6f5bf28a55d.png)
![333333333333](https://user-images.githubusercontent.com/40768649/108593555-5e177a00-73af-11eb-9a47-4dba31cef378.png)

### 额外的细节和日志

- 版本：Porlal-1.7.2
- Docker环境

**Comment by nobodyiam** [comment]
see [配置查看权限](https://ctripcorp.github.io/apollo/#/zh/usage/apollo-user-guide?id=_61-%e9%85%8d%e7%bd%ae%e6%9f%a5%e7%9c%8b%e6%9d%83%e9%99%90)

**Comment by zhangzw218** [comment]
多谢，修改这个配置参数后，其他环境的配置就成功隐藏了。

**Comment by zhangzw218** [comment]
多谢，修改这个配置参数后，其他环境的配置就成功隐藏了。
