### ISSUE TITLE
apollo数据源重试机制

### ISSUE THREAD

**Issue by liufaxue1108** [ctripcorp/apollo#3564]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://ctripcorp.github.io/apollo/#/zh/faq/common-issues-in-deployment-and-development-phase)
apollo服务启动时，数据库服务未完全启动成功，apollo尝试连接4次就不再连接了，如何设置让apollo服务间隔一段时间重连数据库服务
**描述bug**

简洁明了地描述一下bug

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**
有属性可以配置失败重连
简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
I haven't tried that but you may take a look at the [initializationFailTimeout](https://github.com/brettwooldridge/HikariCP#infrequently-used) property, the configuration key in spring boot is `spring.datasource.hikari.initialization-fail-timeout`.

**Comment by 1725636955** [comment]
配置光数据源的重试次数，去看光的文档吧。
https://github.com/brettwooldridge/HikariCP
