### ISSUE TITLE
如果我希望某一个json配置，能够同时给其他appid使用，我应该怎么做？

### ISSUE THREAD

**Issue by zhangzw218** [ctripcorp/apollo#3566]
**描述bug**
虽然目前操作看，公共Namespace应该是只支持properties的，但还是想确认一下，是不是我操作错了什么。
[https://ctripcorp.github.io/apollo/#/zh/design/apollo-core-concept-namespace?id=_3-namespace%e7%9a%84%e6%a0%bc%e5%bc%8f%e6%9c%89%e5%93%aa%e4%ba%9b%ef%bc%9f](url)

**期望**
如果我希望某一个json配置，能够同时给其他appid使用，我应该怎么做？

**截图**
![11111111](https://user-images.githubusercontent.com/40768649/108828778-3ec45b00-7602-11eb-909b-f945bc4a7044.png)

### 额外的细节和日志

- 版本：
- 1.7.2

**Comment by nobodyiam** [comment]
1. 公共namespace目前只支持properties格式
2. namespace的命名不允许出现 .json

**Comment by nisiyong** [comment]
@zhangzw218 可以考虑用公共的properties namespace，里面添加一个key，value为json格式字符串
