### ISSUE TITLE
Quick Start教程中提供的演示包发现如下错误，导致无法正常演示

### ISSUE THREAD

**Issue by permgenspace** [ctripcorp/apollo#3567]
**问题一**
apollo-build-scripts\demo.sh中第185行和第187行，关于$CLIENT_DIR;$CLIENT_JAR，$CLIENT_JAR在定义时已经包含文件夹名了，应该直接使用$CLIENT_JAR；否则启动客户端时会报找不到主类。

**问题二**
客户端读取的是apollo-demo.jar中的app.properties，即apollo-build-scripts\client\apollo-demo.jar\META-INF\app.properties，其中的配置为app.id=100004458，和apolloconfigdb.sql、apolloportaldb.sql中的SimpleApp不一致，导致获取不到属性。

**Comment by nobodyiam** [comment]
1. classpath 需要同时配置文件夹和jar包，否则会读取不到正确的 app.properties
2. 实际获取的 appid 是在 https://github.com/nobodyiam/apollo-build-scripts/blob/master/client/META-INF/app.properties 这里配置的
