### ISSUE TITLE
使用proxysql，创建应用时提示“Role Master+test1 doesn't exist!”

### ISSUE THREAD

**Issue by Sanctionist** [ctripcorp/apollo#3570]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://ctripcorp.github.io/apollo/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

在创建应用时，出现异常。
以创建appid为test1的应用为例，提示"Role Master+test1 doesn't exist!"

当部署模式为 portal -> proxysql -> mariadb-galera 时出现，当部署模式为 portal -> mariadb-galera 时可正常创建

请教下这个问题，是因为什么原因导致的？

报错日志（部分）
![image](https://user-images.githubusercontent.com/12059650/109127985-f9329a00-7789-11eb-80cb-9274515ad75a.png)

### 额外的细节和日志
- 版本：1.8.1
- 平台和操作系统：k8s

**Comment by nobodyiam** [comment]
1. 可以看下`ApolloPortalDB.Role`表中是否存在这条记录
2. 如果没有的话，看看前面的日志是否有报错啥的

**Comment by Sanctionist** [comment]
[apollo-portal.log](https://github.com/ctripcorp/apollo/files/6046823/apollo-portal.log)
重新部署了apollo-portal,把所有的日志download下来，只能看到这个报错信息，但是看不到插入数据的过程，也没有其他相关的报错日志

**Comment by Sanctionist** [comment]
问题查到了
apollo中使用了事务，set autocommit = 1 被代理过滤了，导致mysql执行了sql但是没有commit。

启动proxysql配置 
mysql-forward_autocommit=true
mysql-autocommit_false_is_transaction=true

变更方法参考
1. 登录 proxysql admin端
2. set mysql-forward_autocommit = 'true';
3. set mysql-autocommit_false_is_transaction = 'true';
4. LOAD MYSQL VARIABLES TO RUNTIME;
