### ISSUE TITLE
Integration ReactJS & VueJS

### ISSUE THREAD

**Issue by Allan-Nava** [ctripcorp/apollo#3571]
Is there any integration for reactJS e vueJS? like https://pypi.org/project/apollo-client/ for python

**Comment by Anilople** [comment]
All other language sdks are collectd to here https://ctripcorp.github.io/apollo/#/zh/usage/third-party-sdks-user-guide

**Comment by Anilople** [comment]
You want access apollo config server from frontend directly?

**Comment by Giovanni-94** [comment]
> You want access apollo config server from frontend directly?

i have the same issue

**Comment by Allan-Nava** [comment]
> You want access apollo config server from frontend directly?

I need to setup the api url for frontend

**Comment by nobodyiam** [comment]
Currently there are several nodejs implementations, are they applicable for ReactJS & VueJS? Or maybe we can migrate the main logic from node js implementations to support ReactJS & VueJS?
1. https://github.com/Quinton/node-apollo
2. https://github.com/kaelzhang/ctrip-apollo
3. https://github.com/shinux/node-apollo-client
4. https://github.com/lvgithub/ctrip-apollo-client
5. https://github.com/lengyuxuan/apollo-node
6. https://github.com/xuezier/egg-apollo-client
