### ISSUE TITLE
如何通过openapi批量修改properties的配置

### ISSUE THREAD

**Issue by theonesmx** [ctripcorp/apollo#3576]
openapi针对properites的配置文件，只能单个key进行增，改，如果我想批量更新，或者整个properties文件进行替换，有没有办法。

**Comment by fengzhibin** [comment]
有以下几种做法：

1.循环请求接口
2.通过协程并发请求接口
3.联系阿波罗开发者让他们提供批量操作接口

可以先代码层面封装批量操作的方法，这样上层代码不用感知底层操作，然后方法内部可以先通过循环请求实现操作，因为最简单，后续有时间做升级迭代可以改成协程并发请求。感觉暂时阿波罗不会提供批量操作接口，因为没多大必要。

**Comment by Anilople** [comment]
Duplicate of #2866
