### ISSUE TITLE
服务外网访问场景下，如何安全访问apollo配置

### ISSUE THREAD

**Issue by liuyl1992** [ctripcorp/apollo#3577]
**服务外网访问场景下，如何安全访问apollo配置**

在跨大区场景下公用apollo配置，需要暴露服务地址，导致知道appid情况下可以在任意地址获取到配置，又由于机器过多设置白名单工作繁重

希望增加基于应用Id的ak/sk机制 ，访问要加secret才可访问，另外apollo UI的在没有给用户赋予权限的情况下，依然可以查看，只是不能编辑新增，希望权限基于应用，没有赋权限时增删改查全部不予操作

**其它背景**

**Comment by liuyl1992** [comment]
目前支持的开启访问控制 没有关联到应用，如果关联到应用更安全，，不然一个token可以访问所有应用也非常危险

**Comment by nobodyiam** [comment]
可以参考下[安全相关最佳实践](https://ctripcorp.github.io/apollo/#/zh/usage/apollo-user-guide?id=_71-%e5%ae%89%e5%85%a8%e7%9b%b8%e5%85%b3)，应用秘钥是每个应用不同的
