### ISSUE TITLE
我这边实现了新的阿波罗php库，欢迎围观

### ISSUE THREAD

**Issue by fengzhibin** [ctripcorp/apollo#3578]
github地址：https://github.com/fengzhibin/apollo-sdk-config
composer地址：https://packagist.org/packages/apollo-sdk/config

特性：
1.支持批量获取配置
2.支持配置认证密钥
3.无额外扩展依赖，单纯依赖guzzlehttp composer包实现单进程无阻塞监听多个应用更新

有什么使用问题可以在github上给我留issues。

**Comment by nobodyiam** [comment]
Thanks! The [wiki](https://ctripcorp.github.io/apollo/#/zh/usage/third-party-sdks-user-guide?id=apollo-php-%e5%ae%a2%e6%88%b7%e7%ab%af-2) page is also updated.

**Comment by fengzhibin** [comment]
新增基于apollo-sdk/config库，常驻client的实现https://github.com/fengzhibin/apollo-sdk-clientd

**Comment by nobodyiam** [comment]
@fengzhibin would you please submit a pull request to add this php library to [third-party-sdks-user-guide.md](https://github.com/ctripcorp/apollo/blob/master/docs/zh/usage/third-party-sdks-user-guide.md)?

**Comment by fengzhibin** [comment]
> @fengzhibin would you please submit a pull request to add this php library to [third-party-sdks-user-guide.md](https://github.com/ctripcorp/apollo/blob/master/docs/zh/usage/third-party-sdks-user-guide.md)?

OK

**Comment by nobodyiam** [comment]
#3682 was merged.
