### ISSUE TITLE
投个案例,使用多个namespace做了一个服务版本切换功能

### ISSUE THREAD

**Issue by yazong** [ctripcorp/apollo#3579]
更多详细内容请查看URL:https://blog.llyweb.com/articles/2020/08/11/1597149013480.html
有做的不好的地方，还望能提些建议。谢谢。

**Comment by nobodyiam** [comment]
感谢投稿，想问下是否适合放到 [wiki](https://ctripcorp.github.io/apollo/#/zh/usage/apollo-user-practices) 页面中？

**Comment by yazong** [comment]
@nobodyiam 您这边如果可以的话，我这边没问题，十分开心。这篇文章是去年下半年写的，因为现在投稿，是因为实战了几个月，才刚趋于稳定。我这边最近在加apache/sentinel，加完之后，我再投个搞，模式应该跟这个差不多。

**Comment by nobodyiam** [comment]
已更新至 [wiki](https://ctripcorp.github.io/apollo/#/zh/usage/apollo-user-practices) 页面中

**Comment by yazong** [comment]
> 已更新至 [wiki](https://ctripcorp.github.io/apollo/#/zh/usage/apollo-user-practices) 页面中

谢谢

**Comment by yazong** [comment]
> 已更新至 [wiki](https://ctripcorp.github.io/apollo/#/zh/usage/apollo-user-practices) 页面中

您好，由于一些原因，能否将此案例在wiki中移除，抱歉，打扰了。

**Comment by nobodyiam** [comment]
@yazong 可以直接提交 PR 修改 [apollo-user-practices.md](https://github.com/ctripcorp/apollo/blob/master/docs/zh/usage/apollo-user-practices.md)~
