### ISSUE TITLE
请问修改了adminservice的端口，那么portalservice怎么知道adminservice的端口，在哪里配置？

### ISSUE THREAD

**Issue by conansoft** [ctripcorp/apollo#3582]
修改了adminservice下的start.sh的port
那么portalservice里面不是会调用adminservice吗，我在配置里没看到调用adminservice的配置，portalservice怎么知道adminservice的ip和port呢

**Comment by Anilople** [comment]
参考 https://ctripcorp.github.io/apollo/#/zh/design/apollo-design

这是分布式架构，有服务注册和服务发现的环节

并不是通过启动脚本`.sh`文件进行配置的
