### ISSUE TITLE
apollo各服务对机器的性能有什么要求吗

### ISSUE THREAD

**Issue by howHzz** [ctripcorp/apollo#3586]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://ctripcorp.github.io/apollo/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

不是bug,想知道apollo各服务对机器的性能有什么要求吗，比如cpu 内存 磁盘的型号、快慢、大小的要求。还是普通机器就可以胜任，我们项目常用的机器就是2核4G和4核8G的

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by Anilople** [comment]
Reference https://ctripcorp.github.io/apollo/#/zh/misc/apollo-benchmark

**Comment by Anilople** [comment]
This issue will be convert to discussion
