### ISSUE TITLE
bug/疑问：分布式部署Apollo时，configService和adminService部署在同一台机器，出现端口问题

### ISSUE THREAD

**Issue by yourbatman** [ctripcorp/apollo#3587]
- [-] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [-] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [-] 我已经仔细检查过[FAQ](https://ctripcorp.github.io/apollo/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
![image](https://user-images.githubusercontent.com/18030368/110282936-4a5c4c80-801a-11eb-85dc-12185520ef2c.png)
线上采用分布式部署方式，每台机器部署一个configService和adminService，什么配置都不改，但adminService的端口变成了8080，导致访问失败

**期望**
能够姜块修复。对了：我使用的版本是最新的1.8.1版本

**Comment by klboke** [comment]
你好，我这边使用1.8.1 的代码没发现你的情况，可以贴下本机访问 http://localhost:8080/ 的结果么

**Comment by yourbatman** [comment]
> 你好，我这边使用1.8.1 的代码没发现你的情况，可以贴下本机访问 http://localhost:8080/ 的结果么
本机启动貌似没问题：
![image](https://user-images.githubusercontent.com/18030368/110303395-4c7fd480-8035-11eb-8530-388e599537b0.png)


线上部署就所有homePageUrl的端口都成8080了。我现在是采用写死-D写死homePageUrl的方式来让可用的

**Comment by nobodyiam** [comment]
home page url 里面是包含端口的，看下自己的配置吧。
另外，如果只是想改 IP，不想改端口的话，可以参考下[1.4.2 指定要注册的IP](https://ctripcorp.github.io/apollo/#/zh/deployment/distributed-deployment-guide?id=_142-%e6%8c%87%e5%ae%9a%e8%a6%81%e6%b3%a8%e5%86%8c%e7%9a%84ip)
