### ISSUE TITLE
关于.NETCORE3.1使用apollo异常问题

### ISSUE THREAD

**Issue by a194259440** [ctripcorp/apollo#3588]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://ctripcorp.github.io/apollo/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

简洁明了地描述一下bug
当使用.NETCORE3.1的项目在初次运行时，会发生错误
**复现**

通过如下步骤可以复现：

1. 创建.netcore3.1web项目
2. 在项目中引用Com.Ctrip.Framework.Apollo.Configuration 2.4.1
3. 在startup中使用apollo
4. 运行项目即复现

**期望**

简介明了地描述你希望正常情况下应该发生什么
在.netcore2.2上，项目可正常运行，希望.netcore3.1也能支持，以便于后续升级成.netcore5.0
**截图**

如果可以，附上截图来描述你的问题
![1615201288(1)](https://user-images.githubusercontent.com/43952916/110313185-0b8dbd00-8041-11eb-8ce3-6b4a1c0f3807.jpg)
![1615201302(1)](https://user-images.githubusercontent.com/43952916/110313188-0cbeea00-8041-11eb-80d1-8b4d7ef46f09.jpg)

### 额外的细节和日志

- 版本 Com.Ctrip.Framework.Apollo.Configuration 2.4.1
- 错误日志 System.TypeLoadException:“Method 'get_Secret' in type 'Com.Ctrip.Framework.Apollo.ApolloOptions' from assembly 'Com.Ctrip.Framework.Apollo.Configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=6cdd45170aaef7fc' does not have an implementation.”
- 配置：I5-8400
- 平台和操作系统 windows

**Comment by nobodyiam** [comment]
麻烦到 https://github.com/ctripcorp/apollo.net 提交下这个 issue 吧

**Comment by a194259440** [comment]
好的，已提交
