### ISSUE TITLE
配置和服务需要同步更新，不同步会出错。请教下，应该如何做

### ISSUE THREAD

**Issue by howHzz** [ctripcorp/apollo#3591]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://ctripcorp.github.io/apollo/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

场景：1个服务有n个节点，配置位于apollo上。服务启动方式为热部署，即节点依次启动，这样升级服务的时候，保证服务持续可用。
需求：需要同步更新服务代码和配置。启动新服务的才加载新配置。不同步修改会出错。

问题：先修改配置中心的配置，但是这时候服务为旧服务，旧服务拉取到新配置，用户访问，会报错。

解决方式: 1.可以在配置中心关闭热更新。然后添加新配置，因为关闭了热更新，旧服务拉取到新配置，也不会热更新，所以不会报错。2.部署新服务，启动新服务的时候，会加载新配置启动，所以新服务启动后，也不会有问题。
3.新服务全部启动后，将配置中心的热更新开关打开。

存在的问题：没法在配置中心通过配置灵活控制热更新的开关。apollo.autoUpdateInjectedSpringProperties只是控制是否添加对应监听器，没法实现这个功能

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by howHzz** [comment]
这是我想的解决方式， 请教下各位大佬，针对这种问题，有没有现成的解决方案

**Comment by Anilople** [comment]
试试灰度功能？旧服务全部使用灰度配置？

---

话说为什么新服务读到旧配置会出问题？

那原来的旧服务要怎么处理？

**Comment by howHzz** [comment]
场景：旧配置文件某一配置为加密后的字符串，旧代码会对字符串进行解密，然后进行下边的运算。然后新配置把这一配置改成解密后的原文，新代码不再对该配置解密。
问题：只要代码和配置不同步修改，就会出现解密方面的问题。
灰度是不行的。灰度也不能保证配置和代码同步更新。
要是apollo可以在配置中心界面通过修改配置，灵活地开关热更新，就能解决这个问题。

**Comment by nobodyiam** [comment]
首先，我觉得这个场景可能不太合理，这样对运维要求太高了，比如当新版本发布发现有问题的时候，是否能快速回滚？还是说要考虑到先把配置给回滚了？

一般对这种场景的处理建议是新增一个配置项，这样对同一份配置，新老代码都是兼容的，更利于灰度测试和回滚。
如果实在不想新增配置项，那么可以考虑新的代码指定新的集群，这样新老两个集群的配置在 apollo 中是可以独立配置的
