### ISSUE TITLE
查看apollo源码之后的关于性能的俩个疑惑

### ISSUE THREAD

**Issue by yuyu414** [ctripcorp/apollo#3592]
关于客户端更新配置的过程：
      如果有该客户端关心的配置发布，调用DeferredResult的setResult方法，传入有配置变化的namespace信息返回。客户端从返回的结果中获取到配置变化的namespace后，去请求Config Service获取该namespace的最新配置。
 问题一：为什么不在通知消息中直接把变更内容带过去message，而需要重新获取？
 问题二：在不考虑分布式的部署的情况下，假如关心这个变化的客户端有1万台，同时去请求Config Service获取该namespace的最新配置是否造成瞬时流量的飙升。导致性能不稳定？
 最近想公司内部想做自己的轻量级的配置中心，所在在参考apollo，也是摸着石头过河。这俩个疑惑想听听作者的想法，或者这么做有特定场景的考量，希望能得到一些宝贵的经验。谢谢

**Comment by yuyu414** [comment]
明白了

**Comment by wenbochang888** [comment]
> 问题一，可以参考 [#2582](https://github.com/apolloconfig/apollo/issues/2582)，主要的考虑点一个是幂等，另一个是实现简单 问题二，服务端发现有大量客户端的时候，会分批通知，避免惊群效应

@nobodyiam 请教一个问题，如果客户端为10w，分批通知。假设先通知到了1w台客户端，那么9w台还是旧值。
此时用户请求到的数据就不一致了，这个如何保证呢？
