### ISSUE TITLE
关联公用namespace以后，新增配置的按钮是隐藏的，这是怎么回事？

### ISSUE THREAD

**Issue by conansoft** [ctripcorp/apollo#3598]
想测试配置覆盖的功能，A应用创建了一个关联namespace，集成了B应用的公用namesapce，此时，能在A应用中看到B应用的公用namespace，但是想进行覆盖，却没有新增配置的按钮，查看html，发现这个按钮是隐藏状态的，namespace的权限也配置了，使用的是默认apollo/admin的账号，请问怎么能让这个按钮显示？

**Comment by nisiyong** [comment]
什么版本的Apollo？是不是namespace没有给自己加修改权限？

**Comment by revolyw** [comment]
我也遇到了同样的问题，想知道什么情况下会隐藏「新增配置」的按钮？

**Comment by nobodyiam** [comment]
@revolyw 需要有 namespace 的编辑权限才会展示新增配置按钮
