### ISSUE TITLE
apollo接入ldap之后，ldap账户登录不进去，原来系统账户叶登录不进去

### ISSUE THREAD

**Issue by hansonhantong** [ctripcorp/apollo#3601]

**Comment by hansonhantong** [comment]
spring:
  ldap:
    base: "dc=wxlabs,dc=cn"
    username: "cn=manager,dc=wxlabs,dc=cn"
    password: "xxx"
    searchFilter: "uid={0}"
    urls:
    - "ldap.xxxs.cn:389"
ldap:
  mapping:
    objectClass: "inetOrgPerson"
    loginId: "uid"
    rdnKey: "uid"
    userDisplayName: "displayName"
    email: "mail"
  group:
    objectClass: "posixGroup"
    groupBase: "ou=group"
    groupSearch: "(&(cn=apollo))"
    groupMembership: "memberUid"

**Comment by nobodyiam** [comment]
应该是配置问题吧，可以先尝试简化下，比如 group 相关的配置去除试试

**Comment by hansonhantong** [comment]
之前没用组直接用的上面两个配置也是不行的
