### ISSUE TITLE
feign的配置如何继承到apollo里

### ISSUE THREAD

**Issue by cwtree** [ctripcorp/apollo#3603]
@FeignClient(name = "k8s-order", url = "${cube.boot.order-find-url}")
@Component
public interface MyRpc {

	@GetMapping("/find/{id}")
	public String order(@PathVariable Long id);

}

如上的url配置，如何能够利用上apollo的配置热更新，而且，通过一个config类.get方法去获取这个配置可否？
@Getter
@Setter
@ToString
@Component
@ConfigurationProperties(prefix = "cube.boot")
@RefreshScope
public class MyConfig {

	private String orderFindUrl;

}
把feign改成如下
@FeignClient(name = "k8s-order", url = myConfig.getxxxx)

不知道apollo如何支持，感谢！

**Comment by nobodyiam** [comment]
feign client 初始化读取配置直接用 spring 的 placeholder 就可以了，不过热更新还需要 feign client 自己有方法能设置 url。
如果 feign client 没有相关支持的话，可以看下是否能对 @FeignClient 叠加 @RefreshScope。

**Comment by luoyonghui55** [comment]
FeignClient中的URL配置怎么让它生效的？
