### ISSUE TITLE
apollo在上万每秒的读的场景下会导致CPU飙升。

### ISSUE THREAD

**Issue by superzjcy** [ctripcorp/apollo#3604]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://ctripcorp.github.io/apollo/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

我们的业务开了20个线程，每秒上万次的读场景下，CPU飙升至600%左右(8核），通过堆栈看都阻塞在HashTable获取配置方法调用。堆栈信息如下：

"otherCheckExecutor-0" #79 prio=5 os_prio=0 tid=0x00007f9b04040000 nid=0x62f8 waiting for monitor entry [0x00007f9be94df000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at java.util.Hashtable.get(Hashtable.java:363)
        - waiting to lock <0x0000000603fe6fe8> (a java.util.Properties)
        at java.util.Properties.getProperty(Properties.java:969)
        at com.ctrip.framework.apollo.internals.DefaultConfig.getProperty(DefaultConfig.java:77)

**复现**

通过如下步骤可以复现：
1.  开启多个线程。（建议20个以上)
2.  模拟高并发读取配置 (上万tps以上）

**期望**

在高并发读的场景，性能不会出现瓶颈。

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by Anilople** [comment]
可以参考 https://ctripcorp.github.io/apollo/#/zh/design/apollo-design

>客户端和服务端保持了一个长连接，从而能第一时间获得配置更新的推送。（通过Http Long Polling实现）
客户端还会定时从Apollo配置中心服务端拉取应用的最新配置。
这是一个fallback机制，为了防止推送机制失效导致配置不更新
客户端定时拉取会上报本地版本，所以一般情况下，对于定时拉取的操作，服务端都会返回304 - Not Modified
定时频率默认为每5分钟拉取一次，客户端也可以通过在运行时指定System Property: apollo.refreshInterval来覆盖，单位为分钟。


如果要提高性能，可以打开config service的缓存

[config-service.cache.enabled - 是否开启配置缓存](https://ctripcorp.github.io/apollo/#/zh/deployment/distributed-deployment-guide?id=_323-config-servicecacheenabled-%e6%98%af%e5%90%a6%e5%bc%80%e5%90%af%e9%85%8d%e7%bd%ae%e7%bc%93%e5%ad%98)

要诊断性能，还可以使用 https://arthas.aliyun.com/doc/profiler.html

**Comment by nobodyiam** [comment]
目前客户端使用的是 Properties 对象，继承自 Hashtable，由于方法是 synchronized 的，所以在大量读的时候确实会存在如上描述的现象。
短期 workaround 可以在拿到配置后先存在自己的对象中，然后通过 change listener 来更新，长期方案可能要考虑重构下客户端使用的 Properties 对象。
