### ISSUE TITLE
关于apollo页面查询问题

### ISSUE THREAD

**Issue by diwenzheng** [ctripcorp/apollo#3612]
![image](https://user-images.githubusercontent.com/60613511/112084405-b1096a80-8bc3-11eb-96b6-2f24afe74249.png)
我目前使用的是mycat的数据库中间件,这里的查询会出现问题,导致在选择更多的查询到的是重复的东西.

**Comment by diwenzheng** [comment]
@nobodyiam  这块有点头疼 能否帮忙定位一下 谢谢

**Comment by diwenzheng** [comment]
初步认定为 分页查询的问题,apollo这里用到的分页查询 好像有不兼容的地方,当我使用 0,20分页 就可以显示出我所有的.但是按照目前apollo的逻辑,默认是0,10 但是在使用1,10的时候查询重复.

**Comment by diwenzheng** [comment]
![image](https://user-images.githubusercontent.com/60613511/112085613-cf706580-8bc5-11eb-8f66-63768b3c0a2e.png)
这里的逻辑

**Comment by diwenzheng** [comment]
我们自己服务也有分页查询的逻辑,没有bug的. 这里用的是什么查询方式？

**Comment by nobodyiam** [comment]
apollo 是基于 spring jpa 实现的，其实就是普通的分页查询，可以设置 `spring.jpa.properties.hibernate.show_sql=true` 看下最终生效的 sql 语句或者开启下 debug 日志应该也可以

**Comment by diwenzheng** [comment]
是不是 没有按照 id 或者什么分组排序

**Comment by nobodyiam** [comment]
看代码是没指定排序，默认是按照 id 排序的吧
