### ISSUE TITLE
本地环境使用getConfigFile的方法无法获取文件内容

### ISSUE THREAD

**Issue by xiaocy001** [ctripcorp/apollo#3616]
- [√] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [√] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [√] 我已经仔细检查过[FAQ](https://ctripcorp.github.io/apollo/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

本地环境[ env = Local ]使用getConfigFile的方法尝试获取content时，提示缓存文件不存在
而使用测试环境[ env = FAT ]，则可以正常获取

在本地使用getConfig获取application.properties的配置时，不会提示缓存文件不存在，而使用getConfigFile获取时，一样提示缓存文件不存在

期间有尝试手动创建缓存文件后，可以获取，但是格式需要转换为 content={json} 才能获取。

**复现**
![image](https://user-images.githubusercontent.com/26619980/112119285-327af000-8bf8-11eb-9486-88cfead6d764.png)
![image](https://user-images.githubusercontent.com/26619980/112119382-49214700-8bf8-11eb-832b-ff56d8423ef9.png)
![image](https://user-images.githubusercontent.com/26619980/112119556-72da6e00-8bf8-11eb-85d7-7f3c267b5444.png)
![image](https://user-images.githubusercontent.com/26619980/112120443-31968e00-8bf9-11eb-9249-20bc403fd258.png)

**期望**

希望在本地环境能够直接读取../META-INF/config下的配置文件

### 额外的细节和日志

- 版本：apollo-client  1.8.0
- 错误日志  ：com.ctrip.framework.apollo.internals.AbstractConfigFile.initialize(AbstractConfigFile.java:58):Init Apollo Config File failed - namespace: dbconfig.json, reason: Load config from local config failed! [Cause: Cannot read from local cache file C:\opt\data\xxx\config-cache\xxx+default+dbconfig.json.properties].
- 配置：
- 平台和操作系统：window10

**Comment by nobodyiam** [comment]
目前确实还不支持，这个场景应该主要是在本地开发时才用到？可以考虑通过放在 C:\opt\data\xxx\config-cache\xxx+default+dbconfig.json.properties 来实现？

**Comment by xiaocy001** [comment]
每个环境都会用到，但是只有本地环境会有问题。
目前是只能通过手动在C:\opt\data下新建缓存文件来实现，只是多人开放的时候如果碰到配置更新会比较麻烦。
