### ISSUE TITLE
客户端配置的AppId大小写与服务端不一致时可越过accessKey检查而直接获取到配置

### ISSUE THREAD

**Issue by supershania** [ctripcorp/apollo#3626]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://ctripcorp.github.io/apollo/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

由于config service大小写不敏感，而导致客户端配置的AppId大小写与服务端不一致时可越过accessKey检查而直接获取到配置；
或直接通过postman等工具获取到配置文件；

**复现**

通过如下步骤可以复现：

1. apollo开启访问秘钥
2. 客户端配置 -Dapp.id={此处与portal配置的大小写不一致}
3. 客户端不配置 accessKey
4. 启动应用可以成功获取到配置（或使用postman直接请求）

**期望**

返回401而不是配置

**截图**

![2](https://user-images.githubusercontent.com/26797915/113466389-0409da00-946e-11eb-9209-374bb9548f72.png)
![6](https://user-images.githubusercontent.com/26797915/113466434-61059000-946e-11eb-8219-c793bd7f29b2.png)
![1](https://user-images.githubusercontent.com/26797915/113466395-0835f780-946e-11eb-8795-0ca3a46e7561.png)
![3](https://user-images.githubusercontent.com/26797915/113466390-05d39d80-946e-11eb-9caf-aa50d2e6f588.png)
![4](https://user-images.githubusercontent.com/26797915/113466392-0704ca80-946e-11eb-8547-b35fbae387c6.png)
![5](https://user-images.githubusercontent.com/26797915/113466393-079d6100-946e-11eb-9a65-b46344e94cec.png)

### 额外的细节和日志

- 版本：服务端1.8.1；客户端1.8.0

**Comment by studyzhanglei** [comment]
> * [x]  我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
> * [x]  我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
> * [x]  我已经仔细检查过[FAQ](https://ctripcorp.github.io/apollo/#/zh/faq/common-issues-in-deployment-and-development-phase)
> 
> **描述bug**
> 
> 由于config service大小写不敏感，而导致客户端配置的AppId大小写与服务端不一致时可越过accessKey检查而直接获取到配置；
> 或直接通过postman等工具获取到配置文件；
> 
> **复现**
> 
> 通过如下步骤可以复现：
> 
> 1. apollo开启访问秘钥
> 2. 客户端配置 -Dapp.id={此处与portal配置的大小写不一致}
> 3. 客户端不配置 accessKey
> 4. 启动应用可以成功获取到配置（或使用postman直接请求）
> 
> **期望**
> 
> 返回401而不是配置
> 
> **截图**
> 
> ![2](https://user-images.githubusercontent.com/26797915/113466389-0409da00-946e-11eb-9209-374bb9548f72.png)
> ![6](https://user-images.githubusercontent.com/26797915/113466434-61059000-946e-11eb-8219-c793bd7f29b2.png)
> ![1](https://user-images.githubusercontent.com/26797915/113466395-0835f780-946e-11eb-8795-0ca3a46e7561.png)
> ![3](https://user-images.githubusercontent.com/26797915/113466390-05d39d80-946e-11eb-9caf-aa50d2e6f588.png)
> ![4](https://user-images.githubusercontent.com/26797915/113466392-0704ca80-946e-11eb-8547-b35fbae387c6.png)
> ![5](https://user-images.githubusercontent.com/26797915/113466393-079d6100-946e-11eb-9a65-b46344e94cec.png)
> 
> ### 额外的细节和日志
> * 版本：服务端1.8.1；客户端1.8.0

哥们，你这个issue提的真有水平，给你点个赞
