### ISSUE TITLE
之前实现的 Nodejs client, 可以申请放到 wiki 下么

### ISSUE THREAD

**Issue by zhangxh1023** [ctripcorp/apollo#3631]
https://github.com/zhangxh1023/apollo-node-client

之前差不多只有自己用，这两天增加了密钥功能。

**Comment by Anilople** [comment]
Welcome!
> 欢迎



This Nodejs client will be added to document when PR #3632 merged
> 这个Nodejs客户端当PR #3632 被合并后，会被加到文档中
