### ISSUE TITLE
查看集群是出现两个一样的集群

### ISSUE THREAD

**Issue by taidixiong** [ctripcorp/apollo#3635]
<img width="530" alt="WeChat67e3bee98123892e05eb29fba69e86b9" src="https://user-images.githubusercontent.com/14289101/114427511-bb7cba00-9bed-11eb-8a60-96fe0d72cac2.png">

这是我的请求
http://域名/apps/test/envs/dev/clusters/default

返回值
{"exception":"org.springframework.dao.IncorrectResultSizeDataAccessException","message":"query did not return a unique result: 2; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 2","status":500.0,"timestamp":"2021-04-13T00:10:08.555"}

**Comment by nisiyong** [comment]
应该是脏数据，删除掉重建试试

**Comment by taidixiong** [comment]
试过直接删除掉项目，重新创建一样名字的项目。新创建出来的项目直接就会出现两个重复的相同的集群。

**Comment by nobodyiam** [comment]
@taidixiong 管理员工具 - 系统信息看一下？另外，default 集群是默认创建的，不是你自己创建的吧？

**Comment by taidixiong** [comment]
不是我自己创建的,看起来是没有问题的。我只是用了一个dev环境，没有创建其他环境。
![Lark20210414201049](https://user-images.githubusercontent.com/14289101/114708113-8db68300-9d5d-11eb-8822-0f65f623d652.png)

**Comment by nobodyiam** [comment]
看一下系统参数 apollo.portal.envs 的配置，看现象像是启用了多个环境，但是背后连接的是同一个 apolloconfigdb

**Comment by taidixiong** [comment]
![image](https://user-images.githubusercontent.com/14289101/114968690-7389bb80-9ea9-11eb-87e7-086657018c09.png)
你好，这个是我的apollo.portal.envs的信息，只展示了一条dev环境数据。

**Comment by nobodyiam** [comment]
Cluster 表有两条重复数据确实是异常了，看时间相差了 7 秒，所以也不是并发插入所致，是否有其它因素导致？另外可以再看下 Audit 表

**Comment by nobodyiam** [comment]
可以清除的，建表索引之前由于是软删，所以没有加唯一键，确实有打算加上唯一键，不过由于涉及到较大的 schema 操作，所以暂未提交 pr

**Comment by nisiyong** [comment]
@nobodyiam 如果软删除需要加唯一索引，可以考虑新加字段`DataChange_DeletedTime`来替代`IsDeleted`。用时间戳代表删除可以避免单一的Boolean值限制了唯一索引的设置。

**Comment by nobodyiam** [comment]
@nisiyong 我之前的想法是在 `IsDeleted` 之外，再增加一个 `DataChange_DeletedTime` 字段来做唯一索引，你的意思是只用 `DataChange_DeletedTime` 就够了？

**Comment by nisiyong** [comment]
是啊，我这边的场景也过软删除。不过用的是`Long deleteAt;`，存了删除时间的毫秒值，默认值为0代表未删除，每次删除了直接把当前的时间戳更新进去即可。

查询时，只查`deleteAt=0`的，该字段也可以作为联合唯一索引最后一个字段。

**Comment by nobodyiam** [comment]
@nisiyong 恩，如果是新项目的话应该一个字段就够了，对 apollo 而言，考虑到升级过程中的兼容性，应该还是要增加一个`DataChange_DeletedTime`字段的？

**Comment by nisiyong** [comment]
@nobodyiam 是的，对于Apollo而言兼容性很重要，所以个人建议新增字段`DeleteAt bigint`而非`DataChange_DeletedTime datetime`，考虑要做唯一索引的字段，建议还是简单的数据类型

**Comment by nobodyiam** [comment]
@nisiyong 

我想了下可能还有一个点需要注意下，对于新的数据可以用毫秒数实现唯一性，不过对于已有的数据如果升级的话，需要考虑如何为`DeleteAt`赋值，一种方式是把`DataChange_LastTime`转成毫秒数，不过这个精度目前是秒，可能会产生唯一键冲突，另一种或许可以考虑把`Id`取负值给到`DeleteAt`，这个好处是能确保唯一性，不好的地方是就不是毫秒数了。不知你是否有兴趣尝试实现一下？

**Comment by nisiyong** [comment]
> 考虑如何为`DeleteAt`赋值，一种方式是把`DataChange_LastTime`转成毫秒数，不过这个精度目前是秒，可能会产生唯一键冲突，另一种或许可以考虑把`Id`取负值给到`DeleteAt`，这个好处是能确保唯一性，不好的地方是就不是毫秒数了。

一般来说，我倾向于第一种。但是考虑到每家公司都独立部署维护数据库，我们无法感知他们都数据实际情况，所以我认为id的负数是比较好的方式我认为id的负数是比较好的方式。虽然感觉有点别扭，但是要加入唯一索引特性，这也只是过渡阶段的设计，而且还能识别出哪些数据是被清晰过的，**兼容性放在第一位**。

实现的话问题不是很大，因为我这边刚好就是用JPA实现的DeleteAt，主要考虑哪些表要做些处理，应该不只是集群表。

**Comment by nobodyiam** [comment]
@nisiyong 这个如果要实现的话，应该是要涵盖所有有`IsDeleted`字段的表

**Comment by nisiyong** [comment]
@nobodyiam 让我对整体的实现梳理一下。PTAL

## 开发步骤

### 1. 在所有包含`IsDeleted`字段的表都统一加上`DeleteAt`字段

```
ALTER TABLE `xxx` 
ADD COLUMN `DeleteAt` BIGINT(20) NOT NULL DEFAULT 0 AFTER `IsDeleted`;
```

### 2. 修改存储层相关实现
 
- **删除逻辑**：由原来的`set IsDeleted=1` 改为 `set  DeletedAt=${currentTimeMillis}, IsDeleted=1`
- **查询逻辑**：由原来的`where IsDeleted=0`改为`where (DeleteAt=0 and IsDeleted=0)`

> 注意：currentTimeMillis为当前时间毫秒值，可以直接用`System.currentTimeMillis()`在应用层生成

### 3. 清洗数据，添加唯一索引

设置所有已删除的数据的DeleteAt字段初始值为**主键Id的负数**

```
UPDATE `xxx` SET `DeleteAt`=-Id, `IsDeleted`=0 WHERE `IsDeleted`=1;
```

### 4. 大版本升级去除IsDeleted字段（可后续考虑）

- 先修改改存储层相关实现，去除`IsDeleted`相关逻辑
  - **删除逻辑**：由原来的`set  DeletedAt=${currentTimeMillis}, IsDeleted=1`改为`set  DeletedAt=${currentTimeMillis}。
  - **查询逻辑**：由原来的`where (DeleteAt=0 and IsDeleted=0)`改为`where DeleteAt=0`

- 执行DDL，删除`IsDeleted`字段
  ```
  ALTER TABLE `xxx` 
  DROP COLUMN `IsDeleted`;
  ```

## 用户升级部署注意事项

### 添加DeleteAt字段

1. 执行添加字段的DDL
2. 依次部署新版版的configservice, adminservice, portal
3. 执行DML清洗历史数据
4. 执行DDL修改索引字段

### 删除IsDeleted字段（可后续考虑）

1. 依次部署新版版的configservice, adminservice, portal
2. 执行删除字段的DDL
