### ISSUE TITLE
开启config自带eurka 认证后，portal的meta servr该如何修改

### ISSUE THREAD

**Issue by WillZaan** [ctripcorp/apollo#3636]
开启config自带eurka 认证后，portal的meta servr该如何修改

#开启基于HTTP basic的认证
spring.security.basic.enable=true
spring.security.user.name=**
spring.security.user.password=****

目前启动报 401 错误，就是没有权限，不知道账号密码该怎么附上

**Comment by WillZaan** [comment]
![Uploading image.png…]()

**Comment by nobodyiam** [comment]
portal 的 meta server 不用调整，apolloconfigdb.serverconfig 中的 eureka.service.url 需要配置上用户名和密码，比如http://admin:admin@192.168.0.204:8761/eureka/
