### ISSUE TITLE
使用apollo多namespace，每个namespace配置多了之后，管理页面打开特别慢

### ISSUE THREAD

**Issue by chenhaitong** [ctripcorp/apollo#3641]
**描述bug**
当我用apollo多个private namespace解决多语言问题时，发现一旦namespace里配置项过多，加载就特别慢，即便是打开页面会把namespace内具体配置项收拢，但加载时是同时完成
**复现**
在某个应用下，添加三个private namespace，每个粘贴700+条配置项。然后尝试刷新页面
**建议**
是否可以尝试当展开某个namespace时才正式加载？

**Comment by nobodyiam** [comment]
目前的实现是 namespace 数量在 3 个以上会自动收缩，当 namespace 数量超过 10 个会进入懒加载模式

https://github.com/ctripcorp/apollo/blob/b0173d751e5637069e516c0edbbd25631816b70e/apollo-portal/src/main/resources/static/config.html#L213-L214

![image](https://user-images.githubusercontent.com/837658/115637307-6ace3500-a342-11eb-86bc-5f608c64081d.png)

**Comment by chenhaitong** [comment]
可以尝试一下，我有dev、sit、uat、prd 四个环境，每个环境1个application的namespace、3个自定义的private的namespace，实际测试打开任意一个环境配置界面，加载都要很长时间。后面开始删除namespace，当我把dev、sit的namespace删除后，明显感觉uat、prd配置界面加载速度变快了。

**Comment by nobodyiam** [comment]
> 当我把dev、sit的namespace删除后，明显感觉uat、prd配置界面加载速度变快了。

每个环境都是从各自环境读取配置的，dev, sit 的 namespace 删除应该不会影响到 uat 和 prd 的，你是否是把 private 的 namespace 从所有环境都删除了？
