### ISSUE TITLE
Could not find available meta server for configured meta server addresses

### ISSUE THREAD

**Issue by zhangyinyuan** [ctripcorp/apollo#3648]
- [x] 我已经检查过生产机器上使用curl访问apollo是正常的  

**描述bug**

生产环境运行了将近半个月的程序， 突然报错如下：
```log
2021-04-24 22:00:58.099 WARN  com.ctrip.framework.apollo.core.MetaDomainConsts [Apollo-MetaServiceLocator-1] Could not find available meta server for configured meta server addresses: http://10.100.40.105:8080,http://10.x.x.106:8080, fallback to: http://10.x.x.106:8080


```
**复现**

通过如下步骤可以复现：

1. 第一次遇见，不知道如何复现

**Comment by nobodyiam** [comment]
可以看下是否一直在报还是偶尔一次？看错误信息是 http://10.100.40.105:8080 这个在报错的时间段连不上，所以就自动切换到 http://10.x.x.106:8080 了

**Comment by zhangyinyuan** [comment]
首先，感谢您的回复，
这个错误，偶尔出现， 重启之后立马就OK了。不知道以后还会不会再次爆发~



***@***.***
 
From: Jason Song
Date: 2021-04-29 07:56
To: ctripcorp/apollo
CC: bos; Author
Subject: Re: [ctripcorp/apollo] Could not find available meta server for configured meta server addresses (#3648)
可以看下是否一直在报还是偶尔一次？看错误信息是 http://10.100.40.105:8080 这个在报错的时间段连不上，所以就自动切换到 http://10.x.x.106:8080 了
