### ISSUE TITLE
如何关闭 tmp 目录下打日志问题

### ISSUE THREAD

**Issue by gy09535** [ctripcorp/apollo#3649]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://ctripcorp.github.io/apollo/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

日志文件已经通过修改 startup.sh 文件改掉了，但是发现日志文件同时还会打到 tmp 目录下，对比了一下两边日志内容几乎是一致的。这两个日志文件的区别是什么？ 以及如何关闭 tmp 目录下日志？

**Comment by nobodyiam** [comment]
tmp 目录下的是 stdout 日志，可以修改 apollo-configservice.conf 文件中的 LOG_FOLDER 属性。
可以考虑升级到最新版本，已经不会输出重复日志了。
