### ISSUE TITLE
关于app.properties配置文件的疑惑

### ISSUE THREAD

**Issue by DogerRain** [ctripcorp/apollo#3650]
看了一下Apollo-Demo和readme客户端的接入文档，有个感悟就是：
虽然作者的初衷是可以通过多种方法进行配置，但是给人的感觉就是 特别“乱”。

不知道接入的小伙伴有没有这个共鸣，比如我接入spring项目（非springboot项目）
1、metaServer、appid 可以配置在 vm参数、app.properties 
2、但是cluster就不能配置在a在app.properties，需要通过System.setProperty，或者vm，而且也可以 通过创建一个新的文件 server.properties 进行设置，到这里就感觉有点乱了

如果把所有的 metaServer、appid、cluster 都放在一个配置文件，会不会更好一点？

这是目前我接入遇到的一点麻烦。

**Comment by nobodyiam** [comment]
设计初衷是随环境/部署而改变的配置不应该出现在代码中，而是通过外部环境传入（比如 system property，机器上的文件等），cluster/idc 这些我们认为是环境信息，而 appid 是应用自身信息。
至于 meta server 为啥支持放在 app.properties 里面，主要考虑还是有些公司就一个环境，通过集群来区分各环境的信息，而且该信息一般也不会经常变，所以就支持从 app.properties 读取，不过一般还是建议通过外部环境配置，便于和应用代码解耦。
