### ISSUE TITLE
spring cloud config迁移到apollo

### ISSUE THREAD

**Issue by zznnqq210** [ctripcorp/apollo#3651]
**关于配置同步问题**

apollo可以增加一个配置同步的功能么？把之前用spring cloud config存到git仓库里的配置同步过来，这样把配置中心换成apollo后就可以省一些事情

**Comment by nobodyiam** [comment]
这部分是一次性工作，不建议在 apollo 中实现，可以考虑开发一个单独的迁移工具造福大家~

**Comment by Anilople** [comment]
这里提供一个解决方法

---

将spring cloud config的配置重命名成

```
appId+cluster+application.properties
```
这也是Apollo client的本地缓存命名规则

提前创建好appId

使用bash（curl命令）或者java解析文件名，获得appId clusterName namespaceName

然后调用Portal接口，

https://github.com/ctripcorp/apollo/blob/6deedb3e3f0eb981c66297091a230ffc64d1605b/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/ConfigsImportController.java#L37-L41

在HTTP请求中加入Cookie，导入配置
