### ISSUE TITLE
长轮询报 Invalid timestamp

### ISSUE THREAD

**Issue by sheng-jie** [ctripcorp/apollo#3652]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://ctripcorp.github.io/apollo/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

![](https://user-images.githubusercontent.com/12607748/116342155-b71ee680-a814-11eb-8d39-1ab40bc6db9b.png)

基于最新的Helm Chart（1.8.1）部署Apollo，有指定basepath，从目前的抓包结果看，定时拉取正常，但长轮询不成功，报401，Config-Service 报Invalid timestamp。分析日志发现，日志记录时间和请求头携带的时间戳刚好相差1分钟。

![](https://user-images.githubusercontent.com/12607748/116341676-eaad4100-a813-11eb-9fe0-2b3446c2c72e.png)

有检查客户端和服务端的时区设置，均为GTM+8。

客户端使用：dotnet core sdk： Com.Ctrip.Framework.Apollo.Configuration（2.4.1）

**Comment by klboke** [comment]
检查下长轮询时候的接口地址，是不是直连走负载代理了，而不是连接的服务发现的ip

**Comment by nobodyiam** [comment]
感觉上是客户端和服务端的时间不一致吧，等到机器上看下两边的时间是否就是差了 1 分钟？

**Comment by sheng-jie** [comment]
> 感觉上是客户端和服务端的时间不一致吧，等到机器上看下两边的时间是否就是差了 1 分钟？

这个问题确认过了，客户端和服务端部署在同一个k8s集群里，时间一致。

**Comment by sheng-jie** [comment]
> 检查下长轮询时候的接口地址，是不是直连走负载代理了，而不是连接的服务发现的ip

是的，先走负载均衡，再通过K8S的Ingress转发到对应的Config-Service。

奇怪的是，定时拉取正常，说明负载均衡正常转发，长轮询401，说明请求也正常转发。
感觉长轮询的请求被网络劫持了一分钟一样。😂

**Comment by klboke** [comment]
> > 检查下长轮询时候的接口地址，是不是直连走负载代理了，而不是连接的服务发现的ip
> 
> 
> 
> 是的，先走负载均衡，再通过K8S的Ingress转发到对应的Config-Service。
> 
> 
> 
> 奇怪的是，定时拉取正常，说明负载均衡正常转发，长轮询401，说明请求也正常转发。
> 
> 感觉长轮询的请求被网络劫持了一分钟一样。😂

我们遇到了和你一模一样的情况，通过ingress 转发的会 401，但是客户端按理说通过服务发现直接连接 ip 的啊

**Comment by klboke** [comment]
忘记你是.not 客户端了，好像这个客户端只有直连模式

**Comment by klboke** [comment]
@sheng-jie  嗨，我这边在 ingress 这里有新发现了，你检查下你的 ingress 的这个配置目前配置的是多少 `worker-shutdown-timeout` 。如果小于等于 60s，就将这个值调大一点在试试呢

**Comment by sheng-jie** [comment]
@klboke 谢谢跟进，目前我们采用的是traefik ingress controller，无相关配置。我在研究下dotnet core sdk，看有无线索。

**Comment by sheng-jie** [comment]
@klboke 谢谢跟进，目前我们采用的是traefik ingress controller，无相关配置。我在研究下dotnet core sdk，看有无线索。

**Comment by klboke** [comment]
traefik ingress controller 有没类似的配置，会影响长轮询的请求呢？参考nginx-ingress issue：https://github.com/kubernetes/ingress-nginx/issues/2985

**Comment by klboke** [comment]
已定位并确认是 nginx-ingress 的默认配置：
proxy-stream-next-upstream-tries：3
proxy-read-timeout: 60
导致的问题，造成的现象也和上面描述的吻合。ingress 60s超时，然后发起重试，apollo 判断签名失败返回 401 。将 proxy-read-timeout 设置为 90s，大于 apollo 长轮询的 60s 超时即可。

**Comment by zouyx** [comment]
> 已定位并确认是 nginx-ingress 的默认配置：
> proxy-stream-next-upstream-tries：3
> proxy-read-timeout: 60
> 导致的问题，造成的现象也和上面描述的吻合。ingress 60s超时，然后发起重试，apollo 判断签名失败返回 401 。将 proxy-read-timeout 设置为 90s，大于 apollo 长轮询的 60s 超时即可。

very good

**Comment by sheng-jie** [comment]
@klboke 感谢，的确如此，开始我们以为是traefik-ingress的问题，但未发现相关配置项。最后分析是我们还有一层CLB，将相关参数调整后，测试正常。再次感谢！
