### ISSUE TITLE
Question about Apollo release packaging.

### ISSUE THREAD

**Issue by jjnnzb** [ctripcorp/apollo#3659]
我发现Apollo的Release版本的jar包都是无法用vim或者Windows平台上的7zip等软件打开的，我们有项目需要部署出去，也希望能避免自己的源代码不被人用jd-gui.exe等工具直接查阅。求教这个特性是怎么实现的，谢谢！

**Comment by nobodyiam** [comment]
参考下[Spring Boot Maven Plugin](https://docs.spring.io/spring-boot/docs/2.1.5.RELEASE/reference/html/build-tool-plugins-maven-plugin.html)

**Comment by jjnnzb** [comment]
> 参考下[Spring Boot Maven Plugin](https://docs.spring.io/spring-boot/docs/2.1.5.RELEASE/reference/html/build-tool-plugins-maven-plugin.html)

`              
                <configuration>
                    <executable>true</executable>
                </configuration>
`
感谢大神，经过实践，我发现这个配置是起作用的关键，注释掉这个，Jar包就能正常用压缩软件打开。是这样的么？

**Comment by nobodyiam** [comment]
@jjnnzb 是的，配置这个选项后，在 zip 文件的头部会加入一段 bash 脚本用于启动，你用 vi 编辑一下就能看到。
