### ISSUE TITLE
apollo会额外生成一个与进程相关的日志文件，且内容一直增加不会删除，这个文件是如何生成的？如何移除掉？

### ISSUE THREAD

**Issue by streamfly** [ctripcorp/apollo#3662]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

adminservice 和 configservice 日志里面会额外生成一个 

> 全量写入的日志文件，这个文件会一直增加内容不会删除，最终有可能导致磁盘爆满。
![image](https://user-images.githubusercontent.com/17963187/117282868-c8f92d00-ae97-11eb-8ffd-752b8eb7cfa2.png)

研究代码没发现生成此日志的地方，请给与说明。

- 版本：1.7.1
- 平台和操作系统 centos 7

**Comment by nobodyiam** [comment]
可以升级到 1.8.1 版本解决该问题，修复说明详见 #3488
