### ISSUE TITLE
应用 apollo.bootstrap.namespaces 没有配置application 和 eureka-client-common，每次还是会自动下载

### ISSUE THREAD

**Issue by gotoworld** [ctripcorp/apollo#3663]
应用配置：
apollo.bootstrap.namespaces = TEST1.redis,TEST1.swagger,TEST1.druid,TEST1.db,TEST1.hibernate,TEST1.oss

实际上从apollo 拉取下来的配置，多了两个不在期望里的：application 和 eureka-client-common
![image](https://user-images.githubusercontent.com/8605471/117424992-efc96900-af54-11eb-9ce2-fc7df1c227c4.png)

### 额外的细节和日志

- 版本：Apollo  1.5.1
- 平台和操作系统:  window + linux 容器下 都可复现

**Comment by Anilople** [comment]
可能框架内部指定了使用 eureka-client-common

可以使用DEBUG模式启动，查看一下日志
