### ISSUE TITLE
请问下 apollo 有请求失败次数或者失败率的统计指标么？

### ISSUE THREAD

**Issue by zhangzerui20** [ctripcorp/apollo#3665]
想针对请求的失败情况做告警。

**Comment by nobodyiam** [comment]
参考下 [监控相关](https://www.apolloconfig.com/#/zh/design/apollo-design?id=%e4%ba%94%e3%80%81%e7%9b%91%e6%8e%a7%e7%9b%b8%e5%85%b3)
