### ISSUE TITLE
原生登录功能，登录成功，刷新就退出了

### ISSUE THREAD

**Issue by huanhuan000** [ctripcorp/apollo#3672]
部署方式：使用k8s的服务发现进行部署，portal部署了三个机器
登录方式：apollo自身提供的登录功能 
问题：登录成功后，页面数据不加载，重新刷新一下页面回到了登录页面，反复如此
           当将portal的pod数量降为1个的时候，不会出现这个问题

**Comment by huanhuan000** [comment]
> 原生登录功能需要配置下[session affinity](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_241448-%e4%bb%a5ingress%e9%85%8d%e7%bd%aesession-affinity%e5%bd%a2%e5%bc%8f%e6%9a%b4%e9%9c%b2%e6%9c%8d%e5%8a%a1)

我们公司的k8s中已经取消了ingress控制组件，直接使用了pod+svc映射到了物理网。

**Comment by yinyixie** [comment]
看描述像是一台机器的session 登录态，没有共享给其他机器的原因导致的。

**Comment by nobodyiam** [comment]
@yinyixie 默认的基于 spring security 的登录机制目前状态是单机的，没有在集群间共享
