### ISSUE TITLE
希望helm部署 service类型支持云上的LoadBalancer 

### ISSUE THREAD

**Issue by lyyzwjj** [ctripcorp/apollo#3674]
在使用helm部署的时候 
发现apollo-service的service-configservice.yaml 
不能配置成LoadBalancer暴露config服务  
portal服务也是

期望可以配置成下面酱紫
spec:
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 10.44.1.40

希望
在apollo/scripts/helm/apollo-service/Values配置文件
configService:
  status: {}

在apollo/scripts/helm/apollo-service/templates/service-configservice.yaml 
status:
  {{- toYaml .Values.configService.status | nindent 12 }}

**Comment by JaredTan95** [comment]
Feel free to submit a PR with this change.
