### ISSUE TITLE
Ignoring onDemand update due to rate limiter

### ISSUE THREAD

**Issue by farsunset** [ctripcorp/apollo#3680]
sprongboot 版本2.3.10
springcloud 版本Hoxton.RELEASE
启动时

location:com.netflix.discovery.InstanceInfoReplicator.onDemandUpdate(InstanceInfoReplicator.java:110)
message:Ignoring onDemand update due to rate limiter
thread:DiscoveryClient-InstanceInfoReplicator-0
time:2021-05-13 14:09:34.966

location:com.netflix.discovery.DiscoveryClient$3.notify(DiscoveryClient.java:1323)
message:Saw local status change event StatusChangeEvent [timestamp=1620886174966, current=UP, previous=OUT_OF_SERVICE]
thread:DiscoveryClient-InstanceInfoReplicator-0
time:2021-05-13 14:09:34.966
导致 OUT_OF_SERVICE 变为 UP状态事件被限流 不知道有没有人遇到

**Comment by nobodyiam** [comment]
Is this an apollo issue or simply a spring cloud issue?
