### ISSUE TITLE
helm部署，apollo-portal访问登录页url出现随机端口的跳转

### ISSUE THREAD

**Issue by feiniao886** [ctripcorp/apollo#3687]
部署方式：helm 部署在kubernetes方式

访问方式 ： 公有云LB直接到nodeport形式访问服务， 但访问页面URL中出现随机端口
如下图所示：

**Comment by feiniao886** [comment]
![image](https://user-images.githubusercontent.com/29135686/118441446-cc07df00-b71b-11eb-86d9-621647aff29d.png)

这是哪来的端口。。。

**Comment by nobodyiam** [comment]
贴下 helm 的 values? 
看着像是 nodeport 的端口，页面能正常打开吗？
