### ISSUE TITLE
Apollo如何实现Config配置库Mysql本身的高可用支持

### ISSUE THREAD

**Issue by bg1011** [ctripcorp/apollo#3693]
比如：
Config DB 主备或者读写分离，如何实现主备切换等HA和负载均衡及水平扩展~

多谢~

**Comment by nobodyiam** [comment]
1. 最简单的方式是通过 vip 实现 mysql 主备的切换
2. 如果要实现跨机房的切换，那么可以动态切换下 datasource，类似[dynamic-datasource](https://github.com/ctripcorp/apollo-use-cases/tree/master/dynamic-datasource)
