### ISSUE TITLE
请问是否支持后端启用ssl的mysql 没有找到相关配置

### ISSUE THREAD

**Issue by si7eka** [ctripcorp/apollo#3694]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)
- [x] 我已经仔细检查过https://github.com/ctripcorp/apollo/blob/master/scripts/helm/README.md

**描述bug**

简洁明了地描述一下bug

**复现**

通过如下步骤可以复现：

1. mysql 开启ssl后 通过helm启动异常，关闭ssl后可正常运行
2. 
3. 
4. 

**期望**

简介明了地描述你希望正常情况下应该发生什么

![image](https://user-images.githubusercontent.com/15117469/118770686-318ed380-b8b4-11eb-993b-4bc5266dcd1c.png)
![image](https://user-images.githubusercontent.com/15117469/118770712-3bb0d200-b8b4-11eb-8018-e1b2bfa2d87c.png)

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
配置 `configdb.connectionStringProperties` ?
