### ISSUE TITLE
springboot dubbo动态切换注册中心问题

### ISSUE THREAD

**Issue by yxiaozhou** [ctripcorp/apollo#3703]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

我们在使用springboot(2.1.6） + dubbo(2.5.3) +zookeeper，参考了apollo-use-cases中dynamic-datasource的操作，但是这里有个疑问就是我执行了 this.applicationContext.publishEvent(new EnvironmentChangeEvent(changedKeys));  操作后 如何去重连zk呢，因为使用的是第三方的jar包

            <groupId>com.alibaba.spring.boot</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
，
是需要修改三方jar包里的链接操作么;
 
而且类似的中间件都有类似的问题 比如rabbitmq的spring-boot-starter-amqp的jar包
![image](https://user-images.githubusercontent.com/33828903/119329189-887f1900-bcb7-11eb-8a0e-5ade808a80c7.png)

- 版本：1.5.1

**Comment by nobodyiam** [comment]
apollo 提供的是运行时动态推送配置的能力，实际如何切换数据库、注册中心、MQ 取决于对应中间件 SDK 的实现，数据库这个由于抽象比较好（datasource），所以我们提供了样例代码，其它的场景建议咨询下各自的开源社区，比如 dubbo + zk，建议在 dubbo 项目中讨论下，如果方案可行的话，也希望能提交样例代码到 apollo-use-cases 项目中，造福社区~
