### ISSUE TITLE
SpringBoot2.5 整合 Apollo 1.8.1无法拉取配置文件

### ISSUE THREAD

**Issue by maoxiaoxiong** [ctripcorp/apollo#3710]
1.SpringBoot Version 2.5.0 
Apollo 1.8.1

环境配置 -Denv=DEV

配置文件 application.yml
app
  id: demo          #应用ID                                          
apollo:                                                            
  cacheDir: /opt/data
  #cluster: default                           #指定使用哪个集群的配置         
  meta: http://10.211.55.5:8080       #DEV环境配置中心地址                 
  autoUpdateInjectedSpringProperties: true  #是否开启 Spring 参数自动更新    
  bootstrap:                                                       
    enabled: true                         #是否开启 Apollo             
    # namespaces: application                  #设置 Namespace       
    eagerLoad:                                                     
      enabled: false                      #将 Apollo 加载提到初始化日志系统之前  

2.启动警告： HTTP response code: 503 for URL: http://10.211.55.5:8080/services/config?appId=demo&ip=10.2.208.134
2021-05-26 12:46:05.068  WARN 10229 --- [           main] c.c.f.a.i.AbstractConfigRepository       : Sync config failed, will retry. Repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository, reason: Get config services failed from http://10.211.55.5:8080/services/config?appId=demo&ip=10.2.208.134 [Cause: java.io.IOException: Server returned HTTP response code: 503 for URL: http://10.211.55.5:8080/services/config?appId=demo&ip=10.2.208.134 [Cause: Server returned HTTP response code: 503 for URL: http://10.211.55.5:8080/services/config?appId=demo&ip=10.2.208.134 [Cause: Server returned HTTP response code: 503 for URL: http://10.211.55.5:8080/services/config?appId=demo&ip=10.2.208.134]]]

3.本地执行
curl http://10.211.55.5:8080/services/config?appId=demo&ip=10.2.208.134 
返回结果
[1] 10185

4.浏览器访问
http://10.211.55.5:8080/services/config?appId=demo&ip=10.2.208.134 
返回结果
[
{
appName: "APOLLO-CONFIGSERVICE",
instanceId: "f40d87db7d0c:apollo-configservice:8080",
homepageUrl: "http://172.17.0.4:8080/"
}
]

**Comment by maoxiaoxiong** [comment]
配置文件格式正确 由于贴到这里面 格式发生了变化 配置格式 是没有问题的

**Comment by maoxiaoxiong** [comment]
这里面的8种配置方式都不生效
https://www.apolloconfig.com/#/zh/usage/java-sdk-user-guide?id=_122-apollo-meta-server

最后是这样配置的 是新版本配置发生变化了吗
-Dapollo.configService=http://10.211.55.5:8080

**Comment by nobodyiam** [comment]
`curl -i http://10.211.55.5:8080/services/config?appId=demo&ip=10.2.208.134` 看下

**Comment by maoxiaoxiong** [comment]
@nobodyiam  
curl -i http://10.211.55.5:8080/services/config?appId=demo&ip=10.2.208.134 看下

Response:

[1] 23163
[root@centos-linux7 pulsar-manager]# HTTP/1.1 200 
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: SAMEORIGIN
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Sat, 29 May 2021 19:29:31 GMT

**Comment by nobodyiam** [comment]
@maoxiaoxiong 

之前日志中的报错是服务端返回了 503，不过你这个返回的是 200，两者还是不一样
Cause: Server returned HTTP response code: 503 for URL: http://10.211.55.5:8080/services/config?appId=demo&ip=10.2.208.134

另外，把响应贴全吧，应该是类似下面这样。

curl -i http://106.54.227.205:8080/services/config
```
HTTP/1.1 200
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Sun, 30 May 2021 02:01:05 GMT

[{"appName":"APOLLO-CONFIGSERVICE","instanceId":"172.17.0.13:apollo-configservice:8080","homepageUrl":"http://106.54.227.205:8080/"}]
```

**Comment by maoxiaoxiong** [comment]
`
curl -i http://10.211.55.5:8080/services/config?appId=demo&ip=10.2.208.134 
`

**Comment by maoxiaoxiong** [comment]
1.请求路径：
`curl -i http://10.211.55.5:8080/services/config?appId=demo&ip=10.2.208.134 `

2.响应数据
` [{"appName":"APOLLO-CONFIGSERVICE","instanceId":"f40d87db7d0c:apollo-configservice:8080","homepageUrl":"http://172.17.0.7:8080/"}]`

3. 请求头
`GET /services/config?appId=demo&ip=10.2.208.134 HTTP/1.1
Host: 10.211.55.5:8080
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Connection: keep-alive
Cookie: portainer.LOGIN_STATE_UUID=0e2ef01d-46ae-4218-b29d-13f496bbc17b; _ga=GA1.1.1774120332.1621779851; portainer.datatable_text_filter_home_endpoints=; portainer.datatable_settings_registries=%7B%22open%22%3Afalse%2C%22repeater%22%3A%7B%22autoRefresh%22%3Afalse%2C%22refreshRate%22%3A%2230%22%7D%7D; portainer.datatable_settings_users=%7B%22open%22%3Afalse%2C%22repeater%22%3A%7B%22autoRefresh%22%3Afalse%2C%22refreshRate%22%3A%2230%22%7D%7D; portainer.datatable_settings_roles=%7B%22open%22%3Afalse%2C%22repeater%22%3A%7B%22autoRefresh%22%3Afalse%2C%22refreshRate%22%3A%2230%22%7D%7D; portainer.datatable_settings_groups=%7B%22open%22%3Afalse%2C%22repeater%22%3A%7B%22autoRefresh%22%3Afalse%2C%22refreshRate%22%3A%2230%22%7D%7D; portainer.datatable_settings_tags=%7B%22open%22%3Afalse%2C%22repeater%22%3A%7B%22autoRefresh%22%3Afalse%2C%22refreshRate%22%3A%2230%22%7D%7D; portainer.datatable_settings_networks=%7B%22open%22%3Afalse%2C%22repeater%22%3A%7B%22autoRefresh%22%3Afalse%2C%22refreshRate%22%3A%2230%22%7D%7D; portainer.datatable_settings_images=%7B%22open%22%3Afalse%2C%22repeater%22%3A%7B%22autoRefresh%22%3Afalse%2C%22refreshRate%22%3A%2230%22%7D%7D; portainer.datatable_settings_volumes=%7B%22open%22%3Afalse%2C%22repeater%22%3A%7B%22autoRefresh%22%3Afalse%2C%22refreshRate%22%3A%2230%22%7D%7D; portainer.datatable_settings_containers=%7B%22open%22%3Afalse%2C%22repeater%22%3A%7B%22autoRefresh%22%3Afalse%2C%22refreshRate%22%3A%2230%22%7D%2C%22truncateContainerName%22%3Atrue%2C%22containerNameTruncateSize%22%3A32%2C%22showQuickActionStats%22%3Atrue%2C%22showQuickActionLogs%22%3Atrue%2C%22showQuickActionExec%22%3Atrue%2C%22showQuickActionInspect%22%3Atrue%2C%22showQuickActionAttach%22%3Afalse%7D; portainer.datatable_settings_stacks=%7B%22open%22%3Afalse%2C%22repeater%22%3A%7B%22autoRefresh%22%3Afalse%2C%22refreshRate%22%3A%2230%22%7D%7D; portainer.datatable_text_filter_containers=01ec5b95229a3403e015651471ec9db8331a0ec18bbbaa7dcc3cf3672522fdca; portainer.datatable_text_filter_volumes=01ec5b95229a3403e015651471ec9db8331a0ec18bbbaa7dcc3cf3672522fdca; portainer.datatable_settings_access_registry=%7B%22open%22%3Afalse%2C%22repeater%22%3A%7B%22autoRefresh%22%3Afalse%2C%22refreshRate%22%3A%2230%22%7D%7D; portainer.datatable_settings_events=%7B%22open%22%3Afalse%2C%22repeater%22%3A%7B%22autoRefresh%22%3Afalse%2C%22refreshRate%22%3A%2230%22%7D%7D; portainer.datatable_settings_stack-containers=%7B%22open%22%3Afalse%2C%22repeater%22%3A%7B%22autoRefresh%22%3Afalse%2C%22refreshRate%22%3A%2230%22%7D%2C%22truncateContainerName%22%3Atrue%2C%22containerNameTruncateSize%22%3A32%2C%22showQuickActionStats%22%3Atrue%2C%22showQuickActionLogs%22%3Atrue%2C%22showQuickActionExec%22%3Atrue%2C%22showQuickActionInspect%22%3Atrue%2C%22showQuickActionAttach%22%3Afalse%7D; portainer.datatable_pagination_stack-containers=25; portainer.col_visibility_stack-containers=%7B%22state%22%3A%7B%22open%22%3Atrue%7D%2C%22columns%22%3A%7B%22state%22%3A%7B%22label%22%3A%22State%22%2C%22display%22%3Atrue%7D%2C%22actions%22%3A%7B%22label%22%3A%22Quick%20Actions%22%2C%22display%22%3Atrue%7D%2C%22stack%22%3A%7B%22label%22%3A%22Stack%22%2C%22display%22%3Atrue%7D%2C%22image%22%3A%7B%22label%22%3A%22Image%22%2C%22display%22%3Atrue%7D%2C%22created%22%3A%7B%22label%22%3A%22Created%22%2C%22display%22%3Atrue%7D%2C%22ip%22%3A%7B%22label%22%3A%22IP%20Address%22%2C%22display%22%3Atrue%7D%2C%22host%22%3A%7B%22label%22%3A%22Host%22%2C%22display%22%3Atrue%7D%2C%22ports%22%3A%7B%22label%22%3A%22Published%20Ports%22%2C%22display%22%3Atrue%7D%2C%22ownership%22%3A%7B%22label%22%3A%22Ownership%22%2C%22display%22%3Atrue%7D%7D%7D; JSESSIONID=FE244850F793CD38CCB2E847CB0A9FEE; NG_TRANSLATE_LANG_KEY=zh-CN; XSRF-TOKEN=85b3024b-e038-426d-a451-4ecbb00febf6; 85b3024b-e038-426d-a451-4ecbb00febf6=85b3024b-e038-426d-a451-4ecbb00febf6; Admin-Token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjU0MzFhNzgzYjRjNDcxOWZiYTczMmI4ZGM3MDJkNWY4ODZiNWUyYzI5ZGM5MjQ4YmY3ODc5OTM4ZjIxNGMyNTgxNjIyMzYyMDA1MTYyIiwiZXhwIjoxNjIwNjU5MDM3fQ.qEbvn7Qy9r5pR_XEj3fZALpuyrAof_Z5-nsBsetXrXE; username=admin; tenant=admin; Admin-Environment=demo
Upgrade-Insecure-Requests: 1
Pragma: no-cache
Cache-Control: no-cache`

4.响应头：
`HTTP/1.1 200 
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: SAMEORIGIN
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Sun, 30 May 2021 08:15:15 GMT
Keep-Alive: timeout=60
Connection: keep-alive`

**Comment by nobodyiam** [comment]
看这个贴出来的信息是没问题的，客户端应该是能正常启动的，看下这个 503 报错是不是偶发的？另外也可以看下 config service 的日志，看看在 2021-05-26 12:46:05.068 这个时间段是否有报错？
