### ISSUE TITLE
配置文件内容比对原理？

### ISSUE THREAD

**Issue by andyyumiao** [ctripcorp/apollo#3712]
如题，在配置发布的时候，apollo会显示出文件变更的内容，这里apollo配置文件比对变化的原理是？

**Comment by nobodyiam** [comment]
把编辑态的配置数据和上一次发布的配置做比较

**Comment by andyyumiao** [comment]
> 把编辑态的配置数据和上一次发布的配置做比较

是逐行比较吗？

**Comment by nobodyiam** [comment]
可以看下对应的代码实现
