### ISSUE TITLE
yml格式的namespace查看发布历史时是否能够显示更多明细，例如releasename和comment内容

### ISSUE THREAD

**Issue by rootuserAccount** [ctripcorp/apollo#3715]
**你的特性请求和某个问题有关吗？请描述**
目前properties格式的namespace可以在发布历史页面看到历次发布的详细信息，包括releasename和comment注释等。
但是yml格式的namespace查看发布历史时，就没有这么详细。

**清晰简洁地描述一下你希望的解决方案**

对于yml等其他格式，能否也支持此功能呢？目前只能看到发布者，时间，文件变更明细，没有例如comment等内容。在configdb的release表中是有其他值的。

**清晰简洁地描述一下这个特性的备选方案**

**其它背景**

在这里添加和这个特性请求有关的背景说明、截图

**Comment by nobodyiam** [comment]
我觉得是可以的，这部分数据在前端加载时都已经拿到了，应该改一下前端代码就可以了
@rootuserAccount 你有兴趣提交个 PR 吗？

**Comment by rootuserAccount** [comment]
> 我觉得是可以的，这部分数据在前端加载时都已经拿到了，应该改一下前端代码就可以了
> @rootuserAccount 你有兴趣提交个 PR 吗？

我在本地先做个试验，能否二次开发。感谢提议
