### ISSUE TITLE
配置发布前是否可以做comment内容的检验

### ISSUE THREAD

**Issue by rootuserAccount** [ctripcorp/apollo#3716]
类似git 校验commit message的机制，自定义检查规则，强限制备注内容必须规范化

**Comment by nobodyiam** [comment]
I think we could use some sort of hook mechanism, as was discussed in #1517

**Comment by rootuserAccount** [comment]
> I think we could use some sort of hook mechanism, as was discussed in #1517

Thanks for advice

**Comment by rootuserAccount** [comment]
Thanks

**Comment by xiachaochao** [comment]
> 我认为我们可以使用某种钩子机制，正如在[#1517 中](https://github.com/ctripcorp/apollo/issues/1517)讨论的那样[](https://github.com/ctripcorp/apollo/issues/1517)

我也在做这个校验，对前端页面release_modal.html、item_modal.html的commit文本区域增加了ng-required="true"参数，以达到如果没有输入commit内容，修改或发布按钮被置灰效果。但是我遇到了一个问题，修改了这两处之后，编译打包部署，登陆功能被跳过了，就是说我输入登陆地址后会直接进入系统，跳过了输入账号密码的过程 V1.6.1、1.8.2都有这个情况，希望能够指点一下查错的方向

**Comment by Anilople** [comment]
> > 我认为我们可以使用某种钩子机制，正如在[#1517 中](https://github.com/ctripcorp/apollo/issues/1517)讨论的那样
> 
> 我也在做这个校验，对前端页面release_modal.html、item_modal.html的commit文本区域增加了ng-required="true"参数，以达到如果没有输入commit内容，修改或发布按钮被置灰效果。但是我遇到了一个问题，修改了这两处之后，编译打包部署，登陆功能被跳过了，就是说我输入登陆地址后会直接进入系统，跳过了输入账号密码的过程 V1.6.1、1.8.2都有这个情况，希望能够指点一下查错的方向

和spring的profile有关，需要加入auth的profile

构建时请用build脚本，参考 https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase

在文件夹 scripts 下

**Comment by xiachaochao** [comment]
非常感谢，已经解决。

**Comment by xiachaochao** [comment]
> > > 我认为我们可以使用某种钩子机制，正如在[#1517 中](https://github.com/ctripcorp/apollo/issues/1517)讨论的那样
> > 
> > 
> > 我也在做这个校验，对前端页面release_modal.html、item_modal.html的commit文本区域增加了ng-required="true"参数，以达到如果没有输入commit内容，修改或发布按钮被置灰效果。但是我遇到了一个问题，修改了这两处之后，编译打包部署，登陆功能被跳过了，就是说我输入登陆地址后会直接进入系统，跳过了输入账号密码的过程 V1.6.1、1.8.2都有这个情况，希望能够指点一下查错的方向
> 
> 和spring的profile有关，需要加入auth的profile
> 
> 构建时请用build脚本，参考 https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase
> 
> 在文件夹 scripts 下

非常感谢 已经解决
