### ISSUE TITLE
可否通过环境变量配置灰度读取方式

### ISSUE THREAD

**Issue by shilin3** [ctripcorp/apollo#3745]
现在应用如果部署在docker上时，ip是不固定的，但是可以设置docker的环境变量

可否根据环境变量来推送灰度配置
![image](https://user-images.githubusercontent.com/63432702/120618946-2039ef80-c48e-11eb-9f9d-622a248493af.png)
此部分添加一个根据环境变量来推送配置，是不是更好一点

**Comment by nobodyiam** [comment]
the community already had some discussions on this topic, please refer #2932 for more information and welcome to share your ideas :-)
