### ISSUE TITLE
我想接入公司AD，可是按说明配置完后无法启动Portal

### ISSUE THREAD

**Issue by songyingjie322** [ctripcorp/apollo#3748]
我的Portal运行在winserver2019上，不在startup.sh添加内容可以正常使用，**scripts/startup.sh中添加上 export JAVA_OPTS="$JAVA_OPTS -Dspring.profiles.active=github,ldap"就无法启动了**，我想了解我这样添加有问题吗？
**config/application-ldap.yml内容如下：**
spring:
&nbsp;ldap:
&nbsp;&nbsp;base: "dc=coco,dc=com"
&nbsp;&nbsp;username: "admin"
&nbsp;&nbsp;password: "O0yma#"
&nbsp;&nbsp;searchFilter: "(sAMAccountName={0})"
&nbsp;&nbsp;urls:
&nbsp;&nbsp;- "ldap://10.6.0.30:389"

ldap:
&nbsp;mapping:
&nbsp;&nbsp;objectClass: "user"
&nbsp;&nbsp;loginId: "sAMAccountName"
&nbsp;&nbsp;userDisplayName: "cn"
&nbsp;&nbsp;email: "userPrincipalName"

**启动的日记如下：**
Java HotSpot(TM) 64-Bit Server VM (25.161-b12) for windows-amd64 JRE (1.8.0_161-b12), built on Dec 19 2017 17:52:25 by "java_re" with MS VC++ 10.0 (VS2010)
Memory: 4k page, physical 16776172k(10022292k free), swap 19266540k(12044060k free)
CommandLine flags: -XX:+CMSClassUnloadingEnabled -XX:CMSFullGCsBeforeCompaction=9 -XX:CMSInitiatingOccupancyFraction=60 -XX:+CMSParallelRemarkEnabled -XX:+DisableExplicitGC -XX:+ExplicitGCInvokesConcurrent -XX:GCLogFileSize=5242880 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=E:/Apollo/logs/HeapDumpOnOutOfMemoryError/ -XX:InitialHeapSize=268418752 -XX:MaxHeapSize=4294700032 -XX:MaxNewSize=348966912 -XX:MaxTenuringThreshold=9 -XX:NumberOfGCLogFiles=5 -XX:OldPLABSize=16 -XX:-OmitStackTraceInFastThrow -XX:ParallelGCThreads=4 -XX:+PrintGC -XX:+PrintGCApplicationConcurrentTime -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintHeapAtGC -XX:+ScavengeBeforeFullGC -XX:SoftRefLRUPolicyMSPerMB=0 -XX:+UseCMSCompactAtFullCollection -XX:+UseCMSInitiatingOccupancyOnly -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseConcMarkSweepGC -XX:+UseGCLogFileRotation -XX:-UseLargePagesIndividualAllocation -XX:+UseParNewGC 
2021-06-07T17:18:39.124+0800: 1.054: Application time: 0.8094608 seconds
2021-06-07T17:18:39.296+0800: 1.228: Application time: 0.1734595 seconds
2021-06-07T17:18:39.579+0800: 1.512: Application time: 0.2836042 seconds
2021-06-07T17:18:39.780+0800: 1.722: Application time: 0.2088732 seconds
{Heap before GC invocations=0 (full 0):
 par new generation   total 78656K, used 69952K [0x00000006c0000000, 0x00000006c5550000, 0x00000006d4cc0000)
  eden space 69952K, 100% used [0x00000006c0000000, 0x00000006c4450000, 0x00000006c4450000)
  from space 8704K,   0% used [0x00000006c4450000, 0x00000006c4450000, 0x00000006c4cd0000)
  to   space 8704K,   0% used [0x00000006c4cd0000, 0x00000006c4cd0000, 0x00000006c5550000)
 concurrent mark-sweep generation total 174784K, used 0K [0x00000006d4cc0000, 0x00000006df770000, 0x00000007c0000000)
 Metaspace       used 8066K, capacity 8334K, committed 8448K, reserved 1056768K
  class space    used 905K, capacity 985K, committed 1024K, reserved 1048576K
2021-06-07T17:18:39.780+0800: 1.722: [GC (Allocation Failure) 2021-06-07T17:18:39.780+0800: 1.722: [ParNew: 69952K->4590K(78656K), 0.0142315 secs] 69952K->4590K(253440K), 0.0145713 secs] [Times: user=0.06 sys=0.02, real=0.02 secs] 
Heap after GC invocations=1 (full 0):
 par new generation   total 78656K, used 4590K [0x00000006c0000000, 0x00000006c5550000, 0x00000006d4cc0000)
  eden space 69952K,   0% used [0x00000006c0000000, 0x00000006c0000000, 0x00000006c4450000)
  from space 8704K,  52% used [0x00000006c4cd0000, 0x00000006c514bab0, 0x00000006c5550000)
  to   space 8704K,   0% used [0x00000006c4450000, 0x00000006c4450000, 0x00000006c4cd0000)
 concurrent mark-sweep generation total 174784K, used 0K [0x00000006d4cc0000, 0x00000006df770000, 0x00000007c0000000)
 Metaspace       used 8066K, capacity 8334K, committed 8448K, reserved 1056768K
  class space    used 905K, capacity 985K, committed 1024K, reserved 1048576K
}
2021-06-07T17:18:39.827+0800: 1.759: Application time: 0.0221322 seconds
2021-06-07T17:18:40.499+0800: 2.433: Application time: 0.6739972 seconds
{Heap before GC invocations=1 (full 0):
 par new generation   total 78656K, used 74542K [0x00000006c0000000, 0x00000006c5550000, 0x00000006d4cc0000)
  eden space 69952K, 100% used [0x00000006c0000000, 0x00000006c4450000, 0x00000006c4450000)
  from space 8704K,  52% used [0x00000006c4cd0000, 0x00000006c514bab0, 0x00000006c5550000)
  to   space 8704K,   0% used [0x00000006c4450000, 0x00000006c4450000, 0x00000006c4cd0000)
 concurrent mark-sweep generation total 174784K, used 0K [0x00000006d4cc0000, 0x00000006df770000, 0x00000007c0000000)
 Metaspace       used 12258K, capacity 12612K, committed 12928K, reserved 1060864K
  class space    used 1441K, capacity 1559K, committed 1664K, reserved 1048576K
2021-06-07T17:18:40.499+0800: 2.434: [GC (Allocation Failure) 2021-06-07T17:18:40.499+0800: 2.434: [ParNew: 74542K->3368K(78656K), 0.0364552 secs] 74542K->5937K(253440K), 0.0365955 secs] [Times: user=0.03 sys=0.05, real=0.03 secs] 
Heap after GC invocations=2 (full 0):
 par new generation   total 78656K, used 3368K [0x00000006c0000000, 0x00000006c5550000, 0x00000006d4cc0000)
  eden space 69952K,   0% used [0x00000006c0000000, 0x00000006c0000000, 0x00000006c4450000)
  from space 8704K,  38% used [0x00000006c4450000, 0x00000006c479a100, 0x00000006c4cd0000)
  to   space 8704K,   0% used [0x00000006c4cd0000, 0x00000006c4cd0000, 0x00000006c5550000)
 concurrent mark-sweep generation total 174784K, used 2569K [0x00000006d4cc0000, 0x00000006df770000, 0x00000007c0000000)
 Metaspace       used 12258K, capacity 12612K, committed 12928K, reserved 1060864K
  class space    used 1441K, capacity 1559K, committed 1664K, reserved 1048576K
}
2021-06-07T17:18:41.454+0800: 3.389: Application time: 0.9184918 seconds
2021-06-07T17:18:41.579+0800: 3.521: Application time: 0.1310734 seconds
2021-06-07T17:18:41.595+0800: 3.534: Application time: 0.0129515 seconds
2021-06-07T17:18:41.673+0800: 3.615: Application time: 0.0784886 seconds
{Heap before GC invocations=2 (full 0):
 par new generation   total 78656K, used 73320K [0x00000006c0000000, 0x00000006c5550000, 0x00000006d4cc0000)
  eden space 69952K, 100% used [0x00000006c0000000, 0x00000006c4450000, 0x00000006c4450000)
  from space 8704K,  38% used [0x00000006c4450000, 0x00000006c479a100, 0x00000006c4cd0000)
  to   space 8704K,   0% used [0x00000006c4cd0000, 0x00000006c4cd0000, 0x00000006c5550000)
 concurrent mark-sweep generation total 174784K, used 2569K [0x00000006d4cc0000, 0x00000006df770000, 0x00000007c0000000)
 Metaspace       used 15494K, capacity 16122K, committed 16256K, reserved 1062912K
  class space    used 1921K, capacity 2078K, committed 2176K, reserved 1048576K
2021-06-07T17:18:41.673+0800: 3.615: [GC (Allocation Failure) 2021-06-07T17:18:41.673+0800: 3.615: [ParNew: 73320K->4522K(78656K), 0.0147265 secs] 75889K->7091K(253440K), 0.0148708 secs] [Times: user=0.08 sys=0.00, real=0.02 secs] 
Heap after GC invocations=3 (full 0):
 par new generation   total 78656K, used 4522K [0x00000006c0000000, 0x00000006c5550000, 0x00000006d4cc0000)
  eden space 69952K,   0% used [0x00000006c0000000, 0x00000006c0000000, 0x00000006c4450000)
  from space 8704K,  51% used [0x00000006c4cd0000, 0x00000006c513a910, 0x00000006c5550000)
  to   space 8704K,   0% used [0x00000006c4450000, 0x00000006c4450000, 0x00000006c4cd0000)
 concurrent mark-sweep generation total 174784K, used 2569K [0x00000006d4cc0000, 0x00000006df770000, 0x00000007c0000000)
 Metaspace       used 15494K, capacity 16122K, committed 16256K, reserved 1062912K
  class space    used 1921K, capacity 2078K, committed 2176K, reserved 1048576K
}
2021-06-07T17:18:41.892+0800: 3.832: Application time: 0.2021109 seconds
Heap
 par new generation   total 78656K, used 40455K [0x00000006c0000000, 0x00000006c5550000, 0x00000006d4cc0000)
  eden space 69952K,  51% used [0x00000006c0000000, 0x00000006c23175b0, 0x00000006c4450000)
  from space 8704K,  51% used [0x00000006c4cd0000, 0x00000006c513a910, 0x00000006c5550000)
  to   space 8704K,   0% used [0x00000006c4450000, 0x00000006c4450000, 0x00000006c4cd0000)
 concurrent mark-sweep generation total 174784K, used 2569K [0x00000006d4cc0000, 0x00000006df770000, 0x00000007c0000000)
 Metaspace       used 16576K, capacity 17296K, committed 17408K, reserved 1064960K
  class space    used 2090K, capacity 2237K, committed 2304K, reserved 1048576K
2021-06-07T17:18:42.177+0800: 4.109: Application time: 0.2760546 seconds

**Comment by nobodyiam** [comment]
看下 apollo-portal.log，里面有详细日志的

**Comment by songyingjie322** [comment]
> 看下 apollo-portal.log，里面有详细日志的

多谢提醒，通过几次测试，发现username的值写的有问题，应该是coco\\\\admin，我写成了一个\\，导致没有生成apollo-portal.log日志文件。
