### ISSUE TITLE
我们现在安装完遇到个问题，几个环境的配置修改后是一起变的，不是应该每个环境的配置都是独立的码

### ISSUE THREAD

**Issue by amwitx** [ctripcorp/apollo#3750]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

简洁明了地描述一下bug

**复现**

通过如下步骤可以复现：

1. 我们现在安装完遇到个问题，几个环境的配置新增或者修改，所有环境得配置都一起变了
2. 权限没有，也能再开发环境添加得配置，同步添加到FAT，很奇怪，我们也没改什么设置
3. 目前得部署是2个eureka，2个configserver 2个configdb 1个portal

**期望**

每个环境的配置都是独立的

**截图**
![image](https://user-images.githubusercontent.com/17676182/121130853-8f825b80-c861-11eb-8428-df85d74abc4c.png)
![image](https://user-images.githubusercontent.com/17676182/121130897-a032d180-c861-11eb-87d4-a8d4018f7bbc.png)

**Comment by nobodyiam** [comment]
看现象是两个环境背后的 configdb 是同一个，看下 管理员工具 - 系统信息，然后再检查下连接的 configdb 信息

**Comment by amwitx** [comment]
![image](https://user-images.githubusercontent.com/17676182/121278883-1c7ef080-c906-11eb-8cb6-a7d24a0b2e8f.png)
这个我们运维也发现了

**Comment by nobodyiam** [comment]
看下每个环境 configdb 中 serverconfig  的 eureka.service.url 配置

**Comment by amwitx** [comment]
![image](https://user-images.githubusercontent.com/17676182/121455630-608df600-c9d7-11eb-8447-67a0be67e0e5.png)
![image](https://user-images.githubusercontent.com/17676182/121455649-6aaff480-c9d7-11eb-893f-276aa18117e9.png)

那个是eureka的地址，而且我们分成了2个库，也配置的不是一个地址

**Comment by nobodyiam** [comment]
那就应该是 dev 和 fat 环境的 apollo-adminservice 连得是同一个库导致了
