### ISSUE TITLE
helm部署apollo1.8.2版本eureka访问502

### ISSUE THREAD

**Issue by liuxiang12138** [ctripcorp/apollo#3752]
configservice和adminservice的pod都正常启动，但eureka是空的，portal服务启动后报错，从eureka获取admin地址失败，手动访问地址返回502

portal服务日志：
![image](https://user-images.githubusercontent.com/12131831/121516605-fb5ef280-ca20-11eb-9cb2-970c472f7786.png)

adminservice日志：
![image](https://user-images.githubusercontent.com/12131831/121516874-4c6ee680-ca21-11eb-80fe-4c28313e48e4.png)

configservice日志：
![image](https://user-images.githubusercontent.com/12131831/121517060-804a0c00-ca21-11eb-80a5-9c219fe527a5.png)

**Comment by liuxiang12138** [comment]
进入容器直接curl返回404
bash-4.4# curl http://127.0.0.1:8080/eureka
{"timestamp":"2021-06-10T20:40:30.303+0800","status":404,"error":"Not Found","message":"","path":"/eureka"}bash-4.4# curl http://127.0.0.1:8080/eureka/
{"timestamp":"2021-06-10T20:40:32.402+0800","status":404,"error":"Not Found","message":"","path":"/eureka/"}bash-4.4#

**Comment by nobodyiam** [comment]
helm 部署是用 k8s 原生服务发现的，所以 eureka 不会被启用，可以到 apollo-configservice 机器上 `curl http://127.0.0.1:8080` 再结合日志看下

**Comment by liuxiang12138** [comment]
> helm 部署是用 k8s 原生服务发现的，所以 eureka 不会被启用，可以到 apollo-configservice 机器上 `curl http://127.0.0.1:8080` 再结合日志看下

![image](https://user-images.githubusercontent.com/12131831/121625062-52a6a680-caa5-11eb-8c4f-04b84fa92f9d.png)

进入容器，curl返回的是空

**Comment by liuxiang12138** [comment]
主要是日志没有异常，排错没有头绪了

**Comment by nobodyiam** [comment]
1. helm chart 部署的参数贴一下，看现象是这个地方有问题
2. portal -> 管理员工具 -> 系统信息 看一下

**Comment by liuxiang12138** [comment]
deployment-adminservice.yaml:

configdb:
  name: apollo-configdb
  # apolloconfigdb host
  host: “xxxx”
  port: 3306
  dbName: apolloconfigdb
  # apolloconfigdb user name
  userName: “xxxx”
  # apolloconfigdb password
  password: “xxxx”
  connectionStringProperties: characterEncoding=utf8
  service:
    # whether to create a Service for this host or not
    enabled: false
    fullNameOverride: ""
    port: 3306
    type: ClusterIP

configService:
  name: apollo-configservice
  fullNameOverride: ""
  replicaCount: 1
  containerPort: 8080
  image:
    repository: apolloconfig/apollo-configservice
    tag: ""
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  service:
    fullNameOverride: ""
    port: 8080
    targetPort: 8080
    type: ClusterIP
  ingress:
    enabled: false
    annotations: { }
    hosts:
      - host: ""
        paths: [ ]
    tls: [ ]
  liveness:
    initialDelaySeconds: 100
    periodSeconds: 10
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 5
  config:
    # spring profiles to activate
    profiles: "github,kubernetes"
    # override apollo.config-service.url: config service url to be accessed by apollo-client 
    configServiceUrlOverride: "http://apollo-service-apollo-configservice.ops:8080"
    # override apollo.admin-service.url: admin service url to be accessed by apollo-portal 
    adminServiceUrlOverride: "http://apollo-service-apollo-adminservice.ops:8090"
    # specify the context path, e.g. /apollo
    contextPath: ""
  # environment variables passed to the container, e.g. JAVA_OPTS
  env: {}
  strategy: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

adminService:
  name: apollo-adminservice
  fullNameOverride: ""
  replicaCount: 1
  containerPort: 8090
  image:
    repository: apolloconfig/apollo-adminservice
    tag: ""
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  service:
    fullNameOverride: ""
    port: 8090
    targetPort: 8090
    type: ClusterIP
  ingress:
    enabled: false
    annotations: { }
    hosts:
      - host: ""
        paths: [ ]
    tls: [ ]
  liveness:
    initialDelaySeconds: 100
    periodSeconds: 10
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 5
  config:
    # spring profiles to activate
    profiles: "github,kubernetes"
    # specify the context path, e.g. /apollo
    contextPath: ""
  # environment variables passed to the container, e.g. JAVA_OPTS
  env: {}
  strategy: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

**Comment by liuxiang12138** [comment]
deployment-configservice.yaml :




> 1. helm chart 部署的参数贴一下，看现象是这个地方有问题
> 2. portal -> 管理员工具 -> 系统信息 看一下

values.yaml:

configdb:
  name: apollo-configdb
  # apolloconfigdb host
  host: “xxxx”
  port: 3306
  dbName: apolloconfigdb
  # apolloconfigdb user name
  userName: “xxxx”
  # apolloconfigdb password
  password: “xxxx”
  connectionStringProperties: characterEncoding=utf8
  service:
    # whether to create a Service for this host or not
    enabled: false
    fullNameOverride: ""
    port: 3306
    type: ClusterIP

configService:
  name: apollo-configservice
  fullNameOverride: ""
  replicaCount: 1
  containerPort: 8080
  image:
    repository: apolloconfig/apollo-configservice
    tag: ""
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  service:
    fullNameOverride: ""
    port: 8080
    targetPort: 8080
    type: ClusterIP
  ingress:
    enabled: false
    annotations: { }
    hosts:
      - host: ""
        paths: [ ]
    tls: [ ]
  liveness:
    initialDelaySeconds: 100
    periodSeconds: 10
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 5
  config:
    # spring profiles to activate
    profiles: "github,kubernetes"
    # override apollo.config-service.url: config service url to be accessed by apollo-client 
    configServiceUrlOverride: "http://apollo-service-apollo-configservice.ops:8080"
    # override apollo.admin-service.url: admin service url to be accessed by apollo-portal 
    adminServiceUrlOverride: "http://apollo-service-apollo-adminservice.ops:8090"
    # specify the context path, e.g. /apollo
    contextPath: ""
  # environment variables passed to the container, e.g. JAVA_OPTS
  env: {}
  strategy: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

adminService:
  name: apollo-adminservice
  fullNameOverride: ""
  replicaCount: 1
  containerPort: 8090
  image:
    repository: apolloconfig/apollo-adminservice
    tag: ""
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  service:
    fullNameOverride: ""
    port: 8090
    targetPort: 8090
    type: ClusterIP
  ingress:
    enabled: false
    annotations: { }
    hosts:
      - host: ""
        paths: [ ]
    tls: [ ]
  liveness:
    initialDelaySeconds: 100
    periodSeconds: 10
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 5
  config:
    # spring profiles to activate
    profiles: "github,kubernetes"
    # specify the context path, e.g. /apollo
    contextPath: ""
  # environment variables passed to the container, e.g. JAVA_OPTS
  env: {}
  strategy: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

**Comment by liuxiang12138** [comment]
deployment-adminservice.yaml:

---
# configmap for apollo-adminservice
kind: ConfigMap
apiVersion: v1
metadata:
  {{- $adminServiceFullName := include "apollo.adminService.fullName" . }}
  name: {{ $adminServiceFullName }}
data:
  application-github.properties: |
    spring.datasource.url = jdbc:mysql://{{include "apollo.configdb.serviceName" .}}:{{include "apollo.configdb.servicePort" .}}/{{ .Values.configdb.dbName }}{{ if .Values.configdb.connectionStringProperties }}?{{ .Values.configdb.connectionStringProperties }}{{ end }}
    spring.datasource.username = {{ required "configdb.userName is required!" .Values.configdb.userName }}
    spring.datasource.password = {{ required "configdb.password is required!" .Values.configdb.password }}
    {{- if .Values.adminService.config.contextPath }}
    server.servlet.context-path = {{ .Values.adminService.config.contextPath }}
    {{- end }}

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $adminServiceFullName }}
  labels:
    {{- include "apollo.service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.adminService.replicaCount }}
  selector:
    matchLabels:
      app: {{ $adminServiceFullName }}
  {{- with .Values.adminService.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ $adminServiceFullName }}
    spec:
      {{- with .Values.adminService.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: volume-configmap-{{ $adminServiceFullName }}
          configMap:
            name: {{ $adminServiceFullName }}
            items:
              - key: application-github.properties
                path: application-github.properties
            defaultMode: 420
      containers:
        - name: {{ .Values.adminService.name }}
          image: "{{ .Values.adminService.image.repository }}:{{ .Values.adminService.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.adminService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.adminService.containerPort }}
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.adminService.config.profiles | quote }}
          {{- range $key, $value := .Values.adminService.env }}
            - name: {{ $key }}
              value: {{ $value }}
          {{- end }}
          volumeMounts:
            - name: volume-configmap-{{ $adminServiceFullName }}
              mountPath: /apollo-adminservice/config/application-github.properties
              subPath: application-github.properties
          livenessProbe:
            tcpSocket:
              port: {{ .Values.adminService.containerPort }}
            initialDelaySeconds: {{ .Values.adminService.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.adminService.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.adminService.config.contextPath }}/health
              port: {{ .Values.adminService.containerPort }}
            initialDelaySeconds: {{ .Values.adminService.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.adminService.readiness.periodSeconds }}
          resources:
            {{- toYaml .Values.adminService.resources | nindent 12 }}
    {{- with .Values.adminService.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.adminService.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.adminService.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

**Comment by liuxiang12138** [comment]
deployment-configservice.yaml:

---
# configmap for apollo-configservice
kind: ConfigMap
apiVersion: v1
metadata:
  {{- $configServiceFullName := include "apollo.configService.fullName" . }}
  name: {{ $configServiceFullName }}
data:
  application-github.properties: |
    spring.datasource.url = jdbc:mysql://{{include "apollo.configdb.serviceName" .}}:{{include "apollo.configdb.servicePort" .}}/{{ .Values.configdb.dbName }}{{ if .Values.configdb.connectionStringProperties }}?{{ .Values.configdb.connectionStringProperties }}{{ end }}
    spring.datasource.username = {{ required "configdb.userName is required!" .Values.configdb.userName }}
    spring.datasource.password = {{ required "configdb.password is required!" .Values.configdb.password }}
    {{- if .Values.adminService.config.contextPath }}
    server.servlet.context-path = {{ .Values.adminService.config.contextPath }}
    {{- end }}

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $configServiceFullName }}
  labels:
    {{- include "apollo.service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.configService.replicaCount }}
  selector:
    matchLabels:
      app: {{ $configServiceFullName }}
  {{- with .Values.configService.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ $configServiceFullName }}
    spec:
      {{- with .Values.configService.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: volume-configmap-{{ $configServiceFullName }}
          configMap:
            name: {{ $configServiceFullName }}
            items:
              - key: application-github.properties
                path: application-github.properties
            defaultMode: 420
      containers:
        - name: {{ .Values.configService.name }}
          image: "{{ .Values.configService.image.repository }}:{{ .Values.configService.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.configService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.configService.containerPort }}
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.configService.config.profiles | quote }}
          {{- range $key, $value := .Values.configService.env }}
            - name: {{ $key }}
              value: {{ $value }}
          {{- end }}
          volumeMounts:
            - name: volume-configmap-{{ $configServiceFullName }}
              mountPath: /apollo-configservice/config/application-github.properties
              subPath: application-github.properties
          livenessProbe:
            tcpSocket:
              port: {{ .Values.configService.containerPort }}
            initialDelaySeconds: {{ .Values.configService.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.configService.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.configService.config.contextPath }}/health
              port: {{ .Values.configService.containerPort }}
            initialDelaySeconds: {{ .Values.configService.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.configService.readiness.periodSeconds }}
          resources:
            {{- toYaml .Values.configService.resources | nindent 12 }}
    {{- with .Values.configService.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.configService.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.configService.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

**Comment by liuxiang12138** [comment]
service-adminservice.yaml:

kind: Service
apiVersion: v1
metadata:
  name: {{ include "apollo.adminService.serviceName" . }}
  labels:
    {{- include "apollo.service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.adminService.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.adminService.service.port }}
      targetPort: {{ .Values.adminService.service.targetPort }}
  selector:
    app: {{ include "apollo.adminService.fullName" . }}

**Comment by liuxiang12138** [comment]
service-configservice.yaml:

kind: Service
apiVersion: v1
metadata:
  name: {{ include "apollo.configService.serviceName" . }}
  labels:
    {{- include "apollo.service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.configService.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.configService.service.port }}
      targetPort: {{ .Values.configService.service.targetPort }}
  selector:
    app: {{ include "apollo.configService.fullName" . }}

**Comment by liuxiang12138** [comment]
service-gateway.yaml:

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: apollo-configservice-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - hosts:
    - "apollo-configservice-pro.xxx.com"
    port:
      name: tcp
      number: 18080
      protocol: TCP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apollo-configservice-vs
spec:
  hosts:
  - "apollo-configservice-pro.xxx.com"
  gateways:
    - apollo-configservice-gateway
  tcp:
  - match:
    - port: 18080
    route:
    - destination:
        host: apollo-configservice
        port:
          number: 8080

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: apollo-adminservice-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - hosts:
    - "apollo-adminservice-pro.xxx.com"
    port:
      name: tcp
      number: 18090
      protocol: TCP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apollo-adminservice-vs
spec:
  hosts:
  - "apollo-adminservice-pro.xxx.com"
  gateways:
    - apollo-adminservice-gateway
  tcp:
  - match:
    - port: 18090
    route:
    - destination:
        host: apollo-adminservice
        port:
          number: 8090

**Comment by liuxiang12138** [comment]
是admin server的地址保存到了config server里面吗？一直报错找不到admin server

**Comment by nobodyiam** [comment]
values.yaml 你先只填 configdb 试试，config service 和 admin service  用默认值

```yaml
configdb:
  # apolloconfigdb host
  host: “xxxx”
  port: 3306
  dbName: apolloconfigdb
  # apolloconfigdb user name
  userName: “xxxx”
  # apolloconfigdb password
  password: “xxxx”
```

**Comment by liuxiang12138** [comment]
> values.yaml 你先只填 configdb 试试，config service 和 admin service 用默认值
> 
> ```yaml
> configdb:
>   # apolloconfigdb host
>   host: “xxxx”
>   port: 3306
>   dbName: apolloconfigdb
>   # apolloconfigdb user name
>   userName: “xxxx”
>   # apolloconfigdb password
>   password: “xxxx”
> ```

还是同样的错误：
![image](https://user-images.githubusercontent.com/12131831/122718036-0296c380-d29f-11eb-9cd6-df0f2b87b4bb.png)

**Comment by liuxiang12138** [comment]
config和admin服务启动后，config里面是空的
![image](https://user-images.githubusercontent.com/12131831/122740577-b0619c80-d2b6-11eb-9c79-fd1afc303ada.png)

**Comment by nobodyiam** [comment]
端口确认下是 8080 还是 18080?

![image](https://user-images.githubusercontent.com/837658/123015796-c0cf5f80-d3fb-11eb-86a1-e0727d4df597.png)

![image2](https://user-images.githubusercontent.com/12131831/122740577-b0619c80-d2b6-11eb-9c79-fd1afc303ada.png)

**Comment by liuxiang12138** [comment]
> 端口确认下是 8080 还是 18080?
> 
> ![image](https://user-images.githubusercontent.com/837658/123015796-c0cf5f80-d3fb-11eb-86a1-e0727d4df597.png)
> 
> ![image2](https://user-images.githubusercontent.com/12131831/122740577-b0619c80-d2b6-11eb-9c79-fd1afc303ada.png)

部署成功了，用命令行方式安装的没有问题：）
