### ISSUE TITLE
RemoteConfigLongPollService非常的耗时

### ISSUE THREAD

**Issue by 990753707** [ctripcorp/apollo#3760]
本地开发启动项目，RemoteConfigLongPollService 一直在poll 非常耗时
<img width="1352" alt="图片" src="https://user-images.githubusercontent.com/22473685/122151115-8c0a5800-ce91-11eb-9775-36026226e69f.png">

设备 mac，有网友说是网卡造成的，apollo jar已经升级了，也修改的hosts 用处不大。
求助各位

**Comment by Anilople** [comment]
参考 https://github.com/ctripcorp/apollo/blob/aef7d83416333a39ef94892afd5c83f57046bbd5/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/RemoteConfigLongPollService.java#L178-L192

这是DEBUG级别的日志，把日志改成INFO级别就好了

**Comment by 990753707** [comment]
> 参考
> 
> https://github.com/ctripcorp/apollo/blob/aef7d83416333a39ef94892afd5c83f57046bbd5/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/RemoteConfigLongPollService.java#L178-L192
> 
> 这是DEBUG级别的日志，把日志改成INFO级别就好了

info 也是慢，所以调成debug模式 看看是哪耗时的，感谢，我看能看懂这段代码不～～

**Comment by nobodyiam** [comment]
这个耗时是特意而为之的，具体可以看下[Config Service通知客户端的实现方式](https://www.apolloconfig.com/#/zh/design/apollo-design?id=_212-config-service%e9%80%9a%e7%9f%a5%e5%ae%a2%e6%88%b7%e7%ab%af%e7%9a%84%e5%ae%9e%e7%8e%b0%e6%96%b9%e5%bc%8f)

**Comment by vdisk-group** [comment]
这个耗时是特意这么设计的，如果配置没有变更的话，发起 http 请求之后 60 秒才会返回
