### ISSUE TITLE
dev 与 pro环境，docker部署方式， 所有的写操作都落在pro的数据库上

### ISSUE THREAD

**Issue by leoliuxd** [ctripcorp/apollo#3761]
使用docker方式部署两套环境，一套dev，一套pro。
不论是创建appid，还是发布配置，查看数据库的时候都只更新了pro的数据库

**Comment by leoliuxd** [comment]
![image](https://user-images.githubusercontent.com/4088477/122205854-47071580-ced3-11eb-896e-cfc5556a975a.png)
系统信息

**Comment by leoliuxd** [comment]
![Uploading image.png…]()
补充下docker启动命令

**Comment by leoliuxd** [comment]
![image](https://user-images.githubusercontent.com/4088477/122207061-4a4ed100-ced4-11eb-8b1f-29e05d810ff1.png)

**Comment by leoliuxd** [comment]
![image](https://user-images.githubusercontent.com/4088477/122211867-c8fa3d00-ced9-11eb-9227-f574f4019323.png)

**Comment by leoliuxd** [comment]
![image](https://user-images.githubusercontent.com/4088477/122212010-efb87380-ced9-11eb-9b14-65a55347a2ba.png)

**Comment by nobodyiam** [comment]
两个不同的 meta server 返回了相同的 configservice/adminsevice 的地址，检查下 eureka.service.url 配置吧，另外可以浏览器分别打开两个 meta server 的地址看下 eureka 的信息

**Comment by leoliuxd** [comment]
> 两个不同的 meta server 返回了相同的 configservice/adminsevice 的地址，检查下 eureka.service.url 配置吧，另外可以浏览器分别打开两个 meta server 的地址看下 eureka 的信息

阿里云ecs部署，系统信息里面显示的172.17.0.2 和 172.17.0.3这两个地址外网无法访问，跟db里面配置的eureka.service.url 不一样，db里面配置的是外网地址

**Comment by leoliuxd** [comment]
> 两个不同的 meta server 返回了相同的 configservice/adminsevice 的地址，检查下 eureka.service.url 配置吧，另外可以浏览器分别打开两个 meta server 的地址看下 eureka 的信息

现在看下来的现象是所有portal中的操作，只会调用和portal同一台机器上的adminservice，操作对应的DB。
部署方式是dev环境中部署了configservice 和configadminservice
pro环境中部署了configservice 和configadminservice 和 portal

**Comment by nobodyiam** [comment]
eureka.service.url 没必要配置外网地址，估摸着是这里配错了，参考下[3.2.1 eureka.service.url - Eureka服务Url](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_321-eurekaserviceurl-eureka%e6%9c%8d%e5%8a%a1url)吧
