### ISSUE TITLE
Springboot项目Placeholder方式引入如何指定namespace

### ISSUE THREAD

**Issue by Athena-17** [ctripcorp/apollo#3767]
${key:defaultValue}这种在配置文件里使用和@Value 这种可以选择namespace吗？该怎么用，开发文档里没写啊

**Comment by nobodyiam** [comment]
see [3.2 Spring整合方式](https://www.apolloconfig.com/#/zh/usage/java-sdk-user-guide?id=_32-spring%e6%95%b4%e5%90%88%e6%96%b9%e5%bc%8f)
