### ISSUE TITLE
如何同时配置 oidc 与 auth 认证

### ISSUE THREAD

**Issue by hahait** [ctripcorp/apollo#3769]
### 背景
无论是 online 环境还是 dev 环境，最开始都是使用 Apollo 自带的 Spring Security 简单认证完成配置的添加的，现在要接入 oidc 认证；

### 问题
使用 oidc 认证后，测试发现如下结果：
1.  ```java -Dspring.profiles.active=github,oidc,auth ``` 这样的配置，服务起不来，也就是不能同时配置 oidc 和 auth 认证 ；
2. 使用 oidc 认证登录的用户登录 apollo 后是没有任何权限的；由于不能使用 admin 登录，因此也不能设置权限；

### 期望
1.  最好能同时支持 auth 和 oidc 认证，以便使用 admin 用户做管理员，给其他使用 oidc 登录的用户设置权限之类；
2.  或者能够支持为 oidc 登录的用户设置默认权限；

**Comment by nobodyiam** [comment]
[3.1.4 superAdmin - Portal超级管理员](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_314-superadmin-portal%e8%b6%85%e7%ba%a7%e7%ae%a1%e7%90%86%e5%91%98)

**Comment by hahait** [comment]
> [3.1.4 superAdmin - Portal超级管理员](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_314-superadmin-portal%e8%b6%85%e7%ba%a7%e7%ae%a1%e7%90%86%e5%91%98)

数据库中，默认的超级管理员 apollo 是存在的；但是开了 oidc 认证后，前端页面没有登录入口了，所以这个超级管理员也不能登录；

**Comment by vdisk-group** [comment]
可以先用 oidc 登录一下获取用户id，然后在 Portal 的数据库执行下面这条 sql 语句，把这个用户设为管理员就行了
```sql
UPDATE `ApolloPortalDB`.`ServerConfig` SET `Value` = 'xxxx' WHERE `Key` = 'superAdmin';

```

**Comment by hahait** [comment]
> 可以先用 oidc 登录一下获取用户id，然后在 Portal 的数据库执行下面这条 sql 语句，把这个用户设为管理员就行了
> 
> ```sql
> UPDATE `ApolloPortalDB`.`ServerConfig` SET `Value` = 'xxxx' WHERE `Key` = 'superAdmin';
> ```

嗯嗯，实际上 web 页面上的 “系统参数” 上也可以配置，只是不太友好，提供个下拉框能看到可配置项就好了；
