### ISSUE TITLE
不添加apollo.bootstrap.eagerLoad.enabled=true也能接管日志了吗？

### ISSUE THREAD

**Issue by WaylonTian** [ctripcorp/apollo#3773]
请问现在是不是不添加：
apollo.bootstrap.eagerLoad.enabled=true

也能接管日志相关设置了？

我这边没有添加上述语句，在apollo中配置 logging.level.xxx 的值为WARN，会发现满足的路径真的只会打印WARN日志，请问我的发现是正确的吗？如果是这样，现在apollo.bootstrap.eagerLoad.enabled=true 还有什么使用场景非用不可吗？ 提前谢谢解惑，谢谢。

**Comment by nobodyiam** [comment]
如果不加这个配置项应该是不能接管日志配置的，毕竟 logging system 的初始化顺序是比较早的
