### ISSUE TITLE
Config Service定时轮询扫描ReleaseMessage是否会出现多实例时重复扫描表问题

### ISSUE THREAD

**Issue by yearsFung** [ctripcorp/apollo#3782]
请问，在“Config Service 有一个线程会每秒扫描一次 ReleaseMessage 表，看看是否有新的消息记录，参见ReleaseMessageScanner ”设计上，如果config service部署多个实例，是怎么避免重复扫描消息记录的问题？

查看了com.ctrip.framework.apollo.biz.message.ReleaseMessageScanner#scanAndSendMessages方法及类，没有找到答案，还请解答下，谢谢！

**Comment by yearsFung** [comment]
@nobodyiam  麻烦看下

**Comment by nobodyiam** [comment]
> 如果config service部署多个实例，是怎么避免重复扫描消息记录的问题？

每个 config service 实例都需要扫描消息记录的

**Comment by yearsFung** [comment]
请问，多个config service实例会不会扫到相同的消息记录，然后给同一个客户端发送相同配置更新消息的情况？

**Comment by yearsFung** [comment]
是如何避免上述情形的呢，谢谢 @nobodyiam

**Comment by yearsFung** [comment]
哦我明白了我。

**Comment by yearsFung** [comment]
哦，明白了，是不是这样的：

**Comment by yearsFung** [comment]
哦，明白了，是不是这样的：

**Comment by yearsFung** [comment]
哦，明白了，请问是不是这样的
多个config service实例，分别负责不同的客户端实例，不同客户端只发起一个长连接到某一个config service实例上，所以每个config service实例扫描同一条消息后，是发送该变更配置给不同的客户端实例的
谢谢 @nobodyiam

**Comment by nobodyiam** [comment]
是的

**Comment by nobodyiam** [comment]
是的

**Comment by yearsFung** [comment]
感谢老师
