### ISSUE TITLE
[使用疑问]接入oidc认证，如何把用户标识改为email

### ISSUE THREAD

**Issue by xuzhzz** [ctripcorp/apollo#3795]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**期望**
已经成功接入oidc认证，但是登陆后右上角的用户标识（username）是oidc claim里的sub（用户id，一长串数字）。不具备可读性，在分配权限的时候无法辨别用户的身份。我这里想改为claim里的email作为用户标识

**Comment by xuzhzz** [comment]
https://github.com/ctripcorp/apollo/pull/3629

**Comment by xuzhzz** [comment]
找到相关issue好像解决了这个问题https://github.com/ctripcorp/apollo/pull/3629

**Comment by xuzhzz** [comment]
找到相关issue好像解决了这个问题，但是没有找到配置的方法https://github.com/ctripcorp/apollo/pull/3629

@vdisk-group 请指教

**Comment by vdisk-group** [comment]
#3629 这个PR的内容要1.9.0才会发布，目前的release版是没有这个功能的，而且这个 PR里面我采取的方案是直接取用户昵称(PreferredUsername)这个字段，没有提供配置

**Comment by xuzhzz** [comment]
> #3629 这个PR的内容要1.9.0才会发布，目前的release版是没有这个功能的，而且这个 PR里面我采取的方案是直接取用户昵称(PreferredUsername)这个字段，没有提供配置

好的，了解了谢谢
