### ISSUE TITLE
apollo配置https访问portal，登录失败

### ISSUE THREAD

**Issue by feixia5712** [ctripcorp/apollo#3796]
在一台机器上安装了nginx
nginx配置如下
`server {
     listen       8070 ssl;
     server_name  localhost;
     ssl_certificate     cert/apollo/apollo-cert.pem;
     ssl_certificate_key cert/apollo/apollo-key.key;

     ssl_session_cache    shared:SSL:1m;
     ssl_session_timeout  5m;

     ssl_ciphers "HIGH+EECDH:HIGH+EDH:!aNULL:!MD5:!SHA";
     ssl_prefer_server_ciphers  on;
     ssl_protocols TLSv1.2;
     if ($time_iso8601 ~ "^(\d{4})-(\d{2})-(\d{2})") {
     set $year $1;
     set $month $2;
     set $day $3;
     }
    access_log  logs/https-apollo-$year-$month-$day-access.log main;
    error_log  logs/https-apollo-error.log  notice;

location / {
proxy_pass http://192.168.1.180:8070;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto "https";
}

}
`
浏览器登录
![image](https://user-images.githubusercontent.com/12670758/123775950-68b7c200-d901-11eb-95d0-a7c983bbdd23.png)
但是输入密码之后，会跳转到本机ip的80
![image](https://user-images.githubusercontent.com/12670758/123776153-9997f700-d901-11eb-8e1e-fdec51261147.png)
请教下是不是需要进行rewrite进行配置？？？

**Comment by vdisk-group** [comment]
proxy_set_header 的配置请修改为如下
```nginx
proxy_set_header x-real-ip $remote_addr;
proxy_set_header x-forwarded-for $proxy_add_x_forwarded_for;
proxy_set_header host $http_host;
proxy_set_header x-nginx-proxy true;
proxy_set_header x-forwarded-proto $scheme;

```

**Comment by feixia5712** [comment]
你好，现在配置

> host 的取值应当为 $http_host
> 
> proxy_set_header 的配置例子如下
> 
> ```nginx
> proxy_set_header x-real-ip $remote_addr;
> proxy_set_header x-forwarded-for $proxy_add_x_forwarded_for;
> proxy_set_header host $http_host;
> proxy_set_header x-nginx-proxy true;
> proxy_set_header x-forwarded-proto $scheme;
> ```

你好现在配置如下
`server {
     listen       8070 ssl;
     server_name  localhost;
     ssl_certificate     cert/apollo/apollo-cert.pem;
     ssl_certificate_key cert/apollo/apollo-key.key;

     ssl_session_cache    shared:SSL:1m;
     ssl_session_timeout  5m;

     ssl_ciphers "HIGH+EECDH:HIGH+EDH:!aNULL:!MD5:!SHA";
     ssl_prefer_server_ciphers  on;
     ssl_protocols TLSv1.2;
     if ($time_iso8601 ~ "^(\d{4})-(\d{2})-(\d{2})") {
     set $year $1;
     set $month $2;
     set $day $3;
     }
    access_log  logs/https-apollo-$year-$month-$day-access.log main;
    error_log  logs/https-apollo-error.log  notice;


location / {
proxy_pass http://192.168.1.180:8070;
proxy_set_header x-real-ip $remote_addr;
proxy_set_header x-forwarded-for $proxy_add_x_forwarded_for;
proxy_set_header host $http_host;
proxy_set_header x-nginx-proxy true;
proxy_set_header x-forwarded-proto $scheme;
proxy_set_header X-Forwarded-Proto "https";
}


}
`
但是登录后会跳转http://ip:8070,  还需要重定向吗
![image](https://user-images.githubusercontent.com/12670758/123886543-487c1780-d982-11eb-9943-d5f8aac18b9e.png)

**Comment by vdisk-group** [comment]
还需要配置一个重定向，还有你确认你的证书的 server_name 是 localhost？server_name 和证书对不上浏览器是无法访问的。
```nginx
server {
    listen 80 default_server;

    location / {
        return 301 https://$http_host$request_uri;
    }
}
server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate cert/apollo/apollo-cert.pem;
    ssl_certificate_key cert/apollo/apollo-key.key;
	
    location / {
        proxy_pass http://192.168.1.180:8070;
        proxy_set_header x-real-ip $remote_addr;
        proxy_set_header x-forwarded-for $proxy_add_x_forwarded_for;
        proxy_set_header host $http_host;
        proxy_set_header x-nginx-proxy true;
        proxy_set_header x-forwarded-proto $scheme;
        proxy_http_version 1.1;
    }
}

```

**Comment by feixia5712** [comment]
在加上这一行配置就好了
proxy_redirect ~^http://([^:]+)(:\d+)?(.*)$ https://$1$2$3;

**Comment by feixia5712** [comment]
完整配置如下
location / {
proxy_pass http://192.168.1.180:8070;
proxy_redirect ~^http://([^:]+)(:\d+)?(.*)$ https://$1$2$3;
proxy_set_header x-real-ip $remote_addr;
proxy_set_header x-forwarded-for $proxy_add_x_forwarded_for;
proxy_set_header host $http_host;
proxy_set_header x-nginx-proxy true;
proxy_set_header x-forwarded-proto $scheme;
proxy_set_header X-Forwarded-Proto "https";
}

**Comment by feixia5712** [comment]
> 还需要配置一个重定向，还有你确认你的证书的 server_name 是 localhost？server_name 和证书对不上浏览器是无法访问的。
> 
> ```nginx
> server {
>     listen 80 default_server;
> 
>     location / {
>         return 301 https://$http_host$request_uri;
>     }
> }
> server {
>     listen 443 ssl;
>     server_name localhost;
> 
>     ssl_certificate cert/apollo/apollo-cert.pem;
>     ssl_certificate_key cert/apollo/apollo-key.key;
> 	
>     location / {
>         proxy_pass http://192.168.1.180:8070;
>         proxy_set_header x-real-ip $remote_addr;
>         proxy_set_header x-forwarded-for $proxy_add_x_forwarded_for;
>         proxy_set_header host $http_host;
>         proxy_set_header x-nginx-proxy true;
>         proxy_set_header x-forwarded-proto $scheme;
>         proxy_http_version 1.1;
>     }
> }
> ```

谢谢，我是使用ip配置的https，server_name就没改，现在正常了，谢谢

**Comment by lifeblood** [comment]
haporxy 怎么配置
