### ISSUE TITLE
升级至1.8.2后调用openapi接口comment长度校验问题

### ISSUE THREAD

**Issue by chengasd** [ctripcorp/apollo#3799]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
项目从1.5.0 升级至1.8.2，原业务系统会通过openapi接口创建更新配置。 升级后部分业务场景创建配置item时会提示"Comment length should not exceed 64 characters"。在1.5.0版本未有该限制，数据库字符长度为1024，所以在老的版本未受影响。

原合并记录：https://github.com/ctripcorp/apollo/pull/2849

**期望**

修改ItemController.java && valdr.js && en.json &&zh-CN.json放开comment字符长度限制，按照数据库底层配置的长度1024校验。（包括前端入口）

**截图**
![image](https://user-images.githubusercontent.com/4476162/124086192-63828080-da83-11eb-9b77-5389f364d9ba.png)

![image](https://user-images.githubusercontent.com/4476162/124087000-2e2a6280-da84-11eb-9377-33b4d4ebe3c6.png)

**Comment by nobodyiam** [comment]
看了下 valdr.js 中的几个 comment 都设置为 64 最大长度了，不过后端存储的长度不一，可以考虑提个 PR 修改一下。
另外，comment 在什么场景需要是 1024？

**Comment by chengasd** [comment]
> 看了下 valdr.js 中的几个 comment 都设置为 64 最大长度了，不过后端存储的长度不一，可以考虑提个 PR 修改一下。
> 另外，comment 在什么场景需要是 1024？

这边实际场景是原来业务系统提交时在comment里带上了rds的链接，导致字符长度超过64，在1.5.0版本里面创建成功了，目前长度都在100以内是可以满足需求的。    改成1024的话是参考item表定义的最大长度。
