### ISSUE TITLE
ApolloConfigChangeListener是否可以提供order

### ISSUE THREAD

**Issue by yakamy** [ctripcorp/apollo#3801]
**你的特性请求和某个问题有关吗？请描述**

当apollo和jasypt一起使用时，会导致动态更新失效，是由于jasypt的cache问题导致
解决方法：
通过自定义一个ApolloConfigChangeListener，当接收到字段变更时，发布RefreshScopeRefreshedEvent事件，jasypt接收到这个事件会使cache失效。

**清晰简洁地描述一下你希望的解决方案**

这种方法有个问题，第一次触发动态更新的时候，AutoUpdateConfigChangeListener会先触发导致获取到的还是cache中的值。
所以 ApolloConfigChangeListener 是否可以增加order来保证listener调用的顺序，同时调用lisener的线程池也需要能够扩展（使用单个线程调度）来保证listener顺序执行。

**Comment by Anilople** [comment]
具体场景可以描述一下吗？

**Comment by nobodyiam** [comment]
there is a related issue #2671

**Comment by yakamy** [comment]
ok, 看起来这个feature没被添加，目前只能从jasypt的cache下手，代理jasypt的propertysource使缓存失效。
