### ISSUE TITLE
屏蔽Apollo-client客户端日志输出问题

### ISSUE THREAD

**Issue by villebo** [ctripcorp/apollo#3805]
在spring cloud中使用Apollo-client使用时，控制台会打印输出相关如下日志
[WARN][Apollo-RemoteConfigLongPollService-1] com.ctrip.framework.apollo.internals.RemoteConfigLongPollService.doLongPollingRefresh:197 - Long polling failed, will retry in 1 seconds
基本上每隔2分钟输出一次日志这样会导致大量日志输出，虽然应用使用没有任何问题，但容易对应用日志造成污染以及占用服务器磁盘空间，如何解决？
期望是 屏蔽该日志输出

**Comment by nobodyiam** [comment]
* 这个日志正常不应该出现，如果频繁出现，得排查下原因
* apollo 的日志都是通过 slf4j 托管输出的，如果希望屏蔽某些日志，直接配置对应的 logger 级别即可，可以参考[apollo-demo 的配置](https://github.com/ctripcorp/apollo/blob/master/apollo-demo/src/main/resources/log4j2.xml)

**Comment by villebo** [comment]
非常感谢，问题解决
