### ISSUE TITLE
MessageScanner扫描偶尔跳过个别messageId导致配置发布不生效的问题

### ISSUE THREAD

**Issue by denghuichao** [ctripcorp/apollo#3806]
在ReleaseMessageServiceWithCache.handleMessage中，有下面一段代码：
````
    long gap = message.getId() - maxIdScanned;
    if (gap == 1) {
      mergeReleaseMessage(message);
    } else if (gap > 1) {
      //gap found!
      loadReleaseMessages(maxIdScanned);
    }
````
当发现id不连续时，尝试重新load一下避免漏掉messageId。但是如果loadReleaseMessages时被跳过的message还是没加载到，比如说发布配置的事务还没提交，那是不是这条消息就被永久跳过了，这就导致这条配置发布不生效。生产环境遇到过这个问题，发现确实是messageId被跳过了。

**Comment by nobodyiam** [comment]
> 但是如果loadReleaseMessages时被跳过的message还是没加载到，比如说发布配置的事务还没提交，那是不是这条消息就被永久跳过了，这就导致这条配置发布不生效

如果事务没提交的话，当它提交后会发出 release message 的，不会丢失消息

**Comment by denghuichao** [comment]
> > 但是如果loadReleaseMessages时被跳过的message还是没加载到，比如说发布配置的事务还没提交，那是不是这条消息就被永久跳过了，这就导致这条配置发布不生效
> 
> 如果事务没提交的话，当它提交后会发出 release message 的，不会丢失消息

在mysql的事务隔离级别为RR的时候，假设上次扫描到的maxIdScanned=0，这时假设两个事务在发布配置，A事务先开始，B事务后开启，然后B反而先提交，主键ID为2，这时候扫描程序执行了，扫描到2了，发现有gap，loadReleaseMessages期望加载到跳过的1，但是A还是没提交，后面maxIdScanned=2了，过了一会A才提交了，id为1，那1就被永远跳过了。

生产环境遇到配置不生效的问题，看了日志，确实没有打印这条不生效的releaseMessage，怀疑是这里的问题。

**Comment by nobodyiam** [comment]
似乎确实存在这种可能性，不过 5 分钟的兜底策略应该还是会让配置生效的吧？

**Comment by denghuichao** [comment]
不会，ConfigServiceWithCache也是依赖Scaner的通知才刷新缓存的

**Comment by denghuichao** [comment]
似乎不会，ConfigServiceWithCache也是依赖Scanner通知来刷新缓存的

**Comment by nobodyiam** [comment]
这个看起来是一个潜在的问题
