### ISSUE TITLE
 connect() failed (111: Connection refused) while connecting to upstream, client:

### ISSUE THREAD

**Issue by zhengyazhao** [ctripcorp/apollo#3809]
**描述bug**

- 使用docker部署的apollo,并且绑定域名，从nginx转发到服务器。但是出现nginx一分钟就会出现一个错误记录,记录如下。
- 使用的是docker部署。
![image](https://user-images.githubusercontent.com/37286663/124454118-afeafa80-ddba-11eb-9390-296de65bfdc2.png)
![image](https://user-images.githubusercontent.com/37286663/124454457-1708af00-ddbb-11eb-835a-128778374954.png)
![image](https://user-images.githubusercontent.com/37286663/124454469-1bcd6300-ddbb-11eb-9419-3b64b61a4739.png)

![image](https://user-images.githubusercontent.com/37286663/124454492-22f47100-ddbb-11eb-92dd-5bc35c33770b.png)

**Comment by zhengyazhao** [comment]
抓包时只发现了这么个错误。
![image](https://user-images.githubusercontent.com/37286663/124455148-ce052a80-ddbb-11eb-81af-f724b7541d71.png)

**Comment by nobodyiam** [comment]
default_sso_heartbeat 一分钟会 reload 一次，看报错是 8070 连不上？

https://github.com/ctripcorp/apollo/blob/master/apollo-portal/src/main/resources/static/default_sso_heartbeat.html

**Comment by zhengyazhao** [comment]
8080 也会有截图的时候 没有截全，看了下nginx上错误日志有60多M了。所以现在不太清楚是不是自己哪里配置有问题。。
![image](https://user-images.githubusercontent.com/37286663/124528788-a5bd1080-de3b-11eb-96ef-bf5bfcd23fe8.png)

**Comment by nobodyiam** [comment]
可以 tcpdump 看下实际连接的信息

**Comment by zhengyazhao** [comment]
好的，我去看看有结果在告知。。
