### ISSUE TITLE
apollo部分安全使用问题

### ISSUE THREAD

**Issue by dabusuidedan** [ctripcorp/apollo#3810]
项目使用apollo版本1.6.0-SNAPSHOT
1、	用户名、密码、邮箱均未做合法性校验
管理员工具 –> 用户管理处未对用户输入数据做合法性校验
输入“><img src -1 onclick-alert(1)>”时可以正常添加
 
2、	创建项目->项目管理员查/users接口存在存储型XSS
当在用户管理处添加问题1的用户时，在创建项目界面项目管理员栏目会存在XSS注入，出现界面弹窗

3、	namespaces/application/item接口存在csrfToken和Referer校验

上述问题是否会进行修改？

**Comment by nobodyiam** [comment]
感谢反馈，问题 1 和 2 在 #3340 已经修复了，问题 3 麻烦参照 [Security Policy](https://github.com/ctripcorp/apollo/security/policy) 发邮件至 apollo-config@googlegroups.com 详细描述下，谢谢！
