### ISSUE TITLE
kubernetes 多集群指定方式

### ISSUE THREAD

**Issue by 1314cc** [ctripcorp/apollo#3811]
你好， 文档我已经看过几遍， 多集群的指定方式发现只有一种方式。 

通过 /opt/settings/server.properties 配置文件来指定 集群。

![image](https://user-images.githubusercontent.com/5126487/124543228-77e5c500-de57-11eb-9b6b-ae71187f0538.png)

因为我们公司有多个k8s集群。分不同的集群读取配置。 

我想知道，可以有其他指定的方式吗？  是否可以使用启动参数，或者其他方式来指定 IDC/Cluster

**Comment by nobodyiam** [comment]
可以参考下[1.2.4.2 Cluster（集群）](https://www.apolloconfig.com/#/zh/usage/java-sdk-user-guide?id=_1242-cluster%ef%bc%88%e9%9b%86%e7%be%a4%ef%bc%89)

**Comment by 1314cc** [comment]
你好，[1.2.4.2 Cluster ](https://www.apolloconfig.com/#/zh/usage/java-sdk-user-guide?id=_1242-cluster%ef%bc%88%e9%9b%86%e7%be%a4%ef%bc%89)是客户端指定集群。 我想知道下adminService,ConfigService 如何指定集群，现在看下来只是在 /opt/settings/server.properties 配置文件来指定 集群。

**Comment by nobodyiam** [comment]
有多种指定方式，可以参考下 com.ctrip.framework.apollo.biz.service.BizDBPropertySource#refresh 的逻辑

**Comment by nisiyong** [comment]
@1314cc 容器场景简单的话，可以通过环境变量`IDC`指定集群
