### ISSUE TITLE
公有配置所有用户可见导致的问题

### ISSUE THREAD

**Issue by pgydwhhw** [ctripcorp/apollo#3820]
问题描述：我有多个应用都是使用的同一套数据库连接，Apollo我该如何配置？
想法：我目前想将其作为公有配置，但是很大的问题就是所有用户都可见
解决：每个项目单独配置为私有配置，并开启configView.memberOnly.envs，但是这会造成每个项目都有一份，配置繁琐，修改的话所有涉及到的项目都要去改一遍。这只是举个例子，不一定是数据库连接配置，其他涉密配置如何多个应用共享，Apollo目前似乎不能做到。
建议：公有配置的可见性在portal层面很不合适，能否后期给公有配置在portal层面做可读权限。

**Comment by nobodyiam** [comment]
see #3187
