### ISSUE TITLE
整数精度展示问题

### ISSUE THREAD

**Issue by furaul** [ctripcorp/apollo#3821]
- [x] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**
![image](https://user-images.githubusercontent.com/4946739/125225097-3e063a00-e301-11eb-9009-dc12e75bf914.png)
当配置的value值是较大整数时，保存和编辑时展示的整数是正确的，但是点击value弹出窗口查看的整数有精度丢失。

**To Reproduce**
1. 存储整数数组，[9587743934784070, 13246918697656345, 127525757991925097]
2. 点击发布。
3. 点击整数value值。
4. 查看value与实际整数值存在丢失问题。
5. http://106.54.227.205/config.html?#/appid=defaultAppId 点击链接查看

**Expected behavior**
整数值展示正确。

**Screenshots**
![image](https://user-images.githubusercontent.com/4946739/125225097-3e063a00-e301-11eb-9009-dc12e75bf914.png)

### Additional Details & Logs

- Version
- 当前使用版本基于1.7.1，在首页提供的demo链接中重现了该问题。
- Error logs
- Configuration
- Platform and Operating System

**Comment by nobodyiam** [comment]
Thanks for reporting this issue, it seems a javascript issue, would you like to submit a pull request to fix it?

**Comment by wu560130911** [comment]
这个改动存在问题，如果text内容为json等内容，则自动在Json字符串后面增加了一串数字，导致内容不正确；

**Comment by nobodyiam** [comment]
@wu560130911 Would you please help to submit an issue for the bug you described?

**Comment by furaul** [comment]
> 

这个问题的重现步骤是什么？麻烦提供一下，看到你这个问题，当前官方的更新修复代码我还未同步。

**Comment by furaul** [comment]
> 这个改动存在问题，如果text内容为json等内容，则自动在Json字符串后面增加了一串数字，导致内容不正确； ![image](https://user-images.githubusercontent.com/4394967/143971791-2478aa21-82e3-4e0c-bf3e-fb23cfd3062a.png)

@wu560130911 
这个问题的重现步骤和数据麻烦提供下，我这边担心有你这个问题，还未同步官方的前端修复代码。

**Comment by nobodyiam** [comment]
@furaul see #4183
