### ISSUE TITLE
1.4t版本portal无法代理到nginx后端

### ISSUE THREAD

**Issue by songjuncai1122** [ctripcorp/apollo#3823]
1.4版本的portal准备代理到nginx后端加上路径，按着官方配置了
prefix.path=/apollo
然后nginx的配置
location /apollo/ {
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://127.0.0.1:8070/;
}

**Comment by pengweiqhca** [comment]
使用ip_hash
