### ISSUE TITLE
引用参数不能热更新，是什么情况？

### ISSUE THREAD

**Issue by xzzor** [ctripcorp/apollo#3829]
如两个命名空间：A，B。
A空间里有参数：
Key: test    value: 123

B空间里有参数app，引用A空间参数：
Key: app    value: ${test}

启动程序获取值两个值是正常的。
但是更新test的值为 abc 后，再获取两个值，test的值已经更新，app的值没更新，还是123。

有没有大佬遇到这种情况？怎么解决？

**Comment by nobodyiam** [comment]
see #2862
