### ISSUE TITLE
#.net core#  接入apollo报错

### ISSUE THREAD

**Issue by justinwujian** [ctripcorp/apollo#3868]
接入apollo报这个错误: 
Could not complete get operation - Could not complete get operation [Cause: No MediaTypeFormatter is available to read an object of type 'IList`1' from content with media type 'text/html'.]
项目配置如下：
![image](https://user-images.githubusercontent.com/65995025/128172397-96d47270-0e34-4975-a54d-f2a9b9da6f84.png)
![image](https://user-images.githubusercontent.com/65995025/128172416-bd6977dd-584c-4c4d-936b-2278fa8374c8.png)
![image](https://user-images.githubusercontent.com/65995025/128277773-d83bf45d-c944-4163-8a82-6eb4e50e2ffa.png)

本地可以打开配置能登录进去配置
有没有人遇到过这个问题呢？如何解决？

**Comment by nobodyiam** [comment]
看报错应该是 meta server 地址填错了，直接浏览器访问 http://192.168.1.238:8002/services/config 看看

**Comment by justinwujian** [comment]
> 看报错应该是 meta server 地址填错了，直接浏览器访问 http://192.168.1.238:8002/services/config 看看

试了不行呢，可能是部署的apollo有问题。我再研究看看

**Comment by justinwujian** [comment]
> 看报错应该是 meta server 地址填错了，直接浏览器访问 http://192.168.1.238:8002/services/config 看看

问题解决了。原因确实是地址填错了，apollo对外暴露了两个端口，MetaServer填的应该是服务端的端口，运维的同事给我的却是客户端的端口.
