### ISSUE TITLE
helm安装的时候host必须是IP么

### ISSUE THREAD

**Issue by jiangxiaoqiang** [ctripcorp/apollo#3872]
**描述bug**

Error: Endpoints "apollo-service-dev-apollo-configdb" is invalid: [subsets[0].addresses[0].ip: Invalid value: "apollo-mysql-0.apollo-mysql.reddwarf-storage.cluster.local": must be a valid IP address, (e.g. 10.9.8.7 or 2001:db8::ffff), subsets[0].addresses[0].ip: Invalid value: "apollo-mysql-0.apollo-mysql.reddwarf-storage.cluster.local": must be a valid IP address]

**复现**

通过如下步骤可以复现：

```
helm install apollo-service-dev \
    --set configdb.host=apollo-mysql-0.apollo-mysql.reddwarf-storage.svc.cluster.local \
    --set configdb.userName=root \
    --set configdb.password=u2E32fdgecU4 \
    --set configdb.service.enabled=true \
    --set configService.replicaCount=1 \
    --set adminService.replicaCount=1 \
    -n reddwarf-storage \
    apollo/apollo-service
```

**期望**

正常安装

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统 kubernetes v1.21.3

**Comment by jiangxiaoqiang** [comment]
root@nginx-deployment-66b6c48dd5-lgznj:/# ping apollo-mysql-0.apollo-mysql.reddwarf-storage.svc.cluster.local 
PING apollo-mysql-0.apollo-mysql.reddwarf-storage.svc.cluster.local (10.97.196.216) 56(84) bytes of data.
64 bytes from 10-97-196-216.apollo-mysql-headless.reddwarf-storage.svc.cluster.local (10.97.196.216): icmp_seq=1 ttl=63 time=0.079 ms
64 bytes from 10-97-196-216.apollo-mysql-headless.reddwarf-storage.svc.cluster.local (10.97.196.216): icmp_seq=2 ttl=63 time=0.050 ms
64 bytes from 10-97-196-216.apollo-mysql-headless.reddwarf-storage.svc.cluster.local (10.97.196.216): icmp_seq=3 ttl=63 time=0.057 ms
64 bytes from 10-97-196-216.apollo-mysql-headless.reddwarf-storage.svc.cluster.local (10.97.196.216): icmp_seq=4 ttl=63 time=0.047 ms
64 bytes from 10-97-196-216.apollo-mysql-headless.reddwarf-storage.svc.cluster.local (10.97.196.216): icmp_seq=5 ttl=63 time=0.048 ms

**Comment by nobodyiam** [comment]
>    --set configdb.service.enabled=true 

这个应该不用配置吧，本来就是 service 了
