### ISSUE TITLE
open-api 中为什么没有加入灰度发布功能？

### ISSUE THREAD

**Issue by jianwentao** [ctripcorp/apollo#3891]
我们想基于OpenAPI把apollo的配置开放给非开发人员，需要灰度这个功能，我能问下为什么在OpenAPI里没有集成这个功能么？谢谢！

**Comment by nobodyiam** [comment]
其实是有的，详见 #1518，不过灰度 API 比较复杂，所以没有在文档中标出

**Comment by jianwentao** [comment]
谢谢大佬的回复，但其实我的问题是为什么没有在https://github.com/ctripcorp/apollo/blob/master/apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/client/ApolloOpenApiClient.java 里封装灰度发布的功能？是因为没有资源做这个么？还是有其他的concern？

**Comment by nobodyiam** [comment]
主要考虑还是灰度功能比较复杂，通过 api 方式使用不太直观

**Comment by jianwentao** [comment]
ok，谢谢！
