### ISSUE TITLE
Load more doesn't work for commit history for specific key

### ISSUE THREAD

**Issue by nobodyiam** [ctripcorp/apollo#3893]
- [x] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**
#3878 added support to filter commit history for specific key,  but it seems the load more feature is not adjusted for this feature

**To Reproduce**
1. change the same key 15 times, e.g `a`
2. switch to change history
3. filter the change histories with key `a`
4. click `Load more`
5. The latest histories were loaded instead of the previous ones

**Expected behavior**
More histories with key `a` should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/837658/129437956-b9348b68-748f-4f63-bb54-9e25d845c949.png)

After clicking `Load more`

![image](https://user-images.githubusercontent.com/837658/129438004-6debeebc-76a8-4e5e-9b8d-b105ef320d0e.png)

**Comment by nobodyiam** [comment]
@Accelerater would you please help to verify this bug?

**Comment by Accelerater** [comment]
ok
