### ISSUE TITLE
open API支持并发操作吗？

### ISSUE THREAD

**Issue by lintingjie** [ctripcorp/apollo#3902]
比如修改配置接口，我是先读当前配置，然后再修改配置，怎么避免覆盖其他客户端提交的值

**Comment by Anilople** [comment]
无法避免

可以设计成，只有1个客户端会修改配置，这样可以避开并发问题

**Comment by nobodyiam** [comment]
确实理论上无法避免，不过目前有加锁的机制，可以看看是否能满足需求

[namespace.lock.switch](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_322-namespacelockswitch-%e4%b8%80%e6%ac%a1%e5%8f%91%e5%b8%83%e5%8f%aa%e8%83%bd%e6%9c%89%e4%b8%80%e4%b8%aa%e4%ba%ba%e4%bf%ae%e6%94%b9%e5%bc%80%e5%85%b3%ef%bc%8c%e7%94%a8%e4%ba%8e%e5%8f%91%e5%b8%83%e5%ae%a1%e6%a0%b8)

**Comment by lintingjie** [comment]
只能通过业务控制避免并发了
