### ISSUE TITLE
创建Branch接口报403

### ISSUE THREAD

**Issue by jianwentao** [ctripcorp/apollo#3914]
Hi，我现在正在用如下接口
`http://localhost:8070/openapi/v1/envs/dev/apps/SampleApp/clusters/default/namespaces/product/branches?operator=test`
Header里已经设置好token，但是在执行的时候返回403，如下：
```
{
    "exception": "org.springframework.security.access.AccessDeniedException",
    "message": "Access is denied",
    "status": 403,
    "timestamp": "2021-08-24T17:08:34.636"
}
```
复现流程：
1、利用docker-compose up启动apollo。
2、添加product namespace并且添加第三方应用，将product授权给第三方应用。
3、执行以上接口创建新的branch。

请问：
我认为我已经将product namesapce的修改权限授予给第三方应用的token了，为什么还会看到403的error？谢谢！

**Comment by jianwentao** [comment]
plz ignore this!

**Comment by citycan1991** [comment]
> plz ignore this!

请问怎么解决的呢， 我现在也遇到了这个问题
