### ISSUE TITLE
Document support multiple language switch in every pages

### ISSUE THREAD

**Issue by Anilople** [ctripcorp/apollo#4028]
**Is your feature request related to a problem? Please describe.**
When someone read a document, he/she maybe want to switch to another language, with docsify's navbar, the path information will lose, i.e language switch in navbar only jump to README page, not another language of current page.

In #4025, add `English | 中文` switch, we can add it to every pages.

**Describe the solution you'd like**
There is no suitable plugin in https://docsify.js.org/#/awesome?id=plugins

Maybe we need to write a plugin to do it, calculate current path, generate `English | 中文` button in every page's head.

Like [:memo: Edit Document]() button write in https://github.com/apolloconfig/apollo/blob/master/docs/index.html#L139

![image](https://user-images.githubusercontent.com/15523186/136948062-1c55e086-c210-4419-bf6b-cdf559605ff4.png)

**Describe alternatives you've considered**
Add `English | 中文` in every pages manually.

**Comment by nobodyiam** [comment]
That sounds like a good idea!
BTW, is it possible to apply some logic directly to the translation menu? e.g. when the user clicks the English menu, then the English version of the current page will be displayed?
![image](https://user-images.githubusercontent.com/837658/137048763-c461b671-3a6a-4b11-9e95-c0be7681fc73.png)
