### ISSUE TITLE
这是个人级的开源还是公司级别的开源

### ISSUE THREAD

**Issue by mykite** [ctripcorp/apollo#406]
如果是公司级别的?
1.注释几乎没有
2.开源协议没有
3.没看到文档
如果是个人级别的当我没说,抱歉

**Comment by yiming187** [comment]
作为一个曾经的Apollo开发者，回答一点
1. 必要的和用户使用API相关的注释是有的，大部分没有注释的代码也是通过方法名可以自解释的。
2. 协议是Apache Licence 2，项目根路径下就有，你大概忽略了。
3. 项目的主要开发者，song_s发表过介绍的文章：http://nobodyiam.com/2016/07/09/introduction-to-apollo/

开源是一份努力，每个人都有自己的工作和职责，如果你觉得哪里做得不够好，开源社区是接纳大家的关注和建议的。

**Comment by nobodyiam** [comment]
接受批评，我们会尽快补上安装部署、使用文档。

**Comment by mykite** [comment]
抱歉，我确实没有看到，不过介绍什么的前期可以放在readme里面，后期可能需要有对应的pages详细使用。支持开源，以star，希望加上对于springcloud-configserver的优略势，做这个肯定是在用springcloud-configserver有什么不足才做这个配置中心，谢谢

**Comment by nobodyiam** [comment]
@mykite 多谢中肯的建议~

**Comment by nobodyiam** [comment]
@mykite 我们已经补充了一些使用和设计文档，具体可以通过[项目首页](https://github.com/ctripcorp/apollo)或[Wiki页面](https://github.com/ctripcorp/apollo/wiki)查看。

另外，我们也尝试分析了下Apollo和Spring Cloud Config的优劣势，可以在[FAQ](https://github.com/ctripcorp/apollo/wiki/FAQ#7-apollo%E5%92%8Cspring-cloud-config%E7%9B%B8%E6%AF%94%E6%9C%89%E5%95%A5%E4%BC%98%E5%8A%BF%E5%92%8C%E5%8A%A3%E5%8A%BF)中看到。

最后，感谢你的支持，谢谢！
