### ISSUE TITLE
大牛们apollo项目有部署文档吗?

### ISSUE THREAD

**Issue by reckcn** [ctripcorp/apollo#419]
apollo项目如何部署呢，能否提供出文档呢？谢谢。

**Comment by nobodyiam** [comment]
@reckcn 你好，最近有些事情耽搁了，我们会尽快补上部署文档~

**Comment by reckcn** [comment]
@nobodyiam 支持你们，希望以后越做越好。

**Comment by yonglehou** [comment]
.net 客户端什么时候会开源呢？

**Comment by nobodyiam** [comment]
@yonglehou .net客户端有一些公司内部的依赖，如果需求强烈的话，我们可以后续花点时间重构一下~

**Comment by yangl** [comment]
期待部署指南！

**Comment by nobodyiam** [comment]
@reckcn @yangl 我们准备了一个[Quick Start](https://github.com/ctripcorp/apollo/wiki/Quick-Start)，能够在几分钟内在本地环境部署、启动Apollo配置中心。

可以看一下~

**Comment by reckcn** [comment]
@nobodyiam 看了 <a href="https://github.com/ctripcorp/apollo/wiki/Quick-Start">Quick Start</a> 已成功在本地部署，谢谢。

**Comment by nobodyiam** [comment]
@reckcn 感谢支持~后续有任何问题可以随时咨询~

**Comment by reckcn** [comment]
@nobodyiam   

> .net客户端有一些公司内部的依赖，如果需求强烈的话，我们可以后续花点时间重构一下~

需求强烈哈。

**Comment by nobodyiam** [comment]
@reckcn 好的，要不你再新开一个issue要求.net客户端吧，我们后面安排时间搞一下~
