### ISSUE TITLE
apollo项目编译不了 如像依赖了内部一些库？

### ISSUE THREAD

**Issue by jojozoo** [ctripcorp/apollo#434]
![image](https://cloud.githubusercontent.com/assets/3191530/19416901/16c4467e-93d0-11e6-97a4-3137d62d7d44.png)

	<parent>
		<groupId>com.dianping.cat</groupId>
		<artifactId>parent</artifactId>
		<version>1.4.4</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<artifactId>cat-client</artifactId>
	<name>cat-client</name>
	<packaging>jar</packaging>
    
    <version>1.5.0</version>
	<dependencies>
        
        <dependency>
            <groupId>com.ctrip.framework</groupId>
            <artifactId>framework-foundation</artifactId>
            <version>1.1.4</version>
        </dependency>

**Comment by nobodyiam** [comment]
这部分依赖在最外层的pom.xml声明过会从github拉取（travis-ci是可以编译通过的），估计是网络比较慢，没拉下来。
可以尝试直接把mvn-repo分支下载到本地，放到本地maven仓库中：https://github.com/ctripcorp/apollo/tree/mvn-repo

```xml
<repository>
    <id>internal.repo</id>
    <url>https://raw.github.com/ctripcorp/apollo/mvn-repo/</url>
</repository>
```

**Comment by jojozoo** [comment]
唉 依赖的库很多版本都过低了吧？

**Comment by jojozoo** [comment]
![image](https://cloud.githubusercontent.com/assets/3191530/19418998/ef63f67e-9401-11e6-9540-e31eefbf182c.png)
编译不了

**Comment by nobodyiam** [comment]
@jojozoo 我刚刚找了台windows机器，试了下，是可以编译通过的。
另外，我们的项目接了travis-ci，所以如果编译有问题的话，早就会提示了。。
你是否可以把编译的日志输出（执行下面的命令）发给我 song_s@ctrip.com？
```sh
mvn compile --log-file log.txt
```

另外，依赖的库应该说不是最新的，但说不上过低吧。。。依赖的详情可以通过下面链接查看的。
https://www.versioneye.com/user/projects/56e3ce40df573d0043113a24

**Comment by jojozoo** [comment]
能编译了 cat是否用了自己二次开发版本？windows布署是否会存在问题？依赖的库应该算是半年前的了

**Comment by jojozoo** [comment]
用了过多插件 看来直接想用代码布署还不是一时三会搞得掂。。

**Comment by nobodyiam** [comment]
cat是携程内部增强版。
Windows部署理论上应该没问题的，因为我们都是基于Spring boot的，不过还没有测试过。

**Comment by nobodyiam** [comment]
@jojozoo 如果编译没问题的话，请close issue吧~
