### ISSUE TITLE
start failed

### ISSUE THREAD

**Issue by galenzhao** [ctripcorp/apollo#442]
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: URL [jar:file:/root/apollo-build-scripts/service/apollo-service.jar!/lib/apollo-common-0.2.0-SNAPSHOT.jar!/com/ctrip/framework/apollo/common/datasource/TitanEntityManager.class]; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'fat_titan_url' in string value "${fat_titan_url}"

**Comment by nobodyiam** [comment]
@galenzhao 你是通过quick start中的build.sh启动的吗？

里面有一些参数是预先设置好的，建议还是通过build.sh启动

**Comment by galenzhao** [comment]
@nobodyiam
是的，是通过buildsh启动的，我看了这个shell，里边没有这个参数啊

**Comment by nobodyiam** [comment]
@galenzhao 我们的代码是区分运行时profile的，上述的fat_titan_url参数只在ctrip profile才会被运行。
在quick start的[build.sh](https://github.com/nobodyiam/apollo-build-scripts/blob/master/build.sh)里面应该能看到`-Dspring.profiles.active=dev`的，所以通过这个脚本执行的应该是不会尝试读取fat_titan_url的。。

**Comment by galenzhao** [comment]
@nobodyiam 
+ echo '==== starting service ===='
==== starting service ====
+ export 'JAVA_OPTS=-Denv=dev -Ddev_meta=http://localhost:8080 -Dspring.profiles.active=dev -Deureka.service.url=http://localhost:8080/eureka/ -Dspring.datasource.url=jdbc:mysql://localhost:3306/ApolloConfigDB?characterEncoding=utf8 -Dspring.datasource.username=root -Dspring.datasource.password='
+ JAVA_OPTS='-Denv=dev -Ddev_meta=http://localhost:8080 -Dspring.profiles.active=dev -Deureka.service.url=http://localhost:8080/eureka/ -Dspring.datasource.url=jdbc:mysql://localhost:3306/ApolloConfigDB?characterEncoding=utf8 -Dspring.datasource.username=root -Dspring.datasource.password='
+ [[ -f ./service/apollo-service.jar ]]
+ rm -rf ./service/apollo-service.jar
+ ln apollo-all-in-one.jar ./service/apollo-service.jar
+ chmod a+x ./service/apollo-service.jar
+ java -jar '-Denv=dev -Ddev_meta=http://localhost:8080 -Dspring.profiles.active=dev -Deureka.service.url=http://localhost:8080/eureka/ -Dspring.datasource.url=jdbc:mysql://localhost:3306/ApolloConfigDB?characterEncoding=utf8 -Dspring.datasource.username=root -Dspring.datasource.password=' ./service/apollo-service.jar start --configservice --adminservice

我看shell带了这个参数，

**Comment by galenzhao** [comment]
没问题了，多了个‘
