### ISSUE TITLE
mysql db表名大小写

### ISSUE THREAD

**Issue by galenzhao** [ctripcorp/apollo#445]
默认的quickstart里边的
在区分大小写的mysql下 表名全都没转换成小写的

**Comment by nobodyiam** [comment]
感谢反馈，刚刚把sql文件修复了一下。

请先把目前的数据库清除，然后从下面地址下载sql文件后重新导入即可。

https://github.com/nobodyiam/apollo-build-scripts/tree/master/sql

**Comment by nobodyiam** [comment]
@galenzhao 现在是否还有问题？
