### ISSUE TITLE
The requested profile "github" could not be activated because it does not exist.

### ISSUE THREAD

**Issue by jiucai** [ctripcorp/apollo#455]
使用 ./build.sh start 
编译后没有像预期的那样启动，是否您的脚本里面少了代码呢？

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Apollo ............................................. SUCCESS [  2.105 s]
[INFO] Apollo BuildTools .................................. SUCCESS [  2.919 s]
[INFO] Apollo Core ........................................ SUCCESS [  1.680 s]
[INFO] Apollo Client ...................................... SUCCESS [  3.941 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.567 s
[INFO] Finished at: 2016-11-23T11:54:53+08:00
[INFO] Final Memory: 43M/434M
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "github" could not be activated because it does not exist.

有个警告，并没有如下信息：

==== starting service ====
Started [14309]
Waiting for config service startup......
Config service started. You may visit http://localhost:8080 for service status now!
Waiting for admin service startup...
Admin service started
==== starting portal ====
Started [14370]
Waiting for portal startup.......
Portal started. You can visit http://localhost:8070 now!

没法用啊，亲！

**Comment by nobodyiam** [comment]
apollo项目中的build.sh是用于分布式部署的，只负责打包，不会在本地启动。
Quick Start项目需要从另一个项目apollo-build-scripts或者百度网盘下载，请参考Quick Start页面的内容说明，后面我们会修改一下相关的文档说明。

## 1.3 下载Quick Start安装包
我们准备好了一个Quick Start安装包，大家只需要下载到本地，就可以直接使用，免去了编译、打包过程。

安装包共64M，如果访问github网速不给力的话，可以从百度网盘下载。

1. 从Github下载
    * checkout或下载[apollo-build-scripts项目](https://github.com/nobodyiam/apollo-build-scripts)
2. 从百度网盘下载
    * 通过[网盘链接](https://pan.baidu.com/s/1bpcd4Eb)下载
    * 下载到本地后，在本地解压apollo-build-scripts.zip

**Comment by jiucai** [comment]
OK, thanks for your reply.
