### ISSUE TITLE
可能发布脏数据

### ISSUE THREAD

**Issue by dangding** [ctripcorp/apollo#462]
进行如下操作，是否会发布脏数据？如何避免？
1：user1将key1修改为value1；
2：user2将key1修改为value2;
3：user1发布key1；

发布的key1数据为value2，而非value1，并且在发布时user1并不知道是发布的value2；

**Comment by nobodyiam** [comment]
对于生产环境，我们建议打开namespace.lock.switch，打开后一次发布只能有一个人修改，并且需要另一个人审核后才可以发布。

该配置存储在ApolloConfigDB.ServerConfig表中，我们提供的sql中用了默认值false，改为true即可。

通过这个配置，可以避免这种并发的情况。

**Comment by dangding** [comment]
非常感谢你的回答，想再问下，如果是两个人同时操作一个账户呢？namespace.lock.switch能否保证，一次发布只能一个人修改？

**Comment by nobodyiam** [comment]
namespace.lock.switch能保证的是多个账号不能同时修改一个namespace（比key级别大），如果是同一个账号是无法保证的。

**Comment by dangding** [comment]
谢谢~~~
