### ISSUE TITLE
 client 端jdk是否存在降级的可能性

### ISSUE THREAD

**Issue by secwang** [ctripcorp/apollo#483]
我只看文档提到client端只依赖guava,  guava 是 1.6+ 的，是不是存在可能性，client 端可以使用1.6?

**Comment by nobodyiam** [comment]
要支持1.6的话，应该是要改一些代码的。

如String用在switch的地方，泛型的类型推断等。

你可以尝试修改`apollo-core/pom.xml`和`apollo-client/pom.xml`中的java.version属性为`1.6`，然后按照编译提示修改一下。

**Comment by secwang** [comment]
我这两天会试一下，issue 暂时不关了

**Comment by secwang** [comment]
可以支持 ，需要的可以打我这个 patch https://gist.github.com/secwang/095976ed0808a66c342f154639d2f66b

**Comment by nobodyiam** [comment]
非常感谢~

**Comment by yyf365** [comment]
如果现有应用使用的还是1.5的JDK版本，如何能够让client支持呢？

**Comment by nobodyiam** [comment]
1.5应该和1.6差不多，可以试试 @secwang 的patch

**Comment by nobodyiam** [comment]
@DeanJi 我这里是可以打开的，建议再次尝试一下，或者使用科学上网。

**Comment by DeanJi** [comment]
@nobodyiam 用了几台电脑试了都不行啊。公司电脑无法科学上网，如果能发一份给我感激不尽啊。
邮箱：JIJINDING001@pingan.com.cn

**Comment by nobodyiam** [comment]
@DeanJi Sent by mail.

**Comment by DeanJi** [comment]
Thank you. I just saw the patch is also in the Apollo QQ Group.

**Comment by Watermelonljf** [comment]
> Thank you. I just saw the patch is also in the Apollo QQ Group.

你好能给我也来一分patch吗？公司网出不去

**Comment by nobodyiam** [comment]
见附件：[0001-1.6.patch.zip](https://github.com/ctripcorp/apollo/files/2611950/0001-1.6.patch.zip)

**Comment by zhupeng88** [comment]
请问这是基于哪个版本修改的？
