### ISSUE TITLE
何时能够从Maven中央仓库获取？

### ISSUE THREAD

**Issue by ian4hu** [ctripcorp/apollo#515]
目前检索Maven Central仓库，没有找到这个artifact，是否有有计划发布到Maven中央仓库？

**Comment by lepdou** [comment]
没有哪个artifact呢？

**Comment by ian4hu** [comment]
apollo http://repo.maven.apache.org/maven2/com/ctrip

**Comment by nobodyiam** [comment]
@ian4hu 我们暂时还不会上传apollo到中央仓库，目前主要有以下两点阻碍：

1. Apollo有部分依赖还不在中央仓库
2. Apollo客户端目前会把后端的meta server地址打包进去

**Comment by krast** [comment]
```
	<parent>
		<groupId>com.ctrip.framework</groupId>
		<artifactId>framework-parent</artifactId>
		<version>1.3.0</version>
	</parent>
```
如何获取ctrip.framework的jar？

**Comment by nobodyiam** [comment]
这是一个pom，不是jar。项目中默认会连向github作为repository的，如果网络不行的话，可以把mvn-repo这个分支里面的东西下载到本地。

https://github.com/ctripcorp/apollo/tree/mvn-repo/com/ctrip/framework/framework-parent/1.3.0

**Comment by nobodyiam** [comment]
apollo-client已经推送到Maven中央仓库, [点击此链接查看](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.ctrip.framework.apollo%22%20AND%20a%3A%22apollo-client%22)
