### ISSUE TITLE
首页乱码

### ISSUE THREAD

**Issue by wikimore** [ctripcorp/apollo#556]
使用apollo-build-scripts项目构建启动。

![image](https://cloud.githubusercontent.com/assets/1697662/23606381/6eb34256-029b-11e7-9d27-b94c6c3e5bb9.png)

**Comment by wikimore** [comment]
这个是chrome，版本号是56.0.2924.87

**Comment by wikimore** [comment]
用safari打开不是乱码，但是每打开一个页面都要下载一个叫sso_heartbeat的文件

![image](https://cloud.githubusercontent.com/assets/1697662/23606470/d6857796-029b-11e7-8846-fb02af86d84c.png)

**Comment by lepdou** [comment]
@wikimore 
sso_heartbeat 是由于携程sso有失效时间，这个文件的作用就是防止过期的。但是不会出现下载这个文件，这个只是一个iframe。后面我会加一个开关，如果profile != ctrip,就不会加载这个iframe。但是为啥会下载文件，还需要定位一下。
乱码问题也比较诡异，我们也需要定位一下。
多谢 wikimore 提的问题~

**Comment by nobodyiam** [comment]
@wikimore 乱码这个问题之前在社区另一个朋友也有发现，他的场景是同一个服务端，他在ubuntu英文操作系统打开首页乱码，但是其他电脑看到的都是正常的，所以也比较奇怪。

你这边的环境信息是否方便贴一下？客户端操作系统，语言环境？

另外，是否方便把http的response header也贴一下？

**Comment by wikimore** [comment]
我的操作系统是OSX EI Capitan 10.11.6

**Comment by wikimore** [comment]
语言和地区是中国

**Comment by wikimore** [comment]
请求uri是/apps的response header如下：
```
Cache-Control:no-cache, no-store, max-age=0, must-revalidate
Content-Length:339
Content-Type:application/json;charset=UTF-8
Date:Tue, 07 Mar 2017 07:24:11 GMT
Expires:0
Pragma:no-cache
Server:Apache-Coyote/1.1
X-Application-Context:application:dev:8070
X-Content-Type-Options:nosniff
X-Frame-Options:SAMEORIGIN
X-XSS-Protection:1; mode=block
```

index页面的response header 如下：

```
Accept-Ranges:bytes
Cache-Control:no-cache, no-store, max-age=0, must-revalidate
Content-Language:en
Content-Length:5753
Content-Type:text/html;charset=ISO-8859-1
Date:Tue, 07 Mar 2017 07:24:10 GMT
Expires:0
Last-Modified:Mon, 06 Mar 2017 08:18:50 GMT
Pragma:no-cache
Server:Apache-Coyote/1.1
X-Application-Context:application:dev:8070
X-Content-Type-Options:nosniff
X-Frame-Options:SAMEORIGIN
X-XSS-Protection:1; mode=block
```
Content-Type并不同

**Comment by nobodyiam** [comment]
@wikimore 是否方便把/apps和index页面的request header也发一下？

**Comment by wikimore** [comment]
index页面
```
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:en,zh-CN;q=0.8,zh;q=0.6
Cache-Control:no-cache
Connection:keep-alive
Cookie:__utma=111872281.998368703.1456931899.1465439351.1465449247.19; _ga=GA1.1.998368703.1456931899
DNT:1
Host:localhost:8070
Pragma:no-cache
Referer:http://localhost:8070/config.html?
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
```

/apps

```
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:en,zh-CN;q=0.8,zh;q=0.6
Cache-Control:no-cache
Connection:keep-alive
Cookie:__utma=111872281.998368703.1456931899.1465439351.1465449247.19; _ga=GA1.1.998368703.1456931899
DNT:1
Host:localhost:8070
Pragma:no-cache
Referer:http://localhost:8070/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
```

**Comment by nobodyiam** [comment]
@wikimore 多谢提供有价值的信息，我发现在chrome中把英语设为第一语言确实能重现，我们研究一下。

![image](https://cloud.githubusercontent.com/assets/837658/23658932/546d33f4-037f-11e7-94d8-08230c5fc1c1.png)

**Comment by nobodyiam** [comment]
@wikimore #558 应该解决了首页乱码的问题。

主要是因为如果request header中Accept-Language为en时，会设置默认locale为en。

然后spring boot默认的mime mapping中没有加入encoding信息，所以会导致最终返回的content type是iso8859-1，尽管实际的内容是utf8。所以会造成乱码。

**Comment by nobodyiam** [comment]
@wikimore 我们会在v0.6.1时更细quick start的包。

**Comment by nobodyiam** [comment]
@wikimore safari打开会下载文件的问题在 #559 修复了。

**Comment by wikimore** [comment]
太给力了！

**Comment by nobodyiam** [comment]
@wikimore [v0.6.2](https://github.com/ctripcorp/apollo/releases/tag/v0.6.2)已经发布，另外[quick start](https://github.com/nobodyiam/apollo-build-scripts)也已经更新。
