### ISSUE TITLE
无法正常编译

### ISSUE THREAD

**Issue by fengnex** [ctripcorp/apollo#562]
1、在windows 7、jdk8下面执行mvn package的过程中，有很多问题，不能直接编译
因为找不到下面这块，无法编译，需要注释掉：
<parent>
		<groupId>com.ctrip.framework</groupId>
		<artifactId>framework-parent</artifactId>
		<version>1.3.0</version>
	</parent>

2、找不到framework-foundation-1.5.0.jar无法编译，需要手工从apollo-all-in-one.jar里面解压后放到本地；

3、不支持java 7，需要在pom.xml中添加下面这块：
<plugin>  
					<groupId>org.apache.maven.plugins</groupId>  
					<artifactId>maven-compiler-plugin</artifactId>  
					<version>3.3</version>  
					<configuration>  
						<source>1.7</source>  
						<target>1.7</target>  
						<compilerId>eclipse</compilerId>  
					</configuration>  
					<dependencies>  
						<dependency>  
							<groupId>org.codehaus.plexus</groupId>  
							<artifactId>plexus-compiler-eclipse</artifactId>  
							<version>2.2</version>  
						</dependency>  
					</dependencies>  
				</plugin>

4、无法编译<module>apollo-client</module>，注释掉后继续编译

5、报文件夹找不到apollo-master\apollo-core\target\generated-sources\annotations does not exist

请问对工程该怎么才能方便编译？

**Comment by nobodyiam** [comment]
本地编译在wiki上有详细文档的，建议先仔细看一下。
[分布式部署指南](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97)

你所找不到的依赖，默认在pom中会设置github为repository的，如果网络畅通的话，不需要做额外步骤即可编译。

如果网络不好的话，请看到文档中的说明把相关依赖自己下载到本地仓库。

关于Java版本的问题，在文档中也说明的很清楚。服务端是1.8，客户端是1.7，这些信息在pom中都设置好了的。

如果你只是想在本地IDE开发、学习使用的话，建议再阅读[Apollo开发指南
](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97)

**Comment by fengnex** [comment]
谢谢及时回复，等等验证下

**Comment by fengnex** [comment]
抱歉，quick start的确可以，但是disconf-master下面没有build.sh，我遇到的问题是所有的jar都能正常下载，framework-foundation-1.5.0.jar这种也被处理了，但是还是无法通过pom.xml编译出jar。

不知道怎样才能从disconf-master下面编译

**Comment by nobodyiam** [comment]
https://github.com/ctripcorp/apollo/blob/master/scripts/build.sh

**Comment by fengnex** [comment]
看了quick start部分的效果，还是挺好的，有个疑问在这里请教下：
这个和disconf相比，有啥优点和不足呢？谢谢

**Comment by nobodyiam** [comment]
apollo的功能特点在项目首页都有介绍了的，基本功能、高级功能都有提供，部署简单，不需要额外部署其它组件，项目设计、开发模式相对都会新一些吧。

**Comment by fengnex** [comment]
是的，效果、spring boot/cloud都看好，性能、扩展性等非功能特性也看好，UI也不错
为作者点赞

**Comment by fengnex** [comment]
Windows下面用git bash按下面这样编译apollo-master，不行：
$ ./build.sh
==== starting to build config-service and admin-service ====
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.ctrip.framework.apollo:apollo:0.6.1: Failure to find com.ctrip.framework:framework-parent:pom:1.3.0 in http://118.123.170.50:8081/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of nexus has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 10
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.ctrip.framework.apollo:apollo:0.6.1 (D:\devel\os\apollo-master\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.ctrip.framework.apollo:apollo:0.6.1: Failure to find com.ctrip.framework:framework-parent:pom:1.3.0 in http://118.123.170.50:8081/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of nexus has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 10 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
==== building config-service and admin-service finished ====
==== starting to build portal ====
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.ctrip.framework.apollo:apollo:0.6.1: Failure to find com.ctrip.framework:framework-parent:pom:1.3.0 in http://118.123.170.50:8081/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of nexus has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 10
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.ctrip.framework.apollo:apollo:0.6.1 (D:\devel\os\apollo-master\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.ctrip.framework.apollo:apollo:0.6.1: Failure to find com.ctrip.framework:framework-parent:pom:1.3.0 in http://118.123.170.50:8081/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of nexus has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 10 -> [Help 2]
[ERROR]

**Comment by nobodyiam** [comment]
检查一下本地的settings.xml，把
`<mirrorOf>*</mirrorOf>`改成`<mirrorOf>central</mirrorOf>`

**Comment by nobodyiam** [comment]
Apollo的部分依赖项是以[https://github.com/ctripcorp/apollo/tree/mvn-repo](https://github.com/ctripcorp/apollo/tree/mvn-repo)作为远程仓库的，如果希望项目可以自动从远端下载依赖的话，需要注意本地的settings.xml的mirror设置。如果原来mirrorOf设置为*的话，需要做一下修改。

```xml
    <mirrors>
        <mirror>
            <id>nexus</id>
            <mirrorOf>*</mirrorOf>
            <name>public</name>
            <url>http://someUrl/nexus/content/groups/public</url>
        </mirror>
    </mirrors>
```
改为
```xml
    <mirrors>
        <mirror>
            <id>nexus</id>
            <mirrorOf>!internal.repo,*</mirrorOf>
            <name>public</name>
            <url>http://someUrl/nexus/content/groups/public</url>
        </mirror>
    </mirrors>
```

**Comment by nobodyiam** [comment]
@fengnex 麻烦验证下是否解决了你的问题，谢谢~

**Comment by liangzhangping** [comment]
[WARNING] [Ctrip Group Enforcer Rules] 调用http://cmapi.release.ctripcorp.com/api/regular/deploy/judge检查自定义规则出错或超时,根据策略,本次检查跳过自定义规则检查.
[WARNING] Rule 11: ctripgroup.scm.rule.DistributionManagementRule failed with message:
[ERROR] [Ctrip Group Enforcer Rules] Operation timed out; <--- java.net.ConnectException: Operation timed out
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Apollo ............................................. FAILURE [02:33 min]
[INFO] Apollo BuildTools .................................. SKIPPED
[INFO] Apollo Core ........................................ SKIPPED
[INFO] Apollo Common ...................................... SKIPPED
[INFO] Apollo Biz ......................................... SKIPPED
[INFO] Apollo ConfigService ............................... SKIPPED
[INFO] Apollo AdminService ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:34 min
[INFO] Finished at: 2017-03-16T17:00:30+08:00
[INFO] Final Memory: 34M/644M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce (ctrip-group-check) on project apollo: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by nobodyiam** [comment]
@liangzhangping 你是不是从携程内部拿的framework-parent。。。开源版本的framework-parent是不会执行enforcer的。

https://github.com/ctripcorp/apollo/blob/mvn-repo/com/ctrip/framework/framework-parent/1.3.0/framework-parent-1.3.0.pom

**Comment by nobodyiam** [comment]
@fengnex 由于长久没有更新，此issue就先关了。

如果无法下载依赖的话，还有一个办法就是从百度网盘下载所需要的依赖，参见[1.3.2 手动下载到本地](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#132-%E6%89%8B%E5%8A%A8%E4%B8%8B%E8%BD%BD%E5%88%B0%E6%9C%AC%E5%9C%B0)
