### ISSUE TITLE
String.format error

### ISSUE THREAD

**Issue by poppop0911** [ctripcorp/apollo#566]
/root/apollo/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/listener/AppInfoChangedListener.java:39: 错误: [FormatString] extra format arguments: used 0, provided 2
        Tracer.logError(String.format("Update app's info failed. Env = {}, AppId = {}", env, appId), e);
                                     ^
    (see http://errorprone.info/bugpattern/FormatString)

**Comment by lepdou** [comment]
@poppop0911 
非常感谢反馈。
已Fix~
