### ISSUE TITLE
执行./sudo_before_shutdown.sh报错,是否考虑Installation as an init.d service (System V)

### ISSUE THREAD

**Issue by lyg123** [ctripcorp/apollo#568]
具体信息如下：
grep: /usr/lib/systemd/system/ctripapp@100003173.service: No such file or directory
sed: can't read /usr/lib/systemd/system/ctripapp@100003173.service: No such file or directory
./sudo_before_shutdown.sh: line 7: systemctl: command not found

是否可以考虑提供Installation as an init.d service (System V)脚本

**Comment by nobodyiam** [comment]
sudo_before_shutdown.sh 这个没啥用的，是为了解决ctrip内部的一个服务设置问题。

installation as an init.d service脚本不知是否有相关资料可以参考？我们不是太熟悉。。。

**Comment by lyg123** [comment]
有用吧，方便启停，要不然需要跑到每个script下面执行脚本
我也是看到https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#deployment-initd-service得出来的。
主要是脚本中LimitNOFILE=65536这个不知道init.d如何写。

**Comment by nobodyiam** [comment]
感谢建议，我们后面研究一下~

**Comment by lyg123** [comment]
嗯。我这边也研究下

**Comment by nobodyiam** [comment]
目前使用下来，通过startup.sh和shutdown.sh能满足大部分场景，这个issue先关闭了。

如果有更好的建议，可以提Feature Request
