### ISSUE TITLE
请教env加载的优先级问题

### ISSUE THREAD

**Issue by lyg123** [ctripcorp/apollo#569]
env加载的优先级是怎样的
我看日志是
[framework-foundation] /opt/settings/server.properties does not exist or is not readable.
[framework-foundation] C:/opt/settings/server.properties does not exist or is not readable.
[framework-foundation] JVM system property 'env' is blank. Will try to get environment by OS environment variable 'ENV'.
[framework-foundation] Environment is set to [fat] by OS env variable 'ENV'.
是否是先从server.properties->jvm->environment variable
这样的顺序？

**Comment by nobodyiam** [comment]
顺序是system property(jvm) -> environment variable -> server.properties

具体的可以参考framework foundation的[source file](https://github.com/ctripcorp/apollo/blob/mvn-repo/com/ctrip/framework/framework-foundation/1.5.0/framework-foundation-1.5.0-sources.jar)

**Comment by lyg123** [comment]
好的，谢谢！
