### ISSUE TITLE
namespace 授权的时候如果所属组织中包含中文会报错

### ISSUE THREAD

**Issue by vbvbipny** [ctripcorp/apollo#573]
![image](https://cloud.githubusercontent.com/assets/7246660/24390572/636fa5d8-13bc-11e7-852f-0385c2c28a23.png)

如图：由于界面上取到的中文被编码了，提交到后台后会会匹配不上role表中的RoleName 导致授权失败

**Comment by lepdou** [comment]
@vbvbipny 
这个问题我们这边复现一下，如果确实存在这种问题，我们修复一下。

另外，组织建议用英文，因为公共Namespace的名称是需要拼接组织名称的。所以如果有中文的话，代码里就有一堆中文的东西。

非常感谢~

**Comment by lepdou** [comment]
@vbvbipny 
已Fix. 
https://github.com/ctripcorp/apollo/pull/598
