### ISSUE TITLE
有直接部署到docker的步骤吗?

### ISSUE THREAD

**Issue by insoz** [ctripcorp/apollo#574]
有直接部署到docker的步骤吗?

**Comment by nobodyiam** [comment]
目前还没有，不过之前有用户自己部署过了，应该没啥特别的步骤。
不过网络策略需要注意一下，参见[网络策略](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#15%E7%BD%91%E7%BB%9C%E7%AD%96%E7%95%A5)

**Comment by kulovecc** [comment]
可以参考下这个：https://github.com/kulovecc/docker-apollo

**Comment by kirkvicent** [comment]
如果没加白名单限制(白名单为空)还好，如果加了白名单，那白名单验证的则是 docker 容器内的ip地址，而不是宿主机器。

**Comment by nobodyiam** [comment]
什么白名单？
