### ISSUE TITLE
Centos下执行编译错误

### ISSUE THREAD

**Issue by wangyulu** [ctripcorp/apollo#576]
[root@localhost apollo]# ./scripts/build.sh 
==== starting to build config-service and admin-service ====
[INFO] Scanning for projects...
[ERROR] [ERROR] Could not find the selected project in the reactor: apollo-configservice @ 
[ERROR] Could not find the selected project in the reactor: apollo-configservice -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
==== building config-service and admin-service finished ====
==== starting to build portal ====
[INFO] Scanning for projects...
[ERROR] [ERROR] Could not find the selected project in the reactor: apollo-portal @ 
[ERROR] Could not find the selected project in the reactor: apollo-portal -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
==== building portal finished ====
==== starting to build client ====
[INFO] Scanning for projects...
[ERROR] [ERROR] Could not find the selected project in the reactor: apollo-client @ 
[ERROR] Could not find the selected project in the reactor: apollo-client -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
==== building client finished ====

你好，这个错误是由什么导致的呢，我觉得应该还是缺少依赖包的问题吧，希望能帮助解决下，谢谢！

**Comment by nobodyiam** [comment]
这个build.sh写的不是太好，需要`cd scripts;./build.sh`执行

**Comment by wangyulu** [comment]
==== starting to build config-service and admin-service ====
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Failure to find io.spring.platform:platform-bom:pom:2.0.8.RELEASE in https://raw.github.com/ctripcorp/apollo/mvn-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of internal.repo has elapsed or updates are forced @ line 263, column 16
[ERROR] Non-resolvable import POM: Failure to find org.springframework.cloud:spring-cloud-netflix:pom:1.2.3.RELEASE in https://raw.github.com/ctripcorp/apollo/mvn-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of internal.repo has elapsed or updates are forced @ line 270, column 16
[ERROR] Non-resolvable import POM: Failure to find org.springframework:spring-framework-bom:pom:4.3.4.RELEASE in https://raw.github.com/ctripcorp/apollo/mvn-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of internal.repo has elapsed or updates are forced @ com.ctrip.framework:framework-parent:1.3.0, /root/.m2/repository/com/ctrip/framework/framework-parent/1.3.0/framework-parent-1.3.0.pom, line 221, column 25
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-test:jar is missing. @ line 294, column 15
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.ctrip.framework.apollo:apollo:0.6.2 (/usr/local/src/apollo/pom.xml) has 4 errors
[ERROR]     Non-resolvable import POM: Failure to find io.spring.platform:platform-bom:pom:2.0.8.RELEASE in https://raw.github.com/ctripcorp/apollo/mvn-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of internal.repo has elapsed or updates are forced @ line 263, column 16 -> [Help 2]
[ERROR]     Non-resolvable import POM: Failure to find org.springframework.cloud:spring-cloud-netflix:pom:1.2.3.RELEASE in https://raw.github.com/ctripcorp/apollo/mvn-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of internal.repo has elapsed or updates are forced @ line 270, column 16 -> [Help 2]
[ERROR]     Non-resolvable import POM: Failure to find org.springframework:spring-framework-bom:pom:4.3.4.RELEASE in https://raw.github.com/ctripcorp/apollo/mvn-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of internal.repo has elapsed or updates are forced @ com.ctrip.framework:framework-parent:1.3.0, /root/.m2/repository/com/ctrip/framework/framework-parent/1.3.0/framework-parent-1.3.0.pom, line 221, column 25 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-test:jar is missing. @ line 294, column 15
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
==== building config-service and admin-service finished ====
==== starting to build portal ====
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Failure to find io.spring.platform:platform-bom:pom:2.0.8.RELEASE in https://raw.github.com/ctripcorp/apollo/mvn-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of internal.repo has elapsed or updates are forced @ line 263, column 16
[ERROR] Non-resolvable import POM: Failure to find org.springframework.cloud:spring-cloud-netflix:pom:1.2.3.RELEASE in https://raw.github.com/ctripcorp/apollo/mvn-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of internal.repo has elapsed or updates are forced @ line 270, column 16
[ERROR] Non-resolvable import POM: Failure to find org.springframework:spring-framework-bom:pom:4.3.4.RELEASE in https://raw.github.com/ctripcorp/apollo/mvn-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of internal.repo has elapsed or updates are forced @ com.ctrip.framework:framework-parent:1.3.0, /root/.m2/repository/com/ctrip/framework/framework-parent/1.3.0/framework-parent-1.3.0.pom, line 221, column 25
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-test:jar is missing. @ line 294, column 15
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.ctrip.framework.apollo:apollo:0.6.2 (/usr/local/src/apollo/pom.xml) has 4 errors
[ERROR]     Non-resolvable import POM: Failure to find io.spring.platform:platform-bom:pom:2.0.8.RELEASE in https://raw.github.com/ctripcorp/apollo/mvn-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of internal.repo has elapsed or updates are forced @ line 263, column 16 -> [Help 2]
[ERROR]     Non-resolvable import POM: Failure to find org.springframework.cloud:spring-cloud-netflix:pom:1.2.3.RELEASE in https://raw.github.com/ctripcorp/apollo/mvn-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of internal.repo has elapsed or updates are forced @ line 270, column 16 -> [Help 2]
[ERROR]     Non-resolvable import POM: Failure to find org.springframework:spring-framework-bom:pom:4.3.4.RELEASE in https://raw.github.com/ctripcorp/apollo/mvn-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of internal.repo has elapsed or updates are forced @ com.ctrip.framework:framework-parent:1.3.0, /root/.m2/repository/com/ctrip/framework/framework-parent/1.3.0/framework-parent-1.3.0.pom, line 221, column 25 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-test:jar is missing. @ line 294, column 15
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
==== building portal finished ====
==== starting to build client ====
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Failure to find io.spring.platform:platform-bom:pom:2.0.8.RELEASE in https://raw.github.com/ctripcorp/apollo/mvn-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of internal.repo has elapsed or updates are forced @ line 263, column 16
[ERROR] Non-resolvable import POM: Failure to find org.springframework.cloud:spring-cloud-netflix:pom:1.2.3.RELEASE in https://raw.github.com/ctripcorp/apollo/mvn-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of internal.repo has elapsed or updates are forced @ line 270, column 16
[ERROR] Non-resolvable import POM: Failure to find org.springframework:spring-framework-bom:pom:4.3.4.RELEASE in https://raw.github.com/ctripcorp/apollo/mvn-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of internal.repo has elapsed or updates are forced @ com.ctrip.framework:framework-parent:1.3.0, /root/.m2/repository/com/ctrip/framework/framework-parent/1.3.0/framework-parent-1.3.0.pom, line 221, column 25
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-test:jar is missing. @ line 294, column 15
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.ctrip.framework.apollo:apollo:0.6.2 (/usr/local/src/apollo/pom.xml) has 4 errors
[ERROR]     Non-resolvable import POM: Failure to find io.spring.platform:platform-bom:pom:2.0.8.RELEASE in https://raw.github.com/ctripcorp/apollo/mvn-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of internal.repo has elapsed or updates are forced @ line 263, column 16 -> [Help 2]
[ERROR]     Non-resolvable import POM: Failure to find org.springframework.cloud:spring-cloud-netflix:pom:1.2.3.RELEASE in https://raw.github.com/ctripcorp/apollo/mvn-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of internal.repo has elapsed or updates are forced @ line 270, column 16 -> [Help 2]
[ERROR]     Non-resolvable import POM: Failure to find org.springframework:spring-framework-bom:pom:4.3.4.RELEASE in https://raw.github.com/ctripcorp/apollo/mvn-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of internal.repo has elapsed or updates are forced @ com.ctrip.framework:framework-parent:1.3.0, /root/.m2/repository/com/ctrip/framework/framework-parent/1.3.0/framework-parent-1.3.0.pom, line 221, column 25 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-test:jar is missing. @ line 294, column 15
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException


按照上面所说的执行又报了如下错误，POM的问题？

**Comment by nobodyiam** [comment]
看上去是maven没有正确配置仓库地址，导致只从apollo的仓库获取依赖了，没有从中央仓库或公司的私服拉取依赖。比如io.spring.platform:platform-bom:pom:2.0.8.RELEASE这个依赖是在[maven中央仓库](http://search.maven.org/#artifactdetails%7Cio.spring.platform%7Cplatform-bom%7C2.0.8.RELEASE%7Cpom)的。

Non-resolvable import POM: Failure to find io.spring.platform:platform-bom:pom:2.0.8.RELEASE in https://raw.github.com/ctripcorp/apollo/mvn-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of internal.repo has elapsed or updates are forced @ line 263, column 16

**Comment by wangyulu** [comment]
<mirrors\>
   <mirror\>
      <id\>maven-net-cn</id\>
      <mirrorOf\>central</mirrorOf\>
      <name\>Maven China Mirror</name\>
      <url\>http://repo.maven.apache.org/maven2/</url\>
    </mirror\>
</mirrors\>

按时上面的配置，编译问题已经解决了，但在下载依赖包的过程中可能由于网络问题导致中断，多试几次就ok了。
谢谢 @nobodyiam
