### ISSUE TITLE
一套配置中心服务端配置3个环境的配置，是否支持？如何操作？自测貌似不行

### ISSUE THREAD

**Issue by myfreeway** [ctripcorp/apollo#582]
操作步骤：
1、数据库配置了apollo.portal.envs=dev,fat,uat
2、打包时，scripts/build.sh是这样的：
```
# meta server url
dev_meta=http://localhost:8080
fat_meta=http://localhost:8080
uat_meta=http://localhost:8080
pro_meta=http://localhost:8080
```
3、上portal后台，依次点击dev/fat/uat三个环境，使用文本模式创建key一样的三套配置，并发布
4、自己应用集成客户端，并用此参数启动-Denv=dev -Ddev_meta=http://10.20.100.79:8080。
5、问题来了：当变化env为其他两个环境名启动时，发现每次获取的配置都是最后一次发布的配置。不能根据环境来获取配置。
请问如何解决？是否只能一套服务端只能使用一个环境？
重点：每套环境的配置项key名都是一样的，只是内容不一样。
多谢！

**Comment by nobodyiam** [comment]
每个环境的meta server，config service，admin service和apolloconfigdb都是不同的。你的例子里面不同的环境其实是同一套配置环境，自然是不对的，可以参考一下[分布式部署指南-环境](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#14%E7%8E%AF%E5%A2%83)

**Comment by myfreeway** [comment]
感谢非常及时的回复。按照参考已经搞定。果然要配置多套service，共一套portal。
