### ISSUE TITLE
请问可以自定义端口吗？

### ISSUE THREAD

**Issue by iswu2013** [ctripcorp/apollo#583]

**Comment by nobodyiam** [comment]
每个startup.sh里面都可以修改SERVER_PORT的。如https://github.com/ctripcorp/apollo/blob/master/apollo-configservice/src/main/scripts/startup.sh#L6

adminservice和portal的端口修改相对随意一些，建议不要修改configservice的端口，因为configservice的ip:port会在多个地方配置，所以如果修改了端口，需要连带改其它配置的。
