### ISSUE TITLE
打包的问题。如何把apollo-env.properties配置文件从core的jar包移到外面？

### ISSUE THREAD

**Issue by myfreeway** [ctripcorp/apollo#584]
操作的目的是一个porta配置多套环境的配置。
按照分布式部署指南，我修改scripts/build.sh的
`dev_meta=http://dev-config:8080
fat_meta=http://fat-config:8080
uat_meta=http://uat-config:8080
pro_meta=http://pro-config:8080`
最后发现这几个参数只被打进apollo-portal-0.6.2-dev.zip/apollo-portal-0.6.2.jar/lib/apollo-core-0.6.2.jar/apollo-env.properties。
**我想在外部设置这几个参数的值，应该怎么操作呢？**
目前尝试过的办法有以下几种，都无效。
把最终的apollo-env.properties放在
apollo-portal-8070-dev/config/apollo-env.properties
apollo-portal-8070-dev/apollo-env.properties
把配置项放到apollo-portal-8070-dev/config/application-dev.properties
都无效。
谢谢！

**Comment by nobodyiam** [comment]
启动portal的时候通过-Ddev_meta=xxx可以传入的，可以修改portal的startup.sh中的JAVA_OPTS。

另外，把apollo-env.properties放在和apollo-portal-0.6.2.jar一个目录下不可以吗？

**Comment by myfreeway** [comment]
把apollo-env.properties放在和apollo-portal-0.6.2.jar一个目录下，也不行。
经测试，发现【启动portal的时候通过-Ddev_meta=xxx可以传入的，可以修改portal的startup.sh中的JAVA_OPTS。】这样才可以。
感觉有点不合逻辑。我把application-dev.properties放到config目录里，可以覆盖common包的配置文件。资料也说config的配置文件优先级最高。但是不知道为什么core包的配置文件覆盖不了。

**Comment by nobodyiam** [comment]
可能是加载配置文件的姿势不对，不过只是猜测

https://github.com/ctripcorp/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/apollo/core/utils/ResourceUtils.java#L21

**Comment by myfreeway** [comment]
呵呵，有可能是这行代码。common包怎么加载配置文件呢？他能覆盖jar包里的properties。

**Comment by nobodyiam** [comment]
application-dev.properties是Spring加载的，可能有些不同，后面研究一下~

**Comment by nobodyiam** [comment]
@myfreeway 研究了一下Spring boot加载配置文件的顺序，发现它会优先从working directory而非classpath加载配置文件，所以我也简单改了一下，可以实现你描述的效果了，参见Pull Request #607。

**Comment by nobodyiam** [comment]
[0.7.0](https://github.com/ctripcorp/apollo/releases/tag/v0.7.0)已经发布，此issue先关闭了~
