### ISSUE TITLE
搞了半天，windows上跑不起来

### ISSUE THREAD

**Issue by ExtremeYu** [ctripcorp/apollo#585]

**Comment by ExtremeYu** [comment]
一个是maven部分插件太新，所以eclipse下报错，还有就是总是找不到properties文件

**Comment by nobodyiam** [comment]
如果是demo用途，建议用[quick start](https://github.com/ctripcorp/apollo/wiki/Quick-Start)。

如果是本地IDE启动，eclipse和idea都是没问题的，可以参考[Apollo开发指南](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97)操作。

**Comment by nobodyiam** [comment]
```还有就是总是找不到properties文件```

这个具体的错误信息是啥？

**Comment by nobodyiam** [comment]
一直没有响应，先关闭了。
