### ISSUE TITLE
服务注册发现模块  支持grpc吗？

### ISSUE THREAD

**Issue by iamtiancaif** [ctripcorp/apollo#586]
如题。
谢谢～!   : )

**Comment by nobodyiam** [comment]
服务注册发现模块是基于Eureka的，目前仅用作Apollo自身的服务注册和发现。

不过理论上Eureka也是可以用来做grpc服务的注册和发现吧，只是可能需要一些整合的工作。

**Comment by iamtiancaif** [comment]
“仅用作Apollo自身的服务注册和发现"，  如果我基于Apollo，做其他系统的服务注册发现，工作量大吗？假如我只有两三个人在开发。

这里有个谷哥的技术支持Ray做了一个，不过不是很完善。
https://github.com/saturnism/spring-boot-starter-grpc
目前支持注册发现，不支持health check。 我试用的时候，手动停掉service，在eureka上却还显示up的状态。不知道是不是因为没有health check的原因。
demo的图片： https://ton.twitter.com/i/ton/data/dm/850809585673699331/850809578170101760/C12U81eY.jpg


而Ray说近期没有做 health check 的计划，不知道你们有没有这个计划。  另外grpc的团队有在做loadbalancer，  V2已经实现了，你们有考虑接入吗？

https://docs.google.com/document/d/1exE0_QNwbHJesD-Opl2D6qX1wujADkUm5OpFykks3C8/edit#heading=h.s7cl5qvo4ucv


和Ray的相关聊天记录：
for health checking... that's tricky
because eureka doesn't deal w/ http/2
and you can't expose http/1 health checks via http/2
you'll need to serve 2 ports
e.g., listen to health checks on port 8080 (w/ Jetty starter, not Tomcat)
or, expose your own port w/ netty

**Comment by nobodyiam** [comment]
Eureka的health check其实是客户端发起的，不是服务端定期检查的，所以理论上是可以实现的，这部分也可以参考我之前写的一篇深入分析Eureka的文章 - http://nobodyiam.com/2016/06/25/dive-into-eureka/

因为Apollo专注于实现配置中心的功能，服务注册/发现只是我们使用的一个组件，所以我们不会花很多精力去实现Eureka接入grpc。

**Comment by iamtiancaif** [comment]
谢谢～
