### ISSUE TITLE
如果把Eureka换成zk 难度大吗

### ISSUE THREAD

**Issue by Liubey** [ctripcorp/apollo#588]
公司既有框架，很难引入另一个“zk”（当然，Eureka是另一个zk这句话肯定要被喷）

**Comment by nobodyiam** [comment]
按照目前的设计，可以认为eureka是apollo的内部实现，对外部是不可见的，所以也没有需要把eureka换成zk吧。

如果要换的话，就需要自己实现相关服务注册和发现逻辑了，改动量还是有一些的。
