### ISSUE TITLE
请教关于热更新配置的问题

### ISSUE THREAD

**Issue by myfreeway** [ctripcorp/apollo#593]
spring应用，已经集成客户端，并且加入了更新监听器，如果配置有更新，那么怎么更新spring初始化的bean呢？比如数据库连接池，某些service的某些属性。

**Comment by lepdou** [comment]
可以在客户端增加一个config change listener，在listener里面做这些事情~

**Comment by nobodyiam** [comment]
我们增加了一个代码示例演示动态切换数据源，可以参考一下：https://github.com/ctripcorp/apollo-use-cases/tree/master/dynamic-datasource
