### ISSUE TITLE
ApolloConfigDB.ServerConfig 里配置eureka.service.url 

### ISSUE THREAD

**Issue by mengyilangan** [ctripcorp/apollo#602]
如果 ： eureka.service.url  配置了两个url，其中一个是错误的，之后又将此错误的删除，会出现一种情况就是：一致出现赋值错误，一个永久性的任务错误
 @![image](https://cloud.githubusercontent.com/assets/24906082/25427814/4b343ff0-2aa6-11e7-8809-dcee3acfdfde.png)

**Comment by nobodyiam** [comment]
eureka.service.url每分钟会更新的，在短期内会出现这个错误吧，修正数据后，应该过1分钟就会恢复的。
