### ISSUE TITLE
openapi 支持集群的创建和删除？

### ISSUE THREAD

**Issue by kdlan** [ctripcorp/apollo#610]
请问下是否有这方面的考虑？代码大体看了一下，支持起来也不算复杂。openapi 里面新增一个 controller，还有赋权的 `/open/manage.html` 新增一个表单以及对应的 controller 就行了。如果有这方面考虑的话可以我这边开发好提一个 PR 过来

**Comment by lepdou** [comment]
@kdlan 
Open API创建Namespace的代码已合到master
