### ISSUE TITLE
apollo-buildtools中deploy_jenkins.sh#L34脚本问题

### ISSUE THREAD

**Issue by lyg123** [ctripcorp/apollo#611]
https://github.com/ctripcorp/apollo/blob/master/apollo-buildtools/src/main/scripts/deploy_jenkins.sh#L34

应该是判断APP_SHUTDOWN_SCRIPT脚本是否存在，而不是APP_STARTUP_SCRIPT 
并且应该把33行代码移到到下面的if中去吧

**Comment by nobodyiam** [comment]
应该没有错，只是写的不太清楚，对一些条件判断比较松。

逻辑是: 如果在老版本的目录中发现了启动脚本，那么尝试执行关闭脚本。

**Comment by lyg123** [comment]
好，感谢回答
我当时以为逻辑是：如果在老版本中发现关闭脚本，那么尝试执行关闭脚本。
其实感觉都差不多。
