### ISSUE TITLE
[文档] 小建议

### ISSUE THREAD

**Issue by leonzhouwei** [ctripcorp/apollo#613]
喜欢 apollo 清秀的界面，赞一个！顺带着提个小建议，贵司的各个开源项目的文档（例如还有 x-pipe），建议对于英文数字特殊字符等，前后各加一个英文半角空格，从而和中文明显地分隔开，这样阅读体验会更好。

**Comment by nobodyiam** [comment]
哈哈，好的，感谢建议，我们后面会注意一下~
