### ISSUE TITLE
这个和百度的disconf相比有什么优点？

### ISSUE THREAD

**Issue by sevenma** [ctripcorp/apollo#615]

**Comment by nobodyiam** [comment]
由于我们自己并非Disconf的资深用户，所以无法主观地给出评价。

不过之前Apollo技术支持群中的热心网友[@Krast](https://github.com/krast)做了一个[开源配置中心对比矩阵](https://github.com/ctripcorp/apollo/files/983064/default.pdf)，可以参考一下。

**Comment by sevenma** [comment]
好的，谢谢哦
