### ISSUE TITLE
关于Portal如何接入SSO的问题

### ISSUE THREAD

**Issue by flysqrlboy** [ctripcorp/apollo#619]
如题。我之前没接入过SSO，不太清楚如何接入。能提供些Portal接入的demo吗？我看了com.ctrip.framework.apollo.portal.spi.包下的类，没有发现登录的接口。奇怪。portal没有登录功能怎么控制不同用户的权限呢？

**Comment by nobodyiam** [comment]
一般sso的话，登录都是跳转到sso的界面做的。

apollo的spi其实不管事实上用户是怎么登录的，它只需要实现获取当前用户、查询用户等接口。也就是说apollo本身是不负责authentication的，它只负责authorization。

如果公司没有sso可以接入的话，那就要自己写个登录界面控制登录了。

**Comment by flysqrlboy** [comment]
了解

**Comment by flysqrlboy** [comment]
@lepdou 作者已添加了基于spring security的简单支持 [Portal 实现用户登录功能](https://github.com/ctripcorp/apollo/wiki/Portal-%E5%AE%9E%E7%8E%B0%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95%E5%8A%9F%E8%83%BD)
Thanks！
