### ISSUE TITLE
Mysql 要求 5.6.5 +

### ISSUE THREAD

**Issue by vincent927** [ctripcorp/apollo#621]
在官网找不到符合条件的Mysql版本

**Comment by lepdou** [comment]
可以从百度上下载：http://rj.baidu.com/soft/detail/12585.html

**Comment by nobodyiam** [comment]
5.6.5+是指5.6.5以后的版本，比如目前官网最新是5.7.18，也是满足要求的。

https://dev.mysql.com/downloads/mysql/
