### ISSUE TITLE
动态更新值

### ISSUE THREAD

**Issue by qiankunli** [ctripcorp/apollo#622]
[Java客户端使用指南](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)中提到：出于安全性考虑，目前placeholder只会在启动的时候赋值，在运行过程中即便在Apollo上修改发布了配置，placeholder的值也不会更新。

所谓的出于安全性考虑，是怕修改值时，发生线程安全问题么？

**Comment by nobodyiam** [comment]
线程安全是一方面，主要是无法事先预知代码是怎么用bean里面一个变量的值的，如果在运行时直接改掉可能会出现无法预料的问题。如果需要更新的话，可以看一下文档中建议的几种方式。
