### ISSUE TITLE
PropertySourcesProcessor 的 实例化

### ISSUE THREAD

**Issue by qiankunli** [ctripcorp/apollo#623]
如果只是在xml中配置bean，却未使用EnableApolloConfig注解引发ApolloConfigRegistrar执行registerBeanDefinitions方法的执行，xml中的配置貌似无法正常解析。

在xml中显示配置<bean class="xxx.ConfigPropertySourcesProcessor"/> 可以解决这个问题

是否有更好的方式使ConfigPropertySourcesProcessor自动注册呢

**Comment by nobodyiam** [comment]
如果是纯xml配置的话，是不需要EnableApolloConfig的，只需要在XML中加入配置即可。这里需要显式配置的原因是，有很多情况是需要注入非默认application namespace的配置，自动注册无法实现。更多信息，可以参考Java客户端使用指南。
```xml
<apollo:config/>
```
