### ISSUE TITLE
configservice中的eureka服务

### ISSUE THREAD

**Issue by ccc-rrr** [ctripcorp/apollo#624]
一般来说如果用spring cloud开发的话会有独立的eureka服务，但是configservice也是一个eureka服务，这样就有些重复了，能不能把configservice中的eureka服务剥离出来？在有eureka服务的时候给configservice配置上已有的eureka的url，如果没有eureka服务的话要么单独部署eureka服务要么做一个带eureka服务的configservice。

**Comment by nobodyiam** [comment]
可以的，eureka服务的配置本来就是在ApolloConfigDB.ServerConfig中以`eureka.service.url`做配置的。

修改[ConfigServiceApplication](https://github.com/ctripcorp/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/ConfigServiceApplication.java)，把`@EnableEurekaServer`改成`@EnableEurekaClient`应该就可以了。
