### ISSUE TITLE
多环境配置问题

### ISSUE THREAD

**Issue by fenghlkevin** [ctripcorp/apollo#626]
我看了 集群部署的说明，
1. 如果我有 dev、uat、prod 三套环境 我需要build三套configservice、adminservice，需要三个mysql数据库
同时要build一套 portal？
我的理解对么？ 这个我试验了一下 确实如此，全套集群下来mysql与服务器的数量有点多

2. 如果改成这样配置的话，还需要维护mysql中的配置信息，为什么没有使用git方式呢？

3. 再对一个问题，现在创建了private namespace 是无法删除的，没有途径删除这个吗？比如我项目创建错了等等

**Comment by fenghlkevin** [comment]
同时还有一个问题，如果我其中一个mysql挂掉了 ，里面的配置是不是就会收到影响？

**Comment by ccc-rrr** [comment]
那对于本机开发环境用起来岂不是也很麻烦了？！

**Comment by nobodyiam** [comment]
目前读取配置是基于数据库的，不过在客户端是有缓存的，所以服务挂掉也影响不大。

后续，我们会上一个版本，会在config service缓存配置，这样数据库挂掉的话，影响更小一些。

但是，不管怎么样，数据库是单点这本身就不太合理。

@ccc-rrr 开发环境用起来具体麻烦在哪里？对于客户端而言，只是发起一个http调用，和具体有多套也没啥关系。

**Comment by fenghlkevin** [comment]
我 新加了一个问题 2，3 麻烦帮忙看下，谢谢

**Comment by nobodyiam** [comment]
2. 使用数据库或git都没有本质区别，我们选用数据库的原因是不想增加其他依赖，已经用了数据库了，为啥还要再引入一个新的外部依赖呢？

3. private namespace目前确实是无法删除的，因为我们实际场景用使用private的情况很少，所以暂时没提供删除的功能。

**Comment by fenghlkevin** [comment]
感谢。
关于问题3 能否提供一个脚本用于删除private的情况。或者告诉我下都需要删除哪些表？

**Comment by nobodyiam** [comment]
保险起见，使用软删即可，IsDeleted设为1。

涉及的表有：

1. ApolloPortalDB.AppNamespace
2. ApolloPortalDB.Permission
3. ApolloPortalDB.Role
4. ApolloPortalDB.RolePermission
5. ApolloPortalDB.UserRole
6. ApolloConfigDB.AppNamespace
7. ApolloConfigDB.Commit
8. ApolloConfigDB.GrayReleaseRule（如果配置过灰度的话）
9. ApolloConfigDB.Namespace
10. ApolloConfigDB.Item
11. ApolloConfigDB.Release
12. ApolloConfigDB.ReleaseHistory

**Comment by fenghlkevin** [comment]
非常感谢
