### ISSUE TITLE
加载自定义的本地配置

### ISSUE THREAD

**Issue by fenghlkevin** [ctripcorp/apollo#628]
我看了一下 defaultConfig，可以加载 resource文件。
但是业务上还不能满足我的想法，我想修改下defaultconfig的加载方法 来达到我的目的，
有没有办法不修改源代码完成呢？

**Comment by nobodyiam** [comment]
第一种方法是实现自己的spi，实现自己的ConfigFactory，这样就可以注入自己的Config实现。

第二种方式适用于使用Spring的情况，Apollo本身是作为Spring的一个Property Source的，你也可以把自己本地的配置作为一个Property Source插入到Spring里面。

**Comment by fenghlkevin** [comment]
感谢
