### ISSUE TITLE
无法删除namespace

### ISSUE THREAD

**Issue by fenghlkevin** [ctripcorp/apollo#629]
像这种情况怎么删除
`发现有 1 个实例正在使用Namespace(SVR.S1)，删除Namespace将导致实例获取不到配置。
请到 “实例列表” 确认实例信息，如已确认删除Namespace将不会导致实例异常， 请联系Apollo相关负责人删除Namespace`

**Comment by nobodyiam** [comment]
如果确认要删，可以先把instance config中相关的记录删掉，或者等待它一天过期。

**Comment by fenghlkevin** [comment]
明白了。。谢谢。。

**Comment by x00422559** [comment]
请问如何去掉instance config中相关的记录？我也遇到类似的情况，将tomcat应用进程停掉，这个instance config中还是有记录，导致无法删除

**Comment by nobodyiam** [comment]
默认24小时过期

如果需要强行删除InstanceConfig的话，可以在数据库中操作一下

或者也可以使用管理员工具中的删除appnamespace功能删除
