### ISSUE TITLE
需求建议

### ISSUE THREAD

**Issue by fenghlkevin** [ctripcorp/apollo#630]
个人觉得 对 namespace 、cluster的 管理不够人性化，希望可以改进一下。

**Comment by nobodyiam** [comment]
具体点？

**Comment by fenghlkevin** [comment]
1. cluster新增后无法删除，我觉得至少能删除
2. public namespace之前我记得提过一次，我觉得也是缺少删除
3. 项目 建议也能增加删除功能

暂时只想到了这几项，是我使用过程中的感受，毕竟有时候要测试 有时候会写错

**Comment by lepdou** [comment]
1. 删除cluster有REST接口可以删除，没有开放给用户
2. public Namespace现在是当Namespace没有实例在使用，且没有关联的Namespace时，可以删除
3. 项目现在除了appId不能修改之外，其它信息都可以修改，大部分情况就没必要删除了。

因为删除需要删除一系列关联的表，而且要考虑很多前提条件。现在除了，删除app，另外两个都有对应的接口，如果你想开放给用户，可以稍微改造一下就好了。

**Comment by fenghlkevin** [comment]
删除cluster接口能提供一下么

**Comment by lepdou** [comment]
@PreAuthorize(value = "@permissionValidator.isSuperAdmin()")
  @RequestMapping(value = "apps/{appId}/envs/{env}/clusters/{clusterName:.+}", method = RequestMethod.DELETE)

只有超级管理员能删除
