### ISSUE TITLE
public 的 namespace 即使项目不存在、或者未关联也能被读取 

### ISSUE THREAD

**Issue by daigong** [ctripcorp/apollo#632]
Hello:

感谢这么cool的项目；我们在使用过程中发现，如果建立一个公共的namespace ，然后通过http方式获得配置，即便项目不存在【或者项目存在，未关联该公共的namespace 】也返回配置文件的值；操作步骤如下：

1）建立一个 公共的namespace ；我的Demo：  DEVOPS部门的 apollo-config-to-file 
2）建立一个项目并关联此公共的namespace；我的Demo： 项目ID：redmine 、关联 DEVOPS.apollo-config-to-file 
3）在 DEVOPS.apollo-config-to-file 中填写任意的值并发布
4）通过http获得配置
case 1：
预计可以获得正取的值：
http://$apollo-config-url:8080/configfiles/json/redmine/default/DEVOPS.apollo-config-to-file
结果可以获得

case 2：
预计应该没有值返回
http://$apollo-config-url:8080/configfiles/json/notexistsproject/default/DEVOPS.apollo-config-to-file

但是却有配置值返回

有些奇怪，本意上是这么设计的么？这样意味着公共配置能被任何一个未关联的项目读取；java client 我没有尝试，最近有时间的话我也会试一下；

**Comment by daigong** [comment]
补充：我是在  spring-security-auth 分支上发现的问题:

commit 733abdd873761dc419f27378c8a4dccb09728f1f
Author: lepdou <lepdou@126.com>
Date:   Thu May 18 18:13:17 2017 +0800

    support spring security auth

**Comment by qmwu2000** [comment]
对的，就是这么设计的。

公共的namespace的本意是给基础中间件设计的，会有场景是中间件依赖apollo配置，中间件被业务应用依赖，但是业务应用并没有在apollo中建立项目。既然配置是可以继承（并可覆盖），那么中间件就不能受制于业务应用在Apollo中有没有建立项目；另一方面，公共的配置对业务应用不做项目应该是只读的，所以不会有副作用。



发自我的 iPhone

**Comment by daigong** [comment]
收到、多谢
