### ISSUE TITLE
请问这个可以替代spring cloud config server吗？

### ISSUE THREAD

**Issue by ExtremeYu** [ctripcorp/apollo#633]

**Comment by nobodyiam** [comment]
可以的，在FAQ页面有相关阐述，[apollo和Spring Cloud Config相比有啥优势和劣势？](https://github.com/ctripcorp/apollo/wiki/FAQ#7-apollo%E5%92%8Cspring-cloud-config%E7%9B%B8%E6%AF%94%E6%9C%89%E5%95%A5%E4%BC%98%E5%8A%BF%E5%92%8C%E5%8A%A3%E5%8A%BF)。Apollo的客户端可以通过API方式使用，也可以通过Spring集成方式使用，Spring集成方式的实现原理和Spring Cloud Config一样的，所以可以平滑替代。

**Comment by ExtremeYu** [comment]
spring boot admin 监控页面，能识别apollo为配置服务器吗

**Comment by nobodyiam** [comment]
这个目前应该没有集成，不知你是否了解相关资料？我们可以看看是否有可能做一点改动纳入spring boot admin的监控页面

**Comment by beykery** [comment]
不是纳入spring boot admin监控，而是像它一样，把自己可以作为一个普通的应用注册到eureka等注册中心。这样的好处是，不需要修改原来的应用，而仅仅是添加一个新的应用并注册到注册中心而已。不会引起大规模修改。

**Comment by nobodyiam** [comment]
如果是这样的话，应该只是一个简单配置，如果需要的话，你可以在portal中引入eureka的依赖并标注为EurekaClient，再配置一下eureka服务的地址就OK了。

后续我们看下这个是否是一个通用性的场景。

**Comment by ExtremeYu** [comment]
![w50cz x8 qzh4 2_zt qrce](https://user-images.githubusercontent.com/16620268/26958292-643b2eaa-4cfc-11e7-9588-7e03df1b3a50.png)
spring cloud config server 可以显示出自己目前的profile状态 apollo 就是个 up ，也就是说spring cloud 就是单单把apollo当做了一个普通应用了，然而我觉得应该让spring cloud所有成员吧apollo 当做跟spring cloud config server 一样来对待，这样达到原生级别的支持我觉得更好

**Comment by nobodyiam** [comment]
把apollo当做跟spring cloud config server一模一样来对待应该是不可行的，因为apollo的后端模型和spring cloud config server是很不一样的。

不过这个思路还是可取的，就是注册到Eureka的时候提供更多的内部信息甚至是一些监控等，我们后面研究一下吧，感谢建议。

**Comment by ExtremeYu** [comment]
注册到zookeeper，因为我用的注册中心是spring-cloud-zookeeper-all

**Comment by nobodyiam** [comment]
这个Issue暂时先关闭了，接入spring boot admin的事项我们这边先记一下。

如果有更好的建议，可以提Feature Request

**Comment by ScienJus** [comment]
Spring Cloud Config 能够有这些信息是因为自己实现了 `ConfigServerHealthIndicator`，其实 Apollo 也可以实现一个定制的 `HealthIndicator`，基本上可以在 Admin 或是 Discovery 中通用了。

**Comment by jiming** [comment]
Apollo 是否可以支持 org.springframework.cloud.context.config.annotation.RefreshScope 的功能呢，这个看上去是个很棒的特性

**Comment by nobodyiam** [comment]
支持的，具体可以参考[3.2.2 Spring Placeholder的使用](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#322-spring-placeholder%E7%9A%84%E4%BD%BF%E7%94%A8)中的第三点：使用Spring Cloud的RefreshScope

**Comment by jiming** [comment]
谢谢，太棒了
