### ISSUE TITLE
使用外部eureka器需要怎么配置，外部eureka需要basic认证时，meta服务配置需要如何调整

### ISSUE THREAD

**Issue by expectfly** [ctripcorp/apollo#634]
1.因为项目本身eureka已经在用了，不希望维护多分，使用外部eureka器需要怎么配置。

2.外部eureka需要basic认证时，meta服务配置需要如何调整

**Comment by nobodyiam** [comment]
1. 修改ApolloConfigDB.ServerConfig的[eureka.service.url配置](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#1eurekaserviceurl---eureka%E6%9C%8D%E5%8A%A1url)

2. 把[ConfigServiceApplication](https://github.com/ctripcorp/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/ConfigServiceApplication.java#L25)中的`EnableEurekaServer`改为`EnableEurekaClient`

3. `eureka需要basic认证`，这个应该是eureka自身的一些配置吧，config service和admin service此时就是普通的eureka client，你可以按照eureka相关的说明做对应配置

**Comment by expectfly** [comment]
感谢回答，解答很及时，赞一个
