### ISSUE TITLE
阅读代码过程中遇到一些问题，请指教

### ISSUE THREAD

**Issue by zj19880617** [ctripcorp/apollo#643]
你好，我在阅读源码的时候，在设计章节，看到如下内容：

> Config Service有一个线程会每秒扫描一次ReleaseMessage表，看看是否有新的消息记录，参见ReleaseMessageScanner 

在这个类里，看到**ReleaseMessageRepository**这个接口，但是在代码中并没有找到实现类，勉强找到了AOP的配置类，但依然不明白执行的具体逻辑在哪里。在下不才，刚开始接触，不太明白具体的实现细节，麻烦指点一二。

**Comment by nobodyiam** [comment]
这个是spring data jpa的用法，具体看下对应的[文档](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/)。

**Comment by zj19880617** [comment]
感谢 @nobodyiam 的回答，该问题已经解决。
不过，又遇到了另一个问题。我准备将apollo和spring cloud zuul结合使用，以达到动态调整路由规则的目的。我使用了指南中提到的
@Configuration
@EnableApolloConfig
这两个注解，配置在apollo中的路由规则已经可以成功的获取到了。但是我追加了@RefreshScope注解后，新发布的配置没有能够触发zuul的路由规则刷新，这个地方有什么技巧来实现吗？

**Comment by nobodyiam** [comment]
仔细看一下[RefreshScope](http://cloud.spring.io/spring-cloud-static/docs/1.0.x/spring-cloud.html#_refresh_scope)的文档吧。

简而言之，

1. 在需要刷新配置的bean上加`@RefreshScope`，在你的case中，`@RefreshScope`得加在zuul使用配置的bean上才会有用的，不确定这个你是否能加抑或是它本来就有？
2. 加一个Apollo的ConfigChangeListener，然后在配置变化时调用RefreshScope的`refreshAll()`或者`refresh(String name)`的方法。

**Comment by zj19880617** [comment]
@nobodyiam 感谢你的回答。我现在启用actuator模块，手动调/refresh端点是可以实现动态刷新的。但是在listener里调用RefreshScope的refreshAll方法却不行，可能就像你说的，@RefreshScope得加在zuul使用配置的bean上才会有用，而那个bean上没有，所以refresh不生效。我现在的做法是在listener里监听到配置更新后调用/refresh端点，有点蹩脚，不过也实现了功能，谢谢你。

**Comment by nobodyiam** [comment]
@zj19880617 /refresh endpoint本质上就是调用refreshAll()的呀。。你debug看下`org.springframework.cloud.context.refresh.ContextRefresher#refresh`这个方法中使用到的scope和你自己listener中的RefreshScope有啥区别？

另外，你的listener中的RefreshScope对象应该是Spring注入的，不是你自己new的吧？

![image](https://user-images.githubusercontent.com/837658/27424569-188e7a54-5768-11e7-9176-d94ea2ea0d47.png)

**Comment by zj19880617** [comment]
@nobodyiam 多谢提醒，就在你发的截图里，org.springframework.cloud.context.refresh.ContextRefresher#refresh在调用RefreshScope的refreshAll()方法前做了一系列操作，发布了一个事件。我在之前调用RefreshScope的refreshAll()方法的地方改成调用ContextRefresher.refresh()，就可以正常刷新了。

**Comment by nobodyiam** [comment]
@zj19880617 估计是zuul的代码是根据EnvironmentChangeEvent做操作的吧。。普通的bean应该只要加上了@RefreshScope就可以刷新了~

**Comment by zj19880617** [comment]
@nobodyiam 估计是的。太感谢你了，问题我关闭啦。
