### ISSUE TITLE
客户端使用springboot启动不起来是怎么回事？

### ISSUE THREAD

**Issue by zjm3007210057** [ctripcorp/apollo#646]
你好，我根据文档在本地起Apollo应用(本地应该配的都已经配置好)，然后使用JAVA客户端去连。当我使用Apollo的API去访问时可以获取配置的值：
`Connected to the target VM, address: '127.0.0.1:60152', transport: 'socket'
> hello
your input key is :hello, your get the value is :hao are you
> undefined
your input key is :undefined, your get the value is :how-are-you `
`

但是当我使用springboot方式的时候却发现应用都起不起来：
 :: Spring Boot ::        (v1.4.3.RELEASE)
[2017-06-20 17:06:13.015] - 15241 INFO [main] --- com.apollo.Application: Starting Application on MacBook-Pro.local with PID 15241 (/Users/***/javawork/demoapollo/target/classes started by ** in /Users/***/javawork/demoapollo)
[2017-06-20 17:06:13.036] - 15241 INFO [main] --- com.apollo.Application: No active profile set, falling back to default profiles: default
[2017-06-20 17:06:13.091] - 15241 INFO [main] --- org.springframework.context.annotation.AnnotationConfigApplicationContext: Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@30c15d8b: startup date [Tue Jun 20 17:06:13 CST 2017]; root of context hierarchy
[2017-06-20 17:06:13.646] - 15241 INFO [main] --- org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor: JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
[2017-06-20 17:06:36.356] - 15241 INFO [main] --- org.springframework.jmx.export.annotation.AnnotationMBeanExporter: Registering beans for JMX exposure on startup
[2017-06-20 17:06:36.368] - 15241 INFO [main] --- com.apollo.Application: Started Application in 23.692 seconds (JVM running for 24.049)
Disconnected from the target VM, address: '127.0.0.1:60337', transport: 'socket'

Process finished with exit code 0`

于是我又尝试起动你们github代码里面给的demo，发现：SimpleApolloConfigDemo.java可以运行并获取到配置的值：

`
[apollo-demo][Apollo-RemoteConfigLongPollService-1]2017-06-20 17:10:57,987 WARN  [com.ctrip.framework.apollo.internals.RemoteConfigLongPollService] Long polling failed, will retry in 120 seconds. appId: 100004456, cluster: dev, namespaces: application, reason: Get config services failed from ${dev_meta}/services/config?appId=100004456&ip=10.61.32.247 [Cause: Could not complete get operation [Cause: no protocol: ${dev_meta}/services/config?appId=100004456&ip=10.61.32.247]]
**_timeout（输入的key）_**
> [apollo-demo][main]2017-06-20 17:12:27,827 INFO  [com.ctrip.framework.apollo.demo.api.SimpleApolloConfigDemo] Loading key : timeout with value: 100
`

但是SpringBootSampleApplication.java却启动不了：

`[apollo-demo][main]2017-06-20 17:15:34,347 WARN  [com.ctrip.framework.apollo.internals.LocalFileConfigRepository] Sync config from upstream repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository failed, reason: Get config services failed from ${dev_meta}/services/config?appId=100004456&ip=10.61.32.247 [Cause: Could not complete get operation [Cause: no protocol: ${dev_meta}/services/config?appId=100004456&ip=10.61.32.247]]
[apollo-demo][main]2017-06-20 17:15:34,348 WARN  [com.ctrip.framework.apollo.internals.DefaultConfig] Init Apollo Local Config failed - namespace: FX.apollo, reason: Load config from local config failed! [Cause: Cannot read from local cache file /opt/data/100004456/config-cache/100004456+dev+FX.apollo.properties].
[apollo-demo][main]2017-06-20 17:15:34,355 INFO  [org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor] JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
[apollo-demo][main]2017-06-20 17:15:34,404 WARN  [com.ctrip.framework.apollo.internals.DefaultConfig] Could not load config for namespace FX.apollo from Apollo, please check whether the configs are released in Apollo! Return default value now!
[apollo-demo][main]2017-06-20 17:15:34,411 WARN  [com.ctrip.framework.apollo.internals.DefaultConfig] Could not load config for namespace FX.apollo from Apollo, please check whether the configs are released in Apollo! Return default value now!
[apollo-demo][main]2017-06-20 17:15:34,412 WARN  [com.ctrip.framework.apollo.internals.DefaultConfig] Could not load config for namespace FX.apollo from Apollo, please check whether the configs are released in Apollo! Return default value now!
[apollo-demo][main]2017-06-20 17:15:34,413 INFO  [com.ctrip.framework.apollo.demo.spring.bean.AnnotatedBean] timeout is 100
[apollo-demo][main]2017-06-20 17:15:34,413 INFO  [com.ctrip.framework.apollo.demo.spring.bean.AnnotatedBean] batch is 100
[apollo-demo][main]2017-06-20 17:15:34,413 INFO  [com.ctrip.framework.apollo.demo.spring.bean.AnnotatedBean] Keys for config: [demo, timeout]
[apollo-demo][main]2017-06-20 17:15:34,413 INFO  [com.ctrip.framework.apollo.demo.spring.bean.AnnotatedBean] Keys for anotherConfig: []
[apollo-demo][main]2017-06-20 17:15:34,420 WARN  [com.ctrip.framework.apollo.internals.DefaultConfig] Could not load config for namespace FX.apollo from Apollo, please check whether the configs are released in Apollo! Return default value now!
[apollo-demo][main]2017-06-20 17:15:34,420 WARN  [com.ctrip.framework.apollo.internals.DefaultConfig] Could not load config for namespace FX.apollo from Apollo, please check whether the configs are released in Apollo! Return default value now!
[apollo-demo][main]2017-06-20 17:15:34,432 WARN  [com.ctrip.framework.apollo.internals.DefaultConfig] Could not load config for namespace FX.apollo from Apollo, please check whether the configs are released in Apollo! Return default value now!
[apollo-demo][main]2017-06-20 17:15:34,432 INFO  [com.ctrip.framework.apollo.demo.spring.bean.NormalBean] timeout is 100
[apollo-demo][main]2017-06-20 17:15:34,432 INFO  [com.ctrip.framework.apollo.demo.spring.bean.NormalBean] batch is 100
[apollo-demo][main]2017-06-20 17:15:34,527 INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] Registering beans for JMX exposure on startup
[apollo-demo][main]2017-06-20 17:15:34,534 WARN  [com.ctrip.framework.apollo.internals.DefaultConfig] Could not load config for namespace FX.apollo from Apollo, please check whether the configs are released in Apollo! Return default value now!
[apollo-demo][main]2017-06-20 17:15:34,537 INFO  [com.ctrip.framework.apollo.demo.spring.SpringBootSampleApplication] Started SpringBootSampleApplication in 25.551 seconds (JVM running for 26.344)
[apollo-demo][Thread-3]2017-06-20 17:15:34,539 INFO  [org.springframework.context.annotation.AnnotationConfigApplicationContext] Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@77825085: startup date [Tue Jun 20 17:15:09 CST 2017]; root of context hierarchy
[apollo-demo][Thread-3]2017-06-20 17:15:34,539 INFO  [org.springframework.jmx.export.annotation.AnnotationMBeanExporter] Unregistering JMX-exposed beans on shutdown
Disconnected from the target VM, address: '127.0.0.1:61001', transport: 'socket'

Process finished with exit code 0`
于是百度Unregistering JMX-exposed beans on shutdown
得到在pom.xml里面加上Tomcat依赖[http://www.cnblogs.com/QQ931697811/p/6707740.html](url)
发现仍然启动不了，于是将依赖中的<scope>provided</scope>一行删掉[https://stackoverflow.com/questions/22380119/why-my-spring-boot-app-always-shutdown](url)，却还是不行。

想问一下springboot能否集成Apollo？是否可以更新一下文档，给出比较详细的示例，谢谢！

**Comment by nobodyiam** [comment]
spring boot的集成方式和spring是一样的，[文档](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#3212-%E5%9F%BA%E4%BA%8Ejava%E7%9A%84%E9%85%8D%E7%BD%AE%E6%8E%A8%E8%8D%90)和[demo](https://github.com/ctripcorp/apollo/blob/master/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/spring/SpringBootSampleApplication.java)都有。

你的例子里面取不到配置的原因已经提示的很明显了嘛，打包的时候没有传入dev_meta的信息。

建议仔细阅读一下[Apollo开发指南](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97)和[分布式部署指南](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97)，照着里面做就没问题了。

`[apollo-demo][main]2017-06-20 17:15:34,347 WARN [com.ctrip.framework.apollo.internals.LocalFileConfigRepository] Sync config from upstream repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository failed, reason: Get config services failed from ${dev_meta}/services/config?appId=100004456&ip=10.61.32.247 [Cause: Could not complete get operation [Cause: no protocol: ${dev_meta}/services/config?appId=100004456&ip=10.61.32.247]]`

**Comment by zjm3007210057** [comment]
文档和demo我已经反复看了N遍，现在不是取不到配置的问题，而是使用SpringBoot根本跑不起来呀，但不用SpringBoot却是可以跑的，这个是怎么回事呢？

**Comment by nobodyiam** [comment]
进群讨论吧，估计是你对spring boot不太了解吧。

![qr](https://raw.githubusercontent.com/ctripcorp/apollo/master/doc/images/tech-support-qq.png)
