### ISSUE TITLE
可以支持继承,或者依赖另一个配置文件吗?

### ISSUE THREAD

**Issue by zxj19951029** [ctripcorp/apollo#647]
比如像一个数据库的配置,我可能在上百个项目中用到这个配置,而每个项目就会有不同的环境,就是几百份配置文件,我要依赖到这个数据库配置能做到吗?这也是spring cloud config的一个痛点.

**Comment by lepdou** [comment]
可以继承和覆盖配置文件。详细介绍请看这篇文档：https://github.com/ctripcorp/apollo/wiki/Apollo%E6%A0%B8%E5%BF%83%E6%A6%82%E5%BF%B5%E4%B9%8B%E2%80%9CNamespace%E2%80%9D
