### ISSUE TITLE
有什么办法可以在log4j.properties里使用apollo的配置吗？

### ISSUE THREAD

**Issue by lcy362** [ctripcorp/apollo#649]

**Comment by nobodyiam** [comment]
原生的log4j.properties估计比较困难，不过如果你是用的spring boot的话，或许对于logging.level和logging.file是可以的，因为它本质上是从property source中获取的，只要它获取日志配置不是在bootstrap阶段就可以通过apollo配置。

https://docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html

**Comment by gihubcloner** [comment]
遇到类似的问题。一个spring项目中使用logback，logback-spring.xml需要环境变量提供一个profile的参数。但logback初始化早于Apollo获取配置，无法正常获取peofile参数，导致logback无法正常配置。

**Comment by nobodyiam** [comment]
log4j2支持运行时动态调整配置信息的，具体可以参考 #816

**Comment by nobodyiam** [comment]
我在[apollo-use-cases](https://github.com/ctripcorp/apollo-use-cases)项目中增加了动态刷新日志级别的demo：https://github.com/ctripcorp/apollo-use-cases/tree/master/spring-cloud-logger，可以参考一下。

**Comment by nobodyiam** [comment]
[1.2.0](https://github.com/ctripcorp/apollo/releases/tag/v1.2.0)版本已经支持Spring Boot中Apollo的加载顺序放到日志系统加载之前，从而可以支持日志配置放在Apollo管理（如logging.level.root=info或logback-spring.xml中的参数），可以尝试一下。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
