### ISSUE TITLE
使用Quite start部署的，请问连接数据库库的配置文件在哪儿修改？

### ISSUE THREAD

**Issue by bluexzh** [ctripcorp/apollo#651]
刚使用这个开源项目，下载测试下。很不错开源项目
1.请问使用Quite start部署的，请问连接数据库库的配置文件在哪儿修改？
2.如果想限制公网IP可以访问服务，必须要服务器设置防火墙吗？

**Comment by nobodyiam** [comment]
1. Quick Start有个demo.sh，具体可以参考文档[2.2 配置数据库连接信息](https://github.com/ctripcorp/apollo/wiki/Quick-Start#22-%E9%85%8D%E7%BD%AE%E6%95%B0%E6%8D%AE%E5%BA%93%E8%BF%9E%E6%8E%A5%E4%BF%A1%E6%81%AF)

2. 这个只能在网络层解决了

**Comment by bluexzh** [comment]
嗯。好的。多谢，虽然我没找到demo.sh这个文件

**Comment by nobodyiam** [comment]
demo.sh就在quick start包里面啊，https://github.com/nobodyiam/apollo-build-scripts/blob/master/demo.sh

如果是你很老的quick start的话，名字叫build.sh

**Comment by bluexzh** [comment]
这个测试环境 是以前他们部署的。我在看貌似不是quick start安装，开始看错了。应该是自己编译打包的。现在想找下配置数据库的文件。一直没找到

**Comment by nobodyiam** [comment]
这个是打包的时候打进去的，具体可以看下[2.2 配置数据库连接信息](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#22-%E9%85%8D%E7%BD%AE%E6%95%B0%E6%8D%AE%E5%BA%93%E8%BF%9E%E6%8E%A5%E4%BF%A1%E6%81%AF)。

简单来说，就是打包的时候在[build.sh](https://github.com/ctripcorp/apollo/blob/master/scripts/build.sh)中填入数据库链接，最终会打到apollo-common.jar中的[application-github.properties](https://github.com/ctripcorp/apollo/blob/master/apollo-common/src/main/resources/application-github.properties)，老版本的话，是叫application-dev.properties

**Comment by bluexzh** [comment]
多谢。我还这些包里面一个一个找。还真在这里。谢谢啊。非常感谢
