### ISSUE TITLE
有支持yaml的打算吗？

### ISSUE THREAD

**Issue by baimoer** [ctripcorp/apollo#653]
用习惯了yaml,当配置一些集合，数组的时候，感觉比properties好用多了

**Comment by nobodyiam** [comment]
yaml确实不错，后面我们看一下，也欢迎大家可以贡献相关feature

**Comment by yiming187** [comment]
+1 这个很适合社区贡献，对于使用YAML的公司可以动手做起来。

**Comment by ylpu** [comment]
@nobodyiam ，今天开发了支持yml的功能，目前一切正常，不过还要深入测试一下

**Comment by nobodyiam** [comment]
@ylpu 

不知支持yml的功能后续如何？是否有可能贡献出来？

**Comment by limitAp** [comment]
我们也做了下支持yml格式功能。不过是没有改源码。直接在apollo-client上做了一层封装 利用提供的spi接口改的。重写了RemoteConfigRepository 里面的getConfig。

**Comment by nobodyiam** [comment]
@limitAp 

在getConfig方法里面把yml转换成properties？

**Comment by neatlife** [comment]
@limitAp 兄弟，代码可否分享下👀

**Comment by limitAp** [comment]
@neatlife 我把核心转换代码给你参考下吧。
![image](https://user-images.githubusercontent.com/18351359/47057948-7ed6d000-d1f5-11e8-86e6-7e6ddc39c22a.png)

**Comment by neatlife** [comment]
@limitAp 好的，谢谢 😊

**Comment by anjia0532** [comment]
@nobodyiam 能官方支持么？

**Comment by nobodyiam** [comment]
@anjia0532 后续会考虑支持

**Comment by anjia0532** [comment]
@nobodyiam 好的谢谢

**Comment by yaohuacheng** [comment]
持续关注这个话题。
yaml作为配置文件真的很方便

**Comment by litttlefisher** [comment]
+1

**Comment by limitAp** [comment]
@litttlefisher  能

**Comment by litttlefisher** [comment]
@limitAp 哥，你@错了

**Comment by kezhenxu94** [comment]
@94192448 有没有配置数组之类比较复杂的情况? 像
```yml
array:
  - element0
  - element1
```
转成properties后在客户端读取还能够通过 `com.ctrip.framework.apollo.Config#getArrayProperty` 获取出来吗?

**Comment by nobodyiam** [comment]
我新开了一个PR #1944，支持yml类型的namespace注入到Spring中去，大家可以看一下~
