### ISSUE TITLE
发布后回滚后状态不一致

### ISSUE THREAD

**Issue by zzx0421** [ctripcorp/apollo#654]
发布后的配置项，回滚后状态为未发布，但是取值已经是回滚后的值

**Comment by nobodyiam** [comment]
设计即是如此。

打个比方，编辑状态的配置就是git仓库里面的代码，发布出去的是你的代码包，比如war包。

部署到机器上的是war包，回滚的也是war包。

但是你git仓库里面的代码我们是不会回滚的，稍作修改后可以重新发布。

**Comment by zzx0421** [comment]
那未发布状态的配置项加上一个当前已生效值的列显示是否会更让人清晰明白

**Comment by nobodyiam** [comment]
现在也有这个功能，只是比较隐晦。。点击未发布这个按钮就就能看到已发布的值。。。

![image](https://user-images.githubusercontent.com/837658/28049583-eae2be90-662a-11e7-91b9-bd084ae8a821.png)

**Comment by zzx0421** [comment]
OK

**Comment by zzx0421** [comment]
那如果未发布，但是反悔了，如何快速还原已发布值呢？这里如何交互操作？

**Comment by nobodyiam** [comment]
这个目前还没有快速还原的操作，只能用户自己根据更改历史/发布历史，手动还原

**Comment by zzx0421** [comment]
好，明白
