### ISSUE TITLE
apollo-configservice需要修改这个的端口，需要修改哪些地方？

### ISSUE THREAD

**Issue by llxiao** [ctripcorp/apollo#655]
如题。望解答

**Comment by nobodyiam** [comment]
https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#25-%E9%83%A8%E7%BD%B2apollo-configservice

 注3：如要调整服务的监听端口，可以修改startup.sh中的SERVER_PORT。另外apollo-configservice同时承担meta server职责，如果要修改端口，注意要同时修改scripts/build.sh中的meta server url信息以及ApolloConfigDB.ServerConfig表中的eureka.service.url配置项。

**Comment by llxiao** [comment]
多谢解答。
