### ISSUE TITLE
portal及client的meta_server url是否支持多个？

### ISSUE THREAD

**Issue by anycrane** [ctripcorp/apollo#660]
各位大神，我想问一下
dev_meta,fat_meta等配置meta_server的值能否支持多个？
如配置dev_meta=http://127.0.0.1:8080,http://127.0.0.1:8081

eureka.service.url是支持http://1.1.1.1:8080/eureka/,http://2.2.2.2:8080/eureka/这种配置的。

不然在这一块的高可用是有什么方案吗？
我看部署指南中提到

> 推荐通过SLB（Software Load Balancer）做动态负载均衡。

意思是需要再开发吗？

还望支持一下。谢谢。

**Comment by nobodyiam** [comment]
目前还不支持多个，slb是指类似nginx之类的，做反向代理+健康检查

**Comment by anycrane** [comment]
好的~谢谢。

**Comment by rrfeng** [comment]
同想问这个问题：meta service 是不是就是一个 eureka 服务？还是说还有别的功能？
eureka 的话本身是支持多个的呀，这里为什么不可以呢？

**Comment by rrfeng** [comment]
fat_meta=...
是 client 的配置，也就是 client 去哪里的 eureka 寻找 configservice 的实例。
client 不是一个普通的 eureka client 吗？这里应该相当于 eureka.client.serviceUrl.defaultZone ？

**Comment by nobodyiam** [comment]
meta server是我们封装的接口，目的是不想把eureka暴露给我们的客户端，因为我们有各种语言的客户端，如Java, .Net, Go, Python等等。

**Comment by rrfeng** [comment]
> meta server是我们封装的接口，目的是不想把eureka暴露给我们的客户端，因为我们有各种语言的客户端，如Java, .Net, Go, Python等等。

这么说来如果架构中使用外部的 eureka 的话，meta service 还是存在的？这样 client 应该如何配置呢？有点迷惑了

**Comment by nobodyiam** [comment]
client始终连向meta server，meta server会和eureka通信，可以看一下[架构模块](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1#12-%E6%9E%B6%E6%9E%84%E6%A8%A1%E5%9D%97)

**Comment by eastfisher** [comment]
使用Nginx对metaserver做负载均衡时，是配置configservice的地址（比如10.181.3.211:8080,10.181.3.212:8080），同时修改eureka.service.url（对应的http://10.181.3.211:8080/eureka/,http://10.181.3.212:8080/eureka/）？这样配置之后启动configservice发现10.181.3.211显示10.181.3.212为available-replicas，而10.181.3.212则显示10.181.3.211为unavailable-replicas。不知是哪里配置的问题吗？

**Comment by nobodyiam** [comment]
看看过了一会儿是否显示正常？eureka的状态同步比较慢

**Comment by eastfisher** [comment]
一直有问题的

**Comment by nobodyiam** [comment]
看看日志吧，看看是不是有replication之类的异常

**Comment by nobodyiam** [comment]
PR #1214 支持meta server配置多个ip地址了，不过生产环境还是建议使用域名（走slb）。
