### ISSUE TITLE
springSecurity简单实现登陆的分支有bug啊

### ISSUE THREAD

**Issue by yizhixiaotaozi** [ctripcorp/apollo#661]
关闭mysql大小写区分，告诉我说没有users表，添加不了用户。
不区分大小写，又说apolloconfigdb不存在。
需要修改一下代码里的sql把小写的users改成Users

**Comment by lepdou** [comment]
@yizhixiaotaozi 
已修复，多谢~
https://github.com/ctripcorp/apollo/commit/dad96968094af1831066b5e140660f7295298472
