### ISSUE TITLE
编译报错，编译成功的包启动后也没生成日志？

### ISSUE THREAD

**Issue by lovetonight** [ctripcorp/apollo#662]
git bash执行.\build.sh 编译报错(但是最终的结果显示configService编译成功，adminService及portal编译失败，configService部署后启动超时，且在指定log目录下没有相关日志输出)，好像是window分隔符和linux不一致造成编译报错的，我看了apollo的说明，是可以在win上编译打包的，不知道各位大神是如何操作的，以下是编译：
[ERROR] OS=Windows and the assembly descriptor contains a *nix-specific root-relative-reference (starting with slash) /
----------------------------------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.5:clean (default-clean) on project apollo-adminservice: Failed to clean project: Failed to delete D:\pzzx\apollo-master\apollo-adminservice\target -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :apollo-adminservice
-----------------------------------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.5:clean (default-clean) on project apollo-portal: Failed to clean project: Failed to delete D:\pzzx\apollo-master\apollo-portal\target -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :apollo-portal

**Comment by nobodyiam** [comment]
这个错误和操作系统没关系，应该是你在别的地方打开了这个文件夹，导致没法删除

Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.5:clean (default-clean) on project apollo-adminservice: Failed to clean project: Failed to delete D:\pzzx\apollo-master\apollo-adminservice\target

**Comment by lovetonight** [comment]
谢谢回复，仔细检查了一下，确实是打开了文件夹导致不能正常删除，重新执行后，还是会报：
[ERROR] OS=Windows and the assembly descriptor contains a *nix-specific root-relative-reference (starting with slash) /
但最终结果是各个工程均编译成功，这个是否有问题。
还有我部署了configService和AdminService启动超时且没有日志，有可能是什么原因？

**Comment by lovetonight** [comment]
端口没被占用，目录权限都是最大的777，不知道怎么回事

**Comment by nobodyiam** [comment]
日志的目录是在startup.sh里面设置的，你检查下LOG_DIR的配置是否正确。

执行startup.sh后，可以ps aux | grep java看下进程的状态

**Comment by lovetonight** [comment]
还是没日志，startup.sh后，没看到java进程，手动执行后，如下所示：
[root@localhost apollo-configservice-0.8.0-github]# ./apollo-configservice.jar start
Started [5700]
没有日志信息，只有一个heap_trace.txt
Java HotSpot(TM) 64-Bit Server VM (25.131-b11) for linux-amd64 JRE (1.8.0_131-b11), built on Mar 15 2017 01:23:40 by "java_re" with gcc 4.3.0 20080428 (Red Hat 4.3.0-8)
Memory: 4k page, physical 1870488k(819852k free), swap 1048572k(1048572k free)
CommandLine flags: -XX:+CMSClassUnloadingEnabled -XX:CMSFullGCsBeforeCompaction=9 -XX:CMSInitiatingOccupancyFraction=60 -XX:+CMSParallelRemarkEnabled -XX:+DisableExplicitGC -XX:+ExplicitGCInvokesConcurrent -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/apollo/apollo-configservice-0.8.0-github/HeapDumpOnOutOfMemoryError/ -XX:InitialHeapSize=536870912 -XX:MaxHeapSize=536870912 -XX:MaxMetaspaceSize=268435456 -XX:MaxNewSize=536870912 -XX:MaxTenuringThreshold=9 -XX:MetaspaceSize=134217728 -XX:NewSize=536870912 -XX:OldPLABSize=16 -XX:-OmitStackTraceInFastThrow -XX:ParallelGCThreads=4 -XX:+PrintGC -XX:+PrintGCApplicationConcurrentTime -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintHeapAtGC -XX:+ScavengeBeforeFullGC -XX:SoftRefLRUPolicyMSPerMB=0 -XX:SurvivorRatio=8 -XX:ThreadStackSize=256 -XX:+UseCMSCompactAtFullCollection -XX:+UseCMSInitiatingOccupancyOnly -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseConcMarkSweepGC -XX:+UseParNewGC 
2017-07-17T20:02:08.906-0700: 0.740: Application time: 0.6812687 seconds
2017-07-17T20:02:09.249-0700: 1.082: Application time: 0.3428268 seconds
2017-07-17T20:02:10.250-0700: 2.083: Application time: 1.0007363 seconds
2017-07-17T20:02:11.213-0700: 3.047: Application time: 0.9633831 seconds
Heap
 par new generation   total 471808K, used 318748K [0x00000000e0000000, 0x00000000ffff0000, 0x00000000ffff0000)
  eden space 419392K,  76% used [0x00000000e0000000, 0x00000000f37472b0, 0x00000000f9990000)
  from space 52416K,   0% used [0x00000000f9990000, 0x00000000f9990000, 0x00000000fccc0000)
  to   space 52416K,   0% used [0x00000000fccc0000, 0x00000000fccc0000, 0x00000000ffff0000)
 concurrent mark-sweep generation total 64K, used 0K [0x00000000ffff0000, 0x0000000100000000, 0x0000000100000000)
 Metaspace       used 10324K, capacity 10528K, committed 10624K, reserved 1058816K
  class space    used 1305K, capacity 1372K, committed 1408K, reserved 1048576K
2017-07-17T20:02:11.427-0700: 3.261: Application time: 0.2137414 seconds

**Comment by lovetonight** [comment]
startup.sh后，查不到java进程，没有日志信息，只有一个heap_trace.txt文件：
Java HotSpot(TM) 64-Bit Server VM (25.131-b11) for linux-amd64 JRE (1.8.0_131-b11), built on Mar 15 2017 01:23:40 by "java_re" with gcc 4.3.0 20080428 (Red Hat 4.3.0-8)
Memory: 4k page, physical 1870488k(819852k free), swap 1048572k(1048572k free)
CommandLine flags: -XX:+CMSClassUnloadingEnabled -XX:CMSFullGCsBeforeCompaction=9 -XX:CMSInitiatingOccupancyFraction=60 -XX:+CMSParallelRemarkEnabled -XX:+DisableExplicitGC -XX:+ExplicitGCInvokesConcurrent -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/apollo/apollo-configservice-0.8.0-github/HeapDumpOnOutOfMemoryError/ -XX:InitialHeapSize=536870912 -XX:MaxHeapSize=536870912 -XX:MaxMetaspaceSize=268435456 -XX:MaxNewSize=536870912 -XX:MaxTenuringThreshold=9 -XX:MetaspaceSize=134217728 -XX:NewSize=536870912 -XX:OldPLABSize=16 -XX:-OmitStackTraceInFastThrow -XX:ParallelGCThreads=4 -XX:+PrintGC -XX:+PrintGCApplicationConcurrentTime -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintHeapAtGC -XX:+ScavengeBeforeFullGC -XX:SoftRefLRUPolicyMSPerMB=0 -XX:SurvivorRatio=8 -XX:ThreadStackSize=256 -XX:+UseCMSCompactAtFullCollection -XX:+UseCMSInitiatingOccupancyOnly -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseConcMarkSweepGC -XX:+UseParNewGC
2017-07-17T20:02:08.906-0700: 0.740: Application time: 0.6812687 seconds
2017-07-17T20:02:09.249-0700: 1.082: Application time: 0.3428268 seconds
2017-07-17T20:02:10.250-0700: 2.083: Application time: 1.0007363 seconds
2017-07-17T20:02:11.213-0700: 3.047: Application time: 0.9633831 seconds
Heap
par new generation total 471808K, used 318748K [0x00000000e0000000, 0x00000000ffff0000, 0x00000000ffff0000)
eden space 419392K, 76% used [0x00000000e0000000, 0x00000000f37472b0, 0x00000000f9990000)
from space 52416K, 0% used [0x00000000f9990000, 0x00000000f9990000, 0x00000000fccc0000)
to space 52416K, 0% used [0x00000000fccc0000, 0x00000000fccc0000, 0x00000000ffff0000)
concurrent mark-sweep generation total 64K, used 0K [0x00000000ffff0000, 0x0000000100000000, 0x0000000100000000)
Metaspace used 10324K, capacity 10528K, committed 10624K, reserved 1058816K
class space used 1305K, capacity 1372K, committed 1408K, reserved 1048576K
2017-07-17T20:02:11.427-0700: 3.261: Application time: 0.2137414 seconds

-------------------------------------------------------------------------------------------------
手动启动，如下所示，但查不到java进程
[root@localhost apollo-configservice-0.8.0-github]# ./apollo-configservice.jar start
Started [5700]

**Comment by nobodyiam** [comment]
内存设的不太对吧，先把startup.sh中heap的大小设置都去掉，再启动吧

**Comment by lovetonight** [comment]
非常感谢耐心的回答，重新手工执行了下jar包，从错误信息中发现是bootstrap.yml里配置错了，把文档里的eureka.instance.ip-address整个内容拷过来放到了最后，和bootstrap.yml原有的eureka.instance属性重复，从而导致执行失败，但是没有生成日志信息。

**Comment by lovetonight** [comment]
再请教一下，目前登录portal默认使用apollo，如果不实现单点登录的话，可以自己在页面配置用户或者直接在数据库里新增用户吗

**Comment by nobodyiam** [comment]
可以参考 https://github.com/ctripcorp/apollo/wiki/Portal-%E5%AE%9E%E7%8E%B0%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95%E5%8A%9F%E8%83%BD

实现方式二：使用Apollo提供的Spring Security简单认证

**Comment by lovetonight** [comment]
大神，实现方式二中的http://{portal地址}/user-manage.html 地址，好像不存在呀，请赐教

**Comment by nobodyiam** [comment]
在一个单独的[spring-security-auth分支](https://github.com/ctripcorp/apollo/blob/spring-security-auth/apollo-portal/src/main/resources/static/user-manage.html)上，不是master分支。

**Comment by nobodyiam** [comment]
这个分支很多用户都用过OK的，你加QQ群咨询吧

![qq](https://raw.githubusercontent.com/ctripcorp/apollo/master/doc/images/tech-support-qq.png)
