### ISSUE TITLE
请教下像数据库连接池这样使用长连接的，配置中心修改后客户端如何处理？

### ISSUE THREAD

**Issue by xtylxx** [ctripcorp/apollo#663]
如题

**Comment by nobodyiam** [comment]
大致的方案就是新开一个连接池，后续请求都走新连接池。

老的连接池等待连接都还回来后关闭即可（或者等待一定时间后强行关闭）。

可以参考[dianping/zebra](https://github.com/dianping/zebra/blob/master/zebra-api/src/main/java/com/dianping/zebra/group/jdbc/GroupDataSource.java#L503)的实现方式，@ainilife。

**Comment by nobodyiam** [comment]
我们增加了一个代码示例演示动态切换数据源，可以参考一下：https://github.com/ctripcorp/apollo-use-cases/tree/master/dynamic-datasource
