### ISSUE TITLE
如何创建非properties的namespace

### ISSUE THREAD

**Issue by xtylxx** [ctripcorp/apollo#664]
默认用户apollo不是超级管理员吗 如何创建非properties的namespace

**Comment by nobodyiam** [comment]
目前只有私有namespace可以是非properties的

![image](https://user-images.githubusercontent.com/837658/28352397-b0cb73fa-6c88-11e7-8e25-ce606bbdf0f9.png)

**Comment by xtylxx** [comment]
好的 多谢~
