### ISSUE TITLE
请教客户端集成问题

### ISSUE THREAD

**Issue by xtylxx** [ctripcorp/apollo#665]
按照文档将打好的客户端需要的client core buildtools传至了私服

客户端添加依赖 Install
<dependency>
			<groupId>com.ctrip.framework.apollo</groupId>
			<artifactId>apollo-client</artifactId>
			<version>0.8.0</version>
		</dependency>

无法下载core等jar包

手动添加完整依赖

<dependency>
			<groupId>com.ctrip.framework.apollo</groupId>
			<artifactId>apollo-client</artifactId>
			<version>0.8.0</version>
		</dependency>

		<dependency>
			<groupId>com.ctrip.framework.apollo</groupId>
			<artifactId>apollo-core</artifactId>
			<version>0.8.0</version>
		</dependency>

		<dependency>
			<groupId>com.ctrip.framework.apollo</groupId>
			<artifactId>apollo-buildtools</artifactId>
			<version>0.8.0</version>
		</dependency>

才可以下载下来， 是啥问题~ 求指教

**Comment by nobodyiam** [comment]
应该是pom没有上传吧，每个jar包的pom都要上传的，不然没法传递依赖的

**Comment by xtylxx** [comment]
那我这种用法可以吗？ 客户端 直接依赖3个包  client  core buildtools

**Comment by nobodyiam** [comment]
估计也不行，因为这3个包又有自己的传递依赖的，像guava什么的

**Comment by xtylxx** [comment]
是单独每个包都要上传pom 还是parent的pom就可以，我们用的nexus，
这里是选from pom吗，我刚才选的是 Parameters

<img width="892" alt="qq20170719-150856 2x" src="https://user-images.githubusercontent.com/29626733/28354909-46890e42-6c94-11e7-8146-07cf5cf36f03.png">

**Comment by xtylxx** [comment]
嗯 我重新上传了 现在可以了谢谢
