### ISSUE TITLE
xml namespace无法访问

### ISSUE THREAD

**Issue by xtylxx** [ctripcorp/apollo#666]
http://www.ctrip.com/schema/apollo.xsd 这个地址打不开

**Comment by nobodyiam** [comment]
这个是打不开的，程序中是看这个的，https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/resources/META-INF/spring.schemas

**Comment by xtylxx** [comment]
运行程序

org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 10 in XML document from class path resource [spring-cache.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 10; columnNumber: 18; 元素 "apollo:config" 的前缀 "apollo" 未绑定。

**Comment by nobodyiam** [comment]
使用的时候参考 https://github.com/ctripcorp/apollo/blob/master/apollo-demo/src/main/resources/spring.xml 的写法
