### ISSUE TITLE
客户端一直重启问题求解

### ISSUE THREAD

**Issue by xtylxx** [ctripcorp/apollo#667]
使用了druid，发布更新时 监听器里执行了关闭datasource 重新初始化操作，一直在重启 求解

`public class ComallDataSource extends DruidDataSource {

    private static final String CHANGE_URL= "mysql.jdbcurl";
    private static final String CHANGE_USERNAME = "mysql.username";
    private static final String CHANGE_PASSWORD = "mysql.password";
    /**
     * 监听mysql配置更新
     * @param changeEvent
     */
    @ApolloConfigChangeListener("mysql")
    private void someOnChange(ConfigChangeEvent changeEvent) {
        if(isChangeMysqlServer(changeEvent)) {
            changeMysqlServer(changeEvent);
        }

    }

    private void changeMysqlServer(ConfigChangeEvent changeEvent) {
        // 关闭数据源
        this.closeDataSource();

        String jdbcUrl =  changeEvent.isChanged(CHANGE_URL) ? getChangeValue(changeEvent,CHANGE_URL):null;
        String username = changeEvent.isChanged(CHANGE_USERNAME) ? getChangeValue(changeEvent,CHANGE_USERNAME):null;
        String password = changeEvent.isChanged(CHANGE_PASSWORD) ? getChangeValue(changeEvent,CHANGE_PASSWORD):null;
        if(StringUtils.isNotEmpty(jdbcUrl)) {
            this.setUrl(jdbcUrl);
        }
        if(StringUtils.isNotEmpty(username)) {
            this.setUsername(username);
        }
        if(StringUtils.isNotEmpty(password)) {
            this.setPassword(password);

        }

        try{
            // 重新初始化
            this.init();
        }catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void closeDataSource() {
        this.lock.lock();
        try {
            this.close();
            this.resetStat();
            this.inited = false;
            setUrl(null);
            setEnable(true);
        } finally {
            this.lock.unlock();
        }
    }

    
    private boolean isChangeMysqlServer(ConfigChangeEvent changeEvent) {
        return changeEvent.isChanged(CHANGE_URL) || changeEvent.isChanged(CHANGE_USERNAME) || changeEvent.isChanged(CHANGE_PASSWORD);
    }

    private String getChangeValue(ConfigChangeEvent changeEvent,String key) {
        return changeEvent.getChange(key).getNewValue();
    }
}`

**Comment by nobodyiam** [comment]
一般都是要自己写个datasource，然后composite一个真正的datasource。在配置变化的时候，先把新连接建好，再做一个swap，最后再把老的datasource慢慢关掉，具体你参考下上次给你回复的 #663

**Comment by xtylxx** [comment]
嗯 这个就是简单写一个测试用的代码。 问题解决了是因为 jetty启动项目设置了大于0，会定期检测项目变化自动热部署，   在classes目录下 生成了 config-cache 导致重启

**Comment by nobodyiam** [comment]
ok，apollo默认会往c:/opt/data/或/opt/data/写配置的缓存，如果这两个路径不可写的话，就会写到classes下面。
