### ISSUE TITLE
maven pom 文件报错 无法编译

### ISSUE THREAD

**Issue by gavinage** [ctripcorp/apollo#671]
For artifact {org.springframework:spring-core:null:jar}: The version cannot be empty.

很多项目的pom文件包这个错误，无法启动 但是根下 install 是可以

现在idea15 中起不来 ， 不知道还应该改哪里？
demo里是2016的idea 会是版本的原因？

**Comment by gavinage** [comment]
![image](https://user-images.githubusercontent.com/5218047/28567264-54bfbacc-7164-11e7-9c38-53d6b5d53fc0.png)

**Comment by lepdou** [comment]
mvn compile能编译通过吗？如果编译success的话，就没关系的，估计是idea的问题。
如果编译失败，把编译的日志打一下

**Comment by nobodyiam** [comment]
长时间没有回复，先关闭了。
