### ISSUE TITLE
有办法在spring配置文件中使用 配置中心配置的参数吗？

### ISSUE THREAD

**Issue by llxiao** [ctripcorp/apollo#675]
<mongo:mongo-client host="192.168.0.201" port="27017" credentials="tuzongxun:123456@mongoTest" id="mongo">    
      <mongo:client-options write-concern="SAFE"/>    
  </mongo:mongo-client>   

如题，望解答。

**Comment by nobodyiam** [comment]
apollo是支持和spring集成的，具体可以参考[3.2 Spring整合方式](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#32-spring%E6%95%B4%E5%90%88%E6%96%B9%E5%BC%8F)

不过你贴的这个应该是mongo的配置，不确定它是不是会从spring替换placeholder的值，这个你得自己试一下。

**Comment by nobodyiam** [comment]
这个Issue先关闭了，如果有后续问题，可以提供更多信息~
