### ISSUE TITLE
怎么分配自定义用户的权限

### ISSUE THREAD

**Issue by tlzjff** [ctripcorp/apollo#679]
现在在调研apollo的一些功能，主要的配置功能看起来都很舒服，唯独权限这块，弄起来有点麻烦，有没有什么快速的方式，可以自定义用户权限去控制相关的功能，及登录退出？有没有什么sample？ 后续会更新这块内容吗？
我按照https://github.com/ctripcorp/apollo/wiki/Portal-%E5%AE%9E%E7%8E%B0%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95%E5%8A%9F%E8%83%BD
这个连接去做，但是在第6步的时候卡住了，我没有地方输入原始账号密码登录系统？？？ 按退出也没用？

**Comment by lepdou** [comment]
如果你按照文档部署成功了，重新打开portal，应该就会弹出登陆框的。
basic认证没有退出功能，重新打开浏览器就需要重新登录了。

**Comment by sjw2003go** [comment]
是的，第六步我全局搜索了下，没有这个文件。

**Comment by lepdou** [comment]
如果是spring-security-auth分支，肯定是有这个文件的。你检查一下你的分支

**Comment by nobodyiam** [comment]
暂时先关闭了，如有问题，可以提供更多信息，谢谢~
