### ISSUE TITLE
数据库或者redis等的配置是否放在apollo管理，可以分享下数据库配置更新后如何处理的吗？

### ISSUE THREAD

**Issue by lovezy** [ctripcorp/apollo#680]
携程托管于apollo的配置都有哪些种类，最近公司也在考虑用分布式配置中心，但是对于托管的配置的种类有些分歧，希望可以分享下携程的使用经验，比如数据库或者redis等的配置是否放在apollo管理，数据库配置更新后如何处理的，谢谢

**Comment by lepdou** [comment]
托管在apollo的配置只要是以下几类：
1. 业务项目的业务配置，可能会动态变更的配置、不同环境不同值的配置，比如开关、服务地址等
2. 框架中间件客户端的一些配置。比如dal一些默认ds的配置、（使用公共Namespace）
3. 数据库、redis的配置也可以放在apollo。如果公司没有专门的服务管理这两个配置的系统

动态数据源大致实现原理：
在客户端监听数据库连接配置变更事件，如果配置变更，重新创建一个线程池。新的请求都走新的线程池，等到老的线程池不再使用的时候，销毁掉就可以了。

**Comment by lovezy** [comment]
多谢分享

**Comment by nobodyiam** [comment]
我们增加了一个代码示例演示动态切换数据源，可以参考一下：https://github.com/ctripcorp/apollo-use-cases/tree/master/dynamic-datasource
