### ISSUE TITLE
配置是否打算支持模板等

### ISSUE THREAD

**Issue by qiankunli** [ctripcorp/apollo#682]
据初步观察，我发现你们的配置只支持简单的key value格式，是否有计划支持复杂的配置模板？

比如，有一个jdbc配置的模板，用户使用时，克隆一下，修正部分配置值（比如username、password）等，即可直接使用。

我目前在配置中心的使用过程中，对配置中心和业务系统的边界通常很纠结。比如，leader想将abtest数据直接存在配置中心中，但将abest数据用key value形式组织起来非常复杂，用户（比如产品经理）基本无法直接使用，需要为其提供一个abtest 前端界面，然后将数据按约定格式key value存入配置中心。但如此一来，abtest前端何不如直接将abtest数据存为json，反正abtest用户也不会接触配置中心。

您在处理类似问题时，主要基于什么理念呢？

**Comment by nobodyiam** [comment]
针对第一个问题，目前确实没有模板的功能，只能存储简单的key value格式。

针对第二个问题，目前我们很多使用方就是他们自己有一个系统，会提供相关的界面，供其他用户如运营、产品经理等使用，然后会通过apollo的open api把数据以json格式存储到apollo，从而下发到客户端。

**Comment by lepdou** [comment]
第一个问题：配置模板

你举的jdbc的例子，抽象一下就是一份配置文件，大部分配置都是一样的，但是某几个配置项根据项目自定义的的情况（如果我没理解错的话）。
这种情况，可以使用公共配置文件的方式解决。公共部门提供一份default配置文件，然后各个项目去继承这个文件，然后可以选择覆盖某几个配置项。详细可以参考：https://github.com/ctripcorp/apollo/wiki/Apollo%E6%A0%B8%E5%BF%83%E6%A6%82%E5%BF%B5%E4%B9%8B%E2%80%9CNamespace%E2%80%9D

第二个问题：配置中心和业务系统配置界限

首先，大部分的配置中心，因为是最底层的一个组件，为了通用性，配置中心一般是不会涉及具体业务的配置，也不会去理解配置的含义。对于配置中心来说，它管理的对象就是配置，要么是properties格式、要么是json的。
业务系统的配置，从某种意义上相比于配置中心的配置，多了一层业务含义，本质上也是配置。

你举得ABTest的例子，在我们这边是这样实践的：

ABTest系统有一个后台，这个后台提供定制化的界面给产品经理使用。后台实现是调用配置中心Open API，把生成配置存到配置中心。然后有配置中心把最新的配置推送给客户端。这么做核心是使用了配置中心具有实时推送配置的能力。
关于”abtest前端何不如直接将abtest数据存为json“？
这个问题，其实跟配置的格式没关系的，不管是json还是properties的kv。配置中心比如Apollo也是支持json的。
Apollo Open API文档：https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0

**Comment by qiankunli** [comment]
非常感谢您如此详尽的答复，是否介意说下，你们abtest数据是存储为json的么？

**Comment by lepdou** [comment]
这个还真不清楚。
估计不是properties，properties的kv表现力肯定没有json的强。
你的例子是可以存储为json的。
