### ISSUE TITLE
建议添加Cat的说明wiki

### ISSUE THREAD

**Issue by powerYao** [ctripcorp/apollo#684]
在apollo core中存在判断，如果存在Cat类，则用com.dian.ping.Cat来进行打点。因为client和server都依赖core。Cat作为日志监控，并没有在wiki上说明，建议说明。

**Comment by nobodyiam** [comment]
已经增加 - [监控相关](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1#%E4%BA%94%E7%9B%91%E6%8E%A7%E7%9B%B8%E5%85%B3)

**Comment by powerYao** [comment]
谢谢
