### ISSUE TITLE
客户端提示连接超时

### ISSUE THREAD

**Issue by zustyejunjie** [ctripcorp/apollo#690]
您好。
 Sync config from upstream repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository failed, reason: Load Apollo Config failed - appId: xxx, cluster: default, namespace: application [Cause: Could not complete get operation [Cause: connect timed out]]
配置界面可以正常使用，说明apollo后台服务应该是ok的，请教下还有可能是什么原因。
有没有什么方法可以查看configService是否可用。

**Comment by nobodyiam** [comment]
客户端把debug打开DEBUG日志级别吧，能看到具体的信息。

估计是meta server配置不对之类的。

**Comment by zustyejunjie** [comment]
谢谢，用debug找到原因了。
找到原因了，是因为client端打包进入的是外网地址，然后调用的时候，在HttpUtil类的方法doGetWithSerializeFunction里面把homePageUrl解析成内网地址了。刚好云服务器上的内网地址访问不了，导致连接超时。
解决方法在apollo的官方文档上有写，当时没有仔细看这块。
