### ISSUE TITLE
.net core 2.0支持

### ISSUE THREAD

**Issue by brotherhorse** [ctripcorp/apollo#692]
.net core 2.0已经发布,编译apollo .net 客服端设置为netcore2.0后,有些错误编译不过,摘录几个:
不支持 System.Runtime.Remoting.Messaging
HttpContext需要改为使用system.net.http
不支持 SynchronizedCollection
望能尽快支持

**Comment by nobodyiam** [comment]
请把issue提到[apollo.net](https://github.com/ctripcorp/apollo.net/issues)项目中吧。

另外，我们对.net并不是特别熟悉，可能需要花些时间研究才能支持，如果你有余力的话，也欢迎发起pull request。
