### ISSUE TITLE
需要.net core 2.0支持

### ISSUE THREAD

**Issue by brotherhorse** [ctripcorp/apollo#693]
.net core 2.0正式版本已经发布,apollo客户端需要将csproj文件格式切换为.net core格式(兼容net frame)
但目前编译出现错误,望尽快能提供.net core 版本

csproj文件中更改框架:
<TargetFramework>netcoreapp2.0</TargetFramework>

编译错误:
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS0246	未能找到类型或命名空间名“SynchronizedCollection<>”(是否缺少 using 指令或程序集引用?)	Apollo	D:\MyDownloads\Download\apollo.net-master\Apollo\Internals\AbstractConfigRepository.cs	13	活动的
错误	CS0234	命名空间“System.Runtime”中不存在类型或命名空间名“Remoting”(是否缺少程序集引用?)	Apollo	D:\MyDownloads\Download\apollo.net-master\Apollo\SmartThreadPool\CallerThreadContext.cs	9	活动的
错误	CS0246	未能找到类型或命名空间名“HttpContext”(是否缺少 using 指令或程序集引用?)	Apollo	D:\MyDownloads\Download\apollo.net-master\Apollo\SmartThreadPool\CallerThreadContext.cs	49	活动的
错误	CS0246	未能找到类型或命名空间名“LogicalCallContext”(是否缺少 using 指令或程序集引用?)	Apollo	D:\MyDownloads\Download\apollo.net-master\Apollo\SmartThreadPool\CallerThreadContext.cs	50	活动的
错误	CS0234	命名空间“System.Runtime”中不存在类型或命名空间名“Remoting”(是否缺少程序集引用?)	Apollo	D:\MyDownloads\Download\apollo.net-master\Apollo\SmartThreadPool\CallerThreadContext.cs	9	活动的
错误	CS0246	未能找到类型或命名空间名“HttpContext”(是否缺少 using 指令或程序集引用?)	Apollo	D:\MyDownloads\Download\apollo.net-master\Apollo\SmartThreadPool\CallerThreadContext.cs	49	活动的

**Comment by nobodyiam** [comment]
请把issue提到[apollo.net](https://github.com/ctripcorp/apollo.net/issues)项目中吧。
