### ISSUE TITLE
关于关联类型的nameSpace的疑问

### ISSUE THREAD

**Issue by zustyejunjie** [ctripcorp/apollo#694]
您好。
在不同的应用中，有一些相同的配置信息，就想使用namespace来代替。
创建了一个公共的namespace，没有关联namespace的情况下，配置信息是这样的：
<apollo:config />  使用默认的application
<apollo:config namespaces="TEST1.yejj3"/> 使用yejj3

然后关联了之后，生成了关联类型的namespace，配置信息还是需要
<apollo:config />
<apollo:config namespaces="TEST1.yejj3"/>

所以，这个关联操作有什么用呢，讲道理，把某一个公共的namespace关联过来，在使用的时候，为什么还有指明namespace呢，还是我理解有误。

**Comment by nobodyiam** [comment]
关联是为了继承和覆盖，不是说关联了就一定加载到客户端。
