### ISSUE TITLE
关于页面配置的几个问题

### ISSUE THREAD

**Issue by yoyogao** [ctripcorp/apollo#695]
1.集群创建了无法做任何修改无法删除，请问哪里可以进行配置或删除集群？
2.私有的namespace无论什么情况都不可以删除吗，还是需要进行什么配置？
3.在创建namespace或者namespace中的配置项时候，我只选择了某个环境，但是所有环境都对我的配置生效了，想问是哪里需要进行设置吗？

**Comment by nobodyiam** [comment]
1. 集群目前不支持在页面上删除，不过有接口可以删除
    delete {portal}/apps/{appId}/envs/{env}/clusters/{clusterName:.+}

2. 私有的namespace目前不支持删除

3. 应该是各个环境的meta server指向同一个了，或者是config service连的数据库是同一个了

**Comment by yoyogao** [comment]
非常感谢你的回复～～！！

**Comment by yoyogao** [comment]
今天使用的时候发现，当我回滚了配置之后，namespace中显示的还是回滚前的(修改未发布)配置，这样很难让人分辨出目前的配置到底是什么样的

**Comment by nobodyiam** [comment]
发布历史可以看当前生效的配置

**Comment by nobodyiam** [comment]
配置编辑界面上，如果有配置变化的话，鼠标移上去也可以看到已发布的值的。

**Comment by yoyogao** [comment]
好的，谢谢，你回复的真快，有问题我再请教

**Comment by yoyogao** [comment]
我回滚之后修改另一个配置，发布时会一起连同回滚的值一起发布，可以分开吗

**Comment by nobodyiam** [comment]
一般配置回滚的情况是，一个多几个配置有问题，所以我们认为回滚只是一个短暂状态，一般回滚后对某个配置修改后就会重新发布的，所以我们会保留用户之前的修改配置。

就好像代码发上去之后的回滚，一般就是修一点bug，而不是说所有之前的修改都不要了。

如果真的都不要了，现在的方式是手动把配置恢复到之前的版本（比如使用文本模式，把上一个版本的配置全量复制古来）。

**Comment by yoyogao** [comment]
好的，我明白你的意思了

**Comment by yoyogao** [comment]
namespace不能通过数据库删除数据生效么？如果创建错了就只能那样放着不管了么？
我用了你给的接口去删除集群，但报了500的错，是因为我拉的spring-security-auth分支对于权限有限制吗？

**Comment by nobodyiam** [comment]
public namespace在界面上可以删除的，private namespace目前不能删除

你用了接口删除集群，报了500的错？看下日志吧，和权限没关系的，权限不允许报的是4XX错。

**Comment by yoyogao** [comment]
好的，那创建的项目可以删除吗

**Comment by nobodyiam** [comment]
目前只能在数据库中删除，可以参考下设计文档中的E-R图

**Comment by yoyogao** [comment]
好的

**Comment by nobodyiam** [comment]
最新的master版本已经增加了管理员工具页面，可以删除应用、集群和AppNamespace，会在0.11.0版本中发布，相关文档已经更新，可以参考一下。

https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#5-%E5%A6%82%E4%BD%95%E5%88%A0%E9%99%A4%E5%BA%94%E7%94%A8%E9%9B%86%E7%BE%A4namespace
