### ISSUE TITLE
用户权限（修改和发布）可以细化到某一个环境吗

### ISSUE THREAD

**Issue by zustyejunjie** [ctripcorp/apollo#699]
比如说开发人员A，我希望他在开发环境有修改和发布的权限，用户在修改后可以直接发布自测。
然后对于该项目的正式环境，为了保证安全，开发人员不能有发布权限。
现在权限好像是针对项目和namespace，不能对环境做区分的。
总结下就是 在某一个项目下，开发人员在dev环境下有修改发布权限，但是在正式环境下只有修改权限。这个要怎么做呢？谢谢。

**Comment by nobodyiam** [comment]
目前的权限是到项目+namespace的，没有环境这个维度。

不过有朋友定制Apollo，在权限上加了环境这个维度，从而实现你这个需求。

可以参考下[权限相关E-R Diagram](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1#142-%E6%9D%83%E9%99%90%E7%9B%B8%E5%85%B3e-r-diagram)，看下ApolloPortalDB的role, permission, rolepermission表以及对应的代码。

定制一下不是很复杂，只是我们的理念还是希望由开发人员负责从开发环境一直到生产环境的配置，所以不提供环境这个维度的权限。

**Comment by zustyejunjie** [comment]
好的 谢谢你。

**Comment by nobodyiam** [comment]
感谢 @anthonywanted，Apollo现在支持分环境权限了！详见 #1282，后续会随0.11.0版本发布，请知晓。

权限管理页面截图：

![image](https://user-images.githubusercontent.com/837658/43093361-6ef6d820-8ee2-11e8-8918-26cb1e094115.png)
