### ISSUE TITLE
[feature request]支持配置项的历史版本、可以切换到指定版本

### ISSUE THREAD

**Issue by jiming** [ctripcorp/apollo#700]
这样对于一些复杂的配置，可以直接切换，避免手工录入的工作量和失误

**Comment by nobodyiam** [comment]
这个是指客户端指定加载某个版本，还是portal指定回滚到某个版本？

**Comment by jiming** [comment]
加载某个版本，有点类似一个下拉框，多套可选值。

**Comment by jiming** [comment]
比如我有个复杂的规则配置，在大促的时候用一套，大促前用一套，平时用一套。我就可以通过这个版本的概念很轻松的切换配置了

**Comment by nobodyiam** [comment]
客户端加载指定版本之前也考虑过，但是由于会增加客户端的使用复杂度，容易误用，导致问题，所以我们的策略是客户端始终向服务端请求最新版本。

对于你举的大促和平时两套配置，可以通过灰度发布实现，我们的灰度发布支持AB测试这种场景的。

**Comment by jiming** [comment]
好的，我再深入研究研究啊，多谢了

**Comment by jiming** [comment]
我可能没描述清楚，我说的这个版本对于客户端是不可见的，客户端不知道后端有版本的概念。
客户端只管获取配置项，至于说服务端给返回那个版本，是服务器计算后给出的。

**Comment by nobodyiam** [comment]
那其实就是灰度发布的功能了

**Comment by jiming** [comment]
其实也不是灰度发布，我可能会有 5 个或者甚至更多个版本，而且每次切换版本，都是对所有的线上服务器生效，不是一小部分服务器。

我也在深入了解一下 apollo，看看是不是这样啊。多谢您的热心解答

**Comment by nobodyiam** [comment]
apollo的配置版本不是针对单个配置项的，是针对一个namespace中所有的配置项的，所以模型上不太一样。

**Comment by jiming** [comment]
理解，如果加上这个功能需要增加一个子表了，我先了解了解看这个 feature 是否可以通过 namespace 来简单的实现。多谢了
