### ISSUE TITLE
Apollo 开发的版本管理疑问

### ISSUE THREAD

**Issue by smartwjw** [ctripcorp/apollo#704]
前几天拉下了一份代码 build 了一下，版本号当时是 0.8，这几天看了，发现在 0.8 这个版本上又多了几次提交，这就意味着不同时间 build, 虽然版本都是 0.8， 但是结果是不一样的。
我们内部的做法是，在上一个稳定的版本上 +1 的 SNAPSHOT, 例如目前稳定发布版本是 0.1， 如果要做开发则把版本提升为 0.1-SNAPSHOT, 等确定发版了，把版本提升为 0.2， 依次类推，这样能保证稳定发布版的代码任何时候 build, 结果都是一致的。

**Comment by nobodyiam** [comment]
多谢提醒，#705 已经修改版本为0.9.0-SNAPSHOT。

另外，如果是要实际部署使用的话，建议使用release版本，https://github.com/ctripcorp/apollo/releases。

master分支是开发版本，会一直更新的~
