### ISSUE TITLE
如何删除Cluster

### ISSUE THREAD

**Issue by brotherhorse** [ctripcorp/apollo#708]
添加了的Cluster如何删除掉

**Comment by nobodyiam** [comment]
删除cluster有REST接口可以删除，没有开放给用户，目前接口的权限只允许超级管理员删除

@PreAuthorize(value = "@permissionValidator.isSuperAdmin()")
@requestmapping(value = "apps/{appId}/envs/{env}/clusters/{clusterName:.+}", method = RequestMethod.DELETE)

**Comment by brotherhorse** [comment]
请问具体如何通过curl等工具操作,如何成为超级管理员;另外删除应用(appId)也有同样的需要

**Comment by nobodyiam** [comment]
超级管理员的设置请参考[分布式部署文档](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#3superadmin---portal%E8%B6%85%E7%BA%A7%E7%AE%A1%E7%90%86%E5%91%98)

curl工具的使用自己google一下吧

删除应用目前还没有接口，可以参考[E-R图](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1#14-e-r-diagram)手动清理

**Comment by nobodyiam** [comment]
最新的master版本已经增加了管理员工具页面，可以删除应用、集群和AppNamespace，会在0.11.0版本中发布，相关文档已经更新，可以参考一下。

https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#5-%E5%A6%82%E4%BD%95%E5%88%A0%E9%99%A4%E5%BA%94%E7%94%A8%E9%9B%86%E7%BE%A4namespace
