### ISSUE TITLE
其他语言客户端实现接口为什么不需要使用env参数

### ISSUE THREAD

**Issue by brotherhorse** [ctripcorp/apollo#712]
开放语言文档中的说明和范例都没有使用环境参数,默认获取dev环境吗?如果在服务端配置了多个环境,如何获取不同环境下的配置?

**Comment by nobodyiam** [comment]
URL: {config_server_url}/configfiles/json/{appId}/{clusterName}/{namespaceName}?ip={clientIp}

因为不同环境的{config_server_url}是不同的。

**Comment by brotherhorse** [comment]
如果在同一个Apollo服务器上配置了2个环境,这个url不就是相同的吗

**Comment by nobodyiam** [comment]
no, url包含端口的

比如

- dev是http://localhost:8080
- fat是http://localhost:8081
