### ISSUE TITLE
apollo能够支持线上和本地配置同时读取吗

### ISSUE THREAD

**Issue by buggerfly** [ctripcorp/apollo#714]
我测试下不行……所以是使用了apollo的项目都只能在线上进行配置吗

**Comment by nobodyiam** [comment]
本地配置具体是指？

**Comment by buggerfly** [comment]
是我原来放在本地路径下的配置文件

**Comment by nobodyiam** [comment]
如果是api方式，那只会读取apollo的配置。

如果是spring方式，是没关系的，只是会优先读apollo配置。

**Comment by buggerfly** [comment]
我刚刚测试了下spring方式，当一个项目既用apollo也有本地文件配置时，优先读取的是本地文件里的配置，而且如果要读取apollo里有、但是本地文件里没有的参数，是没办法读到的……

**Comment by nobodyiam** [comment]
从你的描述我得出的结论是，你的项目根本没有从apollo读到过配置，建议仔细阅读下文档和demo吧。

**Comment by buggerfly** [comment]
可是我只要删掉本地的读取方法，就可以正常读取apollo的配置了啊……

**Comment by nobodyiam** [comment]
看看是否符合下面的描述，如果再不行的话，可以看一下源码[PropertySourcesProcessor](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/config/PropertySourcesProcessor.java#L67)

![image](https://user-images.githubusercontent.com/837658/29656786-1739e312-88e8-11e7-88cb-082bc6e6e61b.png)

**Comment by buggerfly** [comment]
ok，打扰您了，感谢回复！
