### ISSUE TITLE
configservice和adminservice支持从外部读取数据库配置吗？

### ISSUE THREAD

**Issue by kuko126** [ctripcorp/apollo#716]
configservice和adminservice模块用的数据库连接地址好像是从common jar包里读取application-github.properties文件获得的。如果需要部署多个环境 是不是只能每次修改build脚本重新构建？

我尝试把application-github.properties提出来放到apollo-adminservice.jar同目录，启动后发现环境列表下PRO会有两个default（common jar包中的application-github.properties配置和根目录下配置不相同）

**Comment by nobodyiam** [comment]
其实如果理解spring配置文件的话，应该知道spring的配置都是支持通过-D system property传入的。

参考下[Apollo开发指南](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97)吧，里面有sample指定spring.datasource.url等数据库参数的。

application-github.properties放到apollo-adminservice.jar同目录或者config目录应该也是可以的，环境列表PRO下有两个default，我还是第一次遇到，不过应该和application-github.properties没啥关系。
