### ISSUE TITLE
为何所有的信息都要打进包里去而不采用外部配置？

### ISSUE THREAD

**Issue by rrfeng** [ctripcorp/apollo#718]
比如 client 端，配置服务器的地址其实可以使用环境变量传递，或者跟 app.id 配置到一起。

感觉打成一个包发布并不是一个好的形式。另外 configDB 还要根据不同环境分别打包。

就像 apollo 诞生的意义：应用程序和配置文件分离，环境只与配置相关而与程序本身无关。然而在 apollo 本身，却又采用了最原始的方式。

在我看来，配置可以分为多个层级：`环境/集群级` -> `服务器级` -> `应用级`
服务器级别的配置一般来说会通过系统环境变量、系统配置文件等传递给应用。而 apollo 配置服务器的地址，我认为是一个 `环境级` 的配置，完全可以也通过集群服务器的系统环境变量来传递。

目前能做到的办法是如过有自己的名字服务，那么可以用自定义域名。然后在不同的环境解析到不同的地址。

以上。

**Comment by nobodyiam** [comment]
思考很深入，先赞一个。

目前Apollo客户端的服务器地址确实是打进包里的，主要目的是为了让开发使用Apollo时零配置。

当然了，我们设计时也考虑过把Apollo服务器地址放在服务器上配置，如server.properties，当时没有采用这个方式的主要原因是这个方式对运维工作又提出了新的要求。

所以，在通过打包传入的方式已经实现了开发零配置的条件下，我们暂时没有采用第二个方案。

后续我们会对客户端做少许改动，支持通过server.properties获取Apollo服务器地址，同时原有的通过打包传入地址的方式也会保留，因为不同公司的实际运维情况会有所不同。

**Comment by rrfeng** [comment]
回复很快，同赞。
不过不止是客户端，meta、config、admin、portal 实际上现在已经是属于基础服务了（更类似于 MySQL 等服务），应该也可以使用外部配置文件的方式。

像 DB 帐号密码配置这种打进包里发布到 maven 相对 client 来说其实问题更严重
```
apollo_config_db_url=jdbc:mysql://localhost:3306/ApolloConfigDB?characterEncoding=utf8
apollo_config_db_username=用户名
apollo_config_db_password=密码
```

顺便再问一个小问题，app.id 这个有什么特殊限制吗？我们架构内部有一个全局唯一的 application.name，是否可以直接当作 apollo app.id 来使用？

**Comment by nobodyiam** [comment]
config, admin, portal都是支持配置通过-D传入的，看下Apollo开发指南里面怎么运行就知道了。通过外部文件也是可以的，这块其实属于spring配置的范畴了，这里就不赘述了。

你们的war包会上传到maven？

app.id只要全局唯一即可。

**Comment by rrfeng** [comment]
嗯这块儿可能是我没看清楚。

感谢回答。

**Comment by nobodyiam** [comment]
apollo-client已经推送到Maven中央仓库, [点击此链接查看](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.ctrip.framework.apollo%22%20AND%20a%3A%22apollo-client%22)
