### ISSUE TITLE
关于namespace的问题

### ISSUE THREAD

**Issue by kuko126** [ctripcorp/apollo#721]
1、@ApolloConfigChangeListener参数中的namespace是否支持通配符如(TEST.*)
2、能否实现把@ApolloConfigChangeListener参数中的namespace也作为apollo平台上的一个配置项
如在application中有一个k,v项   k=namespace v=application,TEST1.test   
我现在的做法是，初始化之前执行下面的方法获取该应用应该监听的namespace
```java
public void update(String namespace) {
        configs = new HashMap<>();
        ApolloChangeListener listener = new ApolloChangeListener();
        for (String ns : namespace.split(",")) {
            Config config = ConfigService.getConfig(ns);
            config.addChangeListener(listener);

            configs.put(ns, config);
            System.out.println("namespace:" + ns);
        }
    }
```

ApolloChangeListener.java
```java
@Override
    public void onChange(ConfigChangeEvent changeEvent) {

        if (changeEvent.getNamespace().equals("application") && changeEvent.isChanged("namespace")) {
            ConfigChange namespace = changeEvent.getChange("namespace");
            //这里的update为上面的方法
            NamespaceManager.getInstance().update(namespace.getNewValue());
        }
//其他操作
}
```

我发现`ConfigService.getConfig(ns);`方法会缓存config，所以即使我清空了configs还是能收到老的namespace上的通知

**Comment by nobodyiam** [comment]
Config对象是按照namespace缓存的，目前看你的场景，可能需要的是config.removeConfigChangeListener()，你可以先在自己的分支增加这个方法，后面我们看是否开源版本也需要这个。

至于namespace参数是否支持通配符，这个我们得考虑一下，因为这样比较容易产生误用，产生不必要的问题。不过你目前的实现方式也不错，把namespace列表作为一项配置来实现，感觉目前也能满足需求了。
