### ISSUE TITLE
怎么添加部门？

### ISSUE THREAD

**Issue by lc273734858** [ctripcorp/apollo#722]
转了一圈没发现添加部门的地方

**Comment by nobodyiam** [comment]
请参考[分布式部署指南 - 2.1.3 调整服务端配置](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#213-%E8%B0%83%E6%95%B4%E6%9C%8D%E5%8A%A1%E7%AB%AF%E9%85%8D%E7%BD%AE)，目前需要在表中直接添加。

**Comment by zhanghaichang** [comment]
什么时候可以有页面添加部门？

**Comment by nobodyiam** [comment]
请参考[分布式部署指南 - 2.1.3 调整服务端配置](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#213-%E8%B0%83%E6%95%B4%E6%9C%8D%E5%8A%A1%E7%AB%AF%E9%85%8D%E7%BD%AE)，现在可以通过`管理员工具 - 系统参数页面`进行配置，修改完一分钟实时生效。
