### ISSUE TITLE
docker部署成功后，环境列表为空，请问是什么问题导致的？

### ISSUE THREAD

**Issue by jston** [ctripcorp/apollo#725]
![image](https://user-images.githubusercontent.com/11856425/29912374-0949e596-8e64-11e7-8ed9-342dd6578fa3.png)

**Comment by hexulin-miaomiao** [comment]
您好我也遇到这样的问题，您的问题解决了吗怎么解决的啊，麻烦告知下，谢谢

**Comment by nobodyiam** [comment]
一般是portal连不上admin service，具体可以看一下portal和admin service的日志
