### ISSUE TITLE
公共NameSpace使用删除后无法再建

### ISSUE THREAD

**Issue by brotherhorse** [ctripcorp/apollo#726]
一个公共NameSpace,创建,并添加配置项,再发布
然后删除该NameSpace,再次创建将提示该NameSpace存在,无法创建!

**Comment by nobodyiam** [comment]
选 关联公共namespace，删除的是关联的实例，不是公共namespace本身

**Comment by brotherhorse** [comment]
公共namespace本身是删除不掉的吗?

**Comment by nobodyiam** [comment]
删除的其实是和cluster的关联，比如应用如果有A,B,C三个cluster，每个cluster下都可以关联公共namespace。

而且目前删除namespace时是有校验的，如果已经有客户端在使用的话，是不允许删除的。

**Comment by brotherhorse** [comment]
谢谢，已经用上了apollo,后期apollo不会有大的变动吧


________________________________
发件人: Jason Song <notifications@github.com>
发送时间: 2017年9月1日 2:10
收件人: ctripcorp/apollo
抄送: brotherhorse; Author
主题: Re: [ctripcorp/apollo] 公共NameSpace使用删除后无法再建 (#726)


删除的其实是和cluster的关联，比如应用如果有A,B,C三个cluster，每个cluster下都可以关联公共namespace。

而且目前删除namespace时是有校验的，如果已经有客户端在使用的话，是不允许删除的。

―

**Comment by nobodyiam** [comment]
主体不会有太大的变动，不过会持续有一些功能改进~

**Comment by nobodyiam** [comment]
最新的master版本已经增加了管理员工具页面，可以删除应用、集群和AppNamespace，会在0.11.0版本中发布，相关文档已经更新，可以参考一下。

https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#5-%E5%A6%82%E4%BD%95%E5%88%A0%E9%99%A4%E5%BA%94%E7%94%A8%E9%9B%86%E7%BE%A4namespace
