### ISSUE TITLE
像dev,pro这样的环境，能不能在新增配置时候自定义，因为每个同事都会有自己的环境呀

### ISSUE THREAD

**Issue by zxj19951029** [ctripcorp/apollo#727]
我觉得在数据库以及配置文件中设置环境的定义会不会不太合理呀，像spring cloud config以及其它的这样远程配置仓库，都是新增配置的时候自定义的，我们一个项目四五个人开发，因为配置文件中有各自的IP地址，我们每个同事都需要一个环境，我们都是以自己名字命名的

**Comment by nobodyiam** [comment]
环境相对是比较固定的东西，部署一个环境需要一整套的服务，成本很高。

你的情况是本地开发环境，建议可以通过-D传入参数，如-Dxxx.host=1.2.3.4

或者也可以为每个人在dev环境创建一个cluster，然后本地开发时通过-Dapollo.cluster=xxx来区分集群配置。

**Comment by zxj19951029** [comment]
@nobodyiam 
哇，好有爱的开发同学，这么快就回复了，给你一个赞。
不过-D加入的参数，可以进入到spring属性中吗？比如说通过value注解获取，而如果IP地址这种参数在本地环境需要，正式环境肯定也需要的，那么就需要-D里面的参数需要覆盖掉apollo里面的配置，不知道apllo当前是否支持

**Comment by nobodyiam** [comment]
-D加入的参数，你可以认为也是apollo的配置，apollo会优先获取的，具体可以看下[DefaultConfig.java](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/DefaultConfig.java#L67)的getProperty方法。

由于apollo和spring进行了集成，所以通过`@Value`是可以获取的。

正式环境不建议通过-D覆盖（会使得打包非常复杂），正式环境如果有这类需求，建议通过创建不同cluster来实现。

**Comment by zxj19951029** [comment]
@nobodyiam 
谢谢，我明白你的意思，不过我的意思是，当我apollo已经配置了一个host的参数时，我在开发环境加上一个-D的启动参数，应该会对其进行覆盖的吧

**Comment by nobodyiam** [comment]
是的
