### ISSUE TITLE
建议上传到dockerhub仓库

### ISSUE THREAD

**Issue by SwenChan** [ctripcorp/apollo#728]
建议上传到dockerhub仓库, 提供一个开箱即用的image, 其实这样更有利于传播这么一个好项目.

**Comment by nobodyiam** [comment]
感谢建议，后面我们把quick start项目弄成一个image，传到dockerhub

**Comment by nobodyiam** [comment]
你好，我们已经上传了docker quick start的镜像，可以参考[Apollo Quick Start Docker部署](https://github.com/ctripcorp/apollo/wiki/Apollo-Quick-Start-Docker%E9%83%A8%E7%BD%B2)跑一下，现在只需要简单的`docker-compose up`即可运行。
