### ISSUE TITLE
xml配置的xsd文件获取失败

### ISSUE THREAD

**Issue by Baivin** [ctripcorp/apollo#730]
有个项目是用xml格式加载的，使用xml方式加载加入以下schema：http://www.ctrip.com/schema/apollo http://www.ctrip.com/schema/apollo.xsd， 使用<apollo:config/> 报错，点击上述appollo.xsd链接发现404，正常来说是可以加载一份 xml的 。

**Comment by nobodyiam** [comment]
这个是通过spring.schemas实现的，不是说真的有这个文件，你看下是不是依赖引用不对。

https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/resources/META-INF/spring.schemas
