### ISSUE TITLE
dev环境集群部署问题

### ISSUE THREAD

**Issue by Baivin** [ctripcorp/apollo#731]
由于dev环境接入较多，想要集群部署，这样一台机子挂了还有其他机子（虽然这时可以读取本地缓存文件，考虑到时效性和多方面的要求），请问客户端能指定多个dev环境吗（我尝试了不行）？ 类似-Ddev_meta=http://localhost:8080，http://localhost:8081 这样子？

**Comment by Baivin** [comment]
我尝试过，启动了两个configService 和 adminService，用相同的数据库，数据库eureka.service.url 配置为对应的两个configService地址，这种能实现集群效果。但是由于client启动只能指定一个configService地址，当这个configService挂掉后，另外一个能补上，不影响读写(缓存效果，记住了spring cloud 互相注册的两台机子)。但是一旦客户端重启就找不到configService了，因为指定的configService挂了

**Comment by nobodyiam** [comment]
按照我们的设计，meta server是通过域名访问的，可以通过一些软负载如nginx等来做转发。

不过考虑到有些公司可能这块运维不是太完善，后续我们会支持meta server以逗号分隔填写多个。

不过为了扩展性，我们仍然是建议通过域名访问，通过软负载转发。
