### ISSUE TITLE
Apollo 和Springcloud config 是一种思路吗? Apollo 完善了Springcloud config?

### ISSUE THREAD

**Issue by daniel-du** [ctripcorp/apollo#734]
最近刚开始看 spring cloud , 发现他有一个 config server, 然后今天看到了您这里有一个 Apollo, 简单看了一下描述. 然后就想问一下, 这个Apollo 是Springcloud config 的一种实现吗?

**Comment by nobodyiam** [comment]
Apollo和Spring Cloud Config类似吧，但不是它的一个实现，可以看一下[Apollo相比于Spring Cloud Config有什么优势？](https://github.com/ctripcorp/apollo/wiki/FAQ#9-apollo%E7%9B%B8%E6%AF%94%E4%BA%8Espring-cloud-config%E6%9C%89%E4%BB%80%E4%B9%88%E4%BC%98%E5%8A%BF)

**Comment by daniel-du** [comment]
谢谢你的回答. 我看了一下对比, 还有下边网友的pdf, 总体看来, 这个还是很给力的.准备持续关注.
