### ISSUE TITLE
有没有提供Java API 往参数配置中心增加参数？

### ISSUE THREAD

**Issue by IcyLemon** [ctripcorp/apollo#736]
Hi，

目前增加、修改参数都是通过管理界面手工输入或拷贝，请问有没有提供Java API，通过程序的方式增加参数？

**Comment by nobodyiam** [comment]
可以看一下[Apollo开放平台](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0)
