### ISSUE TITLE
请教下如何删除apollo中的集群

### ISSUE THREAD

**Issue by wenskys** [ctripcorp/apollo#737]
@nobodyiam
> 集群目前不支持在页面上删除，不过有接口可以删除
> delete {portal}/apps/{appId}/envs/{env}/clusters/{clusterName:.+}

之前看https://github.com/ctripcorp/apollo/issues/695 说可以用接口删除，自己写了个无法删除，想了解具体的curl的写法，不胜感激。
```
#id:web_config env:DEV clusterName:my_home
curl -I -X DELETE  http://apollo.mytest.com/apps/web_config/envs/DEV/clusters/my_home
```

**Comment by nobodyiam** [comment]
删除接口是要校验权限的，一般的做法是先用超级管理员登录，拿到cookie，然后curl的时候把cookie带上。具体curl的语法，man一下就可以了。

**Comment by nobodyiam** [comment]
最新的master版本已经增加了管理员工具页面，可以删除应用、集群和AppNamespace，会在0.11.0版本中发布，相关文档已经更新，可以参考一下。

https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#5-%E5%A6%82%E4%BD%95%E5%88%A0%E9%99%A4%E5%BA%94%E7%94%A8%E9%9B%86%E7%BE%A4namespace
