### ISSUE TITLE
建议：portal 在多 ENV 的配置方式

### ISSUE THREAD

**Issue by rrfeng** [ctripcorp/apollo#743]
按照目前我的理解，会存在以下几个问题：
- 多个 ENV（pro/dev/uat/fat）如果网络隔离的话，portal 很难联系到各环境的 meta。如果将 meta （config）暴露给其他环境显然是不太安全的。如果是外部 eureka 注册中心，暴露给其他环境显然更不安全。同时还需要将 admin 的注册地址更改为可跨网络访问的地址，也不是很方便。
- portal 打包时要填写各个 ENV 的地址。然而这个时候很可能各个 ENV 还没有建立起来。或者存在以后添加 ENV 的情况。即使 portal 的配置可以不用打进包里去，也需要修改配置。

我的想法是，既然 portal 本身只是一个管理界面，全部功能只需要跟 admin service 交互（如果理解有错请指出），那么它本身其实不需要去联系 meta server。只要在 PortalDatabase 里配置不同环境对应的 admin service 的 HTTP 地址即可。对于 admin service 做保护是比较简单的。portal 只需要提供一个『添加 ENV』的配置项，能够填入对应 ENV 的 admin service 地址即可（存到 PortalDatabase 里）。

并且 admin service 也不再需要注册 eureka 了，提供服务的地址可以任意设置。（它本身只需要消费 config service 即可）

如果以上我理解有误还请指出。

**Comment by nobodyiam** [comment]
这个是可以的，只是admin service在扩容、缩容的时候需要同时修改portal中的配置。

**Comment by rrfeng** [comment]
另外又仔细看了一下 admin service 发布配置的方式：写到 db 然后由 config 定时扫描。
所以其实它本身也没有消费 config service，所以也不需要访问 meta 。
这样 admin service 也是一个无状态的服务（仅依赖 ConfigDatabase）。


> 这个是可以的，只是admin service在扩容、缩容的时候需要同时修改portal中的配置。
admin service 本身并不需要扩、缩容吧，甚至在要求不高的环境下，连高可用不不太需要（挂掉也不会影响生产服务，只是无法修改、发布配置了）。
另外这个问题应该也是可以解决的：因为要暴露给外部网络环境，那自然需要一个外部的转发设施（nginx/ha），久可以完成 portal 配置的固化，不需要扩容、缩容时修改。

**Comment by rrfeng** [comment]
update：时候后发现其实 meta 的存在也是多余的，合并 config 和 admin 成一个服务（无状态 http），每个 env 部署一套，通过自己的方案实现高可用（很容易用 nginx/haproxy/slb），然后 portal 同上，配置在 DB 里各个 env 的连接地址即可。

**Comment by nobodyiam** [comment]
portal连admin其实没啥关系的，因为都是短链接。

client连config由于会有长连接，所以是采用IP直连的方式的。不过如果实例不多的话，可能对slb也没啥太大压力。

可以看看对中小规模环境是否可以简化部署啥的。

**Comment by nobodyiam** [comment]
恩，对我们公司由于远不止几万连接，所以为了避免给slb带来麻烦，是通过IP直连的，对于中小规模的可能问题不大。

**Comment by davidclj** [comment]
@nobodyiam

**Comment by davidclj** [comment]
我感觉 adminservice configservice 接口都暴露了 不安全啊
http://106.12.25.204:8080/configs/apollo-demo/default/application
上面这个地址是你们的demo，我可以绕过portal直接访问configservice了

**Comment by nobodyiam** [comment]
config service设计是内网服务，本来就不需要通过portal访问的

**Comment by nobodyiam** [comment]
1.6.1版本已经支持Portal配置自定义环境名字和对应Meta Server地址，详见[调整ApolloPortalDB配置](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#2131-%E8%B0%83%E6%95%B4apolloportaldb%E9%85%8D%E7%BD%AE)
