### ISSUE TITLE
关于env的问题

### ISSUE THREAD

**Issue by qiankunli** [ctripcorp/apollo#744]
我粗略的观察，apollo-adminservice 负责一个具体env的配置。那就是一个env对应一个apollo-adminservice 实例，然后由meta service负责dispatch？

**Comment by nobodyiam** [comment]
一个env对应1..n个config service/meta service和1..n个admin service

meta service只负责返回服务列表，不负责dispatch

dispatch由客户端自己实现的

**Comment by qiankunli** [comment]
这么说，不同env的配置，有可能存在不同的database中？

**Comment by nobodyiam** [comment]
ApolloPortalDB就一个，ApolloConfigDB每个环境一个

**Comment by qiankunli** [comment]
那假如dev环境配了一个配置，开发完毕上线后，product还得再配置一份，有点不方便，这个有解决的措施么

**Comment by qiankunli** [comment]
不好意思哈，我自己实际部署了一个试了一下，apollo提供了在各个环境间同步配置的功能

**Comment by qiankunli** [comment]
请教下，apollo当下使用meta service 维护env的方式挺好的，但其也可以通过在数据库中增加env信息的方式实现。当时这样做，主要有哪些考虑呢？

**Comment by nobodyiam** [comment]
meta service的服务对象是apollo-client和apollo-portal，由于我们会有各种语言的客户端，如Java，.Net，Go等，所以不希望把eureka细节暴露给客户端，所以通过meta service做封装。

数据库中，你是指eureka.service.url这个配置吗？这个只是给config service和admin service用的，用于配置eureka的地址（按照我们的实际部署，就是config service）。

**Comment by qiankunli** [comment]
不是的，我说的还是对多env的支持问题。因为人直接的想法是，为配置或者namespace关联一个env id，这样只需要一个config service就可以了（这样的话，查询配置时要带上env参数）。而对于apollo来说，则是一种新的方式。

**Comment by nobodyiam** [comment]
不建议这种方式，这样无法做到环境隔离、数据隔离。

目前apollo的设计方式就是fat的客户端连接fat的config-service，对应fat的ApolloConfigDB，pro的客户端连接pro的config-service，对应pro的ApolloConfigDB。

环境间互相不会受影响。

唯一跨环境访问的是apollo-portal，不过是受控的。

**Comment by qiankunli** [comment]
![image](https://user-images.githubusercontent.com/8024725/30321336-3a7004ce-97e8-11e7-95e1-bafca2672cda.png)

我自己搭的分布式环境，一直无法看到“补缺环境”，这个一般是什么原因导致的呢？

**Comment by nobodyiam** [comment]
补缺环境只有在portal发现某些环境缺失数据时才会出现的，正常是没有的。

**Comment by qiankunli** [comment]
好的，问题已解决，谢谢您耐心的答复

**Comment by Lao-Tse** [comment]
# 👍
