### ISSUE TITLE
为什么不直接使用apache.common的包，使用StringUtils，基于什么考虑重新写

### ISSUE THREAD

**Issue by Acceml** [ctripcorp/apollo#748]
https://github.com/ctripcorp/apollo/blob/fe4f3b8d80058fba367512e2fb3e79ad32aeb565/apollo-core/src/main/java/com/ctrip/framework/foundation/internals/Utils.java#L3
```
  <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.6</version>
  </dependency>
```
写法是一样的:
```
public static boolean isBlank(final CharSequence cs) {
        int strLen;
        if (cs == null || (strLen = cs.length()) == 0) {
            return true;
        }
        for (int i = 0; i < strLen; i++) {
            if (Character.isWhitespace(cs.charAt(i)) == false) {
                return false;
            }
        }
        return true;
    }
```
是怕打入的包太大了么？

**Comment by Acceml** [comment]
`  <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.6</version>
        </dependency>`

**Comment by nobodyiam** [comment]
主要是为了客户端依赖少一些，不过其实客户端也可以不用自己写，因为客户端依赖了guava，可以改用guava的api
