### ISSUE TITLE
配置项支持格式，如数字、日期等

### ISSUE THREAD

**Issue by Acceml** [ctripcorp/apollo#749]
我看到todo里面有支持数字、日期等这个项目。
[代码](https://github.com/ctripcorp/apollo/blob/fe4f3b8d80058fba367512e2fb3e79ad32aeb565/apollo-client/src/main/java/com/ctrip/framework/apollo/util/function/Functions.java#L5)已经有了啊。

目前我在业务场景中比较常见的是如下几种情况：
```
Set<Integer> getIntSetValue(String key)
Set<Long> getLongSetValue(String name)
Set<Double> getDoubleSetValue(String name, Set<Double> defaultValue)
Map<String, Integer> getStringIntMapValue(String name)
boolean getBoolValue(String name, boolean defaultValue)
```
这个如果需要的话我把它写进去，还是说当时没写是为了给各个客户端最大的自由度自己写一个adapter 去做。

**Comment by nobodyiam** [comment]
这个todo事项是指在portal界面上支持数字、日期等格式，也就是输入的时候使用一些特殊控件之类的，然后可以让用户配置一些meta信息，比如最大、最小值等。

**Comment by Acceml** [comment]
@nobodyiam 那会不会考虑加上map<>的配置，我们部门之前是用zk，后来用apollo，业务场景中用到的还蛮多的，也是把这部分放到zk的基础包里面，相信其他团队也经常遇到。通常是: 
```
key=key1:value1;key2:value2
key=value1,value2,value3
```
这样子。

**Comment by nobodyiam** [comment]
```
key=value1,value2,value3
```

这个配置看上去更像是[getArrayProperty](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/AbstractConfig.java#L220)的场景

```
key=key1:value1;key2:value2
```

这个看上去应该是你说的map<>的场景，只是这个格式有些自定义的意思在里面。

这个其实更像是我们的另外一个todo事项，支持更复杂的格式，如table, tree（展示对象格式）等

这类配置，目前可以存一个json字符串到配置中心，然后应用取出来自己json解析一下

**Comment by nobodyiam** [comment]
暂时先关闭了，可以保存json字符串，然后客户端取出时自行转换一下，谢谢~
