### ISSUE TITLE
demo启动日志报错

### ISSUE THREAD

**Issue by bingwenwuhen** [ctripcorp/apollo#755]
我启动了这个项目中的demo中的spring boot demo，日志报错为：[apollo-demo][Apollo-RemoteConfigLongPollService-1]2017-09-12 10:58:53,124 ERROR [com.ctrip.framework.apollo.util.ConfigUtil] env is not set, please make sure it is set in /opt/settings/server.properties!

server.properties这个文件需要我单独再去创建一份吗？

因为应用默认都是8080端口，我在resources下增加了一个新的配置文件，设置server.port为9090,和这个有没有影响？

**Comment by lepdou** [comment]
这里的server.properties是表示client当前所属的环境信息，是放在应用所在机器上的一个配置文件，不是在项目里。

1.2.2 Environment

Apollo支持应用在不同的环境有不同的配置，所以Environment是另一个从服务器获取配置的重要信息。

Environment可以通过以下3种方式的任意一个配置：

通过Java System Property

可以通过Java的System Property env来指定环境
在Java程序启动脚本中，可以指定-Denv=YOUR-ENVIRONMENT
如果是运行jar文件，需要注意格式是java -Denv=YOUR-ENVIRONMENT -jar xxx.jar
注意key为全小写
通过操作系统的System Environment

还可以通过操作系统的System Environment ENV来指定
注意key为全大写
通过配置文件

最后一个推荐的方式是通过配置文件来指定env=YOUR-ENVIRONMENT
对于Mac/Linux，文件位置为/opt/settings/server.properties
对于Windows，文件位置为C:\opt\settings\server.properties

**Comment by bingwenwuhen** [comment]
@lepdou 我设置了main启动程序参数为-Denv=DEV，这里的DEV是指我们在QuickStart中的dev环境吗？

然后我配置完成后日志为：
[apollo-demo][Apollo-RemoteConfigLongPollService-1]2017-09-12 19:56:45,146 WARN  [com.ctrip.framework.apollo.internals.RemoteConfigLongPollService] Long polling failed, will retry in 2 seconds. appId: 100004458, cluster: default, namespaces: application, reason: Get config services failed from ${dev_meta}/services/config?appId=100004458&ip=192.168.6.43 [Cause: Could not complete get operation [Cause: no protocol: ${dev_meta}/services/config?appId=100004458&ip=192.168.6.43]]

长轮训失败，还是无法拿到正确的配置？

**Comment by lepdou** [comment]
${dev_meta}/services/config?appId=100004458&ip=192.168.6.43
原因是${dev_meta}这个变量没有替换掉dev环境的meta地址。
你的apollo-client包 是自己打出来的吗？
在 [build.sh](https://github.com/ctripcorp/apollo/blob/master/scripts/build.sh)里面，需要设置这个变量值。

**Comment by bingwenwuhen** [comment]
@lepdou 我将apollo项目clone下来，运行的apollo demo模块中的spring boot demo，运行的apollo服务是下载的QuickStart中的安装包。
所以apollo-client包就是Apollo项目中的client模块。

那个quickstart的安装包里面的demo.sh,里面有：
BASE_JAVA_OPTS="-Denv=dev -Ddev_meta=$config_server_url"
有dev-meta的设置。

**Comment by lepdou** [comment]
@bingwenwuhen 
quick start项目是为了快速体验apollo，所以quick start运行的时候，只能用demo.sh来测试。如果直接跑项目里的spring boot demo是不行的。因为没有设置meta地址。
或者你也可以在运行的时候加入-Denv=dev -Ddev_meta=$config_server_url 这几个变量。
注意，把$config_server_url 替换成config server的地址。可以参考demo.sh里面的值，就可以了

**Comment by bingwenwuhen** [comment]
@lepdou 成功了，多谢。
