### ISSUE TITLE
docker compose部署问题

### ISSUE THREAD

**Issue by bingwenwuhen** [ctripcorp/apollo#756]
我把项目clone下来后，执行run.sh 在构建镜像的时候，到apollo-portal时一直有一个warning为：
[Warning] Aborted connection 28 to db: 'ApolloPortalDB' user: 'root' host: '172.26.0.2' (Got an error reading communication packets)
然后
apollo-configservice 和apollo-portal不断的在退出和重启

这个怎么解决？

**Comment by nobodyiam** [comment]
看看有没有更多日志信息吧

[Warning] Aborted connection 28 to db: 'ApolloPortalDB' user: 'root' host: '172.26.0.2' (Got an error reading communication packets)

这个应该是连接数据库异常吧

**Comment by nobodyiam** [comment]
我们更新了docker quick start的镜像，你可以参考下[Apollo Quick Start Docker部署](https://github.com/ctripcorp/apollo/wiki/Apollo-Quick-Start-Docker%E9%83%A8%E7%BD%B2)重新跑一下，现在的步骤简单很多，应该不会遇到这类错误了。
