### ISSUE TITLE
关于namespace表设计的问题

### ISSUE THREAD

**Issue by qiankunli** [ctripcorp/apollo#758]
apollo config db中，有一个AppNamespace 表，其表达的信息只是多了一个isPublic和comment，为什么不将isPublic 字段放在 namespace表中呢？

比如：namespace 新增字段  isPublic 和 refNamespaceId

**Comment by nobodyiam** [comment]
AppNamespace是元信息，跨环境的。你可以认为它是一个class，namespace是它在不同的env, app, cluster下的instance。
