### ISSUE TITLE
[Feature request]提供一些核心的 restful api

### ISSUE THREAD

**Issue by jiming** [ctripcorp/apollo#762]
1. 修改配置的值
2. 发布指定配置

devops 必备功能哦

**Comment by nobodyiam** [comment]
这块已经有了，可以参考[Apollo开放平台接入指南](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0)

**Comment by jiming** [comment]
牛！
