### ISSUE TITLE
内部框架无法注入配置

### ISSUE THREAD

**Issue by qiankunli** [ctripcorp/apollo#763]
我们公司有自己开发的rpc及服务治理系统mainstay。其提供了自己的一套与spring 整合的机制，当我试图使用apollo 注入部分配置时，没有成功。你们那边有碰到类似的问题么？

`   
 <mainstay:client id="albumClient" registry="registry"
                     application="mobileTrackClientApplication" protocol="protocol"
                     iface-class="com.xx.service.album.api.IAlbumFacadeHandler.Iface"
                     enable-netty-native="false"
                     enable-metric="false"
                     io-size="${album.facade.io.size}"
                     timeout="${album.facade.timeout}"
                     max-connection-size="${album.facade.max.connection.size}"
                     max-acquire-pending-size="${album.facade.max.acquire.pending.size}"
                     group="${album.facade.group}"
                     enable-xdcs="true"
    ></mainstay:client>
`
maisntay这边读取 该配置，就可以生成一个client 实例，并注入到业务代码中。

**Comment by nobodyiam** [comment]
如果是spring环境，应该是没问题的。

不过需要注意的是，如果之前有使用`org.springframework.beans.factory.config.PropertyPlaceholderConfigurer`的，请替换成`org.springframework.context.support.PropertySourcesPlaceholderConfigurer`。Spring 3.1以后就不建议使用PropertyPlaceholderConfigurer了，要改用PropertySourcesPlaceholderConfigurer。

**Comment by qiankunli** [comment]
发现了问题了，我在demo中完全是配置文件的方式，貌似需要显式的是在spring 配置文件中写入
`<bean class="xxx.ConfigPropertySourcesProcessor/>`

**Comment by nobodyiam** [comment]
你是不是没有配置apollo？参考下https://github.com/ctripcorp/apollo/blob/master/apollo-demo/src/main/resources/spring.xml吧以及Java客户端使用文档？
```xml
<apollo:config/>
```

**Comment by qiankunli** [comment]
这个是配置了的，我整个项目没有用apollo的注解，纯xml方式。所有没有`@Import(ApolloConfigRegistrar.class)`，import注解没有发挥作用。 这种情况下，你是在哪里触发 `ConfigPropertySourcesProcessor.postProcessBeanDefinitionRegistry` 的执行呢？

**Comment by nobodyiam** [comment]
配置了
```xml
<apollo:config/>
```
会触发[NamespaceHandler](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/config/NamespaceHandler.java)的

**Comment by qiankunli** [comment]
找到这个了，我理解下精髓

` 
static class BeanParser extends AbstractSingleBeanDefinitionParser {
    @Override
    protected Class<?> getBeanClass(Element element) {
      return ConfigPropertySourcesProcessor.class;
    }
}
`

非常感谢您
