### ISSUE TITLE
http://www.ctrip.com/schema/apollo , 界面丢失

### ISSUE THREAD

**Issue by snowygao** [ctripcorp/apollo#764]
http://www.ctrip.com/schema/apollo , 界面丢失。
提示 很抱歉，页面访问失败，需要重新选择目的地。

**Comment by nobodyiam** [comment]
这个是在代码中的，不是一个url

https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/resources/META-INF/spring.handlers

**Comment by snowygao** [comment]
多谢快速反馈。
配置可以正常使用，但是apollo:config报有错误。
另外${username：aaa}设置默认值后不起作用。

以下是我的使用方式：
	<apollo:config/>
	<bean name="jdbcDataSourcem2m_local" class="com.alibaba.druid.pool.DruidDataSource"  init-method="init" destroy-method="close">  
	      
	    <property name="driverClassName" value="com.mysql.jdbc.Driver" />  
	    <property name="url" value="jdbc:mysql://${mysql_ip}:3306/m2m?useUnicode=true&amp;characterEncoding=UTF-8" />  
	    <property name="username" value="${username}" />  
	    <property name="password" value="${password}" />

**Comment by snowygao** [comment]
<apollo:config/>
	<bean name="jdbcDataSourcem2m_local" class="com.alibaba.druid.pool.DruidDataSource"  init-method="init" destroy-method="close">  
	      
	    <property name="driverClassName" value="com.mysql.jdbc.Driver" />  
	    <property name="url" value="jdbc:mysql://${mysql_ip}:3306/m2m?useUnicode=true&amp;characterEncoding=UTF-8" />  
	    <property name="username" value="${username}" />  
	    <property name="password" value="${password}" />

**Comment by snowygao** [comment]
<apollo:config/>  ----》 此处在eclipse里面报错误
<bean name="jdbcDataSourcem2m_local" class="com.alibaba.druid.pool.DruidDataSource"  init-method="init" destroy-method="close">  
      
    <property name="driverClassName" value="com.mysql.jdbc.Driver" />  
    <property name="url" value="jdbc:mysql://${mysql_ip}:3306/m2m?useUnicode=true&amp;characterEncoding=UTF-8" />  
    <property name="username" value="${username:aaa}" />   ---》此处设置默认值无效
    <property name="password" value="${password}" />

**Comment by nobodyiam** [comment]
如果是xml报错的话，说明是没有引用apollo的xmlns，请参考 https://github.com/ctripcorp/apollo/blob/master/apollo-demo/src/main/resources/spring.xml 看一下xml头部怎么写的。

**Comment by snowygao** [comment]
在云主机上运行报一下错误：
2017/09/18 20:17:16 OSS WARN  [org.springframework.beans.factory.xml.XmlBeanDefinitionReader] - Ignored XML validation warning
org.xml.sax.SAXParseException; lineNumber: 18; columnNumber: 18; schema_reference.4: Failed to read schema document 'http://www.ctrip.com/schema/apollo.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.

在我本地只是在eclips里面有提示，但是可以正常运行。这是为什么啊？多谢！

**Comment by snowygao** [comment]
以下是我的声明： 
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:tx="http://www.springframework.org/schema/tx" xmlns:p="http://www.springframework.org/schema/p" 
       xmlns:apollo="http://www.ctrip.com/schema/apollo"
       xmlns:aop="http://www.springframework.org/schema/aop" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans   
    http://www.springframework.org/schema/beans/spring-beans-3.0.xsd   
    http://www.springframework.org/schema/tx   
    http://www.springframework.org/schema/tx/spring-tx-3.0.xsd   
    http://www.springframework.org/schema/aop    
    http://www.springframework.org/schema/aop/spring-aop-3.0.xsd
    http://www.springframework.org/schema/context
    http://www.springframework.org/schema/context/spring-context.xsd
    http://www.ctrip.com/schema/apollo
    http://www.ctrip.com/schema/apollo.xsd">

**Comment by snowygao** [comment]
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:tx="http://www.springframework.org/schema/tx" xmlns:p="http://www.springframework.org/schema/p" 
       xmlns:apollo="http://www.ctrip.com/schema/apollo"
       xmlns:aop="http://www.springframework.org/schema/aop" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans   
    http://www.springframework.org/schema/beans/spring-beans-3.0.xsd   
    http://www.springframework.org/schema/tx   
    http://www.springframework.org/schema/tx/spring-tx-3.0.xsd   
    http://www.springframework.org/schema/aop    
    http://www.springframework.org/schema/aop/spring-aop-3.0.xsd
    http://www.springframework.org/schema/context
    http://www.springframework.org/schema/context/spring-context.xsd
    http://www.ctrip.com/schema/apollo
    http://www.ctrip.com/schema/apollo.xsd">

**Comment by snowygao** [comment]
[shengming.txt](https://github.com/ctripcorp/apollo/files/1310611/shengming.txt)
这是xml中的声明

**Comment by snowygao** [comment]
多谢，问题找到了。是因为本地jar包没有加载。
