### ISSUE TITLE
Long polling问题

### ISSUE THREAD

**Issue by snowygao** [ctripcorp/apollo#765]
在xml内通过<apollo:config/>引入apollo后，从log上看每30秒就会Long polling一次，这个能修改吗？如何设置才能不主动poll？多谢！

以下是log：
2017/09/18 10:14:12 OSS DEBUG [com.ctrip.framework.apollo.internals.RemoteConfigLongPollService] - Long polling

**Comment by nobodyiam** [comment]
long polling机制是保证配置实时性的手段，这个是客户端默认行为，不能关闭。

具体可以参考[Apollo配置中心设计](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1)

**Comment by snowygao** [comment]
好的，多谢。
long polling  30秒的间隔也是不可以设置的吧？

**Comment by nobodyiam** [comment]
这个是服务端控制的，可以设置，不过不建议时间太长。

https://github.com/ctripcorp/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/wrapper/DeferredResultWrapper.java#L20
