### ISSUE TITLE
多个公有云部署问题

### ISSUE THREAD

**Issue by snowygao** [ctripcorp/apollo#766]
我们现在有个需求就是需要在多个公有云上部署配置中心，每个公有云上部署的配置中心都有dev fat uat pro四个环境。怎么样配置开发时才能使用一个统一的客户端jar包呢？多谢！

也就是说开发业务时，我们想依赖同一个客户端，可以做到吗？多谢！

**Comment by snowygao** [comment]
我们现在有个需求就是需要在多个公有云上部署配置中心，每个公有云上部署的配置中心都有dev fat uat pro四个环境。如何配置，开发时才能使用一个统一的客户端jar包呢？多谢！

**Comment by nobodyiam** [comment]
多个公有云之间应该是独立的吧，那这样jar包里面始终指向某个SLB/EIP，然后路由就可以了？

**Comment by snowygao** [comment]
每个公有云的SLB是不一样的, 但是现在客户端需要在编译的时候就写好了dev_meta信息了，这样导致这个客户端就不能通用了。能把这个配置提取出来吗？做成配置文件？

**Comment by nobodyiam** [comment]
这个本来就是可以的，一种方式是在应用通过-Ddev_meta传入，一种是把apollo-env.properties外置放在应用的classpath下。

后面我们会考虑增加一种途径，通过server.properties配置meta server地址。

**Comment by snowygao** [comment]
好的，多谢！
这个的应用说明在哪啊，我在wiki上没找到。

**Comment by nobodyiam** [comment]
这个在 Apollo开发指南 部分有提到，之前主要是为了开发阶段方便。

**Comment by snowygao** [comment]
您好，请问通过server.properties配置meta server地址这种方式，大约什么时候可以支持啊？多谢

**Comment by snowygao** [comment]
您好，请问通过server.properties配置meta server地址这种方式，大约什么时候可以支持啊？多谢

**Comment by nobodyiam** [comment]
这个估计要晚一些，估计要等到0.9.0之后的版本

**Comment by nobodyiam** [comment]
apollo最新版本已经支持通过server.properties配置meta server地址，更多可以参考 [1.2.2 Apollo Meta Server](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#122-apollo-meta-server)，同时1.0.0版本开始可以直接使用Maven中央仓库中的apollo-client。

case先关闭了，如还有问题，可以提供更多信息，或进群交流。
