### ISSUE TITLE
UAT环境下访问失败

### ISSUE THREAD

**Issue by snowygao** [ctripcorp/apollo#767]
[aaaaa.txt](https://github.com/ctripcorp/apollo/files/1313718/aaaaa.txt)

现象：
DEV环境可以正常访问，UAT环境访问失败。

日志：
附件是我截取的log

问题：
1
 UAT环境下提示超时失败; 但是URL我测试是可以访问的。

2
为什么DEV和UAT访问的URL不一样呢？

**Comment by lepdou** [comment]
Get config services failed from http://uat.config.m2m.rootcloud.com:8060/services/config?appId=m2m_config&ip=10.66.64.131 [Cause: Could not complete get operation [Cause: connect timed out]]

日志显示是超时，要么是服务端没启动，要么是客户端网络的问题。

可以看一下服务端http://uat.config.m2m.rootcloud.com:8060 config server是不是正常启动。url你测过可以访问的，那估计是客户端这边的问题。你测试是在你本地机器测试的吗？出错的是uat的机器？如果是这样的话，登录uat的机器 curl测试一下，可能是网络的问题

**Comment by snowygao** [comment]
http://uat.config.m2m.rootcloud.com:8060 是正常的

**Comment by snowygao** [comment]
![1](https://user-images.githubusercontent.com/31984200/30587093-91ee4108-9d64-11e7-9d02-324c805c5fa7.png)
追加截图

**Comment by lepdou** [comment]
你在uat机器上测试能访问这个地址吗？
http://uat.config.m2m.rootcloud.com:8060/services/config?appId=m2m_config&ip=10.66.64.131

**Comment by lepdou** [comment]
dev和uat每个环境独立的一套server，所以地址是不一样的。
可以看一下部署模型。
https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97

客户端根据你配置的meta地址以及当前所属的环境去访问meta server。
uat.meta=http://uat.config.m2m.rootcloud.com:8060
pro.meta=
lpt.meta=${lpt_meta}
local.meta=http://localhost:8080
dev.meta=http://dev.config.m2m.rootcloud.com:8060

**Comment by snowygao** [comment]
访问：http://uat.config.m2m.rootcloud.com:8060/services/config?appId=m2m_config&ip=10.66.64.131
返回的是：
[{"appName":"APOLLO-CONFIGSERVICE","instanceId":"config-uat-890360573-0q5ny:apollo-configservice:8060","homepageUrl":"http://uat.config.m2m.rootcloud.com:8060/"}]

**Comment by snowygao** [comment]
了解，多谢！是本地安全策略的问题，多谢解答！
