### ISSUE TITLE
Apollo的数据库能使用Oracle么

### ISSUE THREAD

**Issue by iamzhangxin** [ctripcorp/apollo#770]

**Comment by nobodyiam** [comment]
可以的，不过需要一些小改动，我们自己没有在oracle上跑过，有几个公司把Apollo的数据库部署在Oracle的，大概的改动可能有以下这些（可能不全）：

1. schema适配到oracle
2. application.properties中initSql需要修改
3. 在pom中引入oracle驱动

**Comment by nobodyiam** [comment]
暂时先关闭了，之前已经有公司成功把apollo跑在oracle上了，不过改动点还是有一些的，如果遇到问题的话，可以进qq群讨论，谢谢~
