### ISSUE TITLE
long polling failed

### ISSUE THREAD

**Issue by qiankunli** [ctripcorp/apollo#772]
我们在测试环境中应用apollo，会报一些`Long polling failed, will retry in 1 seconds. appId: {}, namespaces: {}, reason: connect time out`

请问下，这个是否跟tomcat支持的最大连接数有关系？我查询一些资料，tomcat支持的最大连接数据maxConnections，bio模式下最大是200，nio模式下最大是1000，感觉都没到上限呢。

基于此，线上的最大连接数配置等，您有实践建议推荐么？

**Comment by nobodyiam** [comment]
nio默认是10000吧，apollo目前就是用默认的nio，没有特殊配置。

导致connect timeout的原因有很多，可以看看服务器目前的处理性能，以及客户端和服务端之间的网络情况。

**Comment by klboke** [comment]
你应该检查下你的客户端应用，为什么输出的日志里Long polling failed, will retry in 1 seconds. appId: {}, namespaces: {}, reason: connect time out，诸如appId：{},为什么没有输出具体的appid

**Comment by nobodyiam** [comment]
暂时先关闭了，如有问题，可以提供更多信息，谢谢~
