### ISSUE TITLE
Spring Boot集成Apollo客户端出现问题

### ISSUE THREAD

**Issue by tianyi19970120** [ctripcorp/apollo#773]
# 接收到change Event刷新了值，但是程序中相应的值并没有改变

```
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.cloud.context.config.annotation.RefreshScope;
import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;

/**
 * Created by cldong on 9/27/2017.
 */
@ConfigurationProperties(prefix = "spring.datasource")
@Component("sampleDataSource")
@RefreshScope
public class SampleDataSource {
    private static final Logger logger = LoggerFactory.getLogger(SampleDataSource.class);

    private String username;
    private String password;
    private String url;
    private String driverClassName;

    @PostConstruct
    private void initialize() {
        logger.info("SampleDataSource initialized - username: {}, password: {}, url: {},driverClassName: {}",
                username, password, url, driverClassName);
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public void setDriverClassName(String driverClassName) {
        this.driverClassName = driverClassName;
    }

    @Override
    public String toString() {
        return String.format("[SampleDataSource] username: %s, password: %s, url: %s,driverClassName: %s",
                username, password, url, driverClassName);
    }
}

```
我能通过change event得到相对应的改变，并成功改变SampleDataSource 的值，但是对应的spring.datasource.username通过去取，并没有任何变化，不知道是否我的理解不对

**Comment by tianyi19970120** [comment]
![image](https://user-images.githubusercontent.com/20501175/30899961-bb6d1726-a394-11e7-961c-c9d16a7b8f3a.png)
![image](https://user-images.githubusercontent.com/20501175/30899976-c722e6a4-a394-11e7-9ffe-9358aee6f3b6.png)
![image](https://user-images.githubusercontent.com/20501175/30899988-d23830da-a394-11e7-94bb-4eb4d7956112.png)

**Comment by tianyi19970120** [comment]
这边看到刷新之后spring.datasource.username没有发生变化

**Comment by nobodyiam** [comment]
请参考[apollo-demo的示例代码](https://github.com/ctripcorp/apollo/blob/master/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/spring/springBootDemo/refresh/SpringBootApolloRefreshConfig.java#L33)在配置变化时刷新sampleDataSource这个bean。

**Comment by tianyi19970120** [comment]
![image](https://user-images.githubusercontent.com/20501175/30900183-93ce7786-a395-11e7-8a6b-f4cceeb6e0db.png)

* 我这边能监听到sampleDataSource产生的变化，并且在controller输出时如图也会有不同，但是sampleDataSource下的username的这个属性，是从spring.datasource.username取得，其在sampleDataSource发生了变化，但是通过@Value去取就没有变化。

**Comment by nobodyiam** [comment]
你的spring.datasource.username在两个地方注入了，一个是sampleDataSource，另一个是你另外一个什么bean？

refreshAll调用后，至少sampleDataSource里面的值应该是会变的，你另外一个地方不知道你怎么写的。

另外，你这个sample和[SampleRedisConfig](https://github.com/ctripcorp/apollo/blob/master/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/spring/springBootDemo/config/SampleRedisConfig.java)一样的吧

**Comment by tianyi19970120** [comment]
是的，我刚刚又理解了一下，就比如我这边的spring.datasource.username值需要更改，如果要真的应用到datasource这个bean上，是需要我重写datasource这个bean的实现，然后刷新值是刷新datasource实例中的值，是这个意思么

**Comment by nobodyiam** [comment]
这个其实每个不同的场景都不一样的。

仅以datasource而言，那就是你应该有一个自己的datasource实现，它启动时会获取spring.datasource.name等配置，去composite一个真正的datasource。

然后在spring.datasource.name等配置更新时，使用新的配置创建一个新的datasource，然后做一次swap，让后续请求都走新的datasource，同时异步的把老的datasource的连接逐步释放，最终销毁。

**Comment by tianyi19970120** [comment]
好的，我知道了，谢谢你的回答

**Comment by sunnyfrank** [comment]
意思是datasource redis这种有连接的配置 不能直接使用spring自动配置实时刷新吗？

**Comment by nobodyiam** [comment]
@sunnyfrank 可以参考 [dynamic-datasource](https://github.com/ctripcorp/apollo-use-cases/tree/master/dynamic-datasource)
