### ISSUE TITLE
nested exception is java.util.zip.ZipException: invalid code lengths set的问题解决

### ISSUE THREAD

**Issue by easonjim** [ctripcorp/apollo#778]
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.ctrip.framework.apollo.configservice.ConfigServiceApplication]; nested exception is java.util.zip.ZipException: invalid code lengths set
如果出现以上错误，可以尝试讲本地.m2文件夹删除，然后重新下载所有的包。
可能是本地下载某个JAR包时网络错误导致下载失败。

**Comment by nobodyiam** [comment]
Thanks
