### ISSUE TITLE
使用《分布式部署指南》在单机部署的简单步骤和注意事项

### ISSUE THREAD

**Issue by easonjim** [ctripcorp/apollo#779]
一、下载Release版本
[https://github.com/ctripcorp/apollo/releases](url)
二、登录MySQL并导入数据库脚本
source /path/to/scripts/sql/apolloconfigdb.sql
source /path/to/scripts/sql/apolloportaldb.sql
三、打包
运行 /path/to/scripts/build.sh
四、运行
参考：[https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#22-%E9%85%8D%E7%BD%AE%E6%95%B0%E6%8D%AE%E5%BA%93%E8%BF%9E%E6%8E%A5%E4%BF%A1%E6%81%AF](url)
五、单机运行注意修改apollo-portal的端口为8070
apollo-portal的默认端口是8080，和apollo-configservice一致，所以如果需要在一台机器上同时启动apollo-portal和apollo-configservice的话，需要修改apollo-portal的端口。直接修改startup.sh中的SERVER_PORT即可，如SERVER_PORT=8070。

**Comment by nobodyiam** [comment]
Thanks!
