### ISSUE TITLE
写了一个简单的python客户端

### ISSUE THREAD

**Issue by filamoon** [ctripcorp/apollo#780]
写了一个简单的python客户端，支持long polling，请多多指教
https://github.com/filamoon/pyapollo

用法就在py文件的 if __name__ == '__main__' 块里，很简单。
原理是单开一个线程来执行long polling

**Comment by nobodyiam** [comment]
Thanks!

**Comment by nobodyiam** [comment]
已经更新到[Go、Python、NodeJS等客户端使用指南](https://github.com/ctripcorp/apollo/wiki/Go%E3%80%81Python%E3%80%81NodeJS%E7%AD%89%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)，感谢支持！
