### ISSUE TITLE
XML配置报错

### ISSUE THREAD

**Issue by chowc** [ctripcorp/apollo#783]
按照 [3.2.1.1 基于XML的配置](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#3211-%E5%9F%BA%E4%BA%8Exml%E7%9A%84%E9%85%8D%E7%BD%AE)
的做法，
`  <apollo:config/>`处报错，而访问  http://www.ctrip.com/schema/apollo.xsd 结果是404

**Comment by nobodyiam** [comment]
这个schema是在apollo-core.jar里面的，如果报错，说明没有正确引用apollo-client.jar。

**Comment by chowc** [comment]
是已经导入了client依赖的。
我将apollo.xsd单独抽取出来，然后在IDE中手动指定文件地址，就可以了。

**Comment by nobodyiam** [comment]
应该是不需要这么费力的，通过spring.schemas文件，就可以知道实际的地址了。。。难道你的IDE有啥不同么。。
