### ISSUE TITLE
关于创建部门和被管理的AppId

### ISSUE THREAD

**Issue by bingwenwuhen** [ctripcorp/apollo#790]
创建部门是哪个界面？一直没有找到。
另外就是被管理的AppId是不是就是上面的第三方应用ID？

**Comment by nobodyiam** [comment]
创建部门目前没有界面，请参考[分布式部署指南 - 2.1.3 调整服务端配置](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#213-%E8%B0%83%E6%95%B4%E6%9C%8D%E5%8A%A1%E7%AB%AF%E9%85%8D%E7%BD%AE)操作一下。

被管理的AppId是指你这个open api要操作的配置所属的AppId。比如第三方应用1234，想要操作应用2345的配置。

**Comment by tanhanlin** [comment]
> 创建部门目前没有界面，请参考[分布式部署指南 - 2.1.3 调整服务端配置](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#213-%E8%B0%83%E6%95%B4%E6%9C%8D%E5%8A%A1%E7%AB%AF%E9%85%8D%E7%BD%AE)操作一下。
> 
> 被管理的AppId是指你这个open api要操作的配置所属的AppId。比如第三方应用1234，想要操作应用2345的配置。

要操作的应用有多个怎么办？

**Comment by nobodyiam** [comment]
@tanhanlin 对同一个token多次授权即可
