### ISSUE TITLE
UserInfoController的

### ISSUE THREAD

**Issue by Fanzaijun** [ctripcorp/apollo#794]
@RequestMapping(value = "/users", method = RequestMethod.GET)
  public List<UserInfo> searchUsersByKeyword(@RequestParam(value = "keyword") String keyword,
                                             @RequestParam(value = "offset", defaultValue = "0") int offset,
                                             @RequestParam(value = "limit", defaultValue = "10") int limit) {
问题1：这个获取到的是一个List，前端angularJS获取当前接口的数据可以获取到，但是angularJs的get请求会报错，他解析不了这个。
问题2：这里的分页操作offset不起作用。

**Comment by nobodyiam** [comment]
问题1：get请求会报错，解析不了是啥意思？这个接口在搜索用户的地方会用到，我看了下没有是问题啊？

问题2：貌似SpringSecurityUserService的实现没有考虑offset和limit，这个应该可以改一下。
