### ISSUE TITLE
怎么删除项目

### ISSUE THREAD

**Issue by keven0706** [ctripcorp/apollo#796]
请问在配置中心创建项目后，怎么删除，谢谢！

**Comment by lepdou** [comment]
目前不能删除项目。
一般情况下，不会有删除项目的需求的。只是刚开始搭建阶段，自己创建了很多测试的应用。等到真正上线的时候，直接数据库全清空一下就好了

**Comment by nobodyiam** [comment]
由于删除应用影响面较大，所以现在暂无删除应用功能。

此外，除了appId之外，其它app相关信息都能修改，所以不建议删除app。

如果确实需要删除应用的话，可以参照[5.1 如何删除应用？](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#51-%E5%A6%82%E4%BD%95%E5%88%A0%E9%99%A4%E5%BA%94%E7%94%A8)通过手动执行sql来实现。

**Comment by nobodyiam** [comment]
最新的master版本已经增加了管理员工具页面，可以删除应用、集群和AppNamespace，会在0.11.0版本中发布，相关文档已经更新，可以参考一下。

https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#5-%E5%A6%82%E4%BD%95%E5%88%A0%E9%99%A4%E5%BA%94%E7%94%A8%E9%9B%86%E7%BE%A4namespace

**Comment by teaGod-s** [comment]
> 最新的master版本已经增加了管理员工具页面，可以删除应用、集群和AppNamespace，会在0.11.0版本中发布，相关文档已经更新，可以参考一下。
> 
> https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#5-%E5%A6%82%E4%BD%95%E5%88%A0%E9%99%A4%E5%BA%94%E7%94%A8%E9%9B%86%E7%BE%A4namespace

删除不干净，数据库里还有脏数据，重建同名项目会报错

**Comment by nobodyiam** [comment]
@teaGod-s would you please open a new issue to report the detailed duplication steps and version information?
