### ISSUE TITLE
创建集群异常

### ISSUE THREAD

**Issue by reignsr** [ctripcorp/apollo#799]
同一台机器上部署了configservice，adminservice，portal，数据库、build.sh、apollo-core中的apollo-env.properties里均配置了默认的四个环境dev,fat,uat,pro，登陆并创建项目后，创建集群时出现两个问题：
1、创建集群界面，如果勾选全部环境，则会重复创建集群数据条目，而且页面上会弹出红色框报数据不唯一的异常，试了几次都是如此；
2、创建集群界面，如果仅勾选某一个环境，如pro，创建集群数据正常，但返回到首页，每个环境下方都会出现刚刚添加的集群；（这个问题不知道是不是我的概念有误，我理解是添加集群时勾选哪个环境，则该环境才会有这个集群，其他环境则不会出现该集群。
附件截图供参考。
![inkedclusterdual_li](https://user-images.githubusercontent.com/814702/32095127-abee375a-bb34-11e7-96f5-7cc4a41adc3f.jpg)
![clusterdual-namespace](https://user-images.githubusercontent.com/814702/32094910-f22cfb4e-bb33-11e7-9a11-7721ded5e693.png)
![clusteronlypro](https://user-images.githubusercontent.com/814702/32094913-f2a5eb6c-bb33-11e7-91ab-58cac1699dcf.png)
![clustereveryenv](https://user-images.githubusercontent.com/814702/32094911-f25eccaa-bb33-11e7-85dc-27706c62b930.jpg)

**Comment by reignsr** [comment]
搞清原因了，就是因为只部署了一台机器，四个环境连的都是同一个eureka和同一个数据库，所以向四个环境写数据都写到一个地方了。

**Comment by lepdou** [comment]
@reignsr 

没错~
