### ISSUE TITLE
求问 第一次接触apollo wiki没看懂 普通的spring环境通过apollo管理jdbc

### ISSUE THREAD

**Issue by hjxGit** [ctripcorp/apollo#801]
普通spring java代码 通过pllacehold 配置数据库链接 url name password
如何改造代码支持apollo
以下如何改造呢？？demo没看懂 求高手
【推荐】使用Spring Cloud的RefreshScope
在需要刷新配置的bean上加@RefreshScope
加一个Apollo的ConfigChangeListener，然后在配置变化时调用RefreshScope的refreshAll()或者refresh(String name)的方法。
如果要刷新的不是自己的bean，而是spring cloud的bean，如spring cloud zuul，那么可以调用org.springframework.cloud.context.refresh.ContextRefresher#refresh来刷新配置
相关代码实现，可以参考apollo-demo项目中的AnnotatedBean.java和ApolloRefreshConfig.java
在非Spring Boot环境使用RefreshScope需要引入RefreshAutoConfiguration，引入方式可以参考apollo-demo项目中的相关配置代码：JavaConfig示例，XmlConfig示例

**Comment by hjxGit** [comment]
求帮助

**Comment by nobodyiam** [comment]
看一下[apollo-demo](https://github.com/ctripcorp/apollo/tree/master/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/spring)的相关代码应该就能明白吧。

**Comment by hjxGit** [comment]
原来demo例子 application.properties 新加key 然后可以刷新  新加的a.properties 新key 能扑捉到变化 但是RefreshScope.refresh("**") 查看结果没变

**Comment by nobodyiam** [comment]
refresh("**")是啥意思。。

看一下apollo-demo中的[refresh](https://github.com/ctripcorp/apollo/blob/master/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/spring/springBootDemo/refresh/SpringBootApolloRefreshConfig.java#L33)怎么写的吧。
