### ISSUE TITLE
spring 配置连接池管理 使用properties管理 产生的connection 如何处理？

### ISSUE THREAD

**Issue by hjxGit** [ctripcorp/apollo#802]
1、系统运行 正常连接后。某种原因修改数据库的配置 比如url  那这个是怎么做到实时推送生效？
      还是说人工到服务器重启下应用  
求解？？？

**Comment by nobodyiam** [comment]
参考下 #680

**Comment by hjxGit** [comment]
thank you!

**Comment by nobodyiam** [comment]
我们增加了一个代码示例演示动态切换数据源，可以参考一下：https://github.com/ctripcorp/apollo-use-cases/tree/master/dynamic-datasource
