### ISSUE TITLE
使用logback-spring.xml问题

### ISSUE THREAD

**Issue by miaoyinjun** [ctripcorp/apollo#805]
#apollo创建私有logback-spring，格式选择xml
springBoot项目注解@EnableApolloConfig({"logback-spring.xml"})
目录/opt/data/test/config-cache/下，为什么 是test+default+ logback-spring.xml.properties，请问代码里还能用logback-spring.xml吗

**Comment by nobodyiam** [comment]
xml格式的namespace目前不支持spring注入的

**Comment by miaoyinjun** [comment]
请问xml格式怎么使用，谢谢  @nobodyiam

**Comment by nobodyiam** [comment]
通过ConfigService.getConfigFile获取，可以参考[apollo-demo](https://github.com/ctripcorp/apollo/blob/master/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/api/ApolloConfigDemo.java#L52)

**Comment by miaoyinjun** [comment]
@nobodyiam 我是想把logback-spring.xml也放入apollo，在springBoot中集成这个文件，有什么好的办法吗，谢谢

**Comment by nobodyiam** [comment]
spring boot不认logback-spring.xml的，spring boot认的是logging.level=xxx这样的配置吧

https://docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html

**Comment by miaoyinjun** [comment]
好的，谢谢
