### ISSUE TITLE
为什么configservice和adminservice 要不同环境都部署？？

### ISSUE THREAD

**Issue by tsf2009** [ctripcorp/apollo#806]
为什么configservice和adminservice 要不同环境都部署,就部署一套管理所有环境不可以吗？？还是有其他的考虑。如果部署一套管理所有环境,是不是推荐namespace的方式啊

**Comment by lepdou** [comment]
@tsf2009 

config service和admin service不同环境部署一套主要考虑以下几点：

1. 环境隔离，测试环境不会影响到生产环境
2. 网络隔离，因为大部分公司测试环境是不能访问生产环境的网段。所以，如果只是在生产环境部署一套，那么测试环境就可能出现网络策略问题

第二个问题：如果部署一套管理所有环境，应该怎么做？

可以通过cluster实现。比如只部署在生产环境，那么环境就只有PRO。那么如何区分环境呢？可以通过server.properties中的subenv字段实现。比如subenv=dev，然后在apollo portal上新建一个cluster，名字为dev，那么测试环境就可以读取到dev cluster下面的配置了。
