### ISSUE TITLE
自己的一个xml资源文件 例如a.xml 如何托管有样例不

### ISSUE THREAD

**Issue by hjxGit** [ctripcorp/apollo#809]
我在代码里面需要配置什么或者写什么。
我把properties搞定了 但是xml不会  求帮助

**Comment by nobodyiam** [comment]
xml目前不支持注入spring的，因为spring是k-v的，如果要使用xml的话，得通过API方式，可以参考下[apollo-demo](https://github.com/ctripcorp/apollo/blob/master/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/api/ApolloConfigDemo.java#L52)
