### ISSUE TITLE
请问能否提供apollo-client的开发api

### ISSUE THREAD

**Issue by reignsr** [ctripcorp/apollo#810]
能够开放或提供apollo-client的api文档，目前只是看着demo大概理解，希望详细了解相关注解、方法、事件的意义。

**Comment by nobodyiam** [comment]
客户端对外的接口，如[Config.java](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/Config.java), [ConfigChangeListener.java](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/ConfigChangeListener.java), [EnableApolloConfig.java](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/annotation/EnableApolloConfig.java), [ApolloConfig.java](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/annotation/ApolloConfig.java), [ApolloConfigChangeListener.java](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/annotation/ApolloConfigChangeListener.java)等都有详细的注释的，应该可以看明白吧。一些内部类目前确实注释比较少，可能还是我们比较倾向于让代码自解释，如果有不明白的，可以提出来，或者加Apollo支持群讨论。

**Comment by lepdou** [comment]
@reignsr 
可以看一下这篇文档。https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97

**Comment by reignsr** [comment]
@lepdou 文档之前已经看过了，就是参考文档和demo写了自己应用的实现，获取配置正常。不过还是对某些方法、参数的具体含义存在模糊的地方，我再摸索摸索吧。

**Comment by reignsr** [comment]
@nobodyiam 感谢！
