### ISSUE TITLE
apollo nodejs sdk

### ISSUE THREAD

**Issue by Quinton** [ctripcorp/apollo#811]
https://github.com/Quinton/node-apollo, 大家可以一起参加做贡献。

**Comment by nobodyiam** [comment]
已经更新到[Go、Python、NodeJS等客户端使用指南](https://github.com/ctripcorp/apollo/wiki/Go%E3%80%81Python%E3%80%81NodeJS%E7%AD%89%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)，感谢支持！

**Comment by dishuihengxin** [comment]
@Quinton  我发现修改你源码的一个参数值就可以实现http和https的请求，希望可以尽快更新一个`npm`包。
