### ISSUE TITLE
公共配置命名

### ISSUE THREAD

**Issue by gihubcloner** [ctripcorp/apollo#812]
为什么公共配置要带一个 [创建用户ID] 的前缀？有什么特别的应用场景吗？

**Comment by nobodyiam** [comment]
公共namespace的命名是[部门]的前缀，如FX.apollo。主要是因为公共namespace的名字需要全局唯一，为了方便管理，我们规定了以部门为前缀。

对私有namespace则没有这个限制。

**Comment by gihubcloner** [comment]
好的，非常感谢
