### ISSUE TITLE
apollo-demo 本地没有生成配置文件

### ISSUE THREAD

**Issue by FlankMiao** [ctripcorp/apollo#815]
生成目录为 C:\opt\data\100004458\config-cache

[apollo-demo][Apollo-RemoteConfigRepository-1]2017-11-03 14:36:32,142 WARN  [com.ctrip.framework.apollo.internals.RemoteConfigRepository] Load config failed, will retry in 1 SECONDS. appId: 100004458, cluster: default, namespaces: application
[apollo-demo][Apollo-RemoteConfigRepository-1]2017-11-03 14:36:33,160 WARN  [com.ctrip.framework.apollo.internals.AbstractConfigRepository] Sync config failed, will retry. Repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository, reason: Load Apollo Config failed - appId: 100004458, cluster: default, namespace: application, url: http://192.168.56.1:8080/configs/100004458/default/application?ip=192.168.56.1 [Cause: [status code: 404] Could not find config for namespace - appId: 100004458, cluster: default, namespace: application, please check whether the configs are released in Apollo!]

[apollo-demo][main]2017-11-03 14:51:58,355 WARN  [com.ctrip.framework.apollo.internals.DefaultConfig] Could not load config for namespace application from Apollo, please check whether the configs are released in Apollo! Return default value now!
> [apollo-demo][main]2017-11-03 14:51:58,355 INFO  [com.ctrip.framework.apollo.demo.api.SimpleApolloConfigDemo] Loading key : a with value: undefined

**Comment by nobodyiam** [comment]
[Cause: [status code: 404] Could not find config for namespace - appId: 100004458, cluster: default, namespace: application, please check whether the configs are released in Apollo!]

100004458这个应用的application namespace没有发布过配置。

**Comment by FlankMiao** [comment]
apollo-demo默认有一个私有的namespace：application，已经发布过，但还是不能生成本地配置文件

**Comment by nobodyiam** [comment]
你得看看appid是不是100004458

**Comment by FlankMiao** [comment]
是的，appid=100004455
100004458文件夹和子文件夹config-cache是自动生成的，只是配置文件一直没有

**Comment by nobodyiam** [comment]
这个提示看不懂么。。。没加载到配置啊，所以本地没有文件啊。。。

http://192.168.56.1:8080/configs/100004458/default/application?ip=192.168.56.1 [Cause: [status code: 404] Could not find config for namespace - appId: 100004458, cluster: default, namespace: application, please check whether the configs are released in Apollo!]

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by working-alone** [comment]
什么群

**Comment by SherwinFeng** [comment]
![Uploading image.png…]()
portal页面的这个APP ID需要与项目中app.properties文件中配置的app.id对应上。

**Comment by chenglitao521** [comment]
我也遇到同样的问题，原因是在之前使用过本地开发模式，在C:\opt\settings目录下的server.properties 文件env为local。就不会去服务上拉去配置到本地，所以发布了也找不到，删除这个文件即可
