### ISSUE TITLE
log4j，logback的配置管理

### ISSUE THREAD

**Issue by gihubcloner** [ctripcorp/apollo#816]
您好，请问Apollo是否有管理log4j、logback和log4j2配置的解决方案？
[应用场景] 线上日志等级的调整

**Comment by nobodyiam** [comment]
如果你是用的spring boot的话，对于logging.level和logging.file应该是可以通过Apollo管理的的，不过不确定它是否支持动态调整，可以参考一下下面的文档。

https://docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html

**Comment by LittleShrimp1987** [comment]
log4j2是支持动态调整level的。

`//dynamic change log4j root logger level
        if (changeEvent.isChanged("log.root.level")) {
            ConfigChange configChange = changeEvent.getChange("log.root.level");
            String newLevel = configChange.getNewValue();
            Level level = Level.toLevel(newLevel, Level.WARN);
            LoggerContext context = (LoggerContext) LogManager.getContext(false);
            Configuration conf = context.getConfiguration();

            // change root logger
            conf.getLoggerConfig(LogManager.ROOT_LOGGER_NAME).setLevel(level);
            context.updateLoggers(conf);
        }`

**Comment by nobodyiam** [comment]
如果是spring boot的话，还可以参考下 [通过Apollo动态调整Spring Boot的Logging level](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#7-%E9%80%9A%E8%BF%87apollo%E5%8A%A8%E6%80%81%E8%B0%83%E6%95%B4spring-boot%E7%9A%84logging-level)

**Comment by reignsr** [comment]
同问，不是spring boot的话，log4j、logback之类的日志工具的配置文件如何通过配置中心获取参数？

**Comment by nobodyiam** [comment]
前面 @LittleShrimp1987 贴的示例其实就是普通的log4j2，而不是spring boot吧。

**Comment by nobodyiam** [comment]
我在[apollo-use-cases](https://github.com/ctripcorp/apollo-use-cases)项目中增加了动态刷新日志级别的demo：https://github.com/ctripcorp/apollo-use-cases/tree/master/spring-cloud-logger，可以参考一下。

**Comment by nobodyiam** [comment]
发现一篇文章写得不错，可以参考一下[从Apollo初始化Log4j2的配置](https://blog.csdn.net/u010920692/article/details/80345411)
