### ISSUE TITLE
请问接入自己公司的sso系统，userService是参考携程的来写吗？

### ISSUE THREAD

**Issue by yale2** [ctripcorp/apollo#818]
模拟http请求的方式来实现userService？能否提供一个具体实例？

**Comment by nobodyiam** [comment]
可以参考下[接入公司的统一登录认证系统](https://github.com/ctripcorp/apollo/wiki/Portal-%E5%AE%9E%E7%8E%B0%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95%E5%8A%9F%E8%83%BD#%E5%AE%9E%E7%8E%B0%E6%96%B9%E5%BC%8F%E4%BA%8C-%E6%8E%A5%E5%85%A5%E5%85%AC%E5%8F%B8%E7%9A%84%E7%BB%9F%E4%B8%80%E7%99%BB%E5%BD%95%E8%AE%A4%E8%AF%81%E7%B3%BB%E7%BB%9F)文档说明，按照自己公司实际的情况实现UserService即可，代码可以参考下[ctrip](https://github.com/ctripcorp/apollo/tree/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/ctrip)和[springsecurity](https://github.com/ctripcorp/apollo/tree/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/springsecurity)的实现。

**Comment by yale2** [comment]
持久层用spring jpa，工程跑起来，repository为空，是不是少了什么配置文件






新浪邮箱客户端

------------------------原始邮件------------------------
发件人：Jason Song<notifications@github.com>
时间：2017年11月6日 下午9:47:51
收件人：ctripcorp/apollo<apollo@noreply.github.com>
抄送：Author<author@noreply.github.com>,yale2<xiaolong_ye1@sina.com>
主题：Re: [ctripcorp/apollo] 请问接入自己公司的sso系统，userService是参考携程的来写吗？ (#818)

可以参考下接入公司的统一登录认证系统(https://github.com/ctripcorp/apollo/wiki/Portal-%E5%AE%9E%E7%8E%B0%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95%E5%8A%9F%E8%83%BD#%E5%AE%9E%E7%8E%B0%E6%96%B9%E5%BC%8F%E4%BA%8C-%E6%8E%A5%E5%85%A5%E5%85%AC%E5%8F%B8%E7%9A%84%E7%BB%9F%E4%B8%80%E7%99%BB%E5%BD%95%E8%AE%A4%E8%AF%81%E7%B3%BB%E7%BB%9F)文档说明，按照自己公司实际的情况实现UserService即可，代码可以参考下ctrip(https://github.com/ctripcorp/apollo/tree/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/ctrip)和springsecurity(https://github.com/ctripcorp/apollo/tree/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/springsecurity)的实现。

**Comment by nobodyiam** [comment]
spring data jpa没什么配置文件的，启动时会按照repository中的方法命名来动态生成sql映射

**Comment by yale2** [comment]
没有配置怎么把repository放入spring容器呢？不好意思，没用过spring data jpa ，谢谢你的耐心解答





新浪邮箱客户端

------------------------原始邮件------------------------
发件人：Jason Song<notifications@github.com>
时间：2017年11月6日 下午10:24:29
收件人：ctripcorp/apollo<apollo@noreply.github.com>
抄送：Author<author@noreply.github.com>,yale2<xiaolong_ye1@sina.com>
主题：Re: [ctripcorp/apollo] 请问接入自己公司的sso系统，userService是参考携程的来写吗？ (#818)

spring data jpa没什么配置文件的，启动时会按照repository中的方法命名来动态生成sql映射

**Comment by nobodyiam** [comment]
spring boot启动的时候会扫class的，具体可以参考下 https://docs.spring.io/spring-data/jpa/docs/current/reference/html

**Comment by yale2** [comment]
好的，谢谢





新浪邮箱客户端

------------------------原始邮件------------------------
发件人：Jason Song<notifications@github.com>
时间：2017年11月6日 下午10:49:26
收件人：ctripcorp/apollo<apollo@noreply.github.com>
抄送：Author<author@noreply.github.com>,yale2<xiaolong_ye1@sina.com>
主题：Re: [ctripcorp/apollo] 请问接入自己公司的sso系统，userService是参考携程的来写吗？ (#818)

spring boot启动的时候会扫class的，具体可以参考下https://docs.spring.io/spring-data/jpa/docs/current/reference/html
