### ISSUE TITLE
通知邮件配置

### ISSUE THREAD

**Issue by reignsr** [ctripcorp/apollo#820]
看到官方文档（v0.9.0）中提到了发布和回滚的邮件模板样例，猜测apollo是否提供了邮件通知功能，即发布和回滚动作触发邮件通知？
除了创建用户时给用户指定邮箱，没发现哪里可以配置邮件通知或email服务器之类。我搭的0.9.0版本，是不是我的理解有误？
如果已有邮件通知功能，还望告知如何配置或如何实现？

**Comment by nobodyiam** [comment]
参考下[Portal接入邮件服务](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97#32-portal%E6%8E%A5%E5%85%A5%E9%82%AE%E4%BB%B6%E6%9C%8D%E5%8A%A1)

**Comment by reignsr** [comment]
@nobodyiam 看到了，非常感谢！
