### ISSUE TITLE
apollo有所谓版本的概念？

### ISSUE THREAD

**Issue by huapuyu** [ctripcorp/apollo#825]
我们有一个开发人员联调的docker环境，每个应用打一个镜像，每个应用在实际使用过程中可能会有两个版本，不同的开发人员可以申请这些应用，每个人的配置也需要隔离。现在出现这个情况，比如dev环境下可以通过集群区分不同的开发人员，但是没法体现版本的概念。

例如有个应用A，环境是dev，有两个版本：1.0和1.1，某天，针对1.1版本，张三需要有一套A应用的环境，李四也需要。这种情况不知道apollo有什么好玩法？谢谢！！！

**Comment by lepdou** [comment]
理解了半天，是不是可以这样理解。

一个应用可能有多个版本，每个版本又可能有多份隔离的配置。

你们这个太复杂了，目前apollo是没有好的机制去做这个事情。话说，你们为啥这么复杂，自己能管的过来么？

**Comment by huapuyu** [comment]
是的，类似disconf的版本，我们原来用的disconf，现在换成apollo
我们是每个开发都有一套联调的环境（就是所有模块都打成了docker，联调的时候给这个开发部署一套，disconf也打成了镜像，一起部署，每个人开发的配置中心都是独立的）
现在换成apollo，apollo可以通过portal管理多个环境，还有集群的概念，挺好。
每个开发的一套联调环境部署一个独立的配置中心其实挺麻烦的，我们现在就想用一套apollo管理所有人的环境，但是发现版本这个问题没办法解决，要是类似disconf有个版本的概念就好了

**Comment by nobodyiam** [comment]
这种情况下可以扩展一下集群的概念，通过开发人员+版本来唯一定位一个集群，应该可以实现配置隔离。
不过话说这样的使用的话，管理起来是挺复杂的。

**Comment by huapuyu** [comment]
确实可以这样，但叠加起来太多了，10个开发*2个版本，要配置20个集群，10个开发*3个版本，要配置30个集群，太多了！
