### ISSUE TITLE
本地配置目录可以用参数设置吗？/opt/data/

### ISSUE THREAD

**Issue by lusong1986** [ctripcorp/apollo#826]
本地配置目录位于：
Mac/Linux: /opt/data/{appId}/config-cache
Windows: C:\opt\data\{appId}\config-cache

本地配置目录可以用参数设置吗？

**Comment by nobodyiam** [comment]
这个目前不行，之前考虑的是apollo-client的用户不应该去自定义这个地址，应该是全公司统一的。

不过，这个如果可以允许在maven打包的时候传入的话，会比较好。

**Comment by lusong1986** [comment]
至少留一个systemproperty  供用户来设置。假如用户想用本地的配置，可以设置一个目录来读取。如果想用apollo上的配置，设置另外一个目录，不会互相覆盖。

**Comment by lepdou** [comment]
@lusong1986 

本地开发模式是可以支持。

https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#%E4%BA%94%E6%9C%AC%E5%9C%B0%E5%BC%80%E5%8F%91%E6%A8%A1%E5%BC%8F
