### ISSUE TITLE
关联public namespace失败

### ISSUE THREAD

**Issue by yyguo1986** [ctripcorp/apollo#831]
之前测试，在单机环境下使用0.8.0版本的关联public namespace没有问题。
现在搭建了分布式的环境，改为版本0.9.0, 但关联public namespace显示成功，但实际上并没有关联。是0.9.0版本的bug还是搭建的环境有问题？

**Comment by nobodyiam** [comment]
应该没这个bug的，看下部署是否有啥问题？meta server、数据库连接等。

**Comment by yyguo1986** [comment]
部署了两种环境：dev, fat，portal能显示dev和fat的信息，能查数据库，配置应该没有什么问题啊。
正常的情况下，关联namespace之后，db里Namespace表里的数据要比AppNamespace表的数据多，right?
我查了下config db, 实际要关联的namespace并没有写入库，why?

**Comment by nobodyiam** [comment]
如果操作失败的话，可以看看portal的日志

**Comment by yyguo1986** [comment]
谢谢，找到原因了：namespace格式错误。
