### ISSUE TITLE
配置项Value长度是否可以扩大

### ISSUE THREAD

**Issue by oniza** [ctripcorp/apollo#832]
例如在表ServerConfig中的字段Value定义为varchar(2048)，在项目中配置项的值有可能是一段json内容或者一段长度很长的字符其长度可能超过2048，那么是否可以将字段Value定义为其他类型以便存储超过2048长度的内容？是否会对整个apollo有影响？

**Comment by lepdou** [comment]
现在配置项默认的最大长度是2w个字符。
如果需要调大的话，可以在configdb的serverconfig表，增加一条配置项。
namespace.value.length.limit.override ， Value是json格式，key是Namespace的Id，value是最大字符数{"264":1000000,"600":30000,"616":30000}。

对于apollo最主要的影响是数据量变大了，页面显示可能稍微变慢一点，只要不是特别大，影响是可以忽略的。

**Comment by oniza** [comment]
@lepdou 按照你的意思是在configdb的serverconfig表插入一条数据如以下sql语句，就可以了吗？
INSERT INTO `ServerConfig` (`Key`, `Cluster`, `Value`, `Comment`)
VALUES
    ('namespace.value.length.limit.override', 'default', '25000', '配置项最大长度是2.5w个字符')
这个{"264":1000000,"600":30000,"616":30000}又是指什么呢？
多谢

**Comment by oniza** [comment]
@lepdou 请问如果配置项长度调大，最大可以调到多大呢？

**Comment by lepdou** [comment]
value是一个json，可以针对不同的namespace不同的值。你的例子25000是调整所有namespace最大的值。最大就是数据库的上限了

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
