### ISSUE TITLE
配置项Value在Portal页面中能否显示为json视图

### ISSUE THREAD

**Issue by oniza** [ctripcorp/apollo#833]
项目中配置项的值是一段json，有什么组件或者办法可以让Value显示为json视图

**Comment by lepdou** [comment]
可以的。我刚实现了Namespace是json、yml、xml类型的时候，用对应的编辑器可以编辑。

一个配置项是json或者xml的没有做，这个我也可以搞一下。用的组件是ace，https://github.com/ajaxorg/ace

**Comment by zone1511** [comment]
如何實現不同namespace 用对应的编辑器编辑?

**Comment by nobodyiam** [comment]
目前的版本是根据namespace类型来选择编辑器的，case先关闭了，如还有问题，可以提供更多信息，或进群交流。
