### ISSUE TITLE
为什么private namespace不能被删除？意义是什么？

### ISSUE THREAD

**Issue by lusong1986** [ctripcorp/apollo#834]
为什么private namespace不能被删除？意义是什么？

**Comment by lepdou** [comment]
删肯定是可以删的。主要是删除private namespace，需要删除appnamespace，每个环境都要删，并且权限相关的都要删。删的东西太多了，所以，，，

**Comment by nobodyiam** [comment]
没啥意义，因为在携程private namespace功能没开放，所以没有删除的需求，简而言之，就是这个功能没实现。。

**Comment by IcyLemon** [comment]
不能删除的确不合理。随着项目的迭代，有的namespace需要删除，或者名称起的不规范需要修改。不能删除的话，导致留下很多垃圾namespace。

**Comment by yongxin-pan** [comment]
@lepdou : 
1. 删除namespace没有必要每个环境都删. 不同环境从业务上讲本就是分离的, , 需不需要同步namespace的变更信息是由用户自己决定的. 
2. 权限相关东西是要考虑的, 删的东西多少取决于内部实现.  不过相对环境来讲, 都是轻量级的.

**Comment by nobodyiam** [comment]
目前删除私有Namespace还没有实现，大家如果需要删除的话，可以参考[5.3 如何删除Namespace？](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#53-%E5%A6%82%E4%BD%95%E5%88%A0%E9%99%A4namespace)通过手动执行sql来实现。

**Comment by liutf** [comment]
其实可以不删，前端改造个，做个隐藏就可以了！

**Comment by nobodyiam** [comment]
最新的master版本已经增加了管理员工具页面，可以删除应用、集群和AppNamespace，会在0.11.0版本中发布，相关文档已经更新，可以参考一下。

https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#5-%E5%A6%82%E4%BD%95%E5%88%A0%E9%99%A4%E5%BA%94%E7%94%A8%E9%9B%86%E7%BE%A4namespace

**Comment by nobodyiam** [comment]
另外，最新的master版本已经支持普通用户直接删除private namespace，不过普通用户无法删除AppNamespace，这个需要管理员在管理员工具页面删除。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
