### ISSUE TITLE
在client和configservice断开期间

### ISSUE THREAD

**Issue by LittleShrimp1987** [ctripcorp/apollo#835]
在client和configservice断开期间，有client关心的一个配置发生了几个版本的变化，重新连接后apollo是怎么处理的？

**Comment by lepdou** [comment]
重新连接后，client会向config service发起长连接，长连接会带上客户端所有使用的配置文件的版本号。服务端在处理长连接的时候，先检查一下客户端带过来的文件的版本号是否是最新的，如果落后了，会告诉客户端哪些配置文件版本落后。客户端在收到响应后，会立马跟服务端同步最新的配置。

**Comment by LittleShrimp1987** [comment]
那配置变更事件，只触发一次最新的变更 是吗？
