### ISSUE TITLE
apollo数据库读写有主从方案吗

### ISSUE THREAD

**Issue by LittleShrimp1987** [ctripcorp/apollo#837]
apollo数据库读写有主从方案吗？比如主写，从读

**Comment by lepdou** [comment]
Apollo数据库的压力其实很小的，没必要做读写分离。
当然，如果公司本来就有成熟的读写分离方案，可以接入公司的框架。
如果公司没有统一的读写策略，那么得看一下spring boot如何简单的支持了。
总之，Apollo是不负责处理这一块的。

**Comment by LittleShrimp1987** [comment]
谢谢您的回答。
