### ISSUE TITLE
可否考虑将apollo-client上传至maven官方仓库

### ISSUE THREAD

**Issue by eastfisher** [ctripcorp/apollo#838]
既然apollo-client中的配置项都可以通过JVM参数指定，可否考虑上传通用client？

**Comment by lepdou** [comment]
client主要包含了各个环境的meta地址信息。把meta信息打包进client的好处是，依赖client包的应用就无需指定这个信息了。如果依赖应用通过JVM参数指定，对用户来说成本有点高。
因为打包client也只需要操作一次，所以相对来说成本其实还好。

**Comment by guyaqiongyan** [comment]
可是这样每次Apollo有了新的release之后，都需要去升级client包，并且重新部署一次各个环境的portal等等，也是比较麻烦的事情唉

**Comment by navee** [comment]
meta信息是否应该与项目相关，而不是绑定到client中
例如我们nexus私服是全公司通用，但是test/prod环境网络互相隔离
相信这样的情况也会很多

**Comment by nobodyiam** [comment]
meta信息和项目也没啥关系，可能和环境、机器更相关，后面我们可能会考虑搞个大版本把meta信息和apollo-core解耦。

**Comment by R1310328554** [comment]
我认为应该设置默认值，简化部署。。

**Comment by eagle2016** [comment]
可以用域名。然后可以选择在自己去配置hosts做本地解析。这样client就可以发布到mvn 仓库了。

**Comment by nobodyiam** [comment]
apollo-client已经推送到Maven中央仓库, [点击此链接查看](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.ctrip.framework.apollo%22%20AND%20a%3A%22apollo-client%22)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
