### ISSUE TITLE
先创建一个HELLO.JDBC的公共namespace，为何还允许创建一个私有的同名namespace？

### ISSUE THREAD

**Issue by lusong1986** [ctripcorp/apollo#839]
先创建一个HELLO.JDBC的公共namespace，为何还允许创建一个私有的同名namespace？
这样客户端在使用的时候，读取的是哪里的配置？

**Comment by lepdou** [comment]
不可以创建同名的namespace的，我刚测试过了。

要不你截图看一下？

**Comment by lusong1986** [comment]
![Uploading image.png…]()

我在A项目里面生成一个gongg公共的namespace，我在B项目里面生成一个私有的同名namespace，可以共存。主要还是没有限制同名namespace的存在。

**Comment by nobodyiam** [comment]
私有的和公共的同名是设计上允许的，只有公共的namespace之间才不允许同名，因为那个是全局共享的，私有的只影响app自己。
