### ISSUE TITLE
部门也可以预留出接口

### ISSUE THREAD

**Issue by LittleShrimp1987** [ctripcorp/apollo#840]
和获取用户获预留的接口类似。部门获取也可以预留接口。
另外获取用户接口可以传入部门id

**Comment by lepdou** [comment]
部门信息，因为相对来说是属于“静态”信息，变更较少，所以直接配置在数据库里比较简单。
当然，如果公司内部，比如通过调用专门的服务来获取部门信息的话，自己改造一下也是比较容易的。
--------
获取用户接口传入部门id的目的是啥？是通过部门来搜索用户吗？这个场景很少吧？

**Comment by LittleShrimp1987** [comment]
嗯，改造是挺容易的，但是就不是以扩展的方式，而是改动源码，还是不一样的，后续升级维护啥的不是很方便。

目的就是您说的，还是有这种场景的，选了部门之后，再选用户就可以只显示这个部门的用户，而不用显示不想关的用户。

都是很小的问题，现在已经很好用了
