### ISSUE TITLE
先创建一个public namespace，然后portal页面上删除掉，再重新创建这个namespace，发现不能创建，提示以及存在了。

### ISSUE THREAD

**Issue by lusong1986** [ctripcorp/apollo#842]
先创建一个public namespace，然后portal页面上删除掉，再重新创建这个namespace，发现不能创建，提示以及存在了。
查看数据库发现，删掉掉后，config和portal库中appnamespace表中，这个namespace的isdelete字段还是0

**Comment by nobodyiam** [comment]
删除的是关联的namespace，具体而言，就是config表中的namespace实体。appnamespace实体目前还没有删除功能。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by nobodyiam** [comment]
最新的master版本已经增加了管理员工具页面，可以删除应用、集群和AppNamespace，会在0.11.0版本中发布，相关文档已经更新，可以参考一下。

https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#5-%E5%A6%82%E4%BD%95%E5%88%A0%E9%99%A4%E5%BA%94%E7%94%A8%E9%9B%86%E7%BE%A4namespace
