### ISSUE TITLE
config的appnamespace表和namespace表有什么区别？如果用api创建namespace时使用哪一类接口？

### ISSUE THREAD

**Issue by lusong1986** [ctripcorp/apollo#843]
config的appnamespace表和namespace表有什么区别？
如果用api创建namespace时使用哪一类接口？
appnamespace的还是namespace的？

**Comment by nobodyiam** [comment]
appnamespace是元信息，类似于class，namespace是实际关联在cluster上的，类似于instance。

具体可以看[E-R图](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1#14-e-r-diagram)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by wwcoding** [comment]
请问为什么要加appNameSpace这一层，没太明天它是起什么作用的。
虽然看到了appnamespace是元信息，，类似于class，namespace是实际关联在cluster上的，类似于instance。但是为啥不直接使用cluster和namespace？？

**Comment by why444216978** [comment]
我理解 namespace 表就是关联公共 namespace 的关联表，就像我们设计数据表结构时的实体表和关联表一样，实体表存储所有原数据，关联表只需要存储关联的唯一 key 就好。
