### ISSUE TITLE
apollo app id生成方案

### ISSUE THREAD

**Issue by LittleShrimp1987** [ctripcorp/apollo#847]
apollo里用的appid，携程使用的生成方案能透露吗？

appid如果是有规律的，是有安全隐患，因为任何引用apollo-client包的程序都可以随意修改appid来获取到配置；

如果appid是无规律的，比如guid，我看配置查询都依赖appid查询，并且用appid建了不少索引，这样应该是有一些性能影响。

**Comment by lepdou** [comment]
携程的AppId就是普通的数据库Id自增长。
如果从AppId生成的策略来防止配置被别人读取的话，有一定的作用，相当于token了，如果要做，portal也要做查看权限。
但是AppId一般是用来作为项目的标识，各个系统都要用。基本都是公开的，比如日志监控，他不涉及权限问题，所以appId都是直接公开的。
所以appId很难做成一个不公开的字符串。

至于索引性能问题，是没关系的。只要你的字符串相似度越低，索引的性能越高。而且，apollo的表数据量都很少，不用考虑

**Comment by LittleShrimp1987** [comment]
portal加上查看权限，这块你们这边有考虑过做吗？

**Comment by yicone** [comment]
偶然看到这个历史问题，也说下个人想到的一些角度。
1，一般不会允许apollo这样的配置服务暴露到外网去
2，若安全要求更高，防止无权限的内部人员，通过apollo-client访问到配置内容，
首先是要将配置中的敏感内容，不明文存放，如数据库密码（密钥存放于Vault之类的服务）；
其次是网络隔离，办公网络或透过VPN，都不应被允许连接到apollo server。

**Comment by nobodyiam** [comment]
@yicone 是的，我们也整理了相关说明 - [Apollo安全相关最佳实践](https://github.com/ctripcorp/apollo/wiki/Apollo%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#71-%E5%AE%89%E5%85%A8%E7%9B%B8%E5%85%B3)
