### ISSUE TITLE
如何在项目中保留properties配置文件，并且properties中有随着环境变化的变量，这些变量的值从Apollo配置中心获取

### ISSUE THREAD

**Issue by rabbitgyk** [ctripcorp/apollo#856]
apollo中提供的方式是，将本地properties文件删除，全部迁移到配置中心，而如果properties配置文件是某个jar包依赖的配置文件不能删除怎么破

**Comment by nobodyiam** [comment]
这也是可以的，没啥关系。

你可以简单的把Apollo认为是一个一定会加载，且放在spring层级最前面的properties文件，所以使用上没有啥变化的。

**Comment by rabbitgyk** [comment]
在某个jar包中有这么一段代码：
public class PropertiesUtil {
	private static Properties properties;
	
	private static final String propFile="convepay.properties";
	
	static{
		try {
			properties=new Properties();
			InputStream fileStream = PropertiesUtil.class.getClassLoader().getResourceAsStream(propFile);
			properties.load(fileStream);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	
	public static String getValue(String key){
		try {
			return properties.get(key).toString();
		} catch (NullPointerException e) {
			return null;
		}
	}
}

他指定加载了我的classpath下面的convepay.properties配置文件，我现在要把这个配置文件中的配置放到apollo配置中心中，如何能在不修改jar包的情况下，将配置成功迁移到Apollo配置中心？

**Comment by nobodyiam** [comment]
如果你真要这么干的话，那只能先从Apollo获取配置，然后写到classpath下的文件了。

建议把这个jar包改个新版本吧，不然逻辑绕来绕去容易犯错

**Comment by rabbitgyk** [comment]
OK，多谢回答
