### ISSUE TITLE
portal上所有人都能看到所有配置，后面会考虑做查看权限吗？

### ISSUE THREAD

**Issue by LittleShrimp1987** [ctripcorp/apollo#857]

**Comment by nobodyiam** [comment]
初步设想是portal增加配置，允许针对特定环境，只允许项目成员访问

如果你这边有余力的话，也欢迎贡献代码~

**Comment by guyaqiongyan** [comment]
这个大概排期在哪个release版本中呢 @nobodyiam 谢谢

**Comment by nobodyiam** [comment]
#1531 支持设置某个环境的配置只能被项目成员看到，非项目成员无法查看，可以看一下

**Comment by nobodyiam** [comment]
1.1.0版本已经发布，包含了查看权限控制功能，更多信息可以参考： https://github.com/ctripcorp/apollo/releases/tag/v1.1.0
