### ISSUE TITLE
如何获取整个xml 或json 文档

### ISSUE THREAD

**Issue by ifmeelse** [ctripcorp/apollo#859]
好像没见到相关啊api 啊

**Comment by nobodyiam** [comment]
public static ConfigFile getConfigFile(String namespace, ConfigFileFormat configFileFormat)

可以参考下[apollo-demo](https://github.com/ctripcorp/apollo/blob/master/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/api/ApolloConfigDemo.java#L52)
