### ISSUE TITLE
实例列表一直有实例存在，什么情况会发生，是个bug吧

### ISSUE THREAD

**Issue by lusong1986** [ctripcorp/apollo#861]
我的项目随机启停了几次之后，发现实例列表里面一直有实例存在，清空不了，这是怎么回事？是不是bug？看图

![qq 20171204114132](https://user-images.githubusercontent.com/9333427/33535404-519c860e-d8e8-11e7-8630-0cb8beb286e9.png)

**Comment by lusong1986** [comment]
程序停了几天了 还在实例列表

**Comment by nobodyiam** [comment]
代码里面每次展示的就是最近24小时之内和服务端连接过的客户端，你可以看下InstanceConfig中的DataChange_LastTime是否是最近24小时内更新的。

代码：[getValidInstanceConfigDate](https://github.com/ctripcorp/apollo/blob/master/apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/service/InstanceService.java#L146)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
