### ISSUE TITLE
如果是第一次启动，可以从其它机器上获取已缓存的配置文件。

### ISSUE THREAD

**Issue by huapuyu** [ctripcorp/apollo#864]
查看设计文档，其中有如下描述
![image](https://user-images.githubusercontent.com/703882/33543135-d4965a8a-d910-11e7-8cdb-6b123be53e85.png)
可以从其他机器同步配置？
我做了实验，没有成功，不知道怎么理解这句话，麻烦给些指导，谢谢！

**Comment by nobodyiam** [comment]
请参考下 [1.2.3 本地缓存路径](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#123-%E6%9C%AC%E5%9C%B0%E7%BC%93%E5%AD%98%E8%B7%AF%E5%BE%84)

**Comment by huapuyu** [comment]
ok，就是要手工从有缓存文件的机器上复制过来，我以为是自动会从其他机器复制，还在思考这是怎么实现的。
