### ISSUE TITLE
client端运行在docker容器里 无法访问/opt/logs/ 和 /opt/settings/server.propertie

### ISSUE THREAD

**Issue by desslee** [ctripcorp/apollo#866]
client端运行在docker容器的时候 无法访问/opt/logs/ 和 /opt/settings/server.propertie
这种情况一般怎么处理

**Comment by lepdou** [comment]
是因为权限不够吗？

**Comment by desslee** [comment]
是需要先挂载一个目录吗

**Comment by nobodyiam** [comment]
建议挂在一个，以便持久化。
不挂载的话，得确保程序有权限创建/opt目录

**Comment by desslee** [comment]
我把logback的配置文件这句注释掉了还是会访问去/opt/logs/xxx/xxx.log文件
```<appender-ref ref="FILE" />```
怎么配置才能不去写日志到文件呢？

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
