### ISSUE TITLE
请问0.9.1-SNAPSHOT版本较0.9.0的变化

### ISSUE THREAD

**Issue by reignsr** [ctripcorp/apollo#868]
看到源码pom中版本已经变为0.9.1-SNAPSHOT，但是没有看到release note中有关于0.9.1-SNAPSHOT的描述，请问较0.9.0版本的变化是什么？
另，我们已经部署了0.9.0版本，并且已经有真实数据了，如果升级（尤其后续大版本升级，比如1.0），涉及到数据结构变化，官方是否会有历史数据迁移的支持？

**Comment by lepdou** [comment]
0.9.1-SNAPSHOT是master上的版本，还没有发布，release note只会有正式发布版的信息。
后续版本基本上都是小修小补，不会有大的模型上的改动，所以应该不会涉及到数据迁移的事情。

**Comment by nobodyiam** [comment]
每次升级如果有schema变化的话，都会提供delta schema的。而且我们一般会保证兼容老版本的数据的，自0.5.0开始还没有出现过必须要数据迁移的事情。
