### ISSUE TITLE
打包时是否可以不配置数据库地址，不把数据库地址打在jar包中，而在打包后的配置文件中配置？

### ISSUE THREAD

**Issue by lusong1986** [ctripcorp/apollo#869]
使用build.sh 打包时是否可以不配置数据库地址，不把数据库地址打在jar包中，而在打包后的配置文件中配置？

**Comment by lepdou** [comment]
你试一下，改启动脚本scripts/startup.sh 

在export JAVA_OPTS=""这一行加入几个参数，
-Dspring.datasource.url=,-Dspring.datasource.username=,-Dspring.datasource.password=

**Comment by nobodyiam** [comment]
可以的，通过-D是一种方式，另一种方式是把[application-github.properties](https://github.com/ctripcorp/apollo/blob/master/apollo-common/src/main/resources/application-github.properties)放在和apollo服务端jar包同级目录或config子目录。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by nobodyiam** [comment]
@sunnyvinson meta server也是一样的，apollo-env.properties也可以使用同样的方式外置化。

**Comment by nobodyiam** [comment]
分布式部署文档已经更新，可以参照[2.2.1 直接下载安装包](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#221-%E7%9B%B4%E6%8E%A5%E4%B8%8B%E8%BD%BD%E5%AE%89%E8%A3%85%E5%8C%85)文档直接下载预先打好的安装包，实际部署时只需要修改application-github.properties和apollo-env.properties即可。

**Comment by vincentcui** [comment]
我觉得可以一次把不同环境的application-*.yml(*代表各环境，如dev,fat,pro)打到包里，通过--spring.profiles.active的启动参数来控制选择加载哪一个环境的配置？

**Comment by nobodyiam** [comment]
也是一种方式，不过大家一般都喜欢外部化配置了，所以不太喜欢把配置打到包里面

**Comment by qmwu2000** [comment]
如果配置文件中有敏感信息，则会有安全隐患。


发自我的 iPhone

**Comment by jiash** [comment]
您好:目前三个工程配置分离,配置文件是放在config文件夹下了,但是如果想把配置文件放在其他的地方,应该怎么修改启动脚本呢?

**Comment by nobodyiam** [comment]
@jiash  可以参考一下spring boot的[说明](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-application-property-files)

**Comment by luojieio** [comment]
启动时-D和配置文件和编译时带的参数和数据库的配置，优先级是如何的呢？

**Comment by nobodyiam** [comment]
@luojieio 可以参考一下spring boot的[说明](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-application-property-files)
