### ISSUE TITLE
apollo-configservice无法注册到eureka

### ISSUE THREAD

**Issue by gaoxianrui52** [ctripcorp/apollo#870]
我在一台测试机器起来apollo-adminservice,apollo-configservice,apollo-portal.已经正常启动了，打开apolloapollo-configservice页面，看到registered-replicas和unavailable-replicas这两个都是我构建填的url。那么是不是注册到eureka失败了呢？帖一段apollo-configservice的日志。没其他特别的日志。

> 2017-12-06 19:39:47.717  INFO 6404 --- [AsyncResolver-bootstrap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-12-06 19:39:57.078  INFO 6404 --- [Eureka-EvictionTimer] c.n.e.registry.AbstractInstanceRegistry  : Running the evict task with compensationTime 0ms

**Comment by lepdou** [comment]
这两个有值说明是对的。
主要看Instances currently registered with Eureka这里，config service和admin service有没有注册上来

**Comment by gaoxianrui52** [comment]
好的，谢谢。两个状态都是up。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
