### ISSUE TITLE
无法删除公共的namespace

### ISSUE THREAD

**Issue by changealice** [ctripcorp/apollo#871]
apollo portal A项目上新建了一个公共的namespace  名称为:
   PUBLIC.demo
关联了B,C 二个项目。
   目前发现在A项目上删除 PUBLIC.demo提示   需要先删除B,C。 
  我按照提示的做了，先删除了B和C ，然后成功删除了A ，发现问题如下：
  在A项目添加NameSpace 列表中还有PUBLIC.demo。
这个是为什么 ？
数据库发现还在。

另外发现在PUBLIC.demo的namespace增删改还在在A项目。这个有点无法接受。

**Comment by nobodyiam** [comment]
因为目前删除的namespace是namespace实例，不是namespace的meta信息，也就是appnamespace表目前是不删的。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by nobodyiam** [comment]
最新的master版本已经增加了管理员工具页面，可以删除应用、集群和AppNamespace，会在0.11.0版本中发布，相关文档已经更新，可以参考一下。

https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#5-%E5%A6%82%E4%BD%95%E5%88%A0%E9%99%A4%E5%BA%94%E7%94%A8%E9%9B%86%E7%BE%A4namespace

**Comment by czhangzjut** [comment]
日志文件（eg:log4j2.xml）放到apollo的一个namespace上，项目中怎么读取到？
