### ISSUE TITLE
apollo支持创建多个用户，每个用户只能管理自己创建的Project？

### ISSUE THREAD

**Issue by oniza** [ctripcorp/apollo#872]
如题，是否支持每个用户只能管理自己的Project？

**Comment by nobodyiam** [comment]
可以的，每个项目有管理员权限，管理员可以管理这个项目，赋予其他用户各种权限，如项目管理权限，namespace的编辑和发布权限。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
