### ISSUE TITLE
是否只有负责人才能看到项目？

### ISSUE THREAD

**Issue by onethin** [ctripcorp/apollo#878]
用apollo用户建立了一个应用，并且把用户b添加到管理员，也赋值了修改和发布权限，但是用户b登录看不到这个应用，只有把应用的负责人改成b后，b登录后能看到这应用，但是apollo用户就看不到这个应用了，看现象是只有应用的负责人才能看到对应的应用。
最新的0.9.1版本

**Comment by nobodyiam** [comment]
首页默认展示自己的项目，在搜索框中可以搜索看到其它项目，也可以收藏其它项目。

**Comment by wysun003** [comment]
发现一个问题，apollo建立一个应用t，把b添加到管理员，b可以搜索到t，但是b也可以修改项目负责人啊

**Comment by nobodyiam** [comment]
项目管理员是可以修改项目信息的

**Comment by huzhou520** [comment]
还有对接ldap之后，默认的项目管理员apollo用户就登录不上去了，导致我没有项目管理员权限的账户了
