### ISSUE TITLE
Can i get the source code of textarea editor by ace framework?

### ISSUE THREAD

**Issue by ccl0326** [ctripcorp/apollo#879]
ping @lepdou 
3ks~

**Comment by lepdou** [comment]
@ccl0326 
你的意思是，用ace 代码编辑器来展示和编辑文本？
这个在最新的master分支上已经支持了，还没打release tag。

**Comment by nobodyiam** [comment]
@ccl0326 [v0.9.1](https://github.com/ctripcorp/apollo/releases/tag/v0.9.1)已经release了，包含了ace编辑器的功能，如果要看ace编辑器的源码，直接google就可以了吧。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
