### ISSUE TITLE
当天有实例Namespace如何删除？

### ISSUE THREAD

**Issue by jxplus** [ctripcorp/apollo#889]
如标题

**Comment by lepdou** [comment]
目前比较蛋疼，只能到数据库里把实例数据删除，如何在页面上操作删除。后面可以搞一个强制删除的功能。

**Comment by jxplus** [comment]
看代码看懂了，等待他升级吧。

**Comment by nobodyiam** [comment]
最新的master版本已经增加了管理员工具页面，可以删除应用、集群和AppNamespace，会在0.11.0版本中发布，相关文档已经更新，可以参考一下。

https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#5-%E5%A6%82%E4%BD%95%E5%88%A0%E9%99%A4%E5%BA%94%E7%94%A8%E9%9B%86%E7%BE%A4namespace
