### ISSUE TITLE
代码如何修改apollo的值

### ISSUE THREAD

**Issue by changealice** [ctripcorp/apollo#892]
java api方式动态修改已经配置好的值，看了下有openapi的方式，需要做 修改配置 + 发布二个接口吗 ？

有没有更便捷的方式，

另外openapi做的修改与发布是否可以被其他带有ApolloConfigChangeListener 客户端感知到 ？

**Comment by nobodyiam** [comment]
open api提供了修改配置和发布两个接口，至于接入open api后是分成两步还是一步，可以由你们自己决定。

open api做的修改和发布，等同于用户在portal做修改和发布，所以客户端也是会感知到变化的。

**Comment by changealice** [comment]
@nobodyiam 测试下来如你所说。
