### ISSUE TITLE
有没有不配置opt\settings\server.propertie就可以使用的方法呢

### ISSUE THREAD

**Issue by sangjie** [ctripcorp/apollo#900]
给第三方用，感觉让人配置的比较麻烦

**Comment by lepdou** [comment]
可以通过系统启动的时候，加系统参数-Denv=xxx的方式

**Comment by lijasonvip** [comment]
您好，我们在使用的时候发现env和data_center只有以下三种方式：
(1) JVM system property 'env'
(2) OS env variable 'ENV' nor 
(3) property 'env' from the properties InputStream.
因为我想在我们的框架中对接apollo, 想把这两个配置项集成到我们的配置文件中，有什么方法吗？配置文件opt\settings\server.propertie可以自定义吗路径和文件名吗？

谢谢！

**Comment by nobodyiam** [comment]
我们的设计理念是env是机器的属性，不是代码的属性，所以这个配置不跟着代码走。

如果你们的场景需要读取自己的配置文件的话，可以修改下代码 [DefaultServerProvider. initEnvType](https://github.com/ctripcorp/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/foundation/internals/provider/DefaultServerProvider.java#L106)

**Comment by LittleShrimp1987** [comment]
springboot项目可以在 main函数里增加一段env设置的逻辑，这样可以免掉配置文件。

**Comment by R1310328554** [comment]
框架写得不错，但是过于复杂了，部署起来确实不太友好。 我于是通过修改源码方式，给env 和 app.id 设置了默认值，就可以不用 server.properties 以及 app.properties。
linsage 可以考虑把 namespace 作为env 来用。。

**Comment by lepdou** [comment]
@LittleShrimp1987 
在代码里没法设置env值的，因为一旦代码打成包了，代码就不能动态变更。一个包可以在多个环境下运行，所以这种方式是不行的。要么就是通过-D参数，在启动的时候指定。

**Comment by lepdou** [comment]
@R1310328554 R
如果给env和app.id设置了默认值，那么公司内所有的应用的配置都在同一个应用下管理？
namespace怎么作为env来用？具体设计是怎么样的？

**Comment by zuoyixiao** [comment]
可以通过集群idc来区分环境

**Comment by nobodyiam** [comment]
最新版本的apollo-client已经不再强制要求配置env了，不过apollo的meta server信息还是需要提供的，可以参考一下 [1.2.2 Apollo Meta Server](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#122-apollo-meta-server)，另外，从1.0.0版本开始，可以直接使用Maven中央仓库的apollo-client了。

case先关闭了，如还有问题，可以提供更多信息，或进群交流。
