### ISSUE TITLE
@ConditionalOnProperty 获取不到配置

### ISSUE THREAD

**Issue by Laggar** [ctripcorp/apollo#903]
使用@ConditionalOnProperty 配置bean时，获取不到配置中心的配置

**Comment by nobodyiam** [comment]
有具体case吗？

**Comment by Laggar** [comment]
直接在classpath下放置配置是没问题的，使用配置中心不行。
@conditionalonproperty  貌似在 配置中心获取配置前就已经初始化了

@Configuration
@EnableApolloConfig({ "application.properties"})
public class ConfigCenterConfig {
    
}


    @Bean
    @ConditionalOnProperty(prefix = EcisProperties.PREFIX, name = "spring-session-open", havingValue = "false")
    public DefaultWebSessionManager defaultWebSessionManager(CacheManager cacheShiroManager, EcisProperties gunsProperties) {
        DefaultWebSessionManager sessionManager = new DefaultWebSessionManager();
        sessionManager.setCacheManager(cacheShiroManager);
        sessionManager.setSessionValidationInterval(gunsProperties.getSessionValidationInterval() * 1000);
        sessionManager.setGlobalSessionTimeout(gunsProperties.getSessionInvalidateTime() * 1000);
        sessionManager.setDeleteInvalidSessions(true);
        sessionManager.setSessionValidationSchedulerEnabled(true);
        Cookie cookie = new SimpleCookie(ShiroHttpSession.DEFAULT_SESSION_ID_NAME);
        cookie.setName("shiroCookie");
        cookie.setHttpOnly(true);
        sessionManager.setSessionIdCookie(cookie);
        return sessionManager;
    }

  @Bean
    public DefaultWebSecurityManager securityManager(CookieRememberMeManager rememberMeManager, CacheManager cacheShiroManager, SessionManager sessionManager) {
        DefaultWebSecurityManager securityManager = new DefaultWebSecurityManager();
        securityManager.setRealm(this.shiroDbRealm());
        securityManager.setCacheManager(cacheShiroManager);
        securityManager.setRememberMeManager(rememberMeManager);
        securityManager.setSessionManager(sessionManager);
        return securityManager;
    }


Description:

The dependencies of some of the beans in the application context form a cycle:

   webConfig (field private com.fengunion.ecis.config.properties.EcisProperties com.fengunion.ecis.config.web.WebConfig.ecisProperties)
      ↓
   shiroFilter defined in class path resource [com/fengunion/ecis/config/web/ShiroConfig.class]
      ↓
   methodInvokingFactoryBean defined in class path resource [com/fengunion/ecis/config/web/ShiroConfig.class]
┌─────┐
|  securityManager defined in class path resource [com/fengunion/ecis/config/web/ShiroConfig.class]
└─────┘

**Comment by Laggar** [comment]
@ConditionalOnProperty (ecis.swagger-open=true) did not find property 'swagger-open'
使用配置文件是没问题的，用配置中心出现的

**Comment by nobodyiam** [comment]
多谢，我们后面看一下。

**Comment by nobodyiam** [comment]
@Laggar 

感谢 @tastypinenut 提供Pull Request，目前已经支持在启动阶段注入配置，从而可以很好地支持`@ConditionalOnProperty`的场景，使用说明可以参考 [3.2.1.3 在Spring Boot初始bootstrap阶段注入配置](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#3213-%E5%9C%A8spring-boot%E5%88%9D%E5%A7%8Bbootstrap%E9%98%B6%E6%AE%B5%E6%B3%A8%E5%85%A5%E9%85%8D%E7%BD%AE)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by jim2017jim** [comment]
还是不行

**Comment by nobodyiam** [comment]
照着 [3.2.1.3 在Spring Boot初始bootstrap阶段注入配置](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#3213-%E5%9C%A8spring-boot%E5%88%9D%E5%A7%8Bbootstrap%E9%98%B6%E6%AE%B5%E6%B3%A8%E5%85%A5%E9%85%8D%E7%BD%AE) 应该是没问题的

**Comment by yuyujulin** [comment]
还是不行啊，springboot 2.1.1 + apollo client .1.1.0 已经加了 apollo.bootstrap.enabled = true 和

**Comment by xiebin2015** [comment]
这个问题解决了吗，我也遇到了  ，需要有些根据条件来加载bean的需求，但是读取不到
