### ISSUE TITLE
能否增加配置生效策略的逻辑

### ISSUE THREAD

**Issue by wendaoheri** [ctripcorp/apollo#904]
我现在想把apollo改造成可以应用于手机客户端的配置获取，所以能否增加一层配置生效策略的逻辑。
类似于灰度策略，不同的ip可以拿到不同的配置，那么如果在不同的时间、不同的APP版本、不同的设备平台是否也可以拿到不同的配置。
这些无非都是一个match的过程，根据不同的策略match到不同的配置。
```
public boolean matches(String clientAppId, String clientIp) {
    for (GrayReleaseRuleItemDTO ruleItem : ruleItems) {
      if (ruleItem.matches(clientAppId, clientIp)) {
        return true;
      }
    }
    return false;
  }
```
多谢

**Comment by nobodyiam** [comment]
这个对于配置中心略显复杂了，可以借用集群的模型在外面封装一个API用于提供手机端的配置。

比如不同的app版本可以作为集群的名字。

**Comment by wendaoheri** [comment]
你好，我也确实是要在外面加一层API，把Apollo当做数据源和配置同步引擎，但是Apollo本身并不支持复杂策略，如果只是把Apollo当做配置存储来用的话，个人觉得还不如直接用db。
我们这边服务端已经开始规划使用Apollo，然后我是想客户端的配置读取如果也可以使用的话就会方便很多，毕竟我不需要再实现一遍配置的同步、版本管理、回退等功能。
我想既然灰度是一种策略，那其他类型的生效机制也是一种策略，可以不用实现具体的策略，但是是否可以抽象一个策略的接口，让使用者可以自己定制化开发？
谢谢

**Comment by lijasonvip** [comment]
@nobodyiam 
您好，我们在使用的时候发现env和data_center只有以下三种方式：
(1) JVM system property 'env'
(2) OS env variable 'ENV' nor
(3) property 'env' from the properties InputStream.
因为我想在我们的框架中对接apollo, 想把这两个配置项集成到我们的配置文件中，有什么方法吗？配置文件opt\settings\server.propertie可以自定义吗路径和文件名吗？

谢谢！

**Comment by lepdou** [comment]
@wendaoheri 
配置中心建议不要直接暴露到C端用户。因为客户端都会跟服务端建立一个长连接用来监听配置变更。如果直接把接口暴露到C端，连接数将会很大。
配置中心更多的是作为内网应用的基础服务，暴露到C端最好是有一层API层，或者网关层统一控制出口。对于你提到的接口的逻辑，其实是可以在网关层做的。

**Comment by wendaoheri** [comment]
@lepdou 嗯，了解，肯定不会直接暴露给C端的，我试试如果只包装接口是否可以，多谢

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
