### ISSUE TITLE
在内网使用时登陆页面太慢

### ISSUE THREAD

**Issue by zhangyg3** [ctripcorp/apollo#907]
1、portal中的login.html登录页面，含有外网css样式连接 @import url(https://fonts.googleapis.com/css?family=Roboto:400,300,100,700,500);由于服务都部在内网中，与外网不通，这样访问外网的css样式请求（此css样式里面又有5个外网字体请求）会卡，导致登录页面展示非常慢。建议直接把css与此css引用的5个字体文件下载下来，进行内部 引 用

2、portal中的resources/static/scripts/controller/config/ConfigBaseInfoController.js文件，226行－229行建议去掉。
      因为：如果一个appId下面有多个集群时，默认展示的为default集群，当另一个集群中即有发布的配置，也有未发布的配置时，这时点击另一个集群，后台会报如下异常（报出的异常没有apollo的代码，全是tomcat和spring的代码），只在服务启动后第一次点击集群时才会报异常：
ERROR 7592 --- [io-48300-exec-9]  .c.f.a.c.c.GlobalDefaultExceptionHandler : java.io.IOException: 您的主机中的软件中止了一个已建立的连接。
org.apache.catalina.connector.ClientAbortException: java.io.IOException: 您的主机中的软件中止了一个已建立的连接。
at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:396)
---------
有时也会报
ERROR 8040 --- [io-48300-exec-7] s.r.c.c.c.GlobalDefaultExceptionHandler  : java.io.IOException: 远程主机强迫关闭了一个现有的连接。
org.apache.catalina.connector.ClientAbortException: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:396)
经过抓包分析，发现点击集群时，提交了两次请求（一次是windwos.location.href，一次通过angularjs事件emit/subscribe里面提交的），第一次提交的请求异常(status显示IO_PENDING)。

**Comment by zhangyg3** [comment]
格式有点乱，重新编辑下：
1、如果不是properties文件 name = ${appId所属的部门}.${传入的name值}.${format}，例如调用接口传入的name=xy-z, format=json，应用的部门为框架（FX）,那么name=FX.xy-z.json.
此接口即使不是properties文件，也不能带扩展名，因为Crotroller类里面有校验。否者会报如下错误：{"exception":"studio.raptor.cmdb.common.exception.BadRequestException","message":"Namespace格式错误: 只允许输入数字，字母和符号 - _ . \u0026 不允许以.json, .yml, .yaml, .xml, .properties结尾","status":400,"timestamp":"2018-01-03T14:46:29.987"}

2、portal中的login.html登录页面，含有外网css样式连接 @import url(https://fonts.googleapis.com/css?family=Roboto:400,300,100,700,500);由于服务都部在内网中，与外网不通，这样访问外网的css样式请求（此css样式里面又有5个外网字体请求）会卡，导致登录页面展示非常慢。建议直接把css与此css引用的5个字体文件下载下来，进行内部引用。
例如：<link rel="stylesheet" href="vendor/googleapis/googleapis.css">

3、portal中的resources/static/scripts/controller/config/ConfigBaseInfoController.js文件，226行－229行建议去掉。
      因为：如果一个appId下面有多个集群时，默认展示的为default集群，当另一个集群中即有发布的配置，也有未发布的配置时，这时点击另一个集群，后台会报如下异常（报出的异常没有apollo的代码，全是tomcat和spring的代码），只在服务启动后第一次点击集群时才会报异常：
ERROR 7592 --- [io-48300-exec-9]  .c.f.a.c.c.GlobalDefaultExceptionHandler : java.io.IOException: 您的主机中的软件中止了一个已建立的连接。
org.apache.catalina.connector.ClientAbortException: java.io.IOException: 您的主机中的软件中止了一个已建立的连接。
at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:396)
---------
有时也会报
ERROR 8040 --- [io-48300-exec-7] s.r.c.c.c.GlobalDefaultExceptionHandler  : java.io.IOException: 远程主机强迫关闭了一个现有的连接。
org.apache.catalina.connector.ClientAbortException: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:396)
经过抓包分析，发现点击集群时，提交了两次请求（一次是windwos.location.href，一次通过angularjs事件emit/subscribe里面提交的），第一次提交的请求异常(status显示IO_PENDING)。

**Comment by zhangyg3** [comment]
<link rel="stylesheet" href="vendor/googleapis/googleapis.css">

**Comment by zhangyg3** [comment]
link rel="stylesheet" href="vendor/googleapis/googleapis.css"

**Comment by nobodyiam** [comment]
@zhangyg3 多谢反馈！对于第一点，是否能帮忙提个PR？

@lepdou 对于第二点，能帮忙看下吗？

**Comment by nobodyiam** [comment]
#1723 已经把google font去除了

**Comment by nobodyiam** [comment]
[1.2.0](https://github.com/ctripcorp/apollo/releases/tag/v1.2.0)版本已经发布，去除了google font
