### ISSUE TITLE
About start.sh problem

### ISSUE THREAD

**Issue by tarzan-chou** [ctripcorp/apollo#909]
**What does it mean?** 
until [[ (( counter -ge max_counter )) || "$(curl -X GET --silent --connect-timeout 1 --max-time 2 --head $SERVER_URL | grep "Coyote")" != "" ]];

_when i excute start.sh ,the application will exit in 240s_

**some code in start.sh**

declare -i counter=0
declare -i max_counter=48 # 48*5=240s
declare -i total_time=0

printf "Waiting for server startup"
until [[ (( counter -ge max_counter )) || "$(curl -X GET --silent --connect-timeout 1 --max-time 2 --head $SERVER_URL | grep "Coyote")" != "" ]];
do
    printf "."
    counter+=1
    sleep 5

    checkPidAlive
done

**Comment by nobodyiam** [comment]
This is to check whether the server starts up by requesting an URL resource.

For your case, it sounds like it started up failed, you may check logs for more information.

**Comment by nobodyiam** [comment]
This case is closed for now, you may provide more information if there is any other question.
