### ISSUE TITLE
授权问题

### ISSUE THREAD

**Issue by 13127898836** [ctripcorp/apollo#910]
现在的版本是不是不支持对不同环境权限的授予
比如对于账号A，只想授予测试环境的修改和发布权限，
但是线上只想授予修改，不授予发布权限。

**Comment by 13127898836** [comment]
补充一点，用户的查看权限，现在好像也没法设置

**Comment by nobodyiam** [comment]
是的，目前不支持查看权限和分环境权限控制

**Comment by pengqiangx** [comment]
个人感觉，分环境授于不同的权限 还是很重要的，而且很有实际意义。希望以后可以支持下。

**Comment by nobodyiam** [comment]
感谢 @anthonywanted，Apollo现在支持分环境权限了！详见 #1282，后续会随0.11.0版本发布，请知晓。

权限管理页面截图：

![image](https://user-images.githubusercontent.com/837658/43093361-6ef6d820-8ee2-11e8-8918-26cb1e094115.png)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by nobodyiam** [comment]
#1531 支持设置某个环境的配置只能被项目成员看到，非项目成员无法查看，可以看一下

**Comment by aoof188** [comment]
什么时候能够支持查看权限分环境的权限控制，目前有在开发中吗？

**Comment by nobodyiam** [comment]
@aoof188 

参考下[apollo如何配置查看权限?](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#12-apollo%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE%E6%9F%A5%E7%9C%8B%E6%9D%83%E9%99%90)
