### ISSUE TITLE
关于数据库索引

### ISSUE THREAD

**Issue by yesuhuangsi** [ctripcorp/apollo#912]
注意到所有的表都对`DataChange_LastTime`添加了索引，但对于`IsDeleted`都没有添加索引，这是为什么？因为大概看了下并没有找到DataChange_LastTime作为条件的查询，而有IsDeleted字段的表都会以其作为查询条件

**Comment by yesuhuangsi** [comment]
那DataChange_LastTime是有查询使用了这个字段，只是我没找到？

**Comment by nobodyiam** [comment]
这是我们的数据库规范，每张表都需要有这个字段并且加索引。
