### ISSUE TITLE
appnamespace 和namespace ER 图上显示的是1对多关系，但是两张表在字段上内有任何关系

### ISSUE THREAD

**Issue by qyqcswill** [ctripcorp/apollo#913]

**Comment by lepdou** [comment]
apollo大部分的表都不是通过外键id索引的方式关联，而是通过冗余字段的方式隐式关联。
appnamespace联合主键[appId, namespaceName],namespace联合主键[appId, namespaceName, clusterName]。可以看出namespace的主键是包含appnamespace的主键，所以逻辑上讲是有关联的。

冗余字段的好处是，不用多一次查询，提高查询效率。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
