### ISSUE TITLE
apollo支持忽略没拿到的配置吗

### ISSUE THREAD

**Issue by jxplus** [ctripcorp/apollo#915]
类似PropertyPlaceholderConfigurer中的ignoreUnresolvablePlaceholders=true的情形，
比如程序里有@Value("${some_config}")，如果没有这个some_config配置也不会报错，直接将${some_config}当值。

apollo支持吗？

**Comment by lepdou** [comment]
比如程序里有@value("${some_config}")，如果没有这个some_config配置也不会报错，直接将${some_config}当值。
---------
你说的这种情况，其实并不是好的编程习惯。我们推荐给每一个配置项提供一个DEFAULT值，这样当配置中心挂掉，或者忘记配置的情况下有一层兜底。

不过ignoreUnresolvablePlaceholders=true的行为，应该跟spring一致的。apollo做的事情只是把apollo服务器上namespace的配置塞到spring 的environment里面，后续spring解析placeholder都是spring做的事情，apollo没有侵入到这个过程。所以，应该也是支持的，你可以测试一下。

**Comment by nobodyiam** [comment]
另外，一般还是建议给默认值，比如`@Value("${timeout:200}")`

**Comment by jxplus** [comment]
了解，谢谢
