### ISSUE TITLE
apollo配置完全支持sql导入配置吗？

### ISSUE THREAD

**Issue by changealice** [ctripcorp/apollo#920]
第一次项目上线很多配置，运维人员一个一个在portal上加配置，很崩溃，我想问下如果采用sql脚本导入需要导入需要导入哪些表。
目前我自己了解到：新增需要插入：
Item，Audit ，Commit三个表。
apollo能否完全做到sql导入就能工作？

**Comment by nobodyiam** [comment]
导入配置理论上是可以的，但是由于有一些关联关系，很容易出错。

Apollo是支持以properties文件格式批量导入配置的，具体可以参考[3.2.4 已有配置迁移](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#324-%E5%B7%B2%E6%9C%89%E9%85%8D%E7%BD%AE%E8%BF%81%E7%A7%BB)
