### ISSUE TITLE
portal假死求助

### ISSUE THREAD

**Issue by gblwzgb** [ctripcorp/apollo#922]
portal会出现假死的情况，可以登录，但是查询项目列表，创建用户等接口会夯住。现在临时解决办法是重启portal。

## 排查过程
1. 内存、CPU都很空闲
2. GC全是YGC，时间极短，FGC0次
3. 日志，项目启动完日志就没记录过。
4. 查看数据库线程，都是空闲状态
5. jstack命令未发现异常状态

![](http://ok7wlv1ee.bkt.clouddn.com/18-1-17/90128722.jpg)

6. 查看portal的端口tcp状态，有部分CLOSE_WAIT状态（找了张重启后的图，夯住的时候更多）

![](http://ok7wlv1ee.bkt.clouddn.com/18-1-17/43800546.jpg)

## startup.sh如下
![](http://ok7wlv1ee.bkt.clouddn.com/18-1-17/81241026.jpg)

**Comment by nobodyiam** [comment]
夯住的时候看下具体是哪些请求卡了，同时可以看下jstack是否有啥线程卡了

CLOSE_WAIT应该没啥关系吧

怀疑是不是portal访问其它环境的admin server不通？

日志里面应该会有一些信息吧？

**Comment by gblwzgb** [comment]
@nobodyiam 
日志就打了启动日志，启动完成后就没打过了

admin server都是通的，因为portal重启以后就好了

jstack看起来都是正常的

我已经加了远程调试的断点，下次出现这个问题就直接打断点了
