### ISSUE TITLE
apollo能否读web.xml中配置？

### ISSUE THREAD

**Issue by Lycine** [ctripcorp/apollo#924]
您好，我这边有个项目在web.xml中配置了参数如
`<context-param>
	<param-name>host</param-name>
	<param-value>192.168.11</param-value>
</context-param>`

有个类实现了ServletContextListener接口，在contextInitialized方法里通过servletContext.getInitParameter("host");得到参数。
请问apollo能否配置这种参数？

**Comment by Lycine** [comment]
已解决

**Comment by davidstack** [comment]
@Lycine 如何解决的？能否分析一下，谢谢

**Comment by Lycine** [comment]
@davidstack 当时我们没有解决可以配置web.xml参数的问题。而是把web.xml的参数提到properties里了。
