### ISSUE TITLE
apollo 能支持和mybatis整合的项目配置吗？

### ISSUE THREAD

**Issue by qyqcswill** [ctripcorp/apollo#925]

**Comment by lepdou** [comment]
Apollo没有和mybatis整合，目前只整合了spring

**Comment by nobodyiam** [comment]
mybatis-spring是支持和spring整合的，所以mybatis的配置也是可以通过apollo配置的

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
