### ISSUE TITLE
REST API有问题。私有namespace不能用json格式。

### ISSUE THREAD

**Issue by EMayej** [ctripcorp/apollo#926]
私有namespace用json格式时rest api不能访问，用properties的时候没有问题。

Steps:
1. 用docker启动
2. 在SampleApp下面创建私有namespace，（格式）选json
3. 在创建的namespace里面填合法的json或任意字符串
4. 访问 'http://localhost:8080/configfiles/json/SampleApp/default/myprivate'

返回结果
```json
{
timestamp: "2018-01-18T15:43:19.387+0800",
status: 404,
error: "Not Found",
message: "Could not load configurations with appId: SampleApp, clusterName: default, namespace: myprivate",
path: "/configfiles/json/SampleApp/default/myprivate"
}
```

**Comment by lepdou** [comment]
URL错了吧。
应该是：http://localhost:8080/configfiles/SampleApp/default/myprivate

可以参考[ConfigFileController.java](https://github.com/ctripcorp/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/controller/ConfigFileController.java)

**Comment by nobodyiam** [comment]
非properties格式需要加后缀的

http://localhost:8080/configfiles/json/SampleApp/default/myprivate.json
