### ISSUE TITLE
现在的版本支持管理properties以外的配置文件吗

### ISSUE THREAD

**Issue by qingyun1** [ctripcorp/apollo#928]
如xml、yml、txt之类的文件，如果不支持，我们做二次开发的工作量不算大把？

**Comment by lepdou** [comment]
现在xml、yml、json这些格式是统一以整个文本的方式处理。client获取到整个文件内容之后，需要用户自己解析xml、yml。

二次开发的工作量应该不大的，主要是在apollo-client里面，做配置解析的工作。比如可以提供一个API，用户传入一个类型，自动反序列化json成用户传入类型的对象。

服务端基本上不需要做任何改造。最新版本的portal页面上也支持xml、yml、json控件编辑。[0.9.1版本Release信息](https://github.com/ctripcorp/apollo/releases/tag/v0.9.1)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by bean025** [comment]
API集成方式  支持spring 项目吗？有详细的spring 对接， api方式的使用说明吗？

**Comment by bean025** [comment]
a .xml配置文件引用了其他的配置文件b.properties 、(或者 b.xml 中 引入了 d.xml )  .把 a b  c  d  配置文件全部到apollo 托管,那a  中  b 的路径 和 b  中  d 的路径要改变吗

**Comment by nobodyiam** [comment]
详细的客户端使用方式请参考 [Java客户端使用指南](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)

目前xml配置文件apollo是不做解析的，只是作为一个string返回，所以相关的逻辑需要业务层自己处理

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
