### ISSUE TITLE
spring 3.2 基于spring cloud refreshscope更新配置失败

### ISSUE THREAD

**Issue by qianqiuzhifeng** [ctripcorp/apollo#929]
配置更新后，客户端接到配置修改的消息，但是并未刷新数据，问下是什么造成的呢？
<spring-demo.version>3.2.5.RELEASE</spring-demo.version>
<spring-boot.version>1.3.4.RELEASE</spring-boot.version>
<spring-cloud.version>1.1.0.RELEASE</spring-cloud.version>
依赖的版本

**Comment by lepdou** [comment]
请先对比文档，是否有某个地方遗漏的。
----------
【推荐】使用Spring Cloud的RefreshScope
在需要刷新配置的bean上加@RefreshScope
加一个Apollo的ConfigChangeListener，然后在配置变化时调用RefreshScope的refreshAll()或者refresh(String name)的方法。
如果要刷新的不是自己的bean，而是spring cloud的bean，如spring cloud zuul，那么可以调用org.springframework.cloud.context.refresh.ContextRefresher#refresh来刷新配置
相关代码实现，可以参考apollo-demo项目中的AnnotatedBean.java和ApolloRefreshConfig.java
在非Spring Boot环境使用RefreshScope需要引入RefreshAutoConfiguration，引入方式可以参考apollo-demo项目中的相关配置代码：JavaConfig示例，XmlConfig示例。
----------
如果已经严格按照以上文档操作，建议debug一下  RefreshScope.refreshAll()方法，应该能找到问题。

**Comment by trilobita-org** [comment]
我遇到的是这个问题，执行刷新配置的时候后报
java.util.concurrent.RejectedExecutionException 错误

**Comment by nobodyiam** [comment]
@trilobita-org 不知是否方便传一份有问题的代码上来我们看一下？

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

另外，0.10.2版本已经支持spring注入的配置自动更新，所以一般情况下也不需要`@RefreshScope`了。

**Comment by hdpter** [comment]
@trilobita-org 我也遇到了同样的问题，不知道您是否已经解决，解决办法是啥？谢谢
