### ISSUE TITLE
如何实现一次打包，处处运行的目的

### ISSUE THREAD

**Issue by springCkWyy** [ctripcorp/apollo#931]
我现在是这种需求， 我在本地已经打好admin config portal等jar包了，  ip、数据库信息都是配置的本地的。 现在我需要在公司测试环境安装Apollo， 只想把这三个jar 上传过去，但是测试环境的ip、数据库连接等信息肯定和我本地不一样的。  现在在不重新编辑build,sh配置信息，只有原来这三个jar的前提下， 怎么在新的环境 指定ApolloconfigDB  portalDB和boot.yml哪些配置信息呢？实现一次打包，处处运行的目的

**Comment by nobodyiam** [comment]
1. apollo-client和apollo-core的jar包中包含了所有环境的meta server信息，所以只需要打包一次
2. apollo-portal只需要部署一个环境，所以只需要打包一次
3. apollo-configservice和apollo-adminservice需要在每个环境部署一个，所以需要对不同环境打包，写入不同环境的数据库。如果不想分别打包的话，也可以在运行时通过`-D`参数传入相关信息，具体可以参考下 #716

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
