### ISSUE TITLE
@EnableApolloConfig({"#{public.path}"})

### ISSUE THREAD

**Issue by guyukou** [ctripcorp/apollo#932]
是否可以在@EnableApolloConfig中动态获取环境参数

**Comment by lepdou** [comment]
这个目前是不支持的。

你能详细描述一下，你这么做的原因吗？

**Comment by guyukou** [comment]
我们的项目中,test和demo都在一个环境列表当中，是通过在app.id加上后缀区分开的。当使用了公共配置之后，如果两个环境有参数不一样，那么项目当中引用公共配置的时候就需要变量了。

**Comment by nobodyiam** [comment]
你是指同一份公共配置的namespace的名字不一样？

**Comment by guyukou** [comment]
目前的apollo配置只有一个环境
![image](https://user-images.githubusercontent.com/15632270/35481977-4070b6e6-0469-11e8-8c2b-87c80b4d28f3.png)
但是在这个环境里面有dev，test，demo三个环境，由于公共配置里面有DB连接信息，3个不同环境的连接信息不一样，所以公共配置的app.id不能在代码里面硬编码

**Comment by nobodyiam** [comment]
公共配置的app.id不需要配置啊，对于应用而言，要获取公共的配置，只需要提供公共配置的namespace名字就可以了。
