### ISSUE TITLE
支持非properties的配置文件的灰度发布

### ISSUE THREAD

**Issue by ccl0326** [ctripcorp/apollo#933]
目前只有properties支持灰度发布，但是其他格式的配置文件也有这样的需求。从代码上看，仅修改前端代码就可以支持。

**Comment by lepdou** [comment]
properties灰度比较复杂，涉及到灰度版本和主版本配置的merge操作。
非properties namespace在底层实现就是只有一个key的properties，所以理论上修改的内容较少。
非properties灰度，我们还没有深入分析过。简单的想了一下，交互方式和properties有略微区别，应该是把properties的灰度阉割掉一些功能。你也可以自己想一下，怎么交互比较合理。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
