### ISSUE TITLE
单机部署，如何实现多环境配置？

### ISSUE THREAD

**Issue by linsage** [ctripcorp/apollo#938]
apollo单机部署成功，如何区分不同环境配置（dev、test、pro）.

看了一下需要分布式部署才能支持，需要各自环境部署一个才能实现？这样使用成本有点高

**Comment by lepdou** [comment]
可以部署一套apollo服务，然后通过集群区分环境。

**Comment by R1310328554** [comment]
框架写得不错，但是过于复杂了，部署起来确实不太友好。 我于是通过修改源码方式，给env 和 app.id 设置了默认值。
linsage 可以考虑把 namespace 作为env 来用。。
