### ISSUE TITLE
Java可以设置某个变量值么？

### ISSUE THREAD

**Issue by seanbean1992** [ctripcorp/apollo#939]
我看到只能拿到变量，如果想要通过程序修改变量值可以么

**Comment by nobodyiam** [comment]
修改需要调open api，参考[Apollo开放平台
](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
