### ISSUE TITLE
多个namespace里面有相同的变量名会怎么处理？

### ISSUE THREAD

**Issue by seanbean1992** [ctripcorp/apollo#940]
如果两个或两个以上的namespace被使用，其中包含有共同的变量名，会有什么机制么

**Comment by nobodyiam** [comment]
如果是api方式，一个config对象对应一个namespace，两者没啥关系。如果是spring方式，会有覆盖关系，覆盖顺序通过@EnableApolloConfig中的[order](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/annotation/EnableApolloConfig.java#L43)指定

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
