### ISSUE TITLE
登录安全机制

### ISSUE THREAD

**Issue by reignsr** [ctripcorp/apollo#943]
试用0.9.1版本发现，portal登陆环节缺失相关安全机制，主要想咨询以下两点：
1、图形验证码机制；
2、登陆密码以明文传输至后台；
这两点不知道官方有否考虑在后续版本中实现？如果短期内没有这个考虑，能否指点下自行改造的方案？

**Comment by lepdou** [comment]
apollo这种系统，是内部使用的系统。应该不需要这么高级别的防护措施吧？
或者说，你的portal是部署在阿里云公网上的，那确实有可能被劫持。
Portal授权这一块是通过spring security做的，基本上没做额外的定制，你可以尝试基于spring security做改造。这个解决方案应该是通用的吧。

**Comment by reignsr** [comment]
感谢！ @lepdou

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
