### ISSUE TITLE
如何指定注册服务的端口

### ISSUE THREAD

**Issue by qingyun1** [ctripcorp/apollo#944]
eureka:
  instance:
    homePageUrl: http://${指定的IP}:${指定的Port}
    preferIpAddress: false

如上配置不起作用啊，注册进去的端口还是服务内网端口，我的客户端和服务端不在一个网段，注册的时候需要指定外网ip、端口

**Comment by lepdou** [comment]
理论上应该不会有问题的，你可以解压一下包，看里面的配置文件是否正确的被修改了。

如果实在不行，尝试一下第二种方式。[部署&开发遇到的常见问题](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
