### ISSUE TITLE
Quick Start是否能够修改服务端口

### ISSUE THREAD

**Issue by lic987** [ctripcorp/apollo#945]
您好 请问在服务器上安装Quick Start 能否通过修改demo.sh中的信息来修改启动端口呢？
我修改了config_server_url=http://localhost:9080 结果一直会有Connection refused的问题 查询后应该是eureka注册的问题。
还有如果正是环境能否修改启动端口呢？
谢谢您的解答

**Comment by lepdou** [comment]
quick start可能不能修改端口。
但是正式部署，是可以修改端口号的。具体可以参考一下 [分布式部署指南](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97)

**Comment by lic987** [comment]
好的 谢谢您了
