### ISSUE TITLE
请问如何在日志配置加载前加载apollo配置?

### ISSUE THREAD

**Issue by wenzhen123** [ctripcorp/apollo#946]
你好 项目是Spring Boot,日志用的logback,使用Apollo进行配置的情况下在logback-spring.xml内用springProperty的方式无法取到配置的值,等程序启动完成后能正常获取到值.请问这种情况该如何设置呢?

**Comment by nobodyiam** [comment]
参考 [3.2.1.3 在Spring Boot初始bootstrap阶段注入配置](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#3213-%E5%9C%A8spring-boot%E5%88%9D%E5%A7%8Bbootstrap%E9%98%B6%E6%AE%B5%E6%B3%A8%E5%85%A5%E9%85%8D%E7%BD%AE) 试试

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by nobodyiam** [comment]
日志相关的可以参考 #816
