### ISSUE TITLE
请问下，为什么不能删除私有的namespace？

### ISSUE THREAD

**Issue by seguzhizi** [ctripcorp/apollo#947]
望告知

**Comment by lepdou** [comment]
因为删除私有namespace，相当于删除appnamespace，需要删除所有环境的appnamespace、以及权限相关信息，开销很大。而且实际运行过程中，也很少出现删除namespace的需求，一般都是刚部署阶段，测试namespace的删除。

具体删除可以手动到db里面删。删除方式可以参考 [常见问题 5.3小节](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by seguzhizi** [comment]
qqq

**Comment by nobodyiam** [comment]
最新的master版本已经增加了管理员工具页面，可以删除应用、集群和AppNamespace，会在0.11.0版本中发布，相关文档已经更新，可以参考一下。

https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#5-%E5%A6%82%E4%BD%95%E5%88%A0%E9%99%A4%E5%BA%94%E7%94%A8%E9%9B%86%E7%BE%A4namespace
