### ISSUE TITLE
是否支持zookeeper作为服务注册和发现

### ISSUE THREAD

**Issue by silloy** [ctripcorp/apollo#948]
是否支持zookeeper作为服务注册和发现

**Comment by lepdou** [comment]
理论上是可以的，不过得改一下源码实现。
主要改两块：
1. 注册服务。需要把admin service和config service注册到zk
2. 服务发现。可以参考  [获取服务地址源码](https://github.com/ctripcorp/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/metaservice/controller/ServiceController.java)

但是，没有必要改成zk作为服务注册发现吧？现在eureka是内嵌到Apollo里面，换成zk的目的是啥？感觉是画蛇添足。

**Comment by silloy** [comment]
因为具体的服务可能会使用zk作为服务发现，希望通过配置能够使用同一个套zk，即使使用eureka也希望做成可插拔式的组件，耦合度太高，不利于扩展

**Comment by lepdou** [comment]
我觉得你可以把Apollo里面的eureka忽略，把整个Apollo当成一个整体，不依赖任何其它组件。
我个人认为把Apollo里面的服务注册发现改成zk，没什么任何收益。也不会提高你的运维效率，还要额外的二次开发。
当然你想这么做，肯定也是能做的。

**Comment by handq** [comment]
能把apollo自带的eureka改成自己的eureka注册中心，已经项目已经有一个注册中心了。求教怎么改？

**Comment by nobodyiam** [comment]
1. 修改ApolloConfigDB.ServerConfig表中的eureka.service.url为你自己的eureka地址列表
2. 把config service的`@EnableEurekaServer`改成`@EnableEurekaClient`

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
