### ISSUE TITLE
portal环境问题

### ISSUE THREAD

**Issue by seguzhizi** [ctripcorp/apollo#949]
1：请问如何添加部门信息？有界面操作入口吗？还是直接修改db？

2：本地单机搭建之后，测试了多环境问题，比如开启了dev和fat环境。在新增参数时，是可以选择参数使用环境的，我选择了dev环境，但是fat环境也增加了此参数；我在dev环境发布了参数，fat环境也自动发布了，同理，当我本地设置为pro环境，但是仍然可以获取到dev参数。。。

我看wiki介绍的是portal区分环境的，但是现在发现好像所有操作在不同环境中是同步的。。。是设计如此还是搭建有问题（并未报错）还是portal操作问题？

望告知。。。

**Comment by seguzhizi** [comment]
刚刚回溯了closed的issue，发现了一些解答：
configDB是和环境关联的，不同环境使用不同的configDB，那我的环境都是使用本机的DB，所以配置就无法分开环境了，是吗？
但是portalDB是跨环境通用。。。

现在公司的开发环境，测试环境和生产环境，环境信息都是隔离的，那么使用起来就不可能通用portalDB了，是否只能在各个环境各自搭建一套portal，然后在各自的portal中固定使用该环境的DB？相当于不使用环境区分功能了。

请看下我的理解是否有偏差？谢谢~！

**Comment by nobodyiam** [comment]
可以先看下 [分布式部署-环境部分](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#13%E7%8E%AF%E5%A2%83)

* Portal部署在生产环境的机房，通过它来直接管理FAT、UAT、PRO等环境的配置
* Meta Server、Config Service和Admin Service在每个环境都单独部署，使用独立的数据库

建议还是让一套Portal能连通所有环境的Meta Server和Admin Service，这样才能实现环境间的项目信息共享，不然用户就得在每个环境单独创建项目、namespace之类的。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
