### ISSUE TITLE
想转到springboot项目，怎么才能很好的支持yml格式的配置文件

### ISSUE THREAD

**Issue by myfreeway** [ctripcorp/apollo#950]
现在已经用上了apollo，传统的ssi项目，使用properties格式的配置文件，key -value格式的。用的还不错。最近想用spring boot，但是发现spring boot喜欢用yml格式的配置文件。apollo怎么样才能很好的支持这种需求呢？

**Comment by nobodyiam** [comment]
yml本质上和properties一样的，在spring boot代码中实际使用的配置项信息还是key-value格式。

比如

```yml
spring:
  application:
    name: demo
```

和

```properties
spring.application.name=demo
```

两者是一致的，代码中如果要获取该配置项，使用的还是`${spring.application.name}`。

所以对Apollo而言，目前主要还是支持properties格式，后面或许可以考虑增强一下界面，支持yml录入，properties格式展示。

**Comment by arebya** [comment]
yml和properties文件在绑定参数的时候存在有序和无序的区别，yml load的是LinkedHashMap,properties load的实际上是个HashTable，在某些场景下需要保证顺序，如druid-spring-boot-starter的issue  [issue1796](https://github.com/alibaba/druid/issues/1796)

**Comment by nobodyiam** [comment]
你说的是spring解析文件的过程，Apollo的配置不存在spring解析文件的过程，是直接放一个PropertySource进去的，机制上和spring自己解析是不同的，具体可以看下[代码](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/config/PropertySourcesProcessor.java#L47)

不过程序也不能依赖于配置的顺序吧，这岂不是非常容易出问题了，跑的好好的，不小心调了个顺序就挂了？

**Comment by arebya** [comment]
是的，主要是针对您上面“yml本质上和properties一样的，在spring boot代码中实际使用的配置项信息还是key-value格式。”这个来讨论的。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
