### ISSUE TITLE
Scripts/build.sh脚本是自动生成的吗？

### ISSUE THREAD

**Issue by ray1985113** [ctripcorp/apollo#951]
如果不使用脚本打包，可以说明一下，如何在IDE（Eclipse中）打包吗？

**Comment by nobodyiam** [comment]
build.sh和build.bat是我们写的，主要是有一些配置替换逻辑，不确定通过IDE是否能打包，另外，为啥要让IDE打包呢

**Comment by ray1985113** [comment]
恩, 谢谢, 脚本确实方便。
