### ISSUE TITLE
.net版本 ApolloDemo运行，初始化过程中DataCenter为null，因为没有配置

### ISSUE THREAD

**Issue by ray1985113** [ctripcorp/apollo#952]
你好，C:\opt\settings\server.properties 中的idc不是必须的配置，那么这个配置项的作用是什么呢？例如有什么应用场景吗？

**Comment by lepdou** [comment]
这个参数含义主要是标识当前应用所在的数据中心。
假设公司有两个idc，并且一个应用是双机房部署的。应用在不同的机房读取同一个属性时，值可能是不一样的。这种场景，在Apollo里通过创建多个集群来实现的。在Apollo Client中，会读取server.properties中的idc字段，作为cluster，映射到Portal上环境下面的集群。这样就可以实现不同的机房读取不同的配置值了。
具体可以看一下客户端如何处理cluster属性。[ConfigUtil.java](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/util/ConfigUtil.java)

**Comment by ray1985113** [comment]
@lepdou  C:\opt\settings\server.properties 中的idc的配置其实就跟在web.Config配置的cluster ，作用是一致的。

**Comment by ray1985113** [comment]
谢谢
