### ISSUE TITLE
有几个建议，请大神们帮忙看看

### ISSUE THREAD

**Issue by konglz** [ctripcorp/apollo#954]
### 建议对二开提供一些支持

* 大厂可能会在apollo基础上做不同程度的二开，直接原封不动拿去用的可能性比较小

* 建议多一些图形化语言来描述client端和server端的交互逻辑和时序，详细到接口粒度上。
这样做可以方便大家开发其他语言的客户端，比如php客户端、OpenResty 客户端。

* 能否把对spring/spring boot的依赖收敛起来，各个模块并不直接依赖于spring，仅在spring auto configmaven子模块依赖spring，这样就能够适配众多的java开发环境。
这方面dubbo也是一个例子，我们可以只通过jdk运行dubbo，用手动组装代替spring的bean组装。

### 能否适配更多的注册中心

* 一些公司可能不愿意运维2套注册中心，比如说同时运维eureka和zookeeper。
因此，能否考虑适配一些比较老牌的注册形式，比如说适配zookeeper和redis，dubbo就可以用redis作为注册中心

**Comment by nobodyiam** [comment]
感谢建议！

1. 后续我们补一些client端和server端的交互逻辑和时序图，方便大家理解内部的实现。

2. spring/spring boot的依赖，你是指客户端吧？其实客户端是对spring的依赖是optional的，使用API方式是完全不会使用到spring/spring boot的。

3. 目前Apollo使用的注册中心其实可以认为是Apollo的内部模块实现，因为它对客户端是不可见的，对客户端而言，连接的是Apollo的Meta Server。对服务端而言，其实也不需要运维eureka，因为eureka和apollo是在一个进程中启动的。不过确实有些公司希望能接入他们自己的注册中心，这块我们后面研究下看看是否能提供多套实现。

**Comment by ray1985113** [comment]
支持，点赞！！！
