### ISSUE TITLE
为什么我用你们的docker quick  start  起不来

### ISSUE THREAD

**Issue by hexulin-miaomiao** [ctripcorp/apollo#956]
apollo-quick-start    | Portal failed to start in 120 seconds! Please check ./portal/apollo-portal.log for more information.
apollo-db             | 2018-02-07T11:54:09.497434Z 2 [Note] Aborted connection 2 to db: 'ApolloConfigDB' user: 'root' host: '172.19.0.2' (Got an error reading communication packets)
apollo-db             | 2018-02-07T11:54:09.497602Z 3 [Note] Aborted connection 3 to db: 'ApolloConfigDB' user: 'root' host: '172.19.0.2' (Got an error reading communication packets)
报这个错，需要单独配置什么吗？mysql是起来的可以正常访问

**Comment by nobodyiam** [comment]
看上去是连db出问题了，重试下看看？

你看看db是不是起来了？

**Comment by jieblog** [comment]
我也是同样的问题。。

**Comment by nobodyiam** [comment]
@jieblog @hexulin-miaomiao 

把执行`docker-compose up`后的所有日志都贴一下吧

**Comment by nobodyiam** [comment]
看看是不是docker版本太老的问题？

我这里的docker version：
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by GarinFeng** [comment]
![image](https://user-images.githubusercontent.com/7239179/93450492-a0242780-f908-11ea-893e-55892e5a74fd.png)
![image](https://user-images.githubusercontent.com/7239179/93450521-a9ad8f80-f908-11ea-842c-deaed69ca80e.png)

**Comment by chrisptang** [comment]
我这边也起不来，看起来DB和ConfigServer是起来了，但Portal不行：

apollo-config    | ==== starting service ====
apollo-config    | Service logging file is ./service/apollo-service.log
apollo-config    | Started [49]
apollo-config    | Waiting for config service startup.........
apollo-config    | Config service started. You may visit http://localhost:8080 for service status now!
apollo-config    | Waiting for admin service startup..
apollo-config    | Admin service started
apollo-config    | ==== starting portal ====
apollo-config    | Portal logging file is ./portal/apollo-portal.log
apollo-config    | Started [270]
apollo-config    | Waiting for portal startup........................
apollo-config    | Portal failed to start in 120 seconds! Please check ./portal/apollo-portal.log for more information.
