### ISSUE TITLE
为什么我登录web后感觉正常但是发现没有环境列表？

### ISSUE THREAD

**Issue by hexulin-miaomiao** [ctripcorp/apollo#957]
![image](https://user-images.githubusercontent.com/30501637/35916312-f59193f0-0c44-11e8-9ed1-ef392f9e0f5d.png)
就是web上环境列表没东西？

**Comment by nobodyiam** [comment]
一般是portal连不上admin service，具体可以看一下portal和admin service的日志

**Comment by xcw931924821** [comment]
这个需要配置portaldb的aserverconfig 表中的apollo.portal.envs
2 还要启动的时候配置apollo-core中的apollo-env.properties
中每个环境对应的metaserver的ip:端口。

**Comment by Jesn** [comment]
@hexulin-miaomiao   请问你解决了这个问题么，我也遇到同样的问题

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
