### ISSUE TITLE
某个环节添加集群，会在所有环境下添加？？

### ISSUE THREAD

**Issue by princezhaoyt** [ctripcorp/apollo#960]
如题，三台服务器，对应三个环境，DEV，FAT，UAT。在DEV添加集群dev1后，会自动在FAT和UAT下添加同样的dev1集群。。请问下为什么呢？
注：添加集群的时候，肯定只选择了DEV环境

**Comment by nobodyiam** [comment]
你的3个环境背后是同一套config service或config db，分布式部署需要每个环境部署一套独立的config service/admini service和config db，具体可以参考[分布式部署文档](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97)。

**Comment by princezhaoyt** [comment]
三个服务器也是各自使用自己的mysql，configservice也是三台服务器均各自部署的。
build的配置如下：
rem apollo config db info
set apollo_config_db_url="jdbc:mysql://localhost:3306/ApolloConfigDB?characterEncoding=utf8"
set apollo_config_db_username="root"
set apollo_config_db_password="root"

rem apollo portal db info
set apollo_portal_db_url="jdbc:mysql://localhost:3306/ApolloPortalDB?characterEncoding=utf8"
set apollo_portal_db_username="root"
set apollo_portal_db_password="root"

rem meta server url, different environments should have different meta server addresses
set dev_meta="http://192.168.1.27:8080"
set fat_meta="http://192.168.1.28:8080"
set uat_meta="http://192.168.1.29:8080"
set pro_meta="http://yetAnotherIp:8080"


但是发现startup.sh中配置：
SERVER_URL="http://localhost:$SERVER_PORT"
而且三台服务器上的configservice和adminservice中的appId一样，请问这个是否影响呢？

再就是，之前这三台服务器做过lvs配置，是否也可能有影响呢？

烦请帮忙，，非常感谢。

**Comment by princezhaoyt** [comment]
搞定了，结贴啦。多谢。
因为我之前在三台服务器上搭建过lvs集群，映射出来VIP，导致每次获取ip的时候，三台服务器均获取的同一个ip。将VIP删除后，恢复正常。
望对以后入此坑的人有帮助。
