### ISSUE TITLE
 Long polling failed

### ISSUE THREAD

**Issue by leohsu91** [ctripcorp/apollo#964]
报错如下，何解？
`16:44:41.013 [Apollo-RemoteConfigLongPollService-1] WARN  c.c.f.a.i.RemoteConfigLongPollService - Long polling failed, will retry in 120 seconds. appId: cwps-b, cluster: dev, namespaces: application, reason: com.ctrip.framework.apollo.core.dto.ApolloConfigNotification.setNotificationId(J)V `

**Comment by nobodyiam** [comment]
这点日志貌似看不出问题来，把日志级别调成DEBUG跑一下吧，会有更详细的日志信息。

**Comment by leohsu91** [comment]
已解决，忘记更新

**Comment by weifan01** [comment]
@leohsu91  您好：请问最终是怎么解决的呢？我的也出现这个问题了

**Comment by hansonhantong** [comment]
这个何解呀，也遇到这个问题了
