### ISSUE TITLE
2台机器，分别部署Portal、configService和adminService发现portal高可用访问异常

### ISSUE THREAD

**Issue by Aliexis** [ctripcorp/apollo#966]
2台机器，分别部署Portal(8070)、configService(8090)和adminService(8080)发现portal高可用访问异常，分别单独访问portal后端可以访问，但是通过VIP访问异常，登录不进去，，，请问下是不是两台portal和configService、adminService不能同时部署在一台机器上

**Comment by lepdou** [comment]
>请问下是不是两台portal和configService、adminService不能同时部署在一台机器上
跟这个应该没关系，问题应该出在VIP没啥没起作用，可以往这个方向排查。

**Comment by Aliexis** [comment]
问题解决了，Portal后端session不不共享的，而HAProxy默认的负载均衡策略是rr，导致服务接口出错，改下HA的配置就OK了

**Comment by lepdou** [comment]
嗯，Portal用的spring security，是内存session不共享。
