### ISSUE TITLE
docker-compose up 失败

### ISSUE THREAD

**Issue by craneding** [ctripcorp/apollo#971]
信息如下：
Creating apollo-dbdata ... 

ERROR: for apollo-dbdata  Cannot create container for service apollo-dbdata: No command specified

ERROR: for apollo-dbdata  Cannot create container for service apollo-dbdata: No command specified
ERROR: Encountered errors while bringing up the project.

**Comment by nobodyiam** [comment]
你的docker啥版本啊

**Comment by craneding** [comment]
Docker version 1.12.3, build 6b644ec, experimental

**Comment by nobodyiam** [comment]
升个级吧，我这里docker version看到的和你差别有点大

docker version
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
