### ISSUE TITLE
Apollo在创建docker镜像的时候，如何使用外部mysql

### ISSUE THREAD

**Issue by Jesn** [ctripcorp/apollo#975]
在docker-quick-start里面 docker-compose.yml up  的时候默认会创建一个mysql:5.7的基础镜像，现在我的需求是想把Apollo的数据库接入到我现有的mysql数据库里面去，请问如何处理？

**Comment by nobodyiam** [comment]
docker-quick-start只是个quick start的镜像，所以会把所需要的东西都直接准备好，以便用户一键试用。

如果是实际部署的话，请参考分布式部署文档，在build.sh中需要填入数据库连接串信息的。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
