### ISSUE TITLE
spring boot 中使用ConditionalOnProperty读取不到配置

### ISSUE THREAD

**Issue by mhcxp** [ctripcorp/apollo#977]
```
/**
* 是否启用XXX
*/
@ConditionalOnProperty(prefix = "xxxx", name = "enabled", matchIfMissing = true)
public XXX xxx(){
...
}
```
在配置中心配置xxxx.enable=true或false都会执行`xxx()`; 在应用application.properties文件中配置时无此问题

**Comment by nobodyiam** [comment]
`@ConditionalOnProperty`功能从0.10.0版本开始支持，具体可以参考 [3.2.1.3 在Spring Boot初始bootstrap阶段注入配置](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#322-spring-placeholder%E7%9A%84%E4%BD%BF%E7%94%A8)

**Comment by mhcxp** [comment]
@nobodyiam 
试过了, 0.10.0-SNAPSHOT可以, 什么时候发稳定版?

**Comment by nobodyiam** [comment]
@mhcxp 预计3月中下旬吧

**Comment by nobodyiam** [comment]
@mhcxp 0.10.2版本已经release一段时间了，可以正式使用了，这个case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by leohsu91** [comment]
这个问题最好写到常见问题里面吧。表示遇到了这个坑，找到了这个Issue才解决的问题。

**Comment by nobodyiam** [comment]
已添加 - [9. Spring Boot中使用ConditionalOnProperty读取不到配置](https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#9-spring-boot%E4%B8%AD%E4%BD%BF%E7%94%A8conditionalonproperty%E8%AF%BB%E5%8F%96%E4%B8%8D%E5%88%B0%E9%85%8D%E7%BD%AE)
