### ISSUE TITLE
@ApolloConfig、@ApolloConfigChangeListener 不起作用

### ISSUE THREAD

**Issue by nieguhua** [ctripcorp/apollo#979]
`      Config appConfig;

	@ApolloConfig("application")
	Config config;

	@Autowired
	private TestConfigBean testConfigBean;

	@ApolloConfigChangeListener
	private void change(ConfigChangeEvent changeEvent){
		System.out.println("NameSpace:" + changeEvent.getNamespace());
		for(String key : changeEvent.changedKeys()){
			System.out.println("Changekey:" + key + ";value:" + changeEvent.getChange(key));
		}
	}

	@PostConstruct
	public void init(){
		appConfig = ConfigService.getConfig("application");
		appConfig.addChangeListener(new ConfigChangeListener() {
			@Override
			public void onChange(ConfigChangeEvent changeEvent) {
				System.out.println("NameSpace:" + changeEvent.getNamespace());
				for(String key : changeEvent.changedKeys()){
					System.out.println("Changekey:" + key + ";value:" + changeEvent.getChange(key));
				}
			}
		});
	}

	@GetMapping("/get/{key}")
	public Object getProperty(@PathVariable String key){
		if(config != null){
			System.out.println(config.getProperty(key,"default"));
		}
		System.out.println(testConfigBean.getDriverClassName() + ";" + testConfigBean.getPassword() +
				";" + testConfigBean.getType() + ";" +testConfigBean.getUrl() + ";" + testConfigBean.getUsername());
		return appConfig.getProperty("eureka.client.service-url.defaultZone","default");
	}`
手动实例化Config、添加监听器都成功了，通过@EnableApolloConfig填充配置也成功了，就是使用注解ApolloConfig、ApolloConfigChangeListener自动去实例化和添加监听器没有达到效果，Config为null，监听器在修改时也没反应，采用的是0.10.0版本的，想知道这是什么问题？劳烦解惑，谢谢！！！

**Comment by nobodyiam** [comment]
我估计是`@EnableApolloConfig`没加或者是没加对

到 [ApolloAnnotationProcessor.postProcessBeforeInitialization](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/annotation/ApolloAnnotationProcessor.java#L27)方法打个断点吧，只要`@EnableApolloConfig`加对的话，就会执行的。

**Comment by nieguhua** [comment]
感谢您的回复。
`@Configuration
@EnableApolloConfig
public class MyConfig {

	@Bean
	public TestConfigBean getConfigBean(){
		return new TestConfigBean();
	}
}`
这是我加@EnableApolloConfig的地方，通过调试没发现对上文中config的注入。

**Comment by nobodyiam** [comment]
到我上面说的  [ApolloAnnotationProcessor.postProcessBeforeInitialization](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/spring/annotation/ApolloAnnotationProcessor.java#L27)方法打个断点看看吧

**Comment by nieguhua** [comment]
知道这个注解不起作用的原因了，因为之前用这两个注解是放在DemoApplication这个启动类里面，通过调试该方法postProcessBeforeInitialization，发现在获取DemoApplication这个类中字段时，没有获取到注解下的成员变量，所以没法初始化。不知道为什么获取不到？

**Comment by nobodyiam** [comment]
Spring的Configuration类是不支持的，因为其加载周期早于普通的bean，请放在普通的bean里面。

**Comment by nieguhua** [comment]
恩恩 谢谢

**Comment by xianchaoye** [comment]
@ApolloConfigChangeListener(value="${listener}")
这个可以动态传入监听吗

**Comment by nobodyiam** [comment]
@xianchaoye 

目前还不支持动态传入，在什么场景下需要动态？

**Comment by maolujun** [comment]
动态传入监听场景：
微服务日志打印。定义一个公共的namespaceA，然后服务B的namespaceB、服务C的namespaceC都关联namespaceA，需要编写一个公共的日志监听类：热加载修改日志级别，只想看服务B的debug日志

此时我就需要在这个公共的日志监听类里面添加：@ApolloConfigChangeListener({"namespaceA","namespaceB","namespaceC"})
此时，如果新加入了一个服务D，那么就又需要去改这个基础的日志监听类为：
@ApolloConfigChangeListener({"namespaceA","namespaceB","namespaceC","namespaceD"})

**Comment by maolujun** [comment]
现在的处理办法是：往每个项目的默认application中添加logging.level.root: debug，然后@ApolloConfigChangeListener就用默认的
通过这种方式来控制每一个项目的日志级别热加载

**Comment by nobodyiam** [comment]
公共组件建议通过api方式接入，然后可以把需要监听的namespace列表作为一个配置项使用

**Comment by leohao1018** [comment]
> 恩恩 谢谢



> 动态传入监听场景：
> 微服务日志打印。定义一个公共的namespaceA，然后服务B的namespaceB、服务C的namespaceC都关联namespaceA，需要编写一个公共的日志监听类：热加载修改日志级别，只想看服务B的debug日志
> 
> 此时我就需要在这个公共的日志监听类里面添加：@ApolloConfigChangeListener({"namespaceA","namespaceB","namespaceC"})
> 此时，如果新加入了一个服务D，那么就又需要去改这个基础的日志监听类为：
> @ApolloConfigChangeListener({"namespaceA","namespaceB","namespaceC","namespaceD"})

感谢

> 动态传入监听场景：
> 微服务日志打印。定义一个公共的namespaceA，然后服务B的namespaceB、服务C的namespaceC都关联namespaceA，需要编写一个公共的日志监听类：热加载修改日志级别，只想看服务B的debug日志
> 
> 此时我就需要在这个公共的日志监听类里面添加：@ApolloConfigChangeListener({"namespaceA","namespaceB","namespaceC"})
> 此时，如果新加入了一个服务D，那么就又需要去改这个基础的日志监听类为：
> @ApolloConfigChangeListener({"namespaceA","namespaceB","namespaceC","namespaceD"})

感谢指点，指定 namespace 可以刷新了

**Comment by xiehanghang** [comment]
> Spring的Configuration类是不支持的，因为其加载周期早于普通的bean，请放在普通的bean里面。

项目中有些 bean 需要@Configuration属性来完成初始化，否则启动不了，除了把这些配置都放入 Apollo 上，有什么其他好的方法吗？

**Comment by nobodyiam** [comment]
@xiehanghang 如果是 Spring Boot 的应用，可以试试[Spring Boot集成方式](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#3213-spring-boot%E9%9B%86%E6%88%90%E6%96%B9%E5%BC%8F%E6%8E%A8%E8%8D%90)

**Comment by xiehanghang** [comment]
> @xiehanghang 如果是 Spring Boot 的应用，可以试试[Spring Boot集成方式](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#3213-spring-boot%E9%9B%86%E6%88%90%E6%96%B9%E5%BC%8F%E6%8E%A8%E8%8D%90)

还是不行，我这边是多模块应用，一个 web 包，一个 common 包。
web 启动时需要初始化 common 的 bean，现在的问题是无论是 @EnableApolloConfig 还是 apollo.bootstrap.enabled=true 的方式都不能成功初始化 common 包的 bean，从而导致 web 启动失败（还未把配置迁移到 Apollo，配置都还在本地）
正常来说不是应该配置中心没读到，然后从本地读取吗？
