### ISSUE TITLE
配置的值能否引用已有namespace下的配置值？

### ISSUE THREAD

**Issue by yzyhc** [ctripcorp/apollo#981]
如题，如果我已经有一个公共的namespace（ns1），下面有个配置键值
host.ip=1.2.3.4
那么我在另一个新namespace（ns2）里面新加配置的时候能否引用ns1下host.ip这个配置，类似
url=http://${ns1.host.ip}/xxx

在客户端获取ns2的url时，能取到http://1.2.3.4/xxx

**Comment by nobodyiam** [comment]
如果是在Spring中集成Apollo配置的话是可以的，因为Spring已经把级联配置这块实现了。

如果使用API方式使用Apollo配置的话，目前还不支持。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by zhuxt2015** [comment]
请问这个有计划支持API方式吗?

**Comment by nobodyiam** [comment]
@zhuxt2015 暂时没有，你的使用场景是怎么样的？
