### ISSUE TITLE
apollo是否能保证在方法执行过程中的data consistensy

### ISSUE THREAD

**Issue by charlietianx** [ctripcorp/apollo#983]
之前采用spring-cloud的@RefreshScope,发现如果在方法执行过程中，配置发生改变，data consistency无法保证；Apollo是否能解决这个问题？
如：
 方法A{
   doSomething……   //1
   （配置改变，配置bean刷新）
   doSomething……   //2
}
1和2用的配置不一样，造成数据不一致。

**Comment by lepdou** [comment]
这个问题，目前Apollo也是没法保证的。因为客户端配置更新是业务下层的逻辑，更新的时候无法感知上层业务如何正在使用当前配置？如果要实现的，可能得存很多状态信息，就会很麻烦。

这个问题，如果要保证的话，只能在方法执行前，先把配置值放在一个变量里，相当于临时缓存。这样就能保证同一个方法执行的时候，配置值是一致的。

我的理解大部分配置是没有这种要求的，只有少部分配置有这个要求，可以在业务代码里自己保证。

**Comment by charlietianx** [comment]
@lepdou 谢谢回答；我仔细想了想好像的确是这样，如何使用这个配置是业务层面自己的问题。
