### ISSUE TITLE
正在对接apollo，之前看到过一篇开源的配置中心比较的文档

### ISSUE THREAD

**Issue by lijasonvip** [ctripcorp/apollo#984]
目前正在对接apollo，之前看到过一篇开源的配置中心比较的文档，现在没找到那篇文档了，想问一下那篇比较的文章可以摘部分内容宣传的时候用吗？ 谢谢！

**Comment by lepdou** [comment]
可以参考一下FAQ第九条和第十条。[FAQ](https://github.com/ctripcorp/apollo/wiki/FAQ)
内容是可以摘取的，标注来源就可以了。
