### ISSUE TITLE
fat，uat几个环境不够用有什么方法处理吗？

### ISSUE THREAD

**Issue by onethin** [ctripcorp/apollo#985]
实际环境中需要测试环境，验证环境，压力测试环境，仿真环境，生产环境，怎么标识

**Comment by nobodyiam** [comment]
[Env.java](https://github.com/ctripcorp/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/apollo/core/enums/Env.java)中有LOCAL, DEV, FWS, FAT, UAT, LPT, PRO, TOOLS等8种内置环境，应该够用了。

* LOCAL - Local Development environment
* DEV - Development environment
* FWS - Feature Web Service Test environment
* FAT - Feature Acceptance Test environment
* LPT - Load and Performance Test environment
* UAT - User Acceptance Test environment
* PRO - Production environment

如果还希望自定义的话，就需要修改代码了

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by DuLerWeil** [comment]
有些公司会自己定义各种环境，希望环境名称可以自定义而不是这些固定的枚举值。

**Comment by nobodyiam** [comment]
恩，后续会考虑在portal中让用户通过界面来自定义环境
