### ISSUE TITLE
能否针对环境做权限控制?

### ISSUE THREAD

**Issue by wenzhen123** [ctripcorp/apollo#987]
请问apollo能否根据环境做权限控制,让用户不能随意查看各个项目的配置,特别是PRO环境配置?

**Comment by nobodyiam** [comment]
这个一直是在待办事项中的，初步考虑是增加配置来指明哪些env只允许项目成员查看，然后在代码中做响应权限控制

**Comment by nobodyiam** [comment]
#1531 支持设置某个环境的配置只能被项目成员看到，非项目成员无法查看，可以看一下

**Comment by nobodyiam** [comment]
1.1.0版本已经发布，包含了查看权限控制功能，更多信息可以参考： https://github.com/ctripcorp/apollo/releases/tag/v1.1.0

**Comment by cuiyiping** [comment]
我看到已经有对项目的发布权和修改权进行控制,能否对查看权也进行控制?比如生产环境的配置是只有管理员权限查看,测试,开发环境是开放给一般开发人员的

**Comment by nobodyiam** [comment]
@cuiyiping 参考下[配置查看权限](https://github.com/ctripcorp/apollo/wiki/Apollo%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#61-%E9%85%8D%E7%BD%AE%E6%9F%A5%E7%9C%8B%E6%9D%83%E9%99%90)
