### ISSUE TITLE
.Net客户端使用说明链接错误

### ISSUE THREAD

**Issue by shixy163** [ctripcorp/apollo#988]
.Net客户端链接指向的地址是首页了吗？
是不提供.Net客户端了吗？

**Comment by nobodyiam** [comment]
貌似由于未知原因，.Net客户端使用文档页面丢失了。。。我们看下怎么回事

**Comment by nobodyiam** [comment]
应该是github把这个文件弄丢了，我们先咨询下他们是否可以帮忙恢复，如果不行的话，我们再从google快照中恢复一下。。

**Comment by shixy163** [comment]
好吧，谢谢尽快恢复

**Comment by nobodyiam** [comment]
已经恢复了，[.Net客户端使用指南
](https://github.com/ctripcorp/apollo/wiki/.Net%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)
