### ISSUE TITLE
docker compose 启动后拉取数据异常

### ISSUE THREAD

**Issue by kawhii** [ctripcorp/apollo#991]
* 启动成功
* 外部可访问admin

配置信息：
`-Denv=dev`
`-Ddev_meta=http://docker实例ip:对外映射端口`

异常情况描述：
**拉取配置时采用了docker容器内部ip，导致超时无法拉取配置，请问如何解决？**

**Comment by nobodyiam** [comment]
config service默认会把docker自己的IP和端口注册上去，可以参考[分布式部署指南-网络策略](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#14%E7%BD%91%E7%BB%9C%E7%AD%96%E7%95%A5)

**Comment by kawhii** [comment]
能否直接修改docker-compose来调整这个策略？否则失去快速启动的意义了

**Comment by nobodyiam** [comment]
quick start主要是设计用来演示功能的，所以内置了一个简单的demo程序，那个是可以运行的。

我们后面看看是否可以配置一下。

**Comment by kawhii** [comment]
感谢！
