### ISSUE TITLE
配置能读出来并且缓存，但是似乎没有成功加载

### ISSUE THREAD

**Issue by zhfish** [ctripcorp/apollo#992]
```
20:47:32.298 [main] INFO  c.c.f.f.i.p.DefaultApplicationProvider - App ID is set to fdsgdsrfgsx by app.id property from /META-INF/app.properties
20:47:32.308 [main] INFO  c.c.f.f.i.p.DefaultServerProvider - Loading /opt/settings/server.properties
20:47:32.309 [main] INFO  c.c.f.f.i.p.DefaultServerProvider - Environment is set to [DEV] by property 'env' in server.properties.
```
/opt/data/fdsgdsrfgsx/config-cache 里也有内容

但随后报错
```
Cannot determine embedded database driver class for database type NONE
```
应该是datasource相关配置没有加载

配置相关：
config,admin, portal都是running
client是deploy到私库，并且pom成功引入
src里的yml
```
apollo:
  bootstrap:
    enabled: true
    # will inject 'application' and 'TEST1.apollo' namespaces in bootstrap phase
    namespaces: application
```
另外就是app.properties
```
app.id=app.id=fdsgdsrfgsx
```

是我少配置了什么东西？

**Comment by slankka** [comment]
Cannot determine embedded database driver class for database type NONE
从这句话看出来应该是Spring检测到你因为引入了Mybatis之类的，他需要配置了数据源。
然后缺少了jdbc的依赖？或者你spring.datasource.driverClassName没有配置？

**Comment by nobodyiam** [comment]
apollo.bootstrap.enabled需要最新的master代码才能支持，你确认一下是否是最新的，如果是最新的话，可以到 com.ctrip.framework.apollo.spring.boot.ApolloApplicationContextInitializer#initialize 方法里面打个断点，看看注入进去的配置是否包含了spring.datasource相关的配置。

**Comment by zhfish** [comment]
多谢，仔细检查，是我找了个yml转properties的工具，然而这个工具转换出来的结果是错误的，很多节点对不上-_-#

**Comment by nieguhua** [comment]
我之前也想找这个工具，没找到，自己手动转换的

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
