### ISSUE TITLE
同一个namespace在不同的环境中的配置

### ISSUE THREAD

**Issue by lic987** [ctripcorp/apollo#993]
您好。
想要用api的方式使用namespace，一个项目就打一个包并且部署在不同的服务器上面。我知道不同集群的namespace配置项可以不同；但现在同一集群的不同服务器的配置也有所差异。比如网络带宽等等参数。如何能够解决这个问题呢？或者您有什么好的建议呢？ 
谢谢

**Comment by nobodyiam** [comment]
可以用逻辑集群，-Dapollo.cluster=xxx

**Comment by lic987** [comment]
不好意思 没太理解  能不能给个例子 。 那个-Dapollo是什么意思。。。。。

**Comment by lic987** [comment]
您的意思是把原本的集群拆分成两个集群 参数相同的在一个集群，不同的在另外一个集群么？
原本有aaa集群放3台机器 现在改成aaa集群2台 bbb集群1台的意思么

**Comment by nobodyiam** [comment]
是的，使用逻辑集群的意思，具体可以看下[cluster的说明](https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#124-%E5%8F%AF%E9%80%89%E8%AE%BE%E7%BD%AE)

**Comment by lic987** [comment]
好的 谢谢您
