### ISSUE TITLE
apollo用户登陆验证

### ISSUE THREAD

**Issue by MrLiuhhh** [ctripcorp/apollo#994]
请问下，我想用我们自己系统的一套用户登陆机制来替换apollo的登陆，从哪儿入手比较好呢？

**Comment by nobodyiam** [comment]
参考[Portal 实现用户登录功能](https://github.com/ctripcorp/apollo/wiki/Portal-%E5%AE%9E%E7%8E%B0%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95%E5%8A%9F%E8%83%BD)

**Comment by MrLiuhhh** [comment]
十分感谢。还有一个问题，我想了解下，apollo的客户端和configservice之间的长连接是个什么样机制，5分钟拉取一次配置后，需要应用做相应的处理呢还是直接就会将变化的配置直接注入进去呢？还是说这种长连接的方式也需要加apolloconfigchangelistener呢？因为在我没有使用监听器的时候，发现并不能看到配置的改变。

**Comment by nobodyiam** [comment]
API方式使用的话，每次getProperty返回的都是最新的值

Spring注入方式使用的话，在0.10.0版本开始支持实时更新，之前的版本需要使用`@RefreshScope`，具体看一下Java客户端使用文档吧。

**Comment by MrLiuhhh** [comment]
恩恩 谢谢。关于定时5分钟拉取配置的具体实现是在哪一块呢？我用demo验证时，发现并未更新，麻烦您帮忙看下~或者说需要加什么注解吗》

**Comment by nobodyiam** [comment]
可以看下 [https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1#%E4%B8%89%E5%AE%A2%E6%88%B7%E7%AB%AF%E8%AE%BE%E8%AE%A1](客户端设计)，如果没有更新，应该是哪里出错了，看一下客户端的日志即可，可以打开DEBUG Log level

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
