### ISSUE TITLE
是否支持除了MySQL之外的数据库? 

### ISSUE THREAD

**Issue by oaksharks** [ctripcorp/apollo#996]
正如教程中提到的那样由于使用了带有默认值的 timestamp字段 apollo只能使用指定版本的MySQL ,
目前是否有途径/计划支持Postgres?

**Comment by nobodyiam** [comment]
目前由于精力有限，只支持mysql，之前[vanpersl](https://github.com/vanpersl)实现了支持oracle的，可以参考一下[Oracle适配代码](https://github.com/ctripcorp/apollo/compare/v0.8.0...vanpersl:db-oracle)

**Comment by oaksharks** [comment]
感谢回复, 看起来适配的关键步骤应该是:
1. 改掉代码中与数据具体产品强耦合的代码
2. 修改建表语句适配指定数据库

请问关于 MySQL 的 DEFAULT 值和 ON UPDATE 事件 有没有改造的建议?

**Comment by lepdou** [comment]
Mysql 的 DEFAULT值和 ON UPDATE 事件，我的理解在DAO层代码做增加、更新操作的时候，设置所有字段的值就可以了。
在Apollo里应该没有用到DEFAULT和ON UPDATE 特性吧？或者你哪里有看到的，可以贴出来一下。

**Comment by oaksharks** [comment]
可能我没描述清楚，在`apollo/scripts/sql/apolloconfigdb.sql`中: 
```sql
CREATE TABLE `App` (
  `Id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `AppId` varchar(500) NOT NULL DEFAULT 'default' COMMENT 'AppID',
  ...
  ...
  `DataChange_CreatedTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `DataChange_LastTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  PRIMARY KEY (`Id`),
  KEY `AppId` (`AppId`(191)),
  KEY `DataChange_LastTime` (`DataChange_LastTime`),
  KEY `IX_Name` (`Name`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应用表';

```

字段 `DataChange_LastTime` 的默认值是 `CURRENT_TIMESTAMP` ，`ON UPDATE` 事件触发时也会修改为 `CURRENT_TIMESTAMP` , 这样的高级特性可能在别的数据库中没有。有没有合适的替代方案？

**Comment by nobodyiam** [comment]
@oaksharks 可以试一下在其它数据库使用时去除这些高级特性看看，代码中应该传了时间信息到数据库的

**Comment by oaksharks** [comment]
如此甚好, 那样的话只要修改一下建表语句就不用局限于MySQL 5.7版本了。

**Comment by oaksharks** [comment]
已经成功适配到Postgres: [apollo base on postgres](https://github.com/oaksharks/apollo)

**Comment by nobodyiam** [comment]
@oaksharks 适配的是哪个pg版本？

**Comment by oaksharks** [comment]
@nobodyiam  是 ` PostgreSQL 9.3.20 on x86_64-unknown-linux-gnu`  ,  创建项目,namespace, 配置项，发布，客户端调用以及回调事件 等基本功能已经测试过。 相近的版本应该也可以使用。

**Comment by nobodyiam** [comment]
@oaksharks 多谢！

已经在[分布式部署指南](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#12-mysql)中增加相应提示信息。

![image](https://user-images.githubusercontent.com/837658/37662822-e6a142aa-2c92-11e8-97b4-a653b6c2e387.png)
