### ISSUE TITLE
数据库的连接地址或者端口也可以热发布吗？

### ISSUE THREAD

**Issue by liyufu** [ctripcorp/apollo#997]
如题：
数据库的连接地址或者端口也可以热发布吗？
如果可以，是怎么做到的？会不会影响运行中的connector

**Comment by nobodyiam** [comment]
一般我们的做法是实现动态数据源，可以参考下 #680 和 #663

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by nobodyiam** [comment]
我们增加了一个代码示例演示动态切换数据源，可以参考一下：https://github.com/ctripcorp/apollo-use-cases/tree/master/dynamic-datasource
