### ISSUE TITLE
apollo分布式部署问题

### ISSUE THREAD

**Issue by lic987** [ctripcorp/apollo#998]
您好，我阅读了分布式部署方案，想和图里一样进行分布式部署，但是不同的环境dev,pro如何能够让admin service和config service知道自己为哪个环境服务呢？比如我的pro环境，是在build.sh里面打包的时候 把其他的环境注释掉，只保留pro_meta这样子；dev环境也是一样；最后配置protal的时候再把pro_meta 和dev_meta全部开启这样打包么？

**Comment by lic987** [comment]
还有一个问题是我dev环境和pro环境的java-client是否可以只使用一个jar文件，还是说因为我在build.sh里面的配置不同，所以我的java工程在不同环境跑的时候要引入不同的包呢

**Comment by lic987** [comment]
谢谢

**Comment by nobodyiam** [comment]
由于ApolloConfigDB在每个环境都有部署，所以对不同的环境config-service和admin-service需要使用不同的数据库参数打不同的包，portal和client只需要打一次包即可

所以，admin service和config service它们不需要知道为哪个环境服务，只要让他们连着正确的数据库即可。

portal和client只需要打一次包，因为在apollo-core.jar的apollo-env.properties中会有所有环境的meta server信息，它们会根据自己所处的环境调用不同的meta server地址的。

**Comment by lic987** [comment]
谢谢，其实是admin service和config service连接数据库 ，我的代码client不需要知道数据库链接 只需要知道meta就可以了 所以即使我的dev环境和pro环境网络不通，我只需要调整数据库的链接 下面的meta信息不用变，然后在client的时候指定他的env ，client就不会受到影响了；但是网络不通的话我就要有两个portal ，protal也打两个包对吧

**Comment by lepdou** [comment]
Portal因为需要管理多环境的配置（为了用户方便使用），所以Poral会调用其所管理的所有环境的Admin Server。假设你的Portal是部署在Pro环境，并且Pro环境和Dev环境的网络隔离，那只能每个环境部署一套Portal了。Portal部署多套，对于元数据管理上比较麻烦（有些元数据需要多个环境间同步）。所以最好的方式是能打通两个环境的网络。

**Comment by lic987** [comment]
好的 谢谢您 嘿嘿
